import { District } from '../types';

export default <District>{
  id: 98,
  name: 'ABIM',
  counties: [
    {
      id: 242,
      name: 'LABWOR COUNTY',
      sub_counties: [
        {
          id: 1546,
          name: 'ABIM',
          parishes: [
            {
              id: 9127,
              name: 'ABONGEPACH',
              villages: [
                { id: 57217, name: 'ABONGEPACH' },
                { id: 58161, name: 'AMITA PRISON' },
                { id: 58171, name: 'AMONICEK' },
                { id: 58473, name: 'AREMBWOLA  NORTH' },
                { id: 58474, name: 'AREMBWOLA WEST' },
                { id: 61332, name: 'GANG-LENGO' },
                { id: 68322, name: 'OBANGANGEO' },
              ],
            },
            {
              id: 9150,
              name: 'ADWAL',
              villages: [
                { id: 57495, name: 'ADWAL CENTRAL' },
                { id: 57496, name: 'ADWAL EAST' },
                { id: 57497, name: 'ADWAL NORTH' },
                { id: 57498, name: 'ADWAL WEST' },
                { id: 58318, name: 'ANUKUNAM' },
                { id: 58727, name: 'AWEIRENG' },
                { id: 61376, name: 'GILIGILI' },
                { id: 62480, name: 'KAMURONO' },
                { id: 69009, name: 'OMUNGA' },
              ],
            },
            {
              id: 7279,
              name: 'ANINATA',
              villages: [
                { id: 57407, name: 'ADAGKOLO' },
                { id: 45554, name: 'AJUKUNA' },
                { id: 45555, name: 'ANINATA CENTRAL' },
                { id: 45557, name: 'ANINATA EAST' },
                { id: 45556, name: 'ANINATA NORTH' },
                { id: 45558, name: 'ANINATA SOUTH' },
                { id: 58307, name: 'ANINATA WEST' },
              ],
            },
            {
              id: 7278,
              name: 'AREMBWOLA',
              villages: [
                { id: 45552, name: 'ALUGA' },
                { id: 45553, name: 'AMITA PRISON' },
                { id: 45546, name: 'AMONICEK' },
                { id: 45548, name: 'AREMBWOLA  NORTH' },
                { id: 45549, name: 'AREMBWOLA  SOUTH' },
                { id: 45547, name: 'AREMBWOLA CENTRAL' },
                { id: 45550, name: 'AREMBWOLA EAST' },
                { id: 45551, name: 'OYOMPOLO' },
              ],
            },
            {
              id: 7276,
              name: 'ATUNGA',
              villages: [
                { id: 45527, name: 'APELKERE' },
                { id: 45528, name: 'ATUGO' },
                { id: 45529, name: 'KOPO' },
                { id: 45530, name: 'ORYEOTYENE  EAST' },
                { id: 45531, name: 'ORYEOTYENE NORTH' },
                { id: 45532, name: 'ORYEOTYENE SOUTH' },
                { id: 45533, name: 'OTALABAR  EAST' },
                { id: 45534, name: 'OTALABAR CENTRAL' },
                { id: 45536, name: 'OTALABAR NEWLINE' },
                { id: 45537, name: 'OTALABAR TRADING CENTRE' },
                { id: 45535, name: 'OTALABAR WEST' },
              ],
            },
            {
              id: 7277,
              name: 'KANU',
              villages: [
                { id: 45538, name: 'ANGICA' },
                { id: 45539, name: 'APELKORI' },
                { id: 45545, name: 'AROO' },
                { id: 45540, name: 'AROO WEST' },
                { id: 45542, name: 'GEREGERE EAST' },
                { id: 45543, name: 'GEREGERE NORTH' },
                { id: 45544, name: 'GEREGERE SOUTH' },
                { id: 68357, name: 'OBOKOLOTH' },
                { id: 45541, name: 'OBWORO' },
              ],
            },
            {
              id: 10161,
              name: 'OIMA',
              villages: [
                { id: 57683, name: 'AJWOK-ODINYO' },
                { id: 58386, name: 'APELKORI' },
                { id: 61360, name: 'GEREGERE NORTH' },
                { id: 61361, name: 'GEREGERE SOUTH' },
                { id: 62009, name: 'KACHUNGO' },
                { id: 68396, name: 'OBWORO' },
                { id: 69823, name: 'RIAMIRIAM' },
              ],
            },
          ],
        },
        {
          id: 1551,
          name: 'ABIM TOWN COUNCIL',
          parishes: [
            {
              id: 9159,
              name: 'AGWATA WARD',
              villages: [
                { id: 57169, name: 'ABIM HOSPITAL' },
                { id: 58856, name: 'AYWEE NORTH' },
                { id: 61263, name: 'ENTEBBE' },
                { id: 71217, name: 'YENGLEMI WEST' },
              ],
            },
            {
              id: 9206,
              name: 'ANGWEE WARD',
              villages: [
                { id: 58302, name: 'ANGWEE NORTH' },
                { id: 58303, name: 'ANGWEE SOUTH' },
                { id: 71215, name: 'YENGLEMI EAST' },
                { id: 71216, name: 'YENGLEMI NORTH' },
              ],
            },
            {
              id: 7301,
              name: 'KALAKALA WARD',
              villages: [
                { id: 45756, name: 'AKADO CENTRAL' },
                { id: 45750, name: 'AKADO EAST' },
                { id: 45751, name: 'AKADO SOUTH' },
                { id: 45752, name: 'AKADO WEST' },
                { id: 45753, name: 'AYWEE EAST' },
                { id: 45757, name: 'AYWEE MODEL VILLAGE' },
                { id: 45754, name: 'AYWEE SOUTH' },
                { id: 45755, name: 'AYWEE WEST' },
                { id: 45758, name: 'RIAMIRIAM' },
              ],
            },
            {
              id: 7299,
              name: 'KIRU WARD',
              villages: [
                { id: 45729, name: 'ALULA' },
                { id: 45730, name: 'MISSION' },
                { id: 45728, name: 'NYIKINYIKI' },
                { id: 45731, name: 'OBANGANGEO EAST' },
                { id: 45725, name: 'OBANGANGEO NORTH' },
                { id: 45726, name: 'OBANGANGEO SOUTH' },
                { id: 45727, name: 'OBANGANGEO WEST' },
                { id: 45724, name: 'OYARO NORTH' },
              ],
            },
            {
              id: 10208,
              name: 'ORINGOWELO WARD',
              villages: [
                { id: 58640, name: 'ATING NORTH' },
                { id: 58641, name: 'ATING SOUTH' },
                { id: 61079, name: 'DAGARONYA' },
                { id: 69199, name: 'ORINGOWELO' },
                { id: 71114, name: 'WICERE' },
              ],
            },
            {
              id: 7302,
              name: 'OYARO WARD',
              villages: [
                { id: 45759, name: 'ABONGEDERO' },
                { id: 45762, name: 'ABUK' },
                { id: 45765, name: 'ACHARAETHE' },
                { id: 45761, name: 'ACHARAETHE EAST' },
                { id: 45760, name: 'AROO' },
                { id: 45768, name: 'OLIABONG' },
                { id: 45769, name: 'OMORU' },
                { id: 45770, name: 'ORUM' },
                { id: 45763, name: 'OYARO CENTRAL' },
                { id: 45764, name: 'OYARO EAST' },
                { id: 45766, name: 'OYARO SOUTH' },
                { id: 45771, name: 'OYARO TRIANGLE' },
                { id: 45767, name: 'OYARO WEST' },
              ],
            },
            {
              id: 7300,
              name: 'WIAWER WARD',
              villages: [
                { id: 45732, name: 'ABIM CENTRAL' },
                { id: 45740, name: 'ABIM EAST' },
                { id: 45734, name: 'ABIM HOSPITAL' },
                { id: 45741, name: 'ABIM NORTH' },
                { id: 45742, name: 'ABIM WEST' },
                { id: 45735, name: 'ANGWEE NORTH' },
                { id: 45743, name: 'ANGWEE SOUTH' },
                { id: 45738, name: 'ATING NORTH' },
                { id: 45739, name: 'ATING SOUTH' },
                { id: 45733, name: 'ATWILO' },
                { id: 45744, name: 'AYWEE NORTH' },
                { id: 45745, name: 'DAGARONYA' },
                { id: 45746, name: 'ENTEBBE' },
                { id: 45747, name: 'ORINGOWELO' },
                { id: 45748, name: 'WICERE' },
                { id: 45737, name: 'YENGLEMI EAST' },
                { id: 45749, name: 'YENGLEMI NORTH' },
                { id: 45736, name: 'YENGLEMI WEST' },
              ],
            },
          ],
        },
        {
          id: 1547,
          name: 'ALEREK',
          parishes: [
            {
              id: 9648,
              name: 'KATHIMONGOR',
              villages: [
                { id: 57319, name: 'ACANPENINO' },
                { id: 62119, name: 'KAGURUI' },
                { id: 63079, name: 'KATHIMONGOR' },
                { id: 63259, name: 'KECOKELA' },
                { id: 64336, name: 'KOTIDO' },
                { id: 69825, name: 'RIBOCING' },
                { id: 70900, name: 'TYENOPOBO NORTH' },
                { id: 70901, name: 'TYENOPOBO SOUTH' },
              ],
            },
            {
              id: 7283,
              name: 'KULODWONG',
              villages: [
                { id: 45576, name: 'ACANPENINO' },
                { id: 45585, name: 'ARINGOBOM EAST' },
                { id: 45586, name: 'ARINGOBOM WEST' },
                { id: 45587, name: 'KAKUTHA' },
                { id: 45577, name: 'KATHIMONGOR' },
                { id: 45578, name: 'KECOKELA' },
                { id: 45579, name: 'KOTIDO' },
                { id: 45588, name: 'KULODWONG' },
                { id: 45580, name: 'RIBOCING' },
                { id: 45581, name: 'TYENOPOBO EAST' },
                { id: 45582, name: 'TYENOPOBO NORTH' },
                { id: 45583, name: 'TYENOPOBO SOUTH' },
                { id: 45584, name: 'TYENOPOBO WEST' },
              ],
            },
            {
              id: 7280,
              name: 'LOYOROIT',
              villages: [
                { id: 45559, name: 'ALIMOCAN' },
                { id: 58009, name: 'ALIMOCAN SOUTH' },
                { id: 58139, name: 'AMINA' },
                { id: 61386, name: 'GO-DOWN' },
                { id: 68719, name: 'OKULOWIE' },
                { id: 45560, name: 'OLEM CENTRAL' },
                { id: 45561, name: 'OLEM EAST' },
                { id: 45562, name: 'OLEM NORTH' },
                { id: 68786, name: 'OLEM SOUTH WEST' },
                { id: 45563, name: 'OLEM WEST' },
                { id: 69195, name: 'ORINGI' },
              ],
            },
            {
              id: 10146,
              name: 'OCOM',
              villages: [
                { id: 57464, name: 'ADONGPII' },
                { id: 58550, name: 'ARUKWENY' },
                { id: 61087, name: 'DAM-KE-ELIA' },
                { id: 62197, name: 'KAKET' },
                { id: 64372, name: 'KULODWONG EAST' },
                { id: 64373, name: 'KULODWONG WEST' },
                { id: 68425, name: 'OCOM CENTRAL' },
                { id: 68564, name: 'OGOLOTH' },
              ],
            },
            {
              id: 10175,
              name: 'OLEM',
              villages: [
                { id: 57396, name: 'ADADI' },
                { id: 57461, name: 'ADOLOLONG' },
                { id: 58044, name: 'ALOK-OTHERO' },
                { id: 58229, name: 'ANAM-ONGOK' },
                { id: 58629, name: 'ATHIRIR' },
                { id: 61435, name: 'GUL-KANA' },
                { id: 67054, name: 'NAKIBULA' },
                { id: 68749, name: 'OKWION' },
                { id: 68782, name: 'OLEM CENTRAL' },
                { id: 68783, name: 'OLEM NORTH' },
                { id: 68784, name: 'OLEM NORTH EAST' },
                { id: 68785, name: 'OLEM NORTH WEST' },
                { id: 69099, name: 'OOIAPIE' },
                { id: 70894, name: 'TYEN-CONGO' },
                { id: 70895, name: 'TYEN-CUMU' },
              ],
            },
            {
              id: 7282,
              name: 'OTUMPILI',
              villages: [
                { id: 45569, name: 'ARENGEPUA' },
                { id: 45570, name: 'KAWANG' },
                { id: 45571, name: 'LOYOROIT CENTRAL' },
                { id: 45572, name: 'OTUMPILI CENTRAL' },
                { id: 45573, name: 'OTUMPILI NORTH' },
                { id: 45574, name: 'OTUMPILI SOUTH' },
                { id: 45575, name: 'OTUMPILI SOUTH WEST' },
              ],
            },
            {
              id: 7281,
              name: 'WILELA',
              villages: [
                { id: 45567, name: 'KANYALAKA NORTH' },
                { id: 45568, name: 'KANYALAKA SOUTH' },
                { id: 45564, name: 'WILELA CENTRAL I' },
                { id: 45565, name: 'WILELA SOUTH' },
                { id: 45566, name: 'YWEE-WII' },
              ],
            },
          ],
        },
        {
          id: 1953,
          name: 'ATUNGA',
          parishes: [
            {
              id: 9213,
              name: 'APOK',
              villages: [
                { id: 58417, name: 'APOK' },
                { id: 61290, name: 'ETHIRIR' },
                { id: 61490, name: 'GWILNGEI' },
              ],
            },
            {
              id: 9235,
              name: 'ATUNGA',
              villages: [
                { id: 57558, name: 'AGONGA' },
                { id: 62570, name: 'KANYAKANYA' },
                { id: 69111, name: 'OPEDUR' },
                { id: 69278, name: 'OTALABAR  EAST' },
                { id: 69279, name: 'OTALABAR CENTRAL' },
                { id: 69280, name: 'OTALABAR NEWLINE' },
              ],
            },
            {
              id: 10210,
              name: 'ORYEOTYENE',
              villages: [
                { id: 58354, name: 'AOYAPYEE' },
                { id: 58385, name: 'APELKERE' },
                { id: 64301, name: 'KOPO' },
                { id: 69249, name: 'ORYEOTYENE  EAST' },
                { id: 69250, name: 'ORYEOTYENE CENTRAL' },
                { id: 69251, name: 'ORYEOTYENE NORTH' },
                { id: 69252, name: 'ORYEOTYENE SOUTH' },
              ],
            },
            {
              id: 10212,
              name: 'OTALABAR',
              villages: [
                { id: 57167, name: 'ABILONYERO' },
                { id: 58664, name: 'ATUGO' },
                { id: 65273, name: 'LOCKEN' },
                { id: 68375, name: 'OBUL' },
                { id: 68408, name: 'OCEKABUK' },
                { id: 69281, name: 'OTALABAR TRADING CENTRE' },
                { id: 69282, name: 'OTALABAR WEST' },
              ],
            },
          ],
        },
        {
          id: 1552,
          name: 'AWACH',
          parishes: [
            {
              id: 7303,
              name: 'AWACH',
              villages: [
                { id: 45772, name: 'ADAG KOLO' },
                { id: 45779, name: 'ADAGKOLO NORTH' },
                { id: 45773, name: 'OBANGANGEO' },
                { id: 45774, name: 'OBOKOLOTH' },
                { id: 45775, name: 'OBOKOLOTH CENTRAL' },
                { id: 45778, name: 'OBOKOLOTH EAST' },
                { id: 45776, name: 'ONANGO MOTHO' },
                { id: 45777, name: 'PEM KWORO' },
              ],
            },
            {
              id: 7305,
              name: 'BARLYECH',
              villages: [
                { id: 45796, name: 'ADIOCAI' },
                { id: 45799, name: 'AROO' },
                { id: 45802, name: 'BARLYECH' },
                { id: 45800, name: 'BARLYECH CENTRAL' },
                { id: 45801, name: 'BARLYECH WEST' },
                { id: 45803, name: 'OPOKOLOBO' },
                { id: 45797, name: 'OTHEN' },
                { id: 45798, name: 'PAMO' },
              ],
            },
            {
              id: 7306,
              name: 'GOTAPWOU',
              villages: [
                { id: 45811, name: 'ATHEDER CENTRAL' },
                { id: 45805, name: 'ATHEDER EAST' },
                { id: 45806, name: 'ATHEDER NORTH' },
                { id: 45804, name: 'ATHEDER SOUTH' },
                { id: 45807, name: 'ATHEDER WEST' },
                { id: 45808, name: 'GOTAPWOU' },
                { id: 45812, name: 'GOTAPWOU CENTRAL' },
                { id: 45809, name: 'MAMKAI' },
                { id: 45810, name: 'NATETE' },
                { id: 45813, name: 'OMOO CENTRAL' },
                { id: 45814, name: 'OMOO EAST' },
                { id: 45815, name: 'OMOO SOUTH' },
                { id: 45816, name: 'OMOO WEST' },
              ],
            },
            {
              id: 7304,
              name: 'OPOROTH',
              villages: [
                { id: 45790, name: 'ACARAWANG - SOUTH' },
                { id: 45780, name: 'ACARAWANG CENTRAL' },
                { id: 45781, name: 'ACARAWANG EAST' },
                { id: 45782, name: 'ACARAWANG WEST' },
                { id: 45783, name: 'AGWENG' },
                { id: 45789, name: 'AMONICEK' },
                { id: 45784, name: 'ANYALIMA' },
                { id: 45791, name: 'ANYALIMA WEST' },
                { id: 45785, name: 'BAR OTUKE' },
                { id: 45793, name: 'BAR-OTUKE CENTRAL' },
                { id: 45794, name: 'BAR-OTUKE WEST' },
                { id: 45792, name: 'BARDAGO' },
                { id: 45786, name: 'KOLOLO EAST' },
                { id: 45787, name: 'KOLOLO NEW  LINE' },
                { id: 45795, name: 'PAMO' },
                { id: 45788, name: 'WIPOLO' },
              ],
            },
          ],
        },
        {
          id: 1980,
          name: 'CAMKOK',
          parishes: [
            {
              id: 9204,
              name: 'ANGOROM',
              villages: [
                { id: 57602, name: 'AGWENG' },
                { id: 58630, name: 'ATHOME' },
                { id: 63080, name: 'KATHIPUTH' },
                { id: 66267, name: 'MILIMIL' },
                { id: 66336, name: 'MOGOTH' },
                { id: 68713, name: 'OKUDA' },
              ],
            },
            {
              id: 9799,
              name: 'KOTHIDANY',
              villages: [
                { id: 62783, name: 'KARAPATH' },
                { id: 63587, name: 'KIIRO' },
                { id: 64330, name: 'KOTHIDANY CENTRAL' },
                { id: 64331, name: 'KOTHIDANY EAST' },
                { id: 64332, name: 'KOTHIDANY SOUTH' },
                { id: 64333, name: 'KOTHIDANY WEST' },
                { id: 68703, name: 'OKOROBIO' },
              ],
            },
            {
              id: 10166,
              name: 'OKILILING',
              villages: [
                { id: 58381, name: 'APEIRE' },
                { id: 58898, name: 'BANDAKA' },
                { id: 60834, name: 'CAMKOK EAST' },
                { id: 60835, name: 'CAMKOK WEST' },
                { id: 68952, name: 'OMETHURO' },
                { id: 70537, name: 'SOWETO' },
                { id: 70896, name: 'TYEN-OPEDO' },
              ],
            },
          ],
        },
        {
          id: 2033,
          name: 'KIRU TOWN COUNCIL',
          parishes: [
            {
              id: 9567,
              name: 'KALAKALA WARD',
              villages: [
                { id: 57692, name: 'AKADO CENTRAL' },
                { id: 57693, name: 'AKADO EAST' },
                { id: 57695, name: 'AKADO SOUTH' },
                { id: 57696, name: 'AKADO WEST' },
                { id: 58853, name: 'AYWEE EAST' },
                { id: 58855, name: 'AYWEE MODERN' },
                { id: 58857, name: 'AYWEE SOUTH' },
                { id: 58858, name: 'AYWEE WEST' },
                { id: 69822, name: 'RIAMIRIAM' },
              ],
            },
            {
              id: 9736,
              name: 'KIRU WARD',
              villages: [
                { id: 58064, name: 'ALULA' },
                { id: 68323, name: 'OBANGANGEO  NYIKINYIKI' },
                { id: 68324, name: 'OBANGANGEO EAST' },
                { id: 68325, name: 'OBANGANGEO MISSION' },
                { id: 68326, name: 'OBANGANGEO NORTH' },
                { id: 68327, name: 'OBANGANGEO SOUTH' },
                { id: 68328, name: 'OBANGANGEO WEST' },
                { id: 69391, name: 'OYARO NORTH' },
              ],
            },
            {
              id: 10222,
              name: 'OYARO WARD',
              villages: [
                { id: 57216, name: 'ABONGEDERO' },
                { id: 57248, name: 'ABUK' },
                { id: 57329, name: 'ACHARAETHE' },
                { id: 57330, name: 'ACHARAETHE EAST' },
                { id: 58543, name: 'AROO' },
                { id: 68806, name: 'OLIABONG' },
                { id: 68980, name: 'OMORU' },
                { id: 69224, name: 'ORUM' },
                { id: 69389, name: 'OYARO CENTRAL' },
                { id: 69390, name: 'OYARO EAST' },
                { id: 69392, name: 'OYARO SOUTH' },
                { id: 69393, name: 'OYARO TRIANGLE' },
                { id: 69394, name: 'OYARO WEST' },
              ],
            },
          ],
        },
        {
          id: 1548,
          name: 'LOTUKEI',
          parishes: [
            {
              id: 7285,
              name: 'ACHANGALI',
              villages: [
                { id: 45601, name: 'BUTIWINY' },
                { id: 45606, name: 'GULOPONO CENTRAL' },
                { id: 45607, name: 'GULOPONO EAST' },
                { id: 45608, name: 'GULOPONO NORTH' },
                { id: 45609, name: 'GULOPONO NORTH EAST' },
                { id: 45610, name: 'GULOPONO SOUTH' },
                { id: 45602, name: 'GULOPONO SOUTH EAST' },
                { id: 45603, name: 'LOTUKEI SEEDS' },
                { id: 45605, name: 'ORINGO ADINGA' },
                { id: 45604, name: 'TYEN OLAM' },
              ],
            },
            {
              id: 7286,
              name: 'ARIDAI',
              villages: [
                { id: 45611, name: 'AMORUTU-ICAN' },
                { id: 45613, name: 'AOJAPIRO' },
                { id: 45612, name: 'ARIDAI NORTH' },
                { id: 45619, name: 'ARIDAI SOUTH' },
                { id: 45620, name: 'BARKOLAM' },
                { id: 45614, name: 'LOTUKE CENTRAL' },
                { id: 45615, name: 'LOTUKE EAST' },
                { id: 45616, name: 'LOTUKE NORTH' },
                { id: 45617, name: 'LOTUKE SOUTH' },
                { id: 45618, name: 'LOTUKE WEST' },
                { id: 45621, name: 'LOTUKEI MIXED' },
                { id: 45622, name: 'LOTUKEI TRADING CENTRE' },
                { id: 45623, name: 'MORU HILL' },
                { id: 45624, name: 'YARAYARA' },
              ],
            },
            {
              id: 7287,
              name: 'GANGMING',
              villages: [
                { id: 45625, name: 'GANGMING CENTRAL' },
                { id: 45626, name: 'GANGMING EAST' },
                { id: 45634, name: 'GANGMING NEW LINE' },
                { id: 45627, name: 'GANGMING NORTH' },
                { id: 45628, name: 'GANGMING SOUTH' },
                { id: 45629, name: 'GANGMING SOUTH EAST' },
                { id: 45633, name: 'GANGMING SOUTH WEST' },
                { id: 45632, name: 'GANGMING WEST' },
                { id: 45630, name: 'LOKA WARD' },
                { id: 45631, name: 'WATHAKAU' },
              ],
            },
            {
              id: 7284,
              name: 'ORWAMUGE',
              villages: [
                { id: 45589, name: 'BARTANGA CENTRAL' },
                { id: 45590, name: 'BARTANGA EAST' },
                { id: 45591, name: 'BARTANGA NORTH' },
                { id: 45592, name: 'BARTANGA SOUTH' },
                { id: 45593, name: 'LOKETO EAST' },
                { id: 45599, name: 'LOKETO TRADING CENTRE' },
                { id: 45594, name: 'NADIKETH' },
                { id: 45595, name: 'NYIKINYIKI' },
                { id: 45596, name: 'TYEN OPOK EAST' },
                { id: 45597, name: 'TYEN OPOK NORTH' },
                { id: 45598, name: 'TYEN OPOK SOUTH' },
                { id: 45600, name: 'TYEN OPOK TRADING CENTRE' },
              ],
            },
          ],
        },
        {
          id: 1553,
          name: 'MAGAMAGA',
          parishes: [
            {
              id: 7308,
              name: 'GULOTWORO',
              villages: [
                { id: 45822, name: 'ABIL NINO NORTH' },
                { id: 45823, name: 'ABIL NINO SOUTH' },
                { id: 45824, name: 'ARWAKARA' },
                { id: 45825, name: 'ATHEDER NORTH' },
                { id: 45826, name: 'ATHEDER SOUTH' },
                { id: 45827, name: 'OLILIM' },
              ],
            },
            {
              id: 7307,
              name: 'KOYA',
              villages: [
                { id: 45817, name: 'BEDATA EAST' },
                { id: 45818, name: 'BEDATA SOUTH' },
                { id: 45819, name: 'BEDATA WEST' },
                { id: 45820, name: 'DIC PE EAST' },
                { id: 45821, name: 'DIC PE WEST' },
              ],
            },
            {
              id: 7309,
              name: 'MONYANGA',
              villages: [
                { id: 45828, name: 'KINGO' },
                { id: 45829, name: 'NYIKINYIKI' },
                { id: 45830, name: 'ODOKOMIT' },
                { id: 45831, name: 'WILELA CENTRAL II' },
                { id: 45832, name: 'WILELA NORTH' },
                { id: 71242, name: 'YWEE-WII' },
              ],
            },
          ],
        },
        {
          id: 1549,
          name: 'MORULEM',
          parishes: [
            {
              id: 7289,
              name: 'ADEA',
              villages: [
                { id: 45649, name: 'ABWOLOIT' },
                { id: 45646, name: 'ADEA CENTRAL' },
                { id: 45650, name: 'ADEA TRADING CENTRE' },
                { id: 45651, name: 'ADEA WEST' },
                { id: 45647, name: 'ALIR' },
                { id: 45648, name: 'AYEYE' },
              ],
            },
            {
              id: 7293,
              name: 'AKWANGAGWEL',
              villages: [
                { id: 45678, name: 'AJWACHI NEW LINE' },
                { id: 45679, name: 'AKWANGAGWEL CENTRAL' },
                { id: 45680, name: 'AKWANGAGWEL NORTH' },
                { id: 45681, name: 'AKWANGAGWEL SOUTH' },
              ],
            },
            {
              id: 7288,
              name: 'ANGOLEBWAL',
              villages: [
                { id: 45635, name: 'AGWENG EAST' },
                { id: 45636, name: 'AGWENG WEST' },
                { id: 45637, name: 'AYWEE' },
                { id: 45638, name: 'OBANGANGEO' },
                { id: 45639, name: 'OMORU EAST' },
                { id: 45640, name: 'OMORU WEST' },
                { id: 45641, name: 'OPEIDUKANITH' },
                { id: 45642, name: 'ORINGOWELLO' },
                { id: 45643, name: 'UMLONGE' },
                { id: 45644, name: 'UMLONGE EAST' },
                { id: 45645, name: 'UMLONGE WEST' },
              ],
            },
            {
              id: 7291,
              name: 'AREMO',
              villages: [
                { id: 45661, name: 'AGILE' },
                { id: 45662, name: 'AREMO CENTRAL' },
                { id: 45663, name: 'AREMO EAST' },
                { id: 45664, name: 'AREMO LOBOLWALA' },
                { id: 45665, name: 'AREMO NEW LINE' },
                { id: 45666, name: 'CHWAILAI' },
                { id: 45667, name: 'GOLGOTA' },
                { id: 45668, name: 'MISSION' },
                { id: 45669, name: 'ST. JOSEPH' },
                { id: 45670, name: 'WIPOLO' },
              ],
            },
            {
              id: 7290,
              name: 'KATABOK EAST',
              villages: [
                { id: 45653, name: 'ARENGEPUA NORTH' },
                { id: 45652, name: 'ARENGEPUA SOUTH' },
                { id: 45654, name: 'GULONGER EAST' },
                { id: 45655, name: 'GULONGER WEST' },
                { id: 45656, name: 'KATABOK CENTRAL' },
                { id: 45657, name: 'KATABOK EAST' },
                { id: 45658, name: 'KATABOK TRADING CENTRE' },
                { id: 45659, name: 'KATABOK WEST' },
                { id: 45660, name: 'LOBO-OYEA' },
              ],
            },
            {
              id: 7292,
              name: 'KATABOK WEST',
              villages: [
                { id: 45671, name: 'ODOLO EAST' },
                { id: 45672, name: 'ODOLO WEST' },
                { id: 45673, name: 'RACHKOKO CENTRAL' },
                { id: 45674, name: 'RACHKOKO NORTH' },
                { id: 45677, name: 'RACHKOKO SOUTH' },
                { id: 45675, name: 'RACHKOKO SOUTH EAST' },
                { id: 45676, name: 'RACHKOKO SOUTH WEST' },
              ],
            },
          ],
        },
        {
          id: 1550,
          name: 'NYAKWAE',
          parishes: [
            {
              id: 9647,
              name: 'KATHEBAKUME',
              villages: [
                { id: 58253, name: 'ANGADA' },
                { id: 63077, name: 'KATHEBAKUME' },
                { id: 68604, name: 'OGWEL' },
                { id: 69223, name: 'ORUKUMO' },
              ],
            },
            {
              id: 7298,
              name: 'KOBULIN',
              villages: [
                { id: 45717, name: 'ABOKATH' },
                { id: 45718, name: 'AOYATHOGO' },
                { id: 45719, name: 'BARJOBI' },
                { id: 45723, name: 'IBONGUSUA' },
                { id: 45722, name: 'JERUSALEM' },
                { id: 45720, name: 'KAKORINYANG' },
                { id: 45721, name: 'KANAAN' },
              ],
            },
            {
              id: 10167,
              name: 'OKIMIA',
              villages: [
                { id: 57263, name: 'ABUR' },
                { id: 57299, name: 'ACAN NIKOK' },
                { id: 57854, name: 'AKUMAMER' },
                { id: 58628, name: 'ATHEDER' },
              ],
            },
            {
              id: 7296,
              name: 'OPOPONGO',
              villages: [
                { id: 45699, name: 'AGULE ANGOLOL' },
                { id: 45700, name: 'AKONGUCHWA WEST' },
                { id: 45704, name: 'AKONGUCWA' },
                { id: 45701, name: 'ARIAMATHOLIM' },
                { id: 45702, name: 'CUNG APENYI' },
                { id: 45703, name: 'DII CWINYI' },
                { id: 45711, name: 'KAETHERENG' },
                { id: 45705, name: 'KATALA' },
                { id: 45706, name: 'OBAR  YATH' },
                { id: 45707, name: 'ODOKOMIT' },
                { id: 45708, name: 'OKWANGALUK' },
                { id: 45709, name: 'OPEDUR EAST' },
                { id: 45712, name: 'OPEDUR WEST' },
                { id: 45710, name: 'THULUMUK' },
              ],
            },
            {
              id: 7294,
              name: 'ORETHA',
              villages: [
                { id: 45682, name: 'AGULE' },
                { id: 45683, name: 'BULLA' },
                { id: 45684, name: 'GEREGERE NORTH' },
                { id: 45685, name: 'GEREGERE SOUTH' },
                { id: 45686, name: 'NYIKINYIKI NORTH' },
                { id: 45687, name: 'NYIKINYIKI SOUTH' },
              ],
            },
            {
              id: 7297,
              name: 'PUPUKAMUYA',
              villages: [
                { id: 45713, name: 'ATHEDER NORTH' },
                { id: 45714, name: 'ATHEDER SOUTH' },
                { id: 45715, name: 'AYWEE' },
                { id: 45716, name: 'TERAMOTH' },
              ],
            },
            {
              id: 7295,
              name: 'ROGOM',
              villages: [
                { id: 45688, name: 'ABUR' },
                { id: 45696, name: 'AGULERUKA' },
                { id: 45689, name: 'AKUMAMER' },
                { id: 45690, name: 'ANGADA' },
                { id: 45691, name: 'ATHEDER' },
                { id: 45693, name: 'KAPUNABONG' },
                { id: 45692, name: 'KATHEBAKUME' },
                { id: 45697, name: 'OLULUNG' },
                { id: 45694, name: 'OTHUTHUA' },
                { id: 45698, name: 'ROGOM CENTRAL' },
                { id: 45695, name: 'TYEN KWORO' },
              ],
            },
          ],
        },
        {
          id: 2098,
          name: 'OPOPONGO',
          parishes: [
            {
              id: 9638,
              name: 'KATALA',
              villages: [
                { id: 63028, name: 'KATALA' },
                { id: 63029, name: 'KATALA CENTRAL' },
                { id: 68282, name: 'NYIKINYIKI' },
                { id: 70737, name: 'THULUMUK' },
              ],
            },
            {
              id: 9796,
              name: 'KOPUA',
              villages: [
                { id: 57717, name: 'AKALALE' },
                { id: 64304, name: 'KOPUA' },
                { id: 68479, name: 'ODOKOMIT' },
                { id: 68740, name: 'OKWANGALUK' },
                { id: 69112, name: 'OPEDUR EAST' },
                { id: 69113, name: 'OPEDUR WEST' },
              ],
            },
            {
              id: 10106,
              name: 'NUTHU',
              villages: [
                { id: 61120, name: 'DII CWINYI' },
                { id: 61437, name: 'GULACUTH' },
                { id: 66386, name: 'MORUALOKWANGATH' },
                { id: 67766, name: 'NGOROPAM' },
                { id: 67883, name: 'NUTHU' },
              ],
            },
            {
              id: 10201,
              name: 'OPOPONGO',
              villages: [
                { id: 57574, name: 'AGULE ANGOLOL' },
                { id: 57824, name: 'AKONGUCHWA WEST' },
                { id: 57825, name: 'AKONGUCWA' },
                { id: 58489, name: 'ARIAMATHOLIM' },
                { id: 61071, name: 'CUNG APENYI' },
                { id: 61441, name: 'GULOPONO' },
                { id: 62050, name: 'KAETHERENG' },
                { id: 63826, name: 'KIRITEM' },
                { id: 68333, name: 'OBAR  YATH' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
