import { District } from '../index';

export default {
  id: 23,
  name: 'AGAGO',
  counties: [
    {
      id: 53,
      name: 'AGAGO COUNTY',
      sub_counties: [
        {
          id: 317,
          name: 'ADILANG',
          parishes: [
            {
              id: 1455,
              name: 'KULAKA',
              villages: [
                { id: 9410, name: 'KULAKA LELAJOK' },
                { id: 9411, name: 'KULAKA OBUR' },
                { id: 9412, name: 'KULAKA TEOBIL OKEC' },
                { id: 9413, name: 'LACEK KONYAKITING' },
                { id: 9414, name: 'OLOK KI WINYO' },
              ],
            },
            {
              id: 1453,
              name: 'LABWA',
              villages: [
                { id: 9385, name: 'ALERI DAM' },
                { id: 9386, name: 'AUU KIRUTE' },
                { id: 9395, name: 'BAR APWO' },
                { id: 9394, name: 'KAMANDING' },
                { id: 9387, name: 'LACEKOTO PIDA' },
                { id: 9393, name: 'LAWEE' },
                { id: 9388, name: 'LUMULE EAST' },
                { id: 9396, name: 'LUMULE WEST' },
                { id: 9389, name: 'MUGILA CENTRAL' },
                { id: 9390, name: 'MUGILA EAST' },
                { id: 9391, name: 'MUGILA WEST' },
                { id: 9392, name: 'OMUKO' },
              ],
            },
            {
              id: 1456,
              name: 'LAPYEM',
              villages: [
                { id: 9415, name: 'AJWAA CENTRAL' },
                { id: 9423, name: 'AJWAA EAST' },
                { id: 9416, name: 'AJWAA WEST' },
                { id: 9417, name: 'ANYAMI' },
                { id: 9418, name: 'DOGULAS' },
                { id: 9420, name: 'LAYUGI' },
                { id: 9419, name: 'ODOM CENTRAL' },
                { id: 9421, name: 'ODOM EAST' },
                { id: 9422, name: 'ODOM WEST' },
              ],
            },
            {
              id: 1454,
              name: 'NAM',
              villages: [
                { id: 9399, name: 'ADIO CAI' },
                { id: 9407, name: 'AGUN' },
                { id: 9397, name: 'ALOP' },
                { id: 9401, name: 'BAR JWA' },
                { id: 9402, name: 'BAR OLWETO' },
                { id: 9398, name: 'KIBIRA' },
                { id: 9400, name: 'KIBIRA CENTRAL' },
                { id: 9404, name: 'NAM ODIYO' },
                { id: 9408, name: 'NAMABILI CENTRAL' },
                { id: 9405, name: 'NAMBILI' },
                { id: 9403, name: 'NAMBILI LUNG KULU' },
                { id: 9409, name: 'OKEDE' },
                { id: 68714, name: 'OKUDU CENTRAL' },
                { id: 9406, name: 'OKUDU TEYAA' },
              ],
            },
          ],
        },
        {
          id: 318,
          name: 'ADILANG TOWN COUNCIL',
          parishes: [
            {
              id: 1458,
              name: 'ADILANG CENTRAL WARD',
              villages: [
                { id: 9430, name: 'LALAL CENTRAL' },
                { id: 64992, name: 'LALAL EAST' },
                { id: 9431, name: 'LALAL NORTH' },
                { id: 9429, name: 'LALAL SOUTH' },
                { id: 9432, name: 'LUBIRI' },
              ],
            },
            {
              id: 1459,
              name: 'ALAA WARD',
              villages: [
                { id: 9434, name: 'ANYAMI' },
                { id: 9433, name: 'AYWEE' },
                { id: 61065, name: 'CORNER ADEK' },
                { id: 9435, name: 'DOGULAS' },
                { id: 61755, name: 'JERUSALEM' },
                { id: 9436, name: 'LAYUGI' },
                { id: 65150, name: 'LAYUGI CENTRAL' },
              ],
            },
            {
              id: 1457,
              name: 'LALAL WARD',
              villages: [
                { id: 9424, name: 'CORNER ADEK' },
                { id: 9427, name: 'CORNER ADEK CENTRAL' },
                { id: 9425, name: 'GANGKAL' },
                { id: 9426, name: 'JERUSALEM' },
                { id: 64993, name: 'LALAL NORTH' },
                { id: 64994, name: 'LALAL WEST' },
                { id: 9428, name: 'LOYOBATI' },
              ],
            },
            {
              id: 1460,
              name: 'LUMULE WARD',
              villages: [
                { id: 61334, name: 'GANKAL' },
                { id: 9437, name: 'KULAKA CENTRAL' },
                { id: 64995, name: 'LALAL WEST' },
                { id: 65658, name: 'LUMULE EAST' },
                { id: 65659, name: 'LUMULE WEST' },
                { id: 68845, name: 'OLOK KI WINYO' },
              ],
            },
          ],
        },
        {
          id: 330,
          name: 'AGAGO TOWN COUNCIL',
          parishes: [
            {
              id: 1501,
              name: 'AGAGO CENTRAL WARD',
              villages: [
                { id: 9766, name: 'ADEGKOLO' },
                { id: 9768, name: 'ANYENA CENTRAL' },
                { id: 9769, name: 'ANYENA SOUTH' },
                { id: 9767, name: 'ANYENA WEST' },
                { id: 9770, name: 'LABWOR - OKOK' },
                { id: 9773, name: 'LOKOLE H/Q' },
                { id: 9772, name: 'OLWOR NGUU' },
                { id: 9771, name: 'WE - WII' },
              ],
            },
            {
              id: 1500,
              name: 'AJALI WARD',
              villages: [
                { id: 9760, name: 'LOKOLE EAST' },
                { id: 9761, name: 'MEDE' },
                { id: 9762, name: 'TEGWENG' },
                { id: 9763, name: 'WILOPANY' },
                { id: 9765, name: 'WILOPANY CENTRAL' },
                { id: 9764, name: 'WILOPANY NORTH' },
              ],
            },
            {
              id: 1502,
              name: 'NGORA WARD',
              villages: [
                { id: 9774, name: 'AKWORO' },
                { id: 9777, name: 'BOMBAY' },
                { id: 9775, name: 'BOMBAY SOUTH' },
                { id: 9778, name: 'NGORA' },
                { id: 9779, name: 'NGORA CENTRAL' },
                { id: 9776, name: 'NGORA SOUTH' },
                { id: 9780, name: 'OYARO TONGE' },
                { id: 9783, name: 'OYAROTONGE WEST' },
                { id: 9781, name: 'WII GWENG' },
                { id: 9782, name: 'YEKA' },
              ],
            },
            {
              id: 1503,
              name: 'PAMPARA WARD',
              villages: [
                { id: 9784, name: 'ACILERI' },
                { id: 9785, name: 'OLEYO WIYA' },
                { id: 9789, name: 'PAMPARA CENTRAL' },
                { id: 9788, name: 'PAMPARA EAST' },
                { id: 9790, name: 'PAMPARA NORTH' },
                { id: 9787, name: 'PAMPARA WEST' },
                { id: 9786, name: 'WANG - OPAL' },
              ],
            },
          ],
        },
        {
          id: 322,
          name: 'AGENGO',
          parishes: [
            {
              id: 9146,
              name: 'ADEMI',
              villages: [
                { id: 57376, name: 'ACURU ENGLAND' },
                { id: 57377, name: 'ACURU PAIBALO' },
                { id: 57378, name: 'ACURU SCHOOL' },
                { id: 57424, name: 'ADEG-ARONYA' },
                { id: 57427, name: 'ADEMI CENTRAL' },
                { id: 57428, name: 'ADEMI KEYO' },
                { id: 57105, name: 'ENGLAND EAST' },
                { id: 67748, name: 'NGOM PE WANG' },
                { id: 69755, name: 'PUNO LUGA' },
              ],
            },
            {
              id: 9153,
              name: 'AGENGO',
              villages: [
                { id: 57860, name: 'AKURI' },
                { id: 58910, name: 'BAR APWOO' },
                { id: 61093, name: 'DARA' },
                { id: 62183, name: 'KAKA MII NGO' },
                { id: 63299, name: 'KENYA CENTRAL' },
                { id: 69756, name: 'PUNO OGORO' },
              ],
            },
            {
              id: 1472,
              name: 'ALWEE',
              villages: [
                { id: 9519, name: 'AGIKI AGENGO' },
                { id: 9514, name: 'ALWEE DOGNAM' },
                { id: 9515, name: 'ALWEE KEYO' },
                { id: 9513, name: 'ALWEE NONO' },
                { id: 9516, name: 'ALWEE SCHOOL' },
                { id: 9520, name: 'AYWE CENRAL' },
                { id: 9517, name: 'AYWE KEYO' },
                { id: 9518, name: 'LOCKEN' },
              ],
            },
            {
              id: 1473,
              name: 'LAGUTI',
              villages: [
                { id: 9521, name: 'ADAK LELA' },
                { id: 9523, name: 'ADAK TUMPILI' },
                { id: 9522, name: 'ARINGO PEE' },
                { id: 9524, name: 'DOG DAGO' },
                { id: 9525, name: 'JING KOMI' },
                { id: 9526, name: 'OLOK KI TOO' },
              ],
            },
            {
              id: 9932,
              name: 'LUTOME',
              villages: [
                { id: 57198, name: 'ABOKO LACEN' },
                { id: 57605, name: 'AGWENG' },
                { id: 58124, name: 'AMENYI' },
                { id: 58936, name: 'BARABILI' },
                { id: 59045, name: 'BEYO AJOKA' },
                { id: 61152, name: 'DOGDAM' },
              ],
            },
            {
              id: 1474,
              name: 'TORI',
              villages: [
                { id: 9527, name: 'ALOKOLUM' },
                { id: 9529, name: 'ATABA' },
                { id: 9528, name: 'ENTEBBE' },
                { id: 9531, name: 'OYENYO' },
                { id: 70799, name: 'TOORI' },
                { id: 9532, name: 'TOORI EAST' },
                { id: 9530, name: 'TOORI WEST' },
              ],
            },
          ],
        },
        {
          id: 1935,
          name: 'AJALI',
          parishes: [
            {
              id: 9161,
              name: 'AJALI ATEDE',
              villages: [
                { id: 57290, name: 'ACAM ROMA' },
                { id: 57635, name: 'AJALI GULU' },
                { id: 58250, name: 'ANGA MURI' },
                { id: 58608, name: 'ATEDE' },
                { id: 58611, name: 'ATEDE CENTRAL' },
                { id: 58613, name: 'ATEDE EAST' },
                { id: 58615, name: 'ATEDE WEST' },
                { id: 57103, name: 'BAR-OLAM' },
                { id: 61443, name: 'GULU  SOUTH' },
                { id: 61444, name: 'GULU CENTRAL' },
                { id: 61445, name: 'GULU EAST' },
                { id: 61446, name: 'GULU WEST' },
                { id: 61447, name: 'GULU WETLANDS' },
                { id: 69874, name: 'RUBANGA-KENE' },
                { id: 71110, name: 'WI-GWENG' },
              ],
            },
            {
              id: 9760,
              name: 'KITENY',
              villages: [
                { id: 57410, name: 'ADAK' },
                { id: 57416, name: 'ADAK WEST' },
                { id: 63116, name: 'KATOLIT' },
                { id: 63117, name: 'KATOLIT CENTRAL' },
                { id: 63118, name: 'KATOLIT DOG NAM' },
                { id: 64896, name: 'LACAN KWERI' },
                { id: 64897, name: 'LACAN KWERI EAST' },
                { id: 64898, name: 'LACAN KWERI NORTH' },
                { id: 64899, name: 'LACAN KWERI SOUTH' },
                { id: 68485, name: 'ODONG PA LUTINO EAST' },
                { id: 68486, name: 'ODONG PALITINO' },
              ],
            },
            {
              id: 9853,
              name: 'LADERE',
              villages: [
                { id: 58515, name: 'ARINGO BOMB' },
                { id: 59125, name: 'BIT - DAM' },
                { id: 64919, name: 'LADERE CENTRAL' },
                { id: 64920, name: 'LADERE EAST' },
                { id: 64921, name: 'LADERE SOUTH' },
                { id: 64922, name: 'LADERE WEST' },
                { id: 65126, name: 'LATIN TWOO' },
                { id: 69303, name: 'OTIRO' },
              ],
            },
            {
              id: 9857,
              name: 'LAJWA',
              villages: [
                { id: 57380, name: 'ACUT OKON' },
                { id: 62439, name: 'KAMPALA' },
                { id: 62445, name: 'KAMPALA CENTRAL' },
                { id: 64270, name: 'KONA ABICEL' },
                { id: 64271, name: 'KONA ABICEL EAST' },
                { id: 64910, name: 'LACEKONYA' },
                { id: 64968, name: 'LAJWA' },
                { id: 68600, name: 'OGWARI' },
                { id: 68602, name: 'OGWARI NORTH' },
                { id: 68603, name: 'OGWARI SOUTH' },
                { id: 68814, name: 'OLIK' },
                { id: 68815, name: 'OLIK NORTH' },
                { id: 69860, name: 'ROTA' },
                { id: 71111, name: 'WI-KWEYO' },
              ],
            },
            {
              id: 10216,
              name: 'OTUMPILI',
              villages: [
                { id: 57422, name: 'ADEG ARONYA' },
                { id: 57423, name: 'ADEG ARONYA SOUTH' },
                { id: 58941, name: 'BARALIRI' },
                { id: 58942, name: 'BARALIRI CENTRAL' },
                { id: 58943, name: 'BARALIRI EAST' },
                { id: 58944, name: 'BARALIRI NORTH' },
                { id: 62575, name: 'KANYAMBAR' },
                { id: 65754, name: 'LWALA CENTRAL' },
                { id: 68431, name: 'OCUGA' },
                { id: 69326, name: 'OTUMPILI' },
                { id: 69327, name: 'OTUMPILI CENTRAL' },
                { id: 69329, name: 'OTUMPILI NORTH' },
              ],
            },
          ],
        },
        {
          id: 326,
          name: 'ARUM',
          parishes: [
            {
              id: 1482,
              name: 'ACHOL-PII',
              villages: [
                { id: 9606, name: 'ACANDANO' },
                { id: 9596, name: 'APIL' },
                { id: 9607, name: 'ATENGE' },
                { id: 9597, name: 'LADEK OKWOK' },
                { id: 9598, name: 'LAPONO MUK' },
                { id: 9605, name: 'LATWOKUN' },
                { id: 9601, name: 'LOKIWINYO' },
                { id: 9600, name: 'OJOTA' },
                { id: 9602, name: 'OKWANG A' },
                { id: 9608, name: 'OKWANG B' },
                { id: 9604, name: 'OLEL' },
                { id: 9603, name: 'OTENGO' },
                { id: 9609, name: 'TEBOKE' },
                { id: 9599, name: 'WIPOLO' },
              ],
            },
            {
              id: 1483,
              name: 'AGELEC',
              villages: [
                { id: 9610, name: 'ABEDOBER' },
                { id: 9612, name: 'AKWIL' },
                { id: 9614, name: 'APII OGURU' },
                { id: 9615, name: 'CAWENTE' },
                { id: 9616, name: 'DOGAGWENG B' },
                { id: 9617, name: 'OMOT' },
                { id: 9613, name: 'OMOT EAST' },
                { id: 9618, name: 'OWOLO' },
                { id: 9611, name: 'TIKGINOKELI' },
              ],
            },
            {
              id: 1484,
              name: 'ALELA',
              villages: [
                { id: 9620, name: 'ALELA' },
                { id: 9619, name: 'ANYANGO A' },
                { id: 9622, name: 'ANYANGO B' },
                { id: 9623, name: 'AYIKA' },
                { id: 9627, name: 'BATAYOM' },
                { id: 9624, name: 'BILA' },
                { id: 9621, name: 'GWOK  APUR' },
                { id: 9625, name: 'OLARO COO' },
                { id: 9626, name: 'ONGARO' },
              ],
            },
            {
              id: 1485,
              name: 'KAZIKAZI',
              villages: [
                { id: 9629, name: 'ALOLOLO' },
                { id: 9635, name: 'ARUM' },
                { id: 9631, name: 'ARUM CAMP' },
                { id: 9628, name: 'ARUM CENTRAL' },
                { id: 9632, name: 'ARUM IKOM' },
                { id: 9634, name: 'DOG AGWENG' },
                { id: 9633, name: 'LACAN ONYONG' },
                { id: 9630, name: 'LAMIN ARENG' },
                { id: 9638, name: 'ODUPULURU' },
                { id: 9637, name: 'OKWENY' },
                { id: 9641, name: 'ONWO' },
                { id: 9639, name: 'WATUNA' },
                { id: 9640, name: 'WIATUP' },
                { id: 9636, name: 'WII-KWEYO' },
              ],
            },
          ],
        },
        {
          id: 324,
          name: 'GEREGERE',
          parishes: [
            {
              id: 1479,
              name: 'BARADANGA',
              villages: [
                { id: 9581, name: 'BARADANGA' },
                { id: 9582, name: 'BARADANGA KUYWEE' },
                { id: 9583, name: 'BARADANGA RACKOKO' },
                { id: 9579, name: 'ONYOL CENTRAL' },
                { id: 9580, name: 'OPOTA T.C' },
                { id: 9584, name: 'WANGLOBO' },
              ],
            },
            {
              id: 9867,
              name: 'LATINLING',
              villages: [
                { id: 61090, name: 'DANGI' },
                { id: 65008, name: 'LALUR ONYOL' },
                { id: 65127, name: 'LATINLING NAM' },
                { id: 65128, name: 'LATINLING NGOMOROMO' },
                { id: 65129, name: 'LATINLING YENGLEMI' },
                { id: 67197, name: 'NAM CENTRAL' },
                { id: 67198, name: 'NAM KAMON OJWII' },
                { id: 67759, name: 'NGOMOROMO' },
              ],
            },
            {
              id: 1480,
              name: 'OLUPE',
              villages: [
                { id: 9585, name: 'AGORO CENTRAL' },
                { id: 9586, name: 'AGORO KUMOLO' },
                { id: 9587, name: 'AGORO TOKODO' },
                { id: 9590, name: 'LAJOK KENA JAKA' },
                { id: 9589, name: 'OLUPE AGORO' },
                { id: 9591, name: 'OLUPE CENTRAL' },
                { id: 9592, name: 'OLUPE OJUU' },
                { id: 9588, name: 'OLUPE OPONG' },
              ],
            },
            {
              id: 10313,
              name: 'TENGE',
              villages: [
                { id: 61359, name: 'GEREGERE' },
                { id: 61362, name: 'GEREGERE T/C' },
                { id: 64870, name: 'LABIMA' },
                { id: 64871, name: 'LABIMA CENTRAL' },
                { id: 64872, name: 'LABIMA HIGHLAND' },
                { id: 64963, name: 'LAJOK KENA' },
                { id: 64964, name: 'LAJOK KENA ABILONINO' },
                { id: 64965, name: 'LAJOK KENA CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 327,
          name: 'KOTOMOR',
          parishes: [
            {
              id: 1489,
              name: 'APOBO',
              villages: [
                { id: 9680, name: 'ABULU MOGO' },
                { id: 9675, name: 'AMINA BIL' },
                { id: 9676, name: 'AMOKOWANG' },
                { id: 9677, name: 'APOBO' },
                { id: 9681, name: 'ATUP' },
                { id: 9682, name: 'ATWONKONGO' },
                { id: 9683, name: 'BARGOBA' },
                { id: 9673, name: 'KOT OMOR CENTRAL' },
                { id: 9674, name: 'KOT OMOR EAST' },
                { id: 9684, name: 'OCILA' },
                { id: 9678, name: 'OPILI FARM' },
                { id: 9679, name: 'TEE YAO' },
              ],
            },
            {
              id: 1486,
              name: 'LUKEE',
              villages: [
                { id: 9653, name: 'ADAG AMONE' },
                { id: 9642, name: 'ALUGA EAST' },
                { id: 9654, name: 'ALUGA WEST' },
                { id: 9643, name: 'AMATO LEL' },
                { id: 9644, name: 'APADO' },
                { id: 9645, name: 'AWONG' },
                { id: 9646, name: 'CORNER ALIRO' },
                { id: 9647, name: 'DOG OKEE' },
                { id: 9648, name: 'IYER TEKULU' },
                { id: 9649, name: 'IYERMAKATONG' },
                { id: 9650, name: 'ODOKOMIT EAST' },
                { id: 9651, name: 'ODOKOMIT WEST' },
                { id: 9655, name: 'OGWANG OULA' },
                { id: 9652, name: 'OPIDO LOBO' },
              ],
            },
            {
              id: 1490,
              name: 'OGONG',
              villages: [
                { id: 9685, name: 'ACWIKO' },
                { id: 9686, name: 'BAR OLWEDO' },
                { id: 9687, name: 'OGONG CENTRAL' },
                { id: 9690, name: 'TE BUNG' },
                { id: 9691, name: 'TE DAGO' },
                { id: 9688, name: 'TECWAO' },
                { id: 9692, name: 'TEGWENG' },
                { id: 9689, name: 'TEKULU' },
              ],
            },
            {
              id: 1491,
              name: 'OLYELO WIDYEL',
              villages: [
                { id: 9695, name: 'EBULE' },
                { id: 9696, name: 'EBULE LWALA' },
                { id: 9698, name: 'OLYELO CENTRAL' },
                { id: 9699, name: 'OLYELO TEKULU' },
                { id: 9700, name: 'OLYELO WIDYEL' },
                { id: 9693, name: 'ONEKO ABIR' },
                { id: 9694, name: 'ORINGO UNGA' },
                { id: 9697, name: 'ORORO' },
              ],
            },
            {
              id: 1487,
              name: 'OMATOWEE',
              villages: [
                { id: 9656, name: 'ACWAO' },
                { id: 9657, name: 'AGWEE' },
                { id: 9658, name: 'EWOO' },
                { id: 9659, name: 'ODIRI' },
                { id: 9660, name: 'OGOR RIVER' },
                { id: 9661, name: 'OGUL' },
                { id: 9664, name: 'OGUL CENTRAL' },
                { id: 9662, name: 'OMATOWEE' },
                { id: 9663, name: 'ONUDO APET' },
              ],
            },
            {
              id: 1488,
              name: 'OTEK',
              villages: [
                { id: 9665, name: 'AKENO MOR' },
                { id: 9670, name: 'AKURI MOA' },
                { id: 9666, name: 'AMINOGWAL' },
                { id: 9671, name: 'APANY PEKOK' },
                { id: 9667, name: 'GUU' },
                { id: 9672, name: 'OKUNU AMOR' },
                { id: 9668, name: 'OTEK' },
                { id: 9669, name: 'TETWORO' },
              ],
            },
          ],
        },
        {
          id: 328,
          name: 'LAMIYO',
          parishes: [
            {
              id: 1494,
              name: 'OJUR',
              villages: [
                { id: 9715, name: 'ALULA' },
                { id: 9716, name: 'GUTI' },
                { id: 9717, name: 'LAMINONYULA' },
                { id: 9718, name: 'LAMIYO' },
                { id: 9719, name: 'LUNYPALI' },
                { id: 9721, name: 'OLWORNGUR' },
                { id: 9720, name: 'OMWODLUM' },
              ],
            },
            {
              id: 1493,
              name: 'OTAKA',
              villages: [
                { id: 9709, name: 'AJERE' },
                { id: 9710, name: 'ALYEK CENTRAL' },
                { id: 9711, name: 'ALYEKRIBA' },
                { id: 9714, name: 'BULUJI' },
                { id: 9713, name: 'LAMINODYEK' },
                { id: 9712, name: 'PAICAM AYWEE' },
              ],
            },
            {
              id: 1492,
              name: 'PAICAM',
              villages: [
                { id: 9708, name: 'GEM' },
                { id: 9701, name: 'KWONKIC' },
                { id: 9707, name: 'KWONKIC CENTRAL' },
                { id: 9702, name: 'KWONKIC DOGNAM' },
                { id: 9703, name: 'KWONKIC/LABWOROKEMA' },
                { id: 9704, name: 'LABWOROKEMA' },
                { id: 9705, name: 'LALIRA GEM' },
                { id: 9706, name: 'OLOKOLEB' },
              ],
            },
            {
              id: 1495,
              name: 'POLCANI',
              villages: [
                { id: 9722, name: 'AYAM BUNGA' },
                { id: 9723, name: 'AYAM CENTRAL' },
                { id: 9724, name: 'LABONGEDERO' },
                { id: 9725, name: 'LADYEL KI NYOK' },
                { id: 9726, name: 'LAGALAGA' },
                { id: 9727, name: 'POLCANI BUNGA' },
              ],
            },
          ],
        },
        {
          id: 325,
          name: 'LAPEREBONG',
          parishes: [
            {
              id: 9876,
              name: 'LIGILIGI',
              villages: [
                { id: 58555, name: 'ARUNA' },
                { id: 61142, name: 'DOG DAGO' },
                { id: 62404, name: 'KAMANDING' },
                { id: 64892, name: 'LABWOR ONGURO' },
                { id: 64908, name: 'LACEK KONYA' },
                { id: 64924, name: 'LADIT OKUN WEST' },
                { id: 65189, name: 'LIGILIGI CENTRAL' },
                { id: 65190, name: 'LIGILIGI EAST' },
                { id: 65199, name: 'LINGOTOO' },
                { id: 65200, name: 'LINGOTOO CENTRAL' },
                { id: 65308, name: 'LOII' },
                { id: 69051, name: 'ONGANY' },
                { id: 69053, name: 'ONGANY WEST' },
              ],
            },
            {
              id: 1481,
              name: 'NANANGWE',
              villages: [
                { id: 62602, name: 'KANYIPA  EAST' },
                { id: 62603, name: 'KANYIPA WEST' },
                { id: 9593, name: 'KAROKO EAST' },
                { id: 9594, name: 'KAROKO WEST' },
                { id: 64923, name: 'LADIT OKUN' },
                { id: 68794, name: 'OLENYO EAST' },
                { id: 9595, name: 'OLENYO WEST' },
              ],
            },
            {
              id: 10084,
              name: 'NGEKIDI',
              villages: [
                { id: 57656, name: 'AJIKI MILO' },
                { id: 58281, name: 'ANGOLO EAST' },
                { id: 58282, name: 'ANGOLO WEST' },
                { id: 58701, name: 'AWALKOK' },
                { id: 63700, name: 'KILOKO ITIO' },
                { id: 63702, name: 'KILOLO ITIO CENTRAL' },
                { id: 65588, name: 'LUGAJI' },
                { id: 68589, name: 'OGULU MUKA' },
                { id: 69046, name: 'ONGAKO EAST' },
                { id: 69047, name: 'ONGAKO WEST' },
              ],
            },
            {
              id: 10207,
              name: 'ORINA',
              villages: [
                { id: 58083, name: 'ALWAR' },
                { id: 58560, name: 'ARWAI' },
                { id: 58911, name: 'BAR AYOM' },
                { id: 62233, name: 'KAKONGO EAST' },
                { id: 62234, name: 'KAKONGO WEST' },
                { id: 62653, name: 'KAPEL EAST' },
                { id: 62654, name: 'KAPEL WEST' },
                { id: 69194, name: 'ORINA KAPEL' },
                { id: 69196, name: 'ORINGO  PANGA' },
                { id: 69328, name: 'OTUMPILI EAST' },
                { id: 69330, name: 'OTUMPILI WEST' },
              ],
            },
          ],
        },
        {
          id: 319,
          name: 'LIRA-PALWO',
          parishes: [
            {
              id: 1462,
              name: 'BIWANG',
              villages: [
                { id: 9445, name: 'ARINGO PALA' },
                { id: 9448, name: 'BIWANG BAR-OMAA' },
                { id: 9449, name: 'BIWANG CENTRAL' },
                { id: 9446, name: 'BIWANG LUBIRI' },
                { id: 9447, name: 'BIWANG NGOM LAC' },
                { id: 9450, name: 'BIWANGWIGWENG' },
                { id: 67756, name: 'NGOMLAC' },
                { id: 9451, name: 'WALO' },
              ],
            },
            {
              id: 1464,
              name: 'LANYIRINYIRI',
              villages: [
                { id: 9454, name: 'ACUT OMER' },
                { id: 9453, name: 'AJOBI' },
                { id: 9455, name: 'AWINYI' },
                { id: 9459, name: 'LAPYEM' },
                { id: 9456, name: 'OGUL' },
                { id: 70646, name: 'TE-OPOK' },
                { id: 9457, name: 'WIMUNUPECEK' },
                { id: 9458, name: 'YABWANGI' },
              ],
            },
            {
              id: 1463,
              name: 'LAPETA',
              villages: [
                { id: 61356, name: 'GEMODWONG' },
                { id: 61786, name: 'JUK LEBI' },
                { id: 64436, name: 'KWAL LAGWE' },
                { id: 65100, name: 'LAPETA CENTRAL' },
                { id: 65104, name: 'LAPILYET EAST' },
                { id: 65105, name: 'LAPILYET WEST' },
                { id: 70659, name: 'TECOGA' },
                { id: 9452, name: 'TIMAKCA' },
              ],
            },
            {
              id: 1461,
              name: 'OMONGO',
              villages: [
                { id: 9438, name: 'ABONE GANG-KAL' },
                { id: 9439, name: 'ABONE NORTH' },
                { id: 9440, name: 'ABONE OT YAT' },
                { id: 58736, name: 'AWEN' },
                { id: 58738, name: 'AWEN WEST' },
                { id: 9441, name: 'BADMUNU' },
                { id: 59655, name: 'BUL OTWOMO' },
                { id: 61585, name: 'IIAK KWE' },
                { id: 9443, name: 'LACEK' },
                { id: 9442, name: 'LACEK OYIR' },
                { id: 9444, name: 'NGOMLAC' },
                { id: 69768, name: 'PYER GWENG CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 331,
          name: 'LIRA-PALWO TOWN COUNCIL',
          parishes: [
            {
              id: 1504,
              name: 'ABONE GANG KAL WARD',
              villages: [
                { id: 9792, name: 'ABONE NORTH' },
                { id: 9791, name: 'ABONE OT YAT' },
                { id: 9793, name: 'GANG-KAL CENTRAL' },
                { id: 9794, name: 'GANG-KAL EAST' },
                { id: 61331, name: 'GANG-KAL WEST' },
              ],
            },
            {
              id: 1505,
              name: 'BULOTWOMO WARD',
              villages: [
                { id: 9797, name: 'BULOTWOMO' },
                { id: 9795, name: 'BULOTWOMO EAST' },
                { id: 9796, name: 'BULOTWOMO NORTH' },
                { id: 61092, name: 'DANO BEDO KI WADI' },
              ],
            },
            {
              id: 1506,
              name: 'LAPILYET WARD',
              villages: [
                { id: 9801, name: 'KWALLAGWE' },
                { id: 9803, name: 'LAPII LYET' },
                { id: 9798, name: 'LAPILYET EAST' },
                { id: 9799, name: 'LAPILYET WEST' },
                { id: 9800, name: 'NGATI PE TEK' },
                { id: 9802, name: 'PIDA' },
                { id: 9804, name: 'TIMAKICA' },
              ],
            },
            {
              id: 1507,
              name: 'PYERGWENG WARD',
              villages: [
                { id: 9805, name: 'AWEN' },
                { id: 58737, name: 'AWEN WEST' },
                { id: 9806, name: 'PYERGWENG' },
                { id: 69769, name: 'PYERGWENG A' },
                { id: 69770, name: 'PYERGWENG B' },
                { id: 71124, name: 'WIGWENG' },
              ],
            },
          ],
        },
        {
          id: 320,
          name: 'LOKOLE',
          parishes: [
            {
              id: 9248,
              name: 'AYWEE',
              villages: [
                { id: 57379, name: 'ACUT' },
                { id: 57383, name: 'ACUT WEST' },
                { id: 57500, name: 'ADWARI' },
                { id: 58345, name: 'ANYWAL ATIR' },
                { id: 58854, name: 'AYWEE LABUCE' },
                { id: 58905, name: 'BAR  NYALO' },
                { id: 61164, name: 'DOT LAJWAR' },
                { id: 68528, name: 'ODWOR' },
                { id: 68563, name: 'OGOLO' },
                { id: 69848, name: 'ROMA' },
              ],
            },
            {
              id: 9774,
              name: 'KIWARO',
              villages: [
                { id: 57344, name: 'ACHOLI NYEK' },
                { id: 57347, name: 'ACHOLINYEK CENTRAL' },
                { id: 58070, name: 'ALUNGA TEKWORO' },
                { id: 58071, name: 'ALUNGA WITIM' },
                { id: 58533, name: 'ARIWII' },
                { id: 60810, name: 'BWOL' },
                { id: 64128, name: 'KIWARO' },
                { id: 67428, name: 'NANG' },
                { id: 69005, name: 'OMUKUGUNGU' },
                { id: 69314, name: 'OTONG' },
                { id: 71139, name: 'WII TIM' },
                { id: 71185, name: 'WOT KIWII' },
              ],
            },
            {
              id: 9934,
              name: 'LUZIRA',
              villages: [
                { id: 57163, name: 'ABILNINO' },
                { id: 57548, name: 'AGIKI  LANGO' },
                { id: 58912, name: 'BAR BONE' },
                { id: 61145, name: 'DOG LUKWARA' },
                { id: 64984, name: 'LAKWANA' },
                { id: 65073, name: 'LANGALA  GADO' },
                { id: 65726, name: 'LUZIRA' },
                { id: 65729, name: 'LUZIRA CENTRAL' },
                { id: 65730, name: 'LUZIRA LWALA' },
                { id: 69370, name: 'OWIL' },
                { id: 70645, name: 'TE-OLIM' },
                { id: 71184, name: 'WOT KI OCEKE' },
                { id: 71220, name: 'YER ATYER' },
                { id: 71221, name: 'YER ATYER WEST' },
              ],
            },
            {
              id: 1465,
              name: 'NGUDI',
              villages: [
                { id: 57291, name: 'ACAM TOO' },
                { id: 9460, name: 'ALUNGAR ACAMTOO' },
                { id: 9463, name: 'LACEN OTANY' },
                { id: 65156, name: 'LEE' },
                { id: 9461, name: 'LOI EAST' },
                { id: 65306, name: 'LOI TIM' },
                { id: 9464, name: 'LOYI' },
                { id: 9462, name: 'ODOKOMIT' },
                { id: 69131, name: 'OPIT' },
                { id: 9465, name: 'TIM LEE' },
                { id: 71025, name: 'WANG CWAA' },
              ],
            },
            {
              id: 1467,
              name: 'NGWERO',
              villages: [
                { id: 9481, name: 'ADANI' },
                { id: 9489, name: 'KARUMU  EAST' },
                { id: 9479, name: 'KARUMU CENTRAL' },
                { id: 9483, name: 'KARUMU WEST' },
                { id: 9480, name: 'KOTIDO' },
                { id: 9482, name: 'LALUR' },
                { id: 9486, name: 'LAPIRIN' },
                { id: 9487, name: 'LAPIRIN CENTRAL' },
                { id: 9484, name: 'LAPIRIN EAST' },
                { id: 9488, name: 'OMOK' },
                { id: 9485, name: 'WIGWENG' },
              ],
            },
            {
              id: 1466,
              name: 'OLUNG',
              villages: [
                { id: 9469, name: 'ANYONGO CUNY' },
                { id: 9466, name: 'ARUNA' },
                { id: 9468, name: 'ARUNA SOUTH' },
                { id: 9473, name: 'BAR KILITI WIGWENG' },
                { id: 9467, name: 'BARKILITI' },
                { id: 9475, name: 'CEWENTE' },
                { id: 9474, name: 'KWEYO' },
                { id: 9470, name: 'KWEYO EAST' },
                { id: 9476, name: 'KWEYO NORTH' },
                { id: 9477, name: 'KWILA' },
                { id: 9471, name: 'LWALA CENTRAL' },
                { id: 9478, name: 'LWALA EAST' },
                { id: 9472, name: 'LWALA SOUTH' },
              ],
            },
            {
              id: 10348,
              name: 'WIIDWOL',
              villages: [
                { id: 57592, name: 'AGWATA WIL' },
                { id: 71118, name: 'WIDWOL' },
                { id: 71119, name: 'WIDWOL SOUTH' },
                { id: 71142, name: 'WIIDWOL CENTRAL' },
                { id: 71143, name: 'WIIDWOL EAST' },
                { id: 71144, name: 'WIIDWOL WEST' },
              ],
            },
          ],
        },
        {
          id: 321,
          name: 'OMOT',
          parishes: [
            {
              id: 1468,
              name: 'ATECE',
              villages: [
                { id: 9490, name: 'ADAK TEKULU' },
                { id: 9493, name: 'AMATIBURU' },
                { id: 9492, name: 'ATECE ATECE A' },
                { id: 9491, name: 'ATECE ATECE B' },
                { id: 9495, name: 'KUTANGICA' },
                { id: 9494, name: 'OKWALO MARA' },
              ],
            },
            {
              id: 1471,
              name: 'AWONODWE',
              villages: [
                { id: 9507, name: 'ABERO' },
                { id: 9508, name: 'ABERO B' },
                { id: 9510, name: 'ALWORO' },
                { id: 9509, name: 'ATAPARA BAR' },
                { id: 9511, name: 'OKOL' },
                { id: 9512, name: 'ONGIDO' },
              ],
            },
            {
              id: 1469,
              name: 'BARIMA',
              villages: [
                { id: 9496, name: 'ALONGOTEK' },
                { id: 58867, name: 'BADMUNU-BOR' },
                { id: 9497, name: 'BARIMA' },
                { id: 61057, name: 'COO-PE-MWODO-YEN' },
                { id: 9498, name: 'ONGARO' },
                { id: 9499, name: 'TEBOLO' },
                { id: 9500, name: 'TEGWENG' },
              ],
            },
            {
              id: 1470,
              name: 'OPARI',
              villages: [
                { id: 9501, name: 'ADAK' },
                { id: 9502, name: 'ATULA' },
                { id: 9503, name: 'ATULA CENTRAL' },
                { id: 9505, name: 'BAR MUNU' },
                { id: 9504, name: 'OPARI' },
                { id: 9506, name: 'OPARI TEGWENG' },
              ],
            },
          ],
        },
        {
          id: 323,
          name: 'PATONGO',
          parishes: [
            {
              id: 1476,
              name: 'KAL',
              villages: [
                { id: 9540, name: 'ADEKOKWOK' },
                { id: 9541, name: 'APANO CENTRAL' },
                { id: 9542, name: 'APANO NORTH' },
                { id: 9543, name: 'LABWOR ORYEMO SOUTH' },
                { id: 9544, name: 'NOTA' },
                { id: 9545, name: 'OPYELO CENTRAL' },
                { id: 9546, name: 'ORAMA CENTRAL' },
                { id: 9547, name: 'ORAMA TEBUNG' },
              ],
            },
            {
              id: 1475,
              name: 'LAKWA',
              villages: [
                { id: 9533, name: 'AGRIKACA' },
                { id: 9534, name: 'BAR OPUT' },
                { id: 9535, name: 'LAGWEDOLA' },
                { id: 9537, name: 'LUPEKAR' },
                { id: 9536, name: 'ORYO ONEKOGWENO' },
                { id: 9538, name: 'TOROMA EAST' },
                { id: 9539, name: 'VIETNAM' },
              ],
            },
            {
              id: 1477,
              name: 'LUKWANGOLE',
              villages: [
                { id: 9548, name: 'ALOI CENTRAL' },
                { id: 9549, name: 'ALOI EAST' },
                { id: 9560, name: 'ALOI FOREST' },
                { id: 9550, name: 'ALOI WEST' },
                { id: 9551, name: 'ARII WII' },
                { id: 9552, name: 'ODOKONYERO KADYANG' },
                { id: 9553, name: 'ODOKONYERO WIKIRA' },
                { id: 9554, name: 'OKERE' },
                { id: 9559, name: 'OLOK KI WINYO' },
                { id: 9555, name: 'OMWODLUM' },
                { id: 9556, name: 'OWINY KIBUL' },
                { id: 9557, name: 'OWITO' },
                { id: 9558, name: 'TEKULU' },
              ],
            },
            {
              id: 1478,
              name: 'ODONGKIWINYO',
              villages: [
                { id: 9568, name: 'ACOGO GWAO' },
                { id: 9576, name: 'ADYANG ITUME' },
                { id: 9561, name: 'ADYANG ITUME EAST' },
                { id: 9569, name: 'AGWENG' },
                { id: 9570, name: 'DAGO IRIT' },
                { id: 9571, name: 'KAIRUM' },
                { id: 9577, name: 'LALUR-OMWODA WEST' },
                { id: 9572, name: 'LALUROMWODA CENTRAL' },
                { id: 9562, name: 'LUZIRA CENTRAL' },
                { id: 9563, name: 'MICIRI' },
                { id: 9573, name: 'MICIRI WEST' },
                { id: 9574, name: 'OLYET' },
                { id: 9564, name: 'OPAL' },
                { id: 9565, name: 'OYERE TEKWORO' },
                { id: 9566, name: 'TIM LEE' },
                { id: 9575, name: 'TOO-COO-DOG-DAGU' },
                { id: 9578, name: 'YAO ACOI WEST' },
                { id: 9567, name: 'YAO-ACOI' },
              ],
            },
          ],
        },
        {
          id: 329,
          name: 'PATONGO TOWN COUNCIL',
          parishes: [
            {
              id: 1499,
              name: 'AKOMO WARD',
              villages: [
                { id: 9755, name: 'AGWENG' },
                { id: 9754, name: 'AKOMO CENTRAL' },
                { id: 9758, name: 'AKOMO WEST' },
                { id: 9753, name: 'BAR LACEDE' },
                { id: 9757, name: 'DOG OLUPE' },
                { id: 9756, name: 'KIBEDO IPOO' },
                { id: 9759, name: 'LONDON' },
              ],
            },
            {
              id: 1496,
              name: 'FOREST WARD',
              villages: [
                { id: 9730, name: 'BAR APWOYO' },
                { id: 9728, name: 'BAR APWOYO WEST' },
                { id: 9729, name: 'CULLOMOI QUARTER' },
                { id: 9731, name: 'DOG MISSION' },
                { id: 9732, name: 'FOREST' },
                { id: 9733, name: 'FOREST CENTRAL' },
                { id: 9734, name: 'LALUR -OMWODA EAST' },
              ],
            },
            {
              id: 1497,
              name: 'OPOROT WARD',
              villages: [
                { id: 9735, name: 'BARDEGE' },
                { id: 9740, name: 'COUNTY HQTRS' },
                { id: 9739, name: 'MOODEGE' },
                { id: 9736, name: 'OPOROT CENTRAL' },
                { id: 9737, name: 'OPOROT EAST' },
                { id: 9742, name: 'OPOROT NORTH' },
                { id: 9743, name: 'OPOROT SOUTH' },
                { id: 9738, name: 'TEE ADWOKI' },
                { id: 9741, name: 'TOO COO' },
              ],
            },
            {
              id: 1498,
              name: 'PECE WARD',
              villages: [
                { id: 9744, name: 'AJALI QUATOR' },
                { id: 9746, name: 'JANGLE' },
                { id: 9747, name: 'LABWOR-ORYEMO CENTRAL' },
                { id: 9745, name: 'OGWAL OWOO' },
                { id: 9748, name: 'OLD PATONGO' },
                { id: 9749, name: 'OLIGA QUATOR' },
                { id: 9751, name: 'PATONGO CENTRAL' },
                { id: 9750, name: 'PATONGO EAST' },
                { id: 9752, name: 'PECE' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 54,
      name: 'AGAGO NORTH COUNTY',
      sub_counties: [
        {
          id: 340,
          name: 'KALONGO TOWN COUNCIL',
          parishes: [
            {
              id: 1538,
              name: 'AKADO WARD',
              villages: [
                { id: 10093, name: 'AKADO CENTRAL' },
                { id: 10094, name: 'AKADO EAST' },
                { id: 10095, name: 'AKADO WEST' },
                { id: 10096, name: 'NIMARO' },
                { id: 10097, name: 'SUB-DISTRICT' },
              ],
            },
            {
              id: 1537,
              name: 'ALUPERE WARD',
              villages: [
                { id: 10086, name: 'ALOK KI WINYO' },
                { id: 10087, name: 'ALUPERE CENTRAL' },
                { id: 10089, name: 'ALUPERE MIDDLE' },
                { id: 10088, name: 'ALUPERE ORIGINAL' },
                { id: 10090, name: 'BAR DEGE' },
                { id: 10091, name: 'MAIN MARKET' },
                { id: 10092, name: 'WANG WINY NORTH' },
              ],
            },
            {
              id: 1539,
              name: 'KUBWOR WARD',
              villages: [
                { id: 10101, name: 'KAMWOLO' },
                { id: 10098, name: 'KUBWOR  CENTRAL' },
                { id: 10100, name: 'KUBWOR  EAST' },
                { id: 10102, name: 'KUBWOR BUNGU' },
                { id: 10099, name: 'KUBWOR WEST' },
              ],
            },
            {
              id: 1540,
              name: 'ORET WARD',
              villages: [
                { id: 10103, name: 'ADUNU CENTRAL' },
                { id: 10105, name: 'ADUNU ORIGINAL' },
                { id: 10104, name: 'ADUNU WEST' },
                { id: 10106, name: 'MISSION' },
                { id: 10107, name: 'ORET' },
              ],
            },
            {
              id: 1536,
              name: 'TOWN WARD',
              villages: [
                { id: 10085, name: 'AKADO ORIGINAL' },
                { id: 10081, name: 'AKADO SOUTH' },
                { id: 10084, name: 'ALUPERE WEST' },
                { id: 10079, name: 'OGWAL WOO' },
                { id: 10082, name: 'TOWN BOARD' },
                { id: 10080, name: 'WANG AMUKA' },
                { id: 10083, name: 'WANG WINY SOUTH' },
              ],
            },
          ],
        },
        {
          id: 335,
          name: 'KUYWEE',
          parishes: [
            {
              id: 9236,
              name: 'ATUT',
              villages: [
                { id: 58130, name: 'AMIDA' },
                { id: 58131, name: 'AMIDA WEST' },
                { id: 60163, name: 'BUNGA' },
                { id: 60167, name: 'BUNGA EAST' },
                { id: 61153, name: 'DOGLELA' },
                { id: 62287, name: 'KALAKI' },
                { id: 62290, name: 'KALAKI NORTH' },
                { id: 62622, name: 'KAOLO' },
                { id: 62624, name: 'KAOLO WEST' },
                { id: 64398, name: 'KUROC' },
                { id: 65323, name: 'LOKABAR' },
                { id: 65594, name: 'LUGILA' },
                { id: 66068, name: 'MASAKA' },
                { id: 68491, name: 'ODONGKICEL' },
                { id: 69159, name: 'ORA-OKELO' },
                { id: 69296, name: 'OTIBI' },
              ],
            },
            {
              id: 1519,
              name: 'BOMBO',
              villages: [
                { id: 9885, name: 'ATANGA' },
                { id: 9881, name: 'BOMBO CENTRAL' },
                { id: 9882, name: 'BOMBO EAST' },
                { id: 9886, name: 'BOMBO NORTH' },
                { id: 9883, name: 'BOMBO SOUTH' },
                { id: 9884, name: 'BOMBO WEST' },
                { id: 63377, name: 'KIBIRA' },
                { id: 64213, name: 'KOKOLIK' },
                { id: 64869, name: 'LABIDWOGO' },
                { id: 65094, name: 'LAPAK' },
                { id: 9887, name: 'WANG OLIM' },
              ],
            },
            {
              id: 9561,
              name: 'KAL-AGUM',
              villages: [
                { id: 61077, name: 'CYLON' },
                { id: 61862, name: 'KABAMBA' },
                { id: 62386, name: 'KALWO' },
                { id: 66650, name: 'MURIA' },
                { id: 68621, name: 'OJAKO' },
                { id: 70809, name: 'TOROMA CENTRAL' },
                { id: 70810, name: 'TOROMA NORTH' },
                { id: 70811, name: 'TOROMA SOUTH' },
                { id: 70812, name: 'TOROMA WEST' },
              ],
            },
            {
              id: 1520,
              name: 'LABWORDWONG',
              villages: [
                { id: 9889, name: 'AMATA' },
                { id: 9891, name: 'ATUT - ARWENY' },
                { id: 9890, name: 'ATUT WEST' },
                { id: 9892, name: 'BIWANG' },
                { id: 9893, name: 'BUK OLWONGI' },
                { id: 9894, name: 'JAII CENTRAL' },
                { id: 9895, name: 'JAIL EAST' },
                { id: 9896, name: 'JAIL WEST' },
                { id: 9888, name: 'KILOKO ITIYO' },
                { id: 9897, name: 'LALA KABAL' },
                { id: 9898, name: 'LELA KABALA' },
                { id: 9899, name: 'LELA KABALA EAST' },
                { id: 65454, name: 'LONDON' },
              ],
            },
            {
              id: 9861,
              name: 'LAMIT',
              villages: [
                { id: 58651, name: 'ATIRTIR' },
                { id: 62029, name: 'KADO-MON' },
                { id: 62106, name: 'KAGOR' },
                { id: 62662, name: 'KAPIRI' },
                { id: 63636, name: 'KIKELI' },
                { id: 64363, name: 'KUJOL' },
                { id: 65057, name: 'LAMIT CENTRAL' },
                { id: 65058, name: 'LAMIT EAST' },
                { id: 65059, name: 'LAMIT KWEYO' },
                { id: 65060, name: 'LAMIT NORTH' },
                { id: 65061, name: 'LAMIT WEST' },
                { id: 65068, name: 'LAMOO' },
                { id: 65072, name: 'LANG' },
                { id: 66065, name: 'MASAI' },
                { id: 69024, name: 'OMUTU' },
                { id: 71030, name: 'WANG-GOT' },
              ],
            },
            {
              id: 10235,
              name: 'PALUTI',
              villages: [
                { id: 57773, name: 'AKEE' },
                { id: 58401, name: 'APIL CENTRAL' },
                { id: 58402, name: 'APIL EAST' },
                { id: 58403, name: 'APIL RACKOKO' },
                { id: 58404, name: 'APIL WEST' },
                { id: 58948, name: 'BARARA' },
                { id: 59134, name: 'BIWANG' },
                { id: 62652, name: 'KAPEL' },
                { id: 63701, name: 'KILOKOITIO' },
                { id: 63825, name: 'KIRINYA' },
                { id: 64361, name: 'KUDEM' },
                { id: 64430, name: 'KUYWEE CENTRAL' },
                { id: 64431, name: 'KUYWEE EAST' },
                { id: 64432, name: 'KUYWEE SOUTH' },
                { id: 64433, name: 'KUYWEE WEST' },
                { id: 69766, name: 'PWOYO-LALUR' },
              ],
            },
          ],
        },
        {
          id: 334,
          name: 'LAI-MUTTO TOWN COUNCIL',
          parishes: [
            {
              id: 1515,
              name: 'AKWANG WARD',
              villages: [
                { id: 9864, name: 'AGWICIRI' },
                { id: 9865, name: 'AKWANG' },
                { id: 57885, name: 'AKWANG CENTRAL' },
                { id: 9866, name: 'AKWANG WEST' },
                { id: 9867, name: 'ALOI' },
                { id: 9868, name: 'KOPOR' },
                { id: 9869, name: 'LOBIRI' },
                { id: 9870, name: 'LOBIRI CENTRAL' },
                { id: 9871, name: 'LOBUL DISPENSARY' },
              ],
            },
            {
              id: 1516,
              name: 'LAI WARD',
              villages: [
                { id: 9872, name: 'ATILA' },
                { id: 9874, name: 'KOLAKA' },
                { id: 64868, name: 'LABEDO ONGANY' },
                { id: 64916, name: 'LACWAR' },
                { id: 64917, name: 'LACWAR CENTRAL' },
                { id: 64918, name: 'LACWAR EAST' },
                { id: 9873, name: 'LAI CENTRAL' },
                { id: 65233, name: 'LOBIRI EAST' },
              ],
            },
            {
              id: 1517,
              name: 'MUTTO WARD',
              villages: [
                { id: 57613, name: 'AGWICIRI' },
                { id: 61780, name: 'JUBA' },
                { id: 64222, name: 'KOLAKA' },
                { id: 9875, name: 'LACWAR EAST' },
                { id: 64955, name: 'LAI WEST' },
                { id: 9876, name: 'LOBIRI' },
                { id: 9877, name: 'LOBIRI CENTRAL' },
                { id: 65249, name: 'LOBUL DISPENSARY' },
                { id: 69241, name: 'ORYANG' },
              ],
            },
            {
              id: 1518,
              name: 'WIPOLO WARD',
              villages: [
                { id: 9879, name: 'KACO' },
                { id: 67765, name: 'NGORA ODOKOMIT' },
                { id: 69676, name: 'PIDA CENTRAL' },
                { id: 69678, name: 'PIDA EAST' },
                { id: 9878, name: 'PIDA WEST' },
                { id: 9880, name: 'SOLOTI' },
                { id: 70643, name: 'TE-OKIRO' },
                { id: 71159, name: 'WIPOLO' },
                { id: 71161, name: 'WIPOLO SOUTH' },
              ],
            },
          ],
        },
        {
          id: 333,
          name: 'LAPONO',
          parishes: [
            {
              id: 1513,
              name: 'AMYEL',
              villages: [
                { id: 9842, name: 'ABOKO' },
                { id: 9843, name: 'ACHOLINYEK' },
                { id: 9844, name: 'AKENO CENTRAL' },
                { id: 9845, name: 'AKENO EAST' },
                { id: 57779, name: 'AKENO NORTH' },
                { id: 57780, name: 'AKENO SOUTH' },
                { id: 9846, name: 'AKENOWEST' },
                { id: 9847, name: 'ATIMIKICA' },
                { id: 9848, name: 'ATIMIKICA MAIN STORE' },
                { id: 61091, name: 'DANGI' },
                { id: 9849, name: 'KATINI' },
                { id: 9850, name: 'KIZEE' },
                { id: 9851, name: 'LAGAR' },
                { id: 9852, name: 'LATIK' },
              ],
            },
            {
              id: 9552,
              name: 'KAKET',
              villages: [
                { id: 68280, name: 'NYERIKAN SOUTH' },
                { id: 70629, name: 'TE-KANGO SOUTH' },
                { id: 70637, name: 'TE-OBIA' },
              ],
            },
            {
              id: 1512,
              name: 'LIRA-KAKET',
              villages: [
                { id: 9826, name: 'ABILO BOMB' },
                { id: 9827, name: 'ALUMAR' },
                { id: 9828, name: 'KAABONG' },
                { id: 9829, name: 'KARENGA' },
                { id: 9830, name: 'KASESE' },
                { id: 9831, name: 'LACIC EAST' },
                { id: 9839, name: 'LACIC WEST' },
                { id: 9832, name: 'LAPERE CENTRAL' },
                { id: 9833, name: 'LAPERE NORTH' },
                { id: 9834, name: 'LAPERE SOUTH' },
                { id: 9835, name: 'LAYUGI' },
                { id: 9841, name: 'LAYUGI SOUTH' },
                { id: 9836, name: 'LUBIRI' },
                { id: 9837, name: 'NYERIKAN' },
                { id: 9838, name: 'OCOYOLAMERO' },
                { id: 9840, name: 'TEKANGO' },
              ],
            },
            {
              id: 1514,
              name: 'OGOLE',
              villages: [
                { id: 9853, name: 'AYWEE CENTRAL' },
                { id: 9854, name: 'AYWEE TELELA' },
                { id: 9855, name: 'KAKIRA EAST' },
                { id: 62219, name: 'KAKIRA WEST' },
                { id: 9856, name: 'KALANGORE' },
                { id: 9858, name: 'KIPAKA' },
                { id: 9857, name: 'KIPAKA  EAST' },
                { id: 63787, name: 'KIPAKA  WEST' },
                { id: 9859, name: 'LOKIDIA EAST' },
                { id: 65349, name: 'LOKIDIA WEST' },
                { id: 9860, name: 'OGOLE NORTH' },
                { id: 68562, name: 'OGOLE SOUTH' },
                { id: 9861, name: 'OGWANG KAMOLO EAST' },
                { id: 9862, name: 'OGWANG KAMOLO WEST' },
                { id: 9863, name: 'ORUNYA' },
              ],
            },
            {
              id: 10190,
              name: 'ONGALO',
              villages: [
                { id: 57787, name: 'AKIDI' },
                { id: 58217, name: 'AMUTAYI' },
                { id: 59044, name: 'BETHELEM' },
                { id: 61939, name: 'KABONG EAST' },
                { id: 61940, name: 'KABONG WEST' },
                { id: 61963, name: 'KABULUBULU' },
                { id: 64279, name: 'KONGITEM' },
                { id: 64427, name: 'KUWEL' },
                { id: 64900, name: 'LACAN MAK KWERI' },
                { id: 64911, name: 'LACIC EAST' },
                { id: 64912, name: 'LACIC WEST' },
                { id: 69048, name: 'ONGALO EAST' },
                { id: 69049, name: 'ONGALO WEST' },
                { id: 70695, name: 'TELELA' },
              ],
            },
          ],
        },
        {
          id: 336,
          name: 'LIRA KATO',
          parishes: [
            {
              id: 1521,
              name: 'ABILONINO',
              villages: [
                { id: 9900, name: 'ABILONINO' },
                { id: 57166, name: 'ABILONINO AYWEE' },
                { id: 9904, name: 'KADENGOKEE' },
                { id: 9905, name: 'KILAK' },
                { id: 9906, name: 'KILIBI' },
                { id: 9902, name: 'LANYAKWILAABILONINO AYWEE' },
                { id: 9907, name: 'ODOKOMIT' },
                { id: 9901, name: 'ORWEE' },
                { id: 9903, name: 'ORWEE CENTRAL' },
                { id: 9908, name: 'ORYAA' },
              ],
            },
            {
              id: 1522,
              name: 'BIWANG',
              villages: [
                { id: 9909, name: 'ABOKODING B' },
                { id: 9910, name: 'ADAK' },
                { id: 58088, name: 'ALYEM' },
                { id: 9912, name: 'ALYEM NORTH' },
                { id: 9911, name: 'BIWANG' },
                { id: 9913, name: 'JAL-KOMI' },
                { id: 9914, name: 'LADIT OKUN' },
                { id: 9915, name: 'LUNGETEL' },
                { id: 9916, name: 'OBURGULU' },
              ],
            },
            {
              id: 9864,
              name: 'LAPONO-MUK',
              villages: [
                { id: 57861, name: 'AKURI' },
                { id: 57862, name: 'AKURI-NGOTO' },
                { id: 59086, name: 'BILAMITI' },
                { id: 61560, name: 'IDWOG-INONGA' },
                { id: 61752, name: 'JENGKWOT' },
                { id: 61754, name: 'JERUSALEM' },
                { id: 64882, name: 'LABORA' },
                { id: 64885, name: 'LABORA CENTRAL' },
                { id: 64886, name: 'LABORA EAST' },
                { id: 64887, name: 'LABORA TELELA' },
                { id: 67784, name: 'NGWINYKOMI' },
                { id: 69369, name: 'OWIL' },
              ],
            },
            {
              id: 9880,
              name: 'LIRA-KATO',
              villages: [
                { id: 57606, name: 'AGWENG' },
                { id: 58308, name: 'ANINATE' },
                { id: 58733, name: 'AWELO' },
                { id: 58866, name: 'BADMUNU BOR' },
                { id: 64016, name: 'KITELA' },
                { id: 64889, name: 'LABURU CENTRAL' },
                { id: 64890, name: 'LABURU EAST' },
                { id: 64946, name: 'LAGULA' },
                { id: 65117, name: 'LARWE' },
                { id: 68586, name: 'OGUL' },
                { id: 68587, name: 'OGUL CENTRAL' },
                { id: 68597, name: 'OGWAL OWOO' },
                { id: 70681, name: 'TEKATO' },
                { id: 70690, name: 'TEKWORO' },
                { id: 70691, name: 'TEKWORO CENTRAL' },
                { id: 70692, name: 'TEKWORO EAST' },
              ],
            },
          ],
        },
        {
          id: 341,
          name: 'OMIYA PACWA',
          parishes: [
            {
              id: 1542,
              name: 'LAITA',
              villages: [
                { id: 10121, name: 'ABILNINO' },
                { id: 10131, name: 'KAMUK' },
                { id: 10122, name: 'KONGUL' },
                { id: 10123, name: 'LACEKOTO' },
                { id: 10132, name: 'LAMICA' },
                { id: 10124, name: 'LAMINGONEN CENTRAL' },
                { id: 10125, name: 'LAMINGONEN TEGOT' },
                { id: 10126, name: 'LOCKEN' },
                { id: 10136, name: 'LOKOM' },
                { id: 10127, name: 'LONGOR CENTRAL' },
                { id: 10128, name: 'MOROLEM' },
                { id: 10129, name: 'ODOKOMIT' },
                { id: 10133, name: 'ODOKOMIT TEGOT' },
                { id: 10134, name: 'OTUMPILI' },
                { id: 10130, name: 'PAWEL' },
                { id: 10135, name: 'WILYEC' },
              ],
            },
            {
              id: 1543,
              name: 'LAKWA',
              villages: [
                { id: 58066, name: 'ALUMAR' },
                { id: 10137, name: 'KACICIRO EAST' },
                { id: 10138, name: 'KACICIRO WEST' },
                { id: 10139, name: 'KAKELA' },
                { id: 10140, name: 'LABIMA' },
                { id: 10141, name: 'LACIKI' },
                { id: 10142, name: 'LAKWA A' },
                { id: 10143, name: 'LAKWA B' },
                { id: 10144, name: 'LAKWA CENTRAL' },
                { id: 10145, name: 'LAWIYE-ODUNY' },
                { id: 10146, name: 'MUNU OTAM' },
                { id: 10147, name: 'WIGWENG' },
              ],
            },
            {
              id: 1541,
              name: 'LOJIM',
              villages: [
                { id: 10108, name: 'ABICELO' },
                { id: 10109, name: 'ANYWANG-GAI' },
                { id: 10111, name: 'COO-ODONG' },
                { id: 10110, name: 'COO-ODONG NORTH' },
                { id: 10112, name: 'KACICIRO CENTRAL' },
                { id: 10113, name: 'KACICIRO NORTH' },
                { id: 10114, name: 'KATO' },
                { id: 10115, name: 'KILAK' },
                { id: 10116, name: 'KUR MEGI' },
                { id: 10117, name: 'LAPEL MORU' },
                { id: 10118, name: 'LOJIM A' },
                { id: 10119, name: 'LOJIM B' },
                { id: 10120, name: 'MATUKULA' },
              ],
            },
            {
              id: 1544,
              name: 'LOMOI',
              villages: [
                { id: 10148, name: 'ADIO CAI' },
                { id: 10149, name: 'ARUA' },
                { id: 10151, name: 'COO ROM' },
                { id: 10152, name: 'KAKUNG' },
                { id: 10153, name: 'KAMUKA' },
                { id: 10154, name: 'KICUPA' },
                { id: 10155, name: 'LABWOROMOR' },
                { id: 10156, name: 'LAGWEE DOLA' },
                { id: 10157, name: 'LOLIR' },
                { id: 10158, name: 'LOMOI CENTRAL' },
                { id: 10150, name: 'OWINY KI BUL' },
                { id: 10159, name: 'PIKI' },
                { id: 10160, name: 'TEKIRI' },
                { id: 10161, name: 'TEORYANG' },
                { id: 10162, name: 'WII POLO' },
              ],
            },
          ],
        },
        {
          id: 337,
          name: 'PAIMOL',
          parishes: [
            {
              id: 1523,
              name: 'MUTTO',
              villages: [
                { id: 9917, name: 'APIRI' },
                { id: 58532, name: 'ARIWI' },
                { id: 9918, name: 'ARIWII WEST' },
                { id: 58884, name: 'BALANG' },
                { id: 61076, name: 'CWAKOL' },
                { id: 9919, name: 'JUBA' },
                { id: 65123, name: 'LATEBE' },
                { id: 9920, name: 'LELA DWONG' },
                { id: 9921, name: 'LOCUM' },
                { id: 9922, name: 'LOCUM WEST' },
                { id: 66557, name: 'MUKUNGU-TINGA' },
                { id: 9927, name: 'OORA' },
                { id: 9923, name: 'ORYANG' },
                { id: 9924, name: 'SOLOTI' },
                { id: 9925, name: 'TETUGU' },
                { id: 9926, name: 'WIPOLO' },
              ],
            },
            {
              id: 1525,
              name: 'NGORA',
              villages: [
                { id: 9946, name: 'AKURGOBA' },
                { id: 9945, name: 'ARINGA' },
                { id: 9947, name: 'ARINGA EAST' },
                { id: 9944, name: 'AYWEE' },
                { id: 9949, name: 'GOT ATONGO' },
                { id: 9948, name: 'LABEDO OGANY' },
                { id: 9951, name: 'LAI CENTRAL' },
                { id: 9953, name: 'MORA' },
                { id: 9950, name: 'MORA EAST' },
                { id: 9954, name: 'MORA WEST' },
                { id: 9956, name: 'NGORA CENTRAL' },
                { id: 9952, name: 'NGORA EAST' },
                { id: 9955, name: 'NGORA ODOKOMIT' },
                { id: 9957, name: 'TE-OKIRO' },
                { id: 9958, name: 'WAJOLI' },
              ],
            },
            {
              id: 1524,
              name: 'PACABOL',
              villages: [
                { id: 9934, name: 'KAMONOJWII' },
                { id: 9928, name: 'KAMONOJWII EAST' },
                { id: 9929, name: 'KAMONOJWII WEST' },
                { id: 9936, name: 'KOKIL' },
                { id: 9930, name: 'KOKIL WEST' },
                { id: 9937, name: 'KOPIMO' },
                { id: 9938, name: 'LOBOROM' },
                { id: 9939, name: 'LOKAPEL' },
                { id: 9931, name: 'LOKAPEL SOUTH' },
                { id: 9940, name: 'ODOKOMIT' },
                { id: 9941, name: 'OPIRO' },
                { id: 9942, name: 'OPIRO  EAST' },
                { id: 9932, name: 'OPIRO CENTRAL' },
                { id: 9933, name: 'PALOC' },
                { id: 9935, name: 'TONG-WIRI NORTH' },
                { id: 9943, name: 'TONGWIRI' },
              ],
            },
            {
              id: 10308,
              name: 'TAA',
              villages: [
                { id: 57886, name: 'AKWANG WEST' },
                { id: 58047, name: 'ALOMAR' },
                { id: 63174, name: 'KATURUKUK' },
                { id: 63409, name: 'KICANG' },
              ],
            },
          ],
        },
        {
          id: 338,
          name: 'PARABONGO',
          parishes: [
            {
              id: 1526,
              name: 'PABALA',
              villages: [
                { id: 9959, name: 'ABILONINO EAST' },
                { id: 9960, name: 'ABILONINO WEST WARD' },
                { id: 9961, name: 'ABOT' },
                { id: 9970, name: 'ALEDA CENTRAL' },
                { id: 9971, name: 'ALEDA EAST' },
                { id: 9972, name: 'ALEDA SOUTH' },
                { id: 9962, name: 'ALEDA WEST' },
                { id: 9973, name: 'ALELA' },
                { id: 9965, name: 'KONG ITEM' },
                { id: 9964, name: 'KULIR NORTH' },
                { id: 9974, name: 'KULIR SOUTH' },
                { id: 9966, name: 'LADIGO' },
                { id: 9975, name: 'LADIGO SOUTH' },
                { id: 9976, name: 'LANG' },
                { id: 9963, name: 'LOCKEN' },
                { id: 9967, name: 'MANWOKO WARD' },
                { id: 9968, name: 'OLEK WIRE' },
                { id: 9977, name: 'OLYELO WI DYEL' },
                { id: 9978, name: 'OPWONY SOUTH' },
                { id: 9969, name: 'OPWONY WARD' },
                { id: 9979, name: 'RUGU -RUGU' },
              ],
            },
            {
              id: 1528,
              name: 'PACER',
              villages: [
                { id: 10003, name: 'ALOYI' },
                { id: 9992, name: 'ATURA WARD' },
                { id: 10001, name: 'BIWANG' },
                { id: 9994, name: 'BIWANG EAST WARD' },
                { id: 9993, name: 'BUROBIA' },
                { id: 10006, name: 'DOT LAJWA' },
                { id: 9995, name: 'DYERBAR' },
                { id: 10007, name: 'GARAGARA' },
                { id: 9996, name: 'JINJA WARD' },
                { id: 10008, name: 'KARUMA' },
                { id: 9997, name: 'LALWORO ODONG' },
                { id: 9998, name: 'LAPWOMO WARD' },
                { id: 10009, name: 'OLEE' },
                { id: 10004, name: 'OTUMPILI EAST' },
                { id: 9999, name: 'OTUMPILI WARD' },
                { id: 10000, name: 'PALARO WARD' },
                { id: 10002, name: 'WIPOLO WARD' },
                { id: 10005, name: 'YOTKOM' },
              ],
            },
            {
              id: 1529,
              name: 'PAKOR',
              villages: [
                { id: 57781, name: 'AKER' },
                { id: 61185, name: 'DUNG CENTRAL' },
                { id: 10015, name: 'DUNGU' },
                { id: 61187, name: 'DUNGU EAST' },
                { id: 61188, name: 'DUNGU WEST' },
                { id: 61946, name: 'KABOYE' },
                { id: 10016, name: 'KADOKTA' },
                { id: 10017, name: 'KAYORE' },
                { id: 10011, name: 'KENYA' },
                { id: 10018, name: 'KENYA WEST' },
                { id: 10019, name: 'KICUDE' },
                { id: 10010, name: 'PAKOR CENTRAL' },
                { id: 10012, name: 'TE - LAYUGI' },
                { id: 10013, name: 'TEE OKWANG' },
                { id: 10014, name: 'TWON OKUN BUNGU' },
              ],
            },
            {
              id: 1527,
              name: 'PARUMU',
              villages: [
                { id: 9980, name: 'AKER' },
                { id: 9981, name: 'DUNGU EAST' },
                { id: 9982, name: 'DUNGU WEST' },
                { id: 9983, name: 'KABOYE' },
                { id: 9984, name: 'KALE CENTRAL' },
                { id: 9986, name: 'LELA KALE' },
                { id: 9985, name: 'LELA PEE' },
                { id: 9988, name: 'LUZIRA CENTRAL' },
                { id: 9987, name: 'LUZIRA EAST' },
                { id: 9989, name: 'LUZIRA WEST' },
                { id: 9990, name: 'OKER' },
                { id: 9991, name: 'ONGAM' },
                { id: 69050, name: 'ONGAM EAST' },
              ],
            },
          ],
        },
        {
          id: 339,
          name: 'WOL',
          parishes: [
            {
              id: 1530,
              name: 'KIMIYA',
              villages: [
                { id: 10020, name: 'ARUA' },
                { id: 10021, name: 'ATAA' },
                { id: 61954, name: 'KABUKA' },
                { id: 10027, name: 'KADINGA' },
                { id: 10023, name: 'KAMIN-OLAL' },
                { id: 10024, name: 'KUDANGA' },
                { id: 10022, name: 'LELA KUKU' },
                { id: 10025, name: 'OTINGOWIYE' },
                { id: 71041, name: 'WANGBONE' },
                { id: 10026, name: 'WILIWILI' },
              ],
            },
            {
              id: 1531,
              name: 'LOKABAR',
              villages: [
                { id: 10028, name: 'ATENE' },
                { id: 10031, name: 'KAPIRI' },
                { id: 63665, name: 'KIKORE' },
                { id: 10033, name: 'LOKABAR CENTRAL' },
                { id: 10034, name: 'LOKABAR EAST' },
                { id: 10029, name: 'LOKABAR SOUTH' },
                { id: 10035, name: 'LOKABAR WEST' },
                { id: 10037, name: 'MOYO' },
                { id: 10030, name: 'ODIKO' },
                { id: 10032, name: 'OGILI' },
                { id: 10036, name: 'OKUKA' },
              ],
            },
            {
              id: 9926,
              name: 'LUGUNG',
              villages: [
                { id: 62572, name: 'KANYAKUC' },
                { id: 65606, name: 'LUGUNG' },
              ],
            },
            {
              id: 1533,
              name: 'LUGUNGU',
              villages: [
                { id: 10049, name: 'ADYEBA' },
                { id: 10050, name: 'AYOM-BONO' },
                { id: 10048, name: 'KATONGO - TUT' },
                { id: 10051, name: 'LANGIYA' },
                { id: 10052, name: 'LUGILA' },
                { id: 10053, name: 'OWILE' },
                { id: 10054, name: 'ROGO CENTRAL' },
              ],
            },
            {
              id: 1535,
              name: 'MURA',
              villages: [
                { id: 10067, name: 'ARIKA' },
                { id: 10068, name: 'AYAGO' },
                { id: 10069, name: 'GOT-COL' },
                { id: 10072, name: 'JOLO' },
                { id: 10070, name: 'KABALA JUBA' },
                { id: 10071, name: 'LABILOKWIL' },
                { id: 10074, name: 'LAGUTI' },
                { id: 10073, name: 'LAMONOJWI' },
                { id: 65453, name: 'LONDON' },
                { id: 10075, name: 'NGORA EAST' },
                { id: 10076, name: 'NGORA WEST' },
                { id: 68526, name: 'ODWENG' },
                { id: 10078, name: 'OLEK-WIRE' },
                { id: 10077, name: 'OLEK-WIRE CENTRAL' },
              ],
            },
            {
              id: 1534,
              name: 'OGOLE',
              villages: [
                { id: 10055, name: 'KABUL' },
                { id: 10065, name: 'KARIDO' },
                { id: 10057, name: 'KATONOTUT' },
                { id: 10059, name: 'KUDETA' },
                { id: 10058, name: 'KUPUNGA' },
                { id: 10056, name: 'LAYADA' },
                { id: 10060, name: 'LULA-OMUKA' },
                { id: 65675, name: 'LUPWA' },
                { id: 10066, name: 'NAMBWAC' },
                { id: 10061, name: 'OWIC' },
                { id: 10062, name: 'PAIWAK' },
                { id: 10063, name: 'PANYAGOL' },
                { id: 10064, name: 'PANYAGOL WEST' },
                { id: 70888, name: 'TWARALYEC' },
                { id: 71128, name: 'WIGWENG' },
              ],
            },
            {
              id: 1532,
              name: 'ROGO',
              villages: [
                { id: 10038, name: 'ACUT - OMER' },
                { id: 10039, name: 'KAMDINI' },
                { id: 62571, name: 'KANYAKOYO' },
                { id: 10041, name: 'LAJORO' },
                { id: 10046, name: 'LOGILA' },
                { id: 10047, name: 'LUKUDA' },
                { id: 10042, name: 'NYANZA EAST' },
                { id: 10043, name: 'NYANZA WEST' },
                { id: 10044, name: 'ODOKOMIT' },
                { id: 10045, name: 'OKWADOKO' },
                { id: 69485, name: 'PAIWAK' },
                { id: 10040, name: 'PALUNGURA' },
              ],
            },
          ],
        },
        {
          id: 332,
          name: 'WOL TOWN COUNCIL',
          parishes: [
            {
              id: 1511,
              name: 'GUDA WARD',
              villages: [
                { id: 9822, name: 'BAR DEGE' },
                { id: 60207, name: 'BUR GWENG' },
                { id: 9825, name: 'DAGO PANY' },
                { id: 9824, name: 'JUBA' },
                { id: 65746, name: 'LWALA' },
                { id: 69657, name: 'PECE' },
                { id: 9823, name: 'WOL CENTRAL' },
              ],
            },
            {
              id: 1508,
              name: 'KICO WARD',
              villages: [
                { id: 9807, name: 'ABULUKWANG' },
                { id: 9808, name: 'ABULUKWANG WEST' },
                { id: 9810, name: 'DAGO OLUNG' },
                { id: 61147, name: 'DOG TANGI' },
                { id: 61148, name: 'DOG TANGI SOUTH' },
                { id: 61420, name: 'GOTCOL' },
                { id: 9811, name: 'KENYA' },
                { id: 9809, name: 'KICO' },
                { id: 9812, name: 'LULA' },
              ],
            },
            {
              id: 1509,
              name: 'LUBANYA WARD',
              villages: [
                { id: 9813, name: 'KOPINO' },
                { id: 9816, name: 'LAKOBA CENTRAL' },
                { id: 9814, name: 'LAKOBA EAST' },
                { id: 65567, name: 'LUBANYA' },
                { id: 65568, name: 'LUBANYA NORTH' },
                { id: 65569, name: 'LUBANYA WEST' },
                { id: 9815, name: 'OLEKE' },
                { id: 71027, name: 'WANG LAGER' },
              ],
            },
            {
              id: 1510,
              name: 'PANYAGOL WARD',
              villages: [
                { id: 9820, name: 'KABUL' },
                { id: 9817, name: 'LUTOME' },
                { id: 68607, name: 'OGWIL' },
                { id: 9818, name: 'OWICH' },
                { id: 9819, name: 'PANYAGOL' },
                { id: 69595, name: 'PANYAGOL CENTRAL' },
                { id: 69596, name: 'PANYAGOL WEST' },
                { id: 9821, name: 'WANG OLAL' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
