import { District } from '../index';

export default {
  id: 85,
  name: 'AMOLATAR',
  counties: [
    {
      id: 212,
      name: 'KIOGA COUNTY',
      sub_counties: [
        {
          id: 1332,
          name: 'ABEJA',
          parishes: [
            {
              id: 6257,
              name: 'ABEJA',
              villages: [
                { id: 39384, name: 'ABEJA' },
                { id: 57264, name: 'ABUR' },
                { id: 57513, name: 'ADYEDA' },
                { id: 57720, name: 'AKALI' },
                { id: 58231, name: 'ANAMOLOI' },
                { id: 58419, name: 'APOKGOR' },
                { id: 58945, name: 'BARAMYEM' },
                { id: 39385, name: 'LWALA' },
                { id: 39386, name: 'OKILE' },
                { id: 68757, name: 'OKWOR' },
                { id: 69402, name: 'OYIMA' },
              ],
            },
            {
              id: 6256,
              name: 'AKOL',
              villages: [
                { id: 39383, name: 'ADYEL' },
                { id: 39378, name: 'AGENGI' },
                { id: 57772, name: 'AKEDI' },
                { id: 39379, name: 'AKEKETO' },
                { id: 39380, name: 'ALAC' },
                { id: 39381, name: 'ANGETA' },
                { id: 39382, name: 'APENYOWEO' },
                { id: 58472, name: 'AREGI' },
              ],
            },
            {
              id: 6259,
              name: 'ARINGO CENG',
              villages: [
                { id: 57834, name: 'AKOT' },
                { id: 58025, name: 'ALITO' },
                { id: 39391, name: 'ANGEC' },
                { id: 39392, name: 'ARINGO CENG' },
                { id: 58517, name: 'ARINGOCENG' },
                { id: 60237, name: 'BURLOBO' },
                { id: 39393, name: 'BURUBURU' },
              ],
            },
            {
              id: 6260,
              name: 'LUBIRI',
              villages: [
                { id: 39394, name: 'ANAMOLOI  B' },
                { id: 58232, name: 'ANAMOLOLI A' },
                { id: 39395, name: 'BARIORO' },
                { id: 39396, name: 'GEE' },
                { id: 65576, name: 'LUBIRI' },
              ],
            },
            {
              id: 6258,
              name: 'OTANGOCINGE',
              villages: [
                { id: 57247, name: 'ABUJE' },
                { id: 39388, name: 'ACANOKUN' },
                { id: 39389, name: 'ADAGANIKE' },
                { id: 58371, name: 'APARANGO' },
                { id: 39390, name: 'LWALA' },
                { id: 68310, name: 'OBALO' },
                { id: 39387, name: 'OTANGOCINGE' },
              ],
            },
          ],
        },
        {
          id: 1333,
          name: 'ACII',
          parishes: [
            {
              id: 6261,
              name: 'ACII',
              villages: [
                { id: 39397, name: 'ALAKU' },
                { id: 58726, name: 'AWEIOTAL' },
                { id: 58729, name: 'AWEIWOT' },
                { id: 64296, name: 'KONYA' },
                { id: 64426, name: 'KUWEIT' },
                { id: 39398, name: 'KWOYO' },
                { id: 69211, name: 'OROMOBUTO' },
              ],
            },
            {
              id: 6263,
              name: 'ALWALA',
              villages: [
                { id: 39402, name: 'ALWALA' },
                { id: 58143, name: 'AMINAMOSI' },
                { id: 39404, name: 'ATOLIT' },
                { id: 58782, name: 'AWORA' },
                { id: 39403, name: 'LEMO' },
              ],
            },
            {
              id: 6262,
              name: 'AWIKORI',
              villages: [
                { id: 39400, name: 'ACENGORYEMA' },
                { id: 57458, name: 'ADOLE' },
                { id: 39401, name: 'ATOPI' },
                { id: 58753, name: 'AWIKORI' },
                { id: 39399, name: 'OKELLOONGENY' },
              ],
            },
            {
              id: 6264,
              name: 'KONGORO',
              villages: [
                { id: 57360, name: 'ACII' },
                { id: 58947, name: 'BARAPWOL' },
                { id: 39407, name: 'BAROBWOL' },
                { id: 39405, name: 'KIRYANGA' },
                { id: 39406, name: 'KONGORO' },
                { id: 69680, name: 'PIG AWENO' },
              ],
            },
            {
              id: 6265,
              name: 'MUCHORA',
              villages: [
                { id: 39408, name: 'ABINO A' },
                { id: 39409, name: 'ABINO B' },
                { id: 58514, name: 'ARINGO BANYA' },
                { id: 58672, name: 'ATUR' },
                { id: 58961, name: 'BARIMIR' },
                { id: 65244, name: 'LOBOROM' },
                { id: 39410, name: 'MUCHORA' },
                { id: 69267, name: 'OSOMOLI' },
              ],
            },
            {
              id: 6266,
              name: 'OTIKE',
              villages: [
                { id: 57164, name: 'ABILONINO' },
                { id: 57213, name: 'ABOLONYERO' },
                { id: 58745, name: 'AWIDAGO' },
                { id: 39411, name: 'OTIKE' },
              ],
            },
          ],
        },
        {
          id: 1325,
          name: 'AGIKDAK',
          parishes: [
            {
              id: 6224,
              name: 'ABARIKORI',
              villages: [
                { id: 39182, name: 'ABARI KORI' },
                { id: 39183, name: 'ACWALI' },
                { id: 39184, name: 'ALUM YOMI WANGI' },
                { id: 39185, name: 'AMORMITIMOGO' },
                { id: 39186, name: 'OBURA' },
              ],
            },
            {
              id: 6222,
              name: 'AGIKDAK',
              villages: [
                { id: 39166, name: 'ACAPA' },
                { id: 39167, name: 'ADYANG MIT' },
                { id: 39168, name: 'AGIKDAK' },
                { id: 39169, name: 'ANYAPO' },
                { id: 39170, name: 'AWEKI RYEKO' },
                { id: 39171, name: 'ONENO MAC' },
                { id: 39172, name: 'ONGO CENG' },
                { id: 39173, name: 'ORIBCING' },
                { id: 39174, name: 'OTWONAOLEL' },
              ],
            },
            {
              id: 6225,
              name: 'ALOBO-OKWE',
              villages: [
                { id: 39187, name: 'ACAN MAK KWERI' },
                { id: 39188, name: 'ADAGANI' },
                { id: 39189, name: 'AKOPLOKEDI' },
                { id: 39190, name: 'AKWOTE' },
                { id: 39191, name: 'ALEBLEE' },
                { id: 39192, name: 'ALOBO-OKWE' },
                { id: 39193, name: 'ALWITLONGO' },
                { id: 39194, name: 'AWIDAKO OWIL' },
                { id: 39195, name: 'OLINGAMUK' },
              ],
            },
            {
              id: 6223,
              name: 'AWONANGIRO',
              villages: [
                { id: 39175, name: 'AKOO' },
                { id: 39177, name: 'ATERI CIP' },
                { id: 39178, name: 'AWILWALA' },
                { id: 39179, name: 'AWONANGIRO' },
                { id: 39180, name: 'KOMORA' },
                { id: 39181, name: 'OTURO RAO A' },
                { id: 39176, name: 'OTURO RAO B' },
              ],
            },
          ],
        },
        {
          id: 1326,
          name: 'AGWINGIRI',
          parishes: [
            {
              id: 6229,
              name: 'ACOTEDO',
              villages: [
                { id: 57297, name: 'ACAN LOLE' },
                { id: 39214, name: 'ACOTEDO' },
                { id: 39212, name: 'AKOK OKOT' },
                { id: 39213, name: 'AWEIPEKO' },
                { id: 61116, name: 'DICUNYI' },
                { id: 39216, name: 'OMUKOWIE' },
                { id: 39215, name: 'ORIBCAN' },
              ],
            },
            {
              id: 6228,
              name: 'AGWINGIRI',
              villages: [
                { id: 39207, name: 'ABOLONYERO' },
                { id: 39206, name: 'AGWINGIRI' },
                { id: 39208, name: 'AMAKIKWERI' },
                { id: 39209, name: 'BEDIGEN' },
                { id: 39210, name: 'DIBADI' },
                { id: 39211, name: 'OLAKE' },
              ],
            },
            {
              id: 6226,
              name: 'ALEMERE',
              villages: [
                { id: 57250, name: 'ABUKUTU' },
                { id: 39196, name: 'ABUTO-TARO  A' },
                { id: 39197, name: 'AWIGWENG' },
                { id: 39198, name: 'FARM T C' },
                { id: 39200, name: "KIZIMBA 'A'" },
                { id: 39199, name: 'OLAKE' },
                { id: 68905, name: 'OMARA EBEK' },
              ],
            },
            {
              id: 6230,
              name: 'ALEMERE WEST',
              villages: [
                { id: 39218, name: 'ABARILOP' },
                { id: 39217, name: 'ALARO' },
                { id: 39219, name: 'AMINANGOM' },
                { id: 58469, name: 'ARATI' },
                { id: 39221, name: "KIZIMBA 'B'" },
                { id: 39220, name: 'OULO' },
              ],
            },
            {
              id: 6227,
              name: 'ALYECMEDA',
              villages: [
                { id: 39201, name: 'ABAKO' },
                { id: 57114, name: 'ABAKO-ATIDI TC' },
                { id: 39202, name: 'ACENGORYEMA' },
                { id: 39204, name: "AKURI 'B'" },
                { id: 39203, name: 'BARAYOM' },
                { id: 39205, name: 'OBAGO' },
                { id: 68690, name: 'OKOK' },
                { id: 69362, name: 'OWEE' },
                { id: 70663, name: 'TEDAM' },
              ],
            },
            {
              id: 6231,
              name: 'ANYWAL WAKE',
              villages: [
                { id: 57408, name: 'ADAGKWAC' },
                { id: 39222, name: 'AKAIDEBE' },
                { id: 39225, name: 'ALYECMEDA' },
                { id: 39223, name: 'ANYWAWAKE' },
                { id: 39224, name: 'AWIGWENG' },
                { id: 39226, name: 'BARONGER' },
                { id: 59023, name: 'BEDIWORO' },
              ],
            },
            {
              id: 6232,
              name: 'NAMIZA',
              villages: [
                { id: 39227, name: 'AKANYO AOL' },
                { id: 39228, name: "AKURI 'A'" },
                { id: 39229, name: 'BE IWEE' },
                { id: 60159, name: 'BUNG' },
                { id: 64117, name: 'KITWE' },
                { id: 39231, name: 'NAMIZA' },
                { id: 39230, name: 'ODEOGWOK' },
                { id: 68899, name: 'OMALE' },
              ],
            },
          ],
        },
        {
          id: 1327,
          name: 'AKWON',
          parishes: [
            {
              id: 6234,
              name: 'ABALODYANG',
              villages: [
                { id: 39238, name: 'ABALODYANG' },
                { id: 39239, name: 'ABEDOBER' },
                { id: 39240, name: 'ADAGANGINYA' },
                { id: 39241, name: 'ADYANG OKET' },
                { id: 39242, name: 'AGENGERE' },
                { id: 39243, name: 'AJENGI' },
                { id: 39244, name: 'ALERI' },
                { id: 39245, name: 'ATALI' },
                { id: 39246, name: 'OBALO WAT' },
                { id: 39247, name: 'OCAMO YAT' },
              ],
            },
            {
              id: 6233,
              name: 'AKWON',
              villages: [
                { id: 39232, name: 'ANAM ODUMO' },
                { id: 39235, name: 'ATIN OMANO' },
                { id: 39233, name: 'ATWEYI' },
                { id: 39236, name: 'AWIGWENG' },
                { id: 39234, name: 'AWIGWENG CENTRAL' },
                { id: 39237, name: 'AWINYI DWON' },
              ],
            },
            {
              id: 6235,
              name: 'AROMI',
              villages: [
                { id: 39248, name: 'ACAEOGIK' },
                { id: 39249, name: 'ACOOROMO' },
                { id: 39250, name: 'ADITA A' },
                { id: 39252, name: 'ADITA B' },
                { id: 39251, name: 'ADOG MON MIO' },
                { id: 39253, name: 'AROMI' },
                { id: 39254, name: 'ARWOTOKUN' },
                { id: 39255, name: 'AWIA WEE' },
              ],
            },
            {
              id: 6236,
              name: 'OKIJI',
              villages: [
                { id: 39257, name: 'ANYOMCAN' },
                { id: 39258, name: 'ANYUKA' },
                { id: 39259, name: 'APUM' },
                { id: 39256, name: 'OKIJI' },
                { id: 39260, name: 'ONANGO OGWECO' },
                { id: 39261, name: 'OWIRI' },
              ],
            },
          ],
        },
        {
          id: 1324,
          name: 'AMOLATAR TOWN COUNCIL',
          parishes: [
            {
              id: 6217,
              name: 'ABURKOT WARD',
              villages: [
                { id: 39148, name: 'ABURKOT' },
                { id: 39149, name: 'ALEMERE BUNG' },
                { id: 39150, name: 'ARWOTOKWE' },
              ],
            },
            {
              id: 6221,
              name: 'AMIRIMIRI WARD',
              villages: [
                { id: 39163, name: 'AMIRIMIRI' },
                { id: 39164, name: "AUNGA 'A'" },
                { id: 39165, name: "AUNGA 'B'" },
                { id: 39162, name: 'ORYAMAI' },
              ],
            },
            {
              id: 6218,
              name: 'APALE PE WARD',
              villages: [
                { id: 39151, name: "AMOLATAR HEADQUARTERS 'A'" },
                { id: 39152, name: 'APALE PE' },
                { id: 39153, name: 'APOKOMITIMOGO A' },
                { id: 39154, name: 'ODONGJWIYO' },
              ],
            },
            {
              id: 6219,
              name: 'EPYEL WARD',
              villages: [
                { id: 39155, name: 'ALEMERE MISSION' },
                { id: 39156, name: 'ALEMERE TRADING CENTRE' },
                { id: 39157, name: 'EPYEL' },
              ],
            },
            {
              id: 6220,
              name: 'INOMO WARD',
              villages: [
                { id: 39161, name: "AMOLATAR HEADQUARTERS 'B'" },
                { id: 39158, name: 'CORNER APUTI' },
                { id: 39159, name: 'INOMO' },
                { id: 39160, name: 'ORIMAI' },
              ],
            },
          ],
        },
        {
          id: 1322,
          name: 'APUTI',
          parishes: [
            {
              id: 6209,
              name: 'ALYET',
              villages: [
                { id: 39091, name: 'ALID OWAO PING' },
                { id: 39092, name: 'ALYET' },
                { id: 39093, name: 'ANYAKO OLANA' },
                { id: 58708, name: 'AWANYI' },
                { id: 39094, name: 'OLONGO PING' },
              ],
            },
            {
              id: 6208,
              name: 'AMAI',
              villages: [
                { id: 39085, name: 'ABIEMEDI' },
                { id: 39086, name: "ADING 'A'" },
                { id: 39087, name: "ADING 'B'" },
                { id: 57441, name: 'ADING C' },
                { id: 39089, name: 'AGULE' },
                { id: 39090, name: 'AMAI' },
                { id: 58093, name: 'AMAI B' },
                { id: 39088, name: 'AWIJOBI' },
              ],
            },
            {
              id: 6207,
              name: 'ANYWALI',
              villages: [
                { id: 39080, name: 'ACAN DYANG' },
                { id: 57418, name: 'ADAK-NYEKO' },
                { id: 39081, name: 'ADYANG ODEO' },
                { id: 39082, name: 'AERO NYERO' },
                { id: 59020, name: 'BEDAMWOL' },
                { id: 68673, name: 'OKELLO KUC' },
                { id: 39083, name: 'OLONG-KONGO' },
                { id: 39084, name: "OTIMAI 'A'" },
              ],
            },
            {
              id: 6210,
              name: 'AWINYIPANY',
              villages: [
                { id: 39095, name: 'ABUR KEC' },
                { id: 39096, name: 'AWINYIPANY' },
                { id: 58771, name: 'AWINYIPANY B' },
                { id: 39097, name: 'AYIA PE IYE' },
                { id: 68572, name: 'OGONYO-WORO' },
                { id: 69076, name: 'ONOO' },
                { id: 39098, name: 'TO OBALO DEO' },
              ],
            },
            {
              id: 6211,
              name: 'OBOTO MOO',
              villages: [
                { id: 39100, name: 'ACABA' },
                { id: 57289, name: 'ACABA B' },
                { id: 39101, name: 'ADWILA' },
                { id: 58397, name: 'APII' },
                { id: 39102, name: 'OBOTO MOO' },
                { id: 68373, name: 'OBOTO MOO B' },
                { id: 39099, name: 'OTIMAI B' },
              ],
            },
          ],
        },
        {
          id: 1328,
          name: 'ARWOTCEK',
          parishes: [
            {
              id: 6239,
              name: 'ABURKIDI',
              villages: [
                { id: 39274, name: 'ABURKIDI' },
                { id: 39275, name: 'AGOGA' },
                { id: 39278, name: 'ANGAYIKI' },
                { id: 39279, name: 'ARIBI A' },
                { id: 39276, name: 'ARWOT OMIO' },
                { id: 39280, name: 'AWEKABOKO' },
                { id: 39277, name: 'OJAM' },
                { id: 39281, name: 'OMULAI' },
              ],
            },
            {
              id: 6237,
              name: 'ABWONG',
              villages: [
                { id: 39262, name: 'ABWONGIPINY' },
                { id: 57283, name: 'ABWONGIPINY A' },
                { id: 39263, name: 'ABWONGIPINY B' },
                { id: 39264, name: 'ALINGA B' },
                { id: 58079, name: 'ALUTMIT' },
                { id: 39265, name: 'ATABOBALE' },
                { id: 71169, name: 'WITUR' },
              ],
            },
            {
              id: 6238,
              name: 'ARWOTCEK',
              villages: [
                { id: 39267, name: 'ABEDOBER' },
                { id: 39266, name: 'ABONGO-OLO' },
                { id: 39268, name: 'ACOGOREC' },
                { id: 39270, name: 'ALELANGAO' },
                { id: 39269, name: 'ARWOTCEK' },
                { id: 39271, name: 'AWIGENG' },
                { id: 39272, name: 'ONGUDUANANGA' },
                { id: 39273, name: 'OPIROWIE' },
              ],
            },
            {
              id: 6240,
              name: 'AWAC',
              villages: [
                { id: 57208, name: 'ABOLOKOMA' },
                { id: 39282, name: 'ADYANGLIT' },
                { id: 39283, name: 'ANGWALOJERI' },
                { id: 39284, name: 'ATURA' },
                { id: 39285, name: 'AWAC' },
                { id: 39286, name: 'ODOKODERO' },
              ],
            },
            {
              id: 6241,
              name: 'AYAMAWELE',
              villages: [
                { id: 39287, name: 'AGWEI' },
                { id: 39289, name: 'ARIBI B' },
                { id: 39292, name: 'AYAMAWELE' },
                { id: 39288, name: 'BARAJAN' },
                { id: 39290, name: 'OGO-NYOLO' },
                { id: 39293, name: 'OKANOKONGO A' },
                { id: 39291, name: 'OKANOKONGO B' },
              ],
            },
            {
              id: 6242,
              name: 'OGENGA',
              villages: [
                { id: 57133, name: 'ABARAGUC' },
                { id: 39294, name: 'ABAROCAO' },
                { id: 39295, name: 'AGALO A' },
                { id: 57533, name: 'AGALO B' },
                { id: 39296, name: 'ALINGA A' },
                { id: 39297, name: 'OGENGA' },
              ],
            },
            {
              id: 6243,
              name: 'OJEM',
              villages: [
                { id: 39301, name: 'ADEKNINO' },
                { id: 39299, name: 'AGWENONYWAL' },
                { id: 39298, name: 'APII' },
                { id: 39300, name: 'BAROLIMO' },
                { id: 39304, name: 'OBALO PII' },
                { id: 39302, name: 'OCELAKUR' },
                { id: 39305, name: 'OJEM' },
                { id: 39303, name: 'OTITI' },
              ],
            },
          ],
        },
        {
          id: 1323,
          name: 'AWELLO',
          parishes: [
            {
              id: 6212,
              name: 'AKONGOMIT',
              villages: [
                { id: 39103, name: 'ABALI' },
                { id: 39104, name: 'ABONGOLWORO' },
                { id: 39106, name: 'ADWALA' },
                { id: 39107, name: 'ADYANGOBARO' },
                { id: 39108, name: 'AKONGOMIT' },
                { id: 39105, name: 'AKORE MOR' },
                { id: 39109, name: 'ALONGOTIDI' },
                { id: 39110, name: 'ALWIT' },
                { id: 39111, name: 'AORNGA' },
                { id: 39113, name: 'BARAJANGA' },
                { id: 39112, name: 'OTUROLAKODAL' },
              ],
            },
            {
              id: 6213,
              name: 'ANAMWANY',
              villages: [
                { id: 39115, name: 'ACAMANONO' },
                { id: 39116, name: 'ADAKOGIK' },
                { id: 39114, name: 'AMOKWEE' },
                { id: 39117, name: "ANAMWANY 'A'" },
                { id: 39118, name: "ANAMWANY 'B'" },
                { id: 39119, name: 'ARYEI' },
                { id: 39120, name: 'ATINGI' },
              ],
            },
            {
              id: 6215,
              name: 'ATERO',
              villages: [
                { id: 39131, name: 'ABURKOT' },
                { id: 39129, name: 'ADWONGOLANA' },
                { id: 39135, name: 'ARINGORWOT' },
                { id: 39136, name: 'ATERO' },
                { id: 39130, name: 'ELANY' },
                { id: 39132, name: 'OCAMONYANGA' },
                { id: 39137, name: 'ODEOGWOK' },
                { id: 39138, name: 'ODONGOYERE' },
                { id: 39133, name: 'ODONGOYERE TRADING CENTRE' },
                { id: 39139, name: 'OKETOCEN' },
                { id: 39134, name: 'TURELWANO' },
              ],
            },
            {
              id: 6214,
              name: 'ATOMORO',
              villages: [
                { id: 39121, name: 'ABWOC YIKEC' },
                { id: 39123, name: 'AGENO OBANGA' },
                { id: 39124, name: 'AGONYI' },
                { id: 39125, name: 'AJOKONYWAL' },
                { id: 39126, name: 'ALOBOKET' },
                { id: 39127, name: 'ANEBENEBE' },
                { id: 39128, name: 'ATOMORO' },
                { id: 39122, name: 'DILIKUP' },
              ],
            },
            {
              id: 6216,
              name: 'ODYEDO',
              villages: [
                { id: 39140, name: 'ABEDOBER' },
                { id: 39141, name: 'ADYELODEO' },
                { id: 39143, name: 'AGIRIKACA' },
                { id: 39144, name: 'AKUKURU' },
                { id: 39145, name: 'APAGI' },
                { id: 39146, name: 'ATANGI' },
                { id: 39142, name: 'AWELLO' },
                { id: 39147, name: 'ODYEDO' },
              ],
            },
          ],
        },
        {
          id: 1329,
          name: 'ETAM',
          parishes: [
            {
              id: 6245,
              name: 'ABWOCKWAR',
              villages: [
                { id: 39315, name: 'ABEDMOT' },
                { id: 39316, name: 'ABWOCKWAR' },
                { id: 39317, name: 'ADAGANI' },
                { id: 39319, name: 'ALWAR' },
                { id: 39320, name: 'ANYWALI' },
                { id: 39318, name: 'ARWOT' },
                { id: 39321, name: 'ATIMAKICA' },
                { id: 39322, name: 'OJUL' },
                { id: 39323, name: 'TUROKANGO' },
              ],
            },
            {
              id: 6244,
              name: 'ANAMIDO',
              villages: [
                { id: 39308, name: 'ADERO' },
                { id: 39306, name: 'ALOBOKWE' },
                { id: 39309, name: 'AMAKIKOMA' },
                { id: 39310, name: 'ANAKANENI' },
                { id: 39311, name: 'ANAMIDO' },
                { id: 39312, name: 'ANYIKI' },
                { id: 39313, name: 'AWEIWOT' },
                { id: 39307, name: 'OBANGABER' },
                { id: 39314, name: 'OWEOYIE' },
              ],
            },
            {
              id: 6246,
              name: 'AWIODYEK',
              villages: [
                { id: 39324, name: 'ABWOCCOL' },
                { id: 39325, name: 'ACAMCUTU' },
                { id: 39326, name: 'ACOLAM' },
                { id: 39327, name: 'AMOMIT' },
                { id: 39328, name: 'AORNGA' },
                { id: 39329, name: 'AWIODYEK' },
                { id: 39330, name: 'BARRKWOYO' },
                { id: 39331, name: 'OKUROWIE' },
              ],
            },
          ],
        },
        {
          id: 1331,
          name: 'ETAM TOWN COUNCIL',
          parishes: [
            {
              id: 6253,
              name: 'ADUM WARD',
              villages: [
                { id: 39361, name: 'ADUM' },
                { id: 39362, name: 'AJOKDONG' },
                { id: 58045, name: 'ALOKIWINYO' },
                { id: 39363, name: 'AMONOLOCO' },
                { id: 39364, name: 'NAMABERE' },
                { id: 69377, name: 'OWIRI' },
                { id: 70609, name: 'TE ATOKE' },
              ],
            },
            {
              id: 6255,
              name: 'ALARO WARD',
              villages: [
                { id: 57430, name: 'ADEROLONGO' },
                { id: 39373, name: 'ALARO' },
                { id: 39374, name: 'AMONOLOCO' },
                { id: 58618, name: 'ATEDNGO' },
                { id: 39375, name: 'ETAM A' },
                { id: 39376, name: 'ETAM B' },
                { id: 39377, name: "OTURORAO 'A'" },
              ],
            },
            {
              id: 6254,
              name: 'ARWOT WARD',
              villages: [
                { id: 39369, name: 'AMUK' },
                { id: 58202, name: 'AMULE' },
                { id: 39365, name: 'ANGIC' },
                { id: 39370, name: 'APIDYANG' },
                { id: 39371, name: 'ARWAKERE' },
                { id: 39367, name: 'ARWOT A' },
                { id: 39366, name: 'ARWOT B' },
                { id: 39372, name: 'DAM' },
                { id: 64275, name: 'KONG ILATO' },
                { id: 39368, name: 'OTONGODYEL' },
                { id: 71130, name: 'WIGWENG' },
              ],
            },
            {
              id: 6251,
              name: 'CHAKWARA WARD',
              villages: [
                { id: 39352, name: 'AGAMOTIC' },
                { id: 39355, name: 'ANGAYIKI' },
                { id: 39356, name: 'CANOLOA' },
                { id: 39357, name: 'KITALA' },
                { id: 68547, name: 'OGENGO' },
                { id: 39353, name: 'OKADE' },
                { id: 39354, name: 'WIGWENG' },
              ],
            },
            {
              id: 6252,
              name: 'ETAM WARD',
              villages: [
                { id: 57262, name: 'ABUR' },
                { id: 58750, name: 'AWIDYEGI' },
                { id: 58995, name: 'BAROWALO' },
                { id: 39358, name: 'OKWOR' },
                { id: 39359, name: 'OLELPEK' },
                { id: 39360, name: "OTURORAO 'B'" },
              ],
            },
          ],
        },
        {
          id: 1321,
          name: 'MUNTU',
          parishes: [
            {
              id: 6204,
              name: 'ABARLER',
              villages: [
                { id: 39058, name: 'ADYANGLIT' },
                { id: 39059, name: 'AGWENOPETONGOTING' },
                { id: 39060, name: 'ALUMYOMIWANGI' },
                { id: 39061, name: "APOK MITIMOGO 'B'" },
                { id: 39062, name: "APOK MITIMOGO 'C'" },
                { id: 39063, name: 'OWIRI' },
              ],
            },
            {
              id: 6205,
              name: 'KABANGALA',
              villages: [
                { id: 39071, name: 'ABALER B' },
                { id: 39066, name: 'ACUTCAMI A' },
                { id: 39065, name: 'ACUTCAMI B' },
                { id: 39067, name: 'BARILWA A' },
                { id: 39068, name: 'BARILWA B' },
                { id: 39069, name: 'KABANGALA' },
                { id: 39070, name: 'MUNTU MWALU' },
                { id: 39064, name: 'MUNTU TOWNSHIP' },
              ],
            },
            {
              id: 6202,
              name: 'MUNTU',
              villages: [
                { id: 39042, name: 'ABARLER   A' },
                { id: 39050, name: 'ACUTCAMI  C' },
                { id: 39043, name: 'AGENORWOT' },
                { id: 39044, name: 'ALII' },
                { id: 39045, name: 'ATONG PARO' },
                { id: 39046, name: 'AWERCEK' },
                { id: 39047, name: 'BAROKUTO' },
                { id: 39048, name: 'NAKITUBA A' },
                { id: 39049, name: 'NAKITUBA B' },
              ],
            },
            {
              id: 6203,
              name: 'NAKATITI',
              villages: [
                { id: 39051, name: 'AGULE' },
                { id: 39053, name: "KITALEBA 'A'" },
                { id: 39054, name: "KITALEBA 'B'" },
                { id: 39055, name: 'NABYAITA' },
                { id: 39056, name: 'NAKATITI' },
                { id: 39057, name: 'RWANZOGI A' },
                { id: 39052, name: 'RWANZOGI B' },
              ],
            },
            {
              id: 6206,
              name: 'ODIAK',
              villages: [
                { id: 39072, name: 'AGWENONYWAL' },
                { id: 39073, name: 'AKONGOLIT' },
                { id: 39074, name: 'ALELANGAO A' },
                { id: 39076, name: 'ALELANGAO B' },
                { id: 39075, name: 'AMULI' },
                { id: 39077, name: 'ANGIDI' },
                { id: 39078, name: 'ODIAK' },
                { id: 39079, name: 'OMOR' },
              ],
            },
          ],
        },
        {
          id: 1334,
          name: 'NALUBWOYO',
          parishes: [
            {
              id: 6268,
              name: 'AGWENONYWAL',
              villages: [
                { id: 39419, name: 'AGWENONYWAL A' },
                { id: 39421, name: 'AGWENONYWAL B' },
                { id: 57844, name: 'AKULI' },
                { id: 39420, name: 'ALOBOKWE' },
                { id: 62014, name: 'KACII' },
                { id: 39422, name: "KIDDA 'A'" },
                { id: 39423, name: "KIDDA 'B'" },
                { id: 71047, name: 'WANGIPOL' },
              ],
            },
            {
              id: 6270,
              name: 'ALWALA',
              villages: [
                { id: 58050, name: 'ALONGOLIL' },
                { id: 39431, name: 'ALWALA A' },
                { id: 39428, name: 'ALWALA B' },
                { id: 39429, name: 'ALWALA C' },
                { id: 58249, name: 'ANENORWOT' },
                { id: 62441, name: 'KAMPALA' },
                { id: 39430, name: 'KIBUGU' },
              ],
            },
            {
              id: 6269,
              name: 'AMOLATAR',
              villages: [
                { id: 39427, name: 'AMOLATAR ACON A' },
                { id: 39424, name: 'AMOLATAR ACON B' },
                { id: 58457, name: 'ARAKI' },
                { id: 58730, name: 'AWEIWOT' },
                { id: 39426, name: 'OCAMOLUM A' },
                { id: 39425, name: 'OCAMOLUM B' },
              ],
            },
            {
              id: 6267,
              name: 'NALUBWOYO',
              villages: [
                { id: 58173, name: 'AMONOLOCO' },
                { id: 39412, name: 'AWEINGWEC' },
                { id: 39415, name: "CAMURASA 'A'" },
                { id: 39416, name: "CAMURASA 'B'" },
                { id: 39413, name: 'KINYAI' },
                { id: 39414, name: 'OCWER' },
                { id: 39417, name: "OPIR 'A'" },
                { id: 39418, name: "OPIR 'B'" },
              ],
            },
            {
              id: 6271,
              name: 'OCAMOLUM',
              villages: [
                { id: 57399, name: 'ADAGANI' },
                { id: 57540, name: 'AGENORWOT' },
                { id: 58952, name: 'BARDAGO' },
                { id: 39432, name: 'OCAMOLUM A' },
                { id: 39433, name: 'OCAMOLUM B' },
                { id: 68495, name: 'ODONGOBER' },
              ],
            },
          ],
        },
        {
          id: 1320,
          name: 'NAMASALE',
          parishes: [
            {
              id: 6199,
              name: 'ADAGANI',
              villages: [
                { id: 57301, name: 'ACAN PE KUN' },
                { id: 57318, name: 'ACANPEBUTU-KEC' },
                { id: 39026, name: "ADAGANI 'A'" },
                { id: 39027, name: "ADAGANI 'B'" },
                { id: 39028, name: 'ADAGANI T.C' },
              ],
            },
            {
              id: 6200,
              name: 'AGULUDIA',
              villages: [
                { id: 39033, name: 'ABEDOBER' },
                { id: 39029, name: 'ACANKANYO' },
                { id: 39030, name: 'AGULUDIA' },
                { id: 39031, name: 'ALOKEREDAM' },
                { id: 39032, name: 'KATANGIRA' },
                { id: 39034, name: 'ORIB LWAK' },
              ],
            },
            {
              id: 6196,
              name: 'BANGLADESH',
              villages: [
                { id: 39013, name: 'ACILIDWE' },
                { id: 39009, name: 'ARWOTOMAROTONG' },
                { id: 39007, name: 'BANGALA A' },
                { id: 39008, name: 'BANGALA B' },
                { id: 39010, name: 'DAR-ES-SALAM' },
                { id: 39014, name: 'ECAMABOR' },
                { id: 39015, name: 'KOLOLO' },
                { id: 39011, name: 'MUSOMA' },
                { id: 39012, name: 'OBER-OKAA' },
                { id: 39016, name: 'WOTILWAK' },
              ],
            },
            {
              id: 6201,
              name: 'BURAKWANA',
              villages: [
                { id: 39035, name: 'ADAGARIDA' },
                { id: 39036, name: 'ALWALA' },
                { id: 39037, name: 'ARWOTOMAKOTONG' },
                { id: 39038, name: 'BUNG' },
                { id: 39041, name: 'ENTEBE' },
                { id: 39039, name: 'MARKET AREA' },
                { id: 39040, name: 'OGENGERE' },
              ],
            },
            {
              id: 9488,
              name: 'GOZWE',
              villages: [
                { id: 58032, name: "ALOBOKWE 'A'" },
                { id: 58033, name: "ALOBOKWE 'B'" },
                { id: 58972, name: 'BARLWALA' },
                { id: 61426, name: 'GOZWE' },
                { id: 63009, name: 'KASULE' },
                { id: 68478, name: 'ODOKOMIT' },
              ],
            },
            {
              id: 6194,
              name: 'IZIGWE',
              villages: [
                { id: 38999, name: "ANINOLAL 'A'" },
                { id: 39000, name: "ANINOLAL 'B'" },
                { id: 58343, name: 'ANYOTI' },
                { id: 39001, name: 'AWEIWOT' },
                { id: 58751, name: 'AWIGWENG' },
              ],
            },
            {
              id: 6195,
              name: 'KIKONDO',
              villages: [
                { id: 39002, name: 'ADAGKOLO' },
                { id: 39003, name: 'ALIMIT' },
                { id: 39004, name: 'AWELOBER' },
                { id: 60393, name: 'BUSSIA T C' },
                { id: 39005, name: 'KIPANGANI A' },
                { id: 39006, name: 'KIPANGANI B' },
              ],
            },
            {
              id: 6197,
              name: 'NABWEYO',
              villages: [
                { id: 39019, name: 'AWINYOCOA' },
                { id: 58965, name: 'BARJOBI' },
                { id: 39020, name: 'NABWEYO T/C' },
                { id: 39017, name: 'NGAMII' },
                { id: 39018, name: 'OBANGAKURA' },
              ],
            },
            {
              id: 6198,
              name: 'OLYAKA',
              villages: [
                { id: 57113, name: 'ABAKO FARM' },
                { id: 39021, name: 'ABAKO TRADING CENTRE' },
                { id: 39024, name: 'OJABU' },
                { id: 39022, name: 'OKWOR' },
                { id: 39023, name: 'OLYAKA A' },
                { id: 39025, name: 'OLYAKA B' },
              ],
            },
          ],
        },
        {
          id: 1330,
          name: 'NAMASALE TOWN COUNCIL',
          parishes: [
            {
              id: 6248,
              name: 'AWEIPEKO WARD',
              villages: [
                { id: 39338, name: 'ANGAORYEMI' },
                { id: 39339, name: 'ANOGA A' },
                { id: 39341, name: 'ANOGA B' },
                { id: 39340, name: 'AWEIPEKO' },
                { id: 39342, name: 'MBIKO LANDING SITE' },
              ],
            },
            {
              id: 6249,
              name: 'CENTRAL WARD',
              villages: [
                { id: 39344, name: 'BUNG' },
                { id: 39343, name: 'KAMAULU' },
                { id: 39345, name: 'KISUBI' },
                { id: 39346, name: 'MARKET AREA' },
                { id: 39347, name: 'NAMASALE TRADING CENTRE' },
              ],
            },
            {
              id: 6250,
              name: 'KAYAGO WARD',
              villages: [
                { id: 39351, name: 'APITO-PAT' },
                { id: 39348, name: "KAYAGO 'A'" },
                { id: 39349, name: "KAYAGO 'B'" },
                { id: 39350, name: 'PULEPULE' },
              ],
            },
            {
              id: 6247,
              name: 'WABINUA WARD',
              villages: [
                { id: 39332, name: 'ALOBOKWE' },
                { id: 39333, name: 'ARWOT OGIK' },
                { id: 39334, name: 'ODOKOLIT' },
                { id: 39337, name: 'ORIBCAN' },
                { id: 39335, name: "WABINUA 'A'" },
                { id: 39336, name: "WABINUA 'B'" },
              ],
            },
          ],
        },
        {
          id: 1335,
          name: 'OPALI',
          parishes: [
            {
              id: 6276,
              name: 'ACAN ORYEMA',
              villages: [
                { id: 39451, name: 'ABERAMAIDO' },
                { id: 57154, name: 'ABERAMAIDO B' },
                { id: 39452, name: 'AGWENO NYWAL' },
                { id: 57612, name: 'AGWENO NYWAL B' },
                { id: 39453, name: 'OLUU' },
                { id: 39454, name: 'OTIRA' },
              ],
            },
            {
              id: 6272,
              name: 'ADONYIMO',
              villages: [
                { id: 39435, name: 'ABUR OTIGO' },
                { id: 39436, name: 'ADWALA' },
                { id: 39434, name: 'ALEC' },
                { id: 58294, name: 'ANGUCAMI' },
                { id: 58759, name: 'AWILWALA' },
                { id: 39438, name: 'AWORO' },
                { id: 39437, name: 'OKADODERO' },
                { id: 70728, name: 'TETUGU' },
              ],
            },
            {
              id: 6277,
              name: 'AGWENG',
              villages: [
                { id: 39455, name: 'ABUTI' },
                { id: 39456, name: 'AGWENG' },
                { id: 57882, name: 'AKWAKI' },
                { id: 58391, name: 'APENYOWEO' },
                { id: 39457, name: 'TELELA' },
              ],
            },
            {
              id: 6274,
              name: 'AKURILUBA',
              villages: [
                { id: 57224, name: 'ABONGODERO' },
                { id: 39443, name: 'ACOMI' },
                { id: 39444, name: 'ADEKWOK' },
                { id: 57785, name: 'AKICA' },
                { id: 39445, name: 'AKURILUBA' },
                { id: 59177, name: 'BOROBORO' },
                { id: 68648, name: 'OJUL' },
              ],
            },
            {
              id: 6275,
              name: 'OPALI',
              villages: [
                { id: 39446, name: 'ACAN DOLE' },
                { id: 39449, name: 'ACAN ORYEMA' },
                { id: 57300, name: 'ACAN ORYEMA B' },
                { id: 39447, name: 'ACANOKUN' },
                { id: 39450, name: 'ARWOT NYAP' },
                { id: 39448, name: 'OPALI' },
              ],
            },
            {
              id: 6273,
              name: 'OTIRA',
              villages: [
                { id: 57125, name: 'ABALOWORO' },
                { id: 39439, name: 'ADEROLONGO' },
                { id: 39440, name: 'ELWA' },
                { id: 39441, name: 'OKECOYERE' },
                { id: 39442, name: 'OLEL PEK' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
