import { District } from '../types';

export default <District>{
  id: 86,
  name: 'AMURIA',
  counties: [
    {
      id: 213,
      name: 'AMURIA COUNTY',
      sub_counties: [
        {
          id: 1336,
          name: 'ABARILELA',
          parishes: [
            {
              id: 6282,
              name: 'ARUTE',
              villages: [
                { id: 39479, name: 'AKARE' },
                { id: 39480, name: 'ARUTE' },
                { id: 39481, name: 'DAKABELA' },
                { id: 39482, name: 'ORUNGET' },
              ],
            },
            {
              id: 6283,
              name: 'ASILANG',
              villages: [
                { id: 39483, name: 'AKERIAU' },
                { id: 39484, name: 'ASILANG' },
                { id: 39485, name: 'OKOKORIO' },
                { id: 39486, name: 'ONGUTOI' },
              ],
            },
            {
              id: 6278,
              name: 'DODOS',
              villages: [
                { id: 39458, name: 'ABARILELA' },
                { id: 39459, name: 'DODOS' },
                { id: 39460, name: 'ODUBAI' },
                { id: 39461, name: 'ODUKURUN' },
              ],
            },
            {
              id: 6279,
              name: 'KATINE',
              villages: [
                { id: 39468, name: 'AARATOM' },
                { id: 39462, name: 'ABULE' },
                { id: 39463, name: 'AKAMURIEI' },
                { id: 39464, name: 'KATINE' },
                { id: 39467, name: 'NAIKURO' },
                { id: 39465, name: 'OGWETE' },
                { id: 39466, name: 'OMODOI' },
                { id: 39469, name: 'OPADOI' },
              ],
            },
            {
              id: 6280,
              name: 'OCAL',
              villages: [
                { id: 39470, name: 'ADODOI' },
                { id: 39471, name: 'AGULE' },
                { id: 39472, name: 'OCAL' },
                { id: 39474, name: 'OGALAI' },
                { id: 39473, name: 'OGORIA' },
              ],
            },
            {
              id: 6281,
              name: 'OLELAI',
              villages: [
                { id: 39475, name: 'AGULE' },
                { id: 39477, name: 'MORU ARENGAN' },
                { id: 39476, name: 'OAJAITOI' },
                { id: 39478, name: 'OLELAI' },
              ],
            },
          ],
        },
        {
          id: 1339,
          name: 'ABIA',
          parishes: [
            {
              id: 6299,
              name: 'ABIA',
              villages: [
                { id: 39560, name: 'ABIA' },
                { id: 58490, name: 'ARIAMET' },
                { id: 58586, name: 'ASOGON' },
                { id: 68628, name: 'OJESAI' },
                { id: 39561, name: 'OPOLIN' },
                { id: 39559, name: 'TORONGOLE' },
              ],
            },
            {
              id: 6303,
              name: 'AGWARA',
              villages: [
                { id: 39571, name: 'AGWARA' },
                { id: 39574, name: 'ALALAM' },
                { id: 39572, name: 'ATAKIA' },
                { id: 68722, name: 'OKUNGURO' },
                { id: 39573, name: 'OREBAI' },
                { id: 69298, name: 'OTIIDO' },
              ],
            },
            {
              id: 6300,
              name: 'AKULAR',
              villages: [
                { id: 57465, name: 'ADOO AICERIT' },
                { id: 39563, name: 'AKULAR' },
                { id: 58632, name: 'ATIDA' },
                { id: 39562, name: 'MORU' },
                { id: 68519, name: 'ODUKUT' },
              ],
            },
            {
              id: 6301,
              name: 'ODONGAI',
              villages: [
                { id: 39564, name: 'AOJA' },
                { id: 39565, name: 'ODONGAI' },
                { id: 68813, name: 'OLIJAI' },
                { id: 69106, name: 'OPAUIYENGU' },
                { id: 39567, name: 'ORENGKIPI' },
                { id: 39566, name: 'OTUBOI' },
              ],
            },
            {
              id: 6302,
              name: 'OGUDO',
              villages: [
                { id: 39569, name: 'ABIA WERA' },
                { id: 58265, name: 'ANGARO' },
                { id: 68524, name: 'ODURUR' },
                { id: 39570, name: 'OGUDO' },
                { id: 39568, name: 'OKOKORIO' },
              ],
            },
          ],
        },
        {
          id: 1341,
          name: 'AMOLO',
          parishes: [
            {
              id: 6313,
              name: 'AJOKOMOT',
              villages: [
                { id: 39598, name: 'AJOKOMOT' },
                { id: 58216, name: 'AMUSO' },
                { id: 69379, name: 'OWOIKINAI' },
              ],
            },
            {
              id: 6311,
              name: 'AMOLO',
              villages: [
                { id: 58168, name: 'AMOLO CENTRAL' },
                { id: 39595, name: 'MORUNGATUNY' },
                { id: 70459, name: 'SIMBA' },
              ],
            },
            {
              id: 6314,
              name: 'AMUKURAT',
              villages: [
                { id: 39599, name: 'AMUKURAT A' },
                { id: 58201, name: 'AMUKURAT B' },
                { id: 58360, name: 'APALABERU' },
                { id: 39600, name: 'KELIM' },
                { id: 70841, name: 'TUKUM' },
              ],
            },
            {
              id: 6315,
              name: 'AROBA',
              villages: [
                { id: 57266, name: 'ABURASIRU' },
                { id: 39601, name: 'AROBA' },
                { id: 68436, name: 'OCUUMA' },
              ],
            },
            {
              id: 6317,
              name: 'GOLOKWARA',
              villages: [
                { id: 39604, name: 'GOLOKWARA' },
                { id: 68694, name: 'OKOMION' },
                { id: 69013, name: 'OMUNYAL A' },
                { id: 69014, name: 'OMUNYAL B' },
              ],
            },
            {
              id: 6316,
              name: 'OCOR',
              villages: [
                { id: 58601, name: 'ATAPAR' },
                { id: 39602, name: 'OCOR' },
                { id: 39603, name: 'OKILE' },
                { id: 69306, name: 'OTOGEL' },
              ],
            },
            {
              id: 6318,
              name: 'OPAM',
              villages: [
                { id: 39606, name: 'APEERO' },
                { id: 58674, name: 'ATUTUR' },
                { id: 39605, name: 'OPAM' },
              ],
            },
            {
              id: 6312,
              name: 'SUGUR',
              villages: [
                { id: 39596, name: 'AARATOM' },
                { id: 58254, name: 'ANGAIDA' },
                { id: 58351, name: 'AOJABULE' },
                { id: 39597, name: 'SUGUR' },
              ],
            },
          ],
        },
        {
          id: 1342,
          name: 'AMURIA TOWN COUNCIL',
          parishes: [
            {
              id: 6320,
              name: 'AKISIM WARD',
              villages: [
                { id: 39611, name: 'AKISIM' },
                { id: 39612, name: 'SCHOOL' },
              ],
            },
            {
              id: 6321,
              name: 'ALIRA WARD',
              villages: [
                { id: 39613, name: 'ALIRA' },
                { id: 39614, name: 'AOJAINGUR' },
                { id: 39615, name: 'MEDICAL' },
              ],
            },
            {
              id: 6319,
              name: 'EASTERN WARD',
              villages: [
                { id: 39610, name: 'ADUKA' },
                { id: 39607, name: 'AJIKAI' },
                { id: 39608, name: 'CENTRAL' },
                { id: 39609, name: 'MISSION CELL' },
              ],
            },
            {
              id: 6322,
              name: 'OKUTOI WARD',
              villages: [
                { id: 39618, name: 'AJELUK' },
                { id: 39616, name: 'OBUKU' },
                { id: 39617, name: 'OKUTOI' },
              ],
            },
          ],
        },
        {
          id: 1343,
          name: 'APEDURU',
          parishes: [
            {
              id: 6324,
              name: 'AJAKI',
              villages: [
                { id: 39624, name: 'ADODOI' },
                { id: 39628, name: 'AGUURUT' },
                { id: 39625, name: 'AJAKI' },
                { id: 39629, name: 'AKISIM' },
                { id: 39626, name: 'AYOLA' },
                { id: 39627, name: 'MORUBALE' },
                { id: 39631, name: 'OMODOI' },
                { id: 39630, name: 'OMUGEI' },
              ],
            },
            {
              id: 6323,
              name: 'AMUCU',
              villages: [
                { id: 39622, name: 'ADOME' },
                { id: 39619, name: 'AMUCU' },
                { id: 39620, name: 'AOJABULE' },
                { id: 39621, name: 'MORUCUCUK' },
                { id: 39623, name: 'OITELA IKWENY' },
              ],
            },
            {
              id: 6326,
              name: 'APEDURU',
              villages: [
                { id: 39637, name: 'ACIA' },
                { id: 39644, name: 'AKUM' },
                { id: 39638, name: 'ANGEREPO' },
                { id: 39639, name: 'APEDURU' },
                { id: 39641, name: 'GOLOKWARA' },
                { id: 39643, name: 'MIDDLE EAST OKOONA' },
                { id: 39640, name: 'MISSION AREA' },
                { id: 39642, name: 'TAKARAMIEM A' },
                { id: 39645, name: 'TAKARAMIEM B' },
              ],
            },
            {
              id: 6325,
              name: 'ODOON',
              villages: [
                { id: 39632, name: 'ACWILA' },
                { id: 39635, name: 'APUNGURE' },
                { id: 39633, name: 'ODOON CENTRE' },
                { id: 39634, name: 'OGEMU' },
                { id: 39636, name: 'OTINGAI' },
              ],
            },
            {
              id: 6327,
              name: 'OMARIAI',
              villages: [
                { id: 39646, name: 'AGUYAGUYA' },
                { id: 39647, name: 'ARUBELA' },
                { id: 39650, name: 'MORU AKUWEI' },
                { id: 39649, name: 'ODEBEI' },
                { id: 39648, name: 'OMARIAI' },
              ],
            },
          ],
        },
        {
          id: 1337,
          name: 'ASAMUK',
          parishes: [
            {
              id: 6287,
              name: 'APARISA',
              villages: [
                { id: 39509, name: 'ACUL' },
                { id: 39510, name: 'AGULE I' },
                { id: 39511, name: 'AGULE II' },
                { id: 39512, name: 'APARISA' },
                { id: 39514, name: 'OBOLIA PESUR' },
                { id: 39515, name: 'OJIBAI' },
                { id: 39513, name: 'OKWALO' },
              ],
            },
            {
              id: 6284,
              name: 'ASAMUK',
              villages: [
                { id: 39487, name: 'ADEPANARIO' },
                { id: 39493, name: 'ASAMUK' },
                { id: 39488, name: 'ASAMUK CENTRE' },
                { id: 39489, name: 'ASAMUK MORU' },
                { id: 39492, name: 'OCANAI' },
                { id: 39490, name: 'OLELIA' },
                { id: 39491, name: 'OLITOI' },
                { id: 39495, name: 'OMABULE' },
                { id: 39494, name: 'OMERAI' },
              ],
            },
            {
              id: 6285,
              name: 'ATIRIR',
              villages: [
                { id: 39502, name: 'AMIELI' },
                { id: 39497, name: 'MODOK' },
                { id: 39498, name: 'MORUPUS' },
                { id: 39499, name: 'MUGANA' },
                { id: 39500, name: 'OKOONA' },
                { id: 39501, name: 'ORENGEKEJEI' },
                { id: 39496, name: 'OUKOT' },
              ],
            },
            {
              id: 6288,
              name: 'DOKOLO',
              villages: [
                { id: 39516, name: 'ALASI' },
                { id: 39520, name: 'ALEREKE' },
                { id: 39517, name: 'DOKOLO MORU' },
                { id: 39521, name: 'OCUMA' },
                { id: 39518, name: 'OJAMAI' },
                { id: 39519, name: 'OSEPAI' },
              ],
            },
            {
              id: 6286,
              name: 'OBUR',
              villages: [
                { id: 39503, name: 'AKUMANGOR' },
                { id: 39506, name: 'ALOMAIN' },
                { id: 39504, name: 'OBUR' },
                { id: 39507, name: 'OBUR AGULE' },
                { id: 39505, name: 'OOLOI' },
                { id: 39508, name: 'ORWADAI' },
              ],
            },
            {
              id: 6290,
              name: 'OJAMAI',
              villages: [
                { id: 39528, name: 'AKOBOI' },
                { id: 39529, name: 'ARUKIT' },
                { id: 39530, name: 'ATUBAKINEI' },
                { id: 39532, name: 'BOBOL' },
                { id: 39531, name: 'OJAMAI' },
                { id: 39533, name: 'ONGUNY' },
              ],
            },
            {
              id: 6289,
              name: 'OLEKAI',
              villages: [
                { id: 39522, name: 'AKUSI' },
                { id: 39524, name: 'ANGARO' },
                { id: 39526, name: 'AOJA' },
                { id: 39523, name: 'OLAPAI' },
                { id: 39527, name: 'OLEKAI' },
                { id: 39525, name: 'OROROI' },
              ],
            },
          ],
        },
        {
          id: 1338,
          name: 'KUJU',
          parishes: [
            {
              id: 6291,
              name: 'AMILIMIL',
              villages: [
                { id: 58298, name: 'ANGUR' },
                { id: 58559, name: 'ARUTE' },
                { id: 39536, name: 'NAPAK' },
                { id: 39534, name: 'OMECA' },
                { id: 39535, name: 'ONGEROI' },
                { id: 69154, name: 'OPUYO' },
              ],
            },
            {
              id: 6292,
              name: 'AMUSUS',
              villages: [
                { id: 39538, name: 'ABILET' },
                { id: 39537, name: 'ABWOLOIT' },
                { id: 57583, name: 'AGURUR' },
                { id: 57625, name: 'AIRIAMET' },
                { id: 39539, name: 'AMUSUS' },
              ],
            },
            {
              id: 6294,
              name: 'ANGOROM',
              villages: [
                { id: 57451, name: 'ADODOI' },
                { id: 57647, name: 'AJESAI' },
                { id: 58291, name: 'ANGOROM A' },
                { id: 39544, name: 'ANGOROM B' },
                { id: 69054, name: 'ONGAROI' },
                { id: 39545, name: 'ORWADAI' },
              ],
            },
            {
              id: 6298,
              name: 'AOJAKITOI',
              villages: [
                { id: 39558, name: 'AOJA KUJU' },
                { id: 39557, name: 'AOJAKWAP' },
                { id: 39556, name: 'APOPONG' },
                { id: 69349, name: 'OWADET' },
              ],
            },
            {
              id: 6295,
              name: 'ARAPAI',
              villages: [
                { id: 57628, name: 'AITA' },
                { id: 39546, name: 'ARAPAI' },
                { id: 58528, name: 'ARITEI' },
                { id: 39548, name: 'AYOGA' },
                { id: 39549, name: 'OKEPIA' },
                { id: 39547, name: 'ORIETA' },
              ],
            },
            {
              id: 6296,
              name: 'ATUBA',
              villages: [
                { id: 57443, name: 'ADIPALA' },
                { id: 39550, name: 'AMOTOT' },
                { id: 39551, name: 'ATUBA' },
                { id: 68558, name: 'OGOLAI' },
              ],
            },
            {
              id: 6293,
              name: 'KUJU',
              villages: [
                { id: 39540, name: 'ACOMAI' },
                { id: 39542, name: 'AMOTOT' },
                { id: 64364, name: 'KUJU' },
                { id: 66389, name: 'MORUBAYA' },
                { id: 39541, name: 'OCAUNAKOLONG A' },
                { id: 68403, name: 'OCAUNAKOLONG B' },
                { id: 39543, name: 'OOLOI' },
              ],
            },
            {
              id: 6297,
              name: 'OBAR',
              villages: [
                { id: 57814, name: 'AKOLI' },
                { id: 39552, name: 'ARUPA' },
                { id: 39553, name: 'KATAKWI' },
                { id: 39554, name: 'MORU' },
                { id: 39555, name: 'OBAR' },
              ],
            },
          ],
        },
        {
          id: 1340,
          name: 'WERA',
          parishes: [
            {
              id: 6304,
              name: 'AJOTA',
              villages: [
                { id: 57672, name: 'AJOTA' },
                { id: 39575, name: 'ININGO' },
                { id: 39576, name: 'OTOMEI' },
              ],
            },
            {
              id: 6305,
              name: 'ANGOLE',
              villages: [
                { id: 57794, name: 'AKISIM' },
                { id: 58279, name: 'ANGOLE' },
                { id: 39579, name: 'ANGOLE-AKISIM' },
                { id: 39577, name: 'ARUBELA' },
                { id: 39580, name: 'ASALATAP' },
                { id: 39581, name: 'CENTRAL CELL' },
                { id: 63905, name: 'KISENYI' },
                { id: 67954, name: 'NYADA' },
                { id: 39578, name: 'ONINO' },
              ],
            },
            {
              id: 6310,
              name: 'ATEN',
              villages: [
                { id: 39591, name: 'ACHILA' },
                { id: 57626, name: 'AIRIAMET' },
                { id: 39593, name: 'AMORU' },
                { id: 58604, name: 'ATAPAR' },
                { id: 39592, name: 'ATEN' },
                { id: 68588, name: 'OGULITOK' },
                { id: 68631, name: 'OJIBAI' },
                { id: 39594, name: 'OLAGAR' },
              ],
            },
            {
              id: 6307,
              name: 'OLIANAI',
              villages: [
                { id: 39586, name: 'ALAKAITUK' },
                { id: 58020, name: 'ALIRA' },
                { id: 68724, name: 'OKUNGURO' },
                { id: 68737, name: 'OKWAKIPI' },
                { id: 39585, name: 'OLIANAI' },
                { id: 68910, name: 'OMATAILONG' },
              ],
            },
            {
              id: 6308,
              name: 'OPIRIAI',
              villages: [
                { id: 58185, name: 'AMORU' },
                { id: 68378, name: 'OBULE' },
                { id: 68723, name: 'OKUNGURO' },
                { id: 39587, name: 'OPIRIAI' },
                { id: 70268, name: 'SABATIA' },
              ],
            },
            {
              id: 6309,
              name: 'OSEKAI',
              villages: [
                { id: 57646, name: 'AJESA' },
                { id: 58104, name: 'AMAROGE' },
                { id: 39589, name: 'ANGARO' },
                { id: 39590, name: 'DOKORO' },
                { id: 39588, name: 'OSEKAI' },
              ],
            },
            {
              id: 6306,
              name: 'WERA',
              villages: [
                { id: 39584, name: 'AGUMALOB' },
                { id: 57938, name: 'ALECER' },
                { id: 58445, name: 'APUUTON' },
                { id: 39582, name: 'ATERAI' },
                { id: 39583, name: 'OIMAI' },
                { id: 68698, name: 'OKONY' },
                { id: 68868, name: 'OLUPE' },
                { id: 71104, name: 'WERA' },
                { id: 71105, name: 'WERA-OIMAI' },
              ],
            },
          ],
        },
        {
          id: 1344,
          name: 'WILLA',
          parishes: [
            {
              id: 6330,
              name: 'ABWANGET',
              villages: [
                { id: 39670, name: 'ABUKET' },
                { id: 39664, name: 'ABULE' },
                { id: 39665, name: 'ABWANGET' },
                { id: 39666, name: 'AMILIMIL' },
                { id: 39671, name: 'AMWOGO' },
                { id: 39668, name: 'AUPARAN' },
                { id: 39669, name: 'MOROTO' },
                { id: 39667, name: 'ORWADAI' },
              ],
            },
            {
              id: 6331,
              name: 'AKISIM',
              villages: [
                { id: 39672, name: 'ACINGA' },
                { id: 39676, name: 'ADOME' },
                { id: 39677, name: 'AKISIM' },
                { id: 39674, name: 'ARORO' },
                { id: 39675, name: 'OKUNGURO' },
                { id: 39673, name: 'OLWATAI' },
                { id: 39678, name: 'OODOI' },
              ],
            },
            {
              id: 6332,
              name: 'AKUM',
              villages: [
                { id: 39679, name: 'AGALIBU' },
                { id: 39680, name: 'AKUM' },
                { id: 39681, name: 'ANGEREPO' },
                { id: 39685, name: 'OCALAMIR' },
                { id: 39682, name: 'OGENGERA' },
                { id: 39683, name: 'OJOTA' },
                { id: 39684, name: 'OMATAKILEI' },
              ],
            },
            {
              id: 6328,
              name: 'ALERE',
              villages: [
                { id: 39651, name: 'ABOTA' },
                { id: 39652, name: 'ACOMAI' },
                { id: 39653, name: 'ALERE' },
                { id: 39654, name: 'AOROTOM' },
                { id: 39656, name: 'OJOM' },
                { id: 39655, name: 'OPALANGOR' },
              ],
            },
            {
              id: 6329,
              name: 'WILA',
              villages: [
                { id: 39658, name: 'AGEREGER  - WILLA' },
                { id: 39663, name: 'AGEREGER - KUJU' },
                { id: 39659, name: 'AMOTOT' },
                { id: 39660, name: 'APEDURU' },
                { id: 39661, name: 'ATUKUTUK' },
                { id: 39662, name: 'MORU' },
                { id: 39657, name: 'ONYAKAI' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 214,
      name: 'ORUNGO COUNTY',
      sub_counties: [
        {
          id: 1349,
          name: 'AKERIAU',
          parishes: [
            {
              id: 6361,
              name: 'AITA',
              villages: [
                { id: 39778, name: 'ACANPII' },
                { id: 39779, name: 'AITA' },
                { id: 39780, name: 'ATAPAR' },
                { id: 39782, name: 'CUTUK' },
                { id: 39781, name: 'OTEME' },
              ],
            },
            {
              id: 6357,
              name: 'AKERIAU',
              villages: [
                { id: 39754, name: 'ABWOLOIT' },
                { id: 39755, name: 'AGORA' },
                { id: 39756, name: 'AKERIAU' },
                { id: 39753, name: 'AMORU' },
                { id: 39759, name: 'AYOLA' },
                { id: 39757, name: 'OBIONGIO' },
                { id: 39758, name: 'OKOLIA' },
              ],
            },
            {
              id: 6358,
              name: 'OKUDE',
              villages: [
                { id: 39765, name: 'ACELE' },
                { id: 39760, name: 'ALECER' },
                { id: 39761, name: 'ODUDUI' },
                { id: 39762, name: 'OJAMA' },
                { id: 39763, name: 'OKUDE' },
                { id: 39764, name: 'OMUNYIR' },
                { id: 39766, name: 'ONOTAI' },
              ],
            },
            {
              id: 6359,
              name: 'OTUBET',
              villages: [
                { id: 39768, name: 'ANGARO' },
                { id: 39769, name: 'ANGOROM' },
                { id: 39770, name: 'APOPONG' },
                { id: 39771, name: 'OJOLAI' },
                { id: 39772, name: 'OTUBET' },
                { id: 39767, name: 'OUKOT' },
              ],
            },
            {
              id: 6360,
              name: 'TEMELE',
              villages: [
                { id: 39773, name: 'ABIA' },
                { id: 39775, name: 'AKOYO' },
                { id: 39776, name: 'ALOKODUM' },
                { id: 39774, name: 'ARUBELA' },
                { id: 39777, name: 'TEMELE' },
              ],
            },
          ],
        },
        {
          id: 1348,
          name: 'MORUNGATUNY',
          parishes: [
            {
              id: 6350,
              name: 'ABOKET',
              villages: [
                { id: 39732, name: 'ABOKET' },
                { id: 39733, name: 'AJESAI' },
                { id: 58038, name: 'ALOET' },
                { id: 39734, name: 'OLUSAI' },
              ],
            },
            {
              id: 6351,
              name: 'AITA',
              villages: [
                { id: 57394, name: 'ADACAR' },
                { id: 39736, name: 'AITA' },
                { id: 57644, name: 'AJENIT' },
                { id: 39735, name: 'AKUYA A' },
                { id: 57876, name: 'AKUYA B' },
                { id: 58662, name: 'ATORI' },
              ],
            },
            {
              id: 6352,
              name: 'CORNER STONE',
              villages: [
                { id: 39737, name: 'ACELE A' },
                { id: 39738, name: 'ACELE B' },
                { id: 57591, name: 'AGWATA' },
                { id: 57915, name: 'ALAGA' },
                { id: 39739, name: 'AMUKURUSINGEI' },
                { id: 39740, name: 'ORAPAK' },
              ],
            },
            {
              id: 6354,
              name: 'MORUNGATUNY',
              villages: [
                { id: 39745, name: 'ATEUSO' },
                { id: 39744, name: 'ATEUSO CENTRAL' },
                { id: 39746, name: 'OJOBAI' },
                { id: 39747, name: 'OMUNYIR' },
                { id: 69015, name: 'OMUNYIR CENTRAL' },
              ],
            },
            {
              id: 6355,
              name: 'OGANGAI',
              villages: [
                { id: 58164, name: 'AMOGO' },
                { id: 39748, name: 'OGANGAI' },
                { id: 68538, name: 'OGANGAI CENTRAL' },
                { id: 39749, name: 'ORIMAI' },
                { id: 69359, name: 'OWASAI' },
              ],
            },
            {
              id: 6356,
              name: 'OJUKOT',
              villages: [
                { id: 39751, name: 'ODEKERE' },
                { id: 68446, name: 'ODEKERE CENTRAL' },
                { id: 39750, name: 'ODEKERE-AITA' },
                { id: 39752, name: 'OJUKOT' },
                { id: 69286, name: 'OTATAI' },
              ],
            },
            {
              id: 6353,
              name: 'OMODOI',
              villages: [
                { id: 57314, name: 'ACANIPI' },
                { id: 57796, name: 'AKISIM' },
                { id: 39743, name: 'ANGAAN' },
                { id: 39741, name: 'MORU' },
                { id: 39742, name: 'OMODOI' },
                { id: 69300, name: 'OTINGAI' },
              ],
            },
          ],
        },
        {
          id: 1350,
          name: 'OGOLAI',
          parishes: [
            {
              id: 6362,
              name: 'ABEKO',
              villages: [
                { id: 39783, name: 'AMARET' },
                { id: 39784, name: 'ARUTE' },
                { id: 39786, name: 'OGWARAT' },
                { id: 39785, name: 'OJAMA' },
                { id: 39787, name: 'OLUNGURA' },
                { id: 39789, name: 'ONGEROI' },
                { id: 39788, name: 'ORWADAI' },
              ],
            },
            {
              id: 6365,
              name: 'AKORE',
              villages: [
                { id: 39805, name: 'ABIA' },
                { id: 39806, name: 'ACOMAI' },
                { id: 39807, name: 'AKOCO' },
                { id: 39808, name: 'AKORE' },
                { id: 39809, name: 'ALAYA' },
                { id: 39810, name: 'OBANGIN' },
                { id: 39811, name: 'OJAMA' },
              ],
            },
            {
              id: 6363,
              name: 'OCOCIA',
              villages: [
                { id: 39790, name: 'ABATA' },
                { id: 39791, name: 'ADUKA A' },
                { id: 39797, name: 'ADUKA B' },
                { id: 39792, name: 'AJONAI' },
                { id: 39793, name: 'OBUR' },
                { id: 39794, name: 'OCOCIA' },
                { id: 39795, name: 'OCOCIA CENTRE' },
                { id: 39796, name: 'ODOMAI' },
              ],
            },
            {
              id: 6366,
              name: 'ODEPE',
              villages: [
                { id: 39812, name: 'AJUR' },
                { id: 39815, name: 'AKUYA' },
                { id: 39816, name: 'DOKOLO' },
                { id: 39813, name: 'ODEPE' },
                { id: 39814, name: 'OJARETA' },
              ],
            },
            {
              id: 6364,
              name: 'OGOLAI',
              villages: [
                { id: 39803, name: 'ABIBICO' },
                { id: 39804, name: 'APEULAI' },
                { id: 39799, name: 'ODUKUT' },
                { id: 39798, name: 'OGOLAI' },
                { id: 39800, name: 'OKAO' },
                { id: 39801, name: 'ONYONGO' },
                { id: 39802, name: 'ORIETA' },
              ],
            },
          ],
        },
        { id: 2095, name: 'OGONGORA', parishes: [] },
        {
          id: 1346,
          name: 'OLWA',
          parishes: [
            {
              id: 6339,
              name: 'AGWANJUA',
              villages: [
                { id: 39695, name: 'ABAKULI' },
                { id: 39696, name: 'AGWANJUA' },
                { id: 58144, name: 'AMINIGOI' },
                { id: 58599, name: 'ATAPAR' },
                { id: 68876, name: 'OLWA CORNER A' },
                { id: 39697, name: 'OLWA CORNER B' },
                { id: 39698, name: 'OMUKO' },
              ],
            },
            {
              id: 6342,
              name: 'AWELU',
              villages: [
                { id: 39706, name: 'ADWIR' },
                { id: 39708, name: 'AJOLI' },
                { id: 58428, name: 'APOYONENI' },
                { id: 39709, name: 'APURET' },
                { id: 39710, name: 'AWELU' },
                { id: 39707, name: 'AWELU CENTRAL' },
              ],
            },
            {
              id: 6343,
              name: 'AYOLA',
              villages: [
                { id: 57801, name: 'AKOBOI' },
                { id: 57849, name: 'AKUM' },
                { id: 39712, name: 'AYOLA' },
                { id: 39713, name: 'LALE' },
                { id: 39711, name: 'OTOKE' },
              ],
            },
            {
              id: 6340,
              name: 'JALAM',
              villages: [
                { id: 39699, name: 'ABOKE' },
                { id: 39700, name: 'ACOMAI' },
                { id: 58376, name: 'APEDURU' },
                { id: 39701, name: 'JALAM' },
                { id: 61745, name: 'JAMAIKA' },
                { id: 68451, name: 'ODEPAI' },
                { id: 68907, name: 'OMARIAI' },
              ],
            },
            {
              id: 6341,
              name: 'OLWA',
              villages: [
                { id: 57194, name: 'ABOKE' },
                { id: 57313, name: 'ACANIPI' },
                { id: 39703, name: 'ALELA' },
                { id: 39705, name: 'ALONGET' },
                { id: 58707, name: 'AWANGODIANG' },
                { id: 68334, name: 'OBARAI' },
                { id: 39704, name: 'OJENIT' },
                { id: 39702, name: 'OLALE' },
              ],
            },
          ],
        },
        {
          id: 1345,
          name: 'ONGONGORA',
          parishes: [
            {
              id: 6333,
              name: 'DOKOLO',
              villages: [
                { id: 57253, name: 'ABULE' },
                { id: 57944, name: 'ALEKLEK' },
                { id: 58184, name: 'AMORU' },
                { id: 39686, name: 'DOKOLO' },
                { id: 39687, name: 'OIKIIK' },
              ],
            },
            {
              id: 6334,
              name: 'OCAKAI',
              villages: [
                { id: 57629, name: 'AITAKE' },
                { id: 58443, name: 'APUUTON' },
                { id: 39688, name: 'OCAKAI' },
                { id: 68643, name: 'OJOLAI' },
                { id: 39689, name: 'OYAMAI' },
              ],
            },
            {
              id: 6335,
              name: 'OELAI',
              villages: [
                { id: 58375, name: 'APEDURU' },
                { id: 58603, name: 'ATAPAR' },
                { id: 39690, name: 'OELAI' },
                { id: 68763, name: 'OLAIRE' },
              ],
            },
            {
              id: 6338,
              name: 'OGONGORA',
              villages: [
                { id: 58284, name: 'ANGOPET' },
                { id: 58288, name: 'ANGOROM' },
                { id: 39694, name: 'MATALI' },
                { id: 68567, name: 'OGONGORA' },
                { id: 68781, name: 'OLELAI' },
              ],
            },
            {
              id: 6336,
              name: 'OLELE',
              villages: [
                { id: 58262, name: 'ANGARO' },
                { id: 58350, name: 'AOJA' },
                { id: 58491, name: 'ARIAMET' },
                { id: 39691, name: 'OLELE' },
                { id: 39692, name: 'OLUPE' },
              ],
            },
            {
              id: 6337,
              name: 'ONYEBA',
              villages: [
                { id: 57848, name: 'AKUM' },
                { id: 58356, name: 'APAASI A' },
                { id: 58357, name: 'APAASI B' },
                { id: 68827, name: 'OLIO' },
                { id: 39693, name: 'ONYEBA' },
              ],
            },
          ],
        },
        {
          id: 1347,
          name: 'ORUNGO',
          parishes: [
            {
              id: 6348,
              name: 'ADAKUN',
              villages: [
                { id: 57188, name: 'ABIYA' },
                { id: 39724, name: 'ADAKUN' },
                { id: 39725, name: 'OBUKITEI' },
                { id: 68913, name: 'OMATORI' },
                { id: 39726, name: 'ORIEBAI' },
              ],
            },
            {
              id: 6344,
              name: 'AMECHA',
              villages: [
                { id: 39714, name: 'AMECHA' },
                { id: 58633, name: 'ATIIDA' },
                { id: 61212, name: 'ECAMAITAI' },
                { id: 65216, name: 'LLEREREI' },
                { id: 39715, name: 'OMADIRA' },
              ],
            },
            {
              id: 6346,
              name: 'MORUINERA',
              villages: [
                { id: 39718, name: 'ALILIOI' },
                { id: 58600, name: 'ATAPAR' },
                { id: 66392, name: 'MORUINERA' },
                { id: 39720, name: 'OJEBURUN' },
                { id: 39719, name: 'ONGAROI' },
              ],
            },
            {
              id: 6349,
              name: 'OMORATOK',
              villages: [
                { id: 39727, name: 'ANYAIKI' },
                { id: 66380, name: 'MORU-KAPEL' },
                { id: 39730, name: 'OMETAI' },
                { id: 68950, name: 'OMETAI A' },
                { id: 68951, name: 'OMETAI B' },
                { id: 39731, name: 'OMORATOK' },
                { id: 39728, name: 'ORWADAI' },
                { id: 39729, name: 'TOWNSHIP' },
              ],
            },
            {
              id: 6347,
              name: 'ORUNGO',
              villages: [
                { id: 39722, name: 'ARIDI' },
                { id: 58499, name: 'ARIEBI' },
                { id: 39721, name: 'BULAYA' },
                { id: 39723, name: 'ORUNGO' },
              ],
            },
            {
              id: 6345,
              name: 'OWANGAI',
              villages: [
                { id: 57375, name: 'ACUMBALA' },
                { id: 58776, name: 'AWITWON' },
                { id: 66391, name: 'MORUIJEKO' },
                { id: 39716, name: 'OJALAM' },
                { id: 39717, name: 'OWANGAI' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
