import { District } from '../types';

export default <District>{
  id: 117,
  name: 'BULAMBULI',
  counties: [
    {
      id: 275,
      name: 'BULAMBULI COUNTY',
      sub_counties: [
        {
          id: 1808,
          name: 'BUKHALU',
          parishes: [
            {
              id: 8540,
              name: 'BUKHALU',
              villages: [
                { id: 53561, name: 'BUKATSA' },
                { id: 53563, name: 'BUKHALU A' },
                { id: 53562, name: 'BUKHALU B' },
                { id: 53564, name: 'BULUSAMBU A' },
                { id: 59748, name: 'BULUSAMBU B' },
                { id: 53565, name: 'BUMASIKYE A' },
                { id: 59816, name: 'BUMASIKYE B' },
              ],
            },
            {
              id: 8541,
              name: 'BUNAMALIRO',
              villages: [
                { id: 53566, name: 'BUBUYERA A' },
                { id: 53569, name: 'BUBUYERA B' },
                { id: 53567, name: 'BUFUKHULA' },
                { id: 53571, name: 'BUNAMALIRO' },
                { id: 60104, name: 'BUNANGWAKWA' },
                { id: 53568, name: 'BUNYITSA' },
                { id: 60203, name: 'BUNYWAKA' },
                { id: 53570, name: 'BUWANGOTA' },
              ],
            },
            {
              id: 8542,
              name: 'BUNAMBUTYE',
              villages: [
                { id: 53576, name: 'BULWANGA A' },
                { id: 53572, name: 'BULWANGA B' },
                { id: 53575, name: 'BULWANGA C' },
                { id: 53577, name: 'BUNAMBUTYE A' },
                { id: 60039, name: 'BUNAMBUTYE B' },
                { id: 53573, name: 'BUPOTO' },
                { id: 53574, name: 'BUSHIBALAYI' },
              ],
            },
            {
              id: 8543,
              name: 'BUSHIENDE',
              villages: [
                { id: 53578, name: 'BUKHABOYO' },
                { id: 53581, name: 'BUKHATELEMA' },
                { id: 53579, name: 'BUNAAMARA' },
                { id: 53582, name: 'BUSHIENDE' },
                { id: 53583, name: 'BWIKHONGE A' },
                { id: 53580, name: 'BWIKHONGE B' },
              ],
            },
            {
              id: 8544,
              name: 'BUSIU',
              villages: [
                { id: 53587, name: 'BUMULAHA A' },
                { id: 53584, name: 'BUMULAHA B' },
                { id: 53588, name: 'BUSIU A' },
                { id: 53585, name: 'BUSIU B' },
                { id: 53589, name: 'BUWAKHANYUNYI A' },
                { id: 53586, name: 'BUWAKHANYUNYI B' },
              ],
            },
            {
              id: 8545,
              name: 'SIMU',
              villages: [
                { id: 53596, name: 'BURUKURU A' },
                { id: 53592, name: 'BURUKURU B' },
                { id: 53597, name: 'BUWESONGA A' },
                { id: 53593, name: 'BUWESONGA B' },
                { id: 53598, name: 'LYAMBOKO A' },
                { id: 53594, name: 'LYAMBOKO B' },
                { id: 53590, name: 'SIMU' },
                { id: 53595, name: 'SIMU B' },
                { id: 53591, name: 'SUKUYA' },
              ],
            },
          ],
        },
        {
          id: 1815,
          name: 'BULAMBULI TOWN COUNCIL',
          parishes: [
            {
              id: 8573,
              name: 'BURUKURU WARD',
              villages: [
                { id: 53826, name: 'BURUKURU A' },
                { id: 53824, name: 'BURUKURU B' },
                { id: 53825, name: 'EDUCATION CELL' },
                { id: 53827, name: 'MUYEMBE TOWNSHIP' },
              ],
            },
            {
              id: 8575,
              name: 'BUTTA WARD',
              villages: [
                { id: 53834, name: 'BUBULO' },
                { id: 53835, name: 'BUNAMUNANE' },
                { id: 53838, name: 'BUTTA  B' },
                { id: 53837, name: 'BUTTA A' },
                { id: 53836, name: 'BUTTA CENTRAL' },
                { id: 53839, name: 'BUTTA WEST' },
                { id: 53840, name: 'NAMIKYELO' },
              ],
            },
            {
              id: 8574,
              name: 'BWIKONGE WARD',
              villages: [
                { id: 53828, name: 'BUMASARI' },
                { id: 53832, name: 'BUMASIIME' },
                { id: 53829, name: 'BUNGOKHO' },
                { id: 53831, name: 'BWIKHONGE' },
                { id: 53830, name: 'SANGO' },
                { id: 53833, name: 'TUBAANA' },
              ],
            },
            {
              id: 8572,
              name: 'INDUSTRIAL WARD',
              villages: [
                { id: 53818, name: 'ADMINISTRATION' },
                { id: 53819, name: 'BUTTA ORIGINAL' },
                { id: 53820, name: 'CENTRAL' },
                { id: 53821, name: 'GREEN' },
                { id: 53822, name: 'INDUSTRIAL' },
                { id: 53823, name: 'MARKET' },
              ],
            },
          ],
        },
        {
          id: 1807,
          name: 'BUMUFUNI',
          parishes: [
            {
              id: 8536,
              name: 'BUMBOCHA',
              villages: [
                { id: 53540, name: 'BUBUYA A' },
                { id: 53541, name: 'BUKHURARWA' },
                { id: 53542, name: 'BUMANDALI' },
                { id: 53543, name: 'BUMBOCHA' },
                { id: 53544, name: 'BUMUYONGA' },
              ],
            },
            {
              id: 8538,
              name: 'BUMUFUNI',
              villages: [
                { id: 59210, name: 'BUBICHACHI' },
                { id: 53550, name: 'BUGOBERO' },
                { id: 59585, name: 'BUKOBERO' },
                { id: 53551, name: 'BUKOTO' },
                { id: 59644, name: 'BUKWANGWA' },
                { id: 59661, name: 'BULAKO' },
                { id: 53552, name: 'BULUCHEKHE' },
                { id: 60481, name: 'BUTOTO' },
                { id: 53554, name: 'BUWEBELE' },
                { id: 53553, name: 'BUWESONGA' },
                { id: 53555, name: 'BUYASERE' },
              ],
            },
            {
              id: 8537,
              name: 'BUMWANGU',
              villages: [
                { id: 53546, name: 'BUBULO' },
                { id: 59579, name: 'BUKIYABI' },
                { id: 53547, name: 'BUMUKOYA' },
                { id: 59942, name: 'BUMWANGU' },
                { id: 53545, name: 'BUSONGE' },
                { id: 53548, name: 'BUWAALA' },
                { id: 53549, name: 'BUWANJALA' },
              ],
            },
            {
              id: 8539,
              name: 'BUWEBELE',
              villages: [
                { id: 53556, name: 'BUBUYA B' },
                { id: 53557, name: 'BUKHAYAKI' },
                { id: 53560, name: 'BUNAMBALE' },
                { id: 53558, name: 'BUSANGAI' },
                { id: 53559, name: 'BUWECHALO' },
              ],
            },
          ],
        },
        {
          id: 1809,
          name: 'BUNALWERE',
          parishes: [
            {
              id: 8547,
              name: 'BULUMERA',
              villages: [
                { id: 53604, name: 'BULUMERA MAIN' },
                { id: 53606, name: 'BULUMERA MARKET' },
                { id: 53607, name: 'BUNAMALIKHE' },
                { id: 53605, name: 'BUNASHIMOLO A' },
                { id: 53608, name: 'BUNASHIMOLO B' },
              ],
            },
            {
              id: 8546,
              name: 'BUNALWERE',
              villages: [
                { id: 53602, name: 'BUMWALYE' },
                { id: 53600, name: 'BUNALWERE' },
                { id: 53599, name: 'BUNALWERE B' },
                { id: 53601, name: 'BUNGOKHO' },
                { id: 53603, name: 'NGWANYI' },
              ],
            },
            {
              id: 8548,
              name: 'BUNAMUJJE',
              villages: [
                { id: 53609, name: 'BUDUDA' },
                { id: 53612, name: 'BUNAMUJJE A' },
                { id: 53610, name: 'BUNAMUJJE B' },
                { id: 53614, name: 'BUSAMALI A' },
                { id: 53613, name: 'BUSAMALI B' },
                { id: 53611, name: 'SHILONGO' },
              ],
            },
          ],
        },
        {
          id: 1811,
          name: 'BUNAMBUTYE',
          parishes: [
            {
              id: 8552,
              name: 'BULUGUYA',
              villages: [
                { id: 53638, name: 'BUGOBERO' },
                { id: 53639, name: 'BULWANGA' },
                { id: 53636, name: 'BUNAALE' },
                { id: 53637, name: 'BUNYELESTI' },
                { id: 53640, name: 'BUTSEMA' },
                { id: 53641, name: 'BUWEBERE' },
                { id: 60744, name: 'BUZEMA' },
              ],
            },
            {
              id: 8553,
              name: 'BUMASARI',
              villages: [
                { id: 53642, name: 'BUBUYA' },
                { id: 53646, name: 'BUMASARI' },
                { id: 53643, name: 'BUTSEMA' },
                { id: 53644, name: 'KAATA' },
                { id: 53645, name: 'MABAALE' },
              ],
            },
            {
              id: 8554,
              name: 'BUNANGANDA',
              villages: [
                { id: 53647, name: 'BUCHEKELEYI' },
                { id: 53648, name: 'BUKIKAYI' },
                { id: 53649, name: 'BUKITANGA' },
                { id: 53650, name: 'BUNANGANDA' },
                { id: 53651, name: 'BUNATSUBYA' },
              ],
            },
            {
              id: 8555,
              name: 'BUSHANGI',
              villages: [
                { id: 53653, name: 'BUDUDA' },
                { id: 53652, name: 'BUKHAKOSI' },
                { id: 53654, name: 'BULAKO' },
                { id: 53656, name: 'BULWETA' },
                { id: 53658, name: 'BUMASIKYE' },
                { id: 53655, name: 'BUMULUYA' },
                { id: 53657, name: 'BUMWALYE' },
                { id: 53659, name: 'BUNATUNGA' },
              ],
            },
          ],
        },
        {
          id: 1810,
          name: 'BUWANYANGA',
          parishes: [
            {
              id: 8549,
              name: 'BUMUSAMALI',
              villages: [
                { id: 53615, name: 'BUMAGENI' },
                { id: 53616, name: 'BUMUSAMALI A' },
                { id: 53620, name: 'BUMUSAMALI B' },
                { id: 53618, name: 'BUMUSAMALI C' },
                { id: 59962, name: 'BUNABUMBO' },
                { id: 53617, name: 'BUSANO A' },
                { id: 53619, name: 'BUSANO B' },
                { id: 53621, name: 'BUTITI' },
              ],
            },
            {
              id: 8550,
              name: 'BUSABULO',
              villages: [
                { id: 59744, name: 'BULUMERE B' },
                { id: 53623, name: 'BULUMINO A' },
                { id: 53622, name: 'BULUMINO B' },
                { id: 60057, name: 'BUNAMONO' },
                { id: 53625, name: 'BUSABULO A' },
                { id: 53624, name: 'BUSABULO B' },
                { id: 53626, name: 'BUTSESOOLI' },
                { id: 53627, name: 'BUTTA' },
                { id: 53628, name: 'BUWEBELE' },
                { id: 71200, name: 'YAKA' },
              ],
            },
            {
              id: 8551,
              name: 'BUWANYANGA',
              villages: [
                { id: 59772, name: 'BUMAHENA' },
                { id: 60245, name: 'BURUKURU' },
                { id: 53631, name: 'BUWANYANGA A' },
                { id: 53629, name: 'BUWANYANGA B' },
                { id: 53632, name: 'BUWANYANGA CAHOLIC CHURCH' },
                { id: 53633, name: 'BUYAGA MARKET' },
                { id: 53630, name: 'BUYAGA S.S' },
                { id: 53634, name: 'BUYAGA TC B' },
                { id: 60855, name: 'CENTRAL CELL' },
                { id: 65585, name: 'LUFULA CELL' },
                { id: 53635, name: 'NAMILI' },
                { id: 70335, name: 'SHIBANGA' },
                { id: 70953, name: 'VISION CELL' },
              ],
            },
          ],
        },
        {
          id: 1816,
          name: 'BUYAGA TOWN COUNCIL',
          parishes: [
            {
              id: 8579,
              name: 'BUNGWANYI WARD',
              villages: [
                { id: 53859, name: 'BUMWIYIMA' },
                { id: 53864, name: 'BUNGWANYI  A' },
                { id: 53865, name: 'BUNGWANYI  B' },
                { id: 53866, name: 'BUWANYAMA A' },
                { id: 53860, name: 'BUWANYAMA B' },
                { id: 53862, name: 'BUYAGA  TOWNSHIP A' },
                { id: 53863, name: 'BUYAGA  TOWNSHIP F' },
                { id: 53861, name: 'MURUUBA' },
              ],
            },
            {
              id: 8578,
              name: 'BUYAGA CENTRAL WARD',
              villages: [
                { id: 53855, name: 'BUGOBERO' },
                { id: 53853, name: 'BULUKUYA A' },
                { id: 53854, name: 'BULUKUYA B' },
                { id: 53856, name: 'BUYAGA  TOWN SHIP C' },
                { id: 53857, name: 'BUYAGA  TOWNSHIP  E' },
                { id: 53852, name: 'BUYAKA' },
                { id: 53858, name: 'BUYAKA CENTRAL' },
              ],
            },
            {
              id: 8576,
              name: 'BUYAGA MARKET WARD',
              villages: [
                { id: 53845, name: 'BUYAGA  TOWN SHIP  B' },
                { id: 53841, name: 'BUYAGA MARKET' },
                { id: 53842, name: 'CENTRE' },
                { id: 53843, name: 'LUFULA' },
                { id: 53844, name: 'SIBANGA' },
              ],
            },
            {
              id: 8577,
              name: 'INDUSTRIAL WARD',
              villages: [
                { id: 53846, name: 'BUSUKUYA A' },
                { id: 60403, name: 'BUSUKUYA B' },
                { id: 53847, name: 'BUTSESOLI A' },
                { id: 53848, name: 'BUYAGA TOWNSHIP D' },
                { id: 53850, name: 'INDUSTRIAL' },
                { id: 53851, name: 'PARK' },
                { id: 53849, name: 'POLICE' },
              ],
            },
          ],
        },
        {
          id: 1813,
          name: 'BWIKHONGE',
          parishes: [
            {
              id: 8562,
              name: 'BULUMELA',
              villages: [
                { id: 53719, name: 'BILONGO' },
                { id: 53729, name: 'BUKHABOYO' },
                { id: 53722, name: 'BULUMERA' },
                { id: 53723, name: 'BUMABONO' },
                { id: 53728, name: 'BUMALIRO' },
                { id: 53720, name: 'BUMULAHA' },
                { id: 53721, name: 'BUMULANYI' },
                { id: 53724, name: 'BUMUTSOBA' },
                { id: 53725, name: 'BUNETIBU' },
                { id: 53726, name: 'BUWALUSATI' },
                { id: 53727, name: 'BUWESWA' },
              ],
            },
            {
              id: 8563,
              name: 'BUNALWERE',
              villages: [
                { id: 53732, name: 'BUNALWERE' },
                { id: 53730, name: 'BUSHIYENDE' },
                { id: 53731, name: 'BUSOBA' },
                { id: 53733, name: 'BUTTA' },
                { id: 53734, name: 'BUWEBELE' },
                { id: 53736, name: 'MARAKARU' },
                { id: 53735, name: 'SIPPI T/C A' },
              ],
            },
            {
              id: 8564,
              name: 'BUWABWALA',
              villages: [
                { id: 53737, name: 'BUNABALAYO' },
                { id: 53738, name: 'BUSIANGO' },
                { id: 53742, name: 'BUWABWALA' },
                { id: 53740, name: 'BUWAKOLI' },
                { id: 53739, name: 'BUWANYAMA' },
                { id: 53741, name: 'BUYAKA' },
              ],
            },
            {
              id: 8565,
              name: 'BUWEKANDA',
              villages: [
                { id: 53743, name: 'BUKHINDE' },
                { id: 53744, name: 'BULUSAMBU' },
                { id: 53745, name: 'BUMAYENA' },
                { id: 53746, name: 'BUMUKOYA' },
                { id: 53749, name: 'BUNAMONO' },
                { id: 53747, name: 'BUNANGANDA' },
                { id: 53750, name: 'BUWASYEBA' },
                { id: 53748, name: 'SIPPI T/C B' },
              ],
            },
            {
              id: 8561,
              name: 'BWIKHONGE',
              villages: [
                { id: 53706, name: 'BUBULO' },
                { id: 53717, name: 'BULAKO' },
                { id: 53708, name: 'BULWANGA' },
                { id: 53709, name: 'BUMABUGO' },
                { id: 53710, name: 'BUMATAYA' },
                { id: 53711, name: 'BUMAYINA' },
                { id: 53712, name: 'BUMUKOYA' },
                { id: 53713, name: 'BUMWAMBU' },
                { id: 53707, name: 'BUNABIRO' },
                { id: 53714, name: 'BUNAMWAMBA' },
                { id: 53718, name: 'BUNGWANYI' },
                { id: 53715, name: 'BUWECHALO' },
                { id: 53716, name: 'MAKHONGE' },
              ],
            },
          ],
        },
        {
          id: 1812,
          name: 'MUYEMBE',
          parishes: [
            {
              id: 8560,
              name: 'BULAKO',
              villages: [
                { id: 53701, name: 'BULAKO' },
                { id: 53702, name: 'BUMULEKHWA' },
                { id: 53700, name: 'BUNABIRO' },
                { id: 53703, name: 'BUNAKAMI' },
                { id: 53704, name: 'BUSUKUYA' },
                { id: 53705, name: 'BUWABWALA' },
              ],
            },
            {
              id: 8558,
              name: 'BUMUGOYA',
              villages: [
                { id: 53678, name: 'BULWATSATSA' },
                { id: 53681, name: 'BUMUGOYA A' },
                { id: 53680, name: 'BUMUGOYA B' },
                { id: 53682, name: 'BUNANIMI' },
                { id: 53683, name: 'BUNEKESA' },
                { id: 53679, name: 'BUWESWA' },
                { id: 53684, name: 'NALUKOOSI' },
                { id: 53686, name: 'SIMU' },
                { id: 53685, name: 'SIMU CORNER TOWNSHIP' },
                { id: 53687, name: 'WEWULA' },
              ],
            },
            {
              id: 8557,
              name: 'BUNGWANYI',
              villages: [
                { id: 53672, name: 'BUKHALOOMA' },
                { id: 53673, name: 'BUMULAHA' },
                { id: 53674, name: 'BUNYWAKA  A' },
                { id: 53675, name: 'BUNYWAKA  B' },
                { id: 53677, name: 'BUTAMBALA' },
                { id: 53676, name: 'BUWAMBOKO' },
              ],
            },
            {
              id: 8556,
              name: 'BUWAGOGO',
              villages: [
                { id: 53660, name: 'BUBWAYA' },
                { id: 53663, name: 'BUSAMALI' },
                { id: 53667, name: 'BUWAGOGO' },
                { id: 53661, name: 'BUWAGOGO B' },
                { id: 53662, name: 'BUWANGANI' },
                { id: 53664, name: 'DDEMBE' },
                { id: 53669, name: 'MALUKHU' },
                { id: 53665, name: 'MALUKHU B' },
                { id: 53666, name: 'MATIBO' },
                { id: 53670, name: 'SIMU CORNER' },
                { id: 53671, name: 'SIMU VALLEY' },
                { id: 53668, name: 'WETONGOLA' },
              ],
            },
            {
              id: 8559,
              name: 'BUYAKA',
              villages: [
                { id: 59019, name: 'BEACH' },
                { id: 53690, name: 'BUMASIKYE' },
                { id: 53694, name: 'BUMASIKYE TOWNSHIP' },
                { id: 53688, name: 'BUMWAMBU' },
                { id: 53695, name: 'BUSHITIMO' },
                { id: 53696, name: 'BUYAKA' },
                { id: 53697, name: 'MAKHUYU' },
                { id: 53689, name: 'NALONDO' },
                { id: 53691, name: 'NAMAIKA' },
                { id: 53698, name: 'NAMATITI' },
                { id: 53699, name: 'SHISABASI' },
                { id: 53692, name: 'SUKUTA' },
                { id: 53693, name: 'YEMBE' },
              ],
            },
          ],
        },
        {
          id: 1814,
          name: 'NABBONGO',
          parishes: [
            {
              id: 8570,
              name: 'BUFUKHULA',
              villages: [
                { id: 53794, name: 'BUBETYSE' },
                { id: 53795, name: 'BUFUKHULA' },
                { id: 53796, name: 'BUKHUMWA' },
                { id: 53797, name: 'BULAKO' },
                { id: 53800, name: 'BUMULAHA' },
                { id: 53798, name: 'BUNGWANYI' },
                { id: 53801, name: 'MASATSA' },
                { id: 53802, name: 'NABBONGO P/S EDUC' },
                { id: 53803, name: 'NABBONGO SEC EDUC' },
                { id: 53799, name: 'NABUKIMBI' },
                { id: 53804, name: 'NABUWEMBA' },
                { id: 53805, name: 'NASHISHILILA' },
              ],
            },
            {
              id: 8571,
              name: 'BUFUMBULA',
              villages: [
                { id: 53807, name: 'BUFUMBULA' },
                { id: 53809, name: 'BUKEWA' },
                { id: 53808, name: 'BUKHINDE' },
                { id: 53810, name: 'BUMALENYA' },
                { id: 53813, name: 'BUMUSOMI' },
                { id: 53814, name: 'BUMUTOOLA' },
                { id: 53806, name: 'BUSANGAYI' },
                { id: 53815, name: 'BUTTA' },
                { id: 53811, name: 'BUWALUSATI' },
                { id: 53812, name: 'BUWASYEBA' },
                { id: 53816, name: 'BUWATUWA' },
                { id: 53817, name: 'WANGA' },
              ],
            },
            {
              id: 8568,
              name: 'BUMASOKHO',
              villages: [
                { id: 53773, name: 'BUBULO' },
                { id: 53775, name: 'BUMASOKHO' },
                { id: 53776, name: 'BUMULEKHWA' },
                { id: 53774, name: 'BUNAMONI' },
                { id: 53777, name: 'BUNANDUTU' },
                { id: 53772, name: 'BUWASYEBA' },
                { id: 53778, name: 'BUWATSALA' },
                { id: 53779, name: 'BUWATUWA' },
                { id: 53780, name: 'BUWEKANDA' },
              ],
            },
            {
              id: 8569,
              name: 'BUNANGAKA',
              villages: [
                { id: 53781, name: 'BUKATSA' },
                { id: 53782, name: 'BUKHASYEWA' },
                { id: 53783, name: 'BUKIKAYI' },
                { id: 53787, name: 'BUMWALYE' },
                { id: 53788, name: 'BUMWAMBU' },
                { id: 53789, name: 'BUNAMONO' },
                { id: 53790, name: 'BUNAMUNANE' },
                { id: 53784, name: 'BUNANGAKA' },
                { id: 53791, name: 'BUNANGWAKO' },
                { id: 53785, name: 'BUNGOKHO' },
                { id: 53792, name: 'BURUKURU' },
                { id: 53786, name: 'BUSHYANGI' },
                { id: 53793, name: 'BUSIU' },
              ],
            },
            {
              id: 8566,
              name: 'BUWAKOOLI',
              villages: [
                { id: 53751, name: 'BUDUDA' },
                { id: 53753, name: 'BUKINOMU' },
                { id: 53754, name: 'BUMWANGU' },
                { id: 53755, name: 'BUNAKHAYOTI' },
                { id: 53752, name: 'BUNAMBUTYE' },
                { id: 53756, name: 'BUWABUYI' },
                { id: 53757, name: 'BUWAKOOLI' },
                { id: 53758, name: 'BWIKHONGE' },
              ],
            },
            {
              id: 8567,
              name: 'NABBONGO',
              villages: [
                { id: 53760, name: 'BUBITUMU' },
                { id: 53761, name: 'BUBUTU' },
                { id: 53763, name: 'BUKHAMUNYU' },
                { id: 53762, name: 'BUMATANDA' },
                { id: 53764, name: 'BUNAALE' },
                { id: 53765, name: 'BUNANIMI' },
                { id: 53767, name: 'BUNYWAKA' },
                { id: 53768, name: 'BUSHIENDE' },
                { id: 53769, name: 'BUTSESOLI' },
                { id: 53766, name: 'BUWALA' },
                { id: 53770, name: 'BUWAMBINGWA' },
                { id: 53759, name: 'NABBONGO' },
                { id: 53771, name: 'NABBONGO TOWNSHIP' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 276,
      name: 'ELGON COUNTY',
      sub_counties: [
        {
          id: 1818,
          name: 'BUFUMBO',
          parishes: [
            {
              id: 8586,
              name: 'BUFUMBO',
              villages: [
                { id: 61314, name: 'FUMBO' },
                { id: 53927, name: 'KIBEMBE' },
                { id: 53928, name: 'KISABASI I' },
                { id: 53923, name: 'KISABASI II' },
                { id: 53924, name: 'LUDAMA' },
                { id: 53929, name: 'MABALE' },
                { id: 53925, name: 'MATURUBAYA' },
                { id: 53926, name: 'PEKEDDO' },
                { id: 53930, name: 'WOMUNGA' },
              ],
            },
            {
              id: 8587,
              name: 'BUZEMUNWA',
              villages: [
                { id: 53933, name: 'BUZEMUNWA A' },
                { id: 53931, name: 'BUZEMUNWA B' },
                { id: 53932, name: 'KIDIBA' },
                { id: 53937, name: 'MAGOZWA' },
                { id: 53934, name: 'MAKUMA' },
                { id: 66094, name: 'MASOLA' },
                { id: 53935, name: 'NAKAZUNGU' },
                { id: 53936, name: 'WOKULA' },
              ],
            },
            {
              id: 8588,
              name: 'MALUNGI',
              villages: [
                { id: 53938, name: 'BULUGANYA' },
                { id: 53939, name: 'BUNDEJJE' },
                { id: 53941, name: 'KIDEGA' },
                { id: 53940, name: 'KILABILI' },
                { id: 65627, name: 'LUKOLI' },
                { id: 53944, name: 'MALUNGI' },
                { id: 53942, name: 'NAKIDEGA' },
                { id: 53943, name: 'NAMAYOGESA' },
              ],
            },
            {
              id: 8589,
              name: 'MBIGI',
              villages: [
                { id: 53945, name: 'BOMBO' },
                { id: 53946, name: 'KIBOKO' },
                { id: 53947, name: 'KIFONASI' },
                { id: 53948, name: 'KITONDWANI' },
                { id: 53950, name: 'MABONDYE A' },
                { id: 53949, name: 'MABONDYE B' },
                { id: 53951, name: 'MATANGI' },
                { id: 53952, name: 'MBIGI' },
                { id: 53953, name: 'SUGUTA' },
              ],
            },
          ],
        },
        {
          id: 1817,
          name: 'BUGINYANYA',
          parishes: [
            {
              id: 8581,
              name: 'BUNATAJJE',
              villages: [
                { id: 53881, name: 'BUGIMOTWA' },
                { id: 53878, name: 'BUNATAJJE' },
                { id: 53879, name: 'GABOGI' },
                { id: 53882, name: 'GIBANYI LOWER' },
                { id: 53880, name: 'GIBANYI UPPER' },
                { id: 53883, name: 'KATEBE' },
                { id: 53884, name: 'LUPOTE' },
                { id: 53887, name: 'MADUWA' },
                { id: 53885, name: 'MAKANDE' },
                { id: 53886, name: 'MASUBI' },
                { id: 53888, name: 'NAKIFUMBUKO' },
                { id: 53877, name: 'VOLOTI' },
              ],
            },
            {
              id: 8582,
              name: 'GIDUNO',
              villages: [
                { id: 53889, name: 'BUGEMA' },
                { id: 53890, name: 'BUNAMAHE' },
                { id: 53893, name: 'GIDUNO' },
                { id: 53891, name: 'LUWANGO' },
                { id: 53892, name: 'NABUTWA' },
                { id: 53894, name: 'NAMONDO' },
                { id: 53896, name: 'SOLLA  LOWER' },
                { id: 53895, name: 'SOLLA  UPPER' },
              ],
            },
            {
              id: 8583,
              name: 'GOOZI',
              villages: [
                { id: 53897, name: 'BUMWAMBU' },
                { id: 53898, name: 'GOOZI' },
                { id: 53899, name: 'KIZINGA' },
                { id: 53902, name: 'LUDAMA' },
                { id: 53900, name: 'LUSHA' },
                { id: 53903, name: 'MADENJE' },
                { id: 53901, name: 'MUNDESI' },
                { id: 53904, name: 'TOBOTI' },
              ],
            },
            {
              id: 8580,
              name: 'KIRWALI',
              villages: [
                { id: 53871, name: 'BUGINYANYA LINE' },
                { id: 53867, name: 'BUGUBE LOWER' },
                { id: 53868, name: 'BUGUBE UPPER' },
                { id: 53869, name: 'GIBUZALE' },
                { id: 53870, name: 'KIDWESU' },
                { id: 53872, name: 'KIRWALI MAIN' },
                { id: 53873, name: 'KUKYIGO' },
                { id: 53874, name: 'MASEBE' },
                { id: 53875, name: 'PALIPALE' },
                { id: 53876, name: 'SIMBO' },
              ],
            },
            {
              id: 8584,
              name: 'SISIYI',
              villages: [
                { id: 53905, name: 'KIZUBI LOWER' },
                { id: 53909, name: 'KIZUBI UPPER' },
                { id: 53907, name: 'MAKYELE' },
                { id: 53906, name: 'NABUNULI' },
                { id: 53910, name: 'NAKITABAGO' },
                { id: 53911, name: 'NAMUDINDI' },
                { id: 53912, name: 'SISIYI' },
                { id: 53908, name: 'SUGUTA' },
              ],
            },
            {
              id: 8585,
              name: 'TABALI',
              villages: [
                { id: 53918, name: 'BUWAMBEDYE EAST' },
                { id: 53917, name: 'BUWAMBEDYE WEST' },
                { id: 53919, name: 'GIBIGWA A' },
                { id: 53920, name: 'GIBIGWA B' },
                { id: 53913, name: 'KIDEGA' },
                { id: 53914, name: 'KIRWALI' },
                { id: 53921, name: 'LIGOMBE' },
                { id: 53915, name: 'LISAYILO' },
                { id: 53916, name: 'MAGUGYE' },
                { id: 53922, name: 'TABALI' },
              ],
            },
          ],
        },
        {
          id: 1819,
          name: 'BULAGO',
          parishes: [
            {
              id: 8593,
              name: 'BUGATISA',
              villages: [
                { id: 59314, name: 'BUGATISA' },
                { id: 54008, name: 'BUGATISA T.C' },
                { id: 54001, name: 'GIBEYI' },
                { id: 54009, name: 'GIMADU T.C' },
                { id: 54000, name: 'GOMBE' },
                { id: 63473, name: 'KIGANDA T.C' },
                { id: 54010, name: 'KITWE' },
                { id: 54002, name: 'MADUWA' },
                { id: 54011, name: 'MAKOGOTI' },
                { id: 54012, name: 'MASINZI' },
                { id: 54003, name: 'MASUGUKU' },
                { id: 54013, name: 'MAWOTOLO' },
                { id: 54014, name: 'MAYIRA' },
                { id: 54004, name: 'MULUWE' },
                { id: 54005, name: 'MUSOBA' },
                { id: 54006, name: 'NAGABITA' },
                { id: 54015, name: 'NAMITYE' },
                { id: 54007, name: 'NASHUWU' },
                { id: 54016, name: 'ZEBUGYEYANI' },
              ],
            },
            {
              id: 8591,
              name: 'BUMUSAMALI',
              villages: [
                { id: 53962, name: 'BISAYE' },
                { id: 53961, name: 'DIISI' },
                { id: 53963, name: 'KIDUMI' },
                { id: 63457, name: 'KIFUDI' },
                { id: 65867, name: 'MADOLODOLO' },
                { id: 65999, name: 'MALI' },
                { id: 53964, name: 'MANYONDO' },
                { id: 53965, name: 'MASABASI' },
                { id: 53966, name: 'NAKIZUBO' },
                { id: 53967, name: 'NALWANDA' },
                { id: 53970, name: 'NAPIILA' },
                { id: 53971, name: 'NASANYI' },
                { id: 53968, name: 'NATUSI' },
                { id: 53969, name: 'WODOLA' },
              ],
            },
            {
              id: 8590,
              name: 'BUNASUFWA',
              villages: [
                { id: 53954, name: 'BUDALI' },
                { id: 53957, name: 'DIMBWE' },
                { id: 53955, name: 'GIBUMBUNI' },
                { id: 61378, name: 'GIMADU T.C' },
                { id: 53956, name: 'GIMUTERI' },
                { id: 63433, name: 'KIDEGA' },
                { id: 53958, name: 'KILABIRA' },
                { id: 66163, name: 'MAYILA T.C' },
                { id: 53959, name: 'NAMUSESERI' },
                { id: 70550, name: 'SUGUTA' },
                { id: 53960, name: 'ZEBUGOYA' },
              ],
            },
            {
              id: 8592,
              name: 'BUSIYA',
              villages: [
                { id: 53984, name: 'BULAAGO CORNER' },
                { id: 53972, name: 'BULAGO  T.C' },
                { id: 53973, name: 'GISINGO' },
                { id: 53974, name: 'KAJERE' },
                { id: 53985, name: 'KIBAYA' },
                { id: 53986, name: 'KIBAYA T.C' },
                { id: 53975, name: 'KILABIRI' },
                { id: 53988, name: 'KILOGOZI' },
                { id: 53976, name: 'KISABASI' },
                { id: 53977, name: 'KISINA' },
                { id: 53989, name: 'KYIYEWA' },
                { id: 53987, name: 'LALAGI' },
                { id: 53978, name: 'LUZIRA' },
                { id: 65852, name: 'MADAMA' },
                { id: 53990, name: 'MADAMA T.C' },
                { id: 53979, name: 'MAGABO' },
                { id: 53991, name: 'MAGABO T.C' },
                { id: 53992, name: 'MAGONGOYI' },
                { id: 66972, name: 'NAISA' },
                { id: 53993, name: 'NAKAZUNGU' },
                { id: 53994, name: 'NAKOKO HILL' },
                { id: 67141, name: 'NAKWEKWE T.C' },
                { id: 53980, name: 'NALUNGODO' },
                { id: 53995, name: 'NAMAKWEKWE' },
                { id: 53981, name: 'NASUBU A' },
                { id: 53996, name: 'NASUBU B' },
                { id: 53997, name: 'NAYISI' },
                { id: 53998, name: 'SUGUTA' },
                { id: 53982, name: 'TIRIGIMA' },
                { id: 70935, name: 'UPLAND CELL' },
                { id: 53983, name: 'ZEBUBU' },
                { id: 53999, name: 'ZEMASITO' },
              ],
            },
          ],
        },
        {
          id: 1820,
          name: 'BULEGENI',
          parishes: [
            {
              id: 8595,
              name: 'MBIGI',
              villages: [
                { id: 54035, name: 'BUWANGANI' },
                { id: 54037, name: 'JAMBULA' },
                { id: 54036, name: 'JAMBULA T.C' },
                { id: 54038, name: 'KABUNINGA' },
                { id: 54039, name: 'KIKOMA' },
                { id: 54040, name: 'KITTAKA' },
                { id: 54041, name: 'LUKHOLA' },
                { id: 54042, name: 'MBIGI' },
                { id: 54046, name: 'NAFUTA' },
                { id: 54048, name: 'NAMUTOKOLO' },
                { id: 54047, name: 'NATABA' },
                { id: 54049, name: 'SAMAZI TRADING CENTRE A' },
                { id: 54050, name: 'SAMAZI TRADING CENTRE B' },
                { id: 54043, name: 'SAMAZI TRADING CENTRE C' },
                { id: 54044, name: 'SAMAZI TRADING CENTRE D' },
                { id: 54045, name: 'SAMBUKO' },
              ],
            },
            {
              id: 8596,
              name: 'MUVULE',
              villages: [
                { id: 54051, name: 'KITABYA' },
                { id: 54057, name: 'MAWOLELA' },
                { id: 54058, name: 'MUNDEZI' },
                { id: 54059, name: 'MUSOLA A' },
                { id: 54052, name: 'MUSOLA B' },
                { id: 54060, name: 'MUVULE' },
                { id: 54053, name: 'MUVULE T.C' },
                { id: 54054, name: 'NAGAZA A' },
                { id: 54061, name: 'NAGAZA B' },
                { id: 54062, name: 'NEMBA  A' },
                { id: 54063, name: 'NEMBA  B' },
                { id: 54055, name: 'NEMBA T.C' },
                { id: 54056, name: 'TAP' },
              ],
            },
            {
              id: 8594,
              name: 'SAMAZI',
              villages: [
                { id: 54018, name: 'CHEMURONI' },
                { id: 54021, name: 'KANAPEDE' },
                { id: 54025, name: 'KIKUYU' },
                { id: 54026, name: 'KIYEMBE' },
                { id: 54027, name: 'LUKHUNGU' },
                { id: 54028, name: 'LUWANGO' },
                { id: 54022, name: 'MABALE A' },
                { id: 54020, name: 'MABALE B' },
                { id: 54023, name: 'MAKUYU' },
                { id: 54017, name: 'MANYOLOLO' },
                { id: 54024, name: 'MASABASI A' },
                { id: 54029, name: 'MASABASI B' },
                { id: 54019, name: 'MATATI' },
                { id: 54031, name: 'NAKIFUMBUKO' },
                { id: 54032, name: 'NAKITWE' },
                { id: 54034, name: 'SISIYI A' },
                { id: 54030, name: 'SISIYI B' },
                { id: 54033, name: 'SUGUTA' },
              ],
            },
          ],
        },
        {
          id: 1830,
          name: 'BULEGENI TOWN COUNCIL',
          parishes: [
            {
              id: 8644,
              name: 'BULEGENI WARD',
              villages: [
                { id: 54627, name: 'KABUBUYA' },
                { id: 61999, name: 'KACHEKWASI' },
                { id: 54628, name: 'KAPKWEREMBE' },
                { id: 54629, name: 'KARABACHI' },
                { id: 63649, name: 'KIKOMOSI' },
                { id: 54630, name: 'KIRESI A' },
                { id: 63805, name: 'KIRESI B' },
                { id: 63806, name: 'KIRESI C' },
                { id: 54631, name: 'MUNKOTEKA' },
                { id: 67734, name: 'NGARAMU' },
                { id: 71109, name: 'WETIYA' },
              ],
            },
            {
              id: 8645,
              name: 'KAVULE WARD',
              villages: [
                { id: 59142, name: 'BOGOYA' },
                { id: 61138, name: 'DODO' },
                { id: 61425, name: 'GOZOWA' },
                { id: 54632, name: 'KABEMBE  A' },
                { id: 54633, name: 'KABEMBE  B' },
                { id: 61903, name: 'KABEMBE C' },
                { id: 61904, name: 'KABEMBE D' },
                { id: 54634, name: 'KABEMBE T.C' },
                { id: 62383, name: 'KALUTUSI' },
                { id: 54635, name: 'KAMAYATI A' },
                { id: 62412, name: 'KAMAYATI B' },
                { id: 62498, name: 'KAMWANYI' },
                { id: 54636, name: 'KAPKWENI' },
                { id: 54637, name: 'KAVULE  A' },
                { id: 63188, name: 'KAVULE  B' },
                { id: 65461, name: 'LONGITI' },
                { id: 65655, name: 'LUMBUGU' },
                { id: 65688, name: 'LUSAFU' },
                { id: 65843, name: 'MABONO' },
                { id: 66038, name: 'MARAMA' },
                { id: 66140, name: 'MATUNDA' },
                { id: 66697, name: 'MUSINDIKE' },
              ],
            },
            {
              id: 8643,
              name: 'MAGALA WARD',
              villages: [
                { id: 60908, name: 'CHEMAGERENI' },
                { id: 62173, name: 'KAJEWA' },
                { id: 54622, name: 'KAKWEITA A' },
                { id: 62268, name: 'KAKWEITA CELL' },
                { id: 62382, name: 'KALUTUSI' },
                { id: 54623, name: 'KASHESHE' },
                { id: 54624, name: 'KATONGEN' },
                { id: 63633, name: 'KIKAMELI' },
                { id: 63698, name: 'KILILWASI' },
                { id: 63934, name: 'KISIYATEBE' },
                { id: 64166, name: 'KIZUBI' },
                { id: 65664, name: 'LUNGUKU' },
                { id: 65865, name: 'MADODOLOMO' },
                { id: 54625, name: 'MAGALA A' },
                { id: 65879, name: 'MAGALA B' },
                { id: 66138, name: 'MATUBA' },
                { id: 66477, name: 'MUDWALE' },
                { id: 54626, name: 'NABUGOBEI' },
                { id: 67396, name: 'NAMUSUDA' },
                { id: 67399, name: 'NAMUTIKA' },
              ],
            },
          ],
        },
        {
          id: 1821,
          name: 'BULUGANYA',
          parishes: [
            {
              id: 8597,
              name: 'BULUGANYA',
              villages: [
                { id: 54067, name: 'BULUGANYA TRADING CENTRE' },
                { id: 54068, name: 'BUMAKYOKYE' },
                { id: 54076, name: 'BUMALADYA' },
                { id: 54073, name: 'BUZEMOLILI' },
                { id: 54074, name: 'BWAKUYE' },
                { id: 54066, name: 'LUKUNGIRI' },
                { id: 54078, name: 'LULA' },
                { id: 54069, name: 'LUSOLA' },
                { id: 54070, name: 'MADUWA' },
                { id: 54071, name: 'MAMOLO' },
                { id: 54079, name: 'MASABASI' },
                { id: 54080, name: 'MASOLA' },
                { id: 54081, name: 'MASOLA  T.C' },
                { id: 54075, name: 'MASUGU' },
                { id: 54072, name: 'MUSHUWU' },
                { id: 54064, name: 'NAKAKYELE' },
                { id: 54065, name: 'NAKISIKIRO' },
                { id: 54082, name: 'NAMAKYELE' },
                { id: 54077, name: 'NAMANGO' },
                { id: 54083, name: 'NAYINYINYA' },
                { id: 54084, name: 'TAGALU' },
                { id: 54085, name: 'ZEMA TRADING CENTRE' },
              ],
            },
            {
              id: 8600,
              name: 'MABUGU',
              villages: [
                { id: 54104, name: 'DISI A' },
                { id: 61134, name: 'DISI B' },
                { id: 54099, name: 'GASITOYI' },
                { id: 54100, name: 'KIBANJE' },
                { id: 54101, name: 'LUNGO' },
                { id: 54102, name: 'RUKUNGIRI' },
                { id: 54097, name: 'SANGA' },
                { id: 54098, name: 'SUGUTA A' },
                { id: 54103, name: 'SUGUTA B' },
              ],
            },
            {
              id: 8598,
              name: 'MASAKA',
              villages: [
                { id: 60655, name: 'BUWAYO' },
                { id: 54088, name: 'KIBAYA' },
                { id: 54089, name: 'LUBAYA' },
                { id: 65643, name: 'LUKUNGIRI' },
                { id: 65694, name: 'LUSOLA' },
                { id: 54090, name: 'MASAKA' },
                { id: 54086, name: 'MASAKA T.C' },
                { id: 54087, name: 'MASEJESE' },
                { id: 67078, name: 'NAKITALI' },
              ],
            },
            {
              id: 8599,
              name: 'NAMUNANE',
              villages: [
                { id: 54091, name: 'BIRINDA' },
                { id: 59787, name: 'BUMAKYOKYE' },
                { id: 54092, name: 'BUMBOLE' },
                { id: 60140, name: 'BUNDESI' },
                { id: 60754, name: 'BWAKUYE' },
                { id: 54095, name: 'GAJUMA' },
                { id: 54096, name: 'KASINGIDI' },
                { id: 66063, name: 'MASABASI' },
                { id: 67209, name: 'NAMAGUNGU' },
                { id: 67243, name: 'NAMANGO' },
                { id: 54093, name: 'TOGI' },
                { id: 54094, name: 'ZEMAGO DOWN' },
              ],
            },
            {
              id: 8601,
              name: 'NATABA',
              villages: [
                { id: 54106, name: 'MABIYA' },
                { id: 54110, name: 'MANYOLOLO' },
                { id: 54107, name: 'MASHELUSI' },
                { id: 54108, name: 'NAMUNDYU' },
                { id: 54105, name: 'NATAABA' },
                { id: 54109, name: 'ZESSOSOMI' },
              ],
            },
          ],
        },
        {
          id: 1826,
          name: 'BUMASOBO',
          parishes: [
            {
              id: 8622,
              name: 'BUGIMWERA',
              villages: [
                { id: 54367, name: 'BUGIMWERA' },
                { id: 54362, name: 'BUGIMWERA T.C' },
                { id: 54370, name: 'BUWODERO A' },
                { id: 54363, name: 'BUWODERO B' },
                { id: 54371, name: 'KIBEMBE' },
                { id: 54364, name: 'KILANJI' },
                { id: 54365, name: 'KISIRA' },
                { id: 54366, name: 'LUGUTA' },
                { id: 54372, name: 'LUZZI' },
                { id: 54373, name: 'MAFUTI' },
                { id: 54368, name: 'MASOLA' },
                { id: 54369, name: 'MUDANJE' },
                { id: 54374, name: 'NALWANDA' },
                { id: 54375, name: 'NANDEYO' },
              ],
            },
            {
              id: 8621,
              name: 'BUMASOBO',
              villages: [
                { id: 54360, name: 'KAGOLO' },
                { id: 54355, name: 'KAGORO T.C' },
                { id: 54356, name: 'KIBONDYE' },
                { id: 64148, name: 'KIYIRI' },
                { id: 54357, name: 'LUYIRI' },
                { id: 54361, name: 'NAMBEKYE A' },
                { id: 54359, name: 'NAMBEKYE B' },
                { id: 54358, name: 'SASA' },
              ],
            },
            {
              id: 8623,
              name: 'BUSHUNU',
              villages: [
                { id: 54381, name: 'BUSHUNU' },
                { id: 54376, name: 'BUSHUNU B' },
                { id: 54377, name: 'KIMAKA' },
                { id: 54382, name: 'KITANGA' },
                { id: 54383, name: 'MAWULULU' },
                { id: 54378, name: 'MAYIRA' },
                { id: 54379, name: 'NAKILULU' },
                { id: 54380, name: 'NASHUWU' },
              ],
            },
            {
              id: 8624,
              name: 'BUWOKADALA',
              villages: [
                { id: 54384, name: 'BUNAKUSI A' },
                { id: 54392, name: 'BUWOKADALA' },
                { id: 54393, name: 'BUWOKADALA TRADING CENTRE' },
                { id: 54395, name: 'KIGIKILI' },
                { id: 54391, name: 'KISABASI' },
                { id: 54394, name: 'KYEBOFU' },
                { id: 54396, name: 'LUGUDO' },
                { id: 54385, name: 'MAKUTANO' },
                { id: 54386, name: 'MANGASA' },
                { id: 54387, name: 'MAWOLELA' },
                { id: 54388, name: 'MAYIYI' },
                { id: 54397, name: 'MAYUMBA' },
                { id: 54389, name: 'NABYOKO' },
                { id: 54398, name: 'NAMUNYU' },
                { id: 54399, name: 'NAMWESENYI' },
                { id: 54390, name: 'NEGOKYE' },
              ],
            },
            {
              id: 8625,
              name: 'NAZWAZWA',
              villages: [
                { id: 54405, name: 'BUNABUSO' },
                { id: 54406, name: 'BUNAKUSI  B' },
                { id: 54401, name: 'MALUKU' },
                { id: 54407, name: 'NADELU EAST' },
                { id: 54402, name: 'NADERU WEST' },
                { id: 54403, name: 'NAMBUSI' },
                { id: 54400, name: 'NAZWAZWA A' },
                { id: 54404, name: 'NAZWAZWA B' },
              ],
            },
          ],
        },
        {
          id: 1831,
          name: 'BUMUGIBOLE',
          parishes: [
            {
              id: 8646,
              name: 'BUMASIFWA',
              villages: [
                { id: 54639, name: 'BUGINYANYA COMP' },
                { id: 59866, name: 'BUMUGIBOLE P/S' },
                { id: 54638, name: 'GABOLO' },
                { id: 54640, name: 'GIBOLE' },
                { id: 63442, name: 'KIDODO' },
                { id: 54641, name: 'LOGOLI' },
                { id: 54642, name: 'LOGOLI HILL' },
                { id: 54643, name: 'MADAMA' },
                { id: 54646, name: 'MALINYI' },
                { id: 54644, name: 'SAMAZI' },
                { id: 54645, name: 'SEKYENEZI' },
              ],
            },
            {
              id: 8647,
              name: 'BUMUGIBOLE',
              villages: [
                { id: 54647, name: 'BUMUGIBOLE' },
                { id: 54648, name: 'BUMUGIBOLE  T.C' },
                { id: 59865, name: 'BUMUGIBOLE  T.C II' },
                { id: 54649, name: 'CORNER' },
                { id: 54650, name: 'KIDONDOLOMU' },
                { id: 54651, name: 'KITAKA' },
                { id: 54658, name: 'LOGGI' },
                { id: 54652, name: 'LOGGI HILL' },
                { id: 54653, name: 'MASOLA' },
                { id: 54654, name: 'NAKIBANJE' },
                { id: 54657, name: 'NAKIZUBO' },
                { id: 67091, name: 'NAKIZUBO LOWER' },
                { id: 54659, name: 'NAMEZI' },
                { id: 54655, name: 'WANZIRA   T/C' },
                { id: 54661, name: 'WANZIRA A' },
                { id: 54660, name: 'WANZIRA B' },
                { id: 54656, name: 'ZEBULENYI II' },
              ],
            },
            {
              id: 8648,
              name: 'GAMANGWENI',
              villages: [
                { id: 54668, name: 'DIMBWE' },
                { id: 61128, name: 'DIMBWE UPPER' },
                { id: 54664, name: 'GAMANGWENI A' },
                { id: 54662, name: 'GAMANGWENI B' },
                { id: 54665, name: 'KISIYOPO' },
                { id: 54663, name: 'MAKUMA LOWER' },
                { id: 54666, name: 'MAKUMA UPPER' },
                { id: 54667, name: 'MALABILI' },
              ],
            },
            {
              id: 8649,
              name: 'LOGOLI',
              villages: [
                { id: 54669, name: 'BUGINYANYA T/C' },
                { id: 54670, name: 'GABOYISI' },
                { id: 54673, name: 'GOWOSI' },
                { id: 54674, name: 'LUSOZI' },
                { id: 54671, name: 'LUSOZI LOWER' },
                { id: 54675, name: 'MASEGESE' },
                { id: 54672, name: 'NABULUMBI' },
              ],
            },
            {
              id: 8650,
              name: 'MAYIYI',
              villages: [
                { id: 54681, name: 'GIBENJEYI' },
                { id: 54683, name: 'GOMBE' },
                { id: 54676, name: 'GULUMATI' },
                { id: 54677, name: 'HIGHWAY' },
                { id: 61521, name: 'HIGHWAY UPPER' },
                { id: 54678, name: 'KIFUTI' },
                { id: 63788, name: 'KIPELA' },
                { id: 54679, name: 'KIYEWA' },
                { id: 64228, name: 'KOLO' },
                { id: 54686, name: 'LUNGODO' },
                { id: 54685, name: 'LWANDA' },
                { id: 66080, name: 'MASENYA' },
                { id: 54687, name: 'MATUNDA' },
                { id: 54688, name: 'MAYIYI' },
                { id: 66166, name: 'MAYIYI P/S' },
                { id: 54680, name: 'MAYIYI T/C' },
                { id: 54682, name: 'NALUNGU' },
                { id: 54684, name: 'NYANZIYO' },
                { id: 54689, name: 'ZEBULENYI  I' },
              ],
            },
            {
              id: 8651,
              name: 'SUGUTA',
              villages: [
                { id: 54690, name: 'DUBANA' },
                { id: 54695, name: 'GIBENDIRA' },
                { id: 61370, name: 'GIBINDILA UPPER' },
                { id: 61372, name: 'GIBUZALE P/S' },
                { id: 54691, name: 'KOOTA' },
                { id: 54696, name: 'MAGUMBA' },
                { id: 54692, name: 'MAGUMBA T/C' },
                { id: 54693, name: 'MASEGESE' },
                { id: 66076, name: 'MASEJESE UPPER' },
                { id: 54697, name: 'SUGUTA' },
                { id: 54694, name: 'SUGUTA T/C' },
              ],
            },
          ],
        },
        {
          id: 1832,
          name: 'KAMU',
          parishes: [
            {
              id: 8652,
              name: 'KAMU',
              villages: [
                { id: 66808, name: 'NABAKYEYATU' },
                { id: 67189, name: 'NALWANDA' },
                { id: 54698, name: 'NASETA' },
                { id: 54699, name: 'NGEREBI' },
                { id: 69840, name: 'ROCK VIEW' },
                { id: 54700, name: 'SANGARISI' },
              ],
            },
            {
              id: 8653,
              name: 'KISENYI',
              villages: [
                { id: 61112, name: 'DEMBE' },
                { id: 62449, name: 'KAMU' },
                { id: 54701, name: 'KAMU TRADING CENTRE A' },
                { id: 54702, name: 'KAMU TRADING CENTRE C' },
                { id: 54703, name: 'KAMU TRADING CENTRE D' },
                { id: 63906, name: 'KISENYI A' },
                { id: 63908, name: 'KISENYI B' },
                { id: 65769, name: 'LWANDA' },
              ],
            },
            {
              id: 8654,
              name: 'MASABA',
              villages: [
                { id: 61240, name: 'ELGON' },
                { id: 54704, name: 'KAMU TRADING CENTRE B' },
                { id: 54705, name: 'KAMU TRADING CENTRE E' },
                { id: 63445, name: 'KIDONDOLOMU' },
                { id: 54706, name: 'KWEEN' },
                { id: 66139, name: 'MATUBA' },
              ],
            },
            {
              id: 8655,
              name: 'MASOLA',
              villages: [
                { id: 54707, name: 'KALEGENI' },
                { id: 54708, name: 'KATEGEIZA' },
                { id: 64143, name: 'KIYEMBE' },
                { id: 65776, name: 'LWANDA C' },
                { id: 66095, name: 'MASOLA' },
                { id: 67077, name: 'NAKISWA' },
                { id: 69831, name: 'RIVER SIDE' },
              ],
            },
            {
              id: 8656,
              name: 'SOMI',
              villages: [
                { id: 54710, name: 'FINATARA' },
                { id: 54709, name: 'KAMUNDA' },
                { id: 63223, name: 'KAYEMBE' },
                { id: 70522, name: 'SOMI' },
                { id: 54711, name: 'YEMBE' },
              ],
            },
          ],
        },
        {
          id: 1827,
          name: 'LUSHA',
          parishes: [
            {
              id: 8626,
              name: 'BUMWAMBU',
              villages: [
                { id: 54420, name: 'BUMWAMBU' },
                { id: 54408, name: 'BUMWAMBU  CORNER' },
                { id: 54409, name: 'BUNABUMBO' },
                { id: 61033, name: 'CHUMA' },
                { id: 54410, name: 'GAMUSHENYI  A' },
                { id: 54411, name: 'GAMUSHENYI  B' },
                { id: 54421, name: 'GOMBE A' },
                { id: 54422, name: 'GOMBE B' },
                { id: 54412, name: 'GUNDU A' },
                { id: 61451, name: 'GUNDU B' },
                { id: 54423, name: 'KADDE' },
                { id: 54424, name: 'KIDEGA' },
                { id: 63953, name: 'KISOTANI' },
                { id: 54425, name: 'KISOYA A' },
                { id: 54426, name: 'KISOYA B' },
                { id: 54413, name: 'KISUBI A' },
                { id: 54427, name: 'KISUBI B' },
                { id: 54414, name: 'LUSHA A' },
                { id: 54428, name: 'LUSHA B' },
                { id: 54429, name: 'LWATALI' },
                { id: 65820, name: 'MABALE' },
                { id: 65853, name: 'MADAMA' },
                { id: 54430, name: 'MADONDOLOMU' },
                { id: 65868, name: 'MADOTE' },
                { id: 54415, name: 'MAGIGETI A' },
                { id: 54419, name: 'MAGIGETI B' },
                { id: 54431, name: 'MAGIKILI A' },
                { id: 65887, name: 'MAGIKILI B' },
                { id: 66061, name: 'MASABASI' },
                { id: 54416, name: 'MASEGESE' },
                { id: 54432, name: 'MISSION' },
                { id: 54433, name: 'NAKITWE' },
                { id: 54417, name: 'NAKWALE A' },
                { id: 54434, name: 'NAKWALE B' },
                { id: 54418, name: 'NAMAHE' },
                { id: 54435, name: 'PIIYI' },
                { id: 54436, name: 'STAGE' },
                { id: 71172, name: 'WOGALASA' },
              ],
            },
            {
              id: 8628,
              name: 'BUNABUDE',
              villages: [
                { id: 54450, name: 'BUGATISA' },
                { id: 54451, name: 'KABALE' },
                { id: 54452, name: 'KIDEGA' },
                { id: 54455, name: 'KINGANDA' },
                { id: 54453, name: 'KINGANDA T.C' },
                { id: 54454, name: 'KISABASI' },
                { id: 54463, name: 'KISIYOPO' },
                { id: 54464, name: 'KISUBI' },
                { id: 54465, name: 'KIYEWA' },
                { id: 54456, name: 'LUKUNGU' },
                { id: 54466, name: 'MALINDI' },
                { id: 54457, name: 'MATUNDA' },
                { id: 54458, name: 'MAYIYI A' },
                { id: 54467, name: 'MAYIYI B' },
                { id: 54468, name: 'NABUTONYA' },
                { id: 54460, name: 'NAGABITA A' },
                { id: 54459, name: 'NAGABITA B' },
                { id: 54461, name: 'SISIYI A' },
                { id: 54469, name: 'SISIYI B' },
                { id: 54462, name: 'SUGUTA' },
                { id: 54470, name: 'ZEBUTYONYI' },
              ],
            },
            {
              id: 8629,
              name: 'GOMBE',
              villages: [
                { id: 54471, name: 'GABUSIRONI  A' },
                { id: 54472, name: 'GABUSIRONI  B' },
                { id: 54473, name: 'GOMBE A' },
                { id: 54483, name: 'GOMBE B' },
                { id: 54484, name: 'KIBONDYE' },
                { id: 54474, name: 'KIGOMU' },
                { id: 54485, name: 'KIGOMU LOWER' },
                { id: 54486, name: 'KIKUYU' },
                { id: 54487, name: 'KISECHE' },
                { id: 54475, name: 'LUSHA' },
                { id: 54476, name: 'LWANIKO' },
                { id: 54488, name: 'MAGIKIRI' },
                { id: 54489, name: 'MAGUMBA' },
                { id: 54490, name: 'MASOLA T.C' },
                { id: 54477, name: 'MASOOLA' },
                { id: 54491, name: 'MUDANJE' },
                { id: 54492, name: 'NABISALA' },
                { id: 54478, name: 'NAKITEMBETI' },
                { id: 54479, name: 'NASHUWU  A' },
                { id: 54480, name: 'NASHUWU  B' },
                { id: 54493, name: 'NESANGA' },
                { id: 54481, name: 'NIGGO' },
                { id: 54494, name: 'NIGGO T.C' },
                { id: 54482, name: 'ZEBUTUMI' },
              ],
            },
            {
              id: 8630,
              name: 'JEWA',
              villages: [
                { id: 54497, name: 'BUNONAGA' },
                { id: 54496, name: 'KIDOLO' },
                { id: 54505, name: 'KIKAMELI' },
                { id: 54502, name: 'KIKAMOSI' },
                { id: 54503, name: 'KINOKO  A' },
                { id: 54504, name: 'KINOKO  B' },
                { id: 54498, name: 'NAMAKOLO A' },
                { id: 54499, name: 'NAMAKOLO B' },
                { id: 54506, name: 'NAMBOGA A' },
                { id: 54495, name: 'NAMBOGA B' },
                { id: 54500, name: 'NANOGA' },
                { id: 54507, name: 'SOBEZI' },
                { id: 54501, name: 'TAMUNYINI' },
                { id: 54508, name: 'TIRIGIMA' },
              ],
            },
            {
              id: 8627,
              name: 'KINGANDA',
              villages: [
                { id: 54439, name: 'BUGATISA' },
                { id: 54437, name: 'KIDEGA' },
                { id: 54438, name: 'KINGANDA' },
                { id: 54440, name: 'KINGANDA T.C' },
                { id: 54441, name: 'KISIRA' },
                { id: 54442, name: 'KISIYOPO' },
                { id: 54443, name: 'KIYEWA' },
                { id: 54444, name: 'MALINDI' },
                { id: 54445, name: 'SISIYI A' },
                { id: 54446, name: 'SISIYI B' },
                { id: 54447, name: 'SUGUTA' },
                { id: 54448, name: 'SUGUTA T.C' },
                { id: 54449, name: 'ZEBOLE' },
              ],
            },
          ],
        },
        {
          id: 1823,
          name: 'MASIRA',
          parishes: [
            {
              id: 8607,
              name: 'DUNGA',
              villages: [
                { id: 54151, name: 'DEMBE' },
                { id: 54154, name: 'DIBBU' },
                { id: 54156, name: 'DUNGA' },
                { id: 54152, name: 'KABALE' },
                { id: 54153, name: 'KIFUNGU' },
                { id: 54155, name: 'KIKOOLO' },
                { id: 54158, name: 'KIMWEMWE' },
                { id: 54160, name: 'KISOTONI' },
                { id: 54157, name: 'KIYEWA' },
                { id: 54159, name: 'LUKOOLO' },
                { id: 54161, name: 'LUSASO' },
                { id: 54163, name: 'MASUBI' },
                { id: 54162, name: 'NABUYOMBO' },
              ],
            },
            {
              id: 8606,
              name: 'GABUGOTO',
              villages: [
                { id: 54138, name: 'BUNABIKWATU A' },
                { id: 54140, name: 'BUNABIKWATU B' },
                { id: 54139, name: 'GABUGOTO' },
                { id: 54142, name: 'GOMBE A' },
                { id: 54141, name: 'GOMBE B' },
                { id: 54145, name: 'KIDEGA' },
                { id: 54143, name: 'KILUMATI' },
                { id: 54144, name: 'MADUWA A' },
                { id: 54147, name: 'MADUWA B' },
                { id: 54148, name: 'NABIWA' },
                { id: 54150, name: 'NAKISSA' },
                { id: 54149, name: 'NAKITEBWE LOWER' },
                { id: 54146, name: 'NAKITEBWE UPPER' },
              ],
            },
            {
              id: 8608,
              name: 'GANZO',
              villages: [
                { id: 54164, name: 'GABAATI' },
                { id: 54166, name: 'GANZO' },
                { id: 54167, name: 'GIBUZALE A' },
                { id: 54165, name: 'GIBUZALE B' },
                { id: 54168, name: 'KILABILI' },
                { id: 54169, name: 'KIMULI' },
                { id: 54173, name: 'KITOBO' },
                { id: 54170, name: 'MADAMA' },
                { id: 54171, name: 'MAKUTANO' },
                { id: 54174, name: 'MASESEGWA A' },
                { id: 54172, name: 'MASESEGWA B' },
                { id: 54175, name: 'ZENIGINI' },
              ],
            },
            {
              id: 8609,
              name: 'KIKOBERO',
              villages: [
                { id: 54181, name: 'KIDEREMA A' },
                { id: 54176, name: 'KIDEREMA B' },
                { id: 54183, name: 'KIKOBERO A' },
                { id: 54184, name: 'KIKOBERO B' },
                { id: 54177, name: 'KIKOBERO C' },
                { id: 54178, name: 'KIKOBERO D' },
                { id: 54179, name: 'KIKOBERO E' },
                { id: 54180, name: 'KIKOBERO F' },
                { id: 54185, name: 'MASIRA' },
                { id: 54182, name: 'NAMANGUYI' },
                { id: 54186, name: 'RESEARCH STATION' },
              ],
            },
            {
              id: 8610,
              name: 'KINYOFU',
              villages: [
                { id: 54190, name: 'KIFUDI' },
                { id: 54187, name: 'KIFUTI' },
                { id: 54191, name: 'KINYOFU A' },
                { id: 54188, name: 'KINYOFU B' },
                { id: 54192, name: 'KISAGALI' },
                { id: 54189, name: 'KIYEWA' },
              ],
            },
          ],
        },
        {
          id: 1822,
          name: 'NABIWUTULU',
          parishes: [
            {
              id: 8604,
              name: 'DOOBA',
              villages: [
                { id: 54120, name: 'DOOBA' },
                { id: 54121, name: 'GAJISINZA' },
                { id: 54122, name: 'GIBANGANYI' },
                { id: 54125, name: 'KIDEGA' },
                { id: 54128, name: 'MABAMBU' },
                { id: 54126, name: 'MAKUTANO' },
                { id: 54127, name: 'MASIYOPO' },
                { id: 54123, name: 'NABIWUTULU' },
                { id: 54129, name: 'NABYOKO' },
                { id: 54124, name: 'NAKIMALI' },
              ],
            },
            {
              id: 8602,
              name: 'GABUSOGOLOLO',
              villages: [
                { id: 54111, name: 'BITOBO' },
                { id: 54112, name: 'GABUSOGOLOLO' },
                { id: 61323, name: 'GABUSOGOLOLO T/C' },
                { id: 63434, name: 'KIDEGA' },
                { id: 66062, name: 'MASABASI' },
                { id: 54113, name: 'MASUBI' },
                { id: 54114, name: 'NASHEMBULE' },
              ],
            },
            {
              id: 8603,
              name: 'LUGOBA',
              villages: [
                { id: 54115, name: 'LUGOBA' },
                { id: 54117, name: 'MAKOGOTI' },
                { id: 54116, name: 'NAMBALENZE' },
                { id: 54118, name: 'SUGUTA' },
                { id: 54119, name: 'ZANZIBAR' },
              ],
            },
            {
              id: 8605,
              name: 'TUNYI',
              villages: [
                { id: 54134, name: 'DOKO' },
                { id: 54130, name: 'KIBANGA' },
                { id: 54135, name: 'MAYIRA' },
                { id: 54131, name: 'NAKIDOKO' },
                { id: 54136, name: 'NAKITAMBASI' },
                { id: 54132, name: 'NAMANGO' },
                { id: 54133, name: 'TUNYI' },
                { id: 54137, name: 'ZESUI HILL' },
              ],
            },
          ],
        },
        {
          id: 1828,
          name: 'NAMISUNI',
          parishes: [
            {
              id: 8632,
              name: 'GAMATIMBEI',
              villages: [
                { id: 54521, name: 'BUNAYIWA' },
                { id: 54519, name: 'GAMATIMBEI  A' },
                { id: 54520, name: 'GAMATIMBEI  B' },
                { id: 54522, name: 'KALITUSI T.C' },
                { id: 54525, name: 'MARAMA A' },
                { id: 54523, name: 'MARAMA T.C' },
                { id: 54526, name: 'NABUZIBA' },
                { id: 54524, name: 'NALUMBA' },
              ],
            },
            {
              id: 8633,
              name: 'KISEKYE',
              villages: [
                { id: 54527, name: 'GUBALE' },
                { id: 54528, name: 'INDAIGA' },
                { id: 54529, name: 'KIFUNGU' },
                { id: 54530, name: 'KIFUTI' },
                { id: 54531, name: 'KISASA' },
                { id: 54532, name: 'KISEKYE A' },
                { id: 54533, name: 'KISEKYE B' },
                { id: 54535, name: 'NABUMIZO' },
                { id: 54536, name: 'NEDUNDE' },
                { id: 54534, name: 'RUNGODO' },
              ],
            },
            {
              id: 8634,
              name: 'LUSASO',
              villages: [
                { id: 54537, name: 'GAMASHELO' },
                { id: 54538, name: 'GIBUZALE' },
                { id: 54539, name: 'KAMULI' },
                { id: 54543, name: 'KIGOMU' },
                { id: 54544, name: 'KISIYOPO' },
                { id: 54540, name: 'KIZUBI' },
                { id: 54541, name: 'KYUMA T.C' },
                { id: 54545, name: 'LUSASO' },
                { id: 54542, name: 'MADONDOLOMU' },
                { id: 54546, name: 'MAGIKILI' },
                { id: 54547, name: 'MALUKU' },
                { id: 54548, name: 'NAKIKAMELI' },
                { id: 54549, name: 'TOBBONGONI' },
              ],
            },
            {
              id: 8635,
              name: 'NAMBEKYE',
              villages: [
                { id: 54550, name: 'KABALE' },
                { id: 54551, name: 'KINGANGA' },
                { id: 54552, name: 'LUKUNGU' },
                { id: 54555, name: 'MAPELA' },
                { id: 54556, name: 'MASOLA A' },
                { id: 54553, name: 'MASOLA B' },
                { id: 54554, name: 'NAKITEMBETI' },
                { id: 54557, name: 'NAMBEKYE' },
                { id: 54558, name: 'NEDILE' },
              ],
            },
            {
              id: 8636,
              name: 'NAMEZI',
              villages: [
                { id: 54562, name: 'KALITUSI A' },
                { id: 54559, name: 'KALITUSI B' },
                { id: 54560, name: 'KAMWANYI' },
                { id: 54563, name: 'MAKUYU A' },
                { id: 54561, name: 'MAKUYU B' },
                { id: 54564, name: 'MATUGUTU' },
                { id: 54565, name: 'NAMEZI' },
              ],
            },
            {
              id: 8631,
              name: 'NAMISUNI',
              villages: [
                { id: 54513, name: 'KIFUDU' },
                { id: 54509, name: 'KIKOLO EAST' },
                { id: 54514, name: 'KIKOLO WEST' },
                { id: 54515, name: 'KIKUYU' },
                { id: 54510, name: 'KIKUYU T.C' },
                { id: 54511, name: 'KIYEMBE' },
                { id: 54512, name: 'MASASA' },
                { id: 54516, name: 'NABOTWA' },
                { id: 54517, name: 'NABYOKO' },
                { id: 54518, name: 'NEGOKYE' },
              ],
            },
            {
              id: 8637,
              name: 'NAMUDONGO',
              villages: [
                { id: 54566, name: 'BODDA' },
                { id: 54567, name: 'DINDIMWA' },
                { id: 54570, name: 'DUBBIKI' },
                { id: 54568, name: 'GUZUZWA' },
                { id: 54573, name: 'LUZZI' },
                { id: 54569, name: 'MABONO' },
                { id: 54571, name: 'MAKUYU' },
                { id: 54572, name: 'MULIMANI' },
                { id: 54574, name: 'NALUFUDU' },
                { id: 54575, name: 'NAMUDONGO' },
              ],
            },
          ],
        },
        {
          id: 1829,
          name: 'SIMU',
          parishes: [
            {
              id: 8639,
              name: 'BUKIBOLOGOTO',
              villages: [
                { id: 54581, name: 'KIBOLOGOTO' },
                { id: 54583, name: 'KIDIBO' },
                { id: 54580, name: 'KIDIBO T.C' },
                { id: 67073, name: 'NAKISALI' },
                { id: 54586, name: 'NAKIZUBO' },
                { id: 54585, name: 'NAKIZUNGU T.C' },
                { id: 54587, name: 'SOBEZI' },
                { id: 54582, name: 'ZEBOLE' },
                { id: 54584, name: 'ZEBUJILA' },
              ],
            },
            {
              id: 8640,
              name: 'KIDEGA',
              villages: [
                { id: 54593, name: 'KASELA' },
                { id: 54591, name: 'KIDEGA' },
                { id: 54592, name: 'KIDEGA T/C' },
                { id: 54588, name: 'LONGOTI' },
                { id: 54590, name: 'LUKUNGU' },
                { id: 54595, name: 'LWANDA' },
                { id: 54596, name: 'NABINYINYA' },
                { id: 54597, name: 'NABINYINYA  NORTH' },
                { id: 54589, name: 'SWESWETA' },
                { id: 54594, name: 'WANDABILI' },
              ],
            },
            {
              id: 8641,
              name: 'KIKUYU',
              villages: [
                { id: 54606, name: 'JUNGONI' },
                { id: 54604, name: 'KIKUYU' },
                { id: 54609, name: 'KILOGOZI' },
                { id: 54601, name: 'KILWASI' },
                { id: 54602, name: 'MAKOTO' },
                { id: 54599, name: 'MALEKA' },
                { id: 54600, name: 'MASOLA CENTRE' },
                { id: 54607, name: 'MATAZAFU' },
                { id: 54605, name: 'NAGABITA' },
                { id: 54608, name: 'NAMANDA' },
                { id: 54603, name: 'SONGOGWA' },
                { id: 54598, name: 'TABATI' },
              ],
            },
            {
              id: 8638,
              name: 'SAVANNAH',
              villages: [
                { id: 54577, name: 'MBALA' },
                { id: 54576, name: 'NAKIZUBO T.C' },
                { id: 67092, name: 'NAKIZUNGU' },
                { id: 54579, name: 'ZEBALAGWA' },
                { id: 54578, name: 'ZEMALANYI' },
              ],
            },
            {
              id: 8642,
              name: 'SIMU',
              villages: [
                { id: 54610, name: 'DEMBE A' },
                { id: 54611, name: 'DEMBE B' },
                { id: 54618, name: 'LUKONJE' },
                { id: 54612, name: 'MABALE' },
                { id: 54613, name: 'MAGIKILI' },
                { id: 54616, name: 'MASABASI' },
                { id: 54617, name: 'MATUBA' },
                { id: 54614, name: 'MAYEMBE' },
                { id: 54615, name: 'SASA' },
                { id: 54620, name: 'SIMU A' },
                { id: 54621, name: 'SIMU B' },
                { id: 54619, name: 'TANKA' },
              ],
            },
          ],
        },
        {
          id: 1825,
          name: 'SISIYI',
          parishes: [
            {
              id: 8616,
              name: 'BUMUGUSHA',
              villages: [
                { id: 54246, name: 'BOGOYA' },
                { id: 54248, name: 'GABUTENGANI' },
                { id: 54247, name: 'GABUTUI' },
                { id: 54250, name: 'GIZOMBE' },
                { id: 54249, name: 'JEWA' },
                { id: 54252, name: 'KIBEYI' },
                { id: 54251, name: 'KILOMBE' },
                { id: 54253, name: 'LUGUDO' },
                { id: 54254, name: 'MADAMA' },
                { id: 54255, name: 'MAKOBA' },
                { id: 54264, name: 'NABIGUNGU A' },
                { id: 54256, name: 'NABIGUNGU B' },
                { id: 54257, name: 'NABINYINYA' },
                { id: 54259, name: 'NABINYINYA SOUTH' },
                { id: 54265, name: 'NABISULULA' },
                { id: 54266, name: 'NABUYA' },
                { id: 54260, name: 'NALUNGORO' },
                { id: 54258, name: 'NALWANDA' },
                { id: 54263, name: 'SUGUTA A' },
                { id: 54261, name: 'SUGUTA B' },
                { id: 54262, name: 'SWESWETA' },
              ],
            },
            {
              id: 8615,
              name: 'GIBUZALE',
              villages: [
                { id: 54228, name: 'BANANA' },
                { id: 54229, name: 'BUGWA' },
                { id: 54230, name: 'DAMALI' },
                { id: 54231, name: 'GIDUNO' },
                { id: 54234, name: 'GUVULE' },
                { id: 54232, name: 'KIKOLO' },
                { id: 54237, name: 'KIKOMOSI' },
                { id: 54238, name: 'KILWASI' },
                { id: 63958, name: 'KISOTONO' },
                { id: 54233, name: 'KITONDWANI' },
                { id: 54241, name: 'KIYEMBE' },
                { id: 54242, name: 'KIZUBI' },
                { id: 54235, name: 'LWANGO' },
                { id: 54240, name: 'MAGIKILI' },
                { id: 54236, name: 'MAYIYI' },
                { id: 54239, name: 'NABIGUMBA' },
                { id: 54243, name: 'NABUZIBA' },
                { id: 54244, name: 'NALUMBA' },
                { id: 54245, name: 'NANDELE' },
              ],
            },
            {
              id: 8617,
              name: 'KIBANDA',
              villages: [
                { id: 54267, name: 'CYPRUS' },
                { id: 54270, name: 'GIBUTERERE' },
                { id: 54272, name: 'GOLOBETEYI' },
                { id: 54268, name: 'KAMWANYI' },
                { id: 54269, name: 'KAPANGA' },
                { id: 54274, name: 'KIBANDA A' },
                { id: 54271, name: 'KIBANDA B' },
                { id: 54275, name: 'KIKAMERI' },
                { id: 54273, name: 'LAMEKA' },
                { id: 54283, name: 'LUGUTE' },
                { id: 54277, name: 'LUKUNGU' },
                { id: 54276, name: 'LUNGODO' },
                { id: 54286, name: 'LUWANGO' },
                { id: 54278, name: 'MABALE' },
                { id: 54279, name: 'MASABASI' },
                { id: 54280, name: 'MASIYOPO' },
                { id: 54287, name: 'NABINO' },
                { id: 54281, name: 'NAKIDIBA' },
                { id: 54282, name: 'NAKITAMBASI' },
                { id: 54284, name: 'NAKITOKOLO' },
                { id: 54285, name: 'NAKITWE' },
                { id: 54288, name: 'WANDABIRI' },
              ],
            },
            {
              id: 8618,
              name: 'KISUBI',
              villages: [
                { id: 54289, name: 'GAMADYA' },
                { id: 54290, name: 'GIBETWA' },
                { id: 54291, name: 'KIKOLO' },
                { id: 54294, name: 'KISUBI A' },
                { id: 54292, name: 'KISUBI B' },
                { id: 54293, name: 'KITANGALU' },
                { id: 54298, name: 'MAKOBA' },
                { id: 54296, name: 'MALIMBE' },
                { id: 54300, name: 'NABUGASHA A' },
                { id: 54297, name: 'NABUNGASHA B' },
                { id: 54301, name: 'NAGUDI' },
                { id: 54295, name: 'NALUSISI' },
                { id: 54302, name: 'NAMAKOLA' },
                { id: 54299, name: 'WESUKA' },
              ],
            },
            {
              id: 8619,
              name: 'LUZZI',
              villages: [
                { id: 54303, name: 'BILINDA' },
                { id: 54304, name: 'BILINDA CENTRE' },
                { id: 54308, name: 'GINGOLI' },
                { id: 54306, name: 'GIZANDA' },
                { id: 54305, name: 'GUNDU' },
                { id: 54307, name: 'KAJEERE' },
                { id: 54310, name: 'KIKUYU' },
                { id: 54312, name: 'KISIYOPO' },
                { id: 54309, name: 'LUZZI' },
                { id: 54313, name: 'MASOLA CENTRE' },
                { id: 54311, name: 'MASOOLA' },
                { id: 54314, name: 'MATAGALU' },
                { id: 54319, name: 'NAMUNGU A' },
                { id: 54315, name: 'NAMUNGU B' },
                { id: 54320, name: 'NAMWERU' },
                { id: 54316, name: 'NIIGO' },
                { id: 54321, name: 'SOWESI A' },
                { id: 54317, name: 'SOWESI B' },
                { id: 54318, name: 'TABALI A' },
                { id: 54324, name: 'TABALI B' },
                { id: 54323, name: 'ZAMALENYI' },
                { id: 54322, name: 'ZEMANENYI' },
              ],
            },
            {
              id: 8620,
              name: 'MABONO',
              villages: [
                { id: 54326, name: 'BUMWIDYEKI' },
                { id: 54325, name: 'COAST' },
                { id: 54327, name: 'GIBUGENDOWA' },
                { id: 54329, name: 'GIMAYOTE' },
                { id: 54330, name: 'KAMWANYI' },
                { id: 54331, name: 'KIBUKU' },
                { id: 54332, name: 'KIJEWA' },
                { id: 54328, name: 'KIKAI B' },
                { id: 54333, name: 'KIKAJO' },
                { id: 54346, name: 'KIKAYI A' },
                { id: 54334, name: 'KILUKO' },
                { id: 54336, name: 'KIMULI' },
                { id: 54337, name: 'KIMWEMWE' },
                { id: 54338, name: 'KISOTEYI' },
                { id: 54342, name: 'LUKOLA' },
                { id: 54353, name: 'MABALE' },
                { id: 54343, name: 'MABONO' },
                { id: 54344, name: 'MADOLODOLO' },
                { id: 54345, name: 'MADWAYA' },
                { id: 54341, name: 'MAGONA' },
                { id: 54349, name: 'MAGUJE' },
                { id: 54347, name: 'MAKONJE A' },
                { id: 54350, name: 'MAKONJE B' },
                { id: 54348, name: 'MARAMA' },
                { id: 54335, name: 'MASABASI' },
                { id: 54352, name: 'NAKIDIBO' },
                { id: 54351, name: 'NAKIFUMBUKO' },
                { id: 54354, name: 'NASHEMBULE' },
                { id: 54340, name: 'RWANDA A' },
                { id: 54339, name: 'RWANDA B' },
              ],
            },
          ],
        },
        {
          id: 1824,
          name: 'SOTTI',
          parishes: [
            {
              id: 8611,
              name: 'BUNABAHALA',
              villages: [
                { id: 54196, name: 'BUNABAHALA B' },
                { id: 54197, name: 'BUNABAHALA TRADING CENTRE' },
                { id: 54198, name: 'BUNAGIBUNDU' },
                { id: 61325, name: 'GAJIMA' },
                { id: 61329, name: 'GAMATUYI' },
                { id: 61390, name: 'GODOWN' },
                { id: 54193, name: 'LINE T.C' },
                { id: 54194, name: 'MAJEWA' },
                { id: 54195, name: 'NABUJENERWA' },
                { id: 70535, name: 'SOTTI' },
                { id: 54199, name: 'ZESELENI' },
              ],
            },
            {
              id: 8612,
              name: 'BUNAMBOZO',
              villages: [
                { id: 54203, name: 'BUNAMBOZO' },
                { id: 54200, name: 'DEMBELELA A' },
                { id: 54201, name: 'DEMBELELA B' },
                { id: 62970, name: 'KASINGIDI' },
                { id: 54202, name: 'KOTA' },
                { id: 54206, name: 'KYAKOMA' },
                { id: 54205, name: 'NABIDETE' },
                { id: 54207, name: 'NABODI' },
                { id: 54208, name: 'NASANZA' },
                { id: 54204, name: 'WANDEGEYI' },
              ],
            },
            {
              id: 8613,
              name: 'MARAMA',
              villages: [
                { id: 54209, name: 'BUGIBUTUYA' },
                { id: 54210, name: 'DUBIKYI' },
                { id: 54212, name: 'GILUNGO' },
                { id: 54213, name: 'MALAMA' },
                { id: 54211, name: 'NABUHEMBA' },
              ],
            },
            {
              id: 8614,
              name: 'SOTTI',
              villages: [
                { id: 54215, name: 'BUKYAWO' },
                { id: 54216, name: 'BUMELU' },
                { id: 54220, name: 'GAMATUI' },
                { id: 54222, name: 'GIDIONYI' },
                { id: 54224, name: 'GODOWN' },
                { id: 54225, name: 'GOMBE' },
                { id: 54214, name: 'KIKOLO' },
                { id: 54221, name: 'KITWE' },
                { id: 54223, name: 'NAKILULU' },
                { id: 54227, name: 'NALUTASO' },
                { id: 54217, name: 'NAMAGUDE T.C' },
                { id: 54226, name: 'NANGABO' },
                { id: 54218, name: 'NEDUNDE' },
                { id: 54219, name: 'SOTTI' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
