import { District } from '../types';

export default <District>{
  id: 3,
  name: 'BUNDIBUGYO',
  counties: [
    {
      id: 11,
      name: 'BUGHENDERA COUNTY',
      sub_counties: [
        {
          id: 53,
          name: 'BUKONZO',
          parishes: [
            {
              id: 284,
              name: 'BUHUNDU',
              villages: [
                { id: 2105, name: 'HUMYA' },
                { id: 61528, name: 'HUMYA I' },
                { id: 2106, name: 'TWANZANE' },
                { id: 2107, name: 'TWANZANE CENTRAL' },
                { id: 70887, name: 'TWANZANE III' },
              ],
            },
            {
              id: 283,
              name: 'BUKANGAMA',
              villages: [
                { id: 2101, name: 'KATUMBA' },
                { id: 2100, name: 'KATUMBA CENTRAL' },
                { id: 2102, name: 'KIDEDE' },
                { id: 2104, name: 'KIDEDE II' },
                { id: 63889, name: 'KISENDERA' },
                { id: 2103, name: 'KYAMUKUBE CENTRAL' },
                { id: 64651, name: 'KYAMUKUBE MIDDLE' },
              ],
            },
            {
              id: 285,
              name: 'IRAMBURA',
              villages: [
                { id: 2108, name: 'BUKANGAMA' },
                { id: 2109, name: 'BULIMBA    I' },
                { id: 2110, name: 'BULIMBA    II' },
                { id: 2113, name: 'BULIMBA    III' },
                { id: 2111, name: 'BUTWAKA  I' },
                { id: 2112, name: 'BUTWAKA  II' },
                { id: 2114, name: 'BUTWAKA  III' },
                { id: 60791, name: 'BWERINDE' },
                { id: 2115, name: 'IRAMBURA' },
                { id: 61656, name: 'IRAMBURA CENTRAL' },
              ],
            },
            {
              id: 286,
              name: 'KATSANGIRWA',
              villages: [
                { id: 2119, name: 'BUHUNDU' },
                { id: 59700, name: 'BULHAMBAYIRI' },
                { id: 2116, name: 'KALEBYA' },
                { id: 2120, name: 'KALEBYA II' },
                { id: 2117, name: 'KIBUNANO' },
                { id: 2121, name: 'KIBUNANO II' },
                { id: 2118, name: 'KITSANGIRWA' },
                { id: 66488, name: 'MUGHOMBA II' },
              ],
            },
            {
              id: 287,
              name: 'KITUTI',
              villages: [
                { id: 2122, name: 'BUKANGAMA  II' },
                { id: 59448, name: 'BUKANGAMA  III' },
                { id: 60193, name: 'BUNYAMBURURU' },
                { id: 62104, name: 'KAGONGO' },
                { id: 2124, name: 'KAHEMBE' },
                { id: 2125, name: 'KITUTI' },
                { id: 2123, name: 'KYAMUKUBE' },
              ],
            },
          ],
        },
        {
          id: 57,
          name: 'BURONDO',
          parishes: [
            {
              id: 301,
              name: 'BURONDO',
              villages: [
                { id: 2230, name: 'BURONDO  I' },
                { id: 2231, name: 'BURONDO  II' },
                { id: 2229, name: 'BURONDO CENTRAL' },
                { id: 2227, name: 'KINYAMBOGO' },
                { id: 2228, name: 'RWAKASENYI' },
              ],
            },
            {
              id: 302,
              name: 'KARAMBI',
              villages: [
                { id: 2232, name: 'BURANGAPASI I' },
                { id: 2237, name: 'BURANGAPASI II' },
                { id: 2233, name: 'KARAMBI I' },
                { id: 2241, name: 'KARAMBI II' },
                { id: 2234, name: 'KINONI I' },
                { id: 2235, name: 'KINONI II' },
                { id: 2236, name: 'KINONI III' },
                { id: 2238, name: 'KINYANJOJO I' },
                { id: 2239, name: 'KINYANJOJO II' },
                { id: 2240, name: 'KINYANJOJO III' },
                { id: 2242, name: 'MURAMBI' },
              ],
            },
            {
              id: 303,
              name: 'MWEMBI',
              villages: [
                { id: 2249, name: 'KANYANGEYA' },
                { id: 2243, name: 'KINYANJOJO' },
                { id: 2244, name: 'KITHOMA' },
                { id: 2245, name: 'MURAMBI II' },
                { id: 2246, name: 'MWEMBI I' },
                { id: 2247, name: 'MWEMBI II' },
                { id: 2248, name: 'NYAMISEKE' },
              ],
            },
            {
              id: 304,
              name: 'SEMPAYA',
              villages: [
                { id: 2250, name: 'BURONDO III' },
                { id: 2252, name: 'KYAKATIMBA I' },
                { id: 2253, name: 'KYAKATIMBA II' },
                { id: 2251, name: 'SEMPAYA' },
              ],
            },
          ],
        },
        {
          id: 61,
          name: 'BUTAMA-MITUNDA TOWN COUNCIL',
          parishes: [
            {
              id: 320,
              name: 'BUNDIMBUGA WARD',
              villages: [
                { id: 2334, name: 'BUNDIMBUGA CENTRAL' },
                { id: 2338, name: 'BUNDIMBUGA EAST' },
                { id: 2335, name: 'BUNDIMBUGA I' },
                { id: 2336, name: 'BUNDIMBUGA II' },
                { id: 60145, name: 'BUNDIMBUGA NORTH' },
                { id: 2337, name: 'BUNDIMBUGA SOUTH' },
                { id: 2333, name: 'BUNDIMBUGA WEST' },
              ],
            },
            {
              id: 321,
              name: 'BUNDINJONGYA WARD',
              villages: [
                { id: 2340, name: 'BUNDINJONGYA' },
                { id: 2339, name: 'BUNDINJONGYA CENTRAL' },
                { id: 2341, name: 'BUNDINJONGYA II' },
                { id: 2344, name: 'CENTRAL' },
                { id: 2342, name: 'HABUSAGI' },
                { id: 2345, name: 'MANKONGOBERE' },
                { id: 2343, name: 'NADULE' },
              ],
            },
            {
              id: 322,
              name: 'BUTAMA CENTRAL WARD',
              villages: [
                { id: 2347, name: 'BUNDIMBUGA' },
                { id: 2349, name: 'IRANGO' },
                { id: 2346, name: 'KISANGA' },
                { id: 2348, name: 'KITEMBO' },
                { id: 2350, name: 'KUDI' },
                { id: 2351, name: 'NDUGUTU' },
                { id: 2353, name: 'NYABIYONGA' },
                { id: 2352, name: 'NYAKABUGHA' },
              ],
            },
            {
              id: 323,
              name: 'KAHIMBI WARD',
              villages: [
                { id: 2354, name: 'BUHALO' },
                { id: 2356, name: 'BUNSERU' },
                { id: 60185, name: 'BUNSERU EAST' },
                { id: 2355, name: 'BUNSERU II' },
                { id: 60186, name: 'BUNSERU SOUTH' },
                { id: 63591, name: 'KIJANJABHA' },
              ],
            },
            {
              id: 324,
              name: 'KITENGYA WARD',
              villages: [
                { id: 2357, name: 'BBUBANDA-KITENGYA' },
                { id: 2358, name: 'KITENGYA  I' },
                { id: 2359, name: 'KITENGYA  II' },
                { id: 64026, name: 'KITENGYA III' },
                { id: 64027, name: 'KITENGYA NORTH' },
                { id: 64028, name: 'KITENGYA SOUTH' },
              ],
            },
            {
              id: 319,
              name: 'MUTUNDA WARD',
              villages: [
                { id: 2327, name: 'GOONE' },
                { id: 2324, name: 'GOONE LOWER' },
                { id: 2325, name: 'GOONE MUYENGA' },
                { id: 2331, name: 'MITUNDA' },
                { id: 2326, name: 'MITUNDA II' },
                { id: 2328, name: 'NDUGUTO' },
                { id: 2332, name: 'RWANDEGEYA' },
                { id: 2329, name: 'RWANDEGEYA UPPER' },
                { id: 2330, name: 'RWANDEGEYA WEST' },
              ],
            },
          ],
        },
        {
          id: 50,
          name: 'HARUGALI',
          parishes: [
            {
              id: 272,
              name: 'BUMATE',
              villages: [
                { id: 2057, name: 'BIMARA' },
                { id: 2061, name: 'BUMATE CENTRAL' },
                { id: 62495, name: 'KAMUTHO' },
                { id: 62574, name: 'KANYAMARUNDI' },
                { id: 2058, name: 'KARANGITSIO  I' },
                { id: 2059, name: 'KARANGITSIO  II' },
                { id: 2060, name: 'KIDUNGU I' },
                { id: 2062, name: 'KIDUNGU II' },
                { id: 63542, name: 'KIHAMBA' },
              ],
            },
            {
              id: 270,
              name: 'BUPOMBOLI',
              villages: [
                { id: 61516, name: 'HARUGALE' },
                { id: 2050, name: 'HARUGALE CENTRAL' },
                { id: 2053, name: 'IZAHURA' },
                { id: 2051, name: 'KIBALE I' },
                { id: 2052, name: 'KIHOKO  II' },
                { id: 67676, name: 'NDEWA' },
              ],
            },
            {
              id: 271,
              name: 'KASULENGE',
              villages: [
                { id: 60431, name: 'BUTAMU' },
                { id: 60485, name: 'BUTSAPE' },
                { id: 61961, name: 'KABULONGO' },
                { id: 61979, name: 'KABUTETI' },
                { id: 2054, name: 'KASULENGE  I' },
                { id: 2055, name: 'KASULENGE  II' },
                { id: 2056, name: 'KASULENGE  III' },
              ],
            },
            {
              id: 273,
              name: 'KIHOKO',
              villages: [
                { id: 59069, name: 'BIHOROGHO' },
                { id: 2063, name: 'KABINGO I' },
                { id: 2065, name: 'KABINGO II' },
                { id: 61926, name: 'KABINGO III' },
                { id: 61927, name: 'KABINGO SOUTH' },
                { id: 2066, name: 'KIBALE II' },
                { id: 63341, name: 'KIBALE III' },
                { id: 2064, name: 'KIHOKO   I' },
                { id: 2067, name: 'NGUGHO' },
              ],
            },
            {
              id: 276,
              name: 'KIRINDI',
              villages: [
                { id: 59456, name: 'BUKARARA II' },
                { id: 63010, name: 'KASULENGE III' },
                { id: 2072, name: 'KIRINDI CENTRAL' },
                { id: 2071, name: 'KITSOLIMA  II' },
                { id: 65599, name: 'LUGO' },
                { id: 67773, name: 'NGUBANGALE WEST' },
              ],
            },
            {
              id: 275,
              name: 'KITSOLIMA',
              villages: [
                { id: 59454, name: 'BUKARARA' },
                { id: 2069, name: 'BUTSIKYA' },
                { id: 62320, name: 'KALHALHO' },
                { id: 63564, name: 'KIHOZI' },
                { id: 2070, name: 'KITSOLIMA  I' },
              ],
            },
            {
              id: 274,
              name: 'NYALULU',
              villages: [
                { id: 61962, name: 'KABULONGO II' },
                { id: 63144, name: 'KATSAMBU' },
                { id: 64362, name: 'KUGHUNANE' },
                { id: 67772, name: 'NGUBANGALA EAST' },
                { id: 2068, name: 'NYALULU' },
              ],
            },
          ],
        },
        {
          id: 58,
          name: 'KAGUGU',
          parishes: [
            {
              id: 305,
              name: 'BUNYAMWERA',
              villages: [
                { id: 2256, name: 'BULUMANGOMA' },
                { id: 2254, name: 'BUNYAMWERA' },
                { id: 2257, name: 'KABAKULE' },
                { id: 2255, name: 'KABWE' },
                { id: 2258, name: 'KABWE TRADING CENTRE' },
              ],
            },
            {
              id: 307,
              name: 'KAGHUGHU',
              villages: [
                { id: 2264, name: 'BUKWERA' },
                { id: 2265, name: 'KAGHUGHU' },
                { id: 63348, name: 'KIBANDYA' },
                { id: 2268, name: 'KITHOMA' },
                { id: 2266, name: 'MUSILI' },
                { id: 2267, name: 'NTUMA' },
                { id: 2269, name: 'NYANTANI' },
              ],
            },
            {
              id: 308,
              name: 'KYEBUMBA',
              villages: [
                { id: 2270, name: 'BUNDIKIKALE' },
                { id: 2274, name: 'KYEBUMBA I' },
                { id: 2272, name: 'KYEBUMBA II' },
                { id: 2273, name: 'NTAGATA CENTRAL' },
                { id: 2271, name: 'NTAGATA I' },
                { id: 2275, name: 'NTAGATA II' },
              ],
            },
            {
              id: 306,
              name: 'NKURANGA',
              villages: [
                { id: 2260, name: 'BUNDIKAHONDO I' },
                { id: 2261, name: 'BUNDIKAHONDO II' },
                { id: 2262, name: 'MBUMALI' },
                { id: 2263, name: 'MUSALAWU CENTRAL' },
                { id: 2259, name: 'MUSALAWU I' },
                { id: 66675, name: 'MUSALAWU II' },
              ],
            },
          ],
        },
        {
          id: 51,
          name: 'KASITU',
          parishes: [
            {
              id: 277,
              name: 'KASITU',
              villages: [
                { id: 2073, name: 'ISURA I' },
                { id: 2074, name: 'KASITU  I' },
                { id: 2075, name: 'KITEHE' },
              ],
            },
            {
              id: 279,
              name: 'KATWAKALI',
              villages: [
                { id: 2081, name: 'KAHUMBU  II' },
                { id: 2079, name: 'KASAMBYA' },
                { id: 2083, name: 'KASUNGA' },
                { id: 2080, name: 'KINYIHEMBE I' },
                { id: 2082, name: 'KYABIKUHA' },
              ],
            },
            {
              id: 280,
              name: 'MUNGUNI',
              villages: [
                { id: 2084, name: 'KAGHANDO' },
                { id: 2089, name: 'KINYIHEMBE II' },
                { id: 2085, name: 'KORAKORA' },
                { id: 2086, name: 'KYENJOJO' },
                { id: 2087, name: 'MUNGUNU' },
                { id: 2088, name: 'NGELEMAKE' },
              ],
            },
            {
              id: 278,
              name: 'NDALIBANA',
              villages: [
                { id: 2076, name: 'KAHEMBE' },
                { id: 2078, name: 'KASITU  II' },
                { id: 2077, name: 'KIHOKO' },
              ],
            },
          ],
        },
        {
          id: 60,
          name: 'MABERE',
          parishes: [
            {
              id: 315,
              name: 'MABERE',
              villages: [
                { id: 2302, name: 'KABANGO  II' },
                { id: 62409, name: 'KAMASALE' },
                { id: 2303, name: 'KIGHUTU' },
                { id: 2304, name: 'KIHONDO' },
                { id: 2305, name: 'MABERE  II' },
                { id: 66030, name: 'MANJEBE' },
              ],
            },
            {
              id: 318,
              name: 'MAHINYI',
              villages: [
                { id: 2321, name: 'BUSENDWA II' },
                { id: 2320, name: 'BUSENDWA III' },
                { id: 2319, name: 'KAYEMBE' },
                { id: 2322, name: 'MAHINYI' },
                { id: 65902, name: 'MAHINYI LOWER' },
                { id: 2323, name: 'NGOMEKOME' },
              ],
            },
            {
              id: 316,
              name: 'MALOMBA',
              villages: [
                { id: 2309, name: 'KIREMBERI' },
                { id: 2310, name: 'MALOMBA  CENTRAL' },
                { id: 2306, name: 'MALOMBA  I' },
                { id: 2307, name: 'MALOMBA  II' },
                { id: 2308, name: 'MALOMBA  III' },
                { id: 2311, name: 'MUTITI' },
              ],
            },
            {
              id: 317,
              name: 'NYAKIGHOMA',
              villages: [
                { id: 2313, name: 'BUMBWENDE I' },
                { id: 2316, name: 'BUMBWENDE II' },
                { id: 2314, name: 'KABANGO I' },
                { id: 2312, name: 'KAGHOGHO' },
                { id: 2315, name: 'KAMUBYOLE' },
                { id: 2318, name: 'LIKODU' },
                { id: 2317, name: 'NYAKIGHOMA' },
              ],
            },
          ],
        },
        {
          id: 62,
          name: 'MBATYA',
          parishes: [
            {
              id: 327,
              name: 'BUDWEYA',
              villages: [
                { id: 59275, name: 'BUDWEYA' },
                { id: 2369, name: 'BULIBATHA' },
                { id: 2368, name: 'BUSAMBA  I' },
                { id: 2370, name: 'KIGHARAMA' },
                { id: 66473, name: 'MUDOLO' },
              ],
            },
            {
              id: 328,
              name: 'BULEMBA',
              villages: [
                { id: 2371, name: 'BULEMBA I' },
                { id: 2372, name: 'BULEMBA II' },
                { id: 60264, name: 'BUSAMBA   III' },
                { id: 62604, name: 'KANYISANDE' },
                { id: 62866, name: 'KARUSENGE' },
              ],
            },
            {
              id: 326,
              name: 'BUNGHUHA',
              villages: [
                { id: 2366, name: 'BUKONZO' },
                { id: 2365, name: 'BULYAMBAYA' },
                { id: 60179, name: 'BUNGUHA' },
                { id: 2367, name: 'BUNGUHA  I' },
              ],
            },
            {
              id: 325,
              name: 'BUSAMBA',
              villages: [
                { id: 2360, name: 'BUSAMBA  CENTRAL' },
                { id: 2364, name: 'BUSAMBA  II' },
                { id: 2363, name: 'BUSAMBA IBANDA' },
                { id: 2361, name: 'KILOLKU' },
                { id: 63896, name: 'KISENYI' },
                { id: 2362, name: 'KITHOMA' },
              ],
            },
            {
              id: 329,
              name: 'BUTHUNGERERI',
              villages: [
                { id: 2373, name: 'BUGHARAMA' },
                { id: 2374, name: 'BUNGUHA CENTRAL' },
                { id: 2375, name: 'BUTHUNGERERI' },
                { id: 63085, name: 'KATHUMBI' },
              ],
            },
          ],
        },
        {
          id: 52,
          name: 'NDUGUTU',
          parishes: [
            {
              id: 281,
              name: 'BUTAMA',
              villages: [
                { id: 2090, name: 'BUGWIRO' },
                { id: 2091, name: 'BUTAMA' },
                { id: 2092, name: 'KASINGIRI' },
              ],
            },
            {
              id: 282,
              name: 'KASANZI',
              villages: [
                { id: 2093, name: 'BUSIGHA' },
                { id: 2094, name: 'KASANZI  I' },
                { id: 2095, name: 'KASANZI  II' },
                { id: 2098, name: 'KASANZI III' },
                { id: 2096, name: 'KIBIRIRI' },
                { id: 2097, name: 'KISONKO' },
                { id: 2099, name: 'MIROMBYO' },
              ],
            },
          ],
        },
        {
          id: 56,
          name: 'NGAMBA',
          parishes: [
            {
              id: 300,
              name: 'BURAMBAGIRA',
              villages: [
                { id: 2221, name: 'BURAMBAGIRA  I' },
                { id: 2222, name: 'BURAMBAGIRA  II' },
                { id: 2225, name: 'KAHUKYA' },
                { id: 2223, name: 'KAMANGARA' },
                { id: 2226, name: 'KARAMBE' },
                { id: 2224, name: 'NYAROPE' },
              ],
            },
            {
              id: 299,
              name: 'BUTOLYA',
              villages: [
                { id: 2213, name: 'BUKYAMBU' },
                { id: 2215, name: 'BUSONDWA' },
                { id: 2216, name: 'BUTOLYA  I' },
                { id: 2217, name: 'BUTOLYA  II' },
                { id: 2218, name: 'KALEMEREME' },
                { id: 2220, name: 'KAMANDALYA' },
                { id: 2214, name: 'KASINGA' },
                { id: 2219, name: 'KASUKU' },
              ],
            },
            {
              id: 297,
              name: 'KIKYO',
              villages: [
                { id: 2192, name: 'BUMBILI' },
                { id: 2193, name: 'BUNYANGASYA' },
                { id: 2195, name: 'KALIFONIYA' },
                { id: 2200, name: 'KANYABULENGE' },
                { id: 2196, name: 'KIKYO  I' },
                { id: 2197, name: 'KIKYO  II' },
                { id: 2198, name: 'KIKYO TRADING CENTER' },
                { id: 2194, name: 'MULIBONDO' },
                { id: 2199, name: 'TEYA' },
              ],
            },
            {
              id: 298,
              name: 'NGAMBA',
              villages: [
                { id: 2202, name: 'BUYAYA I' },
                { id: 2203, name: 'BUYAYA II' },
                { id: 2205, name: 'BUYAYA III' },
                { id: 2204, name: 'KAKUKA' },
                { id: 2211, name: 'KILUBO  I' },
                { id: 2212, name: 'KILUBO  II' },
                { id: 2201, name: 'KILUBO BUYING CENTER' },
                { id: 2208, name: 'MANGUNGU' },
                { id: 2206, name: 'NGAMBA  I' },
                { id: 2207, name: 'NGAMBA  II' },
                { id: 2210, name: 'NGAMBA  III' },
                { id: 2209, name: 'NTOME' },
              ],
            },
          ],
        },
        {
          id: 63,
          name: 'NGITE',
          parishes: [
            {
              id: 331,
              name: 'KALEYALEYA',
              villages: [
                { id: 2379, name: 'KALEYALEYA  I' },
                { id: 2380, name: 'KALEYALEYA  II' },
                { id: 2382, name: 'KALEYALEYA  NORTH' },
                { id: 2381, name: 'NGITE' },
                { id: 67742, name: 'NGITE SOUTH' },
              ],
            },
            {
              id: 332,
              name: 'KANYANGOMA',
              villages: [
                { id: 62319, name: 'KALEYALEYA WEST' },
                { id: 2383, name: 'KANYANGOMA' },
                { id: 62581, name: 'KANYANGOMA EAST' },
                { id: 2384, name: 'KARAMBI' },
                { id: 2385, name: 'KIRERYA' },
              ],
            },
            {
              id: 333,
              name: 'MASULE',
              villages: [
                { id: 2386, name: 'BUDENGE' },
                { id: 2387, name: 'BUKWALI' },
                { id: 63802, name: 'KIREMBERI' },
                { id: 66100, name: 'MASULE EAST' },
                { id: 2388, name: 'MBAKATI' },
              ],
            },
            {
              id: 330,
              name: 'NGITE',
              villages: [
                { id: 65600, name: 'LUGO' },
                { id: 2376, name: 'MASULE  I' },
                { id: 2377, name: 'MASULE  II' },
                { id: 2378, name: 'MASULE  III' },
                { id: 66099, name: 'MASULE  SOUTH' },
              ],
            },
          ],
        },
        {
          id: 59,
          name: 'NTANDI TOWN COUNCIL',
          parishes: [
            {
              id: 310,
              name: 'BUNDIMASOLI WARD',
              villages: [
                { id: 2281, name: 'BUNDIMASOLI' },
                { id: 2279, name: 'BUNDIMASOLI CENTRAL' },
                { id: 2282, name: 'BUNDIMASOLI WEST' },
                { id: 2280, name: 'KABALE' },
                { id: 61853, name: 'KABALE CENTRAL' },
                { id: 2283, name: 'NTANDI' },
              ],
            },
            {
              id: 311,
              name: 'KAHUMBU WARD',
              villages: [
                { id: 2284, name: 'ISURA II' },
                { id: 2285, name: 'KAHUMBU  I' },
                { id: 2288, name: 'KARONGOTI' },
                { id: 2286, name: 'NKISYA' },
                { id: 2287, name: 'NYAMBOWE' },
              ],
            },
            {
              id: 312,
              name: 'KIRAMBI WARD',
              villages: [
                { id: 2292, name: 'BUSEYA' },
                { id: 2290, name: 'KIRAMBE' },
                { id: 2291, name: 'MABERE  I' },
                { id: 2289, name: 'MAKILI' },
              ],
            },
            {
              id: 313,
              name: 'MPULYA WARD',
              villages: [
                { id: 2293, name: 'MPULYA CENTRAL' },
                { id: 2297, name: 'MPULYA I' },
                { id: 2295, name: 'MPULYA II' },
                { id: 2296, name: 'MPULYA III' },
                { id: 2294, name: 'MPULYA WEST' },
              ],
            },
            {
              id: 309,
              name: 'NTANDI WARD',
              villages: [
                { id: 2276, name: 'BUMAGA I' },
                { id: 59769, name: 'BUMAGA II' },
                { id: 2277, name: 'NTANDI EAST' },
                { id: 2278, name: 'NTANDI WEST' },
              ],
            },
            {
              id: 314,
              name: 'NYABUGESERA WARD',
              villages: [
                { id: 2298, name: 'BITAHURA I' },
                { id: 2301, name: 'BITAHURA II' },
                { id: 2299, name: 'KUPANGU' },
                { id: 2300, name: 'NYABUGESERA' },
              ],
            },
          ],
        },
        {
          id: 54,
          name: 'NTOTORO',
          parishes: [
            {
              id: 288,
              name: 'BUGANDO',
              villages: [
                { id: 2130, name: 'BUGANDO I' },
                { id: 2131, name: 'BUGANDO II' },
                { id: 2127, name: 'BUGANDO VALLEY' },
                { id: 2128, name: 'BUNDIMAGHUNGA' },
                { id: 2126, name: 'KABUGA' },
                { id: 2129, name: 'KABUGA CENTRAL' },
              ],
            },
            {
              id: 293,
              name: 'BUHUNDU',
              villages: [
                { id: 2162, name: 'BUHUNDU II' },
                { id: 2166, name: 'BUHUNDU III' },
                { id: 2163, name: 'HAHAU' },
                { id: 2165, name: 'KIRUMYA  II' },
                { id: 2164, name: 'NTOME' },
              ],
            },
            {
              id: 290,
              name: 'KANYANSIRI',
              villages: [
                { id: 59396, name: 'BUHUNDU' },
                { id: 2147, name: 'BUHUNDU-KISENYI' },
                { id: 2150, name: 'BUNDIMWALI  I' },
                { id: 2148, name: 'BUNDIMWALI III' },
                { id: 2151, name: 'BUSENDWA  I' },
                { id: 2146, name: 'BUSENDWA  II' },
                { id: 2149, name: 'NYASORO/BUSENDWA' },
              ],
            },
            {
              id: 291,
              name: 'KINYANKENDE',
              villages: [
                { id: 2152, name: 'BUGANDO  I' },
                { id: 2153, name: 'BUGANDO  II' },
                { id: 59295, name: 'BUGANDO VALLEY' },
                { id: 2155, name: 'BUNDIBUTUNDA CENTRAL' },
                { id: 2154, name: 'KINYANKENDE' },
              ],
            },
            {
              id: 289,
              name: 'NTOTORO',
              villages: [
                { id: 2132, name: 'BUBULONGU I' },
                { id: 2137, name: 'BUBULONGU II' },
                { id: 2145, name: 'BUKISE IV' },
                { id: 2133, name: 'BUKISI  I' },
                { id: 2134, name: 'BUKISI  II' },
                { id: 2138, name: 'BUKISI III' },
                { id: 2139, name: 'BUKISI TRADING CENTRE' },
                { id: 2135, name: 'BUNDIMUKERERWA  I' },
                { id: 2136, name: 'BUNDIMUKERERWA  II' },
                { id: 2142, name: 'BUNDIMWALI II' },
                { id: 2141, name: 'MAKERE' },
                { id: 2144, name: 'MAKERE NORTH' },
                { id: 2140, name: 'MANTOROBA TRADING CENTRE' },
                { id: 2143, name: 'MATONGA' },
              ],
            },
            {
              id: 292,
              name: 'NYASORO',
              villages: [
                { id: 2159, name: 'BUNDIBUTUNDA' },
                { id: 2160, name: 'BUNDIMAGWARA' },
                { id: 2156, name: 'HABEDU' },
                { id: 2158, name: 'KIRUMYA EAST' },
                { id: 2157, name: 'KIRUMYA T.C.' },
                { id: 2161, name: 'NYANSORO' },
              ],
            },
          ],
        },
        {
          id: 55,
          name: 'SINDILA',
          parishes: [
            {
              id: 294,
              name: 'BUNYANGULE',
              villages: [
                { id: 2168, name: 'BUNYANGULE  I' },
                { id: 2169, name: 'BUNYANGULE  II' },
                { id: 2167, name: 'BUNYANGULE  III' },
                { id: 2170, name: 'BUNYANGULE CENTRAL' },
                { id: 2171, name: 'BUSIIGHA' },
              ],
            },
            {
              id: 295,
              name: 'KAKUKA',
              villages: [
                { id: 2172, name: 'BIHYA' },
                { id: 2182, name: 'BIHYA II' },
                { id: 2173, name: 'BUBONI' },
                { id: 2183, name: 'BUSANZA' },
                { id: 2184, name: 'BUSIGA CENTRAL' },
                { id: 2174, name: 'KAKUKA  I' },
                { id: 2175, name: 'KAKUKA  II' },
                { id: 2176, name: 'KAKUKA  III' },
                { id: 2185, name: 'KATSWAMBA' },
                { id: 2177, name: 'KINYAMBOMA' },
                { id: 2186, name: 'LHUMBU' },
                { id: 2178, name: 'MALINDI' },
                { id: 2179, name: 'MUTITI  I' },
                { id: 2180, name: 'MUTITI II' },
                { id: 2181, name: 'MUTITI III' },
              ],
            },
            {
              id: 296,
              name: 'NYANKONDA',
              villages: [
                { id: 2187, name: 'BULYATA' },
                { id: 2188, name: 'BULYATA II' },
                { id: 2190, name: 'NYANKONDA  I' },
                { id: 2191, name: 'NYANKONDA  II' },
                { id: 2189, name: 'NYANKONDA CENTRAL' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 10,
      name: 'BWAMBA COUNTY',
      sub_counties: [
        {
          id: 38,
          name: 'BUBANDI',
          parishes: [
            {
              id: 212,
              name: 'KANANKULUNGO',
              villages: [
                { id: 1700, name: 'BUSU CENTRAL' },
                { id: 1698, name: 'BUSU II' },
                { id: 1697, name: 'KANANKULONGO' },
                { id: 1701, name: 'KANANKULUNGO CENTRAL' },
                { id: 1699, name: 'NDUGUTU' },
              ],
            },
            {
              id: 211,
              name: 'NJULE EAST',
              villages: [
                { id: 1686, name: 'BUBANDI III' },
                { id: 1687, name: 'KABUTABULE' },
                { id: 1690, name: 'KABUTABULE CENTRAL' },
                { id: 1692, name: 'KABUTABULE II' },
                { id: 1688, name: 'KIBHANIGE' },
                { id: 1695, name: 'NAKWEYALILA' },
                { id: 1689, name: 'NAMANSENGU' },
                { id: 1696, name: 'NAMASEGU II' },
                { id: 1691, name: 'NAMUGHAJU I' },
                { id: 1694, name: 'NAMUGHAJU II' },
                { id: 1693, name: 'NDUGUTO' },
              ],
            },
            {
              id: 208,
              name: 'NJUULE',
              villages: [
                { id: 1663, name: 'BUNDISELYA' },
                { id: 62401, name: 'KAMALANJALA' },
                { id: 1667, name: 'KANANSIMBI' },
                { id: 1668, name: 'KANANTUWA' },
                { id: 1664, name: 'MUTEMBO' },
                { id: 1665, name: 'NADULE' },
                { id: 1669, name: 'NADULE II' },
                { id: 1666, name: 'NJUULE' },
                { id: 67791, name: 'NJUULE II' },
              ],
            },
            {
              id: 209,
              name: 'NYAMBARO',
              villages: [
                { id: 64233, name: 'KOLOLO' },
                { id: 1678, name: 'NADULE' },
                { id: 67142, name: 'NAKWEYALILA' },
                { id: 1679, name: 'NYAMBARO' },
                { id: 1671, name: 'NYAMBARO   I' },
                { id: 1672, name: 'NYAMBARO  II' },
                { id: 1673, name: 'NYAMBARO  III' },
                { id: 1674, name: 'NYAMBARO  IV' },
                { id: 1675, name: 'NYAMBARO  V' },
                { id: 1677, name: 'NYAMBARO BOARDER' },
                { id: 1676, name: 'NYAMBARO CENTRAL' },
                { id: 68144, name: 'NYAMBARO CITY' },
                { id: 1670, name: 'NYAMBARO NORTH' },
                { id: 68145, name: 'NYAMBARO SOUTH' },
                { id: 68146, name: 'NYAMBARO WEST' },
              ],
            },
            {
              id: 210,
              name: 'TOMBWE',
              villages: [
                { id: 1680, name: 'MANKEDENGU' },
                { id: 1681, name: 'NAMBALANGA' },
                { id: 1684, name: 'NAMBALANGA NORTH' },
                { id: 1685, name: 'TOMBWE CENTRAL' },
                { id: 1682, name: 'TOMBWE I' },
                { id: 1683, name: 'TOMBWE II' },
              ],
            },
          ],
        },
        {
          id: 39,
          name: 'BUBUKWANGA',
          parishes: [
            {
              id: 213,
              name: 'BUBUKWANGA',
              villages: [
                { id: 1702, name: 'BUBUKWANGA   HQT' },
                { id: 1703, name: 'BUBUKWANGA  CENTRAL' },
                { id: 1704, name: 'BUBUKWANGA MODAL' },
                { id: 1705, name: 'BUNDIKITEGANWA   II' },
                { id: 1706, name: 'BUNDIMAGWARA I' },
              ],
            },
            {
              id: 216,
              name: 'BUNYAMWERA',
              villages: [
                { id: 1722, name: 'BUHULA' },
                { id: 1726, name: 'HAKIBALE' },
                { id: 1723, name: 'KIYOMBYA BOARDER' },
                { id: 1724, name: 'SAARA CITY' },
                { id: 1725, name: 'SARA KIHOMBYA' },
              ],
            },
            {
              id: 215,
              name: 'HUMYA',
              villages: [
                { id: 1715, name: 'BUNDIKULIYA' },
                { id: 1716, name: 'BUNDIKULYA MODAL' },
                { id: 1714, name: 'BUNDIMBALI I' },
                { id: 1717, name: 'HUMYA BOARDER' },
                { id: 1718, name: 'HUMYA I' },
                { id: 1720, name: 'HUMYA II' },
                { id: 1721, name: 'HUMYA III' },
                { id: 1719, name: 'MAMPONGURO' },
              ],
            },
            {
              id: 214,
              name: 'MAMPONGYA',
              villages: [
                { id: 1710, name: 'BUBURONGU' },
                { id: 1708, name: 'BUBURONGU BOARDER' },
                { id: 1707, name: 'BUBURONGU CENTRAL' },
                { id: 1712, name: 'BUNDIKITEGANWA   I' },
                { id: 1709, name: 'BUNDIMBALI  II' },
                { id: 1713, name: 'MAMPONGYA' },
                { id: 1711, name: 'MAMPONGYA EAST' },
              ],
            },
            {
              id: 217,
              name: 'SAARA',
              villages: [
                { id: 1727, name: 'BUHUNDU BOARDER' },
                { id: 1728, name: 'BUHUNDU I' },
                { id: 1729, name: 'BUHUNDU II' },
                { id: 1730, name: 'BUNDIMAGWARA II' },
              ],
            },
          ],
        },
        {
          id: 49,
          name: 'BUGANIKERE TOWN COUNCIL',
          parishes: [
            {
              id: 264,
              name: 'BUGANIKIRE WARD',
              villages: [
                { id: 2022, name: 'BUGANIKERE  I' },
                { id: 2024, name: 'BUGANIKERE EAST' },
                { id: 2025, name: 'BUGANIKERE EAST WEST' },
                { id: 59300, name: 'BUGANIKERE IV' },
                { id: 59301, name: 'BUGANIKERE NORTH' },
                { id: 2023, name: 'BUGANIKERE WEST' },
              ],
            },
            {
              id: 266,
              name: 'BUNDIKAKEMBA WARD',
              villages: [
                { id: 2029, name: 'BUGANIKERE  CENTRAL' },
                { id: 2032, name: 'BUNDIKAKEMBA EAST' },
                { id: 2030, name: 'BUNDIKAKEMBA SOUTH' },
                { id: 2031, name: 'NGOMA II' },
              ],
            },
            {
              id: 267,
              name: 'KYAMAIZI WARD',
              villages: [
                { id: 2035, name: 'BUGANIKERE II' },
                { id: 2033, name: 'BUGANIKERE NDIKELE' },
                { id: 2034, name: 'BUGANIKERE SOUTH' },
                { id: 2036, name: 'BUGANIKERE SOUTH WEST' },
                { id: 2038, name: 'KYAMAIZI' },
                { id: 2037, name: 'KYAMAIZI II' },
              ],
            },
            {
              id: 268,
              name: 'NKISYA WARD',
              villages: [
                { id: 2042, name: 'NKISIYA' },
                { id: 2039, name: 'NKISIYA EAST' },
                { id: 2040, name: 'NKISIYA NORTH' },
                { id: 2041, name: 'NKISIYA WEST' },
              ],
            },
            {
              id: 269,
              name: 'NYAHUNGU WARD',
              villages: [
                { id: 2044, name: 'BUTAMA I EAST' },
                { id: 2043, name: 'KANYANTUHA' },
                { id: 2045, name: 'KANYANTUHA EAST' },
                { id: 2049, name: 'NYAHUNGU' },
                { id: 2046, name: 'NYAHUNGU  EAST' },
                { id: 2047, name: 'NYAHUNGU I' },
                { id: 2048, name: 'NYAHUNGU II' },
              ],
            },
            {
              id: 265,
              name: 'SIMBYA WARD',
              villages: [
                { id: 2026, name: 'BUGANIKERE  III' },
                { id: 2027, name: 'BUNDIKAKEMBA  I' },
                { id: 2028, name: 'BUNDIKAKEMBA  II' },
                { id: 60141, name: 'BUNDIKAKEMBA KAMAMBULE' },
                { id: 60142, name: 'BUNDIKAKEMBA WENDO' },
              ],
            },
          ],
        },
        {
          id: 40,
          name: 'BUNDIBUGYO TOWN COUNCIL',
          parishes: [
            {
              id: 223,
              name: 'BIMARA WARD',
              villages: [
                { id: 1763, name: 'BUNDIKPHADA' },
                { id: 1759, name: 'HUMYA' },
                { id: 1760, name: 'KAINDOLE' },
                { id: 1761, name: 'KIBALE' },
                { id: 1762, name: 'NYAMPIRI' },
              ],
            },
            {
              id: 218,
              name: 'BUMADU WARD',
              villages: [
                { id: 1731, name: 'BUMADU CENTRAL' },
                { id: 1732, name: 'GABATA' },
                { id: 1733, name: 'KATUMBA' },
                { id: 1734, name: 'MUSANDARA' },
                { id: 1735, name: 'MUTOMA' },
              ],
            },
            {
              id: 219,
              name: 'BUMATE WARD',
              villages: [
                { id: 1740, name: 'HAMUTITI' },
                { id: 1736, name: 'KAGORA' },
                { id: 1737, name: 'MAINDOLE' },
                { id: 1738, name: 'NAMBAWANI' },
                { id: 1739, name: 'TWANZANE' },
              ],
            },
            {
              id: 220,
              name: 'BUNDIBUGYO CENTRAL WARD',
              villages: [
                { id: 1741, name: 'BUNDIBUGYO  CENTRAL' },
                { id: 1742, name: 'KABALE' },
                { id: 1743, name: 'KAJAMBURA' },
                { id: 1744, name: 'KATANGA' },
                { id: 1745, name: 'KAVULE' },
                { id: 1746, name: 'KISENYI' },
              ],
            },
            {
              id: 221,
              name: 'HAMUTITI WARD',
              villages: [
                { id: 1747, name: 'CITY SQUARE' },
                { id: 1748, name: 'HOSPITAL' },
                { id: 1749, name: 'KAKINDO' },
                { id: 1750, name: 'KAKOGHA' },
                { id: 1751, name: 'KIRIBHA' },
                { id: 1752, name: 'KITUI' },
                { id: 1753, name: 'MPOKU' },
                { id: 1754, name: 'MUTITI' },
              ],
            },
            {
              id: 222,
              name: 'KANYANSIMBI WARD',
              villages: [
                { id: 1755, name: 'BIMARA' },
                { id: 1756, name: 'DUMBA' },
                { id: 1757, name: 'MBUMBAI' },
                { id: 1758, name: 'MUTUKULA' },
              ],
            },
          ],
        },
        {
          id: 46,
          name: 'BUNDINGOMA',
          parishes: [
            {
              id: 251,
              name: 'BUNDINAMANDI',
              villages: [
                { id: 1930, name: 'BUNDIKAHONDO BOADER' },
                { id: 1931, name: 'BUNDIKALEBHA' },
                { id: 1934, name: 'BUNDIMULAMBI II' },
                { id: 1932, name: 'BUNDIMURAMBI' },
                { id: 1933, name: 'BUNDINAMANDI' },
                { id: 1937, name: 'BUNDINAMANDI II' },
                { id: 1935, name: 'BUNYAMWERA' },
                { id: 1936, name: 'KAKIINDO' },
                { id: 1938, name: 'NYABANKOKO' },
              ],
            },
            {
              id: 250,
              name: 'BUNDINGOMA',
              villages: [
                { id: 1921, name: 'BUNDIBHOMBI' },
                { id: 1924, name: 'BUNDINGOMA' },
                { id: 1925, name: 'BUNDINGOMA  CENTRAL' },
                { id: 1926, name: 'BUNDINGOMA I' },
                { id: 1929, name: 'BUSU BUGANDYA' },
                { id: 1920, name: 'KAKUHABIYA' },
                { id: 1922, name: 'KATUMBA' },
                { id: 1923, name: 'KINABATAKA I' },
                { id: 1927, name: 'KINABATAKA II' },
                { id: 1928, name: 'NAMUDUDHE' },
              ],
            },
            {
              id: 252,
              name: 'BUSU',
              villages: [
                { id: 1939, name: 'BUHURA' },
                { id: 1940, name: 'BUKUBANKALI' },
                { id: 1942, name: 'BUSU CENTRAL' },
                { id: 60394, name: 'BUSU EAST' },
                { id: 1943, name: 'BUSU NABALONGO' },
                { id: 60395, name: 'BUSU WEST' },
                { id: 60396, name: 'BUSU-KANAMANSENGU' },
                { id: 1941, name: 'BUSU-NDUGOTO' },
              ],
            },
            {
              id: 253,
              name: 'NAKASOHE',
              villages: [
                { id: 1949, name: 'NYAKASOHA  I' },
                { id: 1950, name: 'NYAKASOHA  II' },
                { id: 1944, name: 'NYAKASOHE BOARDER' },
                { id: 1945, name: 'NYAKASOHE EAST' },
                { id: 1946, name: 'NYAKASOHE IV' },
                { id: 1947, name: 'NYAKASOHE V' },
                { id: 1948, name: 'NYAKASOHE WEST' },
                { id: 1951, name: 'NYAKASOWE CENTRAL' },
                { id: 1952, name: 'NYAKASOWE III' },
              ],
            },
          ],
        },
        {
          id: 41,
          name: 'BUSARU',
          parishes: [
            {
              id: 224,
              name: 'BUGOMBWA',
              villages: [
                { id: 1764, name: 'BUGOMBWA  HARUGALE' },
                { id: 1765, name: 'BUGOMBWA CENTRAL' },
                { id: 1766, name: 'BUNDIBEGENDYA' },
                { id: 1767, name: 'KILEMBE' },
              ],
            },
            {
              id: 227,
              name: 'BUNDIMWENDI',
              villages: [
                { id: 1790, name: 'BUNDIKAGHORA' },
                { id: 1791, name: 'BUNDIKAKOMI' },
                { id: 1792, name: 'BUNDIMWENDI I' },
                { id: 1793, name: 'BUNDIMWENDI II' },
                { id: 1794, name: 'KADINDELE' },
              ],
            },
            {
              id: 225,
              name: 'BUSARU',
              villages: [
                { id: 1768, name: 'BUBOMBOLO BULYAMBWA' },
                { id: 1769, name: 'BUSARU  CENTRAL' },
                { id: 1772, name: 'NYAKAKINDO  I' },
                { id: 1773, name: 'NYAKAKINDO  II' },
                { id: 1770, name: 'NYAKAKINDO III' },
                { id: 1771, name: 'NYAKAKINDO IV' },
              ],
            },
            {
              id: 228,
              name: 'KINYANTE',
              villages: [
                { id: 1795, name: 'KALEBHA' },
                { id: 1796, name: 'KINYANTE  CENTRAL' },
                { id: 1797, name: 'KINYANTE  I' },
                { id: 1798, name: 'KINYANTE  III' },
                { id: 1799, name: 'KINYANTE  IV' },
                { id: 1801, name: 'KINYANTE EAST' },
                { id: 1800, name: 'KINYANTE II' },
              ],
            },
            {
              id: 226,
              name: 'KIRINDI',
              villages: [
                { id: 1774, name: 'BUMATHE  II' },
                { id: 1776, name: 'BUNDIKAHUKA  I' },
                { id: 1777, name: 'BUNDIKAHUKA  II' },
                { id: 1778, name: 'BUNDIKAHUKA  III' },
                { id: 1783, name: 'BUNDIKAHUKA CENTRAL' },
                { id: 1775, name: 'BUNDINDYANKUNDA' },
                { id: 1779, name: 'BUSENGERWA  I' },
                { id: 1780, name: 'BUSENGERWA  II' },
                { id: 1781, name: 'BUSENGERWA  III' },
                { id: 1784, name: 'BUSENGERWA  IV' },
                { id: 1785, name: 'BUSENGERWA  NYALULU' },
                { id: 1786, name: 'MABALE' },
                { id: 1787, name: 'MBUME' },
                { id: 1782, name: 'MUKUNDUNGU' },
                { id: 1788, name: 'MUKUNDUNGU WEST' },
                { id: 1789, name: 'NAMUGONGO' },
              ],
            },
          ],
        },
        {
          id: 48,
          name: 'BUSUNGA TOWN COUNCIL',
          parishes: [
            {
              id: 262,
              name: 'BUSUNGA CENTRAL WARD',
              villages: [
                { id: 2013, name: 'BUSUNGA CENTRAL' },
                { id: 2014, name: 'KATOKE' },
                { id: 2015, name: 'KISENYI' },
              ],
            },
            {
              id: 259,
              name: 'BUSUNGA WARD',
              villages: [
                { id: 1992, name: 'BUSUNGA EAST' },
                { id: 1993, name: 'LAMIA CENTRAL' },
                { id: 1995, name: 'LAMIA I' },
                { id: 1991, name: 'LAMIA II' },
                { id: 1998, name: 'MAJADA EAST' },
                { id: 1994, name: 'MULUNGITANUA III' },
                { id: 1996, name: 'MULUNGITANWA II' },
                { id: 1988, name: 'NDUGUTU I' },
                { id: 68140, name: 'NYAMATORU' },
                { id: 1989, name: 'NYANKONDA  I' },
                { id: 1997, name: 'NYANKONDA  II' },
                { id: 1990, name: 'RUTOOBO' },
              ],
            },
            {
              id: 261,
              name: 'LAMIA WARD',
              villages: [
                { id: 2008, name: 'BUBANDI I - RUTOOBO' },
                { id: 2007, name: 'BUBANDI I-NDUGUTO' },
                { id: 59203, name: 'BUBANDI KALONGE' },
                { id: 2012, name: 'BUNDIJONGIYA SOUTH' },
                { id: 2003, name: 'BUNDINGOMA   II' },
                { id: 2009, name: 'BUNDINGOMA IV' },
                { id: 2004, name: 'BUNDINJOGYA' },
                { id: 62509, name: 'KANANGUNGU' },
                { id: 65915, name: 'MAJADA CENTRAL' },
                { id: 2010, name: 'MAJADA WEST' },
                { id: 66605, name: 'MULUNGITANUA EAST' },
                { id: 2005, name: 'MURUNGITANWA' },
                { id: 66816, name: 'NABHANJINGILI CENTRAL' },
                { id: 2006, name: 'NABHANJINGIRI' },
                { id: 66860, name: 'NABOWA' },
                { id: 69993, name: 'RUTOBO HILL' },
                { id: 69994, name: 'RUTOBO LOWER' },
                { id: 2011, name: 'RUTOOBO CENTRAL' },
              ],
            },
            {
              id: 260,
              name: 'MULUNGITANWA WARD',
              villages: [
                { id: 2002, name: 'KANANKONGE' },
                { id: 2001, name: 'KITUMBA' },
                { id: 1999, name: 'MAJADA' },
                { id: 2000, name: 'MURUNGITANWA' },
              ],
            },
            {
              id: 263,
              name: 'RUTOBO WARD',
              villages: [
                { id: 2019, name: 'BUBANDI CENTRAL' },
                { id: 2016, name: 'BUBANDI II' },
                { id: 2020, name: 'KANAMABALE' },
                { id: 2021, name: 'NDUGUTO HILL' },
                { id: 2018, name: 'NDUGUTU II' },
                { id: 2017, name: 'RUTOBO II' },
              ],
            },
          ],
        },
        {
          id: 43,
          name: 'KIRUMYA',
          parishes: [
            {
              id: 240,
              name: 'BUNDIBUTURO',
              villages: [
                { id: 1867, name: 'BUGHALAMA I' },
                { id: 1866, name: 'BUGHALAMA II' },
                { id: 1868, name: 'BUNDIBUTURO  I' },
                { id: 1869, name: 'BUNDIBUTURO  II' },
                { id: 1870, name: 'KASODO' },
                { id: 1871, name: 'KASULENGE' },
              ],
            },
            {
              id: 239,
              name: 'BUNDIKEKI',
              villages: [
                { id: 1858, name: 'BUNDIKEKI I' },
                { id: 1862, name: 'BUNDIKEKI II' },
                { id: 1859, name: 'BUNDIKEKI-GABATA' },
                { id: 1860, name: 'BUNDIKEKI-KISENYI' },
                { id: 1861, name: 'BUNDIMPHEKU' },
                { id: 1863, name: 'BUNDIMULOMBI  I' },
                { id: 1864, name: 'BUNDIMULOMBI  II' },
                { id: 1865, name: 'HAMUTOMA CENTRAL' },
              ],
            },
            {
              id: 237,
              name: 'BUNDIMULANGYA',
              villages: [
                { id: 1848, name: 'BULAMA CENTRAL' },
                { id: 1844, name: 'BULAMA I' },
                { id: 1849, name: 'BULAMA II' },
                { id: 1845, name: 'KASULENGE  II' },
                { id: 1846, name: 'KIRUMYA  I' },
                { id: 1850, name: 'KIRUMYA CENTRAL' },
                { id: 1847, name: 'KIRUMYA II' },
              ],
            },
            {
              id: 238,
              name: 'KATUMBA',
              villages: [
                { id: 1851, name: 'BUNDIKAYANJA' },
                { id: 1855, name: 'BUNDIMULANGYA' },
                { id: 1856, name: 'BUTUKULU' },
                { id: 1852, name: 'KATUMBA' },
                { id: 1857, name: 'NYABUDE' },
                { id: 1854, name: 'NYABUDE I' },
                { id: 1853, name: 'NYANGASA' },
              ],
            },
            {
              id: 241,
              name: 'NYANKIRO',
              villages: [
                { id: 1872, name: 'BUNDIGERE' },
                { id: 1874, name: 'BUNDIWERUME  BOARDER' },
                { id: 1875, name: 'BUNDIWERUME  CENTRAL' },
                { id: 1873, name: 'BUNDIWERUME II' },
                { id: 1876, name: 'NYANKIRO' },
              ],
            },
          ],
        },
        {
          id: 44,
          name: 'KISUBBA',
          parishes: [
            {
              id: 246,
              name: 'BUBOMBOLI',
              villages: [
                { id: 1899, name: 'BUBOMBOLI  CENTRAL' },
                { id: 1900, name: 'BUBOMBOLI  I' },
                { id: 1901, name: 'BUBOMBOLI  II' },
                { id: 1902, name: 'BUBOMBOLI  III' },
                { id: 1903, name: 'BUNDIKUYALI' },
              ],
            },
            {
              id: 242,
              name: 'BUSORU',
              villages: [
                { id: 1877, name: 'BUSORU  I' },
                { id: 1878, name: 'BUSORU  II' },
                { id: 1879, name: 'BUSORU  III' },
                { id: 1880, name: 'BUTOGO  I' },
                { id: 1881, name: 'BUTOGO II' },
                { id: 1882, name: 'RWANDURU' },
              ],
            },
            {
              id: 243,
              name: 'HAKITARA',
              villages: [
                { id: 1884, name: 'BUNDIBAKEREKE' },
                { id: 1883, name: 'HAKITARA I' },
                { id: 1887, name: 'HAKITARA II' },
                { id: 1885, name: 'KIJANJABA  I' },
                { id: 1886, name: 'KIJANJABA  II' },
              ],
            },
            {
              id: 244,
              name: 'KAGHEMA',
              villages: [
                { id: 1888, name: 'BUFEME' },
                { id: 1889, name: 'BULIREYA  CENTRAL' },
                { id: 1890, name: 'BULIREYA FARM' },
                { id: 1891, name: 'BULIREYA I' },
                { id: 1893, name: 'BULIREYA II' },
                { id: 1892, name: 'BULIREYA NYAKAKINDO' },
              ],
            },
            {
              id: 245,
              name: 'KISUBA',
              villages: [
                { id: 1895, name: 'BUBOMBOLI  III' },
                { id: 1897, name: 'BUBOMBOLI  IV' },
                { id: 1896, name: 'BUBOMBOLI CENTRAL' },
                { id: 1894, name: 'BUBOMBOLI I' },
                { id: 1898, name: 'BUBOMBOLI II' },
              ],
            },
          ],
        },
        {
          id: 45,
          name: 'MIRAMBI',
          parishes: [
            {
              id: 248,
              name: 'KUKA',
              villages: [
                { id: 1910, name: 'BUNDIKAHUNGU CENTRAL' },
                { id: 1907, name: 'BUNDIKAHUNGU NORTH' },
                { id: 1908, name: 'BUNDIKAHUNGU SOUTH' },
                { id: 1911, name: 'BUNDIKAHUNGU WEST' },
                { id: 1909, name: 'BUNDIKAKEMBA  WEST' },
                { id: 1912, name: 'BUNDIKYORA' },
              ],
            },
            {
              id: 247,
              name: 'MIRAMBI',
              villages: [
                { id: 1904, name: 'BUTAMA I' },
                { id: 1905, name: 'KANABILAYA' },
                { id: 1906, name: 'MIRAMBI CENTRAL' },
              ],
            },
            {
              id: 249,
              name: 'NJANJA',
              villages: [
                { id: 1914, name: 'BUTAMA' },
                { id: 1913, name: 'BUTAMA  III' },
                { id: 1915, name: 'BUTAMA II' },
                { id: 1916, name: 'BUTAMA IV' },
                { id: 1917, name: 'KASUMBERIYA' },
                { id: 1919, name: 'KISELIMBE' },
                { id: 1918, name: 'NJANJA' },
              ],
            },
          ],
        },
        {
          id: 42,
          name: 'NYAHUKA  TOWN COUNCIL',
          parishes: [
            {
              id: 231,
              name: 'BHAMBA WARD',
              villages: [
                { id: 1812, name: 'BUNDIKUYALI CENTRAL' },
                { id: 1813, name: 'BUNDIKUYALI II' },
                { id: 1815, name: 'BUNDIMBERE  II' },
                { id: 1814, name: 'BUNDIMBERE  III' },
                { id: 1816, name: 'BUNDIMBERE  IV' },
              ],
            },
            {
              id: 229,
              name: 'BUNDIKAHUNGU WARD',
              villages: [
                { id: 1802, name: 'BANSOGORA' },
                { id: 1804, name: 'BUNDIKAHUNGU   EAST' },
                { id: 1803, name: 'BUNDIKAHUNGU   I' },
                { id: 1805, name: 'BUNDIKAHUNGU   WEST' },
                { id: 1806, name: 'KANANGUGU' },
              ],
            },
            {
              id: 230,
              name: 'BUNDIKUYALI WARD',
              villages: [
                { id: 1807, name: 'BUDIKUYALI  I' },
                { id: 1808, name: 'BUNDIMBERE CENTRAL' },
                { id: 1809, name: 'BUNDIMBERE I' },
                { id: 1810, name: 'KALERA' },
                { id: 1811, name: 'MAKWOLA' },
              ],
            },
            {
              id: 232,
              name: 'BUNDIMULINGA WARD',
              villages: [
                { id: 1817, name: 'BUNDIKAKEMBA III' },
                { id: 1818, name: 'BUNDIMULINGA CENTRAL' },
                { id: 1819, name: 'BUNDIMULINGA EAST' },
                { id: 1822, name: 'BUNDIMULINGA I' },
                { id: 1823, name: 'BUNDIMULINGA III' },
                { id: 1820, name: 'CHABBI' },
                { id: 1821, name: 'KAJURUGA' },
              ],
            },
            {
              id: 233,
              name: 'KAHUNGU WARD',
              villages: [
                { id: 1826, name: 'BUNDIKAHUNGU   II' },
                { id: 1827, name: 'BUNDIKAHUNGU   III' },
                { id: 1824, name: 'BUNDIKAHUNGU  CENTRAL' },
                { id: 1825, name: 'BUNDIKAHUNGU HILL' },
              ],
            },
            {
              id: 234,
              name: 'KASIRI WARD',
              villages: [
                { id: 1830, name: 'BUSU  III' },
                { id: 1829, name: 'BUSU CENTRAL' },
                { id: 1831, name: 'KASIRI' },
                { id: 1828, name: 'KASIRI CENTRAL' },
                { id: 1832, name: 'KITUULE' },
              ],
            },
            {
              id: 235,
              name: 'NYAHUKA WARD',
              villages: [
                { id: 1833, name: 'BUNDIKAHUNGU' },
                { id: 1837, name: 'BUNDIKAHUNGU  IV' },
                { id: 1834, name: 'BUNDIKAHUNGU V' },
                { id: 1838, name: 'NYAHUKA  CENTRAL' },
                { id: 1835, name: 'NYAHUKA  EAST' },
                { id: 1836, name: 'NYAHUKA  WEST' },
              ],
            },
            {
              id: 236,
              name: 'SIMBYA NKURU WARD',
              villages: [
                { id: 1839, name: 'KIJUMBU' },
                { id: 1840, name: 'NGOMA CENTRAL' },
                { id: 1841, name: 'SIMBYANKURU CENTRAL' },
                { id: 1843, name: 'SIMBYANKURU I' },
                { id: 1842, name: 'SIMBYANKURU II' },
              ],
            },
          ],
        },
        {
          id: 47,
          name: 'TOKWE',
          parishes: [
            {
              id: 257,
              name: 'BUHANDA',
              villages: [
                { id: 1980, name: 'BUHANDA CENTRAL' },
                { id: 1976, name: 'BUHANDA I' },
                { id: 1977, name: 'BUHANDA II' },
                { id: 1978, name: 'BUNDIBYESO I' },
                { id: 1981, name: 'BUNDIBYESO II' },
                { id: 1979, name: 'BUNDIKITIBO I' },
                { id: 60144, name: 'BUNDIKITIBO II' },
              ],
            },
            {
              id: 254,
              name: 'BUNDINYAMA',
              villages: [
                { id: 1953, name: 'BUNDIBUKUSU' },
                { id: 1956, name: 'BUNDIMUGAYO I' },
                { id: 60146, name: 'BUNDIMUGAYO II' },
                { id: 1954, name: 'BUNDINYAMA CENTRAL' },
                { id: 1957, name: 'BUNDINYAMA I' },
                { id: 1960, name: 'BUNDINYAMA II' },
                { id: 1958, name: 'BUNDIWELUME' },
                { id: 1955, name: 'BUNDIWELUME CENTRAL' },
                { id: 1961, name: 'BUNDIWELUME II' },
                { id: 1962, name: 'BUNDIWELUME WEST' },
                { id: 1959, name: 'MBANGO' },
              ],
            },
            {
              id: 256,
              name: 'BUNYARUTA',
              villages: [
                { id: 1968, name: 'BUGALAMA' },
                { id: 1969, name: 'BUNDIKATIGA' },
                { id: 1972, name: 'BUNYAMBUWO' },
                { id: 1973, name: 'BUNYAMWERA' },
                { id: 1974, name: 'BUNYAMWERA CENTRAL' },
                { id: 1970, name: 'BUNYARUTA  I' },
                { id: 1971, name: 'BUNYARUTA  II' },
                { id: 1975, name: 'BUNYARUTA III' },
              ],
            },
            {
              id: 258,
              name: 'HAKITENGYA',
              villages: [
                { id: 60143, name: 'BUNDIKAYANJA BOARDER' },
                { id: 1983, name: 'BUNDIKAYANJA I' },
                { id: 1982, name: 'BUNDIKAYANJA II' },
                { id: 1985, name: 'HAKITEGYA BOARDER' },
                { id: 1986, name: 'HAKITEGYA I' },
                { id: 1984, name: 'HAKITEGYA II' },
                { id: 1987, name: 'HAKITEGYA III' },
              ],
            },
            {
              id: 255,
              name: 'MATAISA',
              villages: [
                { id: 1963, name: 'HUMUNANA' },
                { id: 61919, name: 'KABIMBO' },
                { id: 1965, name: 'KANYAMWIRIMA I' },
                { id: 1964, name: 'KANYAMWIRIMA II' },
                { id: 1966, name: 'MATAISA' },
                { id: 1967, name: 'MATAISA II' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
