import { District } from '../types';

export default <District>{
  id: 29,
  name: 'BUNYANGABU',
  counties: [
    {
      id: 65,
      name: 'BUNYANGABU COUNTY',
      sub_counties: [
        {
          id: 421,
          name: 'BUHEESI',
          parishes: [
            {
              id: 1892,
              name: 'KABAHANGO',
              villages: [
                { id: 12166, name: 'BUKORAKOLE' },
                { id: 12170, name: 'GARWEYA' },
                { id: 12167, name: 'IRINDA' },
                { id: 12168, name: 'KABAHANGO I' },
                { id: 12171, name: 'KABAHANGO II' },
                { id: 12169, name: 'KIBENDE' },
                { id: 12174, name: 'KISOMORO I' },
                { id: 12172, name: 'KISOMORO II' },
                { id: 12175, name: 'KITONZI' },
                { id: 12176, name: 'LYEMBAIRE' },
                { id: 12173, name: 'RWEBIGEERA' },
              ],
            },
            {
              id: 1893,
              name: 'KIREMEZI',
              villages: [
                { id: 12177, name: 'KELEZIA' },
                { id: 12179, name: 'KIBINGI' },
                { id: 12180, name: 'KIGAYA' },
                { id: 12181, name: 'KIREMEZI' },
                { id: 12182, name: 'KISABANI' },
                { id: 12183, name: 'KYAMIYAGA A' },
                { id: 12178, name: 'KYAMIYAGA B' },
              ],
            },
          ],
        },
        {
          id: 432,
          name: 'BUHEESI TOWN COUNCIL',
          parishes: [
            {
              id: 1933,
              name: 'KIBOOTA WARD',
              villages: [
                { id: 12407, name: 'BUKIIKA  I' },
                { id: 12408, name: 'BUKIIKA  II' },
                { id: 60824, name: 'BYEREMA' },
                { id: 61253, name: 'ENGANGURA' },
                { id: 63127, name: 'KATOOKE' },
                { id: 63173, name: 'KATURRU' },
                { id: 12409, name: 'KIBOOTA' },
                { id: 12410, name: 'KIGABI A' },
                { id: 63466, name: 'KIGABI B' },
                { id: 12411, name: 'KITENGYA' },
                { id: 12412, name: 'KYABWISO' },
                { id: 12413, name: 'KYEKUMBURWA  A' },
                { id: 12414, name: 'KYEKUMBURWA  B' },
                { id: 65890, name: 'MAGOBA' },
                { id: 12415, name: 'RUHOKO' },
              ],
            },
            {
              id: 1934,
              name: 'RWENSENENE',
              villages: [
                { id: 12423, name: 'IBAALE' },
                { id: 12416, name: 'KAGUMA' },
                { id: 12417, name: 'KAIGEREKA' },
                { id: 12428, name: 'KIGARAMA' },
                { id: 12429, name: 'KIKAMBAGYA' },
                { id: 12418, name: 'KITAGU' },
                { id: 12419, name: 'KITINI' },
                { id: 12420, name: 'KITUMBI' },
                { id: 12421, name: 'KYAMATANGA I' },
                { id: 12427, name: 'KYAMATANGA II' },
                { id: 12422, name: 'MASIKA' },
                { id: 12424, name: 'NYAKAGONGO' },
                { id: 12425, name: 'NYANTWIRI' },
                { id: 12426, name: 'RWENSENENE' },
              ],
            },
          ],
        },
        {
          id: 428,
          name: 'KABONERO',
          parishes: [
            {
              id: 1918,
              name: 'BUKARA',
              villages: [
                { id: 59141, name: 'BOBOORO B' },
                { id: 12308, name: 'BUKARA' },
                { id: 12309, name: 'BUKUBA' },
                { id: 12311, name: 'BULYAMBAGHU' },
                { id: 12310, name: 'BUSANDA' },
                { id: 12312, name: 'BUTEBA' },
                { id: 12315, name: 'KABULINDA' },
                { id: 12313, name: 'KINYAMPANIKA' },
                { id: 12314, name: 'KITENGYA' },
              ],
            },
            {
              id: 1919,
              name: 'KABONERO',
              villages: [
                { id: 12316, name: 'BUNYAMUKONGO' },
                { id: 12317, name: 'BUSAMBA  I' },
                { id: 12318, name: 'BUSAMBA  II A' },
                { id: 60265, name: 'BUSAMBA II B' },
                { id: 12319, name: 'KABALEEBI A' },
                { id: 12326, name: 'KABALEEBI B' },
                { id: 12320, name: 'KABONERO A' },
                { id: 61938, name: 'KABONERO B' },
                { id: 12321, name: 'KITUNGA A' },
                { id: 64109, name: 'KITUNGA B' },
                { id: 12322, name: 'MUTITI A' },
                { id: 12327, name: 'MUTITI B' },
                { id: 12323, name: 'NSORORO' },
                { id: 12324, name: 'NYAMBA A' },
                { id: 68143, name: 'NYAMBA B' },
                { id: 12325, name: 'RWANO' },
              ],
            },
            {
              id: 1920,
              name: 'NYARUGONGO',
              villages: [
                { id: 58872, name: 'BAGORA A' },
                { id: 12328, name: 'BUKURUNGU' },
                { id: 12329, name: 'KASOGI' },
                { id: 62985, name: 'KASOGI RWIMI' },
                { id: 12330, name: 'NYARUGONGO A' },
                { id: 68250, name: 'NYARUGONGO B' },
              ],
            },
          ],
        },
        {
          id: 425,
          name: 'KATEEBWA',
          parishes: [
            {
              id: 1907,
              name: 'BUGHUMBA',
              villages: [
                { id: 12266, name: 'BUGHUMBA' },
                { id: 12268, name: 'BUNAIGA' },
                { id: 12269, name: 'MASIBWE' },
                { id: 12267, name: 'RURAMA' },
              ],
            },
            {
              id: 1905,
              name: 'BUNAIGA',
              villages: [
                { id: 12257, name: 'BUGAYA' },
                { id: 12258, name: 'BULEMEZI' },
                { id: 12260, name: 'IBEMBERO' },
                { id: 12261, name: 'KATUMBA' },
                { id: 12259, name: 'RUSEKE' },
              ],
            },
            {
              id: 1908,
              name: 'BUTYOKA',
              villages: [
                { id: 12273, name: 'BUTYOKA' },
                { id: 12271, name: 'KATEEBWA II' },
                { id: 12272, name: 'KIGANGA' },
                { id: 64145, name: 'KIYIGANGA' },
                { id: 12270, name: 'KYARWAMBA' },
              ],
            },
            {
              id: 1906,
              name: 'KATEEBWA',
              villages: [
                { id: 12262, name: 'BUNYAMANGI' },
                { id: 12263, name: 'KARUGAYA' },
                { id: 12264, name: 'KATEEBWA I' },
                { id: 12265, name: 'KIBOOTA' },
              ],
            },
          ],
        },
        {
          id: 422,
          name: 'KIBIITO',
          parishes: [
            {
              id: 1894,
              name: 'KABAALE',
              villages: [
                { id: 12184, name: 'BUGUNGU' },
                { id: 61857, name: 'KABALE INN' },
                { id: 12185, name: 'KABALE TRADING CENTRE' },
                { id: 12186, name: 'KANGOMA' },
                { id: 12187, name: 'KANYALANGO A' },
                { id: 62573, name: 'KANYALANGO B' },
                { id: 65892, name: 'MAGOMA B' },
                { id: 65893, name: 'MAGOMA C' },
                { id: 12188, name: 'MUGOMA A' },
                { id: 12189, name: 'NYABUSEESE A' },
                { id: 67936, name: 'NYABUSEESE B' },
                { id: 12190, name: 'NYAKARAMBI' },
                { id: 12191, name: 'RWENKUBA' },
              ],
            },
            {
              id: 1896,
              name: 'KASUNGANYANJA',
              villages: [
                { id: 12198, name: 'BUNJOJO' },
                { id: 12200, name: 'KASENYI' },
                { id: 12201, name: 'KASUNGANYANJA' },
                { id: 12202, name: 'KITONZI A' },
                { id: 12197, name: 'KITONZI B' },
                { id: 12203, name: 'NTABAGO A' },
                { id: 12199, name: 'NTABAGO B' },
              ],
            },
            {
              id: 1895,
              name: 'MUJUNJU',
              villages: [
                { id: 12194, name: 'MUJUNJU  I' },
                { id: 12195, name: 'MUJUNJU CENTRAL' },
                { id: 12196, name: 'NSONGYA' },
                { id: 12192, name: 'NYAMUGORO/KANYANSINGA' },
                { id: 12193, name: 'NYAMUGORO/KYATWA' },
              ],
            },
          ],
        },
        {
          id: 426,
          name: 'KIBIITO TOWN COUNCIL',
          parishes: [
            {
              id: 1909,
              name: 'CENTRAL WARD',
              villages: [
                { id: 12274, name: 'KAHOGO' },
                { id: 12275, name: 'KIBIITO B' },
                { id: 12276, name: 'KIBIITO CENTRAL' },
                { id: 12277, name: 'NKIMBIRI' },
              ],
            },
            {
              id: 1910,
              name: 'EAST WARD',
              villages: [
                { id: 12278, name: 'BUBWIKA A' },
                { id: 12280, name: 'BUBWIKA B' },
                { id: 12281, name: 'BUBWIKA C' },
                { id: 12279, name: 'BUKARA' },
              ],
            },
            {
              id: 1911,
              name: 'SOUTH EAST WARD',
              villages: [
                { id: 12282, name: 'KYATWA' },
                { id: 68015, name: 'NYAKAHANGI' },
                { id: 12283, name: 'RWENGWARA' },
                { id: 12284, name: 'RWENGWARA B' },
              ],
            },
            {
              id: 1912,
              name: 'SOUTH WEST WARD',
              villages: [
                { id: 12285, name: 'KYAKAHINDA A' },
                { id: 12286, name: 'KYAKAHINDA B' },
                { id: 68055, name: 'NYAKASOZI' },
              ],
            },
            {
              id: 1913,
              name: 'WEST WARD',
              villages: [
                { id: 12289, name: 'KAGOMA A' },
                { id: 12287, name: 'KAGOMA B' },
                { id: 12288, name: 'KAGOMA C' },
                { id: 12290, name: 'KASAALI A' },
                { id: 12291, name: 'KASAALI B' },
              ],
            },
          ],
        },
        {
          id: 423,
          name: 'KISOMORO',
          parishes: [
            {
              id: 1900,
              name: 'KAHONDO',
              villages: [
                { id: 12232, name: 'KAGOGO' },
                { id: 12233, name: 'KAHONDO' },
                { id: 12234, name: 'KYAKA' },
                { id: 12236, name: 'KYAMUHEMBA' },
                { id: 12237, name: 'NYABUHUKA A' },
                { id: 12235, name: 'NYABUHUKA B' },
              ],
            },
            {
              id: 1897,
              name: 'KICUUCU',
              villages: [
                { id: 12204, name: 'BUGABU A' },
                { id: 59281, name: 'BUGABU B' },
                { id: 12205, name: 'BUKOOKO' },
                { id: 12206, name: 'BUSIITA' },
                { id: 12207, name: 'BWEKALE' },
                { id: 12208, name: 'ITOJO' },
                { id: 12209, name: 'KABAGARA' },
                { id: 12210, name: 'KATUGUNDA' },
                { id: 12211, name: 'KICUUCU' },
                { id: 12212, name: 'KISOLIIRE' },
                { id: 12213, name: 'KITUMBA  I' },
                { id: 12214, name: 'KITUMBA  II' },
                { id: 64563, name: 'KYAKASIGA' },
                { id: 12215, name: 'KYOKYA' },
                { id: 65452, name: 'LONDANI' },
                { id: 12216, name: 'MAHUMBULI' },
                { id: 66496, name: 'MUGURANTE' },
                { id: 12217, name: 'NSAGASA A' },
                { id: 67819, name: 'NSAGASA B' },
              ],
            },
            {
              id: 1898,
              name: 'KISOMORO',
              villages: [
                { id: 59310, name: 'BUGARAMA' },
                { id: 12218, name: 'BUGOGO' },
                { id: 12219, name: 'BUKEKYA' },
                { id: 12220, name: 'KABATA' },
                { id: 12221, name: 'KABUNONO' },
                { id: 12222, name: 'KIBWOORO' },
                { id: 12223, name: 'KISOMORO  I' },
                { id: 12224, name: 'KISOMORO  II' },
                { id: 12225, name: 'MITANDI' },
                { id: 12226, name: 'NYAKIGUMBA' },
                { id: 69958, name: 'RUNYAMI' },
                { id: 70026, name: 'RWABAGAJU' },
              ],
            },
            {
              id: 1899,
              name: 'LYAMABWA',
              villages: [
                { id: 12227, name: 'BUGUZI' },
                { id: 12228, name: 'KARAMBI  I' },
                { id: 12229, name: 'KARAMBI  II' },
                { id: 12230, name: 'KITOJO' },
                { id: 64843, name: 'KYOGA' },
                { id: 12231, name: 'LYAMABWA' },
              ],
            },
          ],
        },
        {
          id: 430,
          name: 'KIYOMBYA',
          parishes: [
            {
              id: 1926,
              name: 'KASURA',
              villages: [
                { id: 12360, name: 'KASURA I' },
                { id: 12358, name: 'KASURA II' },
                { id: 12361, name: 'KYANGABUKAMA' },
                { id: 12359, name: 'MABALE' },
                { id: 12362, name: 'MASITALE' },
                { id: 12363, name: 'RUKORO' },
              ],
            },
            {
              id: 1924,
              name: 'KIYOMBYA',
              villages: [
                { id: 12351, name: 'BIREMBO' },
                { id: 12347, name: 'KANYANSINGA' },
                { id: 12349, name: 'KIGORO I' },
                { id: 12346, name: 'KIGORO II' },
                { id: 12350, name: 'LYENGUMBA' },
                { id: 12348, name: 'NYAKISI' },
              ],
            },
            {
              id: 1927,
              name: 'NYAKATONZI',
              villages: [
                { id: 12364, name: 'MAHOMA' },
                { id: 12365, name: 'MWEGENYWA' },
                { id: 12366, name: 'NSONGYA' },
                { id: 12370, name: 'NTANDA' },
                { id: 12367, name: 'NYAKASUNSA' },
                { id: 12368, name: 'NYAKATONZI' },
                { id: 12369, name: 'RWEBIJOKA' },
              ],
            },
            {
              id: 1925,
              name: 'NYAMISEKE',
              villages: [
                { id: 61504, name: 'HAKITOMA' },
                { id: 12352, name: 'KELEZIYA' },
                { id: 12353, name: 'NGANYAKI' },
                { id: 12355, name: 'NGANYAKI B' },
                { id: 12356, name: 'NYAMISEKE  I' },
                { id: 12357, name: 'NYAMISEKE  II' },
                { id: 12354, name: 'RWENGABI' },
              ],
            },
            {
              id: 1928,
              name: 'PIIDA',
              villages: [
                { id: 12371, name: 'BUTINI' },
                { id: 12372, name: 'KINYWABUSERA' },
                { id: 12374, name: 'KYAKAZINI' },
                { id: 12373, name: 'KYAWEHIGE' },
                { id: 12377, name: 'NYABAKENDA' },
                { id: 12375, name: 'PIIDA' },
                { id: 12376, name: 'RWENTUHA' },
              ],
            },
          ],
        },
        {
          id: 431,
          name: 'KYAMUKUBE TOWN COUNCIL',
          parishes: [
            {
              id: 1932,
              name: 'KYAMUKUBE WARD',
              villages: [
                { id: 12401, name: 'KAGERA' },
                { id: 12402, name: 'KAHUKU' },
                { id: 12403, name: 'KIZUNGU' },
                { id: 12400, name: 'KYAMUKUBE A' },
                { id: 12404, name: 'KYAMUKUBE B' },
                { id: 12406, name: 'NSUURA I' },
                { id: 12405, name: 'NYAMAHWA' },
              ],
            },
            {
              id: 1929,
              name: 'MITANDI WARD',
              villages: [
                { id: 12378, name: 'BUGIMA I' },
                { id: 12381, name: 'BUGIMA II' },
                { id: 59324, name: 'BUGIMA III' },
                { id: 60747, name: 'BWABYA II' },
                { id: 12379, name: 'BWALYA' },
                { id: 12380, name: 'ISULE' },
                { id: 63882, name: 'KISEBERE' },
                { id: 12384, name: 'MABWE TC' },
                { id: 12382, name: 'MITANDI  I' },
                { id: 12383, name: 'MITANDI  II' },
                { id: 12385, name: 'SIBAHIKWA' },
              ],
            },
            {
              id: 1931,
              name: 'MUTUMBA WARD',
              villages: [
                { id: 12393, name: 'BIHONDO' },
                { id: 59068, name: 'BIHONDO TRADING CENTRE' },
                { id: 59202, name: 'BUBANDI' },
                { id: 62134, name: 'KAHUNGE' },
                { id: 12394, name: 'KALERA' },
                { id: 63120, name: 'KATOMA' },
                { id: 12398, name: 'KIBWA' },
                { id: 63793, name: 'KIRANGE' },
                { id: 63874, name: 'KISANGE' },
                { id: 12395, name: 'MABURA' },
                { id: 12397, name: 'MUTUMBA' },
                { id: 12399, name: 'NYABURARA' },
                { id: 12396, name: 'NYAKWIJA' },
              ],
            },
            {
              id: 1930,
              name: 'NSUURA WARD',
              villages: [
                { id: 59319, name: 'BUGHULINJE' },
                { id: 12387, name: 'BUJABARA' },
                { id: 12389, name: 'BUKONGO' },
                { id: 59701, name: 'BULHAMBO' },
                { id: 60470, name: 'BUTINI' },
                { id: 62087, name: 'KAGHANDO' },
                { id: 12386, name: 'KAISENDA' },
                { id: 62535, name: 'KANGONZA' },
                { id: 12390, name: 'KASINDANI' },
                { id: 12392, name: 'KIBATE I' },
                { id: 63352, name: 'KIBATE II' },
                { id: 63661, name: 'KIKONZO' },
                { id: 64044, name: 'KITHOMA' },
                { id: 64500, name: 'KYABIKERE' },
                { id: 65805, name: 'LYAMURUNGU' },
                { id: 12391, name: 'NSUURA  II' },
                { id: 68108, name: 'NYAKISAMBA' },
                { id: 12388, name: 'TUSINGENE' },
              ],
            },
          ],
        },
        {
          id: 429,
          name: 'RUBONA TOWN COUNCIL',
          parishes: [
            {
              id: 1921,
              name: 'CENTRAL WARD',
              villages: [
                { id: 12332, name: 'BUHUUNA' },
                { id: 12334, name: 'BUSANDA' },
                { id: 12331, name: 'KYABAJWA' },
                { id: 12335, name: 'RUBONA  I' },
                { id: 12336, name: 'RUBONA  II' },
                { id: 12333, name: 'RUBONA TOWN' },
                { id: 12337, name: 'RUBONA TRADING CENTRE A' },
              ],
            },
            {
              id: 1922,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 12338, name: 'BIRERE' },
                { id: 12340, name: 'BURONGO  I' },
                { id: 12339, name: 'BURONGO  I B' },
                { id: 12341, name: 'BURONGO  II' },
              ],
            },
            {
              id: 1923,
              name: 'WESTERN WARD',
              villages: [
                { id: 12342, name: 'BUKAMBI' },
                { id: 12343, name: 'BULEGEYA' },
                { id: 12344, name: 'BULINDA' },
                { id: 12345, name: 'BUTUKUURU' },
              ],
            },
          ],
        },
        {
          id: 424,
          name: 'RWIMI',
          parishes: [
            {
              id: 1901,
              name: 'KADINDIMO',
              villages: [
                { id: 12238, name: 'KADINDIMO' },
                { id: 12239, name: 'KAKINGA A' },
                { id: 62215, name: 'KAKINGA B' },
                { id: 12240, name: 'KANYAMUKALE' },
                { id: 66284, name: 'MIRAMBI' },
                { id: 12241, name: 'RUBALIKA  (2A)' },
                { id: 69872, name: 'RUBALIKA  (2B)' },
                { id: 12242, name: 'RUGAAGA' },
              ],
            },
            {
              id: 1902,
              name: 'KAINA',
              villages: [
                { id: 12243, name: 'KAINA  A' },
                { id: 12244, name: 'KAINA  B' },
                { id: 62153, name: 'KAINA C' },
                { id: 12245, name: 'KARAMBI' },
                { id: 62779, name: 'KARAMBI B' },
                { id: 12246, name: 'NJARAYABAANA' },
                { id: 12247, name: 'RUSOONA' },
                { id: 12248, name: 'RWEIHARA' },
                { id: 70115, name: 'RWEIHARA B' },
              ],
            },
            {
              id: 1904,
              name: 'KAJUMIRO',
              villages: [
                { id: 12254, name: 'KAJUMIRO  A' },
                { id: 12256, name: 'KAJUMIRO  B' },
                { id: 12255, name: 'KAJUMIRO  C' },
                { id: 70304, name: 'SEMPENDA' },
              ],
            },
            {
              id: 1903,
              name: 'KAKOOGA',
              villages: [
                { id: 12249, name: 'KAKOOGA  A' },
                { id: 12250, name: 'KAKOOGA  B' },
                { id: 12251, name: 'KAKOOGA  C' },
                { id: 62245, name: 'KAKOOGA CENTRAL' },
                { id: 12252, name: 'RUBALIKA  A' },
                { id: 12253, name: 'RUBALIKA  B' },
              ],
            },
          ],
        },
        {
          id: 427,
          name: 'RWIMI TOWN COUNCIL',
          parishes: [
            {
              id: 1917,
              name: 'NYABWINA WARD',
              villages: [
                { id: 62585, name: 'KANYANSI' },
                { id: 12306, name: 'NYABWINA  A' },
                { id: 12307, name: 'NYABWINA  B' },
              ],
            },
            {
              id: 1914,
              name: 'RWIMI CENTRAL WARD',
              villages: [
                { id: 12293, name: 'KYAKATABAZI' },
                { id: 12294, name: 'KYEIBUMBA' },
                { id: 12295, name: 'MIRAMBI' },
                { id: 12297, name: 'RWIMI CENTRE A' },
                { id: 12292, name: 'RWIMI CENTRE B' },
                { id: 12296, name: 'RWIMI PRISONS' },
              ],
            },
            {
              id: 1916,
              name: 'RWIMI EAST WARD',
              villages: [
                { id: 12302, name: 'KABURAISOKE NORTH' },
                { id: 12303, name: 'KABURAISOKE SOUTH' },
                { id: 12301, name: 'KIBUNGO' },
                { id: 12305, name: 'KYANGA' },
                { id: 12304, name: 'NTAMBI' },
              ],
            },
            {
              id: 1915,
              name: 'RWIMI WEST WARD',
              villages: [
                { id: 12298, name: 'GATYANGA  I' },
                { id: 61338, name: 'GATYANGA  I B' },
                { id: 12299, name: 'GATYANGA  II' },
                { id: 12300, name: 'GATYANGA  III' },
                { id: 63696, name: 'KILEMBERI' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
