import { District } from '../types';

export default {
  id: 30,
  name: 'BUTEBO',
  counties: [
    {
      id: 66,
      name: 'BUTEBO COUNTY',
      sub_counties: [
        {
          id: 433,
          name: 'BUTEBO',
          parishes: [
            {
              id: 1935,
              name: 'BUTEBO',
              villages: [
                { id: 12430, name: 'BULYAMBWA A' },
                { id: 12441, name: 'BULYAMBWA B' },
                { id: 12431, name: 'BUSEKERO' },
                { id: 12432, name: 'BUTEBO A' },
                { id: 12433, name: 'BUTEBO B' },
                { id: 12434, name: 'KABELEKEKE A' },
                { id: 12435, name: 'KABELEKEKE B' },
                { id: 12436, name: 'KAMENYAMUGONGO' },
                { id: 12437, name: 'KAPWATAI A' },
                { id: 12442, name: 'KAPWATAI B' },
                { id: 12444, name: 'KATAKWI' },
                { id: 12438, name: 'KIRURUMA' },
                { id: 12439, name: 'KOTUYAI' },
                { id: 12440, name: 'MATAKOKORE A' },
                { id: 12443, name: 'MATAKOKORE B' },
              ],
            },
            {
              id: 1938,
              name: 'KABELAI',
              villages: [
                { id: 12466, name: 'GAYAZA A' },
                { id: 12469, name: 'GAYAZA B' },
                { id: 12467, name: 'KABELAI' },
                { id: 12468, name: 'KAYOGA' },
                { id: 12470, name: 'KOBUROKOU' },
              ],
            },
            {
              id: 9591,
              name: 'KANGADO',
              villages: [
                { id: 62520, name: 'KANGADO A' },
                { id: 62521, name: 'KANGADO B' },
                { id: 63026, name: 'KATAKWI A' },
                { id: 63027, name: 'KATAKWI B' },
                { id: 69801, name: 'RARAKA' },
                { id: 70521, name: 'SOLONKO' },
              ],
            },
            {
              id: 1936,
              name: 'KANYUM',
              villages: [
                { id: 12445, name: 'AKISIMI' },
                { id: 12451, name: 'AMUSALA' },
                { id: 12452, name: 'BUSOGA' },
                { id: 12446, name: 'KADUON' },
                { id: 12447, name: 'KALEKO' },
                { id: 12448, name: 'KANYUM A' },
                { id: 12453, name: 'KANYUM B' },
                { id: 12449, name: 'KITUBA' },
                { id: 12454, name: 'KITUBA ATAPAR' },
                { id: 12450, name: 'KOKALEN' },
              ],
            },
            {
              id: 1937,
              name: 'KASYEBAI',
              villages: [
                { id: 12455, name: 'AKOBOI' },
                { id: 12456, name: 'KALALAKA A' },
                { id: 12457, name: 'KALALAKA B' },
                { id: 12458, name: 'KANGADO' },
                { id: 12459, name: 'KASYEBAI' },
                { id: 12463, name: 'KATAKWI' },
                { id: 12464, name: 'KOMOROTOTO' },
                { id: 12465, name: 'MORUPEDEL' },
                { id: 12460, name: 'OBOKORA' },
                { id: 12461, name: 'ODIPANYA' },
                { id: 12462, name: 'SOLONKO' },
              ],
            },
            {
              id: 10148,
              name: 'ODIPANYA',
              villages: [
                { id: 57352, name: 'ACHUMET' },
                { id: 62292, name: 'KALALAKA A' },
                { id: 62293, name: 'KALALAKA B' },
                { id: 63024, name: 'KATAKA' },
                { id: 63835, name: 'KIRURUMA A' },
                { id: 63836, name: 'KIRURUMA B' },
                { id: 64256, name: 'KOMOLO' },
                { id: 66415, name: 'MORUPEDEL' },
                { id: 68358, name: 'OBOKORA A' },
                { id: 68359, name: 'OBOKORA B' },
                { id: 68469, name: 'ODIPANYA' },
                { id: 70314, name: 'SETA' },
              ],
            },
          ],
        },
        {
          id: 1990,
          name: 'KABELAI',
          parishes: [
            {
              id: 9476,
              name: 'GAYAZA',
              villages: [
                { id: 59430, name: 'BUKALIGWOKO' },
                { id: 61341, name: 'GAYAZA A' },
                { id: 61343, name: 'GAYAZA B' },
                { id: 66609, name: 'MUMPI' },
              ],
            },
            {
              id: 9520,
              name: 'KABELAI',
              villages: [
                { id: 60304, name: 'BUSETA' },
                { id: 61902, name: 'KABELAI' },
                { id: 64176, name: 'KOBUROKOU A' },
                { id: 64177, name: 'KOBUROKOU B' },
              ],
            },
            {
              id: 9662,
              name: 'KAYOGA',
              villages: [
                { id: 59431, name: 'BUKALIJOKO' },
                { id: 60306, name: 'BUSETA' },
                { id: 60419, name: 'BUSWENZA' },
                { id: 63232, name: 'KAYOGA' },
              ],
            },
          ],
        },
        {
          id: 434,
          name: 'KABWANGASI',
          parishes: [
            {
              id: 9319,
              name: 'BULALAKA',
              villages: [
                { id: 59467, name: 'BUKATIKOKO' },
                { id: 59596, name: 'BUKOMOLO' },
                { id: 59665, name: 'BULALAKA' },
                { id: 59849, name: 'BUMESURA' },
              ],
            },
            {
              id: 9447,
              name: 'DOKO',
              villages: [
                { id: 60195, name: 'BUNYEKERO' },
                { id: 61155, name: 'DOKO I' },
                { id: 61630, name: 'INDUSTRIAL' },
                { id: 67545, name: 'NASENYI II' },
              ],
            },
            {
              id: 1939,
              name: 'KACHURU',
              villages: [
                { id: 12477, name: 'KACHURU' },
                { id: 12471, name: 'KATEKI' },
                { id: 12472, name: 'KATUBAI' },
                { id: 12478, name: 'KINAKUMI' },
                { id: 12479, name: 'KISOGA' },
                { id: 12473, name: 'KOMOLO' },
                { id: 12474, name: 'OGWERE' },
                { id: 12475, name: 'RARAKA I' },
                { id: 12476, name: 'RARAKA II' },
              ],
            },
            {
              id: 9574,
              name: 'KALOJA',
              villages: [
                { id: 60182, name: 'BUNGWANYI' },
                { id: 60795, name: 'BWIBERE' },
                { id: 62345, name: 'KALOJA I' },
                { id: 62346, name: 'KALOJA II' },
              ],
            },
            {
              id: 1940,
              name: 'MAIZIMASA',
              villages: [
                { id: 12488, name: 'BUGOLO' },
                { id: 12489, name: 'IKI-IKI' },
                { id: 12480, name: 'KAKORO' },
                { id: 12481, name: 'KAWORIA' },
                { id: 12482, name: 'KOMOLO' },
                { id: 12483, name: 'MAIZIMASA' },
                { id: 12490, name: 'NAKAWA' },
                { id: 12484, name: 'OKAKATYO' },
                { id: 12485, name: 'OSOMORA' },
                { id: 12486, name: 'SUKUSUKU' },
                { id: 12487, name: 'TIIRA' },
              ],
            },
            {
              id: 1942,
              name: 'NASENYI',
              villages: [
                { id: 12501, name: 'BUKACHERA' },
                { id: 12502, name: 'BULALAKA' },
                { id: 12506, name: 'BUNYEKERO' },
                { id: 12507, name: 'BWIBERE' },
                { id: 12503, name: 'DOKO I' },
                { id: 12504, name: 'KALOJA' },
                { id: 12505, name: 'NASENYI' },
              ],
            },
            {
              id: 1941,
              name: 'PUTTI',
              villages: [
                { id: 12500, name: 'BUKATIKOKO' },
                { id: 12498, name: 'BUKOMOLO' },
                { id: 12491, name: 'BULOKI' },
                { id: 12492, name: 'BUNAMWERA' },
                { id: 12499, name: 'MBULA' },
                { id: 12493, name: 'NABIKU' },
                { id: 12494, name: 'NABITENDE' },
                { id: 12495, name: 'NYADERA' },
                { id: 12496, name: 'PUTTI' },
                { id: 12497, name: 'TIIRA  I' },
              ],
            },
          ],
        },
        {
          id: 436,
          name: 'KABWANGASI TOWN COUNCIL',
          parishes: [
            {
              id: 1947,
              name: 'KABWANGASI WARD',
              villages: [
                { id: 12532, name: 'JAWA' },
                { id: 12530, name: 'KABWANGASI' },
                { id: 12531, name: 'OGOSOI' },
              ],
            },
            {
              id: 1948,
              name: 'KASEKINYI WARD',
              villages: [
                { id: 12535, name: 'BYAKIKA' },
                { id: 12533, name: 'KABWANGASI COLLEGE' },
                { id: 12534, name: 'KASEKENYI' },
              ],
            },
            {
              id: 1949,
              name: 'MORUTOME WARD',
              villages: [
                { id: 12537, name: 'BUDUKULO' },
                { id: 12538, name: 'BWASE' },
                { id: 12536, name: 'MORUTOME' },
              ],
            },
          ],
        },
        {
          id: 1993,
          name: 'KACHURU',
          parishes: [
            {
              id: 9530,
              name: 'KACHURU',
              villages: [
                { id: 59758, name: 'BULYAMBWA' },
                { id: 62012, name: 'KACHURU' },
                { id: 63057, name: 'KATEKI' },
                { id: 64259, name: 'KOMOLO II' },
              ],
            },
            {
              id: 9652,
              name: 'KATUBAI',
              villages: [
                { id: 60307, name: 'BUSETA II' },
                { id: 63146, name: 'KATUBAI' },
                { id: 63938, name: 'KISOGA' },
                { id: 68606, name: 'OGWERE' },
              ],
            },
            {
              id: 9727,
              name: 'KINAKUMI',
              villages: [
                { id: 59466, name: 'BUKATIKOKO' },
                { id: 63734, name: 'KINAKUMI' },
                { id: 69807, name: 'RARAKA I' },
                { id: 69809, name: 'RARAKA II' },
              ],
            },
          ],
        },
        {
          id: 1994,
          name: 'KADOKOLENE',
          parishes: [
            {
              id: 9280,
              name: 'BUCHEMA',
              villages: [
                { id: 59252, name: 'BUCHEMA' },
                { id: 59721, name: 'BULOKI' },
                { id: 61558, name: 'IDOTOI' },
              ],
            },
            {
              id: 9535,
              name: 'KADOKOLENE',
              villages: [
                { id: 59438, name: 'BUKAMUGEWO' },
                { id: 59560, name: 'BUKINOMO' },
                { id: 59600, name: 'BUKOMOLO' },
                { id: 60767, name: 'BWASE' },
                { id: 62032, name: 'KADOKOLENE' },
              ],
            },
            {
              id: 9646,
              name: 'KATERYO',
              villages: [
                { id: 59346, name: 'BUGOLYA' },
                { id: 59594, name: 'BUKOMBA' },
                { id: 63073, name: 'KATERYO' },
              ],
            },
          ],
        },
        {
          id: 435,
          name: 'KAKORO',
          parishes: [
            {
              id: 1943,
              name: 'KADOKOLENE',
              villages: [
                { id: 12508, name: 'BUGOLYA' },
                { id: 12510, name: 'BUKAMUGEWO' },
                { id: 12512, name: 'BUKOMBA' },
                { id: 12509, name: 'BUKOMOLO' },
                { id: 12511, name: 'KADOKOLENE' },
                { id: 12513, name: 'KATERYO' },
              ],
            },
            {
              id: 9536,
              name: 'KADOTO',
              villages: [
                { id: 59227, name: 'BUBULANGA' },
                { id: 62034, name: 'KADOTO' },
                { id: 63187, name: 'KAVULE' },
                { id: 65913, name: 'MAIZIMASA' },
              ],
            },
            {
              id: 1944,
              name: 'KAKORO',
              villages: [
                { id: 12514, name: 'BUBULANGA' },
                { id: 59425, name: 'BUKAKATYO' },
                { id: 12516, name: 'KABEKUN A' },
                { id: 12517, name: 'KADOTO' },
                { id: 12518, name: 'KAKORO' },
                { id: 12515, name: 'KAVULE' },
                { id: 12519, name: 'MAIZIMASA' },
                { id: 12520, name: 'OKURUKA' },
              ],
            },
            {
              id: 1946,
              name: 'KASAJJA',
              villages: [
                { id: 12529, name: 'BUKATIKOMBA' },
                { id: 12526, name: 'KALECHERU' },
                { id: 12527, name: 'KASAJJA A' },
                { id: 12528, name: 'KASONE' },
              ],
            },
            {
              id: 1945,
              name: 'TEKWANA',
              villages: [
                { id: 12521, name: 'BUKOMOLO' },
                { id: 12522, name: 'OGURAMAI' },
                { id: 12525, name: 'OKAWORIA' },
                { id: 12523, name: 'PETTA' },
                { id: 12524, name: 'TEKWANA' },
              ],
            },
          ],
        },
        {
          id: 1997,
          name: 'KAKORO TOWN COUNCIL',
          parishes: [
            {
              id: 9459,
              name: 'EASTERN WARD',
              villages: [
                { id: 59463, name: 'BUKATEGULE' },
                { id: 59468, name: 'BUKATIKOKO A' },
                { id: 61900, name: 'KABEKUN B' },
              ],
            },
            {
              id: 9548,
              name: 'KAITISYA WARD',
              villages: [
                { id: 60197, name: 'BUNYOLO' },
                { id: 62162, name: 'KAITISYA A' },
                { id: 66539, name: 'MUKOGE' },
              ],
            },
            {
              id: 9620,
              name: 'KASAJJA WARD',
              villages: [
                { id: 59470, name: 'BUKATIKOMBA' },
                { id: 62306, name: 'KALECHERU' },
                { id: 62871, name: 'KASAJJA A' },
                { id: 62990, name: 'KASONE' },
              ],
            },
            {
              id: 10095,
              name: 'NORTHERN WARD',
              villages: [
                { id: 59850, name: 'BUMESURA A' },
                { id: 59851, name: 'BUMESURA B' },
                { id: 59902, name: 'BUMUSANA' },
                { id: 70511, name: 'SOGONO A' },
                { id: 70512, name: 'SOGONO B' },
              ],
            },
            {
              id: 10346,
              name: 'WESTERN WARD',
              villages: [
                { id: 59469, name: 'BUKATIKOKO B' },
                { id: 59719, name: 'BULOKI' },
                { id: 62163, name: 'KAITISYA B' },
                { id: 62872, name: 'KASAJJA B' },
              ],
            },
          ],
        },
        {
          id: 438,
          name: 'KANGINIMA',
          parishes: [
            {
              id: 1956,
              name: 'KANGINIMA',
              villages: [
                { id: 12585, name: 'BUPADOYI' },
                { id: 12586, name: 'KANGINIMA' },
                { id: 12587, name: 'LUKONE' },
                { id: 12588, name: 'WENENE' },
              ],
            },
            {
              id: 1957,
              name: 'KASUPETE',
              villages: [
                { id: 12590, name: 'BULALAKA' },
                { id: 12591, name: 'DODOI' },
                { id: 12592, name: 'KASUPETE' },
                { id: 12589, name: 'NAKALOKE' },
              ],
            },
            {
              id: 1955,
              name: 'KITOIKA WONONI',
              villages: [
                { id: 12581, name: 'KATIKA' },
                { id: 12580, name: 'KATORONGO' },
                { id: 12583, name: 'KITOIKAWONONI' },
                { id: 12582, name: 'LADOTO' },
                { id: 12584, name: 'TINGOLI' },
              ],
            },
            {
              id: 1958,
              name: 'NALIDI',
              villages: [
                { id: 12593, name: 'BUGUMBA' },
                { id: 12594, name: 'KADALACHI' },
                { id: 12595, name: 'KISENYI' },
                { id: 12596, name: 'NALIDI I' },
                { id: 12597, name: 'NALIDI II' },
              ],
            },
          ],
        },
        {
          id: 2006,
          name: 'KANYUM',
          parishes: [
            {
              id: 9167,
              name: 'AKISIM',
              villages: [
                { id: 57797, name: 'AKISIM B' },
                { id: 57798, name: 'AKISIMI A' },
                { id: 58211, name: 'AMUSALA A' },
                { id: 58212, name: 'AMUSALA B' },
                { id: 62308, name: 'KALEKO A' },
                { id: 62309, name: 'KALEKO B' },
                { id: 68377, name: 'OBULE' },
              ],
            },
            {
              id: 9537,
              name: 'KADUYON',
              villages: [
                { id: 62041, name: 'KADUYON A' },
                { id: 62042, name: 'KADUYON B' },
                { id: 68666, name: 'OKAWORIA' },
                { id: 68948, name: 'OMESURA' },
              ],
            },
            {
              id: 9600,
              name: 'KANYUM',
              villages: [
                { id: 62612, name: 'KANYUM A' },
                { id: 62613, name: 'KANYUM B' },
                { id: 64099, name: 'KITUBA A' },
                { id: 64101, name: 'KITUBA B' },
                { id: 68517, name: 'ODUKURO' },
              ],
            },
            {
              id: 9787,
              name: 'KOKALEN',
              villages: [
                { id: 60385, name: 'BUSOGA' },
                { id: 64100, name: 'KITUBA ATAPAR' },
                { id: 64209, name: 'KOKALEN' },
                { id: 68476, name: 'ODOKET KILOKI' },
              ],
            },
          ],
        },
        {
          id: 2010,
          name: 'KAPUNYASI',
          parishes: [
            {
              id: 9401,
              name: 'BUYEDA',
              villages: [
                { id: 60204, name: 'BUPALAMA' },
                { id: 60722, name: 'BUYEDA A' },
                { id: 61746, name: 'JAMI-JAMI' },
                { id: 67301, name: 'NAMEDDE' },
              ],
            },
            {
              id: 9615,
              name: 'KAPUNYASI',
              villages: [
                { id: 61135, name: 'DISIRI' },
                { id: 61986, name: 'KABWALALI' },
                { id: 62753, name: 'KAPUNYASI' },
                { id: 66911, name: 'NABWALI' },
              ],
            },
            {
              id: 10072,
              name: 'NASULETA',
              villages: [
                { id: 59472, name: 'BUKAURYA' },
                { id: 59848, name: 'BUMESULA' },
                { id: 63854, name: 'KIRYOLO' },
                { id: 67587, name: 'NASULETA' },
              ],
            },
          ],
        },
        {
          id: 2061,
          name: 'MAIZIMASA',
          parishes: [
            {
              id: 9658,
              name: 'KAWOJAN',
              villages: [
                { id: 58897, name: 'BANDA' },
                { id: 62250, name: 'KAKORO' },
                { id: 66118, name: 'MATENDE' },
                { id: 68658, name: 'OKAKATYO' },
                { id: 69268, name: 'OSOMORA' },
              ],
            },
            {
              id: 9791,
              name: 'KOMOLO',
              villages: [
                { id: 59420, name: 'BUKADUKA' },
                { id: 63775, name: 'KINYOLE' },
                { id: 64257, name: 'KOMOLO' },
                { id: 67027, name: 'NAKAWA' },
                { id: 68667, name: 'OKAWORIA' },
              ],
            },
            {
              id: 9952,
              name: 'MAIZIMASA',
              villages: [
                { id: 59344, name: 'BUGOLO' },
                { id: 61601, name: 'IKI-IKI' },
                { id: 61696, name: 'ITAKA-IWOLU' },
                { id: 62062, name: 'KAFUNGO' },
                { id: 65914, name: 'MAIZIMASA' },
              ],
            },
            {
              id: 10306,
              name: 'SUKUSUKU',
              villages: [
                { id: 59667, name: 'BULALAKA' },
                { id: 62176, name: 'KAJULE' },
                { id: 67822, name: 'NSAMBYA' },
                { id: 70553, name: 'SUKUSUKU' },
                { id: 70743, name: 'TIIRA' },
              ],
            },
          ],
        },
        {
          id: 437,
          name: 'PETETE',
          parishes: [
            {
              id: 1953,
              name: 'KACHABALI',
              villages: [
                { id: 12569, name: 'BURWETA' },
                { id: 12565, name: 'BUYEDA B' },
                { id: 12566, name: 'KACHABALI' },
                { id: 12570, name: 'KACHABALI COMPLEX' },
                { id: 12571, name: 'KALYANTE' },
                { id: 12567, name: 'MANYOWE' },
                { id: 12568, name: 'NALYETE' },
              ],
            },
            {
              id: 1954,
              name: 'KACHOCHA',
              villages: [
                { id: 12576, name: 'BUGANZA' },
                { id: 12577, name: 'BUKATIKOKO' },
                { id: 12578, name: 'BULYAWITA' },
                { id: 12572, name: 'BUNAMWERA' },
                { id: 12573, name: 'KABELEKEKE' },
                { id: 12574, name: 'KACHOCHA' },
                { id: 12579, name: 'KADOTO' },
                { id: 12575, name: 'NAMUSWATA' },
              ],
            },
            {
              id: 1950,
              name: 'KAPUNYASI',
              villages: [
                { id: 12545, name: 'BUKAWOLYA' },
                { id: 12546, name: 'BUMESULA' },
                { id: 12539, name: 'BUPALAMA' },
                { id: 12540, name: 'BUYEDA A' },
                { id: 12547, name: 'DISIRI' },
                { id: 12548, name: 'JAMI-JAMI' },
                { id: 12549, name: 'KABWALALI' },
                { id: 12541, name: 'KAPUNYASI' },
                { id: 12542, name: 'KIRYOLO' },
                { id: 12543, name: 'NABWALI' },
                { id: 12550, name: 'NAMEDDE' },
                { id: 12544, name: 'NASULETA' },
              ],
            },
            {
              id: 9962,
              name: 'MANYOWE',
              villages: [
                { id: 60248, name: 'BURWETA' },
                { id: 62392, name: 'KALYANTE' },
                { id: 66034, name: 'MANYOWE' },
                { id: 67196, name: 'NALYETE' },
              ],
            },
            {
              id: 1951,
              name: 'PETETE',
              villages: [
                { id: 12555, name: 'BUKALIGWOKO' },
                { id: 12556, name: 'BUKOMOLO' },
                { id: 12557, name: 'BULALAKA' },
                { id: 12551, name: 'KABUYAYI' },
                { id: 12558, name: 'KAKWERETA' },
                { id: 12552, name: 'KAVULE' },
                { id: 12553, name: 'KOSINGHE' },
                { id: 12554, name: 'PETETE' },
              ],
            },
            {
              id: 1952,
              name: 'SIDANYI',
              villages: [
                { id: 12563, name: 'BUDOBA' },
                { id: 59471, name: 'BUKATUKI' },
                { id: 59597, name: 'BUKOMOLO' },
                { id: 12559, name: 'KABUSULE A' },
                { id: 12560, name: 'KABUSULE B' },
                { id: 12561, name: 'SIDANYI A' },
                { id: 12562, name: 'SIDANYI B' },
                { id: 12564, name: 'SIDANYI CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 2107,
          name: 'PUTTI',
          parishes: [
            {
              id: 9323,
              name: 'BULOKI',
              villages: [
                { id: 59342, name: 'BUGOLIA' },
                { id: 59718, name: 'BULOKI' },
                { id: 64469, name: 'KYABAGWERE' },
                { id: 66149, name: 'MAUDO' },
                { id: 66202, name: 'MBULA' },
              ],
            },
            {
              id: 10025,
              name: 'NABIKU',
              villages: [
                { id: 59343, name: 'BUGOLO' },
                { id: 59464, name: 'BUKATIKOKO' },
                { id: 66203, name: 'MBULAMBAGO' },
                { id: 66829, name: 'NABIKU' },
              ],
            },
            {
              id: 10029,
              name: 'NABITENDE',
              villages: [
                { id: 60084, name: 'BUNAMWERA' },
                { id: 60388, name: 'BUSOMORA' },
                { id: 62460, name: 'KAMUGO' },
                { id: 63903, name: 'KISENYI' },
                { id: 66851, name: 'NABITENDE' },
              ],
            },
            {
              id: 10253,
              name: 'PUTTI',
              villages: [
                { id: 59599, name: 'BUKOMOLO' },
                { id: 59759, name: 'BULYAMPITI' },
                { id: 60384, name: 'BUSOBYA' },
                { id: 66485, name: 'MUGANZI' },
                { id: 69763, name: 'PUTTI' },
              ],
            },
            {
              id: 10318,
              name: 'TIIRA',
              villages: [
                { id: 59670, name: 'BULALAKA' },
                { id: 60303, name: 'BUSETA' },
                { id: 67955, name: 'NYADERA' },
                { id: 70744, name: 'TIIRA  I' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
