import { District } from '../index';

export default {
  id: 111,
  name: 'BUYENDE',
  counties: [
    {
      id: 266,
      name: 'BUDIOPE EAST COUNTY',
      sub_counties: [
        {
          id: 1732,
          name: 'BUGAYA',
          parishes: [
            {
              id: 8212,
              name: 'BUGAYA',
              villages: [
                { id: 50924, name: 'BUGAYA T/CENTRE' },
                { id: 59317, name: 'BUGEMBE' },
                { id: 59648, name: 'BUKWAYA' },
                { id: 50925, name: 'BULINDA I' },
                { id: 50926, name: 'BULINDA II' },
                { id: 50927, name: 'BULINDA/BWASE' },
                { id: 50929, name: 'BUSEMBERA-BUTITI' },
                { id: 50928, name: 'BUWAIDHENO' },
              ],
            },
            {
              id: 8215,
              name: 'BUSAABI',
              villages: [
                { id: 59027, name: 'BEKULA T.C' },
                { id: 59356, name: 'BUGULUSI' },
                { id: 59576, name: 'BUKITIMBO' },
                { id: 50939, name: 'BUKOFU' },
                { id: 59591, name: 'BUKOLE' },
                { id: 59608, name: 'BUKOOSE' },
                { id: 59688, name: 'BULEGEYA A' },
                { id: 59689, name: 'BULEGEYA B' },
                { id: 60250, name: 'BUSAABI-BUBUGUDHO' },
                { id: 60658, name: 'BUWAZA' },
                { id: 67193, name: 'NALWOOSE' },
              ],
            },
            {
              id: 8213,
              name: 'BUTASWA',
              villages: [
                { id: 50930, name: 'BUGWERI' },
                { id: 50931, name: 'BUKITIMBO' },
                { id: 50932, name: 'BUKOKOBA' },
                { id: 50935, name: 'BUKOSE' },
                { id: 50933, name: 'BUNYWANYI' },
                { id: 50934, name: 'BUWANGA' },
                { id: 60670, name: 'BUWELYA' },
                { id: 62580, name: 'KANYANGO' },
                { id: 63247, name: 'KAZIGO' },
                { id: 66822, name: 'NABIGWO' },
                { id: 67026, name: 'NAKAVUMA' },
              ],
            },
            {
              id: 8216,
              name: 'IRAAPA',
              villages: [
                { id: 50940, name: 'BUBALIYO A' },
                { id: 59200, name: 'BUBALIYO B' },
                { id: 59358, name: 'BUGUNDULYA' },
                { id: 59475, name: 'BUKELEMENTI' },
                { id: 59657, name: 'BULAGALA' },
                { id: 50941, name: 'BULUBAALE' },
                { id: 59735, name: 'BULUBAALE BUWAYA' },
                { id: 50942, name: 'BUWADAMU' },
              ],
            },
            {
              id: 8217,
              name: 'KIGWERI',
              villages: [
                { id: 59201, name: 'BUBANDA' },
                { id: 59612, name: 'BUKOSIYA' },
                { id: 50943, name: 'BUKYOMBA A' },
                { id: 59654, name: 'BUKYOMBA B' },
                { id: 60205, name: 'BUPENDO' },
                { id: 50944, name: 'BUSOBYA' },
              ],
            },
            {
              id: 8218,
              name: 'NAMUKUNYU',
              villages: [
                { id: 50945, name: 'BUDHUGU' },
                { id: 50947, name: 'BUDOOGO A' },
                { id: 59272, name: 'BUDOOGO B' },
                { id: 59331, name: 'BUGOBI' },
                { id: 59449, name: 'BUKANIFA' },
                { id: 59746, name: 'BULUNGU' },
                { id: 50946, name: 'BUSISIRO' },
                { id: 50948, name: 'BUSUSWA/BUKIIKA' },
                { id: 50949, name: 'BUSWANKAMA' },
              ],
            },
            {
              id: 8214,
              name: 'NAMUSIKIZI',
              villages: [
                { id: 59653, name: 'BUKYELAGA' },
                { id: 50937, name: 'BUSAAMA A' },
                { id: 60251, name: 'BUSAAMA B' },
                { id: 50938, name: 'BUTUBI' },
                { id: 50936, name: 'KYELAGA' },
              ],
            },
          ],
        },
        {
          id: 1735,
          name: 'GUMPI',
          parishes: [
            {
              id: 8233,
              name: 'BUDOLA',
              villages: [
                { id: 51019, name: 'BUNABALA' },
                { id: 51018, name: 'BUSULU' },
                { id: 51017, name: 'KIRONGO' },
                { id: 63828, name: 'KIRONGO T.C' },
              ],
            },
            {
              id: 8231,
              name: 'GUMPI',
              villages: [
                { id: 59270, name: 'BUDONGA' },
                { id: 51003, name: 'BUDOPE' },
                { id: 51004, name: 'BULEERO/BUZIBU' },
                { id: 51005, name: 'BUSIGE' },
                { id: 51006, name: 'BUSIKWE A' },
                { id: 51009, name: 'BUSIKWE B' },
                { id: 51010, name: 'BUSULEETA' },
                { id: 51007, name: 'BUSUMBA' },
                { id: 51008, name: 'GABULA' },
              ],
            },
            {
              id: 8234,
              name: 'INNULA',
              villages: [
                { id: 59264, name: 'BUDHATUMMU' },
                { id: 59647, name: 'BUKWAYA' },
                { id: 51020, name: 'BUKWAYA/BUTOOLI' },
                { id: 59649, name: 'BUKWAYA/BUTOOLI T.C' },
                { id: 51021, name: 'BUSINGA/BUDHATUMU' },
                { id: 60410, name: 'BUSUSWA' },
                { id: 60413, name: 'BUSUUBO' },
                { id: 60476, name: 'BUTOOLI' },
                { id: 51022, name: 'BUTOOLI/BUSUBO' },
                { id: 51023, name: 'BUTOOLI/BUSUSWA' },
                { id: 61638, name: 'INNULA T/C' },
                { id: 61639, name: 'INNULA-BUTOOLI' },
              ],
            },
            {
              id: 8235,
              name: 'KIMBAYA',
              villages: [
                { id: 59434, name: 'BUKALINAKI' },
                { id: 59678, name: 'BULANGIRA A' },
                { id: 59679, name: 'BULANGIRA B' },
                { id: 59717, name: 'BULODI' },
                { id: 60353, name: 'BUSIMBA' },
                { id: 51024, name: 'KIMBAYA' },
                { id: 51025, name: 'LUKOTAIME' },
                { id: 66999, name: 'NAKALAMA' },
              ],
            },
            {
              id: 8232,
              name: 'KITUKIRO',
              villages: [
                { id: 51015, name: 'BUDOOLI' },
                { id: 51011, name: 'BUGUNDHO/BUDOOLI' },
                { id: 59450, name: 'BUKANOBE' },
                { id: 51012, name: 'BULANGIRA' },
                { id: 51013, name: 'BUSUUSA' },
                { id: 60415, name: 'BUSUUSWA' },
                { id: 51014, name: 'BUWAIBUGA' },
                { id: 51016, name: 'KYABAGOOLE' },
                { id: 64468, name: 'KYABAGOOLE-BUSAALA' },
              ],
            },
            {
              id: 8236,
              name: 'NABITULA',
              villages: [
                { id: 51026, name: 'BUBEKO' },
                { id: 59208, name: 'BUBEKO-BUGOLO' },
                { id: 51030, name: 'BUBIRO' },
                { id: 51027, name: 'BUDHONGA' },
                { id: 51032, name: 'BUGEMBE' },
                { id: 51031, name: 'BUKAMIRA' },
                { id: 51028, name: 'BUKIIKA' },
                { id: 60270, name: 'BUSANGA' },
                { id: 51029, name: 'BWOGEREZA' },
              ],
            },
          ],
        },
        {
          id: 1736,
          name: 'IRUNDU',
          parishes: [
            {
              id: 8239,
              name: 'BUDIPA',
              villages: [
                { id: 51047, name: 'BUDIPA I' },
                { id: 51048, name: 'BUDIPA II' },
                { id: 51049, name: 'BULUNDA' },
                { id: 51050, name: 'KASSEKENYI' },
                { id: 63391, name: 'KIBUGO' },
              ],
            },
            {
              id: 8237,
              name: 'BUKUTULA',
              villages: [
                { id: 51033, name: 'BUGANZA' },
                { id: 51034, name: 'BUKUTULA' },
                { id: 51035, name: 'BULAGALA' },
                { id: 51036, name: 'BUNANGWE' },
                { id: 51037, name: 'BUSOOKO' },
                { id: 51038, name: 'MASABA' },
                { id: 51039, name: 'NADIOPE' },
                { id: 51040, name: 'NAKAWUNA' },
              ],
            },
            {
              id: 9500,
              name: 'IGALAZA',
              villages: [
                { id: 60445, name: 'BUTEIRA B' },
                { id: 66458, name: 'MPUNDE B' },
                { id: 66988, name: 'NAKABEMBE B' },
              ],
            },
            {
              id: 8240,
              name: 'IGARAZA',
              villages: [
                { id: 51051, name: 'BULONDO' },
                { id: 51052, name: 'BUTEIRA A' },
                { id: 51053, name: 'IGALAZA' },
                { id: 51054, name: 'KINAMAIGA' },
                { id: 51055, name: 'MPUNDE A' },
                { id: 51056, name: 'NAKABEMBE A' },
                { id: 51057, name: 'NGEREKA' },
              ],
            },
            {
              id: 8238,
              name: 'NKOONE',
              villages: [
                { id: 51041, name: 'BUKYAALA' },
                { id: 51042, name: 'BUPIOKO' },
                { id: 51043, name: 'BUTOOLI A' },
                { id: 51044, name: 'BUTOOLI B' },
                { id: 51045, name: 'NADIOPE/NAIKA' },
                { id: 51046, name: 'NAMALOGWE' },
              ],
            },
          ],
        },
        {
          id: 1733,
          name: 'IRUNDU TOWN COUNCIL',
          parishes: [
            {
              id: 8219,
              name: 'BUGULUSI WARD',
              villages: [
                { id: 59016, name: 'BBUDORYO A' },
                { id: 50950, name: 'BUKOKOLA B' },
                { id: 50951, name: 'BUKOKOLA C' },
                { id: 50952, name: 'BUSAMBA' },
                { id: 64353, name: 'KUBOTA A' },
                { id: 64354, name: 'KUBOTA B' },
              ],
            },
            {
              id: 8222,
              name: 'IRUNDU WARD',
              villages: [
                { id: 59587, name: 'BUKOKOLA A' },
                { id: 59588, name: 'BUKOKOLA B' },
                { id: 59589, name: 'BUKOKOLA C' },
                { id: 59590, name: 'BUKOKOLA D' },
                { id: 50956, name: 'BUTEGERE C' },
                { id: 61668, name: 'IRUNDU  B' },
                { id: 50957, name: 'KUBOTA A' },
                { id: 50958, name: 'KUBOTA B' },
              ],
            },
            {
              id: 8220,
              name: 'KAGWA WARD',
              villages: [
                { id: 59017, name: 'BBUDORYO B' },
                { id: 59693, name: 'BULEMEZI A' },
                { id: 59694, name: 'BULEMEZI B' },
                { id: 50953, name: 'KAGWA A' },
                { id: 62121, name: 'KAGWA B' },
              ],
            },
            {
              id: 8221,
              name: 'KANAKU WARD',
              villages: [
                { id: 60442, name: 'BUTEGERE A' },
                { id: 60443, name: 'BUTEGERE B' },
                { id: 60444, name: 'BUTEGERE C' },
                { id: 50954, name: 'DONGI A' },
                { id: 50955, name: 'DONGI B' },
                { id: 67380, name: 'NAMUNYINGI' },
              ],
            },
          ],
        },
        {
          id: 1734,
          name: 'KAGULU',
          parishes: [
            {
              id: 8223,
              name: 'BUMOGOLI',
              villages: [
                { id: 50959, name: 'BUGALU' },
                { id: 50960, name: 'BUGULUSI' },
                { id: 50961, name: 'BULABE' },
                { id: 50962, name: 'BUSOLO' },
                { id: 50963, name: 'BUWALUKA' },
                { id: 50964, name: 'BUWANGA' },
                { id: 50965, name: 'KAMUGOYA' },
                { id: 50966, name: 'MAIRO' },
                { id: 50967, name: 'NAKAWOLO' },
              ],
            },
            {
              id: 8227,
              name: 'BUYUMBA',
              villages: [
                { id: 60741, name: 'BUYUMBA A' },
                { id: 50986, name: 'BUYUMBA B' },
                { id: 50987, name: 'IGWAYA' },
                { id: 50988, name: 'KITOIKI' },
                { id: 50989, name: 'NAMWIZUKYA' },
              ],
            },
            {
              id: 8224,
              name: 'IYINGO',
              villages: [
                { id: 50968, name: 'BULONGOOLI' },
                { id: 50969, name: 'IYINGO TOWN' },
                { id: 50970, name: 'KASANGA' },
                { id: 50971, name: 'KASOZI' },
                { id: 50972, name: 'NAGANGAMA A' },
                { id: 66953, name: 'NAGANGAMA B' },
                { id: 50973, name: 'NAKATWE' },
              ],
            },
            {
              id: 8225,
              name: 'KABUKYE',
              villages: [
                { id: 59302, name: 'BUGANIRA' },
                { id: 50974, name: 'BUNANGWE' },
                { id: 50975, name: 'BUSIGE' },
                { id: 61958, name: 'KABUKYE' },
                { id: 50976, name: 'KAMERI' },
                { id: 63699, name: 'KILIMBI' },
                { id: 50977, name: 'NABUKU' },
                { id: 50978, name: 'NGOLE' },
              ],
            },
            {
              id: 8226,
              name: 'KAGULU',
              villages: [
                { id: 50979, name: 'BULANGIRA' },
                { id: 50981, name: 'BUTAKOMA' },
                { id: 60449, name: 'BUTEMEERA A' },
                { id: 60450, name: 'BUTEMEERA B' },
                { id: 50982, name: 'BUWERYA/BULUBA' },
                { id: 50983, name: 'GABONA' },
                { id: 62461, name: 'KAMUGOYA' },
                { id: 50984, name: 'KIBIRA/KYEZA' },
                { id: 66300, name: 'MIRU' },
                { id: 50985, name: 'NALIINA' },
                { id: 50980, name: 'NALUWA' },
              ],
            },
            {
              id: 8228,
              name: 'KIRIMWA',
              villages: [
                { id: 50990, name: 'BUKONGORO' },
                { id: 50991, name: 'BULAYI A' },
                { id: 59683, name: 'BULAYI B' },
                { id: 50993, name: 'KINAMAGIRA A' },
                { id: 63735, name: 'KINAMAGIRA B' },
                { id: 50994, name: 'KINATEBE A' },
                { id: 50992, name: 'KINATEBE B' },
              ],
            },
            {
              id: 8229,
              name: 'MULALI',
              villages: [
                { id: 59611, name: 'BUKOSE/BUNANGWE A' },
                { id: 50995, name: 'BUKOSE/BUNANGWE B' },
                { id: 59673, name: 'BULANGAIRE' },
                { id: 59733, name: 'BULUBA/BUWERYA A' },
                { id: 59734, name: 'BULUBA/BUWERYA B' },
                { id: 60400, name: 'BUSUBO/MPANGA' },
                { id: 50996, name: 'BUTENDE/BULOBE' },
              ],
            },
            {
              id: 8230,
              name: 'NSOOMBA',
              villages: [
                { id: 50997, name: 'BUGAGA A' },
                { id: 59283, name: 'BUGAGA B' },
                { id: 50998, name: 'BUGEMBE' },
                { id: 50999, name: 'BULUNGANA' },
                { id: 51000, name: 'BUSALWA' },
                { id: 60414, name: 'BUSUUBO-MPANGA' },
                { id: 51001, name: 'ITANINHI' },
                { id: 51002, name: 'KAKIRA' },
              ],
            },
          ],
        },
        {
          id: 1737,
          name: 'NGANDHO',
          parishes: [
            {
              id: 8244,
              name: 'BUYAMBA',
              villages: [
                { id: 59642, name: 'BUKWANGA/BUBIIPI' },
                { id: 51078, name: 'BUKWANGA/BUSANO' },
                { id: 51077, name: 'BUSUSWA BUBEKO' },
                { id: 60712, name: 'BUYAMBA A' },
                { id: 51079, name: 'BUYAMBA B' },
              ],
            },
            {
              id: 8241,
              name: 'GWASE',
              villages: [
                { id: 51064, name: 'BUBEEKO A' },
                { id: 59207, name: 'BUBEEKO B' },
                { id: 51058, name: 'BUGABO' },
                { id: 51062, name: 'BUGALAIRE' },
                { id: 51059, name: 'BUGULUSI/BUTALENGA' },
                { id: 59725, name: 'BULONDA' },
                { id: 51060, name: 'BUSERANDA' },
                { id: 60423, name: 'BUTADHI' },
                { id: 51063, name: 'BWOSI' },
                { id: 51061, name: 'KYABAZAALA' },
              ],
            },
            {
              id: 8245,
              name: 'KIRIMBI',
              villages: [
                { id: 51081, name: 'BUBANDA' },
                { id: 51080, name: 'BUDHUBULI/BUKWALU' },
                { id: 59265, name: 'BUDHUMBULA-BUBANDA' },
                { id: 59641, name: 'BUKWALU' },
                { id: 51083, name: 'BULUNGU/BUGAGA' },
                { id: 51082, name: 'KISANGIRA' },
              ],
            },
            {
              id: 8246,
              name: 'NABISIKI',
              villages: [
                { id: 51085, name: 'BUGAGA/BUSANO A' },
                { id: 59285, name: 'BUGAGA/BUSANO B' },
                { id: 51087, name: 'BUGANZA' },
                { id: 59305, name: 'BUGANZA/BUTOOLI' },
                { id: 51084, name: 'BUGAYA-BULONDO' },
                { id: 59337, name: 'BUGOBI/BUSIKWE' },
                { id: 59675, name: 'BULANGIRA' },
                { id: 51086, name: 'BUSOBYA-BULONDO' },
              ],
            },
            {
              id: 8242,
              name: 'NGANDHO',
              villages: [
                { id: 51065, name: 'BUKOSE/BUGAYA A' },
                { id: 59610, name: 'BUKOSE/BUGAYA B' },
                { id: 51066, name: 'BUSEMBYA' },
                { id: 60412, name: 'BUSUUBO' },
                { id: 51067, name: 'KASINGA/GWALA A' },
                { id: 62969, name: 'KASINGA/GWALA B' },
              ],
            },
            {
              id: 8243,
              name: 'WANDAGO',
              villages: [
                { id: 51070, name: 'BUGE-BULONDO' },
                { id: 59353, name: 'BUGONDA-BUYINGO' },
                { id: 51068, name: 'BUGONDA/BUBBUPI' },
                { id: 51075, name: 'BUKOSE/BUGONZI' },
                { id: 51069, name: 'BUKOZA/BUWANDE' },
                { id: 51076, name: 'BULANDA-BUNABALA' },
                { id: 51071, name: 'BULANGIRA/BUWAYA' },
                { id: 51072, name: 'BUNHA/BUYEGA' },
                { id: 60390, name: 'BUSOOKO-BUGONZI' },
                { id: 51073, name: 'BUSOOKO/BUBAALE' },
                { id: 60391, name: 'BUSOOKO/BUGANDA' },
                { id: 51074, name: 'BUSUSWA/BUKWANGA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 265,
      name: 'BUDIOPE WEST COUNTY',
      sub_counties: [
        {
          id: 1724,
          name: 'BUKUNGU TOWN COUNCIL',
          parishes: [
            {
              id: 8180,
              name: 'BUKUNGU WARD',
              villages: [
                { id: 50759, name: 'BUZAAMA' },
                { id: 50760, name: 'KAPIOKOLO A' },
                { id: 62660, name: 'KAPIOKOLO B' },
                { id: 63936, name: 'KISOGA' },
                { id: 50763, name: 'KIWANTAMA' },
                { id: 64127, name: 'KIWANTAMA T/C' },
                { id: 50761, name: 'KYOGA A' },
                { id: 50762, name: 'KYOGA B' },
                { id: 65586, name: 'LUFULAKIKWATA' },
                { id: 50764, name: 'LUFUULA' },
              ],
            },
            {
              id: 8178,
              name: 'KIBAALE WARD',
              villages: [
                { id: 50753, name: 'BUDOOBA A' },
                { id: 59271, name: 'BUDOOBA B' },
                { id: 50754, name: 'KANGANYANZA' },
                { id: 62522, name: 'KANGANYANZA LANDING SITE' },
                { id: 50755, name: 'KINAMUWANGA A' },
                { id: 63736, name: 'KINAMUWANGA B' },
                { id: 50756, name: 'KINAWANKEMBO A' },
                { id: 63739, name: 'KINAWANKEMBO B' },
              ],
            },
            {
              id: 8179,
              name: 'KYANKOOLE WARD',
              villages: [
                { id: 50757, name: 'BUYANJA A' },
                { id: 60718, name: 'BUYANJA B' },
                { id: 50758, name: 'KYANKOOLE' },
                { id: 64683, name: 'KYANKOOLE LANDING SITE' },
              ],
            },
          ],
        },
        {
          id: 1731,
          name: 'BUYANJA',
          parishes: [
            {
              id: 8209,
              name: 'BUTAYUNJWA',
              villages: [
                { id: 50913, name: 'BUTAYUNJWA A' },
                { id: 50914, name: 'BUTAYUNJWA B' },
                { id: 50915, name: 'KABALONGO' },
                { id: 61860, name: 'KABALONGO T.C' },
                { id: 50917, name: 'KALUNGI' },
                { id: 63580, name: 'KIIGA' },
                { id: 64133, name: 'KIWONGOIRE A' },
                { id: 50916, name: 'KIWONGOIRE B' },
              ],
            },
            {
              id: 8210,
              name: 'BUYANJA',
              villages: [
                { id: 50918, name: 'KASAATO' },
                { id: 50919, name: 'NAWANSASO A' },
                { id: 67644, name: 'NAWANSASO B' },
              ],
            },
            {
              id: 8211,
              name: 'NTAALA',
              villages: [
                { id: 50920, name: 'KASAALA' },
                { id: 50921, name: 'NAKAWA A' },
                { id: 50922, name: 'NAKAWA B' },
                { id: 67029, name: 'NAKAWA C' },
                { id: 67030, name: 'NAKAWA TC' },
                { id: 50923, name: 'NTAALA' },
                { id: 67848, name: 'NTAALA TC' },
              ],
            },
          ],
        },
        {
          id: 1725,
          name: 'BUYENDE',
          parishes: [
            {
              id: 8185,
              name: 'IKANDA',
              villages: [
                { id: 50784, name: 'IGOMERO A' },
                { id: 50789, name: 'IGOMERO B' },
                { id: 50785, name: 'ISISI LANDING' },
                { id: 50786, name: 'KALAMBO A' },
                { id: 62297, name: 'KALAMBO B' },
                { id: 63487, name: 'KIGANJA A' },
                { id: 63488, name: 'KIGANJA B' },
                { id: 50787, name: 'KIGANZA A' },
                { id: 50788, name: 'MAGOGO A' },
                { id: 65891, name: 'MAGOGO B' },
                { id: 66565, name: 'MUKUUMA T/C' },
              ],
            },
            {
              id: 8183,
              name: 'KAKOOGE',
              villages: [
                { id: 62247, name: 'KAKOOGE CENTRAL A' },
                { id: 50774, name: 'KAKOOGE CENTRAL B' },
                { id: 50775, name: 'KAKOOGE LANDING' },
                { id: 62248, name: 'KAKOOGE TC' },
                { id: 50777, name: 'KIKAAYA A' },
                { id: 63625, name: 'KIKAAYA B' },
                { id: 50778, name: 'MAILO A' },
                { id: 65908, name: 'MAILO B' },
                { id: 50776, name: 'NKOONA' },
                { id: 50779, name: 'RWOKO' },
              ],
            },
            {
              id: 8184,
              name: 'KIRIBAIRYA',
              villages: [
                { id: 61681, name: 'ISISI LANDING' },
                { id: 63408, name: 'KIBYASI' },
                { id: 63810, name: 'KIRIBAIRYA A' },
                { id: 63811, name: 'KIRIBAIRYA CENTRAL A' },
                { id: 63812, name: 'KIRIBAIRYA CENTRAL B' },
                { id: 50780, name: 'KIRIBAIRYA LANDING' },
                { id: 50781, name: 'KIRIBAIRYA T/CENTRE' },
                { id: 50783, name: 'MUKUUMA T/C' },
                { id: 50782, name: 'WAIRUGALA' },
              ],
            },
            {
              id: 8181,
              name: 'MANGO',
              villages: [
                { id: 50765, name: 'BUGAGA A' },
                { id: 59284, name: 'BUGAGA B' },
                { id: 59731, name: 'BULUBA' },
                { id: 50769, name: 'BUSOBYA' },
                { id: 50766, name: 'KALIRO A' },
                { id: 62334, name: 'KALIRO B' },
                { id: 63819, name: 'KIRIMBI A' },
                { id: 63820, name: 'KIRIMBI B' },
                { id: 50767, name: 'NAKABEMBE A' },
                { id: 66987, name: 'NAKABEMBE B' },
                { id: 50768, name: 'NSONKO A' },
                { id: 67840, name: 'NSONKO B' },
              ],
            },
            {
              id: 8182,
              name: 'NAMUSITA',
              villages: [
                { id: 50770, name: 'IKOONA' },
                { id: 50771, name: 'KADEBEDE A' },
                { id: 62022, name: 'KADEBEDE B' },
                { id: 50772, name: 'KASULETA A' },
                { id: 63011, name: 'KASULETA B' },
                { id: 50773, name: 'NAMUSITA CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 1729,
          name: 'BUYENDE TOWN COUNCIL',
          parishes: [
            {
              id: 8203,
              name: 'BUMYUKA WARD',
              villages: [
                { id: 50873, name: 'BUDUNGU' },
                { id: 50874, name: 'BUGASANI' },
                { id: 50880, name: 'BULOKE' },
                { id: 50875, name: 'BUMYUKA EAST' },
                { id: 50876, name: 'BUMYUKA WEST' },
                { id: 50877, name: 'BUNANGWE' },
                { id: 50878, name: 'BUTOOLI' },
                { id: 50879, name: 'BUWAIDHA' },
              ],
            },
            {
              id: 8200,
              name: 'BUYENDE WARD',
              villages: [
                { id: 50857, name: 'BUTAASA' },
                { id: 50858, name: 'BUYENDE TRADING CENTRE' },
                { id: 50859, name: 'DEMA' },
                { id: 50860, name: 'KISEEGE' },
                { id: 50861, name: 'NABUKALU' },
              ],
            },
            {
              id: 8201,
              name: 'KINAMBOGO WARD',
              villages: [
                { id: 50862, name: 'BUBALYA' },
                { id: 50863, name: 'BUNANTAMU' },
                { id: 50864, name: 'BUSAMBIRA' },
                { id: 50867, name: 'BUTAALU' },
                { id: 50865, name: 'BUWANDE' },
                { id: 50866, name: 'KANYANYAGO' },
              ],
            },
            {
              id: 8204,
              name: 'MAKANGA WARD',
              villages: [
                { id: 50882, name: 'BUBENGO' },
                { id: 50883, name: 'BUGOGO' },
                { id: 50884, name: 'BUKALIMO' },
                { id: 50881, name: 'BULUUBE' },
                { id: 50885, name: 'BUSEETE' },
                { id: 50886, name: 'BUSUUYI' },
                { id: 50887, name: 'BUWOIRA' },
                { id: 50888, name: 'MAKANGA T/C' },
              ],
            },
            {
              id: 8202,
              name: 'NAKABIRA WARD',
              villages: [
                { id: 59274, name: 'BUDUNGU' },
                { id: 50868, name: 'BUKONOKA' },
                { id: 50869, name: 'BUTANAABA/BUKEWA' },
                { id: 50870, name: 'KISEEGE' },
                { id: 50871, name: 'NAMAVUNDU/ITUBA' },
                { id: 50872, name: 'NAMBALE' },
              ],
            },
          ],
        },
        {
          id: 1727,
          name: 'KIDERA',
          parishes: [
            {
              id: 8194,
              name: 'BULEMBO',
              villages: [
                { id: 50820, name: 'BUKANZA/BUNYONA' },
                { id: 50821, name: 'BULAMULI' },
                { id: 50825, name: 'BULEMBO/MEIRO' },
                { id: 50822, name: 'BULINDA/MWIGA' },
                { id: 50823, name: 'BULINDI' },
                { id: 62269, name: 'KAKYANGA' },
                { id: 62608, name: 'KANYOGOGA' },
                { id: 63583, name: 'KIIKARA' },
                { id: 50824, name: 'MASEMBE' },
                { id: 66211, name: 'MEERU' },
                { id: 50826, name: 'NAKITUBA' },
                { id: 50827, name: 'NAWANSEGA' },
              ],
            },
            {
              id: 8192,
              name: 'KASIIRA',
              villages: [
                { id: 62410, name: 'KAMASIIRA' },
                { id: 62965, name: 'KASIIRA TC' },
                { id: 50813, name: 'KIRIMUNSEEGE' },
                { id: 50814, name: 'NAIROLWA' },
              ],
            },
            {
              id: 8191,
              name: 'KISEKYE',
              villages: [
                { id: 50811, name: 'KISAIKYE' },
                { id: 67064, name: 'NAKIMUNKU' },
                { id: 50812, name: 'NFUMAGANI' },
                { id: 67714, name: 'NFUMAGANI NILE SHORES' },
              ],
            },
            {
              id: 8193,
              name: 'MISERU',
              villages: [
                { id: 50815, name: 'MATIKI A' },
                { id: 50816, name: 'MATIKI B' },
                { id: 50817, name: 'NABIGWO' },
                { id: 50818, name: 'NAMBOLI I' },
                { id: 50819, name: 'NAMBOLI II' },
              ],
            },
            {
              id: 8195,
              name: 'NDUDU',
              villages: [
                { id: 59436, name: 'BUKAMBA' },
                { id: 60474, name: 'BUTOLI' },
                { id: 66193, name: 'MBIIKO TC' },
                { id: 50828, name: 'MIRENGEIZO A' },
                { id: 50829, name: 'MIRENGEIZO B' },
                { id: 50830, name: 'NDUDU' },
              ],
            },
          ],
        },
        {
          id: 1726,
          name: 'KIDERA TOWN COUNCIL',
          parishes: [
            {
              id: 8186,
              name: 'ITAMIA WARD',
              villages: [
                { id: 50790, name: 'BUGEZYA' },
                { id: 50791, name: 'BUZIMBA' },
                { id: 62279, name: 'KALAGALA' },
                { id: 50792, name: 'MERU' },
                { id: 50793, name: 'MERU KYOGA' },
                { id: 50794, name: 'MERU TRIANGLE' },
                { id: 50795, name: 'WALUMBE' },
              ],
            },
            {
              id: 8187,
              name: 'KABUGUDHO WARD',
              villages: [
                { id: 50796, name: 'GREEN ZONE' },
                { id: 61951, name: 'KABUGUDHO A' },
                { id: 50797, name: 'KABUGUDHO B' },
                { id: 61952, name: 'KABUGUDHO TRADING CENTRE' },
                { id: 66916, name: 'NABWEYO A' },
                { id: 66917, name: 'NABWEYO B' },
                { id: 50798, name: 'NAKABEMBE A' },
                { id: 66986, name: 'NAKABEMBE B' },
              ],
            },
            {
              id: 8190,
              name: 'KIDERA WARD',
              villages: [
                { id: 59996, name: 'BUNAKWITA' },
                { id: 50809, name: 'KAKIIKA' },
                { id: 50807, name: 'KIWAMBYA' },
                { id: 50808, name: 'KYAUKA' },
                { id: 50810, name: 'NGULAMUBIRI' },
              ],
            },
            {
              id: 8188,
              name: 'KITAIDHUMBA WARD',
              villages: [
                { id: 50802, name: 'KANANTEGE' },
                { id: 50799, name: 'KATOGWE A' },
                { id: 50801, name: 'KATOGWE B' },
                { id: 50800, name: 'KITAIDHUMBA A' },
                { id: 50803, name: 'KITAIDHUMBA B' },
                { id: 66230, name: 'MERU' },
                { id: 50804, name: 'NAKIBENGO' },
              ],
            },
            {
              id: 8189,
              name: 'KITETE WARD',
              villages: [
                { id: 62393, name: 'KAMAGO' },
                { id: 50805, name: 'KITAYUNJWA' },
                { id: 50806, name: 'KITETE A' },
                { id: 64042, name: 'KITETE B' },
                { id: 64700, name: 'KYANYONYI' },
              ],
            },
          ],
        },
        {
          id: 1730,
          name: 'NDOLWA',
          parishes: [
            {
              id: 8206,
              name: 'BUTONGOLE',
              villages: [
                { id: 50897, name: 'BUDUULI' },
                { id: 50899, name: 'BUGANZA A' },
                { id: 59304, name: 'BUGANZA B' },
                { id: 59437, name: 'BUKAMBI' },
                { id: 60398, name: 'BUSUBO I' },
                { id: 60475, name: 'BUTONGOLE  II' },
                { id: 50898, name: 'BUTONGOLE I' },
              ],
            },
            { id: 10024, name: 'NABIGAGA', villages: [{ id: 59732, name: 'BULUBA I' }] },
            {
              id: 8205,
              name: 'NAWANTALE/NABIGAGA',
              villages: [
                { id: 50891, name: 'BUGAVU' },
                { id: 50889, name: 'BULANGIRA' },
                { id: 50890, name: 'BULUBA II' },
                { id: 50892, name: 'BUTABAZI' },
                { id: 50893, name: 'BUTEMAWA' },
                { id: 50894, name: 'BUYOKERO' },
                { id: 50895, name: 'NABIGAGA' },
                { id: 50896, name: 'NDOLWA TRADING CENTRE' },
              ],
            },
            {
              id: 8207,
              name: 'NDOLWA',
              villages: [
                { id: 50900, name: 'BULONDO' },
                { id: 50901, name: 'BULUUBE' },
                { id: 60341, name: 'BUSIKWE I' },
                { id: 60342, name: 'BUSIKWE II' },
                { id: 50903, name: 'KIGAYA' },
                { id: 50902, name: 'KISUUBO A' },
                { id: 63969, name: 'KISUUBO B' },
                { id: 50904, name: 'MASETE A' },
                { id: 66082, name: 'MASETE B' },
                { id: 50905, name: 'NDULYA/KISUUBO' },
              ],
            },
            {
              id: 8208,
              name: 'WESUNIRE',
              villages: [
                { id: 50906, name: 'BAGANZI' },
                { id: 59306, name: 'BUGANZI-NNYONDO' },
                { id: 50907, name: 'BUKAMBI' },
                { id: 50909, name: 'BUSUBO I' },
                { id: 50908, name: 'BUSUBO II' },
                { id: 60399, name: 'BUSUBO III' },
                { id: 61555, name: 'IDALA-BUTATU' },
                { id: 50910, name: 'IDHAALA A' },
                { id: 61556, name: 'IDHAALA B' },
                { id: 50911, name: 'KISUUYI A' },
                { id: 63970, name: 'KISUUYI B' },
                { id: 50912, name: 'KIYUNGA A' },
                { id: 64150, name: 'KIYUNGA B' },
              ],
            },
          ],
        },
        {
          id: 1728,
          name: 'NKONDO',
          parishes: [
            {
              id: 8196,
              name: 'IMMERI',
              villages: [
                { id: 50834, name: 'IMMERI' },
                { id: 50831, name: 'KYABAZALA' },
                { id: 50832, name: 'NANVUNANO' },
                { id: 50833, name: 'NSEKANSEKA' },
              ],
            },
            {
              id: 8199,
              name: 'IRINGA',
              villages: [
                { id: 50855, name: 'IZUNGWE' },
                { id: 50849, name: 'KALOGOI' },
                { id: 50850, name: 'KASUKU A' },
                { id: 50851, name: 'KASUKU B' },
                { id: 50856, name: 'KIGEIZERE' },
                { id: 50852, name: 'MANI A' },
                { id: 50853, name: 'MANI B' },
                { id: 50854, name: 'NAKASEDHERE' },
              ],
            },
            {
              id: 8197,
              name: 'KIGINGI',
              villages: [
                { id: 50835, name: 'BUSIGE' },
                { id: 50836, name: 'KABUGU' },
                { id: 50837, name: 'KALANGA' },
                { id: 50838, name: 'KASONGOIRE' },
                { id: 50839, name: 'KIWOLOGOMA' },
                { id: 50840, name: 'LWEVOLA/NAWAMPITI' },
                { id: 50841, name: 'NAMULANDA' },
                { id: 50842, name: 'NAWAIKIKI' },
              ],
            },
            {
              id: 8198,
              name: 'NDULYA',
              villages: [
                { id: 50843, name: 'BUTIMBITO' },
                { id: 50844, name: 'KIRANGIRA' },
                { id: 50845, name: 'KIRIMIRA' },
                { id: 50847, name: 'NDHWEDHWE' },
                { id: 50846, name: 'NDULYA' },
                { id: 50848, name: 'TIIMI' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
