import { District } from '../index';

export default {
  id: 102,
  name: 'DOKOLO',
  counties: [
    {
      id: 248,
      name: 'DOKOLO NORTH COUNTY',
      sub_counties: [
        {
          id: 1598,
          name: 'ADOK',
          parishes: [
            {
              id: 7483,
              name: 'ADOK',
              villages: [
                { id: 46458, name: 'ACUNA' },
                { id: 46460, name: 'AGOLOWELO' },
                { id: 46456, name: 'ALYECOWE' },
                { id: 46461, name: 'AMING' },
                { id: 46457, name: 'BARLWALA' },
                { id: 46462, name: 'OBENE' },
                { id: 46463, name: 'OCAMOAYOM' },
                { id: 46464, name: 'ODEO' },
                { id: 46465, name: 'OKILE' },
                { id: 46466, name: 'OPEKE' },
                { id: 46459, name: 'TEDAM' },
              ],
            },
            {
              id: 7485,
              name: 'AMONOLOCO',
              villages: [
                { id: 46474, name: 'ACANDEK' },
                { id: 46476, name: 'ADABADABA' },
                { id: 46477, name: 'AMONOLOCOO' },
                { id: 46475, name: 'OLAROBWOL' },
                { id: 46478, name: 'OLELPEK' },
              ],
            },
            {
              id: 7486,
              name: 'AMUNAMUN',
              villages: [
                { id: 46479, name: 'ABOLI' },
                { id: 46480, name: 'ADWALA' },
                { id: 46481, name: 'AKUBALA' },
                { id: 46482, name: 'ALABI' },
                { id: 46483, name: 'AMULAKERE' },
                { id: 46484, name: 'AMUNAMUN' },
                { id: 46485, name: 'ANYAPONENIGOLO' },
                { id: 46486, name: 'AWIDAM' },
                { id: 46487, name: 'OLIDURU' },
                { id: 46488, name: 'TETOL' },
              ],
            },
            {
              id: 7487,
              name: 'APYE',
              villages: [
                { id: 46489, name: "ABENYONYA 'A'" },
                { id: 46490, name: "ABENYONYA 'B'" },
                { id: 46491, name: "APETI 'A'" },
                { id: 46492, name: "APETI 'B'" },
                { id: 46493, name: 'APYE' },
                { id: 46494, name: 'AWOK' },
                { id: 46495, name: 'BUNG' },
                { id: 46496, name: 'TEAMON' },
              ],
            },
            {
              id: 7484,
              name: 'BARDYANG',
              villages: [
                { id: 46469, name: 'ADWILA' },
                { id: 46470, name: 'AGENGI' },
                { id: 46467, name: 'AKAIDEBE' },
                { id: 46468, name: 'ALWALA' },
                { id: 46472, name: 'AMIAKONY' },
                { id: 46473, name: 'APUTI' },
                { id: 46471, name: 'TE ACII' },
              ],
            },
          ],
        },
        {
          id: 1601,
          name: 'AGWATA TOWN COUNCIL',
          parishes: [
            {
              id: 7502,
              name: 'ACOTO WARD',
              villages: [
                { id: 46589, name: 'ADEDI' },
                { id: 46590, name: "ARAP 'B'" },
                { id: 46588, name: 'AWIDI' },
                { id: 58890, name: 'BAMBALA' },
                { id: 46591, name: 'OWIRI' },
              ],
            },
            {
              id: 7497,
              name: 'AMUDA CENTRAL WARD',
              villages: [
                { id: 46569, name: 'AGEBO A' },
                { id: 46570, name: 'AGEBO B' },
                { id: 46573, name: 'AGEBO C' },
                { id: 46571, name: 'AGWATA-ATIDI' },
                { id: 46572, name: 'BUNG' },
                { id: 46574, name: 'OMUKOCEKE' },
              ],
            },
            {
              id: 7499,
              name: 'AMUDA EASTERN WARD',
              villages: [
                { id: 46578, name: 'ALII' },
                { id: 46580, name: 'ODEYE' },
                { id: 46579, name: 'ODEYE CENTRAL' },
                { id: 46581, name: 'OJUL' },
              ],
            },
            {
              id: 7498,
              name: 'KACUNG EAST WARD',
              villages: [
                { id: 46575, name: "ARAP 'A'" },
                { id: 46576, name: "AWANY 'A'" },
                { id: 46577, name: "AWANY 'B'" },
              ],
            },
            {
              id: 7500,
              name: 'KACUNG WEST WARD',
              villages: [
                { id: 46582, name: 'ACUNGAPENYI' },
                { id: 57543, name: 'AGERINONO' },
                { id: 46583, name: "AKWOTE 'A'" },
                { id: 46584, name: "AKWOTE 'B'" },
              ],
            },
            {
              id: 7501,
              name: 'MAIROANGWEN WARD',
              villages: [
                { id: 46585, name: 'ABALI' },
                { id: 46586, name: "APALA 'A'" },
                { id: 46587, name: "APALA 'B'" },
              ],
            },
            {
              id: 7503,
              name: 'TETUGO A WARD',
              villages: [
                { id: 46592, name: 'ACAN OWILO' },
                { id: 46593, name: 'ANOKI' },
                { id: 46594, name: 'OKWOR' },
              ],
            },
            {
              id: 10314,
              name: 'TETUGO B WARD',
              villages: [
                { id: 65749, name: 'LWALA' },
                { id: 70726, name: 'TETUGO C' },
                { id: 70727, name: 'TETUGO CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 1595,
          name: 'AGWATTA',
          parishes: [
            {
              id: 7468,
              name: 'ADWOKI',
              villages: [
                { id: 46354, name: 'ABONGORWOT' },
                { id: 46355, name: 'AGULA' },
                { id: 46356, name: 'AJET' },
                { id: 46357, name: 'AJOK-DONG' },
                { id: 46358, name: 'AYITO' },
                { id: 46359, name: 'ODEKOGWENO' },
              ],
            },
            {
              id: 7469,
              name: 'AGWICIRI',
              villages: [
                { id: 46360, name: 'ABENYO' },
                { id: 46361, name: 'ACILKOM' },
                { id: 46363, name: "ADAKOGIK 'B'" },
                { id: 46364, name: 'ALITO' },
                { id: 46362, name: 'BARAYOM' },
              ],
            },
            {
              id: 7470,
              name: 'ALYECJUK',
              villages: [
                { id: 46366, name: "ADAKOGIK 'A'" },
                { id: 46367, name: 'AJUK' },
                { id: 46365, name: 'AKWOYO' },
                { id: 46368, name: 'AWEKIPARO' },
                { id: 46369, name: 'OKIIPOKERE' },
                { id: 46370, name: 'OLEKOCEKE' },
                { id: 46371, name: 'OTIMA' },
              ],
            },
          ],
        },
        {
          id: 1599,
          name: 'AMWOMA',
          parishes: [
            {
              id: 7490,
              name: 'ABURCERO',
              villages: [
                { id: 46516, name: 'ABURCERO' },
                { id: 46519, name: 'ACAN GWENO' },
                { id: 46518, name: 'ADWOGONONO' },
                { id: 46521, name: 'ALWAR' },
                { id: 58225, name: 'AMWOMA' },
                { id: 46522, name: 'APII-OWIO' },
                { id: 46517, name: 'BARONGER' },
                { id: 46523, name: 'OKERKOK' },
                { id: 46520, name: 'ORINGO DAKO' },
              ],
            },
            {
              id: 7491,
              name: 'ADAGWOO',
              villages: [
                { id: 46524, name: 'ABAT' },
                { id: 46527, name: 'ADAGWOO' },
                { id: 46528, name: 'ADAK' },
                { id: 46525, name: 'ALYER' },
                { id: 46526, name: 'AOLIKWAC' },
                { id: 46529, name: 'AYAGO' },
                { id: 46530, name: 'IDYENY' },
                { id: 46531, name: 'ORINGOPALA' },
              ],
            },
            {
              id: 7492,
              name: 'AKOLODONG',
              villages: [
                { id: 46533, name: 'ACEDE' },
                { id: 46534, name: 'ADICUNY' },
                { id: 46535, name: 'ALANYI A' },
                { id: 46532, name: 'ALANYI B' },
                { id: 46536, name: 'ARIBI' },
                { id: 46539, name: 'KOROTO' },
                { id: 46538, name: 'OGORA' },
                { id: 46537, name: 'OROMO' },
              ],
            },
            {
              id: 7489,
              name: 'AMWOMA',
              villages: [
                { id: 46506, name: 'ACUKERE' },
                { id: 46509, name: 'ALUTI' },
                { id: 46510, name: 'AMWOMA' },
                { id: 46505, name: 'AWEIWO' },
                { id: 46511, name: 'AWELOGWEI' },
                { id: 46512, name: 'OBUMA' },
                { id: 46508, name: 'OKWALONGWEN' },
                { id: 46513, name: 'OMUKOWIE' },
                { id: 46514, name: 'OTOLOMOGO A' },
                { id: 46507, name: 'OTOLOMOGO B' },
                { id: 46515, name: 'TEILWA' },
              ],
            },
            {
              id: 7488,
              name: 'IGULI',
              villages: [
                { id: 46498, name: 'ABUKI' },
                { id: 46500, name: 'ADAGAMONE' },
                { id: 46501, name: 'ADAGANI' },
                { id: 46497, name: 'AGORI' },
                { id: 46502, name: 'APOR' },
                { id: 46503, name: 'ARAKI' },
                { id: 46504, name: 'AWAT' },
                { id: 46499, name: 'IGULI' },
              ],
            },
          ],
        },
        {
          id: 1602,
          name: 'BATA TOWN COUNCIL',
          parishes: [
            {
              id: 7505,
              name: 'ADEROLONGO SOUTH WARD',
              villages: [
                { id: 46601, name: 'ABINO' },
                { id: 46602, name: 'ADYANGMONO' },
                { id: 46603, name: 'AJWAI' },
                { id: 46604, name: 'ANGUNYDERO' },
                { id: 46605, name: 'OBORO' },
                { id: 46606, name: 'OLONYIORO' },
                { id: 46607, name: 'ONGOCENG' },
              ],
            },
            {
              id: 7504,
              name: 'ANINGO CENTRAL WARD',
              villages: [
                { id: 46595, name: 'ABERIMATO' },
                { id: 46596, name: 'ACOOLWOR' },
                { id: 46597, name: 'ANINGO' },
                { id: 58390, name: 'APENYO' },
                { id: 68674, name: 'OKELOKUC' },
                { id: 46598, name: 'OKWONGO' },
                { id: 46599, name: 'ONEKOCANI' },
                { id: 46600, name: 'OPWOANYIRA' },
              ],
            },
            {
              id: 7506,
              name: 'EASTERN WARD',
              villages: [
                { id: 46609, name: 'ACORI' },
                { id: 46611, name: 'ACWINYI' },
                { id: 46613, name: 'AMOMTUM' },
                { id: 46614, name: 'ANAPAKORI' },
                { id: 46612, name: 'ANARA' },
                { id: 46608, name: 'APADO' },
                { id: 46610, name: 'OCEKICEN' },
              ],
            },
            {
              id: 7508,
              name: 'NORTHERN WARD',
              villages: [
                { id: 46621, name: 'ACANDYANG' },
                { id: 46622, name: 'ADAGKENE' },
                { id: 46623, name: 'ALYET' },
                { id: 46624, name: 'ARWOT' },
                { id: 58950, name: 'BARAYOM' },
                { id: 46625, name: 'OKET' },
                { id: 46626, name: 'TEYAO' },
              ],
            },
            {
              id: 7507,
              name: 'WESTERN WARD',
              villages: [
                { id: 46615, name: 'AKATAKWI' },
                { id: 46617, name: 'AKUKI' },
                { id: 46616, name: 'BARGWENG' },
                { id: 46618, name: 'BUNG' },
                { id: 46619, name: 'ENGET' },
                { id: 46620, name: 'OMENY' },
              ],
            },
          ],
        },
        {
          id: 1596,
          name: 'BATTA',
          parishes: [
            {
              id: 7471,
              name: 'ALAPATA',
              villages: [
                { id: 46372, name: 'ABONGODERO' },
                { id: 46373, name: 'ACAEOGIK' },
                { id: 46375, name: 'ALITO' },
                { id: 46374, name: 'ANYANGACOTO' },
                { id: 46377, name: 'IDAIOL' },
                { id: 46376, name: 'OBALOTIC' },
                { id: 46378, name: 'OKOKOTIO' },
                { id: 46379, name: 'OKWERKWOR' },
              ],
            },
            {
              id: 7473,
              name: 'APENYO',
              villages: [
                { id: 46387, name: 'BERIDWOGO' },
                { id: 46388, name: 'OLEM-KETRE' },
                { id: 46389, name: 'OLOR' },
              ],
            },
            {
              id: 7472,
              name: 'ATABU',
              villages: [
                { id: 46380, name: 'ABUNYI' },
                { id: 46382, name: 'AKWEN' },
                { id: 46384, name: 'ANWONG' },
                { id: 46383, name: 'ATABU' },
                { id: 46381, name: 'AWIGWENG' },
                { id: 46386, name: 'OKALOPYEN' },
                { id: 46385, name: 'OLAMO-DYEL' },
              ],
            },
            {
              id: 7474,
              name: 'BARDEGE',
              villages: [
                { id: 46390, name: 'ABENYO ONYA' },
                { id: 46392, name: 'ABOLI' },
                { id: 46391, name: 'ADIP' },
                { id: 46393, name: 'ALENGO' },
                { id: 46394, name: 'BARDEGE' },
              ],
            },
            {
              id: 7475,
              name: 'BARLELA',
              villages: [
                { id: 46395, name: 'AGWENG' },
                { id: 46396, name: 'BARLELA' },
              ],
            },
            {
              id: 7476,
              name: 'OCERO',
              villages: [
                { id: 46397, name: 'AKABI' },
                { id: 46400, name: 'ALAM' },
                { id: 46398, name: 'ALAPATA' },
                { id: 46399, name: 'ALELA' },
                { id: 46401, name: 'ANYOMORANGA' },
                { id: 46403, name: 'OCERO' },
                { id: 46404, name: 'TEILWA' },
                { id: 46402, name: 'WANGLOBO' },
              ],
            },
          ],
        },
        {
          id: 1597,
          name: 'DOKOLO',
          parishes: [
            {
              id: 7480,
              name: 'ABENYO',
              villages: [
                { id: 46433, name: 'ABENYO' },
                { id: 46434, name: 'ACANATIN' },
                { id: 46436, name: 'AGWAYO' },
                { id: 46435, name: 'AGWEN' },
                { id: 46437, name: 'AKWALI' },
                { id: 46438, name: 'ATALI' },
                { id: 46439, name: 'AYITA' },
                { id: 46440, name: 'ONYOBA' },
              ],
            },
            {
              id: 7481,
              name: 'ACANPII',
              villages: [
                { id: 46441, name: 'ABARLELA' },
                { id: 46443, name: 'ABYECE' },
                { id: 46445, name: 'ACANPII A' },
                { id: 46442, name: 'ACAPII B' },
                { id: 46444, name: 'ADAGNYEKO' },
                { id: 46446, name: 'ALYET' },
                { id: 46447, name: 'ATALI' },
                { id: 46448, name: 'IDUNY' },
                { id: 46449, name: 'OKWALOMOGO' },
              ],
            },
            {
              id: 7479,
              name: 'ADAGMON',
              villages: [
                { id: 46424, name: 'ABWONG' },
                { id: 46425, name: 'ACENLWORO A' },
                { id: 46426, name: 'ACOTO' },
                { id: 46429, name: 'AMATIDOKCON' },
                { id: 46430, name: 'ANYAC A' },
                { id: 46427, name: 'BARTUGO' },
                { id: 46428, name: 'OCEDE' },
                { id: 46431, name: 'OPOKOTEDO A' },
                { id: 46432, name: 'TECEL' },
              ],
            },
            {
              id: 7477,
              name: 'ALENGA',
              villages: [
                { id: 46406, name: 'ABUGE' },
                { id: 46408, name: 'ACANONYOMO' },
                { id: 46410, name: 'ACANYIBI' },
                { id: 46411, name: 'AJWIO' },
                { id: 46405, name: 'AKUT' },
                { id: 46412, name: 'ALENGA' },
                { id: 46413, name: 'ARINGOADING' },
                { id: 46409, name: 'AYOLO' },
                { id: 46407, name: 'KAMPALA' },
                { id: 46414, name: 'TEOBWOLO' },
              ],
            },
            {
              id: 7482,
              name: 'ANANGOGWEC',
              villages: [
                { id: 46450, name: 'AGIKTUKO' },
                { id: 46451, name: 'ALANGOTIC' },
                { id: 46452, name: 'ANANGOGWEC' },
                { id: 46453, name: 'ANGIC' },
                { id: 46454, name: 'APALA' },
                { id: 46455, name: 'KIMA' },
              ],
            },
            {
              id: 7478,
              name: 'AWIRI',
              villages: [
                { id: 46416, name: 'ADAGANI' },
                { id: 46418, name: 'AKWORATORA' },
                { id: 46419, name: 'ALYET' },
                { id: 46415, name: 'AWEI' },
                { id: 46421, name: 'IGUNG' },
                { id: 46422, name: 'ILONG' },
                { id: 46417, name: 'KAGERA' },
                { id: 46423, name: 'OLOMET' },
                { id: 46420, name: 'OYIMA' },
              ],
            },
          ],
        },
        {
          id: 1600,
          name: 'OKWALONGWEN',
          parishes: [
            {
              id: 7493,
              name: 'ABALANG',
              villages: [
                { id: 46541, name: 'ANGOROMO' },
                { id: 46540, name: 'OBANGO ASINGE' },
                { id: 46542, name: 'OCILA' },
                { id: 46543, name: 'ONGORATOK' },
              ],
            },
            {
              id: 7494,
              name: 'ADAGNYEKO',
              villages: [
                { id: 46545, name: 'ABUJE' },
                { id: 46544, name: 'ACANGWENO' },
                { id: 46546, name: 'ADAGNYEKO' },
                { id: 46547, name: 'ADWONGOWOR' },
                { id: 46549, name: 'AMATIBURU' },
                { id: 46548, name: 'ANANGI' },
                { id: 46550, name: 'APIDU' },
                { id: 46551, name: 'ODEYE' },
                { id: 46552, name: 'OMANOABUNGA' },
              ],
            },
            {
              id: 9172,
              name: 'AKWANGA',
              villages: [
                { id: 57406, name: 'ADAGDEDE' },
                { id: 57529, name: 'AGALI' },
                { id: 57670, name: 'AJONYABWOTE' },
                { id: 57870, name: 'AKUROKWE' },
                { id: 58731, name: 'AWEKIPARO' },
                { id: 58742, name: 'AWEOWIA' },
                { id: 59022, name: 'BEDIKUC' },
              ],
            },
            {
              id: 7495,
              name: 'ALUTI',
              villages: [
                { id: 46553, name: 'ADWOYE' },
                { id: 46556, name: 'ALANG ALANG' },
                { id: 46557, name: 'ALUTI' },
                { id: 46558, name: 'AWIEALEM' },
                { id: 46554, name: 'BARYAO' },
                { id: 46559, name: 'ENGET' },
                { id: 46555, name: 'NGA-AMI' },
                { id: 46560, name: 'ORYENY' },
              ],
            },
            {
              id: 7496,
              name: 'OKWALONGWEN',
              villages: [
                { id: 46561, name: 'ACONE' },
                { id: 46562, name: 'ADEKOKWOK' },
                { id: 46564, name: 'AMONOLOCOO' },
                { id: 46565, name: 'AWELO OMER' },
                { id: 46566, name: 'BARADANGA' },
                { id: 46563, name: 'IPARA DUKU' },
                { id: 46567, name: 'OKWALONGWEN' },
                { id: 46568, name: 'OPUKA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 249,
      name: 'DOKOLO SOUTH COUNTY',
      sub_counties: [
        {
          id: 1607,
          name: 'ADEKNINO',
          parishes: [
            {
              id: 7527,
              name: 'ADEKNINO',
              villages: [
                { id: 46747, name: 'ABAROLAM' },
                { id: 46749, name: 'ACANPII' },
                { id: 46751, name: 'ADEKNINO' },
                { id: 46752, name: 'ALIK' },
                { id: 46753, name: 'AWIDI A' },
                { id: 46748, name: 'BAROKUTO' },
                { id: 46754, name: 'KOMARA' },
                { id: 46755, name: 'ONGEI' },
                { id: 46750, name: 'TELELA' },
              ],
            },
            {
              id: 7529,
              name: 'ADWONG-OWOR',
              villages: [
                { id: 46765, name: 'ABONGOWAT' },
                { id: 46766, name: 'ACUNGAPENYI' },
                { id: 46767, name: 'ADEROLONGO' },
                { id: 46768, name: 'ADOGMONMIO' },
                { id: 46769, name: 'ADWEKBER' },
                { id: 46770, name: 'ALENGI' },
                { id: 46764, name: 'OBORO' },
                { id: 46771, name: 'OWOR' },
              ],
            },
            {
              id: 7530,
              name: 'AJIBA',
              villages: [
                { id: 46777, name: 'AJIBA' },
                { id: 46774, name: 'AKANY' },
                { id: 46778, name: 'ALWAR' },
                { id: 46772, name: 'ATUGO' },
                { id: 46779, name: 'ELWANGE' },
                { id: 46776, name: 'OBAKO' },
                { id: 46773, name: 'OBOLOKOME' },
                { id: 46780, name: 'OTURULEE' },
                { id: 46775, name: 'PEBALO' },
              ],
            },
            {
              id: 7531,
              name: 'ARIDI',
              villages: [
                { id: 46782, name: 'ACAMO-OGALI' },
                { id: 46783, name: 'ADALA' },
                { id: 46784, name: "ADYANGOTO 'A'" },
                { id: 46785, name: "ADYANGOTO 'B'" },
                { id: 46786, name: 'AKABI' },
                { id: 46787, name: 'ARIDI' },
                { id: 46781, name: 'AWINYO-COA' },
                { id: 46788, name: 'OKWOR' },
              ],
            },
            {
              id: 7528,
              name: 'AWELO',
              villages: [
                { id: 46756, name: 'ABALANG' },
                { id: 46757, name: 'ALAO' },
                { id: 46758, name: 'AMIT' },
                { id: 46759, name: 'AMUK' },
                { id: 46760, name: 'ANYWALI' },
                { id: 46761, name: 'APEWOTNEKI' },
                { id: 46762, name: 'AWIDI B' },
                { id: 46763, name: 'BATA EBWOL' },
              ],
            },
          ],
        },
        {
          id: 1606,
          name: 'DOKOLO TOWN COUNCIL',
          parishes: [
            {
              id: 7526,
              name: 'CENTRAL WARD',
              villages: [
                { id: 46740, name: 'ACENGRYENY' },
                { id: 46741, name: 'ACUNGAPENYI' },
                { id: 46739, name: 'AKAIDEBE' },
                { id: 46742, name: 'AKONGO-ODYEK' },
                { id: 46743, name: 'ALAM' },
                { id: 46744, name: 'ARWOTNYAP' },
                { id: 46745, name: 'AWINYIPANY' },
                { id: 46746, name: 'OTOLEMOMOLEO' },
              ],
            },
            {
              id: 7522,
              name: 'EASTERN WARD',
              villages: [
                { id: 46706, name: 'ABUR' },
                { id: 46707, name: 'ACANMAC' },
                { id: 46709, name: 'ADUKULOTONG' },
                { id: 46710, name: 'AMIRO' },
                { id: 46711, name: 'AMULI' },
                { id: 46708, name: 'ANYAC B' },
                { id: 46712, name: 'ANYOMOLOI' },
                { id: 46713, name: 'ATERI' },
                { id: 46714, name: 'DIMA' },
                { id: 46715, name: 'ONYONINO' },
              ],
            },
            {
              id: 7523,
              name: 'NOTHERN WARD',
              villages: [
                { id: 46716, name: 'ACENLWORO B' },
                { id: 46719, name: 'ARUDABIRO' },
                { id: 46720, name: 'BASERE A' },
                { id: 46717, name: 'BASERE B' },
                { id: 46721, name: 'GOROGORO A' },
                { id: 46722, name: 'GOROGORO B' },
                { id: 46718, name: 'OPOKOTEDO B' },
              ],
            },
            {
              id: 7525,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 46735, name: 'ABENYO' },
                { id: 46738, name: 'ALAO-OKWANYA' },
                { id: 46736, name: 'ALOKIRI' },
                { id: 46737, name: 'ALWAR' },
              ],
            },
            {
              id: 7524,
              name: 'WESTERN WARD',
              villages: [
                { id: 46723, name: 'ABONGOWOO' },
                { id: 46724, name: 'ACANDYANG' },
                { id: 46725, name: 'AGORA' },
                { id: 46726, name: 'AGWENO NYWAL' },
                { id: 46727, name: 'AKEOGWENO' },
                { id: 46728, name: 'ANOK' },
                { id: 46734, name: 'ATAMA' },
                { id: 46733, name: 'ATUR' },
                { id: 46729, name: 'AYITO' },
                { id: 46730, name: 'OCOKOWIE' },
                { id: 46731, name: 'OGONYOWORO' },
                { id: 46732, name: 'OLELPEK' },
              ],
            },
          ],
        },
        {
          id: 1604,
          name: 'KANGAI',
          parishes: [
            {
              id: 7513,
              name: 'ADWILA',
              villages: [
                { id: 46644, name: 'ABONGOIPALE' },
                { id: 46645, name: 'ACANCILING' },
                { id: 46649, name: 'ACUT KUMU' },
                { id: 46646, name: 'ACWER' },
                { id: 46647, name: 'ADWILA' },
                { id: 46648, name: 'ADWONG GER' },
                { id: 46650, name: 'AKOPANGO' },
                { id: 46651, name: 'GECERE' },
                { id: 46652, name: 'ITONG' },
              ],
            },
            {
              id: 7514,
              name: 'ANGWENYA',
              villages: [
                { id: 46653, name: 'AGUBI' },
                { id: 46654, name: 'ANGWENYA' },
                { id: 46655, name: "OCEKIKOT 'A'" },
                { id: 46656, name: "OCEKIKOT 'B'" },
                { id: 46657, name: 'OLUBA' },
                { id: 46658, name: 'ONYWAKO' },
              ],
            },
            {
              id: 7515,
              name: 'AYUNI',
              villages: [
                { id: 46659, name: 'ALIWOK' },
                { id: 46660, name: 'BATA' },
                { id: 46661, name: 'INGENY' },
              ],
            },
            {
              id: 7516,
              name: 'CHWAGERE',
              villages: [
                { id: 46662, name: 'ACO OBEDO' },
                { id: 46666, name: 'ANGETA' },
                { id: 46663, name: 'AWEIWOT' },
                { id: 46667, name: 'CWAGERE' },
                { id: 46664, name: 'INANG' },
                { id: 46668, name: 'OKWOR' },
                { id: 46665, name: 'OLIFARM' },
                { id: 46669, name: 'OTORO' },
                { id: 46670, name: 'OYIRO-OGOLE' },
              ],
            },
          ],
        },
        {
          id: 1603,
          name: 'KANGAI TOWN COUNCIL',
          parishes: [
            {
              id: 7512,
              name: 'AKUROLANGO WARD',
              villages: [
                { id: 46639, name: 'ABANGKWON' },
                { id: 46641, name: 'ALELA' },
                { id: 46642, name: 'AMATI' },
                { id: 46640, name: 'ANYWAL-ACUT' },
                { id: 46643, name: 'ILONG' },
              ],
            },
            {
              id: 7509,
              name: 'ANGAI WARD',
              villages: [
                { id: 46628, name: 'ADITA' },
                { id: 46627, name: 'AGUBI' },
                { id: 46631, name: 'AKURI' },
                { id: 58023, name: 'ALIT' },
                { id: 46630, name: 'ANGAI' },
                { id: 46629, name: 'OWANGAI' },
              ],
            },
            {
              id: 7510,
              name: 'ANGWENYA WARD',
              villages: [
                { id: 46632, name: 'ABONGORWOT' },
                { id: 46633, name: 'ADYELI' },
                { id: 46634, name: 'OTONGODYEL' },
              ],
            },
            {
              id: 7511,
              name: 'AYUNI WARD',
              villages: [
                { id: 46635, name: 'ABWA' },
                { id: 46636, name: 'ACOGODANO' },
                { id: 46637, name: 'AKONGOMIT' },
                { id: 46638, name: 'AYUNI' },
              ],
            },
          ],
        },
        {
          id: 1605,
          name: 'KWERA',
          parishes: [
            {
              id: 7519,
              name: 'AGOGA',
              villages: [
                { id: 46687, name: 'ADEK KWOK' },
                { id: 46688, name: 'AGEE' },
                { id: 46686, name: 'APOKGOR' },
                { id: 46689, name: 'APYEN' },
                { id: 46690, name: 'ARWOTCOL' },
                { id: 46691, name: 'AUKI' },
                { id: 46692, name: 'OJER' },
              ],
            },
            {
              id: 7517,
              name: 'ANWANGI',
              villages: [
                { id: 46671, name: 'ABINYI A' },
                { id: 46673, name: 'ABINYI B' },
                { id: 46672, name: 'ABULI' },
                { id: 46675, name: 'AKURILUBA A' },
                { id: 46674, name: 'AKURILUBA B' },
                { id: 46676, name: 'ANWANGI' },
                { id: 46677, name: 'OBAPODERO B' },
              ],
            },
            {
              id: 7518,
              name: 'APENYANG',
              villages: [
                { id: 46678, name: 'ABEI' },
                { id: 46679, name: 'ACAN ORYEMA' },
                { id: 46681, name: 'ADING A' },
                { id: 46680, name: 'ADING B' },
                { id: 46682, name: 'ADWILA' },
                { id: 46684, name: 'ALAKE' },
                { id: 46683, name: 'AOA' },
                { id: 46685, name: 'ATWAC' },
              ],
            },
            {
              id: 7520,
              name: 'OTORO',
              villages: [
                { id: 46693, name: 'ABYENEK' },
                { id: 46694, name: 'ADAGI' },
                { id: 46695, name: 'AKULI' },
                { id: 46697, name: 'AWEIWOT' },
                { id: 46696, name: 'OBURAGWE' },
                { id: 46698, name: 'OTORO' },
              ],
            },
            {
              id: 7521,
              name: 'OYENG-OPERE',
              villages: [
                { id: 46700, name: 'ADARI  A' },
                { id: 46701, name: 'ADARI  B' },
                { id: 46702, name: 'ADUUODYEK' },
                { id: 46699, name: 'OBAPODERO A' },
                { id: 46703, name: 'ODUDUI' },
                { id: 46704, name: 'OYENG OPERE  A' },
                { id: 46705, name: 'OYENG OPERE  B' },
              ],
            },
          ],
        },
        {
          id: 1608,
          name: 'OKWONGODUL',
          parishes: [
            {
              id: 7534,
              name: 'AGENI',
              villages: [
                { id: 46803, name: 'AGENI  A' },
                { id: 46804, name: 'AGENI  B' },
                { id: 46805, name: 'ALUT' },
                { id: 46806, name: 'AMARI' },
                { id: 46808, name: 'APUTA APUTA A' },
                { id: 46807, name: 'APUTA APUTA B' },
              ],
            },
            {
              id: 7532,
              name: 'ANERALIBI',
              villages: [
                { id: 46789, name: 'ACAN DYANG A' },
                { id: 46790, name: 'ACAN DYANG B' },
                { id: 46792, name: "AJAA 'A'" },
                { id: 46793, name: 'ANERALIBI' },
                { id: 46794, name: 'ARIKENO' },
                { id: 46795, name: 'ATWAKO A' },
                { id: 46791, name: 'ATWAKO B' },
              ],
            },
            {
              id: 7535,
              name: 'ANYACOTO',
              villages: [
                { id: 46811, name: 'AMIALAKI A' },
                { id: 46809, name: 'AMIALAKI B' },
                { id: 46813, name: 'ANYACOTO A' },
                { id: 46810, name: 'ANYACOTO B' },
                { id: 46814, name: 'OBELOWER' },
                { id: 46815, name: 'OTURORAO A' },
                { id: 46812, name: 'OTURORAO B' },
              ],
            },
            {
              id: 7533,
              name: 'APENYOWEO',
              villages: [
                { id: 46796, name: 'AGURI' },
                { id: 46797, name: 'AJWATI' },
                { id: 46799, name: 'APENYOWEO' },
                { id: 46800, name: 'ATAMA A' },
                { id: 46798, name: 'ATAMA B' },
                { id: 46801, name: 'AYETAYET  A' },
                { id: 46802, name: 'AYETAYET B' },
              ],
            },
            {
              id: 7536,
              name: 'OKWONGODUL',
              villages: [
                { id: 46818, name: 'ADWONGDOK INYOM A' },
                { id: 46816, name: 'ADWONGDOK INYOM B' },
                { id: 46819, name: "AJAA 'B'" },
                { id: 46820, name: 'AMITICENG' },
                { id: 46821, name: 'BARRAYOM' },
                { id: 46822, name: 'OKWONGODUL A' },
                { id: 46817, name: 'OKWONGODUL B' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
