import { District } from '../types';

export default {
  id: 89,
  name: 'IBANDA',
  counties: [
    {
      id: 218,
      name: 'IBANDA COUNTY NORTH',
      sub_counties: [
        {
          id: 1378,
          name: 'ISHONGORORO',
          parishes: [
            {
              id: 6487,
              name: 'KASHOZI',
              villages: [
                { id: 40592, name: 'KAKIRO' },
                { id: 40593, name: 'KANIAMPIHA' },
                { id: 40594, name: 'KASHOZI' },
                { id: 40595, name: 'KATEHE' },
                { id: 40596, name: 'KATENGYETO' },
                { id: 40597, name: 'KATOJO I' },
                { id: 40601, name: 'KATOJO II' },
                { id: 40598, name: 'KATWE I' },
                { id: 40602, name: 'KATWE II' },
                { id: 40599, name: 'KYANYAMAREMBO' },
                { id: 40600, name: 'RUSHAMBYA' },
              ],
            },
            {
              id: 6488,
              name: 'MUSHUNGA',
              villages: [
                { id: 40608, name: 'KITOORO I' },
                { id: 40606, name: 'KITOORO II' },
                { id: 40609, name: 'MUSHUNGA I' },
                { id: 40603, name: 'MUSHUNGA II' },
                { id: 40607, name: 'MUSHUNGA III' },
                { id: 40610, name: 'RUGANDO I' },
                { id: 40604, name: 'RUGANDO II' },
                { id: 40611, name: 'RWEBIRAGO' },
                { id: 40612, name: 'RWETWEKA I' },
                { id: 40605, name: 'RWETWEKA II' },
              ],
            },
            {
              id: 6489,
              name: 'MUZIZA',
              villages: [
                { id: 40613, name: 'AKABARE' },
                { id: 40614, name: 'KAKUUTO I' },
                { id: 40615, name: 'KAKUUTO II' },
                { id: 40616, name: 'KAKUUTO III' },
                { id: 40617, name: 'KARAMBI' },
                { id: 40618, name: 'KASHAGAZI' },
                { id: 40621, name: 'KYEMBOGO' },
                { id: 40619, name: 'KYEMBOGO II' },
                { id: 40622, name: 'MUGONDO' },
                { id: 40623, name: 'MWANA' },
                { id: 40620, name: 'MWANA II' },
              ],
            },
          ],
        },
        {
          id: 1380,
          name: 'ISHONGORORO TOWN COUNCIL',
          parishes: [
            {
              id: 6496,
              name: 'KAKINGA WARD',
              villages: [
                { id: 40680, name: 'BUSINGIRO' },
                { id: 40681, name: 'ISHONGORORO' },
                { id: 40682, name: 'ISHONGORORO  T/C' },
                { id: 40683, name: 'KAKINDO I' },
                { id: 40684, name: 'KAKINDO II' },
                { id: 40685, name: 'KAKINGA A' },
                { id: 40686, name: 'KAKINGA B' },
                { id: 40687, name: 'KASHUNGWA A' },
                { id: 40688, name: 'KASHUNGWA B' },
                { id: 40689, name: 'KATONGORE' },
                { id: 40690, name: 'KIDUNDUMA' },
                { id: 40691, name: 'KITOORO' },
                { id: 40692, name: 'KOLOLO' },
                { id: 40693, name: 'NYAKARAMBI' },
                { id: 40694, name: 'RURAMA' },
                { id: 40695, name: 'RWENSHAJAGWA' },
              ],
            },
            {
              id: 6497,
              name: 'NYANTSIMBO WARD',
              villages: [
                { id: 40696, name: 'ISHONGORORO T/C' },
                { id: 40714, name: 'KAMBENDYAHA T/C' },
                { id: 40715, name: 'KAROKARUNGI' },
                { id: 40697, name: 'KATOJO A' },
                { id: 40698, name: 'KATOJO B' },
                { id: 40699, name: 'KATOJO C' },
                { id: 40700, name: 'KEMIHOKO' },
                { id: 40701, name: 'KIBURARA A' },
                { id: 40702, name: 'KIBURARA B' },
                { id: 40703, name: 'KIBURARA T/C' },
                { id: 40716, name: 'KINYANKORE' },
                { id: 40704, name: 'NCWANO A' },
                { id: 40705, name: 'NCWANO B' },
                { id: 40706, name: 'NCWANO C' },
                { id: 40707, name: 'NYABUSHABI' },
                { id: 40717, name: 'NYAKABUNGO' },
                { id: 40718, name: 'NYAMPIKYE' },
                { id: 40708, name: 'NYANTSIMBO A' },
                { id: 40709, name: 'NYANTSIMBO T/C' },
                { id: 40719, name: 'OMWIGURU' },
                { id: 40710, name: 'OMWITAGI' },
                { id: 40711, name: 'RUGANDO' },
                { id: 40712, name: 'RWENSHOGA' },
                { id: 40713, name: 'RWENYAWAWA' },
              ],
            },
          ],
        },
        {
          id: 1381,
          name: 'KIJONGO',
          parishes: [
            {
              id: 6499,
              name: 'BIRONGO',
              villages: [
                { id: 40729, name: 'BIRONGO II' },
                { id: 40730, name: 'BIRONGO III' },
                { id: 40728, name: 'BIRONGO IV' },
                { id: 40731, name: 'KAAROKARUNGI' },
                { id: 40732, name: 'KABISO' },
                { id: 40733, name: 'KAFUNJO I' },
                { id: 40734, name: 'KAFUNJO II' },
                { id: 40736, name: 'KAFUNJO III' },
                { id: 40735, name: 'KAHOKO' },
                { id: 40738, name: 'MUTENGYETO' },
                { id: 40739, name: 'NTUSI I' },
                { id: 40740, name: 'NTUSI II' },
                { id: 40737, name: 'NYAMABAARE' },
              ],
            },
            {
              id: 6500,
              name: 'KAMWIRI',
              villages: [
                { id: 40741, name: 'ENDAMA' },
                { id: 40745, name: 'GENKUBA' },
                { id: 40742, name: 'IHONDERO' },
                { id: 40744, name: 'KAMWIRI I' },
                { id: 40743, name: 'KAMWIRI II' },
                { id: 40746, name: 'KITOOGO' },
                { id: 40747, name: 'RWANYAKABOGO' },
              ],
            },
            {
              id: 6498,
              name: 'KIJONGO',
              villages: [
                { id: 40721, name: 'KABARUNGI' },
                { id: 40722, name: 'KAKIIKA' },
                { id: 40723, name: 'KANYINYA' },
                { id: 40724, name: 'KAYANJA I' },
                { id: 40720, name: 'KAYANJA II' },
                { id: 40725, name: 'RWANYABIHUKA I' },
                { id: 40726, name: 'RWANYABIHUKA II' },
                { id: 40727, name: 'RWENKUBA' },
              ],
            },
            {
              id: 6501,
              name: 'RWAMBU',
              villages: [
                { id: 40748, name: 'BIRONGO I' },
                { id: 40750, name: 'KINAGA MUKONO' },
                { id: 40751, name: 'KIRYABISHORO' },
                { id: 40749, name: 'RUNONI' },
                { id: 40752, name: 'RWAMBU II' },
                { id: 40753, name: 'RWAMBU III' },
                { id: 40754, name: 'RWAMBU IV' },
                { id: 40755, name: 'RWEMIRAMA' },
              ],
            },
          ],
        },
        {
          id: 1379,
          name: 'NYAMAREBE',
          parishes: [
            {
              id: 6490,
              name: 'BIHANGA',
              villages: [
                { id: 40624, name: 'BIHANGA I' },
                { id: 40625, name: 'BIHANGA II' },
                { id: 40627, name: 'KACEERI' },
                { id: 40626, name: 'KAKUKURU' },
                { id: 40628, name: 'KATENSANI' },
                { id: 40629, name: 'KATOJO II' },
                { id: 40630, name: 'KYABWAYERA' },
                { id: 40631, name: 'NYABIGOYE I' },
                { id: 40632, name: 'NYABIGOYE II' },
                { id: 40633, name: 'NYAKANENGO' },
                { id: 40634, name: 'RUGARAMA' },
                { id: 40635, name: 'RWENKUBA I' },
                { id: 40636, name: 'RWENKUBA II' },
              ],
            },
            {
              id: 6493,
              name: 'KANYARUGIRI',
              villages: [
                { id: 40660, name: 'BUTERANIRO' },
                { id: 40661, name: 'KANYARUGIRI' },
                { id: 40659, name: 'KARAMA' },
                { id: 40662, name: 'KIGAAGA' },
                { id: 40658, name: 'MUGYENGYEZI II' },
                { id: 40663, name: 'RWAMAGUNDU' },
              ],
            },
            {
              id: 6492,
              name: 'KYENGANDO',
              villages: [
                { id: 40642, name: 'BUSINGIRO I' },
                { id: 40643, name: 'BUSINGIRO II' },
                { id: 40644, name: 'BWERA I' },
                { id: 40645, name: 'BWERA II' },
                { id: 40646, name: 'KAARO' },
                { id: 40647, name: 'KAKO' },
                { id: 40648, name: 'KANYINYA' },
                { id: 40649, name: 'KATOOMA' },
                { id: 40650, name: 'KATUTSI' },
                { id: 40651, name: 'KIGORO' },
                { id: 40652, name: 'KOBUHURA  A' },
                { id: 40653, name: 'KOBUHURA  B' },
                { id: 40654, name: 'KYENGANDO' },
                { id: 40655, name: 'NYAKAHITA' },
                { id: 40656, name: 'NYAMAREBE I' },
                { id: 40657, name: 'NYAMAREBE II' },
              ],
            },
            {
              id: 6494,
              name: 'NYAKABUNGO',
              villages: [
                { id: 40664, name: 'AHAKABAARE' },
                { id: 40666, name: 'KASHAARI' },
                { id: 40667, name: 'KITOJO' },
                { id: 40668, name: 'NYAKABUNGO' },
                { id: 40669, name: 'RWAMAHEGA' },
                { id: 40665, name: 'RWENKUBA III' },
                { id: 40670, name: 'RWENKUREIJO I' },
                { id: 40671, name: 'RWENKUREIJO II' },
              ],
            },
            {
              id: 6491,
              name: 'RUSHANGO',
              villages: [
                { id: 40637, name: 'KANGOMA A' },
                { id: 40638, name: 'KANGOMA B' },
                { id: 40639, name: 'KATIKAMWE B' },
                { id: 40640, name: 'MITWEBIRI A' },
                { id: 40641, name: 'MITWEBIRI B' },
              ],
            },
            {
              id: 6495,
              name: 'RYABIJU',
              villages: [
                { id: 40672, name: 'ITABYAMA A' },
                { id: 40673, name: 'RWENCUNDEZI A' },
                { id: 40674, name: 'RWENCUNDEZI B' },
                { id: 40675, name: 'RWENCUNDEZI C' },
                { id: 40676, name: 'RYABIJU B' },
                { id: 40677, name: 'SOOKO A' },
                { id: 40678, name: 'SOOKO B' },
                { id: 40679, name: 'SOOKO C' },
              ],
            },
          ],
        },
        {
          id: 1382,
          name: 'RUSHANGO TOWN COUNCIL',
          parishes: [
            {
              id: 6503,
              name: 'ITABYAMA WARD',
              villages: [
                { id: 40761, name: 'ITABYAMA B' },
                { id: 40762, name: 'ITABYAMA C' },
                { id: 40763, name: 'MUGYENGYEZI I' },
                { id: 40764, name: 'RWEMIRAMA' },
                { id: 40765, name: 'RYABIJU A' },
              ],
            },
            {
              id: 6502,
              name: 'RUSHANGO WARD',
              villages: [
                { id: 40756, name: 'KARAMBI A' },
                { id: 40757, name: 'KARAMBI B' },
                { id: 40758, name: 'KATIKAMWE A' },
                { id: 40759, name: 'RUSHANGO A' },
                { id: 40760, name: 'RUSHANGO B' },
              ],
            },
          ],
        },
        {
          id: 1383,
          name: 'RWENKOBWA TOWN COUNCIL',
          parishes: [
            {
              id: 6505,
              name: 'KAREMBA WARD',
              villages: [
                { id: 40770, name: 'KAREMBA' },
                { id: 40771, name: 'KATONGORE' },
                { id: 40772, name: 'KIJONGO II' },
                { id: 40773, name: 'RWAMBU I' },
              ],
            },
            {
              id: 6504,
              name: 'MIRAMBI WARD',
              villages: [
                { id: 40767, name: 'KATAGATA' },
                { id: 40768, name: 'KIJONGO I' },
                { id: 40766, name: 'MIRAMBI' },
                { id: 40769, name: 'RWENKOBWA T.C' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 219,
      name: 'IBANDA COUNTY SOUTH',
      sub_counties: [
        {
          id: 1389,
          name: 'IGORORA TOWN COUNCIL',
          parishes: [
            {
              id: 6524,
              name: 'IGORORA WARD',
              villages: [
                { id: 40947, name: 'EMBAHO' },
                { id: 40952, name: 'IGORORA' },
                { id: 40948, name: 'KANYEGANYEGYE' },
                { id: 40949, name: 'KYARUKUMBA II' },
                { id: 40950, name: 'NTUNGAMO I' },
                { id: 40951, name: 'NTUNGAMO II' },
              ],
            },
            {
              id: 6525,
              name: 'NGANGO WARD',
              villages: [
                { id: 40955, name: 'KIGANDO I' },
                { id: 40956, name: 'KIGANDO II' },
                { id: 40958, name: 'KIGANDO III' },
                { id: 40957, name: 'NGANGO I' },
                { id: 40953, name: 'NGANGO II' },
                { id: 40954, name: 'NGANGO III' },
              ],
            },
          ],
        },
        {
          id: 1388,
          name: 'KEIHANGARA',
          parishes: [
            {
              id: 6521,
              name: 'KEIHANGARA',
              villages: [
                { id: 40913, name: 'KABINGO' },
                { id: 40914, name: 'KAJWAMUSHANA I' },
                { id: 40920, name: 'KAJWAMUSHANA IV' },
                { id: 40915, name: 'KEIHANGARA I' },
                { id: 40916, name: 'KEIHANGARA II' },
                { id: 40917, name: 'KEIHANGARA III' },
                { id: 40921, name: 'KEIHANGARA IV' },
                { id: 40922, name: 'KEIHANGARA V' },
                { id: 40918, name: 'KYARUKUMBA I' },
                { id: 40919, name: 'RWESHEBESHEBE' },
              ],
            },
            {
              id: 6522,
              name: 'RUGAAGA',
              villages: [
                { id: 40925, name: 'KABURO I' },
                { id: 40926, name: 'KABURO II' },
                { id: 40927, name: 'KAJWAMUSHANA II' },
                { id: 40928, name: 'KAJWAMUSHANA III' },
                { id: 40923, name: 'KAJWAMUSHANA V' },
                { id: 40929, name: 'KAKUNAMA II' },
                { id: 40930, name: 'KAKUNAMA III' },
                { id: 40924, name: 'KYENYENA' },
                { id: 40931, name: 'RUGAAGA I' },
                { id: 40932, name: 'RUGAAGA II' },
                { id: 40933, name: 'RUGAAGA III' },
                { id: 40934, name: 'RUGAAGA IV' },
                { id: 40935, name: 'RUGAAGA V' },
              ],
            },
            {
              id: 6523,
              name: 'RWENSHAMBYA',
              villages: [
                { id: 40936, name: 'BIHEMBE I' },
                { id: 40937, name: 'BIHEMBE II' },
                { id: 40938, name: 'BIHEMBE III' },
                { id: 40939, name: 'BIHEMBE IV' },
                { id: 40942, name: 'KAKUNAMA I' },
                { id: 40944, name: 'RUKINGA I' },
                { id: 40940, name: 'RUKINGA II' },
                { id: 40945, name: 'RWENSAMBYA I' },
                { id: 40946, name: 'RWENSAMBYA II' },
                { id: 40941, name: 'RWENSAMBYA III' },
                { id: 40943, name: 'RWENSAMBYA IV' },
              ],
            },
          ],
        },
        {
          id: 1384,
          name: 'KICUZI',
          parishes: [
            {
              id: 6506,
              name: 'IRIMYA',
              villages: [
                { id: 40774, name: 'BUHINDAGI' },
                { id: 40775, name: 'IRIMYA' },
                { id: 40776, name: 'KAGYEZI' },
                { id: 40777, name: 'KAKINDO' },
                { id: 40778, name: 'KAROKARUNGI' },
                { id: 40779, name: 'KARUHUTSI' },
                { id: 40780, name: 'KATONGOLE' },
                { id: 40781, name: 'KITOOMA' },
                { id: 40782, name: 'KWEREBERA' },
                { id: 40783, name: 'MIRAMA' },
                { id: 40784, name: 'RWEBIYONGI' },
                { id: 40785, name: 'RWENZIGYE' },
                { id: 40786, name: 'RYAKAZO' },
              ],
            },
            {
              id: 6508,
              name: 'KANYWAMBOGO',
              villages: [
                { id: 40803, name: 'KAABUHWEJU' },
                { id: 40804, name: 'KIBINGO' },
                { id: 40805, name: 'KISABO CENTRAL' },
                { id: 40806, name: 'KISABO I' },
                { id: 40807, name: 'KISABO II' },
                { id: 40809, name: 'RYABATENGA  II' },
                { id: 40808, name: 'RYABATENGA I' },
                { id: 40810, name: 'RYAKAGUMBA' },
              ],
            },
            {
              id: 6507,
              name: 'KICUZI',
              villages: [
                { id: 40787, name: 'BRAZIL' },
                { id: 40788, name: 'KABENDE' },
                { id: 40789, name: 'KABUHWA' },
                { id: 40790, name: 'KAGOROGORO' },
                { id: 40791, name: 'KATEGURE' },
                { id: 40792, name: 'KATERERA' },
                { id: 40793, name: 'KICUZI' },
                { id: 40794, name: 'KINYAMUGARA' },
                { id: 40795, name: 'KISABO' },
                { id: 40796, name: 'KITEHE' },
                { id: 40797, name: 'KOGABI' },
                { id: 40798, name: 'MAHUHA' },
                { id: 40799, name: 'MURANGARA' },
                { id: 40800, name: 'MUTURE' },
                { id: 40801, name: 'RUGARAMA' },
                { id: 40802, name: 'RWEMAMBO' },
              ],
            },
          ],
        },
        {
          id: 1385,
          name: 'KIKYENKYE',
          parishes: [
            {
              id: 6511,
              name: 'IRWANIRO',
              villages: [
                { id: 40833, name: 'IRWANIRO I' },
                { id: 40836, name: 'IRWANIRO II' },
                { id: 40834, name: 'KAJUMBURA I' },
                { id: 40838, name: 'KAJUMBURA II' },
                { id: 40835, name: 'KATUNGURU' },
                { id: 40837, name: 'KIHANI I' },
                { id: 40839, name: 'KITEMBEYA' },
              ],
            },
            {
              id: 6509,
              name: 'KIHANI',
              villages: [
                { id: 40811, name: 'KEBICOORI' },
                { id: 40812, name: 'KIHANI II' },
                { id: 40813, name: 'KIHANI III' },
                { id: 40814, name: 'NYAKABUNGO' },
                { id: 40815, name: 'RWENKUBA I' },
                { id: 40816, name: 'RWENKUBA II' },
                { id: 40817, name: 'RWENTARATAMBI' },
                { id: 40818, name: 'SIGIRIRA I' },
                { id: 40819, name: 'SIGIRIRA II' },
                { id: 40820, name: 'SIGIRIRA III' },
                { id: 40821, name: 'SIGIRIRA IV' },
              ],
            },
            {
              id: 6510,
              name: 'RWENGWE',
              villages: [
                { id: 40822, name: 'KAGOIGO' },
                { id: 40823, name: 'KAMIGAMBA I' },
                { id: 40831, name: 'KAMIGAMBA II' },
                { id: 40824, name: 'KARITUSI' },
                { id: 40825, name: 'RWEMENGO I' },
                { id: 40826, name: 'RWEMENGO II' },
                { id: 40827, name: 'RWENGWE I' },
                { id: 40828, name: 'RWENGWE II' },
                { id: 40829, name: 'RWENGWE III' },
                { id: 40830, name: 'RWOMUHORO I' },
                { id: 40832, name: 'RWOMUHORO II' },
              ],
            },
          ],
        },
        {
          id: 1386,
          name: 'NYABUHIKYE',
          parishes: [
            {
              id: 6513,
              name: 'BWAHWA',
              villages: [
                { id: 40847, name: 'KAIRABA' },
                { id: 40848, name: 'KAYANJA' },
                { id: 40849, name: 'KIRUBA' },
                { id: 40851, name: 'MITOOMA' },
                { id: 40850, name: 'NKOMBE' },
                { id: 40853, name: 'RUJUMBURA' },
                { id: 40852, name: 'RWENGWE' },
              ],
            },
            {
              id: 6512,
              name: 'KYENTAMA',
              villages: [
                { id: 40840, name: 'KASESE' },
                { id: 40841, name: 'KATOJO' },
                { id: 40843, name: 'KYATOKO' },
                { id: 40842, name: 'KYENTAAMA' },
                { id: 40844, name: 'NYAKATETE' },
                { id: 40845, name: 'NYARUBIRA' },
                { id: 40846, name: 'RYAKWEERA' },
              ],
            },
            {
              id: 6514,
              name: 'RUGOBA',
              villages: [
                { id: 40854, name: 'KACWAMPARE' },
                { id: 40856, name: 'KAGUNGA' },
                { id: 40857, name: 'KANUNGU' },
                { id: 40858, name: 'KASHASHA' },
                { id: 40855, name: 'KIZIIRA' },
                { id: 40860, name: 'NYAKATETE UPPER' },
                { id: 40859, name: 'RUGOBA' },
                { id: 40861, name: 'RUSHERE' },
              ],
            },
          ],
        },
        {
          id: 1387,
          name: 'RUKIRI',
          parishes: [
            {
              id: 6515,
              name: 'BWENDA',
              villages: [
                { id: 40862, name: 'BWENDA' },
                { id: 40863, name: 'MIRAMBI  I' },
                { id: 40864, name: 'MIRAMBI II' },
                { id: 40865, name: 'MPUNDA' },
                { id: 40866, name: 'NTANGA' },
                { id: 40867, name: 'RUKIIRI' },
                { id: 40868, name: 'RWOBUHOMPO' },
              ],
            },
            {
              id: 6519,
              name: 'KATEMBE',
              villages: [
                { id: 40894, name: 'BWAHIKA' },
                { id: 40895, name: 'IHOME' },
                { id: 40896, name: 'KAIJORORONGA' },
                { id: 40897, name: 'KASHARI' },
                { id: 40898, name: 'KATEMBE' },
                { id: 40899, name: 'KIBANDE I' },
                { id: 40900, name: 'KIBANDE II' },
                { id: 40901, name: 'MUGARAMA I' },
                { id: 40902, name: 'MUGARAMA II' },
                { id: 40903, name: 'NYARUBIRA' },
                { id: 40904, name: 'RWIJOGORO' },
                { id: 40905, name: 'RYAKATIRI' },
              ],
            },
            {
              id: 6518,
              name: 'KIGUNGA',
              villages: [
                { id: 40888, name: 'KABINGO' },
                { id: 40889, name: 'KISENSERO' },
                { id: 40890, name: 'NJEMBE I' },
                { id: 40891, name: 'NJEMBE II' },
                { id: 40892, name: 'NYAKAHITA' },
                { id: 40893, name: 'RWOBUHUNGYE' },
              ],
            },
            {
              id: 6516,
              name: 'MABONA',
              villages: [
                { id: 40869, name: 'KAARA' },
                { id: 40870, name: 'KABINGO' },
                { id: 40871, name: 'KARIHE' },
                { id: 40872, name: 'KITENGURE' },
                { id: 40873, name: 'MABONA' },
                { id: 40874, name: 'RUGAZI' },
                { id: 40875, name: 'RYAMITAMBA' },
                { id: 40876, name: 'VATICAN' },
              ],
            },
            {
              id: 6520,
              name: 'MPASHA',
              villages: [
                { id: 40906, name: 'KAARANGARA' },
                { id: 40907, name: 'KAROMBE' },
                { id: 40908, name: 'KYANIKA' },
                { id: 40909, name: 'MPASHA' },
                { id: 40910, name: 'MUHANGI' },
                { id: 40911, name: 'RWENGOROGORO' },
                { id: 40912, name: 'RYAKASHUNSHA' },
              ],
            },
            {
              id: 6517,
              name: 'NYARUKIIKA',
              villages: [
                { id: 40877, name: 'KAIHO' },
                { id: 40878, name: 'KYEITANA' },
                { id: 40879, name: 'KYEZITIRA I' },
                { id: 40880, name: 'KYEZITIRA II' },
                { id: 40881, name: 'NYAKAYOJO' },
                { id: 40882, name: 'NYARWATO' },
                { id: 40883, name: 'RUGARAMA I' },
                { id: 40884, name: 'RUGARAMA II' },
                { id: 40885, name: 'RUTOOMA' },
                { id: 40886, name: 'RWENSIGA I' },
                { id: 40887, name: 'RWENSIGA II' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 220,
      name: 'IBANDA MUNICIPALITY',
      sub_counties: [
        {
          id: 1390,
          name: 'BISHESHE DIVISION',
          parishes: [
            {
              id: 6526,
              name: 'BUGARAMA WARD',
              villages: [
                { id: 40959, name: 'BISHESHE CENTRAL' },
                { id: 40960, name: 'KANKYENDE I' },
                { id: 40961, name: 'KANKYENDE II' },
                { id: 40962, name: 'KANKYENDE III' },
                { id: 40963, name: 'KATOOMA' },
                { id: 40964, name: 'KIBAGARWA I' },
                { id: 40965, name: 'KIBAGARWA II' },
                { id: 40966, name: 'KIBAGARWA III' },
                { id: 40967, name: 'KIGANDO' },
                { id: 40968, name: 'KITONTOMA CENTRAL' },
                { id: 40969, name: 'KITONTOMA EAST' },
                { id: 40970, name: 'KITONTOMA WEST' },
                { id: 40976, name: 'KYENJOGYERA' },
                { id: 40977, name: 'MASHURI I' },
                { id: 40978, name: 'MASHURI II' },
                { id: 40979, name: 'MASHURI III' },
                { id: 40971, name: 'NYINAIBARE I' },
                { id: 40972, name: 'NYINAIBARE II' },
                { id: 40973, name: 'RUSHASHA I' },
                { id: 40974, name: 'RUSHASHA II' },
                { id: 40975, name: 'RWEBIKOONA' },
                { id: 40980, name: 'RWEMEREIRE III' },
              ],
            },
            {
              id: 6529,
              name: 'KABAARE WARD',
              villages: [
                { id: 41004, name: 'GABARURI' },
                { id: 41005, name: 'KABAARE I' },
                { id: 41006, name: 'KABAARE II' },
                { id: 41007, name: 'KABAARE III' },
                { id: 41008, name: 'KAGANGO I' },
                { id: 41009, name: 'KAGANGO II' },
                { id: 41010, name: 'KAGANGO III' },
                { id: 41011, name: 'KAGANGO IV' },
                { id: 41012, name: 'KAGANGO V' },
                { id: 41013, name: 'KEIHIRO I' },
                { id: 41014, name: 'KEIHIRO II' },
                { id: 41015, name: 'KYEMBOGO I' },
                { id: 41016, name: 'KYEMBOGO II' },
                { id: 41017, name: 'RUSHAKA I' },
                { id: 41018, name: 'RUSHAKA II' },
              ],
            },
            {
              id: 6527,
              name: 'KAKATSI WARD',
              villages: [
                { id: 40981, name: 'BISHAYUMBE' },
                { id: 40982, name: 'KAKATSI I' },
                { id: 40983, name: 'KAKATSI II' },
                { id: 40984, name: 'KAKATSI III' },
                { id: 40985, name: 'MISHOZI I' },
                { id: 40986, name: 'MISHOZI II' },
                { id: 40987, name: 'MISHOZI III' },
              ],
            },
            {
              id: 6528,
              name: 'KARANGARA WARD',
              villages: [
                { id: 40988, name: 'BIROORO I' },
                { id: 40989, name: 'BIROORO II' },
                { id: 40990, name: 'BUGARAMA I' },
                { id: 40991, name: 'BUGARAMA II' },
                { id: 40992, name: 'IREME I' },
                { id: 40993, name: 'IREME II' },
                { id: 40994, name: 'KARANGARA' },
                { id: 40995, name: 'KASHAGAZI' },
                { id: 40996, name: 'KYEMBOGO' },
                { id: 40997, name: 'MUZIZA CENTRAL' },
                { id: 40998, name: 'RUSHAKA I' },
                { id: 40999, name: 'RUSHAKA II' },
                { id: 41000, name: 'RUSHAKA III' },
                { id: 41001, name: 'RWEMEREIRE I' },
                { id: 41002, name: 'RWEMEREIRE II' },
                { id: 41003, name: 'RYAKATUMBA' },
              ],
            },
            {
              id: 6530,
              name: 'KIGARAMA WARD',
              villages: [
                { id: 41022, name: 'BUKUUTO' },
                { id: 41023, name: 'KAGOROGORO' },
                { id: 41019, name: 'KIGARAMA LOWER' },
                { id: 41024, name: 'KIGARAMA T/C' },
                { id: 41025, name: 'KIGARAMA UPPER' },
                { id: 41026, name: 'NYAKATETE I' },
                { id: 41027, name: 'NYAKATETE II' },
                { id: 41020, name: 'NYAKATETE III' },
                { id: 41021, name: 'RWAMABAARE LOWER' },
                { id: 41028, name: 'RWAMABAARE UPPER' },
              ],
            },
            {
              id: 6531,
              name: 'RUGAZI WARD',
              villages: [
                { id: 41029, name: 'BIGYERA' },
                { id: 41031, name: 'KASHAKA I' },
                { id: 41032, name: 'KASHAKA II' },
                { id: 41033, name: 'KYEIKUCU I' },
                { id: 41034, name: 'KYEIKUCU II' },
                { id: 41035, name: 'NYAKATOKYE I' },
                { id: 41036, name: 'NYAKATOKYE II' },
                { id: 41037, name: 'RUGAZI I' },
                { id: 41030, name: 'RUGAZI II' },
              ],
            },
          ],
        },
        {
          id: 1391,
          name: 'BUFUNDA DIVISION',
          parishes: [
            {
              id: 6532,
              name: 'BUFUNDA WARD',
              villages: [
                { id: 41038, name: 'BUBAARE' },
                { id: 41039, name: 'BUFUNDA I A' },
                { id: 41050, name: 'BUFUNDA I B' },
                { id: 41040, name: 'BUFUNDA II' },
                { id: 41041, name: 'BUFUNDA STREET' },
                { id: 41042, name: 'KABARUKA' },
                { id: 41043, name: 'KAFUNJO' },
                { id: 41051, name: 'KANYINAMPETA' },
                { id: 41044, name: 'KYABARENDE' },
                { id: 41045, name: 'KYABASHAMBO' },
                { id: 41052, name: 'KYABUGAIJA LOWER' },
                { id: 41046, name: 'KYABUGAIJA UPPER' },
                { id: 41047, name: 'KYAMOSHE' },
                { id: 41048, name: 'KYEGWISA' },
                { id: 41049, name: 'MPIIRA STREET' },
              ],
            },
            {
              id: 6537,
              name: 'KATONGORE WARD',
              villages: [
                { id: 41094, name: 'KAFUNJO I' },
                { id: 41095, name: 'KAFUNJO II' },
                { id: 41101, name: 'KAFUNJO III' },
                { id: 41098, name: 'KATONGORE I' },
                { id: 41096, name: 'KATONGORE II' },
                { id: 41097, name: 'KAYONZA' },
                { id: 41099, name: 'SIGIRIRA I' },
                { id: 41100, name: 'SIGIRIRA II' },
              ],
            },
            {
              id: 6533,
              name: 'KAYENJE WARD',
              villages: [
                { id: 41053, name: 'KAHUNGYE' },
                { id: 41054, name: 'KATEGURE' },
                { id: 41055, name: 'KAYENJE I' },
                { id: 41056, name: 'KAYENJE II' },
                { id: 41057, name: 'KEMITOOJO' },
                { id: 41058, name: 'KYARUHIMBI' },
                { id: 41059, name: 'NTUNGAMO' },
                { id: 41060, name: 'NYABUHIKYE T/C' },
                { id: 41061, name: 'NYABWEGARIKA' },
                { id: 41062, name: 'NYANGA' },
                { id: 41063, name: 'RUYONZA I' },
                { id: 41064, name: 'RWOBUHUNGYE' },
              ],
            },
            {
              id: 6538,
              name: 'KIKONI WARD',
              villages: [
                { id: 41103, name: 'KIKONI CENTRAL' },
                { id: 41102, name: 'KIKONI EAST' },
                { id: 41104, name: 'KIKONI I' },
                { id: 41105, name: 'KIKONI II' },
                { id: 41106, name: 'RWEMIRAMA I' },
                { id: 41107, name: 'RWEMIRAMA II' },
                { id: 41108, name: 'RWESETA' },
              ],
            },
            {
              id: 6534,
              name: 'NSASI WARD',
              villages: [
                { id: 41065, name: 'BUKUTO  II' },
                { id: 41066, name: 'KARUSHAMBYA' },
                { id: 41067, name: 'KIBARAMA I' },
                { id: 41068, name: 'KIBARAMA II' },
                { id: 41069, name: 'KIBIRIZI' },
                { id: 41073, name: 'KYENTUREGYE' },
                { id: 41070, name: 'NSASI  T/C' },
                { id: 41071, name: 'NYAKAKIRI' },
                { id: 41072, name: 'RWAMANYONYI UPPER' },
              ],
            },
            {
              id: 6535,
              name: 'NYAMIRIMA WARD',
              villages: [
                { id: 41074, name: 'BWENTAAMA' },
                { id: 41075, name: 'KABAGOMA I' },
                { id: 41076, name: 'KABAGOMA II' },
                { id: 41077, name: 'KAGANDO' },
                { id: 41078, name: 'KIBAARE' },
                { id: 41079, name: 'KIGYERA' },
                { id: 41080, name: 'MABANGA' },
                { id: 41081, name: 'NDORAGI I' },
                { id: 41082, name: 'NDORAGI II' },
                { id: 41083, name: 'NYAMIRIMA LOWER' },
                { id: 41084, name: 'NYAMIRIMA UPPER' },
                { id: 41086, name: 'RWEMIRABYO' },
                { id: 41085, name: 'RWENTSINGA' },
              ],
            },
            {
              id: 6539,
              name: 'RUYONZA WARD',
              villages: [
                { id: 41115, name: 'AKAIBUMBA' },
                { id: 41110, name: 'KAREERE I' },
                { id: 41109, name: 'KAREERE II' },
                { id: 41111, name: 'KATETE' },
                { id: 41112, name: 'NYAKABUNGO I' },
                { id: 41113, name: 'NYAKABUNGO II' },
                { id: 41114, name: 'RUYONZA MIDDLE' },
                { id: 41116, name: 'RWAMANYONYI LOWER' },
              ],
            },
            {
              id: 6536,
              name: 'RWOBUZIZI WARD',
              villages: [
                { id: 41087, name: 'KANKAMBWE I' },
                { id: 41092, name: 'KANKAMBWE II' },
                { id: 41088, name: 'KATEMBE' },
                { id: 41089, name: 'RUYOMBA' },
                { id: 41090, name: 'RWOBUZIZI I' },
                { id: 41091, name: 'RWOBUZIZI II' },
                { id: 41093, name: 'RWOBUZIZI III' },
              ],
            },
          ],
        },
        {
          id: 1392,
          name: 'KAGONGO DIVISION',
          parishes: [
            {
              id: 6543,
              name: 'KAGONGO WARD',
              villages: [
                { id: 41159, name: 'BUHUMURIRO' },
                { id: 41150, name: 'KAFUNDA T/CENTRE' },
                { id: 41151, name: 'KAGONGO INSTITUTIONS' },
                { id: 41152, name: 'KASHARARA' },
                { id: 41153, name: 'KATOOMA I' },
                { id: 41154, name: 'KATOOMA II' },
                { id: 41160, name: 'KISIITA' },
                { id: 41155, name: 'MABANGA' },
                { id: 41156, name: 'NYINENDUGU' },
                { id: 41157, name: 'RUKOKOMA' },
                { id: 41161, name: 'RWAMUKIIGI' },
                { id: 41162, name: 'RWENCWAMBA' },
                { id: 41158, name: 'RWENGIRI T/CENTRE' },
              ],
            },
            {
              id: 6542,
              name: 'KANYANSHEKO WARD',
              villages: [
                { id: 41144, name: 'KABURA' },
                { id: 41145, name: 'KANYANSHEKO A' },
                { id: 41146, name: 'KANYANSHEKO B' },
                { id: 41147, name: 'KIKANDURE' },
                { id: 41148, name: 'KYARUFUBANGI' },
                { id: 41149, name: 'NYAKIGANDO' },
              ],
            },
            {
              id: 6540,
              name: 'KASHANGURA WARD',
              villages: [
                { id: 41117, name: 'BIGYERA' },
                { id: 41118, name: 'KAKUKURU' },
                { id: 41119, name: 'KAMUTUTUMI I' },
                { id: 41120, name: 'KAMUTUTUMI II' },
                { id: 41121, name: 'KARINDIRIRO' },
                { id: 41122, name: 'KASHANGURA I' },
                { id: 41123, name: 'KASHANGURA II' },
                { id: 41124, name: 'NYAMUSHWIGA' },
                { id: 41125, name: 'NYARUBIRA' },
                { id: 41126, name: 'RWAHURA I' },
                { id: 41128, name: 'RWATEIBARE' },
                { id: 41127, name: 'RYAKASHANKARA' },
              ],
            },
            {
              id: 6545,
              name: 'KYARUHANGA WARD',
              villages: [
                { id: 41179, name: 'IBANDA  CELL' },
                { id: 41174, name: 'IBANDA CENTRAL' },
                { id: 41180, name: 'JUBILEE STREET' },
                { id: 41182, name: 'KITWE' },
                { id: 41183, name: 'KYARUHANGA I' },
                { id: 41184, name: 'KYARUHANGA II' },
                { id: 41185, name: 'KYARUKOBWA A' },
                { id: 41186, name: 'KYARUKOBWA B' },
                { id: 41176, name: 'KYARUKOOBWA B EAST' },
                { id: 41175, name: 'KYARUKOOBWA C' },
                { id: 41177, name: 'KYEREETA' },
                { id: 41187, name: 'MAIN STREET' },
                { id: 41178, name: 'MUGINDA' },
                { id: 41181, name: 'SAZA' },
              ],
            },
            {
              id: 6544,
              name: 'KYEIKUCU WARD',
              villages: [
                { id: 41163, name: 'BUGORORA' },
                { id: 41164, name: 'KYARUTANGA I' },
                { id: 41165, name: 'KYARUTANGA II' },
                { id: 41166, name: 'KYEIKUCU  I' },
                { id: 41167, name: 'KYEIKUCU  II' },
                { id: 41168, name: 'MAHEGA I' },
                { id: 41169, name: 'MAHEGA II' },
                { id: 41170, name: 'MIRAMBI' },
                { id: 41171, name: 'RUKOKOMA II' },
                { id: 41172, name: 'RWAHURA II' },
                { id: 41173, name: 'RWAMPANGA' },
              ],
            },
            {
              id: 6541,
              name: 'NYAKATOKYE WARD',
              villages: [
                { id: 41129, name: 'BIGYERA' },
                { id: 41130, name: 'KANAMA I' },
                { id: 41131, name: 'KANAMA II' },
                { id: 41132, name: 'KASHAKA' },
                { id: 41133, name: 'KIGAIGO' },
                { id: 41134, name: 'KIGANDO' },
                { id: 41135, name: 'KITOOMA' },
                { id: 41136, name: 'MISHANGI' },
                { id: 41137, name: 'NATEETE' },
                { id: 41138, name: 'NYAKATOKYE CENTRAL' },
                { id: 41139, name: 'NYAMIYAGA I' },
                { id: 41140, name: 'NYAMIYAGA II' },
                { id: 41141, name: 'RWEBIYENJE I' },
                { id: 41142, name: 'RWEBIYENJE II' },
                { id: 41143, name: 'RYAKASHORO' },
              ],
            },
            {
              id: 6546,
              name: 'RWENSHURI WARD',
              villages: [
                { id: 41189, name: 'BYESHEMBE I' },
                { id: 41195, name: 'BYESHEMBE II' },
                { id: 41190, name: 'KABEREEBERE' },
                { id: 41192, name: 'KAKIZERERE I' },
                { id: 41193, name: 'KAKIZERERE II' },
                { id: 41194, name: 'KASHAMBYA I' },
                { id: 41188, name: 'RUGAAGA' },
                { id: 41196, name: 'RWESHURI I' },
                { id: 41191, name: 'RWESHURI II' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
