import { District } from '../types';

export default <District>{
  id: 90,
  name: 'ISINGIRO',
  counties: [
    {
      id: 221,
      name: 'BUKANGA COUNTY',
      sub_counties: [
        {
          id: 1401,
          name: 'BUGANGO TOWN COUNCIL',
          parishes: [
            {
              id: 9632,
              name: 'KASHARIRA WARD',
              villages: [
                { id: 61967, name: 'KABURA I' },
                { id: 62936, name: 'KASHARIRA' },
                { id: 63279, name: 'KEMINAZI' },
                { id: 63815, name: 'KIRIIMA' },
                { id: 69951, name: 'RUMURI' },
              ],
            },
            {
              id: 6588,
              name: 'KIKOKWA WARD',
              villages: [
                { id: 62108, name: 'KAGOROGORO' },
                { id: 41486, name: 'KIKOKWA' },
                { id: 41487, name: 'NSHORORO' },
              ],
            },
            {
              id: 6589,
              name: 'KISHUNJU WARD',
              villages: [
                { id: 41488, name: 'BUGANGO I' },
                { id: 59299, name: 'BUGANGO IV' },
              ],
            },
            {
              id: 6590,
              name: 'KYABAZIBWE WARD',
              villages: [
                { id: 41489, name: 'BUGANGO II' },
                { id: 59298, name: 'BUGANGO III' },
              ],
            },
            {
              id: 10010,
              name: 'MUREMA WARD',
              villages: [
                { id: 61968, name: 'KABURA II' },
                { id: 63478, name: 'KIGANDO' },
                { id: 64039, name: 'KITEREDE' },
                { id: 66644, name: 'MUREMA A' },
                { id: 66645, name: 'MUREMA B' },
                { id: 66646, name: 'MUREMA CENTRAL' },
              ],
            },
            {
              id: 10098,
              name: 'NSHORORO WARD',
              villages: [
                { id: 59412, name: 'BUJUBWE' },
                { id: 62136, name: 'KAHUNGYE' },
                { id: 63274, name: 'KEMENGO' },
                { id: 66174, name: 'MBAARE III' },
                { id: 70176, name: 'RWENJURURU' },
              ],
            },
          ],
        },
        {
          id: 1400,
          name: 'ENDIINZI TOWN COUNCIL',
          parishes: [
            {
              id: 6584,
              name: 'ENDIINZI A WARD',
              villages: [
                { id: 41468, name: 'AKATOOJO' },
                { id: 41463, name: 'ENDIINZI A' },
                { id: 41462, name: 'ENDIINZI B' },
                { id: 41465, name: 'KYARUGAJU A' },
                { id: 41466, name: 'KYARUGAJU B' },
                { id: 41464, name: 'KYARUGAJU C' },
                { id: 41470, name: 'MIRITI' },
                { id: 41467, name: 'MWIGGINA' },
                { id: 41469, name: 'NYAKAKONI' },
              ],
            },
            {
              id: 6586,
              name: 'ENDIINZI B WARD',
              villages: [
                { id: 41477, name: 'BIREZI' },
                { id: 41478, name: 'ENGORORA' },
                { id: 41476, name: 'ENGORORA B' },
                { id: 41480, name: 'ORUBARE' },
                { id: 41481, name: 'SAANO A' },
                { id: 41479, name: 'SAANO B' },
              ],
            },
            {
              id: 6587,
              name: 'KAMAAYA WARD',
              villages: [
                { id: 41482, name: 'EKITOKA' },
                { id: 41483, name: 'KAMAAYA A' },
                { id: 41484, name: 'KAMAAYA B' },
                { id: 41485, name: 'KAMAAYA C' },
              ],
            },
            {
              id: 6585,
              name: 'KIKOBA WARD',
              villages: [
                { id: 41473, name: 'KABARONGO' },
                { id: 41474, name: 'KATANGA A' },
                { id: 41471, name: 'KATANGA B' },
                { id: 41475, name: 'KIKOBA A' },
                { id: 41472, name: 'KIKOBA B' },
              ],
            },
          ],
        },
        {
          id: 1393,
          name: 'ENDINZI',
          parishes: [
            {
              id: 6549,
              name: 'BUHUNGA',
              villages: [
                { id: 57752, name: 'AKATOJO' },
                { id: 59397, name: 'BUHUNGA CENTRAL' },
                { id: 41205, name: 'BUHUNGA I' },
                { id: 41204, name: 'BUHUNGA II' },
                { id: 70028, name: 'RWABAGANDA' },
              ],
            },
            {
              id: 6548,
              name: 'BUSHEKA',
              villages: [
                { id: 41200, name: 'BUSHEKA' },
                { id: 61231, name: 'EKINAZI' },
                { id: 41202, name: 'KAGAAGA' },
                { id: 41201, name: 'MATARA' },
                { id: 41203, name: 'MUGUGU' },
                { id: 70187, name: 'RWENKWANZI' },
              ],
            },
            {
              id: 6550,
              name: 'KASHOGA',
              villages: [
                { id: 41207, name: 'EKIYONZA' },
                { id: 41206, name: 'KASHOGA' },
                { id: 67855, name: 'NTARAMA' },
              ],
            },
            {
              id: 6547,
              name: 'NYABYONDO',
              villages: [
                { id: 41197, name: 'KAMUZINZI' },
                { id: 41198, name: 'NYABYONDO' },
                { id: 41199, name: 'OBUNAZI' },
              ],
            },
            {
              id: 6551,
              name: 'RWAMBAGA',
              villages: [
                { id: 62064, name: 'KAGAAGA' },
                { id: 41208, name: 'KAMWEMA A' },
                { id: 41211, name: 'NTUURA' },
                { id: 41210, name: 'RUSHENYI' },
                { id: 41209, name: 'RWAMBAGA' },
                { id: 70120, name: 'RWEKISHWAGA' },
              ],
            },
          ],
        },
        {
          id: 1399,
          name: 'KAKAMBA',
          parishes: [
            {
              id: 6581,
              name: 'BURUMBA',
              villages: [
                { id: 41448, name: 'BURUMBA' },
                { id: 41451, name: 'KABASHAIJA' },
                { id: 41449, name: 'KARAMA' },
                { id: 41450, name: 'RWENSHAMA' },
              ],
            },
            {
              id: 6579,
              name: 'KAKAMBA',
              villages: [
                { id: 41437, name: 'IZO' },
                { id: 41438, name: 'KABASHERWE' },
                { id: 41440, name: 'KABEGARAMIRE' },
                { id: 41441, name: 'KASUSANO' },
                { id: 41442, name: 'NYAKAGO' },
                { id: 41439, name: 'RUKANDU' },
              ],
            },
            {
              id: 6580,
              name: 'KASHENYI',
              villages: [
                { id: 41445, name: 'KABATANGARE' },
                { id: 41446, name: 'KAKIRARA' },
                { id: 41447, name: 'KASHENYI' },
                { id: 41443, name: 'KEMIKOKOMA' },
                { id: 41444, name: 'NYAKIBINGO' },
              ],
            },
            {
              id: 6582,
              name: 'NTENGA',
              villages: [
                { id: 41452, name: 'KAKABAMBA' },
                { id: 41453, name: 'KATYAZO B' },
                { id: 41455, name: 'NTENGA A' },
                { id: 41456, name: 'NTENGA B' },
                { id: 41454, name: 'NTENGA C' },
              ],
            },
            {
              id: 6583,
              name: 'RURONGO',
              villages: [
                { id: 41457, name: 'BIHANGA' },
                { id: 41458, name: 'KAGANDO' },
                { id: 41460, name: 'KAGERA' },
                { id: 41459, name: 'RURONGO A' },
                { id: 41461, name: 'RURONGO B' },
              ],
            },
          ],
        },
        {
          id: 1394,
          name: 'KASHUMBA',
          parishes: [
            {
              id: 6555,
              name: 'KANKINGI',
              villages: [
                { id: 41240, name: 'JURU' },
                { id: 41241, name: 'KABATAMBA' },
                { id: 41242, name: 'KABIRIZI' },
                { id: 41239, name: 'KANKINGI' },
                { id: 41237, name: 'KASHOJWA' },
                { id: 41238, name: 'KAZYA' },
                { id: 41235, name: 'KITYAZA' },
                { id: 41236, name: 'RUKINGA' },
              ],
            },
            {
              id: 6556,
              name: 'KASHARIRA',
              villages: [
                { id: 41243, name: 'KABURA I' },
                { id: 41246, name: 'KASHARIRA' },
                { id: 41244, name: 'KEMINAZI' },
                { id: 41245, name: 'KIRIIMA' },
                { id: 41247, name: 'RUMURI' },
              ],
            },
            {
              id: 6552,
              name: 'KASHUMBA',
              villages: [
                { id: 41212, name: 'BURAMA' },
                { id: 41218, name: 'BYENYI' },
                { id: 41213, name: 'KAGANGO' },
                { id: 41214, name: 'KASHUMBA' },
                { id: 41217, name: 'NYARUTI' },
                { id: 41216, name: 'RUBARE' },
                { id: 41215, name: 'RUBOMBO' },
              ],
            },
            {
              id: 6553,
              name: 'KIGARAGARA',
              villages: [
                { id: 41226, name: 'BUSHUNGWE' },
                { id: 41227, name: 'KAGAARA' },
                { id: 41222, name: 'KAMISHWA' },
                { id: 41219, name: 'KARORA A' },
                { id: 41228, name: 'KARORA B' },
                { id: 41220, name: 'KASHESHE' },
                { id: 41223, name: 'KIGARAGARA A' },
                { id: 41221, name: 'KIGARAGARA B' },
                { id: 41224, name: 'KITANDA' },
                { id: 41225, name: 'KYAKAHURA' },
              ],
            },
            {
              id: 6554,
              name: 'MUREMA',
              villages: [
                { id: 41232, name: 'KABURA II' },
                { id: 41233, name: 'KIGANDO' },
                { id: 41229, name: 'KITEREDE' },
                { id: 41230, name: 'MUREMA A' },
                { id: 41231, name: 'MUREMA B' },
                { id: 41234, name: 'MUREMA CENTRAL' },
              ],
            },
            {
              id: 6557,
              name: 'RUSHWA',
              villages: [
                { id: 41249, name: 'KATYAZO' },
                { id: 41250, name: 'KIYENJE' },
                { id: 41251, name: 'KYABIBABI' },
                { id: 41256, name: 'NTUNGAMO' },
                { id: 41252, name: 'NYAKABINGO A' },
                { id: 41248, name: 'NYAKABINGO B' },
                { id: 41253, name: 'RUSHWA' },
                { id: 41254, name: 'RWAMACUMU A' },
                { id: 41257, name: 'RWAMACUMU B' },
                { id: 41255, name: 'RWENJERU' },
              ],
            },
          ],
        },
        {
          id: 1397,
          name: 'MBAARE',
          parishes: [
            {
              id: 6574,
              name: 'BURIGI',
              villages: [
                { id: 41405, name: 'BUBAREBWERA' },
                { id: 41406, name: 'BURIGI A' },
                { id: 41407, name: 'BURIGI CENTRAL' },
                { id: 41408, name: 'BURIGI I' },
                { id: 41409, name: 'BURIGI II' },
                { id: 41410, name: 'RWENSHEBASHESHE' },
              ],
            },
            {
              id: 6570,
              name: 'KIHANDA',
              villages: [
                { id: 41378, name: 'ISHUNGA' },
                { id: 41379, name: 'KASHARARA A' },
                { id: 41388, name: 'KASHARARA B' },
                { id: 41380, name: 'KIBEBA' },
                { id: 41381, name: 'KIHANDA CENTRAL' },
                { id: 41382, name: 'KIREBAREBA' },
                { id: 41383, name: 'KIVIGA' },
                { id: 41384, name: 'KYARUKORONGO' },
                { id: 41385, name: 'MISHENYI A' },
                { id: 41389, name: 'MISHENYI B' },
                { id: 41386, name: 'RUTANGA' },
                { id: 41387, name: 'RWENSHEKYE' },
              ],
            },
            {
              id: 6569,
              name: 'KYABAHESI',
              villages: [
                { id: 41366, name: 'BAHIIGI A' },
                { id: 41375, name: 'BAHIIGI B' },
                { id: 41372, name: 'KATAHOOKA' },
                { id: 41374, name: 'KATOJO CENTRAL' },
                { id: 41367, name: 'KATOJO I' },
                { id: 41368, name: 'KATOJO II' },
                { id: 41369, name: 'KAZIIZI A' },
                { id: 41376, name: 'KAZIIZI B' },
                { id: 41370, name: 'KIKOMA' },
                { id: 41371, name: 'KYABAHESI A' },
                { id: 41377, name: 'KYABAHESI B' },
                { id: 41373, name: 'RWABAHINDA' },
              ],
            },
            {
              id: 6572,
              name: 'NSHORORO',
              villages: [
                { id: 41395, name: 'BUJUBWE' },
                { id: 41396, name: 'KAHUNGYE' },
                { id: 41397, name: 'MBARE I' },
                { id: 41398, name: 'MBARE II' },
              ],
            },
            {
              id: 6571,
              name: 'NYAMARUNGI',
              villages: [
                { id: 41391, name: 'BWIZI' },
                { id: 41392, name: 'NYAMARUNGI A' },
                { id: 41393, name: 'NYAMARUNGI B' },
                { id: 41390, name: 'NYAMARUNGI CENTRAL' },
                { id: 41394, name: 'OBUGAAGA' },
              ],
            },
            {
              id: 6573,
              name: 'RUTEETE',
              villages: [
                { id: 41399, name: 'BUBAREBWERA' },
                { id: 41400, name: 'KEMPARA' },
                { id: 41401, name: 'RUTEETE A' },
                { id: 41402, name: 'RUTEETE B' },
                { id: 41404, name: 'RUTEETE C' },
                { id: 41403, name: 'RWENGWE' },
              ],
            },
          ],
        },
        {
          id: 1395,
          name: 'NGARAMA',
          parishes: [
            {
              id: 6558,
              name: 'BURUNGAMO',
              villages: [
                { id: 41258, name: 'BIZEERA' },
                { id: 41259, name: 'KIBENGO I' },
                { id: 41260, name: 'KIBENGO II' },
                { id: 41261, name: 'KYAKABINDI  EAST' },
                { id: 41262, name: 'KYAKABINDI  WEST' },
                { id: 41266, name: 'KYAKABINDI CENTRAL' },
                { id: 41268, name: 'KYAKABINDI NORTH' },
                { id: 41267, name: 'KYAKABINDI SOUTH' },
                { id: 41263, name: 'KYAKAYANDA' },
                { id: 41264, name: 'RWAKABWOHE' },
                { id: 41269, name: 'RWEBINYATSI' },
                { id: 41265, name: 'RWOBUYANGAZA' },
              ],
            },
            {
              id: 6559,
              name: 'KABAARE',
              villages: [
                { id: 41270, name: 'BIHARWE' },
                { id: 41271, name: 'BUSHENYI' },
                { id: 41272, name: 'ISHOZI' },
                { id: 41273, name: 'KABAARE' },
                { id: 41274, name: 'KAMUTINDA' },
                { id: 41275, name: 'KAREREMA' },
                { id: 41277, name: 'KYAJUNGU' },
                { id: 41278, name: 'KYAMBURARA' },
                { id: 41279, name: 'MITOOMA' },
                { id: 41280, name: 'NGANDO' },
                { id: 41276, name: 'RUGANDO' },
              ],
            },
            {
              id: 6561,
              name: 'KAGAAGA',
              villages: [
                { id: 41295, name: 'BUKORE' },
                { id: 41296, name: 'KAGAAGA A' },
                { id: 41297, name: 'KAGAAGA B' },
                { id: 41298, name: 'KATUNGAMO' },
                { id: 41299, name: 'KYANDERA' },
                { id: 41300, name: 'RUMEYA' },
                { id: 41301, name: 'RWENSHEKYE EAST' },
                { id: 41302, name: 'RWENSHEKYE WEST' },
              ],
            },
            {
              id: 6560,
              name: 'NGARAMA',
              villages: [
                { id: 41281, name: 'KAKARAKARE' },
                { id: 41282, name: 'KATYAZO' },
                { id: 41283, name: 'KAYENJE' },
                { id: 41284, name: 'KIGANDO' },
                { id: 41285, name: 'KIGURI' },
                { id: 41286, name: 'KIMURI' },
                { id: 41287, name: 'KISHOJO' },
                { id: 41288, name: 'KYAKASHANA' },
                { id: 41289, name: 'NYANONGO' },
                { id: 41290, name: 'RUGOROGORO' },
                { id: 41291, name: 'RUHIIRA' },
                { id: 41292, name: 'RUKONO' },
                { id: 41293, name: 'RWABAGANGA' },
                { id: 41294, name: 'RWAKABANO' },
              ],
            },
          ],
        },
        {
          id: 1396,
          name: 'RUGAAGA',
          parishes: [
            {
              id: 6567,
              name: 'KABAARE',
              villages: [
                { id: 41350, name: 'KABARE I' },
                { id: 41352, name: 'KABARE II' },
                { id: 41351, name: 'KAFUMBA' },
                { id: 41353, name: 'KAJUMBURA' },
                { id: 41354, name: 'KASHENYI' },
                { id: 41356, name: 'KIKUNYU A' },
                { id: 41357, name: 'KIKUNYU B' },
                { id: 41355, name: 'NYAMIYONGA' },
                { id: 41358, name: 'RUHANGA' },
              ],
            },
            {
              id: 6564,
              name: 'KASHOJWA',
              villages: [
                { id: 41321, name: 'KAROKARUNGI' },
                { id: 41324, name: 'KASHOJWA' },
                { id: 41326, name: 'KASHWINA A' },
                { id: 41322, name: 'KASHWINA B' },
                { id: 41323, name: 'KAZUURA' },
                { id: 41325, name: 'KIRETWA' },
              ],
            },
            {
              id: 6568,
              name: 'KIRYABURO',
              villages: [
                { id: 41360, name: 'BURURUMA I' },
                { id: 41359, name: 'BURURUMA II' },
                { id: 41361, name: 'KABAARE' },
                { id: 41363, name: 'KIRYABURO A' },
                { id: 41365, name: 'KIRYABURO B' },
                { id: 41362, name: 'RWAKINONO' },
                { id: 41364, name: 'RWANKAKIRE' },
              ],
            },
            {
              id: 6562,
              name: 'KYAMPANGO',
              villages: [
                { id: 41305, name: 'KAHEGA' },
                { id: 41306, name: 'KAKIIKA' },
                { id: 41303, name: 'KANIKWA' },
                { id: 41307, name: 'KEIKOBE' },
                { id: 41308, name: 'KYAMPANGO A' },
                { id: 41309, name: 'KYAMPANGO B' },
                { id: 41310, name: 'KYANYANDA' },
                { id: 41304, name: 'NDAYIGA' },
                { id: 41312, name: 'NYAKAZIBA' },
                { id: 41311, name: 'RUGAAGA' },
              ],
            },
            {
              id: 6563,
              name: 'KYARUBAMBURA',
              villages: [
                { id: 41313, name: 'BIRUNDUMA' },
                { id: 41314, name: 'KABUHEMBE' },
                { id: 41315, name: 'KASHAMBYA' },
                { id: 41316, name: 'KATOKYE' },
                { id: 41317, name: 'KITOOMA' },
                { id: 41318, name: 'KYAMUTURA' },
                { id: 41319, name: 'RUKUUBA' },
                { id: 41320, name: 'RWENTURAGARA' },
              ],
            },
            {
              id: 6566,
              name: 'NYABUBAARE',
              villages: [
                { id: 41342, name: 'KASHARE' },
                { id: 41343, name: 'KATUNTU' },
                { id: 41349, name: 'KIGAZI' },
                { id: 41344, name: 'KIJUBWE' },
                { id: 41345, name: 'NYABUBAARE' },
                { id: 41346, name: 'RUTUNGA' },
                { id: 41347, name: 'RWEMBEBA' },
                { id: 41348, name: 'RWENTURAGARA' },
              ],
            },
            {
              id: 6565,
              name: 'RWANGABO',
              villages: [
                { id: 41327, name: 'KAGANDO A' },
                { id: 41339, name: 'KAGANDO B' },
                { id: 41341, name: 'KAHIMA' },
                { id: 41329, name: 'KAITAGURA' },
                { id: 41330, name: 'KATOOMA' },
                { id: 41328, name: 'KEIBARYE' },
                { id: 41331, name: 'KEMENGO' },
                { id: 41332, name: 'KIIJU' },
                { id: 41340, name: 'KYAMUGASHA' },
                { id: 41333, name: 'NTUNGAMO' },
                { id: 41334, name: 'NYARUHUZI A' },
                { id: 41338, name: 'NYARUHUZI B' },
                { id: 41335, name: 'RWANGABO A' },
                { id: 41336, name: 'RWANGABO B' },
                { id: 41337, name: 'RWENDEZI' },
              ],
            },
          ],
        },
        {
          id: 1398,
          name: 'RUSHASHA',
          parishes: [
            {
              id: 6577,
              name: 'IHUNGA',
              villages: [
                { id: 41425, name: 'KENDOBO' },
                { id: 41426, name: 'KINAMI' },
                { id: 41427, name: 'KISUURA' },
                { id: 41424, name: 'KYEMBOGO' },
                { id: 41428, name: 'RUBINGO' },
              ],
            },
            {
              id: 6578,
              name: 'MIRAMBIRO',
              villages: [
                { id: 41432, name: 'KABAHARA' },
                { id: 41429, name: 'KABAZANA' },
                { id: 41430, name: 'KABWERA' },
                { id: 41431, name: 'KASHASHA' },
                { id: 41433, name: 'KIYENJE' },
                { id: 41434, name: 'MISYERA' },
                { id: 41435, name: 'RUHOOKO A' },
                { id: 41436, name: 'RUHOOKO B' },
              ],
            },
            {
              id: 6575,
              name: 'RUSHASHA',
              villages: [
                { id: 41413, name: 'EKIRINDA' },
                { id: 41411, name: 'KAMUTIGANZI' },
                { id: 41412, name: 'KARUNGA' },
                { id: 41414, name: 'NDAYANJOJO' },
                { id: 41415, name: 'NYANGA' },
                { id: 41416, name: 'RUSHASHA' },
              ],
            },
            {
              id: 6576,
              name: 'RWANTAHA',
              villages: [
                { id: 41417, name: 'KYABUZARE' },
                { id: 41418, name: 'NYUNGU' },
                { id: 41419, name: 'RWABARIMIRIZI A' },
                { id: 41420, name: 'RWABARIMIRIZI B' },
                { id: 41421, name: 'RWANTAHA A' },
                { id: 41422, name: 'RWANTAHA B' },
                { id: 41423, name: 'RWANTAHA C' },
              ],
            },
          ],
        },
        {
          id: 1402,
          name: 'RWANJOGYERA',
          parishes: [
            {
              id: 6593,
              name: 'MPIKYE',
              villages: [
                { id: 62072, name: 'KAGARAMA' },
                { id: 41497, name: 'MPIKYE' },
                { id: 41498, name: 'NYANJA' },
                { id: 70122, name: 'RWEKUUBO' },
              ],
            },
            {
              id: 6592,
              name: 'RUKUNGIRI',
              villages: [
                { id: 69944, name: 'RUKUNGIRI A' },
                { id: 69945, name: 'RUKUNGIRI B' },
                { id: 57106, name: 'RWAKAKOORE  C' },
                { id: 41496, name: 'RWAKAKOORE A' },
                { id: 70048, name: 'RWAKAKOORE B' },
              ],
            },
            {
              id: 6594,
              name: 'RUTUNGA',
              villages: [
                { id: 41499, name: 'AKATOOMA A' },
                { id: 57760, name: 'AKATOOMA B' },
                { id: 57765, name: 'AKAYANJA' },
                { id: 41500, name: 'RUTUNGA A' },
                { id: 70012, name: 'RUTUNGA B' },
              ],
            },
            {
              id: 6595,
              name: 'RWAKASASIRA',
              villages: [
                { id: 64626, name: 'KYAMBURARA' },
                { id: 70051, name: 'RWAKASASIRA A' },
                { id: 41502, name: 'RWAKASASIRA B' },
                { id: 41501, name: 'RWANJOGYERA C' },
              ],
            },
            {
              id: 6591,
              name: 'RWANJOGYERA',
              villages: [
                { id: 41491, name: 'KARERABAANA' },
                { id: 41492, name: 'RWAKISHAYAYA A' },
                { id: 70055, name: 'RWAKISHAYAYA B' },
                { id: 41493, name: 'RWANJOGYERA A' },
                { id: 41494, name: 'RWANJOGYERA B' },
                { id: 41495, name: 'RWENKUBA A' },
                { id: 41490, name: 'RWENKUBA B' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 222,
      name: 'ISINGIRO COUNTY NORTH',
      sub_counties: [
        {
          id: 1403,
          name: 'BIRERE',
          parishes: [
            {
              id: 6600,
              name: 'KAHENDA',
              villages: [
                { id: 41531, name: 'KAHENDA I' },
                { id: 41532, name: 'KAHENDA II' },
                { id: 41533, name: 'KITOOHA' },
                { id: 41534, name: 'NDARAGI' },
                { id: 41535, name: 'NSIIKA' },
                { id: 41536, name: 'RUBEYA' },
              ],
            },
            {
              id: 6596,
              name: 'KASAANA',
              villages: [
                { id: 41503, name: 'KASAANA I' },
                { id: 41504, name: 'KASAANA II' },
                { id: 41505, name: 'KIBOONA I' },
                { id: 41506, name: 'KIBOONA II' },
                { id: 41507, name: 'MPAMBAZI' },
                { id: 41508, name: 'NYABUZIBA' },
                { id: 41509, name: 'NYAKIBARE' },
                { id: 41510, name: 'RUGARAMA' },
                { id: 41511, name: 'RUKOMA' },
              ],
            },
            {
              id: 6597,
              name: 'KIKOKWA',
              villages: [
                { id: 41512, name: 'BIRERE' },
                { id: 41513, name: 'KIKOKWA II' },
                { id: 41514, name: 'MIKONOIGANA' },
                { id: 41515, name: 'RWAKIRURI' },
                { id: 41516, name: 'RWEIZIRINGIRO I' },
              ],
            },
            {
              id: 6598,
              name: 'KISHURO',
              villages: [
                { id: 41517, name: 'BUTENGA I' },
                { id: 41518, name: 'BUTENGA II' },
                { id: 41519, name: 'KABAARE I' },
                { id: 41520, name: 'KABAARE II' },
                { id: 41521, name: 'KAMAKISA' },
                { id: 41522, name: 'KISHURO' },
                { id: 41523, name: 'NYABWESHONGOZA' },
              ],
            },
            {
              id: 6599,
              name: 'KYERA',
              villages: [
                { id: 41524, name: 'KASHENYI' },
                { id: 41525, name: 'KITOOMA I' },
                { id: 41526, name: 'KITOOMA II' },
                { id: 41527, name: 'KYERA I' },
                { id: 41528, name: 'KYERA II' },
                { id: 41529, name: 'RWENCWERA I' },
                { id: 41530, name: 'RWENCWERA II' },
              ],
            },
          ],
        },
        {
          id: 1406,
          name: 'ISINGIRO TOWN COUNCIL',
          parishes: [
            {
              id: 6609,
              name: 'KAHARO WARD',
              villages: [
                { id: 41597, name: 'BUSHENGA' },
                { id: 41588, name: 'HUMURA' },
                { id: 41589, name: 'IGAYAZA' },
                { id: 41590, name: 'KABINGO CENTRAL' },
                { id: 41591, name: 'KABINGO II' },
                { id: 41592, name: 'KAHARO' },
                { id: 41593, name: 'KYAMUSYOKA' },
                { id: 41594, name: 'MASHA' },
                { id: 41595, name: 'NYAKISHARARA' },
                { id: 41596, name: 'RYAMIHINI' },
              ],
            },
            {
              id: 6610,
              name: 'KAMURI WARD',
              villages: [
                { id: 41598, name: 'BUHEIGOORE' },
                { id: 41599, name: 'KABARE' },
                { id: 41600, name: 'KIGYENDE' },
                { id: 41606, name: 'KIKUTSI' },
                { id: 41607, name: 'KYARWAMUTAMBARA' },
                { id: 41601, name: 'RUHIMBO' },
                { id: 41602, name: 'RWEMBWA' },
                { id: 41603, name: 'RWENDAMA' },
                { id: 41604, name: 'RWENGIRI' },
                { id: 41605, name: 'RWENTONGORE' },
              ],
            },
            {
              id: 6612,
              name: 'KYABISHAHO WARD',
              villages: [
                { id: 41621, name: 'AKATAFFAARI' },
                { id: 41619, name: 'KACUNUZI' },
                { id: 41620, name: 'KAKINGA' },
                { id: 41623, name: 'KANYERERE' },
                { id: 41626, name: 'KIGANDO' },
                { id: 41622, name: 'KIKOONA' },
                { id: 41624, name: 'KYABISHAHO' },
                { id: 41625, name: 'RUBWEIJANA' },
                { id: 70182, name: 'RWENKUBA' },
              ],
            },
            {
              id: 6611,
              name: 'MABONA WARD',
              villages: [
                { id: 41608, name: 'KIBINGO' },
                { id: 41609, name: 'KIBWERA CENTRAL' },
                { id: 41610, name: 'KIGARAMA' },
                { id: 41612, name: 'KYABIRUKWA' },
                { id: 41613, name: 'KYAMUDIMA' },
                { id: 41611, name: 'KYEIHENDA' },
                { id: 41614, name: 'MABONA' },
                { id: 41615, name: 'MAHWA' },
                { id: 41616, name: 'MAKIRO' },
                { id: 41617, name: 'MBAARE' },
                { id: 41618, name: 'NYAKABANGA' },
              ],
            },
            {
              id: 6613,
              name: 'RWEKUBO WARD',
              villages: [
                { id: 41634, name: 'ISHOOZI' },
                { id: 41629, name: 'KAHIRIMBI' },
                { id: 41630, name: 'KAJURUNGUTSI' },
                { id: 41635, name: 'KAKUNYU' },
                { id: 41633, name: 'KATWENGYE' },
                { id: 41632, name: 'KAYONZA' },
                { id: 41628, name: 'KAYONZA CENTRAL' },
                { id: 41631, name: 'KYAKASHANA' },
                { id: 41627, name: 'MISIRIRA' },
                { id: 70121, name: 'RWEKUUBO' },
              ],
            },
          ],
        },
        {
          id: 1408,
          name: 'KABEREBERE TOWN COUNCIL',
          parishes: [
            {
              id: 6618,
              name: 'KABEREBERE EAST WARD',
              villages: [
                { id: 41661, name: 'KABEREBERE I' },
                { id: 41662, name: 'KYENYANGI' },
                { id: 41663, name: 'RWEIZIRINGIRO II' },
              ],
            },
            {
              id: 6619,
              name: 'KABEREBERE SOUTH WARD',
              villages: [
                { id: 41664, name: 'KABEREBERE II' },
                { id: 41665, name: 'KYABUTOOTO' },
                { id: 41666, name: 'RUTSYA' },
              ],
            },
            {
              id: 6620,
              name: 'KABEREBERE WEST WARD',
              villages: [
                { id: 41667, name: 'AKATEETE' },
                { id: 41668, name: 'KABIRIZI' },
                { id: 41669, name: 'KIKOKWA I' },
              ],
            },
          ],
        },
        {
          id: 1404,
          name: 'KABINGO',
          parishes: [
            {
              id: 9269,
              name: 'BITOOMA',
              villages: [
                { id: 59129, name: 'BITOOMA' },
                { id: 62406, name: 'KAMANZI' },
                { id: 63556, name: 'KIHOGO' },
                { id: 66250, name: 'MIGYENDWA' },
                { id: 66450, name: 'MPORORO' },
                { id: 70030, name: 'RWABASHANDURA' },
              ],
            },
            {
              id: 9542,
              name: 'KAGOGO',
              villages: [
                { id: 62092, name: 'KAGOGO' },
                { id: 62407, name: 'KAMAREMBE' },
                { id: 63280, name: 'KEMINYA' },
                { id: 64521, name: 'KYABWEMI' },
                { id: 64705, name: 'KYARUGAMBA' },
                { id: 68010, name: 'NYAKAGYERA' },
                { id: 68012, name: 'NYAKAGYERA EAST' },
                { id: 68045, name: 'NYAKASERA' },
                { id: 69915, name: 'RUGYEYA' },
              ],
            },
            {
              id: 6601,
              name: 'KATEMBE',
              villages: [
                { id: 41537, name: 'BWEZA' },
                { id: 41538, name: 'KATARAKA' },
                { id: 41539, name: 'KATEMBE' },
                { id: 41540, name: 'KATEMBE CENTRAL' },
                { id: 41541, name: 'NYABUBARE' },
              ],
            },
            {
              id: 6602,
              name: 'KYARUGAAJU',
              villages: [
                { id: 41546, name: 'KABIRA' },
                { id: 41542, name: 'KACOMBEKA' },
                { id: 41543, name: 'KAGAMBA' },
                { id: 41544, name: 'KAGOGO' },
                { id: 41545, name: 'KAYONZA' },
                { id: 41548, name: 'KIYORA' },
                { id: 41547, name: 'KYARUGAJU' },
                { id: 41549, name: 'RUBIRA' },
                { id: 41550, name: 'RWAMUVUGA' },
              ],
            },
            {
              id: 6603,
              name: 'KYEIRUMBA',
              villages: [
                { id: 41551, name: 'BYARUHA I' },
                { id: 41552, name: 'BYARUHA II' },
                { id: 41553, name: 'KABAGABE' },
                { id: 41554, name: 'KYEMPARA II' },
                { id: 41555, name: 'NYABUGANDO' },
                { id: 41556, name: 'RUGARA' },
              ],
            },
          ],
        },
        {
          id: 1995,
          name: 'KAGARAMA',
          parishes: [
            {
              id: 9538,
              name: 'KAGARAMA',
              villages: [
                { id: 58095, name: 'AMAKUKURU' },
                { id: 60315, name: 'BUSHARA' },
                { id: 62069, name: 'KAGARAMA' },
                { id: 63264, name: 'KEITABIKYERE' },
                { id: 63429, name: 'KICWEKANO' },
                { id: 66506, name: 'MUHUNGA' },
                { id: 69893, name: 'RUGAARA' },
                { id: 70052, name: 'RWAKASHAKA' },
              ],
            },
            {
              id: 9772,
              name: 'KITURA',
              villages: [
                { id: 61914, name: 'KABIBI A' },
                { id: 61915, name: 'KABIBI B' },
                { id: 64111, name: 'KITURA A' },
                { id: 64112, name: 'KITURA B' },
                { id: 64113, name: 'KITURA CENTRAL' },
                { id: 70082, name: 'RWAMURUGA' },
              ],
            },
            {
              id: 9810,
              name: 'KYABINUNGA',
              villages: [
                { id: 60180, name: 'BUNGURA A' },
                { id: 60181, name: 'BUNGURA B' },
                { id: 62463, name: 'KAMUHEMBE' },
                { id: 64503, name: 'KYABINUNGA A' },
                { id: 64504, name: 'KYABINUNGA B' },
                { id: 64505, name: 'KYABINUNGA TRADING CENTRE' },
                { id: 66172, name: 'MBAARE' },
                { id: 66173, name: 'MBAARE B' },
                { id: 69939, name: 'RUKONO' },
                { id: 70097, name: 'RWANYAKIHANGA' },
              ],
            },
            {
              id: 10122,
              name: 'NYAKIGYERA',
              villages: [
                { id: 60226, name: 'BURARA I' },
                { id: 60227, name: 'BURARA II' },
                { id: 60758, name: 'BWANGA I' },
                { id: 60759, name: 'BWANGA II' },
                { id: 64761, name: 'KYEBIKARA' },
                { id: 64794, name: 'KYEMPARA I' },
                { id: 67988, name: 'NYAKABUNGO' },
                { id: 68096, name: 'NYAKIBARE' },
                { id: 69892, name: 'RUGAAGA' },
                { id: 69980, name: 'RUSHAYO' },
              ],
            },
          ],
        },
        {
          id: 1405,
          name: 'MASHA',
          parishes: [
            {
              id: 6604,
              name: 'KABAARE',
              villages: [
                { id: 41557, name: 'KABAARE I' },
                { id: 41558, name: 'KABAARE II' },
                { id: 41559, name: 'KABAARE III' },
                { id: 41560, name: 'KABAARE IV' },
                { id: 41561, name: 'KABAARE V' },
                { id: 41562, name: 'KABAARE VI' },
                { id: 41563, name: 'KABAARE VII' },
              ],
            },
            {
              id: 6608,
              name: 'NYAKAKONI',
              villages: [
                { id: 41581, name: 'MASHA' },
                { id: 41582, name: 'NYAKAKONI A' },
                { id: 41583, name: 'NYAKAKONI B' },
                { id: 41584, name: 'NYAKAKONI C' },
                { id: 41585, name: 'NYAKASHARARA' },
                { id: 41586, name: 'OMUKABAARE' },
                { id: 41587, name: 'RWEMBOGO' },
              ],
            },
            {
              id: 6605,
              name: 'NYAMITSINDO',
              villages: [
                { id: 41564, name: 'BUYOJWA I' },
                { id: 41566, name: 'BUYOJWA II' },
                { id: 41565, name: 'KAKYEKA' },
                { id: 41567, name: 'NYABUSHOZI' },
                { id: 41568, name: 'NYAMITANGA' },
              ],
            },
            {
              id: 6607,
              name: 'NYARUBUNGO',
              villages: [
                { id: 41578, name: 'AKABARE' },
                { id: 41573, name: 'AKAFUNDA' },
                { id: 41574, name: 'IGYEREKA' },
                { id: 41575, name: 'KATEREERA' },
                { id: 68046, name: 'NYAKASHARARA' },
                { id: 41576, name: 'NYARUBUNGO I' },
                { id: 41577, name: 'NYARUBUNGO II' },
                { id: 41579, name: 'RUYONZA' },
                { id: 41580, name: 'RWENGANDO' },
              ],
            },
            {
              id: 6606,
              name: 'RUKUUBA',
              villages: [
                { id: 41569, name: 'KAKUTO A' },
                { id: 41570, name: 'KAKUTO B' },
                { id: 41571, name: 'NYAMABARE' },
                { id: 41572, name: 'RUKUUBA' },
              ],
            },
            {
              id: 10272,
              name: 'RUMURI',
              villages: [
                { id: 68178, name: 'NYAMITSINDO' },
                { id: 69952, name: 'RUMURI' },
                { id: 70046, name: 'RWAKAHUNDE I' },
                { id: 70047, name: 'RWAKAHUNDE II' },
              ],
            },
            {
              id: 10291,
              name: 'RWENSHEBASHEBE',
              villages: [
                { id: 57704, name: 'AKAFUNDA' },
                { id: 64144, name: 'KIYENJE' },
                { id: 68989, name: 'OMUKABARE' },
                { id: 70161, name: 'RWENDEZI' },
                { id: 70195, name: 'RWENSHEBASHEBE' },
              ],
            },
          ],
        },
        {
          id: 1407,
          name: 'NYAMUYANJA',
          parishes: [
            {
              id: 6616,
              name: 'IBUMBA',
              villages: [
                { id: 41650, name: 'IBUMBA' },
                { id: 41651, name: 'IJUGANGOMA' },
                { id: 41652, name: 'KAMUTUMO' },
                { id: 41653, name: 'KAYONZA' },
                { id: 41654, name: 'KYAKAZOOBA' },
                { id: 41655, name: 'KYANZA' },
              ],
            },
            {
              id: 6617,
              name: 'KATANOGA',
              villages: [
                { id: 41656, name: 'BUHARWE' },
                { id: 41657, name: 'KATANOGA' },
                { id: 41658, name: 'RUHAMA' },
                { id: 41659, name: 'RUYONZA' },
                { id: 41660, name: 'RWANYINEKIHANDA' },
              ],
            },
            {
              id: 6615,
              name: 'KIGYENDWA',
              villages: [
                { id: 41645, name: 'KIGYENDWA' },
                { id: 41646, name: 'KISHURO' },
                { id: 41647, name: 'RUGARAMA' },
                { id: 41648, name: 'RWAKANYONYI' },
                { id: 41649, name: 'RWEKITOOMA' },
              ],
            },
            {
              id: 6614,
              name: 'NYAMUYANJA',
              villages: [
                { id: 41636, name: 'KARUTANGA' },
                { id: 41637, name: 'KIIHWA' },
                { id: 41638, name: 'NYAKIBARE I' },
                { id: 41639, name: 'NYAKIBARE II' },
                { id: 41640, name: 'NYAKISHENSHERO' },
                { id: 41641, name: 'NYARWASHAMA' },
                { id: 41642, name: 'RWAKANYONYI' },
                { id: 41643, name: 'RWENKUBA' },
                { id: 41644, name: 'TWAMAGONDO' },
              ],
            },
          ],
        },
        {
          id: 2115,
          name: 'RWETANGO',
          parishes: [
            {
              id: 10287,
              name: 'RWENFUNJO',
              villages: [
                { id: 61584, name: 'IHUNGA' },
                { id: 64806, name: 'KYENJOJO' },
                { id: 70013, name: 'RUTUNGU' },
                { id: 70162, name: 'RWENFUNJO' },
              ],
            },
            {
              id: 10294,
              name: 'RWENYANGA',
              villages: [
                { id: 64781, name: 'KYEKYAKIRE' },
                { id: 68016, name: 'NYAKAHITA' },
                { id: 70213, name: 'RWENYANGA I' },
                { id: 70214, name: 'RWENYANGA II' },
              ],
            },
            {
              id: 10295,
              name: 'RWETANGO',
              villages: [
                { id: 64548, name: 'KYAKAMIHANDA' },
                { id: 64645, name: 'KYAMUGURUMA' },
                { id: 64730, name: 'KYARWANSHASHURA' },
                { id: 70127, name: 'RWEMBIRIZI' },
                { id: 70233, name: 'RWETANGO A' },
                { id: 70234, name: 'RWETANGO B' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 223,
      name: 'ISINGIRO COUNTY SOUTH',
      sub_counties: [
        {
          id: 1409,
          name: 'KABUYANDA',
          parishes: [
            {
              id: 6622,
              name: 'KABUGU',
              villages: [
                { id: 41679, name: 'EKISINGA' },
                { id: 41680, name: 'KABESHEKYERE' },
                { id: 41681, name: 'KABUGU I' },
                { id: 41682, name: 'KABUGU II' },
                { id: 41683, name: 'KIGABAGABA I' },
                { id: 41684, name: 'KIGABAGABA II' },
                { id: 41685, name: 'MISHOROSHOZI' },
                { id: 41686, name: 'PARAGONI' },
                { id: 41688, name: 'RWEMANGO' },
                { id: 41687, name: 'RWENDONGO' },
              ],
            },
            {
              id: 6624,
              name: 'KAGARA',
              villages: [
                { id: 41699, name: 'BWENGYERERE' },
                { id: 41700, name: 'KAGARA I' },
                { id: 41701, name: 'KAGARA II' },
                { id: 41702, name: 'KYAMAZINGA I' },
                { id: 41703, name: 'KYAMAZINGA II' },
                { id: 41704, name: 'RUBAGANO' },
              ],
            },
            {
              id: 6621,
              name: 'KANYWAMAIZI',
              villages: [
                { id: 41670, name: 'KAGOTO I' },
                { id: 41671, name: 'KAGOTO II' },
                { id: 41672, name: 'KANYWAMAIZI  II' },
                { id: 41673, name: 'KANYWAMAIZI  III' },
                { id: 41674, name: 'KANYWAMAIZI  IV' },
                { id: 41675, name: 'KANYWAMAIZI I' },
                { id: 41676, name: 'MUHANGA' },
                { id: 41677, name: 'NYAMIYAGA' },
                { id: 41678, name: 'RWABYEMERA' },
              ],
            },
            {
              id: 6623,
              name: 'RWAKAKWENDA',
              villages: [
                { id: 41698, name: 'AKATOOMA' },
                { id: 41689, name: 'BUTERANIRO' },
                { id: 41690, name: 'ITAARE' },
                { id: 41691, name: 'KARWENYI' },
                { id: 41695, name: 'KASHARIRA' },
                { id: 41693, name: 'KATOOMA' },
                { id: 41694, name: 'NYARUHANGA' },
                { id: 41692, name: 'RUKIIRI' },
                { id: 41696, name: 'RUTOOMA' },
                { id: 41697, name: 'RWAKAKWENDA' },
              ],
            },
          ],
        },
        {
          id: 1413,
          name: 'KABUYANDA TOWN COUNCIL',
          parishes: [
            {
              id: 6639,
              name: 'CENTRAL WARD',
              villages: [
                { id: 41817, name: 'AKATENSANI' },
                { id: 41819, name: 'KAARO I' },
                { id: 41820, name: 'KAARO III' },
                { id: 41823, name: 'KABUYANDA' },
                { id: 41821, name: 'KABUYANDA T/C' },
                { id: 41818, name: 'KABUYANDA TOWN CELL' },
                { id: 41822, name: 'RUTOOMA' },
              ],
            },
            {
              id: 6638,
              name: 'IRYANGO WARD',
              villages: [
                { id: 41811, name: 'IRYANGO' },
                { id: 41812, name: 'KASHAKA' },
                { id: 41810, name: 'KIGARAMA' },
                { id: 41813, name: 'KINYARA I' },
                { id: 41815, name: 'KINYARA II' },
                { id: 41816, name: 'NYAMPIKYE I' },
                { id: 41814, name: 'RYABOONA' },
              ],
            },
            {
              id: 6637,
              name: 'KISYORO WARD',
              villages: [
                { id: 41804, name: 'AKATEMBO' },
                { id: 41805, name: 'BUGARAMA II' },
                { id: 41806, name: 'KISYORO II' },
                { id: 41807, name: 'NDAANI' },
                { id: 41809, name: 'NYAMPIKYE II' },
                { id: 41808, name: 'RWEMBWERA II' },
              ],
            },
            {
              id: 6640,
              name: 'NORTHERN WARD',
              villages: [
                { id: 41824, name: 'BUGARAMA I' },
                { id: 41825, name: 'KAARO II' },
                { id: 41826, name: 'KISYORO I' },
                { id: 41827, name: 'KISYORO III' },
                { id: 41828, name: 'RWEMBWERA I' },
              ],
            },
          ],
        },
        {
          id: 1418,
          name: 'KAMUBEIZI',
          parishes: [
            {
              id: 6660,
              name: 'KABESHEKYERE',
              villages: [
                { id: 41908, name: 'KABESHEKYERE' },
                { id: 41909, name: 'KAGARAMA' },
                { id: 41911, name: 'KANANI' },
                { id: 62771, name: 'KARAMA' },
                { id: 41910, name: 'KATOJO' },
                { id: 41912, name: 'KATUKUNDANE' },
                { id: 64786, name: 'KYEMBOGO' },
                { id: 70040, name: 'RWACECE' },
                { id: 70153, name: 'RWEMITARATE' },
              ],
            },
            {
              id: 6658,
              name: 'KAMUBEIZI',
              villages: [
                { id: 61964, name: 'KABUMBA' },
                { id: 41902, name: 'KAGORORA' },
                { id: 62450, name: 'KAMUBEIZI' },
                { id: 62451, name: 'KAMUBEIZI TRADING CENTRE' },
                { id: 41897, name: 'KASHARIRA' },
                { id: 41898, name: 'KIBUBA' },
                { id: 41899, name: 'KIFUMBIRA' },
                { id: 41900, name: 'NYAMIRAMA' },
                { id: 41901, name: 'RUSHOROZA' },
              ],
            },
            {
              id: 6659,
              name: 'KYARUGOZA',
              villages: [
                { id: 41903, name: 'KARO - KARUNGI' },
                { id: 41904, name: 'KASHAKI' },
                { id: 41907, name: 'KASHENYI' },
                { id: 63642, name: 'KIKINGA' },
                { id: 41905, name: 'KYARUGONZA I' },
                { id: 64706, name: 'KYARUGONZA II' },
                { id: 67995, name: 'NYAKABUNGO' },
                { id: 68173, name: 'NYAMITEETE' },
                { id: 41906, name: 'NYAMIYAGA' },
              ],
            },
          ],
        },
        {
          id: 1415,
          name: 'KAMUBEIZI TOWN COUNCIL',
          parishes: [
            {
              id: 6646,
              name: 'BURAMBIRA WARD',
              villages: [
                { id: 41856, name: 'BURAMBIRA' },
                { id: 63052, name: 'KATEETE' },
                { id: 41857, name: 'MIRAMA' },
                { id: 41858, name: 'NYABUGANDO' },
                { id: 41859, name: 'NYAKAMURI I' },
                { id: 68026, name: 'NYAKAMURI II' },
              ],
            },
            {
              id: 6645,
              name: 'KAMUBEIZI WARD',
              villages: [
                { id: 41854, name: 'KAMUBEIZI' },
                { id: 62949, name: 'KASHENYI' },
                { id: 62952, name: 'KASHOGASHOGA' },
                { id: 67712, name: 'NFANSHA' },
                { id: 68072, name: 'NYAKATOJO' },
                { id: 41855, name: 'NYAMWERAMBIKO' },
                { id: 68254, name: 'NYARUHANGA' },
              ],
            },
            {
              id: 6647,
              name: 'KATANZI WARD',
              villages: [
                { id: 62938, name: 'KASHARIRA' },
                { id: 41860, name: 'KATANZI' },
                { id: 66272, name: 'MINAZI' },
                { id: 41861, name: 'NYAKABUNGO' },
                { id: 70221, name: 'RWENZAZA' },
              ],
            },
            {
              id: 6648,
              name: 'KIBAALE WARD',
              villages: [
                { id: 41862, name: 'KANYINYA' },
                { id: 41863, name: 'KAROKARUNGI' },
                { id: 62953, name: 'KASHOJWA' },
                { id: 41864, name: 'KIBAARE' },
                { id: 41865, name: 'RUGARAMA' },
              ],
            },
            {
              id: 6649,
              name: 'KISHARIRA WARD',
              villages: [
                { id: 63914, name: 'KISHARIRA' },
                { id: 64085, name: 'KITOOKO' },
                { id: 41867, name: 'NYAKAGYERA' },
                { id: 41866, name: 'NYAKIGYERA' },
                { id: 41868, name: 'RUSHARIRA' },
                { id: 41869, name: 'RWENANURA' },
              ],
            },
          ],
        },
        {
          id: 1410,
          name: 'KIKAGATE',
          parishes: [
            {
              id: 6625,
              name: 'KYEZIMBIRE',
              villages: [
                { id: 41705, name: 'ENONKO' },
                { id: 41706, name: 'KEIZIBATE' },
                { id: 63915, name: 'KISHARIRA' },
                { id: 41707, name: 'KYAMUSHAIJA' },
                { id: 41708, name: 'KYEMPITSI' },
                { id: 41709, name: 'RWAKIJUMA' },
              ],
            },
            {
              id: 6626,
              name: 'NTUNDU',
              villages: [
                { id: 59083, name: 'BIKURUNGU' },
                { id: 41711, name: 'KABUMBA' },
                { id: 41712, name: 'KAGUNGA' },
                { id: 41714, name: 'MBARARA II' },
                { id: 66187, name: 'MBARARA III' },
                { id: 41713, name: 'NYEIHITA' },
                { id: 41710, name: 'RUJUBUKA' },
                { id: 41715, name: 'RUTARE' },
              ],
            },
            {
              id: 6628,
              name: 'NYABUSHENYI',
              villages: [
                { id: 41723, name: 'KIRUHURA' },
                { id: 41724, name: 'KYIGARAMA' },
                { id: 41725, name: 'MURAZAGYE' },
                { id: 41729, name: 'NYABUSHENYI CELL' },
                { id: 41727, name: 'NYABUSHENYI CENTRAL' },
                { id: 41726, name: 'NYABUSHENYI I' },
                { id: 41728, name: 'NYAMWERAMBIKO' },
                { id: 41730, name: 'NYARUBUNGO' },
              ],
            },
            {
              id: 6627,
              name: 'RWAMWIJUKA',
              villages: [
                { id: 41716, name: 'BUBAARE' },
                { id: 41717, name: 'KABURARA' },
                { id: 41718, name: 'KAMWOSYA' },
                { id: 41719, name: 'KASHARIRA' },
                { id: 63475, name: 'KIGANDO' },
                { id: 41722, name: 'RUYONZA' },
                { id: 41720, name: 'RWAMWIJUKA' },
                { id: 41721, name: 'RWEMIZO' },
              ],
            },
          ],
        },
        {
          id: 1416,
          name: 'KIKAGATE TOWN COUNCIL',
          parishes: [
            {
              id: 6651,
              name: 'KATANGA WARD',
              villages: [
                { id: 62086, name: 'KAGERA' },
                { id: 41872, name: 'KATANGA' },
                { id: 63042, name: 'KATANGA EAST' },
                { id: 41873, name: 'KATANGA WEST' },
                { id: 41874, name: 'KYEZIMBIRE' },
              ],
            },
            {
              id: 6652,
              name: 'KIKAGATE BOARDER WARD',
              villages: [
                { id: 60843, name: 'CASKET' },
                { id: 41875, name: 'KIKAGATE BOARDER CELL' },
                { id: 69942, name: 'RUKUMBYA' },
                { id: 70072, name: 'RWAMPARA' },
              ],
            },
            {
              id: 6650,
              name: 'KIKAGATE WARD',
              villages: [
                { id: 61700, name: 'ITAMA' },
                { id: 67867, name: 'NTUNDU' },
                { id: 67908, name: 'NYABIRUNGI' },
                { id: 41870, name: 'NYAKAYOJO' },
                { id: 41871, name: 'RWENKUBA' },
              ],
            },
            {
              id: 6653,
              name: 'KITEZO WARD',
              villages: [
                { id: 41876, name: 'BWENTARE' },
                { id: 63492, name: 'KIGARAMA' },
                { id: 41877, name: 'KITEZO I' },
                { id: 64043, name: 'KITEZO II' },
                { id: 66204, name: 'MBURAMAIZI' },
                { id: 41878, name: 'NYARUBUNGO' },
              ],
            },
          ],
        },
        {
          id: 1417,
          name: 'NTUNGU',
          parishes: [
            {
              id: 6655,
              name: 'ISHINGISHA',
              villages: [
                { id: 41884, name: 'ISHINGISHA I' },
                { id: 61679, name: 'ISHINGISHA II' },
                { id: 41886, name: 'KEINA I' },
                { id: 41885, name: 'KEINA II' },
                { id: 41883, name: 'KYAKAGABO' },
                { id: 41889, name: 'KYANDARO' },
                { id: 41890, name: 'NYAKAHANDAGAZI' },
                { id: 41887, name: 'OMUKIKIZI' },
                { id: 41888, name: 'RWENJOJO' },
              ],
            },
            {
              id: 6656,
              name: 'KIMBUGU',
              villages: [
                { id: 60316, name: 'BUSHEEKA' },
                { id: 63711, name: 'KIMBUGU' },
                { id: 41891, name: 'MAHAAMA' },
                { id: 69003, name: 'OMUKITOOMA' },
                { id: 70031, name: 'RWABATEGA' },
              ],
            },
            {
              id: 6654,
              name: 'NTUNGU',
              villages: [
                { id: 63103, name: 'KATIMBA' },
                { id: 41879, name: 'KITOJO' },
                { id: 41880, name: 'MAJU' },
                { id: 41881, name: 'NTUNGU CENTRAL' },
                { id: 41882, name: 'NTUNGU TRADING CENTRE' },
                { id: 68997, name: 'OMUKATOOMA' },
                { id: 70134, name: 'RWEMICENCE' },
              ],
            },
            {
              id: 6657,
              name: 'OMUKAKOREIJO',
              villages: [
                { id: 59108, name: 'BIRARA' },
                { id: 59853, name: 'BUMOMA' },
                { id: 60220, name: 'BURAMBIRA' },
                { id: 62934, name: 'KASHARARA I' },
                { id: 62935, name: 'KASHARARA II' },
                { id: 41892, name: 'KYANYAKAHIMBI I' },
                { id: 41893, name: 'KYANYAKAHIMBI II' },
                { id: 41894, name: 'NTUNGU WEST' },
                { id: 68987, name: 'OMUKABAATI' },
                { id: 41896, name: 'OMURWERERE' },
                { id: 41895, name: 'RUGOROGORO' },
              ],
            },
          ],
        },
        {
          id: 1411,
          name: 'NYAKITUNDA',
          parishes: [
            {
              id: 6630,
              name: 'BUGONGI',
              villages: [
                { id: 41748, name: 'BUGONGI I' },
                { id: 41749, name: 'BUGONGI II' },
                { id: 41750, name: 'KAMIRANJOGYERA I' },
                { id: 41751, name: 'KAMIRANJOGYERA II' },
                { id: 41762, name: 'KYEFURWE' },
                { id: 41752, name: 'NYARUHANGA' },
                { id: 41753, name: 'NYARUSHANJE' },
                { id: 41754, name: 'OMUKABALE' },
                { id: 41755, name: 'OMUKANARA' },
                { id: 41761, name: 'OMUKIHANGIRE' },
                { id: 41756, name: 'OMUKIHIMBA' },
                { id: 41757, name: 'OMUKINAZI' },
                { id: 69001, name: 'OMUKINAZI II' },
                { id: 41758, name: 'RWANYINAMAGANGURE I' },
                { id: 41760, name: 'RWANYINAMAGANGURE II' },
                { id: 41759, name: 'TOWN CELL' },
              ],
            },
            {
              id: 6629,
              name: 'KIHIIHI',
              villages: [
                { id: 41731, name: 'KEINA' },
                { id: 41732, name: 'KIHIIHI CENTRAL' },
                { id: 41733, name: 'KIHIIHI I' },
                { id: 41734, name: 'KIHIIHI II' },
                { id: 63551, name: 'KIHIIHI TOWN' },
                { id: 41735, name: 'KITURO' },
                { id: 41736, name: 'KYAAYA' },
                { id: 41737, name: 'MBARE' },
                { id: 41746, name: 'MIRAMBIRO' },
                { id: 41743, name: 'NYAKABUNGO' },
                { id: 41738, name: 'NYANDAMA' },
                { id: 41739, name: 'NYANJA-ETAGYERA I' },
                { id: 41740, name: 'NYANJA-ETAGYERA II' },
                { id: 41741, name: 'NYANJA-ETAGYERA III' },
                { id: 41742, name: 'RWEKISHOJWA I' },
                { id: 41745, name: 'RWEKISHOJWA II' },
                { id: 41747, name: 'RWEMBOGO' },
                { id: 41744, name: 'RWEMONDO' },
              ],
            },
            {
              id: 6631,
              name: 'NYAKARAMBI',
              villages: [
                { id: 41763, name: 'KABUGU' },
                { id: 41773, name: 'KEITANYONYI' },
                { id: 41764, name: 'MBURAMAIZI' },
                { id: 41774, name: 'NYAKABUNGO' },
                { id: 41765, name: 'NYAKARAMBI I' },
                { id: 41766, name: 'NYAKARAMBI II' },
                { id: 41767, name: 'NYANGOROGORO' },
                { id: 41768, name: 'OMUBUSHAMI' },
                { id: 41769, name: 'OMUKINIIKA I' },
                { id: 69002, name: 'OMUKINIKA II' },
                { id: 41770, name: 'OMUNONKO' },
                { id: 41771, name: 'OMURUTOOMA' },
                { id: 41772, name: 'RUGAZI' },
              ],
            },
          ],
        },
        {
          id: 1412,
          name: 'RUBOROGOTA',
          parishes: [
            {
              id: 6633,
              name: 'KARAMA',
              villages: [
                { id: 41782, name: 'IBINJA I' },
                { id: 41783, name: 'KAGARAMA' },
                { id: 41784, name: 'KARAMA I' },
                { id: 41785, name: 'KARAMA II' },
                { id: 41786, name: 'KIBINGO I' },
                { id: 41787, name: 'KIBINGO II' },
                { id: 41788, name: 'KIGANDO' },
              ],
            },
            {
              id: 6632,
              name: 'KYAMUSONI',
              villages: [
                { id: 41775, name: 'KABUMBA' },
                { id: 41776, name: 'KAGANDO' },
                { id: 41777, name: 'KAHAMA' },
                { id: 41778, name: 'KIHIHI' },
                { id: 41779, name: 'KYAMUSONI' },
                { id: 41780, name: 'RUKUREIJO' },
                { id: 41781, name: 'RUZINGA' },
              ],
            },
            {
              id: 6636,
              name: 'NSHENYI',
              villages: [
                { id: 41800, name: 'BUGARIKA' },
                { id: 41801, name: 'KAGERA' },
                { id: 41803, name: 'NSHENYI' },
                { id: 41802, name: 'NYABUGANDO' },
              ],
            },
            {
              id: 6634,
              name: 'RUBOROGOTA',
              villages: [
                { id: 41789, name: 'KABATANGARE' },
                { id: 41790, name: 'KIBABO' },
                { id: 41791, name: 'MPOMA I' },
                { id: 41792, name: 'MPOMA II' },
                { id: 41793, name: 'RUBOROGOTA  I' },
              ],
            },
            {
              id: 6635,
              name: 'RWANGUNGA',
              villages: [
                { id: 41794, name: 'BIBUNGO' },
                { id: 41795, name: 'IBINJA II' },
                { id: 41797, name: 'KAGABAGABA' },
                { id: 41798, name: 'KAHORORO' },
                { id: 41796, name: 'KATUNGURU' },
                { id: 41799, name: 'RWANGUNGA' },
              ],
            },
          ],
        },
        {
          id: 1414,
          name: 'RUHIIRA TOWN COUNCIL',
          parishes: [
            {
              id: 6643,
              name: 'MIGYERA WARD',
              villages: [
                { id: 41842, name: 'KAGONGI I' },
                { id: 41841, name: 'KAGONGI II' },
                { id: 62238, name: 'KAKONI' },
                { id: 41843, name: 'MIGYERA CENTRAL' },
                { id: 41845, name: 'MIGYERA I' },
                { id: 41846, name: 'MIGYERA II' },
                { id: 41847, name: 'RWAKIBEZI I' },
                { id: 41844, name: 'RWAKIBEZI II' },
              ],
            },
            {
              id: 6642,
              name: 'NYAKAMURI WARD',
              villages: [
                { id: 41835, name: 'KARUNDI I' },
                { id: 41836, name: 'KARUNDI II' },
                { id: 41837, name: 'NYAKAMURI I' },
                { id: 41838, name: 'NYAKAMURI II' },
                { id: 68027, name: 'NYAKAMURI III' },
                { id: 41839, name: 'RUGONGI I' },
                { id: 41840, name: 'RUGONGI II' },
              ],
            },
            {
              id: 6644,
              name: 'RUHIIRA NORTHERN WARD',
              villages: [
                { id: 41852, name: 'KANYERERE' },
                { id: 41848, name: 'KISHENYI I' },
                { id: 41850, name: 'KISHENYI II' },
                { id: 41853, name: 'NGOMA CELL' },
                { id: 41849, name: 'OMWICWAMBA' },
                { id: 41851, name: 'TOWN CELL' },
              ],
            },
            {
              id: 6641,
              name: 'RUHIRA CENTRAL WARD',
              villages: [
                { id: 41829, name: 'KABARE I' },
                { id: 41832, name: 'KABARE II' },
                { id: 41831, name: 'KAHURWA I' },
                { id: 41833, name: 'KAHURWA II' },
                { id: 41830, name: 'RUHIIRA II' },
                { id: 41834, name: 'RUHIRA I' },
              ],
            },
          ],
        },
        {
          id: 1419,
          name: 'RUYANGA',
          parishes: [
            {
              id: 6661,
              name: 'KAJAHO',
              villages: [
                { id: 62164, name: 'KAJAHO CELL' },
                { id: 41914, name: 'KAJAHO CENTRAL' },
                { id: 63549, name: 'KIHENDA' },
                { id: 64729, name: 'KYARWANKAMBURA' },
                { id: 41913, name: 'RWAMURUNGA' },
                { id: 41915, name: 'RWANGYENYA' },
              ],
            },
            {
              id: 6663,
              name: 'KATOJO',
              villages: [
                { id: 41921, name: 'KATOJO I' },
                { id: 63114, name: 'KATOJO II' },
                { id: 63481, name: 'KIGANDO I' },
                { id: 41920, name: 'KIGANDO II' },
                { id: 41922, name: 'RUNONI' },
                { id: 70018, name: 'RUYONZA' },
              ],
            },
            {
              id: 6664,
              name: 'NSHUNGEZI',
              villages: [
                { id: 41923, name: 'BUSHEKA' },
                { id: 62126, name: 'KAGYERA' },
                { id: 64539, name: 'KYAKAIJUKA' },
                { id: 41924, name: 'RUBIRIZI I' },
                { id: 69879, name: 'RUBIRIZI II' },
              ],
            },
            {
              id: 6665,
              name: 'RUTOOMA',
              villages: [
                { id: 59067, name: 'BIHIRI CENTRAL' },
                { id: 63246, name: 'KAYUNGWE' },
                { id: 63733, name: 'KINAGA' },
                { id: 41926, name: 'OBUNAZI' },
                { id: 41925, name: 'RUTOOMA A' },
                { id: 70008, name: 'RUTOOMA B' },
                { id: 70009, name: 'RUTOOMA C' },
              ],
            },
            {
              id: 6662,
              name: 'RUYANGA',
              villages: [
                { id: 41918, name: 'BURAMBIRA' },
                { id: 41916, name: 'KASHARIRA' },
                { id: 41917, name: 'KIHANDE' },
                { id: 64772, name: 'KYEHUNA I' },
                { id: 64773, name: 'KYEHUNA II' },
                { id: 41919, name: 'RUYANGA' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
