import { District } from '../types';

export default <District>{
  id: 9,
  name: 'KABALE',
  counties: [
    {
      id: 29,
      name: 'KABALE MUNICIPALITY',
      sub_counties: [
        {
          id: 143,
          name: 'KABALE CENTRAL',
          parishes: [
            {
              id: 693,
              name: 'BUTOBERE',
              villages: [
                { id: 4752, name: 'BUTOBERE' },
                { id: 4753, name: 'KAGUNGA' },
                { id: 4754, name: 'KARUGASHE' },
                { id: 4755, name: 'KINYU' },
                { id: 4756, name: 'KONYO' },
                { id: 4757, name: 'MAFUGA' },
                { id: 4758, name: 'MAKANGA' },
                { id: 4759, name: 'NYARUTUNTU' },
              ],
            },
            {
              id: 694,
              name: 'CENTRAL',
              villages: [
                { id: 4760, name: 'CENTRAL CENTRAL' },
                { id: 4761, name: 'CENTRAL EAST' },
                { id: 4762, name: 'CENTRAL WEST' },
                { id: 4763, name: 'HOSPITAL' },
                { id: 4764, name: 'MAKANGA' },
              ],
            },
            {
              id: 695,
              name: 'KIGONGI WARD',
              villages: [
                { id: 4765, name: 'KIGONGI  A' },
                { id: 4766, name: 'KIGONGI  B' },
                { id: 4767, name: 'NYAKAHITA' },
              ],
            },
            {
              id: 696,
              name: 'NYABIKONI',
              villages: [
                { id: 4768, name: 'GAAJU' },
                { id: 4769, name: 'KANYAKIRIRO' },
                { id: 4770, name: 'KIRWA' },
                { id: 4771, name: 'RUTENGA' },
                { id: 4772, name: 'RUTOOMA' },
                { id: 4773, name: 'RWAKARABA  A' },
              ],
            },
          ],
        },
        {
          id: 144,
          name: 'KABALE NORTHERN',
          parishes: [
            {
              id: 697,
              name: 'KIJUGUTA',
              villages: [
                { id: 4774, name: 'BURAMBIRA' },
                { id: 4775, name: 'KATOJO' },
                { id: 4776, name: 'KIRWA' },
                { id: 4777, name: 'KYETOBOKEIRE' },
                { id: 4778, name: 'RUGARAMA' },
                { id: 4779, name: 'RWAKARABA B' },
              ],
            },
            {
              id: 698,
              name: 'LOWER BUGONGI',
              villages: [
                { id: 4780, name: 'BIGOMBE ROAD' },
                { id: 4781, name: 'BUGONGI ROAD' },
                { id: 4782, name: 'KIGUGWE/KIBIKURA' },
                { id: 4783, name: 'KINYUGUSI LOWER' },
                { id: 4784, name: 'NYAKEIRIMA' },
              ],
            },
            {
              id: 699,
              name: 'RUTOOMA',
              villages: [
                { id: 4785, name: 'BUTARE' },
                { id: 4786, name: 'IBUMBA' },
                { id: 4787, name: 'IHIMBI' },
                { id: 4788, name: 'KATUNGU' },
              ],
            },
            {
              id: 700,
              name: 'UPPER BUGONGI',
              villages: [
                { id: 4789, name: 'BUJANJARA' },
                { id: 4790, name: 'KAKABANO' },
                { id: 4791, name: 'KINYUGUSI UPPER' },
                { id: 4792, name: 'NYAKAHANGA' },
                { id: 4793, name: 'NYAMABARE' },
                { id: 4794, name: 'PIIDA' },
                { id: 4795, name: 'RUSHAMBYA' },
              ],
            },
          ],
        },
        {
          id: 145,
          name: 'KABALE SOUTHERN',
          parishes: [
            {
              id: 701,
              name: 'KARUBANDA',
              villages: [
                { id: 4796, name: 'KABAHANGARA' },
                { id: 4797, name: 'KAHAMA/RUNYANJOKA' },
                { id: 4798, name: 'KARUBANDA' },
                { id: 4799, name: 'KAZIGIZIGI' },
                { id: 4800, name: 'NYAKAKIIKA' },
                { id: 4801, name: 'OMUKIRWA' },
                { id: 4802, name: 'OMUMIHANGA' },
                { id: 4803, name: 'RUSHOROZA' },
                { id: 4804, name: 'RWAGAANA' },
                { id: 4805, name: 'RWEHUYE' },
              ],
            },
            {
              id: 702,
              name: 'KIRIGIME',
              villages: [
                { id: 4806, name: 'BATAKA' },
                { id: 4807, name: 'CENTRAL' },
                { id: 4808, name: 'KABALE N.T.C' },
                { id: 4809, name: 'KAMUKIRA' },
                { id: 4810, name: 'KEKUUBO' },
                { id: 4811, name: 'RUSHAMBYA' },
              ],
            },
            {
              id: 703,
              name: 'MWANJARI',
              villages: [
                { id: 4812, name: 'IGABIRO' },
                { id: 4813, name: 'KIKUNGIRI' },
                { id: 4814, name: 'NDORWA' },
                { id: 4815, name: 'NYAKABUNGO' },
                { id: 4816, name: 'NYAKIHARO' },
                { id: 4817, name: 'NYANGANDE' },
                { id: 4818, name: 'RWAGAANA/KAMATOJO' },
                { id: 4819, name: 'RWAMUKUNDI' },
              ],
            },
            {
              id: 704,
              name: 'RUSHAKI',
              villages: [
                { id: 4820, name: 'NYAMABARE' },
                { id: 4821, name: 'NYARUKONKOROMI' },
                { id: 4822, name: 'OMWIBARE' },
                { id: 4823, name: 'RUGYENDEIRA' },
                { id: 4824, name: 'RUHITA' },
                { id: 4825, name: 'RUSHAKI' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 27,
      name: 'NDORWA COUNTY EAST',
      sub_counties: [
        {
          id: 133,
          name: 'BUHARA',
          parishes: [
            {
              id: 644,
              name: 'BUGARAMA',
              villages: [
                { id: 4208, name: 'AHAMUBUGA' },
                { id: 4209, name: 'AHAMURANGARA' },
                { id: 4210, name: 'BURORANE' },
                { id: 4211, name: 'IRASHANIRO' },
                { id: 4212, name: 'KACURO' },
                { id: 4213, name: 'KAMABARE' },
                { id: 4214, name: 'KASHIJA' },
                { id: 4215, name: 'MISHUNDO  A' },
                { id: 4216, name: 'MISHUNDO  B' },
                { id: 4217, name: 'NYAKABUNGO  A' },
                { id: 4218, name: 'NYAKABUNGO  B' },
                { id: 4219, name: 'RWIRAGUJU' },
              ],
            },
            {
              id: 638,
              name: 'BUHARA',
              villages: [
                { id: 4147, name: 'BUGARAMA' },
                { id: 4148, name: 'BWANJOJO' },
                { id: 62927, name: 'KASHAKI  ?' },
                { id: 4150, name: 'KASHAKI  B' },
                { id: 4149, name: 'KASHAKI A' },
                { id: 4151, name: 'KIGUGO' },
                { id: 4152, name: 'KIJONJO' },
                { id: 4153, name: 'KITUNDUGURU' },
                { id: 4154, name: 'KYASE  A' },
                { id: 4155, name: 'KYASE  B' },
                { id: 4156, name: 'OMURUHANGA' },
              ],
            },
            {
              id: 639,
              name: 'KARWERU (KAFUNJO)',
              villages: [
                { id: 4157, name: 'KABANYONYI' },
                { id: 4158, name: 'KABINDI' },
                { id: 4159, name: 'KAHAMA' },
                { id: 4160, name: 'KIGYERA' },
                { id: 4161, name: 'KIRIMBE' },
                { id: 4162, name: 'MAREMARE' },
                { id: 4163, name: 'MUHENDE' },
                { id: 4164, name: 'NYABICWAMBA' },
                { id: 4165, name: 'NYARUHANGA' },
                { id: 4166, name: 'NYARUTOJO' },
                { id: 4167, name: 'RUBOROGA' },
                { id: 4168, name: 'RUHITA' },
              ],
            },
            {
              id: 640,
              name: 'KITANGA',
              villages: [
                { id: 4169, name: 'NYAKABUNGO' },
                { id: 4171, name: 'NYAKEINA' },
                { id: 4170, name: 'NYAKIHITA' },
                { id: 4172, name: 'NYAMUCENGYERE' },
                { id: 4173, name: 'RUKORE' },
                { id: 4174, name: 'RWAMACANKA' },
                { id: 4175, name: 'RWAMBURA' },
                { id: 4176, name: 'RWAMISHEKYE' },
                { id: 4177, name: 'RWANKUMBA' },
                { id: 4178, name: 'RWANTAMBARA' },
              ],
            },
            {
              id: 641,
              name: 'MUYEBE',
              villages: [
                { id: 4179, name: 'BUKUMBYA' },
                { id: 4180, name: 'KABUYENJE' },
                { id: 4181, name: 'KAMABARE' },
                { id: 4182, name: 'KANABA' },
                { id: 4183, name: 'KIHOKO' },
                { id: 4184, name: 'KYEGYENYI' },
                { id: 4185, name: 'MUYEBE' },
                { id: 4186, name: 'NYAKABUNGO' },
                { id: 4187, name: 'NYAKAHANGA' },
                { id: 4188, name: 'NYAKAKIIKA' },
                { id: 4189, name: 'NYAKATARE' },
                { id: 4190, name: 'NYAMAROGO' },
                { id: 4191, name: 'NYAMIRIMA' },
                { id: 4192, name: 'NYAMURINDIRA' },
                { id: 4193, name: 'NYARWANGARA' },
                { id: 4194, name: 'RWEMBOGO' },
              ],
            },
            {
              id: 642,
              name: 'NTARABANA',
              villages: [
                { id: 4195, name: 'KARUKOBA' },
                { id: 4196, name: 'KASHIJA' },
                { id: 4197, name: 'KYAMPINGA' },
                { id: 4198, name: 'MABUNGO' },
                { id: 4199, name: 'RUSHUMO' },
              ],
            },
            {
              id: 643,
              name: 'RWENE',
              villages: [
                { id: 4200, name: 'BUHORO' },
                { id: 4201, name: 'KIHANGA' },
                { id: 4202, name: 'KIRINGA' },
                { id: 4203, name: 'NYAKABUNGO' },
                { id: 4204, name: 'RUGARAMA' },
                { id: 4205, name: 'RUHITA' },
                { id: 4206, name: 'RUTARE' },
                { id: 4207, name: 'SHORORO' },
              ],
            },
          ],
        },
        {
          id: 134,
          name: 'KAHARO',
          parishes: [
            {
              id: 645,
              name: 'BUGARAMA',
              villages: [
                { id: 4220, name: 'AHAKABIBI' },
                { id: 4221, name: 'AHAKATOJO' },
                { id: 4222, name: 'AHAKATOOMA' },
                { id: 4223, name: 'AHAMUMBA' },
                { id: 4224, name: 'BUGARAMA' },
                { id: 4225, name: 'BYARUSHAMI' },
                { id: 4226, name: 'KABIMBIRI' },
                { id: 4227, name: 'KATOJO' },
                { id: 4228, name: 'KICENCE' },
                { id: 4229, name: 'KIMBUGU' },
                { id: 4230, name: 'KITARE' },
                { id: 4231, name: 'KYOBUGOMBE' },
                { id: 4232, name: 'MUSHUNGA' },
                { id: 4233, name: 'MUTOJO' },
                { id: 4234, name: 'NKONGORO' },
                { id: 4235, name: 'NKUMBURA' },
                { id: 4236, name: 'NYAKABINGO' },
                { id: 4237, name: 'NYAKIGUGWE' },
                { id: 4238, name: 'NYARUKORE' },
                { id: 4239, name: 'OMURUGARAMBIRO' },
                { id: 4240, name: 'OMURUYENJE' },
                { id: 4241, name: 'RUGOMA' },
                { id: 4242, name: 'RWAKACEREGYE' },
              ],
            },
            {
              id: 646,
              name: 'BURAMBIRA',
              villages: [
                { id: 4243, name: 'KANSINGA' },
                { id: 4244, name: 'MUTAGA' },
                { id: 4245, name: 'NYAKABUNGO' },
                { id: 4246, name: 'NYARWANYA' },
                { id: 4247, name: 'OMUKAHITA' },
                { id: 4248, name: 'OMUKARANGARA' },
                { id: 4249, name: 'OMUKISYAMA' },
                { id: 4250, name: 'RUJOGOMA' },
                { id: 4251, name: 'RUSHEBEYA  I' },
                { id: 4252, name: 'RUSHEBEYA  II' },
                { id: 4253, name: 'RUTOOMA' },
                { id: 4254, name: 'RWABIGYERE' },
              ],
            },
            {
              id: 647,
              name: 'KAHARO',
              villages: [
                { id: 4255, name: 'AHAMUREMERE' },
                { id: 4256, name: 'KABARAGA' },
                { id: 4257, name: 'KAMUNOGA' },
                { id: 4258, name: 'KARIBA' },
                { id: 4259, name: 'KARUBENGO' },
                { id: 4260, name: 'KASHARARA' },
                { id: 4261, name: 'KEMENGO' },
                { id: 4262, name: 'KIBUMBA' },
                { id: 4263, name: 'KINYARA' },
                { id: 4264, name: 'KIRANDURA' },
                { id: 4265, name: 'KYAMAKAMBA' },
                { id: 4266, name: 'NYAKABUNGO' },
                { id: 4267, name: 'NYAKAHITA' },
                { id: 4268, name: 'NYAMUGOMA' },
                { id: 4269, name: 'NYAMUSHUNGWA' },
                { id: 4270, name: 'NYARUNGWE' },
                { id: 4271, name: 'RUKOMA' },
                { id: 4272, name: 'RWABASHENYI' },
              ],
            },
            {
              id: 648,
              name: 'KATENGA',
              villages: [
                { id: 4273, name: 'AHAKASIKANO' },
                { id: 4274, name: 'KABUNGO' },
                { id: 4275, name: 'KAMAFUNI' },
                { id: 4276, name: 'KAYORERO' },
                { id: 4277, name: 'KIREIRE' },
                { id: 4278, name: 'KYOBUGOMBE' },
                { id: 4279, name: 'NTUNGAMO' },
                { id: 4280, name: 'NYAKAHITA' },
              ],
            },
            {
              id: 649,
              name: 'KITOHWA',
              villages: [
                { id: 4281, name: 'KAMUKUBA' },
                { id: 4282, name: 'KASHENYI' },
                { id: 4283, name: 'KATOJO' },
                { id: 4284, name: 'KEITAMAHINDA' },
                { id: 4285, name: 'KIBINGO' },
                { id: 4286, name: 'KIBUNGO' },
                { id: 4287, name: 'KIHEESI' },
                { id: 4288, name: 'KYAKABUMBURO' },
                { id: 4289, name: 'KYANGUNDU' },
                { id: 4290, name: 'KYEMBEHO' },
                { id: 4291, name: 'NYABUBARE' },
                { id: 4292, name: 'NYABWESHONGWEIZE' },
                { id: 4293, name: 'NYAKABUNGO' },
                { id: 4294, name: 'NYAKAHANGA' },
                { id: 4295, name: 'NYAKAHITA' },
                { id: 4296, name: 'OMURUHITA' },
                { id: 4297, name: 'RUGARAMA' },
                { id: 4298, name: 'RWABUNYEGYE' },
                { id: 4299, name: 'RWENKUBA' },
                { id: 4300, name: 'RWESASI' },
              ],
            },
            {
              id: 650,
              name: 'NYAKASHARARA',
              villages: [
                { id: 4301, name: 'AHAMURAMBI' },
                { id: 4302, name: 'BUTOORE' },
                { id: 4303, name: 'KARUJANGA' },
                { id: 4304, name: 'KASHANDA' },
                { id: 4305, name: 'KATEETE' },
                { id: 4306, name: 'KYABASHAHO' },
                { id: 4307, name: 'KYAMAKAMBA' },
                { id: 4319, name: 'LYAMUJUNGU' },
                { id: 4320, name: 'LYARUBUNGO' },
                { id: 4321, name: 'LYARUTEKAMA' },
                { id: 4308, name: 'NYAKABUNGO' },
                { id: 4309, name: 'NYAKATARE' },
                { id: 4310, name: 'NYAMISHAKI' },
                { id: 4311, name: 'NYAMITOOMA' },
                { id: 4312, name: 'NYAMUMBA' },
                { id: 4313, name: 'OMUNTUURU' },
                { id: 4314, name: 'OMURUHITA' },
                { id: 4315, name: 'OMURUTOJO' },
                { id: 4316, name: 'RUTOOMA' },
                { id: 4317, name: 'RWAKAREMERA' },
                { id: 4318, name: 'RWAMUGASHA' },
              ],
            },
          ],
        },
        {
          id: 135,
          name: 'KYANAMIRA',
          parishes: [
            {
              id: 651,
              name: 'KANJOBE',
              villages: [
                { id: 4322, name: 'KAMWIRIMA' },
                { id: 4323, name: 'KANJOBE' },
                { id: 4324, name: 'KYAMUGASHA' },
                { id: 4325, name: 'NYAKABINGO' },
                { id: 4326, name: 'NYAKATOJO' },
                { id: 4327, name: 'NYAKIBANDE' },
                { id: 4328, name: 'NYAKIIGA' },
                { id: 4329, name: 'NYAMIGAMBA' },
                { id: 4330, name: 'NYAMIRWA' },
                { id: 4331, name: 'NYAMITEMBE' },
                { id: 4332, name: 'RUSHAMBYA' },
                { id: 4333, name: 'RWEFURA' },
              ],
            },
            {
              id: 652,
              name: 'KATOKYE',
              villages: [
                { id: 4334, name: 'AHEINONI' },
                { id: 4335, name: 'KYAMUHOZI' },
                { id: 4336, name: 'NKOMBE' },
                { id: 4337, name: 'NYAKABUNGO' },
                { id: 4338, name: 'NYAKAHITA' },
                { id: 4339, name: 'NYARUNGWE' },
                { id: 4340, name: 'OMUNGORORERO' },
                { id: 4341, name: 'OMURUTOJO' },
                { id: 4342, name: 'RUBIRA' },
                { id: 4343, name: 'RUGARAMA  I' },
                { id: 4344, name: 'RUGARAMA  II' },
                { id: 4345, name: 'RWAKASHANDE  I' },
                { id: 4346, name: 'RWAKASHANDE  II' },
                { id: 4347, name: 'RWESANZIRO' },
              ],
            },
            {
              id: 653,
              name: 'KIGATA',
              villages: [
                { id: 4348, name: 'BURORANE' },
                { id: 4349, name: 'KABIRA  I' },
                { id: 4350, name: 'KABIRA  II' },
                { id: 4351, name: 'KAKUMBYA' },
                { id: 4352, name: 'KANGANZI' },
                { id: 4353, name: 'KATEGURE' },
                { id: 4354, name: 'KIHANGA' },
                { id: 4355, name: 'KYABUHIRE' },
                { id: 4356, name: 'KYAKAGOYE' },
                { id: 4357, name: 'NYAKAHITA' },
                { id: 4358, name: 'NYAKIGANDO' },
                { id: 4359, name: 'NYARUHANGA' },
                { id: 4360, name: 'OMUKIBEGA' },
                { id: 4361, name: 'RUBOROGA' },
                { id: 4362, name: 'RWABAKATA' },
                { id: 4363, name: 'RWAKASHANDE' },
                { id: 4364, name: 'RWAMURIRO' },
                { id: 4365, name: 'RWEMISHURE' },
                { id: 4366, name: 'RWENKIMA' },
              ],
            },
            {
              id: 654,
              name: 'KYANAMIRA',
              villages: [
                { id: 4367, name: 'AHAMUGWIGWI' },
                { id: 4368, name: 'BUGANDARA' },
                { id: 4369, name: 'BUNOMBE' },
                { id: 4370, name: 'KABATOGOTE' },
                { id: 4371, name: 'KABISHA' },
                { id: 4372, name: 'KAKIBUMBWE' },
                { id: 4373, name: 'KANYINOBURIBA' },
                { id: 4374, name: 'KARANDURA' },
                { id: 4375, name: 'KARUBANDA' },
                { id: 4376, name: 'KARUHUMA' },
                { id: 4377, name: 'KAYANJA' },
                { id: 4378, name: 'KISHEKYERA' },
                { id: 4379, name: 'NYAKAHITA  I' },
                { id: 4380, name: 'NYAKAHITA  II' },
                { id: 4381, name: 'NYAMIYAGA' },
                { id: 4382, name: 'RWABABA' },
                { id: 4383, name: 'RWAMUGIMBA' },
                { id: 4384, name: 'RWAMUTARUHA' },
                { id: 4385, name: 'RWANYABIBOGA' },
                { id: 4386, name: 'RWEBIKONKO' },
              ],
            },
            {
              id: 655,
              name: 'MUYUMBU',
              villages: [
                { id: 4387, name: 'AHABUSIKANO' },
                { id: 4388, name: 'HAKATONGO' },
                { id: 4389, name: 'HAKISHAAHA' },
                { id: 4390, name: 'HAMURAMBI' },
                { id: 4391, name: 'ITUZA' },
                { id: 4392, name: 'KABURA' },
                { id: 4393, name: 'KAGARAMA' },
                { id: 4394, name: 'KASHENYI' },
                { id: 4395, name: 'KINIOGO' },
                { id: 4396, name: 'KIRWA' },
                { id: 4397, name: 'MURUHITA' },
                { id: 4398, name: 'MUSHUNGA' },
                { id: 4399, name: 'MUYUMBU' },
                { id: 4400, name: 'NTUNGAMO' },
                { id: 4401, name: 'NYAKAHANGA' },
                { id: 4402, name: 'NYAKAHITA' },
                { id: 4403, name: 'NYAMUREINGWA' },
                { id: 4404, name: 'RUJANJARA' },
                { id: 4405, name: 'RWAKABUNGA' },
                { id: 4406, name: 'RWANYAMITWE' },
                { id: 4407, name: 'RWEMIGOYE' },
                { id: 4408, name: 'RWEMPANGA' },
              ],
            },
            {
              id: 656,
              name: 'NYABUSHABI',
              villages: [
                { id: 4409, name: 'BWAATO' },
                { id: 4410, name: 'IHIMBI' },
                { id: 4411, name: 'KARUBANDA' },
                { id: 4412, name: 'KAYORERO' },
                { id: 4413, name: 'MPAAMBWE' },
                { id: 4414, name: 'MUKISHEENYI' },
                { id: 4415, name: 'MURAGO' },
                { id: 4416, name: 'NYAKABUNGO' },
                { id: 4417, name: 'NYAKAHITA' },
                { id: 4418, name: 'RUJANJARA' },
                { id: 4419, name: 'RUSHAMBYA' },
                { id: 4420, name: 'RWEERE' },
                { id: 4421, name: 'RWENKIMA' },
              ],
            },
            {
              id: 657,
              name: 'NYAKAGYERA',
              villages: [
                { id: 4422, name: 'BUNOMBE' },
                { id: 4423, name: 'BUSHENSHERO' },
                { id: 4424, name: 'KABISHA' },
                { id: 4425, name: 'KANYANKWANZI' },
                { id: 4426, name: 'KIGONGI' },
                { id: 4427, name: 'NYABIKONI' },
                { id: 4428, name: 'NYAKAHITA' },
                { id: 4429, name: 'NYARUHANGA' },
                { id: 4430, name: 'OMUMWIIGA' },
                { id: 4431, name: 'OMURUHITA' },
                { id: 4432, name: 'OMWIBAARE' },
                { id: 4433, name: 'RUGARAMBIRO' },
                { id: 4434, name: 'RWAKATORYO' },
                { id: 4435, name: 'RWANSHENYIRE' },
              ],
            },
          ],
        },
        {
          id: 136,
          name: 'MAZIBA',
          parishes: [
            {
              id: 658,
              name: 'BIRAMBO',
              villages: [
                { id: 4436, name: 'BIRAMBO' },
                { id: 4437, name: 'EIZINIRO' },
                { id: 4438, name: 'KAMURONKO' },
                { id: 4439, name: 'KANONI' },
                { id: 4440, name: 'KEIRUNGU' },
                { id: 4441, name: 'KYAMPUNGYE' },
                { id: 4442, name: 'NYAKARAMBI' },
                { id: 4443, name: 'NYAMITUNGA' },
                { id: 4444, name: 'OMUKASHENYI' },
                { id: 4445, name: 'RUSHUMO' },
                { id: 4446, name: 'RWEMIHANGA' },
                { id: 4447, name: 'RWIINAMURA' },
              ],
            },
            {
              id: 659,
              name: 'KAHONDO',
              villages: [
                { id: 4448, name: 'KABASYABA' },
                { id: 4449, name: 'KAHONDO TRADING CENTRE' },
                { id: 4450, name: 'KATUKURA' },
                { id: 4451, name: 'MUKOKYE' },
                { id: 4452, name: 'NYAKIGANDO' },
                { id: 4453, name: 'NYAMIRIMA' },
                { id: 4454, name: 'NYAMITOOMA' },
                { id: 4455, name: 'RUKORE' },
                { id: 4456, name: 'RWANYAKACENDE' },
              ],
            },
            {
              id: 660,
              name: 'KARWERU',
              villages: [
                { id: 4457, name: 'AHAKATARE' },
                { id: 4458, name: 'AHASINGYE' },
                { id: 4459, name: 'BUNYERERE' },
                { id: 4460, name: 'BUTANGA' },
                { id: 4461, name: 'KITUNDUGURU' },
                { id: 4462, name: 'KYEIBARE' },
                { id: 4463, name: 'NYAMABARE' },
                { id: 4464, name: 'RUREMA' },
              ],
            },
            {
              id: 661,
              name: 'KAVU',
              villages: [
                { id: 4465, name: 'BUKORO' },
                { id: 4466, name: 'KAGOGO' },
                { id: 4467, name: 'KAGONA' },
                { id: 4468, name: 'KASIRIMA' },
                { id: 4469, name: 'KYERERO' },
                { id: 4470, name: 'MUKOKYE' },
                { id: 4471, name: 'NYAKASA' },
                { id: 4472, name: 'NYAKIIGA' },
                { id: 4473, name: 'RUGARAMA  I' },
                { id: 4474, name: 'RUGARAMA  II' },
                { id: 4475, name: 'RUSHEKYERA' },
                { id: 4476, name: 'RWAKIHAZI' },
              ],
            },
            {
              id: 662,
              name: 'NYANJA',
              villages: [
                { id: 4477, name: 'BURUNGA' },
                { id: 4478, name: 'BWEYO' },
                { id: 4479, name: 'KAMBIBI' },
                { id: 4480, name: 'KANYAKUTANA' },
                { id: 4481, name: 'KIGARAMA  A' },
                { id: 4482, name: 'KIGARAMA  B' },
                { id: 4483, name: 'KIGARAMA  C' },
                { id: 4484, name: 'KITAMBI   B' },
                { id: 4485, name: 'KITAMBI  A' },
                { id: 4486, name: 'KIZIBA  A' },
                { id: 4487, name: 'KIZIBA  B' },
                { id: 4488, name: 'MUBIRA' },
                { id: 4489, name: 'MWENDO' },
                { id: 4490, name: 'NYANJA TRADING CENTRE' },
                { id: 4491, name: 'RWABAKINA' },
                { id: 4492, name: 'RWAMIKIKO' },
              ],
            },
            {
              id: 663,
              name: 'RUGARAMA',
              villages: [
                { id: 4493, name: 'KAGARAMA' },
                { id: 4494, name: 'KANKONDO' },
                { id: 4495, name: 'KARAMBWE' },
                { id: 4496, name: 'KIINA-NYAKATOOMA' },
                { id: 4497, name: 'NYAMUHEMURA' },
                { id: 4498, name: 'NYANGA' },
                { id: 4499, name: 'RWABAREMERA' },
                { id: 4500, name: 'RWAKASHENDWA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 28,
      name: 'NDORWA COUNTY WEST',
      sub_counties: [
        {
          id: 140,
          name: 'BUTANDA',
          parishes: [
            {
              id: 681,
              name: 'BIGAAGA',
              villages: [
                { id: 4661, name: 'KABERE' },
                { id: 4662, name: 'KAGOGO' },
                { id: 4663, name: 'KASUMO' },
                { id: 4664, name: 'KITAHURIRA' },
                { id: 4665, name: 'MURANDAMO' },
                { id: 4666, name: 'MUSHENYI  A' },
                { id: 4667, name: 'MUSHENYI  B' },
                { id: 4668, name: 'NYINABIRERE' },
                { id: 4669, name: 'RUBUMBA' },
                { id: 4670, name: 'RUSISIRO' },
                { id: 4671, name: 'RUTARE' },
                { id: 4672, name: 'RWARA' },
              ],
            },
            {
              id: 683,
              name: 'BUTANDA',
              villages: [
                { id: 4684, name: 'BUGOTO' },
                { id: 4685, name: 'BUSHARA' },
                { id: 4686, name: 'BUTANDA' },
                { id: 4687, name: 'HABUHINGA' },
                { id: 4688, name: 'KABUTUKU' },
                { id: 4689, name: 'KANYABIYENGO' },
                { id: 4690, name: 'KASIRU' },
                { id: 4691, name: 'KEKUUBO' },
                { id: 4692, name: 'KIBUNGO' },
                { id: 4693, name: 'KINYAMARI' },
                { id: 4694, name: 'NTUNGAMO' },
                { id: 4695, name: 'NYAMABARE' },
                { id: 4696, name: 'NYAMIYAGA' },
                { id: 4697, name: 'NYOMBE' },
                { id: 4698, name: 'RWANCERERE' },
              ],
            },
            {
              id: 9521,
              name: 'KABERE',
              villages: [
                { id: 61506, name: 'HAKYOMA' },
                { id: 61909, name: 'KABERE A' },
                { id: 61910, name: 'KABERE B' },
                { id: 69987, name: 'RUSISIRO LOWER' },
                { id: 69991, name: 'RUTARE' },
                { id: 70101, name: 'RWARA' },
                { id: 70939, name: 'UPPER RUSISIRO' },
              ],
            },
            {
              id: 682,
              name: 'KAHUNGYE',
              villages: [
                { id: 4673, name: 'BISHAKI' },
                { id: 4674, name: 'HAMABAARE' },
                { id: 4675, name: 'KABAYA' },
                { id: 4676, name: 'KATOJO  A' },
                { id: 4677, name: 'KATOJO  B' },
                { id: 4678, name: 'KINYAMI' },
                { id: 4679, name: 'KITOJO' },
                { id: 4680, name: 'KYABAGARA' },
                { id: 4681, name: 'NYAKIHANDA' },
                { id: 4682, name: 'RULE' },
                { id: 4683, name: 'RWENKORONGO' },
              ],
            },
            {
              id: 9687,
              name: 'KIFURUGUTU',
              villages: [
                { id: 62109, name: 'KAGOROGORO' },
                { id: 63075, name: 'KATETE' },
                { id: 63460, name: 'KIFURUGUTU' },
                { id: 67802, name: 'NKORA' },
              ],
            },
            {
              id: 9729,
              name: 'KINYAMARI',
              villages: [
                { id: 60313, name: 'BUSHARA' },
                { id: 61981, name: 'KABUTUKU' },
                { id: 62567, name: 'KANYABIYENGO' },
                { id: 63399, name: 'KIBUNGO' },
                { id: 63763, name: 'KINYAMARI' },
                { id: 67873, name: 'NTUNGAMO' },
                { id: 67913, name: 'NYABITABO' },
              ],
            },
            {
              id: 10009,
              name: 'MURAMBO',
              villages: [
                { id: 63133, name: 'KATOOMA' },
                { id: 63212, name: 'KAYANGA' },
                { id: 66638, name: 'MURAMBO' },
                { id: 69995, name: 'RUTOJO' },
              ],
            },
            {
              id: 684,
              name: 'NYAMIRYANGO',
              villages: [
                { id: 4699, name: 'BUTEBE' },
                { id: 4701, name: 'KAGOROGORO' },
                { id: 4702, name: 'KATOOMA' },
                { id: 4700, name: 'KIFURUGUTU' },
                { id: 4703, name: 'KINYAMARI  I' },
                { id: 4704, name: 'KINYAMARI  II' },
                { id: 4705, name: 'KYEVU' },
                { id: 4706, name: 'MAKANGA' },
                { id: 4707, name: 'MURAMBO' },
                { id: 4708, name: 'MUTUNGU' },
                { id: 4709, name: 'NKORA-KATETE' },
                { id: 4710, name: 'RUTOJO' },
              ],
            },
          ],
        },
        {
          id: 1996,
          name: 'KAHUNGYE',
          parishes: [
            {
              id: 9366,
              name: 'BURAMBA',
              villages: [
                { id: 61501, name: 'HAKABUNGO' },
                { id: 68285, name: 'NYINAMUHOMBORI' },
                { id: 70010, name: 'RUTOOMA I' },
                { id: 70011, name: 'RUTOOMA II' },
                { id: 70094, name: 'RWANGANIRO' },
                { id: 70116, name: 'RWEIJUNGU' },
              ],
            },
            {
              id: 9492,
              name: 'HABUHURIRO',
              villages: [
                { id: 63112, name: 'KATOJO  A' },
                { id: 63113, name: 'KATOJO  B' },
                { id: 63764, name: 'KINYAMI' },
                { id: 64466, name: 'KYABAGARA' },
                { id: 67952, name: 'NYABYUMBA' },
              ],
            },
            {
              id: 9546,
              name: 'KAHUNGYE',
              villages: [
                { id: 61507, name: 'HAMABAARE' },
                { id: 61895, name: 'KABAYA' },
                { id: 64055, name: 'KITOJO LOWER' },
                { id: 64056, name: 'KITOJO UPPER' },
                { id: 68100, name: 'NYAKIHANDA' },
                { id: 69947, name: 'RULE' },
                { id: 70180, name: 'RWENKORONGO' },
              ],
            },
            {
              id: 10134,
              name: 'NYOMBE',
              villages: [
                { id: 59117, name: 'BISHAKI' },
                { id: 61495, name: 'HABUHINGA' },
                { id: 62976, name: 'KASIRU' },
                { id: 63744, name: 'KINISYA' },
                { id: 68290, name: 'NYOMBE' },
              ],
            },
            {
              id: 10265,
              name: 'RUBUMBA',
              villages: [
                { id: 64040, name: 'KITESENI' },
                { id: 66639, name: 'MURANDAMO A' },
                { id: 66640, name: 'MURANDAMO B' },
                { id: 69887, name: 'RUBUMBA' },
                { id: 69902, name: 'RUGARAMA' },
              ],
            },
            {
              id: 10283,
              name: 'RWEMIHANGA',
              villages: [
                { id: 59112, name: 'BIRIINGO' },
                { id: 60771, name: 'BWAYA' },
                { id: 61510, name: 'HAMUHARURO' },
                { id: 66509, name: 'MUKABAYA' },
                { id: 67732, name: 'NGANZO' },
                { id: 67946, name: 'NYABWIHEREKO' },
                { id: 68189, name: 'NYAMUGARI' },
                { id: 70107, name: 'RWEBIKOONA' },
                { id: 70137, name: 'RWEMIHANGA' },
              ],
            },
          ],
        },
        {
          id: 137,
          name: 'KAMUGANGUZI',
          parishes: [
            {
              id: 664,
              name: 'BURANGA',
              villages: [
                { id: 61846, name: 'KABAHESI' },
                { id: 62764, name: 'KARAGO' },
                { id: 4501, name: 'KIKORE' },
                { id: 4502, name: 'MURAMBO' },
                { id: 4503, name: 'NYARUBIRA' },
                { id: 4504, name: 'RUKARANGA' },
                { id: 4505, name: 'RUSHEBEYA' },
              ],
            },
            {
              id: 665,
              name: 'KASHEREGYENYI',
              villages: [
                { id: 4506, name: 'KYARUGONDO' },
                { id: 4507, name: 'NYAKARINDI' },
                { id: 4508, name: 'NYAKASHARARA' },
                { id: 4511, name: 'NYAKATUGUNDA' },
                { id: 4509, name: 'NYANGOYE' },
                { id: 4510, name: 'RWAMACUMU' },
              ],
            },
            {
              id: 666,
              name: 'KATENGA',
              villages: [
                { id: 4512, name: 'BWIRANYI' },
                { id: 4513, name: 'KABERA' },
                { id: 4514, name: 'KASHENYI' },
                { id: 4515, name: 'KYONDO' },
                { id: 4516, name: 'NYABYUMBA' },
                { id: 4517, name: 'NYAKABUNGO' },
                { id: 4518, name: 'NYINANYUNDO' },
              ],
            },
            {
              id: 667,
              name: 'KICUMBI',
              villages: [
                { id: 4519, name: 'KASHENYI' },
                { id: 4520, name: 'NYAKATEETE  A' },
                { id: 4521, name: 'NYAKATEETE  B' },
                { id: 4522, name: 'NYAKATOOMA' },
                { id: 4523, name: 'NYAMABARE' },
                { id: 4524, name: 'NYAMURINDIRA  A' },
                { id: 4525, name: 'NYAMURINDIRA  B' },
                { id: 4526, name: 'OMURUJANJARA' },
                { id: 4527, name: 'OMURURINDA' },
                { id: 4528, name: 'RUSHONGATI' },
              ],
            },
            {
              id: 668,
              name: 'KISAASA',
              villages: [
                { id: 4529, name: 'AHAMUHAMBO' },
                { id: 4530, name: 'AHASINGYE' },
                { id: 4531, name: 'KAMUKUNGU' },
                { id: 4532, name: 'NYACONGA' },
              ],
            },
            {
              id: 669,
              name: 'KYASANO',
              villages: [
                { id: 4533, name: 'BUMBA' },
                { id: 4534, name: 'ISINGIRO' },
                { id: 4535, name: 'KAGOROGORO' },
                { id: 4538, name: 'KYAMWIMBA' },
                { id: 4536, name: 'MUGOBOLE' },
                { id: 4537, name: 'RUTUNDWE' },
              ],
            },
            {
              id: 670,
              name: 'MAYENGO',
              villages: [
                { id: 4539, name: 'BUGIRA' },
                { id: 4540, name: 'BUNAGANA' },
                { id: 4541, name: 'MAHURA' },
                { id: 4542, name: 'RWAKAKOBE' },
                { id: 70056, name: 'RWAKIZAMBA' },
                { id: 4543, name: 'RWAKIZAMBA LOWER' },
              ],
            },
          ],
        },
        {
          id: 141,
          name: 'KATUNA TOWN COUNCIL',
          parishes: [
            {
              id: 685,
              name: 'KACERERE WARD',
              villages: [
                { id: 4711, name: 'KAMUGANGUZI' },
                { id: 4712, name: 'KANYANJOKA' },
                { id: 4713, name: 'KITOJO' },
                { id: 4714, name: 'NYAMENGO' },
                { id: 4715, name: 'RWAMPIRI' },
              ],
            },
            {
              id: 686,
              name: 'KINIOGO WARD',
              villages: [
                { id: 4719, name: 'KATUNA BOARDER' },
                { id: 4716, name: 'KINIOGO' },
                { id: 4717, name: 'MAYENGO-KATUNA' },
                { id: 4718, name: 'NYAMIRIMA' },
              ],
            },
            {
              id: 687,
              name: 'KYONYO WARD',
              villages: [
                { id: 4721, name: 'BWAHI' },
                { id: 4720, name: 'KABALIISA' },
                { id: 4723, name: 'NYAKAHITA' },
                { id: 4722, name: 'RWAKATAMBARA' },
              ],
            },
            {
              id: 688,
              name: 'MUKARANGYE WARD',
              villages: [
                { id: 4726, name: 'BURAMBIRA' },
                { id: 4727, name: 'HAKABUNGO' },
                { id: 4724, name: 'KAKOMA' },
                { id: 4729, name: 'KATUNA BURAMBIRA' },
                { id: 4728, name: 'RWEMIHANGA' },
                { id: 4725, name: 'RYARUHINDA' },
              ],
            },
            {
              id: 689,
              name: 'NYINAMURONZI WARD',
              villages: [
                { id: 4730, name: 'BUHEKYENYA' },
                { id: 4731, name: 'NYINAMURONZI' },
                { id: 4732, name: 'RUGARAMA' },
              ],
            },
          ],
        },
        {
          id: 2021,
          name: 'KIBUGA',
          parishes: [
            {
              id: 9618,
              name: 'KARUJANGA',
              villages: [
                { id: 59378, name: 'BUHINGA' },
                { id: 61822, name: 'KAAMANYU' },
                { id: 61898, name: 'KABEHO' },
                { id: 63643, name: 'KIKINGO' },
                { id: 63976, name: 'KITABAGARWA  A' },
                { id: 63977, name: 'KITABAGARWA  B' },
                { id: 66500, name: 'MUHONDO' },
                { id: 68087, name: 'NYAKEINA' },
                { id: 69918, name: 'RUHITA' },
                { id: 69972, name: 'RUSHAKI  A' },
                { id: 69973, name: 'RUSHAKI  B' },
              ],
            },
            {
              id: 9680,
              name: 'KIBUGA',
              villages: [
                { id: 60274, name: 'BUSANGANO A' },
                { id: 60275, name: 'BUSANGANO B' },
                { id: 60309, name: 'BUSHABIRA' },
                { id: 61508, name: 'HAMUBUGA' },
                { id: 62586, name: 'KANYANTE' },
                { id: 66501, name: 'MUHOOKI' },
                { id: 68176, name: 'NYAMITOMA' },
                { id: 68202, name: 'NYAMUTENGUZI' },
                { id: 70102, name: 'RWAZA' },
              ],
            },
            {
              id: 9749,
              name: 'KISIBO',
              villages: [
                { id: 64051, name: 'KITOJO' },
                { id: 65929, name: 'MAKANGA' },
                { id: 66691, name: 'MUSHENYI' },
                { id: 67990, name: 'NYAKABUNGO' },
                { id: 68286, name: 'NYINARUSHENGYE' },
                { id: 69982, name: 'RUSHEBEYA' },
                { id: 70071, name: 'RWAMATEKYE' },
                { id: 70096, name: 'RWANSHONSHORE' },
                { id: 70258, name: 'RYANYAKAHIMA' },
              ],
            },
            {
              id: 10273,
              name: 'RUTARE',
              villages: [
                { id: 63978, name: 'KITABO A' },
                { id: 63979, name: 'KITABO B' },
                { id: 64514, name: 'KYABUHA' },
                { id: 68255, name: 'NYARUHANGA' },
                { id: 70411, name: 'SHOOKO' },
              ],
            },
          ],
        },
        {
          id: 138,
          name: 'KITUMBA',
          parishes: [
            {
              id: 671,
              name: 'BUKORA',
              villages: [
                { id: 4544, name: 'BUGANDARA' },
                { id: 4545, name: 'BUHOBERO' },
                { id: 4546, name: 'HAMUGANDA' },
                { id: 4547, name: 'KABIRA' },
                { id: 4548, name: 'KABUMBA' },
                { id: 4549, name: 'KAGUGO' },
                { id: 4550, name: 'KAKASHENYA' },
                { id: 4551, name: 'KAKOOKO' },
                { id: 4552, name: 'KANYANKWANZI' },
                { id: 4553, name: 'KARIKO' },
                { id: 4554, name: 'KASHAMBYA' },
                { id: 4555, name: 'KENYAGWE' },
                { id: 4556, name: 'KIJUREERA' },
                { id: 4557, name: 'MUMABARE' },
                { id: 4558, name: 'NYABWEGYERERE' },
                { id: 4559, name: 'NYAKYATO' },
                { id: 4560, name: 'RUKOLE' },
                { id: 4561, name: 'RWAKANYWEIRE' },
              ],
            },
            {
              id: 672,
              name: 'BUSHURO',
              villages: [
                { id: 4562, name: 'BUSHURO' },
                { id: 4563, name: 'HAMBUNGO' },
                { id: 4564, name: 'KABINDI' },
                { id: 4565, name: 'KANYANKWANZI' },
                { id: 4566, name: 'KATEMBE' },
                { id: 4567, name: 'KEISHAMUNYORO' },
                { id: 4568, name: 'KEITANKOMBE' },
                { id: 4569, name: 'KIRWA' },
                { id: 4570, name: 'MUTOJO' },
                { id: 4571, name: 'NKOMBE  A' },
                { id: 4572, name: 'NKOMBE  B' },
                { id: 4573, name: 'NYAMABALE' },
                { id: 4574, name: 'RUSHAMBYA' },
              ],
            },
            { id: 673, name: 'BWAMA ISLAND', villages: [{ id: 4575, name: 'BWAMA ISLAND' }] },
            {
              id: 674,
              name: 'KITUMBA',
              villages: [
                { id: 4576, name: 'BUTARE' },
                { id: 4577, name: 'KAHAMA   II' },
                { id: 4578, name: 'KAHAMA  I' },
                { id: 4579, name: 'KASHENYI' },
                { id: 4580, name: 'KENGOMA' },
                { id: 4581, name: 'OMWIRWANIRO' },
                { id: 4582, name: 'RUNYANJOKA' },
                { id: 4583, name: 'RWABIRUNDO' },
              ],
            },
            {
              id: 675,
              name: 'MWENDO',
              villages: [
                { id: 4584, name: 'BUFUKA' },
                { id: 4585, name: 'KABISHA' },
                { id: 4586, name: 'KABUNGO' },
                { id: 4587, name: 'KABURARA' },
                { id: 4588, name: 'KAFORERO' },
                { id: 4589, name: 'KARUJABURA' },
                { id: 4590, name: 'KASINDE' },
                { id: 4591, name: 'KATOOMA' },
                { id: 4592, name: 'KIYOORA' },
                { id: 4593, name: 'KYAMAREBURA' },
                { id: 4594, name: 'MUGABI' },
                { id: 4595, name: 'MUTAABA' },
                { id: 4596, name: 'MWIRANGIZO' },
                { id: 4597, name: 'NYAKABUNGO' },
                { id: 4598, name: 'NYAKEINA' },
                { id: 4599, name: 'NYAKIBANDE' },
                { id: 4600, name: 'NYAMBUGU' },
                { id: 4601, name: 'NYAMIYANGA' },
                { id: 4602, name: 'RWENKONA' },
              ],
            },
          ],
        },
        {
          id: 139,
          name: 'RUBAYA',
          parishes: [
            {
              id: 676,
              name: 'BURAMBA',
              villages: [
                { id: 4603, name: 'BIRIINGO' },
                { id: 4604, name: 'BWAYA' },
                { id: 4605, name: 'HAKABUNGO' },
                { id: 4606, name: 'MUKABAYA' },
                { id: 4607, name: 'NGANZO' },
                { id: 4608, name: 'NYAMUGARI' },
                { id: 4609, name: 'NYINAMUHOMBORI' },
                { id: 4610, name: 'RUTOOMA I' },
                { id: 4611, name: 'RUTOOMA II' },
                { id: 4612, name: 'RWANGANIRO' },
                { id: 4613, name: 'RWEMIHANGA' },
              ],
            },
            {
              id: 9383,
              name: 'BUTENGA',
              villages: [
                { id: 60719, name: 'BUYANJE' },
                { id: 62058, name: 'KAFUMBO' },
                { id: 62076, name: 'KAGASHA' },
                { id: 62790, name: 'KARENGYERE' },
                { id: 62947, name: 'KASHENYI' },
                { id: 63520, name: 'KIGORO' },
                { id: 67989, name: 'NYAKABUNGO' },
                { id: 69917, name: 'RUHIRI' },
                { id: 70035, name: 'RWABIHINDU' },
                { id: 70797, name: 'TOOHA' },
              ],
            },
            {
              id: 677,
              name: 'KARUJANGA',
              villages: [
                { id: 4614, name: 'BUHINGA' },
                { id: 4615, name: 'KABEHO' },
                { id: 4616, name: 'KIKINGO' },
                { id: 4617, name: 'KITABAGARWA  A' },
                { id: 4618, name: 'KITABAGARWA  B' },
                { id: 4619, name: 'KITOJO' },
                { id: 4620, name: 'MUSHENYI' },
                { id: 4621, name: 'NYAKABUNGO' },
                { id: 4622, name: 'NYINARUSHENGYE' },
                { id: 4623, name: 'RUHITA' },
                { id: 4624, name: 'RUSHAKI  A' },
                { id: 4625, name: 'RUSHAKI  B' },
                { id: 4626, name: 'RUSHEBEYA' },
                { id: 4627, name: 'RWANSHONSHORE' },
                { id: 4628, name: 'RYANYAKAHIMA' },
              ],
            },
            {
              id: 678,
              name: 'KIBUGA',
              villages: [
                { id: 4629, name: 'BUSANGANO' },
                { id: 4630, name: 'BUSHABIRA' },
                { id: 4631, name: 'KANYANTE' },
                { id: 4632, name: 'KITABO' },
                { id: 4633, name: 'NYAMITOMA' },
                { id: 4634, name: 'NYARUHANGA' },
                { id: 4635, name: 'RWAZA' },
                { id: 4636, name: 'SHOOKO' },
              ],
            },
            {
              id: 679,
              name: 'KITOOMA',
              villages: [
                { id: 4637, name: 'HABUGARAMA' },
                { id: 4638, name: 'ITARA' },
                { id: 4639, name: 'KAGASHA' },
                { id: 4640, name: 'KAGUUGO' },
                { id: 4641, name: 'KARENGYERE' },
                { id: 4642, name: 'KASHENYI' },
                { id: 4643, name: 'KASHUNGYERA' },
                { id: 4644, name: 'KIGORO' },
                { id: 4645, name: 'KIRWA' },
                { id: 4646, name: 'MBURASHASHO' },
                { id: 4647, name: 'MUKONI' },
                { id: 4648, name: 'NYABIGORE' },
                { id: 4649, name: 'NYAKABUNGO' },
                { id: 4650, name: 'RWABARERA' },
                { id: 4651, name: 'RWABIHINDU' },
              ],
            },
            {
              id: 10011,
              name: 'MUSAMBA',
              villages: [
                { id: 57616, name: 'AHAKAKINGO' },
                { id: 59328, name: 'BUGO' },
                { id: 60322, name: 'BUSHURUGUNYU' },
                { id: 60818, name: 'BYANYAMIHIRIRE' },
                { id: 66536, name: 'MUKIYANJA' },
                { id: 66667, name: 'MURUNGU' },
                { id: 66676, name: 'MUSAMBA' },
                { id: 69884, name: 'RUBOONA' },
              ],
            },
            {
              id: 680,
              name: 'RWANYENA',
              villages: [
                { id: 4653, name: 'AHAKAKINGO' },
                { id: 4652, name: 'BUGO' },
                { id: 4654, name: 'KABIRAGO' },
                { id: 4655, name: 'KIHORONGWA' },
                { id: 4656, name: 'KISHAZE' },
                { id: 4657, name: 'MUKIYANJA' },
                { id: 4658, name: 'MURUNGU' },
                { id: 4659, name: 'MUSAMBA' },
                { id: 4660, name: 'NDARURA' },
              ],
            },
          ],
        },
        {
          id: 142,
          name: 'RYAKARIMIRA TOWN COUNCIL',
          parishes: [
            {
              id: 691,
              name: 'AHAMUHAMBO WARD',
              villages: [
                { id: 4740, name: 'AHAMUHAMBO' },
                { id: 4742, name: 'KANTAMBARA' },
                { id: 4743, name: 'KATABURA' },
                { id: 4741, name: 'KIGARAMA A' },
                { id: 4744, name: 'KIGARAMA B' },
                { id: 65930, name: 'MAKANGA' },
                { id: 4745, name: 'NYINASUNZU' },
              ],
            },
            {
              id: 690,
              name: 'KACERERE WARD',
              villages: [
                { id: 4733, name: 'KACERERE A' },
                { id: 61993, name: 'KACERERE B' },
                { id: 4734, name: 'KARAMBO' },
                { id: 4735, name: 'KIBINGWE' },
                { id: 4736, name: 'MUGURI  A' },
                { id: 4737, name: 'MUGURI  B' },
                { id: 4739, name: 'MUHENVU' },
                { id: 66537, name: 'MUKIYOVU' },
                { id: 4738, name: 'NYAKITOKORI' },
              ],
            },
            {
              id: 692,
              name: 'RUKORE WARD',
              villages: [
                { id: 59307, name: 'BUGARAMA' },
                { id: 4746, name: 'KAGYERA' },
                { id: 4747, name: 'KIHIIRA' },
                { id: 4749, name: 'NYAKIBANDE' },
                { id: 4748, name: 'NYAMABARE' },
                { id: 4751, name: 'NYAMIYAGA' },
                { id: 4750, name: 'RUKORE' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
