import { District } from '../types';

export default <District>{
  id: 10,
  name: 'KABAROLE',
  counties: [
    {
      id: 30,
      name: 'BURAHYA COUNTY',
      sub_counties: [
        {
          id: 146,
          name: 'BUKUUKU',
          parishes: [
            {
              id: 705,
              name: 'KAZINGO',
              villages: [
                { id: 4830, name: 'KAZIGOBE' },
                { id: 4826, name: 'KAZINGO CENTRAL' },
                { id: 4827, name: 'KAZINGO SOUTH' },
                { id: 4828, name: 'KIHWERA LOWER' },
                { id: 66570, name: 'MUKYEYA' },
                { id: 68104, name: 'NYAKINONI' },
                { id: 4829, name: 'RWAKITURA' },
              ],
            },
            {
              id: 706,
              name: 'KITAKA',
              villages: [
                { id: 61930, name: 'KABIRIZI' },
                { id: 4831, name: 'KANYAMULIMI' },
                { id: 4834, name: 'KIHWERA UPPER' },
                { id: 63770, name: 'KINYANTUHA' },
                { id: 4833, name: 'KITAKA' },
                { id: 4832, name: 'MPANGA' },
                { id: 4835, name: 'NYANGO' },
              ],
            },
            {
              id: 707,
              name: 'MANDAKO',
              villages: [
                { id: 4836, name: 'KIMBUGU' },
                { id: 4837, name: 'KINYANGURU' },
                { id: 63922, name: 'KISIITA' },
                { id: 4838, name: 'MANDAKO' },
                { id: 4839, name: 'NYAMIRYANGO' },
              ],
            },
          ],
        },
        {
          id: 147,
          name: 'BUSORO',
          parishes: [
            {
              id: 708,
              name: 'BUSORO',
              villages: [
                { id: 4840, name: 'BUSORO' },
                { id: 4841, name: 'KAIHOKWA' },
                { id: 4842, name: 'KIGARAMA' },
                { id: 4843, name: 'KIRERE' },
                { id: 64580, name: 'KYAKAZIINI' },
                { id: 4844, name: 'KYAMASONGI A' },
                { id: 64615, name: 'KYAMASONGI B' },
                { id: 4845, name: 'KYOGYA' },
                { id: 4846, name: 'NGOMBE  A' },
                { id: 4847, name: 'NGOMBE  B' },
                { id: 4848, name: 'NYABUSENYI  I' },
                { id: 4849, name: 'NYABUSENYI  II' },
                { id: 4850, name: 'NYABUSENYI  III' },
              ],
            },
            {
              id: 711,
              name: 'IBAALE',
              villages: [
                { id: 4884, name: 'BWIKARAGA' },
                { id: 4885, name: 'IBAALE' },
                { id: 4886, name: 'KANYAMAKERRE' },
                { id: 4887, name: 'KATENTEBERE' },
                { id: 4888, name: 'KYAKISEESE' },
                { id: 4889, name: 'RWENTUUHA' },
              ],
            },
            {
              id: 710,
              name: 'KASWA',
              villages: [
                { id: 4869, name: 'BUZIRASAGAMA' },
                { id: 4870, name: 'KANYANKUKURU' },
                { id: 4871, name: 'KASWA  A' },
                { id: 4872, name: 'KASWA  B' },
                { id: 63018, name: 'KASWA C' },
                { id: 4873, name: 'KIAMARA  A' },
                { id: 4874, name: 'KIAMARA  B' },
                { id: 4875, name: 'KIAMARA  C' },
                { id: 4876, name: 'KISAKYABAIRU' },
                { id: 64608, name: 'KYAMAKEMBA' },
                { id: 4877, name: 'KYAMAZIMA' },
                { id: 4878, name: 'MPANGA  A' },
                { id: 4879, name: 'MPANGA  B' },
                { id: 4880, name: 'MUGUSU  A' },
                { id: 4881, name: 'MUGUSU  B' },
                { id: 4882, name: 'SEBITOLI  A' },
                { id: 4883, name: 'SEBITOLI  B' },
              ],
            },
            {
              id: 9733,
              name: 'KIRERE',
              villages: [
                { id: 63497, name: 'KIGARAMA' },
                { id: 63804, name: 'KIRERE' },
                { id: 67937, name: 'NYABUSENYI  I' },
                { id: 67938, name: 'NYABUSENYI  II' },
                { id: 67939, name: 'NYABUSENYI  III' },
                { id: 68190, name: 'NYAMUGONGO' },
                { id: 70165, name: 'RWENGAJU A' },
              ],
            },
            {
              id: 709,
              name: 'RWENGAJU',
              villages: [
                { id: 4851, name: 'BAKEBWA' },
                { id: 4852, name: 'BUKONI' },
                { id: 4853, name: 'BUZINDA' },
                { id: 4854, name: 'KANSENENE' },
                { id: 4855, name: 'KATUNGUTA' },
                { id: 4856, name: 'KICUNA  A' },
                { id: 4857, name: 'KICUNA  B' },
                { id: 4858, name: 'KIDUBULI' },
                { id: 4859, name: 'KINYAIBUMBA' },
                { id: 4860, name: 'KYAKABAKA' },
                { id: 4861, name: 'KYATAMBASA' },
                { id: 4862, name: 'KYEMBOGO' },
                { id: 4863, name: 'MBAGANI' },
                { id: 4864, name: 'MUNIHYA' },
                { id: 4865, name: 'NSAHU' },
                { id: 4866, name: 'NYABWINA' },
                { id: 4867, name: 'RWENGAJU' },
                { id: 4868, name: 'TOP HILL' },
              ],
            },
          ],
        },
        {
          id: 148,
          name: 'HAKIBALE',
          parishes: [
            {
              id: 712,
              name: 'KAHANGI',
              villages: [
                { id: 4890, name: 'KAHANGI CENTRAL' },
                { id: 4891, name: 'KAYANJA' },
                { id: 4892, name: 'KYANSIMBI' },
                { id: 4893, name: 'KYAWANKANDA' },
              ],
            },
            {
              id: 715,
              name: 'KIBASI',
              villages: [
                { id: 59696, name: 'BULERA' },
                { id: 4910, name: 'BUNYONYI' },
                { id: 4911, name: 'HAKIBAALE' },
                { id: 4912, name: 'KIBASI' },
                { id: 4913, name: 'KIGANDO' },
                { id: 4914, name: 'KIYAGA' },
                { id: 4915, name: 'MIRONGO' },
                { id: 4916, name: 'RUKINGA' },
              ],
            },
            {
              id: 713,
              name: 'KIBURARA',
              villages: [
                { id: 4894, name: 'BWABYA' },
                { id: 4895, name: 'KATUMBA' },
                { id: 4896, name: 'KIBURARA' },
                { id: 4897, name: 'KIJENGA' },
                { id: 4898, name: 'MAHAMBA' },
                { id: 4899, name: 'MUHUMBU' },
                { id: 4900, name: 'MWOKYA' },
                { id: 4901, name: 'NYABUHUKA' },
                { id: 4902, name: 'NYAMIHOTI' },
              ],
            },
            {
              id: 714,
              name: 'KITULE',
              villages: [
                { id: 4903, name: 'KAKWORO' },
                { id: 4904, name: 'KIGORO' },
                { id: 4905, name: 'KYAKAGUJU' },
                { id: 4906, name: 'MUHANGI' },
                { id: 4907, name: 'MUHOIRE' },
                { id: 4908, name: 'RWABIHAMBA' },
                { id: 4909, name: 'RWENKUBA' },
              ],
            },
            {
              id: 9828,
              name: 'KYAMUHORO',
              villages: [
                { id: 61503, name: 'HAKIBAALE' },
                { id: 61683, name: 'ISUNGA' },
                { id: 63668, name: 'KIKOYO' },
                { id: 64561, name: 'KYAKASENYA' },
                { id: 64647, name: 'KYAMUHORO' },
                { id: 64702, name: 'KYARUBAIJA' },
                { id: 66299, name: 'MIRONGO' },
              ],
            },
            {
              id: 9837,
              name: 'KYARWAGONYA',
              villages: [
                { id: 63947, name: 'KISONGI' },
                { id: 64726, name: 'KYARWAGONYA' },
                { id: 67862, name: 'NTEZI  I' },
                { id: 67863, name: 'NTEZI  II' },
                { id: 68229, name: 'NYANTEMBO' },
              ],
            },
          ],
        },
        {
          id: 158,
          name: 'HARUGONGO',
          parishes: [
            {
              id: 748,
              name: 'BUSAIGA',
              villages: [
                { id: 5127, name: 'BUSAIGA A' },
                { id: 60259, name: 'BUSAIGA B' },
                { id: 5128, name: 'KIKONGE A' },
                { id: 63652, name: 'KIKONGE B' },
                { id: 64681, name: 'KYANKARA B' },
                { id: 5129, name: 'KYANKARRA A' },
              ],
            },
            {
              id: 749,
              name: 'KYAKAIGO',
              villages: [
                { id: 5130, name: 'BUCUMBI' },
                { id: 5132, name: 'BULYANYENJE' },
                { id: 5131, name: 'BUZINDA' },
                { id: 5137, name: 'HARUGONGO' },
                { id: 5138, name: 'KAKUNDWA' },
                { id: 5134, name: 'KANYATEETE' },
                { id: 5135, name: 'KICARAACA' },
                { id: 5139, name: 'KYAKAIGO' },
                { id: 5136, name: 'KYAMAHULI' },
                { id: 5133, name: 'MUGAMBA B' },
              ],
            },
            {
              id: 747,
              name: 'NYANTABOMA',
              villages: [
                { id: 5117, name: 'BUHARANE' },
                { id: 5119, name: 'BULEEGA' },
                { id: 5124, name: 'BULYAMBUZI A' },
                { id: 5116, name: 'BULYAMBUZI B' },
                { id: 5118, name: 'KABASANJA' },
                { id: 5120, name: 'KANYWANKOKO' },
                { id: 5121, name: 'KIKUUTA' },
                { id: 5125, name: 'MUGAMBA A' },
                { id: 5122, name: 'NYAKABIRA' },
                { id: 68020, name: 'NYAKAINA' },
                { id: 5126, name: 'NYANTABOMA' },
                { id: 5123, name: 'NYANTABOMA MPINGA' },
              ],
            },
          ],
        },
        {
          id: 159,
          name: 'KABENDE',
          parishes: [
            {
              id: 753,
              name: 'KYAKABASEKE',
              villages: [
                { id: 5155, name: 'BURUNGU' },
                { id: 5156, name: 'KARUTETE' },
                { id: 5158, name: 'KASOKERO' },
                { id: 5159, name: 'KYAKABASEKE' },
                { id: 5157, name: 'KYAKIHURA' },
                { id: 68098, name: 'NYAKIBUGUTA' },
              ],
            },
            {
              id: 751,
              name: 'KYAMWIRUKYA',
              villages: [
                { id: 5145, name: 'KABUZIGYE' },
                { id: 5147, name: 'KASESENGE' },
                { id: 5148, name: 'KYAMWIRUKYA' },
                { id: 5149, name: 'KYANGABUKAMA' },
                { id: 5146, name: 'NYAKABUNGO' },
                { id: 69949, name: 'RULONGO' },
                { id: 70303, name: 'SEMILIKI' },
              ],
            },
            {
              id: 750,
              name: 'MASONGORA',
              villages: [
                { id: 62203, name: 'KAKINDO' },
                { id: 5141, name: 'KANYABUHUKA' },
                { id: 5140, name: 'KANYAMIYAGA' },
                { id: 5144, name: 'KIBISO' },
                { id: 5142, name: 'MASONGORA' },
                { id: 5143, name: 'MUKIHARA' },
              ],
            },
            {
              id: 752,
              name: 'NDAIGA',
              villages: [
                { id: 61907, name: 'KABENDE A' },
                { id: 61908, name: 'KABENDE B' },
                { id: 5150, name: 'KABENDE CENTRE' },
                { id: 5151, name: 'KAMIRAMPANGO' },
                { id: 62837, name: 'KAROKURUNGI' },
                { id: 5153, name: 'KYABAKAMBI' },
                { id: 66628, name: 'MUNSISO' },
                { id: 5152, name: 'RWENJEYO' },
                { id: 5154, name: 'RWENSENENE' },
              ],
            },
          ],
        },
        {
          id: 157,
          name: 'KARAGO TOWN COUNCIL',
          parishes: [
            {
              id: 745,
              name: 'IBONDE WARD',
              villages: [
                { id: 5106, name: 'IBONDE  I' },
                { id: 5107, name: 'IBONDE  II' },
                { id: 5103, name: 'KALYANGO A' },
                { id: 5108, name: 'KALYANGO B' },
                { id: 5104, name: 'KITESWEKA' },
                { id: 5105, name: 'NJENGA' },
              ],
            },
            {
              id: 744,
              name: 'KARAGO WARD',
              villages: [
                { id: 5098, name: 'BUKUMBI' },
                { id: 5097, name: 'BUKUUKU' },
                { id: 5099, name: 'CANON APOLLO' },
                { id: 5102, name: 'KARAGO A' },
                { id: 5100, name: 'KARAGO B' },
                { id: 5101, name: 'KATUNGURU' },
              ],
            },
            {
              id: 746,
              name: 'KITARASA WARD',
              villages: [
                { id: 5109, name: 'BAGAAYA' },
                { id: 5110, name: 'BULERA A' },
                { id: 5112, name: 'BULERA B' },
                { id: 5111, name: 'BUSOMA A' },
                { id: 5113, name: 'BUSOMA B' },
                { id: 5115, name: 'KIKURA' },
                { id: 5114, name: 'KITARASA' },
              ],
            },
          ],
        },
        {
          id: 149,
          name: 'KARAMBI',
          parishes: [
            {
              id: 716,
              name: 'BUTEBE',
              villages: [
                { id: 4924, name: 'BUTANGWA' },
                { id: 4917, name: 'BUTEBE TRADING CENTRE' },
                { id: 4918, name: 'FUTI' },
                { id: 4925, name: 'KASINDIKWA' },
                { id: 4926, name: 'KIKUNYU' },
                { id: 4919, name: 'KINYAMAHAMBA' },
                { id: 4920, name: 'MBUZI' },
                { id: 4921, name: 'MUGOMA A' },
                { id: 4927, name: 'MUGOMA B' },
                { id: 4928, name: 'MUGOMA C' },
                { id: 4922, name: 'MUKONOMURA' },
                { id: 4929, name: 'NYAKITOKOLI' },
                { id: 4923, name: 'RWENKUBA' },
                { id: 4930, name: 'RWENKUBA-NYAKARONGO' },
              ],
            },
            {
              id: 719,
              name: 'GWERI',
              villages: [
                { id: 4952, name: 'BUHEESI' },
                { id: 4953, name: 'GAHOMUTWE' },
                { id: 4954, name: 'KADALI' },
                { id: 4955, name: 'KAGUSU' },
                { id: 4956, name: 'KIGAYA' },
                { id: 4957, name: 'MUGASANI' },
                { id: 4958, name: 'RWABAGANDA' },
              ],
            },
            {
              id: 717,
              name: 'KARAMBI',
              villages: [
                { id: 4931, name: 'BIRAYOROBA' },
                { id: 4932, name: 'BUSOKWA' },
                { id: 4933, name: 'HUMURA' },
                { id: 4934, name: 'KANGAMA' },
                { id: 4935, name: 'KARAMBI  I' },
                { id: 4936, name: 'KARAMBI  II' },
                { id: 4937, name: 'KIBOORO' },
                { id: 4938, name: 'KIDUKURU  A' },
                { id: 4939, name: 'KIDUKURU  B' },
                { id: 4940, name: 'MUSOMA/KYARUBOOGA' },
                { id: 4941, name: 'NYAKAINA/NJENGA' },
                { id: 4942, name: 'NYAKASANJA' },
                { id: 4943, name: 'NYAMITOMA' },
                { id: 4944, name: 'NYANSOZI' },
              ],
            },
            {
              id: 718,
              name: 'RUBINGO',
              villages: [
                { id: 4945, name: 'KABENDE' },
                { id: 4946, name: 'KASINDE' },
                { id: 4947, name: 'KIGWENGWE' },
                { id: 4948, name: 'KIKIIKE/KANYANSOHERA' },
                { id: 4949, name: 'MUGURA' },
                { id: 4950, name: 'MUKUMBWE' },
                { id: 4951, name: 'RUBINGO' },
              ],
            },
          ],
        },
        {
          id: 154,
          name: 'KARANGURA',
          parishes: [
            {
              id: 733,
              name: 'KAMABALE',
              villages: [
                { id: 5045, name: 'BUHIKIRA' },
                { id: 5049, name: 'KABANGO' },
                { id: 5050, name: 'KAMABALE A' },
                { id: 5046, name: 'KAMABALE B' },
                { id: 5051, name: 'KARANGURA' },
                { id: 62782, name: 'KARANGURA B' },
                { id: 5047, name: 'KASUNDI' },
                { id: 63182, name: 'KATUURRU' },
                { id: 5048, name: 'KITONYA' },
              ],
            },
            {
              id: 734,
              name: 'KIBWA',
              villages: [
                { id: 5052, name: 'BUTULYA UPPER' },
                { id: 5057, name: 'KAISULE' },
                { id: 5053, name: 'KIBWA A' },
                { id: 5054, name: 'KIBWA B' },
                { id: 5058, name: 'MAHYORO' },
                { id: 5055, name: 'MITOOMA' },
                { id: 68001, name: 'NYAKABURARA' },
                { id: 5056, name: 'NYAKARONGO' },
              ],
            },
            {
              id: 735,
              name: 'NYAKITOKOLI',
              villages: [
                { id: 5060, name: 'BIKUKURU' },
                { id: 5059, name: 'BUHAMIA' },
                { id: 5062, name: 'KAISAMBA' },
                { id: 5063, name: 'KAKINDO' },
                { id: 5064, name: 'KANYAMURA' },
                { id: 5061, name: 'KIBAGHA A' },
                { id: 5065, name: 'KIBAGHA B' },
                { id: 5072, name: 'KIGHUMU' },
                { id: 5066, name: 'KYABWIIRE' },
                { id: 5071, name: 'LWABALA' },
                { id: 5067, name: 'NYAKITOKOLI A' },
                { id: 5068, name: 'NYAKITOKOLI B' },
                { id: 5069, name: 'NYARUKAMBA A' },
                { id: 5070, name: 'NYARUKAMBA B' },
              ],
            },
          ],
        },
        {
          id: 153,
          name: 'KASENDA',
          parishes: [
            {
              id: 732,
              name: 'BURAMBIRA',
              villages: [
                { id: 5040, name: 'KANYANTE' },
                { id: 5041, name: 'KIBUGA  A' },
                { id: 5042, name: 'KIBUGA  B' },
                { id: 63568, name: 'KIHUMURO' },
                { id: 5043, name: 'KITOJO' },
                { id: 66507, name: 'MUHWEZI' },
                { id: 5044, name: 'NYABWEYA  A' },
                { id: 68049, name: 'NYAKASHOJWA' },
                { id: 68256, name: 'NYARUHANGA' },
              ],
            },
            {
              id: 729,
              name: 'ISUNGA',
              villages: [
                { id: 5028, name: 'IRUHUURA  A' },
                { id: 5029, name: 'IRUHUURA  B' },
                { id: 5030, name: 'ISUNGA' },
                { id: 61688, name: 'ISUNGA CENTRAL' },
                { id: 5031, name: 'NYABINYONYI' },
              ],
            },
            {
              id: 731,
              name: 'KYANTAMBARA',
              villages: [
                { id: 63769, name: 'KINYANGABO' },
                { id: 64546, name: 'KYAKAKWANZI' },
                { id: 5037, name: 'KYANGABUKAMA' },
                { id: 5038, name: 'KYANTAMBARA  A' },
                { id: 5039, name: 'KYANTAMBARA  B' },
                { id: 70238, name: 'RWIGO' },
              ],
            },
            {
              id: 730,
              name: 'NYABWEYA',
              villages: [
                { id: 59297, name: 'BUGANGANA' },
                { id: 5032, name: 'KINOMBE' },
                { id: 66728, name: 'MUTUKURA' },
                { id: 5033, name: 'NYABWEYA  B' },
                { id: 5034, name: 'NYABWEYA  C' },
                { id: 5035, name: 'RWENKUBA' },
                { id: 5036, name: 'RWERAZA A' },
                { id: 70223, name: 'RWERAZA B' },
              ],
            },
          ],
        },
        {
          id: 161,
          name: 'KASENDA TOWN COUNCIL',
          parishes: [
            {
              id: 760,
              name: 'KABATA WARD',
              villages: [
                { id: 5184, name: 'KABATA' },
                { id: 5185, name: 'KANYERIIRE' },
                { id: 5186, name: 'MWITAMPUNGU' },
                { id: 5187, name: 'NDALE' },
                { id: 68284, name: 'NYINAMBUGA' },
                { id: 5188, name: 'RUSONA' },
              ],
            },
            {
              id: 759,
              name: 'KASENDA WARD',
              villages: [
                { id: 5180, name: 'HAKABAALE' },
                { id: 62914, name: 'KASENDA CENTRAL' },
                { id: 5181, name: 'KICEERI' },
                { id: 63557, name: 'KIHOGO' },
                { id: 5182, name: 'KIMYA' },
                { id: 64091, name: 'KITOORO' },
                { id: 5183, name: 'RUGYENDE' },
              ],
            },
            {
              id: 761,
              name: 'RWANKENZI WARD',
              villages: [
                { id: 5189, name: 'BUSINGE' },
                { id: 5190, name: 'IRANGIZO' },
                { id: 5192, name: 'NSONGYA  A' },
                { id: 5193, name: 'NSONGYA  B' },
                { id: 5191, name: 'RWANKENZI CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 150,
          name: 'KICWAMBA',
          parishes: [
            {
              id: 720,
              name: 'BWANIKA',
              villages: [
                { id: 4959, name: 'BUHARA I' },
                { id: 4965, name: 'BUHARA II' },
                { id: 4966, name: 'BWANIKA' },
                { id: 61354, name: 'GEME A' },
                { id: 61355, name: 'GEME B' },
                { id: 4960, name: 'KAHONDO' },
                { id: 4961, name: 'KINYAMANGI' },
                { id: 4962, name: 'MAGUNGA' },
                { id: 4963, name: 'NYAMISINGIRI' },
                { id: 4964, name: 'NYANKWANZI A' },
                { id: 4967, name: 'NYANKWANZI B' },
              ],
            },
            {
              id: 721,
              name: 'KIHONDO',
              villages: [
                { id: 4968, name: 'BURONGO' },
                { id: 4969, name: 'BUTULYA' },
                { id: 4970, name: 'KAGOGO' },
                { id: 4971, name: 'KAGUMA' },
                { id: 4972, name: 'KANTARARA' },
                { id: 4973, name: 'KICWAMBA  I' },
                { id: 4974, name: 'KIHONDO' },
                { id: 4975, name: 'KIRANGARA' },
                { id: 4976, name: 'KITANGIRA' },
              ],
            },
            {
              id: 722,
              name: 'MABAALE',
              villages: [
                { id: 4977, name: 'KENJWENGE' },
                { id: 4979, name: 'KICWAMBA  II' },
                { id: 4980, name: 'KITUMBI' },
                { id: 4978, name: 'KYAMAIBA' },
                { id: 4981, name: 'MABAALE I' },
                { id: 4982, name: 'MABAALE II' },
                { id: 4983, name: 'NYABIBYA' },
                { id: 4984, name: 'NYANKUKU' },
              ],
            },
          ],
        },
        {
          id: 162,
          name: 'KIGUMA',
          parishes: [
            {
              id: 762,
              name: 'KIGUMA',
              villages: [
                { id: 5194, name: 'BUNYANSAIGI' },
                { id: 63447, name: 'KIDUBULI' },
                { id: 63525, name: 'KIGUMA' },
                { id: 5195, name: 'KIGUMA CENTRAL' },
                { id: 64551, name: 'KYAKANYOMERA' },
                { id: 64728, name: 'KYARWAMBOGO' },
                { id: 70568, name: 'SUPER JET' },
              ],
            },
            {
              id: 763,
              name: 'NYAKITOJO',
              villages: [
                { id: 5198, name: 'NYAKABIRA' },
                { id: 68111, name: 'NYAKITOJO CENTRAL' },
                { id: 5196, name: 'NYAKITOJO LOWER' },
                { id: 5197, name: 'NYAKITOJO UPPER' },
                { id: 70036, name: 'RWABINYIGINYA' },
              ],
            },
            {
              id: 764,
              name: 'RWENKUBA',
              villages: [
                { id: 63785, name: 'KIPAAPA' },
                { id: 63786, name: 'KIPAAPA UPPER' },
                { id: 5199, name: 'KYAMUHAMIRA' },
                { id: 64710, name: 'KYARUHAZA' },
                { id: 5200, name: 'RWENKUBA' },
              ],
            },
          ],
        },
        {
          id: 155,
          name: 'KIJURA TOWN COUNCIL',
          parishes: [
            {
              id: 737,
              name: 'KAHUUNA WARD',
              villages: [
                { id: 5077, name: 'BUTUKU  I' },
                { id: 5078, name: 'BUTUKU  II' },
                { id: 5079, name: 'NSORRO/KAHUUNA' },
              ],
            },
            {
              id: 738,
              name: 'KAISAGARA WARD',
              villages: [
                { id: 61502, name: 'HAKIBAALE' },
                { id: 5081, name: 'IGOGONYA' },
                { id: 5080, name: 'KABARANGA' },
                { id: 5082, name: 'KABASWISWI' },
                { id: 61888, name: 'KABASWISWI B' },
                { id: 5083, name: 'KAISAGARA' },
              ],
            },
            {
              id: 736,
              name: 'KIJURA WARD',
              villages: [
                { id: 5073, name: 'KATARAKA' },
                { id: 5074, name: 'KIHORA' },
                { id: 5075, name: 'KYAITAMBA  A' },
                { id: 5076, name: 'KYAITAMBA  B' },
              ],
            },
            {
              id: 739,
              name: 'KYEREREZI WARD',
              villages: [
                { id: 5084, name: 'KYEREREZI' },
                { id: 5085, name: 'MUBALI' },
                { id: 5086, name: 'NSORRO' },
              ],
            },
          ],
        },
        {
          id: 156,
          name: 'KIKO TOWN COUNCIL',
          parishes: [
            {
              id: 741,
              name: 'KASIISI WARD',
              villages: [
                { id: 5090, name: 'KASIISI' },
                { id: 5091, name: 'KIGARAMA' },
                { id: 5092, name: 'KIMUHONDE' },
              ],
            },
            {
              id: 740,
              name: 'KIKO WARD',
              villages: [
                { id: 5087, name: 'KANYAMBEHO A' },
                { id: 5088, name: 'KANYAMBEHO B' },
                { id: 5089, name: 'KIKO' },
              ],
            },
            {
              id: 742,
              name: 'KYANYAWARA WARD',
              villages: [
                { id: 5093, name: 'KASOJO' },
                { id: 5094, name: 'MAKOBYO A' },
                { id: 65962, name: 'MAKOBYO B' },
              ],
            },
            {
              id: 743,
              name: 'NYABUBAALE WARD',
              villages: [
                { id: 5095, name: 'NYABINAMBA' },
                { id: 5096, name: 'NYABUBAALE' },
              ],
            },
          ],
        },
        {
          id: 151,
          name: 'MUGUSU',
          parishes: [
            {
              id: 723,
              name: 'KIRAARO',
              villages: [
                { id: 4985, name: 'KANYAMUTWALE' },
                { id: 4986, name: 'KARWOMA' },
                { id: 4987, name: 'KIGAYA' },
                { id: 4988, name: 'MAGUNGA' },
                { id: 4989, name: 'RUKOOKO' },
              ],
            },
            {
              id: 725,
              name: 'KYEZIRE',
              villages: [
                { id: 4998, name: 'BARANGA' },
                { id: 4999, name: 'KABAGONA' },
                { id: 5000, name: 'KYAKIHIRA' },
                { id: 5001, name: 'KYAKIJARA' },
                { id: 5002, name: 'KYEZIRE' },
                { id: 5003, name: 'MYERI' },
                { id: 5004, name: 'NYAHANGA' },
                { id: 5005, name: 'NYAKASOJO' },
              ],
            },
            {
              id: 724,
              name: 'NYABUSWA',
              villages: [
                { id: 4991, name: 'BUBANDI' },
                { id: 4992, name: 'BURUNGU' },
                { id: 4993, name: 'BUTIMANGI' },
                { id: 4994, name: 'KARUNDO' },
                { id: 4995, name: 'KASIRIZA' },
                { id: 4990, name: 'KATUURU' },
                { id: 4996, name: 'KINYANKENDE' },
                { id: 4997, name: 'NYABUSWA' },
              ],
            },
          ],
        },
        {
          id: 160,
          name: 'MUGUSU TOWN COUNCIL',
          parishes: [
            {
              id: 756,
              name: 'BULINDA WARD',
              villages: [
                { id: 5170, name: 'BUTINDA' },
                { id: 5168, name: 'KIGARAMA' },
                { id: 5171, name: 'KIRAARO' },
                { id: 5169, name: 'MUGUSU TRADING CENTRE' },
              ],
            },
            {
              id: 754,
              name: 'BURUNGU WARD',
              villages: [
                { id: 5160, name: 'KIJONGO' },
                { id: 5161, name: 'KIRUGU' },
                { id: 5162, name: 'KYANDURU' },
              ],
            },
            {
              id: 757,
              name: 'KIBEDE WARD',
              villages: [
                { id: 5172, name: 'IBOROGA' },
                { id: 5173, name: 'KIBEEDE' },
                { id: 5174, name: 'MPARO' },
                { id: 5175, name: 'MUGUSU' },
                { id: 5176, name: 'NYANSOZI' },
              ],
            },
            {
              id: 755,
              name: 'KIBOHA WARD',
              villages: [
                { id: 5163, name: 'KITOJO' },
                { id: 5164, name: 'KYABAGAYANA' },
                { id: 5165, name: 'KYAKAWADURU' },
                { id: 5166, name: 'MPERRE' },
                { id: 5167, name: 'NYABATAAHI' },
              ],
            },
            {
              id: 758,
              name: 'KISERU WARD',
              villages: [
                { id: 5177, name: 'KAHUNGERE' },
                { id: 5178, name: 'KISERU' },
                { id: 5179, name: 'KYOGYA' },
              ],
            },
          ],
        },
        {
          id: 152,
          name: 'RUTEETE',
          parishes: [
            {
              id: 727,
              name: 'KYAMUKOKA',
              villages: [
                { id: 5014, name: 'IMARANJARA' },
                { id: 5015, name: 'KAMIGANI  A' },
                { id: 5016, name: 'KANYANDAHI' },
                { id: 5017, name: 'KYAMUSA' },
                { id: 5018, name: 'MITUULI' },
                { id: 5019, name: 'RUTEETE' },
                { id: 5020, name: 'RUTOMA' },
              ],
            },
            {
              id: 726,
              name: 'RURAMA',
              villages: [
                { id: 5006, name: 'BURUNDA' },
                { id: 5007, name: 'KYAKABUZI' },
                { id: 5008, name: 'NYAMIRIMA' },
                { id: 5009, name: 'NYARUZIGATI' },
                { id: 5010, name: 'RURAMA CENTRAL' },
                { id: 5011, name: 'RUSENYI  A' },
                { id: 5012, name: 'RUSENYI  B' },
                { id: 5013, name: 'RWETEERA' },
              ],
            },
            {
              id: 728,
              name: 'RWAIHAMBA',
              villages: [
                { id: 5021, name: 'KAMIGANI  B' },
                { id: 5022, name: 'KANYANSWIGA' },
                { id: 5023, name: 'KIFURUKA' },
                { id: 5024, name: 'KYAKATAAMA' },
                { id: 5025, name: 'KYANYAITAMBA' },
                { id: 5026, name: 'LYANTONDE' },
                { id: 5027, name: 'RWAIHAMBA' },
              ],
            },
          ],
        },
        {
          id: 2114,
          name: 'RWENGAJU',
          parishes: [
            {
              id: 9402,
              name: 'BWABYA',
              villages: [
                { id: 59077, name: 'BIKONI B' },
                { id: 59602, name: 'BUKONI A' },
                { id: 62551, name: 'KANSENENE' },
                { id: 63759, name: 'KINYAIBUMBA' },
                { id: 64780, name: 'KYEKAKERE' },
                { id: 66626, name: 'MUNIHYA' },
              ],
            },
            {
              id: 9684,
              name: 'KICUNA',
              villages: [
                { id: 58876, name: 'BAKEBWA' },
                { id: 63420, name: 'KICUNA  A' },
                { id: 63421, name: 'KICUNA  B' },
                { id: 64527, name: 'KYAKABAKA' },
                { id: 64787, name: 'KYEMBOGO' },
                { id: 66179, name: 'MBAGANI' },
                { id: 66441, name: 'MPARO' },
                { id: 70164, name: 'RWENGAJU' },
              ],
            },
            {
              id: 9686,
              name: 'KIDUBULI',
              villages: [
                { id: 60745, name: 'BUZINDA' },
                { id: 63171, name: 'KATUNGUTA' },
                { id: 63446, name: 'KIDUBULI' },
                { id: 64736, name: 'KYATAMBASA' },
                { id: 67820, name: 'NSAHU' },
                { id: 67947, name: 'NYABWINA' },
                { id: 70801, name: 'TOP HILL' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 31,
      name: 'FORT PORTAL MUNICIPALITY',
      sub_counties: [
        {
          id: 163,
          name: 'EASTERN DIVISION',
          parishes: [
            {
              id: 765,
              name: 'BUKWALI',
              villages: [
                { id: 5201, name: 'BWERA  A' },
                { id: 5202, name: 'BWERA  B' },
                { id: 5203, name: 'KISUMBI  A' },
                { id: 5204, name: 'KISUMBI  B' },
                { id: 5205, name: 'KISUMBI  C' },
                { id: 5206, name: 'NYAKABAALE  A' },
                { id: 5207, name: 'NYAKABAALE  B' },
              ],
            },
            {
              id: 766,
              name: 'KITUMBA',
              villages: [
                { id: 5208, name: 'BINANATA  A' },
                { id: 5209, name: 'BINANATA  B' },
                { id: 5210, name: 'BUGUNDA' },
                { id: 5211, name: 'KABEGIRA' },
                { id: 5212, name: 'KAIHOKWA' },
                { id: 5213, name: 'KITUMBA  A' },
                { id: 5214, name: 'KITUMBA  B' },
                { id: 5215, name: 'KITUMBA  C' },
                { id: 5216, name: 'KYOGYA' },
                { id: 5217, name: 'NYABINAMBA' },
              ],
            },
            {
              id: 767,
              name: 'NJARA',
              villages: [
                { id: 5218, name: 'BOOMA EAST' },
                { id: 5219, name: 'KAMENGO  A' },
                { id: 5220, name: 'KAMENGO  B' },
                { id: 5221, name: 'KITEBUTURA  A' },
                { id: 5222, name: 'KITEBUTURA  B' },
                { id: 5223, name: 'NJARA  A' },
                { id: 5224, name: 'NJARA  B' },
                { id: 5225, name: 'NJARA  C' },
                { id: 5226, name: 'POLICE BARRACKS' },
              ],
            },
            {
              id: 768,
              name: 'NYAKAGONGO',
              villages: [
                { id: 5227, name: 'BUKABYA' },
                { id: 5228, name: 'IHANI  A' },
                { id: 5229, name: 'IHANI  B' },
                { id: 5230, name: 'KANYAMAKERRE' },
                { id: 5231, name: 'KATENTEBERE' },
                { id: 5232, name: 'KYARWABUGODI/BURARO' },
                { id: 5233, name: 'KYEGOBE VILLAGE' },
                { id: 5234, name: 'MUKONOMURA' },
                { id: 5235, name: 'NYAKAGONGO' },
                { id: 5236, name: 'RWENKUBA' },
                { id: 5237, name: "ST. LEO's COLLEGE" },
              ],
            },
          ],
        },
        {
          id: 164,
          name: 'SOUTHERN DIVISION',
          parishes: [
            {
              id: 769,
              name: 'BAZAAR',
              villages: [
                { id: 5238, name: 'BUHINGA' },
                { id: 5239, name: 'HARUKOOTO  A' },
                { id: 5240, name: 'HARUKOOTO  B' },
                { id: 5241, name: 'KABAROLE HILL' },
                { id: 5242, name: 'KAHINJU ROAD' },
                { id: 5243, name: 'KASESE  ROAD' },
                { id: 5244, name: 'KIBOGA ROAD/LUGARD RD' },
                { id: 5245, name: 'KICULEETA' },
                { id: 5246, name: 'KITETE' },
                { id: 5247, name: 'MUGUNU/KISENYI' },
                { id: 5248, name: 'MUGURUSI ROAD' },
                { id: 5249, name: 'NYABURARA  A' },
                { id: 5250, name: 'NYABURARA  B' },
                { id: 5251, name: 'RUKIIDI STREET' },
              ],
            },
            {
              id: 770,
              name: 'KASUSU',
              villages: [
                { id: 5252, name: 'ISEKAHUNGU' },
                { id: 5253, name: 'KASUSU  A' },
                { id: 5254, name: 'KASUSU  B' },
                { id: 5255, name: 'KASUSU  C' },
                { id: 5256, name: 'KIDUKURU/KIHEMBO (A)' },
                { id: 5257, name: 'KIDUKURU/KIHEMBO (B)' },
                { id: 5258, name: 'NSORRO  A' },
                { id: 5259, name: 'NSORRO  B' },
              ],
            },
            {
              id: 771,
              name: 'KIJANJU',
              villages: [
                { id: 5260, name: 'KACWAMBA  A' },
                { id: 5261, name: 'KACWAMBA  B' },
                { id: 5262, name: 'KATUMBA  A' },
                { id: 5263, name: 'KATUMBA  B' },
                { id: 5264, name: 'KIJANJU  A' },
                { id: 5265, name: 'KIJANJU  B' },
                { id: 5266, name: 'KINYAMASIKA' },
                { id: 5267, name: 'MAGURU  A' },
                { id: 5268, name: 'MAGURU  B' },
                { id: 5269, name: 'MAGURU  C' },
                { id: 5270, name: 'VIRIKA' },
              ],
            },
          ],
        },
        {
          id: 165,
          name: 'WESTERN  DIVISION',
          parishes: [
            {
              id: 772,
              name: 'KAGOTE',
              villages: [
                { id: 5271, name: 'KAGOTE  A' },
                { id: 5272, name: 'KAGOTE  B' },
                { id: 5273, name: 'KAGOTE  C' },
                { id: 5274, name: 'KAGOTE D' },
              ],
            },
            {
              id: 773,
              name: 'KIBIMBA',
              villages: [
                { id: 5275, name: 'KASOJO/MUHOTI' },
                { id: 5276, name: 'KATOJO-KASINDIKWA' },
                { id: 5277, name: 'KIBIMBA  A' },
                { id: 5278, name: 'KIBIMBA  B' },
                { id: 5279, name: 'KITEERE' },
              ],
            },
            {
              id: 774,
              name: 'NYABUKARA',
              villages: [
                { id: 5280, name: 'BOMA WEST' },
                { id: 5281, name: 'BULYANYENJE' },
                { id: 5282, name: 'KYAMUKEREGE' },
                { id: 5283, name: 'MUKUBO' },
                { id: 5284, name: 'NYABUKARA' },
                { id: 5285, name: 'NYABUSOZI' },
              ],
            },
            {
              id: 775,
              name: 'RWENGOMA',
              villages: [
                { id: 5286, name: 'RWENGOMA  AI' },
                { id: 5287, name: 'RWENGOMA  AII' },
                { id: 5288, name: 'RWENGOMA  AIII' },
                { id: 5289, name: 'RWENGOMA  BI' },
                { id: 5290, name: 'RWENGOMA  BII' },
                { id: 5291, name: 'RWENGOMA  BIII' },
                { id: 5292, name: 'RWENGOMA  CI' },
                { id: 5293, name: 'RWENGOMA  CII' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
