import { District } from '../index';

export default {
  id: 92,
  name: 'KALIRO',
  counties: [
    {
      id: 227,
      name: 'BULAMOGI COUNTY',
      sub_counties: [
        {
          id: 1452,
          name: 'BUDOMERO',
          parishes: [
            {
              id: 6819,
              name: 'BUDOMERO',
              villages: [
                { id: 42743, name: 'BUGABWE-KASOZI' },
                { id: 42742, name: 'BUGABWE-NGOVA' },
                { id: 42744, name: 'BULANGIRA' },
                { id: 42746, name: 'BULEMO' },
                { id: 42747, name: 'KAHANGO' },
                { id: 42748, name: 'NABINYONYI' },
                { id: 42745, name: 'NAIRIKA T/C' },
                { id: 42749, name: 'NAIRIKA/KABULI' },
                { id: 42750, name: 'NAIRIKA/NAMUZIGO' },
                { id: 42751, name: 'NALUSENYE' },
                { id: 42752, name: 'NAMUKAKALA I' },
                { id: 42753, name: 'NAMUKALALA II' },
                { id: 42754, name: 'NAZIGOMERE' },
              ],
            },
            {
              id: 6820,
              name: 'KIYUNGA',
              villages: [
                { id: 42756, name: 'BUKYESA A' },
                { id: 42758, name: 'BUKYESA B' },
                { id: 42755, name: 'BUSALAMUKA' },
                { id: 42757, name: 'BUSEREKA' },
                { id: 42759, name: 'NAKIBUNGULYA' },
                { id: 42760, name: 'NAMUZIGO' },
              ],
            },
            {
              id: 6821,
              name: 'KYANFUBA',
              villages: [
                { id: 42762, name: 'BUKERE I' },
                { id: 42763, name: 'BUKERE II' },
                { id: 42764, name: 'BUKULIRA' },
                { id: 42765, name: 'KANANSUNA/KISIKI' },
                { id: 42766, name: 'KANANSUNA/KYANFUBBA' },
                { id: 42767, name: 'LUGINGO' },
                { id: 42761, name: 'LUGONGO-KISENYI' },
                { id: 42770, name: 'LUMBUYE-KANANSUNA' },
                { id: 42768, name: 'NABWENDE' },
                { id: 42769, name: 'NAMUZIGO/BUDAMBA' },
              ],
            },
            {
              id: 6822,
              name: 'NABITENDE',
              villages: [
                { id: 42771, name: 'BUGADA' },
                { id: 42773, name: 'KIGOODO' },
                { id: 42772, name: 'NABITENDE' },
                { id: 42774, name: 'NABUKALU' },
                { id: 42775, name: 'NAMAKUNYU' },
                { id: 42776, name: 'NAMAVUNDU A' },
                { id: 42777, name: 'NAMAVUNDU B' },
              ],
            },
          ],
        },
        {
          id: 1446,
          name: 'BULUMBA TOWN COUNCIL',
          parishes: [
            {
              id: 6789,
              name: 'BUJJEJJE WARD',
              villages: [
                { id: 58868, name: 'BAGALAMA' },
                { id: 59408, name: 'BUJEJJE' },
                { id: 59627, name: 'BUKUNYA' },
                { id: 59722, name: 'BULOMA' },
                { id: 42608, name: 'BUSIKWE' },
                { id: 65017, name: 'LAMBUYE' },
              ],
            },
            {
              id: 9327,
              name: 'BULUMBA CENTRAL WARD',
              villages: [
                { id: 59354, name: 'BUGUBI' },
                { id: 59433, name: 'BUKALIMO' },
                { id: 59435, name: 'BUKALIOMO MAIN' },
                { id: 59727, name: 'BULONDO' },
                { id: 66517, name: 'MUKASA' },
              ],
            },
            {
              id: 9381,
              name: 'BUSUNGA WARD',
              villages: [
                { id: 59858, name: 'BUMPI' },
                { id: 60406, name: 'BUSUNGA' },
                { id: 60805, name: 'BWISOBA' },
                { id: 70990, name: 'WAKWESA' },
              ],
            },
            {
              id: 6790,
              name: 'LONDE WARD',
              villages: [
                { id: 42609, name: 'KOSAMU' },
                { id: 42610, name: 'LONDE' },
                { id: 42611, name: 'MUKASA' },
                { id: 42612, name: 'ZEFANIA' },
                { id: 71248, name: 'ZEFANIA B' },
              ],
            },
            {
              id: 6791,
              name: 'MASUNA WARD',
              villages: [
                { id: 42613, name: 'BUGUBI' },
                { id: 42614, name: 'BUMPULI' },
                { id: 66101, name: 'MASUNA' },
                { id: 42615, name: 'NALENYA I' },
                { id: 42616, name: 'NALENYA II' },
              ],
            },
            {
              id: 10048,
              name: 'NALENYA WARD',
              villages: [
                { id: 60471, name: 'BUTITI' },
                { id: 67159, name: 'NALENYA I' },
                { id: 67160, name: 'NALENYA II' },
                { id: 67612, name: 'NATOLOKA' },
                { id: 67879, name: 'NUBIGA' },
              ],
            },
            {
              id: 6792,
              name: 'NKONTE WARD',
              villages: [
                { id: 58871, name: 'BAGOLE' },
                { id: 59674, name: 'BULANGILA' },
                { id: 42617, name: 'BULEJU' },
                { id: 42618, name: 'BULIMUKA' },
                { id: 59709, name: 'BULIMUKA B' },
                { id: 42619, name: 'BUNABALA' },
                { id: 60411, name: 'BUSUSWA' },
              ],
            },
          ],
        },
        {
          id: 1442,
          name: 'BUMANYA',
          parishes: [
            {
              id: 6769,
              name: 'BULIMA',
              villages: [
                { id: 42499, name: 'BULIMA' },
                { id: 42500, name: 'BULOMA I' },
                { id: 42501, name: 'BULOMA II' },
                { id: 42505, name: 'KASOZI' },
                { id: 42502, name: 'KIMUNYAGIRE' },
                { id: 66154, name: 'MAWULIRO' },
                { id: 42503, name: 'NABWEYO' },
                { id: 42504, name: 'NAIGAZI' },
                { id: 42506, name: 'WAKIRERE' },
              ],
            },
            {
              id: 6764,
              name: 'BUMANYA',
              villages: [
                { id: 42458, name: 'BULUMI' },
                { id: 42459, name: 'GENDWA I' },
                { id: 42465, name: 'GENDWA II' },
                { id: 42460, name: 'LUGINGO' },
                { id: 42461, name: 'LUGINGO B' },
                { id: 42462, name: 'NAMBULA/NABUKALU' },
                { id: 42463, name: 'WAMUBIRIGWE' },
                { id: 42464, name: 'WEMPERE' },
              ],
            },
            {
              id: 6767,
              name: 'KALALU',
              villages: [
                { id: 42482, name: 'KABIRI A' },
                { id: 42491, name: 'KABIRI B' },
                { id: 42483, name: 'KALALU  II' },
                { id: 42484, name: 'KALALU I' },
                { id: 42492, name: 'KALALU III' },
                { id: 42485, name: 'KANAMBATIKO' },
                { id: 42486, name: 'KANANSEGA A' },
                { id: 42490, name: 'KANANSEGA B' },
                { id: 42487, name: 'KANANTALE' },
                { id: 42488, name: 'NAMUZIGO A' },
                { id: 42489, name: 'NAMUZIGO B' },
              ],
            },
            {
              id: 6765,
              name: 'KASULETA',
              villages: [
                { id: 42466, name: 'KASULETA' },
                { id: 42467, name: 'NABIGWALI I' },
                { id: 42468, name: 'NABIGWALLI II' },
                { id: 42469, name: 'NAIGAZI' },
                { id: 42470, name: 'TAKIRA  I' },
                { id: 42473, name: 'TAKIRA CENTRAL' },
                { id: 42471, name: 'TAKIRA II' },
                { id: 42472, name: 'TAKIRA III' },
              ],
            },
            {
              id: 6766,
              name: 'KYANI',
              villages: [
                { id: 42474, name: 'KANANZOKI' },
                { id: 42480, name: 'KINAMAGOYE' },
                { id: 42475, name: 'KISENYE' },
                { id: 42481, name: 'KYANI - NYANZA B' },
                { id: 42476, name: 'KYANI T/C' },
                { id: 42477, name: 'KYANI/NYANZA A' },
                { id: 42478, name: 'NAIBINGA' },
                { id: 42479, name: 'NAKABALE' },
                { id: 67296, name: 'NAMBULA' },
              ],
            },
            {
              id: 6768,
              name: 'NAMUSOLO',
              villages: [
                { id: 42493, name: 'BUBBUMBI' },
                { id: 42494, name: 'IHAGALO' },
                { id: 61574, name: 'IHAGALO B' },
                { id: 42495, name: 'KIYUNGA' },
                { id: 42496, name: 'NAMBULA' },
                { id: 42497, name: 'NAMUNYA A' },
                { id: 42498, name: 'NAMUNYA B' },
              ],
            },
          ],
        },
        {
          id: 1448,
          name: 'BUYINDA',
          parishes: [
            {
              id: 6799,
              name: 'BUKONDE',
              villages: [
                { id: 42643, name: 'BUDABA' },
                { id: 42641, name: 'BUKONDE  A' },
                { id: 42642, name: 'BUKONDE  B' },
                { id: 42644, name: 'BUKONDE C' },
                { id: 42645, name: 'KIBUYE A' },
                { id: 42646, name: 'KIBUYE B' },
              ],
            },
            {
              id: 6798,
              name: 'BUYINDA',
              villages: [
                { id: 42635, name: 'BULAGO A' },
                { id: 42640, name: 'BULAGO B' },
                { id: 42636, name: 'BUTONGOLE' },
                { id: 42637, name: 'MAKUUTU' },
                { id: 42638, name: 'NABIINA A' },
                { id: 42639, name: 'NABIINA B' },
              ],
            },
            {
              id: 6800,
              name: 'KIRANGA',
              villages: [
                { id: 42647, name: 'KIRANGA A' },
                { id: 42648, name: 'KIRANGA B' },
                { id: 42649, name: 'KIRANGA C' },
                { id: 42650, name: 'KIRANGA TOWN' },
                { id: 42651, name: 'NAMUNINGE' },
              ],
            },
            {
              id: 6801,
              name: 'MADIBIRA',
              villages: [
                { id: 42652, name: 'KASULETA' },
                { id: 42653, name: 'KIKOOGE A' },
                { id: 42656, name: 'KIKOOGE B' },
                { id: 42654, name: 'KIRAMA A' },
                { id: 42655, name: 'KIRAMA B' },
                { id: 42657, name: 'MADIBIRA A' },
                { id: 42658, name: 'MADIBIRA B' },
                { id: 42659, name: 'NAMAYOBYO' },
              ],
            },
            {
              id: 6803,
              name: 'NAMEJJE',
              villages: [
                { id: 42664, name: 'KEREBU A' },
                { id: 42667, name: 'KEREBU B' },
                { id: 42665, name: 'NAMEJJE  A' },
                { id: 42666, name: 'NAMEJJE  B' },
                { id: 42668, name: 'NAMEJJE C' },
              ],
            },
            {
              id: 6802,
              name: 'WANGOBO',
              villages: [
                { id: 42660, name: 'BUKUNYA' },
                { id: 42661, name: 'KANABUGO A' },
                { id: 42663, name: 'NABUHAALI' },
                { id: 42662, name: 'WAMPITEKU' },
              ],
            },
          ],
        },
        {
          id: 1443,
          name: 'GADUMIRE',
          parishes: [
            {
              id: 6770,
              name: 'BUPYANA',
              villages: [
                { id: 42507, name: 'BUKERE' },
                { id: 42508, name: 'BUVUNDYA' },
                { id: 42509, name: 'KIRANGA A' },
                { id: 63792, name: 'KIRANGA B' },
                { id: 42510, name: 'KYAMBA' },
                { id: 42512, name: 'NAMUKOKO' },
                { id: 42511, name: 'NANSOHERA' },
                { id: 67471, name: 'NANSOHERA B' },
              ],
            },
            {
              id: 6774,
              name: 'BUTAMBALA',
              villages: [
                { id: 42529, name: 'BUBALALA' },
                { id: 42530, name: 'BUDONGO' },
                { id: 42531, name: 'BUSERU' },
                { id: 42532, name: 'BUTAMBALA' },
                { id: 61660, name: 'IREHE' },
                { id: 67028, name: 'NAKAWA' },
              ],
            },
            {
              id: 6775,
              name: 'BUYUGE',
              villages: [
                { id: 42533, name: 'BUWUMBA' },
                { id: 42534, name: 'KABWIKWA/KABEGA' },
                { id: 42535, name: 'KAYIIRA A' },
                { id: 63228, name: 'KAYIIRA B' },
                { id: 42536, name: 'NAKANA' },
              ],
            },
            {
              id: 6771,
              name: 'GADUMIRE',
              villages: [
                { id: 42513, name: 'BUGADA/BUSEREKA' },
                { id: 42516, name: 'BUGONYA' },
                { id: 59954, name: 'BUNABIRO' },
                { id: 42515, name: 'BUSUSWA' },
                { id: 42514, name: 'GADUMIRE TRADING CENTRE' },
                { id: 42517, name: 'WAMUSUTA' },
              ],
            },
            {
              id: 6773,
              name: 'ISALO',
              villages: [
                { id: 42525, name: 'BUSIGINYI' },
                { id: 60510, name: 'BUTWOOLI' },
                { id: 42526, name: 'BWISANGA' },
                { id: 42527, name: 'ISAALO' },
                { id: 42528, name: 'LUHUNGA' },
              ],
            },
            {
              id: 6772,
              name: 'PANYOLO',
              villages: [
                { id: 42524, name: 'BUSEEGE' },
                { id: 42518, name: 'BUSIRO' },
                { id: 42519, name: 'BUSIRO CENTRAL' },
                { id: 42521, name: 'BUSIRO TABINA' },
                { id: 42520, name: 'IGULILYO' },
                { id: 42522, name: 'LAKE NAKUWA' },
                { id: 67074, name: 'NAKISENYI' },
                { id: 42523, name: 'NYOLO' },
              ],
            },
            {
              id: 6776,
              name: 'TABABA',
              villages: [
                { id: 42537, name: 'BUKOOTI' },
                { id: 60286, name: 'BUSEETA' },
                { id: 42538, name: 'KIBEMBE' },
                { id: 42539, name: 'KIBEMBE B' },
                { id: 66606, name: 'MULUNGU' },
                { id: 42540, name: 'NAMUHONDO' },
                { id: 42541, name: 'NANSIONO' },
                { id: 42542, name: 'NASERE' },
              ],
            },
          ],
        },
        {
          id: 1447,
          name: 'KALIRO TOWN COUNCIL',
          parishes: [
            {
              id: 6794,
              name: 'BUDINI WARD',
              villages: [
                { id: 42623, name: 'BAMUTAZE' },
                { id: 58893, name: 'BAMUTAZE B' },
                { id: 58894, name: 'BAMUTAZE C' },
                { id: 42624, name: 'MISSION' },
                { id: 66311, name: 'MISSION B' },
                { id: 66312, name: 'MISSION C' },
                { id: 42625, name: 'NYANZA' },
                { id: 68235, name: 'NYANZA B' },
              ],
            },
            {
              id: 6793,
              name: 'BUKUMANKOOLA WARD',
              villages: [
                { id: 59191, name: 'BRIGHT FITURE' },
                { id: 42620, name: 'BUGOMA' },
                { id: 59348, name: 'BUGOMA B' },
                { id: 59349, name: 'BUGOMA C' },
                { id: 59419, name: 'BUKADAMA' },
                { id: 59473, name: 'BUKAVIRI' },
                { id: 42621, name: 'KIRINDI' },
                { id: 63822, name: 'KIRINDI B' },
                { id: 42622, name: 'MWANGHA' },
                { id: 66761, name: 'MWANGHA B' },
              ],
            },
            {
              id: 6796,
              name: 'BUYUNGA WARD',
              villages: [
                { id: 42629, name: 'BUSOMA' },
                { id: 42630, name: 'BUWALUJJO' },
                { id: 61568, name: 'IGOMBE LUBOWA' },
                { id: 66556, name: 'MUKUNGU' },
                { id: 66704, name: 'MUSUMA B' },
                { id: 66981, name: 'NAKABALE' },
                { id: 42631, name: 'NAKIYANJA' },
                { id: 67089, name: 'NAKIYANJA B' },
                { id: 67090, name: 'NAKIYANJA C' },
                { id: 69533, name: 'PALISA ISMA' },
              ],
            },
            {
              id: 6797,
              name: 'LUMBUYE WARD',
              villages: [
                { id: 42632, name: 'INDUSTRIAL AREA' },
                { id: 61631, name: 'INDUSTRIAL AREA B' },
                { id: 61632, name: 'INDUSTRIAL AREA C' },
                { id: 61633, name: 'INDUSTRIAL AREA D' },
                { id: 62331, name: 'KALINTUSI B' },
                { id: 62332, name: 'KALINTUSI C' },
                { id: 42633, name: 'KALITUNSI' },
                { id: 42634, name: 'VALLEY HILL' },
                { id: 70949, name: 'VALLEY HILL B' },
                { id: 70950, name: 'VALLEY HILL C' },
                { id: 70951, name: 'VALLEY HILL D' },
              ],
            },
            {
              id: 6795,
              name: 'NAIGOMBWA WARD',
              villages: [
                { id: 42626, name: 'BUGABWE' },
                { id: 59282, name: 'BUGABWE B' },
                { id: 42627, name: 'BULANGIRA' },
                { id: 59680, name: 'BULANGIRA B' },
                { id: 42628, name: 'ZIBONDO' },
                { id: 71250, name: 'ZIBONDO B' },
              ],
            },
          ],
        },
        {
          id: 1449,
          name: 'KASOKWE',
          parishes: [
            {
              id: 6808,
              name: 'BUSANDA',
              villages: [
                { id: 42696, name: 'BULANGIRA' },
                { id: 42693, name: 'BUSANDA' },
                { id: 42694, name: 'BUSANDA B' },
                { id: 42695, name: 'BUSANDA C' },
                { id: 65937, name: 'MAKERE' },
              ],
            },
            {
              id: 6805,
              name: 'BUTAJJUBE',
              villages: [
                { id: 42675, name: 'BUKAKUBBE' },
                { id: 42676, name: 'BUTUJU' },
                { id: 42677, name: 'BUYIGANGAINE' },
                { id: 42678, name: 'KALALU' },
                { id: 42679, name: 'NAKABALE' },
              ],
            },
            {
              id: 6807,
              name: 'BUYODI',
              villages: [
                { id: 42687, name: 'BUGOODO' },
                { id: 42688, name: 'BUNAITA-BUJJOGO' },
                { id: 42690, name: 'BUTONGOLE' },
                { id: 42691, name: 'BUYODI/KIBOYO' },
                { id: 42692, name: 'KIRUMBI-KIBWAKUSIO' },
                { id: 42689, name: 'NYAKYATO' },
              ],
            },
            {
              id: 6804,
              name: 'BWAYUYA',
              villages: [
                { id: 42669, name: 'BUTESA A' },
                { id: 42672, name: 'BUTESA B' },
                { id: 42670, name: 'BWAYUYA A' },
                { id: 42671, name: 'BWAYUYA B' },
                { id: 42673, name: 'BWAYUYA C' },
                { id: 42674, name: 'BWAYUYA TRADING CENTRE' },
              ],
            },
            {
              id: 6806,
              name: 'KASOKWE',
              villages: [
                { id: 42681, name: 'BUKONGOLO' },
                { id: 42680, name: 'BUSIBA' },
                { id: 42682, name: 'BUYODI KINANTAMA' },
                { id: 42685, name: 'KASOKWE NKALU B' },
                { id: 42686, name: 'KASOKWE T/C' },
                { id: 42683, name: 'KASOKWE/KIBOYO' },
                { id: 42684, name: 'NKALU A' },
              ],
            },
          ],
        },
        {
          id: 1450,
          name: 'KISINDA',
          parishes: [
            {
              id: 6811,
              name: 'BUSULUMBA',
              villages: [
                { id: 42706, name: 'BUKAYALE A' },
                { id: 42707, name: 'BUKAYALE B' },
                { id: 42708, name: 'BUTANGA' },
                { id: 42709, name: 'KYONAMUSA' },
                { id: 42710, name: 'NAKIKONDO' },
                { id: 42712, name: 'NAMUMBYA' },
                { id: 42713, name: 'NANTAHAYA' },
                { id: 42711, name: 'NYENDE' },
              ],
            },
            {
              id: 6813,
              name: 'KIBWIZA',
              villages: [
                { id: 42719, name: 'KAMUTAKA' },
                { id: 42720, name: 'KIBEMBE A' },
                { id: 42722, name: 'KIBEMBE B' },
                { id: 42721, name: 'KIBWIIZA' },
                { id: 63406, name: 'KIBWIIZA B' },
                { id: 42723, name: 'NAKAKOOGE' },
              ],
            },
            {
              id: 6810,
              name: 'KISINDA',
              villages: [
                { id: 42705, name: 'BUHOMBI' },
                { id: 42702, name: 'BUKUNYA' },
                { id: 42700, name: 'BUKUNYA TRADING CENTRE' },
                { id: 42703, name: 'NAKABOKO' },
                { id: 42704, name: 'NAMUNTU' },
                { id: 42701, name: 'NSULUMBI' },
              ],
            },
            {
              id: 6809,
              name: 'LUBULO',
              villages: [
                { id: 42697, name: 'KIBAALE A' },
                { id: 63333, name: 'KIBAALE B' },
                { id: 42698, name: 'MAHUMO A' },
                { id: 65904, name: 'MAHUMO B' },
                { id: 42699, name: 'NAMASAKA A' },
                { id: 67253, name: 'NAMASAKA B' },
              ],
            },
            {
              id: 6814,
              name: 'MPAMBWA',
              villages: [
                { id: 42724, name: 'LWAMBOGA A' },
                { id: 42725, name: 'LWAMBOGA B' },
                { id: 42726, name: 'MPAMBWA A' },
                { id: 66433, name: 'MPAMBWA B' },
                { id: 42727, name: 'NANDERE A' },
                { id: 67420, name: 'NANDERE B' },
              ],
            },
            {
              id: 6812,
              name: 'NAWANDYO',
              villages: [
                { id: 42714, name: 'BULEEMO' },
                { id: 42716, name: 'IGEMBE' },
                { id: 42718, name: 'KIROBA' },
                { id: 42715, name: 'NABWEYO' },
                { id: 42717, name: 'NAWANDYO' },
              ],
            },
          ],
        },
        {
          id: 1444,
          name: 'NAMUGONGO',
          parishes: [
            {
              id: 6783,
              name: 'BUGODA',
              villages: [
                { id: 42578, name: 'BUGODA' },
                { id: 42579, name: 'BUTINDA' },
                { id: 42580, name: 'KALUNGU' },
                { id: 62995, name: 'KASOZI' },
                { id: 42581, name: 'KASULETA' },
              ],
            },
            {
              id: 6777,
              name: 'BUGONZA',
              villages: [
                { id: 42543, name: 'BUDANGHA/BULALA' },
                { id: 42545, name: 'BUHODI' },
                { id: 42546, name: 'BUKONGOLE' },
                { id: 42544, name: 'NABIRERE' },
                { id: 42547, name: 'NAKALANGA' },
              ],
            },
            {
              id: 6778,
              name: 'BUTEGE',
              villages: [
                { id: 42548, name: 'KANANTEGE' },
                { id: 42552, name: 'KANANTEGE B' },
                { id: 42549, name: 'KITALIKIKYO' },
                { id: 42550, name: 'NAKISENYI' },
                { id: 42551, name: 'WAKUKUUTA' },
                { id: 42553, name: 'WAKUKUUTA B' },
              ],
            },
            {
              id: 6784,
              name: 'IGULAMUBIRI',
              villages: [
                { id: 42582, name: 'IGULAMUBIRI A' },
                { id: 42585, name: 'IGULAMUBIRI B' },
                { id: 42583, name: 'NABINYONYI' },
                { id: 42584, name: 'NAKABALE' },
              ],
            },
            {
              id: 6782,
              name: 'KANAKAMBA',
              villages: [
                { id: 42576, name: 'BUHULULAIRE' },
                { id: 59383, name: 'BUHULULAIRE B' },
                { id: 42574, name: 'BULOGO' },
                { id: 42575, name: 'BULYANKOKO' },
                { id: 42577, name: 'BUSOOBA' },
              ],
            },
            {
              id: 6779,
              name: 'NABIKOOLI',
              villages: [
                { id: 42554, name: 'BUKULABWIRE' },
                { id: 42555, name: 'BUKULABWIRE B' },
                { id: 42557, name: 'KAJANABULWAIRE A' },
                { id: 42559, name: 'KAJANABULWAIRE B' },
                { id: 42556, name: 'LUMBUYE' },
                { id: 42558, name: 'NAMAKANDA A' },
                { id: 42560, name: 'NAMAKANDA B' },
              ],
            },
            {
              id: 6780,
              name: 'NAMUKOOGE',
              villages: [
                { id: 42562, name: 'BUKIGIKI' },
                { id: 42563, name: 'BUKIGIKI B' },
                { id: 42564, name: 'NAKYERE' },
                { id: 42566, name: 'NAKYERE B' },
                { id: 42561, name: 'NAMUKOOGE T/C' },
                { id: 42565, name: 'SIRIKA' },
              ],
            },
            {
              id: 6781,
              name: 'NATWANA',
              villages: [
                { id: 42567, name: 'BULONDO/BUBONGO A' },
                { id: 42573, name: 'BULONDO/BUBONGO B' },
                { id: 42568, name: 'N.T.C KALIRO' },
                { id: 42569, name: 'NATWANA' },
                { id: 42572, name: 'NATWANA B' },
                { id: 42570, name: 'NYALINYALI' },
                { id: 42571, name: 'NYALINYALI B' },
              ],
            },
          ],
        },
        {
          id: 1445,
          name: 'NAMWIWA',
          parishes: [
            {
              id: 6788,
              name: 'KIGANDA',
              villages: [
                { id: 42604, name: 'IZINGA A' },
                { id: 42607, name: 'IZINGA B' },
                { id: 42605, name: 'KIGANDA A' },
                { id: 42606, name: 'KIGANDA B' },
                { id: 42603, name: 'KITUKIRO' },
              ],
            },
            {
              id: 6787,
              name: 'KIWANABUZI',
              villages: [
                { id: 42600, name: 'KIWA A' },
                { id: 64123, name: 'KIWA B' },
                { id: 42601, name: 'NABUZZI' },
                { id: 42602, name: 'NAWANGOMA A' },
                { id: 67642, name: 'NAWANGOMA B' },
              ],
            },
            {
              id: 6785,
              name: 'NAMWIWA',
              villages: [
                { id: 42588, name: 'BULUGULI' },
                { id: 42587, name: 'BUSAMBEKO  B' },
                { id: 42586, name: 'BUSAMBEKO A' },
                { id: 42589, name: 'NAMUGERA' },
                { id: 42590, name: 'NAMWIWA B' },
              ],
            },
            {
              id: 6786,
              name: 'SAAKA',
              villages: [
                { id: 42591, name: 'BUGUGE' },
                { id: 42594, name: 'BUKEREHE' },
                { id: 42595, name: 'BWISANGA' },
                { id: 42596, name: 'IGEREKA' },
                { id: 42592, name: 'KAKOSI A' },
                { id: 42593, name: 'KAKOSI B' },
                { id: 42599, name: 'KAKOSI C' },
                { id: 42598, name: 'SAAKA A' },
                { id: 42597, name: 'SAAKA B' },
              ],
            },
          ],
        },
        {
          id: 1451,
          name: 'NAMWIWA TOWN COUNCIL',
          parishes: [
            {
              id: 6815,
              name: 'BUKAIRE WARD',
              villages: [
                { id: 42731, name: 'BUKAIRE' },
                { id: 59421, name: 'BUKAIRE B' },
                { id: 59626, name: 'BUKUNYA' },
                { id: 42728, name: 'KANABUGO B' },
                { id: 42730, name: 'WANGOBO  B' },
                { id: 42729, name: 'WANGOBO A' },
              ],
            },
            {
              id: 6816,
              name: 'BULARI WARD',
              villages: [
                { id: 42734, name: 'BIRAALI' },
                { id: 59751, name: 'BULUUKO' },
                { id: 42732, name: 'KAVULE A' },
                { id: 63189, name: 'KAVULE B' },
                { id: 67369, name: 'NAMULUNGU TC' },
                { id: 42733, name: 'NAWANGOMA' },
              ],
            },
            {
              id: 6817,
              name: 'BUNSWEZYA WARD',
              villages: [
                { id: 42737, name: 'BUNSWEZYA' },
                { id: 60453, name: 'BUTENDE' },
                { id: 42736, name: 'KAKWANGALA B' },
                { id: 66715, name: 'MUTOME' },
                { id: 42735, name: 'NAKWANGALA A' },
              ],
            },
            {
              id: 9374,
              name: 'BUSEREKA WARD',
              villages: [
                { id: 59014, name: 'BAZIRABAIRA' },
                { id: 59340, name: 'BUGOBOLO' },
                { id: 60300, name: 'BUSEREKA A' },
                { id: 60301, name: 'BUSEREKA B' },
                { id: 66489, name: 'MUGIRE' },
              ],
            },
            {
              id: 9589,
              name: 'KANABUGO WARD',
              villages: [
                { id: 62502, name: 'KANABUGO A' },
                { id: 63030, name: 'KATALAKABI' },
                { id: 70595, name: 'TALINA' },
                { id: 71009, name: 'WAMPITEKU' },
                { id: 71054, name: 'WANGOBO  B' },
              ],
            },
            {
              id: 6818,
              name: 'NAMWIWA WARD',
              villages: [
                { id: 58869, name: 'BAGANZI' },
                { id: 42739, name: 'BUGOBOLO' },
                { id: 42738, name: 'BUSEREKA A' },
                { id: 61324, name: 'GABWIIRE' },
                { id: 42741, name: 'MUTENDERI' },
                { id: 42740, name: 'NAMWIWA  A' },
              ],
            },
            {
              id: 10339,
              name: 'WANGOBO WARD',
              villages: [
                { id: 60178, name: 'BUNGUBEKA' },
                { id: 66866, name: 'NABUHALI' },
                { id: 71055, name: 'WANGOBO A' },
                { id: 71056, name: 'WANGOBO C' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 228,
      name: 'BULAMOGI NORTH WEST COUNTY',
      sub_counties: [
        {
          id: 1453,
          name: 'BUKAMBA',
          parishes: [
            {
              id: 6823,
              name: 'BUJUGU',
              villages: [
                { id: 42779, name: 'ISOOBA' },
                { id: 42780, name: 'KANABI A' },
                { id: 42778, name: 'KANABI B' },
                { id: 42783, name: 'KISU B' },
                { id: 42781, name: 'KITENGA A' },
                { id: 42782, name: 'KITENGA B' },
              ],
            },
            {
              id: 6827,
              name: 'BUKAMBA',
              villages: [
                { id: 42812, name: 'BEEDA A' },
                { id: 42814, name: 'BEEDA B' },
                { id: 42809, name: 'BUKAMBA A' },
                { id: 42813, name: 'BUKAMBA B' },
                { id: 65759, name: 'LWAMBA A' },
                { id: 42810, name: 'LWAMBA B' },
                { id: 42811, name: 'LWAMBA C' },
              ],
            },
            {
              id: 6825,
              name: 'BUSEREKA',
              villages: [
                { id: 42796, name: 'BUGALIMU' },
                { id: 42793, name: 'BUGOLYO' },
                { id: 42794, name: 'BUSEREKA' },
                { id: 42795, name: 'KISANGA' },
                { id: 42797, name: 'KUNYA' },
                { id: 42798, name: 'KYAKYAMPASA A' },
                { id: 64590, name: 'KYAKYAMPASA B' },
              ],
            },
            {
              id: 6824,
              name: 'BUVULUNGUTI',
              villages: [
                { id: 42784, name: 'BUVULUNGUTI' },
                { id: 42790, name: 'BUVULUNGUTI EAST' },
                { id: 42791, name: 'BUVULUNGUTI WEST' },
                { id: 42785, name: 'BUZAAYA A' },
                { id: 42792, name: 'BUZAAYA B' },
                { id: 42786, name: 'KIBUYE A' },
                { id: 42787, name: 'KIBUYE B' },
                { id: 42788, name: 'KIBUYE C' },
                { id: 42789, name: 'KIBUYE D' },
              ],
            },
            {
              id: 6826,
              name: 'KITEGA',
              villages: [
                { id: 42800, name: 'BUKUNYA A' },
                { id: 42805, name: 'BUKUNYA B' },
                { id: 42799, name: 'BUNENE' },
                { id: 42802, name: 'KASULETA A' },
                { id: 42806, name: 'KASULETA B' },
                { id: 42801, name: 'KITEGA A' },
                { id: 64014, name: 'KITEGA B' },
                { id: 42803, name: 'NABUSIRA A' },
                { id: 42807, name: 'NABUSIRA B' },
                { id: 42804, name: 'NAKIBUNGULYA A' },
                { id: 42808, name: 'NAKIBUNGULYA B' },
              ],
            },
            {
              id: 6828,
              name: 'NANGALA',
              villages: [
                { id: 42815, name: 'BUZINGE T/C' },
                { id: 63962, name: 'KISU A' },
                { id: 42819, name: 'KUUTO A' },
                { id: 42816, name: 'KUUTO B' },
                { id: 42818, name: 'MUTUMIZI' },
                { id: 42820, name: 'MUTUMIZI A' },
                { id: 42817, name: 'MUTUMIZI B' },
              ],
            },
            {
              id: 6829,
              name: 'NAWAMPITI',
              villages: [
                { id: 42825, name: 'KABOLE' },
                { id: 42821, name: 'KAGWA' },
                { id: 42822, name: 'KISIRA' },
                { id: 42826, name: 'LUGONYOLA' },
                { id: 65602, name: 'LUGONYOLA B' },
                { id: 42823, name: 'LYADA' },
                { id: 42824, name: 'NDOLI' },
                { id: 67684, name: 'NDOLI B' },
                { id: 42827, name: 'SEMUTEWO' },
                { id: 42828, name: 'WALULALO' },
                { id: 42829, name: 'WOIRA' },
              ],
            },
          ],
        },
        {
          id: 1454,
          name: 'NANSOLOLO',
          parishes: [
            {
              id: 9320,
              name: 'BULIKE',
              villages: [
                { id: 59249, name: 'BUBWIIKA' },
                { id: 59261, name: 'BUDEEBA A' },
                { id: 59262, name: 'BUDEEBA B' },
                { id: 59593, name: 'BUKOMAHO' },
                { id: 68306, name: 'NZIRAKAYINDI A' },
                { id: 68307, name: 'NZIRAKAYINDI B' },
              ],
            },
            {
              id: 6832,
              name: 'BULUYA',
              villages: [
                { id: 42850, name: 'AZALIYA BALISULEYO' },
                { id: 42849, name: 'BALISULEYO' },
                { id: 42854, name: 'BULAWA' },
                { id: 42855, name: 'BUNANGWE' },
                { id: 42856, name: 'BUSUSWA' },
                { id: 42851, name: 'KOSIYA KALUYA' },
                { id: 42852, name: 'KYALIZWANYUMA' },
                { id: 42853, name: 'PEREZI KASAJJA' },
              ],
            },
            {
              id: 6830,
              name: 'MUHIRA',
              villages: [
                { id: 42830, name: 'BULUYA II' },
                { id: 42838, name: 'BUSENKE' },
                { id: 42840, name: 'IKONERO' },
                { id: 42831, name: 'ISOOBA MALE' },
                { id: 42832, name: 'KIHOLERE' },
                { id: 42833, name: 'MULI  I' },
                { id: 42839, name: 'MULI I T/C' },
                { id: 42834, name: 'MULI II' },
                { id: 42835, name: 'NAIVULUNGUTI A' },
                { id: 42841, name: 'NAIVULUNGUTI B' },
                { id: 42836, name: 'NAKASWA' },
                { id: 42837, name: 'SAULO ITALO' },
              ],
            },
            {
              id: 6833,
              name: 'NANSOLOLO',
              villages: [
                { id: 42857, name: 'BUSANGO' },
                { id: 42858, name: 'BUWOLOGOMA' },
                { id: 42859, name: 'BWOYE' },
                { id: 42860, name: 'KAMANYA' },
                { id: 42861, name: 'NANSOLOLO T/C' },
              ],
            },
            {
              id: 6831,
              name: 'NANTAMALI',
              villages: [
                { id: 61830, name: 'KAATO' },
                { id: 42842, name: 'KIKOMERA A' },
                { id: 42847, name: 'KIKOMERA B' },
                { id: 42843, name: 'KINANGIRI' },
                { id: 42844, name: 'MBAGO/IBANDA' },
                { id: 42845, name: 'MPITI A' },
                { id: 42846, name: 'MPITI B' },
                { id: 42848, name: 'NANTAMALI TC' },
              ],
            },
          ],
        },
        {
          id: 1456,
          name: 'NAWAIKOKE',
          parishes: [
            {
              id: 6838,
              name: 'BUHANGALA',
              villages: [
                { id: 42881, name: 'BEEDA' },
                { id: 42883, name: 'BEEDA CENTRAL' },
                { id: 42885, name: 'BUHANGALA T/C' },
                { id: 42882, name: 'BUWANGALA' },
                { id: 42884, name: 'KITAMBOGO A' },
                { id: 42886, name: 'KITAMBOGO B' },
              ],
            },
            {
              id: 6839,
              name: 'BUPENI',
              villages: [
                { id: 42887, name: 'BUBBULI' },
                { id: 42888, name: 'BUKIMINYI' },
                { id: 59676, name: 'BULANGIRA' },
                { id: 42892, name: 'BULUBA' },
                { id: 42889, name: 'BUPENI' },
                { id: 42890, name: 'KABUTANYA' },
                { id: 42893, name: 'LUNYENKE' },
                { id: 42891, name: 'MAHAMBA' },
                { id: 42894, name: 'MENYA' },
              ],
            },
            {
              id: 9824,
              name: 'KYAMBAYA',
              villages: [
                { id: 59381, name: 'BUHOYA' },
                { id: 59416, name: 'BUKAABYA' },
                { id: 66734, name: 'MUWUMBA' },
                { id: 66850, name: 'NABITENDE' },
                { id: 67698, name: 'NEKEMIA MUWUMBA' },
                { id: 71199, name: 'YAIRO MAGINO' },
              ],
            },
            {
              id: 6840,
              name: 'NAMAWA',
              villages: [
                { id: 42895, name: 'BUTATA' },
                { id: 42901, name: 'KAFUNDIKIRE' },
                { id: 42896, name: 'KAFUNDIKIRE T/C' },
                { id: 42899, name: 'KAITANGA' },
                { id: 42897, name: 'KANANSYAIKYE A' },
                { id: 42903, name: 'KANANSYAIKYE B' },
                { id: 42898, name: 'KASOZI' },
                { id: 42902, name: 'NABULO' },
                { id: 42900, name: 'NALUBOMBOKA' },
                { id: 67179, name: 'NALUNYA' },
              ],
            },
            {
              id: 6841,
              name: 'NSAMULE',
              villages: [
                { id: 42904, name: 'BUKUBAITUBA' },
                { id: 42905, name: 'BUKUNYA' },
                { id: 42908, name: 'BUKYESA' },
                { id: 59726, name: 'BULONDO' },
                { id: 42907, name: 'BUSULETA A' },
                { id: 42912, name: 'BUSULETA B' },
                { id: 42910, name: 'KAMANYA' },
                { id: 42909, name: 'KANAMUNYA' },
                { id: 66177, name: 'MBADAALI' },
                { id: 42906, name: 'NSAMULE TRADING CENTRE' },
                { id: 42911, name: 'YOKOYASI' },
              ],
            },
          ],
        },
        {
          id: 1455,
          name: 'NAWAIKOKE TOWN COUNCIL',
          parishes: [
            {
              id: 9293,
              name: 'BUGWABI WARD',
              villages: [
                { id: 59214, name: 'BUBINGA' },
                { id: 59359, name: 'BUGWABI A' },
                { id: 59360, name: 'BUGWABI B' },
                { id: 59361, name: 'BUGWABI TC' },
                { id: 59672, name: 'BULANDA' },
                { id: 60357, name: 'BUSINDI' },
                { id: 66755, name: 'MUZINGE' },
              ],
            },
            {
              id: 6834,
              name: 'MUSIHA WARD',
              villages: [
                { id: 42862, name: 'BUGWABI' },
                { id: 59645, name: 'BUKWAYA' },
                { id: 59728, name: 'BULONDO' },
                { id: 42863, name: 'BUSIHA' },
                { id: 42865, name: 'NAMALEMBA' },
                { id: 67230, name: 'NAMALEMBA CENTRAL' },
                { id: 67231, name: 'NAMALEMBA NORTH' },
                { id: 67232, name: 'NAMALEMBA SOUTH' },
                { id: 42864, name: 'WAMUNSYONO' },
                { id: 71013, name: 'WAMUSYONO A' },
                { id: 71014, name: 'WAMUSYONO B' },
              ],
            },
            {
              id: 6835,
              name: 'MWANGHA WARD',
              villages: [
                { id: 42869, name: 'BUBINGA' },
                { id: 42870, name: 'BUGWABI B' },
                { id: 42866, name: 'BUGYAKU' },
                { id: 59406, name: 'BUJAKU TC' },
                { id: 42867, name: 'BUKUMBI' },
                { id: 60339, name: 'BUSIKWE' },
                { id: 60439, name: 'BUTASA' },
                { id: 42868, name: 'BUTYANGA' },
                { id: 65802, name: 'LYADA' },
                { id: 70458, name: 'SILVE' },
              ],
            },
            {
              id: 6837,
              name: 'NAWAIKOKE WARD',
              villages: [
                { id: 42876, name: 'BUKUNYA' },
                { id: 42877, name: 'KAJUBU' },
                { id: 42878, name: 'LUKUMI' },
                { id: 42879, name: 'NABUUKU' },
                { id: 42880, name: 'NAWAIKOKE' },
              ],
            },
            {
              id: 10094,
              name: 'NOMBE WARD',
              villages: [
                { id: 59617, name: 'BUKULABONE' },
                { id: 60434, name: 'BUTANDOLA A' },
                { id: 60435, name: 'BUTANDOLA B' },
                { id: 61676, name: 'ISEKESYA' },
                { id: 71068, name: 'WANZALA' },
              ],
            },
            {
              id: 6836,
              name: 'WALYABIRA WARD',
              villages: [
                { id: 42871, name: 'BUKULABONE' },
                { id: 42875, name: 'BUNKULEGA' },
                { id: 42872, name: 'BUTANDOLA' },
                { id: 61742, name: 'JALAJA' },
                { id: 64592, name: 'KYALIKOBA' },
                { id: 42873, name: 'MULASI' },
                { id: 66576, name: 'MULASI A' },
                { id: 42874, name: 'WALYABIRA' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
