import { District } from '../types';

export default <District>{
  id: 83,
  name: 'KANUNGU',
  counties: [
    {
      id: 209,
      name: 'KINKIZI COUNTY EAST',
      sub_counties: [
        {
          id: 1295,
          name: 'KAMBUGA',
          parishes: [
            {
              id: 6089,
              name: 'BUGONGI',
              villages: [
                { id: 38379, name: 'IHEMBE' },
                { id: 38380, name: 'KAKINGA' },
                { id: 38381, name: 'KIGARAMA' },
                { id: 38382, name: 'MUKORONGERO' },
                { id: 38383, name: 'MUREHE  A' },
                { id: 38384, name: 'MUREHE  B' },
                { id: 38385, name: 'NYAKATUNGURU' },
                { id: 38386, name: 'RUKIRI' },
                { id: 38387, name: 'RUSHEBEYA  A' },
                { id: 38388, name: 'RUSHEBEYA  B' },
                { id: 38389, name: 'RWAMANYONYI' },
              ],
            },
            {
              id: 6090,
              name: 'KIRINGA',
              villages: [
                { id: 38390, name: 'BUSHOMBE' },
                { id: 38391, name: 'KATEMBE' },
                { id: 38392, name: 'KIGANDO' },
                { id: 38393, name: 'MUSHUNGA' },
                { id: 38394, name: 'NYAMBIZI' },
                { id: 38395, name: 'RWEMBOGO' },
                { id: 38396, name: 'RWENTONDO' },
                { id: 38397, name: 'ZOROOMA' },
              ],
            },
            {
              id: 6091,
              name: 'NYARUGUNDA',
              villages: [
                { id: 38398, name: 'KAKONI' },
                { id: 38399, name: 'KASHURI' },
                { id: 38400, name: 'KATOJO' },
                { id: 38401, name: 'NYARUGUNDA' },
                { id: 38402, name: 'RUTOOMA' },
              ],
            },
            {
              id: 6092,
              name: 'NYARUTOJO',
              villages: [
                { id: 38403, name: 'KAGONGO' },
                { id: 38406, name: 'KASHAYO' },
                { id: 38407, name: 'KIGARAMA' },
                { id: 38408, name: 'KIRUNDWE' },
                { id: 38404, name: 'KYAMPOZA' },
                { id: 38405, name: 'KYAMUGAGA' },
                { id: 38409, name: 'KYOMURINGA' },
                { id: 38410, name: 'NYAKAGYEZI' },
                { id: 38411, name: 'NYAKEINA' },
                { id: 38412, name: 'NYARUTOJO' },
                { id: 38413, name: 'RWERE' },
              ],
            },
          ],
        },
        {
          id: 1302,
          name: 'KAMBUGA TOWN COUNCIL',
          parishes: [
            {
              id: 6119,
              name: 'CENTRAL WARD',
              villages: [
                { id: 38621, name: 'NGARAMA' },
                { id: 38622, name: 'RUGALI' },
              ],
            },
            {
              id: 6120,
              name: 'EASTERN WARD',
              villages: [
                { id: 38625, name: 'BUNYINYA' },
                { id: 38623, name: 'KATUNGU' },
                { id: 38624, name: 'KITORERO' },
              ],
            },
            {
              id: 6121,
              name: 'NORTHERN WARD',
              villages: [
                { id: 38626, name: 'KAYANGA' },
                { id: 38627, name: 'NYAKATUNGURU' },
              ],
            },
            {
              id: 6122,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 38628, name: 'KANYAMOMO' },
                { id: 38629, name: 'KIBALE  I' },
                { id: 38630, name: 'KIBALE  II' },
              ],
            },
          ],
        },
        {
          id: 1299,
          name: 'KANUNGU TOWN COUNCIL',
          parishes: [
            {
              id: 6107,
              name: 'EASTERN WARD',
              villages: [
                { id: 38561, name: 'BURONDO' },
                { id: 38562, name: 'KARENGYE' },
                { id: 38563, name: 'KIFUNJO' },
                { id: 38564, name: 'KYAMUNJURI' },
                { id: 38565, name: 'MARUMBA' },
                { id: 38566, name: 'MURENGYEZA' },
                { id: 38567, name: 'MUSHASHA' },
                { id: 38568, name: 'RUGOMA' },
              ],
            },
            {
              id: 6109,
              name: 'NORTHERN WARD',
              villages: [
                { id: 38578, name: 'BUKOORA' },
                { id: 38579, name: 'BUSHANJA' },
                { id: 38580, name: 'KARUHINDA' },
                { id: 38581, name: 'KAZIRANCENDE' },
                { id: 38582, name: 'KICWAMBA' },
                { id: 38583, name: 'KISHOJWA' },
                { id: 38584, name: 'KYAMBOGO' },
                { id: 38585, name: 'NYAKIHIRA' },
                { id: 38586, name: 'NYAMIHUNGYE' },
                { id: 38587, name: 'RUSHEBEYA' },
                { id: 38588, name: 'RWABUSHUNJU' },
              ],
            },
            {
              id: 6106,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 38550, name: 'BURANDAMI' },
                { id: 38551, name: 'BUTARE' },
                { id: 38552, name: 'KANJARA' },
                { id: 38553, name: 'KANYANTAMA' },
                { id: 38554, name: 'KARAMA' },
                { id: 38555, name: 'KASHENYI' },
                { id: 38556, name: 'KISHAMBA' },
                { id: 38557, name: 'KYABWOORO' },
                { id: 38558, name: 'KYANDAGO' },
                { id: 38559, name: 'MUHORORO' },
                { id: 38560, name: 'OMUMBUGA' },
              ],
            },
            {
              id: 6108,
              name: 'WESTERN WARD',
              villages: [
                { id: 38569, name: 'BUREBANE' },
                { id: 38570, name: 'BWOMA' },
                { id: 38571, name: 'IFUBURA' },
                { id: 38572, name: 'KANUNGU' },
                { id: 38577, name: 'KATAATE' },
                { id: 38573, name: 'KYAMAGOTE' },
                { id: 38574, name: 'MASHENGA' },
                { id: 38575, name: 'NYAKATARE' },
                { id: 38576, name: 'RUMBA' },
              ],
            },
          ],
        },
        {
          id: 1300,
          name: 'KATETE',
          parishes: [
            {
              id: 6110,
              name: 'KAYANJA',
              villages: [
                { id: 38589, name: 'KAYANJA' },
                { id: 38590, name: 'KIREMBE' },
                { id: 38591, name: 'MPANGANGO' },
              ],
            },
            {
              id: 6111,
              name: 'KISHURO',
              villages: [
                { id: 38592, name: 'IBUMBWE' },
                { id: 38593, name: 'KISHURO' },
                { id: 38594, name: 'MUTOJO' },
              ],
            },
            {
              id: 6112,
              name: 'NYAKISHOJWA',
              villages: [
                { id: 38595, name: 'KANYAMISINGA' },
                { id: 38597, name: 'NYAKISHOJWA' },
                { id: 38596, name: 'NYARUHANGA' },
              ],
            },
            {
              id: 6113,
              name: 'NYARURAMBI',
              villages: [
                { id: 38598, name: 'KAYENJE' },
                { id: 38599, name: 'KITOHA' },
                { id: 38600, name: 'NYARURAMBI' },
                { id: 38601, name: 'RWEYEREZO' },
              ],
            },
          ],
        },
        {
          id: 1301,
          name: 'KINAABA',
          parishes: [
            {
              id: 6114,
              name: 'KAMAKOMA',
              villages: [
                { id: 38602, name: 'ISERERERO' },
                { id: 38603, name: 'KAMAKOMA' },
                { id: 38604, name: 'RUGYEYO' },
                { id: 38605, name: 'RUNYAMI' },
              ],
            },
            {
              id: 6115,
              name: 'KANYAMATEMBE',
              villages: [
                { id: 38606, name: 'KANYABWOGO' },
                { id: 38607, name: 'KANYAMATEMBE' },
                { id: 38608, name: 'NYABIRERE' },
              ],
            },
            {
              id: 6116,
              name: 'KIZIBA',
              villages: [
                { id: 38609, name: 'BUGORO' },
                { id: 38610, name: 'KACWAMBA' },
                { id: 38611, name: 'KIZENGA' },
                { id: 38612, name: 'KIZIIBA' },
              ],
            },
            {
              id: 6117,
              name: 'KYAMUKOMBE',
              villages: [
                { id: 38613, name: 'BAKUNDEINE' },
                { id: 38614, name: 'KITOBI' },
                { id: 38615, name: 'KYAMUKOMBE' },
              ],
            },
            {
              id: 6118,
              name: 'MUKIRWA',
              villages: [
                { id: 38616, name: 'BUREBANE' },
                { id: 38617, name: 'ISHAYA' },
                { id: 38618, name: 'KIKANGAGA' },
                { id: 38619, name: 'MUGANDU' },
                { id: 38620, name: 'MUKIRWA' },
              ],
            },
          ],
        },
        {
          id: 1296,
          name: 'KIRIMA',
          parishes: [
            {
              id: 6095,
              name: 'BUSHURA',
              villages: [
                { id: 38431, name: 'AHABUTARE' },
                { id: 38432, name: 'BUGANDARO' },
                { id: 38433, name: 'BUSHURA' },
                { id: 38434, name: 'KAJUMO' },
                { id: 38435, name: 'KATWA' },
                { id: 38436, name: 'KAZURU' },
                { id: 38437, name: 'KIKONDEKA' },
                { id: 38438, name: 'KIRIMA' },
                { id: 38439, name: 'MUGONGO' },
                { id: 38440, name: 'MUTOJO' },
                { id: 38441, name: 'NYAKABUNGO' },
                { id: 38442, name: 'RWENGWE' },
              ],
            },
            {
              id: 6096,
              name: 'KIHANDA',
              villages: [
                { id: 38443, name: 'BUJERENGYE' },
                { id: 38444, name: 'IBARYA' },
                { id: 38445, name: 'KATEMBE' },
                { id: 38446, name: 'KIHUMURO' },
                { id: 38447, name: 'NYAKAGYEZI' },
                { id: 38448, name: 'NYAKARAMBI' },
                { id: 38449, name: 'NYAKATOOMA' },
                { id: 38450, name: 'NYAKIBUGA' },
                { id: 38451, name: 'NYAMIZI' },
                { id: 38452, name: 'NYARUHARO' },
                { id: 38453, name: 'OMURWAMBU' },
                { id: 38454, name: 'RURAMA' },
                { id: 38455, name: 'RUTONDE' },
                { id: 38456, name: 'RWENDAHI' },
                { id: 38457, name: 'RWENKYENDE' },
              ],
            },
            {
              id: 6093,
              name: 'RUBIMBWA',
              villages: [
                { id: 38414, name: 'BUKONO' },
                { id: 38415, name: 'KAJUBWE' },
                { id: 38416, name: 'KASHAKI' },
                { id: 38417, name: 'KASONI' },
                { id: 38418, name: 'KITUNGA' },
                { id: 38419, name: 'NYAKABUNGO' },
                { id: 38420, name: 'NYARWEMARIRA' },
                { id: 38421, name: 'RUHEZA' },
              ],
            },
            {
              id: 6094,
              name: 'RUTUGUNDA',
              villages: [
                { id: 38422, name: 'BUGARAMA/NKAMBA' },
                { id: 38423, name: 'BUHAMBA' },
                { id: 38424, name: 'KANYANKYENDE' },
                { id: 38425, name: 'KATUNGU' },
                { id: 38426, name: 'KITONGO' },
                { id: 38427, name: 'KYEIJANGA' },
                { id: 38428, name: 'MABAARE' },
                { id: 38429, name: 'RUTOOMA' },
                { id: 38430, name: 'RUTORO' },
              ],
            },
          ],
        },
        {
          id: 1297,
          name: 'RUGYEYO',
          parishes: [
            {
              id: 6097,
              name: 'KASHOJWA',
              villages: [
                { id: 38458, name: 'KABAHESI' },
                { id: 38459, name: 'KABATWA' },
                { id: 38460, name: 'KABUNGO' },
                { id: 38461, name: 'KAHAMA' },
                { id: 38462, name: 'KATUNGU' },
                { id: 38463, name: 'MURARA' },
                { id: 38464, name: 'NYAMAKAMBA' },
                { id: 38465, name: 'NYAMUTUNDAMI' },
                { id: 38466, name: 'RUTOOMA' },
                { id: 38467, name: 'RWEIBALE' },
                { id: 38468, name: 'SHUNGA' },
              ],
            },
            {
              id: 6098,
              name: 'KATUNGU',
              villages: [
                { id: 38469, name: 'BIKOMERO' },
                { id: 38470, name: 'BUNYORO' },
                { id: 38471, name: 'BURORA' },
                { id: 38472, name: 'KABASHAKI' },
                { id: 38473, name: 'KAGASHE' },
                { id: 38474, name: 'KATEREZA' },
                { id: 38475, name: 'MARONKO' },
                { id: 38476, name: 'MIRINDI' },
                { id: 38477, name: 'NYABIHAZI' },
                { id: 38478, name: 'RWAKIBANGA' },
                { id: 38479, name: 'RWAKISHANA' },
              ],
            },
            {
              id: 6099,
              name: 'KAYUNGWE',
              villages: [
                { id: 38480, name: 'IRENGA' },
                { id: 38481, name: 'KATEBERE' },
                { id: 38482, name: 'KIGARAMA' },
                { id: 38483, name: 'KITUMBWE' },
                { id: 38484, name: 'MAHWA' },
                { id: 38485, name: 'MAKANGA' },
                { id: 38486, name: 'NYAMITUMBA' },
                { id: 38487, name: 'RWAMAZO' },
                { id: 38488, name: 'RWEIBARE' },
                { id: 38489, name: 'RWENCUNCU' },
              ],
            },
            {
              id: 6100,
              name: 'KITOJO',
              villages: [
                { id: 38490, name: 'BUHINGIRO' },
                { id: 38491, name: 'BUSHEKWE' },
                { id: 38492, name: 'KARUBANDA' },
                { id: 38493, name: 'KATUNGU' },
                { id: 38494, name: 'KESAASI' },
                { id: 38495, name: 'MIRINDI' },
                { id: 38496, name: 'NKONI' },
                { id: 38497, name: 'RUGARAMBIRO' },
                { id: 38498, name: 'RWABIKONDO' },
              ],
            },
            {
              id: 6101,
              name: 'MISHENYI',
              villages: [
                { id: 38499, name: 'BUTAGASI' },
                { id: 38500, name: 'KABAHESI' },
                { id: 38501, name: 'KABUGIRI' },
                { id: 38502, name: 'KANYABWEZA' },
                { id: 38503, name: 'KINYAMAGABO' },
                { id: 38504, name: 'NYAKAZINGA' },
                { id: 38505, name: 'OMUKIBALE' },
                { id: 38506, name: 'RWEIBARE' },
                { id: 38507, name: 'RWENGONGO' },
              ],
            },
            {
              id: 6102,
              name: 'NYARURAMBI',
              villages: [
                { id: 38508, name: 'BUHOORO' },
                { id: 38509, name: 'KACURAGYENYI' },
                { id: 38510, name: 'KATERAMPUNGU' },
                { id: 38511, name: 'KICWAMBA' },
                { id: 38512, name: 'KINYAMUMBYA' },
                { id: 38513, name: 'KIRAGIRO' },
                { id: 38514, name: 'KISHORORO' },
                { id: 38515, name: 'KYAMPUNGU' },
                { id: 38516, name: 'MUKINGA - CENTRAL' },
                { id: 38517, name: 'NYAKABUNGO' },
                { id: 38518, name: 'NYARUBINGO' },
                { id: 38519, name: 'NYARURAMBI' },
              ],
            },
          ],
        },
        {
          id: 1298,
          name: 'RUTENGA',
          parishes: [
            {
              id: 6103,
              name: 'KATOJO',
              villages: [
                { id: 38520, name: 'BIIZI' },
                { id: 38521, name: 'GARAMA' },
                { id: 38522, name: 'KARENGYERE' },
                { id: 38523, name: 'KATAGIRAMAIZI' },
                { id: 38524, name: 'KESENENE' },
                { id: 38525, name: 'KIGARAMA' },
                { id: 38526, name: 'KYANJOBE' },
                { id: 38527, name: 'NYABIZURU' },
                { id: 38528, name: 'NYAMIRENGYERE' },
                { id: 38529, name: 'RUGANDO' },
              ],
            },
            {
              id: 6104,
              name: 'MAFUGA',
              villages: [
                { id: 38531, name: 'KAMUGYENEKA' },
                { id: 38532, name: 'KANGARAME' },
                { id: 38533, name: 'KINYAFURWE' },
                { id: 38530, name: 'MAFUGA FOREST RESERVE' },
                { id: 38534, name: 'NGIRISI' },
                { id: 38535, name: 'NYAKARAMBI' },
                { id: 38536, name: 'NYAMUGARI' },
              ],
            },
            {
              id: 6105,
              name: 'MURAMBA',
              villages: [
                { id: 38537, name: 'KANYAMATO' },
                { id: 38538, name: 'KASIIZI' },
                { id: 38539, name: 'KIJUMWA' },
                { id: 38540, name: 'KYANKYERE' },
                { id: 38541, name: 'MASHENYA' },
                { id: 38542, name: 'NYAMABARE' },
                { id: 38543, name: 'NYAMIRENGYERE' },
                { id: 38544, name: 'NYARUSHANJE' },
                { id: 38545, name: 'NYUNDO' },
                { id: 38546, name: 'RUHAGO' },
                { id: 38547, name: 'RUHIJA' },
                { id: 38548, name: 'RWAKATUNGURU' },
                { id: 38549, name: 'RWEMENGO' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 210,
      name: 'KINKIZI COUNTY WEST',
      sub_counties: [
        {
          id: 1311,
          name: 'BUTOGOTA TOWN COUNCIL',
          parishes: [
            {
              id: 6157,
              name: 'EASTERN WARD',
              villages: [
                { id: 38868, name: 'KANYABUHAMA' },
                { id: 38869, name: 'NYAKAGYEZI' },
              ],
            },
            {
              id: 6158,
              name: 'NORTHERN WARD',
              villages: [
                { id: 38870, name: 'FACTORY' },
                { id: 38871, name: 'KEBIREMU-ISHASHA' },
                { id: 38872, name: 'KYABUYORWA-LOWER' },
                { id: 38873, name: 'KYABUYORWA-UPPER' },
              ],
            },
            {
              id: 6159,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 38874, name: 'BIKUTO' },
                { id: 38875, name: 'BUTOGOTA-CENTRAL' },
                { id: 38876, name: 'BUTOGOTA-RUTWE' },
                { id: 38877, name: 'RUSHAMBYA' },
              ],
            },
            {
              id: 6160,
              name: 'WESTERN WARD',
              villages: [
                { id: 38878, name: 'BUTOGOTA UPPER' },
                { id: 38879, name: 'KIREHE' },
                { id: 38880, name: 'MUNYAGA' },
                { id: 38881, name: 'NYAKIREHE' },
              ],
            },
          ],
        },
        {
          id: 1303,
          name: 'KANYANTOROGO',
          parishes: [
            {
              id: 6126,
              name: 'BUREMA',
              villages: [
                { id: 38650, name: 'KAHAMA' },
                { id: 38651, name: 'KASHANDA' },
                { id: 38652, name: 'KITOOKYE' },
                { id: 38653, name: 'NYARUHANGA' },
              ],
            },
            {
              id: 6123,
              name: 'KIHEMBE',
              villages: [
                { id: 38631, name: 'KANYASHANDE' },
                { id: 38632, name: 'KENGOMA' },
                { id: 38633, name: 'KIHEMBE-CENTRAL' },
                { id: 38634, name: 'KYOZI' },
                { id: 38635, name: 'NYABIREHE' },
                { id: 38636, name: 'NYAKASHARARA' },
                { id: 38637, name: 'RUGARAMA' },
                { id: 38638, name: 'RUKARARA' },
              ],
            },
            {
              id: 6125,
              name: 'KISHENYI',
              villages: [
                { id: 38645, name: 'BURAMBIRA' },
                { id: 38646, name: 'KANYUNGUSI' },
                { id: 38647, name: 'KISHAYO' },
                { id: 38648, name: 'NYAMBARE' },
                { id: 38649, name: 'RUNYINYA' },
              ],
            },
            {
              id: 6124,
              name: 'NYAMIGOYE',
              villages: [
                { id: 38639, name: 'BUGIRI' },
                { id: 38640, name: 'BUSHORO/KAMPALA' },
                { id: 38641, name: 'ISHASHA' },
                { id: 38642, name: 'KYAJURA' },
                { id: 38643, name: 'NYABIHOKO' },
                { id: 38644, name: 'NYABUBARE' },
              ],
            },
          ],
        },
        {
          id: 1304,
          name: 'KAYONZA',
          parishes: [
            {
              id: 6127,
              name: 'BUJENGWE',
              villages: [
                { id: 38654, name: 'BUGARURA' },
                { id: 38655, name: 'BYUMBA' },
                { id: 38656, name: 'KABIRIZI' },
                { id: 38657, name: 'KAKYERERE' },
                { id: 38658, name: 'KANONI' },
                { id: 38659, name: 'KAZAHI' },
                { id: 38660, name: 'KISHANDA' },
                { id: 38661, name: 'KISHEGYERE' },
                { id: 38662, name: 'MAYANJA' },
                { id: 38663, name: 'MUSHORERO' },
                { id: 38664, name: 'NYAMISHAMBA' },
              ],
            },
            {
              id: 6128,
              name: 'KARANGARA',
              villages: [
                { id: 38665, name: 'BUJENGWE' },
                { id: 38666, name: 'KAGOMA' },
                { id: 38667, name: 'MUSHEIJA' },
                { id: 38668, name: 'NSHAGI' },
                { id: 38669, name: 'NTEGYEIRE' },
                { id: 38670, name: 'NYAKABINGO' },
                { id: 38672, name: 'NYAKAHANGA' },
                { id: 38673, name: 'NYAMABARE' },
                { id: 38671, name: 'RUTARE' },
                { id: 38674, name: 'RWAMIYUMBU' },
                { id: 38675, name: 'RWEMIRAMA' },
              ],
            },
            {
              id: 6129,
              name: 'KYESHERO',
              villages: [
                { id: 38676, name: 'BWERONDE' },
                { id: 38677, name: 'KAKUREIJU' },
                { id: 38678, name: 'KASHENYI' },
                { id: 38679, name: 'KATIBA' },
                { id: 38680, name: 'KYESHERO-CENTRAL' },
                { id: 38681, name: 'MBOHA' },
                { id: 38682, name: 'NYAKISHOJWA' },
                { id: 38683, name: 'NYAMIRAMBI' },
              ],
            },
            {
              id: 6130,
              name: 'MUKONO',
              villages: [
                { id: 38684, name: 'BUHOMA CENTRAL' },
                { id: 38685, name: 'IRAARO' },
                { id: 38686, name: 'KANYAMISINGA' },
                { id: 38687, name: 'KANYASHANDE' },
                { id: 38688, name: 'KASHEBEYA' },
                { id: 38689, name: 'KYUMBUGUSHU' },
                { id: 38690, name: 'MUKONGORO' },
                { id: 38691, name: 'MUKONO' },
                { id: 38692, name: 'NKWENDA' },
                { id: 38693, name: 'NYAKEINA' },
                { id: 38694, name: 'RUBONWA' },
              ],
            },
            {
              id: 6131,
              name: 'RUTENDERE',
              villages: [
                { id: 38695, name: 'BURANDA' },
                { id: 38697, name: 'KANGYEYO' },
                { id: 38698, name: 'KATABURAZA' },
                { id: 38699, name: 'KYANDAGO' },
                { id: 38700, name: 'RUTENDERE CENTRAL' },
                { id: 38696, name: 'RWABUTERA' },
              ],
            },
          ],
        },
        {
          id: 1305,
          name: 'KIHIIHI',
          parishes: [
            {
              id: 6134,
              name: 'KABUGA',
              villages: [
                { id: 38724, name: 'BUSHERE' },
                { id: 38725, name: 'KABUGA' },
                { id: 38726, name: 'KAYEMBE' },
                { id: 38727, name: 'KIRURUMA' },
                { id: 38728, name: 'MATANDA  I' },
                { id: 38729, name: 'MATANDA  II' },
              ],
            },
            {
              id: 6132,
              name: 'KIBIMBIRI',
              villages: [
                { id: 38701, name: 'GROUP  FARM  B' },
                { id: 38702, name: 'GROUP FARM  A' },
                { id: 38703, name: 'KAMEME' },
                { id: 38704, name: 'KANYINABURIMANO' },
                { id: 38705, name: 'KIRURUMA  A' },
                { id: 38706, name: 'KIRURUMA  B' },
                { id: 38707, name: 'KYENYABUTONGO' },
                { id: 38708, name: 'MATANDA' },
                { id: 38709, name: 'OMWIRANGIZO' },
                { id: 38710, name: 'RUSOROZA' },
                { id: 38711, name: 'RWERERE  A' },
                { id: 38712, name: 'RWERERE  B' },
                { id: 38713, name: 'RWERERE  C' },
              ],
            },
            {
              id: 6133,
              name: 'RUSOROZA',
              villages: [
                { id: 38714, name: 'CUMBUGU' },
                { id: 38715, name: 'IBAMBIRO' },
                { id: 38716, name: 'KASHOJWA' },
                { id: 38717, name: 'KAZINGA LOWER' },
                { id: 38718, name: 'KAZINGA UPPER' },
                { id: 38719, name: 'KIBIMBIRI' },
                { id: 38720, name: 'KYAKATARANGYI' },
                { id: 38721, name: 'NYARURAMBI' },
                { id: 38722, name: 'RWERERE' },
                { id: 38723, name: 'TUKUNDANE' },
              ],
            },
          ],
        },
        {
          id: 1308,
          name: 'KIHIIHI TOWN COUNCIL',
          parishes: [
            {
              id: 6145,
              name: 'BIHOMBORWA WARD',
              villages: [
                { id: 38777, name: 'BIHOMBORWA' },
                { id: 38778, name: 'BUZANIRO' },
                { id: 38779, name: 'KAKYENKYE' },
                { id: 38780, name: 'KAZINGA' },
                { id: 38781, name: 'KIBAYA' },
                { id: 38782, name: 'KINYANGWE' },
                { id: 38783, name: 'KINYASHOHERA' },
                { id: 38784, name: 'NCUNDA' },
                { id: 38785, name: 'RUTOOMA' },
                { id: 38786, name: 'RWEMISISI' },
                { id: 38787, name: 'RWENYERERE  A' },
                { id: 38788, name: 'RWENYERERE  B' },
              ],
            },
            {
              id: 6148,
              name: 'KIHIIHI TOWN WARD',
              villages: [
                { id: 38815, name: 'BUGONGO' },
                { id: 38816, name: 'CENTRAL KIHIIHI' },
                { id: 38817, name: 'KASIRO' },
                { id: 38818, name: 'MARKET CELL' },
                { id: 38819, name: 'NDEEBA' },
                { id: 38820, name: 'NYAKIYAGA' },
                { id: 38821, name: 'RUTWE' },
                { id: 38822, name: 'RUYAYO' },
                { id: 38823, name: 'RWEMISISI' },
              ],
            },
            {
              id: 6146,
              name: 'NYAKATUNGURU WARD',
              villages: [
                { id: 38789, name: 'BUBARE' },
                { id: 38790, name: 'BUGONGO' },
                { id: 38791, name: 'KABUKWENDA' },
                { id: 38792, name: 'KAMUTUNGU' },
                { id: 38793, name: 'KARAMA' },
                { id: 38794, name: 'KIKUNDA BUKAMA' },
                { id: 38795, name: 'KINYAMASHE' },
                { id: 38797, name: 'KINYASHWEHERA' },
                { id: 38796, name: 'KIRURUMA' },
                { id: 38802, name: 'KISHANDA' },
                { id: 38798, name: 'KISHUNJU' },
                { id: 38799, name: 'NDEEBA' },
                { id: 38800, name: 'NKUMBAGARA' },
                { id: 38801, name: 'NYAMWEGABIRA' },
                { id: 38803, name: 'RUSHENYI' },
                { id: 38804, name: 'RWENYERERE' },
              ],
            },
            {
              id: 6147,
              name: 'RWANGA WARD',
              villages: [
                { id: 38805, name: 'BINYUNGU' },
                { id: 38806, name: 'IBAMBIRO' },
                { id: 38807, name: 'KARAMBI' },
                { id: 38808, name: 'KAZINGA  I' },
                { id: 38809, name: 'KAZINGA  II' },
                { id: 38810, name: 'MUZIIZI' },
                { id: 38811, name: 'NYAKATUNGURU' },
                { id: 38812, name: 'NYAKIYAGA' },
                { id: 38813, name: 'RUKARARA' },
                { id: 38814, name: 'RWEMISISI' },
              ],
            },
          ],
        },
        {
          id: 2044,
          name: 'KYESHERO',
          parishes: [
            {
              id: 9406,
              name: 'BWERONDE',
              villages: [
                { id: 60792, name: 'BWERONDE' },
                { id: 62260, name: 'KAKUREIJU' },
              ],
            },
            {
              id: 9633,
              name: 'KASHENYI',
              villages: [
                { id: 62945, name: 'KASHENYI' },
                { id: 63086, name: 'KATIBA' },
              ],
            },
            {
              id: 9847,
              name: 'KYESHERO',
              villages: [
                { id: 64828, name: 'KYESHERO-CENTRAL' },
                { id: 68110, name: 'NYAKISHOJWA' },
              ],
            },
            {
              id: 10267,
              name: 'RUGANDO',
              villages: [
                { id: 66201, name: 'MBOHA' },
                { id: 68164, name: 'NYAMIRAMBI' },
              ],
            },
          ],
        },
        {
          id: 1307,
          name: 'MPUNGU',
          parishes: [
            {
              id: 6143,
              name: 'BUREMBA',
              villages: [
                { id: 38769, name: 'BWEYONGYEZO' },
                { id: 38770, name: 'HAKIKOOME' },
                { id: 38771, name: 'KARUKARA' },
                { id: 38772, name: 'KATUNDA' },
                { id: 38773, name: 'RUKUNGWE' },
              ],
            },
            {
              id: 6141,
              name: 'MPUNGU',
              villages: [
                { id: 38762, name: 'KANYASHOGYE' },
                { id: 38763, name: 'MURUKORE' },
                { id: 38764, name: 'MURUSHASHA' },
                { id: 38765, name: 'NYAMIZO' },
              ],
            },
            {
              id: 6142,
              name: 'MURAMBA',
              villages: [
                { id: 38766, name: 'KARAMBI' },
                { id: 38767, name: 'KIBIINGO' },
                { id: 38768, name: 'KYAMBEYA' },
              ],
            },
            {
              id: 6144,
              name: 'NGAARA',
              villages: [
                { id: 38774, name: 'BUSHEGYENYI' },
                { id: 38775, name: 'KIGAAGA' },
                { id: 38776, name: 'KYOGO' },
              ],
            },
          ],
        },
        {
          id: 1309,
          name: 'NYAKINONI',
          parishes: [
            {
              id: 6151,
              name: 'KANYAMBEHO',
              villages: [
                { id: 38839, name: 'BURUHUKIRO' },
                { id: 38840, name: 'KANYAMBEHO' },
                { id: 38841, name: 'KASIIRO' },
                { id: 38842, name: 'NYAKAHITA' },
                { id: 38843, name: 'NYAKAYAGA' },
              ],
            },
            {
              id: 6149,
              name: 'KARUBEIZI',
              villages: [
                { id: 38824, name: 'BUHUMURIRO' },
                { id: 38825, name: 'KAMUSHWA' },
                { id: 38826, name: 'MUKIBUNGO' },
                { id: 38827, name: 'MUKIRWA' },
                { id: 38828, name: 'MURUHURA' },
                { id: 38829, name: 'NYAMABALE' },
                { id: 38830, name: 'NYAMIYAGA' },
                { id: 38831, name: 'RWAMAHAMBA' },
                { id: 38832, name: 'RWANGOBOKA' },
              ],
            },
            {
              id: 6152,
              name: 'NYAKIKONI',
              villages: [
                { id: 38844, name: 'KARONDE' },
                { id: 38845, name: 'MPANGANGO' },
                { id: 38846, name: 'NYAKINONI' },
              ],
            },
            {
              id: 6150,
              name: 'SAMARIA',
              villages: [
                { id: 38833, name: 'BUSHOGYE  A' },
                { id: 38834, name: 'BUSHOGYE  B' },
                { id: 38835, name: 'KIRURUMA' },
                { id: 38836, name: 'NYAKARAMBI' },
                { id: 38837, name: 'NYAKASHURE' },
                { id: 38838, name: 'SAMARIA' },
              ],
            },
          ],
        },
        {
          id: 1306,
          name: 'NYAMIRAMA',
          parishes: [
            {
              id: 6136,
              name: 'KIGARAMA',
              villages: [
                { id: 38735, name: 'AHAKIBUNGO' },
                { id: 38736, name: 'KARONI' },
                { id: 38737, name: 'MUKIRWA' },
                { id: 38738, name: 'SAMARIA' },
              ],
            },
            {
              id: 6137,
              name: 'MASHAKU',
              villages: [
                { id: 38739, name: 'KAYENJE' },
                { id: 38740, name: 'KAZINDIRO' },
                { id: 38741, name: 'MASHAKU  I' },
                { id: 38742, name: 'MASHAKU  II' },
                { id: 38743, name: 'RWEMISHINYA' },
              ],
            },
            {
              id: 6140,
              name: 'NTUNGWA',
              villages: [
                { id: 38758, name: 'KAGUNGA' },
                { id: 38759, name: 'KANIABIZO' },
                { id: 38760, name: 'MISHENYI' },
                { id: 38761, name: 'MUKISHAHA' },
              ],
            },
            {
              id: 6138,
              name: 'NYAKASHURE',
              villages: [
                { id: 38744, name: 'BUYUNDO' },
                { id: 38745, name: 'KAHAMA' },
                { id: 38746, name: 'KARONI' },
                { id: 38747, name: 'KARUKONDO' },
                { id: 38748, name: 'KIBARAMA' },
                { id: 38749, name: 'SAMARIA' },
              ],
            },
            {
              id: 6139,
              name: 'NYARURAMBI',
              villages: [
                { id: 38750, name: 'KAYENJE' },
                { id: 38751, name: 'KIBAALE' },
                { id: 38752, name: 'MPANGANGO LOWER' },
                { id: 38753, name: 'MPANGANGO UPPER' },
                { id: 38754, name: 'NTUNGAMO' },
                { id: 38755, name: 'NYAKATOOMA' },
                { id: 38756, name: 'NYAMIYAGA  I' },
                { id: 38757, name: 'NYAMIYAGA  II' },
              ],
            },
            {
              id: 6135,
              name: 'RUSHAKA',
              villages: [
                { id: 38730, name: 'KIRURUMA' },
                { id: 38731, name: 'MASHOOKO' },
                { id: 38732, name: 'NYABUSHORO' },
                { id: 38733, name: 'NYAKAGYERA' },
                { id: 38734, name: 'NYARUHUNGYE' },
              ],
            },
          ],
        },
        {
          id: 1310,
          name: 'NYANGA',
          parishes: [
            {
              id: 6155,
              name: 'BUKORWE',
              villages: [
                { id: 38858, name: 'BUKORWE' },
                { id: 38859, name: 'BURAMBI' },
                { id: 38861, name: 'KARAMBI' },
                { id: 38860, name: 'KAZINGA' },
                { id: 38862, name: 'NYAKABUNGO' },
                { id: 38863, name: 'NYAKASHOZI' },
              ],
            },
            {
              id: 6156,
              name: 'KAMAHE',
              villages: [
                { id: 38864, name: 'BWERAMAANA' },
                { id: 38865, name: 'NYARUTEMBE  A' },
                { id: 38866, name: 'NYARUTEMBE  B' },
                { id: 38867, name: 'YERUSALEMU' },
              ],
            },
            {
              id: 6153,
              name: 'NKUNDA',
              villages: [
                { id: 38849, name: 'KAZINGA' },
                { id: 38848, name: 'NKUNDA' },
                { id: 38847, name: 'NYEIBINGA' },
                { id: 38850, name: 'RUNYINYA' },
                { id: 38851, name: 'RURAMA' },
              ],
            },
            {
              id: 6154,
              name: 'NYANGA',
              villages: [
                { id: 38852, name: 'BUSANZA' },
                { id: 38853, name: 'ISHASHA' },
                { id: 38854, name: 'MUNTUHA' },
                { id: 38855, name: 'MUSHUNGA' },
                { id: 38856, name: 'NYANGA' },
                { id: 38857, name: 'RUTOOMA' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
