import { District } from '../index';

export default {
  id: 37,
  name: 'KAPELEBYONG',
  counties: [
    {
      id: 81,
      name: 'KAPELEBYONG COUNTY',
      sub_counties: [
        {
          id: 511,
          name: 'ACINGA',
          parishes: [
            {
              id: 2373,
              name: 'ACINGA',
              villages: [
                { id: 15525, name: 'ACINGA' },
                { id: 15526, name: 'AIRIAMET' },
                { id: 15527, name: 'AKISIM' },
                { id: 15528, name: 'AKULONY' },
                { id: 15530, name: 'OLOBAI' },
                { id: 15529, name: 'ORIWO' },
              ],
            },
            {
              id: 2374,
              name: 'ADEPAR',
              villages: [
                { id: 15533, name: 'ACELEKWENY' },
                { id: 15532, name: 'ADEPAR' },
                { id: 15537, name: 'AMORU' },
                { id: 15535, name: 'ATIDO' },
                { id: 15534, name: 'CEELE' },
                { id: 15531, name: 'KISENYI' },
                { id: 15536, name: 'OMASAI' },
              ],
            },
            {
              id: 2375,
              name: 'CULA',
              villages: [
                { id: 57446, name: 'ADIPALA' },
                { id: 58368, name: 'APAPAI' },
                { id: 15539, name: 'APELEUN' },
                { id: 15540, name: 'ATUKOI' },
                { id: 15538, name: 'CULA' },
              ],
            },
            {
              id: 2376,
              name: 'NYAIKURO',
              villages: [
                { id: 15541, name: 'ANGOPET' },
                { id: 15543, name: 'NYAKURO' },
                { id: 15542, name: 'ODOOT' },
                { id: 15544, name: 'OKWENY' },
                { id: 15545, name: 'OPEDES' },
              ],
            },
            {
              id: 2377,
              name: 'OLET',
              villages: [
                { id: 15546, name: 'AIPENES' },
                { id: 15547, name: 'ATELENG' },
                { id: 15549, name: 'OLET' },
                { id: 15548, name: 'OMUKUNY' },
                { id: 15550, name: 'OSAGARI' },
              ],
            },
          ],
        },
        {
          id: 506,
          name: 'ACOWA',
          parishes: [
            {
              id: 2346,
              name: 'ACOWA',
              villages: [
                { id: 15328, name: 'ACOWA' },
                { id: 15337, name: 'ADODOI CENTRAL' },
                { id: 15329, name: 'ADODOI EAST' },
                { id: 15330, name: 'ADODOI WEST' },
                { id: 15331, name: 'AKOU ETOM' },
                { id: 15332, name: 'ALUKUMUGE' },
                { id: 15338, name: 'OBUR CENTRAL' },
                { id: 15333, name: 'OBUR EAST' },
                { id: 15334, name: 'OBUR WEST' },
                { id: 15335, name: 'OCITO' },
                { id: 15336, name: 'ORIBABAI' },
              ],
            },
            {
              id: 2347,
              name: 'AKUM',
              villages: [
                { id: 15339, name: 'ACEDAPEL' },
                { id: 15340, name: 'AGUU EAST' },
                { id: 15348, name: 'AGUU WEST' },
                { id: 15350, name: 'AGUYAGUYA' },
                { id: 15341, name: 'AJELEIK CENTRAL' },
                { id: 15342, name: 'AJELEIK EAST' },
                { id: 15349, name: 'AJELEIK WEST' },
                { id: 15343, name: 'ALERE' },
                { id: 15344, name: 'APUUTON' },
                { id: 15345, name: 'ATIRAI' },
                { id: 15346, name: 'MORUTEMEL' },
                { id: 15347, name: 'OMINAI' },
              ],
            },
            {
              id: 2348,
              name: 'AMERO',
              villages: [
                { id: 15351, name: 'ACANGA' },
                { id: 15363, name: 'AJESAI' },
                { id: 15352, name: 'AMERO' },
                { id: 15353, name: 'AMUGEI' },
                { id: 15354, name: 'APOPONG' },
                { id: 15359, name: 'APUJAN' },
                { id: 15360, name: 'APUUTON' },
                { id: 15355, name: 'IKOBATUM' },
                { id: 15356, name: 'ILIIL' },
                { id: 15361, name: 'MORU ISIRU' },
                { id: 15364, name: 'OBUR - AITENG' },
                { id: 15357, name: 'OINTU OSASA' },
                { id: 15362, name: 'OKOKORIO' },
                { id: 15358, name: 'ROGOM' },
              ],
            },
            {
              id: 2350,
              name: 'ANGEREPO',
              villages: [
                { id: 15374, name: 'AKARUKEI' },
                { id: 15370, name: 'ALUNGAR' },
                { id: 58213, name: 'AMUSIA' },
                { id: 15371, name: 'ANGEREPO' },
                { id: 15372, name: 'OCUMAI' },
                { id: 15373, name: 'OJOKAI' },
              ],
            },
            {
              id: 2349,
              name: 'ANGOLEBWAL',
              villages: [
                { id: 15365, name: 'AIMUARET' },
                { id: 15366, name: 'AKAJIKAJ' },
                { id: 15367, name: 'ANGOLEBWAL' },
                { id: 15368, name: 'APUNGURE' },
                { id: 15369, name: 'OTUBOI' },
              ],
            },
          ],
        },
        {
          id: 509,
          name: 'AKOROMIT',
          parishes: [
            {
              id: 2364,
              name: 'AKORE',
              villages: [
                { id: 15468, name: 'AIRIAMET' },
                { id: 15467, name: 'AKORE' },
                { id: 15469, name: 'ALASO' },
                { id: 15471, name: 'ATUTUR' },
                { id: 15472, name: 'OMETWA' },
                { id: 15466, name: 'ONAPAI' },
                { id: 15473, name: 'OWOIKINAI' },
                { id: 15470, name: 'TUKUM' },
              ],
            },
            {
              id: 2362,
              name: 'AKOROMIT',
              villages: [
                { id: 15455, name: 'AFRICA' },
                { id: 15451, name: 'AKORET/C' },
                { id: 15452, name: 'AKWORO' },
                { id: 15456, name: 'AMUKURAT' },
                { id: 15454, name: 'ANGOPET' },
                { id: 15457, name: 'NAPAK' },
                { id: 15453, name: 'TOBORA' },
              ],
            },
            {
              id: 2365,
              name: 'AMINITO',
              villages: [
                { id: 15474, name: 'ACOMAIT' },
                { id: 15480, name: 'ADETA' },
                { id: 15475, name: 'AMINITO' },
                { id: 15476, name: 'ANGARO' },
                { id: 15477, name: 'ARUGWANG' },
                { id: 15479, name: 'ASILO' },
                { id: 15478, name: 'ATEUSO' },
              ],
            },
            {
              id: 2363,
              name: 'KOBUIN',
              villages: [
                { id: 15458, name: 'ABOLOT' },
                { id: 15459, name: 'AJALAI' },
                { id: 15464, name: 'ARUBELA' },
                { id: 15460, name: 'ATARUKOT' },
                { id: 15465, name: 'IYALAKWE' },
                { id: 15461, name: 'OPAKWI' },
                { id: 15462, name: 'OTITINGO' },
                { id: 15463, name: 'TIK TIK' },
              ],
            },
            {
              id: 2366,
              name: 'OLEKAT',
              villages: [
                { id: 15487, name: 'ABURET' },
                { id: 15482, name: 'ADONG' },
                { id: 15481, name: 'ALELES' },
                { id: 15484, name: 'APARISIA' },
                { id: 15485, name: 'MATAILONG' },
                { id: 15483, name: 'OITELAIKILIOK' },
                { id: 15486, name: 'OLEKAT' },
              ],
            },
          ],
        },
        {
          id: 512,
          name: 'ALITO',
          parishes: [
            {
              id: 2379,
              name: 'AKILENG',
              villages: [
                { id: 15558, name: 'AKILENG' },
                { id: 15559, name: 'ALITO CENTRAL' },
                { id: 58323, name: 'ANYAIKIN' },
                { id: 15560, name: 'OGWOTAI A' },
                { id: 15562, name: 'OGWOTAI B' },
                { id: 15561, name: 'ORINGOI' },
              ],
            },
            {
              id: 2378,
              name: 'ALITO',
              villages: [
                { id: 15551, name: 'ABARITUK A' },
                { id: 15553, name: 'ABARITUK B' },
                { id: 15556, name: 'ABEDOBER' },
                { id: 15552, name: 'ABERAN' },
                { id: 15554, name: 'AGWENG' },
                { id: 15555, name: 'ALITO' },
                { id: 15557, name: 'ARARO' },
              ],
            },
            {
              id: 2380,
              name: 'ANGICA',
              villages: [
                { id: 58072, name: 'ALUNGAKOIT' },
                { id: 58182, name: 'AMORICAN' },
                { id: 15563, name: 'ANGICA  A' },
                { id: 15564, name: 'ANGICA  B' },
                { id: 62145, name: 'KAIDERO' },
                { id: 68460, name: 'ODIAMA' },
              ],
            },
            {
              id: 2381,
              name: 'IYALAKWE',
              villages: [
                { id: 57237, name: 'ABOTA B' },
                { id: 58285, name: 'ANGOPET' },
                { id: 58812, name: 'AYELAPE' },
                { id: 15565, name: 'IYALAKWE A' },
                { id: 61716, name: 'IYALAKWE B' },
                { id: 68294, name: 'NYONOKWON' },
                { id: 15566, name: 'OJEPAI' },
              ],
            },
            {
              id: 2382,
              name: 'MATILONG',
              villages: [
                { id: 57312, name: 'ACANIPI' },
                { id: 57627, name: 'AIRIAMET' },
                { id: 58261, name: 'ANGARO' },
                { id: 15567, name: 'MATILONG  A' },
                { id: 15568, name: 'MATILONG  B' },
                { id: 68622, name: 'OJAMA' },
              ],
            },
          ],
        },
        {
          id: 507,
          name: 'KAPELEBYONG',
          parishes: [
            {
              id: 2351,
              name: 'AMASENIKO',
              villages: [
                { id: 15375, name: 'ADITETAU' },
                { id: 15376, name: 'ADUKAIT' },
                { id: 15377, name: 'AMASENIKO' },
                { id: 15378, name: 'ANYANGARENG' },
                { id: 15380, name: 'OBULEKOPU' },
                { id: 15379, name: 'ONGANYAKONYE' },
                { id: 15381, name: 'OTAPENGO' },
              ],
            },
            {
              id: 2355,
              name: 'AMEMIA',
              villages: [
                { id: 15405, name: 'ADIPALA' },
                { id: 15406, name: 'AKUM' },
                { id: 15409, name: 'AMEMIA' },
                { id: 15407, name: 'APEDU' },
                { id: 15410, name: 'OKEPIA' },
                { id: 15411, name: 'OLIABAI' },
                { id: 15408, name: 'OLOTAI' },
                { id: 15412, name: 'OMATAI' },
              ],
            },
            {
              id: 2356,
              name: 'ATIIRA',
              villages: [
                { id: 15413, name: 'ACUMET' },
                { id: 15414, name: 'AKAMUREI' },
                { id: 15416, name: 'AKIMENGA' },
                { id: 15417, name: 'APELUKE' },
                { id: 15418, name: 'APOPONG' },
                { id: 15419, name: 'ATIIDA' },
                { id: 15420, name: 'ATIIRA' },
                { id: 15415, name: 'ATUBESOLO' },
              ],
            },
            {
              id: 2352,
              name: 'KAPELEBYONG',
              villages: [
                { id: 15382, name: 'ACEGEREKUMA' },
                { id: 15383, name: 'ADUKULE' },
                { id: 15384, name: 'ALUNGATUKO' },
                { id: 15385, name: 'APOPONG' },
                { id: 15386, name: 'KAPELEBYONG' },
                { id: 15389, name: 'NYAKALI' },
                { id: 15387, name: 'ODUKUL' },
                { id: 15390, name: 'OKUNGURO' },
                { id: 15388, name: 'OLOBAI' },
              ],
            },
            {
              id: 2353,
              name: 'NYADA',
              villages: [
                { id: 15393, name: 'AKUNYUKO' },
                { id: 15394, name: 'ALEPELEP' },
                { id: 15395, name: 'CHANGWENO' },
                { id: 15391, name: 'MAMBASA' },
                { id: 15392, name: 'NYADA' },
                { id: 15396, name: 'ODITEL A' },
                { id: 15398, name: 'ODITEL B' },
                { id: 15399, name: 'OKOONA' },
                { id: 15397, name: 'TAKARAMIEM' },
              ],
            },
            {
              id: 2354,
              name: 'OKOBOI',
              villages: [
                { id: 15400, name: 'AKULONYO' },
                { id: 15404, name: 'AREMEJIK' },
                { id: 15401, name: 'ATURAI' },
                { id: 15402, name: 'OKOBOI' },
                { id: 15403, name: 'OMOKORI' },
              ],
            },
          ],
        },
        {
          id: 508,
          name: 'OBALANGA',
          parishes: [
            {
              id: 2359,
              name: 'ALUPE',
              villages: [
                { id: 57641, name: 'AJELUK' },
                { id: 15436, name: 'ALELA' },
                { id: 15435, name: 'ALUPE A' },
                { id: 15437, name: 'ALUPE B' },
                { id: 70840, name: 'TUKUM' },
              ],
            },
            {
              id: 2361,
              name: 'ALWENYA',
              villages: [
                { id: 15446, name: 'ADULA' },
                { id: 15447, name: 'AKORA' },
                { id: 15449, name: 'ALWENYA A' },
                { id: 15450, name: 'ALWENYA B' },
                { id: 15448, name: 'AMOTOT' },
              ],
            },
            {
              id: 2360,
              name: 'LABIRA',
              villages: [
                { id: 15438, name: 'ABOTA A' },
                { id: 15439, name: 'ADUNGO' },
                { id: 15440, name: 'AGALIBU A' },
                { id: 15441, name: 'AGALIBU B' },
                { id: 15442, name: 'ANGATUNY A' },
                { id: 15445, name: 'ANGATUNY B' },
                { id: 15443, name: 'LABIRA B' },
                { id: 15444, name: 'OKENYAI' },
              ],
            },
            {
              id: 2357,
              name: 'OBALANGA',
              villages: [
                { id: 15425, name: 'AMARE A' },
                { id: 15421, name: 'AMARE B' },
                { id: 15426, name: 'AMENANGURA' },
                { id: 15427, name: 'AOJANGUR' },
                { id: 15424, name: 'ASINGE' },
                { id: 15423, name: 'OBAJAI/AJESAI' },
                { id: 15428, name: 'OBALANGA CENTRE' },
                { id: 15422, name: 'OKOLAS' },
              ],
            },
            {
              id: 2358,
              name: 'OPOT',
              villages: [
                { id: 15429, name: 'AGAYA' },
                { id: 15431, name: 'ARUBELA A' },
                { id: 58545, name: 'ARUBELA B' },
                { id: 15430, name: 'INDIA' },
                { id: 15434, name: 'OBEDO' },
                { id: 15432, name: 'OJIJI A' },
                { id: 68635, name: 'OJIJI B' },
                { id: 15433, name: 'OPOT' },
              ],
            },
          ],
        },
        {
          id: 510,
          name: 'OKUNGUR',
          parishes: [
            {
              id: 2368,
              name: 'AGONGA',
              villages: [
                { id: 15499, name: 'AMONI' },
                { id: 15500, name: 'KARAMATA' },
                { id: 15501, name: 'OCONGODA' },
                { id: 15502, name: 'OKERAI A' },
                { id: 15497, name: 'OKERAI B' },
                { id: 15498, name: 'OKUNGURO' },
              ],
            },
            {
              id: 2367,
              name: 'AIRABET',
              villages: [
                { id: 15489, name: 'AIRABET' },
                { id: 15488, name: 'ALALAR' },
                { id: 15490, name: 'AMINIT' },
                { id: 15496, name: 'ATAPAR' },
                { id: 15492, name: 'ATARUKOT' },
                { id: 15495, name: 'ATURAI' },
                { id: 15491, name: 'OBULIN' },
                { id: 15493, name: 'OKUNGUR' },
                { id: 15494, name: 'OLILIA' },
              ],
            },
            {
              id: 2372,
              name: 'AKODOKODOI',
              villages: [
                { id: 15519, name: 'AKODOKODOI' },
                { id: 15524, name: 'APOPONG' },
                { id: 15522, name: 'MAGA' },
                { id: 15520, name: 'OGOLAI' },
                { id: 15523, name: 'OLILIA A' },
                { id: 15521, name: 'OLILIA B' },
              ],
            },
            {
              id: 2369,
              name: 'AMOOTOM',
              villages: [
                { id: 15503, name: 'AMOOTOM' },
                { id: 15504, name: 'AMOOTOM ORIGINAL' },
                { id: 15505, name: 'ARENGEPUA' },
                { id: 15507, name: 'OCORIKOIT A' },
                { id: 15506, name: 'OCORIKOIT B' },
              ],
            },
            {
              id: 2371,
              name: 'ARIDAI',
              villages: [
                { id: 15514, name: 'AGUYAGUYA' },
                { id: 15516, name: 'AJESAI' },
                { id: 15515, name: 'AMINIT' },
                { id: 15517, name: 'ARIDAI A' },
                { id: 15518, name: 'ONGOPAI' },
              ],
            },
            {
              id: 2370,
              name: 'ODIDING',
              villages: [
                { id: 15511, name: 'AJELEL' },
                { id: 15510, name: 'ASUKUSUKU' },
                { id: 15508, name: 'ODIDING' },
                { id: 15512, name: 'ODIMAI' },
                { id: 15509, name: 'ORUMAI' },
                { id: 15513, name: 'OSILON' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
