import { District } from '../types';

export default <District>{
  id: 130,
  name: 'KARENGA',
  counties: [
    {
      id: 305,
      name: 'DODOTH WEST COUNTY',
      sub_counties: [
        {
          id: 1999,
          name: 'KAKWANGA',
          parishes: [
            {
              id: 9558,
              name: 'KAKWANGA',
              villages: [
                { id: 62266, name: 'KAKWANGA CENTRAL' },
                { id: 62583, name: 'KANYANGOR' },
                { id: 65355, name: 'LOKIPIE' },
                { id: 66412, name: 'MORUNYANG' },
                { id: 67110, name: 'NAKORWA' },
                { id: 67540, name: 'NARYONOMORU' },
              ],
            },
            {
              id: 9902,
              name: 'LOMALER',
              villages: [
                { id: 65314, name: 'LOITARENG' },
                { id: 65421, name: 'LOMALER' },
                { id: 65507, name: 'LOPWA' },
                { id: 69726, name: 'POOCHO' },
                { id: 70777, name: 'TODIR' },
              ],
            },
            {
              id: 10033,
              name: 'NAESEKAPEL',
              villages: [
                { id: 65179, name: 'LEMUKOROI' },
                { id: 66948, name: 'NAESEKAPEL NORTH' },
                { id: 66949, name: 'NAESEKAPEL SOUTH' },
                { id: 67603, name: 'NATEMO' },
              ],
            },
          ],
        },
        {
          id: 2007,
          name: 'KAPEDO',
          parishes: [
            {
              id: 9572,
              name: 'KALIMON',
              villages: [
                { id: 61701, name: 'ITANYIA' },
                { id: 61821, name: 'KAALIMON' },
                { id: 62598, name: 'KANYIKWAR' },
                { id: 65558, name: 'LOYORO' },
                { id: 67151, name: 'NALEECH' },
              ],
            },
            {
              id: 9603,
              name: 'KAPEDO',
              villages: [
                { id: 61813, name: 'K.D.A' },
                { id: 63039, name: 'KATANGA' },
                { id: 64235, name: 'KOLOLO' },
                { id: 64236, name: 'KOLOLO KRAALS' },
                { id: 65513, name: 'LORENGECHORA' },
                { id: 66335, name: 'MOGOS' },
                { id: 67107, name: 'NAKORICHOKEI' },
                { id: 67573, name: 'NASINYONOIT EAST' },
                { id: 67574, name: 'NASINYONOIT WEST' },
              ],
            },
            {
              id: 9790,
              name: 'KOMOLICHER',
              villages: [
                { id: 61467, name: 'GURUMA' },
                { id: 61816, name: 'KAACHOMIN' },
                { id: 62815, name: 'KARIWONYANG' },
                { id: 63043, name: 'KATANYIA' },
                { id: 64250, name: 'KOMEM' },
                { id: 65230, name: 'LOBELUNA' },
                { id: 65544, name: 'LOWALA' },
                { id: 66902, name: 'NABUTERA' },
                { id: 67650, name: 'NAWOYAPIE' },
              ],
            },
          ],
        },
        {
          id: 2011,
          name: 'KARENGA(NAPORE)',
          parishes: [
            {
              id: 9592,
              name: 'KANGOLE',
              villages: [
                { id: 62531, name: 'KANGOLE CENTRAL' },
                { id: 62533, name: 'KANGOLE NORTH' },
                { id: 62534, name: 'KANGOLE SOUTH' },
                { id: 65504, name: 'LOPUTUK' },
                { id: 65523, name: 'LORWAMA' },
              ],
            },
            {
              id: 9616,
              name: 'KARENGA',
              villages: [
                { id: 62468, name: 'KAMUKOI CENTRAL' },
                { id: 62469, name: 'KAMUKOI NORTH' },
                { id: 62470, name: 'KAMUKOI SOUTH' },
                { id: 65376, name: 'LOKODOPE' },
                { id: 67152, name: 'NALEMORU' },
                { id: 70694, name: 'TELEL' },
                { id: 71072, name: 'WAPAKIRU' },
              ],
            },
            {
              id: 9923,
              name: 'LOYORO/NAPORE',
              villages: [
                { id: 61363, name: 'GEREMECH' },
                { id: 62530, name: 'KANGOLE' },
                { id: 65559, name: 'LOYORO CENTRAL' },
                { id: 65560, name: 'LOYORO NORTH' },
                { id: 65561, name: 'LOYORO SOUTH' },
                { id: 67711, name: 'NEW KARENGA' },
              ],
            },
            {
              id: 10045,
              name: 'NAKITOIT',
              villages: [
                { id: 65519, name: 'LORUKUL' },
                { id: 67083, name: 'NAKITOIT NORTH' },
                { id: 67084, name: 'NAKITOIT SOUTH' },
              ],
            },
          ],
        },
        {
          id: 2016,
          name: 'KAWALAKOL',
          parishes: [
            {
              id: 9655,
              name: 'KAWALAKOL',
              villages: [
                { id: 63195, name: 'KAWALAKOL CENTRAL' },
                { id: 65228, name: 'LOBELE' },
                { id: 65486, name: 'LOPEERU' },
                { id: 66408, name: 'MORUNGOLE' },
                { id: 67010, name: 'NAKAPANGITENGA' },
                { id: 67094, name: 'NAKODOIKODIO' },
                { id: 67262, name: 'NAMATENGE' },
                { id: 67444, name: 'NANGOLECHOWA' },
              ],
            },
            {
              id: 9789,
              name: 'KOKORO',
              villages: [
                { id: 61817, name: 'KAAKOCHIL' },
                { id: 62351, name: 'KALOKORIO' },
                { id: 64218, name: 'KOKORO' },
                { id: 64224, name: 'KOLELE' },
                { id: 65488, name: 'LOPELIPEL' },
                { id: 66378, name: 'MORU-ARENGAN' },
                { id: 66409, name: 'MORUNGOLE' },
                { id: 66959, name: 'NAGOLOPAK' },
              ],
            },
            {
              id: 9903,
              name: 'LOMANOK',
              villages: [
                { id: 61089, name: 'DANGASIL' },
                { id: 65384, name: 'LOKOONA' },
                { id: 65426, name: 'LOMANOK' },
                { id: 65505, name: 'LOPUTUK' },
                { id: 66107, name: 'MATAKUWAR' },
                { id: 67061, name: 'NAKIIRIAS' },
                { id: 67630, name: 'NAURUTOCHOM' },
              ],
            },
            {
              id: 9904,
              name: 'LOMEJ/NATIIRA',
              villages: [
                { id: 64187, name: 'KOCHOLO' },
                { id: 65506, name: 'LOPWA' },
                { id: 65534, name: 'LOTIPWAL' },
                { id: 65539, name: 'LOUKOMOR' },
                { id: 66792, name: 'NAAPONG' },
                { id: 67121, name: 'NAKUNGUROIT' },
                { id: 67516, name: 'NAPORUKOLONG' },
                { id: 70843, name: 'TULELO' },
              ],
            },
            {
              id: 10066,
              name: 'NAOYAGUM',
              villages: [
                { id: 65281, name: 'LODIRINYANG' },
                { id: 65375, name: 'LOKODOPE' },
                { id: 65393, name: 'LOKOSIMALITIT' },
                { id: 65498, name: 'LOPOKOR' },
                { id: 66403, name: 'MORULEM' },
                { id: 66411, name: 'MORUNYANG' },
                { id: 66794, name: 'NAAPONG' },
                { id: 67056, name: 'NAKIDIIR' },
                { id: 67520, name: 'NAPUSIMORU' },
                { id: 67649, name: 'NAWOYAGUM' },
              ],
            },
            {
              id: 10071,
              name: 'NASEPERWAE',
              villages: [
                { id: 65178, name: 'LEMUKIAL' },
                { id: 65471, name: 'LOOKUSE' },
                { id: 65515, name: 'LORITIT' },
                { id: 66375, name: 'MORU ITA' },
                { id: 67075, name: 'NAKISIMOE' },
                { id: 67546, name: 'NASEPERWAE' },
                { id: 67593, name: 'NATAABA-A-LOKURE' },
                { id: 70305, name: 'SEMUKOI' },
              ],
            },
          ],
        },
        {
          id: 2049,
          name: 'LOBALANGIT',
          parishes: [
            {
              id: 9882,
              name: 'LOBALANGIT',
              villages: [
                { id: 65221, name: 'LOBALANGIT CENTRAL' },
                { id: 65222, name: 'LOBALANGIT MAIN' },
                { id: 65286, name: 'LODWARI' },
                { id: 65522, name: 'LORUTAM' },
                { id: 66960, name: 'NAGOLOPAK' },
                { id: 66961, name: 'NAGOLOPAK SOUTH' },
              ],
            },
            {
              id: 9887,
              name: 'LODAPAL',
              villages: [
                { id: 62218, name: 'KAKIRA' },
                { id: 65274, name: 'LODAPAL' },
                { id: 65407, name: 'LOKWASINYON' },
                { id: 67528, name: 'NARENGEPUWA' },
                { id: 67653, name: 'NAWOYARO' },
                { id: 70732, name: 'TEUS' },
              ],
            },
            {
              id: 9911,
              name: 'LONGOLETYAANGA',
              villages: [
                { id: 65425, name: 'LOMANAKO' },
                { id: 65427, name: 'LOMANOKO NORTH' },
                { id: 65462, name: 'LONGOLETYANGA NORTH' },
                { id: 65463, name: 'LONGOLETYANGA SOUTH' },
              ],
            },
            {
              id: 10041,
              name: 'NAKELLIO',
              villages: [
                { id: 61118, name: 'DIDIT' },
                { id: 62795, name: 'KARIAMANGOROK' },
                { id: 65332, name: 'LOKAPUKE EAST' },
                { id: 65333, name: 'LOKAPUKE WEST' },
                { id: 67037, name: 'NAKELLIO NORTH' },
                { id: 67038, name: 'NAKELLIO SOUTH' },
                { id: 67647, name: 'NAWARA' },
              ],
            },
            {
              id: 10251,
              name: 'PIRE',
              villages: [
                { id: 65485, name: 'LOPEEI' },
                { id: 67120, name: 'NAKUNGURIT' },
                { id: 67535, name: 'NARIUPWAL' },
                { id: 69692, name: 'PIRE' },
                { id: 69693, name: 'PIRE CENTRAL' },
              ],
            },
            {
              id: 10301,
              name: 'SARACHOM',
              villages: [
                { id: 62408, name: 'KAMARINYANG' },
                { id: 65403, name: 'LOKWAKINEI' },
                { id: 65405, name: 'LOKWANGKIR' },
                { id: 65435, name: 'LOMISINIK' },
                { id: 65492, name: 'LOPET' },
                { id: 65496, name: 'LOPILIPEL' },
                { id: 69745, name: 'PUDA' },
                { id: 70285, name: 'SARACHOM' },
              ],
            },
          ],
        },
        {
          id: 2051,
          name: 'LOKORI',
          parishes: [
            {
              id: 9685,
              name: 'KIDEPO',
              villages: [
                { id: 58418, name: 'APOKA' },
                { id: 63175, name: 'KATURUM' },
                { id: 63436, name: 'KIDEPO' },
                { id: 65312, name: 'LOITANIT' },
                { id: 67594, name: 'NATAABA-A-LOKURE-GATE' },
              ],
            },
            {
              id: 9899,
              name: 'LOKORI',
              villages: [
                { id: 61819, name: 'KAAKURUK' },
                { id: 61997, name: 'KACHAPANGOLE' },
                { id: 62151, name: 'KAILUNGO' },
                { id: 65389, name: 'LOKORI' },
                { id: 65494, name: 'LOPIAN' },
                { id: 66815, name: 'NABETELENG' },
              ],
            },
            {
              id: 10202,
              name: 'OPOTIPOT',
              villages: [
                { id: 61180, name: 'DUKOOLE' },
                { id: 61820, name: 'KAALIMON' },
                { id: 62352, name: 'KALOKUDO' },
                { id: 65272, name: 'LOCHWANGALEM' },
                { id: 65322, name: 'LOKABAIYA' },
                { id: 65399, name: 'LOKUYON' },
                { id: 67448, name: 'NANGOLEMORU' },
                { id: 67652, name: 'NAWOYARO' },
                { id: 69142, name: 'OPOTIPOT' },
              ],
            },
          ],
        },
        {
          id: 2116,
          name: 'SANGAR',
          parishes: [
            {
              id: 9785,
              name: 'KOCHOLO',
              villages: [
                { id: 61084, name: 'DAISIK' },
                { id: 65335, name: 'LOKASANGATE' },
                { id: 65436, name: 'LOMODOOCH' },
                { id: 67514, name: 'NAPORUKOLONG' },
                { id: 67538, name: 'NAROUCHOM' },
              ],
            },
            {
              id: 9805,
              name: 'KUMET',
              villages: [
                { id: 61398, name: 'GOLOPAK' },
                { id: 64391, name: 'KUMET' },
                { id: 65416, name: 'LOLIBIKAN' },
                { id: 65512, name: 'LORENGECHORA' },
                { id: 65518, name: 'LOROBOROB' },
                { id: 65536, name: 'LOTOUKOROE' },
                { id: 67505, name: 'NAPETAAOI' },
              ],
            },
            {
              id: 9892,
              name: 'LOKIAL',
              villages: [
                { id: 65344, name: 'LOKIAL' },
                { id: 65459, name: 'LONGEREP' },
                { id: 66954, name: 'NAGARA' },
                { id: 67140, name: 'NAKWAYELEL' },
              ],
            },
            {
              id: 10044,
              name: 'NAKITEMYET (LOTWAL)',
              villages: [
                { id: 62349, name: 'KALOKIENY' },
                { id: 64392, name: 'KUMET' },
                { id: 65288, name: 'LOESEMUDANG' },
                { id: 66812, name: 'NABAS' },
                { id: 66934, name: 'NACHUKUL' },
                { id: 67513, name: 'NAPOOK' },
              ],
            },
            {
              id: 10300,
              name: 'SANGAR',
              villages: [
                { id: 61397, name: 'GOLOPAK' },
                { id: 62301, name: 'KALANYAKORI' },
                { id: 65439, name: 'LOMONIYOLO' },
                { id: 65440, name: 'LOMORUNYANGAE' },
                { id: 65543, name: 'LOWAKUJ' },
                { id: 67447, name: 'NANGOLEMORU' },
                { id: 67492, name: 'NAOYASE' },
                { id: 67506, name: 'NAPETAAOI' },
                { id: 67536, name: 'NARIWOSE' },
                { id: 70514, name: 'SOKODOKAN' },
                { id: 70804, name: 'TORE' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
