import { District } from '../types';

export default {
  id: 38,
  name: 'KASANDA',
  counties: [
    {
      id: 295,
      name: 'BUKUYA COUNTY',
      sub_counties: [
        {
          id: 1968,
          name: 'BUKUYA',
          parishes: [
            {
              id: 9621,
              name: 'KASAMBA',
              villages: [
                { id: 61947, name: 'KABUGA' },
                { id: 62873, name: 'KASAMBA A' },
                { id: 62874, name: 'KASAMBA B' },
                { id: 63451, name: 'KIDUUKULU' },
                { id: 63602, name: 'KIJJWA' },
                { id: 63860, name: 'KISAGAZI' },
                { id: 63931, name: 'KISINZA' },
                { id: 66182, name: 'MBALE' },
                { id: 66768, name: 'MWEYA/SENGENDO' },
              ],
            },
            {
              id: 9777,
              name: 'KIZIBAWO',
              villages: [
                { id: 62355, name: 'KALONGO  TOWN' },
                { id: 62356, name: 'KALONGO VILLAGE' },
                { id: 62877, name: 'KASAMBYA' },
                { id: 63006, name: 'KASSUBI' },
                { id: 63193, name: 'KAWAGALO' },
                { id: 63600, name: 'KIJJUKIRA' },
                { id: 63851, name: 'KIRYANONGO' },
                { id: 64058, name: 'KITOKOLO' },
                { id: 64155, name: 'KIZIBAAWO' },
                { id: 64834, name: 'KYETUME' },
                { id: 65702, name: 'LUSUNGWE' },
                { id: 66852, name: 'NABITI' },
              ],
            },
            {
              id: 10058,
              name: 'NAMIRYANGO',
              villages: [
                { id: 59410, name: 'BUJONJO' },
                { id: 61887, name: 'KABASULA' },
                { id: 62907, name: 'KASEBWEMBE' },
                { id: 62909, name: 'KASEENENE' },
                { id: 63623, name: 'KIJWANGANYA' },
                { id: 64632, name: 'KYAMPISI' },
                { id: 64835, name: 'KYEWULA' },
                { id: 65790, name: 'LWAWONA' },
                { id: 67321, name: 'NAMIRYANGO' },
              ],
            },
          ],
        },
        {
          id: 1969,
          name: 'BUKUYA TOWN COUNCIL',
          parishes: [
            {
              id: 9316,
              name: 'BUKUYA WARD',
              villages: [
                { id: 58878, name: 'BAKULE' },
                { id: 59037, name: 'BERIA ROAD' },
                { id: 60790, name: 'BWERENGA' },
                { id: 63005, name: 'KASSANDA RD' },
                { id: 63167, name: 'KATUNGULU' },
                { id: 63248, name: 'KAZIGWE ROAD' },
                { id: 63382, name: 'KIBISI' },
                { id: 65835, name: 'MABINDO' },
                { id: 66454, name: 'MPUMUDDE' },
                { id: 67801, name: 'NKONGE' },
                { id: 67844, name: 'NSUMBA' },
                { id: 67864, name: 'NTONYEZE' },
                { id: 70296, name: 'SEETA' },
              ],
            },
            {
              id: 9525,
              name: 'KABOSI WARD',
              villages: [
                { id: 59603, name: 'BUKONYOGO' },
                { id: 60732, name: 'BUYIRIGO' },
                { id: 61945, name: 'KABOSI CENTRAL' },
                { id: 64642, name: 'KYAMUGUGU A' },
                { id: 64643, name: 'KYAMUGUGU B' },
                { id: 66903, name: 'NABUTITTI' },
              ],
            },
            {
              id: 9529,
              name: 'KABUYIMBA WARD',
              villages: [
                { id: 60392, name: 'BUSOOLO' },
                { id: 61985, name: 'KABUYIMBA' },
                { id: 62391, name: 'KALYANKOKO' },
                { id: 63662, name: 'KIKOOBA' },
                { id: 63710, name: 'KIMBEJJA' },
              ],
            },
            {
              id: 9564,
              name: 'KALAATA WARD',
              villages: [
                { id: 59133, name: 'BIWALWE' },
                { id: 62065, name: 'KAGABA' },
                { id: 62276, name: 'KALAATA' },
                { id: 62402, name: 'KAMALENGE' },
                { id: 63527, name: 'KIGUNDA' },
                { id: 64034, name: 'KITEREDDE' },
                { id: 64501, name: 'KYABIKOLA' },
                { id: 65648, name: 'LULAMBA' },
                { id: 66814, name: 'NABBONDO' },
              ],
            },
            {
              id: 10077,
              name: 'NCHWAMAZZI WARD',
              villages: [
                { id: 60613, name: 'BUWANUKA' },
                { id: 61828, name: 'KAATEMA' },
                { id: 62436, name: 'KAMONDO' },
                { id: 63201, name: 'KAWERIMIDDE' },
                { id: 64167, name: 'KKUZA' },
                { id: 67660, name: 'NCWAMAZZI' },
                { id: 67798, name: 'NKOKONJERU' },
              ],
            },
          ],
        },
        {
          id: 2027,
          name: 'KIJJUNA',
          parishes: [
            {
              id: 9281,
              name: 'BUCOOCO',
              villages: [
                { id: 59253, name: 'BUCOCO A' },
                { id: 59254, name: 'BUCOCO B' },
                { id: 63194, name: 'KAWALA' },
                { id: 63801, name: 'KIREKU' },
                { id: 65570, name: 'LUBANYI A' },
                { id: 65571, name: 'LUBANYI B' },
                { id: 65572, name: 'LUBANYI C' },
              ],
            },
            {
              id: 9565,
              name: 'KALAGALA',
              villages: [
                { id: 61840, name: 'KABABUGA' },
                { id: 62282, name: 'KALAGALA A' },
                { id: 62283, name: 'KALAGALA B' },
                { id: 62284, name: 'KALAGALA TOWN' },
                { id: 63090, name: 'KATIKANDEGEYA  A' },
                { id: 63091, name: 'KATIKANDEGEYA  C' },
                { id: 65786, name: 'LWANKONGE' },
                { id: 66260, name: 'MIKKA' },
              ],
            },
            {
              id: 9711,
              name: 'KIJJUNA',
              villages: [
                { id: 61094, name: 'DDINGO' },
                { id: 62354, name: 'KALONGO' },
                { id: 63452, name: 'KIDUUZI NORTH' },
                { id: 63453, name: 'KIDUUZI SOUTH' },
                { id: 63601, name: 'KIJJUNA' },
                { id: 65598, name: 'LUGINGI D' },
                { id: 68293, name: 'NYONGA' },
              ],
            },
            {
              id: 9740,
              name: 'KIRYAJOOBYO',
              villages: [
                { id: 62496, name: 'KAMWALO A' },
                { id: 62497, name: 'KAMWALO B' },
                { id: 63216, name: 'KAYANJA' },
                { id: 63841, name: 'KIRYAJOBYO  A' },
                { id: 63842, name: 'KIRYAJOBYO  B' },
              ],
            },
            {
              id: 9830,
              name: 'KYAMULINGA',
              villages: [
                { id: 61839, name: 'KABABUGA' },
                { id: 62479, name: 'KAMUNYAANYA' },
                { id: 63051, name: 'KATEEBE' },
                { id: 63230, name: 'KAYINDA' },
                { id: 64069, name: 'KITONGO A' },
                { id: 64070, name: 'KITONGO B' },
                { id: 64593, name: 'KYALUTEMBE' },
                { id: 64653, name: 'KYAMULINGA' },
                { id: 65791, name: 'LWAWUNA' },
              ],
            },
            {
              id: 9925,
              name: 'LUGINGI',
              villages: [
                { id: 63092, name: 'KATIKANDEGEYA B' },
                { id: 64525, name: 'KYAGUUGU' },
                { id: 65595, name: 'LUGINGI  A' },
                { id: 65596, name: 'LUGINGI  B' },
                { id: 65597, name: 'LUGINGI  C' },
                { id: 65601, name: 'LUGONGWE' },
                { id: 66453, name: 'MPUMUDDE' },
                { id: 67850, name: 'NTAMAGA' },
              ],
            },
          ],
        },
        {
          id: 2037,
          name: 'KITUMBI',
          parishes: [
            {
              id: 9321,
              name: 'BULINIMULA',
              villages: [
                { id: 59712, name: 'BULINIMULA A' },
                { id: 59713, name: 'BULINIMULA B' },
                { id: 60735, name: 'BUYONDO' },
                { id: 65591, name: 'LUGAZI A' },
                { id: 65592, name: 'LUGAZI B' },
                { id: 66505, name: 'MUHUMUZA' },
                { id: 67060, name: 'NAKIGALALA' },
                { id: 70168, name: 'RWENGIRI A' },
                { id: 70169, name: 'RWENGIRI B' },
              ],
            },
            {
              id: 9585,
              name: 'KAMUSENENE',
              villages: [
                { id: 59402, name: 'BUJAAYU' },
                { id: 62486, name: 'KAMUSENENE A' },
                { id: 62487, name: 'KAMUSENENE B' },
                { id: 62490, name: 'KAMUSENENE SOUTH' },
                { id: 63861, name: 'KISAGAZI A' },
                { id: 63862, name: 'KISAGAZI B' },
                { id: 67363, name: 'NAMULANDA' },
              ],
            },
            {
              id: 9770,
              name: 'KITUMBI',
              villages: [
                { id: 62232, name: 'KAKONDWE' },
                { id: 63231, name: 'KAYINJA' },
                { id: 64107, name: 'KITUMBI' },
                { id: 64802, name: 'KYENGERA' },
                { id: 65562, name: 'LUBAALI' },
                { id: 71022, name: 'WANDAGI' },
              ],
            },
            {
              id: 9779,
              name: 'KIZIIKA',
              villages: [
                { id: 62388, name: 'KALYABULO' },
                { id: 63448, name: 'KIDUDUMA' },
                { id: 63798, name: 'KIREEBA A' },
                { id: 63799, name: 'KIREEBA B' },
                { id: 64157, name: 'KIZIIKA/KATUUGO' },
                { id: 64161, name: 'KIZINGA' },
                { id: 64587, name: 'KYAKISIKI' },
                { id: 66740, name: 'MUYENGA' },
                { id: 66806, name: 'NABAGABE' },
              ],
            },
            {
              id: 10006,
              name: 'MUNDADDE',
              villages: [
                { id: 63179, name: 'KATUUGO' },
                { id: 64625, name: 'KYAMBOGO' },
                { id: 66490, name: 'MUGOBWA A' },
                { id: 66491, name: 'MUGOBWA B' },
                { id: 66613, name: 'MUNDADDE A' },
                { id: 66614, name: 'MUNDADDE B' },
                { id: 67713, name: 'NFUKA' },
                { id: 67834, name: 'NSIRA' },
              ],
            },
          ],
        },
        {
          id: 2062,
          name: 'MAKOKOTO',
          parishes: [
            {
              id: 9259,
              name: 'BBIRA',
              villages: [
                { id: 59015, name: 'BBIRA' },
                { id: 61452, name: 'GUNGA' },
                { id: 63110, name: 'KATOGO' },
                { id: 63630, name: 'KIKALAALA' },
                { id: 67666, name: 'NDAIGA' },
              ],
            },
            {
              id: 9329,
              name: 'BULYAMBIDDE',
              villages: [
                { id: 59757, name: 'BULYAMBIDDE' },
                { id: 62910, name: 'KASEESE' },
                { id: 64124, name: 'KIWAATULA' },
                { id: 65845, name: 'MABUUBI' },
                { id: 66990, name: 'NAKABISO' },
                { id: 70833, name: 'TTUBA' },
              ],
            },
            {
              id: 9656,
              name: 'KAWASA',
              villages: [
                { id: 63198, name: 'KAWANJUKI' },
                { id: 63199, name: 'KAWASA' },
                { id: 63224, name: 'KAYEMBE' },
                { id: 64434, name: 'KUZIMU A' },
                { id: 64435, name: 'KUZIMU B' },
              ],
            },
            {
              id: 9809,
              name: 'KYABAKADE',
              villages: [
                { id: 59695, name: 'BULENGEJJA' },
                { id: 60763, name: 'BWANJA' },
                { id: 63204, name: 'KAWOLONGOJO' },
                { id: 64477, name: 'KYABAKADDE' },
                { id: 64478, name: 'KYABAKADDE TOWN' },
                { id: 67799, name: 'NKOLE' },
              ],
            },
            {
              id: 9955,
              name: 'MAKOKOTO',
              villages: [
                { id: 62546, name: 'KANOGA' },
                { id: 63932, name: 'KISIRYE' },
                { id: 65963, name: 'MAKOKOTO' },
                { id: 67661, name: 'NCWAMIGGO' },
              ],
            },
            {
              id: 10050,
              name: 'NAMAKONKOME',
              villages: [
                { id: 60184, name: 'BUNONO' },
                { id: 67018, name: 'NAKASEETA' },
                { id: 67222, name: 'NAMAKONKOME A' },
                { id: 67223, name: 'NAMAKONKOME B' },
                { id: 70544, name: 'SSUNGA A' },
                { id: 70545, name: 'SSUNGA B' },
              ],
            },
          ],
        },
        {
          id: 2065,
          name: 'MBIRIZI',
          parishes: [
            {
              id: 9373,
              name: 'BUSEREGENYU',
              villages: [
                { id: 60298, name: 'BUSEREGENYU A' },
                { id: 60299, name: 'BUSEREGENYU B' },
                { id: 60464, name: 'BUTIMBA' },
                { id: 64062, name: 'KITOMA' },
                { id: 64648, name: 'KYAMUKASA' },
                { id: 69936, name: 'RUKOLA' },
              ],
            },
            {
              id: 9701,
              name: 'KIGUDDE',
              villages: [
                { id: 62882, name: 'KASAMBYA' },
                { id: 63252, name: 'KAZIKIZA' },
                { id: 63419, name: 'KICUMBANSWA' },
                { id: 63534, name: 'KIGUUDE' },
                { id: 63868, name: 'KISALIZI' },
                { id: 64803, name: 'KYENGEZA' },
                { id: 66446, name: 'MPOLOGOMA' },
              ],
            },
            {
              id: 9750,
              name: 'KISIITA',
              villages: [
                { id: 59255, name: 'BUCUCUUKE' },
                { id: 62504, name: 'KANAMIRE' },
                { id: 63388, name: 'KIBONGOYA' },
                { id: 63418, name: 'KICUCUULA' },
                { id: 63923, name: 'KISIITA' },
              ],
            },
            {
              id: 9839,
              name: 'KYATO',
              villages: [
                { id: 59582, name: 'BUKOBA A' },
                { id: 59583, name: 'BUKOBA B' },
                { id: 60662, name: 'BUWEJJE' },
                { id: 63996, name: 'KITAMIRWA' },
                { id: 66151, name: 'MAVUVUMIRA A' },
                { id: 66152, name: 'MAVUVUMIRA B' },
              ],
            },
            {
              id: 9971,
              name: 'MBIRIIZI',
              villages: [
                { id: 62448, name: 'KAMPINDU' },
                { id: 64582, name: 'KYAKIDDU' },
                { id: 64594, name: 'KYALUWOLERA A' },
                { id: 64595, name: 'KYALUWOLERA B' },
                { id: 64752, name: 'KYAWATUBA A' },
                { id: 64753, name: 'KYAWATUBA B  DANGER' },
                { id: 66077, name: 'MASEKE' },
                { id: 66196, name: 'MBIRIIZI' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 82,
      name: 'KASSANDA COUNTY NORTH',
      sub_counties: [
        {
          id: 514,
          name: 'KALWANA',
          parishes: [
            {
              id: 2392,
              name: 'BWEYONGEDDE',
              villages: [
                { id: 15642, name: 'BULAGANO' },
                { id: 15643, name: 'BWEYONGEDDE' },
                { id: 15644, name: 'KABULAMULIRO' },
                { id: 15645, name: 'KALWANGA' },
                { id: 15646, name: 'KITAGONERWA' },
              ],
            },
            {
              id: 2396,
              name: 'DDALAMBA',
              villages: [
                { id: 15665, name: 'BUDDE' },
                { id: 15667, name: 'DDALAMBA' },
                { id: 15666, name: 'KANKOKWA' },
                { id: 15668, name: 'KANSEERA A' },
                { id: 15669, name: 'KANSEERA B' },
                { id: 15671, name: 'KAYUNGA' },
                { id: 15670, name: 'KIBASI' },
                { id: 15672, name: 'NAKASOZI' },
              ],
            },
            {
              id: 2393,
              name: 'KASAAZI',
              villages: [
                { id: 15647, name: 'KABULUBUUTU TOWN' },
                { id: 15648, name: 'KABULUBUUTU VILLAGE' },
                { id: 15649, name: 'KASAAZI  A' },
                { id: 15650, name: 'KASAAZI  B' },
                { id: 15651, name: 'KASAMBYA' },
                { id: 15652, name: 'KYANSOLE' },
                { id: 15653, name: 'LUSAANA' },
              ],
            },
            {
              id: 2394,
              name: 'KIKANDWA',
              villages: [
                { id: 15654, name: 'BUSULA' },
                { id: 15655, name: 'KASENSERO' },
                { id: 15656, name: 'KIKANDWA TOWN' },
                { id: 15657, name: 'KIKANDWA VILLAGE' },
                { id: 15658, name: 'KITEREDDE' },
                { id: 15659, name: 'KITONGO' },
                { id: 15660, name: 'MAKALIZO' },
              ],
            },
            {
              id: 2395,
              name: 'KYABALANZI',
              villages: [
                { id: 15661, name: 'KABUGA' },
                { id: 15662, name: 'KIKULA' },
                { id: 15663, name: 'KYABALANZI' },
                { id: 15664, name: 'NABUGANDO' },
              ],
            },
            {
              id: 2397,
              name: 'LWABAZA',
              villages: [
                { id: 15673, name: 'KABAALE' },
                { id: 15679, name: 'KACWI' },
                { id: 15676, name: 'KYABAKULUNGO' },
                { id: 15678, name: 'LWABAZZA' },
                { id: 15674, name: 'LWAMAGABO' },
                { id: 15675, name: 'LWAMALONGO' },
                { id: 15677, name: 'NAKATOVU' },
                { id: 15680, name: 'NYONJO' },
              ],
            },
            {
              id: 2398,
              name: 'MAYIRIKITI',
              villages: [
                { id: 15681, name: 'KABAKONJO' },
                { id: 15684, name: 'KALAGALA' },
                { id: 15685, name: 'KAMULI' },
                { id: 15686, name: 'KIKUBE' },
                { id: 15682, name: 'KITOOLO' },
                { id: 15687, name: 'MAYIRIKITI' },
                { id: 15683, name: 'NETULIDDE' },
              ],
            },
            {
              id: 2399,
              name: 'NAKATEETE',
              villages: [
                { id: 15688, name: 'BUSAALE' },
                { id: 15689, name: 'KANYOGOGA' },
                { id: 15690, name: 'KYANAMUNUNGU' },
                { id: 15691, name: 'LWANGIRI  A' },
                { id: 15692, name: 'LWANGIRI  B' },
                { id: 15693, name: 'NAKATEETE  A' },
                { id: 15694, name: 'NAKATEETE  B' },
                { id: 15695, name: 'TTUBA' },
              ],
            },
          ],
        },
        {
          id: 2001,
          name: 'KAMULI',
          parishes: [
            {
              id: 9582,
              name: 'KAMULI',
              villages: [
                { id: 62210, name: 'KAKINDU' },
                { id: 62473, name: 'KAMULI' },
                { id: 63777, name: 'KINYONYI  A' },
                { id: 64129, name: 'KIWAWU' },
                { id: 64622, name: 'KYAMBOGA' },
                { id: 65990, name: 'MALABIGAMBO' },
              ],
            },
            {
              id: 9622,
              name: 'KASAMBYA',
              villages: [
                { id: 61841, name: 'KABABUGGA' },
                { id: 61959, name: 'KABULANAKA' },
                { id: 62211, name: 'KAKINDU' },
                { id: 62881, name: 'KASAMBYA' },
                { id: 66098, name: 'MASOOLI' },
              ],
            },
            {
              id: 9849,
              name: 'KYOGA',
              villages: [
                { id: 62194, name: 'KAKATA' },
                { id: 64832, name: 'KYETUME' },
                { id: 64844, name: 'KYOGA  A' },
                { id: 64845, name: 'KYOGA  B' },
                { id: 65695, name: 'LUSOLO A' },
                { id: 65696, name: 'LUSOLO B' },
              ],
            },
            {
              id: 9931,
              name: 'LUSABA',
              villages: [
                { id: 59605, name: 'BUKOOKI' },
                { id: 63142, name: 'KATOVU' },
                { id: 65687, name: 'LUSABA' },
                { id: 67268, name: 'NAMATUBA' },
              ],
            },
            {
              id: 9961,
              name: 'MANYOGASEKA',
              villages: [
                { id: 60369, name: 'BUSIRIMU' },
                { id: 63778, name: 'KINYONYI  B' },
                { id: 66033, name: 'MANYOGASEKA' },
                { id: 67835, name: 'NSOLOLO' },
              ],
            },
          ],
        },
        {
          id: 513,
          name: 'KASSANDA',
          parishes: [
            {
              id: 2389,
              name: 'BINIKIRA',
              villages: [
                { id: 15620, name: 'BBINIKIRA CENTRAL' },
                { id: 15621, name: 'BBINIKIRA EAST' },
                { id: 15622, name: 'BBINIKIRA WEST' },
                { id: 15623, name: 'KYAMASANSA' },
                { id: 15624, name: 'ZIWOMEREDDE' },
              ],
            },
            {
              id: 2391,
              name: 'KAMULI NJAGALA',
              villages: [
                { id: 15636, name: 'KABAGEYA' },
                { id: 15637, name: 'KALAGALA' },
                { id: 15639, name: 'KAMULI' },
                { id: 15638, name: 'KYABAALE' },
                { id: 15640, name: 'LUGOBA' },
                { id: 15641, name: 'NTUUMA' },
              ],
            },
            {
              id: 2383,
              name: 'KITONGO',
              villages: [
                { id: 15569, name: 'BUSENGEJJO' },
                { id: 15570, name: 'BUSWEEKA' },
                { id: 15571, name: 'DWALIRO' },
                { id: 15572, name: 'KABAALE' },
                { id: 15573, name: 'KABUGEZA' },
                { id: 15574, name: 'KAGAVU' },
                { id: 15575, name: 'KAKINDU' },
                { id: 15576, name: 'KASANDA TOWN' },
                { id: 15577, name: 'KAWAAWA' },
                { id: 15578, name: 'KITONGO' },
                { id: 15579, name: 'KYANYONDO' },
                { id: 15580, name: 'KYEDIKYO' },
                { id: 15581, name: 'MAKONZI  A' },
                { id: 15582, name: 'MAKONZI  B' },
                { id: 15583, name: 'MIJJUBWE' },
                { id: 15584, name: 'MIREMBE KAWEESA' },
                { id: 15585, name: 'MWASABIKOPO' },
                { id: 15586, name: 'SSERUNYONYI' },
              ],
            },
            {
              id: 2387,
              name: 'KYANIKA',
              villages: [
                { id: 15604, name: 'KALAMA A' },
                { id: 15610, name: 'KALAMA B' },
                { id: 15609, name: 'KYAMBOGO' },
                { id: 15605, name: 'KYANIKA' },
                { id: 15606, name: 'LUKIGA' },
                { id: 15607, name: 'NAKASAGAZI' },
                { id: 15608, name: 'NAMASWANTA' },
              ],
            },
            {
              id: 2388,
              name: 'MAGGWA',
              villages: [
                { id: 15611, name: 'BIJOGOLI' },
                { id: 15618, name: 'BUSWA A' },
                { id: 15619, name: 'BUSWA B' },
                { id: 15613, name: 'BUSWA C' },
                { id: 15617, name: 'BUSWA WEST' },
                { id: 15612, name: 'BUTEEKA-KIGUMYA' },
                { id: 15614, name: 'JUMA' },
                { id: 15615, name: 'MAGGWA  A' },
                { id: 15616, name: 'MAGGWA  B' },
              ],
            },
            {
              id: 2384,
              name: 'NABUGONDO',
              villages: [
                { id: 15587, name: 'KATABONA' },
                { id: 15592, name: 'KIRAMBULA' },
                { id: 15588, name: 'KYABABEEZI' },
                { id: 15589, name: 'KYERIMA' },
                { id: 15590, name: 'LUSAANA' },
                { id: 15591, name: 'NABUGONDO' },
              ],
            },
            {
              id: 2385,
              name: 'NAMABAALE',
              villages: [
                { id: 15597, name: 'KALAGALA' },
                { id: 15593, name: 'KASIMU' },
                { id: 15594, name: 'KATEMWA' },
                { id: 15595, name: 'LUKOKO' },
                { id: 15596, name: 'NAMABAALE' },
              ],
            },
            {
              id: 2390,
              name: 'NAMIRINGA',
              villages: [
                { id: 15625, name: 'BUKANDE' },
                { id: 15626, name: 'BWAKAGGO' },
                { id: 15627, name: 'JJEMBA EAST' },
                { id: 15628, name: 'JJEMBA WEST' },
                { id: 15629, name: 'KABUUKA' },
                { id: 15630, name: 'KIGOGWA' },
                { id: 15631, name: 'KISENYI' },
                { id: 15632, name: 'MIREMBE MARIA' },
                { id: 15633, name: 'NAMIRINGA' },
                { id: 15634, name: 'NANULA EAST' },
                { id: 15635, name: 'NANULA WEST' },
              ],
            },
            {
              id: 2386,
              name: 'NAMIRINGA (LWANTALE)',
              villages: [
                { id: 15598, name: 'KASAMBYA' },
                { id: 15599, name: 'KASEKERE KAWALA' },
                { id: 15600, name: 'KIRWANIRE' },
                { id: 15601, name: 'KITULEGE' },
                { id: 15602, name: 'LWANTALE KKOKOOWE' },
                { id: 15603, name: 'MUJJUNWA' },
              ],
            },
          ],
        },
        {
          id: 2014,
          name: 'KASSANDA TOWN COUNCIL',
          parishes: [
            {
              id: 9372,
              name: 'BUSENGEJJO WARD',
              villages: [
                { id: 60295, name: 'BUSENGEJJO' },
                { id: 61193, name: 'DWALIRO' },
                { id: 62886, name: 'KASANDA TOWN' },
                { id: 64132, name: 'KIWOLOGOMA' },
                { id: 66327, name: 'MODERN' },
                { id: 66763, name: 'MWASABIKOPO' },
              ],
            },
            {
              id: 9414,
              name: 'CENTRAL WARD',
              villages: [
                { id: 58880, name: 'BALABA' },
                { id: 60851, name: 'CENTRAL' },
                { id: 62329, name: 'KALINAABIRI' },
                { id: 63183, name: 'KATWE' },
                { id: 66742, name: 'MUYENGA' },
              ],
            },
            {
              id: 9515,
              name: 'JJEMBA WARD',
              villages: [
                { id: 59441, name: 'BUKANDE' },
                { id: 61763, name: 'JJEMBA CENTRAL' },
                { id: 61764, name: 'JJEMBA EAST' },
                { id: 61765, name: 'JJEMBA WEST' },
                { id: 61983, name: 'KABUUKA' },
                { id: 63376, name: 'KIBIRA' },
              ],
            },
            {
              id: 9763,
              name: 'KITONGO WARD',
              villages: [
                { id: 62208, name: 'KAKINDU' },
                { id: 63709, name: 'KIMBEJJA' },
                { id: 64067, name: 'KITONGO' },
                { id: 64699, name: 'KYANYONDO' },
                { id: 66253, name: 'MIJJUBWE' },
                { id: 70541, name: 'SSERUNYONYI' },
              ],
            },
            {
              id: 9840,
              name: 'KYEDIKYO WARD',
              villages: [
                { id: 57108, name: 'AASON' },
                { id: 62081, name: 'KAGAVU A' },
                { id: 62082, name: 'KAGAVU B' },
                { id: 64763, name: 'KYEDIKYO A' },
                { id: 64764, name: 'KYEDIKYO B' },
              ],
            },
            {
              id: 9956,
              name: 'MAKONZI WARD',
              villages: [
                { id: 60815, name: 'BYAMBOGO' },
                { id: 61837, name: 'KABAALE' },
                { id: 63191, name: 'KAWAAWA A' },
                { id: 63192, name: 'KAWAAWA B' },
                { id: 65966, name: 'MAKONZI  A' },
                { id: 65967, name: 'MAKONZI  B' },
              ],
            },
            {
              id: 9984,
              name: 'MIREMBE-KAWEESA WARD',
              villages: [
                { id: 60418, name: 'BUSWEEKA' },
                { id: 61950, name: 'KABUGEZA' },
                { id: 63960, name: 'KISOZI' },
                { id: 66293, name: 'MIREMBE KAWEESA A' },
                { id: 66294, name: 'MIREMBE KAWEESA B' },
              ],
            },
            {
              id: 10057,
              name: 'NAMIRINGA WARD',
              villages: [
                { id: 60753, name: 'BWAKAGGO' },
                { id: 63506, name: 'KIGOGWA' },
                { id: 63897, name: 'KISENYI' },
                { id: 66295, name: 'MIREMBE MARIA' },
                { id: 66787, name: 'NAANULA CENTRAL' },
                { id: 66788, name: 'NAANULA EAST' },
                { id: 66789, name: 'NAANULA WEST' },
                { id: 67320, name: 'NAMIRINGA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 83,
      name: 'KASSANDA COUNTY SOUTH',
      sub_counties: [
        {
          id: 515,
          name: 'KIGANDA',
          parishes: [
            {
              id: 2400,
              name: 'KAMUSENENE',
              villages: [
                { id: 15696, name: 'KAMUSENENE' },
                { id: 15697, name: 'KITAYIZA  A' },
                { id: 15698, name: 'KITAYIZA  B' },
                { id: 15699, name: 'KYASAMPAWO' },
              ],
            },
            {
              id: 2407,
              name: 'KASAMBYA',
              villages: [
                { id: 15739, name: 'KASAMBYA' },
                { id: 15742, name: 'KIREKU/KALONGO' },
                { id: 15741, name: 'KISOLOOZA' },
                { id: 15740, name: 'YALA' },
              ],
            },
            {
              id: 2402,
              name: 'KAWUNGERA',
              villages: [
                { id: 15708, name: 'BUSALAMBWA' },
                { id: 15709, name: 'KAWUNGEERA' },
                { id: 15710, name: 'KYAMUSOTA' },
                { id: 15711, name: 'MPOLOGOMA' },
                { id: 15712, name: 'NAKABIMBA' },
                { id: 15713, name: 'SEETA' },
              ],
            },
            {
              id: 2401,
              name: 'KAYUNGA',
              villages: [
                { id: 15700, name: 'KALAMBA' },
                { id: 15701, name: 'KAMUSU' },
                { id: 15702, name: 'KAYUNGA' },
                { id: 15703, name: 'KINYERERA' },
                { id: 15704, name: 'KIRYANONGO' },
                { id: 15705, name: 'KITAAMA' },
                { id: 15706, name: 'NAKASOZI' },
                { id: 15707, name: 'NDIMULABA' },
              ],
            },
            {
              id: 2403,
              name: 'KIGALAMA',
              villages: [
                { id: 15714, name: 'GAYAZA' },
                { id: 15715, name: 'KALAGI' },
                { id: 15716, name: 'KIGALAMA' },
                { id: 15717, name: 'KIMBEJJA' },
                { id: 15718, name: 'KISIGULA' },
                { id: 15720, name: 'LWAMAGAGGA' },
                { id: 15719, name: 'LWAMAGEMBE' },
              ],
            },
            {
              id: 2404,
              name: 'KINONI',
              villages: [
                { id: 15721, name: 'KASAWO EAST' },
                { id: 15722, name: 'KASAWO WEST' },
                { id: 15723, name: 'KIBUULU' },
                { id: 15724, name: 'KINONI' },
                { id: 15725, name: 'NANSIMBI' },
              ],
            },
            {
              id: 2406,
              name: 'KYOJJOMANYI',
              villages: [
                { id: 15733, name: 'KASEBWEMBE' },
                { id: 15734, name: 'KIRYAMENVU' },
                { id: 15735, name: 'KYAMUYINI' },
                { id: 15736, name: 'KYOJJOMANYI' },
                { id: 15737, name: 'MABAALE' },
                { id: 15738, name: 'NAKIDUDDUMA' },
              ],
            },
            {
              id: 2408,
              name: 'MUSOZI',
              villages: [
                { id: 15743, name: 'BULYANKUYEGE' },
                { id: 15744, name: 'KIBOOBA' },
                { id: 15745, name: 'KIREWE' },
                { id: 15746, name: 'MUSOZI/KALUNGI' },
              ],
            },
            {
              id: 2405,
              name: 'NSOZINGA',
              villages: [
                { id: 15726, name: 'BUGAYO' },
                { id: 15727, name: 'KITOVU' },
                { id: 15728, name: 'KYAKAYANJA' },
                { id: 15729, name: 'KYAMWERO' },
                { id: 15730, name: 'LWABUSANA' },
                { id: 15731, name: 'MBAALE' },
                { id: 15732, name: 'NSOZINGA' },
              ],
            },
          ],
        },
        {
          id: 2024,
          name: 'KIGANDA TOWN COUNCIL',
          parishes: [
            {
              id: 9569,
              name: 'KALAMBA WARD',
              villages: [
                { id: 62295, name: 'KALAMBA' },
                { id: 62296, name: 'KALAMBA CENTRAL' },
                { id: 62541, name: 'KANKOLE' },
                { id: 64131, name: 'KIWOGO' },
              ],
            },
            {
              id: 9587,
              name: 'KAMUSU WARD',
              villages: [
                { id: 62494, name: 'KAMUSU' },
                { id: 64033, name: 'KITEREDDE' },
                { id: 67215, name: 'NAMAKAJJO' },
                { id: 67588, name: 'NASULU' },
              ],
            },
            {
              id: 9623,
              name: 'KASAMBYA WARD',
              villages: [
                { id: 62880, name: 'KASAMBYA' },
                { id: 63517, name: 'KIGOOBA' },
                { id: 63772, name: 'KINYERERA' },
                { id: 63943, name: 'KISOLOOZA A' },
                { id: 63944, name: 'KISOLOOZA B' },
              ],
            },
            {
              id: 9659,
              name: 'KAWUNGERA WARD',
              villages: [
                { id: 60755, name: 'BWANDA' },
                { id: 63210, name: 'KAWUNGEERA' },
                { id: 63472, name: 'KIGANDA' },
              ],
            },
            {
              id: 9690,
              name: 'KIGALAMA WARD',
              villages: [
                { id: 61340, name: 'GAYAZA' },
                { id: 62080, name: 'KAGAVU' },
                { id: 62610, name: 'KANYOGOGA' },
                { id: 63471, name: 'KIGALAMA' },
                { id: 66612, name: 'MUNDADDE' },
              ],
            },
            {
              id: 9818,
              name: 'KYAKAYANJA WARD',
              villages: [
                { id: 59316, name: 'BUGAYO' },
                { id: 61934, name: 'KABISAGAZI' },
                { id: 62280, name: 'KALAGALA' },
                { id: 64577, name: 'KYAKAYANJA' },
              ],
            },
            {
              id: 9832,
              name: 'KYAMUSOTA WARD',
              villages: [
                { id: 62182, name: 'KAKA' },
                { id: 62187, name: 'KAKAJO' },
                { id: 64659, name: 'KYAMUSOTA' },
                { id: 66445, name: 'MPOLOGOMA' },
                { id: 67303, name: 'NAMENGO' },
              ],
            },
            {
              id: 10038,
              name: 'NAKABIMBA WARD',
              villages: [
                { id: 60263, name: 'BUSALAMBWA' },
                { id: 66743, name: 'MUYENGA' },
                { id: 66989, name: 'NAKABIMBA' },
                { id: 70297, name: 'SEETA' },
              ],
            },
            {
              id: 10043,
              name: 'NAKIDUDUMA WARD',
              villages: [
                { id: 60738, name: 'BUYONGA' },
                { id: 63140, name: 'KATOSI' },
                { id: 63995, name: 'KITAMIRWA' },
                { id: 66853, name: 'NABITOMA' },
                { id: 67058, name: 'NAKIDUDDUMA' },
              ],
            },
            {
              id: 10101,
              name: 'NSOZINGA WARD',
              villages: [
                { id: 61861, name: 'KABALUNGI' },
                { id: 64667, name: 'KYAMWERO' },
                { id: 66807, name: 'NABAKAZI' },
                { id: 67842, name: 'NSOZINGA A' },
                { id: 67843, name: 'NSOZINGA B' },
              ],
            },
          ],
        },
        {
          id: 517,
          name: 'MANYOGASEKA',
          parishes: [
            {
              id: 2416,
              name: 'KAWAWA',
              villages: [
                { id: 15795, name: 'KAWAWA' },
                { id: 15796, name: 'LWEMITONGOLE' },
                { id: 15794, name: 'LWENKALABO' },
                { id: 15797, name: 'LWENYANGE' },
              ],
            },
            {
              id: 2417,
              name: 'KITEREDDE',
              villages: [
                { id: 15798, name: 'BUNAKABWA' },
                { id: 15799, name: 'KITEREDDE' },
                { id: 15800, name: 'LWAKABUTU' },
                { id: 15801, name: 'LWAMUJENYI' },
              ],
            },
            {
              id: 2415,
              name: 'KYABAYIMA',
              villages: [
                { id: 15791, name: 'KABULENGWA' },
                { id: 15792, name: 'KYABAYIMA' },
                { id: 15793, name: 'LWEMIRITI' },
              ],
            },
            {
              id: 2418,
              name: 'KYAYI',
              villages: [
                { id: 15804, name: 'KASAWO/MUKADDE' },
                { id: 15802, name: 'KASHENYI' },
                { id: 15805, name: 'KYAYI' },
                { id: 15803, name: 'NABISISI' },
              ],
            },
            {
              id: 2413,
              name: 'LUTUNKU',
              villages: [
                { id: 15783, name: 'KYASANSUWA' },
                { id: 15784, name: 'LUTUNKU' },
                { id: 15782, name: 'LWENSOLOLO' },
              ],
            },
            {
              id: 2414,
              name: 'MANYOGASEKA',
              villages: [
                { id: 15785, name: 'BUZAWULA  A' },
                { id: 15786, name: 'BUZAWULA  B' },
                { id: 15790, name: 'KARUNAGA' },
                { id: 15788, name: 'KAZINGA' },
                { id: 15787, name: 'MANYOGASEKA' },
                { id: 15789, name: 'NABITOMA' },
              ],
            },
            {
              id: 2419,
              name: 'MYALIRO',
              villages: [
                { id: 15808, name: 'KYAKITANGA A' },
                { id: 15809, name: 'KYAKITANGA B' },
                { id: 15810, name: 'MYALIRO A' },
                { id: 15806, name: 'MYALIRO B' },
                { id: 15807, name: 'MYALIRO C' },
              ],
            },
            {
              id: 2420,
              name: 'NDEEBA',
              villages: [
                { id: 15811, name: 'KITABAZI' },
                { id: 15813, name: 'KIWANGULA' },
                { id: 15812, name: 'NATETE' },
                { id: 15814, name: 'NDEEBA' },
              ],
            },
          ],
        },
        {
          id: 516,
          name: 'MYANZI',
          parishes: [
            {
              id: 2409,
              name: 'KAMPIRI',
              villages: [
                { id: 15747, name: 'BULYAMAGUNJU  I' },
                { id: 15748, name: 'BULYAMAGUNJU  II' },
                { id: 15749, name: 'GWAFU' },
                { id: 15750, name: 'KITANDWE' },
                { id: 15751, name: 'KYASEETA  I' },
                { id: 15752, name: 'KYASEETA  II' },
                { id: 15753, name: 'LUKIRA' },
                { id: 15754, name: 'MAKATA' },
              ],
            },
            {
              id: 2410,
              name: 'KASAANA',
              villages: [
                { id: 15755, name: 'BINAKOOTA' },
                { id: 15756, name: 'KASAANA' },
                { id: 15757, name: 'LUKOMA' },
                { id: 15758, name: 'MUSABA  I' },
                { id: 15759, name: 'MUSABA  II' },
                { id: 15760, name: 'MUYENJE' },
                { id: 15762, name: 'NABWEYO' },
                { id: 15761, name: 'NAKASOZI' },
                { id: 15763, name: 'NAKIGOYE' },
              ],
            },
            {
              id: 2411,
              name: 'KIGALAMA',
              villages: [
                { id: 15764, name: 'KANZIIRA  A' },
                { id: 15765, name: 'KANZIIRA  B' },
                { id: 15766, name: 'KIDDUKULU' },
                { id: 15767, name: 'KIGALAMA  A' },
                { id: 15768, name: 'KIGALAMA  B' },
                { id: 15769, name: 'KITAAMA' },
                { id: 15770, name: 'KYENGEZA' },
                { id: 15771, name: 'NAKASOZI' },
              ],
            },
            {
              id: 2412,
              name: 'MYANZI',
              villages: [
                { id: 15772, name: 'BAGWE' },
                { id: 15773, name: 'BUGOLO' },
                { id: 15774, name: 'KALAMA' },
                { id: 15775, name: 'KATOOKE' },
                { id: 15776, name: 'KISWEERA' },
                { id: 15777, name: 'LUBUMBA' },
                { id: 15778, name: 'LUSWA' },
                { id: 15780, name: 'MYANZI T.C.' },
                { id: 15779, name: 'MYANZI V' },
                { id: 15781, name: 'TONTEREKERA' },
              ],
            },
          ],
        },
        {
          id: 518,
          name: 'NALUTUNTU',
          parishes: [
            {
              id: 2424,
              name: 'GAMBWA',
              villages: [
                { id: 15843, name: 'BUJERU' },
                { id: 15844, name: 'GAMBWA' },
                { id: 15845, name: 'KAKINDU' },
                { id: 15846, name: 'KITALEGERWA' },
                { id: 15847, name: 'KITONYA' },
                { id: 15848, name: 'KYAWATUBA' },
                { id: 15849, name: 'NAMASENGERE' },
              ],
            },
            {
              id: 2421,
              name: 'KYAKATEBE',
              villages: [
                { id: 15815, name: 'BUKOMPE' },
                { id: 15816, name: 'KANYOGOGA' },
                { id: 15817, name: 'KAYUNGA' },
                { id: 15818, name: 'KIWUUBA' },
                { id: 15819, name: 'KYAKATEBE' },
                { id: 15820, name: 'LWAMASANGA' },
                { id: 15821, name: 'MIREMBE' },
                { id: 15822, name: 'NAMUGANGA' },
                { id: 15823, name: 'NKOKOOMA' },
              ],
            },
            {
              id: 2422,
              name: 'KYANAMUGERA',
              villages: [
                { id: 15824, name: 'KAKUNGUBE' },
                { id: 15825, name: 'KALAGI' },
                { id: 15826, name: 'KATUUGO  A' },
                { id: 15827, name: 'KATUUGO  B' },
                { id: 15828, name: 'KIBONWA' },
                { id: 15829, name: 'KISAANA' },
                { id: 15830, name: 'KYAMUGERI' },
                { id: 15831, name: 'KYANAMUGERA' },
                { id: 15832, name: 'NKANDWA' },
              ],
            },
            {
              id: 2423,
              name: 'NALUTUNTU',
              villages: [
                { id: 15833, name: 'BUKOBA' },
                { id: 15834, name: 'KABAGALA' },
                { id: 15835, name: 'KIBANYI' },
                { id: 15836, name: 'KIWUMULO  A' },
                { id: 15837, name: 'KIWUMULO  B' },
                { id: 15838, name: 'KYAKASENGULA' },
                { id: 15839, name: 'KYAKATEBE  A' },
                { id: 15840, name: 'KYAKATEBE  B' },
                { id: 15841, name: 'KYAKAYONGO' },
                { id: 15842, name: 'NAMUGANGA' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
