import { District } from '../types';

export default {
  id: 71,
  name: 'KATAKWI',
  counties: [
    {
      id: 174,
      name: 'TOROMA COUNTY',
      sub_counties: [
        {
          id: 1072,
          name: 'AMUSIA',
          parishes: [
            {
              id: 4954,
              name: 'ABULE',
              villages: [
                { id: 31687, name: 'ABOLOI' },
                { id: 31689, name: 'ABULE' },
                { id: 31688, name: 'ADOKAR' },
                { id: 31690, name: 'ATAPAR' },
                { id: 31692, name: 'MADERA' },
                { id: 31691, name: 'OKICIRA' },
              ],
            },
            {
              id: 4956,
              name: 'AMUSIA',
              villages: [
                { id: 31698, name: 'ADURUKOI' },
                { id: 31700, name: 'AGULE A' },
                { id: 31701, name: 'AGULE B' },
                { id: 31699, name: 'AMUSIA CENTRAL' },
                { id: 31702, name: 'OKILE' },
                { id: 31703, name: 'OMAJU' },
              ],
            },
            {
              id: 4957,
              name: 'ASURET',
              villages: [
                { id: 31704, name: 'AKISIM' },
                { id: 58590, name: 'ASURET' },
                { id: 31707, name: 'CONGO' },
                { id: 31705, name: 'OMUSUNGUN A' },
                { id: 31706, name: 'OMUSUNGUN B' },
                { id: 69023, name: 'OMUSUNGUN C' },
              ],
            },
            {
              id: 4955,
              name: 'MORU',
              villages: [
                { id: 58267, name: 'ANGARO' },
                { id: 58580, name: 'ASINGE' },
                { id: 31694, name: 'MORU  A' },
                { id: 31695, name: 'MORU  B' },
                { id: 31697, name: 'MORU COMPLEX' },
                { id: 31693, name: 'OJIJIMA' },
                { id: 68636, name: 'OJIJIMA EAST' },
                { id: 31696, name: 'ORISAI' },
              ],
            },
          ],
        },
        {
          id: 1073,
          name: 'ANGODINGOD',
          parishes: [
            {
              id: 4958,
              name: 'ACUNA',
              villages: [
                { id: 31708, name: 'ACUNA' },
                { id: 31709, name: 'AGUYAI' },
                { id: 58444, name: 'APUUTON' },
                { id: 60837, name: 'CANAN' },
                { id: 31710, name: 'OTUKO' },
              ],
            },
            {
              id: 4959,
              name: 'AKISIM',
              villages: [
                { id: 31711, name: 'AGEGO' },
                { id: 57668, name: 'AJOKOMOT' },
                { id: 31712, name: 'AKISIM' },
                { id: 57847, name: 'AKULUME' },
                { id: 31713, name: 'ALELES' },
                { id: 68745, name: 'OKWII' },
              ],
            },
            {
              id: 4961,
              name: 'ANGODINGOD',
              villages: [
                { id: 31718, name: 'AKALELE' },
                { id: 31719, name: 'ANGODINGOD' },
                { id: 68809, name: 'OLIDET' },
                { id: 31720, name: 'OMAGARA' },
                { id: 69270, name: 'OSUDIO' },
              ],
            },
            {
              id: 4960,
              name: 'ATETE',
              villages: [
                { id: 31715, name: 'ALOET' },
                { id: 31716, name: 'ATETE' },
                { id: 31717, name: 'OKERISIO' },
                { id: 31714, name: 'OMONYOKORIO' },
                { id: 69077, name: 'ONOTAI' },
              ],
            },
          ],
        },
        {
          id: 1071,
          name: 'KAPUJAN',
          parishes: [
            {
              id: 4951,
              name: 'KAPUJAN',
              villages: [
                { id: 31669, name: 'ADODOI' },
                { id: 31670, name: 'APULE' },
                { id: 31671, name: 'ARIET' },
                { id: 31672, name: 'DAMASIKO' },
                { id: 31673, name: 'KELIM/KAPUJAN' },
                { id: 31674, name: 'OKII' },
              ],
            },
            {
              id: 4952,
              name: 'KOKORIO',
              villages: [
                { id: 31675, name: 'KOKORIO' },
                { id: 31676, name: 'OIDOTONGOLE' },
                { id: 31677, name: 'OMOSINGO' },
                { id: 31678, name: 'OREGIA' },
                { id: 31679, name: 'OSUGURO' },
                { id: 31680, name: 'SORIMAN' },
              ],
            },
            {
              id: 4953,
              name: 'ORIMAI',
              villages: [
                { id: 31681, name: 'AGULE' },
                { id: 31682, name: 'AKOBOI' },
                { id: 31683, name: 'GORIA' },
                { id: 31684, name: 'KELIM/ORIMAI' },
                { id: 31685, name: 'OCELAKWENY' },
                { id: 31686, name: 'OSONGAI' },
              ],
            },
          ],
        },
        {
          id: 1074,
          name: 'MAGORO',
          parishes: [
            {
              id: 4966,
              name: 'ANGISA',
              villages: [
                { id: 31747, name: 'ABOBOREI' },
                { id: 31748, name: 'AGEREGER' },
                { id: 57963, name: 'ALENGO' },
                { id: 31749, name: 'AMAIDO' },
                { id: 31750, name: 'ANGARO' },
                { id: 31751, name: 'ANGISA' },
                { id: 58384, name: 'APEITOLIM' },
                { id: 58392, name: 'APERIT ISIRU' },
                { id: 31752, name: 'APOPONG' },
                { id: 58645, name: 'ATIRAI' },
              ],
            },
            {
              id: 4962,
              name: 'KAMENU',
              villages: [
                { id: 31721, name: 'AGIRITOM' },
                { id: 31722, name: 'ALELES' },
                { id: 31723, name: 'APELEUN' },
                { id: 31724, name: 'APUUTON' },
                { id: 31728, name: 'ATAPAR' },
                { id: 31725, name: 'KAMENU' },
                { id: 31726, name: 'OBWOKOMOR' },
                { id: 31727, name: 'OKORIO' },
                { id: 31729, name: 'OSUDIO' },
              ],
            },
            {
              id: 4963,
              name: 'MAGORO',
              villages: [
                { id: 31730, name: 'AJAMAKA' },
                { id: 31731, name: 'AKWOORO' },
                { id: 58264, name: 'ANGARO' },
                { id: 31732, name: 'APEERO' },
                { id: 31733, name: 'KANAPA' },
                { id: 31734, name: 'MAGORO CENTRE' },
                { id: 68645, name: 'OJOM' },
              ],
            },
            {
              id: 4964,
              name: 'OMASIA',
              villages: [
                { id: 31735, name: 'ADURUKOI' },
                { id: 31740, name: 'KAIKAMOSING' },
                { id: 31741, name: 'KIIYA' },
                { id: 31736, name: 'KIPINYANG' },
                { id: 31737, name: 'OOLIR' },
                { id: 31738, name: 'ORIAU  A' },
                { id: 31739, name: 'ORIAU  B' },
              ],
            },
            {
              id: 4965,
              name: 'OPETA',
              villages: [
                { id: 31742, name: 'AGULE' },
                { id: 31743, name: 'AKISIM' },
                { id: 31746, name: 'KAREU' },
                { id: 31744, name: 'KIDE' },
                { id: 31745, name: 'LALEI' },
              ],
            },
          ],
        },
        {
          id: 1075,
          name: 'MAGORO TOWN COUNCIL',
          parishes: [
            {
              id: 4967,
              name: 'EASTERN WARD',
              villages: [
                { id: 31753, name: 'ATAPAR INANGUT' },
                { id: 31754, name: 'KAMECA' },
                { id: 31755, name: 'OIGO' },
                { id: 31756, name: 'TANK' },
              ],
            },
            {
              id: 4968,
              name: 'OBWANGOR WARD',
              villages: [
                { id: 31757, name: 'AKISIM' },
                { id: 31759, name: 'CENTRE CELL' },
                { id: 31758, name: 'OBWANGOR' },
              ],
            },
          ],
        },
        {
          id: 1078,
          name: 'OMODOI',
          parishes: [
            {
              id: 4976,
              name: 'ADUNGULU',
              villages: [
                { id: 31793, name: 'ADUNGULU' },
                { id: 68839, name: 'OLOBAI' },
                { id: 68963, name: 'OMODOI CENTRAL' },
                { id: 69691, name: 'PIONEER' },
                { id: 70746, name: 'TIITI' },
              ],
            },
            {
              id: 4977,
              name: 'AKOBOI',
              villages: [
                { id: 31795, name: 'AKOBOI' },
                { id: 31794, name: 'APOPONG' },
                { id: 31797, name: 'OCAKARATURA' },
                { id: 31798, name: 'OCEP' },
                { id: 31796, name: 'OKOKOMA' },
              ],
            },
            {
              id: 4980,
              name: 'APARISA',
              villages: [
                { id: 31806, name: 'AMEKEDE' },
                { id: 31810, name: 'AMUKURAT' },
                { id: 31807, name: 'APARISIA A' },
                { id: 31808, name: 'APARISIA B' },
                { id: 31809, name: 'OCULURA' },
              ],
            },
            {
              id: 4978,
              name: 'ATIRIR',
              villages: [
                { id: 31801, name: 'APELEUN' },
                { id: 31800, name: 'ATIRIR' },
                { id: 68467, name: 'ODIKE' },
                { id: 31799, name: 'OGUGUT' },
              ],
            },
            {
              id: 4979,
              name: 'OMODOI',
              villages: [
                { id: 57788, name: 'AKIIMIT' },
                { id: 31802, name: 'AKWAKEL' },
                { id: 31803, name: 'KAREU' },
                { id: 31804, name: 'NAPAKOL' },
                { id: 31805, name: 'OMODOI UPPER' },
              ],
            },
          ],
        },
        {
          id: 1076,
          name: 'TOROMA',
          parishes: [
            {
              id: 4969,
              name: 'AKURAO',
              villages: [
                { id: 31765, name: 'ACUNA' },
                { id: 31760, name: 'AJELEL' },
                { id: 31761, name: 'AKURAO' },
                { id: 31762, name: 'ALELES' },
                { id: 31763, name: 'ALER' },
                { id: 31764, name: 'MAGARA' },
              ],
            },
            {
              id: 4972,
              name: 'APUUTON',
              villages: [
                { id: 31788, name: 'ABATAIT' },
                { id: 31780, name: 'ADAPUR' },
                { id: 31781, name: 'AKISIM' },
                { id: 31782, name: 'ANGIRINYI' },
                { id: 31783, name: 'APUUTON' },
                { id: 31784, name: 'ASINGE' },
                { id: 31785, name: 'MUNYANGA' },
                { id: 31786, name: 'ODOKUNA' },
                { id: 31787, name: 'OLET' },
              ],
            },
            {
              id: 4970,
              name: 'OMINYA',
              villages: [
                { id: 31766, name: 'AGULE' },
                { id: 31776, name: 'AKARAMAI' },
                { id: 31767, name: 'AKWAKELA' },
                { id: 31770, name: 'KANGAIDA' },
                { id: 31771, name: 'OLUPE' },
                { id: 31772, name: 'OMINYA' },
                { id: 31768, name: 'ONGATUNYO-AGULE' },
                { id: 31769, name: 'ONGATUNYO-OMINYA' },
                { id: 31773, name: 'ONGOKIA' },
                { id: 31774, name: 'ONYURUTI' },
                { id: 31775, name: 'SUDAN' },
              ],
            },
            {
              id: 4971,
              name: 'TOROMA',
              villages: [
                { id: 31777, name: 'MORUNYANG' },
                { id: 31779, name: 'MORUNYANG B' },
                { id: 31778, name: 'OMIRO' },
              ],
            },
          ],
        },
        {
          id: 1077,
          name: 'TOROMA TOWN COUNCIL',
          parishes: [
            {
              id: 4973,
              name: 'ATOROM OBONGUT WARD',
              villages: [
                { id: 57189, name: 'ABOBORE' },
                { id: 58663, name: 'ATOROMA OBONGUT' },
                { id: 31789, name: 'TOROMA TRADING CENTRE' },
              ],
            },
            {
              id: 4974,
              name: 'NORTHERN WARD',
              villages: [
                { id: 57238, name: 'ABROSINGE' },
                { id: 61267, name: 'EPAKU' },
                { id: 31790, name: 'MAJENGO' },
              ],
            },
            {
              id: 4975,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 31791, name: 'CENTRAL' },
                { id: 31792, name: 'KK CELL' },
                { id: 70310, name: 'SENIOR QUARTERS' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 173,
      name: 'USUK COUNTY',
      sub_counties: [
        {
          id: 1059,
          name: 'AKOBOI',
          parishes: [
            {
              id: 4873,
              name: 'AKOBOI',
              villages: [
                { id: 57642, name: 'AJENEBUKUI' },
                { id: 31402, name: 'AKOBOI' },
                { id: 31406, name: 'ASITUNI' },
                { id: 31403, name: 'EKODE' },
                { id: 31404, name: 'OILOTOR' },
                { id: 31405, name: 'OMODINGO' },
              ],
            },
            {
              id: 4874,
              name: 'ALELES',
              villages: [
                { id: 31407, name: 'ACOME' },
                { id: 31408, name: 'AGURIGUR' },
                { id: 31409, name: 'ALELES' },
                { id: 31411, name: 'ARIAMARENG' },
                { id: 31410, name: 'ATEKWA' },
                { id: 31412, name: 'ORIAU' },
              ],
            },
            {
              id: 4875,
              name: 'ALUKUCOK',
              villages: [
                { id: 31413, name: 'ALUKUCOK' },
                { id: 58492, name: 'ARIAMIRIAM' },
                { id: 31414, name: 'OGONGORA' },
                { id: 31416, name: 'ONYOPAI' },
                { id: 31415, name: 'OTOMEI' },
              ],
            },
            {
              id: 4876,
              name: 'DADAS',
              villages: [
                { id: 31420, name: 'ANGOPET' },
                { id: 31417, name: 'ATERAI' },
                { id: 58705, name: 'AWANGAGOLA' },
                { id: 31418, name: 'DADAS' },
                { id: 31419, name: 'OTUBOI' },
              ],
            },
            {
              id: 4877,
              name: 'LALEI',
              villages: [
                { id: 31422, name: 'LALEI A' },
                { id: 31423, name: 'LALEI B' },
                { id: 68801, name: 'OLEROI' },
                { id: 31421, name: 'OMURIAKORI' },
              ],
            },
            {
              id: 4878,
              name: 'OKOKOMA',
              villages: [
                { id: 58200, name: 'AMUKURAT' },
                { id: 31424, name: 'ASINGE' },
                { id: 31425, name: 'MORUINYAMAT' },
                { id: 68338, name: 'OBELE' },
                { id: 31426, name: 'OKOKOMA' },
                { id: 68961, name: 'OMODO' },
              ],
            },
          ],
        },
        {
          id: 1062,
          name: 'GETOM',
          parishes: [
            {
              id: 4892,
              name: 'ABELA',
              villages: [
                { id: 31472, name: 'CHEELE' },
                { id: 62152, name: 'KAIMORU' },
                { id: 31471, name: 'KIDE' },
                { id: 31473, name: 'MORU  A' },
                { id: 31474, name: 'MORU  B' },
                { id: 68445, name: 'ODEBEI' },
              ],
            },
            {
              id: 4890,
              name: 'ABOIBOI',
              villages: [
                { id: 31465, name: 'ABOIBOI' },
                { id: 31468, name: 'AFRICA' },
                { id: 60894, name: 'CHEELE NORTH' },
                { id: 31466, name: 'MORUAPESUR' },
                { id: 31467, name: 'ONGUOK' },
              ],
            },
            {
              id: 4893,
              name: 'ABWANGET',
              villages: [
                { id: 31475, name: 'ABWANGET' },
                { id: 31477, name: 'AGUYA' },
                { id: 31476, name: 'NAMULE' },
              ],
            },
            {
              id: 4891,
              name: 'AJESAI',
              villages: [
                { id: 31470, name: 'AJESAI' },
                { id: 31469, name: 'OTIAKOL' },
                { id: 69480, name: 'PAILAKOL' },
              ],
            },
            {
              id: 4894,
              name: 'ANGOROM',
              villages: [
                { id: 31478, name: 'ANGOROM' },
                { id: 31481, name: 'IGOLA' },
                { id: 31479, name: 'NAMULE' },
                { id: 31480, name: 'ORIAMAI' },
              ],
            },
            {
              id: 4895,
              name: 'GETOM',
              villages: [
                { id: 57523, name: 'AENE' },
                { id: 31483, name: 'AKULET' },
                { id: 31484, name: 'GETOM' },
                { id: 31485, name: 'OGUYAI' },
                { id: 31482, name: 'PAILEKOL' },
              ],
            },
            {
              id: 4896,
              name: 'OLUPE',
              villages: [
                { id: 57493, name: 'ADUSE' },
                { id: 57554, name: 'AGOLOMIR' },
                { id: 58673, name: 'ATURITUR' },
                { id: 31486, name: 'MUKOKORO' },
                { id: 31487, name: 'OJUTAI' },
                { id: 31488, name: 'OLUPE' },
              ],
            },
          ],
        },
        {
          id: 1064,
          name: 'GUYAGUYA',
          parishes: [
            {
              id: 4911,
              name: 'AAKUM',
              villages: [
                { id: 31518, name: 'ACHANGA' },
                { id: 31519, name: 'AMERITELE' },
                { id: 31521, name: 'APUUTON' },
                { id: 31520, name: 'OCOR-OKUM' },
                { id: 68945, name: 'OMEON' },
              ],
            },
            {
              id: 4912,
              name: 'ADACAR',
              villages: [
                { id: 31522, name: 'ADACAR' },
                { id: 58377, name: 'APEERO' },
                { id: 68336, name: 'OBEEJET' },
                { id: 31523, name: 'OKADANYA' },
                { id: 31524, name: 'OKIBUI' },
              ],
            },
            {
              id: 4910,
              name: 'GUYAGUYA',
              villages: [
                { id: 57374, name: 'ACUMA' },
                { id: 31516, name: 'GUYAGUYA' },
                { id: 31517, name: 'ODOOM' },
                { id: 69288, name: 'OTEKETEKE' },
              ],
            },
            {
              id: 4914,
              name: 'ORUNGO TOWN BOARD',
              villages: [
                { id: 31528, name: 'ACERA' },
                { id: 57671, name: 'AJOPO' },
                { id: 31529, name: 'AMUKURAT' },
                { id: 31530, name: 'ORUNGO CORNER' },
              ],
            },
            {
              id: 4913,
              name: 'TOIBONG',
              villages: [
                { id: 57782, name: 'AKEREO' },
                { id: 58378, name: 'APEERO' },
                { id: 31527, name: 'APUUTON - OKINYANG' },
                { id: 31525, name: 'OITELA' },
                { id: 31526, name: 'TOIBONG' },
              ],
            },
          ],
        },
        {
          id: 1060,
          name: 'KATAKWI',
          parishes: [
            {
              id: 4879,
              name: 'ALIAKAMER',
              villages: [
                { id: 31427, name: 'ABELEBUKU' },
                { id: 31428, name: 'AELENYANG' },
                { id: 31431, name: 'ALIAKAMER' },
                { id: 31429, name: 'APUUTON' },
                { id: 31430, name: 'OALE' },
                { id: 68426, name: 'OCOMAI' },
              ],
            },
            {
              id: 4881,
              name: 'ALOGOOK',
              villages: [
                { id: 31438, name: 'AJOKOPIR' },
                { id: 31436, name: 'AKWENYUTU' },
                { id: 31439, name: 'ALOGOOK' },
                { id: 31440, name: 'AMURIA' },
                { id: 31437, name: 'IGOLA' },
                { id: 69133, name: 'OPOC' },
              ],
            },
            {
              id: 4883,
              name: 'APARISA',
              villages: [
                { id: 31445, name: 'ADIDIT' },
                { id: 31446, name: 'APARISIA' },
                { id: 68347, name: 'OBILIKERETA' },
                { id: 68844, name: 'OLOJA' },
              ],
            },
            {
              id: 4884,
              name: 'APOLIN',
              villages: [
                { id: 31448, name: 'AGURIGUR' },
                { id: 31449, name: 'ANGOBO' },
                { id: 31450, name: 'APOLIN' },
                { id: 31451, name: 'APUUTON' },
                { id: 31447, name: 'ATIRIR' },
              ],
            },
            {
              id: 4880,
              name: 'KATAKWI',
              villages: [
                { id: 31432, name: 'ABUROSINGE' },
                { id: 31434, name: 'AUJONGABA' },
                { id: 31435, name: 'OCORIMONGIN' },
                { id: 31433, name: 'OLESAI' },
              ],
            },
            {
              id: 4885,
              name: 'OCORIMONGIN TOWN BOARD',
              villages: [
                { id: 31452, name: 'ABUROSINGE' },
                { id: 31453, name: 'OCORIMONGIN' },
              ],
            },
            {
              id: 4882,
              name: 'OLELA',
              villages: [
                { id: 31441, name: 'AJEELUK' },
                { id: 31442, name: 'KEELIM' },
                { id: 31444, name: 'OLELA' },
                { id: 31443, name: 'OSUPA' },
              ],
            },
            {
              id: 4886,
              name: 'OSUDAN',
              villages: [
                { id: 31454, name: 'AKISIM' },
                { id: 31455, name: 'GUYAGUYA' },
                { id: 69064, name: 'ONGOPAI' },
                { id: 31456, name: 'OSUDAN' },
                { id: 31457, name: 'WERA' },
              ],
            },
          ],
        },
        {
          id: 1061,
          name: 'KATAKWI TOWN COUNCIL',
          parishes: [
            {
              id: 4887,
              name: 'NOTHERN WARD',
              villages: [
                { id: 31458, name: 'CENTRAL' },
                { id: 31459, name: 'KATANGA' },
              ],
            },
            {
              id: 4888,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 31460, name: 'ALELES' },
                { id: 31461, name: 'ANGOPET' },
              ],
            },
            {
              id: 4889,
              name: 'WESTERN WARD',
              villages: [
                { id: 31462, name: 'AJELUK' },
                { id: 31463, name: 'DOKOMER' },
                { id: 31464, name: 'PAMBA' },
              ],
            },
          ],
        },
        {
          id: 1063,
          name: 'NGARIAM',
          parishes: [
            {
              id: 4901,
              name: 'ACANGA',
              villages: [
                { id: 57311, name: 'ACANGA' },
                { id: 31500, name: 'APUUTON' },
                { id: 58624, name: 'ATEKWA' },
                { id: 69336, name: 'OUDEKE' },
                { id: 70875, name: 'TURUKAN' },
              ],
            },
            {
              id: 4902,
              name: 'ADIPALA',
              villages: [
                { id: 31501, name: 'ACEGELEKINEI' },
                { id: 31502, name: 'ADIPALA' },
                { id: 58172, name: 'AMONIEIK' },
                { id: 31504, name: 'APUTIPUT' },
                { id: 68393, name: 'OBWALAKOU' },
                { id: 68618, name: 'OIPWOR' },
                { id: 31503, name: 'OKWEE' },
              ],
            },
            {
              id: 4899,
              name: 'AKISIM',
              villages: [
                { id: 57588, name: 'AGUURUC' },
                { id: 31494, name: 'AKISIM' },
                { id: 31495, name: 'ALUNGAR' },
                { id: 58119, name: 'AMEN' },
                { id: 31496, name: 'ATAPAR' },
              ],
            },
            {
              id: 4903,
              name: 'AMORU',
              villages: [
                { id: 58118, name: 'AMEILA' },
                { id: 31505, name: 'AMORU' },
                { id: 61375, name: 'GILGIL' },
                { id: 68435, name: 'OCULURU' },
                { id: 69027, name: 'OMWATOK' },
              ],
            },
            {
              id: 4904,
              name: 'APELEUN',
              villages: [
                { id: 58126, name: 'AMERIMON' },
                { id: 58263, name: 'ANGARO' },
                { id: 31506, name: 'APELEUN' },
                { id: 31507, name: 'APUUTON' },
                { id: 68409, name: 'OCEKAI' },
              ],
            },
            {
              id: 4897,
              name: 'BISINA',
              villages: [
                { id: 58334, name: 'ANYIPA' },
                { id: 58581, name: 'ASINGE' },
                { id: 31489, name: 'ATAPAR' },
                { id: 31490, name: 'BISINA' },
                { id: 31491, name: 'OSEP' },
              ],
            },
            {
              id: 4898,
              name: 'KAIKAMOSING',
              villages: [
                { id: 57252, name: 'ABULE' },
                { id: 31492, name: 'ADOKAR' },
                { id: 58634, name: 'ATIIRA' },
                { id: 58643, name: 'ATIPO' },
                { id: 31493, name: 'KAIKAMOSING' },
                { id: 67735, name: 'NGARIAM HEADQUARTERS' },
                { id: 68379, name: 'OBULEKAPEL' },
                { id: 68619, name: 'OITAGWEL' },
              ],
            },
            {
              id: 4905,
              name: 'NYERO',
              villages: [
                { id: 57466, name: 'ADOPUT' },
                { id: 57872, name: 'AKUTAKAN' },
                { id: 58437, name: 'APUTIRO' },
                { id: 31508, name: 'NYERO' },
                { id: 68677, name: 'OKICHIRA' },
              ],
            },
            {
              id: 4906,
              name: 'OEDEPUS',
              villages: [
                { id: 58585, name: 'ASOGOL' },
                { id: 58657, name: 'ATOBOCO' },
                { id: 68450, name: 'ODENGERUO' },
                { id: 68534, name: 'OEDEPUS' },
                { id: 31509, name: 'ORIBOK' },
                { id: 69297, name: 'OTIBOK' },
                { id: 69299, name: 'OTIMONG' },
              ],
            },
            {
              id: 4907,
              name: 'OKUSO',
              villages: [
                { id: 57229, name: 'ABONGOSI' },
                { id: 57832, name: 'AKORINYANG' },
                { id: 57904, name: 'AKWORO' },
                { id: 68342, name: 'OBIAT' },
                { id: 68448, name: 'ODELO' },
                { id: 31510, name: 'OKUSO' },
              ],
            },
            {
              id: 4908,
              name: 'OLUPE',
              villages: [
                { id: 31512, name: 'AGURUR' },
                { id: 57623, name: 'AILIKONYE' },
                { id: 57624, name: 'AIPANYA' },
                { id: 57940, name: 'ALEEREITUK' },
                { id: 58493, name: 'ARIAMIRIAM' },
                { id: 68761, name: 'OLACAT' },
                { id: 31511, name: 'OLUPE' },
              ],
            },
            {
              id: 10180,
              name: 'OLUPE TOWN BOARD',
              villages: [
                { id: 59121, name: 'BISINA' },
                { id: 68870, name: 'OLUPE' },
              ],
            },
            {
              id: 4909,
              name: 'OSEP',
              villages: [
                { id: 31513, name: 'AARACEPA' },
                { id: 31514, name: 'ACOMAI' },
                { id: 58163, name: 'AMOEBE' },
                { id: 31515, name: 'AMORA' },
                { id: 58644, name: 'ATIRAI' },
                { id: 69261, name: 'OSEP' },
                { id: 70722, name: 'TESO' },
              ],
            },
            {
              id: 4900,
              name: 'OSOBUT',
              villages: [
                { id: 31498, name: 'AGULE' },
                { id: 31497, name: 'APELEUN' },
                { id: 68453, name: 'ODERAI' },
                { id: 31499, name: 'OSOBUT' },
              ],
            },
          ],
        },
        {
          id: 1066,
          name: 'OKORE',
          parishes: [
            {
              id: 4926,
              name: 'ADUGULU',
              villages: [
                { id: 57249, name: 'ABUKOIKONG' },
                { id: 31576, name: 'ADUNGULU' },
                { id: 31577, name: 'AKOBOI' },
                { id: 57956, name: 'ALENGO' },
              ],
            },
            {
              id: 4920,
              name: 'AMINIT',
              villages: [
                { id: 58146, name: 'AMINIT' },
                { id: 31556, name: 'APAPAI' },
                { id: 31557, name: 'OLET' },
                { id: 68894, name: 'OMAA' },
                { id: 31558, name: 'OMAMTUM' },
              ],
            },
            {
              id: 4927,
              name: 'KEELIM',
              villages: [
                { id: 57802, name: 'AKODWOKODOI' },
                { id: 31580, name: 'AMOO' },
                { id: 31578, name: 'APELEUN' },
                { id: 31579, name: 'KEELIM' },
                { id: 68437, name: 'OCWIIN' },
              ],
            },
            {
              id: 4922,
              name: 'OKORE',
              villages: [
                { id: 31563, name: 'ABOBORE' },
                { id: 31564, name: 'AKUT' },
                { id: 31565, name: 'ATIANGIRO' },
                { id: 58666, name: 'ATUKOI' },
                { id: 31566, name: 'OITAKOL' },
                { id: 31567, name: 'OKORE' },
              ],
            },
            {
              id: 4923,
              name: 'OPIANANYA',
              villages: [
                { id: 58355, name: 'APAALA' },
                { id: 31570, name: 'ARUKIA' },
                { id: 68676, name: 'OKEYIA' },
                { id: 68687, name: 'OKODE' },
                { id: 31569, name: 'OPIANANYA' },
                { id: 31568, name: 'OSASIA' },
              ],
            },
            {
              id: 4924,
              name: 'ORIMON',
              villages: [
                { id: 31571, name: 'ABELAN' },
                { id: 58635, name: 'ATIKOKIN' },
                { id: 61030, name: 'CHOS' },
                { id: 68657, name: 'OKABALE' },
                { id: 69193, name: 'ORIMON' },
              ],
            },
            {
              id: 4921,
              name: 'PAKWI',
              villages: [
                { id: 31559, name: 'APOKOR' },
                { id: 31562, name: 'OGUGUT' },
                { id: 31560, name: 'OGURIGUR' },
                { id: 31561, name: 'OKIBUI' },
                { id: 69516, name: 'PAKWI' },
                { id: 69759, name: 'PUPES' },
              ],
            },
            {
              id: 4925,
              name: 'RWATAMA',
              villages: [
                { id: 31572, name: 'ADERE' },
                { id: 31573, name: 'AKUNGURO' },
                { id: 57997, name: 'ALIGOI' },
                { id: 31574, name: 'AODOT' },
                { id: 58669, name: 'ATULOM' },
                { id: 31575, name: 'RWATAMA' },
              ],
            },
          ],
        },
        {
          id: 1069,
          name: 'OKULONYO',
          parishes: [
            {
              id: 4943,
              name: 'ANGEREPO',
              villages: [
                { id: 31645, name: 'AMUTURO' },
                { id: 31643, name: 'ANGEREPO' },
                { id: 65922, name: 'MAJENGO' },
                { id: 31644, name: 'OBULENGOROK' },
                { id: 68908, name: 'OMASAI' },
              ],
            },
            {
              id: 4946,
              name: 'OKOCHO',
              villages: [
                { id: 31654, name: 'ACURU' },
                { id: 31655, name: 'OGORIA' },
                { id: 31656, name: 'OKOCHO' },
                { id: 31657, name: 'ORUKUKUN' },
              ],
            },
            {
              id: 4944,
              name: 'OKULIAK',
              villages: [
                { id: 31647, name: 'AKOBOI' },
                { id: 58061, name: 'ALUKUBYONG' },
                { id: 31648, name: 'AMARATOIT' },
                { id: 31646, name: 'AMEDERA' },
                { id: 58626, name: 'ATERAI' },
                { id: 68376, name: 'OBULE' },
                { id: 31649, name: 'OKULIAK' },
              ],
            },
            {
              id: 4945,
              name: 'OKULONYO',
              villages: [
                { id: 31650, name: 'ACOMAI' },
                { id: 31651, name: 'OGANGAI' },
                { id: 31652, name: 'OKULONYO' },
                { id: 31653, name: 'OMOR' },
              ],
            },
            {
              id: 4947,
              name: 'OMUKUNY',
              villages: [
                { id: 31660, name: 'AJOKOTULIA' },
                { id: 31658, name: 'ANYANGABELA' },
                { id: 31659, name: 'OBARUTE' },
                { id: 31661, name: 'OMUKUNY' },
              ],
            },
          ],
        },
        {
          id: 1067,
          name: 'ONGONGOJA',
          parishes: [
            {
              id: 4928,
              name: 'AKETA',
              villages: [
                { id: 31585, name: 'ABOLOT' },
                { id: 31581, name: 'AKETA' },
                { id: 31582, name: 'AKWAMOR' },
                { id: 31583, name: 'AKWORO' },
                { id: 58602, name: 'ATAPAR' },
                { id: 31584, name: 'KOMOLO' },
                { id: 68613, name: 'OIGO IMOMWA' },
              ],
            },
            {
              id: 4933,
              name: 'AKETA TOWN BOARD',
              villages: [
                { id: 31602, name: 'AKWAMOR' },
                { id: 31603, name: 'EAST' },
                { id: 31604, name: 'WEST' },
              ],
            },
            {
              id: 4934,
              name: 'AKOMOTUKOI',
              villages: [
                { id: 31605, name: 'ABOSA' },
                { id: 31607, name: 'AKOMOTUKOI' },
                { id: 31608, name: 'AKORE' },
                { id: 31606, name: 'APURUSIO' },
              ],
            },
            {
              id: 4935,
              name: 'MILMIL',
              villages: [
                { id: 31609, name: 'ALEDEI' },
                { id: 31612, name: 'APUUTON' },
                { id: 31610, name: 'MILIMIL' },
                { id: 31611, name: 'MORU' },
              ],
            },
            {
              id: 4936,
              name: 'OBURATUM',
              villages: [
                { id: 31613, name: 'AKOU  ETOM' },
                { id: 68383, name: 'OBURATUM' },
                { id: 68656, name: 'OKAAMETA' },
                { id: 68869, name: 'OLUPE' },
              ],
            },
            {
              id: 4929,
              name: 'OBWOBWO',
              villages: [
                { id: 31589, name: 'ALEULEUN' },
                { id: 31590, name: 'AMUTURUNYO' },
                { id: 31586, name: 'ANGOLEKIT' },
                { id: 31587, name: 'OBWOBWO' },
                { id: 31588, name: 'OLIMIR' },
              ],
            },
            {
              id: 4932,
              name: 'OKUDA',
              villages: [
                { id: 31601, name: 'AKIMENG' },
                { id: 31598, name: 'APUUTON' },
                { id: 31599, name: 'OKUDA' },
                { id: 31600, name: 'OMERIMONG' },
              ],
            },
            {
              id: 4931,
              name: 'ONGATUNYO',
              villages: [
                { id: 31595, name: 'ONGATUNYO' },
                { id: 31597, name: 'ONGUNGA' },
                { id: 31596, name: 'OPIANANYA' },
              ],
            },
            {
              id: 4930,
              name: 'ONGONGOJA',
              villages: [
                { id: 57286, name: 'ACAAN' },
                { id: 31592, name: 'AKAMURIEI' },
                { id: 31594, name: 'OCAK' },
                { id: 31591, name: 'OKUDASAMA' },
                { id: 31593, name: 'ONGONGOJA' },
                { id: 69208, name: 'OROBOI' },
              ],
            },
          ],
        },
        {
          id: 1068,
          name: 'PALAM',
          parishes: [
            {
              id: 4937,
              name: 'ACANGA',
              villages: [
                { id: 31614, name: 'ALELES' },
                { id: 31615, name: 'OLIANGOI' },
                { id: 31616, name: 'OOLOIN' },
                { id: 31617, name: 'ORUKURUKIO' },
              ],
            },
            {
              id: 4938,
              name: 'NGARIAM',
              villages: [
                { id: 31618, name: 'ACUCU' },
                { id: 31623, name: 'AKWAREKIA' },
                { id: 31619, name: 'ALENGO' },
                { id: 31620, name: 'AMORWONGORA' },
                { id: 31621, name: 'APUUTON' },
                { id: 31622, name: 'NGARIAM' },
              ],
            },
            {
              id: 4939,
              name: 'ODOOT',
              villages: [
                { id: 31624, name: 'ACOITE' },
                { id: 31627, name: 'AKWARADADA' },
                { id: 31628, name: 'AMIRIAI' },
                { id: 31625, name: 'OPEDONGOR' },
                { id: 31626, name: 'TUMTUM' },
              ],
            },
            {
              id: 4941,
              name: 'OKWAMOMWAR',
              villages: [
                { id: 31634, name: 'AKOLIKEJE' },
                { id: 31635, name: 'AKOSOBWA' },
                { id: 31636, name: 'ATIIRA' },
                { id: 31637, name: 'OKWAMOMWAR' },
              ],
            },
            {
              id: 4940,
              name: 'OLILIM',
              villages: [
                { id: 31632, name: 'AITI' },
                { id: 31629, name: 'MORULINGA' },
                { id: 31630, name: 'OSEMWA' },
                { id: 31631, name: 'OSIOMIT' },
                { id: 31633, name: 'SIRIYE' },
              ],
            },
            {
              id: 4942,
              name: 'PALAM',
              villages: [
                { id: 31638, name: 'AELENYANG' },
                { id: 31639, name: 'AMUTURO' },
                { id: 31640, name: 'ARUSI AKAN' },
                { id: 31641, name: 'ORAMUN' },
                { id: 31642, name: 'PALAM' },
              ],
            },
          ],
        },
        {
          id: 1065,
          name: 'USUK',
          parishes: [
            {
              id: 4918,
              name: 'ABWOKODIA',
              villages: [
                { id: 31549, name: 'ABWOKODIA' },
                { id: 31550, name: 'OLEROI' },
                { id: 31551, name: 'OPOYONGO' },
                { id: 31552, name: 'OTUJAI' },
              ],
            },
            {
              id: 4919,
              name: 'ABYELUT',
              villages: [
                { id: 31553, name: 'ACURUN' },
                { id: 31554, name: 'AKWOORO A' },
                { id: 57903, name: 'AKWOORO B' },
                { id: 31555, name: 'ONGEMA' },
              ],
            },
            {
              id: 4917,
              name: 'CHELEUKO',
              villages: [
                { id: 31543, name: 'AMULI' },
                { id: 31547, name: 'ANYANGA' },
                { id: 31544, name: 'APARISA' },
                { id: 31545, name: 'OBWAPESUR' },
                { id: 31548, name: 'ONGOLE' },
                { id: 31546, name: 'OSUDIO' },
              ],
            },
            {
              id: 4915,
              name: 'OKORITOK',
              villages: [
                { id: 31531, name: 'ADUKAIT' },
                { id: 31532, name: 'AMALERA' },
                { id: 31533, name: 'AMORU' },
                { id: 31534, name: 'AOJABULE EAST' },
                { id: 31535, name: 'AOJABULE WEST' },
                { id: 31536, name: 'OTIDI' },
              ],
            },
            {
              id: 4916,
              name: 'ONGEMA',
              villages: [
                { id: 31537, name: 'AOJATOROM' },
                { id: 31538, name: 'ARIAMARENG EAST' },
                { id: 31542, name: 'ARIAMARENG WEST' },
                { id: 31539, name: 'ATERAI' },
                { id: 31540, name: 'OLUPE' },
                { id: 31541, name: 'ONGEMA' },
              ],
            },
          ],
        },
        {
          id: 1070,
          name: 'USUK TOWN COUNCIL',
          parishes: [
            {
              id: 4948,
              name: 'CENTRAL WARD',
              villages: [
                { id: 31662, name: 'AKISIM' },
                { id: 31663, name: 'APUUTON' },
                { id: 31664, name: 'USUK TRADING CENTRE EAST' },
                { id: 31665, name: 'USUK TRADING CENTRE WEST' },
              ],
            },
            {
              id: 4949,
              name: 'NORTHERN WARD',
              villages: [
                { id: 57545, name: 'AGETOMA' },
                { id: 31666, name: 'AMECA/ORUKURUKUN' },
              ],
            },
            {
              id: 4950,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 31668, name: 'ADURUKOI' },
                { id: 31667, name: 'ASURET' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
