import { District } from '../index';

export default {
  id: 75,
  name: 'KAYUNGA',
  counties: [
    {
      id: 183,
      name: 'BBALE COUNTY',
      sub_counties: [
        {
          id: 1126,
          name: 'BBAALE',
          parishes: [
            {
              id: 5189,
              name: 'BBAALE',
              villages: [
                { id: 33192, name: 'BBAALE EAST' },
                { id: 33193, name: 'BBAALE WEST' },
                { id: 33194, name: 'KANAMUGADDU' },
                { id: 33195, name: 'KYANSANDE' },
                { id: 33196, name: 'MUKONDO' },
                { id: 33197, name: 'NAMIREMBE' },
                { id: 33198, name: 'WABIRUMBA' },
              ],
            },
            {
              id: 5190,
              name: 'KAVULE',
              villages: [
                { id: 33199, name: 'GAYAZA' },
                { id: 33200, name: 'KAVULE' },
                { id: 33201, name: 'MULAYA' },
                { id: 33202, name: 'MULUGA' },
                { id: 33203, name: 'NAMATAALA' },
              ],
            },
            {
              id: 5191,
              name: 'KOKOTERO',
              villages: [
                { id: 33204, name: 'KOKOTERO' },
                { id: 33205, name: 'KYAKWAMBALA' },
                { id: 33206, name: 'TANGOYE' },
              ],
            },
            {
              id: 5192,
              name: 'MISANGA',
              villages: [
                { id: 33207, name: 'KABIRA' },
                { id: 33208, name: 'MISANGA A' },
                { id: 33209, name: 'MISANGA B' },
                { id: 33210, name: 'MISANGA C' },
                { id: 33211, name: 'NSUBE' },
              ],
            },
            {
              id: 5193,
              name: 'MUGONGO',
              villages: [
                { id: 33212, name: 'JIIRA' },
                { id: 33213, name: 'MUGONGO EAST' },
                { id: 33214, name: 'MUGONGO WEST' },
              ],
            },
            {
              id: 5194,
              name: 'NAKITOKOLO',
              villages: [
                { id: 33215, name: 'KABAKU' },
                { id: 33216, name: 'KATUUGO' },
                { id: 33217, name: 'NABISUBYAKI' },
                { id: 33218, name: 'NAKITOKOLO' },
              ],
            },
          ],
        },
        {
          id: 1127,
          name: 'GALIRAYA',
          parishes: [
            {
              id: 5195,
              name: 'GALIRAYA',
              villages: [
                { id: 33219, name: 'BUSUNGIRE' },
                { id: 33220, name: 'GALIRAYA' },
                { id: 33221, name: 'KIDIBYA A' },
                { id: 33222, name: 'KIDIBYA B' },
                { id: 33223, name: 'KIWUULA' },
                { id: 33225, name: 'KYAMULETERE' },
                { id: 33224, name: 'NAKAKOOLA' },
              ],
            },
            {
              id: 5196,
              name: 'GWERO-NAMAYUGE',
              villages: [
                { id: 33226, name: 'BBAIZO' },
                { id: 33227, name: 'GWERO A' },
                { id: 33232, name: 'GWERO B' },
                { id: 33233, name: 'KABUTERE' },
                { id: 33228, name: 'NABITYANKA' },
                { id: 33229, name: 'NAKATULI' },
                { id: 33230, name: 'NKUUTU' },
                { id: 33231, name: 'SOKOSO' },
              ],
            },
            {
              id: 5197,
              name: 'KASOKWE',
              villages: [
                { id: 33237, name: 'BANDA' },
                { id: 33234, name: 'KASOKWE' },
                { id: 33238, name: 'KATAIGWA' },
                { id: 33235, name: 'KIRUBO' },
                { id: 33236, name: 'KIRYOLA' },
              ],
            },
            {
              id: 5198,
              name: 'KIRASA',
              villages: [
                { id: 33239, name: 'KIRASA CENTRAL' },
                { id: 33243, name: 'KISALIZI' },
                { id: 33240, name: 'KIWENDA' },
                { id: 33241, name: 'KIYAGO' },
                { id: 33242, name: 'SOBYA' },
              ],
            },
            {
              id: 5199,
              name: 'NAMALERE',
              villages: [
                { id: 33244, name: 'BWEYALE  A' },
                { id: 33245, name: 'BWEYALE  B' },
                { id: 33246, name: 'KAMBATANE' },
                { id: 33247, name: 'KISUUGA A' },
                { id: 33248, name: 'KISUUGA B' },
                { id: 33249, name: 'KYEDIKYO' },
                { id: 33250, name: 'NAMALERE' },
              ],
            },
            {
              id: 5200,
              name: 'NTIMBA',
              villages: [
                { id: 33251, name: 'KALENGE' },
                { id: 33252, name: 'KAWONGO A' },
                { id: 33253, name: 'KAWONGO B' },
                { id: 33254, name: 'KIKOTA' },
                { id: 33255, name: 'KITWE' },
                { id: 33256, name: 'MISOZI' },
              ],
            },
          ],
        },
        {
          id: 1128,
          name: 'KAYONZA',
          parishes: [
            {
              id: 5208,
              name: 'BALISANGA',
              villages: [
                { id: 33318, name: 'BALINSANGA' },
                { id: 33319, name: 'KABALANGAJJA' },
                { id: 33320, name: 'KIKWAATA' },
                { id: 33321, name: 'KIRISURU' },
                { id: 33322, name: 'MATIGI' },
                { id: 33323, name: 'NABUSANJA' },
                { id: 33324, name: 'NKONKONJERU' },
                { id: 33325, name: 'NSAMBYA' },
                { id: 33326, name: 'NZINGU' },
              ],
            },
            {
              id: 5209,
              name: 'KAFUMBA',
              villages: [
                { id: 33327, name: 'BUKOMBA' },
                { id: 33328, name: 'KAFUMBA' },
                { id: 33329, name: 'KAKOOGE' },
                { id: 33330, name: 'KIWUNA' },
                { id: 33331, name: 'NAWANKONGE' },
                { id: 33332, name: 'NYONDO A' },
                { id: 33333, name: 'NYONDO B' },
              ],
            },
            {
              id: 5201,
              name: 'KAMUSABI',
              villages: [
                { id: 33257, name: 'BUGATTO' },
                { id: 33258, name: 'BUGONYA A' },
                { id: 33267, name: 'BUGONYA B' },
                { id: 33259, name: 'KAMUSABI' },
                { id: 33260, name: 'KASOLOKAMPONYE' },
                { id: 33261, name: 'KIGANDA' },
                { id: 33268, name: 'KISWASWA' },
                { id: 33262, name: 'LUGASA WEST' },
                { id: 33263, name: 'LUKONDA' },
                { id: 33264, name: 'NSANVU' },
                { id: 33265, name: 'NSIIMA' },
                { id: 33266, name: 'WABUNYONYI' },
              ],
            },
            {
              id: 5202,
              name: 'KANYWERO',
              villages: [
                { id: 33269, name: 'KATUGO' },
                { id: 33270, name: 'KAZINGA' },
                { id: 33271, name: 'KIDUKULU' },
                { id: 33272, name: 'KISEETA  A' },
                { id: 33273, name: 'KISEETA  B' },
                { id: 33274, name: 'KITWE EAST' },
                { id: 33276, name: 'TAKAJUNGE' },
                { id: 33275, name: 'TI   NDIANI' },
                { id: 33277, name: 'WUNGA' },
              ],
            },
            {
              id: 5203,
              name: 'KITWE',
              villages: [
                { id: 33278, name: 'BUGOMA' },
                { id: 33279, name: 'BUSABIRA' },
                { id: 33280, name: 'KAATO I' },
                { id: 33284, name: 'KAATO II' },
                { id: 33281, name: 'KYAMUGONGO' },
                { id: 33282, name: 'KYAMUJUMBI' },
                { id: 33283, name: 'SALAAMA' },
              ],
            },
            {
              id: 5205,
              name: 'NAKYESANJA',
              villages: [
                { id: 33294, name: 'BUKERERE' },
                { id: 33295, name: 'KAKIIKA A' },
                { id: 33301, name: 'KAKIIKA B' },
                { id: 33296, name: 'KALIGOYA' },
                { id: 33297, name: 'KIRIMANTOOGO' },
                { id: 33298, name: 'NAKYESANJA' },
                { id: 33299, name: 'NAMANOGA' },
                { id: 33300, name: 'NSONGWE' },
              ],
            },
            {
              id: 5204,
              name: 'NAKYESSA',
              villages: [
                { id: 33293, name: 'KAVULE V' },
                { id: 33285, name: 'NAKYESA I' },
                { id: 33286, name: 'NAKYESA II' },
                { id: 33287, name: 'NAKYESA III' },
                { id: 33288, name: 'NAKYESA IV' },
                { id: 33289, name: 'NAMATOGONYA I' },
                { id: 33290, name: 'NAMATOGONYA II' },
                { id: 33291, name: 'NAMATOGONYA III' },
                { id: 33292, name: 'NAMATOGONYA IV' },
              ],
            },
            {
              id: 5206,
              name: 'NAMALIRI',
              villages: [
                { id: 33302, name: 'KAWOLOKOTA WEST' },
                { id: 33303, name: 'KAYONZA' },
                { id: 33304, name: 'KYAATO I' },
                { id: 33305, name: 'KYAATO II' },
                { id: 33306, name: 'KYAATO III' },
                { id: 33307, name: 'LUGASA  EAST' },
                { id: 33308, name: 'MAKUKULU' },
                { id: 33309, name: 'NAKABANGO' },
                { id: 33310, name: 'NAMALIIRI' },
              ],
            },
            {
              id: 5207,
              name: 'NAMIZO',
              villages: [
                { id: 33311, name: 'BUJWAAYA' },
                { id: 33312, name: 'KAWOLOKOTA EAST' },
                { id: 33313, name: 'NAMAVUNDU A' },
                { id: 33317, name: 'NAMAVUNDU B' },
                { id: 33314, name: 'NAMIZO A' },
                { id: 33315, name: 'NAMIZO B' },
                { id: 33316, name: 'NAWANSAMA' },
              ],
            },
          ],
        },
        {
          id: 1129,
          name: 'KITIMBWA',
          parishes: [
            {
              id: 5215,
              name: 'KITATYA',
              villages: [
                { id: 33363, name: 'BUGIRINYA' },
                { id: 33364, name: 'BWAMULAMIRA' },
                { id: 33365, name: 'KITATYA A' },
                { id: 33366, name: 'KITATYA B' },
                { id: 33367, name: 'KITATYA C' },
              ],
            },
            {
              id: 5210,
              name: 'KYERIMA',
              villages: [
                { id: 33334, name: 'BWERAMONDO' },
                { id: 33335, name: 'KIGALAMA' },
                { id: 33336, name: 'NAKASEETA' },
                { id: 33337, name: 'NAMABUGGA' },
                { id: 33338, name: 'NANJWENGE' },
              ],
            },
            {
              id: 5211,
              name: 'NAKIVUBO',
              villages: [
                { id: 33339, name: 'BISAKA CENTRAL' },
                { id: 33344, name: 'BISAKA NORTH' },
                { id: 33340, name: 'KABALIRA' },
                { id: 33341, name: 'NAKIVUBO A' },
                { id: 33342, name: 'NAKIVUBO B' },
                { id: 33343, name: 'NONGO' },
              ],
            },
            {
              id: 5212,
              name: 'NAMULABA',
              villages: [
                { id: 33345, name: 'KIWUBA' },
                { id: 33346, name: 'KYEBANJA' },
                { id: 33347, name: 'MANSA A' },
                { id: 33348, name: 'MANSA B' },
                { id: 33349, name: 'NAMULABA' },
                { id: 33350, name: 'NONGO' },
                { id: 33351, name: 'WANTETE' },
              ],
            },
            {
              id: 5213,
              name: 'NKOKONJERU',
              villages: [
                { id: 33352, name: 'BULAULA A' },
                { id: 33353, name: 'BULAULA B' },
                { id: 33354, name: 'BULAULA C' },
                { id: 33355, name: 'NKOKONJERU A' },
                { id: 33356, name: 'NKOKONJERU B' },
                { id: 33357, name: 'TWEYAGALIRE  A' },
                { id: 33358, name: 'TWEYAGALIRE  B' },
              ],
            },
            {
              id: 5214,
              name: 'WABWOKO',
              villages: [
                { id: 33359, name: 'KAKOOLA' },
                { id: 33360, name: 'KIRIMAMPOKYA  A' },
                { id: 33361, name: 'KIRIMAMPOKYA  B' },
                { id: 33362, name: 'WABUTI' },
              ],
            },
          ],
        },
        {
          id: 1130,
          name: 'KITIMBWA TOWN COUNCIL',
          parishes: [
            {
              id: 5217,
              name: 'KYERIMA WARD',
              villages: [
                { id: 33376, name: 'KYERIMA A' },
                { id: 33377, name: 'KYERIMA B' },
                { id: 33378, name: 'KYERIMA C' },
                { id: 33379, name: 'MAFUMBE' },
                { id: 33380, name: 'MBULAKATI' },
              ],
            },
            {
              id: 5216,
              name: 'WABUYINJA WARD',
              villages: [
                { id: 33368, name: 'BUDAADA' },
                { id: 33369, name: 'KITIMBWA I' },
                { id: 33370, name: 'KITIMBWA II' },
                { id: 33371, name: 'KYATTO' },
                { id: 33372, name: 'KYETUME A' },
                { id: 33373, name: 'KYETUME B' },
                { id: 33374, name: 'KYETUME C' },
                { id: 33375, name: 'WABUYINJA' },
              ],
            },
            {
              id: 5218,
              name: 'WABWOKO WARD',
              villages: [
                { id: 33381, name: 'WABWOKO A' },
                { id: 33382, name: 'WABWOKO B' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 184,
      name: 'NTENJERU COUNTY NORTH',
      sub_counties: [
        {
          id: 1131,
          name: 'BUSAANA',
          parishes: [
            {
              id: 5219,
              name: 'KASANA',
              villages: [
                { id: 33385, name: 'BUGOBERO' },
                { id: 33383, name: 'KASANA II' },
                { id: 33384, name: 'WABUSONKO' },
              ],
            },
            {
              id: 5220,
              name: 'KIWANGULA',
              villages: [
                { id: 33386, name: 'BUYUNGIRIZI' },
                { id: 33387, name: 'KIWANGULA' },
                { id: 33388, name: 'NAKATOVU' },
                { id: 33389, name: 'NGEYE' },
                { id: 33390, name: 'WAMPONGO' },
                { id: 33391, name: 'WANTETE A' },
                { id: 33392, name: 'WANTETE B' },
              ],
            },
            {
              id: 5221,
              name: 'LUSENKE',
              villages: [
                { id: 33393, name: 'BAKUTTA' },
                { id: 33394, name: 'BUGADDU B' },
                { id: 33395, name: 'BUNZIBIRIDDE' },
                { id: 33396, name: 'BUSUNSULI' },
                { id: 33397, name: 'KIBUZI' },
                { id: 33398, name: 'KIREKU - LUSENKE' },
              ],
            },
            {
              id: 5222,
              name: 'NABUGANYI',
              villages: [
                { id: 33399, name: 'BUMALI' },
                { id: 33400, name: 'NABUGANYI' },
                { id: 33401, name: 'NAMATOGONYA' },
                { id: 33402, name: 'NEKOYEDDE' },
              ],
            },
            {
              id: 5224,
              name: 'NAMIREMBE',
              villages: [
                { id: 33409, name: 'KIYUYA' },
                { id: 33410, name: 'NAMIREMBE B' },
              ],
            },
            {
              id: 5225,
              name: 'NAMPANYI',
              villages: [
                { id: 33411, name: 'BUKUNGULU' },
                { id: 33412, name: 'KIREKU - NAMPANYI' },
                { id: 33413, name: 'NAKAKANDWA' },
                { id: 33414, name: 'NAMPANYI' },
              ],
            },
            {
              id: 5223,
              name: 'NAMUKUMA',
              villages: [
                { id: 33403, name: 'KASOTA' },
                { id: 33404, name: 'KITALA' },
                { id: 33405, name: 'KYENGERA' },
                { id: 33406, name: 'NAMUKUMA' },
                { id: 33407, name: 'NANGABO' },
                { id: 33408, name: 'NANYUKI' },
              ],
            },
            {
              id: 5226,
              name: 'NAMUSAALA',
              villages: [
                { id: 33415, name: 'BISAKA' },
                { id: 33419, name: 'LUSENKE' },
                { id: 33417, name: 'MASEMBE' },
                { id: 33418, name: 'NAMUSAALA' },
                { id: 33416, name: 'NAMUTYA' },
              ],
            },
          ],
        },
        {
          id: 1134,
          name: 'BUSAANA TOWN COUNCIL',
          parishes: [
            {
              id: 5240,
              name: 'KASANA WARD',
              villages: [
                { id: 33493, name: 'BUGADDU' },
                { id: 33494, name: 'BUSAANA' },
                { id: 33495, name: 'KASANA I' },
              ],
            },
            {
              id: 5241,
              name: 'LUSENKE WARD',
              villages: [
                { id: 33496, name: 'BUGADDU A' },
                { id: 33497, name: 'KUFU' },
                { id: 33498, name: 'KYENGERA' },
                { id: 33499, name: 'LUSENKE' },
              ],
            },
            {
              id: 5242,
              name: 'NAMIREMBE WARD',
              villages: [
                { id: 33500, name: 'KAUKU' },
                { id: 33501, name: 'NAMIREMBE A' },
                { id: 33502, name: 'WAMPOLOGOMA' },
              ],
            },
            {
              id: 5243,
              name: 'NAMUKUMA WARD',
              villages: [
                { id: 33503, name: 'KAYONJO' },
                { id: 33504, name: 'KYAYAYE' },
              ],
            },
          ],
        },
        {
          id: 1132,
          name: 'KAYUNGA',
          parishes: [
            {
              id: 5227,
              name: 'BUBAJJWE',
              villages: [
                { id: 33420, name: 'BUBAJJWE A' },
                { id: 33426, name: 'BUBAJJWE B' },
                { id: 33421, name: 'KAAZI A' },
                { id: 33427, name: 'KAAZI B' },
                { id: 33422, name: 'NALUMULI' },
                { id: 33423, name: 'NALYAMABIDDE A' },
                { id: 33428, name: 'NALYAMABIDDE B' },
                { id: 33424, name: 'NAMATOGONYA' },
                { id: 33425, name: 'WAJJANZI' },
              ],
            },
            {
              id: 5228,
              name: 'BUKOLOTO',
              villages: [
                { id: 33429, name: 'BUTAKOOLA' },
                { id: 33430, name: 'BWETYABA' },
                { id: 33431, name: 'GAAZA' },
                { id: 33432, name: 'KYAMBOGO' },
                { id: 33433, name: 'KYAMPISI' },
                { id: 33434, name: 'NAWANDAGALA' },
                { id: 33435, name: 'NDEEBA' },
                { id: 33436, name: 'NTOOKE' },
              ],
            },
            {
              id: 5229,
              name: 'BUKUJU',
              villages: [
                { id: 33437, name: 'BUKUJJU' },
                { id: 33438, name: 'BUSOLO' },
                { id: 33439, name: 'KIYAGI' },
                { id: 33440, name: 'KYAMIMBI' },
                { id: 33441, name: 'NALWEWETA' },
              ],
            },
            {
              id: 5230,
              name: 'BUSAALE',
              villages: [
                { id: 33442, name: 'BUSAALE' },
                { id: 33443, name: 'KATIKAMU' },
                { id: 33444, name: 'KITO' },
                { id: 33445, name: 'KYEBANJA A' },
                { id: 33446, name: 'KYEBANJA B' },
              ],
            },
            {
              id: 5231,
              name: 'BUYOBE',
              villages: [
                { id: 33447, name: 'BULYANKUYEGE' },
                { id: 33448, name: 'BUWUNGIRO' },
                { id: 33449, name: 'BUYOBE' },
                { id: 33450, name: 'KANJUKI/WABUSONKO' },
                { id: 33451, name: 'KAWUKU' },
                { id: 33452, name: 'KOKOTERO/GWANIKA' },
                { id: 33453, name: 'KYANIKA' },
                { id: 33454, name: 'KYANYA' },
              ],
            },
            {
              id: 5234,
              name: 'KITEREDDE',
              villages: [
                { id: 33469, name: 'BUGOGGE' },
                { id: 33470, name: 'KAGOYE' },
                { id: 33471, name: 'KISAGAZI' },
                { id: 33472, name: 'KITEREDDE' },
                { id: 33473, name: 'WABIGGWO' },
              ],
            },
            {
              id: 5232,
              name: 'NAKASEETA',
              villages: [
                { id: 33455, name: 'KIRYAMULI' },
                { id: 33456, name: 'KISOMBWA' },
                { id: 33457, name: 'NAKASEETA A' },
                { id: 33460, name: 'NAKASEETA B' },
                { id: 33458, name: 'NAKAZIBA' },
                { id: 33459, name: 'WANKYAYIRAKI' },
              ],
            },
            {
              id: 5233,
              name: 'NSOTOKA',
              villages: [
                { id: 33461, name: 'BUNYUMYA' },
                { id: 33462, name: 'KIWOOZA A' },
                { id: 33468, name: 'KIWOOZA B' },
                { id: 33463, name: 'MATABA' },
                { id: 33464, name: 'NAMULANDA' },
                { id: 33465, name: 'NJALEBIREESE' },
                { id: 33466, name: 'NSOTOKA' },
                { id: 33467, name: 'SSUKKA' },
              ],
            },
          ],
        },
        {
          id: 1133,
          name: 'KAYUNGA TOWN COUNCIL',
          parishes: [
            {
              id: 5235,
              name: 'BUKOLOTO WARD',
              villages: [
                { id: 33474, name: 'ASONI KAGGWA' },
                { id: 33475, name: 'KAKOWEKOWE' },
                { id: 33476, name: 'KAMUNYE' },
                { id: 33477, name: 'NDEEBA' },
                { id: 33478, name: 'SAJJABI' },
              ],
            },
            {
              id: 5236,
              name: 'KAYUNGA CENTRAL WARD',
              villages: [
                { id: 33479, name: 'KAYUNGA CENTRAL' },
                { id: 33480, name: 'KAYUNGA NORTH' },
              ],
            },
            {
              id: 5237,
              name: 'NAMAGABI WARD',
              villages: [
                { id: 33481, name: 'KISAABA' },
                { id: 33482, name: 'NAMAGABI A' },
                { id: 33483, name: 'NAMAGABI B' },
                { id: 33484, name: 'WANYANGA' },
              ],
            },
            {
              id: 5238,
              name: 'NTENJERU WARD',
              villages: [
                { id: 33485, name: 'KYAMBOGO' },
                { id: 33486, name: 'NAKALIRO' },
                { id: 33487, name: 'NTENJERU I' },
                { id: 33488, name: 'NTENJERU II' },
                { id: 33489, name: 'TENTE' },
              ],
            },
            {
              id: 5239,
              name: 'WEST/KIBIRA WARD',
              villages: [
                { id: 33490, name: 'KAYUNGA WEST' },
                { id: 33492, name: 'KIBIRA' },
                { id: 33491, name: 'KISAWO' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 185,
      name: 'NTENJERU COUNTY SOUTH',
      sub_counties: [
        {
          id: 1135,
          name: 'KANGULUMIRA',
          parishes: [
            {
              id: 5244,
              name: 'KAWOOMYA',
              villages: [
                { id: 33505, name: 'BUKEEKA' },
                { id: 33510, name: 'KALIDASI' },
                { id: 33506, name: 'KAWOOMYA' },
                { id: 33507, name: 'KUNGU' },
                { id: 33508, name: 'MAGALITA' },
                { id: 33509, name: 'MIREMBE' },
              ],
            },
            {
              id: 5245,
              name: 'KIKWANYA',
              villages: [
                { id: 33511, name: 'KIBETU' },
                { id: 33512, name: 'KIKWANYA' },
                { id: 33513, name: 'KIMOOLI' },
                { id: 33514, name: 'KIREKU' },
                { id: 33515, name: 'KIZAWULA' },
                { id: 33516, name: 'KYABAKADDE' },
                { id: 33517, name: 'MAYAGA' },
                { id: 33518, name: 'MUSAMYA' },
              ],
            },
            {
              id: 5246,
              name: 'SEETA-NYIIZE',
              villages: [
                { id: 33519, name: 'BUKASA' },
                { id: 33526, name: 'KAYINJA' },
                { id: 33520, name: 'KAYUNGA' },
                { id: 33521, name: 'NAKIRUBI' },
                { id: 33522, name: 'NAMAKANDWA' },
                { id: 33523, name: 'NYIIZE' },
                { id: 33524, name: 'SEETA' },
                { id: 33527, name: 'WAMPEEWO' },
                { id: 33525, name: 'WANTAYI' },
              ],
            },
          ],
        },
        {
          id: 1137,
          name: 'KANGULUMIRA TOWN COUNCIL',
          parishes: [
            {
              id: 5254,
              name: 'KANGULUMIRA WARD',
              villages: [
                { id: 33577, name: 'KAKANDE ZONE' },
                { id: 33566, name: 'KALAGALA' },
                { id: 33567, name: 'KANGULUMIRA CENTRAL' },
                { id: 33574, name: 'KANYOGOGA' },
                { id: 33568, name: 'KASAMBYA' },
                { id: 33575, name: 'KIBIRA' },
                { id: 33569, name: 'KITABAZI' },
                { id: 33570, name: 'KIWALASI' },
                { id: 33571, name: 'KIWUGU' },
                { id: 33573, name: 'MAKINDYE' },
                { id: 33576, name: 'MUTUKULA' },
                { id: 33572, name: 'SOONA' },
              ],
            },
            {
              id: 5255,
              name: 'KIGAYAZA WARD',
              villages: [
                { id: 33578, name: 'KAMIRA' },
                { id: 33579, name: 'KIGAYAZA' },
                { id: 33580, name: 'KITAMBUZA' },
                { id: 33581, name: 'NAKATUNDU' },
              ],
            },
            {
              id: 5256,
              name: 'NAKATUNDU WARD',
              villages: [
                { id: 33582, name: 'KAMULI' },
                { id: 33583, name: 'KISEGA' },
                { id: 33584, name: 'MBULAKATI' },
                { id: 33585, name: 'MPUMUDDE' },
                { id: 66778, name: 'MWOLOLA' },
                { id: 33586, name: 'NONGO' },
                { id: 33587, name: 'RWANDA' },
                { id: 33588, name: 'WABUKWA' },
              ],
            },
          ],
        },
        {
          id: 1136,
          name: 'NAZIGO',
          parishes: [
            {
              id: 5247,
              name: 'BUKAMBA',
              villages: [
                { id: 33528, name: 'BUGUVU' },
                { id: 33529, name: 'BUKAMBA A' },
                { id: 33530, name: 'BUKAMBA B' },
                { id: 33531, name: 'BUKAMBA TOWN' },
                { id: 33532, name: 'GAYAZA' },
                { id: 33533, name: 'KISWA' },
                { id: 33534, name: 'NAMIREMBE' },
              ],
            },
            {
              id: 5248,
              name: 'KATIKANYONYI',
              villages: [
                { id: 33535, name: 'BUDOODA' },
                { id: 33536, name: 'KATIKANYONYI' },
                { id: 33537, name: 'KITEREDDE' },
                { id: 33538, name: 'KIWUBA' },
                { id: 33539, name: 'NAKATOOKE' },
              ],
            },
            {
              id: 5249,
              name: 'KIMANYA',
              villages: [
                { id: 33540, name: 'KIMAANYA' },
                { id: 33541, name: 'KISOGA' },
                { id: 33542, name: 'KIZIIKA' },
                { id: 33543, name: 'KYETUME' },
              ],
            },
            {
              id: 5250,
              name: 'KIRINDI',
              villages: [
                { id: 33544, name: 'DAMBA' },
                { id: 33545, name: 'KASEGA' },
                { id: 33546, name: 'KIRINDI' },
                { id: 33547, name: 'NAKAKONGE' },
                { id: 33548, name: 'NSIIMA - KIBAATI' },
                { id: 33549, name: 'ZAKALIA ZONE' },
              ],
            },
            {
              id: 5251,
              name: 'NATTETA',
              villages: [
                { id: 33550, name: 'BUSAGAZI' },
                { id: 33551, name: 'KIRIBEDDA' },
                { id: 33552, name: 'NAKATOVU' },
                { id: 33553, name: 'WABIRONGO' },
              ],
            },
            {
              id: 5252,
              name: 'NAZIGO',
              villages: [
                { id: 33554, name: 'KIGOBERO' },
                { id: 33555, name: 'KIRIMANTUNGO' },
                { id: 33556, name: 'KOTWE' },
                { id: 33557, name: 'KYAMPISI' },
                { id: 33558, name: 'MAGALA' },
                { id: 33559, name: 'NAKAKONGE' },
              ],
            },
            {
              id: 5253,
              name: 'NSIIMA',
              villages: [
                { id: 33560, name: 'KIREMEEZI A' },
                { id: 33561, name: 'KIREMEEZI B' },
                { id: 33562, name: 'KOTWE D' },
                { id: 33563, name: 'NAZIGO HQRS' },
                { id: 33564, name: 'SALAAMA' },
                { id: 33565, name: 'SPORTA' },
              ],
            },
          ],
        },
        {
          id: 1138,
          name: 'NAZIGO TOWN COUNCIL',
          parishes: [
            { id: 5257, name: 'KIMANYA WARD', villages: [{ id: 33589, name: 'GANGAMA' }] },
            {
              id: 5258,
              name: 'NATTETA WARD',
              villages: [
                { id: 33590, name: 'GOMBOLOLA ZONE' },
                { id: 33591, name: 'KAWONAWO ZONE' },
                { id: 33592, name: 'KINYALA ZONE' },
                { id: 33593, name: 'NATEETA' },
                { id: 33594, name: 'NAZIGO VILLAGE' },
                { id: 33595, name: 'OLD NAZIGO' },
              ],
            },
            {
              id: 5259,
              name: 'NAZIGO WARD',
              villages: [
                { id: 33596, name: 'NAZIGO-KISEVENI' },
                { id: 33597, name: 'SENDA' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
