import { District } from '../index';

export default {
  id: 132,
  name: 'KAZO',
  counties: [
    {
      id: 307,
      name: 'KAZO COUNTY',
      sub_counties: [
        {
          id: 1975,
          name: 'BUREMBA TOWN COUNCIL',
          parishes: [
            {
              id: 9263,
              name: 'BIGUTSYO WARD',
              villages: [
                { id: 59059, name: 'BIGUTSYO' },
                { id: 60799, name: 'BWIIZI B' },
                { id: 62462, name: 'KAMUGYENE' },
                { id: 62540, name: 'KANISYA' },
                { id: 63404, name: 'KIBWERA' },
              ],
            },
            {
              id: 9524,
              name: 'KABINGO WARD',
              villages: [
                { id: 61924, name: 'KABINGO A' },
                { id: 61925, name: 'KABINGO B' },
                { id: 63779, name: 'KINYUGUNYU' },
                { id: 63919, name: 'KISHORORO' },
                { id: 66459, name: 'MPUUGA A' },
                { id: 66460, name: 'MPUUGA B' },
                { id: 69018, name: 'OMUNZIGYE' },
              ],
            },
            {
              id: 9556,
              name: 'KAKONI WARD',
              villages: [
                { id: 62240, name: 'KAKONI A' },
                { id: 62241, name: 'KAKONI B' },
                { id: 66057, name: 'MARUMBA' },
                { id: 68988, name: 'OMUKABARE' },
                { id: 69976, name: 'RUSHANGO  I' },
                { id: 70019, name: 'RUYUBU' },
              ],
            },
            {
              id: 9714,
              name: 'KIJOOHA WARD',
              villages: [
                { id: 60230, name: 'BUREMBA' },
                { id: 60231, name: 'BUREMBA CENTRAL' },
                { id: 60807, name: 'BWIZI A' },
                { id: 62785, name: 'KAREBE' },
                { id: 63125, name: 'KATONGORE' },
                { id: 63610, name: 'KIJOOHA' },
                { id: 66303, name: 'MISHAMBYA' },
                { id: 70173, name: 'RWENGWE' },
              ],
            },
            {
              id: 9755,
              name: 'KITAMBA WARD',
              villages: [
                { id: 59415, name: 'BUJWAKWEZI' },
                { id: 63168, name: 'KATUNGURU' },
                { id: 63993, name: 'KITAMBA I' },
                { id: 63994, name: 'KITAMBA II' },
                { id: 64089, name: 'KITOOMA' },
                { id: 67832, name: 'NSINUNGI' },
                { id: 70261, name: 'RYENSINDIZI' },
              ],
            },
            {
              id: 9808,
              name: 'KYABAHURA WARD',
              villages: [
                { id: 60764, name: 'BWANTAAMA' },
                { id: 62229, name: 'KAKOMA' },
                { id: 64472, name: 'KYABAHURA I' },
                { id: 64473, name: 'KYABAHURA II' },
                { id: 66285, name: 'MIRAMBI' },
                { id: 66558, name: 'MUKUNGURU I' },
                { id: 66559, name: 'MUKUNGURU II' },
                { id: 66560, name: 'MUKUNGURU III' },
              ],
            },
            {
              id: 10088,
              name: 'NGOMBA WARD',
              villages: [
                { id: 62067, name: 'KAGANDO' },
                { id: 66103, name: 'MATAABA I' },
                { id: 66104, name: 'MATAABA II' },
                { id: 67753, name: 'NGOMBA' },
                { id: 69977, name: 'RUSHANGO II' },
                { id: 70065, name: 'RWAMANYONYI I' },
                { id: 70066, name: 'RWAMANYONYI II' },
              ],
            },
          ],
        },
        {
          id: 1976,
          name: 'BURUNGA',
          parishes: [
            {
              id: 9368,
              name: 'BURUNGA',
              villages: [
                { id: 60218, name: 'BURAMA B' },
                { id: 60246, name: 'BURUNGA' },
                { id: 60707, name: 'BUYAGA' },
                { id: 62214, name: 'KAKINGA' },
                { id: 62447, name: 'KAMPARA' },
                { id: 63203, name: 'KAWIRI' },
                { id: 63823, name: 'KIRINGA' },
                { id: 63920, name: 'KISHORORWA' },
                { id: 64613, name: 'KYAMASHITA' },
                { id: 66304, name: 'MISHENYI' },
                { id: 69974, name: 'RUSHAMAITU' },
              ],
            },
            {
              id: 9703,
              name: 'KIGUMA',
              villages: [
                { id: 60219, name: 'BURAMA K' },
                { id: 60765, name: 'BWANTAMA' },
                { id: 63351, name: 'KIBANI' },
                { id: 63524, name: 'KIGUMA' },
                { id: 63578, name: 'KIHWA' },
                { id: 63916, name: 'KISHEBASHEBE' },
                { id: 64808, name: 'KYENJOKI' },
                { id: 66757, name: 'MUZIRANGATA' },
                { id: 66774, name: 'MWITANUNGI' },
              ],
            },
            {
              id: 9949,
              name: 'MAGONDO',
              villages: [
                { id: 59124, name: 'BISYORO' },
                { id: 59373, name: 'BUHEMBE' },
                { id: 61595, name: 'IJWARA' },
                { id: 61845, name: 'KABAGORE' },
                { id: 61918, name: 'KABIMBA' },
                { id: 63296, name: 'KENWA' },
                { id: 63431, name: 'KIDAAMA' },
                { id: 63635, name: 'KIKANJA' },
                { id: 65895, name: 'MAGONDO' },
                { id: 70033, name: 'RWABIHEERA I' },
                { id: 70034, name: 'RWABIHEERA II' },
                { id: 70113, name: 'RWEIBUGUMYA' },
                { id: 70245, name: 'RWOMUBU' },
              ],
            },
            {
              id: 10296,
              name: 'RWIGI',
              villages: [
                { id: 57775, name: 'AKEMBOGO' },
                { id: 60812, name: 'BYABASIITA' },
                { id: 62569, name: 'KANYABUREZI' },
                { id: 63918, name: 'KISHONGOZA' },
                { id: 64811, name: 'KYENSHAMA' },
                { id: 70239, name: 'RWIIGI' },
              ],
            },
          ],
        },
        {
          id: 1983,
          name: 'ENGARI',
          parishes: [
            {
              id: 9268,
              name: 'BISHOZI',
              villages: [
                { id: 57751, name: 'AKATI' },
                { id: 59118, name: 'BISHOZI I' },
                { id: 59119, name: 'BISHOZI II' },
                { id: 62802, name: 'KARIHIRA II' },
                { id: 62812, name: 'KARITUTSI  II' },
                { id: 68064, name: 'NYAKATEETE' },
              ],
            },
            {
              id: 9465,
              name: 'ENGARI',
              villages: [
                { id: 59562, name: 'BUKIRO I' },
                { id: 59563, name: 'BUKIRO II' },
                { id: 61228, name: 'EKIJORONGA' },
                { id: 61254, name: 'ENGARI I' },
                { id: 61255, name: 'ENGARI II' },
                { id: 61256, name: 'ENGARI-SYA' },
                { id: 61922, name: 'KABINGO' },
                { id: 67924, name: 'NYABUBARE' },
                { id: 70217, name: 'RWENYAWERA' },
                { id: 70574, name: 'SYA' },
              ],
            },
            {
              id: 9554,
              name: 'KAKINDO',
              villages: [
                { id: 57738, name: 'AKARAMA' },
                { id: 59309, name: 'BUGARAMA' },
                { id: 60779, name: 'BWERA' },
                { id: 61615, name: 'IMIRAMIRINGA' },
                { id: 62201, name: 'KAKINDO' },
                { id: 67993, name: 'NYAKABUNGO' },
                { id: 68086, name: 'NYAKEERA' },
                { id: 69227, name: 'ORUSHANGO' },
              ],
            },
            {
              id: 9594,
              name: 'KANTAGANYA',
              villages: [
                { id: 62552, name: 'KANTAGANYA' },
                { id: 62553, name: 'KANTAGANYA T/CENTRE' },
                { id: 62944, name: 'KASHENYI' },
                { id: 63295, name: 'KENTUREGYE' },
                { id: 63566, name: 'KIHUMURO' },
                { id: 64071, name: 'KITONGORE' },
                { id: 64072, name: 'KITONGORE T/CENTER' },
                { id: 67870, name: 'NTUNGAMO' },
                { id: 69960, name: 'RUPYANI' },
              ],
            },
            {
              id: 9665,
              name: 'KEICHUMU',
              villages: [
                { id: 57687, name: 'AKABARE' },
                { id: 57776, name: 'AKENGOMA' },
                { id: 61223, name: 'EKIGAAGA' },
                { id: 61225, name: 'EKIGONGI' },
                { id: 62142, name: 'KAICUMU I' },
                { id: 62143, name: 'KAICUMU II' },
                { id: 62144, name: 'KAICUMU TRADING CENTRE' },
                { id: 66231, name: 'MERUMERU' },
                { id: 69895, name: 'RUGANDO' },
              ],
            },
            {
              id: 9843,
              name: 'KYENGANDO',
              villages: [
                { id: 59564, name: 'BUKIRO III' },
                { id: 61825, name: 'KAARO' },
                { id: 62951, name: 'KASHITAMO' },
                { id: 63135, name: 'KATOOMA' },
                { id: 64799, name: 'KYENGANDO I' },
                { id: 64800, name: 'KYENGANDO II' },
                { id: 64801, name: 'KYENGANDO III' },
                { id: 67911, name: 'NYABISHEKYE' },
                { id: 68192, name: 'NYAMUHIRWA' },
              ],
            },
            {
              id: 10096,
              name: 'NSHESHE',
              villages: [
                { id: 61233, name: 'EKYAMBU I' },
                { id: 61234, name: 'EKYAMBU II' },
                { id: 61264, name: 'ENTUNGA' },
                { id: 61265, name: 'ENTUNGA II' },
                { id: 66237, name: 'MEZIMERU' },
                { id: 67824, name: 'NSHESHE I' },
                { id: 67825, name: 'NSHESHE II' },
              ],
            },
          ],
        },
        {
          id: 2004,
          name: 'KANONI',
          parishes: [
            {
              id: 9403,
              name: 'BWAGONGA',
              villages: [
                { id: 60748, name: 'BWAGONGA  T/C' },
                { id: 60749, name: 'BWAGONGA I' },
                { id: 60750, name: 'BWAGONGA II' },
                { id: 60751, name: 'BWAGONGA III' },
                { id: 68244, name: 'NYARUBANGA' },
              ],
            },
            {
              id: 9764,
              name: 'KITONGORE',
              villages: [
                { id: 61971, name: 'KABURISHOKYE' },
                { id: 62071, name: 'KAGARAMA' },
                { id: 63913, name: 'KISHANGA' },
                { id: 70060, name: 'RWAMAGUFA' },
                { id: 70242, name: 'RWOBUHURA I' },
                { id: 70243, name: 'RWOBUHURA II' },
              ],
            },
            {
              id: 9972,
              name: 'MBOGO',
              villages: [
                { id: 57754, name: 'AKATONGORE' },
                { id: 62801, name: 'KARIHIRA' },
                { id: 62811, name: 'KARITUTSI  I' },
                { id: 63022, name: 'KATAGYENGYERA I' },
                { id: 63023, name: 'KATAGYENGYERA II' },
                { id: 63532, name: 'KIGUSHA' },
                { id: 66197, name: 'MBOGO I' },
                { id: 66198, name: 'MBOGO II' },
              ],
            },
            {
              id: 10129,
              name: 'NYARUBANGA',
              villages: [
                { id: 60825, name: 'BYERIMA' },
                { id: 62549, name: 'KANONI T/C' },
                { id: 63476, name: 'KIGANDO' },
                { id: 67894, name: 'NYABIHERERE I' },
                { id: 67895, name: 'NYABIHERERE II' },
                { id: 67896, name: 'NYABIHERERE III' },
                { id: 68000, name: 'NYAKABUNGO' },
              ],
            },
            {
              id: 10276,
              name: 'RWAKAHAYA',
              villages: [
                { id: 59062, name: 'BIHEMBE I' },
                { id: 59063, name: 'BIHEMBE II' },
                { id: 59064, name: 'BIHEMBE III' },
                { id: 63800, name: 'KIREEGA' },
                { id: 70042, name: 'RWAKAHAYA I' },
                { id: 70043, name: 'RWAKAHAYA II' },
              ],
            },
            {
              id: 10282,
              name: 'RWEMENGO',
              villages: [
                { id: 67868, name: 'NTUNGAMO' },
                { id: 67926, name: 'NYABUBARE  I' },
                { id: 68221, name: 'NYANJA' },
                { id: 69914, name: 'RUGUMA' },
                { id: 70131, name: 'RWEMENGO IV' },
                { id: 70132, name: 'RWEMENGO V' },
                { id: 70133, name: 'RWEMENGO VI' },
                { id: 70135, name: 'RWEMIGINA' },
              ],
            },
          ],
        },
        {
          id: 2018,
          name: 'KAZO',
          parishes: [
            {
              id: 9660,
              name: 'KAYANGA',
              villages: [
                { id: 62950, name: 'KASHENYI' },
                { id: 63214, name: 'KAYANGA  I' },
                { id: 63215, name: 'KAYANGA  II' },
                { id: 64029, name: 'KITENGYENTO' },
                { id: 68136, name: 'NYAMAMBO' },
              ],
            },
            {
              id: 9969,
              name: 'MBABA',
              villages: [
                { id: 60454, name: 'BUTERANIRO' },
                { id: 61890, name: 'KABATANAGI' },
                { id: 63283, name: 'KEMIZO' },
                { id: 63294, name: 'KENSINGA' },
                { id: 66176, name: 'MBABA' },
                { id: 68103, name: 'NYAKINOMBE' },
              ],
            },
            {
              id: 10103,
              name: 'NTAMBAZI',
              villages: [
                { id: 62270, name: 'KAKYERA' },
                { id: 63490, name: 'KIGARAMA' },
                { id: 64690, name: 'KYANTUUMO' },
                { id: 64827, name: 'KYESHEBASHEBE' },
                { id: 67851, name: 'NTAMBAZI' },
                { id: 69975, name: 'RUSHANGO' },
                { id: 70230, name: 'RWETAMU' },
              ],
            },
            {
              id: 10280,
              name: 'RWAMURANGA',
              villages: [
                { id: 59374, name: 'BUHENDA' },
                { id: 62587, name: 'KANYANYA' },
                { id: 64778, name: 'KYEJU' },
                { id: 66281, name: 'MIRAMA I' },
                { id: 66283, name: 'MIRAMA II' },
                { id: 67931, name: 'NYABUHAAMA' },
                { id: 70081, name: 'RWAMURANGA' },
              ],
            },
          ],
        },
        {
          id: 2019,
          name: 'KAZO TOWN COUNCIL',
          parishes: [
            {
              id: 9408,
              name: 'BYESHEMBE WARD',
              villages: [
                { id: 60826, name: 'BYESHEMBE' },
                { id: 64708, name: 'KYARUGYENDO' },
              ],
            },
            {
              id: 9475,
              name: 'GABARUNGI WARD',
              villages: [
                { id: 61322, name: 'GABARUNGI' },
                { id: 70039, name: 'RWABWONYO' },
                { id: 70084, name: 'RWAMUYEYE' },
              ],
            },
            {
              id: 9664,
              name: 'KAZO WARD',
              villages: [
                { id: 60794, name: 'BWESIRABO' },
                { id: 63253, name: 'KAZO I' },
                { id: 63254, name: 'KAZO II' },
              ],
            },
            {
              id: 10141,
              name: 'OBWENGARA WARD',
              villages: [
                { id: 68394, name: 'OBWENGARA' },
                { id: 70063, name: 'RWAMANUUMA' },
                { id: 70100, name: 'RWANYAMUZIRA' },
              ],
            },
            {
              id: 10285,
              name: 'RWEMIRONDO WARD',
              villages: [
                { id: 62806, name: 'KARISIZO' },
                { id: 70147, name: 'RWEMIRONDO I' },
                { id: 70148, name: 'RWEMIRONDO II' },
              ],
            },
            {
              id: 10286,
              name: 'RWEMPIRI WARD',
              villages: [
                { id: 63521, name: 'KIGOROGORO' },
                { id: 70023, name: 'RUZINGA' },
                { id: 70142, name: 'RWEMINYAFU' },
                { id: 70156, name: 'RWEMPIRI' },
              ],
            },
          ],
        },
        {
          id: 2043,
          name: 'KYAMPANGARA',
          parishes: [
            {
              id: 9166,
              name: 'AKENGYEYA',
              villages: [
                { id: 57777, name: 'AKENGYEYA I' },
                { id: 57778, name: 'AKENGYEYA II' },
                { id: 59066, name: 'BIHENDWA' },
                { id: 70236, name: 'RWETUMA' },
              ],
            },
            {
              id: 9496,
              name: 'IBAARE',
              villages: [
                { id: 57743, name: 'AKASHAYI' },
                { id: 61533, name: 'IBAARE I' },
                { id: 62262, name: 'KAKUUTO' },
                { id: 70248, name: 'RWOMUNAGO' },
                { id: 70254, name: 'RYAKAHABWA' },
              ],
            },
            {
              id: 9826,
              name: 'KYAMPANGARA',
              villages: [
                { id: 57759, name: 'AKATOOMA' },
                { id: 61534, name: 'IBAARE II' },
                { id: 64630, name: 'KYAMPANGARA I' },
                { id: 64631, name: 'KYAMPANGARA II' },
              ],
            },
            {
              id: 10013,
              name: 'MUSHABWA',
              villages: [
                { id: 66686, name: 'MUSHABWA I' },
                { id: 66687, name: 'MUSHABWA II' },
                { id: 68391, name: 'OBUZINGA I' },
                { id: 68392, name: 'OBUZINGA II' },
              ],
            },
            {
              id: 10135,
              name: 'NYUNGU',
              villages: [
                { id: 57739, name: 'AKAREERE' },
                { id: 57747, name: 'AKASIISA' },
                { id: 68299, name: 'NYUNGU  I' },
                { id: 68300, name: 'NYUNGU  II' },
              ],
            },
          ],
        },
        {
          id: 2068,
          name: 'MIGINA',
          parishes: [
            {
              id: 9165,
              name: 'AKATONGORE',
              villages: [
                { id: 57707, name: 'AKAGANDO' },
                { id: 57755, name: 'AKATONGORE CENTRAL' },
                { id: 57756, name: 'AKATONGORE I' },
                { id: 57757, name: 'AKATONGORE II' },
                { id: 57758, name: 'AKATONGORE III' },
                { id: 64788, name: 'KYEMBOGO' },
              ],
            },
            {
              id: 9719,
              name: 'KIKONI',
              villages: [
                { id: 63654, name: 'KIKONI CENTRAL' },
                { id: 63655, name: 'KIKONI I' },
                { id: 63656, name: 'KIKONI II' },
                { id: 66308, name: 'MISINGA' },
                { id: 69219, name: 'ORUGYEYA' },
              ],
            },
            {
              id: 9980,
              name: 'MIGINA',
              villages: [
                { id: 57703, name: 'AKAFENE' },
                { id: 61894, name: 'KABAURE' },
                { id: 62827, name: 'KAROKARUNGI' },
                { id: 62930, name: 'KASHAMBYA I' },
                { id: 62931, name: 'KASHAMBYA II' },
                { id: 64483, name: 'KYABAKOKWA' },
                { id: 66247, name: 'MIGINA' },
              ],
            },
          ],
        },
        {
          id: 2085,
          name: 'NKUNGU',
          parishes: [
            {
              id: 9539,
              name: 'KAGARAMIRA',
              villages: [
                { id: 57745, name: 'AKASHENYI' },
                { id: 62073, name: 'KAGARAMIRA CENTRAL' },
                { id: 62074, name: 'KAGARAMIRA I' },
                { id: 62488, name: 'KAMUSENENE I' },
                { id: 64060, name: 'KITOKYE' },
                { id: 64530, name: 'KYAKABUNGO' },
                { id: 70249, name: 'RWOMUSHAYO' },
              ],
            },
            {
              id: 9541,
              name: 'KAGIRA',
              villages: [
                { id: 62075, name: 'KAGARAMIRA II' },
                { id: 62089, name: 'KAGIRA I' },
                { id: 62090, name: 'KAGIRA II' },
                { id: 62489, name: 'KAMUSENENE II' },
                { id: 68990, name: 'OMUKABARE' },
                { id: 69028, name: 'OMWIBARE I' },
                { id: 69889, name: 'RUCUMU' },
              ],
            },
            {
              id: 9549,
              name: 'KAJUZYA',
              villages: [
                { id: 57686, name: 'AKABARE' },
                { id: 62181, name: 'KAJUZYA II' },
                { id: 62256, name: 'KAKUKURU' },
                { id: 66447, name: 'MPOMA I' },
                { id: 66448, name: 'MPOMA II' },
                { id: 69029, name: 'OMWIBARE II' },
                { id: 69989, name: 'RUTABO I' },
                { id: 69990, name: 'RUTABO II' },
                { id: 70183, name: 'RWENKUBA' },
              ],
            },
            {
              id: 9642,
              name: 'KATARAZA',
              villages: [
                { id: 57705, name: 'AKAFUNJO' },
                { id: 62929, name: 'KASHAMBYA' },
                { id: 63045, name: 'KATARAZA A' },
                { id: 63048, name: 'KATARAZA B' },
                { id: 63124, name: 'KATONGA' },
                { id: 66232, name: 'MERUMERU A' },
                { id: 66233, name: 'MERUMERU B' },
                { id: 67785, name: 'NGYEZI' },
              ],
            },
            {
              id: 10093,
              name: 'NKUNGU',
              villages: [
                { id: 62077, name: 'KAGASHA I' },
                { id: 62078, name: 'KAGASHA II' },
                { id: 62943, name: 'KASHENYANKU' },
                { id: 63074, name: 'KATETE' },
                { id: 63461, name: 'KIGAAGA' },
                { id: 67804, name: 'NKUNGU CENTRAL' },
                { id: 68198, name: 'NYAMUSHOJWA' },
                { id: 68291, name: 'NYONDO' },
                { id: 68996, name: 'OMUKATOJO' },
                { id: 69010, name: 'OMUNTEBE I' },
                { id: 69011, name: 'OMUNTEBE II' },
                { id: 69876, name: 'RUBINDESYA' },
              ],
            },
            {
              id: 10099,
              name: 'NSHUNGA',
              villages: [
                { id: 57724, name: 'AKANARA' },
                { id: 60314, name: 'BUSHARA' },
                { id: 60821, name: 'BYARUMANYA' },
                { id: 62180, name: 'KAJUZYA I' },
                { id: 62429, name: 'KAMIRAMPETA' },
                { id: 62940, name: 'KASHASHA' },
                { id: 67665, name: 'NDAGI' },
                { id: 67805, name: 'NKUNGU II' },
                { id: 67827, name: 'NSHUNGA' },
              ],
            },
          ],
        },
        {
          id: 2113,
          name: 'RWEMIKOMA',
          parishes: [
            {
              id: 9285,
              name: 'BUGARIHE',
              villages: [
                { id: 57764, name: 'AKAYAGA' },
                { id: 59311, name: 'BUGARUHE I' },
                { id: 59313, name: 'BUGARUHE I\u00c3\u0192\u00c2\u008d' },
                { id: 63166, name: 'KATUNDA' },
                { id: 66538, name: 'MUKO' },
                { id: 69931, name: 'RUKINGA' },
                { id: 70049, name: 'RWAKAKUNGU' },
                { id: 70119, name: 'RWEKISHWAGA' },
              ],
            },
            {
              id: 9715,
              name: 'KIJUMA',
              villages: [
                { id: 59621, name: 'BUKUMBAGARE' },
                { id: 62149, name: 'KAIKOTI' },
                { id: 63064, name: 'KATENGYETO' },
                { id: 63494, name: 'KIGARAMA' },
                { id: 63614, name: 'KIJUMA I' },
                { id: 63615, name: 'KIJUMA II' },
                { id: 64815, name: 'KYENTUREGYE' },
                { id: 66493, name: 'MUGORE' },
                { id: 68168, name: 'NYAMIRIMA' },
              ],
            },
            {
              id: 10284,
              name: 'RWEMIKOMA',
              villages: [
                { id: 59123, name: 'BISYA' },
                { id: 62798, name: 'KARIBA I' },
                { id: 62799, name: 'KARIBA II' },
                { id: 62800, name: 'KARIBA III' },
                { id: 66563, name: 'MUKURU' },
                { id: 70140, name: 'RWEMIKOMA LOWER' },
                { id: 70141, name: 'RWEMIKOMA UPPER' },
                { id: 70262, name: 'RYENTANGA I' },
                { id: 70263, name: 'RYENTANGA II' },
                { id: 70264, name: 'RYENTANGA III' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
