import { District } from '../types';

export default <District>{
  id: 39,
  name: 'KIKUUBE',
  counties: [
    {
      id: 84,
      name: 'BUHAGUZI COUNTY',
      sub_counties: [
        {
          id: 519,
          name: 'BUGAMBE',
          parishes: [
            {
              id: 2425,
              name: 'BUGAMBE',
              villages: [
                { id: 15850, name: 'KANIGIRO' },
                { id: 15851, name: 'KIBARARU' },
                { id: 15858, name: 'KYABAKAHUNA' },
                { id: 15852, name: 'KYAKIIZA' },
                { id: 15853, name: 'KYAKIRUBE' },
                { id: 15854, name: 'MAIRIRWE' },
                { id: 15861, name: 'MUHWIJU EAST' },
                { id: 15855, name: 'MUHWIJU WEST' },
                { id: 15856, name: 'MUNTOOKE' },
                { id: 15857, name: 'NYABUHERE' },
                { id: 15860, name: 'NYAIBALE' },
                { id: 15859, name: 'RUKEDE' },
              ],
            },
            {
              id: 2426,
              name: 'KATANGA',
              villages: [
                { id: 15862, name: 'IBAMBIRO' },
                { id: 15879, name: 'KADINDIMO' },
                { id: 15877, name: 'KAHARA' },
                { id: 15863, name: 'KAHOOJO' },
                { id: 15876, name: 'KAKORA' },
                { id: 15864, name: 'KATANGA ZAVU' },
                { id: 15865, name: 'KATANWA A' },
                { id: 15880, name: 'KATANWA B' },
                { id: 15875, name: 'KIZINIRO' },
                { id: 15866, name: 'KYABASEKE' },
                { id: 15881, name: 'KYABAYAGA' },
                { id: 64496, name: 'KYABERINDA' },
                { id: 15867, name: 'KYAKATAHA' },
                { id: 15868, name: 'KYAMBARA' },
                { id: 15869, name: 'NYAMAROBYO A' },
                { id: 15870, name: 'NYAMAROBYO B' },
                { id: 15871, name: 'NYAMULIMA' },
                { id: 15872, name: 'RWAMUTONGA' },
                { id: 15878, name: 'RWEBITERA' },
                { id: 15873, name: 'RWENGABI' },
                { id: 15874, name: 'RWENKOBE' },
              ],
            },
            {
              id: 2427,
              name: 'NYARUGABU',
              villages: [
                { id: 15882, name: 'KIGANGAMA' },
                { id: 15885, name: 'KIJENGA' },
                { id: 15886, name: 'KIKINDA' },
                { id: 15887, name: 'KIPOROPYO' },
                { id: 15888, name: 'KIRYAMBA' },
                { id: 15883, name: 'KISEETURA' },
                { id: 15889, name: 'KITONDORA' },
                { id: 15890, name: 'KYAKABAALE' },
                { id: 15891, name: 'KYAMULYANGA' },
                { id: 15884, name: 'WAMUNGA' },
              ],
            },
            {
              id: 2428,
              name: 'RUGUSE',
              villages: [
                { id: 15892, name: 'BUJAIGA EAST' },
                { id: 15909, name: 'BUJAIGA WEST' },
                { id: 15893, name: 'BUJUGU EAST' },
                { id: 15894, name: 'BUJUGU WEST' },
                { id: 15908, name: 'KICHOPE' },
                { id: 15895, name: 'KIHINYA' },
                { id: 15896, name: 'KIHOMBYA' },
                { id: 15897, name: 'KIKAYA' },
                { id: 15898, name: 'KISIITA EAST' },
                { id: 15910, name: 'KISIITA WEST' },
                { id: 15899, name: 'KIYOORA EAST' },
                { id: 15911, name: 'KIYOORA WEST' },
                { id: 15900, name: 'KYABASIMBA/KYABA' },
                { id: 15901, name: 'KYAKAJAKA' },
                { id: 15902, name: 'KYAKASORO' },
                { id: 15903, name: 'KYAMASUKA' },
                { id: 15904, name: 'KYARUBANGA(I)' },
                { id: 15905, name: 'KYARUBANGA(II)' },
                { id: 15907, name: 'KYARUHUTU' },
                { id: 15912, name: 'KYARWENSOZI' },
                { id: 15906, name: 'MARONGO' },
              ],
            },
          ],
        },
        {
          id: 520,
          name: 'BUHIMBA',
          parishes: [
            {
              id: 2429,
              name: 'KINOGOZI',
              villages: [
                { id: 15913, name: 'KACUNGIRO' },
                { id: 63363, name: 'KIBIIHYA' },
                { id: 15914, name: 'KIKONA' },
                { id: 15915, name: 'KINOGOZI EAST' },
                { id: 15916, name: 'KINOGOZI WEST' },
                { id: 15917, name: 'KIPOGO' },
                { id: 15918, name: 'KIRANGAZI' },
                { id: 15919, name: 'KISENYI' },
                { id: 15920, name: 'MPIGIZA' },
                { id: 15921, name: 'NGOGOMA' },
                { id: 15922, name: 'NYAKABONGE' },
                { id: 15923, name: 'RUGWANO' },
              ],
            },
            {
              id: 2430,
              name: 'KYABATALYA',
              villages: [
                { id: 15924, name: 'KIBARARU EAST' },
                { id: 15925, name: 'KIBARARU WEST' },
                { id: 15926, name: 'KIKOBOZA' },
                { id: 15927, name: 'MUHWIJU' },
              ],
            },
            {
              id: 2433,
              name: 'MUSAIJAMUKURU EAST',
              villages: [
                { id: 15942, name: 'BUJALYA' },
                { id: 15943, name: 'KABANYANSI' },
                { id: 15944, name: 'KALIBATANA' },
                { id: 15945, name: 'KIBINGO' },
                { id: 15946, name: 'KIHABWEMI NORTH' },
                { id: 15947, name: 'KIHABWEMI SOUTH' },
                { id: 15948, name: 'MUGABI' },
                { id: 15949, name: 'MUSAIJAMUKURU  A' },
                { id: 15950, name: 'MUSAIJAMUKURU  B' },
              ],
            },
            {
              id: 2431,
              name: 'MUSAIJAMUKURU WEST',
              villages: [
                { id: 15928, name: 'IBANDA' },
                { id: 15929, name: 'KARAMA  A' },
                { id: 15930, name: 'KARAMA  B' },
                { id: 15931, name: 'KISIIHA' },
                { id: 15932, name: 'KYAWAKAME' },
              ],
            },
            {
              id: 2432,
              name: 'RUHUNGA',
              villages: [
                { id: 15933, name: 'KABAALE/KYABICWE' },
                { id: 15934, name: 'KIGWANGU' },
                { id: 15935, name: 'KIHOOKO' },
                { id: 15936, name: 'KIJUGUNYA' },
                { id: 15937, name: 'KITINDURA' },
                { id: 15938, name: 'KITOOLE' },
                { id: 15939, name: 'MUMITI' },
                { id: 15940, name: 'RUHUNGA' },
                { id: 15941, name: 'RWEMPARAKI' },
              ],
            },
          ],
        },
        {
          id: 524,
          name: 'BUHIMBA TOWN COUNCIL',
          parishes: [
            {
              id: 2446,
              name: 'BUHIMBA EAST WARD',
              villages: [
                { id: 16148, name: 'BUHIMBA EAST' },
                { id: 16150, name: 'KIZINGA' },
                { id: 16146, name: 'KIZINGA WEST' },
                { id: 16147, name: 'NYANTWE' },
                { id: 16149, name: 'RWOBUBAZI' },
              ],
            },
            {
              id: 2447,
              name: 'BUHIMBA WEST WARD',
              villages: [
                { id: 16152, name: 'BUHIMBA CENTRAL' },
                { id: 16151, name: 'KITUNDURU' },
                { id: 16153, name: 'KYABATALYA' },
                { id: 16154, name: 'KYAMAGIGI' },
                { id: 16155, name: 'KYEGANYWA' },
              ],
            },
            {
              id: 2448,
              name: 'KIGAAYA EAST WARD',
              villages: [
                { id: 16159, name: 'KIGAAYA  EAST' },
                { id: 16156, name: 'KIGAAYA CENTRAL' },
                { id: 16158, name: 'KIGABANJOJO' },
                { id: 16157, name: 'KYABANJERU' },
              ],
            },
            {
              id: 2449,
              name: 'KIGAAYA WEST WARD',
              villages: [
                { id: 16161, name: 'KAKOOGE NORTH' },
                { id: 16160, name: 'KAKOOGE SOUTH' },
                { id: 16162, name: 'KIGAAYA  WEST' },
                { id: 63758, name: 'KINYAGIRWA' },
                { id: 16163, name: 'NYANTENDE' },
              ],
            },
          ],
        },
        {
          id: 521,
          name: 'KABWOYA',
          parishes: [
            {
              id: 2434,
              name: 'BUBOGO',
              villages: [
                { id: 15951, name: 'IKOBA I' },
                { id: 15967, name: 'IKOBA II' },
                { id: 15954, name: 'KAABIRA' },
                { id: 15952, name: 'KABAGANDA' },
                { id: 15953, name: 'KABANGO' },
                { id: 15955, name: 'KAHEMBE' },
                { id: 15968, name: 'KASENENE' },
                { id: 15969, name: 'KIDUUBI' },
                { id: 15956, name: 'KIHENDA' },
                { id: 15957, name: 'KIHOOKO' },
                { id: 15958, name: 'KIKONDA  I' },
                { id: 15959, name: 'KIKONDA  II' },
                { id: 15960, name: 'KISINDI' },
                { id: 15961, name: 'KISONSOMYA' },
                { id: 15962, name: 'KITOOLE' },
                { id: 15963, name: 'KYAKASORO' },
                { id: 15964, name: 'KYAMUGOBA' },
                { id: 15970, name: 'KYARULYAKA' },
                { id: 15965, name: 'NYAKABAALE' },
                { id: 15966, name: 'RWOBUHUKA' },
              ],
            },
            {
              id: 2435,
              name: 'IGWANJURA',
              villages: [
                { id: 15971, name: 'KINENAMABAALE' },
                { id: 15972, name: 'KITAGANYA' },
                { id: 15973, name: 'KITOOKE/KITAANA' },
                { id: 15974, name: 'KITUURU' },
                { id: 15975, name: 'KYABAHINDA' },
                { id: 15976, name: 'KYAMUJOGO' },
                { id: 15977, name: 'MAAYA A' },
                { id: 15979, name: 'MAAYA B' },
                { id: 15980, name: 'MAAYA C' },
                { id: 15981, name: 'RUSOONA' },
                { id: 15978, name: 'RWENTAHI' },
              ],
            },
            {
              id: 2436,
              name: 'KASEETA',
              villages: [
                { id: 15982, name: 'HOHWA' },
                { id: 15983, name: 'KYENJOJO' },
                { id: 15984, name: 'NDONGO' },
                { id: 15985, name: 'NYAIRONGO' },
                { id: 15986, name: 'NYANSEKE' },
                { id: 15987, name: 'RWENGABI' },
              ],
            },
            {
              id: 2438,
              name: 'KIMBUGU',
              villages: [
                { id: 15994, name: 'BWIJONGORO' },
                { id: 15995, name: 'KARAMA' },
                { id: 15996, name: 'KIBURARA(A)' },
                { id: 15997, name: 'KIBURARA(B)' },
                { id: 15998, name: 'KIMBUGU' },
                { id: 15999, name: 'KISAARU TEA ESTATE' },
                { id: 16003, name: 'KYABASAARA' },
                { id: 16000, name: 'KYABAYANJA' },
                { id: 16001, name: 'NYAIGUGU' },
                { id: 16004, name: 'NYAKAFUNJO' },
                { id: 16002, name: 'NYANGABBI' },
              ],
            },
            {
              id: 2437,
              name: 'NKONDO',
              villages: [
                { id: 15993, name: 'KYEHORRO LOWER' },
                { id: 15988, name: 'KYEHORRO UPPER' },
                { id: 15989, name: 'NKONDO I' },
                { id: 15992, name: 'NKONDO II' },
                { id: 15990, name: 'NYAWAIGA' },
                { id: 15991, name: 'SEBAGORRO' },
              ],
            },
          ],
        },
        {
          id: 522,
          name: 'KIZIRANFUMBI',
          parishes: [
            {
              id: 2439,
              name: 'BULIMYA',
              villages: [
                { id: 16005, name: 'BULIMYA' },
                { id: 16006, name: 'BUTYAMBA' },
                { id: 16007, name: 'KABEERYA' },
                { id: 16008, name: 'KAKENDE' },
                { id: 16009, name: 'KAMUSUNSI' },
                { id: 16010, name: 'KICAAYA' },
                { id: 16023, name: 'KICAKAMYA' },
                { id: 16011, name: 'KIGORORA' },
                { id: 16012, name: 'KIGOZI' },
                { id: 16013, name: 'KISAMBO' },
                { id: 16014, name: 'KISIIGA' },
                { id: 16015, name: 'KISONKO' },
                { id: 16016, name: 'KITAGASA' },
                { id: 16017, name: 'KIZIRANFUMBI' },
                { id: 16018, name: 'KYAISAMBA' },
                { id: 16019, name: 'KYARWENSAMBYA' },
                { id: 16020, name: 'MUKABARA' },
                { id: 16021, name: 'RUJUNJU' },
                { id: 16022, name: 'RUMOGI' },
              ],
            },
            {
              id: 2440,
              name: 'KIDOMA',
              villages: [
                { id: 16024, name: 'BUTIMBA EAST' },
                { id: 16033, name: 'BUTIMBA WEST' },
                { id: 16025, name: 'KANYEGARAMIRA' },
                { id: 16026, name: 'KIDOMA' },
                { id: 16027, name: 'KIHIIGWA' },
                { id: 16028, name: 'KIHOHORO' },
                { id: 16034, name: 'KITAMBARA' },
                { id: 16029, name: 'KYAKATEMBA' },
                { id: 16030, name: 'NYAMIGOGO' },
                { id: 16031, name: 'RUSAKA' },
                { id: 16032, name: 'RWAMUSAGA' },
              ],
            },
            {
              id: 2441,
              name: 'MUNTEME',
              villages: [
                { id: 16035, name: 'KAIGO' },
                { id: 16036, name: 'KAJOGA' },
                { id: 16037, name: 'KICHOMPYO' },
                { id: 16038, name: 'KICUUNDA' },
                { id: 16039, name: 'KIGABU' },
                { id: 16040, name: 'KIHUGUZI' },
                { id: 16041, name: 'KIKUUBA  A' },
                { id: 16042, name: 'KIKUUBA  B' },
                { id: 16043, name: 'KINYWAMBEHO' },
                { id: 16050, name: 'KIRYATETE' },
                { id: 16044, name: 'KISAMBYA' },
                { id: 16045, name: 'KISWAZA' },
                { id: 16046, name: 'KYANDANGANO' },
                { id: 16047, name: 'MUNTEME' },
                { id: 66671, name: 'MURWOMA' },
                { id: 16048, name: 'MUZIRANDURU' },
                { id: 16049, name: 'NYANSORORO' },
                { id: 16051, name: 'RWENGABI' },
              ],
            },
          ],
        },
        {
          id: 523,
          name: 'KYANGWALI',
          parishes: [
            {
              id: 2442,
              name: 'BUHUKA',
              villages: [
                { id: 16052, name: 'BUSIGI' },
                { id: 16053, name: 'KACUNDE' },
                { id: 16054, name: 'KIINA' },
                { id: 16055, name: 'KYABASAMBU' },
                { id: 16056, name: 'KYAKAPERE' },
                { id: 16057, name: 'KYENYANJA' },
                { id: 16058, name: 'NSONGA A' },
                { id: 16062, name: 'NSONGA B' },
                { id: 16059, name: 'NSUUNZU A' },
                { id: 16063, name: 'NSUUNZU B' },
                { id: 16060, name: 'SENJOJO' },
                { id: 16064, name: 'SONGARAU' },
                { id: 16061, name: 'SUSA' },
              ],
            },
            {
              id: 2445,
              name: 'BUTOOLE',
              villages: [
                { id: 16124, name: 'BUHUMURIRO' },
                { id: 16107, name: 'BUTOOLE  I' },
                { id: 16108, name: 'BUTOOLE  II' },
                { id: 16142, name: 'BWEERA' },
                { id: 16125, name: 'KAKONO' },
                { id: 16126, name: 'KAMUGAMBA' },
                { id: 16127, name: 'KANYEGARAMIRE' },
                { id: 16128, name: 'KAROKARUNGI' },
                { id: 16129, name: 'KARONGO' },
                { id: 16109, name: 'KASAMBYA' },
                { id: 16110, name: 'KASOGA' },
                { id: 16130, name: 'KASOGA A' },
                { id: 16131, name: 'KASOGA B' },
                { id: 16132, name: 'KASUNGWA' },
                { id: 16111, name: 'KATIKARA/BUTOOLE' },
                { id: 16133, name: 'KATOMA' },
                { id: 16112, name: 'KIBAALE' },
                { id: 16134, name: 'KIKOORA' },
                { id: 16113, name: 'KINYAMAHWA  I' },
                { id: 16114, name: 'KINYAMAHWA  II' },
                { id: 16135, name: 'KISOROZA' },
                { id: 16136, name: 'KYABARONGO' },
                { id: 16137, name: 'KYAMUGASA' },
                { id: 64689, name: 'KYANSOROSOZI' },
                { id: 16115, name: 'KYARUJUMBA  I' },
                { id: 16116, name: 'KYARUJUMBA  II' },
                { id: 16117, name: 'KYARUSESA A' },
                { id: 16138, name: 'KYARUSESA B' },
                { id: 16118, name: 'MAHAMBA' },
                { id: 16139, name: 'MANDWIGA' },
                { id: 16119, name: 'MBURARA' },
                { id: 16120, name: 'NSOZI' },
                { id: 16121, name: 'NYABISOJO' },
                { id: 16140, name: 'NYABUNENDE' },
                { id: 16141, name: 'NYAKAFUNJO' },
                { id: 68195, name: 'NYAMULIMIRWA' },
                { id: 16143, name: 'RWEMISEKE' },
                { id: 16144, name: 'RWENGABI' },
                { id: 16122, name: 'TONTEMA' },
                { id: 16145, name: 'TUHUMURE' },
                { id: 16123, name: 'WAIRAGAZA' },
              ],
            },
            {
              id: 2443,
              name: 'KASONGA',
              villages: [
                { id: 16065, name: 'BUKINDA  I' },
                { id: 16066, name: 'BUKINDA  II' },
                { id: 16076, name: 'BWIZIBWERA A' },
                { id: 16077, name: 'BWIZIBWERA B' },
                { id: 16078, name: 'HARUBALI' },
                { id: 16067, name: 'KABENENA' },
                { id: 16068, name: 'KATIKARA  I' },
                { id: 16069, name: 'KATIKARA  II A' },
                { id: 16079, name: 'KATIKARA  II B' },
                { id: 16070, name: 'KAVULE A' },
                { id: 16080, name: 'KAVULE B' },
                { id: 16071, name: 'KYAKIYORA' },
                { id: 16073, name: 'KYEYA' },
                { id: 66586, name: 'MULINDAIHOJO' },
                { id: 16074, name: 'NGURWE A' },
                { id: 16082, name: 'NGURWE B' },
                { id: 16083, name: 'NYAMIGANDA' },
                { id: 16075, name: 'NYAMIGISA A' },
                { id: 16081, name: 'NYAMIGISA B' },
                { id: 16084, name: 'RWEMBOGO' },
                { id: 16072, name: 'RWESHAMA' },
              ],
            },
            {
              id: 2444,
              name: 'KYANGWALI',
              villages: [
                { id: 16102, name: 'BOMA' },
                { id: 16085, name: 'HANGA  I' },
                { id: 16086, name: 'HANGA  II  A' },
                { id: 16087, name: 'HANGA  II  B' },
                { id: 16103, name: 'HANGA  WEST' },
                { id: 16104, name: 'IKAMIRO A' },
                { id: 16105, name: 'IKAMIRO B' },
                { id: 16106, name: 'KAMWOKYA' },
                { id: 16088, name: 'KITUUTI' },
                { id: 16089, name: 'KYANGWALI' },
                { id: 16090, name: 'NGOGOLI  I' },
                { id: 16091, name: 'NGOGOLI  II  A' },
                { id: 16092, name: 'NGOGOLI  II  B' },
                { id: 16093, name: 'NGOMA' },
                { id: 16094, name: 'NYAKATEHE  I' },
                { id: 16095, name: 'NYAKATEHE  II' },
                { id: 16096, name: 'NYAMENGO' },
                { id: 16097, name: 'NYAMYEHEMBO' },
                { id: 16098, name: 'NYANSENGE  A' },
                { id: 16099, name: 'NYANSENGE  B' },
                { id: 16100, name: 'RWEMISANGA' },
                { id: 16101, name: 'RWENSAMBYA' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
