import { District } from '../types';

export default {
  id: 120,
  name: 'KIRYANDONGO',
  counties: [
    {
      id: 281,
      name: 'KIBANDA NORTH COUNTY',
      sub_counties: [
        {
          id: 1857,
          name: 'BWEYALE TOWN COUNCIL',
          parishes: [
            {
              id: 8758,
              name: 'CENTRAL WARD',
              villages: [
                { id: 55274, name: 'BWEYALE' },
                { id: 55275, name: 'NYAMUSASA' },
              ],
            },
            {
              id: 8759,
              name: 'NORTHERN WARD',
              villages: [
                { id: 55276, name: 'ADAGWOO' },
                { id: 55277, name: 'KICWABUNGINGO' },
              ],
            },
            {
              id: 8760,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 55278, name: 'NYAKADOT' },
                { id: 55280, name: 'PANYADOLI' },
                { id: 55279, name: 'SIRIBA' },
              ],
            },
          ],
        },
        {
          id: 1981,
          name: 'DIIMA',
          parishes: [
            {
              id: 9443,
              name: 'DIIMA',
              villages: [
                { id: 57958, name: 'ALENGO' },
                { id: 58919, name: 'BAR ODUGU A' },
                { id: 58920, name: 'BAR ODUGU B' },
                { id: 61123, name: 'DIIMA  A' },
                { id: 61124, name: 'DIIMA  B' },
                { id: 61125, name: 'DIIMA HANGA' },
                { id: 69427, name: 'PA-LEE A' },
                { id: 69428, name: 'PA-LEE B' },
                { id: 69681, name: 'PII-AKEYO A' },
                { id: 69682, name: 'PII-AKEYO B' },
              ],
            },
            {
              id: 10171,
              name: 'OKWECE',
              villages: [
                { id: 68549, name: 'OGENGO  A' },
                { id: 68550, name: 'OGENGO  B' },
                { id: 70650, name: 'TE-YAGO A' },
                { id: 70651, name: 'TE-YAGO B' },
                { id: 70652, name: 'TE-YAGO C' },
              ],
            },
          ],
        },
        {
          id: 1853,
          name: 'KARUMA TOWN COUNCIL',
          parishes: [
            {
              id: 8747,
              name: 'CENTRAL WARD',
              villages: [
                { id: 55210, name: 'AWOO' },
                { id: 55211, name: 'AYUDA' },
                { id: 55212, name: 'GWARA  I' },
                { id: 55213, name: 'KARUMA' },
              ],
            },
            {
              id: 8748,
              name: 'NORTHERN WARD',
              villages: [
                { id: 55214, name: 'BEDMOT A' },
                { id: 59025, name: 'BEDMOT B' },
                { id: 55215, name: 'OKWECHE A' },
                { id: 68742, name: 'OKWECHE B' },
              ],
            },
            {
              id: 8749,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 55216, name: 'ABINDO  A' },
                { id: 55217, name: 'ABINDO  B' },
                { id: 55218, name: 'GWARA  II' },
                { id: 55219, name: 'GWARA  III' },
              ],
            },
          ],
        },
        {
          id: 1856,
          name: 'KICHWABUGINGO',
          parishes: [
            {
              id: 8755,
              name: 'CHOPE LWOR',
              villages: [
                { id: 55263, name: 'CHOPELWOR EAST' },
                { id: 61025, name: 'CHOPELWOR WEST' },
                { id: 55264, name: 'OPOK   I' },
                { id: 55265, name: 'OPOK   II' },
              ],
            },
            {
              id: 8756,
              name: 'KARUNGU',
              villages: [
                { id: 59097, name: 'BIMOKEMA' },
                { id: 61515, name: 'HANGA MAKWER' },
                { id: 55266, name: 'KANABA' },
                { id: 55267, name: 'KARUNGU  I' },
                { id: 55268, name: 'KARUNGU  II' },
                { id: 55269, name: 'KIOGOMA  I' },
                { id: 55270, name: 'KIOGOMA  II' },
                { id: 55271, name: 'POCHENG' },
              ],
            },
            {
              id: 8754,
              name: 'KICHWABUGINGO',
              villages: [
                { id: 55259, name: 'KATULIKIRE' },
                { id: 63159, name: 'KATULIKIRE B' },
                { id: 55260, name: 'KISONA' },
                { id: 55261, name: 'KITWANGA' },
                { id: 55262, name: 'KYABAHULU' },
              ],
            },
            {
              id: 8757,
              name: 'NYINGA',
              villages: [
                { id: 62379, name: 'KALUNGI' },
                { id: 64162, name: 'KIZINGA' },
                { id: 68137, name: 'NYAMASOGA' },
                { id: 55272, name: 'NYINGA  I' },
                { id: 55273, name: 'NYINGA  II' },
                { id: 70603, name: 'TANTARA' },
                { id: 70707, name: 'TENANDA' },
              ],
            },
          ],
        },
        {
          id: 1854,
          name: 'KIRYANDONGO',
          parishes: [
            {
              id: 8752,
              name: 'KIBEKA',
              villages: [
                { id: 55246, name: 'KABONYI' },
                { id: 62485, name: 'KAMUSENENE' },
                { id: 62615, name: 'KANYWAMAIZI' },
                { id: 63678, name: 'KIKUNGULU' },
                { id: 64073, name: 'KITONGOZI I' },
                { id: 64074, name: 'KITONGOZI II' },
                { id: 64662, name: 'KYAMUTESWEKA' },
                { id: 66971, name: 'NAGURU' },
                { id: 67685, name: 'NDOYO' },
                { id: 68130, name: 'NYAMALEBE' },
                { id: 68196, name: 'NYAMUNTENDE' },
                { id: 70661, name: 'TECWA' },
              ],
            },
            {
              id: 8750,
              name: 'KIKUBE',
              villages: [
                { id: 55220, name: 'BULIGI' },
                { id: 55221, name: 'KABAROLE' },
                { id: 55223, name: 'KINYOMOZI' },
                { id: 55224, name: 'KIROKO  I' },
                { id: 55225, name: 'KIROKO  II' },
                { id: 55226, name: 'KITALEEBA' },
                { id: 55222, name: 'KYAMABALE' },
                { id: 55227, name: 'MAHONGE' },
                { id: 55228, name: 'MASAMBA' },
                { id: 55230, name: 'NYABIISO' },
                { id: 55229, name: 'NYABUKONI' },
                { id: 55231, name: 'NYAKAGANDO' },
                { id: 55232, name: 'NYAKAKINDO' },
                { id: 55233, name: 'NYAKATAAMA I' },
                { id: 55234, name: 'RUNYANYA' },
              ],
            },
            {
              id: 8751,
              name: 'KITWARA',
              villages: [
                { id: 55238, name: 'KAKOOGE' },
                { id: 62519, name: 'KANENOBERI' },
                { id: 55236, name: 'KANKOBA' },
                { id: 55237, name: 'KAPUNDO' },
                { id: 55240, name: 'KIRONGOLO' },
                { id: 55241, name: 'KIRYAMPUNGULA' },
                { id: 55242, name: 'KITWARA' },
                { id: 55243, name: 'KOOKI' },
                { id: 55244, name: 'KYAMAKUBAGI' },
                { id: 55235, name: 'KYAMUTESWEKA' },
                { id: 55245, name: 'KYANSANYI' },
                { id: 55239, name: 'MULYANTAMA' },
              ],
            },
            {
              id: 9841,
              name: 'KYEMBERA',
              villages: [
                { id: 61196, name: 'DYANG' },
                { id: 61337, name: 'GASPA' },
                { id: 62299, name: 'KALANGALA' },
                { id: 62384, name: 'KALWALA' },
                { id: 63888, name: 'KISEKURA' },
                { id: 63965, name: 'KISUNGA I' },
                { id: 64784, name: 'KYEMBERA' },
                { id: 66297, name: 'MIRIMA' },
                { id: 67932, name: 'NYABUKONI' },
              ],
            },
          ],
        },
        {
          id: 1858,
          name: 'KIRYANDONGO TOWN COUNCIL',
          parishes: [
            {
              id: 8761,
              name: 'NORTHERN WARD',
              villages: [
                { id: 55281, name: 'KIRYANDONGO I' },
                { id: 55282, name: 'KISOROSORO' },
                { id: 55283, name: 'MUKONOGUMU' },
              ],
            },
            {
              id: 8762,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 55285, name: 'KAROKARUNGI' },
                { id: 55286, name: 'KIKUUBE' },
                { id: 55284, name: 'KIRYANDONGO II' },
                { id: 55287, name: 'KYAKALYABE' },
              ],
            },
          ],
        },
        {
          id: 1859,
          name: 'KYANKENDE',
          parishes: [
            {
              id: 8764,
              name: 'DIIKA',
              villages: [
                { id: 61122, name: 'DIIKA' },
                { id: 55294, name: 'KIGAYA' },
                { id: 55295, name: 'KIHURA' },
                { id: 63972, name: 'KISWEKA I' },
                { id: 63973, name: 'KISWEKA II' },
                { id: 55296, name: 'KYANKULU' },
                { id: 66218, name: 'MENGO' },
                { id: 55297, name: 'SABASABA' },
                { id: 70276, name: 'SAMBYA' },
                { id: 55298, name: 'TUGO' },
              ],
            },
            {
              id: 8765,
              name: 'KAHARA',
              villages: [
                { id: 60191, name: 'BUNYAMA I' },
                { id: 55301, name: 'BUNYAMA II' },
                { id: 60192, name: 'BUNYAMA III' },
                { id: 55299, name: 'KAAPOLE' },
                { id: 61850, name: 'KABALE' },
                { id: 55300, name: 'KAHARA' },
                { id: 63367, name: 'KIBIMBYA I' },
                { id: 63368, name: 'KIBIMBYA II' },
                { id: 55302, name: 'KIRWALA' },
                { id: 55303, name: 'SAMBYA' },
              ],
            },
            {
              id: 8763,
              name: 'KYANKENDE',
              villages: [
                { id: 57218, name: 'ABONGO' },
                { id: 60830, name: 'CALIFONIA' },
                { id: 55288, name: 'KARAGALYA I' },
                { id: 62763, name: 'KARAGALYA II' },
                { id: 63165, name: 'KATUMBATUMBA' },
                { id: 55289, name: 'KIJUNE' },
                { id: 55290, name: 'KISUNGA  II' },
                { id: 55291, name: 'KYANKENDE' },
                { id: 55292, name: 'KYESIMBWA' },
                { id: 55293, name: 'MOMBI' },
              ],
            },
          ],
        },
        {
          id: 1855,
          name: 'MUTUNDA',
          parishes: [
            {
              id: 8753,
              name: 'KAKWOKWO',
              villages: [
                { id: 55247, name: 'ISUNGA' },
                { id: 62171, name: 'KAJEBE' },
                { id: 55250, name: 'KAWITI' },
                { id: 55248, name: 'KAWITI A' },
                { id: 55249, name: 'KAWITI B' },
                { id: 55251, name: 'KIKONGE' },
                { id: 55252, name: 'KIRULI' },
                { id: 55253, name: 'KISURA' },
                { id: 55254, name: 'KITINA' },
                { id: 55255, name: 'MUTUNDA  A' },
                { id: 55256, name: 'MUTUNDA  B' },
                { id: 55257, name: 'NYAKAGWENG' },
                { id: 55258, name: 'POPARA EAST' },
              ],
            },
            {
              id: 9725,
              name: 'KIMOGORO',
              villages: [
                { id: 61870, name: 'KABANGAMURO' },
                { id: 62887, name: 'KASANJA  A' },
                { id: 62888, name: 'KASANJA  B' },
                { id: 62889, name: 'KASANJA  C' },
                { id: 62890, name: 'KASANJA  D' },
                { id: 63718, name: 'KIMOGORO A' },
                { id: 63719, name: 'KIMOGORO B' },
                { id: 63720, name: 'KIMOGORO C' },
                { id: 63721, name: 'KIMOGORO D' },
                { id: 63722, name: 'KIMOGORO E' },
              ],
            },
            {
              id: 10242,
              name: 'PANYADOLI',
              villages: [
                { id: 69589, name: 'PANYADOLI  A' },
                { id: 69590, name: 'PANYADOLI  B' },
                { id: 69591, name: 'PANYADOLI  C' },
                { id: 69592, name: 'PANYADOLI  D' },
                { id: 69593, name: 'PANYADOLI  E' },
                { id: 69594, name: 'PANYADOLI  F' },
              ],
            },
          ],
        },
        {
          id: 1860,
          name: 'NYAMAHASA',
          parishes: [
            {
              id: 8767,
              name: 'ALERO',
              villages: [
                { id: 55308, name: 'ALARO-TINGA' },
                { id: 55309, name: 'ALERO  A' },
                { id: 55310, name: 'ALERO  B' },
                { id: 55311, name: 'ALERO  C' },
                { id: 55312, name: 'ALERO  D' },
                { id: 55313, name: 'ALILA' },
                { id: 55314, name: 'NANDA' },
                { id: 55315, name: 'TENAM  A' },
                { id: 55316, name: 'TENAM  B' },
              ],
            },
            {
              id: 8768,
              name: 'LABOKE',
              villages: [
                { id: 55317, name: 'ALARO-OGWAL-WOO A' },
                { id: 57932, name: 'ALARO-OGWAL-WOO B' },
                { id: 64874, name: 'LABOKE' },
                { id: 64875, name: 'LABOKE  HANGA A' },
                { id: 64876, name: 'LABOKE  HANGA B' },
                { id: 55318, name: 'LABOKE - KOLOLO' },
                { id: 55320, name: 'LABOKE - PACWACH' },
                { id: 55319, name: 'NANDA GAME' },
                { id: 55321, name: 'TE-LABOKE' },
              ],
            },
            {
              id: 8769,
              name: 'NANDA',
              villages: [
                { id: 61319, name: 'FUNGUA  MACHO A' },
                { id: 61320, name: 'FUNGUA  MACHO B' },
                { id: 55322, name: 'LAVOR-ONGUR  A' },
                { id: 55323, name: 'LAVOR-ONGUR  B' },
                { id: 55326, name: 'LAVOR-ONGUR C' },
                { id: 55324, name: 'NANDA  A' },
                { id: 55325, name: 'NANDA  B' },
                { id: 67414, name: 'NANDA  C' },
                { id: 69727, name: 'POPARA WEST A' },
              ],
            },
            {
              id: 8766,
              name: 'NYAMAHASA',
              villages: [
                { id: 62172, name: 'KAJEBE A' },
                { id: 55304, name: 'KAJEBE B' },
                { id: 65132, name: 'LATWORO A' },
                { id: 65133, name: 'LATWORO B' },
                { id: 55305, name: 'NYAMAHASA  A' },
                { id: 55306, name: 'NYAMAHASA  B' },
                { id: 55307, name: 'POPARA  WEST' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 280,
      name: 'KIBANDA SOUTH COUNTY',
      sub_counties: [
        {
          id: 1849,
          name: 'KIGUMBA',
          parishes: [
            {
              id: 8737,
              name: 'BUHOOMOZI',
              villages: [
                { id: 55172, name: 'BUHOMOZI' },
                { id: 62036, name: 'KADUKU  I' },
                { id: 62037, name: 'KADUKU  II' },
                { id: 62038, name: 'KADUKU  III' },
                { id: 63400, name: 'KIBURA' },
                { id: 55173, name: 'KIKOOBA' },
                { id: 55174, name: 'KIRULI' },
                { id: 65864, name: 'MADISI' },
                { id: 66585, name: 'MULIMANI' },
                { id: 68122, name: 'NYAMA  I' },
                { id: 68123, name: 'NYAMA  II' },
              ],
            },
            {
              id: 8735,
              name: 'KIGUMBA',
              villages: [
                { id: 55147, name: 'CO-OP COLLEGE' },
                { id: 62446, name: 'KAMPALA CERERE' },
                { id: 55148, name: 'KATAMARWA' },
                { id: 55150, name: 'KIDIDIMA' },
                { id: 55151, name: 'KINAGIRANA' },
                { id: 55157, name: 'KYAKIBANGA' },
                { id: 55149, name: 'KYAKIBANGA II' },
                { id: 55158, name: 'KYAMUGENYI' },
                { id: 64640, name: 'KYAMUGENYI B' },
                { id: 55154, name: 'NYAKIBETE  I' },
                { id: 55159, name: 'NYAKIBETE  II' },
                { id: 55152, name: 'NYAKIBETE UPPER' },
                { id: 55153, name: 'PONDO' },
                { id: 55155, name: 'RWABIGARAGARA' },
                { id: 55156, name: 'RWAKAYATA' },
                { id: 70053, name: 'RWAKAYATA II' },
              ],
            },
            {
              id: 8736,
              name: 'KIIGYA',
              villages: [
                { id: 55161, name: 'JEEJA  I' },
                { id: 55162, name: 'JEEJA  II' },
                { id: 55160, name: 'KAMUSIKIRI' },
                { id: 55166, name: 'KIGENGERE' },
                { id: 55167, name: 'KIIGYA' },
                { id: 55168, name: 'KINYARA  I' },
                { id: 55169, name: 'KINYARA  II' },
                { id: 55170, name: 'KINYARA III' },
                { id: 55163, name: 'KISENYI' },
                { id: 55164, name: 'NYAKYEFUMBIRA' },
                { id: 55165, name: 'NYARUBALE' },
                { id: 55171, name: 'TITI' },
              ],
            },
            {
              id: 9997,
              name: 'MPUMWE',
              villages: [
                { id: 61852, name: 'KABALE' },
                { id: 61880, name: 'KABARANGA' },
                { id: 62879, name: 'KASAMBYA' },
                { id: 63407, name: 'KIBYAMA' },
                { id: 63483, name: 'KIGANGARA EAST' },
                { id: 63484, name: 'KIGANGARA WEST' },
                { id: 64682, name: 'KYANKOGE' },
                { id: 64769, name: 'KYEGANYWA  I' },
                { id: 64770, name: 'KYEGANYWA  II' },
                { id: 66456, name: 'MPUMWE' },
                { id: 67069, name: 'NAKINOMBER' },
                { id: 70073, name: 'RWAMUDOPYO' },
              ],
            },
          ],
        },
        {
          id: 1852,
          name: 'KIGUMBA TOWN COUNCIL',
          parishes: [
            {
              id: 8744,
              name: 'WARD A',
              villages: [
                { id: 55201, name: 'KIBURAMATU' },
                { id: 55202, name: 'KIGUMBA  I' },
                { id: 55203, name: 'NYAKATUGO' },
              ],
            },
            {
              id: 8745,
              name: 'WARD B',
              villages: [
                { id: 55204, name: 'KABUKYE' },
                { id: 55205, name: 'KIGARAGARA' },
                { id: 55206, name: 'KIGUMBA  II' },
              ],
            },
            {
              id: 8746,
              name: 'WARD C',
              villages: [
                { id: 55207, name: 'KIHURA  I' },
                { id: 55208, name: 'KIHURA  II' },
                { id: 55209, name: 'KITWANGA' },
              ],
            },
          ],
        },
        {
          id: 1851,
          name: 'MASINDI PORT',
          parishes: [
            {
              id: 8742,
              name: 'KADUKU',
              villages: [
                { id: 55188, name: 'KADUKU  I' },
                { id: 55189, name: 'KADUKU  II' },
                { id: 55190, name: 'KATUGO' },
                { id: 55191, name: 'KINYONGA  I' },
                { id: 55192, name: 'KINYONGA  II' },
                { id: 55193, name: 'KITALEBA' },
                { id: 68183, name: 'NYAMIZO' },
                { id: 68287, name: 'NYINARWENKUNYI' },
                { id: 70838, name: 'TUFOMA' },
                { id: 55194, name: 'WAKISANYI' },
              ],
            },
            {
              id: 9769,
              name: 'KITUKUZA',
              villages: [
                { id: 58902, name: 'BANKWEYO' },
                { id: 62333, name: 'KALIRO' },
                { id: 63379, name: 'KIBIRANI' },
                { id: 63629, name: 'KIKAITO' },
                { id: 63717, name: 'KIMIOKA' },
                { id: 63830, name: 'KIRULI' },
                { id: 63904, name: 'KISENYI' },
                { id: 64105, name: 'KITUKUZA' },
                { id: 64820, name: 'KYERIA' },
                { id: 70158, name: 'RWEMPONDO' },
              ],
            },
            {
              id: 8743,
              name: 'WAIBANGO',
              villages: [
                { id: 55195, name: 'KIMIOKA' },
                { id: 55196, name: 'KIRYANSEKA' },
                { id: 55197, name: 'KITUKUZA' },
                { id: 55198, name: 'NAMILYANGO' },
                { id: 68031, name: 'NYAKARONGO' },
                { id: 55199, name: 'RWENKUNYI' },
                { id: 55200, name: 'WAIBANGO' },
              ],
            },
            {
              id: 10335,
              name: 'WAKISANYI',
              villages: [
                { id: 63148, name: 'KATUGO' },
                { id: 63282, name: 'KEMIYAMBI' },
                { id: 66438, name: 'MPANGAIBIRI' },
                { id: 66782, name: 'MYEBA' },
                { id: 67812, name: 'NKWOKOITWA' },
                { id: 70987, name: 'WAKISANYI' },
              ],
            },
          ],
        },
        {
          id: 1850,
          name: 'MBOIRA',
          parishes: [
            {
              id: 8741,
              name: 'APODORWA',
              villages: [
                { id: 57171, name: 'ABIRA' },
                { id: 55185, name: 'APODORWA' },
                { id: 58415, name: 'APODORWA II' },
                { id: 55186, name: 'IRANDA' },
                { id: 62816, name: 'KARKOVE' },
                { id: 55187, name: 'KIFURUTA  I' },
                { id: 68069, name: 'NYAKATITI I' },
                { id: 68070, name: 'NYAKATITI II' },
              ],
            },
            {
              id: 8739,
              name: 'KIFURUTA',
              villages: [
                { id: 57961, name: 'ALENGO' },
                { id: 60841, name: 'CANNA' },
                { id: 55180, name: 'KIFURUTA  II' },
                { id: 55181, name: 'KIFURUTA  III' },
                { id: 64544, name: 'KYAKAKUNGULU I' },
                { id: 64545, name: 'KYAKAKUNGULU II' },
                { id: 65136, name: 'LAVORONGUR EAST' },
                { id: 55182, name: 'LAVORONGUR WEST' },
                { id: 70948, name: 'UYAA' },
              ],
            },
            {
              id: 8738,
              name: 'MBOIRA',
              villages: [
                { id: 55175, name: 'HANGA' },
                { id: 55176, name: 'MBOIRA  I' },
                { id: 55177, name: 'MBOIRA  II' },
                { id: 55178, name: 'NKWENDA  I' },
                { id: 55179, name: 'NKWENDA  II' },
                { id: 67811, name: 'NKWENDA  III' },
                { id: 68006, name: 'NYAKAFUNJO' },
              ],
            },
            {
              id: 8740,
              name: 'NYAKABALE',
              villages: [
                { id: 55183, name: 'KEMENZU' },
                { id: 63275, name: 'KEMENZU CENTRAL' },
                { id: 63276, name: 'KEMENZU LOWER' },
                { id: 55184, name: 'KIKUNYA' },
                { id: 67969, name: 'NYAKABALE I' },
                { id: 67971, name: 'NYAKABALE II' },
                { id: 67972, name: 'NYAKABALE III' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
