import { District } from '../types';

export default <District>{
  id: 48,
  name: 'KITGUM',
  counties: [
    {
      id: 105,
      name: 'CHUA EAST COUNTY',
      sub_counties: [
        {
          id: 665,
          name: 'KITENY',
          parishes: [
            {
              id: 3041,
              name: 'KITENY',
              villages: [
                { id: 19771, name: 'AKUNA' },
                { id: 19770, name: 'ALWONGO CHUA' },
                { id: 19765, name: 'KABOKOTUM B' },
                { id: 19766, name: 'LALEKAN CENTRAL' },
                { id: 19767, name: 'LALEKAN EAST' },
                { id: 19772, name: 'OBEM' },
                { id: 19768, name: 'PALOWALA' },
                { id: 19769, name: 'TEGOT KALABONG' },
              ],
            },
            {
              id: 3038,
              name: 'KWARAYO',
              villages: [
                { id: 57677, name: 'AJULU' },
                { id: 19744, name: 'APIMOTUR' },
                { id: 19745, name: 'GOONA' },
                { id: 19750, name: 'GOONA NORTH' },
                { id: 19752, name: 'KAMONI' },
                { id: 19746, name: 'KONA ABIM' },
                { id: 19747, name: 'LACEKOCOT' },
                { id: 19751, name: 'LACEKOCOT B' },
                { id: 19748, name: 'LAKONGERA' },
                { id: 19749, name: 'RYAMAKILOK' },
              ],
            },
            {
              id: 3039,
              name: 'LADOTONEN',
              villages: [
                { id: 19758, name: 'AWINYO' },
                { id: 19753, name: 'LADOTONEN CENTRAL' },
                { id: 19754, name: 'LADOTONEN EAST' },
                { id: 19755, name: 'LADOTONEN WEST' },
                { id: 64925, name: 'LADOTONONEN CITY' },
                { id: 19756, name: 'LAMOGI' },
                { id: 19757, name: 'OTOME' },
              ],
            },
            {
              id: 3040,
              name: 'PALUBA',
              villages: [
                { id: 19759, name: 'BONGO PII EAST' },
                { id: 19760, name: 'BONGOPII WEST' },
                { id: 19761, name: 'KABOKOTUM A' },
                { id: 19762, name: 'PALOBAR A' },
                { id: 19763, name: 'PALOBAR B' },
                { id: 19764, name: 'TELATYENG' },
              ],
            },
          ],
        },
        {
          id: 668,
          name: 'MUCHWINI',
          parishes: [
            {
              id: 3048,
              name: 'AKARA',
              villages: [
                { id: 19832, name: 'BIDIN' },
                { id: 19833, name: 'JUBA' },
                { id: 19834, name: 'LACENOTINGA EAST' },
                { id: 19835, name: 'LACENOTINGA WEST' },
                { id: 19836, name: 'MOTA A' },
                { id: 19842, name: 'MOTA B' },
                { id: 19837, name: 'OMOKLURU' },
                { id: 19838, name: 'ORIMA A' },
                { id: 19839, name: 'ORIMA B' },
                { id: 19840, name: 'ORIMA CENTRAL' },
                { id: 19841, name: 'TWON OKUN' },
              ],
            },
            {
              id: 3049,
              name: 'PAJONG',
              villages: [
                { id: 57382, name: 'ACUT OMER' },
                { id: 19843, name: 'AGWOKO' },
                { id: 61440, name: 'GULIT' },
                { id: 19844, name: 'LABATIOLWONGA A' },
                { id: 19845, name: 'LAGOT A' },
                { id: 19846, name: 'LAGOT B' },
                { id: 19848, name: 'LATOL' },
                { id: 65296, name: 'LOGOT BURLELA' },
                { id: 19849, name: 'LUBATIOLWONGA B' },
                { id: 65575, name: 'LUBIRI' },
                { id: 65685, name: 'LURWO' },
                { id: 19847, name: 'MOYA' },
                { id: 19850, name: 'PAJONG A' },
                { id: 19851, name: 'PAJONG B' },
                { id: 19852, name: 'PAJONG C' },
              ],
            },
            {
              id: 3050,
              name: 'YEPA',
              villages: [
                { id: 59176, name: 'BOROBORO' },
                { id: 19855, name: 'KOMNURU' },
                { id: 19861, name: 'LONDON' },
                { id: 65557, name: 'LOYONYUKA' },
                { id: 19853, name: 'MUCWINI CENTRAL WARD' },
                { id: 19854, name: 'OBIA WARD' },
                { id: 19862, name: 'OWINY WARD' },
                { id: 19860, name: 'PADWONG' },
                { id: 19856, name: 'YEPA A' },
                { id: 19857, name: 'YEPA B' },
                { id: 19858, name: 'YEPA CENTRAL' },
                { id: 19859, name: 'YEPA WEST OWINY' },
              ],
            },
          ],
        },
        {
          id: 666,
          name: 'MUCHWINI EAST',
          parishes: [
            {
              id: 3044,
              name: 'OGWAPOKE',
              villages: [
                { id: 61603, name: 'IKOROM' },
                { id: 65193, name: 'LIKOL A' },
                { id: 19796, name: 'LIKOL B' },
                { id: 65194, name: 'LIKOL CENTRAL' },
                { id: 19797, name: 'OMUNA A' },
                { id: 19800, name: 'OMUNA B' },
                { id: 19798, name: 'ORUMA' },
                { id: 69659, name: 'PEDERYAM  A' },
                { id: 69660, name: 'PEDERYAM  B' },
                { id: 19799, name: 'PUKURE' },
              ],
            },
            {
              id: 3042,
              name: 'OKOL',
              villages: [
                { id: 19773, name: 'ARAA' },
                { id: 19774, name: 'AYOMOLOLA  A' },
                { id: 19775, name: 'BIWANG EAST' },
                { id: 19776, name: 'BIWANG WEST' },
                { id: 19777, name: 'KITIBOL' },
                { id: 19778, name: 'PAMA BONE' },
                { id: 19779, name: 'POCODO' },
              ],
            },
            {
              id: 3043,
              name: 'PUBECH',
              villages: [
                { id: 19793, name: 'AGWENG' },
                { id: 19780, name: 'BUCE' },
                { id: 19792, name: 'KALALA' },
                { id: 19782, name: 'KALANG A' },
                { id: 19787, name: 'KALANG B' },
                { id: 19790, name: 'KELPOLO' },
                { id: 19795, name: 'LAGOT CUGU' },
                { id: 19781, name: 'LARAKARAKA CENTRAL' },
                { id: 19783, name: 'LINGALINGA A' },
                { id: 19791, name: 'LINGALINGA B' },
                { id: 19784, name: 'LOTUKUBOR' },
                { id: 19785, name: 'MULIKI' },
                { id: 19786, name: 'OBELE' },
                { id: 19794, name: 'PARYEKO TEL  B' },
                { id: 19788, name: 'PARYEKO TEL A' },
                { id: 19789, name: 'PUBECH EAST' },
                { id: 69744, name: 'PUBECH WEST' },
              ],
            },
          ],
        },
        {
          id: 667,
          name: 'MUCHWINI WEST',
          parishes: [
            {
              id: 3045,
              name: 'BURA',
              villages: [
                { id: 19801, name: 'AGULA A' },
                { id: 19802, name: 'AGULA B' },
                { id: 19803, name: 'LAWOGOWOGO A' },
                { id: 19811, name: 'LAWOGOWOGO B' },
                { id: 19808, name: 'NGWENY EAST' },
                { id: 19804, name: 'NGWENY WEST' },
                { id: 19805, name: 'PANYUM A' },
                { id: 19806, name: 'PANYUM B' },
                { id: 19810, name: 'PANYUM CENTRAL' },
                { id: 19812, name: 'PUDURE' },
                { id: 19807, name: 'PUDURE A' },
                { id: 19809, name: 'PUDURE B' },
              ],
            },
            {
              id: 3046,
              name: 'PACHUA',
              villages: [
                { id: 58106, name: 'AMATKIMEYA' },
                { id: 19813, name: 'BUR LELA' },
                { id: 19814, name: 'ICEGO TYENA' },
                { id: 19815, name: 'PAKUBA CENTRAL' },
                { id: 19816, name: 'PAKUBA EAST' },
                { id: 19817, name: 'PAKUBA WEST' },
                { id: 69543, name: 'PALWE' },
              ],
            },
            {
              id: 3047,
              name: 'PUDO',
              villages: [
                { id: 19818, name: 'GOLNGOM A' },
                { id: 19819, name: 'GOLNGOM B' },
                { id: 19820, name: 'KABETE' },
                { id: 19821, name: 'LAKWELE OKATO A' },
                { id: 19828, name: 'LAKWELE OKATO B' },
                { id: 19822, name: 'MUGILA' },
                { id: 19823, name: 'PANYOK' },
                { id: 19827, name: 'PUDO A' },
                { id: 19831, name: 'PUDO B' },
                { id: 19824, name: 'PUDO CENTRAL' },
                { id: 19830, name: 'PUDO KWEYO' },
                { id: 19829, name: 'TEPWOYO CENTRAL' },
                { id: 19825, name: 'TEPWOYO EAST' },
                { id: 19826, name: 'TEPWOYO WEST' },
              ],
            },
          ],
        },
        {
          id: 669,
          name: 'NAM-OKORA',
          parishes: [
            {
              id: 3051,
              name: 'DIETE',
              villages: [
                { id: 19863, name: 'AGOTAGOT' },
                { id: 19864, name: 'BARJERE' },
                { id: 61198, name: 'DYE-BUNGA' },
                { id: 69857, name: 'ROSIL' },
                { id: 19865, name: 'TUMANGU' },
              ],
            },
            {
              id: 3052,
              name: 'PUGODA EAST',
              villages: [
                { id: 61433, name: 'GUDA' },
                { id: 19871, name: 'MASAKA' },
                { id: 19867, name: 'ODILANG' },
                { id: 19868, name: 'ORABUL' },
                { id: 19869, name: 'ORYEBO' },
                { id: 19866, name: 'PALABUL' },
                { id: 19870, name: 'ROSIL' },
              ],
            },
            {
              id: 3053,
              name: 'PUGODA WEST',
              villages: [
                { id: 19872, name: 'BOROBORO' },
                { id: 19873, name: 'JAIPII' },
                { id: 19874, name: 'LAPANA' },
                { id: 19877, name: 'LAYIKA' },
                { id: 19879, name: 'LOGURUC' },
                { id: 19878, name: 'MULOZI' },
                { id: 19875, name: 'NYAPEA A' },
                { id: 19876, name: 'NYAPEA B' },
              ],
            },
          ],
        },
        {
          id: 671,
          name: 'NAM-OKORA NORTH',
          parishes: [
            {
              id: 3061,
              name: 'KALABONG',
              villages: [
                { id: 19928, name: 'GILIGILI' },
                { id: 19933, name: 'GILIGILI KAL' },
                { id: 19929, name: 'KALABONG CENTRAL' },
                { id: 19930, name: 'KALABONG EAST' },
                { id: 19931, name: 'MASESE' },
                { id: 19932, name: 'PALOBOLU' },
              ],
            },
            {
              id: 3058,
              name: 'ONYALA',
              villages: [
                { id: 58007, name: 'ALIMA LAGOT' },
                { id: 61494, name: 'GWOLO' },
                { id: 19918, name: 'LAGOT GWOLO' },
                { id: 19915, name: 'LAGUM A' },
                { id: 19916, name: 'LAGUM B' },
                { id: 19919, name: 'LAKOGA' },
                { id: 19922, name: 'LOGUM DOG TANGI' },
                { id: 19917, name: 'ONYALA' },
                { id: 19920, name: 'ONYALA CENTRAL' },
                { id: 19921, name: 'PALOMUTE' },
              ],
            },
            {
              id: 3060,
              name: 'PAGWOK',
              villages: [
                { id: 19926, name: 'DOG DEM A' },
                { id: 61146, name: 'DOG TANGI' },
                { id: 19927, name: 'DOGDEM B' },
                { id: 64980, name: 'LAKOKOK' },
                { id: 65300, name: 'LOGUM A' },
                { id: 65301, name: 'LOGUM DOG TANGI' },
              ],
            },
            {
              id: 3059,
              name: 'PALABOLO',
              villages: [
                { id: 19923, name: 'KALABONG WEST' },
                { id: 68388, name: 'OBUTU CEL' },
                { id: 19924, name: 'OGUL' },
                { id: 69537, name: 'PALOBOLU' },
                { id: 69646, name: 'PAWINY' },
                { id: 19925, name: 'WINYO RAC' },
              ],
            },
          ],
        },
        {
          id: 664,
          name: 'NAMOKORA TOWN COUNCIL',
          parishes: [
            {
              id: 3034,
              name: 'CENTRAL WARD',
              villages: [
                { id: 19732, name: 'MISSION' },
                { id: 19734, name: 'ORYANG CENTRAL' },
                { id: 19733, name: 'PAGER' },
                { id: 19735, name: 'PUNU AKURU' },
                { id: 70891, name: 'TWON OKUN' },
              ],
            },
            {
              id: 3035,
              name: 'KATUBBU WARD',
              villages: [
                { id: 57278, name: 'ABWOBE' },
                { id: 61405, name: 'GONY KITENGE' },
                { id: 19736, name: 'KAKO' },
                { id: 62225, name: 'KAKO CENTRAL' },
                { id: 19737, name: 'KITELENG' },
              ],
            },
            {
              id: 3036,
              name: 'LADWOGGI WARD',
              villages: [
                { id: 62623, name: 'KAOLO' },
                { id: 19738, name: 'KWEYO' },
                { id: 19739, name: 'LADWOGI' },
                { id: 64926, name: 'LADWOGI CENTRAL' },
                { id: 19740, name: 'NGORA' },
              ],
            },
            {
              id: 3037,
              name: 'WIGWENG WARD',
              villages: [
                { id: 19741, name: 'BOROBORO' },
                { id: 64939, name: 'LAGOT CUGU' },
                { id: 19742, name: 'ORYANG' },
                { id: 69245, name: 'ORYANG WEST' },
                { id: 19743, name: 'RAPAI' },
              ],
            },
          ],
        },
        {
          id: 673,
          name: 'OMIYA-ANYIMA',
          parishes: [
            {
              id: 3066,
              name: 'MELONG',
              villages: [
                { id: 19985, name: 'BALANGO CENTRAL' },
                { id: 19978, name: 'BALANGOR KWEYO' },
                { id: 19979, name: 'BALANGOR TEGOT' },
                { id: 19980, name: 'JOLLO A' },
                { id: 19986, name: 'JOLO B' },
                { id: 62098, name: 'KAGON' },
                { id: 19987, name: 'KUMELE KASESE' },
                { id: 19981, name: 'KUMELE WICERE' },
                { id: 19982, name: 'KWEYO' },
                { id: 19983, name: 'MANYNGEYI' },
                { id: 19984, name: 'MANYNGEYI CENTRAL' },
              ],
            },
            {
              id: 10154,
              name: 'OGILI',
              villages: [
                { id: 61054, name: 'COO PELWO' },
                { id: 62310, name: 'KALELE CENTRAL' },
                { id: 64389, name: 'KUMELE KASESE' },
                { id: 64390, name: 'KUMELE WICERE' },
                { id: 65076, name: 'LANGO OYENG' },
                { id: 65078, name: 'LANGOLA NGOLA' },
                { id: 65086, name: 'LANYAP' },
                { id: 70618, name: 'TE YAA' },
              ],
            },
            {
              id: 10245,
              name: 'PANYUM',
              villages: [
                { id: 58656, name: 'ATO-CON' },
                { id: 58851, name: 'AYWEE' },
                { id: 59168, name: 'BONGO LAYIK' },
                { id: 59169, name: 'BONGOLAYIK EAST' },
                { id: 61115, name: 'DIC-PEE' },
                { id: 62385, name: 'KALWENY' },
                { id: 64448, name: 'KWEYO' },
                { id: 65131, name: 'LATUTURU EAST' },
                { id: 65554, name: 'LOYO ATERA' },
                { id: 68311, name: 'OBALO GUNGU' },
                { id: 68484, name: 'ODONG LOR EAST' },
                { id: 68494, name: 'ODONGLOR' },
                { id: 68780, name: 'OLELA' },
                { id: 69761, name: 'PUR BER' },
              ],
            },
            {
              id: 3068,
              name: 'PANYUM MELONG',
              villages: [
                { id: 19996, name: 'CENTRAL' },
                { id: 19997, name: 'LATUTURU' },
                { id: 19998, name: 'LYELO KWAR' },
              ],
            },
            {
              id: 3069,
              name: 'PANYUM PELA',
              villages: [
                { id: 20010, name: 'AGUKU MANYIGE WEST' },
                { id: 20008, name: 'BARA-TOYO' },
                { id: 20002, name: 'CENTRAL' },
                { id: 20001, name: 'CENTRAL KWEYO' },
                { id: 20000, name: 'KALELE' },
                { id: 19999, name: 'KATOPLAK' },
                { id: 20011, name: 'KATOPLAK B' },
                { id: 20003, name: 'KWEYO' },
                { id: 20004, name: 'LABWOROMOR' },
                { id: 20009, name: 'LACAN BIL' },
                { id: 20005, name: 'OGILI' },
                { id: 20007, name: 'TE-GWENG' },
                { id: 20006, name: 'TE-OKIRO' },
              ],
            },
            {
              id: 3067,
              name: 'PELLA',
              villages: [
                { id: 19988, name: 'AMOYOKOL' },
                { id: 19995, name: 'AMOYOKOL CENTRAL' },
                { id: 61197, name: 'DYANGBII' },
                { id: 61466, name: 'GURUGURU' },
                { id: 62288, name: 'KALAKI' },
                { id: 19989, name: 'LAMODYAK' },
                { id: 19990, name: 'LOKAOLET' },
                { id: 67747, name: 'NGOM LAC' },
                { id: 19991, name: 'PELLA CENTRAL' },
                { id: 19992, name: 'PUYUDA' },
                { id: 19994, name: 'PUYUDA EAST' },
                { id: 70954, name: 'VITNAM' },
                { id: 19993, name: 'WICERE' },
              ],
            },
          ],
        },
        {
          id: 672,
          name: 'OMIYA-ANYIMA WEST',
          parishes: [
            {
              id: 3064,
              name: 'AKOBI',
              villages: [
                { id: 19956, name: 'ABAKA DYEL AELI' },
                { id: 19965, name: 'ABAKA DYEL WEST' },
                { id: 19967, name: 'AELI' },
                { id: 57800, name: 'AKOBI KENYA CENTRAL' },
                { id: 19957, name: 'AKOBI OLWOC' },
                { id: 57926, name: 'ALAMATU' },
                { id: 58956, name: 'BARDYANG' },
                { id: 58957, name: 'BARDYANG CENTRAL' },
                { id: 58958, name: 'BARDYANG TECWA' },
                { id: 19958, name: 'GWOKNGWEE EAST' },
                { id: 19959, name: 'GWOKNGWEE WEST' },
                { id: 61493, name: 'GWOKOGWEE CENTRAL' },
                { id: 19963, name: 'GWOKONGWE EAST' },
                { id: 19964, name: 'KANYUMA' },
                { id: 19966, name: 'LAGAMPIR' },
                { id: 19960, name: 'PEDERYAM' },
                { id: 70614, name: 'TE ODONG' },
                { id: 19962, name: 'TE-GWIRI EAST' },
                { id: 19961, name: 'TEGWIRI' },
              ],
            },
            {
              id: 3065,
              name: 'PALAMENY',
              villages: [
                { id: 19969, name: 'ABONGOLEE' },
                { id: 19968, name: 'ALYEKA' },
                { id: 58766, name: 'AWINY KI LEE' },
                { id: 19975, name: 'LABAKARA' },
                { id: 64901, name: 'LACANBIL' },
                { id: 19974, name: 'LWALA' },
                { id: 19970, name: 'OBOLOKOME' },
                { id: 19971, name: 'OBWORE WEST' },
                { id: 19972, name: 'ORABONYO' },
                { id: 19977, name: 'ORABONYO CENTRAL' },
                { id: 19973, name: 'PALAMENY CENTRAL' },
                { id: 19976, name: 'PALAMENY WEST' },
              ],
            },
            {
              id: 3063,
              name: 'PALWO',
              villages: [
                { id: 19946, name: 'ACUT OMER' },
                { id: 19947, name: 'APOT-ALOR' },
                { id: 19954, name: 'APOTA ALOR SOUTH' },
                { id: 19952, name: 'KAGAK' },
                { id: 64862, name: 'LABAL WII' },
                { id: 19955, name: 'LABONGO OGURU' },
                { id: 19948, name: 'LARAKA' },
                { id: 19949, name: 'MOTA CENTRAL' },
                { id: 19950, name: 'MOTA FOREST' },
                { id: 19953, name: 'OBWORE CENTRAL' },
                { id: 19951, name: 'OBWORE EAST' },
                { id: 71154, name: 'WINY CIK' },
              ],
            },
            {
              id: 3062,
              name: 'PARA',
              villages: [
                { id: 19945, name: 'ACALAWAI FOREST' },
                { id: 19935, name: 'ACALAWAYI' },
                { id: 19934, name: 'ACHALAWAI' },
                { id: 19936, name: 'KENYA CENTRAL' },
                { id: 19937, name: 'KENYA EAST' },
                { id: 19938, name: 'KENYA WEST' },
                { id: 19939, name: 'LELA PUNGOR' },
                { id: 19942, name: 'LODWAR CENTRAL' },
                { id: 19940, name: 'LODWAR JAIPII' },
                { id: 67757, name: 'NGOMLAC' },
                { id: 19943, name: 'TE-GWENG' },
                { id: 19944, name: 'TE-OBOKE' },
                { id: 19941, name: 'WANG LANGO' },
              ],
            },
          ],
        },
        {
          id: 670,
          name: 'OROM',
          parishes: [
            {
              id: 9490,
              name: 'GULE',
              villages: [
                { id: 57694, name: 'AKADO JWAT' },
                { id: 65036, name: 'LAMINGONEN' },
                { id: 65710, name: 'LUTOR' },
                { id: 70751, name: 'TIKAO' },
                { id: 70771, name: 'TOBOI' },
                { id: 70926, name: 'UMGOT' },
                { id: 71158, name: 'WIPOLO' },
              ],
            },
            {
              id: 3054,
              name: 'KARAKELET',
              villages: [
                { id: 19889, name: 'ABIL NINO' },
                { id: 19880, name: 'CAMGWENG' },
                { id: 19886, name: 'CAMGWENG WEST' },
                { id: 19881, name: 'JUBA' },
                { id: 19888, name: 'JUBA CENTRAL' },
                { id: 19885, name: 'LAGWOK OMER' },
                { id: 19882, name: 'LAPEITAK' },
                { id: 19883, name: 'LAPENE' },
                { id: 19887, name: 'NGARIYAK' },
                { id: 19884, name: 'RINGILIL' },
              ],
            },
            {
              id: 3057,
              name: 'LOLIA',
              villages: [
                { id: 19907, name: 'DODOMA' },
                { id: 19908, name: 'KONA' },
                { id: 19913, name: 'LADITOYWEE' },
                { id: 19909, name: 'LENGA CENTRAL' },
                { id: 19910, name: 'LOKIPAWA' },
                { id: 19911, name: 'RUKUK' },
                { id: 19914, name: 'TEMPOLO' },
                { id: 19912, name: 'WANG KENYA' },
              ],
            },
            {
              id: 3056,
              name: 'LOLWA',
              villages: [
                { id: 19897, name: 'AGOROMIN' },
                { id: 19898, name: 'AGOROMIN CITY' },
                { id: 19899, name: 'ISAREAL' },
                { id: 19900, name: 'KAMANDING' },
                { id: 19901, name: 'LABWOROMOR' },
                { id: 19906, name: 'LABWOROMOR WEST' },
                { id: 19902, name: 'LAGWELIMA' },
                { id: 19903, name: 'LOGEREMA' },
                { id: 19905, name: 'MADI OPEI' },
                { id: 19904, name: 'MULEMBE' },
                { id: 68981, name: 'OMORU' },
              ],
            },
            {
              id: 3055,
              name: 'LUNGANYURA',
              villages: [
                { id: 19890, name: 'AGORA' },
                { id: 19891, name: 'BALE' },
                { id: 19892, name: 'CEYLON' },
                { id: 19893, name: 'CEYLON WEST' },
                { id: 19894, name: 'LONGANYURA CENTRAL' },
                { id: 19895, name: 'LONGANYURA EAST' },
                { id: 65528, name: 'LOT-LOKOYO' },
                { id: 19896, name: 'OJORONGOLE' },
              ],
            },
          ],
        },
        {
          id: 674,
          name: 'OROM EAST',
          parishes: [
            {
              id: 3070,
              name: 'AKURUMO',
              villages: [
                { id: 20012, name: 'LOBALE' },
                { id: 20020, name: 'LOCHUM' },
                { id: 20013, name: 'LOCOMO CENTRAL' },
                { id: 20014, name: 'LODWAR' },
                { id: 20015, name: 'LOLUNG' },
                { id: 20016, name: 'LOPERU' },
                { id: 20017, name: 'NABOLO' },
                { id: 20018, name: 'NAGOLO PAK' },
                { id: 20019, name: 'NARUNGA TUNY' },
                { id: 20021, name: 'ZAIRE' },
              ],
            },
            {
              id: 3071,
              name: 'KATWOTWO',
              villages: [
                { id: 20022, name: 'ANGAN' },
                { id: 20023, name: 'BILAYOLO' },
                { id: 20029, name: 'LATODORE' },
                { id: 20027, name: 'LOBIRI' },
                { id: 20024, name: 'LOKONGU' },
                { id: 20025, name: 'LOLUKO' },
                { id: 20026, name: 'LOMULE' },
                { id: 20034, name: 'MOROCOLONG' },
                { id: 20028, name: 'MORULEM' },
                { id: 66406, name: 'MORULEM NORTH' },
                { id: 20030, name: 'OLAYA' },
                { id: 20031, name: 'RACKOKO' },
                { id: 20032, name: 'TULTUL CENTRAL' },
                { id: 20033, name: 'TULTUL NORTH' },
              ],
            },
            {
              id: 3072,
              name: 'OKUTI',
              villages: [
                { id: 20035, name: 'AKILOK CENTRAL' },
                { id: 57789, name: 'AKILOK NORTH' },
                { id: 20036, name: 'AKILOK SOUTH' },
                { id: 20045, name: 'DALA' },
                { id: 20037, name: 'KACELEM' },
                { id: 20038, name: 'KOLOPIRE' },
                { id: 20039, name: 'LAKORE' },
                { id: 20040, name: 'LAWEL' },
                { id: 20041, name: 'LOCOM' },
                { id: 20046, name: 'LOJIRA' },
                { id: 20042, name: 'LOKIBARAC' },
                { id: 20043, name: 'LOKOM' },
                { id: 20047, name: 'NYAPEYA' },
                { id: 20044, name: 'PUDPUD' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 104,
      name: 'CHUA WEST COUNTY',
      sub_counties: [
        {
          id: 663,
          name: 'AKWANG',
          parishes: [
            {
              id: 3030,
              name: 'LAMIT',
              villages: [
                { id: 19692, name: 'ADYEE' },
                { id: 19693, name: 'BAJERE' },
                { id: 19699, name: 'BAJERE EAST' },
                { id: 19701, name: 'BAJERE SOUTH' },
                { id: 19703, name: 'BONGO-LAKUR' },
                { id: 19700, name: 'DERO-OMEDA' },
                { id: 19694, name: 'LABWOROMOR' },
                { id: 19695, name: 'LAMIT LIBA' },
                { id: 19702, name: 'LOKORO-ORWE' },
                { id: 19696, name: 'PEM' },
                { id: 19704, name: 'TAD LAGWE' },
                { id: 19697, name: 'TUMANGU' },
                { id: 19698, name: 'VIETNAM' },
              ],
            },
            {
              id: 3031,
              name: 'LUGWAR',
              villages: [
                { id: 19705, name: 'AKADO' },
                { id: 19706, name: 'GOKO' },
                { id: 19707, name: 'LUBENE EAST' },
                { id: 19710, name: 'LUBENE WEST' },
                { id: 19708, name: 'MWOLBUNE' },
                { id: 19709, name: 'ORYANG OGOM' },
              ],
            },
            {
              id: 3033,
              name: 'MURA',
              villages: [
                { id: 19726, name: 'LUGWAR CENTRAL' },
                { id: 19730, name: 'MIDLAND' },
                { id: 19727, name: 'OGET' },
                { id: 19731, name: 'OKWICI EAST' },
                { id: 19728, name: 'OKWICI WEST' },
                { id: 19729, name: 'PALI' },
              ],
            },
            {
              id: 3032,
              name: 'PAJIMO',
              villages: [
                { id: 19711, name: 'ABUDERE' },
                { id: 19718, name: 'AGWENG' },
                { id: 19712, name: 'ATENG' },
                { id: 19720, name: 'BOLBOM' },
                { id: 19723, name: 'KILIME EAST' },
                { id: 19713, name: 'KILIME WEST' },
                { id: 19719, name: 'MEDE' },
                { id: 19722, name: 'ODONGILURU' },
                { id: 19714, name: 'PAJIMO BOLA' },
                { id: 19715, name: 'PAJIMO CENTRAL' },
                { id: 19716, name: 'PAJIMO EAST' },
                { id: 19717, name: 'PAJIMO WEST' },
                { id: 19725, name: 'PANYKEL' },
                { id: 19724, name: 'PINYMUNU' },
                { id: 19721, name: 'WIGWENG' },
              ],
            },
          ],
        },
        {
          id: 657,
          name: 'KITGUM MATIDI',
          parishes: [
            {
              id: 3005,
              name: 'LUMULE',
              villages: [
                { id: 19517, name: 'ADAK' },
                { id: 19518, name: 'BOLKOL' },
                { id: 19519, name: 'BOLKOL CENTRAL' },
                { id: 19520, name: 'GORE' },
                { id: 19531, name: 'LACAN-ONYONG' },
                { id: 19530, name: 'LALWORO-ONEN' },
                { id: 19521, name: 'LANYAMBIRA' },
                { id: 19522, name: 'LUWALOGUR' },
                { id: 19523, name: 'NAZERERTH' },
                { id: 19524, name: 'OKWONGOBONE' },
                { id: 19525, name: 'OLAMBYERA' },
                { id: 19526, name: 'OMARODWEE' },
                { id: 19527, name: 'ONYAA CENTRAL' },
                { id: 19528, name: 'TONGROM' },
                { id: 19529, name: 'WANGOLAM' },
              ],
            },
            {
              id: 3006,
              name: 'ORYANG B',
              villages: [
                { id: 19539, name: 'ACUT OMER' },
                { id: 19538, name: 'AMAKO RYEK' },
                { id: 19532, name: 'LABIGIRYAM' },
                { id: 19533, name: 'LABONGO DONYO SOUTH' },
                { id: 19542, name: 'LABONGO-ODONYO CENTRAL' },
                { id: 19541, name: 'LABONGO-ODONYO NORTH' },
                { id: 19534, name: 'LANGII' },
                { id: 19540, name: 'OGOO WINYO' },
                { id: 19535, name: 'PUNOCOL' },
                { id: 19536, name: 'PUTUKE EAST' },
                { id: 19537, name: 'PUTUKE WEST' },
              ],
            },
            {
              id: 3007,
              name: 'PAIBONY',
              villages: [
                { id: 19543, name: 'APUTUBERE' },
                { id: 19553, name: 'APUTUBERE A' },
                { id: 19554, name: 'APUTUBERE B' },
                { id: 19544, name: 'DOGTUNY' },
                { id: 19545, name: 'LAPANA A' },
                { id: 19546, name: 'LAPANA B' },
                { id: 19547, name: 'MAKTUNU' },
                { id: 19548, name: 'MULAGO A' },
                { id: 19549, name: 'MULAGO B' },
                { id: 19555, name: 'MUNUOTAM' },
                { id: 19551, name: 'OBYEN CENTRAL' },
                { id: 19550, name: 'OBYEN EAST' },
                { id: 19552, name: 'ORAKWE' },
              ],
            },
          ],
        },
        {
          id: 658,
          name: 'KITGUM MATIDI TOWN COUNCIL',
          parishes: [
            {
              id: 3008,
              name: 'IBAKARA WARD',
              villages: [
                { id: 19556, name: 'BOBI  A' },
                { id: 19557, name: 'BOBI B' },
                { id: 19558, name: 'BOBI CENTRAL' },
                { id: 19560, name: 'BOBI EAST' },
                { id: 19559, name: 'BOBI OLOK KI AYWERI' },
                { id: 19561, name: 'OLOKAYWERI' },
              ],
            },
            {
              id: 3010,
              name: 'JERUSALEM',
              villages: [
                { id: 19566, name: 'DOGNAM' },
                { id: 61757, name: 'JERUSALEM LUNG GWENG' },
                { id: 19567, name: 'JERUSALEM WIGWENG' },
                { id: 19568, name: 'LAKWERAJOK' },
              ],
            },
            { id: 9513, name: 'JERUSALEM WARD', villages: [] },
            {
              id: 3012,
              name: 'PAGWA WARD',
              villages: [
                { id: 19574, name: 'PAGWA AWERE' },
                { id: 19578, name: 'PAGWA CENTRAL' },
                { id: 19575, name: 'PAGWA DOGNAM' },
                { id: 19573, name: 'PAGWA LAGOMA' },
                { id: 19576, name: 'PAGWA LAYAMO' },
                { id: 19577, name: 'PAGWA SAMBA' },
                { id: 69476, name: 'PAGWA WILELA' },
              ],
            },
            {
              id: 3009,
              name: 'PAKUMU WARD',
              villages: [
                { id: 19563, name: 'PAKUMU A' },
                { id: 19564, name: 'PAKUMU JANGYAT' },
                { id: 19562, name: 'PAKUMU KAMDINI' },
                { id: 19565, name: 'PAKUMU OLUK' },
              ],
            },
            {
              id: 3011,
              name: 'PARWECH WARD',
              villages: [
                { id: 19569, name: 'PARWECH ALANGO' },
                { id: 19570, name: 'PARWECH LOJUL' },
                { id: 19572, name: 'PARWECH LUMAK' },
                { id: 19571, name: 'PARWECH TEGWENG' },
              ],
            },
          ],
        },
        {
          id: 660,
          name: 'LABONGO-AMIDA',
          parishes: [
            {
              id: 3019,
              name: 'AKWORO',
              villages: [
                { id: 19619, name: 'AKWORO TECWA NORTH' },
                { id: 19614, name: 'AKWORO TECWA SOUTH' },
                { id: 19620, name: 'AROMO RWOT' },
                { id: 19615, name: 'GANGLELA' },
                { id: 19616, name: 'MANWOKO NORTH' },
                { id: 19617, name: 'MANWOKO SOUTH' },
                { id: 19618, name: 'OYURU' },
              ],
            },
            {
              id: 3017,
              name: 'LUKWOR',
              villages: [
                { id: 19609, name: 'LOKIRA CENTRAL' },
                { id: 19602, name: 'LOKIRA NORTH' },
                { id: 19603, name: 'LOKIRA SOUTH' },
                { id: 19604, name: 'LUKWOR EAST A' },
                { id: 19607, name: 'LUKWOR EAST B' },
                { id: 19605, name: 'LUKWOR WEST A' },
                { id: 65646, name: 'LUKWOR WEST B' },
                { id: 19606, name: 'OPETTE' },
                { id: 19608, name: 'OPETTE EAST' },
              ],
            },
            {
              id: 3018,
              name: 'ORYANG A',
              villages: [
                { id: 19610, name: 'BIPONG' },
                { id: 69243, name: 'ORYANG OJUMA  B' },
                { id: 69244, name: 'ORYANG OJUMA  SOUTH B' },
                { id: 19613, name: 'ORYANG OJUMA A NORTH' },
                { id: 19611, name: 'ORYANG OJUMA A SOUTH' },
                { id: 19612, name: 'TANGI AGORO' },
              ],
            },
          ],
        },
        {
          id: 2046,
          name: 'LABONGO-AMIDA WEST',
          parishes: [
            {
              id: 9784,
              name: 'KOCH',
              villages: [
                { id: 57970, name: 'ALERO' },
                { id: 68430, name: 'OCUBU LATARA' },
                { id: 70592, name: 'TAIOCOT' },
                { id: 71070, name: 'WAO CENTRAL' },
                { id: 71071, name: 'WAOBINEN' },
              ],
            },
            {
              id: 9862,
              name: 'LAMOLA',
              villages: [
                { id: 59099, name: 'BINEN' },
                { id: 64934, name: 'LAGAYA' },
                { id: 64935, name: 'LAGAYA WEST' },
                { id: 65146, name: 'LAYIK EAST' },
                { id: 65147, name: 'LAYIK KOCO' },
                { id: 65148, name: 'LAYIK WEST' },
                { id: 69008, name: 'OMUMY BULL WEST' },
                { id: 69012, name: 'OMUNY BUL' },
              ],
            },
            {
              id: 10165,
              name: 'OKIDI',
              villages: [
                { id: 58744, name: 'AWERE' },
                { id: 61200, name: 'DYEORYANG' },
                { id: 62440, name: 'KAMPALA' },
                { id: 62444, name: 'KAMPALA ANYUKA' },
                { id: 64952, name: 'LAGWAL' },
                { id: 65001, name: 'LALILIBI' },
                { id: 65108, name: 'LARABA' },
                { id: 68678, name: 'OKIDI CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 659,
          name: 'LABONGO-LAYAMO',
          parishes: [
            {
              id: 3016,
              name: 'OCETOKE',
              villages: [
                { id: 19596, name: 'LAMUGU' },
                { id: 19597, name: 'OCETOKE  CENTRAL' },
                { id: 19598, name: 'OCETOKE EAST' },
                { id: 19599, name: 'OCETOKE NORTH' },
                { id: 19600, name: 'OCETOKE WEST' },
                { id: 19601, name: 'TUMA ATOO' },
              ],
            },
            {
              id: 3013,
              name: 'PAGEN',
              villages: [
                { id: 19579, name: 'GWENG AJUT' },
                { id: 19584, name: 'LALWAL' },
                { id: 19580, name: 'LELAMUR' },
                { id: 19581, name: 'PAGEN CENTRAL' },
                { id: 19582, name: 'PAGEN EAST' },
                { id: 19583, name: 'PAGEN WEST' },
              ],
            },
            {
              id: 3015,
              name: 'PAIBWOR',
              villages: [
                { id: 19595, name: 'PAIBWOR CENTRAL' },
                { id: 19591, name: 'PAIBWOR EAST' },
                { id: 19592, name: 'PAIBWOR NORTH' },
                { id: 19593, name: 'PAIBWOR SOUTH' },
                { id: 19594, name: 'PAIBWOR WEST' },
              ],
            },
            {
              id: 3014,
              name: 'PAMOLO',
              villages: [
                { id: 19590, name: 'ATURA' },
                { id: 19585, name: 'OBEM CENTRAL' },
                { id: 19586, name: 'OBEM EAST' },
                { id: 19587, name: 'OBEM NORTH' },
                { id: 19589, name: 'PAMOLO CENTRAL' },
                { id: 19588, name: 'PAMOLO OLET' },
              ],
            },
          ],
        },
        {
          id: 662,
          name: 'LAGORO',
          parishes: [
            {
              id: 3026,
              name: 'AKUNA',
              villages: [
                { id: 19668, name: 'AJUMANI' },
                { id: 19669, name: 'AKUNA' },
                { id: 19672, name: 'AKUNA CENTRAL' },
                { id: 19670, name: 'LAJANGA' },
                { id: 19671, name: 'LAJANGA WEST' },
              ],
            },
            {
              id: 3027,
              name: 'BULUZI',
              villages: [
                { id: 19673, name: 'ATEM' },
                { id: 59752, name: 'BULUZI' },
                { id: 59753, name: 'BULUZI CENTRAL' },
                { id: 19676, name: 'KIWER' },
                { id: 19674, name: 'LAMOGI' },
                { id: 19675, name: 'LANYIKOR' },
              ],
            },
            {
              id: 3024,
              name: 'LABER',
              villages: [
                { id: 57769, name: 'AKECAH B' },
                { id: 57770, name: 'AKECHA A' },
                { id: 57771, name: 'AKECHA CENTRAL' },
                { id: 19655, name: 'ALERO' },
                { id: 19652, name: 'BOLO' },
                { id: 59716, name: 'BULOBO' },
                { id: 19653, name: 'DAGO PANY' },
                { id: 19654, name: 'RAA-OKUM' },
              ],
            },
            {
              id: 3028,
              name: 'LABILO',
              villages: [
                { id: 19682, name: 'ALEL CENTRAL' },
                { id: 19677, name: 'ALEL EAST' },
                { id: 19678, name: 'ALEL WEST' },
                { id: 19681, name: 'ALEL WEST B' },
                { id: 19679, name: 'LABILO  A' },
                { id: 19680, name: 'LABILO  B' },
                { id: 19683, name: 'LABILO CENTRAL' },
                { id: 65089, name: 'LANYATONO' },
              ],
            },
            {
              id: 3025,
              name: 'PAWIDI',
              villages: [
                { id: 19666, name: 'DOG ORA' },
                { id: 19667, name: 'GULU GWEN' },
                { id: 19664, name: 'LADUR' },
                { id: 19658, name: 'LAGAMPI  B' },
                { id: 19657, name: 'LAGAMPI A' },
                { id: 19656, name: 'LAGAMPIR' },
                { id: 19665, name: 'LATANG' },
                { id: 19659, name: 'OGUDA' },
                { id: 19662, name: 'OGUDA  EAST' },
                { id: 19663, name: 'OGUDA  WEST' },
                { id: 19660, name: 'ORUA  A' },
                { id: 19661, name: 'ORUA  B' },
              ],
            },
            {
              id: 3029,
              name: 'WIGWENG',
              villages: [
                { id: 19684, name: 'APECHA' },
                { id: 19685, name: 'LABORA' },
                { id: 19686, name: 'LAJORO' },
                { id: 19689, name: 'NAM-OYIKA' },
                { id: 19691, name: 'OYIKA-TEKIKWA' },
                { id: 19687, name: 'PACO' },
                { id: 19688, name: 'VIETNAM' },
                { id: 19690, name: 'WIGWENG' },
              ],
            },
          ],
        },
        {
          id: 661,
          name: 'LALANO',
          parishes: [
            {
              id: 3020,
              name: 'ALOTO',
              villages: [
                { id: 19621, name: 'ALOTO CENTRAL' },
                { id: 19622, name: 'ALOTO NORTH' },
                { id: 19623, name: 'ALOTO SOUTH' },
                { id: 19627, name: 'LAMIN  PIC' },
                { id: 19624, name: 'LANGO OMUK' },
                { id: 19625, name: 'LANGOL ALENGA  A' },
                { id: 65077, name: 'LANGOL ALENGA B' },
                { id: 19626, name: 'LAUDA' },
              ],
            },
            {
              id: 3021,
              name: 'BALAKWA',
              villages: [
                { id: 19628, name: 'ADAK' },
                { id: 57767, name: 'AKAYOLITWAC' },
                { id: 19631, name: 'ALYEMO' },
                { id: 58882, name: 'BALAKWA' },
                { id: 19629, name: 'DAGOPANY' },
                { id: 19630, name: 'IKOR' },
                { id: 19634, name: 'LALOO EAST' },
                { id: 19633, name: 'LALOO WEST' },
                { id: 19632, name: 'LALOR' },
              ],
            },
            {
              id: 3023,
              name: 'LAKWOR',
              villages: [
                { id: 19641, name: 'ADINGA A' },
                { id: 19651, name: 'ADINGA B' },
                { id: 19642, name: 'DANYA' },
                { id: 19643, name: 'JAMAIKA A' },
                { id: 19650, name: 'JAMIKA B' },
                { id: 19648, name: 'LAKWOR CENTRAL A' },
                { id: 19647, name: 'LAKWOR CENTRAL B' },
                { id: 19649, name: 'OGUL WEST' },
                { id: 19646, name: 'POKA LOK TEK' },
                { id: 19644, name: 'RUCURUCU' },
                { id: 19645, name: 'WANGKWORO' },
              ],
            },
            {
              id: 3022,
              name: 'LALANO',
              villages: [
                { id: 57790, name: 'AKINO' },
                { id: 19638, name: 'DAM KULUKWAC B' },
                { id: 19635, name: 'DEM KULUKWAC A' },
                { id: 19636, name: 'LAGWE KONYA' },
                { id: 19637, name: 'LALANO' },
                { id: 19640, name: 'LALANO CENTRAL' },
                { id: 19639, name: 'LEI BIT' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 106,
      name: 'KITGUM MUNICIPALITY',
      sub_counties: [
        {
          id: 675,
          name: 'CENTRAL DIVISION',
          parishes: [
            {
              id: 3073,
              name: 'TOWN WARD',
              villages: [
                { id: 20048, name: 'APOLO GROUND' },
                { id: 20049, name: 'CENTRAL' },
                { id: 20050, name: 'LANGA LANGA' },
              ],
            },
            {
              id: 3074,
              name: 'WEST LAND WARD A',
              villages: [
                { id: 20051, name: '1ST JENGE' },
                { id: 20052, name: 'ACUT OMER A' },
                { id: 20054, name: 'LAMDOGI' },
                { id: 20053, name: 'LUWALINGA' },
              ],
            },
            {
              id: 3075,
              name: 'WEST LAND WARD B',
              villages: [
                { id: 20055, name: '2ND JENGE' },
                { id: 20056, name: 'AFRICAN VILLAGE' },
                { id: 20057, name: 'KONY PACO' },
                { id: 20058, name: 'WEST VILLAGE' },
              ],
            },
          ],
        },
        {
          id: 677,
          name: 'PAGER DIVISION',
          parishes: [
            {
              id: 3080,
              name: 'GREEN LAND WARD',
              villages: [
                { id: 20077, name: 'LEMOBONGOLEWIC EAST' },
                { id: 20078, name: 'LEMOBONGOLEWIC SOUTH' },
                { id: 20079, name: 'LEMOBONGOLEWIC WEST' },
              ],
            },
            {
              id: 3081,
              name: 'PAGER WARD A',
              villages: [
                { id: 20082, name: 'LAMIT KAPIM CENTRAL' },
                { id: 20080, name: 'LAMIT KAPIM NORTH' },
                { id: 20081, name: 'LAMIT KAPIM SOUTH' },
              ],
            },
            {
              id: 3083,
              name: 'PAGER WARD B',
              villages: [
                { id: 20090, name: 'AYUL A NORTH' },
                { id: 20086, name: 'AYUL A SOUTH' },
                { id: 20087, name: 'AYUL B' },
                { id: 20088, name: 'AYUL C' },
                { id: 20089, name: 'OGWAL WOO' },
              ],
            },
            {
              id: 3082,
              name: 'PONGDWONGO WARD',
              villages: [
                { id: 20085, name: 'LATITI' },
                { id: 20084, name: 'NYANYA' },
                { id: 20083, name: 'NYIKI-NYIKI' },
              ],
            },
          ],
        },
        {
          id: 676,
          name: 'PANDWONG DIVISION',
          parishes: [
            {
              id: 3076,
              name: 'ALANGO WARD',
              villages: [
                { id: 20059, name: 'ALANGO EAST' },
                { id: 20060, name: 'ALANGO WEST' },
                { id: 20061, name: 'CAMCAM' },
                { id: 20062, name: 'TANGI AGORO' },
              ],
            },
            {
              id: 3077,
              name: 'GUU WARD A',
              villages: [
                { id: 20063, name: 'GINNERY EAST' },
                { id: 20064, name: 'GINNERY WEST' },
                { id: 20065, name: 'ORYANG OJUMA' },
              ],
            },
            {
              id: 3079,
              name: 'GUU WARD B',
              villages: [
                { id: 20073, name: 'EAST VILLAGE  A' },
                { id: 20074, name: 'EAST VILLAGE  B' },
                { id: 20076, name: 'EAST VILLAGE C' },
                { id: 20075, name: 'UPLAND' },
              ],
            },
            {
              id: 3078,
              name: 'PANDWONG WARD',
              villages: [
                { id: 20070, name: 'ACUT OMER' },
                { id: 20066, name: 'AUCH' },
                { id: 20067, name: 'BAR DEGE' },
                { id: 20068, name: 'GANGDYANG' },
                { id: 20071, name: 'GODOWN' },
                { id: 20072, name: 'HILLTOP' },
                { id: 20069, name: 'PANDWONG' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
