import { District } from '../types';

export default {
  id: 14,
  name: 'KOLE',
  counties: [
    {
      id: 40,
      name: 'KOLE NORTH COUNTY',
      sub_counties: [
        {
          id: 214,
          name: 'ABOKE',
          parishes: [
            {
              id: 994,
              name: 'APACH',
              villages: [
                { id: 6755, name: 'ABIL A' },
                { id: 6756, name: 'ABIL B' },
                { id: 6757, name: "ADYANG OPIRO 'A'" },
                { id: 6758, name: "ADYANG OPIRO 'B'" },
                { id: 6759, name: 'AGWATA TEK' },
                { id: 6760, name: 'AGWET' },
                { id: 6761, name: 'ALIK MOLA' },
                { id: 6762, name: 'AMUGE' },
                { id: 6763, name: 'APAT AYIKA' },
                { id: 6764, name: "AYAI 'A'" },
                { id: 6765, name: "AYAI 'B'" },
                { id: 6766, name: 'AYI DERO LONGO' },
                { id: 6767, name: 'BAR MOGO' },
                { id: 6768, name: "BAR OWAK 'A'" },
                { id: 6769, name: "BAR OWAK 'B'" },
                { id: 6770, name: 'BAR ROMO' },
                { id: 6771, name: "BAR YAO 'A'" },
                { id: 6772, name: "BAR YAO 'B'" },
                { id: 6782, name: 'BARLWALA' },
                { id: 6773, name: 'OBANGA KONYA' },
                { id: 6774, name: 'OBELOWER' },
                { id: 6775, name: 'OGAM KATI' },
                { id: 6776, name: "OKOKO 'A'" },
                { id: 6777, name: 'OKOKO SAFI' },
                { id: 6778, name: 'OLIDURU' },
                { id: 6779, name: "TELELA 'A'" },
                { id: 6780, name: "TELELA 'B'" },
                { id: 6781, name: 'WOROMITE' },
              ],
            },
            {
              id: 992,
              name: 'APURU',
              villages: [
                { id: 6728, name: 'ABONGODERO HILL' },
                { id: 57284, name: 'ABWOR' },
                { id: 6718, name: 'ACET DYEL' },
                { id: 6719, name: 'ADAG ACAE' },
                { id: 6720, name: 'AMWONYA' },
                { id: 6721, name: 'ANYANGOMIT' },
                { id: 6729, name: 'APURU ILELA' },
                { id: 6722, name: 'ARWOT PE RIBERE' },
                { id: 6723, name: 'ATEK IGWALI' },
                { id: 6724, name: 'OLEPO' },
                { id: 6725, name: 'OLI-AOLA' },
                { id: 6726, name: 'OYIMA' },
                { id: 6727, name: 'PUKICA' },
              ],
            },
            {
              id: 993,
              name: 'OPETA',
              villages: [
                { id: 6730, name: 'ABAKO' },
                { id: 6731, name: 'ACOTO' },
                { id: 6732, name: 'ADAKTARO' },
                { id: 6733, name: 'AGUNG' },
                { id: 6734, name: 'AGWENO OLWOKO WELO' },
                { id: 6735, name: 'AJAKA' },
                { id: 6736, name: 'AJUBI' },
                { id: 6737, name: 'AKAOIDEBE' },
                { id: 6738, name: 'AKUTIGUDU' },
                { id: 6739, name: 'ALEM' },
                { id: 6740, name: 'AMUKU AYET' },
                { id: 6741, name: 'BAR CIK' },
                { id: 6742, name: 'BAR DYEL' },
                { id: 6743, name: 'BAR IBATI' },
                { id: 6746, name: 'BAR NYANG' },
                { id: 6744, name: 'BAR ODIR' },
                { id: 6745, name: 'BAR ODYEK' },
                { id: 6747, name: 'BE-IOKO' },
                { id: 6752, name: 'BEDIWORO' },
                { id: 6748, name: 'MAT IMED IKITI' },
                { id: 6749, name: 'OGWANG OLO WELO' },
                { id: 6750, name: 'ONGINY HIGHLAND' },
                { id: 6751, name: "OPETA 'A'" },
                { id: 6753, name: 'ROC-PACO' },
                { id: 6754, name: 'WII-DAM' },
              ],
            },
          ],
        },
        {
          id: 217,
          name: 'ABOKE TOWN COUNCIL',
          parishes: [
            {
              id: 1011,
              name: 'AKWIRIDIDI WARD',
              villages: [
                { id: 6980, name: 'ABOKE HIGH SCH.' },
                { id: 6981, name: 'ABUNG GENGA' },
                { id: 6982, name: 'ABUTO CILO' },
                { id: 6983, name: 'ACEKE LAT' },
                { id: 6984, name: 'ACO PE CEMO IMON' },
                { id: 6985, name: "ACUNGU LYEC 'A'" },
                { id: 6986, name: "ACUNGU LYEC 'B'" },
                { id: 6987, name: 'ACWE ANYIRA' },
                { id: 6988, name: "AKAIDEBE 'A'" },
                { id: 6989, name: "AKAIDEBE 'B'" },
                { id: 6990, name: 'AMUKUGUNGU' },
                { id: 6991, name: 'AROMONYONGO' },
                { id: 6992, name: 'BAR AWENO' },
                { id: 6993, name: 'BAR ICOC' },
                { id: 7004, name: 'CUNGACIKI' },
                { id: 6994, name: 'DAGAYELA' },
                { id: 6995, name: 'IMATO' },
                { id: 6996, name: 'KWERI IKWERI' },
                { id: 6997, name: 'OCOKCAN A' },
                { id: 7005, name: 'OCOKCAN B' },
                { id: 6998, name: 'OKELOCONY' },
                { id: 6999, name: 'OYETOLEYI A' },
                { id: 7006, name: 'OYETOLEYI B' },
                { id: 7000, name: 'TE ABOLO' },
                { id: 7001, name: 'TE ILWA' },
                { id: 7002, name: 'WANG LOBO' },
                { id: 7003, name: 'WIP PIP' },
              ],
            },
            {
              id: 1012,
              name: 'AWEINGWEC WARD',
              villages: [
                { id: 7016, name: 'ABOKE H/C' },
                { id: 7007, name: 'ACEKELEYE' },
                { id: 7008, name: 'ACERO A' },
                { id: 7009, name: 'ACERO B' },
                { id: 7010, name: 'ALYAT A' },
                { id: 7011, name: 'ALYAT B' },
                { id: 7012, name: 'ARAO A' },
                { id: 7017, name: 'ARAO B' },
                { id: 7013, name: 'AWEINGWEC B' },
                { id: 7014, name: 'AWELE' },
                { id: 7015, name: 'WIRAO' },
              ],
            },
            {
              id: 1013,
              name: 'EASTERN WARD',
              villages: [
                { id: 7018, name: 'ADAG ANII' },
                { id: 7019, name: 'AMAT MIT' },
                { id: 7020, name: 'APALA' },
                { id: 7021, name: 'ATEK ADWONG' },
                { id: 7022, name: 'AWEE IBURA' },
                { id: 7023, name: 'BAR IGWERI' },
                { id: 7024, name: 'BAR LWALA' },
                { id: 7025, name: 'IWANYO IKENG' },
                { id: 7026, name: 'PACO PE TOO APE' },
                { id: 7027, name: 'TE-IPIE' },
                { id: 7028, name: 'TE-ORYANG' },
              ],
            },
            {
              id: 1010,
              name: 'OGWANGACUMA WARD',
              villages: [
                { id: 6971, name: 'ACULBANYA A' },
                { id: 6977, name: 'ACULBANYA B' },
                { id: 6972, name: 'ATEK' },
                { id: 6979, name: 'CORNER MOWLEM' },
                { id: 6973, name: 'LOKA LAGA A' },
                { id: 6978, name: 'LOKA LAGA B' },
                { id: 6974, name: 'OMOLO' },
                { id: 6975, name: 'TE-OKOLE' },
                { id: 6976, name: 'TEOWAK' },
              ],
            },
          ],
        },
        {
          id: 216,
          name: 'ALITO',
          parishes: [
            {
              id: 1004,
              name: 'ALITO',
              villages: [
                { id: 6902, name: 'AKUKI' },
                { id: 6899, name: 'ANAM OKUN' },
                { id: 6900, name: 'BAR-RWOT A' },
                { id: 6901, name: 'TE-AGUNGA' },
              ],
            },
            {
              id: 1007,
              name: 'AMUGE',
              villages: [
                { id: 6942, name: 'ABAK ALITO' },
                { id: 6943, name: 'ABAK CENTRAL' },
                { id: 6944, name: 'ABAR WINYO' },
                { id: 6935, name: 'AGOMA' },
                { id: 6936, name: 'AGWENGOTOP' },
                { id: 6937, name: 'AKWERI' },
                { id: 6938, name: 'ALYATO' },
                { id: 6934, name: 'AMUGE A' },
                { id: 6939, name: 'AMUGE B' },
                { id: 6940, name: 'ATON' },
                { id: 6945, name: 'BUNG' },
                { id: 6941, name: 'OCERE' },
                { id: 6946, name: 'PAR ANYIM' },
                { id: 6947, name: 'TEE EME' },
              ],
            },
            {
              id: 1006,
              name: 'APALA',
              villages: [
                { id: 6916, name: 'ACANKADO A' },
                { id: 6917, name: 'ACANKADO B' },
                { id: 6922, name: 'ADOKINGEI' },
                { id: 6919, name: 'ADYEL A' },
                { id: 6931, name: 'ADYEL B' },
                { id: 6920, name: 'AGWENOTONGO WELO' },
                { id: 6933, name: 'ANGULI' },
                { id: 6918, name: 'ATINGO DOGA' },
                { id: 6923, name: 'ATOP' },
                { id: 6924, name: 'BAR PII ADWONG' },
                { id: 6925, name: 'BAR PII ATIDI' },
                { id: 6926, name: 'IRAM' },
                { id: 6927, name: 'JINJA' },
                { id: 6921, name: 'LOCKEN' },
                { id: 6928, name: 'OBUBU' },
                { id: 6929, name: 'OMITO A' },
                { id: 6932, name: 'OMITO B' },
                { id: 6930, name: 'PALA  TAI' },
              ],
            },
            {
              id: 1009,
              name: 'APIIOGURO',
              villages: [
                { id: 6958, name: 'ABONGOIMAKI' },
                { id: 6970, name: 'ADAGANII' },
                { id: 6959, name: 'APIIOGURO' },
                { id: 6967, name: 'BARAKERE' },
                { id: 6968, name: 'BARNOT' },
                { id: 6965, name: 'BARONAN' },
                { id: 6966, name: 'KWOGWA' },
                { id: 6960, name: 'ONYWAL A' },
                { id: 6961, name: 'ONYWAL B' },
                { id: 6963, name: 'OWAKA' },
                { id: 6962, name: 'TEKULO' },
                { id: 6964, name: 'WELOWE' },
                { id: 6969, name: 'WOREKENI' },
              ],
            },
            {
              id: 1005,
              name: 'AYALA-OYA',
              villages: [
                { id: 6903, name: 'ABAKO  DIP' },
                { id: 6904, name: "ABAKO 'A'" },
                { id: 6905, name: 'ABEDO BER' },
                { id: 6906, name: 'ABIM CENTER' },
                { id: 6907, name: 'ABIM NORTH' },
                { id: 6908, name: 'ACANOJER' },
                { id: 6911, name: 'ALEM' },
                { id: 6912, name: 'AMON' },
                { id: 6913, name: 'BAR GIL' },
                { id: 6914, name: 'ODYEK PE ILANG' },
                { id: 6915, name: 'OGONYOLAO' },
                { id: 6909, name: 'OTIKOKIN' },
                { id: 6910, name: 'WIPIP' },
              ],
            },
            {
              id: 1008,
              name: 'BARONGIN',
              villages: [
                { id: 6954, name: 'AKAIDEBE' },
                { id: 6948, name: 'ALIT' },
                { id: 6949, name: 'APURU' },
                { id: 6950, name: 'AWURU' },
                { id: 6955, name: 'AYILE' },
                { id: 6951, name: 'GICEM' },
                { id: 6952, name: 'ONYUT CENTRE' },
                { id: 6956, name: 'ORUPU' },
                { id: 6953, name: 'OTIRI' },
                { id: 6957, name: 'TE-OPOK' },
              ],
            },
            {
              id: 1003,
              name: 'OTKWACH',
              villages: [
                { id: 6889, name: 'ABWAL' },
                { id: 6890, name: 'ADUKE' },
                { id: 6891, name: 'ALONGOWEE' },
                { id: 6892, name: 'AWAKA DUNY' },
                { id: 6894, name: 'AYITATWON' },
                { id: 6893, name: 'LWALA' },
                { id: 6895, name: 'OCOR' },
                { id: 6896, name: 'OLIPA' },
                { id: 6897, name: 'TE-LELA' },
                { id: 6898, name: 'TE-OWAK' },
              ],
            },
          ],
        },
        {
          id: 1941,
          name: 'ALITO TOWN COUNCIL',
          parishes: [
            {
              id: 9169,
              name: 'AKOR WARD',
              villages: [
                { id: 57210, name: 'ABOLONENO' },
                { id: 57258, name: 'ABUNG GENGA' },
                { id: 57317, name: 'ACANOWEE' },
                { id: 58159, name: 'AMINTATO A' },
                { id: 58160, name: 'AMINTATO B' },
                { id: 58341, name: 'ANYONOMAC' },
                { id: 58718, name: 'AWATNGWENINO' },
                { id: 58909, name: 'BAR APWO' },
                { id: 69304, name: 'OTKWAC AMALO' },
                { id: 70675, name: 'TEGWENG' },
              ],
            },
            {
              id: 9274,
              name: 'BUA-ATYENO WARD',
              villages: [
                { id: 57220, name: 'ABONGO COO' },
                { id: 58026, name: 'ALITO TRADING CENTRE' },
                { id: 58412, name: 'APIT PE DAA' },
                { id: 58987, name: 'BARONGIN' },
                { id: 61261, name: 'ENTEBBE' },
                { id: 61307, name: 'FOREST RESERVE' },
                { id: 66238, name: 'MI WAA ANYIM' },
                { id: 68475, name: 'ODOKAMIDO' },
                { id: 68891, name: 'OLYET' },
                { id: 70620, name: 'TE-DAM' },
              ],
            },
            {
              id: 10220,
              name: 'OWANI ADILO WARD',
              villages: [
                { id: 57265, name: 'ABURA' },
                { id: 57310, name: 'ACANDYEL' },
                { id: 57519, name: 'ADYELOMWODO' },
                { id: 58004, name: 'ALILO' },
                { id: 58245, name: 'ANENOBER A' },
                { id: 58246, name: 'ANENOBER B' },
                { id: 58924, name: 'BAR RWOT B' },
                { id: 69335, name: 'OTYANG' },
                { id: 70653, name: 'TE-YAO' },
                { id: 71136, name: 'WII ADU' },
              ],
            },
            {
              id: 10312,
              name: 'TEKIDI WARD',
              villages: [
                { id: 57637, name: 'AJALIGADO' },
                { id: 58242, name: 'ANEKAPIRI' },
                { id: 58388, name: 'APENA OONY' },
                { id: 58922, name: 'BAR OYELE' },
                { id: 61143, name: 'DOG GUDU' },
                { id: 68522, name: 'ODURE' },
                { id: 70612, name: 'TE KIDI' },
                { id: 70613, name: 'TE KWORO A' },
                { id: 70631, name: 'TE-KWORO B' },
                { id: 71131, name: 'WIGWENG' },
              ],
            },
          ],
        },
        {
          id: 215,
          name: 'OKWERODOT',
          parishes: [
            {
              id: 995,
              name: 'ABONG JOK',
              villages: [
                { id: 6792, name: 'ABOLO NENO' },
                { id: 6788, name: 'ABONGO-PAPA' },
                { id: 6783, name: 'ACOO TEDO A' },
                { id: 6784, name: 'ACOO TEDO B' },
                { id: 6789, name: 'ADAG-ANYWAR' },
                { id: 6785, name: 'ALAKE' },
                { id: 6787, name: 'APII' },
                { id: 6791, name: 'APIT TYE IPOLO' },
                { id: 6790, name: 'OGWEO A' },
                { id: 68605, name: 'OGWEO B' },
                { id: 6786, name: 'WORO MITE' },
              ],
            },
            { id: 9129, name: 'ABONGO JOK', villages: [] },
            {
              id: 996,
              name: 'ADEL-LOGO',
              villages: [
                { id: 6793, name: "ABUKA 'A'" },
                { id: 6794, name: "ABUKA 'B'" },
                { id: 6804, name: 'ACAKE-TE-KULU' },
                { id: 57652, name: 'AJIDA BORDER' },
                { id: 6795, name: 'AJOK AWELO' },
                { id: 6796, name: 'ALEGE' },
                { id: 6797, name: "AWOBE ODE 'A'" },
                { id: 6798, name: "AWOBE ODE 'B'" },
                { id: 6799, name: 'BAR OPIRO' },
                { id: 6800, name: 'BAR PUNU' },
                { id: 6805, name: 'BARILEC' },
                { id: 6807, name: 'ETENG' },
                { id: 6806, name: 'LAII' },
                { id: 6801, name: 'LELA MUNU' },
                { id: 6802, name: 'ODONG PE YAMO' },
                { id: 6803, name: 'TE OKUTO' },
                { id: 6808, name: 'TE-OCOL' },
              ],
            },
            {
              id: 1002,
              name: 'AYAMO',
              villages: [
                { id: 6879, name: 'ALEKOLIL' },
                { id: 6876, name: 'AROADYANG' },
                { id: 6881, name: 'AYAMO A' },
                { id: 6877, name: 'AYAMO B' },
                { id: 6875, name: 'BAR ODWONG TC' },
                { id: 6880, name: 'BARONGER' },
                { id: 6878, name: 'GWOK WI ATINIWAYA' },
                { id: 6884, name: 'LELA OMIA' },
                { id: 6882, name: 'OBANGA OLEKA' },
                { id: 6885, name: 'OKUNAYAI' },
                { id: 6886, name: 'ORUNI A' },
                { id: 6883, name: 'ORUNI B' },
                { id: 6887, name: 'TELELA' },
                { id: 6888, name: 'WITIM' },
              ],
            },
            {
              id: 998,
              name: 'AYARA',
              villages: [
                { id: 6825, name: 'ABOLOWO' },
                { id: 6821, name: 'ADAG ANII' },
                { id: 6822, name: 'AJUK A' },
                { id: 6823, name: 'AJUK B' },
                { id: 6820, name: 'AYARA CENTRAL' },
                { id: 6826, name: 'AYIA CAI' },
                { id: 6827, name: 'BAR ABOLO' },
                { id: 6828, name: "BAR ODWONG 'A'" },
                { id: 6829, name: "BAR ODWONG 'B'" },
                { id: 6830, name: 'BAR-OPENO' },
                { id: 6831, name: 'LWALA' },
                { id: 6832, name: 'ORIB CING' },
                { id: 6824, name: 'TE ITEK' },
              ],
            },
            {
              id: 999,
              name: 'LELAKOT',
              villages: [
                { id: 6833, name: 'ADAK ATARO' },
                { id: 6834, name: 'ADENGAWIC' },
                { id: 6835, name: "ADILI 'A'" },
                { id: 6836, name: "ADILI 'B'" },
                { id: 57927, name: 'ALANGA CONER' },
                { id: 6838, name: 'ALONGO YITE BIT' },
                { id: 6839, name: 'ANENO BER' },
                { id: 6840, name: 'AWIRO' },
                { id: 6841, name: 'BARADUU' },
                { id: 6842, name: 'DULA A' },
                { id: 6845, name: 'DULA B' },
                { id: 6837, name: 'LELA OOLA' },
                { id: 6843, name: 'LELAKOT' },
                { id: 6846, name: 'LELAOCIKA' },
                { id: 6844, name: 'OLENG OBIR' },
              ],
            },
            {
              id: 1001,
              name: 'LWALA',
              villages: [
                { id: 6864, name: 'ACANMWOL' },
                { id: 6862, name: 'AKENA' },
                { id: 6872, name: 'AKENA B' },
                { id: 6857, name: 'ALYEC A' },
                { id: 6866, name: 'ALYEC B' },
                { id: 6874, name: 'AMIA BIL' },
                { id: 6860, name: 'AMOLI' },
                { id: 6863, name: 'AWILI' },
                { id: 6858, name: 'AYILE A' },
                { id: 6867, name: 'AYILE B' },
                { id: 6873, name: 'BAR ODYEK' },
                { id: 6865, name: 'BAR-LONYO' },
                { id: 6861, name: 'LWALA A' },
                { id: 6870, name: 'LWALA B' },
                { id: 6871, name: 'OGABI' },
                { id: 6859, name: 'OMEROGWENO A' },
                { id: 6868, name: 'OMEROGWENO B' },
                { id: 6856, name: 'TE-OPOK A' },
                { id: 70648, name: 'TE-OPOK B' },
                { id: 6869, name: 'WORE KENI' },
              ],
            },
            {
              id: 1000,
              name: 'OBUTU',
              villages: [
                { id: 6852, name: 'ABOLOOWO' },
                { id: 6851, name: 'ALANGO' },
                { id: 6847, name: 'BAR IBULE A' },
                { id: 6848, name: 'BAR IBULE B' },
                { id: 6853, name: 'BAR IBULE CENTRE' },
                { id: 6850, name: 'OBUTU CENTRE' },
                { id: 6854, name: 'OBUTU CORNER' },
                { id: 6855, name: 'TE OBIA B' },
                { id: 6849, name: 'TE-OBIA A' },
              ],
            },
            {
              id: 997,
              name: 'OKWERODOT',
              villages: [
                { id: 6809, name: 'ABONGO JOK' },
                { id: 6810, name: 'ACAEOGIK' },
                { id: 6812, name: 'ACO OTEDO' },
                { id: 6811, name: 'ADAG ANII' },
                { id: 6816, name: 'ADOG-MON-MIO' },
                { id: 6814, name: 'ADYEL ODEO' },
                { id: 6813, name: 'AGOGA' },
                { id: 6818, name: 'KAKIRA' },
                { id: 6819, name: 'ONGURA' },
                { id: 6817, name: 'TE-OPOK' },
                { id: 6815, name: 'TEYAO' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 39,
      name: 'KOLE SOUTH COUNTY',
      sub_counties: [
        {
          id: 209,
          name: 'AKALO',
          parishes: [
            {
              id: 970,
              name: 'ABELI',
              villages: [
                { id: 6529, name: 'ACUNG APENYI' },
                { id: 6530, name: 'ALWALA' },
                { id: 6531, name: 'APUTI' },
                { id: 6532, name: 'AWELO' },
                { id: 6533, name: 'AWIE OLAL' },
                { id: 6534, name: 'BUNG ABUNGA' },
                { id: 6535, name: 'BUNG ODYEK' },
                { id: 6536, name: 'IREDA' },
                { id: 6537, name: 'LORO' },
                { id: 6538, name: 'ODEO' },
                { id: 6539, name: 'OTUTA' },
              ],
            },
            {
              id: 971,
              name: 'BAR-AKALO',
              villages: [
                { id: 6540, name: 'ABIBUTI' },
                { id: 6541, name: 'ABOLOKOMA' },
                { id: 6542, name: 'ADAKINGO' },
                { id: 6543, name: 'ADWILA' },
                { id: 6544, name: 'ADWIR' },
                { id: 6545, name: 'AGERINONO' },
                { id: 6547, name: 'AMOMTOO' },
                { id: 6548, name: 'APARANGO' },
                { id: 6549, name: 'BAROWO' },
                { id: 6546, name: 'OJUKILWALA' },
                { id: 6550, name: 'OROC' },
              ],
            },
          ],
        },
        {
          id: 1938,
          name: 'AKALO TOWN COUNCIL',
          parishes: [
            {
              id: 9456,
              name: 'EASTERN A WARD',
              villages: [
                { id: 57320, name: 'ACANPII' },
                { id: 57667, name: 'AJOK OWEO' },
                { id: 57863, name: 'AKURIDEN' },
                { id: 57866, name: 'AKURILUBA' },
                { id: 58908, name: 'BAR ALIRO' },
                { id: 58915, name: 'BAR ILWA' },
                { id: 61566, name: 'IGEL' },
                { id: 69128, name: 'OPIRA' },
                { id: 69366, name: 'OWEO' },
                { id: 71168, name: 'WITIM' },
              ],
            },
            {
              id: 9457,
              name: 'EASTERN B WARD',
              villages: [
                { id: 57146, name: 'ABEDIWORO' },
                { id: 58001, name: 'ALIK IMALO' },
                { id: 58002, name: 'ALIK IPING' },
                { id: 58638, name: 'ATILEM' },
                { id: 58921, name: 'BAR OPOK' },
                { id: 68400, name: 'OCAN OYERE' },
                { id: 69357, name: 'OWANGODYANG A' },
                { id: 69358, name: 'OWANGODYANG B' },
              ],
            },
            {
              id: 10343,
              name: 'WESTERN A WARD',
              villages: [
                { id: 57514, name: 'ADYEDA' },
                { id: 57857, name: 'AKURA' },
                { id: 58022, name: 'ALIRI' },
                { id: 58536, name: 'AROBI' },
                { id: 58913, name: 'BAR IBU' },
                { id: 58938, name: 'BARAJET' },
                { id: 58955, name: 'BARDOK OCULI' },
                { id: 68337, name: 'OBELA' },
                { id: 68730, name: 'OKUT' },
                { id: 68776, name: 'OLAYA' },
              ],
            },
            {
              id: 10344,
              name: 'WESTERN B WARD',
              villages: [
                { id: 57398, name: 'ADAGANI' },
                { id: 57665, name: 'AJODYATA' },
                { id: 57710, name: 'AKAIDEBE' },
                { id: 57774, name: 'AKEK' },
                { id: 61121, name: 'DIIBADI' },
                { id: 69333, name: 'OTWON IMALO' },
                { id: 69334, name: 'OTWON PINY' },
                { id: 69354, name: 'OWALO IMALO' },
                { id: 69355, name: 'OWALO IPINY' },
                { id: 70655, name: 'TEAMAGA' },
              ],
            },
          ],
        },
        {
          id: 210,
          name: 'AYER',
          parishes: [
            {
              id: 972,
              name: 'ABUR',
              villages: [
                { id: 6551, name: 'ABIROPOO' },
                { id: 6552, name: 'ABUGE' },
                { id: 6559, name: 'ABUR WARD' },
                { id: 6553, name: 'ADWIL' },
                { id: 6558, name: 'AERONYERO' },
                { id: 6554, name: 'AGWEA' },
                { id: 6555, name: 'ANYWAL' },
                { id: 6556, name: 'APURIPARO' },
                { id: 6557, name: 'AWEKI' },
              ],
            },
            {
              id: 973,
              name: 'ALEMI',
              villages: [
                { id: 6560, name: 'ABAKO' },
                { id: 6561, name: 'ABILONINO' },
                { id: 6565, name: 'ABUKU A' },
                { id: 6566, name: 'ABUKU B' },
                { id: 6562, name: 'ALEGE' },
                { id: 6569, name: 'ATEK B' },
                { id: 6563, name: 'BAR-ODUGU' },
                { id: 6564, name: 'BAR-OPUU' },
                { id: 6567, name: 'OBENY' },
                { id: 6568, name: 'TE KIDI' },
              ],
            },
            {
              id: 974,
              name: 'ILERA',
              villages: [
                { id: 6570, name: 'AKOO' },
                { id: 6571, name: 'APALA' },
                { id: 6572, name: 'BAROBER' },
                { id: 6573, name: 'BUNG' },
                { id: 6574, name: 'KONA' },
                { id: 6575, name: 'LELA' },
                { id: 6576, name: 'OBUTU' },
                { id: 6577, name: 'OKABO' },
                { id: 6578, name: 'OMUNGO' },
                { id: 6579, name: 'OTANGULA' },
                { id: 6580, name: 'WIGWENG' },
              ],
            },
            {
              id: 977,
              name: 'LWALA',
              villages: [
                { id: 6597, name: 'ABELI' },
                { id: 6598, name: 'ABILONINO' },
                { id: 6601, name: 'AKWANYCINGI' },
                { id: 6602, name: 'AKWOO' },
                { id: 6599, name: 'ALUBI' },
                { id: 6600, name: 'ANOTO-CAO' },
                { id: 6604, name: 'APARANGO' },
                { id: 6606, name: 'ATIMONING' },
                { id: 6603, name: 'BARDYEL' },
                { id: 6605, name: 'IJUMARA' },
                { id: 6607, name: 'NYAMKERE' },
                { id: 6608, name: 'RAO' },
                { id: 6609, name: 'TE-OPOK' },
              ],
            },
            {
              id: 976,
              name: 'OKWOR',
              villages: [
                { id: 6594, name: 'ADITAURO' },
                { id: 6595, name: 'ALIP' },
                { id: 6596, name: "ATEK 'A'" },
              ],
            },
            {
              id: 975,
              name: 'TELELA',
              villages: [
                { id: 6581, name: 'ABOLONYERO' },
                { id: 6582, name: 'AMOLA' },
                { id: 6583, name: 'AMWA' },
                { id: 6584, name: 'APALA' },
                { id: 6585, name: 'ATEK' },
                { id: 6592, name: 'BARAMINDYANG WARD' },
                { id: 6586, name: 'BUNG' },
                { id: 6587, name: 'KULUYAGO' },
                { id: 6588, name: 'LEYE' },
                { id: 6589, name: 'OBELE' },
                { id: 6593, name: 'OKAR' },
                { id: 6590, name: 'OYETOLEYI' },
                { id: 6591, name: 'PWD NO.2' },
              ],
            },
          ],
        },
        { id: 1955, name: 'BALA', parishes: [] },
        {
          id: 213,
          name: 'BALA TOWN COUNCIL',
          parishes: [
            {
              id: 988,
              name: 'EASTERN A WARD',
              villages: [
                { id: 6690, name: 'ACATO BUNG' },
                { id: 6686, name: 'ANYONGO PIDA' },
                { id: 6681, name: 'ANYONGO TUPINY' },
                { id: 6682, name: 'ATINAACEL' },
                { id: 6683, name: 'ONOO' },
                { id: 6687, name: 'OPUGU' },
                { id: 6688, name: 'TE ABOLO' },
                { id: 6689, name: 'TEORYANG A' },
                { id: 6684, name: 'TEORYANG B' },
                { id: 6685, name: 'TETUGU' },
              ],
            },
            {
              id: 989,
              name: 'EASTERN B WARD',
              villages: [
                { id: 6691, name: 'ABIECE' },
                { id: 6693, name: 'ABONGO RWOT' },
                { id: 6692, name: 'ACATO GUDU' },
                { id: 6694, name: 'ATOKIMEDI' },
                { id: 6696, name: 'BARDYANG' },
                { id: 6697, name: 'CENG' },
                { id: 6698, name: 'DOG TANGI' },
                { id: 6695, name: 'LOOYOCENG' },
                { id: 6700, name: 'WICERE' },
                { id: 6699, name: 'WIGWENG B' },
              ],
            },
            {
              id: 990,
              name: 'WESTERN A WARD',
              villages: [
                { id: 6701, name: 'ABONGWEN' },
                { id: 6703, name: 'AGWENG A' },
                { id: 6706, name: 'AUMIDANI' },
                { id: 6707, name: 'CANOMONANINO' },
                { id: 6702, name: 'LOBO LOBO' },
                { id: 6709, name: 'OLAI' },
                { id: 6710, name: 'OLIL' },
                { id: 6704, name: 'OWITI' },
                { id: 6705, name: 'TE CAMBIA A' },
                { id: 6708, name: 'TE KEO' },
              ],
            },
            {
              id: 991,
              name: 'WESTERN B WARD',
              villages: [
                { id: 6711, name: 'AKURI OKOK' },
                { id: 6713, name: 'APONGIMALO' },
                { id: 6714, name: 'BAR ADURI' },
                { id: 6715, name: 'BAR OPU' },
                { id: 6712, name: 'DOG GUDO' },
                { id: 68397, name: 'OCAI BUNGTE' },
                { id: 70658, name: 'TECAMBIA B' },
                { id: 6717, name: 'TEIBULE' },
                { id: 6716, name: 'WIGWENG A' },
              ],
            },
          ],
        },
        {
          id: 211,
          name: 'BALLA',
          parishes: [
            {
              id: 979,
              name: 'AGEGE',
              villages: [
                { id: 6620, name: 'ABILONINO' },
                { id: 6621, name: 'AGEGELELA' },
                { id: 6622, name: 'AGWEI' },
                { id: 6623, name: 'AKECA' },
                { id: 6624, name: 'ALEM' },
                { id: 6625, name: 'APELO' },
                { id: 6626, name: 'AROMONGA' },
                { id: 6627, name: 'BARMOLA' },
                { id: 6628, name: 'ORWOMA' },
              ],
            },
            {
              id: 984,
              name: 'AMOILELA',
              villages: [
                { id: 6649, name: 'ABALOKARA' },
                { id: 6650, name: 'ADIM' },
                { id: 6651, name: 'AMII' },
                { id: 6652, name: 'AMOILELA' },
                { id: 6653, name: 'DOG DAM' },
                { id: 6654, name: 'DOGIKORE' },
                { id: 6655, name: 'OCODONYOR' },
              ],
            },
            {
              id: 985,
              name: 'ANGIC',
              villages: [
                { id: 6658, name: 'ADWONGOTINGO' },
                { id: 6659, name: 'AKWOO' },
                { id: 6660, name: 'ALEBERE' },
                { id: 6661, name: 'ALELEBANYA' },
                { id: 6656, name: 'ALELEBANYA - WIGWENG' },
                { id: 6662, name: 'ANGIC' },
                { id: 6657, name: 'ANGIC UPPER CENTRE' },
                { id: 58678, name: 'ATWOL' },
                { id: 6664, name: 'OLIMO' },
                { id: 6663, name: 'TEOPOK' },
              ],
            },
            {
              id: 981,
              name: 'AUMI',
              villages: [
                { id: 6631, name: 'ABANGOLAM' },
                { id: 6632, name: 'ADAGWOO' },
                { id: 6633, name: 'ADU ODYEK' },
                { id: 6634, name: 'APAK' },
                { id: 6635, name: 'ATINGTWO' },
                { id: 6636, name: 'IJUMARA' },
                { id: 6637, name: 'INGAINGA' },
                { id: 6638, name: 'OGEDI' },
              ],
            },
            {
              id: 980,
              name: 'BALLA',
              villages: [
                { id: 6630, name: 'ANYONGO CENTRAL' },
                { id: 6629, name: 'ANYONGO-OGENGO' },
              ],
            },
            {
              id: 978,
              name: 'OMOLADYANG',
              villages: [
                { id: 6610, name: 'ACANPANY' },
                { id: 6613, name: 'APARANGO' },
                { id: 6612, name: 'APARANGWEN' },
                { id: 6614, name: 'APONGIMALO' },
                { id: 6615, name: 'ATIRA' },
                { id: 6616, name: 'AYATNINO' },
                { id: 6617, name: 'OKELLOKIZA' },
                { id: 6618, name: 'OMATOLONGO' },
                { id: 6611, name: 'OMOLODYANG DANI' },
                { id: 6619, name: 'TEYAO' },
              ],
            },
            {
              id: 982,
              name: 'OMUGE',
              villages: [
                { id: 6639, name: 'ADWILA' },
                { id: 6640, name: 'ARWOT LANGO' },
                { id: 6641, name: 'BAR' },
                { id: 6642, name: 'BUNG' },
                { id: 6643, name: 'EDUKA' },
                { id: 6644, name: 'ILERA' },
                { id: 6645, name: 'TEOBIA' },
              ],
            },
            {
              id: 983,
              name: 'OMWARA',
              villages: [
                { id: 6646, name: 'ANYANGACOTO' },
                { id: 6647, name: 'AWINYWOO' },
                { id: 6648, name: 'ONYANY' },
              ],
            },
          ],
        },
        {
          id: 212,
          name: 'KOLE TOWN COUNCIL',
          parishes: [
            {
              id: 986,
              name: 'EASTERN WARD',
              villages: [
                { id: 6665, name: 'AKAIDEBE' },
                { id: 6666, name: 'ATEK' },
                { id: 6668, name: 'AYER' },
                { id: 6671, name: "AYITODUNY 'B'" },
                { id: 6669, name: 'BUNG' },
                { id: 6670, name: 'OUKA' },
                { id: 6672, name: 'PWD NO.3' },
                { id: 6667, name: 'WIGWENG' },
              ],
            },
            {
              id: 987,
              name: 'WESTERN WARD',
              villages: [
                { id: 6675, name: 'ALEGE' },
                { id: 6674, name: 'ATIGOMER' },
                { id: 6676, name: "AYITODUNY 'A'" },
                { id: 6678, name: 'BANYA' },
                { id: 6680, name: 'K.C.C' },
                { id: 6679, name: 'OMUKU' },
                { id: 6677, name: 'TE-AKWAR' },
                { id: 6673, name: 'TEATIT' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
