import { District } from '../types';

export default <District>{
  id: 40,
  name: 'KWANIA',
  counties: [
    {
      id: 85,
      name: 'KWANIA COUNTY',
      sub_counties: [
        {
          id: 529,
          name: 'ABONGOMOLA',
          parishes: [
            {
              id: 2467,
              name: 'ABANY',
              villages: [
                { id: 16342, name: 'ABANY-IMALO' },
                { id: 16343, name: 'ABANYIPINY' },
                { id: 16344, name: 'ANGINY' },
                { id: 16345, name: 'ANGULE A' },
                { id: 16349, name: 'ANGULE B' },
                { id: 16346, name: 'AWEI' },
                { id: 16347, name: 'OLAIPALI' },
                { id: 16348, name: 'OTORONGOLE' },
              ],
            },
            {
              id: 2466,
              name: 'ACUNGI',
              villages: [
                { id: 16329, name: 'ABALI' },
                { id: 16330, name: "ABONGORWOT 'A'" },
                { id: 16331, name: "ABONGORWOT 'B'" },
                { id: 16332, name: "ACUNGI 'A'" },
                { id: 16333, name: "ACUNGI 'B'" },
                { id: 16334, name: 'AMULO A' },
                { id: 16338, name: 'AMULO B' },
                { id: 16335, name: 'BAR ACUT' },
                { id: 16336, name: "BARACER 'A'" },
                { id: 16337, name: "BARACER 'B'" },
                { id: 16339, name: 'OMEO' },
                { id: 16340, name: 'OYERE A' },
                { id: 16341, name: 'OYERE B' },
              ],
            },
            {
              id: 2468,
              name: 'AMORIGOGA',
              villages: [
                { id: 16350, name: 'AGOLO-OWELO A' },
                { id: 16356, name: 'AGOLOWELO' },
                { id: 16351, name: 'AMORIGOGA A' },
                { id: 16352, name: 'AMORIGOGA B' },
                { id: 16353, name: 'ATONGA' },
                { id: 16357, name: 'ATONGA B' },
                { id: 16355, name: 'AYIKI  B' },
                { id: 16354, name: 'AYIKI A' },
                { id: 16358, name: 'AYIKI C' },
              ],
            },
            {
              id: 10159,
              name: 'OGWOK',
              villages: [
                { id: 57147, name: 'ABEDOBER' },
                { id: 68413, name: 'OCERICANI' },
                { id: 68610, name: 'OGWOK A' },
                { id: 68611, name: 'OGWOK B' },
                { id: 68668, name: 'OKEC A' },
                { id: 68669, name: 'OKEC B' },
                { id: 68791, name: 'OLENGERE  B' },
                { id: 68792, name: 'OLENGERE A' },
              ],
            },
            {
              id: 2469,
              name: 'TEIORO',
              villages: [
                { id: 16360, name: 'ACUR' },
                { id: 16361, name: 'APARI A' },
                { id: 16359, name: 'APARI B' },
                { id: 16362, name: 'ARWOT-ODONG' },
                { id: 16363, name: 'ATUGU' },
                { id: 16364, name: 'AWANGA' },
                { id: 16365, name: 'BUNG' },
                { id: 16366, name: 'ONYONG' },
              ],
            },
          ],
        },
        {
          id: 525,
          name: 'ADUKU',
          parishes: [
            {
              id: 2453,
              name: 'ABOKO',
              villages: [
                { id: 16196, name: 'ACANDEK' },
                { id: 16197, name: 'AGONG' },
                { id: 16198, name: 'ALEBE' },
                { id: 16199, name: 'ALYET' },
                { id: 16200, name: "AMIA 'A'" },
                { id: 16201, name: "AMIA 'B'" },
                { id: 16202, name: 'AMULI' },
                { id: 16203, name: 'AORA' },
                { id: 16204, name: 'ARUMA' },
                { id: 16205, name: 'ODEO-BUNG' },
                { id: 16206, name: 'ODEO-CORNER' },
                { id: 16207, name: 'OLANYOTAI' },
                { id: 16208, name: 'OLIL' },
                { id: 16209, name: 'WIGWENG' },
              ],
            },
            {
              id: 2450,
              name: 'ADYEDA',
              villages: [
                { id: 16164, name: 'ADYEDA IMALO' },
                { id: 16165, name: 'ANYWAL' },
                { id: 16166, name: "APOR- WEGI 'A'" },
                { id: 16167, name: "APOR-WEGI 'B'" },
                { id: 16168, name: 'ATAKARA' },
              ],
            },
            {
              id: 2451,
              name: 'ALIRA',
              villages: [
                { id: 16169, name: "AKOT 'A'" },
                { id: 16170, name: "AKOT 'B'" },
                { id: 16171, name: "AKWODONG 'A'" },
                { id: 16172, name: "AKWODONG 'B'" },
                { id: 16173, name: 'AKWOYO' },
                { id: 16174, name: "ALIRA 'A'" },
                { id: 16175, name: "ALIRA 'B'" },
                { id: 16176, name: "BUNG 'A'" },
                { id: 16177, name: "BUNG 'B" },
                { id: 16178, name: "BUNG 'C'" },
                { id: 16179, name: "BUNG 'D'" },
                { id: 16180, name: 'EGUM' },
                { id: 16181, name: 'ELING' },
                { id: 16182, name: 'OGILI' },
                { id: 16183, name: 'OLEKE' },
              ],
            },
            {
              id: 2454,
              name: 'APIRE',
              villages: [
                { id: 16210, name: 'ACUT' },
                { id: 16211, name: 'ALONG-OMULA' },
                { id: 16212, name: 'ANGOLENYANG' },
                { id: 16213, name: 'APIRE A' },
                { id: 16214, name: 'APIRE CENTRE' },
                { id: 16215, name: 'BUNG- APIRE' },
                { id: 16216, name: 'GWERI' },
                { id: 16217, name: 'INYER' },
                { id: 16218, name: 'OCWALI' },
                { id: 16219, name: 'OKWAINYWAGI' },
                { id: 16220, name: 'TE-OPOK' },
              ],
            },
            {
              id: 2452,
              name: 'ONGOCENG',
              villages: [
                { id: 16184, name: 'ABALOKWERI' },
                { id: 16185, name: 'ABEIBUTI' },
                { id: 16186, name: 'ABONGONYEKO' },
                { id: 16187, name: 'ACULA' },
                { id: 16188, name: 'AKUNI' },
                { id: 16189, name: 'AKWON' },
                { id: 16190, name: 'ALYELI' },
                { id: 16191, name: 'AMWAK' },
                { id: 16192, name: 'ANGINYI' },
                { id: 16193, name: 'AWANGA' },
                { id: 16194, name: 'OGUNGU' },
                { id: 16195, name: 'OLWER' },
              ],
            },
          ],
        },
        {
          id: 530,
          name: 'ADUKU TOWN COUNCIL',
          parishes: [
            {
              id: 2471,
              name: 'IKWERA WARD',
              villages: [
                { id: 16375, name: 'AKAIDEBE' },
                { id: 16376, name: 'IGURA' },
                { id: 16377, name: 'IKWERA' },
                { id: 16378, name: "OLAMI 'A'" },
                { id: 16379, name: "OLAMI 'B'" },
              ],
            },
            {
              id: 2470,
              name: 'TEDUKA WARD',
              villages: [
                { id: 16367, name: 'ADUKU S.S.S.' },
                { id: 16373, name: 'ADUKU TOWNSHIP' },
                { id: 16368, name: 'ADYEDA  T.C' },
                { id: 16369, name: 'ALANY' },
                { id: 16370, name: 'BUNG TEDUKA' },
                { id: 16371, name: 'OGOBI' },
                { id: 16372, name: 'OT-OGOLE' },
                { id: 16374, name: 'UCC ADUKU' },
              ],
            },
          ],
        },
        {
          id: 1937,
          name: 'AKALI',
          parishes: [
            {
              id: 9135,
              name: 'ABWONG',
              villages: [
                { id: 57282, name: 'ABWONG-DANI' },
                { id: 58195, name: 'AMUDA B' },
                { id: 58196, name: 'AMUDA C' },
                { id: 58309, name: 'ANINO-CEK' },
                { id: 58639, name: 'ATIMNADI' },
                { id: 58933, name: 'BAR-ONGER' },
              ],
            },
            {
              id: 9147,
              name: 'ADEROLONGO',
              villages: [
                { id: 57431, name: 'ADEROLONGO' },
                { id: 57542, name: 'AGERI' },
                { id: 57719, name: 'AKALI' },
                { id: 61552, name: 'ICEKELEYE' },
                { id: 68530, name: 'ODYEK-PE A' },
                { id: 68531, name: 'ODYEK-PE B' },
                { id: 69294, name: 'OTENGORO A' },
                { id: 69295, name: 'OTENGORO B' },
              ],
            },
            {
              id: 9158,
              name: 'AGWA',
              villages: [
                { id: 57589, name: 'AGWA' },
                { id: 58194, name: 'AMUDA A' },
                { id: 58395, name: 'APIDYANG A' },
                { id: 58396, name: 'APIDYANG B' },
                { id: 58658, name: 'ATONGA ESTATE' },
                { id: 58931, name: 'BAR-OCAO' },
                { id: 68828, name: 'OLIO' },
                { id: 68942, name: "OMENYA 'A'" },
                { id: 68943, name: "OMENYA 'B'" },
              ],
            },
            {
              id: 9164,
              name: 'AKALI',
              villages: [
                { id: 57400, name: 'ADAGANI' },
                { id: 58132, name: 'AMIDO A' },
                { id: 58133, name: 'AMIDO B' },
                { id: 68482, name: 'ODOLOBOK' },
                { id: 70702, name: 'TELELA CENTRAL' },
                { id: 70703, name: 'TELELA EAST' },
                { id: 70704, name: 'TELELA WEST' },
              ],
            },
            {
              id: 9177,
              name: 'ALEL',
              villages: [
                { id: 57929, name: 'ALANGO' },
                { id: 57945, name: 'ALEL' },
                { id: 58021, name: 'ALIRA' },
                { id: 61646, name: 'INYON' },
                { id: 68321, name: 'OBANGANGEO' },
                { id: 68574, name: 'OGORA' },
              ],
            },
          ],
        },
        {
          id: 1952,
          name: 'ATONGTIDI',
          parishes: [
            {
              id: 9137,
              name: 'ACENLWORO',
              villages: [
                { id: 57419, name: 'ADAKINGO' },
                { id: 58446, name: 'APWORI' },
                { id: 58829, name: 'AYIRA' },
                { id: 58934, name: 'BAR-ORYANG' },
                { id: 64246, name: 'KOMALER' },
                { id: 69007, name: 'OMULE' },
                { id: 69138, name: 'OPOKWELE' },
                { id: 69401, name: 'OYIKOWANGE' },
                { id: 71135, name: 'WIGWENG B' },
              ],
            },
            {
              id: 9154,
              name: 'AGOLOWELO',
              villages: [
                { id: 57270, name: 'ABUTI' },
                { id: 57402, name: 'ADAGANI' },
                { id: 57504, name: 'ADWONG OWIRI' },
                { id: 57555, name: 'AGOLOWELO' },
                { id: 60175, name: 'BUNGKULE' },
                { id: 68345, name: 'OBILAKEC' },
              ],
            },
            {
              id: 9233,
              name: 'ATONGTIDI',
              villages: [
                { id: 57305, name: 'ACANANUMU' },
                { id: 57709, name: 'AKAIDEBE' },
                { id: 58973, name: 'BARMOGO' },
                { id: 58974, name: 'BAROBIA' },
                { id: 58994, name: 'BAROPOK' },
                { id: 70627, name: 'TE-ILWA A' },
                { id: 70628, name: 'TE-ILWA B' },
              ],
            },
            {
              id: 9482,
              name: 'GOI',
              villages: [
                { id: 57119, name: 'ABALI' },
                { id: 57823, name: 'AKONGOMIT' },
                { id: 57881, name: 'AKWAIWANGA' },
                { id: 58722, name: 'AWEI' },
                { id: 58804, name: 'AYAT' },
                { id: 61392, name: 'GOI' },
                { id: 70599, name: 'TANGALA' },
                { id: 71134, name: 'WIGWENG A' },
              ],
            },
            {
              id: 9510,
              name: 'IWAL',
              villages: [
                { id: 57634, name: 'AJALI' },
                { id: 57951, name: 'ALEMO' },
                { id: 58348, name: 'ANYWARGIKI' },
                { id: 58808, name: 'AYEI' },
                { id: 58993, name: 'BAROPOBO' },
                { id: 61713, name: 'IWAL' },
                { id: 70679, name: 'TEIBIRA' },
              ],
            },
            {
              id: 10347,
              name: 'WIGWENG',
              villages: [
                { id: 57576, name: 'AGULUNONO' },
                { id: 58223, name: 'AMWANGA A' },
                { id: 58224, name: 'AMWANGA B' },
                { id: 58233, name: 'ANAMORINGO' },
                { id: 58449, name: 'APYELAMOT' },
                { id: 58937, name: 'BARADU' },
                { id: 71126, name: 'WIGWENG' },
              ],
            },
          ],
        },
        {
          id: 1954,
          name: 'AYABI',
          parishes: [
            {
              id: 9133,
              name: 'ABULI',
              villages: [
                { id: 57254, name: 'ABULI ABULA' },
                { id: 57900, name: 'AKWO-AGWE' },
                { id: 58169, name: 'AMOMPUT' },
                { id: 58295, name: 'ANGUKAI' },
                { id: 58962, name: 'BARIRWE' },
                { id: 68443, name: 'ODALOWANG' },
                { id: 68626, name: 'OJENGERE' },
                { id: 68755, name: 'OKWOAGWE' },
                { id: 69032, name: "OMWONO 'B'" },
                { id: 69033, name: "OMWONO'A'" },
                { id: 69283, name: 'OTALIMALO' },
              ],
            },
            {
              id: 9141,
              name: 'ACULAWIC',
              villages: [
                { id: 57373, name: 'ACULAWIC' },
                { id: 57388, name: 'ACWAO A' },
                { id: 68312, name: 'OBALONGWEN A' },
                { id: 68313, name: 'OBALONGWEN B' },
                { id: 68580, name: 'OGOTI' },
              ],
            },
            {
              id: 9361,
              name: 'BUNG',
              villages: [
                { id: 57432, name: 'ADEYE A' },
                { id: 57433, name: 'ADEYE B' },
                { id: 57643, name: 'AJENGI' },
                { id: 58154, name: 'AMINOGWANG' },
                { id: 58539, name: 'AROMI' },
                { id: 58595, name: 'ATABO TIDI' },
                { id: 58844, name: 'AYOMLWOR' },
                { id: 58946, name: 'BARAPWO' },
                { id: 58951, name: 'BARBUNG' },
                { id: 60177, name: 'BUNGRAKORI' },
                { id: 68527, name: 'ODWONG' },
                { id: 68681, name: 'OKIK' },
                { id: 68712, name: 'OKUC' },
                { id: 69408, name: 'OYITOYAT' },
                { id: 71116, name: 'WIDAM' },
              ],
            },
            {
              id: 10158,
              name: 'OGWIL',
              villages: [
                { id: 57292, name: 'ACAMCABO' },
                { id: 57601, name: 'AGWENG' },
                { id: 57614, name: 'AGWILA' },
                { id: 57913, name: 'ALAC A' },
                { id: 57914, name: 'ALAC B' },
                { id: 68609, name: 'OGWIL' },
                { id: 68653, name: 'OJWIYE' },
                { id: 69794, name: 'RAMTAMA' },
              ],
            },
            {
              id: 10221,
              name: 'OWINY',
              villages: [
                { id: 57420, name: 'ADAROKOT' },
                { id: 57682, name: 'AJWAOTIO' },
                { id: 57845, name: 'AKULI' },
                { id: 58275, name: 'ANGIC' },
                { id: 58927, name: 'BAR-APWO' },
                { id: 58932, name: 'BAR-OKENY' },
                { id: 69372, name: 'OWINYITENGE A' },
                { id: 69373, name: 'OWINYITENGE B' },
              ],
            },
          ],
        },
        {
          id: 531,
          name: 'AYABI TOWN COUNCIL',
          parishes: [
            {
              id: 2472,
              name: 'AYABI WARD',
              villages: [
                { id: 57144, name: 'ABEBE' },
                { id: 16380, name: 'ACOBANOK' },
                { id: 16381, name: 'ACOBATEK' },
                { id: 16383, name: 'ADAGLAKO' },
                { id: 16384, name: 'ADII BOR  B' },
                { id: 16385, name: 'ALANGO SOUTH' },
                { id: 16386, name: 'ALONGO OYENG' },
                { id: 16387, name: 'BAR-OROMO' },
                { id: 16382, name: 'OKWOT' },
              ],
            },
            {
              id: 2474,
              name: 'CENTRAL WARD',
              villages: [
                { id: 16395, name: 'AGRO WARD' },
                { id: 16396, name: 'AGWA' },
                { id: 58398, name: 'APII BOR B' },
                { id: 16398, name: "ATWAR 'B'" },
                { id: 16397, name: 'ATWAR A' },
                { id: 16399, name: 'AYABI TRADING CENTRE' },
                { id: 16400, name: 'AYABI-AYABA' },
                { id: 16401, name: 'OBALODEO' },
                { id: 69127, name: 'OPIR' },
              ],
            },
            {
              id: 2473,
              name: 'PUNUATAR WARD',
              villages: [
                { id: 16389, name: 'ADAGANI A' },
                { id: 16390, name: 'ADAGANI B' },
                { id: 16391, name: 'AKERO' },
                { id: 16388, name: 'ALANGO NORTH' },
                { id: 16392, name: 'APII BOR A' },
                { id: 68442, name: 'ODAL OWANG' },
                { id: 16393, name: 'PUNUATAR A' },
                { id: 16394, name: 'PUNUATAR B' },
                { id: 69758, name: 'PUNUATAR C' },
              ],
            },
          ],
        },
        {
          id: 526,
          name: 'CAWENTE',
          parishes: [
            {
              id: 9123,
              name: 'ABAPIRI',
              villages: [
                { id: 57131, name: 'ABAPIRI' },
                { id: 57841, name: 'AKUKURU' },
                { id: 58270, name: 'ANGAYIKI' },
                { id: 58276, name: 'ANGIC' },
                { id: 58292, name: 'ANGU' },
                { id: 58710, name: 'AWARA' },
                { id: 61086, name: 'DAM' },
                { id: 68895, name: 'OMAC' },
                { id: 69126, name: 'OPIOLUNGA' },
              ],
            },
            {
              id: 9148,
              name: 'ADOGRAO',
              villages: [
                { id: 57149, name: 'ABEIBUTI' },
                { id: 57453, name: 'ADOGRAO' },
                { id: 57527, name: 'AGADI' },
                { id: 57921, name: 'ALAKET' },
                { id: 58561, name: 'ARWENY' },
                { id: 68752, name: 'OKWIR A' },
                { id: 68753, name: 'OKWIR B' },
              ],
            },
            {
              id: 2457,
              name: 'AJAR',
              villages: [
                { id: 16235, name: 'ABEL' },
                { id: 16237, name: 'ADERA' },
                { id: 16236, name: 'AJAR' },
                { id: 16239, name: 'AWILA' },
                { id: 16240, name: 'OBOLOCANI A' },
                { id: 16241, name: 'OLELPEK' },
                { id: 16242, name: 'TE-OPOK' },
                { id: 16238, name: 'TEIBU' },
              ],
            },
            {
              id: 2456,
              name: 'ALIDO',
              villages: [
                { id: 16228, name: 'ABARNGEC' },
                { id: 16227, name: 'ABOLI' },
                { id: 16230, name: 'AGURI' },
                { id: 16231, name: 'AGWICIRI' },
                { id: 16232, name: 'ALIDO' },
                { id: 16233, name: 'AOLE' },
                { id: 16234, name: 'ENGORO' },
                { id: 16229, name: 'GWENG' },
              ],
            },
            {
              id: 9214,
              name: 'APOLIKA',
              villages: [
                { id: 57281, name: 'ABWONG' },
                { id: 58422, name: 'APOLIKA' },
                { id: 58497, name: 'ARIDO' },
                { id: 61614, name: 'IMENG' },
                { id: 65516, name: 'LORO' },
                { id: 68696, name: 'OKOMO' },
                { id: 71040, name: 'WANGAOGIK' },
              ],
            },
            {
              id: 2455,
              name: 'ATULE',
              villages: [
                { id: 16222, name: 'ABEI' },
                { id: 16223, name: "AGWA 'A'" },
                { id: 16224, name: "AGWA 'B'" },
                { id: 16221, name: 'ANAMODUMU' },
                { id: 16225, name: 'ATULE' },
                { id: 16226, name: 'BODA' },
              ],
            },
          ],
        },
        {
          id: 527,
          name: 'INOMO',
          parishes: [
            {
              id: 2459,
              name: 'AGWICIRI',
              villages: [
                { id: 16251, name: 'ADAGANI' },
                { id: 16252, name: 'AGERINONO' },
                { id: 16253, name: 'ALAI A' },
                { id: 16254, name: 'ALERO' },
                { id: 16255, name: 'ANYWAL' },
                { id: 16256, name: "AOLI 'A'" },
                { id: 16257, name: "AOLI 'B'" },
                { id: 16258, name: 'APUMI' },
                { id: 16259, name: 'AYEGWEN' },
                { id: 16260, name: 'AYITO' },
                { id: 16261, name: 'BAR' },
                { id: 16262, name: 'GEE' },
                { id: 16263, name: 'OKWEROWILABONGO' },
                { id: 16264, name: 'OTEO' },
              ],
            },
            {
              id: 2460,
              name: 'AJOK',
              villages: [
                { id: 57145, name: 'ABED BER' },
                { id: 16265, name: 'ACOBAGWENO A' },
                { id: 16267, name: 'ACOBAGWENO B' },
                { id: 16266, name: 'AGINYI' },
                { id: 57803, name: 'AKOGE' },
                { id: 58704, name: 'AWANG OTOLE' },
                { id: 58721, name: 'AWEE IWOT' },
                { id: 16268, name: 'AYERA' },
                { id: 16269, name: 'BARANYWAR' },
                { id: 16270, name: 'BARIBU' },
                { id: 58970, name: 'BARLELA' },
                { id: 16271, name: 'BAROPOK' },
                { id: 16272, name: 'BEDIWORO' },
                { id: 59041, name: 'BERLIN' },
                { id: 16273, name: 'BUNG-GUDU' },
                { id: 16274, name: 'JERUSALEM' },
                { id: 16275, name: 'LWALA A' },
                { id: 16278, name: 'LWALA B' },
                { id: 16276, name: 'ONGICA' },
                { id: 16277, name: 'OYELO-AKIMA' },
              ],
            },
            {
              id: 2461,
              name: 'ALUKA',
              villages: [
                { id: 16280, name: 'ALAM A' },
                { id: 16279, name: 'ALAM B' },
                { id: 16281, name: 'ALIK ENGEL' },
                { id: 16282, name: 'ALIK IPING' },
                { id: 16283, name: 'AMON-OLO-COO' },
                { id: 16286, name: 'BARITEK' },
                { id: 58968, name: 'BARKWAC' },
                { id: 16288, name: 'BAROPOBO' },
                { id: 16289, name: 'ONYWALOTE' },
                { id: 16284, name: 'TE-OPOK' },
                { id: 16285, name: 'TO-PEYERO MAIN' },
                { id: 16287, name: 'TOO-PEYERO MASINDI' },
              ],
            },
            {
              id: 2458,
              name: 'BANYA',
              villages: [
                { id: 16243, name: "ACANKUMI 'A'" },
                { id: 16244, name: "ACANKUMI 'B'" },
                { id: 16245, name: 'AJOBO' },
                { id: 16246, name: 'AKOREMOR' },
                { id: 16247, name: 'AKUTOABWOLE' },
                { id: 16248, name: 'AKWIA-WORO' },
                { id: 16249, name: 'ARINGOKEC' },
                { id: 16250, name: 'AWIRITOYO' },
              ],
            },
          ],
        },
        {
          id: 532,
          name: 'INOMO TOWN COUNCIL',
          parishes: [
            {
              id: 2475,
              name: 'EASTERN WARD',
              villages: [
                { id: 16402, name: 'ABUGE' },
                { id: 16403, name: "ABWOC 'B'" },
                { id: 16404, name: 'ACEGI' },
                { id: 16405, name: 'AKOLOMOMTI' },
                { id: 16406, name: 'ALAI B' },
                { id: 16407, name: 'ALEKO' },
                { id: 16408, name: 'AMAMBALE A' },
                { id: 16414, name: 'AMAMBALE B' },
                { id: 16409, name: 'BARADU' },
                { id: 16413, name: 'BARAPWO' },
                { id: 16410, name: 'BARDEK' },
                { id: 16411, name: 'BUNG' },
                { id: 16412, name: 'OGOBI' },
              ],
            },
            {
              id: 2476,
              name: 'WESTERN WARD',
              villages: [
                { id: 16415, name: 'ADINGDONG' },
                { id: 16424, name: 'ALYEC JUK' },
                { id: 16419, name: 'APIREMIT' },
                { id: 16420, name: 'APUTOLWAR A' },
                { id: 16416, name: 'APUTOLWAR B' },
                { id: 16421, name: 'AWANGA A' },
                { id: 16417, name: 'AWANGA B' },
                { id: 16422, name: "BARLWALA 'A'" },
                { id: 16418, name: 'BARLWALA B' },
                { id: 16423, name: 'BAROKANGO' },
              ],
            },
          ],
        },
        {
          id: 528,
          name: 'NAMBIESO',
          parishes: [
            {
              id: 2464,
              name: 'ACABA',
              villages: [
                { id: 16310, name: 'AGWINGIRI' },
                { id: 16311, name: 'ATUMA' },
                { id: 16312, name: 'BARAKUDE' },
                { id: 16313, name: 'BARATEGO' },
                { id: 16314, name: 'BARMOGO' },
                { id: 16315, name: 'ELET' },
                { id: 16316, name: 'OYIMA' },
              ],
            },
            {
              id: 9143,
              name: 'ACWAO',
              villages: [
                { id: 57389, name: 'ACWAO A' },
                { id: 57391, name: 'ACWAO B' },
                { id: 57538, name: "AGENGI  'A'" },
                { id: 57539, name: "AGENGI 'B'" },
                { id: 57590, name: 'AGWA' },
                { id: 57597, name: 'AGWEI' },
                { id: 69135, name: 'OPOKOPYEN' },
              ],
            },
            {
              id: 2463,
              name: 'ANWANGI',
              villages: [
                { id: 16308, name: 'ABULUBULU' },
                { id: 16301, name: 'ANGEOKOMA' },
                { id: 16309, name: 'ARINGO-LUK' },
                { id: 16302, name: "EMIN 'A'" },
                { id: 16303, name: "EMIN 'B'" },
                { id: 16304, name: "EMIN 'C'" },
                { id: 16305, name: "EMIN 'D'" },
                { id: 16306, name: 'OPENY' },
                { id: 16307, name: 'TEILIGO' },
              ],
            },
            {
              id: 2462,
              name: 'AORNGA',
              villages: [
                { id: 16290, name: 'ABURA' },
                { id: 16291, name: 'ABURU' },
                { id: 16292, name: 'ACOKAOLA' },
                { id: 16293, name: 'AKAIDEBE' },
                { id: 16294, name: 'AMOK' },
                { id: 16295, name: 'AWALDEK' },
                { id: 16296, name: 'EGWOR' },
                { id: 61221, name: 'EGWOR A' },
                { id: 16300, name: 'ILERA' },
                { id: 16297, name: 'OKWOR' },
                { id: 16298, name: 'TE-ORYANG' },
                { id: 16299, name: 'WIDAM' },
              ],
            },
            {
              id: 2465,
              name: 'ETEKIBER',
              villages: [
                { id: 16317, name: 'ABURUKANGO' },
                { id: 16318, name: 'ABURUKEC' },
                { id: 16319, name: "AGWENYERE 'A'" },
                { id: 16320, name: "AGWENYERE 'B'" },
                { id: 16321, name: 'AKOKODAKO' },
                { id: 16322, name: 'ATANGA' },
                { id: 16323, name: 'ATUM ZERICO' },
                { id: 16328, name: 'AWEILOK' },
                { id: 16324, name: "ETEKIBER 'A'" },
                { id: 16325, name: "ETIKIBER 'B'" },
                { id: 16326, name: 'ODYEDO' },
                { id: 71125, name: 'WIGWENG' },
                { id: 16327, name: 'WII ADUU' },
              ],
            },
            {
              id: 10164,
              name: 'OJOKDOT',
              villages: [
                { id: 57255, name: 'ABULUBULU' },
                { id: 57955, name: 'ALENGERE' },
                { id: 58805, name: "AYAT 'A'" },
                { id: 58806, name: "AYAT 'B'" },
                { id: 65745, name: 'LWALA' },
                { id: 69203, name: "ORIYE 'A'" },
                { id: 69204, name: "ORIYE 'B'" },
              ],
            },
          ],
        },
      ],
    },
  ],
};
