import { District } from '../types';

export default {
  id: 15,
  name: 'KWEEN',
  counties: [
    {
      id: 41,
      name: 'KWEEN COUNTY',
      sub_counties: [
        {
          id: 218,
          name: 'BENET',
          parishes: [
            {
              id: 1017,
              name: 'KITANY',
              villages: [
                { id: 7043, name: 'KAPKUNEROI' },
                { id: 7044, name: 'KAPMWEYET' },
                { id: 7045, name: 'KITANY' },
              ],
            },
            {
              id: 1015,
              name: 'LIKIL',
              villages: [
                { id: 7033, name: 'KAPCHEMELEI' },
                { id: 7034, name: 'KAPSIRIK' },
                { id: 7035, name: 'KOKWOTOROKWO' },
                { id: 7036, name: 'LIKIL' },
                { id: 7037, name: 'LOCH' },
              ],
            },
            {
              id: 1018,
              name: 'MENGYA',
              villages: [
                { id: 7046, name: 'KABORITIN' },
                { id: 7047, name: 'KASTOY' },
                { id: 7048, name: 'KOKWOPNGOTUNY' },
                { id: 7049, name: 'MENGYA' },
              ],
            },
            {
              id: 1014,
              name: 'PISWA',
              villages: [
                { id: 7029, name: 'KABARAK' },
                { id: 7031, name: 'KAKWEEN' },
                { id: 7030, name: 'KAPKURESON' },
                { id: 7032, name: 'TARAGON UPPER' },
              ],
            },
            {
              id: 1016,
              name: 'TARAGON',
              villages: [
                { id: 7038, name: 'CHEMWONBEI' },
                { id: 7039, name: 'ROROK' },
                { id: 7040, name: 'SUKUT' },
                { id: 7042, name: 'TARAGON LOWER' },
                { id: 7041, name: 'TULWO' },
              ],
            },
          ],
        },
        {
          id: 219,
          name: 'BINYINY',
          parishes: [
            {
              id: 1022,
              name: 'CHEPYAKANIET',
              villages: [
                { id: 7065, name: 'CHEPYAKANIET' },
                { id: 7063, name: 'KAMOWO' },
                { id: 7064, name: 'KAMUGENGERE' },
                { id: 7067, name: 'KAPCHESOBEI' },
                { id: 7066, name: 'KAPTEKEYEN' },
              ],
            },
            {
              id: 1021,
              name: 'KISONGI',
              villages: [
                { id: 7060, name: 'KABAI' },
                { id: 7061, name: 'KAPENGURIA' },
                { id: 7062, name: 'SIRO' },
              ],
            },
            {
              id: 1020,
              name: 'KONO',
              villages: [
                { id: 7059, name: 'BEBOCHEBEROM' },
                { id: 7057, name: 'CHESOSURWO' },
                { id: 7058, name: 'KAMUKE' },
                { id: 7056, name: 'KWORUS' },
              ],
            },
            {
              id: 1019,
              name: 'TABAGON',
              villages: [
                { id: 7051, name: 'CHEMURON' },
                { id: 7050, name: 'CHEPTANTAN' },
                { id: 7053, name: 'CHESAKAT' },
                { id: 7055, name: 'KAPCHEKWEROP' },
                { id: 7052, name: 'KUBEREN' },
                { id: 7054, name: 'TABAGON' },
              ],
            },
            {
              id: 1023,
              name: 'TUKUMO',
              villages: [
                { id: 60868, name: 'CHAPTARRE' },
                { id: 7072, name: 'KAMWALECH' },
                { id: 7068, name: 'NGOSI' },
                { id: 7069, name: 'SUKUT' },
                { id: 7070, name: 'TARAK' },
                { id: 7071, name: 'TUIKAT' },
                { id: 7073, name: 'TUKUMO' },
              ],
            },
          ],
        },
        {
          id: 228,
          name: 'BINYINY TOWN COUNCIL',
          parishes: [
            {
              id: 1066,
              name: 'KAPKWOROS WARD',
              villages: [
                { id: 7318, name: 'CHELUK' },
                { id: 7319, name: 'KAMAYAK' },
                { id: 7320, name: 'KAPKWOROS' },
              ],
            },
            {
              id: 1067,
              name: 'KISONGI WARD',
              villages: [
                { id: 7321, name: 'BINYNY' },
                { id: 7325, name: 'CHEBEREN' },
                { id: 7326, name: 'CHEPKWOSITEN' },
                { id: 7324, name: 'KAMOWO' },
                { id: 7327, name: 'KAMUTENG' },
                { id: 7329, name: 'KEW' },
                { id: 7322, name: 'KISONGI' },
                { id: 7328, name: 'MULYABOI' },
                { id: 7323, name: 'RIKWO' },
              ],
            },
            {
              id: 1068,
              name: 'KWOBUS WARD',
              villages: [
                { id: 7332, name: 'KAPLAM' },
                { id: 7330, name: 'KAPNARONGO' },
                { id: 7331, name: 'KWOBUS' },
              ],
            },
          ],
        },
        {
          id: 231,
          name: 'CHEPSUKUNYA TOWN COUNCIL',
          parishes: [
            {
              id: 1083,
              name: 'CHEPTERE WARD',
              villages: [
                { id: 7390, name: 'CHEPTARRE' },
                { id: 7391, name: 'KUSKONG' },
                { id: 69742, name: 'PRISON' },
                { id: 7392, name: 'SERETYO' },
              ],
            },
            {
              id: 1082,
              name: 'KAPKWICH WARD',
              villages: [
                { id: 7386, name: 'CHEKWUTO' },
                { id: 7385, name: 'KAPKWICH' },
                { id: 7387, name: 'KATALEL' },
                { id: 7388, name: 'NASAK' },
                { id: 7389, name: 'TOBOTO' },
              ],
            },
            {
              id: 1084,
              name: 'NASAK WARD',
              villages: [
                { id: 7393, name: 'CHEPSUKUNYA' },
                { id: 7394, name: 'KITNET' },
                { id: 7395, name: 'NYISWA' },
                { id: 7396, name: 'PANGANI' },
              ],
            },
            {
              id: 1085,
              name: 'NGARIAMWET WARD',
              villages: [
                { id: 62478, name: 'KAMUNGEI' },
                { id: 7397, name: 'KAPNDAROI' },
                { id: 7398, name: 'NGORYOWET' },
              ],
            },
            {
              id: 1086,
              name: 'TULWO WARD',
              villages: [
                { id: 7400, name: 'MURTAMAI' },
                { id: 7399, name: 'MUTALIA' },
                { id: 67109, name: 'NAKOROMAN' },
                { id: 70851, name: 'TULWO' },
                { id: 70885, name: 'TWAMA' },
              ],
            },
          ],
        },
        {
          id: 224,
          name: 'GREEK RIVER',
          parishes: [
            {
              id: 1045,
              name: 'ALALAM',
              villages: [
                { id: 7163, name: 'ALALAM' },
                { id: 7164, name: 'CHEBINYINY' },
                { id: 7165, name: 'CHEKWIR' },
                { id: 7166, name: 'KAPCHEKWOK' },
                { id: 7167, name: 'KAPTERIT' },
                { id: 7168, name: 'KIRYAMET' },
                { id: 7169, name: 'LWOGON' },
                { id: 7170, name: 'MOKOYON' },
                { id: 7171, name: 'NAREROK' },
                { id: 7172, name: 'NDILAI' },
                { id: 7173, name: 'NGANIA' },
              ],
            },
            {
              id: 1046,
              name: 'KAPSWAMA',
              villages: [
                { id: 7176, name: 'CHAMCHAM' },
                { id: 7174, name: 'CHEBURBEI' },
                { id: 7177, name: 'KAPKOROKON' },
                { id: 7175, name: 'KAPSWAMA' },
                { id: 7178, name: 'KAPTURBORI' },
                { id: 7181, name: 'NGENY' },
                { id: 7179, name: 'TULWOYOS' },
                { id: 7180, name: 'TUYOBEI' },
              ],
            },
            {
              id: 1047,
              name: 'KERE',
              villages: [
                { id: 7182, name: 'CHEKWASTA' },
                { id: 7185, name: 'CHEPTUYA' },
                { id: 7183, name: 'KABENDER' },
                { id: 62688, name: 'KAPKWAROI' },
                { id: 7186, name: 'KIDUDU' },
                { id: 7184, name: 'KIPTARI' },
                { id: 7187, name: 'KURKURWO' },
                { id: 7188, name: 'SWAYOI' },
                { id: 7189, name: 'TULWOMOI' },
              ],
            },
            {
              id: 1049,
              name: 'KIRIKI',
              villages: [
                { id: 7197, name: 'BILILAK' },
                { id: 7198, name: 'CHEMUROT' },
                { id: 7199, name: 'CHEPTUIMAT' },
                { id: 7204, name: 'KABUNDUKI' },
                { id: 7201, name: 'KAMABATI' },
                { id: 7202, name: 'KAPSONGOYWO' },
                { id: 7200, name: 'KIRIKI' },
                { id: 7203, name: 'KONAMASIWA' },
                { id: 7205, name: 'NABUJEJE' },
              ],
            },
            {
              id: 1048,
              name: 'KORITE',
              villages: [
                { id: 7190, name: 'AYOREI' },
                { id: 7192, name: 'KAMOKOYWO' },
                { id: 7193, name: 'KAPTENIS' },
                { id: 7194, name: 'KORITE' },
                { id: 7195, name: 'KUKUMAI' },
                { id: 7191, name: 'MEKUNGA' },
                { id: 7196, name: 'SURUMIT' },
              ],
            },
          ],
        },
        {
          id: 232,
          name: 'KAPKWATA',
          parishes: [
            {
              id: 1089,
              name: 'CHERAKAN',
              villages: [
                { id: 7410, name: 'CHERAKAN' },
                { id: 7411, name: 'KAMUNCHAN' },
                { id: 62664, name: 'KAPKALAKWASINKA' },
                { id: 64002, name: 'KITAU' },
                { id: 70766, name: 'TITEM' },
                { id: 7412, name: 'TOWET' },
              ],
            },
            {
              id: 1090,
              name: 'KAPEROTWO',
              villages: [
                { id: 59714, name: 'BULKEIWO' },
                { id: 60933, name: 'CHEMURON' },
                { id: 7414, name: 'CHEPTOLOCH' },
                { id: 7413, name: 'KAPOROTWO' },
                { id: 64409, name: 'KURUMBO' },
                { id: 65258, name: 'LOCH' },
                { id: 69733, name: 'POSHA' },
                { id: 69862, name: 'ROTIN' },
              ],
            },
            {
              id: 1087,
              name: 'KAPKWATA',
              villages: [
                { id: 7402, name: 'KAPKWATA' },
                { id: 63789, name: 'KIPSIKARE' },
                { id: 7404, name: 'KISANGANI' },
                { id: 64443, name: 'KWEEN' },
                { id: 7401, name: 'MUNGEGERE' },
                { id: 7405, name: 'MUSHEMBO' },
                { id: 7403, name: 'TARAK' },
                { id: 70773, name: 'TOBOSWO' },
              ],
            },
            {
              id: 1088,
              name: 'KAPKWOROS',
              villages: [
                { id: 59174, name: 'BONIO A' },
                { id: 60903, name: 'CHELOLONG' },
                { id: 60910, name: 'CHEMANGALAL' },
                { id: 60944, name: 'CHEPATPAT' },
                { id: 7408, name: 'CHEPCHABAI' },
                { id: 61977, name: 'KABUSTO' },
                { id: 62430, name: 'KAMIRYO' },
                { id: 62435, name: 'KAMOMBU' },
                { id: 62678, name: 'KAPKOROS' },
                { id: 7409, name: 'KONGTA' },
                { id: 67692, name: 'NDUMA' },
                { id: 7407, name: 'NGEREP' },
                { id: 7406, name: 'SUKUT' },
              ],
            },
            {
              id: 1091,
              name: 'KUSURUT',
              villages: [
                { id: 7417, name: 'CHEMONGE' },
                { id: 7415, name: 'CHEMWATAT' },
                { id: 7416, name: 'CHEPTOROR' },
                { id: 62471, name: 'KAMUKOR' },
                { id: 63598, name: 'KIJITAN' },
                { id: 64415, name: 'KUSURUT' },
                { id: 66178, name: 'MBAFU' },
                { id: 66341, name: 'MOKOIWO' },
                { id: 66522, name: 'MUKEYWO' },
              ],
            },
            {
              id: 1092,
              name: 'KWORUS',
              villages: [
                { id: 58895, name: 'BANANWA' },
                { id: 59173, name: 'BONIO' },
                { id: 60972, name: 'CHEPTOPOT' },
                { id: 7419, name: 'GREEN VALLEY' },
                { id: 62434, name: 'KAMOKOTYIN' },
                { id: 62641, name: 'KAPCHERUI' },
                { id: 62643, name: 'KAPCHESAMSBUN' },
                { id: 7420, name: 'KAPSOYEN' },
                { id: 64007, name: 'KITAWASAWAY' },
                { id: 7418, name: 'KWORUS' },
                { id: 70492, name: 'SISMWA' },
              ],
            },
            {
              id: 1093,
              name: 'SISMACH',
              villages: [
                { id: 7423, name: 'CHESEBIT' },
                { id: 60997, name: 'CHESORET' },
                { id: 62251, name: 'KAKORWO' },
                { id: 62691, name: 'KAPKWEMRIO' },
                { id: 62703, name: 'KAPMWOGIN' },
                { id: 63309, name: 'KEW' },
                { id: 64351, name: 'KUBEREN NORTH' },
                { id: 66042, name: 'MARAMBACH' },
                { id: 69737, name: 'POSHA' },
                { id: 7421, name: 'SISIMACH' },
                { id: 7422, name: 'TULWO' },
              ],
            },
          ],
        },
        {
          id: 220,
          name: 'KAPRORON',
          parishes: [
            {
              id: 1025,
              name: 'CHEMWANIA',
              villages: [
                { id: 7078, name: 'CHEMWANIA' },
                { id: 7077, name: 'KAPTARE' },
                { id: 7079, name: 'KULULU' },
              ],
            },
            {
              id: 1024,
              name: 'KAMWAM',
              villages: [
                { id: 7074, name: 'KAMWAM' },
                { id: 7075, name: 'KAPSWAYOY' },
                { id: 7076, name: 'TULWO' },
              ],
            },
            {
              id: 1026,
              name: 'RARAWA',
              villages: [
                { id: 7081, name: 'CHEMERIN' },
                { id: 7082, name: 'KAPYOMAT' },
                { id: 7083, name: 'KARASOY' },
                { id: 7084, name: 'KURES' },
                { id: 7086, name: 'LELKETI' },
                { id: 7085, name: 'NDILAY' },
                { id: 7080, name: 'RARAWA' },
              ],
            },
          ],
        },
        {
          id: 230,
          name: 'KAPRORON TOWN COUNCIL',
          parishes: [
            {
              id: 1077,
              name: 'CHEMWINA EAST WARD',
              villages: [
                { id: 60940, name: 'CHEMWANIA CENTRAL' },
                { id: 62736, name: 'KAPTARE EAST' },
                { id: 64382, name: 'KULULU SOUTH' },
                { id: 7377, name: 'MOKOWO' },
                { id: 7378, name: 'SUMOTWO' },
              ],
            },
            {
              id: 1078,
              name: 'KAPLAKATET WARD',
              villages: [
                { id: 60235, name: 'BURIRKUT' },
                { id: 62699, name: 'KAPLAKATET LOWER' },
                { id: 7379, name: 'KAPLAKATET UPPER' },
              ],
            },
            {
              id: 1075,
              name: 'KAPRORON WARD',
              villages: [
                { id: 7369, name: 'KAMERUT' },
                { id: 7373, name: 'KAPNYALI' },
                { id: 7372, name: 'KAPRORON' },
                { id: 65176, name: 'LELKETI CENTRAL' },
                { id: 7370, name: 'LESOSO' },
                { id: 69810, name: 'RARAWA EAST' },
                { id: 7371, name: 'ST. MICHAEL' },
              ],
            },
            {
              id: 1076,
              name: 'KAPSOMO WARD',
              villages: [
                { id: 7375, name: 'KAPKWOBOR' },
                { id: 7374, name: 'KAPSOMO' },
                { id: 7376, name: 'ROTIN' },
              ],
            },
            {
              id: 1079,
              name: 'KERE WARD',
              villages: [
                { id: 59831, name: 'BUMATET' },
                { id: 60934, name: 'CHEMURON' },
                { id: 62810, name: 'KARITUSI' },
                { id: 7380, name: 'KERE' },
              ],
            },
            {
              id: 1080,
              name: 'KOROSI WARD',
              villages: [
                { id: 59183, name: 'BOSHA' },
                { id: 60892, name: 'CHEBURER' },
                { id: 62499, name: 'KAMWANYIN' },
                { id: 7381, name: 'KOROSI' },
                { id: 67807, name: 'NKURUMA' },
              ],
            },
            {
              id: 1081,
              name: 'SUNDET WARD',
              villages: [
                { id: 7383, name: 'CHEMOLON' },
                { id: 7382, name: 'KWENUT' },
                { id: 7384, name: 'SUNDET' },
              ],
            },
          ],
        },
        {
          id: 229,
          name: 'KAPTOYOY',
          parishes: [
            {
              id: 1069,
              name: 'KAPKOCH',
              villages: [
                { id: 7333, name: 'CHEMUNY' },
                { id: 7334, name: 'KAPKOCH' },
                { id: 7335, name: 'KAPKOROS' },
                { id: 7336, name: 'KAPTOBOSWO' },
                { id: 7337, name: 'KAYMATOI' },
                { id: 7338, name: 'SERERWO' },
              ],
            },
            {
              id: 1072,
              name: 'KAPTENG',
              villages: [
                { id: 7351, name: 'KAMUTILILWO' },
                { id: 7352, name: 'KAPKWOSOBEI' },
                { id: 7353, name: 'KAPTENG' },
                { id: 7354, name: 'KEWARWONG' },
              ],
            },
            {
              id: 1070,
              name: 'KAPTOYOY',
              villages: [
                { id: 7341, name: 'KAPCHEKWOI' },
                { id: 7339, name: 'KAPTOYOY' },
                { id: 7340, name: 'KUPSAMIY' },
                { id: 7342, name: 'RWAKOI' },
                { id: 7343, name: 'SENENDENT' },
                { id: 7344, name: 'SUKUT' },
              ],
            },
            {
              id: 1073,
              name: 'KEROP',
              villages: [
                { id: 7355, name: 'CHEBINYINY' },
                { id: 7356, name: 'CHEMAGALAL' },
                { id: 7360, name: 'KAPCHEROPTA' },
                { id: 7359, name: 'KAPKURE' },
                { id: 7357, name: 'KAPKWAWAI' },
                { id: 7361, name: 'KAPTEROR' },
                { id: 7362, name: 'KASEMIA' },
                { id: 7358, name: 'KEROP' },
                { id: 7363, name: 'KOI' },
              ],
            },
            {
              id: 1074,
              name: 'NGORYEMWO',
              villages: [
                { id: 7368, name: 'KAPCHEBOR' },
                { id: 7364, name: 'KAPCHEMIRYOT' },
                { id: 7365, name: 'KOSWO' },
                { id: 7366, name: 'NGORYEMWO' },
                { id: 7367, name: 'REBERWO' },
              ],
            },
            {
              id: 1071,
              name: 'TOSWO',
              villages: [
                { id: 7345, name: 'CHEPKWOSUM' },
                { id: 7346, name: 'CHESIMWO' },
                { id: 7347, name: 'KAPCHESIKOR' },
                { id: 7348, name: 'KAPTOKOLO' },
                { id: 7349, name: 'KAPTOLONG' },
                { id: 7350, name: 'KORYA' },
              ],
            },
          ],
        },
        {
          id: 225,
          name: 'KAPTUM',
          parishes: [
            {
              id: 1052,
              name: 'ALOMAN',
              villages: [
                { id: 7220, name: 'ALOMAN' },
                { id: 7221, name: 'BUMOTOI' },
                { id: 7222, name: 'CHEBOROM' },
                { id: 7225, name: 'CHEMURON' },
                { id: 7227, name: 'CHEPAKANAR' },
                { id: 7224, name: 'KAKWEMPEL' },
                { id: 7226, name: 'KAMAKUNGA' },
                { id: 7228, name: 'KAMOWO' },
                { id: 7231, name: 'KAMUSHEMBU' },
                { id: 7229, name: 'KAPKWERE' },
                { id: 7230, name: 'KAPNAKAK' },
                { id: 7232, name: 'KAPTORO' },
                { id: 7223, name: 'KAYABAI' },
              ],
            },
            {
              id: 1053,
              name: 'CHEBINYINY',
              villages: [
                { id: 7235, name: 'CHEBINYINY' },
                { id: 7233, name: 'CHELWENG' },
                { id: 7234, name: 'KAPTOBORWO' },
                { id: 7236, name: 'KURENY' },
                { id: 7237, name: 'SIMATON' },
              ],
            },
            {
              id: 1051,
              name: 'CHEMINY',
              villages: [
                { id: 7215, name: 'BOSHA' },
                { id: 7214, name: 'CHEMINY' },
                { id: 7217, name: 'KAPULAYA' },
                { id: 7216, name: 'LOCH' },
                { id: 7218, name: 'RWANDET' },
                { id: 7219, name: 'SUKUT' },
              ],
            },
            {
              id: 1050,
              name: 'KAPTUM',
              villages: [
                { id: 7206, name: 'KAKWIRWOK' },
                { id: 7210, name: 'KAPTOBURWO' },
                { id: 7211, name: 'KAYAMOYA' },
                { id: 7207, name: 'KONGELEL' },
                { id: 7208, name: 'REBERWO' },
                { id: 7212, name: 'SESUN' },
                { id: 7209, name: 'SONGOK' },
                { id: 7213, name: 'SONKOROCH' },
              ],
            },
            {
              id: 1054,
              name: 'SERERE',
              villages: [
                { id: 7238, name: 'KOKWOBUTAKI' },
                { id: 7239, name: 'LAKATET' },
                { id: 7240, name: 'MUKUT' },
                { id: 7241, name: 'SALAWU' },
                { id: 7242, name: 'SERERE' },
                { id: 7243, name: 'TOROR' },
              ],
            },
          ],
        },
        {
          id: 233,
          name: 'KASEKO',
          parishes: [
            {
              id: 1095,
              name: 'CHEBEREN',
              villages: [
                { id: 7432, name: 'CHEBEREN' },
                { id: 7433, name: 'KITAL' },
                { id: 7431, name: 'KOKWOMONGESAI' },
                { id: 64396, name: 'KUNOBET' },
                { id: 7434, name: 'RWANDA' },
                { id: 7435, name: 'TUYOBEI' },
              ],
            },
            {
              id: 1096,
              name: 'KAPNARKUT TOWN BOARD',
              villages: [
                { id: 7437, name: 'CHEMUKANGOI' },
                { id: 7436, name: 'CHEMURON' },
                { id: 7438, name: 'CHEMWOM' },
                { id: 7439, name: 'KAPNARKUT' },
                { id: 7440, name: 'NGENGE' },
              ],
            },
            {
              id: 1094,
              name: 'KASEKO',
              villages: [
                { id: 7424, name: 'CHEMANGA' },
                { id: 7426, name: 'CHEPSENETON' },
                { id: 7427, name: 'KAMASAREN' },
                { id: 7428, name: 'KAPAWU' },
                { id: 7429, name: 'KASEKO' },
                { id: 62915, name: 'KASENKE' },
                { id: 7425, name: 'KOPSIYOY' },
                { id: 7430, name: 'LAIKONG' },
              ],
            },
            {
              id: 1097,
              name: 'MULUNGWA',
              villages: [
                { id: 7442, name: 'CHEMUMUL' },
                { id: 7441, name: 'KAPCHESUKE' },
                { id: 7443, name: 'MULUNGWA' },
                { id: 7444, name: 'SITOTWET' },
              ],
            },
            {
              id: 1098,
              name: 'TAMBAJJA',
              villages: [
                { id: 7445, name: 'KAPCHEKWORIS' },
                { id: 7446, name: 'TAMBAJJA' },
                { id: 7447, name: 'TOBOT' },
                { id: 7448, name: 'TWENGE' },
              ],
            },
          ],
        },
        {
          id: 226,
          name: 'KITAWOI',
          parishes: [
            {
              id: 1056,
              name: 'KEWAKWEEN',
              villages: [
                { id: 7249, name: 'KAPCHEKWES' },
                { id: 7252, name: 'KEWAKWARE' },
                { id: 7250, name: 'KEWAKWEEN' },
                { id: 7251, name: 'KIRING' },
              ],
            },
            {
              id: 1055,
              name: 'KITAWOI',
              villages: [
                { id: 7244, name: 'KAPKOWET' },
                { id: 7245, name: 'KITAWOI' },
                { id: 7246, name: 'KOSTOY' },
                { id: 7247, name: 'PIYONON' },
                { id: 7248, name: 'POSHA' },
              ],
            },
            {
              id: 1057,
              name: 'SUMATON',
              villages: [
                { id: 7255, name: 'KASOWON' },
                { id: 7256, name: 'KOKWOMATILA' },
                { id: 7254, name: 'LOCH' },
                { id: 7257, name: 'RWANJAG' },
                { id: 7253, name: 'SUMATON' },
              ],
            },
            {
              id: 1058,
              name: 'TABAGON',
              villages: [
                { id: 7260, name: 'CHECHAS' },
                { id: 7261, name: 'CHEMOMUL' },
                { id: 7258, name: 'KAMOWO' },
                { id: 7259, name: 'SISITYA' },
                { id: 7262, name: 'TABAGON' },
              ],
            },
            {
              id: 1059,
              name: 'TARAK',
              villages: [
                { id: 7264, name: 'KAPKWOROS' },
                { id: 7263, name: 'KOKWOBALIAT' },
                { id: 7265, name: 'TARAK' },
                { id: 7266, name: 'TARAK LOWER' },
              ],
            },
            {
              id: 1060,
              name: 'TEREMPOY',
              villages: [
                { id: 7272, name: 'CHEKWOTOK' },
                { id: 7267, name: 'KAPCHERWONGOY' },
                { id: 7268, name: 'KENZIN' },
                { id: 7269, name: 'SUKUT' },
                { id: 7270, name: 'TERENPOY' },
                { id: 7271, name: 'TOPOT' },
              ],
            },
          ],
        },
        {
          id: 222,
          name: 'KWANYIY',
          parishes: [
            {
              id: 1034,
              name: 'KAMWESA',
              villages: [
                { id: 58467, name: 'ARAPMITI' },
                { id: 59182, name: 'BOSHA' },
                { id: 60891, name: 'CHEBURBEI' },
                { id: 60925, name: 'CHEMUROM' },
                { id: 7129, name: 'KAMWESA' },
                { id: 62636, name: 'KAPCHEBEREN' },
                { id: 62749, name: 'KAPTUNGURURWO' },
                { id: 67422, name: 'NANDI' },
                { id: 70313, name: 'SESUT' },
                { id: 70315, name: 'SHAMBA' },
                { id: 70772, name: 'TOBOSWET' },
                { id: 70856, name: 'TULWO' },
              ],
            },
            {
              id: 9608,
              name: 'KAPKWAIKOI',
              villages: [
                { id: 60906, name: 'CHELONG NORTH' },
                { id: 62005, name: 'KACHITAN' },
                { id: 62538, name: 'KANGOTA' },
                { id: 62676, name: 'KAPKOROKON' },
                { id: 69858, name: 'ROSTI A' },
              ],
            },
            {
              id: 1032,
              name: 'KAPKWOIKOI',
              villages: [
                { id: 7120, name: 'CHEKWASTA' },
                { id: 7122, name: 'CHEPAR' },
                { id: 7123, name: 'KAPJOKEN' },
                { id: 7121, name: 'KAPKOIKOI' },
                { id: 7124, name: 'LOMOYWO' },
              ],
            },
            {
              id: 1033,
              name: 'KAPLEGEP',
              villages: [
                { id: 7127, name: 'CHEMONG' },
                { id: 60931, name: 'CHEMURON' },
                { id: 7128, name: 'KAPLEGEP LOWER' },
                { id: 7125, name: 'KAPLEGEP UPPER' },
                { id: 63307, name: 'KEW' },
                { id: 7126, name: 'KUROT' },
                { id: 70587, name: 'TABOSWO' },
                { id: 70814, name: 'TOROR' },
              ],
            },
            {
              id: 1035,
              name: 'KUTWECH',
              villages: [
                { id: 60904, name: 'CHELOLONG SOUTH' },
                { id: 61874, name: 'KABARAK' },
                { id: 61905, name: 'KABEN' },
                { id: 7132, name: 'KAPLEKETET' },
                { id: 7133, name: 'KAPTENDEN' },
                { id: 7130, name: 'KUTWECH' },
                { id: 66552, name: 'MUKULEI' },
                { id: 7131, name: 'NYIMEI' },
                { id: 69859, name: 'ROSTI B' },
              ],
            },
            {
              id: 1036,
              name: 'MUNDA',
              villages: [
                { id: 7135, name: 'CHAMCHAM' },
                { id: 61976, name: 'KABUSHE' },
                { id: 62738, name: 'KAPTASKE' },
                { id: 64268, name: 'KONA' },
                { id: 7134, name: 'MOKOTU' },
                { id: 66611, name: 'MUNDA' },
                { id: 66653, name: 'MURKOKOI' },
                { id: 70855, name: 'TULWO' },
              ],
            },
            {
              id: 1031,
              name: 'NYIMEI',
              villages: [
                { id: 62729, name: 'KAPSWAYOY' },
                { id: 7117, name: 'KAWUSWO   A' },
                { id: 7118, name: 'KAWUSWO   B' },
                { id: 7119, name: 'KWANYIY' },
                { id: 66343, name: 'MOKOYO' },
                { id: 66426, name: 'MOWET' },
                { id: 69861, name: 'ROTIN' },
              ],
            },
            {
              id: 1037,
              name: 'SUMOTWO',
              villages: [
                { id: 7137, name: 'BUMOTOI' },
                { id: 60983, name: 'CHEPUREI' },
                { id: 7136, name: 'KAPKWATA FOREST' },
                { id: 62701, name: 'KAPLAMAI' },
                { id: 62723, name: 'KAPSOKANA' },
                { id: 65260, name: 'LOCH' },
                { id: 7138, name: 'RWANDA' },
                { id: 70562, name: 'SUMOTWO' },
              ],
            },
          ],
        },
        {
          id: 223,
          name: 'KWOSIR',
          parishes: [
            {
              id: 1040,
              name: 'CHEPKUBE',
              villages: [
                { id: 7147, name: 'CHEPKUBE' },
                { id: 62483, name: 'KAMURYONY' },
                { id: 62639, name: 'KAPCHEMIRYOT' },
                { id: 62679, name: 'KAPKOROSOI' },
                { id: 7149, name: 'KIJIRIR' },
                { id: 70557, name: 'SUKUT' },
                { id: 7148, name: 'SUNDET' },
              ],
            },
            {
              id: 1041,
              name: 'CHEPTANDAN',
              villages: [
                { id: 7150, name: 'BENET EAST' },
                { id: 7151, name: 'BENET WEST' },
                { id: 59179, name: 'BOROWO' },
                { id: 7152, name: 'CHEPTANDAN' },
                { id: 69851, name: 'ROROK' },
                { id: 70854, name: 'TULWO' },
                { id: 7153, name: 'TULWO EAST' },
                { id: 7154, name: 'TULWO WEST' },
              ],
            },
            {
              id: 1042,
              name: 'CHERANGUT',
              villages: [
                { id: 60930, name: 'CHEMURON' },
                { id: 7155, name: 'CHERANGUT' },
                { id: 62638, name: 'KAPCHELAL' },
                { id: 7156, name: 'KORTOW' },
                { id: 64323, name: 'KORTOWOP MAIL' },
              ],
            },
            {
              id: 1039,
              name: 'KAPNGOTINY',
              villages: [
                { id: 59830, name: 'BUMATET' },
                { id: 7144, name: 'KAPNGOTINY' },
                { id: 70271, name: 'SAKAT' },
                { id: 7145, name: 'SINOPTUMBO' },
                { id: 70561, name: 'SUMOTWO' },
                { id: 7146, name: 'TULOLWO' },
              ],
            },
            {
              id: 1043,
              name: 'KAWORYO',
              villages: [
                { id: 59178, name: 'BOROTWO' },
                { id: 61970, name: 'KABURET' },
                { id: 62397, name: 'KAMAKONGEN' },
                { id: 62684, name: 'KAPKUMOLON' },
                { id: 7157, name: 'KAWORYO' },
                { id: 7158, name: 'LITEI' },
                { id: 66427, name: 'MOWET' },
                { id: 7159, name: 'NAMORYO' },
              ],
            },
            {
              id: 1038,
              name: 'KWOSIR',
              villages: [
                { id: 58504, name: 'ARIMOT' },
                { id: 7139, name: 'KAMATELONG' },
                { id: 7140, name: 'KWOSIR' },
                { id: 7142, name: 'MUKULIET B' },
                { id: 7141, name: 'MUKUT' },
                { id: 69664, name: 'PEKERYO' },
                { id: 70556, name: 'SUKUT' },
                { id: 7143, name: 'TEKANTET' },
              ],
            },
            {
              id: 1044,
              name: 'TOPOT',
              villages: [
                { id: 7162, name: 'KAMATUNGWO' },
                { id: 62475, name: 'KAMULOSTIN' },
                { id: 7160, name: 'KAPTERIS' },
                { id: 70092, name: 'RWANDET' },
                { id: 70570, name: 'SUSEN' },
                { id: 7161, name: 'TOPOT' },
              ],
            },
          ],
        },
        {
          id: 227,
          name: 'MOYOK',
          parishes: [
            {
              id: 1062,
              name: 'KABELYO',
              villages: [
                { id: 7280, name: 'CHEKWATA' },
                { id: 7281, name: 'CHEPSURWA' },
                { id: 7282, name: 'KABELYO' },
                { id: 7285, name: 'KAKWOYONGEN' },
                { id: 7286, name: 'KAMWASAI' },
                { id: 7287, name: 'KAPCHEMOKEN' },
                { id: 7288, name: 'KAPNGOKIN' },
                { id: 7289, name: 'KAPTERIT' },
                { id: 7283, name: 'MOKOYON' },
                { id: 7290, name: 'MUYESA' },
                { id: 7292, name: 'NDILAI' },
                { id: 7284, name: 'SUKUT' },
                { id: 7291, name: 'TARAGON' },
              ],
            },
            {
              id: 1065,
              name: 'KAPCHESIMET',
              villages: [
                { id: 7313, name: 'CHESAKAS' },
                { id: 7315, name: 'CHESOPIT' },
                { id: 7316, name: 'KAPCHESIMET' },
                { id: 7312, name: 'KAWIMBI' },
                { id: 7317, name: 'MAKUNGA' },
                { id: 7314, name: 'NYAMA' },
                { id: 7311, name: 'ROSTI' },
                { id: 7310, name: 'SUMATON' },
              ],
            },
            {
              id: 1063,
              name: 'KAPLEKEPSOI',
              villages: [
                { id: 7293, name: 'CHEMWEN' },
                { id: 7294, name: 'KAPCHERIPISTIN' },
                { id: 7296, name: 'KAPLEKEP-SOI' },
                { id: 7295, name: 'KONGTA' },
                { id: 7297, name: 'KWURES' },
                { id: 7298, name: 'SINGILAY' },
                { id: 7299, name: 'SONGOK' },
              ],
            },
            {
              id: 1064,
              name: 'KAPYATEI',
              villages: [
                { id: 7300, name: 'CHEBURONY' },
                { id: 7301, name: 'FARM' },
                { id: 7302, name: 'KAPCHEKWUTWO' },
                { id: 7305, name: 'KAPYATEI' },
                { id: 7306, name: 'KASAPEN' },
                { id: 7309, name: 'KERE' },
                { id: 7303, name: 'SOSHO' },
                { id: 7304, name: 'SURURTOI' },
                { id: 7307, name: 'TOBOSWO' },
                { id: 7308, name: 'TULWO' },
              ],
            },
            {
              id: 1061,
              name: 'MOYOK',
              villages: [
                { id: 7273, name: 'CHEKWIR' },
                { id: 7276, name: 'CHEMURON' },
                { id: 7274, name: 'MATINYBEI' },
                { id: 7277, name: 'MENGYA' },
                { id: 7275, name: 'MOYOK' },
                { id: 7278, name: 'TANGWEN' },
                { id: 7279, name: 'TAYEKO' },
              ],
            },
          ],
        },
        {
          id: 221,
          name: 'NGENGE',
          parishes: [
            {
              id: 1028,
              name: 'KABACHIRIA',
              villages: [
                { id: 7095, name: 'BUTARIA' },
                { id: 7093, name: 'CHEBOROM' },
                { id: 7096, name: 'CHEPKERKER' },
                { id: 7094, name: 'KABACHIRYA' },
                { id: 7099, name: 'KABOMBEI' },
                { id: 7097, name: 'KAPKALACHI' },
                { id: 7098, name: 'KAPLOBOTWO' },
                { id: 7100, name: 'MOKONAT' },
                { id: 7101, name: 'NGANIET' },
                { id: 7102, name: 'SUTOO' },
              ],
            },
            {
              id: 1027,
              name: 'KAPKWOT',
              villages: [
                { id: 7089, name: 'ARYOWET' },
                { id: 7090, name: 'CHERINGIR' },
                { id: 62477, name: 'KAMUNGEI' },
                { id: 7087, name: 'KAPLAL' },
                { id: 7088, name: 'KAPTULEL' },
                { id: 7091, name: 'KOKWANYI' },
                { id: 65978, name: 'MAKUNGA' },
                { id: 7092, name: 'MAKUTANO' },
              ],
            },
            {
              id: 1029,
              name: 'SIKWO',
              villages: [
                { id: 7103, name: 'AMKOKEL' },
                { id: 7104, name: 'CHEPNOIBEI' },
                { id: 7105, name: 'KAIBOS' },
                { id: 7106, name: 'KAIMARENG' },
                { id: 7107, name: 'KWURES' },
                { id: 7108, name: 'MOKOYWET' },
                { id: 7109, name: 'SIKWO' },
                { id: 7110, name: 'SOSET' },
              ],
            },
            {
              id: 1030,
              name: 'SOSHO',
              villages: [
                { id: 7111, name: 'ANIO-KWENIK' },
                { id: 7112, name: 'ATYAI' },
                { id: 7113, name: 'KAPSAWURIA' },
                { id: 7114, name: 'MARANDAN' },
                { id: 7116, name: 'SOSHO' },
                { id: 7115, name: 'WORYO' },
              ],
            },
          ],
        },
        {
          id: 234,
          name: 'SUNDET',
          parishes: [
            {
              id: 1100,
              name: 'KAPTERIT',
              villages: [
                { id: 7455, name: 'CHEPKUMALIS' },
                { id: 7456, name: 'KAPTERIT' },
                { id: 7457, name: 'MAKUNGA' },
                { id: 66654, name: 'MURTAMAI' },
                { id: 7458, name: 'TULWOMWANGA' },
                { id: 70884, name: 'TWAMA' },
              ],
            },
            {
              id: 1101,
              name: 'KUBOBEY',
              villages: [
                { id: 7459, name: 'CHEPKUNOI' },
                { id: 7460, name: 'CHEPTUYIS' },
                { id: 62644, name: 'KAPCHESARUR' },
                { id: 7461, name: 'KAPKWAROI' },
                { id: 7462, name: 'KUBOBEY' },
                { id: 7463, name: 'SOWUR' },
                { id: 7464, name: 'SUKUNYA' },
                { id: 7465, name: 'SURUMTIT' },
              ],
            },
            {
              id: 1102,
              name: 'NYILIT',
              villages: [
                { id: 62645, name: 'KAPCHESARUR' },
                { id: 7466, name: 'KAPTOBOYON' },
                { id: 7467, name: 'NGORNA' },
                { id: 7468, name: 'NYILIT' },
                { id: 7469, name: 'SOSET' },
                { id: 7470, name: 'TUYOBEI' },
              ],
            },
            {
              id: 1099,
              name: 'SUNDET',
              villages: [
                { id: 7449, name: 'CHEMENGICH' },
                { id: 7450, name: 'CHEMURON' },
                { id: 7451, name: 'KAPKWARE' },
                { id: 7452, name: 'KAPKWOROS' },
                { id: 62721, name: 'KAPSIRIKA' },
                { id: 7453, name: 'MOKOTU' },
                { id: 7454, name: 'SUNDET' },
              ],
            },
          ],
        },
        {
          id: 235,
          name: 'TUIKAT',
          parishes: [
            {
              id: 1106,
              name: 'CHEPKUTUS',
              villages: [
                { id: 60739, name: 'BUYONON' },
                { id: 7485, name: 'CHEPKUTUS' },
                { id: 7486, name: 'KABELYO' },
                { id: 7487, name: 'KAPTANG' },
                { id: 69855, name: 'ROROK A' },
                { id: 7488, name: 'TUNKWOSERET' },
              ],
            },
            {
              id: 1105,
              name: 'KERE',
              villages: [
                { id: 7479, name: 'CHEPKWASTA' },
                { id: 60973, name: 'CHEPTOROR' },
                { id: 61899, name: 'KABEKERIS B' },
                { id: 7480, name: 'KAPLAMAI' },
                { id: 7484, name: 'KAPSIKWON' },
                { id: 7481, name: 'KERE' },
                { id: 64240, name: 'KOLONGEY' },
                { id: 7482, name: 'KONGTA' },
                { id: 7483, name: 'MUKULIET A' },
              ],
            },
            {
              id: 1107,
              name: 'MOIGUT',
              villages: [
                { id: 7489, name: 'CHEMURON' },
                { id: 7490, name: 'KAMWAM' },
                { id: 65980, name: 'MAKUNGA' },
                { id: 7491, name: 'MOIGUT' },
                { id: 70872, name: 'TURMAIS' },
              ],
            },
            {
              id: 1108,
              name: 'SOSUR',
              villages: [
                { id: 60943, name: 'CHEMWONICHBEI' },
                { id: 61884, name: 'KABAROWO' },
                { id: 7492, name: 'KAPCHEBAKON' },
                { id: 65196, name: 'LIMET' },
                { id: 70091, name: 'RWANDET' },
                { id: 7493, name: 'SOSUR' },
                { id: 70850, name: 'TULWO' },
              ],
            },
            {
              id: 1109,
              name: 'TOLIL',
              villages: [
                { id: 60992, name: 'CHESABIT' },
                { id: 62663, name: 'KAPIYONWO' },
                { id: 69845, name: 'ROLOK B' },
                { id: 7494, name: 'TOLIL' },
                { id: 70792, name: 'TOLOSHO' },
              ],
            },
            {
              id: 1104,
              name: 'TUIKAT',
              villages: [
                { id: 61876, name: 'KABARAK' },
                { id: 62696, name: 'KAPKWOROSOY' },
                { id: 63255, name: 'KEBERIS A' },
                { id: 64445, name: 'KWEEN' },
                { id: 7477, name: 'SUKUT' },
                { id: 7478, name: 'TUIKAT' },
              ],
            },
            {
              id: 1103,
              name: 'YATUI',
              villages: [
                { id: 7471, name: 'ARKUT' },
                { id: 7472, name: 'CHEMUKULA' },
                { id: 7473, name: 'CHESIKONGO' },
                { id: 7475, name: 'MATUPSOO' },
                { id: 69856, name: 'ROROKOPCHEKUKEN' },
                { id: 7474, name: 'SABU' },
                { id: 70517, name: 'SOKORWET' },
                { id: 7476, name: 'YATUI' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
