import { District } from '../types';

export default {
  id: 112,
  name: 'KYEGEGWA',
  counties: [
    {
      id: 267,
      name: 'KYAKA NORTH COUNTY',
      sub_counties: [
        {
          id: 1738,
          name: 'HAPUUYO',
          parishes: [
            {
              id: 8247,
              name: 'IRINGA',
              villages: [
                { id: 51089, name: 'IRINGA' },
                { id: 51088, name: 'KABURARA' },
                { id: 51090, name: 'KANANGA' },
                { id: 62616, name: 'KANYWAMBOGO' },
                { id: 51091, name: 'KIZINAMADARA' },
                { id: 51092, name: 'KYAKASOORO' },
                { id: 51093, name: 'MAGA' },
              ],
            },
            {
              id: 8248,
              name: 'KIJUMA',
              villages: [
                { id: 51094, name: 'HARWOOMA' },
                { id: 51095, name: 'KAHUNGERA' },
                { id: 51097, name: 'KIHEEKA' },
                { id: 51100, name: 'KIJOGOJO' },
                { id: 51098, name: 'KIJUMA' },
                { id: 63634, name: 'KIKANGA' },
                { id: 51096, name: 'KISANA' },
                { id: 51099, name: 'KYEGANYWA' },
                { id: 51102, name: 'MUKARA' },
                { id: 51101, name: 'RULINJA' },
              ],
            },
            {
              id: 8249,
              name: 'MUKONDA',
              villages: [
                { id: 60798, name: 'BWIHYA' },
                { id: 51104, name: 'LYAMAKOMA' },
                { id: 51103, name: 'MUKONDA' },
                { id: 68992, name: 'OMUKANARA' },
                { id: 70125, name: 'RWEMBAHO' },
                { id: 70149, name: 'RWEMIRONGO' },
                { id: 70218, name: 'RWENYENJE' },
              ],
            },
            {
              id: 8250,
              name: 'RUCWAMIIGO',
              villages: [
                { id: 59052, name: 'BICUMU' },
                { id: 61083, name: 'DAIMANDA' },
                { id: 61600, name: 'IKARANGIRO' },
                { id: 62021, name: 'KACWAMPALI' },
                { id: 64465, name: 'KYABAGAIGA' },
                { id: 66449, name: 'MPOROGOMA' },
                { id: 51105, name: 'RUCWAMIIGO' },
              ],
            },
          ],
        },
        {
          id: 1746,
          name: 'HAPUUYO TOWN COUNCIL',
          parishes: [
            {
              id: 8280,
              name: 'KARUMAIMA WARD',
              villages: [
                { id: 51322, name: 'HABUSORO' },
                { id: 62859, name: 'KARUMAIMA' },
                { id: 51325, name: 'KIRYABYENJU' },
                { id: 51323, name: 'KISOKE' },
                { id: 51327, name: 'KYABAGONYA' },
                { id: 64614, name: 'KYAMASIYALE' },
                { id: 64717, name: 'KYARUKARABU' },
                { id: 51324, name: 'MBAARA' },
                { id: 69921, name: 'RUHUNGA' },
                { id: 51326, name: 'RWEITANO' },
                { id: 70150, name: 'RWEMISENKE' },
              ],
            },
            {
              id: 8279,
              name: 'KITALEESA WARD',
              villages: [
                { id: 51317, name: 'BUSEKYA' },
                { id: 51318, name: 'KIDONGO' },
                { id: 63594, name: 'KIJEEBA' },
                { id: 63612, name: 'KIJUGIRA' },
                { id: 51319, name: 'KISIITA' },
                { id: 51320, name: 'KITALEESA A' },
                { id: 63989, name: 'KITALEESA B' },
                { id: 63990, name: 'KITALEESA C' },
                { id: 51321, name: 'KYANKUBA A' },
                { id: 64685, name: 'KYANKUBA B' },
              ],
            },
            {
              id: 8281,
              name: 'MUZIIZI WARD',
              villages: [
                { id: 62543, name: 'KANKWALI' },
                { id: 51330, name: 'KISEREMBA' },
                { id: 51328, name: 'KYAIGUMA' },
                { id: 51331, name: 'KYARUJUMBA' },
                { id: 51329, name: 'MWAARO' },
                { id: 69897, name: 'RUGARA C' },
              ],
            },
            {
              id: 8282,
              name: 'NYAMUGURA WARD',
              villages: [
                { id: 62110, name: 'KAGOROGORO' },
                { id: 51336, name: 'KATEETE' },
                { id: 51332, name: 'KIKEREKEETE' },
                { id: 66516, name: 'MUKARAMA' },
                { id: 51333, name: 'NYAMUGURA' },
                { id: 51334, name: 'NYARUKONI' },
                { id: 51335, name: 'RUGARA A' },
                { id: 51337, name: 'RUGARA B' },
                { id: 69948, name: 'RULIMENGO' },
              ],
            },
          ],
        },
        {
          id: 1739,
          name: 'KAKABARA',
          parishes: [
            {
              id: 8253,
              name: 'IHUNGA',
              villages: [
                { id: 51121, name: 'IHUNGA' },
                { id: 51123, name: 'KATWEMPARRA' },
                { id: 51124, name: 'KIKONDA' },
                { id: 51122, name: 'KILYABYOMA' },
                { id: 51127, name: 'KYAKARONGO' },
                { id: 51120, name: 'KYAKASUKULE' },
                { id: 51125, name: 'KYARUTANGA' },
                { id: 51128, name: 'MUNSAMBYA' },
                { id: 51126, name: 'MUZAHURA' },
              ],
            },
            {
              id: 8252,
              name: 'KIHAGUZI',
              villages: [
                { id: 51114, name: 'BULAAYA' },
                { id: 51115, name: 'KASASA' },
                { id: 51117, name: 'KIHAGUZI A' },
                { id: 51118, name: 'KIHAGUZI B' },
                { id: 63616, name: 'KIJUMBA' },
                { id: 51119, name: 'KIKUUTA' },
                { id: 65938, name: 'MAKERERE' },
                { id: 51116, name: 'NYABUSOZI' },
              ],
            },
            {
              id: 8251,
              name: 'KIJAGUZO',
              villages: [
                { id: 51109, name: 'BUHEMBE' },
                { id: 59705, name: 'BULIIJO' },
                { id: 51108, name: 'KATERRE' },
                { id: 63402, name: 'KIBUUBA' },
                { id: 51112, name: 'KIDOGODO' },
                { id: 51106, name: 'KIGIMU' },
                { id: 51110, name: 'KIJAGUZO' },
                { id: 51111, name: 'KIKOMERO' },
                { id: 51113, name: 'KISOJO' },
                { id: 64660, name: 'KYAMUTAHIKYA' },
                { id: 51107, name: 'MPAAMA' },
              ],
            },
            {
              id: 8254,
              name: 'KYARWEHUTA',
              villages: [
                { id: 51131, name: 'BUGARAMA' },
                { id: 51130, name: 'KARUNGULE A' },
                { id: 62864, name: 'KARUNGULE B' },
                { id: 64024, name: 'KITENGULE' },
                { id: 64541, name: 'KYAKAJAAJA' },
                { id: 51132, name: 'KYARWEHUUTA' },
                { id: 66194, name: 'MBIIRRO' },
                { id: 51129, name: 'RWEMITUKUZA' },
              ],
            },
          ],
        },
        {
          id: 1741,
          name: 'KAKABARA TOWN COUNCIL',
          parishes: [
            {
              id: 8262,
              name: 'BURARO WARD',
              villages: [
                { id: 51193, name: 'BURARO' },
                { id: 51194, name: 'KIHUMBYA' },
                { id: 63892, name: 'KISENGYA' },
                { id: 63895, name: 'KISENKA' },
                { id: 51195, name: 'KYAISAZA' },
                { id: 64574, name: 'KYAKATERABWIRE' },
                { id: 51196, name: 'NSORRO' },
              ],
            },
            {
              id: 8263,
              name: 'KAKABARA WARD',
              villages: [
                { id: 51197, name: 'IGUNDA A' },
                { id: 62185, name: 'KAKABARA CENTRAL' },
                { id: 64011, name: 'KITEBUTURA' },
                { id: 51198, name: 'MISENYI' },
              ],
            },
            {
              id: 8260,
              name: 'KIKYEDO WARD',
              villages: [
                { id: 59382, name: 'BUHOZA' },
                { id: 51183, name: 'IGUNDA B' },
                { id: 51184, name: 'KABALE' },
                { id: 51186, name: 'KIBUGA' },
                { id: 51185, name: 'KICWAMIRUNDI' },
                { id: 51187, name: 'KIKYEDO' },
                { id: 66130, name: 'MATOOJO' },
                { id: 51182, name: 'MIRONGO' },
              ],
            },
            {
              id: 8261,
              name: 'KISIITA WARD',
              villages: [
                { id: 61674, name: 'ISANDARA' },
                { id: 51189, name: 'KIKURUNGO' },
                { id: 51192, name: 'KINONA' },
                { id: 51190, name: 'KISIITA' },
                { id: 51191, name: 'KYENJOKI' },
                { id: 51188, name: 'NGANGI' },
                { id: 68210, name: 'NYANGA' },
              ],
            },
          ],
        },
        {
          id: 1740,
          name: 'KASULE',
          parishes: [
            {
              id: 8258,
              name: 'BUGOGO',
              villages: [
                { id: 51163, name: 'BUGEZA' },
                { id: 51160, name: 'BUGOGO' },
                { id: 51162, name: 'KABARUNGI' },
                { id: 51161, name: 'KIGARAMA' },
                { id: 51165, name: 'KIKOBOZA' },
                { id: 51167, name: 'KYEHANGI' },
                { id: 51164, name: 'MABYARRA' },
                { id: 51166, name: 'MUNGANDO' },
                { id: 51171, name: 'MWIGURU' },
                { id: 51169, name: 'NYABULIKO' },
                { id: 51170, name: 'NYAMUSIBURA' },
                { id: 51168, name: 'SEMITWE' },
              ],
            },
            {
              id: 8255,
              name: 'KARAMA',
              villages: [
                { id: 51134, name: 'BWENGIRI A' },
                { id: 51135, name: 'BWENGIRI B' },
                { id: 51136, name: 'KABAALE' },
                { id: 51133, name: 'KARAMA' },
                { id: 51139, name: 'KYATAMUTEKA' },
                { id: 51137, name: 'MIRONGO' },
                { id: 51138, name: 'MUGEGA' },
                { id: 51140, name: 'RUBONA' },
              ],
            },
            {
              id: 8256,
              name: 'KASULE',
              villages: [
                { id: 51141, name: 'KAKASORO' },
                { id: 51142, name: 'KAMAISANE' },
                { id: 51143, name: 'KASULE' },
                { id: 51144, name: 'MUHANGI' },
                { id: 51145, name: 'RUGARA' },
                { id: 51146, name: 'RWEBISAJWA' },
              ],
            },
            {
              id: 8257,
              name: 'KIBUUBA',
              villages: [
                { id: 51158, name: 'BUUBALE BWERA' },
                { id: 51147, name: 'DERE' },
                { id: 51153, name: 'DERE EAST' },
                { id: 51154, name: 'DERE SOUTH' },
                { id: 51148, name: 'KAMUSENENE' },
                { id: 51149, name: 'KIBUUBA' },
                { id: 51150, name: 'KIDINDIMYA' },
                { id: 51151, name: 'KIJUNGIRO NORTH' },
                { id: 51159, name: 'KIJUNGIRO SOUTH' },
                { id: 51152, name: 'KIKONGE' },
                { id: 51157, name: 'KYANJOGEZA' },
                { id: 51155, name: 'KYENSAMBU' },
                { id: 51156, name: 'RWEPANGA' },
              ],
            },
            {
              id: 8259,
              name: 'NGANGI',
              villages: [
                { id: 51177, name: 'HAMUYAGA' },
                { id: 51175, name: 'KABAGARA' },
                { id: 51181, name: 'KANOGA' },
                { id: 51176, name: 'KATOMA' },
                { id: 51179, name: 'KIRUNGA' },
                { id: 51172, name: 'KYAIBUMBA' },
                { id: 51174, name: 'KYARWANGA' },
                { id: 51178, name: 'MIKOLE' },
                { id: 51180, name: 'NGANGI' },
                { id: 51173, name: 'ZITEGERE' },
              ],
            },
          ],
        },
        {
          id: 1744,
          name: 'KIGAMBO',
          parishes: [
            {
              id: 8272,
              name: 'KIGAMBO',
              villages: [
                { id: 51261, name: 'KIGAMBO' },
                { id: 51262, name: 'KIKANJA' },
                { id: 51264, name: 'KINYWAAGI' },
                { id: 51265, name: 'KITONGO' },
                { id: 51266, name: 'MAINWA' },
                { id: 51263, name: 'MIJUNWA' },
                { id: 51260, name: 'NYABUHAAMA' },
              ],
            },
            {
              id: 8273,
              name: 'KYANYAMBALI',
              villages: [
                { id: 51267, name: 'BUKAARA' },
                { id: 51273, name: 'BUTALE' },
                { id: 51268, name: 'KAMUGENYI A' },
                { id: 51272, name: 'KAMUGENYI B' },
                { id: 51271, name: 'KASORRO' },
                { id: 51269, name: 'KATOMA' },
                { id: 51270, name: 'KIHORONGWA' },
                { id: 51275, name: 'KYANYAMBALI' },
                { id: 51274, name: 'NYABULIKO' },
              ],
            },
            {
              id: 8274,
              name: 'MAGOMA',
              villages: [
                { id: 51279, name: 'BUHUMURRO' },
                { id: 51278, name: 'BUSINGE' },
                { id: 51277, name: 'IBUGA' },
                { id: 51283, name: 'KAHANAMA' },
                { id: 51281, name: 'KARAMA' },
                { id: 51284, name: 'KAROKARUNGI' },
                { id: 51286, name: 'KIKAMBA' },
                { id: 51285, name: 'KYALIBONI' },
                { id: 51287, name: 'MABAALE' },
                { id: 51280, name: 'MAGOMA' },
                { id: 51276, name: 'MUGERA' },
                { id: 51282, name: 'NTUNTU' },
                { id: 51288, name: 'NYAKAHO' },
                { id: 69943, name: 'RUKUNGIRI' },
                { id: 51289, name: 'YERUZALEMU' },
              ],
            },
          ],
        },
        {
          id: 1747,
          name: 'KYATEGA',
          parishes: [
            {
              id: 9640,
              name: 'KATAMBA',
              villages: [
                { id: 61541, name: 'IBANDA' },
                { id: 61849, name: 'KABALE' },
                { id: 62474, name: 'KAMULI' },
                { id: 63014, name: 'KASUNGA' },
                { id: 63033, name: 'KATAMBA' },
                { id: 63250, name: 'KAZIIZI A' },
                { id: 63251, name: 'KAZIIZI B' },
                { id: 63774, name: 'KINYINYA' },
                { id: 64586, name: 'KYAKIKOBA' },
                { id: 64665, name: 'KYAMUTWE' },
                { id: 66321, name: 'MITYEBIRI' },
                { id: 67914, name: 'NYABITINDA A' },
                { id: 67915, name: 'NYABITINDA B' },
                { id: 68043, name: 'NYAKASENYI' },
                { id: 69969, name: 'RUSARA' },
                { id: 70166, name: 'RWENGANDO' },
              ],
            },
            {
              id: 8283,
              name: 'KYATEGA',
              villages: [
                { id: 51338, name: 'BUSWASWA' },
                { id: 51339, name: 'KAHANGA' },
                { id: 51340, name: 'KICUUMU' },
                { id: 63870, name: 'KISAMBYA' },
                { id: 51341, name: 'KISAMURA A' },
                { id: 51342, name: 'KISAMURA B' },
                { id: 51344, name: 'KYANGOMA' },
                { id: 51345, name: 'KYATEGA' },
                { id: 51343, name: 'NYAMITOMA' },
              ],
            },
            {
              id: 8284,
              name: 'NKOMANGANI',
              villages: [
                { id: 60409, name: 'BUSURRU' },
                { id: 51348, name: 'KABAGARA' },
                { id: 51346, name: 'KANYARUKOMA' },
                { id: 51347, name: 'KASENENE' },
                { id: 63624, name: 'KIJWARA' },
                { id: 63872, name: 'KISANA' },
                { id: 51351, name: 'KISIMWENDA' },
                { id: 51349, name: 'KITURA' },
                { id: 51352, name: 'NKOMANGANI' },
                { id: 51350, name: 'NSUNGE' },
                { id: 69997, name: 'RUTOMA' },
              ],
            },
          ],
        },
        {
          id: 1743,
          name: 'KYEGEGWA TOWN COUNCIL',
          parishes: [
            {
              id: 8269,
              name: 'KIBIRA WARD',
              villages: [
                { id: 51221, name: 'BIKOKWA' },
                { id: 51222, name: 'BUKARAGA' },
                { id: 51225, name: 'KAIJA' },
                { id: 51224, name: 'KARONGO' },
                { id: 51227, name: 'KASEKERE A' },
                { id: 51228, name: 'KASEKERE B' },
                { id: 51223, name: 'KIBAMBALI' },
                { id: 51226, name: 'KIBANDA' },
                { id: 51229, name: 'KIBIRA' },
                { id: 51230, name: 'KIJUNJU' },
                { id: 51231, name: 'KYAMUTAGOBWA' },
                { id: 51232, name: 'MPUNA' },
                { id: 51233, name: 'MUSABWE' },
                { id: 51234, name: 'NGANGI' },
                { id: 51235, name: 'NGATA' },
              ],
            },
            {
              id: 8270,
              name: 'KYEGEGWA WARD',
              villages: [
                { id: 51242, name: 'BUTERA' },
                { id: 51236, name: 'BYEBA' },
                { id: 51237, name: 'HAISAZA' },
                { id: 51243, name: 'HUMURA' },
                { id: 51241, name: 'KAKO' },
                { id: 51238, name: 'KASAMBYA' },
                { id: 51239, name: 'KASENENE' },
                { id: 51245, name: 'KIGANDO' },
                { id: 51248, name: 'KIRANZI' },
                { id: 51240, name: 'KYAKAKWANZI' },
                { id: 51249, name: 'KYEGEGWA' },
                { id: 51244, name: 'NSONDAITANO' },
                { id: 51246, name: 'NYANGA' },
                { id: 51247, name: 'RWERA' },
                { id: 51250, name: 'RWOBUNYONYI' },
                { id: 51251, name: 'WEKOMIRE' },
              ],
            },
            {
              id: 8268,
              name: 'NKAAKA WARD',
              villages: [
                { id: 51211, name: 'GALIRAYA' },
                { id: 51214, name: 'KACUMBI' },
                { id: 51212, name: 'KANKUBA' },
                { id: 51216, name: 'KIHONGERWA' },
                { id: 51217, name: 'KIMOKA' },
                { id: 51213, name: 'KYARWEMERA' },
                { id: 51215, name: 'KYARWETABA' },
                { id: 51218, name: 'NKAAKA' },
                { id: 51219, name: 'NYAMIGISA' },
                { id: 51220, name: 'RWAMIIJO' },
              ],
            },
            {
              id: 8271,
              name: 'NYAMUHANAMI WARD',
              villages: [
                { id: 51253, name: 'BUHUNGA' },
                { id: 51252, name: 'KATENTE' },
                { id: 51254, name: 'KIHUNGA' },
                { id: 51255, name: 'MITWEYANKOKO' },
                { id: 51256, name: 'MUSOMBA' },
                { id: 51257, name: 'NYAMUHANAMI' },
                { id: 51258, name: 'RUKUNYU' },
                { id: 51259, name: 'RUTOMA' },
              ],
            },
          ],
        },
        {
          id: 1745,
          name: 'MIGONGWE',
          parishes: [
            {
              id: 8278,
              name: 'KIGORANI',
              villages: [
                { id: 51311, name: 'BULINGO' },
                { id: 51315, name: 'KIBANI' },
                { id: 51316, name: 'KYABYAKWAGA' },
                { id: 51314, name: 'KYARWISAMBA' },
                { id: 67997, name: 'NYAKABUNGO' },
                { id: 68151, name: 'NYAMIGISA' },
                { id: 69968, name: 'RUSAMBYA' },
                { id: 51313, name: 'RUTOMA' },
                { id: 70032, name: 'RWABATEGURA' },
                { id: 51312, name: 'RWENYUNYUZI' },
              ],
            },
            {
              id: 8276,
              name: 'KISOIRA',
              villages: [
                { id: 51303, name: 'KIHUNA' },
                { id: 51301, name: 'KIKUBA' },
                { id: 51299, name: 'KISOIRA' },
                { id: 51300, name: 'KYABIGUGU' },
                { id: 51304, name: 'KYAKATAHA' },
                { id: 64641, name: 'KYAMUGONDA' },
                { id: 51302, name: 'NYABAGAHYA' },
              ],
            },
            {
              id: 8277,
              name: 'KYANKUNYULE',
              villages: [
                { id: 51305, name: 'KAROKARUNGI' },
                { id: 51309, name: 'KIGORANI' },
                { id: 51310, name: 'KYANKUNYULE A' },
                { id: 51308, name: 'KYANKUNYULE B' },
                { id: 66279, name: 'MIRAMA' },
                { id: 51306, name: 'MUYENGA' },
                { id: 67925, name: 'NYABUBARE' },
                { id: 51307, name: 'RUSAMBYA' },
              ],
            },
            {
              id: 8275,
              name: 'MIGONGWE',
              villages: [
                { id: 51293, name: 'KAKONGORANO' },
                { id: 51294, name: 'KALIBWOYA' },
                { id: 51295, name: 'KARAMA' },
                { id: 62993, name: 'KASORRO' },
                { id: 51290, name: 'KATOOKE' },
                { id: 51291, name: 'KIJAARA' },
                { id: 51296, name: 'KYAKABAMBA' },
                { id: 51297, name: 'KYEMA' },
                { id: 51292, name: 'KYERENGA' },
                { id: 51298, name: 'MIGONGWE' },
                { id: 66302, name: 'MIRYANTE' },
              ],
            },
          ],
        },
        {
          id: 1742,
          name: 'NKAAKWA',
          parishes: [
            {
              id: 8264,
              name: 'ISUNGA',
              villages: [
                { id: 51199, name: 'ISUNGA A' },
                { id: 61687, name: 'ISUNGA B' },
                { id: 63357, name: 'KIBENGO' },
                { id: 64038, name: 'KITEREDE' },
                { id: 51200, name: 'KYABIGWIRE A' },
                { id: 64499, name: 'KYABIGWIRE B' },
                { id: 51201, name: 'KYAMUGUNGU A' },
                { id: 64644, name: 'KYAMUGUNGU B' },
              ],
            },
            {
              id: 8265,
              name: 'KAINGANI',
              villages: [
                { id: 51202, name: 'KAINGANI' },
                { id: 63115, name: 'KATOKYE' },
                { id: 66753, name: 'MUZIIZI' },
                { id: 67877, name: 'NTUSI' },
                { id: 68008, name: 'NYAKAGONGO' },
                { id: 69439, name: 'PABU' },
                { id: 51203, name: 'RWENTULEGE' },
              ],
            },
            {
              id: 8266,
              name: 'LYARUHINDA',
              villages: [
                { id: 51204, name: 'BUBISI A' },
                { id: 59216, name: 'BUBISI B' },
                { id: 60358, name: 'BUSINGE' },
                { id: 61511, name: 'HAMUKINGA' },
                { id: 64566, name: 'KYAKASUNDARA' },
                { id: 51206, name: 'LYARUHINDA' },
                { id: 51207, name: 'NYABWINGIRI' },
                { id: 51205, name: 'RWENGO' },
                { id: 70220, name: 'RWENYUNYUZI' },
              ],
            },
            {
              id: 8267,
              name: 'NKAAKWA',
              villages: [
                { id: 60458, name: 'BUTEREVU A' },
                { id: 60459, name: 'BUTEREVU B' },
                { id: 51210, name: 'BUZOOBA' },
                { id: 51208, name: 'KIHOMPORO' },
                { id: 64602, name: 'KYAMAGANDAZI' },
                { id: 64658, name: 'KYAMUSOGA' },
                { id: 66167, name: 'MAYUMBA' },
                { id: 51209, name: 'NKAAKWA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 268,
      name: 'KYAKA SOUTH COUNTY',
      sub_counties: [
        {
          id: 1749,
          name: 'KAZINGA TOWN COUNCIL',
          parishes: [
            {
              id: 8290,
              name: 'KAZINGA WARD',
              villages: [
                { id: 59392, name: 'BUHUMURIRO' },
                { id: 51377, name: 'KARURUMA' },
                { id: 51380, name: 'KAZINGA A' },
                { id: 51381, name: 'KAZINGA B' },
                { id: 51378, name: 'KAZINGA CENTRAL' },
                { id: 51379, name: 'KIJANAMIGANDA' },
              ],
            },
            {
              id: 8291,
              name: 'RUSHAYUMBE WARD',
              villages: [
                { id: 61237, name: 'EKYISHOZI' },
                { id: 61527, name: 'HUMURA' },
                { id: 62257, name: 'KAKUKURU' },
                { id: 51383, name: 'KAKUNYU' },
                { id: 51384, name: 'KANYAITEEKA' },
                { id: 51382, name: 'KITEMBA' },
                { id: 66587, name: 'MULISATU' },
                { id: 67943, name: 'NYABUTALE' },
                { id: 51385, name: 'RUSAYUMBE' },
              ],
            },
            {
              id: 8292,
              name: 'RUTARAKA WARD',
              villages: [
                { id: 51387, name: 'BUHEMBE' },
                { id: 60232, name: 'BUREMBO' },
                { id: 60362, name: 'BUSINGYE' },
                { id: 61575, name: 'IHAHURA' },
                { id: 62599, name: 'KANYINYA' },
                { id: 63569, name: 'KIHUMURO' },
                { id: 51386, name: 'KYERISHO' },
                { id: 64821, name: 'KYERUNGA' },
                { id: 65821, name: 'MABALE' },
                { id: 51389, name: 'RUTARAKA A' },
                { id: 51388, name: 'RUTARAKA B' },
              ],
            },
          ],
        },
        {
          id: 1751,
          name: 'KYEGEGWA',
          parishes: [
            {
              id: 8302,
              name: 'BULINGO',
              villages: [
                { id: 51445, name: 'BULINGO A' },
                { id: 51444, name: 'BULINGO B' },
                { id: 51446, name: 'BWEYALE' },
                { id: 51449, name: 'ISANGA A' },
                { id: 51448, name: 'ISANGA B' },
                { id: 51450, name: 'KICHWAMBA' },
                { id: 51447, name: 'KIRYANDONGO' },
                { id: 51451, name: 'MAIRA' },
              ],
            },
            {
              id: 8299,
              name: 'KABWEZA',
              villages: [
                { id: 51409, name: 'BUKERE' },
                { id: 51413, name: 'BUSASI' },
                { id: 51416, name: 'BWAKAHINDA' },
                { id: 51415, name: 'ITAMBABINIGA' },
                { id: 51410, name: 'KABWEZA' },
                { id: 51411, name: 'KYAKATWANGA' },
                { id: 51414, name: 'MPASANA' },
                { id: 51412, name: 'MUHANGI' },
              ],
            },
            {
              id: 8300,
              name: 'KIBUYE',
              villages: [
                { id: 51417, name: 'BUTOOKE' },
                { id: 51431, name: 'GALIBOLEKA' },
                { id: 51419, name: 'KANYINYA' },
                { id: 51423, name: 'KIBUYE' },
                { id: 51421, name: 'KITENDE' },
                { id: 51428, name: 'KIYUGUYA' },
                { id: 51422, name: 'KYEBANDO' },
                { id: 51420, name: 'LYANYOGOLI' },
                { id: 51426, name: 'LYENFUKA' },
                { id: 51427, name: 'MITOMA' },
                { id: 51430, name: 'NDAMA' },
                { id: 51424, name: 'NGAIJA' },
                { id: 51432, name: 'NYANTARAGUZA' },
                { id: 51425, name: 'RUBONA' },
                { id: 51418, name: 'RUKAGATE' },
                { id: 51429, name: 'RUTUNGU' },
              ],
            },
            {
              id: 8301,
              name: 'KIHAMBA',
              villages: [
                { id: 51433, name: 'BARANYWA' },
                { id: 51436, name: 'HAIRWE' },
                { id: 51442, name: 'KABALE' },
                { id: 51438, name: 'KAJUMA' },
                { id: 51434, name: 'KASUNGA' },
                { id: 51440, name: 'KIHAMBA' },
                { id: 51441, name: 'KINYINYA' },
                { id: 51443, name: 'KYEMPURA' },
                { id: 51435, name: 'MBINDO' },
                { id: 51437, name: 'MITOMA' },
                { id: 51439, name: 'NKONGE' },
              ],
            },
            {
              id: 8303,
              name: 'SWESWE',
              villages: [
                { id: 51460, name: 'BUSINGE' },
                { id: 51455, name: 'IGANDA' },
                { id: 51453, name: 'KAHE' },
                { id: 51456, name: 'KAKINDO' },
                { id: 51458, name: 'KANYEGARAMIRE' },
                { id: 51454, name: 'KINONI' },
                { id: 51452, name: 'NYABURUNGI' },
                { id: 51459, name: 'ORUKINGA' },
                { id: 51457, name: 'SWESWE' },
              ],
            },
          ],
        },
        {
          id: 1750,
          name: 'MIGAMBA',
          parishes: [
            {
              id: 8295,
              name: 'KAHUNGURA',
              villages: [
                { id: 61526, name: 'HUMURA' },
                { id: 61826, name: 'KAARO' },
                { id: 51395, name: 'KAHUNGURA' },
                { id: 62271, name: 'KAKYINDO' },
                { id: 64036, name: 'KITEREDE' },
                { id: 67917, name: 'NYABITOOMA' },
                { id: 51396, name: 'NYAKATOMA' },
              ],
            },
            {
              id: 8293,
              name: 'KASABANWA',
              villages: [
                { id: 59391, name: 'BUHUMURIRO' },
                { id: 51390, name: 'KASABANWA' },
                { id: 63667, name: 'KIKOTO' },
                { id: 64122, name: 'KIVAKEDO' },
                { id: 67907, name: 'NYABIRUNGI' },
              ],
            },
            {
              id: 8297,
              name: 'KITEMBE',
              villages: [
                { id: 62966, name: 'KASIKIZI' },
                { id: 51402, name: 'KITEMBE I' },
                { id: 51403, name: 'KITEMBE II' },
                { id: 64061, name: 'KITOKYE' },
                { id: 66288, name: 'MIRAMBI' },
                { id: 51404, name: 'RWEMIRAMA' },
              ],
            },
            {
              id: 8298,
              name: 'MIGAMBA',
              villages: [
                { id: 61708, name: 'ITORORO' },
                { id: 51408, name: 'KAGADI' },
                { id: 51406, name: 'KAKO' },
                { id: 64538, name: 'KYAKAHWA' },
                { id: 64618, name: 'KYAMATURO' },
                { id: 51405, name: 'MIGAMBA' },
                { id: 51407, name: 'RWAKITURA' },
                { id: 70105, name: 'RWEBIHORA' },
                { id: 70224, name: 'RWERERE' },
              ],
            },
            {
              id: 8294,
              name: 'NSONGA',
              villages: [
                { id: 60785, name: 'BWERANYANGE' },
                { id: 61365, name: 'GERUNDA' },
                { id: 51392, name: 'KENYANA' },
                { id: 51393, name: 'KIGANGA' },
                { id: 63679, name: 'KIKUNYU' },
                { id: 51391, name: 'KISUULI' },
                { id: 66773, name: 'MWITANGUNDU' },
                { id: 51394, name: 'NSONGA' },
                { id: 68058, name: 'NYAKASOZI' },
              ],
            },
            {
              id: 8296,
              name: 'SOOBA',
              villages: [
                { id: 51397, name: 'BWEERA' },
                { id: 51399, name: 'KAGOMA' },
                { id: 62542, name: 'KANKUNGU' },
                { id: 66183, name: 'MBALE I' },
                { id: 66184, name: 'MBALE II' },
                { id: 67980, name: 'NYAKABINGO' },
                { id: 51401, name: 'RUKIIZI' },
                { id: 51398, name: 'RWEMBURARA' },
                { id: 51400, name: 'SOOBA' },
              ],
            },
          ],
        },
        {
          id: 1752,
          name: 'MPARA',
          parishes: [
            {
              id: 8305,
              name: 'KIBAALE',
              villages: [
                { id: 57737, name: 'AKARAMA' },
                { id: 51469, name: 'KABUNDAIRE' },
                { id: 51468, name: 'KABURAISOKE' },
                { id: 51467, name: 'KIBAALE' },
                { id: 67875, name: 'NTUNTU' },
                { id: 70188, name: 'RWENSAMBYA' },
              ],
            },
            {
              id: 8306,
              name: 'KIRYABYOOMA',
              villages: [
                { id: 51470, name: 'KATAGIIBWA' },
                { id: 51471, name: 'KIRYABYOMA' },
                { id: 66079, name: 'MASENGA' },
                { id: 66170, name: 'MAZINGA' },
                { id: 68083, name: 'NYAKATOOKE WEST' },
              ],
            },
            {
              id: 8307,
              name: 'NYAKATOMA',
              villages: [
                { id: 51476, name: 'BIDWOOLI' },
                { id: 60224, name: 'BURANGA' },
                { id: 51477, name: 'KACUNGIRO' },
                { id: 51472, name: 'KAHUNGERA' },
                { id: 51475, name: 'KYESEGA' },
                { id: 51473, name: 'KYESEGA B' },
                { id: 51474, name: 'MPEWERE' },
                { id: 66518, name: 'MUKASOJO' },
                { id: 51478, name: 'NYAKATOMA' },
              ],
            },
            {
              id: 8304,
              name: 'RWAHUNGA',
              villages: [
                { id: 51466, name: 'IRINGA A' },
                { id: 51463, name: 'IRINGA B' },
                { id: 51464, name: 'IRINGA C' },
                { id: 51462, name: 'KIJWIIGA' },
                { id: 51461, name: 'KIKALITUNSI' },
                { id: 66678, name: 'MUSANJU WEST' },
                { id: 51465, name: 'RWAHUNGA' },
              ],
            },
          ],
        },
        {
          id: 1748,
          name: 'MPARA TOWN COUNCIL',
          parishes: [
            {
              id: 8288,
              name: 'BUGIDO WARD',
              villages: [
                { id: 51369, name: 'BUGIDO' },
                { id: 60775, name: 'BWENJERU' },
                { id: 51371, name: 'KAROKARUNGI' },
                { id: 63507, name: 'KIGOIGO' },
                { id: 64502, name: 'KYABIKYA' },
                { id: 51370, name: 'KYAMUTYETYE' },
                { id: 69988, name: 'RUTAALI' },
              ],
            },
            {
              id: 8285,
              name: 'KISAMBYA WARD',
              villages: [
                { id: 51358, name: 'BARWENDA' },
                { id: 51354, name: 'KIJIIBI' },
                { id: 51359, name: 'KISAMBYA' },
                { id: 51360, name: 'KITABOMBA' },
                { id: 51355, name: 'KYAKIKOYO' },
                { id: 51356, name: 'KYEGANGA' },
                { id: 51357, name: 'KYEGAYUKE' },
                { id: 51353, name: 'KYEZITIRA' },
                { id: 70181, name: 'RWENKUBA' },
              ],
            },
            {
              id: 8289,
              name: 'MPARA WARD',
              villages: [
                { id: 64516, name: 'KYABULIKARAARA' },
                { id: 51374, name: 'KYAMABAALE' },
                { id: 64672, name: 'KYANDARA' },
                { id: 51373, name: 'KYARWONZIRA' },
                { id: 51375, name: 'MPARA A' },
                { id: 51372, name: 'MPARA CENTRAL' },
                { id: 51376, name: 'NYAKASAKA' },
              ],
            },
            {
              id: 8286,
              name: 'MUSANJU WARD',
              villages: [
                { id: 51362, name: 'KAROKARUNGI' },
                { id: 51361, name: 'KIJUNJU EAST' },
                { id: 63621, name: 'KIJUNJU SOUTH' },
                { id: 63622, name: 'KIJUNJU WEST' },
                { id: 64583, name: 'KYAKIIZA' },
                { id: 64792, name: 'KYEMENGO' },
                { id: 66439, name: 'MPARA B' },
                { id: 66677, name: 'MUSANJU EAST' },
                { id: 51363, name: 'MUSANJU SUB-CENTRAL' },
                { id: 51364, name: 'NYAKATOKE' },
              ],
            },
            {
              id: 8287,
              name: 'NSONDAITANO WARD',
              villages: [
                { id: 51365, name: 'BAHURA' },
                { id: 62204, name: 'KAKINDO' },
                { id: 51367, name: 'KISORORA' },
                { id: 51368, name: 'NSONDAITANO' },
                { id: 69233, name: 'ORUTOOMA' },
                { id: 51366, name: 'RWEMITWARO' },
              ],
            },
          ],
        },
        {
          id: 1755,
          name: 'NKANJA',
          parishes: [
            {
              id: 8319,
              name: 'BUJUBULI',
              villages: [
                { id: 59411, name: 'BUJUBULI CENTRAL' },
                { id: 51542, name: 'BUJUBULI EAST' },
                { id: 51543, name: 'BUJUBULI WEST' },
                { id: 51541, name: 'IJUGANGOMA' },
                { id: 61591, name: 'IJUGANGOMA EAST' },
                { id: 70003, name: 'RUTOOMA' },
              ],
            },
            {
              id: 8320,
              name: 'KAKONI',
              villages: [
                { id: 51545, name: 'KAKONI A' },
                { id: 51544, name: 'KAKONI C' },
                { id: 62774, name: 'KARAMBI' },
                { id: 62832, name: 'KAROKARUNGI' },
              ],
            },
            {
              id: 8321,
              name: 'KYABULIKUYA',
              villages: [
                { id: 62202, name: 'KAKINDO' },
                { id: 51549, name: 'KAKONI B' },
                { id: 51548, name: 'KYABULIKUYA' },
                { id: 64543, name: 'KYAKAKOTOKA' },
                { id: 51546, name: 'NKANJA A' },
                { id: 51547, name: 'NKANJA B' },
              ],
            },
            {
              id: 8322,
              name: 'KYAMAGABU',
              villages: [
                { id: 62821, name: 'KAROKARUNGI' },
                { id: 63673, name: 'KIKUMBWE' },
                { id: 51553, name: 'KIRANDA' },
                { id: 64520, name: 'KYABWARAMA' },
                { id: 51550, name: 'KYAKALINZI' },
                { id: 51552, name: 'KYAMAGABU' },
                { id: 66668, name: 'MURUSEESE' },
                { id: 51551, name: 'MUTOOKE' },
                { id: 67669, name: 'NDARAGI' },
                { id: 67950, name: 'NYABWISIKI' },
              ],
            },
          ],
        },
        {
          id: 1753,
          name: 'RUYONZA',
          parishes: [
            {
              id: 8308,
              name: 'KARWENYI',
              villages: [
                { id: 51480, name: 'KAJUMBURA' },
                { id: 51485, name: 'KARWENYI TRADING CENTRE' },
                { id: 51481, name: 'KATARUBATA' },
                { id: 51482, name: 'KYAKWEZI' },
                { id: 51487, name: 'KYANYANGOMA A' },
                { id: 51486, name: 'KYANYANGOMA B' },
                { id: 51483, name: 'KYENTALE' },
                { id: 51479, name: 'RWABANYWA' },
                { id: 51484, name: 'RWEMBOGO' },
              ],
            },
            {
              id: 8310,
              name: 'KATIIRWE',
              villages: [
                { id: 51496, name: 'AKOOMA A' },
                { id: 51497, name: 'AKOOMA B' },
                { id: 51500, name: 'KATIIRWE' },
                { id: 51501, name: 'MUGAAJU' },
                { id: 51499, name: 'RUTERWA' },
                { id: 51498, name: 'RWENGENYI' },
              ],
            },
            {
              id: 8309,
              name: 'KIJONGOBYA',
              villages: [
                { id: 51489, name: 'KAMUTUMI' },
                { id: 51490, name: 'KASIKIZI' },
                { id: 51491, name: 'KATETE' },
                { id: 51488, name: 'KIHUMURO' },
                { id: 51492, name: 'KIJONGOBYA' },
                { id: 51493, name: 'KISOOJO' },
                { id: 51495, name: 'KYAKASAMBA' },
                { id: 51494, name: 'RUHOKO' },
              ],
            },
            {
              id: 8311,
              name: 'KIREMBA',
              villages: [
                { id: 51502, name: 'KIJWAJWA' },
                { id: 51506, name: 'KIREGANI' },
                { id: 51503, name: 'KIREMBA' },
                { id: 51504, name: 'MASOORO' },
                { id: 51505, name: 'RUYONZA' },
              ],
            },
            {
              id: 8312,
              name: 'KISHAGAZI',
              villages: [
                { id: 51510, name: 'BYISINGOMA' },
                { id: 51507, name: 'KAYONZA' },
                { id: 51508, name: 'KISAGAZI EAST' },
                { id: 51509, name: 'KISAGAZI WEST' },
                { id: 51511, name: 'MIREMBE' },
              ],
            },
          ],
        },
        {
          id: 1754,
          name: 'RWENTUHA',
          parishes: [
            {
              id: 8313,
              name: 'KABARABA',
              villages: [
                { id: 51512, name: 'KABARABA' },
                { id: 51514, name: 'KAKYINDO A' },
                { id: 51516, name: 'KASOMORO' },
                { id: 65827, name: 'MABALE GIRAGURA' },
                { id: 51515, name: 'MULEJU' },
                { id: 67977, name: 'NYAKABINGO' },
                { id: 51513, name: 'NYANGABO' },
                { id: 70070, name: 'RWAMASONGORA' },
                { id: 70152, name: 'RWEMISUNUNU' },
              ],
            },
            {
              id: 8314,
              name: 'KYARUJUMBA',
              villages: [
                { id: 51520, name: 'BUKARAGYI' },
                { id: 51518, name: 'KYARUJUMBA A' },
                { id: 64715, name: 'KYARUJUMBA B' },
                { id: 51517, name: 'NYABUBAALE' },
                { id: 69228, name: 'ORUSHASHA' },
                { id: 51519, name: 'RUBIRIZI' },
              ],
            },
            {
              id: 8315,
              name: 'KYESHOMBIRE',
              villages: [
                { id: 57708, name: 'AKAGYERA' },
                { id: 51522, name: 'BUGARAMA' },
                { id: 51523, name: 'KAJUMIKA' },
                { id: 62826, name: 'KAROKARUNGI' },
                { id: 51524, name: 'KIBINGO' },
                { id: 64158, name: 'KIZINDA' },
                { id: 64716, name: 'KYARUKARA' },
                { id: 51521, name: 'KYESOMBIRE' },
                { id: 66315, name: 'MITOMA' },
                { id: 68209, name: 'NYANGA' },
                { id: 51525, name: 'RWIBALE' },
              ],
            },
            {
              id: 8318,
              name: 'NGANGI',
              villages: [
                { id: 57748, name: 'AKASOJWA' },
                { id: 61259, name: 'ENJOJO' },
                { id: 62831, name: 'KAROKARUNGI' },
                { id: 51536, name: 'KASHASHA' },
                { id: 63111, name: 'KATOJO' },
                { id: 64537, name: 'KYAKAHURERE' },
                { id: 51537, name: 'KYANIKA' },
                { id: 66515, name: 'MUKARA' },
                { id: 51538, name: 'NGANGI' },
                { id: 51540, name: 'NTUNGAMO' },
                { id: 69020, name: 'OMURIBIRI' },
                { id: 51539, name: 'RUSORORA' },
              ],
            },
            {
              id: 8316,
              name: 'RUHANGIRE',
              villages: [
                { id: 57766, name: 'AKAYEMBE' },
                { id: 51526, name: 'BUJUNJURA' },
                { id: 51527, name: 'KINOMBE' },
                { id: 63829, name: 'KIRUHURA' },
                { id: 66292, name: 'MIREMBE' },
                { id: 66504, name: 'MUHUMURE' },
                { id: 51528, name: 'RUHANGIRE' },
                { id: 70139, name: 'RWEMIKINDO' },
              ],
            },
            {
              id: 8317,
              name: 'RWENTUHA',
              villages: [
                { id: 60319, name: 'BUSHENYI' },
                { id: 51531, name: 'IMARANJARA' },
                { id: 51532, name: 'KAFOODA' },
                { id: 51533, name: 'KAKYINDO B' },
                { id: 51529, name: 'KARUBAGIMBA' },
                { id: 64057, name: 'KITOKE A' },
                { id: 64059, name: 'KITOKOME' },
                { id: 51535, name: 'MUKICERE' },
                { id: 68073, name: 'NYAKATOKE' },
                { id: 51534, name: 'RWEMIRAMA' },
                { id: 51530, name: 'RWENTUHA' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
