import { District } from '../types';

export default {
  id: 76,
  name: 'KYENJOJO',
  counties: [
    {
      id: 188,
      name: 'MWENGE CENTRAL COUNTY',
      sub_counties: [
        {
          id: 1160,
          name: 'BUGAAKI',
          parishes: [
            {
              id: 5375,
              name: 'BUSASA',
              villages: [
                { id: 34131, name: 'BUSASA' },
                { id: 34132, name: 'BUSASA B' },
                { id: 34133, name: 'KABIRIZI' },
                { id: 34130, name: 'KARONGO-NYAMISISA' },
                { id: 34134, name: 'KIREGYA' },
              ],
            },
            {
              id: 5378,
              name: 'BUTARA',
              villages: [
                { id: 34143, name: 'BUHEMBA' },
                { id: 34144, name: 'BUTARA' },
                { id: 34145, name: 'KINYERRE' },
                { id: 34146, name: 'NYAKATOMA' },
                { id: 34147, name: 'NYARUTOMA' },
              ],
            },
            {
              id: 5370,
              name: 'HIIMA',
              villages: [
                { id: 34095, name: 'KAGOROGORO' },
                { id: 34096, name: 'KIRONGO' },
                { id: 34097, name: 'KYAKIROORO' },
                { id: 34098, name: 'KYERAGIRA/ KYAMAHINDA' },
                { id: 34099, name: 'NTOROKO RD' },
                { id: 34100, name: 'NYABITOJO' },
                { id: 34101, name: 'RWABAGANDA' },
              ],
            },
            {
              id: 5376,
              name: 'KANYAMUKWAYA',
              villages: [
                { id: 34136, name: 'KIHOIGA' },
                { id: 34135, name: 'KYANYAMUKWAYA' },
                { id: 34137, name: 'MABALE FACTORY' },
                { id: 34138, name: 'MABALE/MUGUSU' },
              ],
            },
            {
              id: 5377,
              name: 'KASAMBA',
              villages: [
                { id: 34139, name: 'BYARA' },
                { id: 60820, name: 'BYARA B' },
                { id: 34140, name: 'KASAMBA' },
                { id: 34141, name: 'KASOZI' },
                { id: 34142, name: 'KASUNGA' },
              ],
            },
            {
              id: 5371,
              name: 'KASENYI',
              villages: [
                { id: 34102, name: 'BWASIRI' },
                { id: 34103, name: 'KASENYI' },
                { id: 34104, name: 'KATOOKE' },
                { id: 34105, name: 'KYANSANGI' },
                { id: 64750, name: 'KYAWAAKO' },
                { id: 34106, name: 'MABAALE/KYAWAAKO' },
              ],
            },
            {
              id: 5379,
              name: 'KYABAGONZA',
              villages: [
                { id: 34148, name: 'KISAMUTONGOLE' },
                { id: 34149, name: 'KYABAGONZA' },
                { id: 34150, name: 'MAHANGWE' },
                { id: 34151, name: 'NYANJAETAGERA' },
              ],
            },
            {
              id: 5372,
              name: 'KYABARANGA',
              villages: [
                { id: 34107, name: 'BUHUMBA' },
                { id: 34108, name: 'IJUMANYANZA' },
                { id: 34109, name: 'KASOJO/ NYAMASOGA' },
                { id: 34110, name: 'KATIBA' },
                { id: 34111, name: 'KITWA/KIDUKURU' },
              ],
            },
            {
              id: 5373,
              name: 'MITOMA',
              villages: [
                { id: 34113, name: 'BUKOIKO' },
                { id: 34112, name: 'BUTALE' },
                { id: 34114, name: 'KAHUNGERA' },
                { id: 34115, name: 'KYABOROBYA' },
                { id: 34116, name: 'KYAIRUMBA' },
                { id: 34117, name: 'KYAKAIRAGURA' },
                { id: 34118, name: 'MITOMA' },
              ],
            },
            {
              id: 5374,
              name: 'NYAMABUGA',
              villages: [
                { id: 34119, name: 'BURAGO' },
                { id: 34121, name: 'ISUNGA' },
                { id: 34122, name: 'KATIKARA' },
                { id: 34123, name: 'KICUUCU' },
                { id: 34124, name: 'KISANGI' },
                { id: 34125, name: 'MASESE' },
                { id: 34126, name: 'MIRAMBI' },
                { id: 34120, name: 'NTENGO' },
                { id: 34128, name: 'NYABANDA' },
                { id: 34127, name: 'NYANKOKO' },
                { id: 34129, name: 'RWERA' },
              ],
            },
            {
              id: 5380,
              name: 'RUGOMBE TOWN BOARD',
              villages: [
                { id: 34154, name: 'KIKOKWA' },
                { id: 34153, name: 'MIHONDO' },
                { id: 34155, name: 'NYAKATOOKE' },
                { id: 34156, name: 'RUGOMBE T/C' },
                { id: 34152, name: 'RUGOMBE/KASOZI' },
              ],
            },
          ],
        },
        {
          id: 1161,
          name: 'KATOOKE',
          parishes: [
            {
              id: 5381,
              name: 'BWAHURRO',
              villages: [
                { id: 34157, name: 'BWAHURRO' },
                { id: 34161, name: 'HARWOMA' },
                { id: 34158, name: 'KIGABU' },
                { id: 34159, name: 'KYARUJANJI' },
                { id: 64812, name: 'KYENTALE' },
                { id: 34160, name: 'NYAKATI' },
              ],
            },
            {
              id: 5382,
              name: 'KIJWIGA',
              villages: [
                { id: 34162, name: 'KANYAMAIZI' },
                { id: 34164, name: 'KIJWIGA' },
                { id: 34163, name: 'KIRENDU' },
                { id: 34165, name: 'NYARUTUNTU' },
                { id: 34166, name: 'RWAKIRAITA' },
              ],
            },
            {
              id: 5384,
              name: 'KINOGERO',
              villages: [
                { id: 34172, name: 'KINOGERO I' },
                { id: 34173, name: 'KINOGERO II' },
                { id: 34174, name: 'NYARWINA' },
                { id: 34175, name: 'RUKIZI I' },
                { id: 34176, name: 'RUKIZI II' },
              ],
            },
            {
              id: 5387,
              name: 'KITONYA',
              villages: [
                { id: 34186, name: 'KADIKI' },
                { id: 34187, name: 'KALYABUHIIRE' },
                { id: 34189, name: 'KIBENGA' },
                { id: 34188, name: 'KIJUGO' },
                { id: 64533, name: 'KYAKAGORO' },
                { id: 34190, name: 'MUHORRO I' },
              ],
            },
            {
              id: 5383,
              name: 'KYAKABOYO',
              villages: [
                { id: 34167, name: 'HAIKONA' },
                { id: 34170, name: 'KAIGANGA' },
                { id: 34168, name: 'KIGUUZA' },
                { id: 34169, name: 'KYAKABOYO' },
                { id: 65804, name: 'LYAMUGUMBA' },
                { id: 34171, name: 'NYAMWANDARA' },
              ],
            },
            {
              id: 5385,
              name: 'MYERI',
              villages: [
                { id: 62620, name: 'KANYWAMBUGA' },
                { id: 34177, name: 'KASOGA' },
                { id: 63611, name: 'KIJUBIKA' },
                { id: 34178, name: 'MUHORRO II' },
                { id: 34179, name: 'MYERI' },
                { id: 34180, name: 'NKERA' },
              ],
            },
            {
              id: 5386,
              name: 'RWAMUKORA',
              villages: [
                { id: 34181, name: 'ICWAMUKONO' },
                { id: 34183, name: 'KYEJUMBA' },
                { id: 34182, name: 'NKINGA' },
                { id: 67927, name: 'NYABUGANDO' },
                { id: 34184, name: 'RWAMUKOORA' },
                { id: 34185, name: 'RWENSINGA' },
              ],
            },
          ],
        },
        {
          id: 1163,
          name: 'KATOOKE TOWN COUNCIL',
          parishes: [
            {
              id: 5395,
              name: 'IBOROOGA WARD',
              villages: [
                { id: 63129, name: 'KATOOKE/KYAWAAKO' },
                { id: 34221, name: 'KIBUGA LOWER' },
                { id: 63390, name: 'KIBUGA UPPER' },
                { id: 34220, name: 'RWENGAAJU' },
              ],
            },
            {
              id: 5394,
              name: 'KAKUBA WARD',
              villages: [
                { id: 34216, name: 'BULENGE' },
                { id: 62127, name: 'KAHANDA' },
                { id: 34217, name: 'KAKUBA' },
                { id: 34218, name: 'KYABIRANJU' },
                { id: 34219, name: 'RWEBOHA' },
              ],
            },
            {
              id: 5396,
              name: 'KATARA WARD',
              villages: [
                { id: 34222, name: 'KATARA' },
                { id: 34223, name: 'KIGUNGA' },
                { id: 34224, name: 'KITWETWE' },
                { id: 34225, name: 'MPONGO' },
              ],
            },
            {
              id: 5397,
              name: 'KATOOKE WARD',
              villages: [
                { id: 63128, name: 'KATOOKE B' },
                { id: 34228, name: 'KATOOKE T.C' },
                { id: 34227, name: 'KATOOKE/KYAWAAKO' },
                { id: 34226, name: 'KYASEMU' },
              ],
            },
            {
              id: 5398,
              name: 'KYANYABONGO WARD',
              villages: [
                { id: 34230, name: 'KATEMBE A' },
                { id: 34231, name: 'KATEMBE B' },
                { id: 34229, name: 'KYANYABONGO' },
                { id: 34232, name: 'MUKOLE' },
              ],
            },
            {
              id: 5393,
              name: 'MWARO WARD',
              villages: [
                { id: 34213, name: 'MWARO A' },
                { id: 34214, name: 'MWARO B' },
                { id: 34215, name: 'NYABIHOMA' },
              ],
            },
          ],
        },
        {
          id: 1162,
          name: 'KYARUSOZI',
          parishes: [
            {
              id: 5388,
              name: 'BARAHIIJA',
              villages: [
                { id: 34191, name: 'BARAHIIJA' },
                { id: 34196, name: 'IBAALE' },
                { id: 34192, name: 'KYARUKOMI' },
                { id: 64814, name: 'KYENTANGA' },
                { id: 34193, name: 'MITOMA KYATURUCUMITA' },
                { id: 34195, name: 'MITOMA-KIBIMBA' },
                { id: 66316, name: 'MITOMA-KYAAPA' },
                { id: 34194, name: 'NTUNTU' },
              ],
            },
            {
              id: 5389,
              name: 'BINUNDA',
              villages: [
                { id: 34198, name: 'KYAMUTWE' },
                { id: 64783, name: 'KYEMBAMBA' },
                { id: 34200, name: 'NSINDE-KAPUUSASI' },
                { id: 34199, name: 'NSINDE-KIBAYA' },
                { id: 67909, name: 'NYABIRUNGI' },
                { id: 34197, name: 'NYAMBEHO' },
              ],
            },
            {
              id: 5390,
              name: 'KAISAMBA',
              villages: [
                { id: 34202, name: 'KAISAMBA' },
                { id: 34201, name: 'KAISAMBA T/CENTRE' },
                { id: 34204, name: 'KIBAMU' },
                { id: 34203, name: 'KYAKATUMBA' },
                { id: 66189, name: 'MBATA' },
                { id: 67769, name: 'NGOTE' },
              ],
            },
            {
              id: 5391,
              name: 'KYANYINAIBALE',
              villages: [
                { id: 59756, name: 'BULYAMAGURU' },
                { id: 62986, name: 'KASOKERO' },
                { id: 34205, name: 'KIBUGO' },
                { id: 34206, name: 'KYABUKONGE' },
                { id: 34207, name: 'KYANYINAIBAALE' },
                { id: 34208, name: 'RUGWARRA' },
              ],
            },
            {
              id: 5392,
              name: 'KYONGERA',
              villages: [
                { id: 34209, name: 'BIHANGA' },
                { id: 63516, name: 'KIGOOBA' },
                { id: 34210, name: 'KIJUGURA' },
                { id: 34212, name: 'KYONGERA' },
                { id: 34211, name: 'RUBONA' },
                { id: 70160, name: 'RWENDENGE' },
              ],
            },
            { id: 10100, name: 'NSINDE', villages: [] },
          ],
        },
        {
          id: 1164,
          name: 'KYARUSOZI TOWN COUNCIL',
          parishes: [
            {
              id: 5402,
              name: 'BINUNDA WARD',
              villages: [
                { id: 34241, name: 'BINUNDA' },
                { id: 34242, name: 'KYAKAKOGA' },
                { id: 34244, name: 'MAKARRA' },
                { id: 34243, name: 'RWENKUBA' },
              ],
            },
            {
              id: 5399,
              name: 'BUHAZA WARD',
              villages: [
                { id: 34233, name: 'BUHAZA' },
                { id: 34234, name: 'KYANJUBU' },
              ],
            },
            {
              id: 9706,
              name: 'KIHARA WARD',
              villages: [
                { id: 63544, name: 'KIHARA' },
                { id: 64721, name: 'KYARUSOZI  OLD' },
                { id: 64722, name: 'KYARUSOZI  VILLAGE' },
              ],
            },
            {
              id: 9827,
              name: 'KYAMUGENYI WARD',
              villages: [
                { id: 59686, name: 'BULEGEYA' },
                { id: 64639, name: 'KYAMUGENYI' },
                { id: 64674, name: 'KYANGABUKAMA' },
              ],
            },
            {
              id: 5400,
              name: 'KYARUSOZI WARD',
              villages: [
                { id: 34235, name: 'KATOOKE' },
                { id: 34236, name: 'KYARUSOZI T/C' },
              ],
            },
            {
              id: 5401,
              name: 'NYAKITOJO WARD',
              villages: [
                { id: 34238, name: 'KIBAALE' },
                { id: 34239, name: 'KISENYI' },
                { id: 34237, name: 'MWENGE TEA ESTATE' },
                { id: 34240, name: 'NYAKITOJO' },
              ],
            },
          ],
        },
        {
          id: 1159,
          name: 'NYAKISI',
          parishes: [
            {
              id: 5368,
              name: 'ENJERU',
              villages: [
                { id: 34088, name: 'BUKOMBA' },
                { id: 34086, name: 'ENJERU' },
                { id: 34089, name: 'KISANGWA' },
                { id: 34085, name: 'KITAHABUSINGE' },
                { id: 34087, name: 'KYONGO' },
              ],
            },
            {
              id: 5364,
              name: 'KABATOORO',
              villages: [
                { id: 34067, name: 'KABATOORO' },
                { id: 63646, name: 'KIKOKO' },
                { id: 34068, name: 'NYARUTUNTU' },
                { id: 34069, name: 'RUJARAGA' },
              ],
            },
            {
              id: 5369,
              name: 'KAFUNDA',
              villages: [
                { id: 34092, name: 'KAFUNDA' },
                { id: 34093, name: 'KISOJO A' },
                { id: 34094, name: 'KISOJO B' },
                { id: 34090, name: 'MISENYI' },
                { id: 34091, name: 'NYAKATOMA' },
              ],
            },
            {
              id: 5365,
              name: 'KAGORRA',
              villages: [
                { id: 34072, name: 'BUHURA SOUTH' },
                { id: 34070, name: 'KAGORRA A' },
                { id: 34071, name: 'KAGORRA B' },
                { id: 34073, name: 'KYABINYANSI' },
                { id: 34074, name: 'KYAKATULI' },
              ],
            },
            {
              id: 5366,
              name: 'NYAKISI',
              villages: [
                { id: 34076, name: 'KAKONI A' },
                { id: 34075, name: 'KASABUNGO' },
                { id: 34077, name: 'KYANGUKA' },
                { id: 66510, name: 'MUKABENGE' },
                { id: 34078, name: 'RUGONJO' },
              ],
            },
            {
              id: 5367,
              name: 'RUBANGO',
              villages: [
                { id: 62239, name: 'KAKONI A' },
                { id: 34079, name: 'KAKONI B' },
                { id: 34080, name: 'KALIRUGA' },
                { id: 34081, name: 'KIBALE' },
                { id: 34084, name: 'MUJUNA' },
                { id: 34082, name: 'RUBANGO A' },
                { id: 34083, name: 'RUBANGO B' },
              ],
            },
          ],
        },
        {
          id: 2111,
          name: 'RUGOMBE TOWN COUNCIL',
          parishes: [
            {
              id: 9382,
              name: 'BUTARA WARD',
              villages: [
                { id: 59372, name: 'BUHEMBA' },
                { id: 60436, name: 'BUTARA' },
                { id: 68079, name: 'NYAKATOMA' },
                { id: 68261, name: 'NYARUTOMA' },
              ],
            },
            {
              id: 9744,
              name: 'KISANGI WARD',
              villages: [
                { id: 60215, name: 'BURAGO' },
                { id: 61684, name: 'ISUNGA' },
                { id: 63875, name: 'KISANGI' },
                { id: 66286, name: 'MIRAMBI' },
                { id: 66442, name: 'MPARO-MASESE' },
                { id: 68023, name: 'NYAKAKOKO' },
                { id: 70222, name: 'RWERA' },
              ],
            },
            {
              id: 9981,
              name: 'MIHONDO WARD',
              villages: [
                { id: 65900, name: 'MAHANGWE' },
                { id: 66251, name: 'MIHONDO' },
                { id: 68052, name: 'NYAKASI' },
                { id: 68222, name: 'NYANJETAGERA' },
              ],
            },
            {
              id: 10124,
              name: 'NYAMABUGA WARD',
              villages: [
                { id: 59702, name: 'BULIBA' },
                { id: 63093, name: 'KATIKARA' },
                { id: 63422, name: 'KICUUCU' },
                { id: 67859, name: 'NTENGO' },
                { id: 68128, name: 'NYAMABUGA' },
              ],
            },
            {
              id: 10269,
              name: 'RUGOMBE WARD',
              villages: [
                { id: 63647, name: 'KIKOKWA' },
                { id: 63773, name: 'KINYERRE' },
                { id: 68081, name: 'NYAKATOOKE' },
                { id: 69907, name: 'RUGOMBE T/C' },
                { id: 69908, name: 'RUGOMBE/KASOZI' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 186,
      name: 'MWENGE COUNTY NORTH',
      sub_counties: [
        {
          id: 1956,
          name: 'BATALIKA',
          parishes: [
            {
              id: 9256,
              name: 'BATALIKA',
              villages: [
                { id: 59011, name: 'BATALIKA  A' },
                { id: 59012, name: 'BATALIKA  B' },
                { id: 63449, name: 'KIDUKURU' },
                { id: 64663, name: 'KYAMUTURA' },
                { id: 68153, name: 'NYAMIGISA' },
                { id: 68298, name: 'NYUNGU' },
              ],
            },
            {
              id: 9262,
              name: 'BIGANDO',
              villages: [
                { id: 59056, name: 'BIGANDO' },
                { id: 59057, name: 'BIGANDO B' },
                { id: 63881, name: 'KISARULE' },
                { id: 68039, name: 'NYAKARUNGI' },
              ],
            },
            {
              id: 9710,
              name: 'KIJEBERE',
              villages: [
                { id: 62415, name: 'KAMAZIMA' },
                { id: 62454, name: 'KAMUGAGA A' },
                { id: 62455, name: 'KAMUGAGA B' },
                { id: 63592, name: 'KIJEBERE A' },
                { id: 63593, name: 'KIJEBERE B' },
                { id: 66503, name: 'MUHUMULE' },
              ],
            },
            {
              id: 9745,
              name: 'KISANSA',
              villages: [
                { id: 59164, name: 'BOMERA' },
                { id: 62083, name: 'KAGAZI' },
                { id: 63180, name: 'KATUUGU' },
                { id: 63181, name: 'KATUUGU CENTRAL' },
                { id: 63879, name: 'KISANSA' },
                { id: 66754, name: 'MUZIIZI' },
              ],
            },
            {
              id: 9976,
              name: 'MBURARA',
              villages: [
                { id: 59010, name: 'BATALIKA' },
                { id: 62139, name: 'KAHYORO' },
                { id: 62857, name: 'KARUKUJENGE' },
                { id: 64517, name: 'KYABUMBA' },
                { id: 66208, name: 'MBURARA' },
                { id: 66532, name: 'MUKIKOONA' },
              ],
            },
            {
              id: 9998,
              name: 'MUBEMBE',
              villages: [
                { id: 62323, name: 'KALIGENDA' },
                { id: 66466, name: 'MUBEMBE' },
                { id: 66531, name: 'MUKIGAIGA' },
                { id: 67906, name: 'NYABIRUNGI' },
                { id: 68154, name: 'NYAMIHINDI' },
                { id: 70287, name: 'SAYUNI' },
              ],
            },
          ],
        },
        {
          id: 1139,
          name: 'BUFUNJO',
          parishes: [
            {
              id: 5266,
              name: 'BATALIKA',
              villages: [
                { id: 33627, name: 'BATALIKA  A' },
                { id: 33628, name: 'BATALIKA  B' },
                { id: 33629, name: 'KIDUKURU' },
                { id: 33630, name: 'KYAMUTURA' },
                { id: 33631, name: 'NYUNGU' },
              ],
            },
            {
              id: 5260,
              name: 'BIGANDO',
              villages: [
                { id: 33598, name: 'BIGANDO' },
                { id: 33599, name: 'KISARULE' },
                { id: 33600, name: 'NYAKARUNGI' },
              ],
            },
            {
              id: 5262,
              name: 'BUKONGWA',
              villages: [
                { id: 33611, name: 'BUKONGWA' },
                { id: 33608, name: 'ISUNGA' },
                { id: 33606, name: 'KAHOMBO' },
                { id: 33610, name: 'KASAMBYA' },
                { id: 33607, name: 'KIHAMYA' },
                { id: 33613, name: 'KYABAYANJA' },
                { id: 33609, name: 'KYAMUSAMBYA' },
                { id: 33612, name: 'KYARUNTENGYE' },
                { id: 33614, name: 'RUGYENDABARA' },
              ],
            },
            {
              id: 5264,
              name: 'KANDAMA',
              villages: [
                { id: 33619, name: 'BULINGO' },
                { id: 33620, name: 'KANDAMA A' },
                { id: 33621, name: 'KANDAMA B' },
                { id: 66758, name: 'MUZIZI' },
              ],
            },
            {
              id: 9641,
              name: 'KATARAZA',
              villages: [
                { id: 59308, name: 'BUGARAMA' },
                { id: 61512, name: 'HAMURAMA' },
                { id: 61589, name: 'IJUGA' },
                { id: 63046, name: 'KATARAZA A' },
                { id: 63047, name: 'KATARAZA B' },
                { id: 63095, name: 'KATIKARA' },
                { id: 67951, name: 'NYABYONDO' },
                { id: 70190, name: 'RWENSAMBYA' },
              ],
            },
            {
              id: 5265,
              name: 'KATEGERE',
              villages: [
                { id: 33625, name: 'BWERA' },
                { id: 33624, name: 'KATEGERE' },
                { id: 33622, name: 'KIGABO' },
                { id: 33623, name: 'MABAALE' },
                { id: 33626, name: 'MUBANGIZI' },
                { id: 67942, name: 'NYABUSOZI' },
              ],
            },
            {
              id: 5261,
              name: 'MBALE',
              villages: [
                { id: 33605, name: 'KAMATA' },
                { id: 33602, name: 'KITABONA' },
                { id: 33603, name: 'MBALE' },
                { id: 33604, name: 'NKUNUNU' },
                { id: 33601, name: 'NYAMIZO' },
              ],
            },
            {
              id: 5263,
              name: 'NYAMANGA',
              villages: [
                { id: 33615, name: 'KIHUURA' },
                { id: 33617, name: 'KITEMBE' },
                { id: 64809, name: 'KYENKUBA' },
                { id: 66511, name: 'MUKABINGO' },
                { id: 68021, name: 'NYAKAINA' },
                { id: 33616, name: 'NYAMANGA' },
                { id: 33618, name: 'RWEMBOGO' },
              ],
            },
            {
              id: 5267,
              name: 'RWENJAZA',
              villages: [
                { id: 33632, name: 'KANTENGA' },
                { id: 62772, name: 'KARAMA' },
                { id: 62778, name: 'KARAMBI' },
                { id: 33633, name: 'RUTOMA' },
                { id: 33634, name: 'RWENJAZA' },
              ],
            },
          ],
        },
        {
          id: 1146,
          name: 'KANYEGARAMIRE',
          parishes: [
            {
              id: 5294,
              name: 'BYERWA',
              villages: [
                { id: 60366, name: 'BUSINGYE' },
                { id: 33754, name: 'BYERWA' },
                { id: 61911, name: 'KABEREBERE' },
                { id: 66530, name: 'MUKIBINGO' },
                { id: 33755, name: 'NYABURUNGI' },
              ],
            },
            {
              id: 5293,
              name: 'KANYEGARAMIRE',
              villages: [
                { id: 33750, name: 'BULEMBA' },
                { id: 62035, name: 'KADUGU' },
                { id: 33751, name: 'KANYEGARAMIRE' },
                { id: 33752, name: 'KARUBANJU' },
                { id: 33753, name: 'KYAKAHYORO' },
                { id: 67920, name: 'NYABUBALE' },
              ],
            },
            {
              id: 5292,
              name: 'KYAMUGARRA',
              villages: [
                { id: 61236, name: 'EKYIGIGA' },
                { id: 33749, name: 'KAMUKUBE' },
                { id: 64534, name: 'KYAKAHIIGWA' },
                { id: 64552, name: 'KYAKANYORO' },
                { id: 64637, name: 'KYAMUGARRA' },
                { id: 67992, name: 'NYAKABUNGO' },
                { id: 70124, name: 'RWEMANZI' },
              ],
            },
            {
              id: 5291,
              name: 'NYAMICU',
              villages: [
                { id: 61571, name: 'IGONGWE' },
                { id: 62781, name: 'KARANGARA' },
                { id: 33745, name: 'KITOMA' },
                { id: 64106, name: 'KITUMBA' },
                { id: 33746, name: 'MUNYWAMBOGO' },
                { id: 33748, name: 'NYABUSOZI' },
                { id: 33747, name: 'NYAMICU' },
              ],
            },
          ],
        },
        {
          id: 1142,
          name: 'KIGOYERA',
          parishes: [
            {
              id: 5276,
              name: 'IGOMA',
              villages: [
                { id: 33670, name: 'IGOMA A' },
                { id: 33672, name: 'IGOMA B' },
                { id: 33673, name: 'KABUYANDA' },
                { id: 33671, name: 'NYABUSOZI' },
              ],
            },
            {
              id: 5275,
              name: 'KATAMBALE',
              villages: [
                { id: 33664, name: 'KAJUMA - ITWARA' },
                { id: 33669, name: 'KAJUMA-NTUNTU' },
                { id: 33666, name: 'KATAMBALE' },
                { id: 33665, name: 'KIGANDO' },
                { id: 33668, name: 'KINONI' },
                { id: 33667, name: 'KITEMBE' },
              ],
            },
            {
              id: 9700,
              name: 'KIGOYERA',
              villages: [
                { id: 60827, name: 'BYEYA' },
                { id: 62177, name: 'KAJUMA ZONE' },
                { id: 62217, name: 'KAKIRA' },
                { id: 63350, name: 'KIBANGALI' },
                { id: 63522, name: 'KIGOYERA T.C' },
                { id: 66067, name: 'MASAKA' },
                { id: 70129, name: 'RWEMBOGO' },
              ],
            },
            {
              id: 5277,
              name: 'KITUGUTU',
              villages: [
                { id: 33674, name: 'BUHUMULIRO' },
                { id: 33676, name: 'KANYESASI' },
                { id: 63219, name: 'KAYANJA' },
                { id: 33675, name: 'KIGANDO' },
                { id: 33677, name: 'KITUGUTU' },
              ],
            },
            {
              id: 5278,
              name: 'MWOKYA',
              villages: [
                { id: 33678, name: 'KASWA' },
                { id: 33679, name: 'MWOKYA' },
                { id: 67847, name: 'NSWIGA' },
                { id: 33680, name: 'RWENTALE' },
              ],
            },
          ],
        },
        {
          id: 1141,
          name: 'KITEGA',
          parishes: [
            {
              id: 5274,
              name: 'KIJENGI',
              villages: [
                { id: 33663, name: 'BITOMA' },
                { id: 61573, name: 'IGUNGA' },
                { id: 62120, name: 'KAGUSYO' },
                { id: 63595, name: 'KIJENGI' },
              ],
            },
            {
              id: 9747,
              name: 'KISENGYA',
              villages: [
                { id: 63762, name: 'KINYAMA' },
                { id: 63891, name: 'KISENGYA' },
                { id: 64066, name: 'KITONGE' },
                { id: 66627, name: 'MUNJERU' },
              ],
            },
            {
              id: 5272,
              name: 'KITEGA',
              villages: [
                { id: 60223, name: 'BURANGA' },
                { id: 33657, name: 'BUSINDA' },
                { id: 33658, name: 'KITEGA' },
                { id: 68207, name: 'NYANDONGO' },
              ],
            },
            {
              id: 5273,
              name: 'RUKUKURU',
              villages: [
                { id: 62823, name: 'KAROKARUNGI' },
                { id: 33659, name: 'MUGAMBAJE' },
                { id: 33661, name: 'NTUNTU' },
                { id: 33662, name: 'RUKUKURU' },
                { id: 33660, name: 'RWEKOMIIRE' },
              ],
            },
          ],
        },
        {
          id: 1145,
          name: 'KYAMUTUNZI TOWN COUNCIL',
          parishes: [
            {
              id: 5289,
              name: 'KAKINDO WARD',
              villages: [
                { id: 33739, name: 'KAKINDO' },
                { id: 33740, name: 'KYAKAROMBA' },
                { id: 33741, name: 'KYEEYA' },
                { id: 66533, name: 'MUKIKORA' },
              ],
            },
            {
              id: 5290,
              name: 'KATOOGO WARD',
              villages: [
                { id: 33742, name: 'KATOOGO' },
                { id: 33743, name: 'RUKUKURU A' },
                { id: 33744, name: 'RUSAMBYA' },
              ],
            },
            {
              id: 5288,
              name: 'KIHANI WARD',
              villages: [
                { id: 33736, name: 'BUHUNGA' },
                { id: 33737, name: 'KIHANI' },
                { id: 64121, name: 'KIVAKADO' },
                { id: 33738, name: 'NYABIRUNGI' },
              ],
            },
            {
              id: 5287,
              name: 'MUZIZI WARD',
              villages: [
                { id: 33735, name: 'MUZIIZI A' },
                { id: 33733, name: 'MUZIIZI B' },
                { id: 33734, name: 'NYAKABINGO' },
              ],
            },
          ],
        },
        {
          id: 1144,
          name: 'KYEMBOGO',
          parishes: [
            {
              id: 5282,
              name: 'KASABA',
              villages: [
                { id: 33705, name: 'KASABA A' },
                { id: 33704, name: 'KASABA B' },
                { id: 33706, name: 'KASABA C' },
                { id: 33707, name: 'KASABA TRADING CENTRE' },
                { id: 33709, name: 'KIIZI KIRUNGI' },
                { id: 33711, name: 'MUHABURA' },
                { id: 33708, name: 'MUZIRANDURU' },
                { id: 33710, name: 'NYAKAGONGO' },
              ],
            },
            {
              id: 5283,
              name: 'KYAMUGENYI',
              villages: [
                { id: 33712, name: 'KABALE' },
                { id: 33713, name: 'KYABAGANDA' },
                { id: 33714, name: 'KYAMUGONERA' },
                { id: 33715, name: 'KYANIKA' },
                { id: 33716, name: 'NCUMBI' },
                { id: 33717, name: 'NYABWENGA' },
              ],
            },
            {
              id: 5284,
              name: 'MIRAMBI',
              villages: [
                { id: 33718, name: 'ISUNGA' },
                { id: 33719, name: 'KIRINDA' },
                { id: 33720, name: 'KYEMBOGO' },
                { id: 64791, name: 'KYEMBOGO TRADING CENTRE' },
                { id: 33722, name: 'MASOZI' },
                { id: 33721, name: 'MIRAMBI' },
              ],
            },
            {
              id: 5285,
              name: 'MPARO',
              villages: [
                { id: 33726, name: 'ASWA' },
                { id: 33727, name: 'GALILAAYA' },
                { id: 33723, name: 'MPARO A' },
                { id: 33724, name: 'MPARO B' },
                { id: 33725, name: 'NYARUZIGATI' },
                { id: 70288, name: 'SAYUNI' },
              ],
            },
            {
              id: 5286,
              name: 'NYABURARA',
              villages: [
                { id: 33728, name: 'BWEREME' },
                { id: 33730, name: 'HABUBALE' },
                { id: 33729, name: 'HARWOMA' },
                { id: 33732, name: 'KALANGALA' },
                { id: 33731, name: 'NYABURARA' },
              ],
            },
          ],
        },
        {
          id: 1140,
          name: 'MABIRA TOWN COUNCIL',
          parishes: [
            {
              id: 5269,
              name: 'HAIKONA WARD',
              villages: [
                { id: 33640, name: 'HAIKOONA' },
                { id: 33642, name: 'KITENGULE' },
                { id: 33641, name: 'MUBAKI' },
                { id: 33643, name: 'NYANKWANZI   A' },
                { id: 33644, name: 'NYANKWANZI  B' },
              ],
            },
            {
              id: 5270,
              name: 'KITAIHUKA WARD',
              villages: [
                { id: 33646, name: 'HARWOMA A' },
                { id: 33651, name: 'HARWOMA B' },
                { id: 33647, name: 'KABATOORO' },
                { id: 33650, name: 'KYARUGANGAMA' },
                { id: 33645, name: 'KYEBANJA WEST' },
                { id: 33649, name: 'MIRAMBI' },
                { id: 33648, name: 'RWENTALE' },
              ],
            },
            {
              id: 5268,
              name: 'KYASIGIREKI WARD',
              villages: [
                { id: 33635, name: 'KIKYEDU  A' },
                { id: 33636, name: 'KIKYEDU B' },
                { id: 33637, name: 'KYANSIGIREKI' },
                { id: 64688, name: 'KYANSIGIREKI WEST' },
                { id: 33638, name: 'KYEBANJA' },
                { id: 64759, name: 'KYEBANJA WEST' },
                { id: 33639, name: 'MABIRA A' },
              ],
            },
            {
              id: 5271,
              name: 'MABIRA WARD',
              villages: [
                { id: 33656, name: 'KIJEBERE' },
                { id: 33653, name: 'KITWETWE A' },
                { id: 33654, name: 'KITWETWE B' },
                { id: 33655, name: 'KYADUULI' },
                { id: 33652, name: 'MABIRA B' },
                { id: 70200, name: 'RWENTALE' },
              ],
            },
          ],
        },
        {
          id: 1147,
          name: 'NYABIRONGO',
          parishes: [
            {
              id: 5297,
              name: 'KASWA',
              villages: [
                { id: 33765, name: 'KASWA' },
                { id: 33762, name: 'KATEERRA' },
                { id: 33763, name: 'NYANTONZI' },
                { id: 33764, name: 'RUBANGO' },
              ],
            },
            {
              id: 5299,
              name: 'KIJEBERE',
              villages: [
                { id: 33769, name: 'KAMUGAGA A' },
                { id: 33771, name: 'KAMUGAGA B' },
                { id: 33770, name: 'KIJEBERE A' },
                { id: 33772, name: 'KIJEBERE B' },
              ],
            },
            {
              id: 5295,
              name: 'KISANGI',
              villages: [
                { id: 33758, name: 'KALEREMA' },
                { id: 33756, name: 'KYENTAAMA' },
                { id: 33757, name: 'NYABURAMA' },
                { id: 33759, name: 'NYAKABALE' },
              ],
            },
            {
              id: 5298,
              name: 'KYAKASANA',
              villages: [
                { id: 33767, name: 'KABASOGA' },
                { id: 33766, name: 'KYAKASANA' },
                { id: 33768, name: 'KYARUBUMBI' },
              ],
            },
            {
              id: 5300,
              name: 'NSANJA',
              villages: [
                { id: 33773, name: 'KANENA' },
                { id: 63257, name: 'KEBIRUNGI' },
                { id: 33774, name: 'NSANJA' },
                { id: 33775, name: 'NYAKABUNGO' },
              ],
            },
            {
              id: 5296,
              name: 'NYABIRONGO',
              villages: [
                { id: 33761, name: 'KAHIIHI' },
                { id: 63496, name: 'KIGARAMA' },
                { id: 33760, name: 'NYABIRONGO' },
              ],
            },
          ],
        },
        {
          id: 1143,
          name: 'NYANKWANZI',
          parishes: [
            {
              id: 9547,
              name: 'KAITANYANA',
              villages: [
                { id: 61500, name: 'HAKABALE' },
                { id: 62160, name: 'KAITANYANA' },
                { id: 64164, name: 'KIZIRAHETE' },
                { id: 64165, name: 'KIZIRAHETE CENTRAL' },
                { id: 67892, name: 'NYABIDOGO' },
                { id: 67910, name: 'NYABIRUNGI' },
              ],
            },
            {
              id: 5279,
              name: 'KAMAZIMA',
              villages: [
                { id: 33682, name: 'KAHURU' },
                { id: 33683, name: 'KIBAALE A' },
                { id: 33684, name: 'KIBAALE B' },
                { id: 33685, name: 'KIBAALE C' },
                { id: 33686, name: 'KIBAALE D' },
                { id: 33681, name: 'RWENSAMBYA' },
              ],
            },
            {
              id: 9671,
              name: 'KIBALE',
              villages: [
                { id: 62137, name: 'KAHURU' },
                { id: 63335, name: 'KIBAALE C' },
                { id: 63336, name: 'KIBAALE NORTH' },
                { id: 70189, name: 'RWENSAMBYA' },
              ],
            },
            {
              id: 5280,
              name: 'KISANSA',
              villages: [
                { id: 33687, name: 'BATALIKA' },
                { id: 33690, name: 'KAGAZI' },
                { id: 33688, name: 'KATUUGU' },
                { id: 33691, name: 'KISANSA' },
                { id: 33689, name: 'KYIBUMBA' },
                { id: 33693, name: 'MUBEMBE' },
                { id: 33692, name: 'NYAMIHINDI' },
              ],
            },
            {
              id: 5281,
              name: 'NYAMYEZI',
              villages: [
                { id: 33694, name: 'HAKINYASI' },
                { id: 33698, name: 'HAMUGALI' },
                { id: 33695, name: 'KAITABIGYERE' },
                { id: 33696, name: 'KAITANYANA' },
                { id: 33700, name: 'KIZIRAHETE' },
                { id: 33701, name: 'NTURAGYE A' },
                { id: 33699, name: 'NTURAGYE B' },
                { id: 33697, name: 'NYABIDOGO' },
                { id: 33702, name: 'NYAMYEZI' },
                { id: 33703, name: 'RUKUKURU B' },
                { id: 71005, name: 'WAMBUZI' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 187,
      name: 'MWENGE COUNTY SOUTH',
      sub_counties: [
        {
          id: 1148,
          name: 'BUTIITI',
          parishes: [
            {
              id: 5304,
              name: 'BUSANZA',
              villages: [
                { id: 33793, name: 'BUSANZA' },
                { id: 60278, name: 'BUSANZA B' },
                { id: 33794, name: 'KICWERA' },
                { id: 33792, name: 'KISABAGWA' },
                { id: 33795, name: 'MUKONOMURA' },
                { id: 66762, name: 'MWARO' },
              ],
            },
            {
              id: 5301,
              name: 'BUTIITI',
              villages: [
                { id: 33776, name: 'BIRENGA' },
                { id: 63951, name: 'KISORORO' },
                { id: 33777, name: 'KITONZI' },
                { id: 33778, name: 'NYABUBAALE' },
                { id: 67919, name: 'NYABUBAALE B' },
                { id: 33779, name: 'NYOBYA' },
                { id: 33780, name: 'ST AUGUSTINE PTC' },
              ],
            },
            {
              id: 5305,
              name: 'BWENZI',
              villages: [
                { id: 33796, name: 'KYOYA' },
                { id: 33797, name: 'NYAKAHAAMA' },
                { id: 33798, name: 'RWAMATUNDU' },
              ],
            },
            {
              id: 5306,
              name: 'ISANDARA',
              villages: [
                { id: 33799, name: 'BULYANSUNGU' },
                { id: 33801, name: 'ISANDARA-BULYASUNGU' },
                { id: 33800, name: 'ISANDARA-MUTONYA' },
                { id: 33802, name: 'KAKOLE' },
                { id: 33803, name: 'KIJAGARA' },
                { id: 33806, name: 'KISUUGA' },
                { id: 33805, name: 'MUKONO' },
                { id: 33804, name: 'NYONDO' },
              ],
            },
            {
              id: 5302,
              name: 'KAIHURA',
              villages: [
                { id: 33784, name: 'KAIHURA CENTRAL' },
                { id: 62467, name: 'KAMUKENDE' },
                { id: 33781, name: 'KIRIMA' },
                { id: 33782, name: 'KISEKERA' },
                { id: 64657, name: 'KYAMUSEGU' },
                { id: 33783, name: 'KYARUGAAYA' },
                { id: 33786, name: 'NYAKAGONGO' },
                { id: 33785, name: 'NYARUBINGO' },
              ],
            },
            {
              id: 5307,
              name: 'KAKINDO',
              villages: [
                { id: 33807, name: 'KAKINDO' },
                { id: 62621, name: 'KANYWANKOKO' },
                { id: 62766, name: 'KARAHIZO' },
                { id: 33808, name: 'KIBINGO' },
                { id: 33809, name: 'KISAMURA' },
                { id: 63871, name: 'KISAMURA B' },
              ],
            },
            {
              id: 5303,
              name: 'MUKUNYU',
              villages: [
                { id: 33791, name: 'KIBUUKA' },
                { id: 63761, name: 'KINYAIRINGA' },
                { id: 64497, name: 'KYABEYEZA' },
                { id: 33788, name: 'KYAKAITERA' },
                { id: 33789, name: 'MIRANGA' },
                { id: 33787, name: 'MUKUNYU CENTRAL' },
                { id: 67897, name: 'NYABIHOKO' },
                { id: 33790, name: 'NYARUGONGO' },
              ],
            },
          ],
        },
        {
          id: 1152,
          name: 'BUTUNDUZI',
          parishes: [
            {
              id: 5330,
              name: 'KANYINYA',
              villages: [
                { id: 33935, name: 'HARUKOTO' },
                { id: 33930, name: 'KABIRIZI' },
                { id: 33931, name: 'KANYINYA' },
                { id: 33933, name: 'KANYINYA B' },
                { id: 33934, name: 'KIBISAMWIKA' },
                { id: 33932, name: 'MUKATOOKE' },
                { id: 67987, name: 'NYAKABUNGO' },
              ],
            },
            {
              id: 9965,
              name: 'MATEETE',
              villages: [
                { id: 60432, name: 'BUTANDA' },
                { id: 62017, name: 'KACUNGIRO' },
                { id: 62960, name: 'KASHOZI' },
                { id: 66117, name: 'MATEETE' },
                { id: 66535, name: 'MUKITOMA' },
              ],
            },
            {
              id: 5333,
              name: 'MUGALI',
              villages: [
                { id: 59388, name: 'BUHUMULIRO' },
                { id: 60217, name: 'BURAMA' },
                { id: 61499, name: 'HAKABAALE' },
                { id: 33945, name: 'MUGAALI A' },
                { id: 66481, name: 'MUGAALI B' },
              ],
            },
            {
              id: 5334,
              name: 'NAKAHUKA',
              villages: [
                { id: 33946, name: 'KAROKARUNGI' },
                { id: 66995, name: 'NAKAHUKA' },
                { id: 68160, name: 'NYAMIRAMA' },
                { id: 33947, name: 'RUGORRA A' },
                { id: 69911, name: 'RUGORRA B' },
                { id: 69912, name: 'RUGORRA C' },
              ],
            },
            {
              id: 5335,
              name: 'NYABUBALE',
              villages: [
                { id: 67921, name: 'NYABUBALE A' },
                { id: 67922, name: 'NYABUBALE B' },
                { id: 67923, name: 'NYABUBALE C' },
                { id: 67979, name: 'NYAKABINGO' },
                { id: 33948, name: 'NYAKARAMBI' },
                { id: 68048, name: 'NYAKASHOJO' },
              ],
            },
            {
              id: 5331,
              name: 'NYAKATOMA',
              villages: [
                { id: 33938, name: 'BUSINGYE' },
                { id: 33936, name: 'BUTAHWA' },
                { id: 33940, name: 'KAITABAHUMA' },
                { id: 33937, name: 'KOROKONYO' },
                { id: 33939, name: 'NYAKATOMA' },
              ],
            },
            {
              id: 5332,
              name: 'RUGORRA',
              villages: [
                { id: 60437, name: 'BUTARE' },
                { id: 33942, name: 'MUKALERE' },
                { id: 66571, name: 'MUKYEYA' },
                { id: 33941, name: 'NYAMABAALE' },
                { id: 33943, name: 'RUGAGA' },
                { id: 33944, name: 'RUKINDO' },
              ],
            },
          ],
        },
        {
          id: 1156,
          name: 'BUTUNDUZI TOWN COUNCIL',
          parishes: [
            {
              id: 5355,
              name: 'BUTUBIRI WARD',
              villages: [
                { id: 34030, name: 'BUTUBIRI' },
                { id: 60813, name: 'BYABATEMA' },
                { id: 61848, name: 'KABAKA' },
                { id: 69924, name: 'RUKARABO' },
              ],
            },
            {
              id: 5354,
              name: 'BUTUNDUZI WARD',
              villages: [
                { id: 59385, name: 'BUHUMIRIRO' },
                { id: 34028, name: 'BUTUNDUZI' },
                { id: 60507, name: 'BUTUNDUZI B' },
                { id: 60508, name: 'BUTUNDUZI CENTRAL' },
                { id: 34029, name: 'BWEGALIKE' },
                { id: 62550, name: 'KANSANGA MOSLEM' },
                { id: 34027, name: 'KINYWAGI' },
                { id: 66325, name: 'MIYORA CENTRAL' },
              ],
            },
            {
              id: 9499,
              name: 'IGAALI WARD',
              villages: [
                { id: 61561, name: 'IGAALI' },
                { id: 62135, name: 'KAHUNGURA' },
                { id: 63499, name: 'KIGASANI' },
                { id: 63500, name: 'KIGASANI B' },
              ],
            },
            {
              id: 9835,
              name: 'KYANYAMUGABO WARD',
              villages: [
                { id: 63782, name: 'KINYWAGI' },
                { id: 64694, name: 'KYANYAMUGABO' },
                { id: 65931, name: 'MAKANGA' },
                { id: 66520, name: 'MUKATETE' },
              ],
            },
            {
              id: 10000,
              name: 'MUKONOMURA WARD',
              villages: [
                { id: 60793, name: 'BWESESE' },
                { id: 63450, name: 'KIDUKURU' },
                { id: 63470, name: 'KIGAIGA' },
                { id: 66544, name: 'MUKONOMURA' },
              ],
            },
            {
              id: 10264,
              name: 'RUBAKA WARD',
              villages: [
                { id: 66324, name: 'MIYOORA' },
                { id: 69870, name: 'RUBAKA' },
                { id: 69871, name: 'RUBAKA B' },
              ],
            },
            {
              id: 5356,
              name: 'RWENYUNYUZI WARD',
              villages: [
                { id: 63982, name: 'KITAGATA' },
                { id: 34031, name: 'MISENYI' },
                { id: 67998, name: 'NYAKABUNGO' },
                { id: 34032, name: 'RWENYUNYUZI' },
              ],
            },
            {
              id: 5353,
              name: 'RWIBALE WARD',
              villages: [
                { id: 34026, name: 'KABWERA' },
                { id: 62063, name: 'KAFUZI' },
                { id: 62594, name: 'KANYEGARAMIRE' },
                { id: 34023, name: 'KIRINDAMENI' },
                { id: 64540, name: 'KYAKAITAMBA' },
                { id: 34024, name: 'KYARWAJONGO' },
                { id: 34025, name: 'RWIBAALE' },
              ],
            },
          ],
        },
        {
          id: 1153,
          name: 'KIGARAALE',
          parishes: [
            {
              id: 9502,
              name: 'IKAMIRO',
              villages: [
                { id: 59687, name: 'BULEGEYA' },
                { id: 61598, name: 'IKAMIRO' },
                { id: 63565, name: 'KIHUMBYA' },
                { id: 63992, name: 'KITAMARA' },
              ],
            },
            {
              id: 5338,
              name: 'KABAALE',
              villages: [
                { id: 33961, name: 'KABAALE  A' },
                { id: 33962, name: 'KABAALE  B' },
                { id: 61838, name: 'KABAALE CENTRAL' },
                { id: 33963, name: 'KAHAARA' },
                { id: 33965, name: 'KYEEYA' },
                { id: 33964, name: 'MIRAMBI' },
                { id: 67964, name: 'NYAKABAALE' },
              ],
            },
            { id: 9693, name: 'KIGARAALE', villages: [{ id: 61590, name: 'IJUGA' }] },
            {
              id: 5336,
              name: 'KIGARALE',
              villages: [
                { id: 33949, name: 'GALIHUMA' },
                { id: 33951, name: 'KIGARALE' },
                { id: 33950, name: 'KIRISA' },
                { id: 33953, name: 'KYAMAGOGO' },
                { id: 33954, name: 'MISINDO' },
                { id: 33952, name: 'RUHUUNA' },
              ],
            },
            {
              id: 5339,
              name: 'KIKUMIRO',
              villages: [
                { id: 33968, name: 'KATENGEETA' },
                { id: 33966, name: 'KIKUMIRO' },
                { id: 33969, name: 'KYARUKUMBYA' },
                { id: 33970, name: 'MWARO' },
                { id: 33967, name: 'ORUHANGA' },
              ],
            },
            {
              id: 5340,
              name: 'KISENGYA',
              villages: [
                { id: 33971, name: 'BUTENDE' },
                { id: 62138, name: 'KAHYORO' },
                { id: 33972, name: 'KISENGYA' },
                { id: 33973, name: 'KYAMUGOMA' },
                { id: 66655, name: 'MURUGANDO' },
                { id: 69220, name: 'ORUKINGA' },
              ],
            },
            {
              id: 5341,
              name: 'MABUGA',
              villages: [
                { id: 33974, name: 'KABAMUHIKE' },
                { id: 33975, name: 'KARUBONGOYA' },
                { id: 64771, name: 'KYEGANYWA B' },
                { id: 33976, name: 'MABUGA' },
                { id: 67941, name: 'NYABUSOZI' },
              ],
            },
            {
              id: 5337,
              name: 'NYAIBANDA',
              villages: [
                { id: 33957, name: 'KABURANDA' },
                { id: 33955, name: 'KAKOMA' },
                { id: 33956, name: 'KYABWENGE' },
                { id: 33958, name: 'KYEGANYWA' },
                { id: 33959, name: 'NYAIBANDA' },
                { id: 33960, name: 'RWAKAHIIRA' },
              ],
            },
          ],
        },
        {
          id: 1149,
          name: 'KIHUURA',
          parishes: [
            {
              id: 5311,
              name: 'KAWARUJU',
              villages: [
                { id: 33832, name: 'BIBUYE' },
                { id: 33833, name: 'ISOROMA' },
                { id: 33834, name: 'MAHASA' },
                { id: 33835, name: 'NYAMIRIMA' },
                { id: 33836, name: 'RUSONGORA' },
              ],
            },
            {
              id: 5308,
              name: 'KIHUURA',
              villages: [
                { id: 33811, name: 'BUKORA' },
                { id: 33813, name: 'KASAALI' },
                { id: 33814, name: 'KICWAMBA' },
                { id: 33815, name: 'KIHUURA' },
                { id: 33816, name: 'KIKUKURU' },
                { id: 33812, name: 'KIREGESA' },
                { id: 33817, name: 'KISAKARA' },
                { id: 33810, name: 'KISIITA' },
                { id: 33818, name: 'MURONGO' },
                { id: 33819, name: 'NYAKAHAMA' },
              ],
            },
            {
              id: 5312,
              name: 'KIJWEKA',
              villages: [
                { id: 60258, name: 'BUSAIGA' },
                { id: 33837, name: 'KIGANDO' },
                { id: 33839, name: 'KIJWEKA' },
                { id: 33838, name: 'KISIITA' },
                { id: 33840, name: 'KYABALEBERA' },
                { id: 33841, name: 'KYABULYEZIBWA' },
                { id: 33842, name: 'KYAMALAYA' },
              ],
            },
            {
              id: 5309,
              name: 'KYANKARAMATA',
              villages: [
                { id: 33820, name: 'BUSESE' },
                { id: 33821, name: 'KIHOOKA' },
                { id: 33822, name: 'KIRENDU' },
                { id: 33823, name: 'KIRYANDONGO' },
                { id: 33824, name: 'KYAMUNWA' },
                { id: 33825, name: 'NYABUSOZI' },
              ],
            },
            {
              id: 5310,
              name: 'MATIRI',
              villages: [
                { id: 33826, name: 'GANYINAYO' },
                { id: 33827, name: 'KICWAMBA' },
                { id: 33828, name: 'KISENGENYI' },
                { id: 33829, name: 'MATIRI' },
                { id: 33831, name: 'MUKWISI' },
                { id: 33830, name: 'NYAKAHAAMA' },
              ],
            },
            {
              id: 5313,
              name: 'NGOMBE',
              villages: [
                { id: 33843, name: 'BISA' },
                { id: 33845, name: 'BURAMBA' },
                { id: 33846, name: 'KIJOIJORO' },
                { id: 33844, name: 'MAKOROIGO' },
                { id: 33847, name: 'NGOMBE' },
              ],
            },
          ],
        },
        {
          id: 1154,
          name: 'KISOJO',
          parishes: [
            {
              id: 5342,
              name: 'KIKODA',
              villages: [
                { id: 33977, name: 'KIJONJOZA' },
                { id: 33978, name: 'KIKODA' },
                { id: 33979, name: 'KISINGO' },
                { id: 33980, name: 'MAHEZI' },
                { id: 33981, name: 'NDAMA' },
                { id: 33982, name: 'RUGANDO' },
              ],
            },
            {
              id: 5344,
              name: 'KITONGOLE',
              villages: [
                { id: 33991, name: 'ISOROMA' },
                { id: 33989, name: 'KISWARRA A' },
                { id: 33987, name: 'KISWARRA B' },
                { id: 33990, name: 'KITONGOLE' },
                { id: 33988, name: 'KYAKIKOKWA' },
              ],
            },
            {
              id: 5343,
              name: 'RWEITENGYA',
              villages: [
                { id: 33983, name: 'BITUUMO' },
                { id: 33984, name: 'KIKUMBO' },
                { id: 33985, name: 'NDIRAKOHA' },
                { id: 33986, name: 'RWAITENGYA' },
              ],
            },
          ],
        },
        {
          id: 1157,
          name: 'KISOJO TOWN COUNCIL',
          parishes: [
            {
              id: 5360,
              name: 'BIBUYE WARD',
              villages: [
                { id: 34049, name: 'BIBUYE A' },
                { id: 34051, name: 'BIBUYE B' },
                { id: 63528, name: 'KIGUNDA B' },
                { id: 34050, name: 'KYAKAPECE' },
              ],
            },
            {
              id: 5357,
              name: 'KIGUNDA WARD',
              villages: [
                { id: 34033, name: 'KIBURARA' },
                { id: 34034, name: 'KIGUNDA A' },
                { id: 34035, name: 'KIZINISA' },
                { id: 34038, name: 'KYAMULIMI' },
                { id: 34036, name: 'MIGOMBWA' },
                { id: 34037, name: 'NYABUBALE' },
              ],
            },
            {
              id: 5358,
              name: 'KISOJO WARD',
              villages: [
                { id: 63617, name: 'KIJUMBA-KITANGA' },
                { id: 34039, name: 'KISANA' },
                { id: 34040, name: 'KISOJO' },
                { id: 34041, name: 'KITABONA' },
                { id: 34042, name: 'KITERWA' },
                { id: 34043, name: 'KYAMULIMI' },
                { id: 34044, name: 'KYARUSURA' },
              ],
            },
            {
              id: 5359,
              name: 'KYAMITARA WARD',
              villages: [
                { id: 34045, name: 'KINYANA' },
                { id: 34046, name: "KIRONGO 'A'" },
                { id: 34047, name: "KIRONGO 'B'" },
                { id: 34048, name: 'KYAMITARA' },
              ],
            },
          ],
        },
        {
          id: 1158,
          name: 'KYAKATWIRE TOWN COUNCIL',
          parishes: [
            {
              id: 5363,
              name: 'KANGONDO WARD',
              villages: [
                { id: 34063, name: 'BAGESIIGIRE' },
                { id: 61991, name: 'KABYOOMA' },
                { id: 34066, name: 'KANGONDO' },
                { id: 34064, name: 'KYAMUJANGA' },
                { id: 34065, name: 'MPANGA' },
                { id: 70536, name: 'SOWETO' },
              ],
            },
            {
              id: 5361,
              name: 'KYAKATWIRE WARD',
              villages: [
                { id: 61881, name: 'KABARATA' },
                { id: 61885, name: 'KABASOMBA' },
                { id: 34052, name: 'KATAKA' },
                { id: 34053, name: 'KIGORO' },
                { id: 63814, name: 'KIRIIKA' },
                { id: 34054, name: 'KYAKATWIRE' },
                { id: 34055, name: 'NYAMIRONGO' },
              ],
            },
            { id: 10018, name: 'MWIBAALE WARD', villages: [{ id: 68119, name: 'NYAKYETENGWA' }] },
            {
              id: 5362,
              name: 'OMWIBAALE WARD',
              villages: [
                { id: 34058, name: 'BWEERA' },
                { id: 34059, name: 'KABUKANGA' },
                { id: 34057, name: 'KAROKARUNGI' },
                { id: 34060, name: 'KINYANTALE' },
                { id: 34056, name: 'MURUTOMA' },
                { id: 34061, name: 'OMWIBAALE' },
                { id: 34062, name: 'RUBONA' },
              ],
            },
          ],
        },
        {
          id: 1151,
          name: 'KYENJOJO TOWN COUNCIL',
          parishes: [
            {
              id: 5326,
              name: 'BUCUNI WARD',
              villages: [
                { id: 33911, name: 'BUCUNI' },
                { id: 33912, name: 'BWENDERO' },
                { id: 33914, name: 'KASUNGA' },
                { id: 33916, name: 'KIDOMI' },
                { id: 33913, name: 'KYABIGANJA' },
                { id: 33915, name: 'KYAMAPULI' },
              ],
            },
            {
              id: 5327,
              name: 'HAKATOMA WARD',
              villages: [
                { id: 33917, name: 'KABUNGO' },
                { id: 33918, name: 'KATUMBA' },
                { id: 33919, name: 'KITANYATA' },
                { id: 33920, name: 'RWENKUBA' },
              ],
            },
            {
              id: 5323,
              name: 'KASIINA WARD',
              villages: [
                { id: 33896, name: 'KABONGO' },
                { id: 33897, name: 'KASIINA' },
                { id: 33898, name: 'KYENJOJO CENTRAL' },
                { id: 33899, name: 'RWEBIJOKA' },
              ],
            },
            {
              id: 5325,
              name: 'KIJUMA WARD',
              villages: [
                { id: 33906, name: 'KATOOSA' },
                { id: 33910, name: 'KIJUMA' },
                { id: 33909, name: 'KISERUKA' },
                { id: 33907, name: 'KYENJOJO-KISENYI' },
                { id: 33908, name: 'KYENJOJO-NYAKABARA' },
              ],
            },
            {
              id: 5324,
              name: 'KIRONGO WARD',
              villages: [
                { id: 33902, name: 'KABAGUNDA' },
                { id: 33903, name: 'KIRONGO' },
                { id: 33904, name: 'KYAKAHULI' },
                { id: 33900, name: 'KYANKUTA' },
                { id: 33905, name: 'MPUNDA' },
                { id: 33901, name: 'NYAMBYA' },
              ],
            },
            {
              id: 5329,
              name: 'MISANDIKA WARD',
              villages: [
                { id: 33927, name: 'MUSANDIIKA' },
                { id: 33928, name: 'NGEZI' },
                { id: 33929, name: 'NYABUGOROGORO' },
                { id: 33926, name: 'NYARUGONGO' },
              ],
            },
            {
              id: 5328,
              name: 'NTOOMA WARD',
              villages: [
                { id: 33921, name: 'KIKWETE' },
                { id: 33922, name: "NTOOMA 'A'" },
                { id: 33923, name: "NTOOMA 'B'" },
                { id: 33924, name: 'NYANTUNGO A' },
                { id: 33925, name: 'NYANTUNGO B' },
              ],
            },
          ],
        },
        {
          id: 1155,
          name: 'NYABUHARWA',
          parishes: [
            {
              id: 5345,
              name: 'KABIRIZI',
              villages: [
                { id: 33992, name: 'KABIRIZI CENTRAL' },
                { id: 33994, name: 'KYABIKANGA' },
                { id: 33995, name: 'MIRONGO I' },
                { id: 33996, name: "MUHANGI 'A'" },
                { id: 33993, name: "MUHANGI 'B'" },
              ],
            },
            {
              id: 5348,
              name: 'KAIGORO',
              villages: [
                { id: 59699, name: 'BULEZI' },
                { id: 34004, name: 'BUSORO' },
                { id: 34005, name: 'KAIGORO' },
                { id: 34006, name: 'KAMUGASA' },
                { id: 34007, name: 'KIHORA' },
                { id: 63561, name: 'KIHORA CENTRAL' },
              ],
            },
            {
              id: 5349,
              name: 'KIGANDO',
              villages: [
                { id: 34009, name: 'KIGANDO' },
                { id: 63480, name: 'KIGANDO B' },
                { id: 67796, name: 'NKINGA CENTRAL' },
                { id: 34010, name: 'NKINGA I' },
                { id: 34011, name: 'NKINGA II' },
                { id: 34008, name: 'RWAMAGEMBE' },
              ],
            },
            {
              id: 5350,
              name: 'KINYANTALE',
              villages: [
                { id: 34012, name: 'KINYANTALE  A' },
                { id: 34013, name: 'KINYANTALE  B' },
                { id: 70027, name: 'RWABAGANDA' },
                { id: 34014, name: 'RWENSENENE' },
              ],
            },
            {
              id: 5346,
              name: 'MBALE',
              villages: [
                { id: 33998, name: 'BUHYABUNGA' },
                { id: 33999, name: 'KINUBI' },
                { id: 63756, name: 'KINUBI CENTRAL' },
                { id: 33997, name: 'KIREBEKI' },
                { id: 34000, name: 'MIHIKIRO' },
              ],
            },
            {
              id: 5351,
              name: 'MUGOMA',
              villages: [
                { id: 34016, name: 'BIHEHE' },
                { id: 61551, name: 'IBURRO' },
                { id: 34015, name: 'KAMUKONGA' },
                { id: 34017, name: 'KATEBE' },
                { id: 34019, name: 'MAHUNGU' },
                { id: 34018, name: 'MUGOMA' },
                { id: 66705, name: 'MUTAHYOMU' },
                { id: 67884, name: 'NYABAGOMA' },
              ],
            },
            {
              id: 5352,
              name: 'NYABUHARWA',
              villages: [
                { id: 34020, name: 'KASOGA' },
                { id: 64627, name: 'KYAMIJUMBI' },
                { id: 34021, name: 'MIRONGO II' },
                { id: 34022, name: 'NYABUHARWA' },
              ],
            },
            {
              id: 5347,
              name: 'NYAKARONGO',
              villages: [
                { id: 60240, name: 'BURONZI' },
                { id: 34002, name: 'KASWA' },
                { id: 67928, name: 'NYABUGANDO' },
                { id: 34001, name: 'NYAKARONGO' },
                { id: 34003, name: 'RUBONA II' },
                { id: 70179, name: 'RWENKORAIGO' },
              ],
            },
          ],
        },
        {
          id: 1150,
          name: 'NYANTUNGO',
          parishes: [
            {
              id: 5314,
              name: 'BURARO',
              villages: [
                { id: 33848, name: 'BIBUNGO' },
                { id: 33849, name: 'BURARRO A' },
                { id: 33850, name: 'BURARRO B' },
                { id: 33852, name: 'KASOGA-KISEMERA' },
                { id: 64532, name: 'KYAKAGORO' },
                { id: 64567, name: 'KYAKASUURA' },
                { id: 33851, name: 'KYANYAMUTALE' },
                { id: 33854, name: 'KYEKUBA' },
                { id: 68179, name: 'NYAMIYAGA' },
                { id: 33853, name: 'NYARUKOMA' },
              ],
            },
            {
              id: 5319,
              name: 'IHAMBA',
              villages: [
                { id: 33876, name: 'BUTEEKA' },
                { id: 33878, name: 'IHAMBA' },
                { id: 33879, name: 'KAKIRA' },
                { id: 33880, name: 'NYABUSOZI' },
                { id: 33877, name: 'NYAKAGONGO' },
              ],
            },
            {
              id: 5320,
              name: 'KANYANDAHI',
              villages: [
                { id: 33882, name: 'BUKABARA' },
                { id: 33881, name: 'KIREEGA' },
                { id: 33884, name: 'MPAHA' },
                { id: 33883, name: 'NDAMA' },
                { id: 33885, name: 'NYAKAYUBU' },
              ],
            },
            {
              id: 5315,
              name: 'KIBIRA',
              villages: [
                { id: 60708, name: 'BUYAGAARA' },
                { id: 33855, name: 'ISEMIHABO' },
                { id: 33856, name: 'KATUNGURU' },
                { id: 33857, name: 'KIPOLANDA' },
                { id: 33860, name: 'KISABA' },
                { id: 33858, name: 'KITONKYA' },
                { id: 33859, name: 'KYENTE' },
                { id: 68191, name: 'NYAMUHAGURA' },
              ],
            },
            {
              id: 5316,
              name: 'KYAMUTASA',
              villages: [
                { id: 33861, name: 'BUTAAHA' },
                { id: 33866, name: 'KARONGO' },
                { id: 33862, name: 'KIDUDU' },
                { id: 33863, name: 'KIPEEPA' },
                { id: 33864, name: 'KIRONGO' },
                { id: 33865, name: 'KYAMUTASA' },
              ],
            },
            {
              id: 5318,
              name: 'MABAALE',
              villages: [
                { id: 33872, name: 'BUHISI' },
                { id: 33874, name: 'KABUGENYI' },
                { id: 33873, name: 'KAROKARUNGI' },
                { id: 33875, name: 'MABAALE' },
                { id: 68249, name: 'NYARUGONGO' },
              ],
            },
            {
              id: 5321,
              name: 'MABWONWA',
              villages: [
                { id: 33886, name: 'BYENTALE' },
                { id: 33887, name: 'KIRANGA' },
                { id: 33888, name: 'KIZIIRA' },
                { id: 33889, name: 'MABONWA' },
                { id: 33890, name: 'MUJUNWA' },
                { id: 33891, name: 'RWEMYONGO' },
              ],
            },
            {
              id: 5322,
              name: 'NTUNTU',
              villages: [
                { id: 60200, name: 'BUNYONYI' },
                { id: 63553, name: 'KIHINDA' },
                { id: 33893, name: 'KYANYAMA' },
                { id: 33892, name: 'MUGOLE' },
                { id: 33894, name: 'NTUNTU' },
                { id: 33895, name: 'NYAKAHAMA' },
              ],
            },
            {
              id: 5317,
              name: 'RUHOKO',
              villages: [
                { id: 33867, name: 'KIGUGU' },
                { id: 33868, name: 'KIRONGO' },
                { id: 33869, name: 'KISINGA' },
                { id: 33870, name: 'KYAMIRUNDI/RUSIRIBA' },
                { id: 69986, name: 'RUSIRIBA' },
                { id: 33871, name: 'RWENKUNGA' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
