import { District } from '../types';

export default <District>{
  id: 122,
  name: 'LUUKA',
  counties: [
    {
      id: 284,
      name: 'LUUKA NORTH COUNTY',
      sub_counties: [
        {
          id: 1880,
          name: 'BUKOOMA',
          parishes: [
            {
              id: 8870,
              name: 'BUKOOMA',
              villages: [
                { id: 55738, name: 'BUKANHA A' },
                { id: 55741, name: 'BUKANHA B' },
                { id: 55739, name: 'BUKOOMA A' },
                { id: 55742, name: 'BUKOOMA B' },
                { id: 55740, name: 'MUSITA' },
              ],
            },
            {
              id: 8871,
              name: 'BUKYANGWA',
              villages: [
                { id: 55743, name: 'BUDHANA A' },
                { id: 55744, name: 'BUDHANA B' },
                { id: 55745, name: 'BUKYANGWA' },
                { id: 55746, name: 'BUKYANGWA B' },
              ],
            },
            {
              id: 8872,
              name: 'NABYOTO',
              villages: [
                { id: 55747, name: 'BUKOOVA A' },
                { id: 55757, name: 'BUKOOVA B' },
                { id: 55748, name: 'BUKOOVA T/C' },
                { id: 55749, name: 'BUNABALA  A' },
                { id: 55758, name: 'BUNABALA B' },
                { id: 55751, name: "BUSANDHA 'B'" },
                { id: 55750, name: 'BUSANDHA A' },
                { id: 55752, name: 'BUTASERWA' },
                { id: 55753, name: 'BUYOGA' },
                { id: 55754, name: 'MAKUUTU' },
                { id: 55755, name: 'NABYOTO' },
                { id: 55756, name: 'NABYOTO B' },
              ],
            },
            {
              id: 8873,
              name: 'NAIGOBYA',
              villages: [
                { id: 55759, name: 'NAIGOBYA A' },
                { id: 55760, name: 'NAIGOBYA B' },
                { id: 55761, name: 'NAIGOBYA T/C' },
                { id: 55762, name: 'NAIRIKA  EAST' },
                { id: 55763, name: 'NAIRIKA  WEST' },
              ],
            },
            {
              id: 8874,
              name: 'NAMASENDA',
              villages: [
                { id: 55764, name: 'BULALU' },
                { id: 55765, name: 'BUSAKU' },
                { id: 55766, name: 'KIRIMWA  A' },
                { id: 55767, name: 'KIRIMWA  B' },
                { id: 55768, name: 'NABIMOGO A' },
                { id: 55770, name: 'NABIMOGO B' },
                { id: 55771, name: 'NAMANSENDA B' },
                { id: 55769, name: 'NAMASENDA  A' },
              ],
            },
            {
              id: 8875,
              name: 'NAMULANDA',
              villages: [
                { id: 55775, name: 'GWEMBUZI' },
                { id: 55774, name: 'GWEMBUZI B' },
                { id: 55776, name: 'NAMULANDA' },
                { id: 55773, name: 'NAMULANDA B' },
                { id: 55777, name: 'NAWANSEGA' },
                { id: 55772, name: 'NAWANSEGA B' },
              ],
            },
          ],
        },
        {
          id: 1881,
          name: 'BULONGO',
          parishes: [
            {
              id: 8876,
              name: 'BUDHABANGULA',
              villages: [
                { id: 55778, name: 'BUDHABANGULA A' },
                { id: 55779, name: 'BUDHABANGULA B' },
                { id: 55780, name: 'KIBUUTU' },
              ],
            },
            {
              id: 8877,
              name: 'BUGONYOKA',
              villages: [
                { id: 55781, name: 'BUGONYOKA  A' },
                { id: 55782, name: 'BUGONYOKA  B' },
                { id: 55785, name: 'BUZAAYA' },
                { id: 55783, name: 'NAKISENYI  A' },
                { id: 55784, name: 'NAKISENYI  B' },
              ],
            },
            {
              id: 8878,
              name: 'BUKENDI',
              villages: [
                { id: 55786, name: 'BUGABULA A' },
                { id: 55787, name: 'BUGABULA B' },
                { id: 55788, name: 'BUKENDI' },
                { id: 55789, name: 'NABITAMA  A' },
                { id: 55790, name: 'NABITAMA  B' },
              ],
            },
            {
              id: 8879,
              name: 'BULONGO',
              villages: [
                { id: 55791, name: 'BUWAISWA' },
                { id: 55792, name: 'KAMWIRUNGU A' },
                { id: 55793, name: 'KAMWIRUNGU B' },
              ],
            },
            {
              id: 8880,
              name: 'NAKABUGU',
              villages: [
                { id: 55794, name: 'BUSEETE' },
                { id: 55795, name: 'BUYUNZE A' },
                { id: 55796, name: 'BUYUNZE B' },
                { id: 55797, name: 'NAKABUGU  A' },
                { id: 55798, name: 'NAKABUGU B' },
              ],
            },
            {
              id: 8881,
              name: 'NAMALEMBA',
              villages: [
                { id: 55799, name: 'BULIKE' },
                { id: 55800, name: 'BUSALA' },
                { id: 55801, name: 'KASOZI' },
                { id: 55802, name: 'NAMALEMBA' },
              ],
            },
          ],
        },
        {
          id: 1882,
          name: 'IKUMBYA',
          parishes: [
            {
              id: 8882,
              name: 'BUNAFU',
              villages: [
                { id: 55803, name: 'BUNAFU A' },
                { id: 55804, name: 'BUNAFU B' },
                { id: 55805, name: 'NABISIRA' },
                { id: 55806, name: 'NAWANYAGO' },
              ],
            },
            {
              id: 8883,
              name: 'IKUMBYA',
              villages: [
                { id: 55807, name: 'BUWUTU' },
                { id: 55808, name: 'IKUMBYA' },
                { id: 55809, name: 'NSAMBYA' },
                { id: 55810, name: 'WANDAGO' },
              ],
            },
            {
              id: 8884,
              name: 'INUULA',
              villages: [
                { id: 55811, name: 'BUDHUUBA   A' },
                { id: 55812, name: 'BUDHUUBA   B' },
                { id: 55813, name: 'BUGAMBO' },
                { id: 55814, name: 'INNULA' },
              ],
            },
            {
              id: 8885,
              name: 'NAWAKA',
              villages: [
                { id: 55815, name: 'BUGONZA' },
                { id: 55816, name: 'KAWANGA' },
                { id: 55817, name: 'NANTAMALI' },
                { id: 55818, name: 'NAWAKA  A' },
                { id: 55819, name: 'NAWAKA  B' },
                { id: 55820, name: 'NAWAKA  CENTRAL' },
              ],
            },
            {
              id: 8886,
              name: 'NTAYIGIRWA',
              villages: [
                { id: 55821, name: 'BUKOBO' },
                { id: 55822, name: 'BULIKE' },
                { id: 55823, name: 'IDOOME  EAST' },
                { id: 55824, name: 'IDOOME  WEST' },
                { id: 55825, name: 'NABITENDE' },
                { id: 55826, name: 'NTAYIGIRWA' },
              ],
            },
          ],
        },
        {
          id: 1883,
          name: 'LUUKA TOWN COUNCIL',
          parishes: [
            {
              id: 8889,
              name: 'BUSIMAWU WARD',
              villages: [
                { id: 55833, name: 'BUDUMBWIIRE' },
                { id: 55835, name: 'BUSIMAWU' },
                { id: 55834, name: 'WAIGUGWE' },
              ],
            },
            {
              id: 8891,
              name: 'BUSONGA WARD',
              villages: [
                { id: 55839, name: 'BUKABOLI' },
                { id: 55840, name: 'BUSONGA' },
              ],
            },
            {
              id: 8890,
              name: 'KITWEKYAMBOGO WARD',
              villages: [
                { id: 55836, name: 'MBOGO' },
                { id: 55837, name: 'NAWAMWENA' },
                { id: 55838, name: 'NAWASUDE' },
              ],
            },
            {
              id: 8887,
              name: 'KIYUNGA WARD',
              villages: [
                { id: 55828, name: 'KIYUNGA  INDUSTRIAL' },
                { id: 55829, name: 'KIYUNGA CENTRAL' },
                { id: 55827, name: 'KIYUNGA HOSPITAL' },
              ],
            },
            {
              id: 8888,
              name: 'LWADA WARD',
              villages: [
                { id: 55830, name: 'BWAMBUZI' },
                { id: 55831, name: 'LWANDA' },
                { id: 55832, name: 'NTANDAGWE' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 285,
      name: 'LUUKA SOUTH COUNTY',
      sub_counties: [
        {
          id: 1884,
          name: 'BUKANGA',
          parishes: [
            {
              id: 8892,
              name: 'BUDONDO',
              villages: [
                { id: 55841, name: 'BUDONDO A' },
                { id: 55842, name: 'BUDONDO B' },
                { id: 55843, name: 'BUGOBA' },
                { id: 55844, name: 'KIMANTO A' },
                { id: 55845, name: 'KIMANTO B' },
              ],
            },
            {
              id: 8893,
              name: 'BUSALAMU',
              villages: [
                { id: 55846, name: 'BUSIRINGE' },
                { id: 55847, name: 'BUTONDOLO' },
                { id: 55848, name: 'KIGULAMO' },
                { id: 55849, name: 'KIRINGO' },
                { id: 55850, name: 'LUKOTAIME' },
                { id: 55851, name: 'LUKUNHU A' },
                { id: 55852, name: 'LUKUNHU B' },
              ],
            },
            {
              id: 8894,
              name: 'BUWOLOGOMA',
              villages: [
                { id: 55853, name: 'BUGOGO' },
                { id: 55854, name: 'BUKAADE' },
                { id: 55855, name: 'BUKWANGA' },
                { id: 55856, name: 'BUWOLOGOMA CENTRAL' },
                { id: 55857, name: 'KATALAKABI' },
                { id: 55858, name: 'NABINONI' },
                { id: 55859, name: 'NAKAMINI' },
                { id: 55860, name: 'NDHOYA A' },
                { id: 55861, name: 'NDHOYA B' },
              ],
            },
            {
              id: 8895,
              name: 'KIROBA',
              villages: [
                { id: 55862, name: 'BIGUNHO' },
                { id: 55863, name: 'BUDOMA' },
                { id: 55864, name: 'BULONDE' },
                { id: 55865, name: 'BUSANDHA' },
                { id: 55866, name: 'KISIMBA' },
                { id: 55867, name: 'NAWANTALE' },
              ],
            },
            {
              id: 8896,
              name: 'NABUBYA',
              villages: [
                { id: 55868, name: 'BUDOMA A' },
                { id: 55869, name: 'BUDOMA B' },
                { id: 55870, name: 'BUDOMA C' },
                { id: 55871, name: 'BUNHIRIRA' },
                { id: 55872, name: 'NABUBYA A' },
                { id: 55873, name: 'NABUBYA B' },
                { id: 55874, name: 'NAKABONDO' },
              ],
            },
            {
              id: 8897,
              name: 'NAMUKUBEMBE',
              villages: [
                { id: 55875, name: 'BUKENDI' },
                { id: 55876, name: 'BULWASIRA' },
                { id: 55877, name: 'BUMANHA A' },
                { id: 55878, name: 'BUMANHA B' },
                { id: 55879, name: 'BUMANHA C' },
                { id: 55880, name: 'KANTENGA' },
                { id: 55881, name: 'NAMUKUBEMBE I' },
                { id: 55882, name: 'NAMUKUBEMBE II' },
              ],
            },
          ],
        },
        {
          id: 1885,
          name: 'IRONGO',
          parishes: [
            {
              id: 8901,
              name: 'IRONGO',
              villages: [
                { id: 55909, name: 'BUFUMBA' },
                { id: 55902, name: 'BUWALA' },
                { id: 55903, name: 'GANSEMBYE' },
                { id: 55904, name: 'IGANGA A' },
                { id: 55905, name: 'IGANGA B' },
                { id: 55906, name: 'IRONGO' },
                { id: 55907, name: 'NAIMULI' },
                { id: 55910, name: 'NAIMULI B' },
                { id: 55908, name: 'NSIRIRA' },
              ],
            },
            {
              id: 8898,
              name: 'KALYOWA',
              villages: [
                { id: 55883, name: 'BUKYAMATA' },
                { id: 55884, name: 'BUNIKO' },
                { id: 55888, name: 'BUNIKO B' },
                { id: 55885, name: 'KALYOWA' },
                { id: 55887, name: 'KALYOWA B' },
                { id: 55886, name: 'KIGUNGA' },
              ],
            },
            {
              id: 8899,
              name: 'KIBINGA',
              villages: [
                { id: 55889, name: 'KANTENGA' },
                { id: 55890, name: 'KIBINGA A' },
                { id: 55891, name: 'KIBINGA B' },
                { id: 55892, name: 'NAKAVUMA' },
                { id: 55893, name: 'NKANDAKULYOWA' },
              ],
            },
            {
              id: 8900,
              name: 'KYANVUMA',
              villages: [
                { id: 55894, name: 'BUWAIGALA' },
                { id: 55895, name: 'KAZIGO' },
                { id: 55896, name: 'KIWALAZI' },
                { id: 55897, name: 'KYANVUMA T/C' },
                { id: 55898, name: 'KYANVUMA VILLAGE' },
                { id: 55899, name: 'NAKABAALE A' },
                { id: 55900, name: 'NAKABAALE B' },
                { id: 55901, name: 'NAKASEDHERE' },
              ],
            },
            {
              id: 8902,
              name: 'NAWANYAGO',
              villages: [
                { id: 55911, name: 'BUBIRO' },
                { id: 55917, name: 'BUGAGA A' },
                { id: 55918, name: 'BUGAGA B' },
                { id: 55912, name: 'BUTOGONYA' },
                { id: 55913, name: 'BUYEMBA' },
                { id: 55914, name: 'LUZINGA  PARK' },
                { id: 55915, name: 'NAWAMPITI' },
                { id: 55916, name: 'NAWANYAGO (BUGOBI)' },
              ],
            },
          ],
        },
        {
          id: 1886,
          name: 'NAWAMPITI',
          parishes: [
            {
              id: 8903,
              name: 'BUGOMBA',
              villages: [
                { id: 55919, name: 'BUGOMBA' },
                { id: 55920, name: 'BUWANDA' },
                { id: 55921, name: 'NAWANDIO' },
              ],
            },
            {
              id: 8904,
              name: 'BUYOOLA',
              villages: [
                { id: 55922, name: 'BUYOOLA' },
                { id: 55923, name: 'IKONIA A' },
                { id: 55925, name: 'IKONIA BUSIGE' },
                { id: 55924, name: 'IKONIA CENTRAL' },
                { id: 55926, name: 'NAKYERE' },
              ],
            },
            {
              id: 8905,
              name: 'NAKISWIGA',
              villages: [
                { id: 55927, name: 'BUWAMWA' },
                { id: 55928, name: 'NABIKUYI' },
                { id: 55929, name: 'NAKISWIGA  A' },
                { id: 55930, name: 'NAKISWIGA  B' },
                { id: 55931, name: 'NAMAGERA' },
                { id: 55932, name: 'NJABABONA' },
              ],
            },
            {
              id: 8906,
              name: 'NAWAMPITI',
              villages: [
                { id: 55933, name: 'BUZIMBA' },
                { id: 55934, name: 'KITUUTO A' },
                { id: 55935, name: 'KITUUTO B' },
                { id: 55936, name: 'NAWAMPITI' },
              ],
            },
            {
              id: 8907,
              name: 'NAWANKOMPE',
              villages: [
                { id: 55937, name: 'KASOZI' },
                { id: 55938, name: 'NAWANKOMPE  A' },
                { id: 55939, name: 'NAWANKOMPE  B' },
                { id: 55940, name: 'WALUGABA' },
              ],
            },
          ],
        },
        {
          id: 1887,
          name: 'WAIBUGA',
          parishes: [
            {
              id: 8908,
              name: 'BUSIIRO',
              villages: [
                { id: 55941, name: 'BULINDI' },
                { id: 55942, name: 'BUSIIRO' },
                { id: 55943, name: 'BUSIIRO -  BWAMBA' },
                { id: 55948, name: 'BUSIIRO T/C' },
                { id: 55944, name: 'KYAMAWUNDO' },
                { id: 55945, name: "NANVUNAMO 'B'" },
                { id: 55946, name: "NANVUNAMO 'C'" },
                { id: 55947, name: "NANVUNANO 'A'" },
              ],
            },
            {
              id: 8909,
              name: 'BUTIMBWA',
              villages: [
                { id: 55949, name: 'BUKYOGO' },
                { id: 55950, name: 'BUTIMBWA' },
                { id: 55956, name: 'BUTIMBWA B' },
                { id: 55951, name: 'IKONKO' },
                { id: 55952, name: 'LWANIKA' },
                { id: 55953, name: 'NAMAKAKALE' },
                { id: 55957, name: 'NAMAKAKALE B' },
                { id: 55954, name: 'WAIBUGA A' },
                { id: 55955, name: 'WAIBUGA B' },
              ],
            },
            {
              id: 8910,
              name: 'ITAKAIBOLU',
              villages: [
                { id: 55958, name: 'BUKAPALA' },
                { id: 55959, name: 'BWIIRI' },
                { id: 55960, name: 'ITAKAIBOLU A' },
                { id: 55961, name: 'ITAKAIBOLU B' },
                { id: 55962, name: 'KIGAYA' },
              ],
            },
            {
              id: 8911,
              name: 'LWAKI',
              villages: [
                { id: 55963, name: 'KIWANYI' },
                { id: 55964, name: 'LWAKI' },
                { id: 55965, name: 'MAUMO' },
                { id: 55966, name: 'NAMADOPE' },
              ],
            },
            {
              id: 8912,
              name: 'WALIBO',
              villages: [
                { id: 55967, name: 'BUGWANALA' },
                { id: 55973, name: 'BULANGA A' },
                { id: 55974, name: 'BULANGA B' },
                { id: 55968, name: 'BULANGA T/C' },
                { id: 55969, name: 'ITWE' },
                { id: 55970, name: 'MAWUNDO' },
                { id: 55972, name: 'MAWUNDO B' },
                { id: 55971, name: 'WALIBO' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
