import { District } from '../types';

export default {
  id: 52,
  name: 'LUWEERO',
  counties: [
    {
      id: 117,
      name: 'BAMUNANIKA COUNTY',
      sub_counties: [
        {
          id: 738,
          name: 'BAMUNANIKA',
          parishes: [
            {
              id: 3428,
              name: 'KIBANYI',
              villages: [
                { id: 21606, name: 'BUGABO' },
                { id: 21607, name: 'GIRIYADA' },
                { id: 21608, name: 'KALWE' },
                { id: 21609, name: 'KANJUKI' },
                { id: 21610, name: 'KAWUKU' },
                { id: 21611, name: 'KIBANYI' },
                { id: 21612, name: 'KIDOLINDO' },
                { id: 21613, name: 'KYABBUGGA' },
                { id: 21614, name: 'KYANIKA' },
              ],
            },
            {
              id: 3429,
              name: 'KIBIRIZI',
              villages: [
                { id: 21615, name: 'BUSAMBU' },
                { id: 21616, name: 'GAVU' },
                { id: 21617, name: 'KIBIBI-KISOGOZI' },
                { id: 21618, name: 'KIBIRIIZI' },
                { id: 21619, name: 'KISANGA' },
                { id: 21620, name: 'NKOKONJERU' },
                { id: 21621, name: 'NKULUZE' },
              ],
            },
            {
              id: 3430,
              name: 'KITEME',
              villages: [
                { id: 21622, name: 'BUKESA' },
                { id: 21623, name: 'BUTALYAMISANA' },
                { id: 21624, name: 'BUWANUKA' },
                { id: 21625, name: 'BUWEKE' },
                { id: 21626, name: 'KASOLO-BUDDU' },
                { id: 21629, name: 'KASOLO-KITOBOLA' },
                { id: 21627, name: 'KIKONDA' },
                { id: 21628, name: 'KITEME' },
                { id: 21630, name: 'KIVULE' },
                { id: 21631, name: 'KIWEBYA' },
                { id: 21632, name: 'KYONDO' },
                { id: 21633, name: 'KYOTAMUGAVU' },
                { id: 21634, name: 'MALUNGU' },
                { id: 21635, name: 'NALONGO' },
                { id: 21636, name: 'NALWEWETA' },
              ],
            },
            {
              id: 3431,
              name: 'KYAMPISI (BAMUNANIKA)',
              villages: [
                { id: 21637, name: 'BBUTO  A' },
                { id: 21638, name: 'BBUTO  B/PIIDA' },
                { id: 21639, name: 'KAKIRA' },
                { id: 21640, name: 'KANSEKA' },
                { id: 21641, name: 'KASENENE' },
                { id: 21642, name: 'KIKAABYA' },
                { id: 21643, name: 'KISAKU' },
                { id: 21647, name: 'LUBIRI' },
                { id: 21644, name: 'LUTEETE' },
                { id: 21645, name: 'MAGOGO' },
                { id: 21648, name: 'MUYENGA ZONE' },
                { id: 21646, name: 'NDYALUMU' },
              ],
            },
            {
              id: 3432,
              name: 'MPOLOGOMA',
              villages: [
                { id: 21649, name: 'BBUGGA' },
                { id: 21650, name: 'KANGULUMIRA' },
                { id: 21651, name: 'KIYUNGA' },
                { id: 21652, name: 'MITYEBIRI' },
                { id: 21653, name: 'MPOLOGOMA' },
                { id: 21654, name: 'MPUNGU' },
              ],
            },
            {
              id: 3433,
              name: 'SEKAMULI',
              villages: [
                { id: 21655, name: 'KAKOOLA' },
                { id: 21656, name: 'KASIRIBIITI' },
                { id: 21657, name: 'KITTO' },
                { id: 21658, name: 'MPUTTE' },
                { id: 21659, name: 'NAKULABYE' },
                { id: 21660, name: 'NAMAKOFU' },
                { id: 21661, name: 'NDABIRAAKODDALA' },
                { id: 21662, name: 'SEKAMULI' },
                { id: 21663, name: 'WABIYINJA' },
                { id: 21664, name: 'WANTULA' },
              ],
            },
          ],
        },
        {
          id: 739,
          name: 'KALAGALA',
          parishes: [
            {
              id: 3434,
              name: 'BUSIIKA',
              villages: [
                { id: 21665, name: 'BISIIKA' },
                { id: 21670, name: 'BUSIIKA MAIN' },
                { id: 21666, name: 'LUBANYI' },
                { id: 21667, name: 'NAKAFUMU' },
                { id: 21668, name: 'NAMUGANJA' },
                { id: 21669, name: 'WABIKOKOMA' },
              ],
            },
            {
              id: 3435,
              name: 'BUSOKE',
              villages: [
                { id: 21671, name: 'BUSOKE' },
                { id: 21672, name: 'KIWANGULA' },
                { id: 21673, name: 'MPIGI' },
                { id: 21674, name: 'NAKASEETA' },
                { id: 21675, name: 'SAGAALA' },
                { id: 21676, name: 'SEETA' },
                { id: 21677, name: 'VUMBA' },
              ],
            },
            {
              id: 3436,
              name: 'DDEGEYA',
              villages: [
                { id: 21678, name: 'BUGABO' },
                { id: 21679, name: 'BULEMEEZI' },
                { id: 21680, name: 'DDEGEYA CENTRAL' },
                { id: 21681, name: 'KALAGI' },
                { id: 21682, name: 'KIBAJJWE' },
                { id: 21683, name: 'KIREKA' },
                { id: 21684, name: 'NAMWATULIRA' },
              ],
            },
            {
              id: 3437,
              name: 'KALANAMU',
              villages: [
                { id: 21685, name: 'GANGAMA' },
                { id: 21688, name: 'KALAGALA MAIN' },
                { id: 21686, name: 'KALAGALA TOWN' },
                { id: 21687, name: 'KALANAMU' },
                { id: 21689, name: 'KALUNGU' },
                { id: 21690, name: 'KYASAMPAWO' },
                { id: 21691, name: 'NAKIBENGO' },
                { id: 21692, name: 'NAMUSWE' },
              ],
            },
            {
              id: 3438,
              name: 'KAMIRA',
              villages: [
                { id: 21693, name: 'BUNSULE' },
                { id: 21694, name: 'LUKYAMU' },
              ],
            },
            {
              id: 3439,
              name: 'KAYINDU',
              villages: [
                { id: 21695, name: 'BUGODDO' },
                { id: 21696, name: 'BUSAAKWA' },
                { id: 21697, name: 'KALAGALA' },
                { id: 21698, name: 'KAYINDU' },
                { id: 21699, name: 'KYAMPISI' },
                { id: 21700, name: 'KYOGA' },
                { id: 21701, name: 'LUTEETE' },
                { id: 21702, name: 'NABITEETE' },
                { id: 21703, name: 'WAMPEEWO' },
              ],
            },
            {
              id: 3440,
              name: 'LUNYOLYA',
              villages: [
                { id: 21704, name: 'GAAZA' },
                { id: 21705, name: 'KATIKANDEGEYA' },
                { id: 21706, name: 'KISUBI' },
                { id: 21707, name: 'KKOKO DWALIRO' },
                { id: 21708, name: 'KKOKO KYAMBOGO' },
                { id: 21710, name: 'LUNYOLYA' },
                { id: 21709, name: 'NANKAABA' },
              ],
            },
            {
              id: 3441,
              name: 'VVUMBA',
              villages: [
                { id: 21711, name: 'KABEMBE' },
                { id: 21712, name: 'KAKONI' },
                { id: 21713, name: 'KIBANGA' },
                { id: 21714, name: 'KYETUME' },
                { id: 21715, name: 'MAYINDO/KAWANGA' },
                { id: 21716, name: 'NDEEBA' },
                { id: 21717, name: 'VVUMBA' },
              ],
            },
          ],
        },
        {
          id: 740,
          name: 'KAMIRA',
          parishes: [
            {
              id: 3442,
              name: 'KABUNYATA',
              villages: [
                { id: 21718, name: 'KABUNYATA' },
                { id: 21719, name: 'KADULA' },
                { id: 21720, name: 'KIISO' },
                { id: 21721, name: 'MATEMBE' },
              ],
            },
            {
              id: 3443,
              name: 'KASWA',
              villages: [
                { id: 21722, name: 'KAMIRA' },
                { id: 21723, name: 'KIKANDWA' },
                { id: 21726, name: 'KITANSWA' },
                { id: 21724, name: 'NAKASEJJERE' },
                { id: 21725, name: 'NAMUNINGI' },
              ],
            },
            {
              id: 3444,
              name: 'KATAGGWE',
              villages: [
                { id: 21727, name: 'BUKIIBI' },
                { id: 21731, name: 'KAKOOLA' },
                { id: 21728, name: 'KEERA' },
                { id: 21729, name: 'MAKONKONYIGO' },
                { id: 21730, name: 'WANFUFU' },
              ],
            },
            {
              id: 3445,
              name: 'KITENDERI',
              villages: [
                { id: 21732, name: 'BUWANUKA' },
                { id: 21733, name: 'KITENDERI' },
              ],
            },
            {
              id: 3446,
              name: 'MABUYE',
              villages: [
                { id: 21734, name: 'BUGABO' },
                { id: 21735, name: 'KIKONDERE' },
                { id: 21736, name: 'KIZITO' },
                { id: 21737, name: 'KYAKULA' },
                { id: 21738, name: 'KYAMPOLOGOMA' },
                { id: 21739, name: 'MABUYE' },
              ],
            },
            {
              id: 3447,
              name: 'MAZZI',
              villages: [
                { id: 21740, name: 'KAABUKUNGA' },
                { id: 21741, name: 'KAKIRA-KIBANGA' },
                { id: 21744, name: 'KIRIMANTUNGO' },
                { id: 21742, name: 'MAZZI' },
                { id: 21743, name: 'NABINAKA' },
              ],
            },
            {
              id: 3448,
              name: 'NAMBERE',
              villages: [
                { id: 21745, name: 'BAKATADDE' },
                { id: 21746, name: 'GALIKWOLEKA' },
                { id: 21747, name: 'MBOGA' },
                { id: 21749, name: 'NAMBEERE' },
                { id: 21750, name: 'NANTEEKO' },
                { id: 21748, name: 'SEMABIIRA' },
              ],
            },
          ],
        },
        {
          id: 741,
          name: 'KIKYUSA',
          parishes: [
            {
              id: 3449,
              name: 'KIBENGO',
              villages: [
                { id: 21751, name: 'BINIKIRA' },
                { id: 21752, name: 'KATABONA' },
                { id: 21753, name: 'KYEPUKULU' },
                { id: 21754, name: 'LUKOWE' },
                { id: 21755, name: 'MANYWA' },
                { id: 21756, name: 'MAYANGAYANGA' },
                { id: 21757, name: 'NAMALIMBA' },
              ],
            },
            {
              id: 3450,
              name: 'KIREKU',
              villages: [
                { id: 21765, name: 'KALAGALA' },
                { id: 21758, name: 'KATASULE' },
                { id: 21759, name: 'KIKANDWA' },
                { id: 21760, name: 'KIREKU/LWAMULA' },
                { id: 21761, name: 'KIWANGUZI' },
                { id: 21762, name: 'MULUNGI-OMU' },
                { id: 21763, name: 'NAMAKOFU' },
                { id: 21764, name: 'SENYOMO A' },
              ],
            },
            {
              id: 3451,
              name: 'KIZIBA',
              villages: [
                { id: 21766, name: 'KABALOGE' },
                { id: 21767, name: 'KANYOGOGA' },
                { id: 21776, name: 'KATWE' },
                { id: 21768, name: 'KIKYUSA KELEZIA ZONE' },
                { id: 21769, name: 'KIWAMIREMBE' },
                { id: 21770, name: 'KYAKATULA' },
                { id: 21774, name: 'LUFFULA' },
                { id: 21775, name: 'MUKYUSA' },
                { id: 21771, name: 'NAKABIITO' },
                { id: 21772, name: 'SENYOMO B' },
                { id: 21773, name: 'WAKIVULE' },
              ],
            },
            {
              id: 3454,
              name: 'KYAMPOGOLA',
              villages: [
                { id: 21788, name: 'BWABA' },
                { id: 21789, name: 'KAWE' },
                { id: 21790, name: 'KYAMPOGOLA' },
                { id: 21791, name: 'MASINGA' },
              ],
            },
            {
              id: 3452,
              name: 'WABUSANA',
              villages: [
                { id: 21777, name: 'BUZZIBWERA' },
                { id: 21778, name: 'GAMBIRANA' },
                { id: 21779, name: 'KANKOOLE' },
                { id: 21780, name: 'KATALEKAKE' },
                { id: 21781, name: 'TTEMA' },
                { id: 21782, name: 'WABUSAANA' },
              ],
            },
            {
              id: 3453,
              name: 'WANKAANYA',
              villages: [
                { id: 21783, name: 'GAYAZA' },
                { id: 21784, name: 'KAVULE' },
                { id: 21785, name: 'LUSANJA' },
                { id: 21786, name: 'MUSANJE' },
                { id: 21787, name: 'WANKAANYA' },
              ],
            },
          ],
        },
        {
          id: 742,
          name: 'ZIROBWE',
          parishes: [
            {
              id: 3455,
              name: 'BUBUUBI',
              villages: [
                { id: 21792, name: 'BUBUUBI' },
                { id: 21793, name: 'KABUWOMERO' },
                { id: 63126, name: 'KATOOGO' },
                { id: 21794, name: 'MASUNKWE' },
                { id: 21795, name: 'NABITETE' },
                { id: 21798, name: 'NAMAKOFU' },
                { id: 21796, name: 'NAMAKOFU/NAKABULULU' },
                { id: 21797, name: 'WANJAZA' },
              ],
            },
            {
              id: 3456,
              name: 'BUKIMU',
              villages: [
                { id: 21799, name: 'BUKASA/KIKUTUZI' },
                { id: 21800, name: 'BUKIMU' },
                { id: 21801, name: 'KASOKOSO' },
                { id: 21802, name: 'KIRYANKONZI' },
                { id: 21803, name: 'KISULA' },
                { id: 21804, name: 'MPANGATI' },
                { id: 21805, name: 'NAMAWOJJA' },
                { id: 21806, name: 'ZIROBWE' },
                { id: 21807, name: 'ZIROBWE CENTRAL B' },
              ],
            },
            {
              id: 3457,
              name: 'KABULANAKA',
              villages: [
                { id: 21811, name: 'BULAMI T/C' },
                { id: 21808, name: 'JANDA A' },
                { id: 21812, name: 'JANDA B' },
                { id: 21809, name: 'KABULANAKA' },
                { id: 21810, name: 'MANYAMA' },
              ],
            },
            {
              id: 3458,
              name: 'KAKAKALA',
              villages: [
                { id: 21813, name: 'BUBENGWA' },
                { id: 21814, name: 'KAKAKALA' },
                { id: 21815, name: 'KALERE' },
                { id: 21816, name: 'KIREEBA' },
                { id: 21817, name: 'KYAMBOGO' },
                { id: 21818, name: 'KYEWANISE' },
                { id: 21819, name: 'WAKATAAYI' },
              ],
            },
            {
              id: 3459,
              name: 'KYETUME',
              villages: [
                { id: 21820, name: 'BUYONDO' },
                { id: 21824, name: 'KAMWANO' },
                { id: 21821, name: 'KIRAMBULA' },
                { id: 21822, name: 'KYETUME' },
                { id: 21825, name: 'NAKASEETA' },
                { id: 21823, name: 'WABUTUNGULU' },
                { id: 21826, name: 'WABUTUNGULU T/C' },
              ],
            },
            {
              id: 3461,
              name: 'NAKIGOZA',
              villages: [
                { id: 21837, name: 'BAAGYA' },
                { id: 21838, name: 'GWALIMUTALA' },
                { id: 21832, name: 'KIYIIYA' },
                { id: 21833, name: 'KYAMBOGO' },
                { id: 21834, name: 'LUTEETE' },
                { id: 21835, name: 'NAKIGOZA A' },
                { id: 21839, name: 'NAKIGOZA B' },
                { id: 21840, name: 'NAMATOVU' },
                { id: 21836, name: 'NAWABANGO' },
              ],
            },
            {
              id: 3460,
              name: 'NAMBI',
              villages: [
                { id: 21827, name: 'BBULABAKULU' },
                { id: 21828, name: 'NAMAKOFU' },
                { id: 21829, name: 'NAMBI' },
                { id: 21830, name: 'NAMPUNGE' },
                { id: 21831, name: 'NTAWAWULWA' },
              ],
            },
            {
              id: 3462,
              name: 'NGALONKALU',
              villages: [
                { id: 21841, name: 'BUYIKI' },
                { id: 21846, name: 'KAJJAWO' },
                { id: 21842, name: 'KONKO/TOMI' },
                { id: 21843, name: 'NAKISAMATA' },
                { id: 21844, name: 'NGALONKALU' },
                { id: 70542, name: 'SSIMBA' },
                { id: 21845, name: 'TIMBA/SSANGA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 115,
      name: 'KATIKAMU COUNTY NORTH',
      sub_counties: [
        {
          id: 729,
          name: 'BUTUNTUMULA',
          parishes: [
            {
              id: 3372,
              name: 'BAMUGOLODDE',
              villages: [
                { id: 21243, name: 'BAMUGOLODDE' },
                { id: 21244, name: 'GENDA' },
                { id: 21245, name: 'GWEYAWADDE' },
                { id: 21246, name: 'KAKUUTO' },
                { id: 21247, name: 'KASIISO' },
                { id: 21248, name: 'KAZINGA' },
                { id: 21249, name: 'KIBIKKE-KATENTE' },
                { id: 21250, name: 'KIKUNYU' },
                { id: 21251, name: 'LUMONDE' },
                { id: 21252, name: 'MANYA' },
              ],
            },
            {
              id: 3373,
              name: 'BUKAMBAGGA',
              villages: [
                { id: 21253, name: 'BUKAMBAGGA' },
                { id: 21254, name: 'KATUUMU' },
                { id: 21255, name: 'KITO' },
                { id: 21256, name: 'LUKYAMU' },
                { id: 21257, name: 'LUSENKE' },
              ],
            },
            {
              id: 3374,
              name: 'KAKABALA',
              villages: [
                { id: 21258, name: 'GAYAZA' },
                { id: 21259, name: 'KAKABALA' },
                { id: 21260, name: 'KAKIINZI-KAKOOLA' },
                { id: 21261, name: 'KAKIINZI-LUGAGALA' },
                { id: 21262, name: 'KYAMUYINULA' },
                { id: 21263, name: 'NALONGO' },
                { id: 21264, name: 'NAMATOGONYA' },
                { id: 21265, name: 'NDIBULUNGI' },
                { id: 21266, name: 'VVUMBA' },
                { id: 21267, name: 'YANDWE' },
              ],
            },
            {
              id: 3375,
              name: 'KAKINZI',
              villages: [
                { id: 21268, name: 'KABANYI' },
                { id: 21269, name: 'KAKINZI' },
                { id: 21270, name: 'KASOZI' },
                { id: 21271, name: 'KAYONZA' },
                { id: 21272, name: 'KIJJUKIRA' },
                { id: 21273, name: 'KYAMBOGO' },
                { id: 21274, name: 'NAKAKONO' },
              ],
            },
            {
              id: 3376,
              name: 'KALWANGA',
              villages: [
                { id: 21275, name: 'KAAYA FARM/KITABULA' },
                { id: 21276, name: 'KAGALAMA' },
                { id: 21277, name: 'LUKIIZI' },
                { id: 21278, name: 'NABIGOZA' },
              ],
            },
            {
              id: 3377,
              name: 'KYAWANGABI',
              villages: [
                { id: 21279, name: 'BUZIRANDUULU' },
                { id: 21280, name: 'KATEERA' },
                { id: 21281, name: 'KYAWANGABI' },
                { id: 21282, name: 'LUTUULA' },
                { id: 21283, name: 'MUWANGI' },
                { id: 21284, name: 'NABUTAKA' },
                { id: 21285, name: 'NAKAKONO' },
                { id: 21286, name: 'NALUVULE' },
                { id: 21287, name: 'NANSAKA' },
              ],
            },
            {
              id: 3378,
              name: 'NGOGOLO',
              villages: [
                { id: 21288, name: 'BUKUSU' },
                { id: 21289, name: 'BUTUNTUMULA' },
                { id: 21290, name: 'KASAALA' },
                { id: 21291, name: 'KIIYA' },
                { id: 21292, name: 'NGOGOLO' },
                { id: 21293, name: 'NSENGE' },
                { id: 21294, name: 'WANONDA' },
              ],
            },
          ],
        },
        {
          id: 730,
          name: 'KATIKAMU',
          parishes: [
            {
              id: 3379,
              name: 'BUYUKI',
              villages: [
                { id: 21295, name: 'BUNYIRI' },
                { id: 21296, name: 'BUYUKI' },
                { id: 21297, name: 'GULAMA' },
                { id: 21298, name: 'KACWAMPA' },
                { id: 21299, name: 'KIRYAMULONDO' },
                { id: 21300, name: 'KITEREDDE' },
                { id: 21301, name: 'KKUBAMITWE' },
                { id: 21302, name: 'LUWUBE' },
                { id: 21303, name: 'MONDE' },
                { id: 21304, name: 'NTEBBE' },
                { id: 21305, name: 'SINGO' },
              ],
            },
            {
              id: 3380,
              name: 'KYALUGONDO',
              villages: [
                { id: 21306, name: 'BULINDE' },
                { id: 21307, name: 'BUTANZA' },
                { id: 21308, name: 'BUTEKE' },
                { id: 21309, name: 'KIGUGU' },
                { id: 21310, name: 'KIKOZA' },
                { id: 21311, name: 'KYALUGONDO' },
                { id: 21312, name: 'LUKIRA' },
                { id: 21313, name: 'LUTEMBE' },
                { id: 21314, name: 'NGABO' },
              ],
            },
            {
              id: 3381,
              name: 'MIGADDE',
              villages: [
                { id: 21315, name: 'BUTANZA' },
                { id: 21316, name: 'GAVU' },
                { id: 21317, name: 'KALEMBWE' },
                { id: 21318, name: 'KANYIKE  I' },
                { id: 21319, name: 'KAZINGA' },
                { id: 21320, name: 'KIREMBWE' },
                { id: 21322, name: 'KOOJO LUTUNKU' },
                { id: 21321, name: 'KOOJO PROPER' },
                { id: 21323, name: 'LUKOMERA' },
                { id: 21324, name: 'MIGADDE' },
                { id: 21325, name: 'NAKYEWA' },
                { id: 21326, name: 'NALUVULE' },
                { id: 21327, name: 'NETUNZE' },
                { id: 21328, name: 'NSANVU' },
                { id: 21329, name: 'NTANGALA' },
              ],
            },
          ],
        },
        {
          id: 732,
          name: 'LUWEERO  TOWN COUNCIL',
          parishes: [
            {
              id: 3396,
              name: 'KASANA P.W.D WARD',
              villages: [
                { id: 21401, name: 'KIKUBAJJINJA' },
                { id: 21402, name: 'MABANDA' },
                { id: 21403, name: 'PWD' },
              ],
            },
            {
              id: 3391,
              name: 'KAVULE WARD',
              villages: [
                { id: 21385, name: 'KAKOOKOLO' },
                { id: 21386, name: 'KAVULE' },
              ],
            },
            {
              id: 3392,
              name: 'KIWOGOZI WARD',
              villages: [
                { id: 21387, name: 'KALONGO-MITI' },
                { id: 21388, name: 'KASANA MARKET' },
                { id: 21389, name: 'KIWOGOZI' },
                { id: 21390, name: 'MABAALE' },
              ],
            },
            {
              id: 3393,
              name: 'LUWERO CENTRAL WARD',
              villages: [
                { id: 21391, name: 'KATALE' },
                { id: 21392, name: 'KATWE' },
                { id: 21393, name: 'LUMU ZONE' },
                { id: 21394, name: 'MULIRO ZONE' },
              ],
            },
            {
              id: 3394,
              name: 'LUWERO SOUTH EAST WARD',
              villages: [
                { id: 21395, name: 'KALONGO' },
                { id: 21396, name: 'KIYENJE' },
                { id: 21397, name: 'KIZITO' },
              ],
            },
            {
              id: 3395,
              name: 'LUWERO WEST WARD',
              villages: [
                { id: 21398, name: 'BINYONYI ZONE' },
                { id: 21399, name: 'GALUWEERO ZONE' },
                { id: 21400, name: 'KASOMA ZONE' },
              ],
            },
          ],
        },
        {
          id: 731,
          name: 'LUWERO',
          parishes: [
            {
              id: 3382,
              name: 'BWAZIBA',
              villages: [
                { id: 21330, name: 'BUTANSWA' },
                { id: 21331, name: 'BWAZIBA' },
                { id: 21332, name: 'KAKAKALA' },
                { id: 21333, name: 'KIKEREGE' },
                { id: 21334, name: 'LUTEETE' },
                { id: 21335, name: 'NAKIJJU' },
                { id: 21336, name: 'NDAGGA-BWEYA' },
                { id: 21337, name: 'NKONDO' },
              ],
            },
            {
              id: 3383,
              name: 'BWEYEYO',
              villages: [
                { id: 21338, name: 'BWEYEYO' },
                { id: 21339, name: 'KANYOGOGA' },
                { id: 21340, name: 'NSAASI' },
                { id: 21341, name: 'TEBALYALA' },
              ],
            },
            {
              id: 3384,
              name: 'KABAKEDDI',
              villages: [
                { id: 21342, name: 'KABAKEDI' },
                { id: 21343, name: 'KIBULA' },
                { id: 21344, name: 'KIGAVU' },
                { id: 21345, name: 'KYEYAGALIRE' },
                { id: 21346, name: 'LWOGI' },
                { id: 21347, name: 'NALONGO' },
                { id: 21348, name: 'NALYAMAGONJA' },
                { id: 21349, name: 'NSANVU' },
              ],
            },
            {
              id: 3385,
              name: 'KAGUGO',
              villages: [
                { id: 21350, name: 'BUKUMA' },
                { id: 21351, name: 'BUNYAAKA' },
                { id: 21352, name: 'BUNYEENYE' },
                { id: 21356, name: 'DDEKABUSA' },
                { id: 21353, name: 'KAGUGO' },
                { id: 21354, name: 'KYETUME' },
                { id: 21355, name: 'SAKABUSOLO' },
              ],
            },
            {
              id: 3386,
              name: 'KASAALA',
              villages: [
                { id: 21357, name: 'KASAALA' },
                { id: 21358, name: 'KATUNDU' },
                { id: 21359, name: 'KYEGOMBWA' },
                { id: 21360, name: 'KYEVUNZE' },
              ],
            },
            {
              id: 3387,
              name: 'KATUGO',
              villages: [
                { id: 21361, name: 'BALITTA' },
                { id: 21362, name: 'BULANZI' },
                { id: 21365, name: 'KABAAGA' },
                { id: 21363, name: 'KATUGO' },
                { id: 21364, name: 'MULUNGI-OMU' },
              ],
            },
            {
              id: 3388,
              name: 'KIGOMBE',
              villages: [
                { id: 21366, name: 'BULAWULA' },
                { id: 21367, name: 'KIBANVU' },
                { id: 21368, name: 'KIGOMBE' },
                { id: 21369, name: 'KIWUMPA' },
                { id: 21370, name: 'MAMULI  A' },
                { id: 21371, name: 'MAMULI  B' },
                { id: 21372, name: 'NSOZIBIRYE' },
              ],
            },
            {
              id: 3389,
              name: 'KIKUBE',
              villages: [
                { id: 21373, name: 'KANYOGOGA' },
                { id: 21374, name: 'KAWUULA' },
                { id: 21375, name: 'KIKUBE' },
                { id: 21376, name: 'KYAMPISI' },
                { id: 21377, name: 'KYEBANDO' },
                { id: 21378, name: 'NAKINYAMA' },
              ],
            },
            {
              id: 3390,
              name: 'NAKIKOOTA',
              villages: [
                { id: 21379, name: 'BUKASA' },
                { id: 21380, name: 'BUKOMBA' },
                { id: 21381, name: 'KIRANGIRA' },
                { id: 21382, name: 'KIRYANYONZA' },
                { id: 21383, name: 'NAKIKOOTA' },
                { id: 21384, name: 'NKOLOOGI' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 116,
      name: 'KATIKAMU COUNTY SOUTH',
      sub_counties: [
        {
          id: 733,
          name: 'BOMBO TOWN COUNCIL',
          parishes: [
            {
              id: 3397,
              name: 'BOMBO CENTRAL WARD',
              villages: [
                { id: 21404, name: 'BOMBO CENTRAL' },
                { id: 21405, name: 'KALAGALA ROAD' },
                { id: 21406, name: 'KAMPALA ROAD' },
                { id: 21407, name: 'KINYO ROAD' },
              ],
            },
            {
              id: 3402,
              name: 'GANGAMA WARD',
              villages: [
                { id: 21424, name: 'GANGAMA  A' },
                { id: 21425, name: 'GANGAMA  B' },
                { id: 21426, name: 'LUTAMANDWA  A' },
                { id: 21427, name: 'LUTAMANDWA  B' },
              ],
            },
            {
              id: 3398,
              name: 'LOMULE WARD',
              villages: [
                { id: 21408, name: 'LOMULE CENTRAL' },
                { id: 21409, name: 'LOMULE NORTH' },
                { id: 21410, name: 'LOMULE SOUTH' },
                { id: 21411, name: 'UMEA COMPLEX' },
                { id: 21412, name: 'WABIKOOKOMA' },
              ],
            },
            {
              id: 3401,
              name: 'MPAKAWERO WARD',
              villages: [
                { id: 21421, name: 'GOGONYA' },
                { id: 21422, name: 'LUFULA' },
                { id: 21423, name: 'MPAKAWERO MAIN' },
              ],
            },
            {
              id: 3400,
              name: 'NAMALIGA WARD',
              villages: [
                { id: 21416, name: 'NAMALIGA  CENTRAL' },
                { id: 21417, name: 'NAMALIGA  EAST' },
                { id: 21418, name: 'NAMALIGA NORTH' },
                { id: 21419, name: 'NAMALIGA SOUTH' },
                { id: 21420, name: 'NAMALIGA WEST' },
              ],
            },
            {
              id: 3399,
              name: 'NKOKONJERU WARD',
              villages: [
                { id: 21413, name: 'KABULANAKA  EAST' },
                { id: 21414, name: 'KABULANAKA WEST' },
                { id: 21415, name: 'NKOKONJERU' },
              ],
            },
          ],
        },
        {
          id: 734,
          name: 'KATIKAMU',
          parishes: [
            {
              id: 3403,
              name: 'BUKEEKA',
              villages: [
                { id: 21428, name: 'BUFUMBANSWA' },
                { id: 21429, name: 'BUKEEKA' },
                { id: 21430, name: 'KANDE' },
                { id: 21431, name: 'KAZINGA' },
                { id: 21432, name: 'KISULE' },
                { id: 21433, name: 'MONDE/BUKEEKA' },
                { id: 21434, name: 'MULINDWA' },
                { id: 21435, name: 'NAKASEETA' },
                { id: 21436, name: 'NKONGE' },
                { id: 21437, name: 'NSWANTA' },
              ],
            },
            {
              id: 3405,
              name: 'KIKOMA',
              villages: [
                { id: 21452, name: 'BUKALASA' },
                { id: 21453, name: 'GANGU' },
                { id: 21454, name: 'GEMBE' },
                { id: 21455, name: 'KIBIKKE' },
                { id: 21456, name: 'KIRYAMBIDDE' },
                { id: 21457, name: 'KUNGU' },
                { id: 21458, name: 'KYEVUNZE' },
                { id: 21459, name: 'NSERO' },
              ],
            },
            {
              id: 3404,
              name: 'MUSAALE',
              villages: [
                { id: 21438, name: 'BUGGA' },
                { id: 21439, name: 'BUSONGOLA' },
                { id: 21440, name: 'BUSULA  A' },
                { id: 21441, name: 'BUSULA  B' },
                { id: 21442, name: 'KAKAKALA' },
                { id: 21443, name: 'KAKINGA' },
                { id: 21444, name: 'KASWA' },
                { id: 21445, name: 'KIBISI' },
                { id: 21446, name: 'LUKOOGE' },
                { id: 21447, name: 'LUMUNDI' },
                { id: 21448, name: 'NGANJO' },
                { id: 21449, name: 'NNONGO' },
                { id: 21450, name: 'NSAWO' },
                { id: 21451, name: 'SEMPA' },
              ],
            },
            {
              id: 3406,
              name: 'TWEYANZE',
              villages: [
                { id: 21460, name: 'BUTUNDU' },
                { id: 21461, name: 'BUWANUKA' },
                { id: 21462, name: 'KIKAABYA' },
                { id: 21463, name: 'KIRWANYI' },
                { id: 21464, name: 'KITO' },
                { id: 21465, name: 'LUKYAMU' },
                { id: 21466, name: 'LUSENKE' },
                { id: 21467, name: 'MONDE' },
                { id: 21468, name: 'TWEYANZE' },
              ],
            },
          ],
        },
        {
          id: 735,
          name: 'MAKULUBITA',
          parishes: [
            {
              id: 3407,
              name: 'KAGOGO',
              villages: [
                { id: 21469, name: 'BOWA' },
                { id: 21470, name: 'BULIGWE-NTINDA' },
                { id: 21471, name: 'NAKALEMBEKA' },
                { id: 21472, name: 'NAMAGALA/BULIGGWE' },
                { id: 21473, name: 'NAMYESO' },
                { id: 21474, name: 'SEMYUNGU-KAGOGO' },
              ],
            },
            {
              id: 3408,
              name: 'KALASA',
              villages: [
                { id: 21475, name: 'KABEMBE' },
                { id: 21476, name: 'KABIRA/KATIITI' },
                { id: 21477, name: 'KALASA' },
                { id: 21478, name: 'KATIITI/BIBBO' },
                { id: 21479, name: 'MUGOGO' },
              ],
            },
            {
              id: 3409,
              name: 'KANGAVE',
              villages: [
                { id: 21480, name: 'BUGOMBA' },
                { id: 21481, name: 'KANGAVVE' },
                { id: 21482, name: 'KAWUMU' },
                { id: 21483, name: 'KIKUNYU' },
                { id: 21484, name: 'KIREMEERA' },
              ],
            },
            {
              id: 3410,
              name: 'KANYANDA',
              villages: [
                { id: 21485, name: 'BULAMBA' },
                { id: 21486, name: 'KANYANDA' },
                { id: 21490, name: 'KITO-KANYANDA' },
                { id: 21487, name: 'MULAMA-KITEBERE' },
                { id: 21488, name: 'NAMATAKA' },
                { id: 21489, name: 'SINGO-BUKWESE' },
              ],
            },
            {
              id: 3411,
              name: 'KASOZI',
              villages: [
                { id: 21497, name: 'BUGAYO-SENGA' },
                { id: 21491, name: 'BUKEKETE' },
                { id: 21492, name: 'KABENGEREDDWA' },
                { id: 21493, name: 'KASOZI' },
                { id: 21494, name: 'KYAMUWOOYA' },
                { id: 21495, name: 'LUBWAMA' },
                { id: 21496, name: 'MAGGWA' },
              ],
            },
            {
              id: 3412,
              name: 'MAKULUBITA',
              villages: [
                { id: 21498, name: 'KIDUUKULU' },
                { id: 21499, name: 'KIKOKO' },
                { id: 21500, name: 'KITWALANYE' },
                { id: 21501, name: 'MAKULUBITA  A' },
                { id: 21502, name: 'MAKULUBITA  B' },
                { id: 21503, name: 'NAKIKONGE' },
              ],
            },
            {
              id: 3413,
              name: 'MAWALE',
              villages: [
                { id: 21504, name: 'BUGOZI' },
                { id: 21505, name: 'BUTEZA' },
                { id: 21506, name: 'KAGEMBE' },
                { id: 21507, name: 'KAWUMU' },
                { id: 21508, name: 'LUKAAKA' },
                { id: 21509, name: 'MAWALE' },
              ],
            },
            {
              id: 3414,
              name: 'NSANVU',
              villages: [
                { id: 21510, name: 'KASIZI' },
                { id: 21511, name: 'MAWU' },
                { id: 21512, name: 'MULIRA' },
                { id: 21513, name: 'NAMAYAMBA' },
                { id: 21514, name: 'WESUNE' },
              ],
            },
            {
              id: 3415,
              name: 'WALULEETA',
              villages: [
                { id: 21515, name: 'BAKIJJULULA' },
                { id: 21516, name: 'BOWA-KIBIRA' },
                { id: 21520, name: 'BUGUNGU' },
                { id: 21519, name: 'BWETYABA' },
                { id: 21521, name: 'KAWAGALO' },
                { id: 21518, name: 'MPUMUDDE' },
                { id: 21517, name: 'WALULEETA' },
              ],
            },
          ],
        },
        {
          id: 736,
          name: 'NYIMBWA',
          parishes: [
            {
              id: 3419,
              name: 'BAJJO',
              villages: [
                { id: 21562, name: 'BAJJO ZONE II' },
                { id: 21553, name: 'KIKANDAGGA' },
                { id: 21554, name: 'KIRERANGALO' },
                { id: 21555, name: 'KISINGIRI ZONE  I' },
                { id: 21556, name: 'KONDE' },
                { id: 21557, name: 'LUKOLE TOWN' },
                { id: 21558, name: 'LUMANSI' },
                { id: 21559, name: 'NAANYWA A' },
                { id: 21560, name: 'NAANYWA B' },
                { id: 21561, name: 'SSASASSA' },
              ],
            },
            {
              id: 3421,
              name: 'BUVUMA',
              villages: [
                { id: 21574, name: 'BUFUMBANSWA' },
                { id: 21575, name: 'KIBAMBULA' },
                { id: 21576, name: 'KIKUBAMPAGI' },
                { id: 21577, name: 'KIZEEYI' },
                { id: 21578, name: 'NKONDO' },
              ],
            },
            {
              id: 3418,
              name: 'KALULE',
              villages: [
                { id: 21544, name: 'BWASANKU' },
                { id: 21545, name: 'KALULE TOWN' },
                { id: 21546, name: 'KALULE VILLAGE' },
                { id: 21547, name: 'KAZINGA' },
                { id: 21548, name: 'KIBAMBA' },
                { id: 21549, name: 'KWESE' },
                { id: 21550, name: 'MPANDE' },
                { id: 21551, name: 'NTONYEZE' },
                { id: 21552, name: 'SINALYA' },
              ],
            },
            {
              id: 3420,
              name: 'KIYANDA',
              villages: [
                { id: 21563, name: 'BBAALE  CENTRAL  C' },
                { id: 21564, name: 'BBAALE KAMUZINGIZA' },
                { id: 21565, name: 'GUNDA' },
                { id: 21566, name: 'KABULANAKA' },
                { id: 21567, name: 'KAYUNGA' },
                { id: 21568, name: 'KIKUNGAANYA' },
                { id: 21569, name: 'KISOOBA' },
                { id: 21570, name: 'KIYANDA' },
                { id: 21571, name: 'LUYOBYO' },
                { id: 21572, name: 'MUBANDA' },
                { id: 21573, name: 'NANDERE' },
              ],
            },
            {
              id: 3416,
              name: 'NAKATONYA',
              villages: [
                { id: 21522, name: 'ASURU' },
                { id: 21523, name: 'BEMBE CENTRAL' },
                { id: 21524, name: 'BEMBE EAST' },
                { id: 21525, name: 'BUTAMBUZA' },
                { id: 21526, name: 'GGOGONYA' },
                { id: 21527, name: 'KAYANJA' },
                { id: 21528, name: 'KAZINGA' },
                { id: 21529, name: 'KIKOMEKO' },
                { id: 21530, name: 'MAYIRIKITI' },
                { id: 21531, name: 'NYIMBWA' },
                { id: 21532, name: 'SEDERTULA' },
                { id: 21533, name: 'WABULANKOKO' },
              ],
            },
            {
              id: 3417,
              name: 'SSAMBWE',
              villages: [
                { id: 21534, name: 'BUYEGO  A' },
                { id: 21535, name: 'BUYEGO  B' },
                { id: 21536, name: 'KAKUTE' },
                { id: 21537, name: 'KIYANA' },
                { id: 21538, name: 'NALWANA' },
                { id: 21539, name: 'NDEJJE KABUYE' },
                { id: 21540, name: 'NDEJJE SCHOOL' },
                { id: 21541, name: 'SSAMBWE  A' },
                { id: 21542, name: 'SSAMBWE  B' },
                { id: 21543, name: 'SSAMBWE  C' },
              ],
            },
          ],
        },
        {
          id: 737,
          name: 'WOBULENZI TOWN COUNCIL',
          parishes: [
            {
              id: 3427,
              name: 'BUKALASA WARD',
              villages: [
                { id: 21600, name: 'BUKALASA  CENTRAL' },
                { id: 21601, name: 'BUKALASA LOWER' },
                { id: 21602, name: 'BUKALASA NORTH/CENTRAL' },
                { id: 21603, name: 'BUKALASA SOUTH/CENTRAL' },
                { id: 21604, name: 'BUKALASA UPPER EAST' },
                { id: 21605, name: 'BUKALASA UPPER WEST' },
              ],
            },
            {
              id: 3422,
              name: 'BUKOLWA WARD',
              villages: [
                { id: 21579, name: 'BUKOLWA  CENTRAL' },
                { id: 21580, name: 'GWAFU' },
                { id: 21582, name: 'KATIKAMU PROPER' },
                { id: 21581, name: 'LUSIYA' },
              ],
            },
            {
              id: 3426,
              name: 'KATIKAMU WARD',
              villages: [
                { id: 21598, name: 'GALA' },
                { id: 21595, name: 'KASENENE' },
                { id: 21599, name: 'KATIKAMU SDA' },
                { id: 21596, name: 'LUTAMU' },
                { id: 21597, name: 'LUYIMA' },
              ],
            },
            {
              id: 3423,
              name: 'WOBULENZI CENTRAL WARD',
              villages: [
                { id: 21583, name: 'KATALE' },
                { id: 21584, name: 'KIKASA' },
                { id: 21585, name: 'KIKOMA' },
                { id: 21586, name: 'LUZZI' },
              ],
            },
            {
              id: 3424,
              name: 'WOBULENZI EAST WARD',
              villages: [
                { id: 21587, name: 'KIGULU' },
                { id: 21588, name: 'KISAAWE' },
                { id: 21589, name: 'KITTANTE' },
                { id: 21590, name: 'NAKASERO' },
              ],
            },
            {
              id: 3425,
              name: 'WOBULENZI WEST WARD',
              villages: [
                { id: 21591, name: 'MODERN' },
                { id: 21592, name: 'NAKADINGIDI' },
                { id: 21593, name: 'SIKANUSU' },
                { id: 21594, name: 'WAMPAMBA' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
