import { District } from '../index';

export default {
  id: 108,
  name: 'LYANTONDE',
  counties: [
    {
      id: 260,
      name: 'KABULA COUNTY',
      sub_counties: [
        {
          id: 1696,
          name: 'KALIIRO',
          parishes: [
            {
              id: 8060,
              name: 'KABATEMA',
              villages: [
                { id: 49999, name: 'BULUNGA' },
                { id: 50000, name: 'KABATEMA' },
                { id: 50001, name: 'KANONI' },
                { id: 50002, name: 'KASAMBYA' },
                { id: 50003, name: 'KIGANDO' },
                { id: 50004, name: 'KINONI A' },
                { id: 50005, name: 'KINONI B' },
                { id: 50006, name: 'KINONI C' },
                { id: 50007, name: 'KYAKALAZIRE' },
                { id: 50008, name: 'KYAKALEMA' },
                { id: 50009, name: 'LWENSAALI' },
                { id: 50010, name: 'NAKASEETA A' },
                { id: 50011, name: 'NAKASEETA B' },
              ],
            },
            {
              id: 8061,
              name: 'KASAMBYA',
              villages: [
                { id: 50012, name: 'KALAMBI A' },
                { id: 50013, name: 'KALAMBI B' },
                { id: 50014, name: 'KASAMBYA' },
                { id: 50015, name: 'KASULA' },
                { id: 50016, name: 'KATAGENGERA' },
                { id: 50017, name: 'KIGAAGA' },
                { id: 50018, name: 'KITOVU' },
                { id: 50019, name: 'LWABIJOGO' },
                { id: 50020, name: 'MUGAMBA' },
              ],
            },
            {
              id: 8062,
              name: 'KIYINDA',
              villages: [
                { id: 50021, name: 'KAMENGO' },
                { id: 50022, name: 'KIBISI' },
                { id: 50023, name: 'KISETULA' },
                { id: 50024, name: 'KITESA' },
                { id: 50025, name: 'KIWANGIRE' },
                { id: 50026, name: 'KIYINDA  T/C' },
                { id: 50027, name: 'KIYINDA VILLAGE' },
                { id: 50028, name: 'KYAKALINDA' },
                { id: 50029, name: 'KYALWANDEMU' },
                { id: 50030, name: 'KYAMULAMA' },
                { id: 50031, name: 'KYAMUSALE' },
                { id: 50032, name: 'RUGONERA' },
              ],
            },
            {
              id: 8063,
              name: 'KYAKUTEREKERA',
              villages: [
                { id: 50033, name: 'BYONGE' },
                { id: 50034, name: 'KABUNDI' },
                { id: 50035, name: 'KANKUBEBE' },
                { id: 50036, name: 'KYEMBOGO' },
                { id: 50037, name: 'KYEMPISI' },
                { id: 50038, name: 'KYENGEZA' },
                { id: 50039, name: 'MAKUKULU' },
                { id: 50040, name: 'MUSHAIJA' },
                { id: 50041, name: 'NAKISAJJA A' },
                { id: 50046, name: 'NAKISAJJA B' },
                { id: 50042, name: 'RUGARAMA' },
                { id: 50043, name: 'RWEMITUNGA' },
                { id: 50044, name: 'RWENTONDO-KABAJUNGU' },
                { id: 50045, name: 'RWENTONDO-NAMUTAMBA' },
              ],
            },
          ],
        },
        {
          id: 1703,
          name: 'KALIIRO TOWN COUNCIL',
          parishes: [
            {
              id: 8088,
              name: 'KALIIRO CENTRAL WARD',
              villages: [
                { id: 50204, name: 'GAYAZA' },
                { id: 62325, name: 'KALIIRO I' },
                { id: 50205, name: 'KALIIRO II' },
                { id: 50206, name: 'KALIIRO III' },
                { id: 63383, name: 'KIBISI I' },
              ],
            },
            {
              id: 8087,
              name: 'KALIIRO WARD',
              villages: [
                { id: 50199, name: 'KENYERERE' },
                { id: 50197, name: 'KIBISI II' },
                { id: 50198, name: 'KIBISI III' },
                { id: 50200, name: 'KIWUMULO' },
                { id: 50201, name: 'KYABASIITA' },
                { id: 50202, name: 'KYEMPISI' },
                { id: 50203, name: 'NKIRO' },
              ],
            },
            {
              id: 8089,
              name: 'KATALE WARD',
              villages: [
                { id: 50207, name: 'KABAZUNGU-NABIGOYE' },
                { id: 50208, name: 'KAJOJE' },
                { id: 50209, name: 'KASANA-NABIGOYE' },
                { id: 50210, name: 'KATALE-NABIGOYE' },
                { id: 50211, name: 'NABIGOYE-RWENSABISABI' },
              ],
            },
          ],
        },
        {
          id: 1697,
          name: 'KASAGAMA',
          parishes: [
            {
              id: 8064,
              name: 'BUYANJA',
              villages: [
                { id: 50047, name: 'BUYANJA' },
                { id: 50050, name: 'BUYANJA II' },
                { id: 50051, name: 'KAGAAGA' },
                { id: 50048, name: 'KIHUMURO' },
                { id: 50049, name: 'MUZAIRE A' },
                { id: 50052, name: 'MUZAIRE B' },
              ],
            },
            {
              id: 8068,
              name: 'KAGARA',
              villages: [
                { id: 50063, name: 'KAGAARA' },
                { id: 50066, name: 'KANYANYA' },
                { id: 50064, name: 'KAYEERA' },
                { id: 50065, name: 'MITYEKULA' },
              ],
            },
            {
              id: 8065,
              name: 'KATEBE',
              villages: [
                { id: 50053, name: 'KABUTETERA' },
                { id: 50056, name: 'KALAGALA' },
                { id: 50054, name: 'KATAMACHUBA' },
                { id: 50055, name: 'KATEBE' },
              ],
            },
            {
              id: 8066,
              name: 'KISALUWOKO',
              villages: [
                { id: 50057, name: 'KASAGAMA T/C' },
                { id: 50058, name: 'KIRINDIMURA' },
                { id: 50059, name: 'KISALUWOKO' },
              ],
            },
            {
              id: 8067,
              name: 'NAMUTAMBA',
              villages: [
                { id: 50060, name: 'KASAMBYA' },
                { id: 50062, name: 'KIBEIJA' },
                { id: 50061, name: 'NAMUTAMBA' },
              ],
            },
          ],
        },
        {
          id: 1698,
          name: 'KINUUKA',
          parishes: [
            {
              id: 8069,
              name: 'BWAMULAMIRA',
              villages: [
                { id: 50067, name: 'BWAMULAMIRA' },
                { id: 50068, name: 'KAMUSENENE' },
                { id: 50069, name: 'KAYUNGA' },
                { id: 50070, name: 'KYEMPIRI' },
                { id: 50071, name: 'KYENSHAMA' },
                { id: 50072, name: 'RWERA' },
                { id: 50073, name: 'SEETA' },
              ],
            },
            {
              id: 8070,
              name: 'NAKASOZI',
              villages: [
                { id: 50074, name: 'GAYAZA' },
                { id: 50075, name: 'KINUUKA' },
                { id: 50076, name: 'MAKONDO' },
                { id: 50077, name: 'NAKASOZI' },
                { id: 50078, name: 'RWEMIKOMA' },
              ],
            },
            {
              id: 8071,
              name: 'WABUSANA',
              villages: [
                { id: 50079, name: 'BINIKIRA' },
                { id: 50080, name: 'KANYOGOGA' },
                { id: 50081, name: 'KAWUNGU' },
                { id: 50082, name: 'LUGAAGA' },
                { id: 50083, name: 'LUGALAMA' },
                { id: 50084, name: 'LWETTAMU' },
                { id: 50085, name: 'NAKATO' },
                { id: 50086, name: 'NKOTE A' },
                { id: 50087, name: 'NKOTE B' },
              ],
            },
          ],
        },
        {
          id: 1702,
          name: 'LYAKAJURA',
          parishes: [
            {
              id: 8085,
              name: 'KICWAMBA',
              villages: [
                { id: 50189, name: 'BWIHAGAJU' },
                { id: 50192, name: 'ELISA ZONE' },
                { id: 50190, name: 'KICWAMBA' },
                { id: 50193, name: 'KICWAMBA T.C' },
                { id: 50191, name: 'KINONI' },
              ],
            },
            {
              id: 8084,
              name: 'KYEMAMBA',
              villages: [
                { id: 50185, name: 'KAISHANGO' },
                { id: 50186, name: 'KANSHAMA' },
                { id: 50187, name: 'KYEMAMBA' },
                { id: 50188, name: 'RWOMA' },
              ],
            },
            {
              id: 8083,
              name: 'LYAKAJURA',
              villages: [
                { id: 50180, name: 'KABUNDABUNDA' },
                { id: 50181, name: 'KIKUTO' },
                { id: 50182, name: 'LYAKAJURA' },
                { id: 50183, name: 'NAMIWUNDA A' },
                { id: 50184, name: 'NAMIWUNDA B' },
              ],
            },
            {
              id: 8086,
              name: 'RWEERA',
              villages: [
                { id: 50194, name: 'KABALE' },
                { id: 50195, name: 'KAKOMA' },
                { id: 50196, name: 'RWERA' },
              ],
            },
          ],
        },
        {
          id: 1699,
          name: 'LYANTONDE',
          parishes: [
            {
              id: 8072,
              name: 'BIWOLOBO',
              villages: [
                { id: 50088, name: 'BIWOLOBO' },
                { id: 50089, name: 'BUYANJA' },
                { id: 50090, name: 'GAYAZA' },
                { id: 50091, name: 'KABASENGWA' },
                { id: 50092, name: 'KABETEMERE' },
                { id: 50093, name: 'KAGOGO' },
                { id: 50094, name: 'KAKIBANDI' },
                { id: 50098, name: 'KATOGO' },
                { id: 50099, name: 'KITINDO' },
                { id: 50095, name: 'KYAKABARU' },
                { id: 50096, name: 'LYABUGUMA' },
                { id: 50097, name: 'NAKINOMBE' },
              ],
            },
            {
              id: 8073,
              name: 'KALAGALA',
              villages: [
                { id: 50100, name: 'KABALONGO' },
                { id: 50101, name: 'KABULA' },
                { id: 50102, name: 'KALAGALA' },
                { id: 50110, name: 'KALAGALA II' },
                { id: 50103, name: 'KAWULE/NSEESE' },
                { id: 50104, name: 'KINVUNIKIDDE' },
                { id: 50105, name: 'KIRANGAZI' },
                { id: 50106, name: 'KITABO' },
                { id: 50111, name: 'KYEIBUMBA' },
                { id: 50107, name: 'KYETUME' },
                { id: 50108, name: 'LWAMAYONGO' },
                { id: 50109, name: 'MWEYOGEREZE' },
              ],
            },
            {
              id: 8074,
              name: 'KATOVU',
              villages: [
                { id: 50112, name: 'KATOVU' },
                { id: 50113, name: 'KITAZIGOLOKWA' },
                { id: 50117, name: 'KITAZIGOLOKWA CENTRAL' },
                { id: 50114, name: 'KYAKAKALA' },
                { id: 50115, name: 'LUSANA' },
                { id: 50116, name: 'LUWAAMA A' },
                { id: 50118, name: 'LUWAAMA B' },
                { id: 50119, name: 'LYAKASOLOLA' },
              ],
            },
            {
              id: 8075,
              name: 'KIROWOOZA',
              villages: [
                { id: 50120, name: 'KABAALE' },
                { id: 50121, name: 'KASAMBYA' },
                { id: 50122, name: 'KYABAZAALA' },
                { id: 50123, name: 'MUKOKOMA' },
              ],
            },
            {
              id: 8076,
              name: 'KYEWANULA',
              villages: [
                { id: 50124, name: 'BUYANJA' },
                { id: 50125, name: 'KABAYANDA' },
                { id: 50126, name: 'KAMENGO' },
                { id: 50134, name: 'KAMPEGA' },
                { id: 50127, name: 'KAMUTOGOLO' },
                { id: 50128, name: 'KANYOGOGA' },
                { id: 50129, name: 'KASESE' },
                { id: 50130, name: 'KIBISI' },
                { id: 50135, name: 'KYANZALA' },
                { id: 50131, name: 'KYEWANULA' },
                { id: 50132, name: 'LWAMAWUNGU' },
                { id: 50133, name: 'LWENSINGA' },
                { id: 50136, name: 'MPUMUDE' },
              ],
            },
          ],
        },
        {
          id: 1700,
          name: 'LYANTONDE TOWN COUNCIL',
          parishes: [
            {
              id: 8078,
              name: 'KALIIRO WARD',
              villages: [
                { id: 50140, name: 'CELL 1A' },
                { id: 50141, name: 'CELL 2B' },
              ],
            },
            {
              id: 8077,
              name: 'KOOKI WARD',
              villages: [
                { id: 50137, name: 'CELL 3C' },
                { id: 50138, name: 'CELL 4D' },
                { id: 50139, name: 'KIJJUKIZO' },
              ],
            },
          ],
        },
        {
          id: 1701,
          name: 'MPUMUDDE',
          parishes: [
            {
              id: 8079,
              name: 'BUYAGA',
              villages: [
                { id: 50142, name: 'BUYAGA' },
                { id: 50143, name: 'BWIHA' },
                { id: 50144, name: 'KASANA' },
                { id: 50145, name: 'KEMBOGO' },
                { id: 50146, name: 'MPUMUDDE A' },
                { id: 50147, name: 'MPUMUDDE B' },
                { id: 50148, name: 'RWENSHAMA' },
                { id: 50149, name: 'RWENTANGA A' },
                { id: 50150, name: 'RWENTANGA B' },
              ],
            },
            {
              id: 8080,
              name: 'MPUMUDDE',
              villages: [
                { id: 50151, name: 'BIKOKORA A' },
                { id: 50152, name: 'BIKOKORA B' },
                { id: 50153, name: 'BIKOKORA C' },
                { id: 50154, name: 'BIKOKORA D' },
                { id: 50155, name: 'KALYAMENVU A' },
                { id: 50156, name: 'KALYAMENVU B' },
                { id: 50161, name: 'KALYAMENVU T/C' },
                { id: 50157, name: 'KANAALA A' },
                { id: 50158, name: 'KANAALA B' },
                { id: 50159, name: 'KANYEGANYEGYE A' },
                { id: 50162, name: 'KANYEGANYEGYE B' },
                { id: 50163, name: 'MPUMUDDE T.C' },
                { id: 50160, name: 'NYAKAYAGA' },
              ],
            },
            {
              id: 8081,
              name: 'NSIIKA',
              villages: [
                { id: 50164, name: 'BURUNGA A' },
                { id: 50165, name: 'BURUNGA B' },
                { id: 50166, name: 'KEMUNYU' },
                { id: 50167, name: 'KIREBE A' },
                { id: 50168, name: 'KIREBE B' },
                { id: 50169, name: 'KYEIRUMBA A' },
                { id: 50170, name: 'KYEIRUMBA B' },
                { id: 50173, name: 'KYEIRUMBA C' },
                { id: 50171, name: 'NSIIKA' },
                { id: 50172, name: 'RWENZAZA' },
              ],
            },
            {
              id: 8082,
              name: 'RWAMABARA',
              villages: [
                { id: 50174, name: 'KITEREDDE A' },
                { id: 50179, name: 'KITEREDDE B' },
                { id: 50175, name: 'RWAMABARA A' },
                { id: 50176, name: 'RWAMABARA B' },
                { id: 50177, name: 'RWAMABARA C' },
                { id: 50178, name: 'RWAMABARA D' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
