import { District } from '../index';

export default {
  id: 134,
  name: 'MADI-OKOLLO',
  counties: [
    {
      id: 309,
      name: 'LOWER MADI COUNTY',
      sub_counties: [
        {
          id: 1985,
          name: 'EWANGA',
          parishes: [
            {
              id: 9455,
              name: 'DUMUNGA',
              villages: [
                { id: 61305, name: 'FOLIGO' },
                { id: 61617, name: 'IMVI' },
                { id: 64282, name: 'KONGOLONGA' },
                { id: 68520, name: 'ODULU' },
                { id: 68535, name: 'OFUNGA' },
              ],
            },
            {
              id: 9472,
              name: 'EWANGURU',
              villages: [
                { id: 57994, name: 'ALIGATI' },
                { id: 61039, name: 'CINYAGO' },
                { id: 61299, name: 'EYU-KINGA' },
                { id: 66464, name: 'MUBARI' },
                { id: 70318, name: 'SHAMBIA' },
              ],
            },
            {
              id: 9731,
              name: 'KIRANGA',
              villages: [
                { id: 58752, name: 'AWII' },
                { id: 58758, name: 'AWILOKANGO' },
                { id: 58777, name: 'AWOGA' },
                { id: 66622, name: 'MUNDUREMO' },
                { id: 66642, name: 'MUREDELI' },
                { id: 66666, name: 'MURUNGU' },
              ],
            },
            {
              id: 10259,
              name: 'ROGA',
              villages: [
                { id: 57492, name: 'ADURUSO' },
                { id: 57678, name: 'AJUMANI' },
                { id: 58016, name: 'ALINGA' },
                { id: 65724, name: 'LUYI' },
              ],
            },
            {
              id: 10334,
              name: 'WAKA-DINYA',
              villages: [
                { id: 61383, name: 'GITORA' },
                { id: 62096, name: 'KAGOMA' },
                { id: 65394, name: 'LOKPE' },
                { id: 69531, name: 'PALIRI' },
              ],
            },
          ],
        },
        {
          id: 2094,
          name: 'OGOKO',
          parishes: [
            {
              id: 9241,
              name: 'AYAVU',
              villages: [
                { id: 58000, name: 'ALIJODA' },
                { id: 58807, name: 'AYAVU GAZI' },
                { id: 68630, name: 'OJIBA' },
              ],
            },
            {
              id: 9466,
              name: 'ENYIO',
              villages: [
                { id: 65000, name: 'LALI' },
                { id: 68594, name: 'OGURUKU' },
                { id: 68936, name: 'OMBOKORO' },
                { id: 69519, name: 'PALANDRA' },
              ],
            },
            {
              id: 10174,
              name: 'OLALI',
              villages: [
                { id: 61098, name: 'DEGIYA' },
                { id: 61205, name: 'EAST JAWURA' },
                { id: 68768, name: 'OLALI' },
                { id: 69651, name: 'PAYAWE' },
                { id: 71107, name: 'WEST JAWURA' },
              ],
            },
            {
              id: 10239,
              name: 'PAMVARA',
              villages: [
                { id: 57468, name: 'ADOVU' },
                { id: 58028, name: 'ALIVU' },
                { id: 58501, name: 'ARIKEYI' },
                { id: 69039, name: 'ONAVA' },
                { id: 69582, name: 'PAMVARA' },
              ],
            },
            {
              id: 10351,
              name: 'YACHI',
              villages: [
                { id: 57327, name: 'ACHA' },
                { id: 57472, name: 'ADROYI' },
                { id: 59046, name: 'BIACHICHI' },
                { id: 61336, name: 'GARIA' },
                { id: 65207, name: 'LIRIA' },
              ],
            },
          ],
        },
        {
          id: 2104,
          name: 'PAWOR',
          parishes: [
            {
              id: 10078,
              name: 'NDAVU',
              villages: [
                { id: 57549, name: 'AGIRA' },
                { id: 67671, name: 'NDAVU' },
                { id: 69653, name: 'PAYILA' },
                { id: 69751, name: 'PULWAL' },
              ],
            },
            {
              id: 10183,
              name: 'OLYEVU',
              villages: [
                { id: 58426, name: 'APORO' },
                { id: 68892, name: 'OLYEVU' },
                { id: 68893, name: 'OLYEVU EAST' },
                { id: 69361, name: 'OWAVU' },
              ],
            },
            {
              id: 10240,
              name: 'PANDUKU',
              villages: [
                { id: 57763, name: 'AKAVU' },
                { id: 58240, name: 'ANDIR' },
                { id: 66463, name: 'MUBANDA' },
                { id: 69040, name: 'ONDEKO' },
                { id: 69477, name: 'PAGWAYA' },
                { id: 69583, name: 'PANDUKU' },
                { id: 69655, name: 'PAYONGA' },
              ],
            },
            {
              id: 10246,
              name: 'PARABOK',
              villages: [
                { id: 58237, name: 'ANDENI' },
                { id: 65548, name: 'LOWER PARABOK' },
                { id: 65549, name: 'LOWER PARABOK EAST' },
                { id: 70597, name: 'TAMWELE' },
                { id: 70937, name: 'UPPER PARABOK' },
              ],
            },
          ],
        },
        {
          id: 2108,
          name: 'RHINO CAMP',
          parishes: [
            {
              id: 9207,
              name: 'ANIPI',
              villages: [
                { id: 57357, name: 'ACIDRAKU' },
                { id: 58500, name: 'ARIKAYI' },
                { id: 61257, name: 'ENIOBE' },
                { id: 61349, name: 'GBEIYIA' },
                { id: 66052, name: 'MARIZE' },
                { id: 69420, name: 'OYUU' },
                { id: 69423, name: 'OZURUA' },
                { id: 69687, name: 'PILLIA' },
              ],
            },
            {
              id: 9239,
              name: 'AWUVU',
              villages: [
                { id: 57138, name: 'ABARIO' },
                { id: 63012, name: 'KASUMENGE' },
                { id: 63298, name: 'KENYA' },
                { id: 67668, name: 'NDARA' },
                { id: 68841, name: 'OLODIOVA' },
                { id: 68931, name: 'OMBENIVA' },
                { id: 69631, name: 'PASUMU' },
                { id: 69819, name: 'RHINO CAMP SS' },
                { id: 70604, name: 'TANZANIA  A' },
                { id: 70605, name: 'TANZANIA  B' },
                { id: 71023, name: 'WANDI' },
              ],
            },
            {
              id: 9251,
              name: 'BANDILI',
              villages: [
                { id: 57328, name: 'ACHAA' },
                { id: 58483, name: 'ARIA-JOBI' },
                { id: 58900, name: 'BANDILI' },
                { id: 61352, name: 'GBORO/ESEA' },
                { id: 68853, name: 'OLOMAKU' },
                { id: 69343, name: 'OVUOCAKU' },
                { id: 69607, name: 'PARAA' },
                { id: 70785, name: 'TOLIOVA' },
              ],
            },
            {
              id: 9467,
              name: 'ERAMVA',
              villages: [
                { id: 57345, name: 'ACHOLI QUARTER' },
                { id: 57943, name: 'ALEIVA' },
                { id: 61748, name: 'JANDUA' },
                { id: 63040, name: 'KATANGA' },
                { id: 65155, name: 'LEDRIVA' },
                { id: 65639, name: 'LUKUDU' },
                { id: 66028, name: 'MANGOSABA' },
                { id: 67682, name: 'NDIOVA' },
                { id: 69209, name: 'ORODRIVA' },
              ],
            },
            {
              id: 9478,
              name: 'GBULUKUATUNI',
              villages: [
                { id: 57477, name: 'ADUAFE  B' },
                { id: 57478, name: 'ADUAFE A' },
                { id: 58575, name: 'ASAROA' },
                { id: 61295, name: 'EWANANI' },
                { id: 68654, name: 'OKAA' },
                { id: 69098, name: 'ONZI' },
                { id: 69160, name: 'ORAA' },
                { id: 69412, name: 'OYOA' },
                { id: 70823, name: 'TRANGALA' },
              ],
            },
            {
              id: 9960,
              name: 'MANAGO',
              villages: [
                { id: 57474, name: 'ADUA' },
                { id: 57631, name: 'AJAGORO' },
                { id: 61069, name: 'CULUA' },
                { id: 65285, name: 'LODORO' },
                { id: 66014, name: 'MANAGO' },
              ],
            },
          ],
        },
        {
          id: 2109,
          name: 'RIGBO',
          parishes: [
            {
              id: 9180,
              name: 'ALIBA',
              villages: [
                { id: 57358, name: 'ACIDRAKU' },
                { id: 61245, name: 'ELUKWESINYONGO' },
                { id: 61271, name: 'ERADRIRU' },
                { id: 61308, name: 'FORIA' },
                { id: 61316, name: 'FUNDO' },
                { id: 65139, name: 'LAWARA' },
                { id: 68344, name: 'OBIBIFE' },
                { id: 69222, name: 'ORUKU' },
                { id: 69253, name: 'OSA  B' },
                { id: 71075, name: 'WARANGA' },
                { id: 71207, name: 'YANGA' },
              ],
            },
            {
              id: 9807,
              name: 'KWILI',
              villages: [
                { id: 57172, name: 'ABIRI' },
                { id: 58059, name: 'ALUKPERENGA' },
                { id: 59625, name: 'BUKUNGA' },
                { id: 60210, name: 'BURA' },
                { id: 61251, name: 'EMVENGA' },
                { id: 68509, name: 'ODRUAKU' },
                { id: 68515, name: 'ODUJO' },
                { id: 68706, name: 'OKPOTANI' },
                { id: 68833, name: 'OLIONGA' },
              ],
            },
            {
              id: 9924,
              name: 'LUBA',
              villages: [
                { id: 57489, name: 'ADUPI' },
                { id: 58031, name: 'ALLI' },
                { id: 61272, name: 'ERAGO' },
                { id: 61448, name: 'GULUBU' },
                { id: 64231, name: 'KOLOLO' },
                { id: 64453, name: 'KWILI' },
                { id: 66224, name: 'MERE-ANDREKUA' },
                { id: 66955, name: 'NAGBULU' },
                { id: 68838, name: 'OLIVU' },
                { id: 69273, name: 'OSULU' },
                { id: 70998, name: 'WALOPE' },
              ],
            },
            {
              id: 10142,
              name: 'OCEA',
              villages: [
                { id: 57176, name: 'ABIRICENDUKU' },
                { id: 58017, name: 'ALINYIRI' },
                { id: 61215, name: 'EDEN' },
                { id: 61293, name: 'EWADROMATI' },
                { id: 68406, name: 'OCEA' },
                { id: 70868, name: 'TUNDURU' },
                { id: 71235, name: 'YORO' },
              ],
            },
            {
              id: 10150,
              name: 'ODOI',
              villages: [
                { id: 57261, name: 'ABUNIA' },
                { id: 61040, name: 'CINYAGO' },
                { id: 62324, name: 'KALIGO' },
                { id: 65201, name: 'LIONGA' },
                { id: 68427, name: 'OCOMBENGA' },
                { id: 69254, name: 'OSA A' },
                { id: 71065, name: 'WANYANGE B' },
                { id: 71213, name: 'YELEGO' },
              ],
            },
            {
              id: 10152,
              name: 'ODUBU',
              villages: [
                { id: 58101, name: 'AMANGUNGA' },
                { id: 61344, name: 'GBALALA' },
                { id: 68506, name: 'ODROO' },
                { id: 70750, name: 'TIKA' },
                { id: 71064, name: 'WANYANGE  A' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 311,
      name: 'UPPER MADI COUNTY',
      sub_counties: [
        {
          id: 1947,
          name: 'ANYIRIBU',
          parishes: [
            {
              id: 9245,
              name: 'AYUU',
              villages: [
                { id: 57470, name: 'ADRIBU' },
                { id: 58305, name: 'ANIBU' },
                { id: 69339, name: 'OVIBU' },
                { id: 69496, name: 'PAJURU - AYUU' },
                { id: 69497, name: 'PAJURU/OLINI' },
              ],
            },
            {
              id: 9271,
              name: 'BONDO',
              villages: [
                { id: 57989, name: 'ALIBORO' },
                { id: 61219, name: 'EGIRO-AYINI' },
                { id: 61775, name: 'JOROBU' },
                { id: 65195, name: 'LILII' },
                { id: 66750, name: 'MUZEETU' },
                { id: 69019, name: 'OMURIBA' },
              ],
            },
            {
              id: 10186,
              name: 'OMII',
              villages: [
                { id: 57939, name: 'ALEE' },
                { id: 61661, name: 'IRIRI' },
                { id: 62528, name: 'KANGO' },
                { id: 68710, name: 'OKUBU' },
                { id: 68810, name: 'OLIDO' },
                { id: 69397, name: 'OYEKU' },
                { id: 69662, name: 'PEEPIA' },
                { id: 69663, name: 'PEERA' },
              ],
            },
            {
              id: 10357,
              name: 'YILLI',
              villages: [
                { id: 58468, name: 'ARASI' },
                { id: 68859, name: 'OLOYI' },
                { id: 69493, name: 'PAJOBI' },
                { id: 69602, name: 'PANYUA' },
                { id: 71188, name: 'WUA' },
              ],
            },
          ],
        },
        {
          id: 2093,
          name: 'OFFAKA',
          parishes: [
            {
              id: 9149,
              name: 'ADRAA',
              villages: [
                { id: 57439, name: 'ADIBU DRAJIBU/OCONYARA' },
                { id: 57469, name: 'ADRAA' },
                { id: 58272, name: 'ANGESI' },
                { id: 58816, name: 'AYIBU/OSABU' },
                { id: 58828, name: 'AYIO/ADOGWE' },
                { id: 58831, name: 'AYIRA' },
                { id: 58849, name: 'AYUU' },
                { id: 69544, name: 'PAMACHI' },
              ],
            },
            {
              id: 9464,
              name: 'ELIBU',
              villages: [
                { id: 57992, name: 'ALIBU/DIMU T.C' },
                { id: 57993, name: 'ALIBU/NYANYABU' },
                { id: 58273, name: 'ANGESI/ABAALI' },
                { id: 68807, name: 'OLIBA/MUNI-OJIBA' },
                { id: 69187, name: 'ORIBU/ALEJU' },
                { id: 69491, name: 'PAJIA/PACENI' },
                { id: 69827, name: 'RIKI' },
                { id: 71189, name: 'WUA/IBII/NDRIBA' },
              ],
            },
            {
              id: 10143,
              name: 'OCEBU',
              villages: [
                { id: 57581, name: 'AGURU' },
                { id: 58451, name: 'ARAARA  A/B' },
                { id: 67664, name: 'NDABU' },
                { id: 67686, name: 'NDRIIBA - ADABU' },
                { id: 67687, name: 'NDRIIBA ALIBU/OCEBU-ALIBU' },
                { id: 68499, name: 'ODRABU' },
                { id: 68918, name: 'OMBABU/IGA' },
                { id: 68920, name: 'OMBACHI' },
              ],
            },
            {
              id: 10205,
              name: 'ORIBU',
              villages: [
                { id: 57371, name: 'ACUBU' },
                { id: 57990, name: 'ALIBU' },
                { id: 67689, name: 'NDU' },
                { id: 68233, name: 'NYANYABU' },
                { id: 68407, name: 'OCEBU IRIRI' },
                { id: 68711, name: 'OKUBU' },
                { id: 68767, name: 'OLALI' },
                { id: 68808, name: 'OLIBU' },
                { id: 69025, name: 'OMVULOO' },
                { id: 69255, name: 'OSABU' },
                { id: 69492, name: 'PAJO' },
                { id: 69580, name: 'PAMURA' },
                { id: 69640, name: 'PATRU' },
              ],
            },
          ],
        },
        {
          id: 2097,
          name: 'OKOLLO',
          parishes: [
            {
              id: 9162,
              name: 'AJIBU',
              villages: [
                { id: 57991, name: 'ALIBU' },
                { id: 58111, name: 'AMBALA' },
                { id: 58827, name: 'AYIO' },
                { id: 61038, name: 'CINYAA-RANCH' },
                { id: 68510, name: 'ODRUBU' },
                { id: 68811, name: 'OLII' },
                { id: 68921, name: 'OMBACI' },
                { id: 69490, name: 'PAJIA/OYIBU' },
                { id: 71243, name: 'ZABU' },
              ],
            },
            {
              id: 9249,
              name: 'BAITO',
              villages: [
                { id: 57471, name: 'ADRIBU' },
                { id: 57651, name: 'AJIBU' },
                { id: 58873, name: 'BAITO' },
                { id: 61252, name: 'ENDEBU' },
                { id: 71089, name: 'WAWA' },
              ],
            },
            {
              id: 10168,
              name: 'OKOLLO',
              villages: [
                { id: 58694, name: 'AWAA' },
                { id: 58818, name: 'AYIJU' },
                { id: 67691, name: 'NDUBU' },
                { id: 68692, name: 'OKOLLO TRADING CENTRE' },
                { id: 69122, name: 'OPIBU' },
                { id: 69414, name: 'OYOBU' },
                { id: 69603, name: 'PANZORO' },
                { id: 69610, name: 'PARABU' },
                { id: 69643, name: 'PAUNI' },
                { id: 70961, name: 'VUU' },
              ],
            },
            {
              id: 10195,
              name: 'ONYOMU',
              villages: [
                { id: 57673, name: 'AJUIMUNI' },
                { id: 58342, name: 'ANYORA/OSABU' },
                { id: 58874, name: 'BAIYA' },
                { id: 58960, name: 'BARIBU/DRAJINI' },
                { id: 60867, name: 'CHANYA' },
                { id: 65857, name: 'MADELI' },
                { id: 69094, name: 'ONYOMU KATI' },
                { id: 69095, name: 'ONYOMU/MULUU' },
                { id: 69581, name: 'PAMVA/OMVEKO' },
              ],
            },
          ],
        },
        {
          id: 2122,
          name: 'ULEPPI',
          parishes: [
            {
              id: 9219,
              name: 'ARARA',
              villages: [
                { id: 57575, name: 'AGULUA' },
                { id: 58496, name: 'ARIBU' },
                { id: 58690, name: 'AVE' },
                { id: 61289, name: 'ETELEVA' },
                { id: 71090, name: 'WAWAFE' },
              ],
            },
            {
              id: 9650,
              name: 'KATIYI',
              villages: [
                { id: 58830, name: 'AYIRA' },
                { id: 61266, name: 'ENYIO' },
                { id: 69043, name: 'ONDUKO' },
                { id: 69495, name: 'PAJULU' },
                { id: 70546, name: 'ST. LUKE MISSION' },
                { id: 70960, name: 'VURRA' },
              ],
            },
            {
              id: 9869,
              name: 'LAWURA',
              villages: [
                { id: 58815, name: 'AYIBU' },
                { id: 65208, name: 'LIRIMVA' },
                { id: 66625, name: 'MUNI' },
                { id: 68498, name: 'ODRABU' },
                { id: 68512, name: 'ODUBU' },
                { id: 68919, name: 'OMBACHI' },
                { id: 69381, name: 'OYABU' },
                { id: 70921, name: 'ULEPPI TRADING CENTRE' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
