import { District } from '../index';

export default {
  id: 53,
  name: 'MASAKA',
  counties: [
    {
      id: 119,
      name: 'BUKOTO COUNTY CENTRAL',
      sub_counties: [
        {
          id: 746,
          name: 'KABONERA',
          parishes: [
            {
              id: 3480,
              name: 'BISANJE',
              villages: [
                { id: 21993, name: 'BISANJE EAST' },
                { id: 21994, name: 'BISANJE WEST' },
                { id: 21995, name: 'BUTAAYA' },
                { id: 21996, name: 'KAGGANDA' },
                { id: 21997, name: 'KANABUKULIRO' },
                { id: 21998, name: 'KASAALI' },
                { id: 21999, name: 'NABINENE' },
              ],
            },
            {
              id: 3486,
              name: 'BUTALE',
              villages: [
                { id: 22035, name: 'BUTALE  A' },
                { id: 22036, name: 'BUTALE  B' },
                { id: 22037, name: 'KAYUNGA' },
                { id: 22038, name: 'KIKUNGWE  A' },
                { id: 22039, name: 'KIKUNGWE  B' },
                { id: 22040, name: 'NABULAGO' },
                { id: 22041, name: 'TAKAJJUNGE' },
              ],
            },
            {
              id: 3482,
              name: 'KAKUNYU',
              villages: [
                { id: 22008, name: 'BUKOTO' },
                { id: 22009, name: 'KAKUNYU' },
                { id: 22010, name: 'KASANGO' },
                { id: 22011, name: 'KISENYI  A' },
                { id: 22012, name: 'KISENYI  B' },
                { id: 22013, name: 'KYANAKASE' },
              ],
            },
            {
              id: 3484,
              name: 'KIRIMYA',
              villages: [
                { id: 22023, name: 'GAYAZA  FUWE' },
                { id: 22024, name: 'GAYAZA  NABBOWA' },
                { id: 22025, name: 'KIRIMYA  A' },
                { id: 22026, name: 'KIRIMYA  B' },
                { id: 22027, name: 'KIRIMYA  VILLAGE' },
              ],
            },
            {
              id: 3483,
              name: 'KITANGA',
              villages: [
                { id: 22014, name: 'DDEGEYA' },
                { id: 22015, name: 'KANSAMBYA' },
                { id: 22016, name: 'KASEETA' },
                { id: 22017, name: 'KAWULE' },
                { id: 22018, name: 'KAYIRIRA' },
                { id: 22019, name: 'KITANGA' },
                { id: 22020, name: 'KYAJUBIRA' },
                { id: 22021, name: 'KYALULIRA' },
                { id: 22022, name: 'MBIRIZI' },
              ],
            },
            {
              id: 3481,
              name: 'KIZIBA',
              villages: [
                { id: 22000, name: 'BUKOONA' },
                { id: 22001, name: 'BUSAGALA' },
                { id: 22002, name: 'KABONERA  A' },
                { id: 22003, name: 'KABONERA  B' },
                { id: 22004, name: 'KASANJE' },
                { id: 22005, name: 'KITO' },
                { id: 22006, name: 'KIZIBA' },
                { id: 22007, name: 'LUFUMBA' },
              ],
            },
            {
              id: 3485,
              name: 'KYAMUYIMBWA',
              villages: [
                { id: 22028, name: 'BUSENSE' },
                { id: 22029, name: 'KABAGABO' },
                { id: 22030, name: 'KAGEZI' },
                { id: 22031, name: 'KIKALAALA' },
                { id: 22032, name: 'KYAMUYIMBWA' },
                { id: 22033, name: 'KYANJALE' },
                { id: 22034, name: 'LWANSUSU' },
              ],
            },
          ],
        },
        {
          id: 747,
          name: 'KYANAMUKAKA',
          parishes: [
            {
              id: 3487,
              name: 'BUYAGA',
              villages: [
                { id: 22042, name: 'BBAALE' },
                { id: 22043, name: 'BIBAALE' },
                { id: 22044, name: 'KANYAGA' },
                { id: 22045, name: 'KIWUMPA' },
                { id: 22046, name: 'LUWEREKERA' },
                { id: 22047, name: 'MIJUNJU' },
                { id: 22048, name: 'MPALA' },
                { id: 22049, name: 'NAMIREMBE' },
                { id: 22050, name: 'NKOMA' },
                { id: 22051, name: 'NKUUNA' },
                { id: 22052, name: 'SSERINYA' },
              ],
            },
            {
              id: 3488,
              name: 'BUYINJA',
              villages: [
                { id: 22053, name: 'BUYINJA' },
                { id: 22054, name: 'KYENGERERE' },
                { id: 22055, name: 'LUKODDE' },
                { id: 22056, name: 'LUZINGA' },
                { id: 22057, name: 'MIKOMAGO' },
                { id: 22058, name: 'MIRUNDU' },
                { id: 22059, name: 'SSEMUTO' },
              ],
            },
            {
              id: 3489,
              name: 'KAMUZINDA',
              villages: [
                { id: 22060, name: 'BIYA' },
                { id: 22061, name: 'BUKUNDA' },
                { id: 22062, name: 'BULEGEYA' },
                { id: 22063, name: 'KALUUMA' },
                { id: 22064, name: 'KAMUZINDA' },
                { id: 22065, name: 'KANONI' },
                { id: 22066, name: 'KIKUUMA - DDUNGU' },
                { id: 22067, name: 'KYAMULA' },
                { id: 22068, name: 'LUBUMBA - BULEMBE' },
                { id: 22069, name: 'MANZI' },
                { id: 22070, name: 'TTALA' },
              ],
            },
            {
              id: 3490,
              name: 'KYANTALE',
              villages: [
                { id: 22071, name: 'BUWUNDE' },
                { id: 22072, name: 'KAGOLOGOLO' },
                { id: 22073, name: 'KAMUNGU' },
                { id: 22074, name: 'KANAMUSALABA' },
                { id: 22075, name: 'KASOLO' },
                { id: 22076, name: 'KATIITI' },
                { id: 22077, name: 'KIZIGO' },
                { id: 22078, name: 'KKINDU' },
                { id: 22079, name: 'KYAJJUNGU' },
                { id: 22080, name: 'KYAMBAZI' },
                { id: 22081, name: 'KYANAMUKAKA' },
                { id: 22082, name: 'KYANANJULA' },
                { id: 22084, name: 'LUVUNJA' },
                { id: 22085, name: 'MANYWA' },
                { id: 22083, name: 'NFUULA' },
                { id: 22086, name: 'SSERINYA - BBAALA' },
              ],
            },
            {
              id: 3491,
              name: 'ZZIMWE',
              villages: [
                { id: 22087, name: 'BUKYALA' },
                { id: 22088, name: 'BUTANU' },
                { id: 22089, name: 'KALAMBI' },
                { id: 22090, name: 'KATINYONDO' },
                { id: 22091, name: 'KYASA' },
                { id: 22092, name: 'LUBUMBA' },
                { id: 22093, name: 'LUKINDU (A)' },
                { id: 22094, name: 'LUKINDU (B)' },
                { id: 22095, name: 'MINYINYA - PROPER' },
                { id: 22096, name: 'MINYINYA GALILAYA' },
                { id: 22097, name: 'MINYINYA KABAALE' },
                { id: 22098, name: 'MINYINYA KYAMUTWE' },
                { id: 22099, name: 'NSANGWA' },
                { id: 22100, name: 'ZZIMWE' },
              ],
            },
          ],
        },
        {
          id: 748,
          name: 'KYESIIGA',
          parishes: [
            {
              id: 3495,
              name: 'BBULIRO',
              villages: [
                { id: 22138, name: 'BBULIRO A' },
                { id: 22139, name: 'BBULIRO B' },
                { id: 22140, name: 'BYAMBAALE' },
                { id: 22141, name: 'DDIMO' },
                { id: 22142, name: 'GAYAZA' },
                { id: 22143, name: 'KATIKAMU' },
                { id: 22144, name: 'KIRAMBULA' },
                { id: 22145, name: 'MUWOLOLO' },
                { id: 22146, name: 'NABITAKA' },
              ],
            },
            {
              id: 3492,
              name: 'BUGERE',
              villages: [
                { id: 22101, name: 'BUGERE A' },
                { id: 22102, name: 'BUGERE B' },
                { id: 22103, name: 'BUTOZI' },
                { id: 22104, name: 'KAJJWA' },
                { id: 22105, name: 'KAMUGENYI' },
                { id: 22106, name: 'KAMULEGU' },
                { id: 22107, name: 'KIBBE' },
                { id: 22108, name: 'LWAGGULWE A' },
                { id: 22109, name: 'LWAGGULWE B' },
                { id: 22110, name: 'LWAGGULWE C' },
                { id: 22111, name: 'MWERUKA A' },
                { id: 22112, name: 'MWERUKA B' },
                { id: 22113, name: 'MWERUKA C' },
              ],
            },
            {
              id: 3493,
              name: 'KITUNGA',
              villages: [
                { id: 22114, name: 'BIGGA' },
                { id: 22115, name: 'KIKONDA' },
                { id: 22116, name: 'KITUNGA A' },
                { id: 22117, name: 'KITUNGA B' },
                { id: 22118, name: 'KYAMUZIMBA' },
                { id: 22119, name: 'LUKONO' },
                { id: 22120, name: 'MALEMBO' },
                { id: 22121, name: 'MUKOBE' },
                { id: 22122, name: 'MUKUNYU' },
              ],
            },
            {
              id: 3494,
              name: 'KYESIIGA',
              villages: [
                { id: 22123, name: 'BAMUNANIKA' },
                { id: 22124, name: 'BIRONGO' },
                { id: 22125, name: 'BUGO - LWEMODDE' },
                { id: 22126, name: 'BUNYUMA' },
                { id: 22127, name: 'KABANDA' },
                { id: 22128, name: 'KALINGOMA' },
                { id: 22129, name: 'KASANJE' },
                { id: 22130, name: 'KATWE' },
                { id: 22131, name: 'KISEREKETE' },
                { id: 22132, name: 'KYATOKOLO' },
                { id: 22133, name: 'LUKOLO' },
                { id: 22134, name: 'MAGEEGE' },
                { id: 22135, name: 'MAGIRI' },
                { id: 22136, name: 'MULEMA' },
                { id: 22137, name: 'NATEETE' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 118,
      name: 'BUKOTO COUNTY EAST',
      sub_counties: [
        {
          id: 743,
          name: 'BUKAKATA',
          parishes: [
            {
              id: 3463,
              name: 'BUKIBONGA',
              villages: [
                { id: 21857, name: 'BISWA' },
                { id: 21847, name: 'BUKAKATA' },
                { id: 21848, name: 'BUKIBONGA' },
                { id: 21849, name: 'BUNADDU' },
                { id: 21850, name: 'KABASESE  A' },
                { id: 21851, name: 'KABASESE  B' },
                { id: 21852, name: 'KACHANGA' },
                { id: 21853, name: 'KASOKERO' },
                { id: 21854, name: 'KAZIRU' },
                { id: 21855, name: 'KIKONOKA' },
                { id: 21858, name: 'KISASA' },
                { id: 21856, name: 'LAMBU A' },
                { id: 21859, name: 'LAMBU B' },
                { id: 21860, name: 'LAMBU C' },
                { id: 21861, name: 'NAKITOKOLO' },
              ],
            },
            {
              id: 3465,
              name: 'MAKONZI',
              villages: [
                { id: 21870, name: 'BUKOKO' },
                { id: 21871, name: 'BUZIRANGO' },
                { id: 21872, name: 'BWAMI' },
                { id: 21873, name: 'KISUKU' },
                { id: 21874, name: 'MITONDO' },
              ],
            },
            {
              id: 3464,
              name: 'SSUNGA',
              villages: [
                { id: 21862, name: 'BBAALE' },
                { id: 21863, name: 'BIRINZI' },
                { id: 21864, name: 'BUKAAYI  A' },
                { id: 21865, name: 'BUKAAYI  B' },
                { id: 21866, name: 'KASANJE-NAKIGGA' },
                { id: 21867, name: 'KIGO' },
                { id: 21868, name: 'KISAAKA  A' },
                { id: 21869, name: 'KISAAKA  B' },
              ],
            },
          ],
        },
        {
          id: 744,
          name: 'BUWUNGA',
          parishes: [
            {
              id: 3473,
              name: 'BULANDO',
              villages: [
                { id: 21934, name: 'BULANDO  A' },
                { id: 21935, name: 'BULANDO  B' },
                { id: 21936, name: 'KABAGABO' },
                { id: 21937, name: 'KAYIJJA' },
                { id: 21938, name: 'KIBINDI' },
                { id: 21939, name: 'SERINYA-BULUNGU' },
              ],
            },
            {
              id: 3472,
              name: 'BUWUNGA',
              villages: [
                { id: 21926, name: 'BUWUNGA-KYABBUMBA' },
                { id: 21927, name: 'BUYANJA' },
                { id: 21928, name: 'KASEETA' },
                { id: 21929, name: 'KITWE A' },
                { id: 21930, name: 'KITWE B' },
                { id: 21931, name: 'KYANTE-KAWULE' },
                { id: 21932, name: 'KYASSUNSU-DOGERO' },
                { id: 21933, name: 'MIKONI-KATTOLO' },
              ],
            },
            {
              id: 3466,
              name: 'GGULUMA',
              villages: [
                { id: 21875, name: 'BUKINDA-KAKINTU' },
                { id: 21876, name: 'BUKINDA-NAKATEETE' },
                { id: 21877, name: 'JANGANO' },
                { id: 21878, name: 'KABUCUNCU-NAKASOJJO' },
                { id: 21879, name: 'KAWERE-KIGANGAZZI' },
              ],
            },
            {
              id: 3467,
              name: 'KAMWOZI',
              villages: [
                { id: 21880, name: 'BUTEBERE' },
                { id: 21888, name: 'BUWANGA - NAROZAALI' },
                { id: 21881, name: 'KALUGONDO' },
                { id: 21882, name: 'KAMWOZI' },
                { id: 21883, name: 'KIJONJO' },
                { id: 21884, name: 'KYANJOVU' },
                { id: 21885, name: 'KYEERA' },
                { id: 21886, name: 'LUGAZI' },
                { id: 21887, name: 'LWANUNDA' },
              ],
            },
            {
              id: 3468,
              name: 'KANYWA',
              villages: [
                { id: 21889, name: 'BUKEERI' },
                { id: 21890, name: 'BULEMBA' },
                { id: 21891, name: 'KABIRA-KANAMUSABALA' },
                { id: 21892, name: 'KANNYWA' },
                { id: 21893, name: 'KASOZI' },
                { id: 21894, name: 'KITOMA' },
                { id: 21895, name: 'MBIRA' },
                { id: 21900, name: 'MUMPU-MUTEMANTE' },
                { id: 21896, name: 'NAKIYAGA' },
                { id: 21897, name: 'NKUKE A' },
                { id: 21898, name: 'NKUKE B' },
                { id: 21899, name: 'TEKERA' },
              ],
            },
            {
              id: 3469,
              name: 'KASAKA',
              villages: [
                { id: 21901, name: 'BIRONGO' },
                { id: 21902, name: 'BULENGE' },
                { id: 21903, name: 'KAJUNA  BENA' },
                { id: 21904, name: 'KAJUNA  CHURCH' },
                { id: 21905, name: 'KALODDO' },
                { id: 21906, name: 'KASAKA - EMIRIRO  A' },
                { id: 21907, name: 'KASAKA - EMIRIRO  B' },
                { id: 21908, name: 'KASAKA - FELESIO' },
                { id: 21909, name: 'NNYONDO' },
              ],
            },
            {
              id: 3470,
              name: 'KITENGEESA',
              villages: [
                { id: 21910, name: 'KIDDA' },
                { id: 21911, name: 'KITENGEESA  B' },
                { id: 21912, name: 'KITENGEESA  T.C.' },
                { id: 21913, name: 'KYANGA - KITEZA' },
                { id: 21914, name: 'KYASSUMA' },
                { id: 21915, name: 'LWANYI' },
                { id: 21916, name: 'MAZINGA  A' },
                { id: 21917, name: 'MAZINGA  B' },
              ],
            },
            {
              id: 3471,
              name: 'MAZINGA',
              villages: [
                { id: 21918, name: 'BUTALE' },
                { id: 21919, name: 'BUTENZI-BUSAALE' },
                { id: 21920, name: 'BUTENZI-KANNYOGOGA' },
                { id: 21921, name: 'KATOOGO' },
                { id: 21922, name: 'MAZINGA' },
                { id: 21923, name: 'MISANSALA' },
                { id: 21924, name: 'MUGUMBA' },
                { id: 21925, name: 'NDOZI' },
              ],
            },
          ],
        },
        {
          id: 745,
          name: 'MUKUNGWE',
          parishes: [
            {
              id: 3474,
              name: 'BUGABIRA',
              villages: [
                { id: 21940, name: 'BUGABIRA' },
                { id: 21941, name: 'KALUNDIRA' },
                { id: 21942, name: 'KISAGAZI/BUTERERE' },
                { id: 21943, name: 'KIYIMBWE' },
                { id: 21944, name: 'KYALI' },
                { id: 21945, name: 'KYALUGO' },
                { id: 21946, name: 'LWABUSISI' },
                { id: 21947, name: 'NDEGEYA' },
              ],
            },
            {
              id: 3475,
              name: 'BULAYI',
              villages: [
                { id: 21948, name: 'BULAYI  LUGUUDO' },
                { id: 21949, name: 'BULAYI  SEETA' },
                { id: 21950, name: 'KIGATTO' },
                { id: 21951, name: 'KIKULULA' },
                { id: 21952, name: 'KIWAALA' },
                { id: 21953, name: 'KIYUMBA' },
                { id: 21954, name: 'MITEMULA' },
              ],
            },
            {
              id: 3476,
              name: 'KALAGALA',
              villages: [
                { id: 21955, name: 'BUGGYA' },
                { id: 21956, name: 'KALAGALA' },
                { id: 21957, name: 'KASAANA' },
                { id: 21958, name: 'KASANA' },
                { id: 21959, name: 'KAYIRIKITI' },
                { id: 21960, name: 'KAYUNGA' },
                { id: 21961, name: 'KINONI' },
                { id: 21962, name: 'KIRINDA' },
                { id: 21963, name: 'KITENGA A' },
                { id: 21964, name: 'KITENGA B' },
                { id: 21965, name: 'LWABIKERE' },
                { id: 21966, name: 'MISAALI' },
                { id: 21967, name: 'MULEMA' },
              ],
            },
            {
              id: 3477,
              name: 'KATWADDE',
              villages: [
                { id: 21968, name: 'KASAALA' },
                { id: 21969, name: 'KASAANA' },
                { id: 21970, name: 'KATWADDE' },
                { id: 21971, name: 'KAYUGI' },
                { id: 21972, name: 'LUVULE' },
                { id: 21973, name: 'MANYWA-KAZIRA' },
                { id: 21974, name: 'NJUMAGA' },
              ],
            },
            {
              id: 3478,
              name: 'MATANGA',
              villages: [
                { id: 21975, name: 'BUTALE' },
                { id: 21976, name: 'BUTENDE' },
                { id: 21977, name: 'KINYERERE' },
                { id: 21978, name: 'KIWANYIZI' },
                { id: 21979, name: 'LWANDA' },
                { id: 21980, name: 'MATANGA' },
                { id: 21981, name: 'NAKATOOKE' },
                { id: 21982, name: 'NSANGAMO' },
              ],
            },
            {
              id: 3479,
              name: 'SAMALIYA',
              villages: [
                { id: 21983, name: 'KAKO HILL' },
                { id: 21984, name: 'KAKO VILLAGE' },
                { id: 21985, name: 'KYALUSOWE  A' },
                { id: 21986, name: 'KYALUSOWE  B' },
                { id: 21987, name: 'LUZINGA' },
                { id: 21988, name: 'MPUGWE T.C' },
                { id: 21989, name: 'MPUGWE VILLAGE' },
                { id: 21990, name: 'MUKUNGWE/KIYANJA' },
                { id: 21991, name: 'NAMAKINDU' },
                { id: 21992, name: 'SAMALIYA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 120,
      name: 'MASAKA MUNICIPALITY',
      sub_counties: [
        {
          id: 749,
          name: 'KATWE/BUTEGO',
          parishes: [
            {
              id: 3496,
              name: 'BUTEGO',
              villages: [
                { id: 22147, name: 'BUTEGO' },
                { id: 22148, name: 'KALAGALA' },
                { id: 22149, name: 'KAMUGOMBWA' },
                { id: 22150, name: 'KIRUMBA  A' },
                { id: 22151, name: 'KIRUMBA  B' },
                { id: 22152, name: 'KIYIMBWE' },
                { id: 22153, name: 'SSAZA' },
                { id: 22154, name: 'U.T.C MASAKA' },
              ],
            },
            {
              id: 3497,
              name: 'KATWE',
              villages: [
                { id: 22155, name: 'BATA CELL' },
                { id: 22156, name: 'BWALA' },
                { id: 22157, name: 'CINEMA CELL' },
                { id: 22158, name: 'FOLK LAND CELL' },
                { id: 22159, name: 'KANONI' },
                { id: 22160, name: 'KIRUMBA -KATWE' },
                { id: 22161, name: 'KISUUNA' },
                { id: 22162, name: 'KITABAZI' },
                { id: 22163, name: 'MARKET CELL' },
                { id: 22164, name: 'MUTUBA-MUSISI GARDENS' },
                { id: 22165, name: 'TOWN YARD' },
              ],
            },
          ],
        },
        {
          id: 750,
          name: 'KIMAANYA/KYABAKUZA',
          parishes: [
            {
              id: 3498,
              name: 'KIMAANYA',
              villages: [
                { id: 22166, name: 'KASSIJAGIRWA  VILLAGE' },
                { id: 22167, name: 'KIJJABWEMI A' },
                { id: 22175, name: 'KIJJABWEMI B' },
                { id: 22168, name: 'KIMAANYA A' },
                { id: 22169, name: 'KIMAANYA B' },
                { id: 22170, name: 'KIZUNGU' },
                { id: 22171, name: 'KUMBU  H.E' },
                { id: 22172, name: 'MASAKA  HOSPITAL' },
                { id: 22173, name: 'MASAKA  S.S.S' },
                { id: 22176, name: 'NEW KKUMBU' },
                { id: 22174, name: 'POLICE/PRISON BARRACKS' },
              ],
            },
            {
              id: 3499,
              name: 'KYABAKUZA',
              villages: [
                { id: 22177, name: 'GAYAAZA' },
                { id: 22178, name: 'KYABAKUZA  A' },
                { id: 22179, name: 'KYABAKUZA  B' },
                { id: 22180, name: 'KYABAKUZA  T.C' },
                { id: 22181, name: 'MWALO' },
              ],
            },
          ],
        },
        {
          id: 751,
          name: 'NYENDO/SENYANGE',
          parishes: [
            {
              id: 3500,
              name: 'NYENDO',
              villages: [
                { id: 22182, name: 'BINYONYI  A' },
                { id: 22183, name: 'BINYONYI  B' },
                { id: 22184, name: 'BLOCK A' },
                { id: 22185, name: 'BUJJA-NJERU' },
                { id: 22186, name: 'KASANA' },
                { id: 22187, name: 'KAYIRIKITI' },
                { id: 22188, name: 'KINSADDE' },
                { id: 22189, name: 'KITAKA' },
                { id: 22190, name: 'KITOVU - NNUME' },
                { id: 22191, name: 'KITOVU ROAD' },
                { id: 22192, name: 'MARKET - TRIANGLE' },
                { id: 22193, name: 'MUKUDDE' },
                { id: 22194, name: 'NAKAYIBA  A' },
                { id: 22195, name: 'NAKAYIBA  B' },
                { id: 22196, name: 'NSEREKO' },
              ],
            },
            {
              id: 3501,
              name: 'SENYANGE',
              villages: [
                { id: 22197, name: 'BUCHULO' },
                { id: 22198, name: 'KITOVU HOSPITAL' },
                { id: 22199, name: 'KITOVU-KASANA' },
                { id: 22200, name: 'SSENYANGE  A' },
                { id: 22201, name: 'SSENYANGE  B' },
                { id: 22202, name: "ST.HENRY'S COLLEGE KITOVU" },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
