import { District } from '../types';

export default {
  id: 54,
  name: 'MASINDI',
  counties: [
    {
      id: 121,
      name: 'BUJENJE COUNTY',
      sub_counties: [
        {
          id: 755,
          name: 'BIKONZI',
          parishes: [
            {
              id: 3511,
              name: 'BIKONZI',
              villages: [
                { id: 59079, name: 'BIKONZI  I' },
                { id: 22266, name: 'IKOBA' },
                { id: 22267, name: 'ISAGARA KIRYANJOJO' },
                { id: 22268, name: 'ISAGARA KIRYANSEKA' },
                { id: 62863, name: 'KARUNGU-KIRYAMASASA' },
                { id: 22265, name: 'KATUUGO' },
                { id: 63626, name: 'KIKAIKYA' },
                { id: 22269, name: 'KISINGO  I' },
                { id: 22270, name: 'KISINGO  II' },
                { id: 22271, name: 'KISONGA' },
              ],
            },
            {
              id: 3514,
              name: 'KIKUBE',
              villages: [
                { id: 22285, name: 'BALYEIJUKIRA' },
                { id: 22286, name: 'KABAHAARA' },
                { id: 22287, name: 'KIKUUBE I' },
                { id: 63683, name: 'KIKUUBE II' },
                { id: 22288, name: 'KINYWAMURARA' },
                { id: 64479, name: 'KYABAKAMA' },
                { id: 22289, name: 'KYAKAITERA' },
                { id: 64857, name: 'KYONEKA' },
              ],
            },
            {
              id: 3513,
              name: 'KITONOZI',
              villages: [
                { id: 22282, name: 'BIHANGA' },
                { id: 63584, name: 'KIINA I' },
                { id: 22283, name: 'KITONONZI-IKOBA' },
                { id: 64076, name: 'KITONOZI-KANONI' },
                { id: 64077, name: 'KITONOZI-KATUGO' },
                { id: 22284, name: 'KITYEDO' },
              ],
            },
            {
              id: 3512,
              name: 'RUKONDWA',
              villages: [
                { id: 22272, name: 'KABBO' },
                { id: 63398, name: 'KIBUNDIRA' },
                { id: 22273, name: 'KICHANDI' },
                { id: 22274, name: 'KIINA' },
                { id: 22275, name: 'KIKARANGA' },
                { id: 22276, name: 'KISOMABUTUZI' },
                { id: 22277, name: 'KYANYAMBUBI' },
                { id: 22278, name: 'NSAMBYA' },
                { id: 22279, name: 'RUBANI' },
                { id: 69957, name: 'RUNYA' },
                { id: 22280, name: 'RWABATINI' },
                { id: 22281, name: 'RWENTALE' },
              ],
            },
          ],
        },
        {
          id: 752,
          name: 'BUDONGO',
          parishes: [
            { id: 9407, name: 'BWINAMIRA', villages: [{ id: 62039, name: 'KADUKURU  I' }] },
            {
              id: 3502,
              name: 'KABANGO',
              villages: [
                { id: 22203, name: 'BWINAMIRA  I' },
                { id: 22204, name: 'BWINAMIRA  II' },
                { id: 22205, name: 'BWINAMIRA  III' },
                { id: 22206, name: 'LUGAZI' },
              ],
            },
            {
              id: 9617,
              name: 'KARONGO',
              villages: [
                { id: 58774, name: 'AWIRE' },
                { id: 62595, name: 'KANYEGE I T/C' },
                { id: 62596, name: 'KANYEGE II' },
                { id: 62844, name: 'KARONGO' },
                { id: 64797, name: 'KYEMPUNU' },
                { id: 66053, name: 'MARRAM' },
                { id: 67893, name: 'NYABIGOMA' },
                { id: 68637, name: 'OJIMANYAN' },
              ],
            },
            {
              id: 3503,
              name: 'KASONGOIRE',
              villages: [
                { id: 22207, name: 'BULYANGO' },
                { id: 22208, name: 'KASONGOIRE' },
                { id: 22209, name: 'KIMANYA LOWER' },
                { id: 63708, name: 'KIMATUKA' },
                { id: 22210, name: 'KIRYAMYONGO' },
                { id: 22211, name: 'KISAGURA' },
                { id: 22212, name: 'KYABIJWENGE' },
                { id: 22213, name: 'NYAKYEJU' },
                { id: 22214, name: 'WAIPACU' },
              ],
            },
            {
              id: 3504,
              name: 'NYABYEYA',
              villages: [
                { id: 63880, name: 'KISARABWIRE' },
                { id: 64616, name: 'KYAMASUKA' },
                { id: 22215, name: 'NYABYEYA  I' },
                { id: 22216, name: 'NYABYEYA  II' },
                { id: 22217, name: 'NYABYEYA  T/C' },
                { id: 22218, name: 'NYAKAFUNJO' },
              ],
            },
          ],
        },
        {
          id: 1970,
          name: 'BULIIMA TOWN COUNCIL',
          parishes: [
            {
              id: 9544,
              name: 'KAHEMBE WARD',
              villages: [
                { id: 61844, name: 'KABAGARAMA' },
                { id: 63049, name: 'KATASENYWA' },
                { id: 63937, name: 'KISOGA' },
                { id: 64493, name: 'KYABATEKA' },
                { id: 64734, name: 'KYASWETE' },
                { id: 69882, name: 'RUBONA' },
                { id: 70178, name: 'RWENKOLE' },
              ],
            },
            {
              id: 9743,
              name: 'KISALIZI WARD',
              villages: [
                { id: 63713, name: 'KIMIGI' },
                { id: 63869, name: 'KISALIZI' },
                { id: 63980, name: 'KITABOHA' },
                { id: 64556, name: 'KYAKARANGWA' },
                { id: 64617, name: 'KYAMATAMA' },
                { id: 67912, name: 'NYABISOJO' },
              ],
            },
            {
              id: 9963,
              name: 'MARONGO WARD',
              villages: [
                { id: 63217, name: 'KAYANJA' },
                { id: 64012, name: 'KITEERA' },
                { id: 64482, name: 'KYABAKAZINDE' },
                { id: 64636, name: 'KYAMUGAMBA' },
                { id: 64754, name: 'KYAWINYI' },
              ],
            },
          ],
        },
        {
          id: 753,
          name: 'BWIJANGA',
          parishes: [
            {
              id: 3505,
              name: 'KAHEMBE',
              villages: [
                { id: 22219, name: 'KYABABANDE' },
                { id: 22220, name: 'MAIHA' },
                { id: 22221, name: 'MURRO' },
                { id: 22222, name: 'MUSOMA' },
                { id: 22223, name: 'NTUUMA' },
                { id: 22224, name: 'RWAMAKERE' },
              ],
            },
            {
              id: 3506,
              name: 'KITAMBA',
              villages: [
                { id: 22225, name: 'BUBANDA  I' },
                { id: 22226, name: 'BYEBEGA' },
                { id: 22227, name: 'BYERIMA' },
                { id: 22228, name: 'ISIMBA' },
                { id: 22229, name: 'KAIHA' },
                { id: 22230, name: 'KIHAARA' },
                { id: 22231, name: 'KIKINGURA' },
                { id: 22232, name: 'KINENABUHERE' },
                { id: 22233, name: 'KISAMBO' },
                { id: 22234, name: 'KITAMBA' },
                { id: 22235, name: 'KYAMAISO' },
                { id: 22236, name: 'KYAMAROLERE' },
                { id: 22237, name: 'KYAMUKUDUMI' },
                { id: 22238, name: 'KYANDANGI' },
                { id: 22239, name: 'MIRAMURA' },
              ],
            },
            {
              id: 3507,
              name: 'NTOMA',
              villages: [
                { id: 22240, name: 'BISEKE' },
                { id: 22241, name: 'BUBANDA  II' },
                { id: 22242, name: 'KATAKUNGIRWA' },
                { id: 22243, name: 'KIHAGANI' },
                { id: 22245, name: 'KYABAGABU' },
                { id: 22244, name: 'KYABAKOOTO' },
                { id: 22246, name: 'KYABIKULE' },
                { id: 22247, name: 'KYAKAHEERU' },
                { id: 22248, name: 'KYAKAKI' },
                { id: 22249, name: 'RUSANGURA' },
                { id: 22250, name: 'RWEBIGWARA' },
                { id: 22251, name: 'RWENJOJO' },
                { id: 70199, name: 'RWENSORORO' },
                { id: 22252, name: 'RWENZIRAMIRE' },
              ],
            },
          ],
        },
        {
          id: 754,
          name: 'KABANGO TOWN COUNCIL',
          parishes: [
            {
              id: 3509,
              name: 'KABANGO WARD',
              villages: [
                { id: 61872, name: 'KABANGO CENTRAL' },
                { id: 22255, name: 'KABANGO EAST' },
                { id: 61873, name: 'KABANGO SOUTH' },
                { id: 22256, name: 'KABANGO WEST' },
                { id: 22257, name: 'KADUKURU II' },
                { id: 22258, name: 'KIDAMUKE' },
                { id: 22259, name: 'KYANKADE' },
                { id: 22260, name: 'MUBENDE' },
              ],
            },
            {
              id: 3510,
              name: 'KAPEEKA WARD',
              villages: [
                { id: 22264, name: 'EWAFALA' },
                { id: 22261, name: 'KAPEEKA  I' },
                { id: 22262, name: 'KAPEEKA  II' },
                { id: 22263, name: 'KAPEEKA  III' },
              ],
            },
            {
              id: 3508,
              name: 'KINYARA SUGAR L.T.D.  WARD',
              villages: [
                { id: 57107, name: '8G' },
                { id: 22253, name: 'LABOUR' },
                { id: 22254, name: 'SENIOR QTRS' },
              ],
            },
          ],
        },
        {
          id: 756,
          name: 'NYANTONZI',
          parishes: [
            {
              id: 3519,
              name: 'KAJURA',
              villages: [
                { id: 22309, name: 'ABANGI' },
                { id: 22310, name: 'BYASIKU' },
                { id: 61167, name: 'DRABANI' },
                { id: 22311, name: 'EJIENGA' },
                { id: 22312, name: 'KIBALI' },
                { id: 22313, name: 'OGADRA' },
                { id: 68541, name: 'OGATI' },
              ],
            },
            {
              id: 3515,
              name: 'KASENENE',
              villages: [
                { id: 58010, name: 'ALIMUGONZA' },
                { id: 22290, name: 'BISAJU' },
                { id: 66703, name: 'MUSUMA' },
                { id: 22291, name: 'ONIENI' },
                { id: 70163, name: 'RWENGABI' },
                { id: 22292, name: 'SIMBA' },
              ],
            },
            {
              id: 3517,
              name: 'KIMANYA',
              villages: [
                { id: 57127, name: 'ABAMI' },
                { id: 22299, name: 'BINENEZA' },
                { id: 61189, name: 'DUNIA' },
                { id: 22300, name: 'KABALE' },
                { id: 22301, name: 'KIMANYA  II' },
                { id: 63707, name: 'KIMANYA SOUTH' },
                { id: 22302, name: 'RWENTALE  I' },
                { id: 22303, name: 'RWENTALE  II' },
              ],
            },
            {
              id: 3516,
              name: 'NYANTONZI',
              villages: [
                { id: 22293, name: 'KABABITO' },
                { id: 22294, name: 'KATANGA' },
                { id: 63151, name: 'KATUGO  I' },
                { id: 22295, name: 'KATUGO  II' },
                { id: 22296, name: 'NYANTONZI CENTRE' },
                { id: 68230, name: 'NYANTONZI EAST' },
                { id: 22297, name: 'RWANGARA' },
                { id: 22298, name: 'SIIBA' },
              ],
            },
            {
              id: 3518,
              name: 'RWEMPISI',
              villages: [
                { id: 22304, name: 'AKARAKAVENI  I' },
                { id: 22305, name: 'AKARAKAVENI  II' },
                { id: 22306, name: 'AMBAKA' },
                { id: 22307, name: 'KYAMONGI' },
                { id: 70064, name: 'RWAMANYA' },
                { id: 22308, name: 'RWEMPISI EAST' },
                { id: 70157, name: 'RWEMPISI WEST' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 122,
      name: 'BURULI COUNTY',
      sub_counties: [
        {
          id: 761,
          name: 'KIJUNJUBWA',
          parishes: [
            {
              id: 3529,
              name: 'KIJUNJUBWA',
              villages: [
                { id: 59604, name: 'BUKOOBA II' },
                { id: 22362, name: 'KYANGAMWOYO' },
              ],
            },
            {
              id: 3530,
              name: 'KYARUTANGA',
              villages: [
                { id: 22363, name: 'KITINWA' },
                { id: 22364, name: 'KIZIMWE' },
                { id: 22365, name: 'KYARUTANGA' },
                { id: 64777, name: 'KYEITUNGAMYE' },
                { id: 22366, name: 'NYINEZARA' },
                { id: 70246, name: 'RWOMUKABARA' },
              ],
            },
            {
              id: 3528,
              name: 'MIDUMA',
              villages: [
                { id: 22360, name: 'KAIKUKU' },
                { id: 22361, name: 'KATEIRWE' },
                { id: 22358, name: 'MIDUUMA' },
                { id: 22359, name: 'OMWIGURU' },
              ],
            },
          ],
        },
        {
          id: 762,
          name: 'KIJUNJUBWA TOWN COUNCIL',
          parishes: [
            {
              id: 3531,
              name: 'BUKOOBA WARD',
              villages: [
                { id: 22367, name: 'BUKOOBA I' },
                { id: 68067, name: 'NYAKATETE' },
              ],
            },
            {
              id: 3532,
              name: 'KIJUNJUBWA WARD',
              villages: [
                { id: 63596, name: 'KIJINJUBWA SOUTH' },
                { id: 22368, name: 'KIJUNJUBWA NORTH' },
              ],
            },
            {
              id: 10128,
              name: 'NYAMUKONGO WARD',
              villages: [
                { id: 68150, name: 'NYAMIGAMBA' },
                { id: 68194, name: 'NYAMUKONGO' },
              ],
            },
          ],
        },
        {
          id: 758,
          name: 'KIMENGO',
          parishes: [
            {
              id: 3523,
              name: 'KIBANGYA',
              villages: [
                { id: 22325, name: 'KAYERA' },
                { id: 22326, name: 'KIBANGYA' },
                { id: 63628, name: 'KIKAITO' },
                { id: 66145, name: 'MATUUGO' },
              ],
            },
            {
              id: 3522,
              name: 'KIMENGO',
              villages: [
                { id: 22322, name: 'KARANGWE' },
                { id: 22323, name: 'KARWARA' },
                { id: 64160, name: 'KIZINGA' },
                { id: 66783, name: 'MYEBA' },
                { id: 22324, name: 'NYAKARONGO' },
              ],
            },
          ],
        },
        {
          id: 2034,
          name: 'KIRULI',
          parishes: [
            {
              id: 9654,
              name: 'KATUUGO',
              villages: [
                { id: 63152, name: 'KATUGO EAST' },
                { id: 63153, name: 'KATUGO WEST' },
                { id: 63716, name: 'KIMINA EAST' },
                { id: 63831, name: 'KIRULI  II' },
                { id: 63832, name: 'KIRULI CENTRAL' },
                { id: 63929, name: 'KISINDIZI  II A' },
                { id: 63930, name: 'KISINDIZI  II B' },
              ],
            },
            {
              id: 9674,
              name: 'KIBIBIRA',
              villages: [
                { id: 59162, name: 'BOMBO' },
                { id: 62085, name: 'KAGERA' },
                { id: 63359, name: 'KIBIBIRA CENTRALI' },
                { id: 63360, name: 'KIBIBIRA I' },
                { id: 63627, name: 'KIKAITO' },
                { id: 64108, name: 'KITUMU' },
                { id: 67968, name: 'NYAKABALE I' },
                { id: 67970, name: 'NYAKABALE II' },
                { id: 68035, name: 'NYAKARONGO I' },
                { id: 68036, name: 'NYAKARONGO II' },
              ],
            },
            {
              id: 9737,
              name: 'KIRULI',
              villages: [
                { id: 61268, name: 'EPEDI' },
                { id: 63574, name: 'KIHUNGYA' },
                { id: 63999, name: 'KITANYATA  II' },
                { id: 64000, name: 'KITANYATA I' },
                { id: 64001, name: 'KITANYATA-KYAMUNARA' },
                { id: 64025, name: 'KITENGULE I' },
                { id: 64462, name: 'KYABABYARA I' },
                { id: 64463, name: 'KYABABYARA II' },
                { id: 64495, name: 'KYABATITI' },
                { id: 64774, name: 'KYEICUMU' },
                { id: 67790, name: 'NJUNWEKI' },
              ],
            },
          ],
        },
        {
          id: 757,
          name: 'KYATIRI TOWN COUNCIL',
          parishes: [
            {
              id: 3521,
              name: 'KYATIRI EAST WARD',
              villages: [
                { id: 22317, name: 'KIBOIJOGORO  I' },
                { id: 22318, name: 'KIBOIJOGORO  II' },
                { id: 22319, name: 'KISEKURA  I' },
                { id: 22321, name: 'KISEKURA II' },
                { id: 22320, name: 'KYABAKAMI' },
                { id: 64743, name: 'KYATIRI CENTRE' },
              ],
            },
            {
              id: 3520,
              name: 'KYATIRI WEST WARD',
              villages: [
                { id: 64575, name: 'KYAKAYAGA  I' },
                { id: 64576, name: 'KYAKAYAGA  II' },
                { id: 22314, name: 'KYAMBOGO' },
                { id: 22316, name: 'NYAKASAGAZI  I' },
                { id: 22315, name: 'NYAKASAGAZI  II' },
              ],
            },
          ],
        },
        {
          id: 2045,
          name: 'LABONGO',
          parishes: [
            {
              id: 9630,
              name: 'KASENYI',
              villages: [
                { id: 59149, name: 'BOKWE' },
                { id: 62917, name: 'KASENYI' },
                { id: 63489, name: 'KIGARAGARA' },
                { id: 63530, name: 'KIGUNIA  I' },
                { id: 63531, name: 'KIGUNIA II' },
                { id: 63618, name: 'KIJUMBURA I' },
                { id: 63619, name: 'KIJUMBURA II' },
                { id: 64102, name: 'KITUKA   II' },
                { id: 64103, name: 'KITUKA  CENTRAL' },
              ],
            },
            {
              id: 9704,
              name: 'KIHAGUZI',
              villages: [
                { id: 61514, name: 'HANGA  I' },
                { id: 63454, name: 'KIDWERA  I' },
                { id: 63539, name: 'KIHAGUZI A' },
                { id: 63540, name: 'KIHAGUZI B' },
                { id: 63541, name: 'KIHAGUZI CENTRAL' },
                { id: 64720, name: 'KYARUMBEIHA' },
                { id: 68116, name: 'NYAKYANIKA  I' },
                { id: 68174, name: 'NYAMITETE' },
              ],
            },
            {
              id: 9707,
              name: 'KIHONDA',
              villages: [
                { id: 63096, name: 'KATIKARA' },
                { id: 63456, name: 'KIDWERA CENTRAL' },
                { id: 63559, name: 'KIHONDA' },
                { id: 63692, name: 'KILANYI' },
                { id: 63846, name: 'KIRYAMPATE' },
                { id: 64492, name: 'KYABATEGA' },
                { id: 68117, name: 'NYAKYANIKA CENTRAL' },
                { id: 71001, name: 'WALYOBA' },
              ],
            },
            {
              id: 9851,
              name: 'LABONGO',
              villages: [
                { id: 62023, name: 'KADEDEBE' },
                { id: 63455, name: 'KIDWERA  II' },
                { id: 63791, name: 'KIRALIIRE' },
                { id: 63858, name: 'KISABAGWA' },
                { id: 63876, name: 'KISANJA' },
                { id: 64646, name: 'KYAMUGWERA' },
                { id: 64879, name: 'LABONGO' },
                { id: 68118, name: 'NYAKYANIKA II' },
                { id: 70177, name: 'RWENKOBE' },
              ],
            },
          ],
        },
        {
          id: 759,
          name: 'MIIRYA',
          parishes: [
            {
              id: 3524,
              name: 'BIGANDO',
              villages: [
                { id: 22327, name: 'BALYEGOMBA' },
                { id: 22328, name: 'KABUTUKURU' },
                { id: 22329, name: 'KAHARA I' },
                { id: 22334, name: 'KAHARA II' },
                { id: 22330, name: 'KATAGURUKWA' },
                { id: 22331, name: 'KIBAALI KITONDE' },
                { id: 22332, name: 'KIJENGA' },
                { id: 22333, name: 'KINUUMA' },
              ],
            },
            {
              id: 3525,
              name: 'ISIMBA',
              villages: [
                { id: 22335, name: 'KISINDIZI' },
                { id: 22336, name: 'KITOOKA' },
                { id: 22337, name: 'KYABASWA' },
                { id: 22338, name: 'KYABASWA/KICHOPE' },
                { id: 22339, name: 'KYEDIKYO' },
              ],
            },
            {
              id: 3526,
              name: 'KIGUULYA',
              villages: [
                { id: 22340, name: 'BISHENYI' },
                { id: 22341, name: 'KIGEZI TC' },
                { id: 22342, name: 'KIJOGORO' },
                { id: 22343, name: 'KISUGA/KINUMI' },
                { id: 22344, name: 'KITWETWE' },
                { id: 22345, name: 'KYARUKUNYA' },
                { id: 22346, name: 'RWEMIGAALI' },
              ],
            },
          ],
        },
        {
          id: 760,
          name: 'PAKANYI',
          parishes: [
            {
              id: 3527,
              name: 'KYAKAMESE',
              villages: [
                { id: 22347, name: 'ALIMUGONZA I' },
                { id: 22349, name: 'KABOROGOTA A' },
                { id: 22350, name: 'KABOROGOTA B' },
                { id: 22348, name: 'KABOROGOTA CENTRAL' },
                { id: 22351, name: 'KATUGO' },
                { id: 22352, name: 'KIBAMBA BLOCK B' },
                { id: 22353, name: 'KIBAMBA CENTRAL' },
                { id: 22354, name: 'KIBAMBA TRADING CENTRE I' },
                { id: 22355, name: 'KISINDIZI  IA' },
                { id: 63928, name: 'KISINDIZI  IB' },
                { id: 22356, name: 'KYAKAMESE' },
                { id: 22357, name: 'NAMAGONGE' },
              ],
            },
            {
              id: 9813,
              name: 'KYAKAMESE CENTRAL',
              villages: [
                { id: 58011, name: 'ALIMUGONZA CENTRAL' },
                { id: 61024, name: 'CHONGOYOMA' },
                { id: 61544, name: 'IBARALIBI' },
                { id: 62989, name: 'KASOMORO' },
                { id: 63164, name: 'KATUMBA' },
                { id: 63378, name: 'KIBIRANI' },
                { id: 63927, name: 'KISINDI' },
                { id: 64591, name: 'KYALABWOMI' },
                { id: 64719, name: 'KYARUMBEIHA' },
                { id: 64749, name: 'KYATWENGE' },
                { id: 69502, name: 'PAKANYI' },
                { id: 70978, name: 'WAIGA A' },
              ],
            },
            {
              id: 9814,
              name: 'KYAKAMESE EAST',
              villages: [
                { id: 62876, name: 'KASAMBYA' },
                { id: 63974, name: 'KISWERAMAHINDA' },
                { id: 64152, name: 'KIYUUYA' },
                { id: 64635, name: 'KYAMUDIKYA' },
                { id: 68024, name: 'NYAKAKOMA' },
                { id: 68071, name: 'NYAKATOGO' },
                { id: 69433, name: 'PABIIDI' },
                { id: 70979, name: 'WAIGA B' },
              ],
            },
            { id: 9815, name: 'KYAKAMESE WEST', villages: [] },
            {
              id: 9834,
              name: 'KYANGAMYOYO',
              villages: [
                { id: 63715, name: 'KIMINA' },
                { id: 63833, name: 'KIRULI I' },
                { id: 64675, name: 'KYANGAMWOYO' },
                { id: 68206, name: 'NYANDIMA' },
                { id: 70602, name: 'TANTARA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 123,
      name: 'MASINDI MUNICIPALITY',
      sub_counties: [
        {
          id: 765,
          name: 'CENTRAL DIVISION',
          parishes: [
            {
              id: 3538,
              name: 'CIVIC CENTRE WARD',
              villages: [
                { id: 22415, name: 'CENTRAL I' },
                { id: 22414, name: 'CENTRAL II' },
                { id: 22416, name: 'EASTERN' },
                { id: 22417, name: 'KATAMA' },
                { id: 22418, name: 'NORTHEN' },
                { id: 22419, name: 'SOUTHERN' },
                { id: 22420, name: 'WESTERN' },
              ],
            },
            {
              id: 3539,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 22421, name: 'KABARWANA' },
                { id: 22422, name: 'KIRASA  I' },
                { id: 22423, name: 'KIRASA  II' },
                { id: 22424, name: 'NYAMIGISA' },
                { id: 22425, name: 'NYANGAHYA' },
              ],
            },
            {
              id: 3540,
              name: 'WESTERN WARD',
              villages: [
                { id: 22426, name: 'BULYASOJO' },
                { id: 22427, name: 'KIHANDE  I' },
                { id: 22428, name: 'KIHANDE  II' },
                { id: 22429, name: 'KIJURA  CENTRAL' },
                { id: 22430, name: 'KIJURA  NORTH' },
                { id: 22431, name: 'KIJURA  SOUTH' },
                { id: 22432, name: 'KISIITA' },
              ],
            },
          ],
        },
        {
          id: 763,
          name: 'KARUJUBU DIVISION',
          parishes: [
            {
              id: 3535,
              name: 'KIBWONA WARD',
              villages: [
                { id: 22385, name: 'BULYANGO  I' },
                { id: 22386, name: 'BULYANGO  II' },
                { id: 22387, name: 'IRAGARA' },
                { id: 22388, name: 'KABALYE   I' },
                { id: 22389, name: 'KIBWONA' },
                { id: 22390, name: 'KYABADINDI' },
              ],
            },
            {
              id: 3533,
              name: 'KIHUUBA WARD',
              villages: [
                { id: 22369, name: 'KABALYE SETTLEMENT' },
                { id: 22370, name: 'KAMUNYONGA' },
                { id: 22377, name: 'KIGAJU/KASEKURO' },
                { id: 22378, name: 'KIHUUBA A' },
                { id: 22371, name: 'KIHUUBA B' },
                { id: 22372, name: 'KIROYA' },
                { id: 22373, name: 'KISARABWIRE' },
                { id: 22374, name: 'KISINDIZI' },
                { id: 22375, name: 'KISWATA' },
                { id: 22376, name: 'KYEMA' },
              ],
            },
            {
              id: 3534,
              name: 'KISIITA WARD',
              villages: [
                { id: 22379, name: 'KARUJUBU' },
                { id: 22380, name: 'KINOGOZI  A' },
                { id: 22381, name: 'KINOGOZI  B' },
                { id: 22382, name: 'KIRIMA' },
                { id: 22383, name: 'KITOJO' },
                { id: 22384, name: 'KYARUGANGARA' },
              ],
            },
          ],
        },
        {
          id: 766,
          name: 'KIGULYA DIVISION',
          parishes: [
            {
              id: 3541,
              name: 'BIGANDO WARD',
              villages: [
                { id: 22434, name: 'BIGANDO' },
                { id: 22435, name: 'GORORA' },
                { id: 22433, name: 'KIDURU' },
                { id: 22436, name: 'KYAKASOZI' },
                { id: 22437, name: 'KYAMUJWARA' },
                { id: 22438, name: 'KYAMWITA' },
                { id: 22439, name: 'NYABINYIRA' },
              ],
            },
            {
              id: 3543,
              name: 'ISIMBA WARD',
              villages: [
                { id: 61680, name: 'ISIMBA' },
                { id: 22445, name: 'KIJOGO' },
                { id: 22446, name: 'KISANJA/KICHOPE' },
                { id: 22447, name: 'KITAMANYA' },
                { id: 22448, name: 'KYEMA/KYAKATO' },
                { id: 22449, name: 'NYAKALOGI/KASAMBYA' },
              ],
            },
            {
              id: 3542,
              name: 'KIGULYA WARD',
              villages: [
                { id: 22440, name: 'KIGULYA-KYETEGYA' },
                { id: 22441, name: 'KIHAMYA' },
                { id: 22442, name: 'KIKONYA' },
                { id: 22444, name: 'MIIRYA' },
                { id: 22443, name: 'NYAKATOOKE' },
              ],
            },
          ],
        },
        {
          id: 764,
          name: 'NYANGAHYA DIVISION',
          parishes: [
            {
              id: 3537,
              name: 'KIKWANANA WARD',
              villages: [
                { id: 22405, name: 'BIIZI' },
                { id: 22406, name: 'BINYINYA' },
                { id: 22407, name: 'KAKWESE  I' },
                { id: 22408, name: 'KAKWESE  II' },
                { id: 22413, name: 'KAMURASI' },
                { id: 22409, name: 'KIJAMBURA' },
                { id: 22410, name: 'KIKWANANA' },
                { id: 22411, name: 'KISENGYA' },
                { id: 22412, name: 'KYAMUGWERI' },
              ],
            },
            {
              id: 3536,
              name: 'KIRYANGA WARD',
              villages: [
                { id: 22391, name: 'BUTOOBE' },
                { id: 22392, name: 'BWIITA' },
                { id: 22393, name: 'BYERIMA' },
                { id: 22394, name: 'KALYANGO' },
                { id: 22395, name: 'KATASENYWA' },
                { id: 22404, name: 'KATENDERO' },
                { id: 22403, name: 'KAYANJA' },
                { id: 22396, name: 'KIBYAMA' },
                { id: 22397, name: 'KIJWEKA' },
                { id: 22398, name: 'KIRYANGA  II' },
                { id: 22399, name: 'KYAKATABUKA' },
                { id: 67779, name: 'NGURAGULE' },
                { id: 22400, name: 'NYABISENSE' },
                { id: 22401, name: 'RWENSA' },
                { id: 22402, name: 'RWIJEERE' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
