import { District } from '../index';

export default {
  id: 77,
  name: 'MAYUGE',
  counties: [
    {
      id: 189,
      name: 'BUNYA COUNTY EAST',
      sub_counties: [
        {
          id: 1167,
          name: 'BUKABOOLI',
          parishes: [
            {
              id: 5414,
              name: 'BUGOTO',
              villages: [
                { id: 34316, name: 'BUGOTO  A' },
                { id: 34317, name: 'BUGOTO  B' },
                { id: 34318, name: 'BUTUMBULA' },
                { id: 34324, name: 'KAKOGE' },
                { id: 34322, name: 'KITUMBEZI' },
                { id: 34325, name: 'LULANDA' },
                { id: 34319, name: 'MUNYAZI' },
                { id: 34323, name: 'MUSUBI' },
                { id: 34320, name: 'NAMULULI' },
                { id: 34321, name: 'NAWAMPONGO' },
              ],
            },
            {
              id: 5417,
              name: 'BUGUMIA',
              villages: [
                { id: 34338, name: 'BUDUMBA' },
                { id: 34339, name: 'KALIRO' },
                { id: 34340, name: 'KANYANA' },
                { id: 34341, name: 'KIRONGO  A' },
                { id: 34342, name: 'KIRONGO  B' },
                { id: 34343, name: 'MAKOOMA' },
                { id: 34344, name: 'NAKASUWA' },
              ],
            },
            {
              id: 5418,
              name: 'BUKABOOLI',
              villages: [
                { id: 34345, name: 'BUKABOOLI' },
                { id: 34346, name: 'KALAGALA A' },
                { id: 34350, name: 'KALAGALA B' },
                { id: 34347, name: 'KIKUNYU' },
                { id: 34348, name: "NAMULWANA 'A'" },
                { id: 34349, name: "NAMULWANA 'B'" },
              ],
            },
            {
              id: 5419,
              name: 'BUYUGU',
              villages: [
                { id: 34355, name: 'BUSITEMA' },
                { id: 34351, name: 'BUYUGU' },
                { id: 34356, name: 'IGAYAZA' },
                { id: 34352, name: 'KINAWAMBUZI' },
                { id: 34357, name: 'MBALE' },
                { id: 34353, name: 'NABYAMA' },
                { id: 34358, name: 'NABYAMA BEACH' },
                { id: 34354, name: 'NAMAKOKO' },
              ],
            },
            {
              id: 5416,
              name: 'MATOVU',
              villages: [
                { id: 34334, name: 'BUKANGA' },
                { id: 34335, name: 'MATOVU' },
                { id: 34336, name: 'NABIWERO' },
                { id: 34337, name: 'NAKIBAGO' },
              ],
            },
            {
              id: 5415,
              name: 'MAYIRINYA',
              villages: [
                { id: 34326, name: 'BUSIRA' },
                { id: 34327, name: 'KASOZI' },
                { id: 34333, name: 'KASOZI B' },
                { id: 34332, name: 'LUWUTA' },
                { id: 34328, name: 'LWANDERA' },
                { id: 34329, name: 'MAIRINYA  A' },
                { id: 34330, name: "MAIRINYA 'B'" },
                { id: 34331, name: 'NAWANDEGEYI' },
              ],
            },
          ],
        },
        {
          id: 1165,
          name: 'BUWAAYA',
          parishes: [
            {
              id: 5403,
              name: 'BUWAISWA',
              villages: [
                { id: 34245, name: 'BUBAGO' },
                { id: 34246, name: 'BUWAAYA' },
                { id: 34247, name: 'BUWAISWA' },
                { id: 34249, name: 'NABUYAGI' },
                { id: 34248, name: 'NTAFUNGIRWA' },
              ],
            },
            {
              id: 5405,
              name: 'BUWOLYA',
              villages: [
                { id: 34255, name: 'BUWOLYA' },
                { id: 34256, name: 'IVUGUNYU' },
                { id: 34257, name: 'IWUUBA' },
                { id: 34258, name: 'KAKINDU' },
                { id: 34259, name: 'NTINDA' },
              ],
            },
            {
              id: 5404,
              name: 'ISIKIRO',
              villages: [
                { id: 34254, name: 'BUKOOBA' },
                { id: 34250, name: 'IBANGA' },
                { id: 34251, name: 'ISIKIRO' },
                { id: 34252, name: 'KANYABWINA' },
                { id: 34253, name: 'KIKUBO' },
              ],
            },
            {
              id: 5406,
              name: 'KABAINGIRIRE',
              villages: [
                { id: 34260, name: 'KABANGIRE' },
                { id: 34261, name: 'NAKATE' },
                { id: 34262, name: 'NAMADHI' },
                { id: 34263, name: 'NAMATALE' },
                { id: 34264, name: 'NAWANVUBU' },
              ],
            },
            {
              id: 5407,
              name: 'NSANGO',
              villages: [
                { id: 34265, name: 'BULONDO' },
                { id: 34266, name: 'LUGANGU' },
                { id: 34267, name: 'NABITTU' },
                { id: 34268, name: 'NAMAGO' },
                { id: 34269, name: 'NSANGO' },
              ],
            },
          ],
        },
        {
          id: 1166,
          name: 'KIGANDALO',
          parishes: [
            {
              id: 5412,
              name: 'BUGONDO',
              villages: [
                { id: 34304, name: 'BUGONDO' },
                { id: 34305, name: 'NABUKONI' },
                { id: 34306, name: 'NAKAWA' },
                { id: 34307, name: 'NAMALEGE' },
                { id: 34308, name: 'WALUKOKO' },
              ],
            },
            {
              id: 5408,
              name: 'ISENDA',
              villages: [
                { id: 34270, name: 'BUGUNDA' },
                { id: 34271, name: 'ISENDA' },
                { id: 34272, name: 'ISENDA  A' },
                { id: 34273, name: 'KATALAKABI' },
                { id: 34274, name: 'NAMAIGA' },
                { id: 34275, name: 'NAMATOVU' },
                { id: 34276, name: 'NANVUNANO' },
                { id: 34277, name: 'NVUNWA' },
                { id: 34278, name: 'WALULENGA' },
              ],
            },
            {
              id: 5409,
              name: 'KIGANDALO',
              villages: [
                { id: 34280, name: 'KIGANDALO A' },
                { id: 34286, name: 'KIGANDALO B' },
                { id: 34281, name: 'NAIGERIA' },
                { id: 34287, name: 'NAKASERO' },
                { id: 34279, name: 'NAKAZIGO' },
                { id: 34282, name: 'NAKIDUBULI' },
                { id: 34283, name: 'NAMPU' },
                { id: 34284, name: 'NDALAEGOBYE' },
                { id: 34285, name: 'WANDAWA' },
              ],
            },
            {
              id: 5411,
              name: 'KIGULU',
              villages: [
                { id: 34297, name: 'BUBBALYA' },
                { id: 34298, name: 'BUYAGA' },
                { id: 34299, name: 'KIGULU' },
                { id: 34300, name: 'KIREWE' },
                { id: 34301, name: 'NAMASAKA' },
                { id: 34302, name: 'NAMUGOLO' },
                { id: 34303, name: 'NSUMBA' },
              ],
            },
            {
              id: 5410,
              name: 'KIOGA (MAYENGO)',
              villages: [
                { id: 34288, name: 'BUSUI' },
                { id: 34289, name: 'BUYEGO' },
                { id: 34290, name: 'BWEZA' },
                { id: 34291, name: 'KAZINGA' },
                { id: 34292, name: 'KIOGA' },
                { id: 34293, name: 'LUKUNYU' },
                { id: 34295, name: 'NABIKOMO' },
                { id: 34294, name: 'NAKAVULE' },
                { id: 34296, name: 'SESE' },
              ],
            },
            {
              id: 5413,
              name: 'MALEKA',
              villages: [
                { id: 34309, name: 'ISOOLA' },
                { id: 34310, name: 'KIGULAMU' },
                { id: 34311, name: 'MABIRIZI' },
                { id: 34312, name: 'MALEKA A' },
                { id: 34315, name: 'MALEKA B' },
                { id: 34313, name: 'NAKITWALO' },
                { id: 34314, name: 'WANKONGE' },
              ],
            },
          ],
        },
        {
          id: 1168,
          name: 'MPUNGWE',
          parishes: [
            {
              id: 5424,
              name: 'BUYERE',
              villages: [
                { id: 34381, name: 'BUGUWA' },
                { id: 34382, name: 'BUYERE' },
                { id: 34383, name: 'MUSIMA' },
                { id: 34384, name: 'MUSITA' },
                { id: 34385, name: 'NAKITAMU' },
              ],
            },
            {
              id: 5423,
              name: 'MAINA',
              villages: [
                { id: 34376, name: 'BUSU' },
                { id: 34380, name: 'KABERE' },
                { id: 34377, name: 'KYETE' },
                { id: 34378, name: 'MAINA' },
                { id: 34379, name: 'MWEZI' },
              ],
            },
            {
              id: 5420,
              name: 'MUGGI',
              villages: [
                { id: 34359, name: 'BUWANUKA' },
                { id: 34360, name: 'KASOKWE' },
                { id: 34361, name: 'MPUNGWE' },
                { id: 34362, name: 'MUGGI' },
              ],
            },
            {
              id: 5421,
              name: 'WAIRAMA',
              villages: [
                { id: 34363, name: 'BULYANGADA' },
                { id: 34370, name: 'BUWALIRA' },
                { id: 34364, name: 'KASUTAIME' },
                { id: 34365, name: 'MAWUMU' },
                { id: 34367, name: 'MPUMU' },
                { id: 34366, name: 'MUNYONYI' },
                { id: 34368, name: 'NAWANKOLE' },
                { id: 34369, name: 'WAIRAMA' },
              ],
            },
            {
              id: 5422,
              name: 'WAMULONGO',
              villages: [
                { id: 34371, name: 'BUSWIKIRA' },
                { id: 34372, name: 'MAKOOVA' },
                { id: 34373, name: 'NAMATOOKE' },
                { id: 34374, name: 'WAMULONGO' },
                { id: 34375, name: 'WANDAWA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 190,
      name: 'BUNYA COUNTY SOUTH',
      sub_counties: [
        {
          id: 1173,
          name: 'BUGADDE TOWN COUNCIL',
          parishes: [
            {
              id: 5448,
              name: 'BUGADE WARD',
              villages: [
                { id: 34547, name: 'BUGADDE A' },
                { id: 34548, name: 'BUGADDE B' },
                { id: 34552, name: 'BUGADDE C' },
                { id: 34550, name: 'BUGADDE EAST' },
                { id: 34553, name: 'BUGADDE NORTH' },
                { id: 34551, name: 'BUGADDE WEST' },
                { id: 34549, name: 'BUGOYA' },
              ],
            },
            {
              id: 5449,
              name: 'BUSENDA WARD',
              villages: [
                { id: 34554, name: 'BUSENDA A' },
                { id: 34555, name: 'BUSENDA B' },
                { id: 34556, name: 'BUSENDA C' },
              ],
            },
            {
              id: 5447,
              name: 'KITYERERA WARD',
              villages: [
                { id: 34544, name: 'KITYERERA  A' },
                { id: 34545, name: 'KITYERERA  B' },
                { id: 34546, name: 'KITYERERA  C' },
              ],
            },
            {
              id: 5450,
              name: 'NAKIBENGO WARD',
              villages: [
                { id: 34557, name: 'ITUBA A' },
                { id: 34559, name: 'ITUBA B' },
                { id: 34558, name: 'KIKOKOLI' },
                { id: 34560, name: 'NAKIBENGO' },
              ],
            },
          ],
        },
        {
          id: 1172,
          name: 'BUSAKIRA',
          parishes: [
            {
              id: 5446,
              name: 'BUKUNJA',
              villages: [
                { id: 34537, name: "BUKUNJA 'A'" },
                { id: 34538, name: "BUKUNJA 'B'" },
                { id: 34539, name: 'BUSAALA' },
                { id: 34540, name: 'LUBALI' },
                { id: 34541, name: "NAMISU 'A'" },
                { id: 34542, name: "NAMISU 'B'" },
                { id: 34543, name: 'NAMISU C' },
              ],
            },
            {
              id: 5444,
              name: 'BUTANGALA',
              villages: [
                { id: 34525, name: 'BUBALI' },
                { id: 34526, name: 'BUGOYE' },
                { id: 34528, name: "BUTANGALA 'A'" },
                { id: 34529, name: "BUTANGALA 'B'" },
                { id: 34527, name: 'MUKONDA' },
                { id: 34530, name: 'NAMIRO' },
                { id: 34531, name: 'WAITA' },
              ],
            },
            {
              id: 5442,
              name: 'KALUUBA',
              villages: [
                { id: 34512, name: "BUSAKIRA 'A'" },
                { id: 34514, name: "BUSAKIRA 'C'" },
                { id: 34515, name: "BUSAKIRA 'D'" },
                { id: 34513, name: 'BUSAKIRA B' },
                { id: 34516, name: 'KAFUMITA' },
                { id: 34518, name: "KALUUBA 'B'" },
                { id: 34519, name: "KALUUBA 'C'" },
                { id: 34517, name: "KAULUBA 'A'" },
              ],
            },
            {
              id: 5443,
              name: 'MAUMU',
              villages: [
                { id: 34520, name: 'BUSEERA B' },
                { id: 34521, name: 'BUYANIRWA' },
                { id: 34522, name: 'MAUMU A' },
                { id: 34523, name: 'MAUMU B' },
                { id: 34524, name: 'NAMWOBA' },
              ],
            },
            {
              id: 5445,
              name: 'WAMBETE',
              villages: [
                { id: 34532, name: "BUSEERA 'A'" },
                { id: 34533, name: "BUSEERA 'C'" },
                { id: 34534, name: 'MACHECHE' },
                { id: 34535, name: "WAMBETE 'A'" },
                { id: 34536, name: "WAMBETE 'B'" },
              ],
            },
          ],
        },
        {
          id: 1174,
          name: 'BWONDHA TOWN COUNCIL',
          parishes: [
            {
              id: 5451,
              name: 'BWONDHA CENTRAL',
              villages: [
                { id: 34562, name: 'BWONDHA  D' },
                { id: 34563, name: 'BWONDHA B' },
                { id: 34561, name: 'BWONDHA CENTRAL' },
              ],
            },
            {
              id: 5452,
              name: 'BWONDHA SOUTH WARD',
              villages: [
                { id: 34566, name: 'BWONDHA A' },
                { id: 34564, name: 'BWONDHA EAST' },
                { id: 34565, name: 'NABIDONGA' },
              ],
            },
            {
              id: 5453,
              name: 'MAKONKO WARD',
              villages: [
                { id: 34567, name: 'KAYANJA' },
                { id: 34568, name: 'KIYONJO' },
                { id: 34569, name: 'MAKONKO A' },
                { id: 34570, name: 'MAKONKO B' },
                { id: 34571, name: 'MIREMBE' },
              ],
            },
            {
              id: 5454,
              name: 'MUSOMA WARD',
              villages: [
                { id: 34572, name: 'BUKIMERA' },
                { id: 34573, name: 'MUSOMA' },
                { id: 34574, name: 'NAKAWA' },
              ],
            },
            {
              id: 5455,
              name: 'NALUBABWE',
              villages: [
                { id: 34578, name: 'BWONDHA C' },
                { id: 34577, name: 'MULOWOZA' },
                { id: 34575, name: 'NALUBABWE A' },
                { id: 34576, name: 'NALUBABWE B' },
              ],
            },
            {
              id: 5456,
              name: 'NKALANJA WARD',
              villages: [
                { id: 34579, name: 'BWONDHA CENTRAL MARKET' },
                { id: 34580, name: 'NKALANGA A' },
                { id: 34581, name: 'NKALANGA B' },
                { id: 34582, name: 'VICTORIAL' },
              ],
            },
          ],
        },
        {
          id: 1171,
          name: 'JAGUZI',
          parishes: [
            {
              id: 5437,
              name: 'BUMBA',
              villages: [
                { id: 34489, name: 'BUKABAMBWE' },
                { id: 34490, name: 'BUYAKO BEACH' },
                { id: 34491, name: 'BUYAKO VILLAGE' },
                { id: 34492, name: 'GALILAYA' },
              ],
            },
            {
              id: 5438,
              name: 'JAGUZI',
              villages: [
                { id: 34493, name: 'BUSABALA A' },
                { id: 34500, name: 'BUSABALA B' },
                { id: 34494, name: 'BWAYA/BUKEMBO' },
                { id: 34495, name: 'GOOLI A' },
                { id: 34502, name: 'GOOLI B' },
                { id: 34496, name: 'KAZIRU' },
                { id: 34497, name: 'MUBEMBE' },
                { id: 34498, name: 'MUSOMA' },
                { id: 34501, name: 'NABUKALU A' },
                { id: 34499, name: 'NABUKALU B' },
              ],
            },
            {
              id: 5440,
              name: 'KAAZA',
              villages: [
                { id: 34506, name: 'KAAZA  A' },
                { id: 34507, name: 'KAAZA  B' },
                { id: 34508, name: 'SIMWE ISLAND' },
              ],
            },
            {
              id: 5441,
              name: 'MASOLYA',
              villages: [
                { id: 34509, name: "MASOLYA 'A'" },
                { id: 34510, name: "MASOLYA 'B'" },
                { id: 34511, name: 'MASOLYA CENTRAL' },
              ],
            },
            {
              id: 5436,
              name: 'SAGITU',
              villages: [
                { id: 34485, name: 'BUSWETA' },
                { id: 34486, name: 'DEMBE' },
                { id: 34487, name: 'MAGANDA' },
                { id: 34488, name: 'NALUWERERE' },
              ],
            },
            {
              id: 5439,
              name: 'SERINYABI',
              villages: [
                { id: 34505, name: 'KOLOLO' },
                { id: 34503, name: 'LUKOBA' },
                { id: 34504, name: 'MASAMBA' },
              ],
            },
          ],
        },
        {
          id: 1169,
          name: 'KITYERERA',
          parishes: [
            {
              id: 5429,
              name: 'BUBINGE',
              villages: [
                { id: 34418, name: 'BUBINGE' },
                { id: 34419, name: 'BULIDHA' },
                { id: 34420, name: 'BUSIMO' },
                { id: 34421, name: 'IGUNDA' },
                { id: 34422, name: 'KIKANDWA' },
              ],
            },
            {
              id: 5427,
              name: 'BUKALENZI',
              villages: [
                { id: 34400, name: 'BUKALENZI' },
                { id: 34401, name: 'BUKOBA  A' },
                { id: 34402, name: "BUKOBA 'B'" },
                { id: 34410, name: 'BUKOBA CENTRAL' },
                { id: 34403, name: 'BUKUKU' },
                { id: 34404, name: "LUTALE 'A'" },
                { id: 34409, name: 'LUTALE D' },
                { id: 34405, name: 'MASHANGA  A' },
                { id: 34406, name: 'MASHANGA  B' },
                { id: 34407, name: 'NAMALERE' },
                { id: 34408, name: 'NGAYAMA' },
              ],
            },
            {
              id: 5428,
              name: 'KITOVU',
              villages: [
                { id: 34411, name: 'KABAGANJA' },
                { id: 34412, name: 'KIKOMA' },
                { id: 34413, name: 'KITOVU' },
                { id: 34414, name: "LUTALE 'B'" },
                { id: 34417, name: 'LUTALE C' },
                { id: 34415, name: 'MITIMITO' },
                { id: 34416, name: 'NTAMBI' },
              ],
            },
            {
              id: 5425,
              name: 'NDAIGA',
              villages: [
                { id: 34386, name: 'BUBALULE A' },
                { id: 34387, name: 'BUBALULE B' },
                { id: 34388, name: 'NAKIRIMIRA A' },
                { id: 34389, name: 'NAKIRIMIRA B' },
                { id: 34393, name: 'NAKIRIMIRA C' },
                { id: 34390, name: 'NDAIGA A' },
                { id: 34391, name: 'NDAIGA B' },
                { id: 34392, name: 'NDAIGA C' },
              ],
            },
            {
              id: 5426,
              name: 'WANDEGEYA',
              villages: [
                { id: 34394, name: 'KATUBA' },
                { id: 34395, name: 'NENDA A' },
                { id: 34399, name: 'NENDA B' },
                { id: 34396, name: 'WAKIWUNGU' },
                { id: 34397, name: 'WANDEGEYA   A' },
                { id: 34398, name: 'WANDEGEYA   B' },
              ],
            },
          ],
        },
        {
          id: 1170,
          name: 'MALONGO',
          parishes: [
            {
              id: 5432,
              name: 'BUKATABIRA',
              villages: [
                { id: 34450, name: 'BUKATABIRA A' },
                { id: 34454, name: 'BUKATABIRA B' },
                { id: 34451, name: 'NKOLONGO' },
                { id: 34453, name: 'NKOLONGO A' },
                { id: 34452, name: 'NKOLONGO B' },
                { id: 34455, name: 'NKOLONGO C' },
              ],
            },
            {
              id: 5433,
              name: 'BULUTA',
              villages: [
                { id: 34456, name: "BUKAGABO 'A' BEACH" },
                { id: 34457, name: "BUKAGABO 'A' VILLAGE" },
                { id: 34458, name: "BUKAGABO 'B' BEACH" },
                { id: 34459, name: "BUKAGABO 'B' VILLAGE" },
                { id: 34465, name: 'BUKAGABO C' },
                { id: 34460, name: 'BULUTA  A' },
                { id: 34466, name: 'BULUTA B' },
                { id: 34464, name: 'BULUTA BULAIRE' },
                { id: 34467, name: 'BULUTA C' },
                { id: 34461, name: 'BULUTA IKOLE' },
                { id: 34462, name: 'BULUTA KITOGO' },
                { id: 34463, name: 'MALINDI' },
              ],
            },
            {
              id: 5435,
              name: 'BUMWENA',
              villages: [
                { id: 34475, name: 'BUGATA' },
                { id: 34477, name: 'BUGOOMA BEACH' },
                { id: 34483, name: 'BULEBI' },
                { id: 34480, name: 'BULUBUDHE' },
                { id: 34484, name: 'BUMWENA A' },
                { id: 34481, name: 'BUMWENA B' },
                { id: 34482, name: 'NAKIGO A' },
                { id: 34476, name: 'NAKIGO B' },
                { id: 34478, name: 'NAMASONKO' },
                { id: 34479, name: 'NAWAMPONGO' },
              ],
            },
            {
              id: 5430,
              name: 'MALONGO',
              villages: [
                { id: 34423, name: 'KABUKA' },
                { id: 34439, name: 'KABUKA BEACH' },
                { id: 34424, name: 'KAYANJA  BEACH' },
                { id: 34425, name: 'KAYANJA  VILLAGE' },
                { id: 34427, name: 'MALONGO  EAST' },
                { id: 34426, name: 'MALONGO A T/C' },
                { id: 34435, name: 'MALONGO B' },
                { id: 34428, name: 'MALONGO B T/C' },
                { id: 34429, name: 'MALONGO C' },
                { id: 34440, name: 'MALONGO CENTRAL' },
                { id: 34430, name: 'MALONGO D' },
                { id: 34434, name: 'MALONGO INN' },
                { id: 34436, name: 'MALONGO NORTH' },
                { id: 34438, name: 'MALONGO UPPER' },
                { id: 34437, name: 'MALONGO WEST' },
                { id: 34431, name: 'MASAKA' },
                { id: 34432, name: 'NANGO  VILLAGE' },
                { id: 34433, name: 'NANGO BEACH' },
              ],
            },
            {
              id: 5431,
              name: 'NAMADHI',
              villages: [
                { id: 34441, name: 'NAMADHI  A' },
                { id: 34442, name: 'NAMADHI  B' },
                { id: 34448, name: 'NAMADHI  BEACH' },
                { id: 34449, name: 'NAMADHI  SOUTH' },
                { id: 34443, name: 'NAMADHI C' },
                { id: 34447, name: 'NAMADHI D' },
                { id: 34444, name: 'NAMADHI T/C' },
                { id: 34445, name: 'NAMAVUNDHU KYONDO' },
                { id: 34446, name: 'NAMAVUNDHU T/C' },
              ],
            },
            {
              id: 5434,
              name: 'NAMONI',
              villages: [
                { id: 34468, name: 'BULUNGU' },
                { id: 34474, name: 'MAGOOLA A' },
                { id: 34469, name: 'MAGOOLA B' },
                { id: 34470, name: "NAMONI 'A'" },
                { id: 34471, name: "NAMONI 'B'" },
                { id: 34472, name: 'NAMONI BEACH' },
                { id: 34473, name: 'WAMALA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 191,
      name: 'BUNYA COUNTY WEST',
      sub_counties: [
        {
          id: 1175,
          name: 'BAITAMBOGWE',
          parishes: [
            {
              id: 5463,
              name: 'BUGODI',
              villages: [
                { id: 34607, name: 'BUGODI A' },
                { id: 34610, name: 'BUGODI B' },
                { id: 34608, name: 'MUSITA  B' },
                { id: 34609, name: 'NAWANGIRI' },
              ],
            },
            {
              id: 5457,
              name: 'BUTTE',
              villages: [
                { id: 34583, name: "BUTE 'A'" },
                { id: 34584, name: "BUTE 'B'" },
                { id: 34585, name: 'NALWESAMBULA  A' },
                { id: 34586, name: 'NALWESAMBULA  B' },
              ],
            },
            {
              id: 5461,
              name: 'IGEYERO',
              villages: [
                { id: 34600, name: 'IGEYERO A' },
                { id: 34603, name: 'IGEYERO B' },
                { id: 34601, name: 'MUKUTA' },
                { id: 34602, name: 'WAGONA' },
              ],
            },
            {
              id: 5458,
              name: 'KATONTE',
              villages: [
                { id: 34587, name: "BUWANGA 'A'" },
                { id: 34588, name: "BUWANGA 'B'" },
                { id: 34589, name: 'KATONTE' },
                { id: 34590, name: 'NAMAGERA' },
              ],
            },
            {
              id: 5459,
              name: 'LUGOLOLE',
              villages: [
                { id: 34591, name: 'BAITAMBOGWE' },
                { id: 34592, name: 'LUGOLOLE B' },
                { id: 34593, name: 'LUGULOLE A' },
                { id: 34594, name: 'MBIRIZI' },
              ],
            },
            {
              id: 5462,
              name: 'LUKONE',
              villages: [
                { id: 34604, name: 'LUKONE' },
                { id: 34605, name: 'MAGAMAGA' },
                { id: 34606, name: 'NSINDA' },
              ],
            },
            {
              id: 5460,
              name: 'MULINGILIRE',
              villages: [
                { id: 34595, name: 'BUBABWE' },
                { id: 34596, name: 'IZINGA' },
                { id: 34597, name: 'MULINGIRIRE' },
                { id: 34598, name: 'MUSITA  A' },
                { id: 34599, name: 'NAMUSENWA' },
              ],
            },
            {
              id: 5464,
              name: 'WAINHA',
              villages: [
                { id: 34612, name: 'NABALONGO A' },
                { id: 34611, name: 'NABALONGO B' },
                { id: 34613, name: "WAINHA 'A'" },
                { id: 34614, name: "WAINHA 'B'" },
              ],
            },
          ],
        },
        {
          id: 1178,
          name: 'BUKATUBE',
          parishes: [
            {
              id: 5477,
              name: 'BUKALEBA',
              villages: [
                { id: 34691, name: 'BUKALEBA' },
                { id: 34692, name: 'NAKALANGA A' },
                { id: 34695, name: 'NAKALANGA B' },
                { id: 34693, name: 'NAMUGONGO' },
                { id: 34694, name: 'WALUMBE BEACH' },
              ],
            },
            {
              id: 5474,
              name: 'BUYEMBA',
              villages: [
                { id: 34663, name: 'BUBALAGALA' },
                { id: 34664, name: 'BUKASERO A' },
                { id: 34665, name: 'BUKASERO B' },
                { id: 34666, name: "BUYEMBA  'A'" },
                { id: 34667, name: "BUYEMBA 'B'" },
                { id: 34668, name: 'LUUBU A' },
                { id: 34670, name: 'LUUBU B' },
                { id: 34671, name: 'MUGERI A' },
                { id: 34669, name: 'MUGERI B' },
              ],
            },
            {
              id: 5475,
              name: 'LWANIKA',
              villages: [
                { id: 34672, name: "BUDHALA 'A'" },
                { id: 34673, name: "BUDHALA 'B'" },
                { id: 34674, name: "BUKATUBE 'A'" },
                { id: 34682, name: 'BUKATUBE B' },
                { id: 34675, name: 'BUTIMBWA' },
                { id: 34684, name: 'BUWOLOMERA' },
                { id: 34676, name: 'KAPALUKO' },
                { id: 34677, name: 'LUKINDU  A' },
                { id: 34678, name: 'LUKINDU  B' },
                { id: 34679, name: 'LWANIKA A' },
                { id: 34685, name: 'LWANIKA B' },
                { id: 34680, name: 'NDHOKERO A' },
                { id: 34683, name: 'NDHOKERO B' },
                { id: 34681, name: 'WAMONDO' },
              ],
            },
            {
              id: 5476,
              name: 'MAUTA',
              villages: [
                { id: 34686, name: 'BUGULUMA' },
                { id: 34687, name: 'BUYOKA' },
                { id: 34688, name: 'KABUKI' },
                { id: 34689, name: 'KYANDO' },
                { id: 34690, name: 'MAUTA' },
              ],
            },
            {
              id: 5478,
              name: 'MBIRABIRA',
              villages: [
                { id: 34696, name: 'BUFUTA A' },
                { id: 34701, name: 'BUFUTA B' },
                { id: 34697, name: 'BUGWANANDALA' },
                { id: 34698, name: 'BUWERERE' },
                { id: 34699, name: 'MASAKA' },
                { id: 34700, name: 'MBIRABIRA' },
              ],
            },
          ],
        },
        {
          id: 1176,
          name: 'IMANYIRO',
          parishes: [
            {
              id: 5469,
              name: 'BUFULUBI',
              villages: [
                { id: 34640, name: 'BUFULUBI  A' },
                { id: 34641, name: 'BUFULUBI  B' },
                { id: 34642, name: 'BUKOMYA' },
                { id: 34646, name: 'BUVUNA' },
                { id: 34643, name: 'KISULE' },
                { id: 34644, name: 'LWABALA' },
                { id: 34645, name: 'NAKIWATA' },
              ],
            },
            {
              id: 5465,
              name: 'MAGADA',
              villages: [
                { id: 34615, name: 'BULYAMPINDI' },
                { id: 34616, name: 'LUYIRA' },
                { id: 34617, name: 'MAGADA' },
                { id: 34618, name: 'NAMADUDU' },
                { id: 34619, name: 'NAMAKAKALE' },
                { id: 34621, name: 'WALUGOGO' },
                { id: 34620, name: 'WANTE' },
              ],
            },
            {
              id: 5466,
              name: 'MAYUGE',
              villages: [
                { id: 34622, name: 'BUDHEBERA' },
                { id: 34623, name: 'BUKAWONGO' },
                { id: 34624, name: 'BWIWULA' },
                { id: 34625, name: 'LUWANULA' },
                { id: 34626, name: 'MATUBA' },
              ],
            },
            {
              id: 5467,
              name: 'MBAALE',
              villages: [
                { id: 34627, name: 'IGUNDA' },
                { id: 34628, name: 'IMANYIRO' },
                { id: 34633, name: 'KAKUNU' },
                { id: 34629, name: 'MAGUNGA' },
                { id: 34630, name: 'MBAALE' },
                { id: 34631, name: 'NAMWOGI' },
                { id: 34632, name: 'WANSWA' },
              ],
            },
            {
              id: 5468,
              name: 'NKOMBE',
              villages: [
                { id: 34634, name: 'KITOVU' },
                { id: 34635, name: 'KYANDAILE' },
                { id: 34636, name: 'LWANDA' },
                { id: 34639, name: 'NAKABALE' },
                { id: 34637, name: "NKOMBE 'A'" },
                { id: 34638, name: "NKOMBE 'B'" },
              ],
            },
          ],
        },
        {
          id: 1180,
          name: 'MAGAMAGA  TOWN COUNCIL',
          parishes: [
            {
              id: 5484,
              name: 'BUKOLI WARD',
              villages: [
                { id: 34723, name: 'BUKOLI  A' },
                { id: 34724, name: 'BUKOLI  B' },
                { id: 34725, name: 'BUKOLI  C' },
                { id: 34726, name: 'MUTUKULA' },
              ],
            },
            {
              id: 5483,
              name: 'MAGAMAGA WARD',
              villages: [
                { id: 34719, name: 'KAWUDHU' },
                { id: 34720, name: 'MAGAMAGA T/C' },
                { id: 34721, name: 'MARKET ZONE' },
                { id: 34722, name: 'TASAGA' },
              ],
            },
            {
              id: 5485,
              name: 'WABULUNGU WARD',
              villages: [
                { id: 34727, name: 'BODA' },
                { id: 34728, name: 'BRIDGE' },
                { id: 34730, name: 'DONGA' },
                { id: 34731, name: 'MUYENGA' },
                { id: 34732, name: 'NAKASERO' },
                { id: 34733, name: 'NAMUFUNA' },
                { id: 34729, name: 'WABULUNGU A' },
              ],
            },
            {
              id: 5486,
              name: 'WANDAGO WARD',
              villages: [
                { id: 34734, name: 'CHURCH OF UGANDA' },
                { id: 34735, name: 'ISIIKO' },
                { id: 34736, name: 'WANDAGO   A' },
                { id: 34737, name: 'WANDAGO  B' },
              ],
            },
          ],
        },
        {
          id: 1177,
          name: 'MAYUGE TOWN COUNCIL',
          parishes: [
            {
              id: 5470,
              name: 'IKULWE WARD',
              villages: [
                { id: 34647, name: 'BUGINGO' },
                { id: 34649, name: 'IGAMBA  B' },
                { id: 34648, name: 'IGAMBA A' },
                { id: 34650, name: 'KATWE' },
                { id: 34651, name: 'TSE-TSE' },
              ],
            },
            {
              id: 5472,
              name: 'KASUGU WARD',
              villages: [
                { id: 34656, name: 'DWALIRO' },
                { id: 34657, name: "KASUGU 'A'" },
                { id: 34658, name: "KASUGU 'B'" },
              ],
            },
            {
              id: 5471,
              name: 'KAVULE WARD',
              villages: [
                { id: 34652, name: 'BUDHEBERA' },
                { id: 34653, name: 'DFI' },
                { id: 34654, name: 'KAVULE' },
                { id: 34655, name: 'MAYUGE  CENTRAL' },
              ],
            },
            {
              id: 5473,
              name: 'KYEBANDO WARD',
              villages: [
                { id: 34659, name: 'KYEBANDO' },
                { id: 34660, name: 'NAKABAFU' },
                { id: 34661, name: 'ST. MULUMBA' },
                { id: 34662, name: 'WAKALENDE' },
              ],
            },
          ],
        },
        {
          id: 1179,
          name: 'WAIRASA',
          parishes: [
            {
              id: 5479,
              name: 'BUSUYI',
              villages: [
                { id: 34702, name: 'BUGABWE' },
                { id: 34706, name: 'BUSOWANIRE' },
                { id: 34703, name: 'BUSUYI' },
                { id: 34704, name: 'BUYEMBA' },
                { id: 34705, name: 'KASITA' },
              ],
            },
            {
              id: 5480,
              name: 'IGULUIBI',
              villages: [
                { id: 34707, name: 'IGULUIBI   A' },
                { id: 34708, name: 'IGULUIBI  B' },
                { id: 34709, name: 'NTOKOLO' },
                { id: 34710, name: 'WAIBALE' },
              ],
            },
            {
              id: 5482,
              name: 'MISOLI',
              villages: [
                { id: 34714, name: 'BUSALAMU' },
                { id: 34715, name: 'MISOOLI  VILLAGE' },
                { id: 34716, name: 'MISOOLI BEACH' },
                { id: 34717, name: 'MISOOLI TRADING CENTRE' },
                { id: 34718, name: 'NTINKALU' },
              ],
            },
            {
              id: 5481,
              name: 'WANDAGO',
              villages: [
                { id: 34713, name: 'BUWANGA/LUGWARA QTRS' },
                { id: 34711, name: 'NAMALERE' },
                { id: 34712, name: 'WAIRASA' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
