import { District } from '../index';

export default {
  id: 55,
  name: 'MBALE',
  counties: [
    {
      id: 124,
      name: 'BUNGOKHO COUNTY NORTH',
      sub_counties: [
        {
          id: 772,
          name: 'BUBYANGU',
          parishes: [
            {
              id: 3566,
              name: 'BUBYANGU',
              villages: [
                { id: 22660, name: 'BIBOTO' },
                { id: 22657, name: 'BUBYANGU UPPER' },
                { id: 22658, name: 'BUNALUTERE' },
                { id: 22659, name: 'BUNAWOZI UPPER' },
                { id: 22662, name: 'KIKOBERO' },
                { id: 22661, name: 'MUBALAGAYE' },
                { id: 22663, name: 'WAMBEWO TOWNSHIP' },
              ],
            },
            {
              id: 3569,
              name: 'BUKIKOSO',
              villages: [
                { id: 22674, name: 'BUKIKOSO' },
                { id: 22677, name: 'BUNAKOFA' },
                { id: 22673, name: 'BUNANDUDU' },
                { id: 22675, name: 'BUWANDYERO' },
                { id: 22678, name: 'KALUBI' },
                { id: 22679, name: 'KIYENGA' },
                { id: 22676, name: 'LWASINZI' },
                { id: 22680, name: 'MAYIIRA' },
              ],
            },
            {
              id: 3568,
              name: 'BUMADANDA',
              villages: [
                { id: 22671, name: 'BUKUBA' },
                { id: 22669, name: "BUKWAGA  'B'" },
                { id: 22668, name: 'BUMADANDA' },
                { id: 22670, name: 'KITUMBA' },
                { id: 22672, name: 'MUNANU' },
              ],
            },
            {
              id: 3570,
              name: 'BUNABIGUBO',
              villages: [
                { id: 22681, name: 'BUNABIGUBO LOWER' },
                { id: 22682, name: 'BUNABIGUBO UPPER' },
                { id: 22683, name: 'KIKAMERI' },
                { id: 22684, name: 'LUKONJE' },
                { id: 22685, name: 'MADIRI' },
              ],
            },
            {
              id: 3571,
              name: 'BUNABULOLI',
              villages: [
                { id: 22689, name: 'BUNABULOLI  LOWER' },
                { id: 22690, name: 'BUNABULOLI  UPPER' },
                { id: 22688, name: 'BUNANDUDU' },
                { id: 22691, name: 'BUNANGALAMA' },
                { id: 22687, name: 'MAKUYU' },
                { id: 22692, name: 'MAKYESE TOWNSHIP' },
                { id: 22686, name: 'MASABA' },
              ],
            },
            {
              id: 3572,
              name: 'BUNAMOLI',
              villages: [
                { id: 22693, name: 'BUMASIFA' },
                { id: 22694, name: 'BUNAMOLI' },
                { id: 22695, name: 'MAJENGA' },
                { id: 22696, name: 'NAMAKOLO' },
              ],
            },
            {
              id: 3573,
              name: 'BUNAWOZI',
              villages: [
                { id: 22697, name: "BUKWAGA 'A'" },
                { id: 22698, name: 'BUNAWOZI LOWER' },
                { id: 22699, name: 'KIYANZA' },
                { id: 22700, name: 'MAGO' },
                { id: 22701, name: 'MAJENYA' },
              ],
            },
            {
              id: 3567,
              name: 'KILAYI',
              villages: [
                { id: 22666, name: 'BUMOTEKA' },
                { id: 22664, name: 'BUMUDULI' },
                { id: 22665, name: 'KIRAYI' },
                { id: 22667, name: 'WANASWA' },
              ],
            },
            {
              id: 3574,
              name: 'LUSAMENTA',
              villages: [
                { id: 22702, name: 'BUKWANA LOWER' },
                { id: 22703, name: 'BUKWANA UPPER' },
                { id: 22704, name: 'BUMBOWA' },
                { id: 22705, name: 'GUMU' },
                { id: 22706, name: 'LUSAMENTA' },
                { id: 22707, name: 'NABIRINDA' },
              ],
            },
            {
              id: 3575,
              name: 'MADEGE',
              villages: [
                { id: 22709, name: 'BUBYANGU LOWER' },
                { id: 22712, name: 'BUFIIGI' },
                { id: 22708, name: 'KANASA' },
                { id: 22710, name: 'MADENGE' },
                { id: 22713, name: 'MAYENZE' },
                { id: 22711, name: 'NKUNGU' },
              ],
            },
          ],
        },
        {
          id: 773,
          name: 'BUDWALE',
          parishes: [
            {
              id: 3576,
              name: 'BUDWALE',
              villages: [
                { id: 22717, name: 'BUGEMA' },
                { id: 22714, name: 'BUNAMUNDUMBULI' },
                { id: 22715, name: 'BUWANYANGA' },
                { id: 22718, name: 'KIDIDIKIRO' },
                { id: 22719, name: 'LWABUSO' },
                { id: 22716, name: 'MAWA' },
              ],
            },
            {
              id: 3577,
              name: 'BUKINGALA',
              villages: [
                { id: 22720, name: 'BUKINGALA' },
                { id: 22721, name: 'KIDDE' },
                { id: 22723, name: 'MALAGA' },
                { id: 22722, name: 'NSAALO' },
              ],
            },
            {
              id: 3578,
              name: 'BUNAMAHE',
              villages: [
                { id: 22724, name: 'BUKUMI' },
                { id: 22725, name: 'BUNAMAHE' },
                { id: 22729, name: 'KIDOBO' },
                { id: 22730, name: 'KIGEZI' },
                { id: 22726, name: 'KYESULA' },
                { id: 22727, name: 'LWASOHE' },
                { id: 22728, name: 'MAYIYI' },
              ],
            },
            {
              id: 3579,
              name: 'BUWANAGADI',
              villages: [
                { id: 22731, name: 'BIDUWA' },
                { id: 22732, name: 'BUNABUSOBA' },
                { id: 22733, name: 'BUWANANGADI' },
                { id: 22734, name: 'MULINA' },
                { id: 22736, name: 'NALUKAYAZA' },
                { id: 22735, name: 'TUMBI' },
              ],
            },
          ],
        },
        {
          id: 767,
          name: 'BUFUMBO',
          parishes: [
            {
              id: 3545,
              name: 'BUKOBE',
              villages: [
                { id: 22456, name: 'BUKOBE  LOWER' },
                { id: 22457, name: 'BUKOBE  UPPER' },
                { id: 22458, name: 'KYAPE' },
                { id: 22459, name: 'NALUWERERE TOWNSHIP' },
              ],
            },
            {
              id: 3546,
              name: 'BUMAGIRA',
              villages: [
                { id: 22461, name: 'BUMAGIRA' },
                { id: 22462, name: 'LULANGASA' },
                { id: 22460, name: 'MABOOLO' },
                { id: 22466, name: 'MULUKA TOWNSHIP' },
                { id: 22463, name: 'NABUSHERO' },
                { id: 22465, name: 'RWADEBE' },
                { id: 22464, name: 'RWANDA' },
              ],
            },
            {
              id: 3547,
              name: 'BUMUSIRI',
              villages: [
                { id: 22468, name: 'BUMUSIRI' },
                { id: 22470, name: 'ITALE' },
                { id: 22471, name: 'KIBEMBE' },
                { id: 22473, name: 'LUFUNGA' },
                { id: 22469, name: 'LWASABUBI' },
                { id: 22472, name: 'MAYENZE' },
                { id: 22467, name: 'NEEMBA' },
              ],
            },
            {
              id: 3548,
              name: 'BUNAMAJJE',
              villages: [
                { id: 22474, name: 'BUNAMAJJE' },
                { id: 22476, name: 'BUZALANGIZO LOWER' },
                { id: 22475, name: 'KIBEMBE' },
                { id: 22477, name: 'LUSISI' },
              ],
            },
            {
              id: 3549,
              name: 'BUZALANGIZO',
              villages: [
                { id: 22480, name: 'BUGWERI' },
                { id: 22478, name: 'BUZALANGIZO UPPER' },
                { id: 22479, name: 'NABOODI' },
              ],
            },
            {
              id: 3544,
              name: 'KAMA',
              villages: [
                { id: 22454, name: 'BUMAGAWA' },
                { id: 22450, name: 'KAMA  LOWER' },
                { id: 22451, name: 'KAMA  TOWNSHIP' },
                { id: 22452, name: 'KAMA  UPPER' },
                { id: 22453, name: 'KIKONYERO' },
                { id: 22455, name: 'MALUKU' },
              ],
            },
          ],
        },
        {
          id: 768,
          name: 'BUKONDE',
          parishes: [
            {
              id: 3550,
              name: 'BULWETA',
              villages: [
                { id: 22481, name: 'BULWETA A' },
                { id: 22489, name: 'BULWETA B' },
                { id: 22482, name: 'BUMALUNDA' },
                { id: 22494, name: 'BUSAHE' },
                { id: 22483, name: 'BUWAMWANGU' },
                { id: 22488, name: 'BUWAMWANGU T.C' },
                { id: 22498, name: 'IBANDA' },
                { id: 22497, name: 'KIBUDI' },
                { id: 22499, name: 'KIDABAGO' },
                { id: 22490, name: 'KIDUMI' },
                { id: 22484, name: 'KIFULULIRO' },
                { id: 22485, name: 'KIWILA' },
                { id: 22495, name: 'LUSULULA' },
                { id: 22487, name: 'MAGANGA' },
                { id: 22486, name: 'MAHALWE' },
                { id: 22500, name: 'MAHOOTA' },
                { id: 22501, name: 'MAHUWA' },
                { id: 22502, name: 'MAYIYI' },
                { id: 22493, name: 'MPIGWE' },
                { id: 22503, name: 'MULUNDU' },
                { id: 22492, name: 'MUSOOLA' },
                { id: 22504, name: 'NABUKALISHA LOWER' },
                { id: 22505, name: 'NABUKALISHA UPPER' },
                { id: 22506, name: 'NAGWERE' },
                { id: 22507, name: 'NAHANDO' },
                { id: 22508, name: 'NAKINAWA' },
                { id: 22509, name: 'NAMASANZA' },
                { id: 22510, name: 'NAMBALE' },
                { id: 22511, name: 'NAMUHONDO' },
                { id: 22491, name: 'NAMWANI' },
                { id: 22496, name: 'NANYILA' },
              ],
            },
            {
              id: 3551,
              name: 'BUMULUYA',
              villages: [
                { id: 22512, name: 'BUMULUYA MAIN' },
                { id: 22513, name: 'BUMULUYA UPPER' },
                { id: 22515, name: 'BUWACHI A' },
                { id: 22526, name: 'GIZOMBE' },
                { id: 22514, name: 'IKOKO' },
                { id: 22523, name: 'KIDUWA' },
                { id: 22516, name: 'KILAGALA' },
                { id: 22519, name: 'KIYANZA' },
                { id: 22525, name: 'MACHELE' },
                { id: 22518, name: 'MAKUYU' },
                { id: 22522, name: 'MATALE T.C' },
                { id: 22521, name: 'MATUNGULU' },
                { id: 22517, name: 'MUSIITU' },
                { id: 22524, name: 'NABIRINDA' },
                { id: 22520, name: 'NAMUGOBERA' },
              ],
            },
            {
              id: 3552,
              name: 'BUMUYANGA',
              villages: [
                { id: 22527, name: 'BUMUSAMALI' },
                { id: 22529, name: 'BUMUYAGA' },
                { id: 22533, name: 'BUMUYAGA UPPER' },
                { id: 22531, name: 'BUWAKI B' },
                { id: 22536, name: 'LUGONGO' },
                { id: 22532, name: 'LUKHOBE' },
                { id: 22538, name: 'MASABA' },
                { id: 22535, name: 'MUFUDU DISPENSARY' },
                { id: 22537, name: 'MUTUMBA' },
                { id: 22528, name: 'NABWAMI' },
                { id: 22530, name: 'NAGULUNGULU' },
                { id: 22534, name: 'WEBUTA TOWNSHIP' },
              ],
            },
            {
              id: 3553,
              name: 'NANYUNZA',
              villages: [
                { id: 22539, name: 'ITUGUTU' },
                { id: 22546, name: 'KIKONDO' },
                { id: 22545, name: 'LUSAALA' },
                { id: 22543, name: 'MAKOSI' },
                { id: 22540, name: 'MASEGESE' },
                { id: 22541, name: 'NAKITOKOLO' },
                { id: 22544, name: 'NANYUNZA' },
                { id: 22542, name: 'SAGIYA' },
              ],
            },
          ],
        },
        {
          id: 777,
          name: 'JEWA TOWN COUNCIL',
          parishes: [
            {
              id: 3596,
              name: 'JEWA WARD',
              villages: [
                { id: 22812, name: 'JEWA LOWER' },
                { id: 22813, name: 'JEWA TOWNSHIP A' },
                { id: 22814, name: 'JEWA TOWNSHIP B' },
                { id: 22815, name: 'NABINI' },
              ],
            },
            {
              id: 3597,
              name: 'KITAGALU WARD',
              villages: [
                { id: 22817, name: 'BUKABALYENDA' },
                { id: 22818, name: 'KITAGALU' },
                { id: 22816, name: 'MADUWA' },
              ],
            },
            {
              id: 3598,
              name: 'NAKYANIKILE WARD',
              villages: [
                { id: 22819, name: 'DOHOLO' },
                { id: 22821, name: 'NAKYANIKIRE' },
                { id: 22820, name: 'NKUSI' },
              ],
            },
            {
              id: 3599,
              name: 'NALUMOYA WARD',
              villages: [
                { id: 22822, name: 'JEWA UPPER' },
                { id: 22824, name: 'MABOLO' },
                { id: 22825, name: 'MUJINI' },
                { id: 22823, name: 'NALUMOYA' },
              ],
            },
            {
              id: 3600,
              name: 'NDOKO WARD',
              villages: [
                { id: 22826, name: 'MADODO' },
                { id: 67683, name: 'NDOKO' },
                { id: 22827, name: 'NDOKO LOWER' },
              ],
            },
          ],
        },
        {
          id: 774,
          name: 'LWASSO',
          parishes: [
            {
              id: 3581,
              name: 'BUKIKALI',
              villages: [
                { id: 22751, name: 'BUKIKALI CENTRAL' },
                { id: 22744, name: 'KATALE' },
                { id: 22745, name: 'KILONGO' },
                { id: 22748, name: 'KILONGO UPPER' },
                { id: 22746, name: 'KYAMUGUNGU' },
                { id: 22747, name: 'LWANDERA' },
                { id: 22749, name: 'NAGOBONGOBO' },
                { id: 22750, name: 'NANZEGO' },
              ],
            },
            {
              id: 3582,
              name: 'BUWANGOLO',
              villages: [
                { id: 22755, name: 'BUKISYELO' },
                { id: 22756, name: 'BUMADI' },
                { id: 22752, name: 'BUWANGOLO' },
                { id: 22753, name: 'INTEBE' },
                { id: 22757, name: 'NAMAKYESE' },
                { id: 22754, name: 'NAMULAMA' },
              ],
            },
            {
              id: 3583,
              name: 'KIHUNO',
              villages: [
                { id: 22759, name: 'KIBAGALA' },
                { id: 22763, name: 'KITUTI' },
                { id: 22762, name: 'KYAKYOYA' },
                { id: 22758, name: 'NABULOHO' },
                { id: 22760, name: 'NAFULYUNGU' },
                { id: 22761, name: 'NAMAZABA' },
              ],
            },
            {
              id: 3580,
              name: 'LWASSO',
              villages: [
                { id: 22741, name: 'BALEGALI' },
                { id: 22737, name: 'BUKIMUGA' },
                { id: 22739, name: 'MAGADA' },
                { id: 22738, name: 'MAKUYU' },
                { id: 22740, name: 'MASIWE' },
                { id: 22742, name: 'MASIWE LOWER' },
                { id: 22743, name: 'MUTUBA' },
              ],
            },
          ],
        },
        {
          id: 769,
          name: 'NAKALOKE',
          parishes: [
            {
              id: 3555,
              name: 'KIREKA',
              villages: [
                { id: 22551, name: 'KADEBEDDE LOWER' },
                { id: 22552, name: 'KADEBEDDE UPPER' },
              ],
            },
            {
              id: 3556,
              name: 'NAMBULU/KASANJA',
              villages: [
                { id: 22555, name: 'DOKO I' },
                { id: 22556, name: 'DOKO II' },
                { id: 22553, name: 'KASANJA A' },
                { id: 22557, name: 'KASANJA B' },
                { id: 22554, name: 'NAMBULU' },
                { id: 22558, name: 'NSEREKO' },
                { id: 22559, name: 'WANAGOLI' },
              ],
            },
            {
              id: 3554,
              name: 'NAMUNSI',
              villages: [
                { id: 22547, name: 'DOCTOR GESA' },
                { id: 22548, name: 'NTATE' },
                { id: 22549, name: 'WABOBOLA' },
                { id: 22550, name: 'WABUSIMBA' },
              ],
            },
          ],
        },
        {
          id: 775,
          name: 'NAKALOKE TOWN COUNCIL',
          parishes: [
            {
              id: 3584,
              name: 'AFYA WARD',
              villages: [
                { id: 22766, name: 'AFYA' },
                { id: 22764, name: 'BUSAJA-BWAKUBA A' },
                { id: 22769, name: 'BUSAJJA-BWANKUBA B' },
                { id: 22767, name: 'KABOGGOZA' },
                { id: 22768, name: 'KAWANGA' },
                { id: 22765, name: 'NAKALOKE III' },
              ],
            },
            {
              id: 3585,
              name: 'FIKA SALAMA WARD',
              villages: [
                { id: 22771, name: 'KIREKA MAILO VI' },
                { id: 22772, name: 'MULINDWA' },
                { id: 22773, name: 'SAJJABI' },
                { id: 22770, name: 'WABOMBA' },
              ],
            },
            {
              id: 3590,
              name: 'KIREKA WARD',
              villages: [
                { id: 22792, name: 'BYABATO' },
                { id: 22791, name: 'KAGWA' },
                { id: 22790, name: 'KIREKA CENTRAL' },
              ],
            },
            {
              id: 3589,
              name: 'MUKUNJA WARD',
              villages: [
                { id: 22788, name: 'MUKUNJA' },
                { id: 22789, name: 'MUWEREZA' },
                { id: 22787, name: 'NAMUNSI CENTRAL' },
              ],
            },
            {
              id: 3586,
              name: 'NAJJA WARD',
              villages: [
                { id: 22774, name: 'KAZIBWE' },
                { id: 22775, name: 'NAKALOKE II LOWER' },
                { id: 22776, name: 'NAKALOKE II UPPER' },
                { id: 22777, name: 'NAMIGALO' },
              ],
            },
            {
              id: 3587,
              name: 'NAKALOKE WARD',
              villages: [
                { id: 22779, name: 'ENTEBBE ROAD' },
                { id: 22781, name: 'MUTUBA' },
                { id: 22780, name: 'NABITENDE' },
                { id: 22778, name: 'NAKALOKE I' },
              ],
            },
            {
              id: 3588,
              name: 'ROCK WARD',
              villages: [
                { id: 22782, name: 'NAKALOKE CENTRAL' },
                { id: 22786, name: 'NAMABASA II LOWER' },
                { id: 22783, name: 'NAMABASA II UPPER' },
                { id: 22784, name: 'NANDALA A' },
                { id: 22785, name: 'NANDALA B' },
              ],
            },
          ],
        },
        {
          id: 776,
          name: 'NAMABASA',
          parishes: [
            {
              id: 3592,
              name: 'BWANA',
              villages: [
                { id: 22798, name: 'BWANA' },
                { id: 62281, name: 'KALAGALA' },
                { id: 22799, name: 'KOLONYI  II UPPER' },
                { id: 22800, name: 'KOLONYI II LOWER' },
              ],
            },
            {
              id: 3593,
              name: 'DOKO',
              villages: [
                { id: 22801, name: 'DOKO ZONE' },
                { id: 22803, name: 'KIBUMBIRE' },
                { id: 22804, name: 'NAMABASA CENTRAL III' },
                { id: 22802, name: 'NAMABASA III A' },
              ],
            },
            {
              id: 3594,
              name: 'KOLONYI',
              villages: [
                { id: 22805, name: 'KOLONYI  I' },
                { id: 22806, name: 'KOLONYI CENTRAL' },
                { id: 22807, name: 'KOLONYI FARM' },
              ],
            },
            {
              id: 3591,
              name: 'NAMABASA',
              villages: [
                { id: 22793, name: 'NAMABASA IV' },
                { id: 22796, name: 'NAMABASA IV LOWER' },
                { id: 22795, name: 'NAMABASA IV UPPER' },
                { id: 22794, name: 'NAMABASA V A' },
                { id: 22797, name: 'NAMABASA V B' },
              ],
            },
            {
              id: 3595,
              name: 'SALEM',
              villages: [
                { id: 22810, name: 'NAMABASA I LOWER' },
                { id: 22809, name: 'NAMABASA I UPPER' },
                { id: 22808, name: 'SALEM A' },
                { id: 22811, name: 'SALEM B' },
              ],
            },
          ],
        },
        {
          id: 770,
          name: 'NAMANYONYI',
          parishes: [
            {
              id: 3557,
              name: 'AISA',
              villages: [
                { id: 22560, name: 'AISA TEKO' },
                { id: 22569, name: 'AISA-TEKO UPPER' },
                { id: 22561, name: 'MASANDA A' },
                { id: 22568, name: 'MASANDA B' },
                { id: 22562, name: 'MBIKO A' },
                { id: 22566, name: 'MBIKO B' },
                { id: 22571, name: 'MUWONZA' },
                { id: 22567, name: 'NAKIGALO' },
                { id: 22563, name: 'NAMABWA' },
                { id: 22565, name: 'NANGOLO' },
                { id: 22564, name: 'NANKUSI' },
                { id: 22570, name: 'UTC ELGON' },
                { id: 22572, name: 'UTC ELGON CENTRAL' },
              ],
            },
            {
              id: 3558,
              name: 'NABWEYA',
              villages: [
                { id: 22579, name: 'BUDI A' },
                { id: 22574, name: 'BUGEMBE' },
                { id: 22573, name: 'KASANVU' },
                { id: 22576, name: 'KILULU A' },
                { id: 22582, name: 'KILULU B' },
                { id: 22580, name: 'LUMUMBA' },
                { id: 22577, name: 'MAKUDUYI' },
                { id: 22578, name: 'NABUGOYE A' },
                { id: 22583, name: 'NABUGOYE B' },
                { id: 22575, name: 'NABWEYA TOP' },
                { id: 22584, name: 'NANKOBE' },
                { id: 22581, name: 'WANYANGA' },
              ],
            },
            {
              id: 3560,
              name: 'NAMAGUMBA',
              villages: [
                { id: 22606, name: 'BUNGULYA' },
                { id: 22598, name: 'BUSAMIRA' },
                { id: 22603, name: 'BUSAMIRA UPPER' },
                { id: 22599, name: 'KIFAFA LOWER' },
                { id: 22604, name: 'KIFAFA UPPER' },
                { id: 22600, name: 'NAMAGUMBA A' },
                { id: 22602, name: 'NAMAGUMBA B' },
                { id: 22605, name: 'NAMAKOLE' },
                { id: 22608, name: 'NAMAWONDO' },
                { id: 22601, name: 'NAMENGO' },
                { id: 22607, name: 'NANYURU' },
              ],
            },
            {
              id: 3559,
              name: 'NKOMA',
              villages: [
                { id: 22596, name: 'BUDI B' },
                { id: 22586, name: 'KANIKWA A' },
                { id: 22597, name: 'KANIKWA B' },
                { id: 22587, name: 'KINYOLI A' },
                { id: 22593, name: 'KINYOLI B' },
                { id: 22594, name: 'NABUNYIRI' },
                { id: 22588, name: 'NAMANYONYI CENTRE A' },
                { id: 22592, name: 'NAMANYONYI CENTRE B' },
                { id: 22595, name: 'NAMATALA ZONE' },
                { id: 22585, name: 'NANSU' },
                { id: 22589, name: 'NDEEGA' },
                { id: 22590, name: 'NKOMA CENTRE A' },
                { id: 22591, name: 'NKOMA CENTRE B' },
              ],
            },
          ],
        },
        {
          id: 771,
          name: 'WANALE',
          parishes: [
            {
              id: 3561,
              name: 'BUBETSYE',
              villages: [
                { id: 22609, name: 'BUBIRABI LOWER' },
                { id: 22617, name: 'BUKHATOGO' },
                { id: 22618, name: 'BUKHOOBA' },
                { id: 22612, name: 'BUNABUBULO LOWER' },
                { id: 22613, name: 'BUNABUBULO UPPER' },
                { id: 22616, name: 'NABURWA' },
                { id: 22619, name: 'NDOKHWE' },
                { id: 22615, name: 'SHANYUNYI' },
                { id: 22620, name: 'SHIKULU' },
                { id: 22621, name: 'SHILONGO' },
                { id: 22610, name: 'SHITELEMA' },
                { id: 22611, name: 'SUBAALI' },
                { id: 22614, name: 'WEPILYA' },
              ],
            },
            {
              id: 3563,
              name: 'BUNATSOMA',
              villages: [
                { id: 22634, name: 'BUNATSOMA  LOWER' },
                { id: 22635, name: 'BUNATSOMA UPPER' },
                { id: 22636, name: 'BUWASU A' },
                { id: 22638, name: 'BUWASU B' },
                { id: 22639, name: 'KHALANDA' },
                { id: 22637, name: 'LWANGASA' },
                { id: 22641, name: 'NASUSI' },
                { id: 22642, name: 'NKWASI' },
                { id: 22632, name: 'SAADI' },
                { id: 22633, name: 'WADINDYA' },
                { id: 22640, name: 'WAHORA' },
              ],
            },
            {
              id: 3562,
              name: 'BUSHIUYO',
              villages: [
                { id: 22622, name: 'BUGHAHEME' },
                { id: 22625, name: 'BUNANDUTU' },
                { id: 22627, name: 'BUSHIUYO' },
                { id: 22630, name: 'BUSHIUYO UPPER' },
                { id: 22628, name: 'KIDEGA' },
                { id: 22623, name: 'MAJENGA' },
                { id: 22631, name: 'MUJINI' },
                { id: 22629, name: 'NALUBANDELA' },
                { id: 22624, name: 'NASONGO' },
                { id: 22626, name: 'WEBELI' },
              ],
            },
            {
              id: 3564,
              name: 'KHAUKHA',
              villages: [
                { id: 22644, name: 'BUBIRABI UPPER' },
                { id: 22645, name: 'BUFOOTO' },
                { id: 22643, name: 'BUMATSOTI' },
                { id: 22646, name: 'LUGAGA' },
                { id: 22647, name: 'LUSYERA' },
                { id: 22648, name: 'MAKHUMA' },
                { id: 22649, name: 'NAMAJJE' },
                { id: 22650, name: 'NKONGOLO' },
              ],
            },
            {
              id: 3565,
              name: 'NABANYOLE',
              villages: [
                { id: 22654, name: 'BUKHAMOLI A' },
                { id: 22655, name: 'BUKHAMOLI B' },
                { id: 22651, name: 'BUKHANAKWA' },
                { id: 22652, name: 'BUNABWIIRE' },
                { id: 22653, name: 'BUNAMONDO' },
                { id: 22656, name: 'BUSOBA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 125,
      name: 'BUNGOKHO COUNTY SOUTH',
      sub_counties: [
        {
          id: 784,
          name: 'BUKASAKYA',
          parishes: [
            {
              id: 3633,
              name: 'DOKO',
              villages: [
                { id: 23081, name: 'CENTRE' },
                { id: 23082, name: 'DOKO NSAMBYA' },
                { id: 23083, name: 'MOSQUE' },
                { id: 23084, name: 'SALUTE' },
              ],
            },
            {
              id: 3634,
              name: 'MARALE',
              villages: [
                { id: 23086, name: 'BUGEMA  B' },
                { id: 23085, name: 'KISENYI' },
                { id: 23088, name: 'MARALE' },
                { id: 23087, name: 'NANSINGE' },
              ],
            },
            {
              id: 3635,
              name: 'NABITIRI',
              villages: [
                { id: 23094, name: 'GREEN PASTURE' },
                { id: 23089, name: 'MAKHUMBO' },
                { id: 23091, name: 'MASANDA' },
                { id: 23092, name: 'MUSOTO' },
                { id: 23090, name: 'NABITIRI' },
                { id: 23093, name: 'NAKIBISO' },
              ],
            },
            {
              id: 3632,
              name: 'TSABANYANYA',
              villages: [
                { id: 23075, name: 'BUGEMA C' },
                { id: 23076, name: 'KIBINIKO' },
                { id: 23078, name: 'MASABA' },
                { id: 23079, name: 'NASHISA' },
                { id: 23080, name: 'TSABANYANYA' },
                { id: 23077, name: 'WANGITO' },
              ],
            },
          ],
        },
        {
          id: 778,
          name: 'BUKHIENDE',
          parishes: [
            {
              id: 3604,
              name: 'BUGWANYI',
              villages: [
                { id: 22863, name: 'BUMALIRO' },
                { id: 22864, name: 'BUYAKA  A' },
                { id: 22865, name: 'BUYAKA  B' },
                { id: 22866, name: 'NAMIKYERO' },
                { id: 22867, name: 'SHAALA' },
                { id: 22868, name: 'SHIKUNDU' },
              ],
            },
            {
              id: 3605,
              name: 'BUMAENA',
              villages: [
                { id: 22870, name: 'BUMAENA' },
                { id: 22871, name: 'MAUSI' },
                { id: 22872, name: 'MULATSI' },
                { id: 22873, name: 'NABIKHOSO A' },
                { id: 22869, name: 'NABIKHOSO B' },
              ],
            },
            {
              id: 3601,
              name: 'BUMUTSOPA',
              villages: [
                { id: 22828, name: 'BUKHAKOSI' },
                { id: 22830, name: 'BUKHATELEMA' },
                { id: 22835, name: 'BUKHONE' },
                { id: 22829, name: 'BUMAKIKA' },
                { id: 22831, name: 'BUTSESOOLI' },
                { id: 22836, name: 'BUWANGWIRI' },
                { id: 22832, name: 'LUTEMBETE' },
                { id: 22837, name: 'MAAKA' },
                { id: 22838, name: 'NALONDO' },
                { id: 22833, name: 'NASASA' },
                { id: 22839, name: 'NASHILULU' },
                { id: 22840, name: 'NATSEKOO' },
                { id: 22834, name: 'WAPONDO' },
              ],
            },
            {
              id: 3602,
              name: 'BUNASHIMOLO',
              villages: [
                { id: 22841, name: 'BUKHABOYO LOWER' },
                { id: 22842, name: 'BUKHABOYO UPPER' },
                { id: 22845, name: 'BUNAMALIRO A' },
                { id: 22846, name: 'BUNAMALIRO B' },
                { id: 22847, name: 'BWIKHONJE' },
                { id: 22848, name: 'LUSAFU' },
                { id: 22843, name: 'LUSISI' },
                { id: 22844, name: 'NAMALA' },
                { id: 22849, name: 'RONGORO' },
              ],
            },
            {
              id: 3603,
              name: 'BURUKURU',
              villages: [
                { id: 22850, name: 'BUMABALA' },
                { id: 22851, name: 'BUMWAMBU' },
                { id: 22852, name: 'BUNABULAYI  A' },
                { id: 22853, name: 'BUNABULAYI  B' },
                { id: 22854, name: 'BUNAMONO' },
                { id: 22855, name: 'BUNANGAKA' },
                { id: 22856, name: 'BUNATSABWANA' },
                { id: 22857, name: 'LUBOOLO' },
                { id: 22858, name: 'MATSANZA' },
                { id: 22859, name: 'MUFURA' },
                { id: 22860, name: 'MUKARI' },
                { id: 22861, name: 'NANGOLO' },
                { id: 22862, name: 'NASINJE' },
              ],
            },
            {
              id: 3606,
              name: 'BUSHANGI',
              villages: [
                { id: 22875, name: 'BUNALWELE A' },
                { id: 22876, name: 'BUSHANGI A' },
                { id: 22874, name: 'BUSHANGI B' },
                { id: 22877, name: 'BWIKHASA' },
                { id: 22878, name: 'KITINDYA' },
                { id: 22879, name: 'NAMAMA' },
              ],
            },
            {
              id: 3607,
              name: 'ISANGO',
              villages: [
                { id: 22881, name: 'BUNALWELE  B' },
                { id: 22882, name: 'IKYENGA' },
                { id: 22883, name: 'KYEMULA' },
                { id: 22884, name: 'SHIKOYE' },
                { id: 22880, name: 'SHIYATSA' },
              ],
            },
          ],
        },
        {
          id: 785,
          name: 'BUMASIKYE',
          parishes: [
            {
              id: 3636,
              name: 'LUBAALE',
              villages: [
                { id: 23097, name: 'BUFUKHULA' },
                { id: 23095, name: 'BUTSABI' },
                { id: 23098, name: 'BUWUMBA' },
                { id: 23096, name: 'LUBAALE' },
                { id: 23099, name: 'MAKUNDA' },
                { id: 23100, name: 'NAMUKHURA' },
              ],
            },
            {
              id: 3637,
              name: 'LWABOBA',
              villages: [
                { id: 23102, name: 'LWABOBA LOWER' },
                { id: 23109, name: 'LWABOBA T.C' },
                { id: 23101, name: 'LWABOBA UPPER' },
                { id: 23103, name: 'MAKHONJE' },
                { id: 23104, name: 'NANGIRIMA  LOWER' },
                { id: 23105, name: 'NANGIRIMA  UPPER' },
                { id: 23106, name: 'WABUTEYA' },
                { id: 23107, name: 'WOKUKIRI' },
                { id: 23110, name: 'WOKUKIRI LOWER' },
                { id: 23108, name: 'WOKUKIRI UPPER' },
              ],
            },
            {
              id: 3638,
              name: 'MUANDA',
              villages: [
                { id: 23116, name: 'BUMANYE' },
                { id: 23111, name: 'KIMWANGA' },
                { id: 23112, name: 'MUANDA' },
                { id: 23113, name: 'NABUYAKA' },
                { id: 23114, name: 'NAMALOKO' },
                { id: 23115, name: 'NAMWENULA' },
                { id: 23118, name: 'NASHITOKHOLO' },
                { id: 23117, name: 'WASEKESE' },
              ],
            },
            {
              id: 3639,
              name: 'TOMA',
              villages: [
                { id: 23119, name: 'BUKAYA' },
                { id: 23123, name: 'BULANDU' },
                { id: 23122, name: 'LUKOBA' },
                { id: 23125, name: 'MUNYU' },
                { id: 23120, name: 'RAASA' },
                { id: 23121, name: 'TOMA' },
                { id: 23124, name: 'TOMA LOWER' },
                { id: 23126, name: 'WANDEKA' },
              ],
            },
          ],
        },
        {
          id: 788,
          name: 'BUMBOBI',
          parishes: [
            {
              id: 3650,
              name: 'BUFUYA',
              villages: [
                { id: 23198, name: 'MAKHU' },
                { id: 23199, name: 'MARARE' },
                { id: 23200, name: 'SHILOMBE' },
                { id: 23197, name: 'SHIRAKARU' },
                { id: 23201, name: 'SHISINYO' },
                { id: 23202, name: 'SHIYATSA' },
              ],
            },
            {
              id: 3649,
              name: 'BUKHUMWA',
              villages: [
                { id: 23192, name: 'BUMALEMA' },
                { id: 23193, name: 'BUMASULE' },
                { id: 23194, name: 'MAFUTU' },
                { id: 23195, name: 'NAMUNYU' },
                { id: 23196, name: 'WABUKHASA' },
              ],
            },
            {
              id: 3648,
              name: 'BUMBOBI',
              villages: [
                { id: 23184, name: 'BUKHUMEKA I' },
                { id: 23185, name: 'BUKHUMEKA II' },
                { id: 23186, name: 'LUKKI' },
                { id: 23187, name: 'MASALIRE' },
                { id: 23191, name: 'NABIKHOMWA LOWER' },
                { id: 23188, name: 'NABIKHOMWA UPPER' },
                { id: 23189, name: 'SIIRA I' },
                { id: 23190, name: 'SIIRA II' },
              ],
            },
            {
              id: 3651,
              name: 'BUSAMBE',
              villages: [
                { id: 23203, name: 'BUSAMBE' },
                { id: 23204, name: 'NAMASHELE' },
                { id: 23205, name: 'NASASA' },
                { id: 23208, name: 'NATSUSI' },
                { id: 23206, name: 'SHAMBALA' },
                { id: 23207, name: 'SHIRULI' },
              ],
            },
          ],
        },
        {
          id: 1973,
          name: 'BUNAMBUTYE',
          parishes: [
            {
              id: 9348,
              name: 'BUNAMBUTYE',
              villages: [
                { id: 64196, name: 'KOFFI' },
                { id: 65828, name: 'MABANGA' },
                { id: 66301, name: 'MIRUMBA' },
                { id: 66963, name: 'NAGONO' },
                { id: 66964, name: 'NAGONO LOWER' },
                { id: 66965, name: 'NAGONO UPPER' },
              ],
            },
            {
              id: 9935,
              name: 'LWABOBA',
              villages: [
                { id: 65016, name: 'LAMBO LOWER' },
                { id: 65736, name: 'LWABOBA' },
                { id: 65737, name: 'LWABOBA CENTRAL' },
                { id: 65738, name: 'LWABOBA EAST' },
                { id: 66693, name: 'MUSHISHA' },
                { id: 71101, name: 'WEKUYA' },
              ],
            },
            {
              id: 9957,
              name: 'MAKUNDA',
              villages: [
                { id: 65977, name: 'MAKUNDA' },
                { id: 66607, name: 'MULYULI' },
                { id: 67200, name: 'NAMAANGA' },
                { id: 67614, name: 'NATSAKI' },
                { id: 70563, name: 'SUNU' },
                { id: 70564, name: 'SUNU LOWER' },
                { id: 70565, name: 'SUNU UPPER' },
              ],
            },
            {
              id: 10012,
              name: 'MUSESE',
              villages: [
                { id: 64223, name: 'KOLANI' },
                { id: 66002, name: 'MALUKHU' },
                { id: 66012, name: 'MANAFWA KOLANI' },
                { id: 66569, name: 'MUKYELO' },
                { id: 66683, name: 'MUSESE UPPER' },
                { id: 66684, name: 'MUSESE WAMPOMOKHA' },
                { id: 67122, name: 'NAKUNUKU' },
                { id: 71073, name: 'WAPOMOKHA' },
              ],
            },
          ],
        },
        {
          id: 779,
          name: 'BUNGOKHO',
          parishes: [
            {
              id: 3608,
              name: 'BUBIRABI',
              villages: [
                { id: 22885, name: 'BUKHATOKO' },
                { id: 22886, name: 'BUKHULENGA' },
                { id: 22887, name: 'KASONKO' },
                { id: 22890, name: 'LWALERA' },
                { id: 22888, name: 'LWATUBI' },
                { id: 22891, name: 'MAKAMBO' },
                { id: 22892, name: 'NATONDOME' },
                { id: 22889, name: 'SAKIYA' },
              ],
            },
            {
              id: 3609,
              name: 'BUMAGENI',
              villages: [
                { id: 22901, name: 'BUMAGENI BARRACKS' },
                { id: 22893, name: 'BUMWERU LOWER' },
                { id: 22894, name: 'BUNAPONGO LOWER' },
                { id: 22895, name: 'BUSHIRUSA' },
                { id: 22900, name: 'MANYONYI LOWER' },
                { id: 22896, name: 'MANYONYI UPPER' },
                { id: 22897, name: 'NAMUKONGO' },
                { id: 22898, name: 'NAPULU' },
                { id: 22899, name: 'SHANANDA' },
              ],
            },
            {
              id: 3610,
              name: 'BUSHIKORI',
              villages: [
                { id: 22904, name: 'KHAMOTO' },
                { id: 22905, name: 'LUYEKHE' },
                { id: 22906, name: 'MABANGA' },
                { id: 22902, name: 'NAKHALAPA' },
                { id: 22907, name: 'NAMAWANGA' },
                { id: 22910, name: 'NAMBALE' },
                { id: 22908, name: 'NAMBITI A' },
                { id: 22903, name: 'NAMBITI B' },
                { id: 22909, name: 'NASHIKHASO' },
              ],
            },
            {
              id: 3611,
              name: 'KHAMOTO',
              villages: [
                { id: 22911, name: 'KHAMOTO' },
                { id: 22912, name: 'NAKHALAPA' },
                { id: 22913, name: 'SHIBINIKO' },
                { id: 22914, name: 'TUMBU' },
                { id: 22915, name: 'WAMBEWO' },
              ],
            },
            {
              id: 3612,
              name: 'LWAMBOGO',
              villages: [
                { id: 22916, name: 'BUMWERU UPPER' },
                { id: 22918, name: 'BUNAPONGO UPPER' },
                { id: 22919, name: 'LUNGANGA' },
                { id: 22917, name: 'NAMUTUNGERI LOWER' },
                { id: 22920, name: 'NAMUTUNGERI UPPER' },
                { id: 22921, name: 'NANGOMBI' },
              ],
            },
          ],
        },
        {
          id: 780,
          name: 'BUSANO',
          parishes: [
            {
              id: 3615,
              name: 'BUFOOTO',
              villages: [
                { id: 22948, name: 'BUFOOTO' },
                { id: 22953, name: 'BUMASWERE' },
                { id: 22949, name: 'BUMUKARI' },
                { id: 22954, name: 'BUNYWAKA' },
                { id: 22947, name: 'BUTSONGOLA' },
                { id: 22956, name: 'BUWAMBUSI' },
                { id: 22955, name: 'BUWANGWA CENTRAL' },
                { id: 22950, name: 'BUWANGWA LOWER' },
                { id: 22951, name: 'BUWANGWA UPPER' },
                { id: 22952, name: 'NABIKYENGA' },
                { id: 22957, name: 'SHITEKA' },
              ],
            },
            {
              id: 3613,
              name: 'BUSANO',
              villages: [
                { id: 22924, name: 'BILINDA' },
                { id: 22922, name: 'BUKHANAKWA' },
                { id: 22928, name: 'BULUKHATI' },
                { id: 22929, name: 'BUSHILELO' },
                { id: 22923, name: 'BUTSIBITI' },
                { id: 22925, name: 'BUWANYANGA' },
                { id: 22926, name: 'BUYANGO EAST' },
                { id: 22927, name: 'BUYANGO WEST' },
                { id: 22930, name: 'LUWELELE' },
                { id: 22931, name: 'NALENDA' },
                { id: 22932, name: 'SHILIMI' },
              ],
            },
            {
              id: 3614,
              name: 'BUYAKA',
              villages: [
                { id: 22938, name: 'BIKEMO' },
                { id: 22933, name: 'BUMAMALI' },
                { id: 22934, name: 'BUMUKAMBA' },
                { id: 22939, name: 'BUMUSAMALI' },
                { id: 22935, name: 'BUNANDUTU' },
                { id: 22940, name: 'BUSANO TOWNSHIP' },
                { id: 22936, name: 'BUSIANGO' },
                { id: 22941, name: 'BUTITI' },
                { id: 22942, name: 'BUWATSALA' },
                { id: 22937, name: 'BUYAKA' },
                { id: 22943, name: 'LULANGATSA' },
                { id: 22944, name: 'NABIRINI' },
                { id: 22945, name: 'SHIYENGA' },
                { id: 22946, name: 'TSOSHELO' },
              ],
            },
            {
              id: 3616,
              name: 'BWIKHONJE',
              villages: [
                { id: 22958, name: 'BUNGWANYI' },
                { id: 22960, name: 'BWIKHONJE' },
                { id: 22961, name: 'LWABUSANO' },
                { id: 22962, name: 'MALUNDU' },
                { id: 22959, name: 'SHANGO' },
                { id: 22964, name: 'SHITULO' },
                { id: 22963, name: 'WAMANGONO' },
              ],
            },
          ],
        },
        {
          id: 781,
          name: 'BUSIU',
          parishes: [
            {
              id: 3617,
              name: 'BUFUKHULA',
              villages: [
                { id: 60709, name: 'BUYAKA' },
                { id: 22965, name: 'LUKHUNA' },
                { id: 22967, name: 'LUKHUNA LOWER' },
                { id: 22966, name: 'MAKHONJE' },
                { id: 22969, name: 'MAKHONJE LOWER' },
                { id: 65948, name: 'MAKHONJE T/C' },
                { id: 22968, name: 'MAKHONJE UPPER' },
              ],
            },
            {
              id: 3619,
              name: 'BULUSAMBU',
              villages: [
                { id: 22974, name: 'BULUSAMBU' },
                { id: 59749, name: 'BULUSAMBU LOWER' },
                { id: 22977, name: 'BULUSAMBU WASU' },
                { id: 22975, name: 'BUMULAAH WASU' },
                { id: 22976, name: 'LUTONYI' },
                { id: 22978, name: 'MAKHUYU' },
                { id: 65959, name: 'MAKHUYU UPPER' },
                { id: 22979, name: 'WAALE' },
              ],
            },
            {
              id: 3618,
              name: 'BUNAMBUTYE',
              villages: [
                { id: 22973, name: 'LAMBO LOWER' },
                { id: 22971, name: 'LWABOBA' },
                { id: 22972, name: 'LWABOBA EAST' },
                { id: 22970, name: 'MIRUMBA' },
              ],
            },
            {
              id: 3620,
              name: 'BUWALASI',
              villages: [
                { id: 22981, name: 'BUWALASI BILAA' },
                { id: 22980, name: 'LWABOBA' },
                { id: 65739, name: 'LWABOBA-MUKHUYU' },
                { id: 65740, name: 'LWABOBA-MUYEKHE' },
                { id: 22982, name: 'MATOLOTOLO' },
                { id: 66128, name: 'MATOLOTOLO EAST' },
                { id: 66129, name: 'MATOLOTOLO WEST' },
              ],
            },
            {
              id: 3621,
              name: 'LUMBUKU',
              villages: [
                { id: 22983, name: 'BUNANIMI' },
                { id: 60106, name: 'BUNANIMI LOWER' },
                { id: 22986, name: 'BUNAYAGA' },
                { id: 22985, name: 'LUMBUKU' },
                { id: 65693, name: 'LUSISI' },
                { id: 22984, name: 'NAMAKYE' },
                { id: 22987, name: 'RAILWAY' },
              ],
            },
            {
              id: 3622,
              name: 'MUSESE',
              villages: [
                { id: 22988, name: 'MANAFWA KOLANI' },
                { id: 22989, name: 'MULYULI' },
                { id: 22990, name: 'MUSESE UPPER' },
                { id: 22993, name: 'MUSESE WAMPOMOKHA' },
                { id: 22994, name: 'NAKUNUKU' },
                { id: 22991, name: 'NAMAANGA' },
                { id: 22992, name: 'SUNU' },
              ],
            },
          ],
        },
        {
          id: 790,
          name: 'BUSIU TOWN COUNCIL',
          parishes: [
            {
              id: 3658,
              name: 'ALPHA WARD',
              villages: [
                { id: 23241, name: 'BUWALASI CENTRAL' },
                { id: 65071, name: 'LANDI' },
                { id: 66150, name: 'MAUMBE' },
                { id: 23239, name: 'NAMWITAKO' },
                { id: 23238, name: 'TOWNSHIP MAIN' },
                { id: 23240, name: 'WALUKHU' },
              ],
            },
            {
              id: 3659,
              name: 'BUFUKHULA CENTRAL WARD',
              villages: [
                { id: 23244, name: 'BUFUKHULA UPPER' },
                { id: 23242, name: 'BUMULAAH TOMA' },
                { id: 23243, name: 'MANAFWA' },
                { id: 70294, name: 'SCHOOL' },
              ],
            },
            {
              id: 3666,
              name: 'BUFUKHULA WARD',
              villages: [
                { id: 23275, name: 'BUFUKHULA CENTRAL' },
                { id: 23273, name: 'BUFUKHULA TOMA' },
                { id: 59872, name: 'BUMUKHAMA' },
                { id: 23274, name: 'BUNAYAGA' },
                { id: 65965, name: 'MAKONJE UPPER' },
                { id: 70969, name: 'WABUNGU' },
              ],
            },
            {
              id: 3667,
              name: 'BUWALASI WARD',
              villages: [
                { id: 23279, name: 'BUWALASI TOMA' },
                { id: 66013, name: 'MANAFWA LOWER' },
                { id: 23276, name: 'MITOMITO' },
                { id: 67040, name: 'NAKHABALE' },
                { id: 23280, name: 'NATONDOME' },
                { id: 23277, name: 'RWENZORI' },
                { id: 23278, name: 'WAMUTYENGU' },
              ],
            },
            {
              id: 3660,
              name: 'CENTRAL WARD',
              villages: [
                { id: 23245, name: 'BILAAH' },
                { id: 23246, name: 'BUSIKU' },
                { id: 23247, name: 'CENTRAL' },
                { id: 65889, name: 'MAGILA' },
                { id: 23248, name: 'WANANDA' },
              ],
            },
            {
              id: 3661,
              name: 'HOSPITAL WARD',
              villages: [
                { id: 23249, name: 'BUWALASI' },
                { id: 23250, name: 'FACTORY' },
                { id: 23251, name: 'HOSPITAL' },
                { id: 23252, name: 'SDA' },
              ],
            },
            {
              id: 3662,
              name: 'KOLAN WARD',
              villages: [
                { id: 23253, name: 'GREEN HILL' },
                { id: 23255, name: 'KOLAN CENTRAL' },
                { id: 23256, name: 'KOLAN EAST' },
                { id: 23258, name: 'KOLAN NORTH' },
                { id: 23254, name: 'MABANGA KOLANI' },
                { id: 23257, name: 'NAMBUTYE' },
                { id: 23259, name: 'NANGONO' },
              ],
            },
            {
              id: 3663,
              name: 'MABANGA WARD',
              villages: [
                { id: 23260, name: 'GREEN LAND' },
                { id: 23261, name: 'MABANGA CENTRAL' },
                { id: 23262, name: 'MABANGA LOWER' },
                { id: 23263, name: 'MABANGA UPPER' },
              ],
            },
            {
              id: 3664,
              name: 'NAMIREMBE WARD',
              villages: [
                { id: 59139, name: 'BOARDER' },
                { id: 23267, name: 'BWIKHONJE' },
                { id: 61241, name: 'ELGON' },
                { id: 23265, name: 'GAYAZA' },
                { id: 23266, name: 'GREEN' },
                { id: 61520, name: 'HIGHWAY' },
                { id: 23268, name: 'NAMIREMBE' },
                { id: 23264, name: 'NAMUNYU' },
              ],
            },
            {
              id: 3665,
              name: 'TOWN WARD',
              villages: [
                { id: 23269, name: 'KOLAN LOWER' },
                { id: 23270, name: 'NAKHAISO' },
                { id: 23271, name: 'NAMAASA' },
                { id: 23272, name: 'TOWN CELL' },
              ],
            },
          ],
        },
        {
          id: 782,
          name: 'BUSOBA',
          parishes: [
            {
              id: 3623,
              name: 'BUMASIKYE',
              villages: [
                { id: 22995, name: 'BUMASIKYE' },
                { id: 22999, name: 'BUTEBO' },
                { id: 23000, name: 'LUBANGA' },
                { id: 22996, name: 'MAAKO' },
                { id: 22997, name: 'NALONDO A' },
                { id: 23001, name: 'NALONDO B' },
                { id: 22998, name: 'SIIRA' },
              ],
            },
            {
              id: 3624,
              name: 'BUNAMBUTYE',
              villages: [
                { id: 23002, name: 'BUSOBA' },
                { id: 23007, name: 'KAAMULI' },
                { id: 23006, name: 'MABINDA' },
                { id: 23004, name: 'MATIBO' },
                { id: 23003, name: 'NALONDO' },
                { id: 23005, name: 'NALONDO A' },
              ],
            },
            {
              id: 3625,
              name: 'BUNANIMI',
              villages: [
                { id: 23013, name: 'BUTUNDE' },
                { id: 23012, name: 'BUWALASI' },
                { id: 23011, name: 'LUMA' },
                { id: 23009, name: 'MATIBO' },
                { id: 23010, name: 'NAMWARO' },
                { id: 23008, name: 'TULULU' },
              ],
            },
            {
              id: 3626,
              name: 'BUSOBA',
              villages: [
                { id: 23032, name: 'BUBETSYE' },
                { id: 23033, name: 'BUKATSA' },
                { id: 23015, name: 'BULOLERO' },
                { id: 23024, name: 'BULUSAMBU' },
                { id: 23023, name: 'BULUSAMBU A' },
                { id: 23018, name: 'BUMWALYE' },
                { id: 23026, name: 'BUSHENDE A' },
                { id: 23019, name: 'BUSHIENDE' },
                { id: 23020, name: 'BUWANGOLO' },
                { id: 23016, name: 'LULWANDA' },
                { id: 23031, name: 'LWAKHA' },
                { id: 23021, name: 'LWANGOLI' },
                { id: 23028, name: 'LWANGOLI A' },
                { id: 23029, name: 'LWANGOLI LOWER' },
                { id: 23017, name: 'LWANGOLI UPPER' },
                { id: 23022, name: 'MAKHAI' },
                { id: 23037, name: 'MURUMBA' },
                { id: 23036, name: 'NABUNYWI' },
                { id: 23025, name: 'NAMASHISYO' },
                { id: 23014, name: 'NAMASHISYO A' },
                { id: 23027, name: 'NAMWALYE' },
                { id: 23030, name: 'SEKERERE' },
                { id: 23034, name: 'SHITOBO' },
                { id: 23035, name: 'SUKURA' },
              ],
            },
          ],
        },
        {
          id: 786,
          name: 'LUKHONGE',
          parishes: [
            {
              id: 3641,
              name: 'NABWEYE',
              villages: [
                { id: 23144, name: 'MAFUTU' },
                { id: 23138, name: 'MANANA' },
                { id: 23139, name: 'NABWEYE LOWER' },
                { id: 23143, name: 'NABWEYE UPPER' },
                { id: 23140, name: 'SYEEBA' },
                { id: 23142, name: 'WALUSYEMBE' },
                { id: 23141, name: 'WAMALO' },
              ],
            },
            {
              id: 3640,
              name: 'NAMAWANGA',
              villages: [
                { id: 23128, name: 'BUMAKIKA' },
                { id: 23137, name: 'BUNAMONO UPPER' },
                { id: 23130, name: 'BUSHANGI' },
                { id: 23131, name: 'BUTSESOOLI' },
                { id: 23132, name: 'BUWAKHANYINYI A' },
                { id: 23135, name: 'BUWAKHANYINYI B' },
                { id: 23133, name: 'BUWALIBITSA' },
                { id: 23136, name: 'BUWAMUWAYA' },
                { id: 23127, name: 'NAMUKHONGE' },
                { id: 23129, name: 'NASHANGALE' },
                { id: 23134, name: 'NEKOMBE' },
              ],
            },
            {
              id: 3642,
              name: 'NAMBWA',
              villages: [
                { id: 23151, name: 'KHAKAKHO' },
                { id: 23150, name: 'KISENYI' },
                { id: 23145, name: 'LUKHONGE' },
                { id: 23147, name: 'MARINDE' },
                { id: 23148, name: 'MATUWA' },
                { id: 23149, name: 'NAMBWA' },
                { id: 23152, name: 'NAMUSONJE' },
                { id: 23146, name: 'WAMELI' },
              ],
            },
            {
              id: 3643,
              name: 'WANINDA',
              villages: [
                { id: 23153, name: 'BULEKYA A' },
                { id: 23154, name: 'BULEKYA B' },
                { id: 23161, name: 'BUMAKIKA II' },
                { id: 23155, name: 'BUNAMONO II' },
                { id: 23156, name: 'BUNANDYEBI A' },
                { id: 23157, name: 'BUNANDYEBI B' },
                { id: 23159, name: 'MUYEMBE' },
                { id: 23160, name: 'WANINDA A' },
                { id: 23158, name: 'WANINDA B' },
              ],
            },
          ],
        },
        {
          id: 789,
          name: 'NABUMALI TOWN COUNCIL',
          parishes: [
            {
              id: 3652,
              name: 'BUKUWA WARD',
              villages: [
                { id: 23211, name: 'BUNANIMI' },
                { id: 23212, name: 'MATSAKHA' },
                { id: 23209, name: 'NAMILI' },
                { id: 23210, name: 'WOTSONGOLE' },
              ],
            },
            {
              id: 3653,
              name: 'MASIKYE WARD',
              villages: [
                { id: 23216, name: 'BUBETSYE CENTRAL' },
                { id: 23213, name: 'BUBETSYE LOWER' },
                { id: 23214, name: 'BUMUYELERO LOWER' },
                { id: 23218, name: 'BUWAMALERO LOWER' },
                { id: 23217, name: 'BUWAMALERO UPPER' },
                { id: 23215, name: 'BUWUMALERO UPPER' },
                { id: 23220, name: 'MANYENYA' },
                { id: 23219, name: 'NANGWASI' },
              ],
            },
            {
              id: 3654,
              name: 'MUNGOMA WARD',
              villages: [
                { id: 23222, name: 'BUKHAMUNYU' },
                { id: 23223, name: 'MAAHANGA' },
                { id: 23224, name: 'MAYONGA' },
                { id: 23221, name: 'NABUMALI TRINITY' },
                { id: 23225, name: 'UTUTU' },
              ],
            },
            {
              id: 3655,
              name: 'NABUMALI CENTRAL WARD',
              villages: [
                { id: 23228, name: 'MATOTOWA' },
                { id: 23227, name: 'NABUMALI H/S' },
                { id: 23229, name: 'NABUMALI TOWNSHIP' },
                { id: 23226, name: 'NASHISAKA MAIN' },
              ],
            },
            {
              id: 3656,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 23231, name: 'BUNYWAKA' },
                { id: 23232, name: 'BUWABUYI' },
                { id: 23230, name: 'NASHIKA LOWER' },
                { id: 23233, name: 'SHIYATSA' },
              ],
            },
            {
              id: 3657,
              name: 'WAMWA WARD',
              villages: [
                { id: 23234, name: 'BUFUKHULA' },
                { id: 23235, name: 'BUMUKHAMA' },
                { id: 23237, name: 'MUYEKHE' },
                { id: 23236, name: 'NAKHABOKO' },
              ],
            },
          ],
        },
        {
          id: 783,
          name: 'NAMBALE',
          parishes: [
            {
              id: 3627,
              name: 'BUMBOI',
              villages: [
                { id: 23043, name: 'BUMADI' },
                { id: 23046, name: 'BUMBOI T/C' },
                { id: 23040, name: 'BUNAGIMESU' },
                { id: 23042, name: 'KIDOBO' },
                { id: 23039, name: 'MAGAKHALA' },
                { id: 23038, name: 'NABISOLO' },
                { id: 23044, name: 'NALOKHA' },
                { id: 23041, name: 'NAMASHELE' },
                { id: 23045, name: 'SHIDULA' },
              ],
            },
            {
              id: 3629,
              name: 'BUMUTOTO',
              villages: [
                { id: 23060, name: 'BUKISUKYE LOWER' },
                { id: 23052, name: 'BUKISUKYE UPPER' },
                { id: 23059, name: 'BUKUNALIRE LOWER' },
                { id: 23061, name: 'BUKUNALIRE UPPER' },
                { id: 23058, name: 'BUNAMWANI LOWER' },
                { id: 23053, name: 'BUNAMWANI UPPER' },
                { id: 23057, name: 'KATWAKA' },
                { id: 23054, name: 'MAKOKHA' },
                { id: 23056, name: 'MUTOTO LOWER' },
                { id: 23055, name: 'MUTOTO UPPER' },
              ],
            },
            {
              id: 3628,
              name: 'MOONI',
              villages: [
                { id: 23048, name: 'BUKHOSA' },
                { id: 23049, name: 'BUKHUNGALA' },
                { id: 23047, name: 'BULUJERE' },
                { id: 23050, name: 'MIALE' },
                { id: 23051, name: 'MIREMBE' },
              ],
            },
            {
              id: 3631,
              name: 'MUYANDA',
              villages: [
                { id: 23070, name: 'BUBENTSYE' },
                { id: 23071, name: 'BUSIMBA' },
                { id: 23072, name: 'MUKHUBU' },
                { id: 23074, name: 'NAMIKHO' },
                { id: 23073, name: 'SHIKUNGA' },
              ],
            },
            {
              id: 3630,
              name: 'NAMALOGO',
              villages: [
                { id: 23062, name: 'KAMISYO' },
                { id: 23063, name: 'LUSAGA' },
                { id: 23064, name: 'MANGHO LOWER' },
                { id: 23065, name: 'MANGHO UPPER' },
                { id: 23068, name: 'MUKHUWA' },
                { id: 23066, name: 'MUSOLA' },
                { id: 23069, name: 'NABWISYA' },
                { id: 23067, name: 'WAKHANGO' },
              ],
            },
          ],
        },
        {
          id: 791,
          name: 'NAUYO TOWN COUNCIL',
          parishes: [
            {
              id: 3668,
              name: 'BUKASAKYA WARD',
              villages: [
                { id: 23281, name: 'BUGEMA  A' },
                { id: 23282, name: 'BUGEMA CENTRE' },
                { id: 63538, name: 'KIGYA' },
                { id: 23283, name: 'MUNKAGA' },
              ],
            },
            {
              id: 3669,
              name: 'KIJJA WARD',
              villages: [
                { id: 23284, name: 'AUSI' },
                { id: 23285, name: 'BALAYO' },
                { id: 23286, name: 'OUZIMA' },
                { id: 23287, name: 'WOLYEMA' },
              ],
            },
            {
              id: 3670,
              name: 'NAPOOLI CENTRAL WARD',
              villages: [
                { id: 23289, name: 'KIGUNDU' },
                { id: 23288, name: 'NABWOMA' },
                { id: 23290, name: 'PRIMARY CELL' },
                { id: 23291, name: 'WEPHUKHULU' },
              ],
            },
            {
              id: 3671,
              name: 'NAPOOLI LOWER WARD',
              villages: [
                { id: 23292, name: 'KENGEKE' },
                { id: 23293, name: 'KHABUS' },
                { id: 23294, name: 'MUTENDE' },
                { id: 23295, name: 'MUTENYO' },
                { id: 23296, name: 'SITUMA' },
              ],
            },
            {
              id: 3672,
              name: 'NAPOOLI UPPER WARD',
              villages: [
                { id: 23297, name: 'LIGHT ACADEMY' },
                { id: 23298, name: 'MOITI' },
                { id: 23299, name: 'NAMUNANE' },
                { id: 23300, name: 'WAKHOLI' },
              ],
            },
            {
              id: 3673,
              name: 'WAKHWABA CENTRAL WARD',
              villages: [
                { id: 23301, name: 'MABONGA' },
                { id: 23302, name: 'MUSA' },
                { id: 23303, name: 'WARID' },
                { id: 23304, name: 'ZADOKI' },
              ],
            },
            {
              id: 3674,
              name: 'WAKHWABA LOWER WARD',
              villages: [
                { id: 23305, name: 'ARAMANZAN' },
                { id: 23306, name: 'FLORIDA' },
                { id: 23307, name: 'WAKHWABA A' },
                { id: 23308, name: 'WAKHWABA B' },
                { id: 23309, name: 'WAKHWABA C' },
              ],
            },
            {
              id: 3675,
              name: 'WAKHWABA UPPER WARD',
              villages: [
                { id: 23310, name: 'HOLY TRINITY' },
                { id: 23311, name: 'MASABA' },
                { id: 23312, name: 'MUTUTU' },
                { id: 23313, name: 'NAMABELE' },
              ],
            },
          ],
        },
        { id: 2082, name: 'NAUYO-BUGEMA TOWN COUNCIL', parishes: [] },
        {
          id: 787,
          name: 'NYONDO',
          parishes: [
            {
              id: 3644,
              name: 'BUBETSYE',
              villages: [
                { id: 23163, name: 'BUBETSYE UPPER' },
                { id: 23164, name: 'BUKATSA' },
                { id: 23170, name: 'BUMASIKYE' },
                { id: 23166, name: 'KOOYI' },
                { id: 23162, name: 'MABALE' },
                { id: 23168, name: 'MURUBA' },
                { id: 23169, name: 'NABIIRI' },
                { id: 23165, name: 'SHITIMO LOWER' },
                { id: 23167, name: 'SHITIMO UPPER' },
              ],
            },
            {
              id: 3647,
              name: 'BUFUKHULA',
              villages: [
                { id: 23180, name: 'FUMU' },
                { id: 23181, name: 'NYONDO' },
                { id: 23182, name: 'NYONDO P.T.C' },
                { id: 23183, name: 'SHILONGO' },
              ],
            },
            { id: 3645, name: 'NABUMALI', villages: [{ id: 23171, name: 'NABALOSI' }] },
            {
              id: 3646,
              name: 'NYONDO',
              villages: [
                { id: 23172, name: 'BULUSAMBU' },
                { id: 23173, name: 'BUMULAHA' },
                { id: 23174, name: 'BUNAMBUTYE' },
                { id: 23179, name: 'MAYEYE' },
                { id: 23178, name: 'NABUNYUNGA' },
                { id: 23175, name: 'NAMATOKOTA' },
                { id: 23177, name: 'SHIBUMBA' },
                { id: 23176, name: 'SHITULWA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 126,
      name: 'MBALE MUNICIPALITY',
      sub_counties: [
        {
          id: 792,
          name: 'INDUSTRIAL BOROUGH',
          parishes: [
            {
              id: 3676,
              name: 'MALUKHU',
              villages: [
                { id: 23314, name: 'BUSANO' },
                { id: 23315, name: 'MAJANGA' },
                { id: 23316, name: 'MUTI' },
                { id: 23320, name: 'MUYEMBE' },
                { id: 23317, name: 'PRIMARY' },
                { id: 23318, name: 'SIRONKO' },
                { id: 23319, name: 'WANYERA' },
              ],
            },
            {
              id: 3677,
              name: 'MASABA',
              villages: [
                { id: 23321, name: 'BUGWERE' },
                { id: 23322, name: 'BUMASIFWA' },
                { id: 23323, name: 'BUTALEJA' },
                { id: 23324, name: 'MALAWA' },
                { id: 23325, name: 'PALLISA' },
                { id: 23326, name: 'TEMUTWEWO MUKASA' },
              ],
            },
            {
              id: 3678,
              name: 'NAMATALA',
              villages: [
                { id: 23333, name: 'BUBIRABI' },
                { id: 23327, name: 'DOKO' },
                { id: 23334, name: 'KIDUDA' },
                { id: 23328, name: 'MVULE' },
                { id: 23329, name: 'NYANZA' },
                { id: 23330, name: 'SISYE' },
                { id: 23331, name: 'SOMERO' },
                { id: 23332, name: 'WANDAWA' },
              ],
            },
            {
              id: 3679,
              name: 'SOUTH CENTRAL',
              villages: [
                { id: 23335, name: 'CATHEDRAL' },
                { id: 23336, name: 'FOODS' },
                { id: 23337, name: 'KALE' },
                { id: 23338, name: 'LWAKAKA' },
                { id: 23339, name: 'NABOA' },
                { id: 23340, name: 'PARK' },
                { id: 23341, name: 'POLICE' },
                { id: 23342, name: 'REPUBLIC' },
                { id: 23343, name: "ST. ANDREW'S" },
                { id: 23344, name: 'WASIKYE' },
              ],
            },
          ],
        },
        {
          id: 793,
          name: 'NORTHERN BOROUGH',
          parishes: [
            {
              id: 3684,
              name: 'IU-IU',
              villages: [
                { id: 23378, name: 'NORTHERN' },
                { id: 23379, name: 'SHERATON' },
                { id: 23380, name: 'STAFF' },
              ],
            },
            {
              id: 3680,
              name: 'NABUYONGA',
              villages: [
                { id: 23345, name: 'BUWALASI' },
                { id: 23346, name: 'KIKYAFU' },
                { id: 23347, name: 'KISENYI' },
                { id: 23349, name: 'MAGEZI' },
                { id: 23350, name: 'MIREMBE' },
                { id: 23348, name: 'SEBEI' },
              ],
            },
            {
              id: 3681,
              name: 'NAMAKWEKWE',
              villages: [
                { id: 23351, name: 'BUFUMBO' },
                { id: 23352, name: 'BULAGO' },
                { id: 23353, name: 'COLLEGE' },
                { id: 61242, name: 'ELGON' },
                { id: 23354, name: 'GUDOI' },
                { id: 23355, name: 'KACHUMBALA' },
                { id: 23356, name: 'KITESO' },
                { id: 23357, name: 'LINK ROAD' },
                { id: 23358, name: 'MISSION' },
                { id: 23359, name: 'MPUMUDE' },
                { id: 23360, name: 'MUGISU' },
                { id: 23361, name: 'NABIGYO' },
                { id: 67188, name: 'NALUWERERE' },
              ],
            },
            {
              id: 3682,
              name: 'NKOMA',
              villages: [
                { id: 23362, name: 'BUJOLOTO' },
                { id: 23367, name: 'BUYONJO' },
                { id: 23364, name: 'GANGAMA' },
                { id: 23365, name: 'HYGIENE' },
                { id: 23366, name: 'NAMBOZO' },
                { id: 23368, name: 'SENKULU' },
                { id: 23363, name: 'WAGAGAI' },
                { id: 23369, name: 'WANAMBWA' },
              ],
            },
            {
              id: 3683,
              name: 'NORTH CENTRAL',
              villages: [
                { id: 23370, name: 'BYASHARA' },
                { id: 23371, name: 'CLOCK TOWER' },
                { id: 23372, name: 'DUKA' },
                { id: 23373, name: 'HOSPITAL' },
                { id: 23377, name: 'HOSTEL' },
                { id: 23374, name: 'NKOKONJERU' },
                { id: 23375, name: 'NORTH ROAD' },
                { id: 23376, name: 'PESA' },
              ],
            },
          ],
        },
        {
          id: 794,
          name: 'WANALE BOROUGH',
          parishes: [
            {
              id: 3685,
              name: 'BOMA',
              villages: [
                { id: 23381, name: 'BUKWA' },
                { id: 23382, name: 'BUNKOKO' },
                { id: 23383, name: 'ELGON' },
                { id: 23384, name: 'FAIRWAY' },
                { id: 23385, name: 'MASABA' },
                { id: 23386, name: 'NABIJJO' },
                { id: 23387, name: 'NAKHUPA' },
                { id: 23388, name: 'UNION' },
                { id: 23389, name: 'WANALE' },
              ],
            },
            {
              id: 3686,
              name: 'BUSAMAGA EAST',
              villages: [
                { id: 23391, name: 'BUTANDIGA' },
                { id: 23390, name: 'NAMALOGO' },
                { id: 23392, name: 'NAMATSYO' },
                { id: 23393, name: 'NAMPANGA' },
              ],
            },
            {
              id: 3688,
              name: 'BUSAMAGA WEST',
              villages: [
                { id: 23398, name: 'BUMBOI' },
                { id: 23399, name: 'HEALTH CENTRE' },
                { id: 23401, name: 'MOSQUE' },
                { id: 23400, name: 'NABWEYA' },
              ],
            },
            {
              id: 3687,
              name: 'MOONI',
              villages: [
                { id: 23395, name: 'MUTOTO' },
                { id: 23396, name: 'NAGUDI' },
                { id: 23394, name: 'NAMUBIRU' },
                { id: 23397, name: 'NASHIBISO' },
              ],
            },
            {
              id: 3689,
              name: 'MUKHUBU',
              villages: [
                { id: 23402, name: 'ISEBELLE' },
                { id: 23403, name: 'SAWA' },
                { id: 23404, name: 'SHENDE' },
                { id: 23405, name: 'ZESUI' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
