import { District } from '../types';

export default {
  id: 17,
  name: 'MITOOMA',
  counties: [
    {
      id: 45,
      name: 'RUHINDA COUNTY',
      sub_counties: [
        {
          id: 247,
          name: 'KABIRA',
          parishes: [
            {
              id: 1162,
              name: 'BUHARAMBO',
              villages: [
                { id: 7980, name: 'KANYABUHANGA' },
                { id: 7981, name: 'KIBINGO' },
                { id: 7982, name: 'KITOOKYE' },
                { id: 7983, name: 'NYAKAGOMORA' },
                { id: 7984, name: 'NYAKIZIBA' },
                { id: 7985, name: 'RUREKA' },
              ],
            },
            {
              id: 1163,
              name: 'NYABUBARE',
              villages: [
                { id: 7986, name: 'IHUNGU' },
                { id: 7987, name: 'KARANGARA' },
                { id: 7988, name: 'KASHARARA' },
                { id: 7989, name: 'KYAMUYANGA' },
                { id: 7990, name: 'KYENDARE' },
                { id: 7991, name: 'NTSISA' },
                { id: 7992, name: 'NYABUBARE' },
                { id: 7993, name: 'NYAKAGONGO' },
                { id: 7994, name: 'NYAKANONI' },
                { id: 7995, name: 'NYAKASHARARA' },
                { id: 7996, name: 'NYAMABARE' },
                { id: 7997, name: 'OMUKACENCE' },
                { id: 7998, name: 'OMUKIBARE' },
                { id: 7999, name: 'RUSHOJWA' },
                { id: 8000, name: 'RWAKATARA' },
              ],
            },
            {
              id: 1164,
              name: 'NYAKATETE',
              villages: [
                { id: 8001, name: 'KYARUGABA' },
                { id: 8002, name: 'NYAMUSHEBEYA' },
                { id: 8003, name: 'NYARUTUNTU' },
                { id: 8004, name: 'RUNYINYA' },
                { id: 8005, name: 'RWAMUJAKA' },
                { id: 8006, name: 'RWEMBURARA' },
              ],
            },
            {
              id: 1165,
              name: 'RUREHE NORTH',
              villages: [
                { id: 8007, name: 'KAARO' },
                { id: 8008, name: 'KEIROKOKYE' },
                { id: 8009, name: 'NYAKAGONGO' },
                { id: 8010, name: 'NYAKANYINYA' },
                { id: 8011, name: 'NYAKAZINGA' },
                { id: 8012, name: 'NYAMUSHUNGWA' },
                { id: 8013, name: 'RUREHE' },
                { id: 8014, name: 'RWENYANGI' },
              ],
            },
          ],
        },
        {
          id: 248,
          name: 'KASHENSHERO',
          parishes: [
            {
              id: 1166,
              name: 'BUKARI',
              villages: [
                { id: 8015, name: 'BWEZA' },
                { id: 8016, name: 'KASHAMBYA' },
                { id: 8017, name: 'KATOOMA' },
                { id: 8018, name: 'KIHUNDA' },
                { id: 8019, name: 'KYABAHETSI' },
                { id: 8020, name: 'NYAMPIKYE' },
                { id: 8021, name: 'NYARUKAZI' },
              ],
            },
            {
              id: 1167,
              name: 'BUKUBA',
              villages: [
                { id: 8022, name: 'AKAREERE' },
                { id: 8023, name: 'BUKUBA I' },
                { id: 8024, name: 'BUKUBA II' },
                { id: 8025, name: 'KIHENGAMO' },
                { id: 8026, name: 'SHONGORA II' },
              ],
            },
            {
              id: 1168,
              name: 'KIRERA',
              villages: [
                { id: 8027, name: 'KAREEBO I' },
                { id: 8028, name: 'KAREEBO II' },
                { id: 8030, name: 'KIHIHI I' },
                { id: 8031, name: 'KIHIHI II' },
                { id: 8032, name: 'KIKUNYU I' },
                { id: 8033, name: 'KIKUNYU II' },
                { id: 8034, name: 'KIRERA I' },
                { id: 8035, name: 'KIRERA II' },
                { id: 8029, name: 'KITANOGA III' },
                { id: 8037, name: 'MATSYA I' },
                { id: 8036, name: 'MATSYA II' },
                { id: 8038, name: 'ORUHITA I' },
              ],
            },
            {
              id: 1169,
              name: 'KYANZIRE',
              villages: [
                { id: 8039, name: 'KAREHE I' },
                { id: 8040, name: 'KAREHE II' },
                { id: 8041, name: 'KITOJO I' },
                { id: 8042, name: 'KITOJO II' },
                { id: 8043, name: 'KYANYARUHANGO I' },
                { id: 8044, name: 'KYANYARUHANGO II' },
                { id: 8045, name: 'MUBANDA I' },
                { id: 8046, name: 'MUBANDA II' },
                { id: 8047, name: 'RWEIBARE I' },
                { id: 8048, name: 'RWEIBARE II' },
              ],
            },
            {
              id: 1170,
              name: 'NYAKATOOMA',
              villages: [
                { id: 8049, name: 'BURERA II' },
                { id: 8050, name: 'KITANOGA I' },
                { id: 8051, name: 'KITANOGA II' },
                { id: 8052, name: 'NYAKATOOMA I' },
                { id: 8053, name: 'NYAKATOOMA II' },
              ],
            },
          ],
        },
        {
          id: 254,
          name: 'KASHENSHERO TOWN COUNCIL',
          parishes: [
            {
              id: 1197,
              name: 'KASHENSHERO  WARD I',
              villages: [
                { id: 8307, name: 'BUBANGIZI' },
                { id: 8309, name: 'RUTI I' },
                { id: 8310, name: 'RUTI II' },
                { id: 8308, name: 'SHONGORA I' },
              ],
            },
            {
              id: 1198,
              name: 'KASHENSHERO  WARD II',
              villages: [
                { id: 8311, name: 'KASHENSHERO I' },
                { id: 8312, name: 'KASHENSHERO II' },
                { id: 8313, name: 'KIHUNGYE' },
                { id: 8314, name: 'RYAMBUZI' },
              ],
            },
            {
              id: 1199,
              name: 'KASHENSHERO CENTRAL WARD',
              villages: [
                { id: 8315, name: 'BUKARI' },
                { id: 8316, name: 'KASHENSHERO CENTRAL' },
                { id: 8317, name: 'NYAKAGONGO' },
                { id: 8318, name: 'RWENYONYOZI' },
              ],
            },
            {
              id: 1200,
              name: 'NYARUBIRA-BURERA WARD',
              villages: [
                { id: 8319, name: 'BURERA I' },
                { id: 8320, name: 'NYARUBIRA I' },
                { id: 8321, name: 'NYARUBIRA II' },
              ],
            },
          ],
        },
        {
          id: 251,
          name: 'KATENGA',
          parishes: [
            {
              id: 1185,
              name: 'BITOOMA',
              villages: [
                { id: 8176, name: 'BITOOMA I' },
                { id: 8177, name: 'BITOOMA II' },
                { id: 8178, name: 'KAKAMBA' },
                { id: 8179, name: 'KAKYERA I' },
                { id: 8180, name: 'KAKYERA II' },
                { id: 8181, name: 'KATENGA I' },
                { id: 8182, name: 'KATENGA II' },
                { id: 8183, name: 'RUSHOZI I' },
                { id: 8184, name: 'RUSHOZI II' },
                { id: 8185, name: 'RWAGASHANI' },
                { id: 8186, name: 'RWENKURI I' },
                { id: 8187, name: 'RWENKURI II' },
              ],
            },
            {
              id: 1188,
              name: 'IGAMBIRO',
              villages: [
                { id: 8224, name: 'KAGONGO' },
                { id: 8225, name: 'NYABUBARE' },
                { id: 8226, name: 'NYABWINA I' },
                { id: 8227, name: 'NYABWINA II' },
                { id: 8228, name: 'NYAKAZIBA' },
                { id: 8229, name: 'RUKONDO' },
              ],
            },
            {
              id: 1186,
              name: 'KIREMBE',
              villages: [
                { id: 8188, name: 'KATENGA I' },
                { id: 8189, name: 'KATENGA II' },
                { id: 8190, name: 'KAYANGA I' },
                { id: 8191, name: 'KAYANGA II' },
                { id: 8192, name: 'KIREMBE I' },
                { id: 8193, name: 'KIREMBE II' },
                { id: 8194, name: 'NGOMBA I' },
                { id: 8195, name: 'NGOMBA II' },
                { id: 8196, name: 'NYAKASHARARA' },
                { id: 8197, name: 'NYAMIYAGA I' },
                { id: 8198, name: 'NYAMIYAGA II' },
                { id: 8199, name: 'NYARUZINGA' },
                { id: 8200, name: 'RUBAASA' },
                { id: 8201, name: 'RUBUMBA' },
                { id: 8202, name: 'RUKUKURU' },
                { id: 8203, name: 'RUNYINYA I' },
                { id: 8204, name: 'RUNYINYA II' },
                { id: 8205, name: 'RUZIIZI' },
              ],
            },
            {
              id: 1187,
              name: 'RUKARARWE',
              villages: [
                { id: 8206, name: 'BURINDI' },
                { id: 8208, name: 'KABARORE' },
                { id: 8209, name: 'KAMUKARURUKA' },
                { id: 8211, name: 'KARIRE' },
                { id: 8212, name: 'KAZIIRA' },
                { id: 8213, name: 'KAZIKO' },
                { id: 8214, name: 'KIKUUTO' },
                { id: 8210, name: 'KINOGO' },
                { id: 8215, name: 'KINYEMERA' },
                { id: 8216, name: 'NYAKAGONGO' },
                { id: 8217, name: 'NYAKAHITA' },
                { id: 8219, name: 'NYAKASHOJWA' },
                { id: 8218, name: 'NYAKATUNTU' },
                { id: 8207, name: 'OMUKINYINYA' },
                { id: 8220, name: 'RUBAARE A' },
                { id: 8221, name: 'RUBAARE B' },
                { id: 8222, name: 'RUKARARWE' },
                { id: 8223, name: 'SAZINGA' },
              ],
            },
          ],
        },
        {
          id: 252,
          name: 'MAYANGA',
          parishes: [
            {
              id: 1191,
              name: 'KATAGATA',
              villages: [
                { id: 8258, name: 'ITARA' },
                { id: 8259, name: 'KATAGATA' },
                { id: 8260, name: 'KENSHUMBA' },
                { id: 8261, name: 'NYARWANYA A' },
                { id: 8262, name: 'NYARWANYA B' },
              ],
            },
            {
              id: 1189,
              name: 'MAYANGA',
              villages: [
                { id: 8230, name: 'BUYAAYO A' },
                { id: 8231, name: 'BUYAAYO B' },
                { id: 8232, name: 'BUYAAYO C' },
                { id: 8233, name: 'MAYANGA A' },
                { id: 8234, name: 'MAYANGA B' },
                { id: 8235, name: 'MAYANGA C' },
                { id: 8236, name: 'MAYANGA D' },
                { id: 8237, name: 'NYAKATOOMA A' },
                { id: 8238, name: 'NYAKATOOMA B' },
                { id: 8239, name: 'NYARUZINGA A' },
                { id: 8240, name: 'NYARUZINGA B' },
                { id: 8241, name: 'NYARUZINGA C' },
                { id: 8242, name: 'RUNYINYA A' },
                { id: 8243, name: 'RUNYINYA B' },
                { id: 8244, name: 'RUSHEREGYENYI A' },
                { id: 8245, name: 'RUSHEREGYENYI B' },
              ],
            },
            {
              id: 1192,
              name: 'RWAMUJURA',
              villages: [
                { id: 8263, name: 'MUTANOGA' },
                { id: 8264, name: 'RUCURURU' },
                { id: 8265, name: 'RUGANDO' },
                { id: 8266, name: 'RUTOOMA' },
                { id: 8267, name: 'RWAMUJURA' },
              ],
            },
            {
              id: 1190,
              name: 'RWANJA EAST',
              villages: [
                { id: 8246, name: 'KAKYEZA' },
                { id: 8247, name: 'KANGANGA' },
                { id: 8248, name: 'KARUKARE' },
                { id: 8249, name: 'KYABUKAMA' },
                { id: 8250, name: 'NYAMUSHEHSE' },
                { id: 8251, name: 'NYARUZINGA' },
                { id: 8252, name: 'NYARWANYA' },
                { id: 8253, name: 'ORUJEBE' },
                { id: 8254, name: 'RUGANDO' },
                { id: 8255, name: 'RWAKUTAKA' },
                { id: 8256, name: 'RWEMIRAMA' },
                { id: 8257, name: 'RWONGORA' },
              ],
            },
          ],
        },
        {
          id: 249,
          name: 'MITOOMA',
          parishes: [
            {
              id: 1171,
              name: 'IJUMO',
              villages: [
                { id: 8055, name: 'KAKO' },
                { id: 8054, name: 'KANJWIGA' },
                { id: 8056, name: 'KAZIKO' },
                { id: 8057, name: 'KIRAMBI I' },
                { id: 8058, name: 'KIRAMBI II' },
                { id: 8059, name: 'KIRAMBI III' },
                { id: 8060, name: 'NYAKABINGO' },
                { id: 8061, name: 'NYAKIIGA' },
                { id: 8062, name: 'RUSHOROZA' },
                { id: 8063, name: 'RWENTOOKYE I' },
                { id: 8064, name: 'RWENTOOYE II' },
                { id: 8065, name: 'RWIRARA I' },
                { id: 8066, name: 'RWIRARA II' },
              ],
            },
            {
              id: 1174,
              name: 'KATUNDA',
              villages: [
                { id: 8086, name: 'KABUGURUKA' },
                { id: 8087, name: 'KATUNDA A' },
                { id: 8088, name: 'KATUNDA B' },
                { id: 8089, name: 'KYANKUKWE' },
                { id: 8090, name: 'RUSHOROZA A' },
                { id: 8091, name: 'RUSHOROZA B' },
                { id: 8092, name: 'RUTOOMA II' },
                { id: 8093, name: 'RWEKITOOMA' },
              ],
            },
            {
              id: 1172,
              name: 'MUSHUNGA',
              villages: [
                { id: 8067, name: 'BUTAGASI' },
                { id: 8068, name: 'KIBINGO I' },
                { id: 8069, name: 'KIBINGO II' },
                { id: 8070, name: 'KIBINGO III' },
                { id: 8071, name: 'KIBINGO IV' },
                { id: 8072, name: 'KIRERA' },
                { id: 8073, name: 'NYAKAHITA' },
                { id: 8074, name: 'RUGABAGABA' },
                { id: 8075, name: 'RUKUNYU' },
                { id: 8076, name: 'RUTOOMA I' },
              ],
            },
            {
              id: 1175,
              name: 'NKINGA',
              villages: [
                { id: 8094, name: 'KAGABA A' },
                { id: 8095, name: 'KAGABA B' },
                { id: 8096, name: 'KICWAMBA A' },
                { id: 8097, name: 'KICWAMBA B' },
                { id: 8099, name: 'MITSIBIKA A' },
                { id: 8098, name: 'MITSIBIKA B' },
                { id: 8100, name: 'NKINGA A' },
                { id: 8101, name: 'NKINGA B' },
                { id: 8102, name: 'NTUNGAMO A' },
                { id: 8103, name: 'NTUNGAMO B' },
              ],
            },
            {
              id: 1173,
              name: 'NYAKISHOJWA',
              villages: [
                { id: 8077, name: 'KAASHA' },
                { id: 8078, name: 'KAROZA A' },
                { id: 8079, name: 'KAROZA B' },
                { id: 8080, name: 'KASHASHA' },
                { id: 8081, name: 'KIBISHO A' },
                { id: 8082, name: 'KIBISHO B' },
                { id: 8083, name: 'KIHUMURO' },
                { id: 8084, name: 'KIHUNGA' },
                { id: 8085, name: 'NYAKISHOJWA CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 255,
          name: 'MITOOMA TOWN COUNCIL',
          parishes: [
            {
              id: 1201,
              name: 'WARD I',
              villages: [
                { id: 8322, name: 'BUBAARE' },
                { id: 8323, name: 'BUHARAMBO A' },
                { id: 8324, name: 'BUHARAMBO B' },
                { id: 8326, name: 'KATOOMA' },
                { id: 8327, name: 'KYEMPOROGOMA' },
                { id: 8325, name: 'NYAKASHOJWA' },
              ],
            },
            {
              id: 1202,
              name: 'WARD II',
              villages: [
                { id: 8329, name: 'NSHENGA A' },
                { id: 8328, name: 'NSHENGA B' },
                { id: 8330, name: 'NYAKAHANDAGAZI A' },
                { id: 8331, name: 'NYAKAHANDAGAZI B' },
              ],
            },
            {
              id: 1203,
              name: 'WARD III',
              villages: [
                { id: 8334, name: 'KATAGATA A' },
                { id: 8332, name: 'KYEMENGO' },
                { id: 8333, name: 'RYAKAHIMBI' },
              ],
            },
            {
              id: 1204,
              name: 'WARD IV',
              villages: [
                { id: 8335, name: 'KATAGATA B' },
                { id: 8336, name: 'MITOOMA TOWN' },
              ],
            },
          ],
        },
        {
          id: 250,
          name: 'MUTARA',
          parishes: [
            {
              id: 1181,
              name: 'BIKUNGU',
              villages: [
                { id: 8141, name: 'AKATOJO' },
                { id: 8142, name: 'BUNYINYA' },
                { id: 8143, name: 'KYAKATANDA II' },
                { id: 8144, name: 'KYEIRAMA I' },
                { id: 8145, name: 'KYEIRAMA II' },
                { id: 8146, name: 'MUTARA T.C' },
                { id: 8147, name: 'OBUBARE I' },
                { id: 8148, name: 'OBUBARE II' },
                { id: 8149, name: 'RUNAZI I' },
                { id: 8150, name: 'RUNAZI II' },
              ],
            },
            {
              id: 1178,
              name: 'BUKONGORO',
              villages: [
                { id: 8113, name: 'BUKONGORO I' },
                { id: 8114, name: 'BUKONGORO III' },
                { id: 8115, name: 'BUKONGORO IV' },
                { id: 8116, name: 'BUKONGORO V' },
                { id: 8122, name: 'BUKONGORO VI' },
                { id: 8117, name: 'BWEYO' },
                { id: 8123, name: 'KASHOJWA' },
                { id: 8118, name: 'KINYEMI II' },
                { id: 8119, name: 'KINYEMI III' },
                { id: 8120, name: 'KIRERA I' },
                { id: 8121, name: 'KIRERA II' },
              ],
            },
            {
              id: 1176,
              name: 'ENSHAKA',
              villages: [
                { id: 8107, name: 'BUKUNGU' },
                { id: 8104, name: 'ENSHAKA' },
                { id: 8105, name: 'KISHANDA' },
                { id: 8106, name: 'KITWE' },
                { id: 64571, name: 'KYAKATANDA I' },
                { id: 8108, name: 'NYABICENCE' },
              ],
            },
            {
              id: 1182,
              name: 'FURUMA',
              villages: [
                { id: 8151, name: 'BUKONGORO II' },
                { id: 8152, name: 'FURUMA I' },
                { id: 8153, name: 'FURUMA II' },
                { id: 8154, name: 'FURUMA III' },
                { id: 8155, name: 'KINYEMI I' },
                { id: 8158, name: 'KYANYINIHI' },
                { id: 8159, name: 'MUTANOGA' },
                { id: 8156, name: 'MUTARA I' },
                { id: 8160, name: 'MUTARA II' },
                { id: 8157, name: 'RUTEETE' },
              ],
            },
            {
              id: 1177,
              name: 'KATAHO',
              villages: [
                { id: 68109, name: 'NYAKISHOJWA' },
                { id: 8109, name: 'NYARUZINGA' },
                { id: 8110, name: 'ORUBIRA' },
                { id: 8111, name: 'ORUHITA' },
                { id: 8112, name: 'RUTOOMA A' },
                { id: 70007, name: 'RUTOOMA B' },
              ],
            },
            {
              id: 1179,
              name: 'KYEIBARE',
              villages: [
                { id: 8134, name: 'KICERERE' },
                { id: 8124, name: 'KICWAMBA' },
                { id: 8125, name: 'KIHOONA' },
                { id: 8126, name: 'KITOJO' },
                { id: 8127, name: 'KYEIBARE CENTRAL' },
                { id: 8128, name: 'KYOBUKYERA' },
                { id: 8130, name: 'NKUKURU' },
                { id: 8129, name: 'NTEEKO' },
                { id: 8131, name: 'NYAKATUNTU' },
                { id: 8132, name: 'RUSHAMBYA' },
                { id: 8133, name: 'RWABAHESI' },
                { id: 8135, name: 'RWENKANJA' },
              ],
            },
            {
              id: 1183,
              name: 'MAHWIZI',
              villages: [
                { id: 8161, name: 'KIGABAGABA' },
                { id: 8163, name: 'KIRIRIMA' },
                { id: 8162, name: 'KYAMUHWA' },
                { id: 8166, name: 'MAHWIZI I' },
                { id: 8167, name: 'MAHWIZI II' },
                { id: 8168, name: 'NYAKABARE' },
                { id: 8164, name: 'NYAKITOKO' },
                { id: 8165, name: 'NYARWANYA' },
                { id: 8169, name: 'OMUKIBIRIZI' },
              ],
            },
            {
              id: 1184,
              name: 'NYAKIHITA',
              villages: [
                { id: 57706, name: 'AKAGAANA' },
                { id: 8172, name: 'KAGAANA' },
                { id: 8170, name: 'KYAMURUNGA' },
                { id: 8171, name: 'MUTAKA' },
                { id: 8173, name: 'NYAKIHITA' },
                { id: 8174, name: 'RWAKIKAMBUZI' },
                { id: 8175, name: 'RWANYANDERE' },
              ],
            },
            {
              id: 1180,
              name: 'RYAKITANGA',
              villages: [
                { id: 60216, name: 'BURAMA' },
                { id: 8137, name: 'NTUNGAMO' },
                { id: 8138, name: 'NYAKATONTOMA' },
                { id: 8136, name: 'NYAMATONGO III' },
                { id: 8139, name: 'NYARUSHAKA' },
                { id: 8140, name: 'RYAKITANGA CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 246,
          name: 'NYAKIZINGA',
          parishes: [
            {
              id: 1158,
              name: 'KIKANI',
              villages: [
                { id: 7955, name: 'IHUNGU' },
                { id: 7956, name: 'KABIRA' },
                { id: 7954, name: 'KIKANI B' },
                { id: 7957, name: 'KIKANI CENTRAL' },
                { id: 7958, name: 'KYARUKOBA' },
                { id: 7959, name: 'KYEITOKO' },
              ],
            },
            {
              id: 1157,
              name: 'MURAMBI',
              villages: [
                { id: 7950, name: 'KABAARE' },
                { id: 7948, name: 'KYEIHUMBA' },
                { id: 7951, name: 'MAAJU' },
                { id: 7952, name: 'MURAMBI' },
                { id: 7953, name: 'NTUNGAMO' },
                { id: 7949, name: 'RUSHA B' },
              ],
            },
            {
              id: 1160,
              name: 'MUTI',
              villages: [
                { id: 7966, name: 'BUGONGO' },
                { id: 7967, name: 'EKIKOKORA' },
                { id: 7970, name: 'KASHENSHERO A' },
                { id: 7968, name: 'KASHENSHERO B' },
                { id: 7969, name: 'KITOJO' },
                { id: 7971, name: 'KYAMPUNU' },
                { id: 7972, name: 'NYAMATONGO I' },
                { id: 68139, name: 'NYAMATONGO II' },
              ],
            },
            {
              id: 1159,
              name: 'NYAKIZINGA',
              villages: [
                { id: 7960, name: 'ENGARAMA' },
                { id: 7961, name: 'NYAKATUGUNDA' },
                { id: 7962, name: 'NYAKIZINGA' },
                { id: 7963, name: 'RURYENGYE' },
                { id: 7964, name: 'RUSHA A' },
                { id: 7965, name: 'RWENKUBA' },
              ],
            },
            {
              id: 1161,
              name: 'RUBIRIZI',
              villages: [
                { id: 7974, name: 'KABAHEESI' },
                { id: 64470, name: 'KYABAHESI' },
                { id: 7976, name: 'KYAKAHAMBA' },
                { id: 7978, name: 'RUBIRIZI A' },
                { id: 7973, name: 'RUBIRIZI B' },
                { id: 70006, name: 'RUTOOMA A' },
                { id: 7979, name: 'RUTOOMA B' },
                { id: 7975, name: 'RUTUGUNDA' },
                { id: 7977, name: 'RWAKARITU' },
              ],
            },
          ],
        },
        {
          id: 253,
          name: 'RUREHE',
          parishes: [
            {
              id: 1194,
              name: 'RUREHE SOUTH',
              villages: [
                { id: 8278, name: 'IRANGARA' },
                { id: 8279, name: 'KARIMONGORA' },
                { id: 8280, name: 'KASHAMWE' },
                { id: 8281, name: 'MURAMBI' },
                { id: 8282, name: 'NYABUTEMBE' },
                { id: 8283, name: 'NYAKANENGO' },
                { id: 8284, name: 'NYARUHITA' },
                { id: 8285, name: 'OMUBUBARE' },
                { id: 8286, name: 'OMUMWIINO' },
                { id: 8287, name: 'RUBANGA' },
                { id: 8288, name: 'RUBIRIZI' },
                { id: 8289, name: 'RUGARAMA' },
                { id: 8290, name: 'RWANYABUZANA' },
                { id: 8291, name: 'RWENKUBA' },
              ],
            },
            {
              id: 1196,
              name: 'RUTOOMA',
              villages: [
                { id: 8302, name: 'KABOROGOTA A' },
                { id: 8303, name: 'KABOROGOTA B' },
                { id: 8300, name: 'KIGIMBI C' },
                { id: 8301, name: 'KIGIMBI D' },
                { id: 8304, name: 'RUTOOMA A' },
                { id: 8305, name: 'RUTOOMA B' },
                { id: 8306, name: 'RUTOOMA C' },
              ],
            },
            {
              id: 1195,
              name: 'RWANJA WEST',
              villages: [
                { id: 8292, name: 'BUREBANE' },
                { id: 8293, name: 'KABUNGO' },
                { id: 8294, name: 'NTUNGAMO' },
                { id: 8295, name: 'NYAKINENG0' },
                { id: 8296, name: 'RUGOROGORO' },
                { id: 8297, name: 'RWAKITUURWA' },
                { id: 8298, name: 'RWAMUSHARIRA' },
                { id: 8299, name: 'RWANJA' },
              ],
            },
            {
              id: 1193,
              name: 'RYENGYERERO',
              villages: [
                { id: 8268, name: 'BUHASHA A I' },
                { id: 8269, name: 'BUHASHA A II' },
                { id: 8270, name: 'BUHASHA B I' },
                { id: 8271, name: 'BUHASHA B II' },
                { id: 8272, name: 'BUHASHA B III' },
                { id: 8273, name: 'KIGIMBI A' },
                { id: 8274, name: 'KIGIMBI B' },
                { id: 8275, name: 'RYENGYERERO A' },
                { id: 8276, name: 'RYENGYERERO B' },
                { id: 8277, name: 'RYENGYERERO C' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 46,
      name: 'RUHINDA NORTH COUNTY',
      sub_counties: [
        {
          id: 256,
          name: 'BITEREKO',
          parishes: [
            {
              id: 1208,
              name: 'BUGONGO',
              villages: [
                { id: 8367, name: 'BITEREKO T.C' },
                { id: 8368, name: 'BUGONGO CENTRAL' },
                { id: 8369, name: 'BUGONGO I' },
                { id: 8370, name: 'BUGONGO II' },
                { id: 8371, name: 'KAMABARE  II' },
                { id: 8372, name: 'NCWERA' },
                { id: 8373, name: 'NYAKANYINYA' },
                { id: 8374, name: 'NYAKINENGO' },
                { id: 8375, name: 'NYAMIYAGA' },
                { id: 8376, name: 'RWAKARUNGI' },
              ],
            },
            {
              id: 1205,
              name: 'BUSHEREGYENYI',
              villages: [
                { id: 8337, name: 'BUGOMORA I' },
                { id: 8338, name: 'BUGOMORA II' },
                { id: 8345, name: 'BUSHEREGYENY1' },
                { id: 8339, name: 'KAMABARE' },
                { id: 8340, name: 'KANYAMWATA' },
                { id: 8341, name: 'KASHOJWA' },
                { id: 8342, name: 'KEBIREMU' },
                { id: 8343, name: 'KYAMWEBYA' },
                { id: 8344, name: 'KYANTONDE' },
                { id: 8346, name: 'RUTSIRO' },
              ],
            },
            {
              id: 1209,
              name: 'KARANGARA',
              villages: [
                { id: 8377, name: 'KAMABARE' },
                { id: 8378, name: 'KAMAKORA' },
                { id: 8379, name: 'KARANGARA' },
                { id: 8380, name: 'KIYOORA' },
                { id: 8381, name: 'NYABUBARE  I' },
                { id: 8382, name: 'NYABUBARE  II' },
                { id: 8383, name: 'RUHUNGYE' },
                { id: 8384, name: 'RUSHEBEYA' },
              ],
            },
            {
              id: 1206,
              name: 'KARIMBIRO',
              villages: [
                { id: 8347, name: 'KABARE I' },
                { id: 8348, name: 'KABARE II' },
                { id: 8349, name: 'KARIMBIRO' },
                { id: 8350, name: 'KARISIZO' },
                { id: 8351, name: 'MAHUNGYE' },
                { id: 8352, name: 'MUKOKO' },
                { id: 8353, name: 'NYAKATOOMA' },
                { id: 8354, name: 'NYARUKONO' },
                { id: 8355, name: 'RUTOOMA' },
                { id: 8356, name: 'SANGA' },
              ],
            },
            {
              id: 1207,
              name: 'KIGARAMA',
              villages: [
                { id: 8357, name: 'KAMABARE  I' },
                { id: 8358, name: 'KANYABUKUNDU' },
                { id: 8359, name: 'KATWE I' },
                { id: 8360, name: 'KATWE II' },
                { id: 8361, name: 'KIGARAMA' },
                { id: 8362, name: 'KINIOGO' },
                { id: 8363, name: 'KITOJO' },
                { id: 8364, name: 'NYAMIKO' },
                { id: 8365, name: 'OMUBUREMBO' },
                { id: 8366, name: 'OMUKIBARE' },
              ],
            },
          ],
        },
        {
          id: 257,
          name: 'KANYABWANGA',
          parishes: [
            {
              id: 1214,
              name: 'BWERA',
              villages: [
                { id: 8422, name: 'BWERA A' },
                { id: 8423, name: 'BWERA B' },
                { id: 8426, name: 'BWERA C' },
                { id: 8424, name: 'KYABUZIGYE A' },
                { id: 8425, name: 'KYABUZIGYE B' },
                { id: 8427, name: 'NYANDAGO A' },
                { id: 8428, name: 'NYANDAGO B' },
                { id: 8431, name: 'NYANDAGO C' },
                { id: 8429, name: 'RWENSHAMA A' },
                { id: 8430, name: 'RWENSHAMA B' },
              ],
            },
            {
              id: 1210,
              name: 'KANYABWANGA',
              villages: [
                { id: 8385, name: 'KIBUNGO  IA' },
                { id: 8386, name: 'KIBUNGO  IB' },
                { id: 8387, name: 'KIBUNGO  II' },
                { id: 8388, name: 'KIGYENDE  IA' },
                { id: 8389, name: 'KIGYENDE  IB' },
                { id: 8390, name: 'KIGYENDE  II' },
                { id: 8391, name: 'KOBURUNGA' },
                { id: 8392, name: 'RUGAZI' },
              ],
            },
            {
              id: 1211,
              name: 'KASHONGORERO',
              villages: [
                { id: 8393, name: 'BWERA' },
                { id: 8396, name: 'KAHESHA' },
                { id: 8394, name: 'KAROKARUNGI A' },
                { id: 8395, name: 'KAROKARUNGI B' },
                { id: 8397, name: 'KASHONGORERO' },
                { id: 8398, name: 'RUGARAMA' },
                { id: 8399, name: 'RWENKURIJU A' },
                { id: 8400, name: 'RWENKURIJU B' },
              ],
            },
            {
              id: 1212,
              name: 'KATI',
              villages: [
                { id: 8402, name: 'KATI A' },
                { id: 8401, name: 'KATI B' },
                { id: 8403, name: 'KIGUNGA A' },
                { id: 8404, name: 'KIGUNGA B' },
                { id: 8405, name: 'KITAKA A' },
                { id: 8406, name: 'KITAKA B' },
                { id: 8407, name: 'RWAMUNIORI A' },
                { id: 8408, name: 'RWAMUNIORI B' },
                { id: 8409, name: 'RWENTOJO A' },
                { id: 8410, name: 'RWENTOJO B' },
                { id: 8411, name: 'RWENTOJO C' },
              ],
            },
            {
              id: 1213,
              name: 'RUCENCE',
              villages: [
                { id: 8412, name: 'KYABUZIGYE C' },
                { id: 8413, name: 'RUCENCE A' },
                { id: 8414, name: 'RUCENCE B' },
                { id: 8415, name: 'RWEBITUNDA A' },
                { id: 8416, name: 'RWEBITUNDA B' },
                { id: 8417, name: 'RWEBITUNDA C' },
                { id: 8418, name: 'RWEIBARE A' },
                { id: 8419, name: 'RWEIBARE B' },
                { id: 8420, name: 'RWEMPUNGU A' },
                { id: 8421, name: 'RWEMPUNGU B' },
              ],
            },
          ],
        },
        {
          id: 259,
          name: 'KIYANGA',
          parishes: [
            {
              id: 1220,
              name: 'IRARAMIRA',
              villages: [
                { id: 8462, name: 'BIKUNGU' },
                { id: 8463, name: 'IRARAMIRA CENTRAL' },
                { id: 8464, name: 'IRARAMIRA I' },
                { id: 8465, name: 'IRARAMIRA II' },
                { id: 8466, name: 'KABURARA' },
                { id: 8467, name: 'KATEIJA' },
                { id: 8468, name: 'NYAKAGYERA' },
                { id: 8469, name: 'RWAMURERA' },
              ],
            },
            {
              id: 1222,
              name: 'KAGATI',
              villages: [
                { id: 8479, name: 'KAFUNJO' },
                { id: 8481, name: 'KAIRABWA' },
                { id: 8480, name: 'KASHAMBYA' },
                { id: 8482, name: 'KYEMENGO' },
                { id: 8483, name: 'NYABUBAARE' },
                { id: 8484, name: 'NYAKASHEBEYA' },
                { id: 8485, name: 'RWOBURUNGA' },
                { id: 8486, name: 'SHERERE' },
              ],
            },
            {
              id: 1223,
              name: 'KASHASHA',
              villages: [
                { id: 8487, name: 'KANIAMPIHA' },
                { id: 8488, name: 'KASHASHA' },
                { id: 8489, name: 'KATANGYEMEKO' },
                { id: 8490, name: 'KIBAYA' },
                { id: 8491, name: 'KIBINGO' },
                { id: 8492, name: 'KIHUNGYE' },
                { id: 8493, name: 'NDURUMO' },
                { id: 8494, name: 'NKONGI' },
                { id: 8495, name: 'NYARUSHINYA' },
                { id: 8496, name: 'RURAMA' },
              ],
            },
            {
              id: 1219,
              name: 'KIYANGA',
              villages: [
                { id: 8450, name: 'BUKIRIRO I' },
                { id: 8451, name: 'BUKIRIRO II' },
                { id: 8452, name: 'KAGATI' },
                { id: 8453, name: 'KAKIMBA' },
                { id: 8454, name: 'KAMABARE' },
                { id: 8455, name: 'KIBISHWAMWIKA' },
                { id: 8456, name: 'KIRAMA' },
                { id: 8457, name: 'KISIIZI I' },
                { id: 8458, name: 'KISIIZI II' },
                { id: 8459, name: 'KYESHABO' },
                { id: 8460, name: 'NYANGA' },
                { id: 8461, name: 'RUTOBO' },
              ],
            },
            {
              id: 1221,
              name: 'RWOBURUNGA',
              villages: [
                { id: 8470, name: 'KAROKARUNGI' },
                { id: 8471, name: 'KENGYEYA' },
                { id: 8477, name: 'MUZINGA' },
                { id: 8472, name: 'NDURUMO' },
                { id: 8473, name: 'NYABYONDO' },
                { id: 8474, name: 'NYAKAGONGO' },
                { id: 8475, name: 'RUBAYA' },
                { id: 8476, name: 'RUSHOOROZA' },
                { id: 8478, name: 'RUZONGA' },
              ],
            },
          ],
        },
        {
          id: 258,
          name: 'RUTOOKYE TOWN COUNCIL',
          parishes: [
            {
              id: 1215,
              name: 'CENTRAL WARD',
              villages: [
                { id: 8432, name: 'KIHUMURO' },
                { id: 8433, name: 'KIMURI I' },
                { id: 8434, name: 'KIMURI II' },
                { id: 8435, name: 'NYERAMBIRE II' },
                { id: 8436, name: 'RUTOOKYE TRADING CENTRE' },
              ],
            },
            {
              id: 1217,
              name: 'KIBARE WARD',
              villages: [
                { id: 8440, name: 'KIBARE  I' },
                { id: 8441, name: 'KIBARE  II' },
                { id: 8442, name: 'NYAKAHANGA' },
                { id: 8443, name: 'RUTOOKYE III' },
                { id: 8444, name: 'SHERERE' },
              ],
            },
            {
              id: 1218,
              name: 'NYAKATSIRO WARD',
              villages: [
                { id: 8445, name: 'KAGOROGORO' },
                { id: 8446, name: 'KAKOMBE I' },
                { id: 8447, name: 'KAKOMBE II' },
                { id: 8448, name: 'NYERAMBIRE I' },
                { id: 8449, name: 'RUGARAMA' },
              ],
            },
            {
              id: 1216,
              name: 'SANGA WARD',
              villages: [
                { id: 8437, name: 'RUTOOKYE I' },
                { id: 70000, name: 'RUTOOKYE II' },
                { id: 8438, name: 'SANGA I' },
                { id: 8439, name: 'SANGA II' },
                { id: 70280, name: 'SANGA III' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
