import { District } from '../index';

export default {
  id: 96,
  name: 'MITYANA',
  counties: [
    {
      id: 236,
      name: 'BUSUJJU COUNTY',
      sub_counties: [
        {
          id: 1518,
          name: 'BBANDA',
          parishes: [
            {
              id: 7135,
              name: 'KAYANGA',
              villages: [
                { id: 44619, name: 'BUTAYUNJA' },
                { id: 44620, name: 'KAYANGA' },
                { id: 44621, name: 'KITWE' },
                { id: 44622, name: 'LUSALIRA' },
                { id: 44623, name: 'SINGA' },
              ],
            },
            {
              id: 7134,
              name: 'MPONGO',
              villages: [
                { id: 44613, name: 'BATUUSA' },
                { id: 44614, name: 'KABEERE' },
                { id: 44615, name: 'KAKUBANSIRI' },
                { id: 44612, name: 'KATATUULA' },
                { id: 44616, name: 'MISIMBA' },
                { id: 44617, name: 'MPONGO' },
                { id: 44618, name: 'SEETA' },
              ],
            },
          ],
        },
        {
          id: 1519,
          name: 'BBANDA TOWN COUNCIL',
          parishes: [
            {
              id: 7136,
              name: 'BBANDA WARD',
              villages: [
                { id: 44624, name: 'BBANDA' },
                { id: 44625, name: 'BUWALA A' },
                { id: 44626, name: 'BUWALA B' },
                { id: 44628, name: 'KYABOMBO' },
                { id: 44629, name: 'KYENGEZA' },
                { id: 44630, name: 'LUBIRA' },
                { id: 44627, name: 'MAWA' },
                { id: 44631, name: 'MAWANGA A' },
                { id: 44632, name: 'MAWANGA B' },
              ],
            },
            {
              id: 7137,
              name: 'BUZIBAZZI WARD',
              villages: [
                { id: 44633, name: 'BUZIBAZZI' },
                { id: 44635, name: 'KAKINDU' },
                { id: 44636, name: 'KANYOGOGA' },
                { id: 44637, name: 'NABAALE A' },
                { id: 44634, name: 'NABAALE/NSOMBA' },
                { id: 44638, name: 'NABIGAAGA' },
                { id: 44639, name: 'NAKASEETA' },
                { id: 44640, name: 'NAKIMPUNGE' },
              ],
            },
            {
              id: 7138,
              name: 'KANYALE WARD',
              villages: [
                { id: 44642, name: 'GAYAAZA' },
                { id: 44643, name: 'KALUNGU/BALA' },
                { id: 44644, name: 'KANYALE' },
                { id: 44645, name: 'KIREKU' },
                { id: 44646, name: 'MISINJUULA' },
                { id: 44647, name: 'NABUKONDO' },
                { id: 44648, name: 'NDIRAWERU' },
                { id: 44641, name: 'NKOKONJERU' },
              ],
            },
          ],
        },
        {
          id: 1514,
          name: 'BUTAYUNJA',
          parishes: [
            {
              id: 7115,
              name: 'KITEBERE',
              villages: [
                { id: 44477, name: 'BULENGE' },
                { id: 44478, name: 'KATEBERE' },
                { id: 44479, name: 'KITEBERE' },
              ],
            },
            {
              id: 7116,
              name: 'KITONGO',
              villages: [
                { id: 44480, name: 'BULUMA' },
                { id: 44481, name: 'KALEZI' },
                { id: 44482, name: 'KIGGWA' },
                { id: 44483, name: 'KIGOGOLO' },
                { id: 44484, name: 'KITONGO' },
                { id: 44485, name: 'KKANDE' },
                { id: 44486, name: 'MBUYE' },
                { id: 44487, name: 'NAKASUMBI' },
                { id: 44488, name: 'NSABWA' },
                { id: 44489, name: 'NTALANDA' },
              ],
            },
            {
              id: 7117,
              name: 'NAKAZIBA(GGAVU)',
              villages: [
                { id: 44490, name: 'GGAVU' },
                { id: 44491, name: 'KAKUNYU' },
                { id: 44492, name: 'NAKAZIBA' },
              ],
            },
            {
              id: 7118,
              name: 'NGANDWE',
              villages: [
                { id: 44493, name: 'BEKIINA  A' },
                { id: 44494, name: 'BEKIINA  B' },
                { id: 44495, name: 'BUTAYUNJA' },
                { id: 44496, name: 'NAWANGIRI' },
                { id: 44497, name: 'NGANDWE' },
              ],
            },
          ],
        },
        {
          id: 1515,
          name: 'KAKINDU',
          parishes: [
            {
              id: 7123,
              name: 'KAKINDU TOWN',
              villages: [
                { id: 44529, name: 'KAKINDU CHURCH ZONE' },
                { id: 44530, name: 'KAKINDU MALWA' },
                { id: 44531, name: 'KAKINDU TOWN' },
                { id: 44532, name: 'KASOZI GAYAZA' },
                { id: 44533, name: 'TTEGO LUGO' },
              ],
            },
            {
              id: 7119,
              name: 'MWERA',
              villages: [
                { id: 44498, name: 'BANANZE' },
                { id: 44499, name: 'KABONERWA' },
                { id: 44500, name: 'KIREKU BUGOLO' },
                { id: 44503, name: 'KITIDDIBULI' },
                { id: 44501, name: 'KIWANDE' },
                { id: 44502, name: 'MWERA' },
              ],
            },
            {
              id: 7120,
              name: 'NGUGULO',
              villages: [
                { id: 44504, name: 'BBUMBU' },
                { id: 44505, name: 'BETHANY CONVENT' },
                { id: 44506, name: 'GOMBE' },
                { id: 44507, name: 'KIKUUTA' },
                { id: 44508, name: 'MAYIRYE  A' },
                { id: 44509, name: 'MAYIRYE  B' },
                { id: 44510, name: 'MAYOBYO' },
                { id: 44513, name: 'MWANJALE' },
                { id: 44511, name: 'NGUGULO' },
                { id: 44512, name: 'NONVE/KASANA' },
              ],
            },
            {
              id: 7121,
              name: 'NSAMBYA',
              villages: [
                { id: 44514, name: 'BUBANZI' },
                { id: 44515, name: 'BUFUUMA' },
                { id: 44516, name: 'KALAMA' },
                { id: 44517, name: 'KAWANJUKI/KANYOGOGA' },
                { id: 44518, name: 'KIWOOYA BWEZA' },
                { id: 44519, name: 'NSAMBYA' },
                { id: 44521, name: 'TTUMBU' },
                { id: 44520, name: 'TTUULA' },
              ],
            },
            {
              id: 7122,
              name: 'VVUMBE',
              villages: [
                { id: 44522, name: 'BUKUNDUGULU' },
                { id: 44523, name: 'BUMBUGWE' },
                { id: 44528, name: 'BUTEGAAYA' },
                { id: 44524, name: 'MAWANDA KYENGEZA' },
                { id: 44525, name: 'MWERA-NAMPADWA' },
                { id: 44526, name: 'NABWIRI/KANGUNDU' },
                { id: 44527, name: 'VVUMBE KAZINGA' },
              ],
            },
          ],
        },
        {
          id: 1516,
          name: 'MAANYI',
          parishes: [
            {
              id: 7124,
              name: 'KASOTA',
              villages: [
                { id: 44534, name: 'BUNJAAYA' },
                { id: 44535, name: 'GGULWE  A' },
                { id: 44536, name: 'GGULWE  B' },
                { id: 44537, name: 'KASOTA' },
                { id: 44538, name: 'LUBAJJA  A' },
                { id: 44539, name: 'LUBAJJA  B' },
              ],
            },
            {
              id: 7125,
              name: 'KIMULI',
              villages: [
                { id: 44540, name: 'BUGOYE' },
                { id: 44541, name: 'GAYAZA' },
                { id: 44542, name: 'KIMULI' },
                { id: 44543, name: 'NAJJANANKUMBI' },
                { id: 44544, name: 'NKAZEBUKU' },
              ],
            },
            {
              id: 7128,
              name: 'KIVUVVU',
              villages: [
                { id: 44560, name: 'BUYOBE' },
                { id: 44561, name: 'BUYUKI' },
                { id: 44562, name: 'GULEJJA' },
                { id: 44563, name: 'KABAYENGA' },
                { id: 44564, name: 'KIVUVU' },
                { id: 44565, name: 'KYETUUZO' },
                { id: 44566, name: 'MAANYI' },
                { id: 44567, name: 'NAKULAMUDDE' },
                { id: 44559, name: 'NAMUNGOONA' },
              ],
            },
            {
              id: 7129,
              name: 'MISIGI',
              villages: [
                { id: 44568, name: 'LUGABO' },
                { id: 44569, name: 'LUTALO' },
                { id: 44570, name: 'MISIGI' },
                { id: 44571, name: 'NTEYAFA' },
                { id: 44572, name: 'SEETA' },
              ],
            },
            {
              id: 7126,
              name: 'NAMUTUNKU',
              villages: [
                { id: 44545, name: 'BUKOLA' },
                { id: 44546, name: 'JINJA' },
                { id: 44547, name: 'KAATO' },
                { id: 44548, name: 'KABIRA' },
                { id: 44549, name: 'KAJOJI' },
                { id: 44550, name: 'KIBUTO' },
                { id: 44551, name: 'MAYIRIKITI' },
                { id: 44552, name: 'NABAALE' },
                { id: 44553, name: 'NAMUTUNKU' },
              ],
            },
            {
              id: 7127,
              name: 'NFUMBYE',
              villages: [
                { id: 44554, name: 'BULABAKULU' },
                { id: 44555, name: 'BUWUNGA' },
                { id: 44556, name: 'KITTI' },
                { id: 44557, name: 'NDEESE' },
                { id: 44558, name: 'NFUMBYE' },
              ],
            },
            {
              id: 7130,
              name: 'SSERINYA',
              villages: [
                { id: 44573, name: 'KINONI  A' },
                { id: 44574, name: 'KINONI  B' },
                { id: 44575, name: 'KIZIMIZO' },
                { id: 44576, name: 'KYANDAALO  A' },
                { id: 44577, name: 'KYANDAALO  B' },
                { id: 44578, name: 'MABIRA' },
                { id: 44579, name: 'MIBANGWE' },
                { id: 44580, name: 'SSERINYA' },
              ],
            },
          ],
        },
        {
          id: 1517,
          name: 'MALANGALA',
          parishes: [
            {
              id: 7131,
              name: 'KANYANYA',
              villages: [
                { id: 44581, name: 'BBONGOLE' },
                { id: 44582, name: 'BUSENYA' },
                { id: 44583, name: 'KABYUMA  A' },
                { id: 44584, name: 'KABYUMA  B' },
                { id: 44585, name: 'KANYANYA  A' },
                { id: 44586, name: 'KANYANYA  B' },
                { id: 44587, name: 'KAYUNGA' },
                { id: 44588, name: 'LULUMBU  A' },
                { id: 44589, name: 'LULUMBU  B' },
                { id: 44590, name: 'NAMAYOVU  A' },
                { id: 44591, name: 'NAMAYOVU  B' },
                { id: 44592, name: 'NANDWAGUDDE' },
              ],
            },
            {
              id: 7132,
              name: 'KIWAWU',
              villages: [
                { id: 44593, name: 'BWESIGE' },
                { id: 44594, name: 'KAMULI' },
                { id: 44595, name: 'KASIBA' },
                { id: 44596, name: 'KAWANGA  I' },
                { id: 44597, name: 'KAWANGA  II' },
                { id: 44598, name: 'KAYUNGA' },
                { id: 44599, name: 'KAZINGA' },
                { id: 44600, name: 'KIWAWU' },
                { id: 44601, name: 'KYESENGEZE' },
                { id: 44602, name: 'MAGEZI/NTONYEZE' },
                { id: 44603, name: 'MALANGALA' },
              ],
            },
            {
              id: 7133,
              name: 'MAGONGA',
              villages: [
                { id: 44604, name: 'BBALA' },
                { id: 44605, name: 'DDAJJE' },
                { id: 44606, name: 'KIGOLOBA' },
                { id: 44607, name: 'KITTO' },
                { id: 44608, name: 'MAGONGA' },
                { id: 44609, name: 'MUBANGO' },
                { id: 44610, name: 'NNONO' },
                { id: 44611, name: 'NSIISI' },
              ],
            },
          ],
        },
        {
          id: 1520,
          name: 'ZIGOTI TOWN COUNCIL',
          parishes: [
            {
              id: 7140,
              name: 'NABATTU WARD',
              villages: [
                { id: 44658, name: 'KABAGGOLO  A' },
                { id: 44659, name: 'KABAGGOLO  B' },
                { id: 44660, name: 'KANJUKI' },
                { id: 44661, name: 'KYENGEZA' },
                { id: 44662, name: 'NABATTU' },
                { id: 44663, name: 'NALUBUDDE' },
                { id: 44664, name: 'NALUGAMBA' },
              ],
            },
            {
              id: 7139,
              name: 'ZIGOTI WARD',
              villages: [
                { id: 44649, name: 'KASALAGA  A' },
                { id: 44650, name: 'KASALAGA  B' },
                { id: 44651, name: 'KASOOZO' },
                { id: 44652, name: 'MABUYE/KABALUNGI' },
                { id: 44653, name: 'MAWUNDWE EAST' },
                { id: 44654, name: 'MAWUNDWE WEST' },
                { id: 44655, name: 'ZIGOTI  E' },
                { id: 44656, name: 'ZIGOTI  N' },
                { id: 44657, name: 'ZIGOTI  S' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 237,
      name: 'MITYANA COUNTY NORTH',
      sub_counties: [
        {
          id: 1521,
          name: 'BULERA',
          parishes: [
            {
              id: 7146,
              name: 'BAKIJULULA',
              villages: [
                { id: 44693, name: 'BAKIJJULULA' },
                { id: 44695, name: 'KIBIBI' },
                { id: 44694, name: 'NAMUNYANYULA' },
              ],
            },
            {
              id: 7147,
              name: 'BULAMU',
              villages: [
                { id: 44697, name: 'BULAMU' },
                { id: 44696, name: 'KAKONDE' },
                { id: 44698, name: 'KIBUTO' },
              ],
            },
            {
              id: 7141,
              name: 'BULERA',
              villages: [
                { id: 44665, name: 'BULERA' },
                { id: 44666, name: 'BUNNYA' },
                { id: 44667, name: 'LWAMBA' },
                { id: 44668, name: 'SENDA-KAKINDU' },
                { id: 44669, name: 'SSERUNGWANGU' },
              ],
            },
            {
              id: 7145,
              name: 'KIBAALE',
              villages: [
                { id: 44686, name: 'BOMBO' },
                { id: 44687, name: 'BULEEYA' },
                { id: 44688, name: 'BULIGIYA' },
                { id: 44690, name: 'BULWANYAMAYINJA' },
                { id: 44689, name: 'BUWALANTAMA' },
                { id: 44691, name: 'LUBANYI/KAYUNGA' },
                { id: 44692, name: 'LUSAANA' },
              ],
            },
            {
              id: 7148,
              name: 'KIBOGO',
              villages: [
                { id: 44699, name: 'KIBOGO' },
                { id: 44701, name: 'NAKATEMBE' },
                { id: 44702, name: 'NAMIWUNDA' },
                { id: 44700, name: 'NDAGI' },
              ],
            },
            {
              id: 7149,
              name: 'KITEMU',
              villages: [
                { id: 44703, name: 'KITEMU' },
                { id: 44704, name: 'NAKYERIIRA A' },
                { id: 44705, name: 'NAKYERIIRA B' },
                { id: 44706, name: 'NERONDEDDE' },
                { id: 44707, name: 'SANGALA' },
              ],
            },
            {
              id: 7143,
              name: 'LUSANJA',
              villages: [
                { id: 44676, name: 'KIBIKKA' },
                { id: 44679, name: 'KKONDE' },
                { id: 44677, name: 'LUSANJA' },
                { id: 44678, name: 'MWERERWE' },
              ],
            },
            {
              id: 7142,
              name: 'MISEEBE',
              villages: [
                { id: 44672, name: 'GEMA' },
                { id: 44670, name: 'LUBIRA' },
                { id: 44673, name: 'MISEEBE CENTRAL' },
                { id: 44671, name: 'NAJJA' },
                { id: 44674, name: 'NAMBUTE' },
                { id: 44675, name: 'NDAYIGA' },
              ],
            },
            {
              id: 7150,
              name: 'NABUMBUGU',
              villages: [
                { id: 44708, name: 'BUTALEEGA' },
                { id: 44709, name: 'KIWUJJA-BUYAMBI' },
                { id: 44710, name: 'LWOGERO' },
                { id: 44711, name: 'NABUMBUGU' },
              ],
            },
            {
              id: 7151,
              name: 'NALYANKANJA',
              villages: [
                { id: 44713, name: 'BUBAJWE' },
                { id: 44712, name: 'BUKOOKA' },
                { id: 44715, name: 'JJUNGWE' },
                { id: 44714, name: 'KYETUME' },
                { id: 44716, name: 'NABITI' },
                { id: 44717, name: 'NABUSOLO' },
                { id: 44718, name: 'NALYANKANJA' },
              ],
            },
            {
              id: 7144,
              name: 'NAMUTAMBA',
              villages: [
                { id: 44680, name: 'BUTUMBIIZI' },
                { id: 44681, name: 'KABUNGO' },
                { id: 44683, name: 'KIWANDA' },
                { id: 44684, name: 'KYETUME' },
                { id: 44685, name: 'LWEEYO' },
                { id: 44682, name: 'MBIRO' },
              ],
            },
            {
              id: 7152,
              name: 'NAMUTIDDE',
              villages: [
                { id: 44719, name: 'KIVUNAANA' },
                { id: 44720, name: 'NAMASENENE' },
                { id: 44721, name: 'NAMUTIDDE' },
                { id: 44722, name: 'NGONZA' },
              ],
            },
          ],
        },
        {
          id: 1523,
          name: 'KALANGAALO',
          parishes: [
            {
              id: 7167,
              name: 'BUJAAYU',
              villages: [
                { id: 44809, name: 'BUJAAYU' },
                { id: 44812, name: 'KASAMBYA' },
                { id: 44811, name: 'KIMULI' },
                { id: 44813, name: 'KIRYAMMULI' },
                { id: 44814, name: 'KITEGO' },
                { id: 44810, name: 'SERUNYONYI' },
              ],
            },
            {
              id: 7171,
              name: 'BUSEMBI',
              villages: [
                { id: 44832, name: 'BINAJJA' },
                { id: 44830, name: 'BUSEMBI' },
                { id: 44828, name: 'KIBALANGULO' },
                { id: 44833, name: 'KISIGALA' },
                { id: 44831, name: 'MAGOMA B' },
                { id: 44829, name: 'MAGOMA CENTRAL' },
              ],
            },
            {
              id: 7161,
              name: 'KALAMA',
              villages: [
                { id: 44781, name: 'KALAMA' },
                { id: 44783, name: 'KYEWANISE A' },
                { id: 44782, name: 'KYEWANISE B' },
                { id: 44784, name: 'MAYOBYO A' },
                { id: 44785, name: 'MAYOBYO B' },
                { id: 44786, name: 'MMAMBA' },
                { id: 44780, name: 'NALUGGI' },
              ],
            },
            {
              id: 7162,
              name: 'KALANGAALO',
              villages: [
                { id: 44788, name: 'KALAGALA' },
                { id: 44789, name: 'KALANGAALO' },
                { id: 44790, name: 'KYAMIGAVU' },
                { id: 44787, name: 'MABIBI' },
                { id: 44791, name: 'NAYISE' },
              ],
            },
            {
              id: 7168,
              name: 'KIKUBE',
              villages: [
                { id: 44815, name: 'KABUUKIRA' },
                { id: 44816, name: 'KIKUBE' },
                { id: 44817, name: 'KYAMANYOOLI' },
                { id: 44818, name: 'MIREMBE' },
              ],
            },
            {
              id: 7169,
              name: 'KIKUUTA',
              villages: [
                { id: 44819, name: 'FULULU' },
                { id: 44820, name: 'KIKUUTA' },
                { id: 44821, name: 'MUGOYE' },
              ],
            },
            {
              id: 7163,
              name: 'KIRYOKYA',
              villages: [
                { id: 44792, name: 'BUKUMULA' },
                { id: 44793, name: 'KIRYOKYA  A' },
                { id: 44794, name: 'KIRYOKYA  B' },
              ],
            },
            {
              id: 7164,
              name: 'KITEREDDE',
              villages: [
                { id: 44795, name: 'KIGO' },
                { id: 44796, name: 'KINONI' },
                { id: 44797, name: 'KITEREDDE' },
                { id: 44798, name: 'NAKAWERE' },
              ],
            },
            {
              id: 7165,
              name: 'KIYOGANYI',
              villages: [
                { id: 44799, name: 'BBOMBO' },
                { id: 44801, name: 'KAYONDO' },
                { id: 44802, name: 'KIYOGAANYI' },
                { id: 44803, name: 'LUGAZI A' },
                { id: 44800, name: 'LUGAZI B' },
              ],
            },
            {
              id: 7170,
              name: 'KYAMUSISI',
              villages: [
                { id: 44822, name: 'BUTEBE' },
                { id: 44824, name: 'KISOSONKOLE' },
                { id: 44825, name: 'KYAMUSISI' },
                { id: 44826, name: 'MAGALA' },
                { id: 44823, name: 'MUKAAGA' },
                { id: 44827, name: 'NALYAMAGONJA' },
              ],
            },
            {
              id: 7166,
              name: 'MUTETTEMA',
              villages: [
                { id: 44804, name: 'KITETAAGA' },
                { id: 44805, name: 'LUJAJI' },
                { id: 44806, name: 'MUTETEMA' },
                { id: 44807, name: 'NDEKUYAMUKUNGU' },
                { id: 44808, name: 'SIROBERA' },
              ],
            },
          ],
        },
        {
          id: 1522,
          name: 'KIKANDWA',
          parishes: [
            {
              id: 7153,
              name: 'BAMBULA',
              villages: [
                { id: 44723, name: 'BBAMBULA' },
                { id: 44724, name: 'GGAMBA' },
                { id: 44725, name: 'KABONGEZO' },
                { id: 44726, name: 'KASEJJERE' },
                { id: 44727, name: 'KAVULE' },
                { id: 44728, name: 'KIMANYA' },
                { id: 44729, name: 'KYASA' },
                { id: 44730, name: 'NAKASEETA' },
              ],
            },
            {
              id: 7154,
              name: 'KIKANDWA',
              villages: [
                { id: 44731, name: 'KABUMBA' },
                { id: 44732, name: 'KIKANDWA' },
                { id: 44733, name: 'KIZIGO' },
                { id: 44734, name: 'KYENGEZA' },
                { id: 44735, name: 'NABITEETE  A' },
                { id: 44736, name: 'NABITEETE  B' },
                { id: 44737, name: 'NABWENDO' },
              ],
            },
            {
              id: 7159,
              name: 'KIKUNYU',
              villages: [
                { id: 44764, name: 'KAJOJI' },
                { id: 44765, name: 'KIKUNYU' },
                { id: 44772, name: 'KITAMAVU' },
                { id: 44766, name: 'KITOTOLO' },
                { id: 44771, name: 'MBALALA' },
                { id: 44767, name: 'NAKITOOLA' },
                { id: 44768, name: 'NAMUDAALI' },
                { id: 44769, name: 'NSANGABWAMI' },
                { id: 44770, name: 'SSEBBANDA' },
              ],
            },
            {
              id: 7158,
              name: 'LUWUNGA',
              villages: [
                { id: 44757, name: 'BULEREJJE' },
                { id: 44758, name: 'KABULAMULIRO' },
                { id: 44759, name: 'KAKINGA' },
                { id: 44760, name: 'LUWUNGA' },
                { id: 44761, name: 'MASIRIBA' },
                { id: 44763, name: 'NAKATOOKE' },
                { id: 44762, name: 'NAKAZIBA' },
              ],
            },
            {
              id: 7155,
              name: 'NAKWAYA',
              villages: [
                { id: 44738, name: 'BBOMBO' },
                { id: 44739, name: 'KITONYA' },
                { id: 44744, name: 'KITUUMA' },
                { id: 44740, name: 'LUKUGA' },
                { id: 44741, name: 'NAKWAYA  A' },
                { id: 44742, name: 'NAKWAYA  B' },
                { id: 44743, name: 'WABINYIRA' },
              ],
            },
            {
              id: 7156,
              name: 'NAMIGAVU',
              villages: [
                { id: 44750, name: 'KANYALE' },
                { id: 44745, name: 'KIBISI' },
                { id: 44746, name: 'NAMATABA' },
                { id: 44747, name: 'NAMIGAVU' },
                { id: 44748, name: 'NANZIRUGADDE' },
                { id: 44749, name: 'SSETTUMBA' },
              ],
            },
            {
              id: 7157,
              name: 'NAMWENE',
              villages: [
                { id: 44751, name: 'KALYANGO' },
                { id: 44752, name: 'KAWANSENYI' },
                { id: 44753, name: 'LUKIRIBI' },
                { id: 44754, name: 'NAKASEETA' },
                { id: 44755, name: 'WABIYINJA  I' },
                { id: 44756, name: 'WABIYINJA  II' },
              ],
            },
            {
              id: 7160,
              name: 'WATTUBA',
              villages: [
                { id: 44773, name: 'KASAMBYA' },
                { id: 44774, name: 'KYERIMA' },
                { id: 44775, name: 'MATTE' },
                { id: 44776, name: 'NAMUZIKIZA' },
                { id: 44777, name: 'NANA' },
                { id: 44779, name: 'WANGOMA' },
                { id: 44778, name: 'WATTUBA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 238,
      name: 'MITYANA COUNTY SOUTH',
      sub_counties: [
        {
          id: 1527,
          name: 'BUSUNJU TOWN COUNCIL',
          parishes: [
            {
              id: 7188,
              name: 'CENTRAL WARD',
              villages: [
                { id: 44937, name: 'BUSUNJU A' },
                { id: 44938, name: 'BUSUNJU B' },
                { id: 44939, name: 'BUSUNJU C' },
                { id: 44940, name: 'BUSUNJU D' },
              ],
            },
            {
              id: 7189,
              name: 'NORTH WARD',
              villages: [
                { id: 44942, name: 'KAWAFU' },
                { id: 44941, name: 'KAWOOMYA' },
                { id: 44943, name: 'KIDUUZI' },
                { id: 44944, name: 'NALUKWAKULA' },
              ],
            },
            {
              id: 7186,
              name: 'SOUTH WARD',
              villages: [
                { id: 44932, name: 'NAMULAMBA A' },
                { id: 44933, name: 'NAMULAMBA B' },
              ],
            },
            {
              id: 7187,
              name: 'WEST WARD',
              villages: [
                { id: 44935, name: 'KIBUBULA A' },
                { id: 44934, name: 'KIBUBULA B' },
                { id: 44936, name: 'KIBUBULA C' },
              ],
            },
          ],
        },
        {
          id: 1525,
          name: 'NAMUNGO',
          parishes: [
            {
              id: 7176,
              name: 'KASANGULA',
              villages: [
                { id: 44861, name: 'KASANGULA  A' },
                { id: 44862, name: 'KASANGULA  B' },
                { id: 44863, name: 'KITAVUJJA' },
                { id: 44864, name: 'NAKIRAGALA' },
                { id: 44865, name: 'NAMASENENE' },
              ],
            },
            {
              id: 7177,
              name: 'KISAANA',
              villages: [
                { id: 44866, name: 'KAWOLONGOJJO' },
                { id: 44867, name: 'KIKONGE' },
                { id: 44868, name: 'KISAANA  A' },
                { id: 44869, name: 'KISAANA  B' },
                { id: 44870, name: 'NAKABAZZI' },
                { id: 44871, name: 'SAMBA' },
                { id: 44872, name: 'SSESE' },
              ],
            },
            {
              id: 7180,
              name: 'KITEETE',
              villages: [
                { id: 44886, name: 'BUTALE' },
                { id: 44887, name: 'BUWALULA  A' },
                { id: 44888, name: 'BUWALULA  B' },
                { id: 44889, name: 'DDAVULA' },
                { id: 44890, name: 'KITEETE' },
                { id: 44891, name: 'MULAMBAALO' },
                { id: 44892, name: 'NAKINYUGUZI' },
              ],
            },
            {
              id: 7178,
              name: 'MPIRIGWA',
              villages: [
                { id: 44873, name: 'BWESIGE' },
                { id: 44874, name: 'KANYOGOGA' },
                { id: 44875, name: 'KITEREDDE' },
                { id: 44876, name: 'MPIRIGGWA  A' },
                { id: 44877, name: 'MPIRIGGWA  B' },
                { id: 44878, name: 'NABUTAKA' },
                { id: 44879, name: 'ZZIRA' },
              ],
            },
            {
              id: 7181,
              name: 'MUGULU',
              villages: [
                { id: 44893, name: 'BUKALAKAMBA' },
                { id: 44894, name: 'BUTEYONGERA' },
                { id: 44895, name: 'KITO' },
                { id: 44896, name: 'NAKWANGU' },
                { id: 44897, name: 'NAMUGULU' },
              ],
            },
            {
              id: 7179,
              name: 'NAMUNGO',
              villages: [
                { id: 44880, name: 'BULAMU' },
                { id: 44881, name: 'DDUNDU' },
                { id: 44882, name: 'KAKOOLA' },
                { id: 44883, name: 'LUNYOLYA' },
                { id: 44884, name: 'NAMUNGO' },
                { id: 44885, name: 'WALUJJO' },
              ],
            },
          ],
        },
        {
          id: 1524,
          name: 'SSEKANYONYI',
          parishes: [
            {
              id: 7172,
              name: 'BUKOOBA',
              villages: [
                { id: 44834, name: 'BUKOOBA' },
                { id: 44837, name: 'KANYOGOGA' },
                { id: 44838, name: 'KASENENE' },
                { id: 44839, name: 'KIWAMIREMBE' },
                { id: 44835, name: 'KYAMPISI' },
                { id: 44840, name: 'LUKINGIRIDDE' },
                { id: 44836, name: 'LUTEETE' },
                { id: 44841, name: 'NAKILAGALA' },
              ],
            },
            {
              id: 7173,
              name: 'KAGEREKAMU',
              villages: [
                { id: 44843, name: 'GGOMBE' },
                { id: 44844, name: 'KABASEKE' },
                { id: 44845, name: 'KAGEREKAMU' },
                { id: 44846, name: 'KATIITI' },
                { id: 44847, name: 'KAWAALA' },
                { id: 44848, name: 'KYAKKOSI' },
                { id: 44842, name: 'ZZIGI' },
              ],
            },
            {
              id: 7175,
              name: 'KASIKOMBE',
              villages: [
                { id: 44856, name: 'BUDIMBO' },
                { id: 44857, name: 'BUMBU' },
                { id: 44858, name: 'KASIIKOMBE' },
                { id: 44859, name: 'KISAMBA' },
                { id: 44860, name: 'NJAGALA MWENGE' },
              ],
            },
            {
              id: 7174,
              name: 'MAGALA',
              villages: [
                { id: 44851, name: 'KALAGALA' },
                { id: 44852, name: 'KIREKA' },
                { id: 44849, name: 'KYAGALANYI' },
                { id: 44853, name: 'MAGALA' },
                { id: 44854, name: 'MONDE' },
                { id: 44850, name: 'NAJJANANKUMBI' },
                { id: 44855, name: 'NKUUBI' },
              ],
            },
          ],
        },
        {
          id: 1526,
          name: 'SSEKANYONYI TOWN COUNCIL',
          parishes: [
            {
              id: 7183,
              name: 'BULYANKUYEGE WARD',
              villages: [
                { id: 44905, name: 'BULYANKUYEGE' },
                { id: 44906, name: 'BYAMUTUNDA' },
                { id: 44907, name: 'KIJJUDDE  A' },
                { id: 44908, name: 'KIJJUDDE  B' },
                { id: 44909, name: 'KITO' },
                { id: 44910, name: 'LUGEYE' },
                { id: 44911, name: 'VVUNAMBA' },
              ],
            },
            {
              id: 7182,
              name: 'KABBEGA WARD',
              villages: [
                { id: 44899, name: 'KABBEGA' },
                { id: 44900, name: 'KAZINGA' },
                { id: 44901, name: 'KIWEEKA' },
                { id: 44902, name: 'MAKOBA' },
                { id: 44898, name: 'NAKASERO' },
                { id: 44903, name: 'NAKIRYA' },
                { id: 44904, name: 'SSEBOBBO' },
              ],
            },
            {
              id: 7185,
              name: 'KYETUME WARD',
              villages: [
                { id: 44927, name: 'BUTEGA' },
                { id: 44926, name: 'KIBANYI' },
                { id: 44928, name: 'KYETUME' },
                { id: 44929, name: 'LUKAKA' },
                { id: 44930, name: 'NAMUKOMAGO' },
                { id: 44931, name: 'SULIYA' },
              ],
            },
            {
              id: 7184,
              name: 'SSEKANYONYI WARD',
              villages: [
                { id: 44912, name: 'BBIRA  A' },
                { id: 44913, name: 'BBIRA  B' },
                { id: 44914, name: 'BUTALALE A' },
                { id: 44923, name: 'BUTALALE B' },
                { id: 44916, name: 'KASIRYE' },
                { id: 44915, name: 'KASWI' },
                { id: 44918, name: 'KITAVUJJA' },
                { id: 44917, name: 'KITTANSWA' },
                { id: 44919, name: 'LUGUZI' },
                { id: 44920, name: 'LUWONVU  A' },
                { id: 44921, name: 'LUWONVU  B' },
                { id: 44924, name: 'MAKAJJO BARRACKS' },
                { id: 44922, name: 'SEKANYONYI A' },
                { id: 44925, name: 'SEKANYONYI B' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 239,
      name: 'MITYANA MUNICIPALITY',
      sub_counties: [
        {
          id: 1528,
          name: 'BUSIMBI DIVISION',
          parishes: [
            {
              id: 7193,
              name: 'EAST WARD',
              villages: [
                { id: 44979, name: 'BUSIMBI GOMBOLOLA AREA' },
                { id: 44981, name: 'BUSIMBI RAILWAY' },
                { id: 44980, name: 'BUSIMBI/KASIMBI' },
                { id: 44982, name: 'KIBIBI GARAGE A' },
                { id: 44983, name: 'KIBIBI GARAGE B' },
                { id: 44984, name: 'KIYINDA A' },
                { id: 44985, name: 'KIYINDA B' },
                { id: 44986, name: 'MUSALABA ZONE' },
              ],
            },
            {
              id: 7190,
              name: 'KIREKU WARD',
              villages: [
                { id: 44945, name: 'BUWAALI' },
                { id: 44946, name: 'KATEETE' },
                { id: 44947, name: 'KAWOKO/WABISWA' },
                { id: 44948, name: 'KIGOGOZI' },
                { id: 44949, name: 'KIREKU' },
                { id: 44950, name: 'KITEMAMBAZZI' },
                { id: 44951, name: 'LUBANJA/GUNDA' },
                { id: 44952, name: 'LUCACA' },
                { id: 44953, name: 'NZUNGA/TTABA' },
                { id: 44954, name: 'ZIRIBANDA/NAMAJIRI' },
              ],
            },
            {
              id: 7191,
              name: 'NAAMA WARD',
              villages: [
                { id: 44955, name: 'BUSINZIGO  A' },
                { id: 44956, name: 'BUSINZIGO  B' },
                { id: 44957, name: 'BUSUNDO - MPANGA' },
                { id: 44958, name: 'BUSUNDO A' },
                { id: 44959, name: 'GOMBE KYALO' },
                { id: 44960, name: 'GOMBE MWALO' },
                { id: 44961, name: 'KALAMBA' },
                { id: 44962, name: 'KATIKO A' },
                { id: 44963, name: 'KATIKO B' },
                { id: 44964, name: 'LUSUNDO' },
                { id: 44965, name: 'MUJUMBULA' },
                { id: 44966, name: 'NAAMA  A' },
                { id: 44967, name: 'NAAMA CENTRAL' },
                { id: 44968, name: 'NALUGAZI' },
              ],
            },
            {
              id: 7192,
              name: 'NAKASEETA WARD',
              villages: [
                { id: 44969, name: 'DDANYA' },
                { id: 44970, name: 'KALAGI' },
                { id: 44971, name: 'KANYOMU' },
                { id: 44972, name: 'KIKONGE/KAKUNKWE' },
                { id: 44973, name: 'KISULE' },
                { id: 44974, name: 'KUNYWA  A' },
                { id: 44975, name: 'KUNYWA  B' },
                { id: 44976, name: 'LUKYAMU' },
                { id: 44977, name: 'NAKASEETA' },
                { id: 44978, name: 'TTUMBU/KIRYAGONJA' },
              ],
            },
            {
              id: 7194,
              name: 'NORTH WARD',
              villages: [
                { id: 44987, name: 'BBUYE/KIKUMBI' },
                { id: 44988, name: 'BUSWABULONGO' },
                { id: 44989, name: 'KATAKALA A' },
                { id: 44990, name: 'KIKUMBI LC 1' },
                { id: 44991, name: 'KINVUNIKIDDE' },
                { id: 44992, name: 'MIZIGO A' },
                { id: 44993, name: 'MIZIGO B' },
              ],
            },
          ],
        },
        {
          id: 1529,
          name: 'CENTRAL DIVISION',
          parishes: [
            {
              id: 7197,
              name: 'CENTRAL WARD',
              villages: [
                { id: 45013, name: 'AGIP AREA' },
                { id: 45014, name: 'BUSIMBI CENTRAL A' },
                { id: 45015, name: 'BUSIMBI CENTRAL B' },
                { id: 45016, name: 'BUSIMBI CENTRAL C' },
                { id: 45017, name: 'HOSPITAL AREA' },
                { id: 45018, name: 'KAMPALA ROAD' },
                { id: 45019, name: 'KIYUDAYA' },
                { id: 45020, name: 'THOBAN ROAD' },
              ],
            },
            {
              id: 7195,
              name: 'KATAKALA WARD',
              villages: [
                { id: 44994, name: 'BAMUNANIKA' },
                { id: 44995, name: 'BUKANAGA' },
                { id: 44996, name: 'KANNAMBA' },
                { id: 44997, name: 'KANSULETI' },
                { id: 44998, name: 'KATAKALA - KIDE' },
                { id: 44999, name: 'KIKUMBI - KABA' },
                { id: 45000, name: 'MAGONGOLO' },
                { id: 45001, name: 'NAMAMONDE' },
                { id: 45002, name: 'NANYONGA' },
                { id: 45003, name: 'NKONYA' },
              ],
            },
            {
              id: 7196,
              name: 'NAKIBANGA WARD',
              villages: [
                { id: 45004, name: 'BUTEBI  A' },
                { id: 45005, name: 'BUTEBI  B' },
                { id: 45006, name: 'KABANDA' },
                { id: 45007, name: 'KIWEREZA' },
                { id: 45008, name: 'LULAGALA' },
                { id: 45009, name: 'NAKIBANGA  A' },
                { id: 45010, name: 'NAKIBANGA  B' },
                { id: 45011, name: 'NAMBALE' },
                { id: 45012, name: 'NYANZI' },
              ],
            },
            {
              id: 7198,
              name: 'WEST WARD',
              villages: [
                { id: 45021, name: 'KANNAMBA D.F.I.' },
                { id: 45022, name: 'KAYUNGA CENTRAL' },
                { id: 45023, name: 'KAYUNGA KIGOGWA' },
                { id: 45024, name: 'KAYUNGA KIMEMETTE' },
                { id: 45025, name: 'MITYANA A KATOVU' },
                { id: 45026, name: 'MITYANA CENTRAL' },
                { id: 45027, name: 'NAMUKOZI CENTRAL' },
                { id: 45028, name: 'NAMUKOZI EAST' },
                { id: 45029, name: 'NAMUKOZI WEST' },
              ],
            },
          ],
        },
        {
          id: 1530,
          name: 'TTAMU DIVISION',
          parishes: [
            {
              id: 7204,
              name: 'BUSUBIZI WARD',
              villages: [
                { id: 45079, name: 'BUNYOLO/BUTEGA' },
                { id: 45080, name: 'BUSUUBIZI' },
                { id: 45081, name: 'GINGO' },
                { id: 45082, name: 'KAMBUZI' },
                { id: 45083, name: 'KIGANWA' },
                { id: 45084, name: 'KIRUNGU' },
                { id: 45085, name: 'KISAAWA/BUTEGA' },
                { id: 45086, name: 'MBALE' },
                { id: 45087, name: 'MITIMBOJJE' },
                { id: 45088, name: 'NTIKIDE/BUTEGA' },
              ],
            },
            {
              id: 7199,
              name: 'KABULE WARD',
              villages: [
                { id: 45030, name: 'KABULE' },
                { id: 45031, name: 'MAWONVU' },
                { id: 45032, name: 'MIGGO' },
                { id: 45033, name: 'NAKITOLO' },
                { id: 45034, name: 'NAMALELE/BULIGWA' },
                { id: 45035, name: 'NKWALE' },
                { id: 45036, name: 'SAALA  A' },
                { id: 45037, name: 'SAALA  B' },
                { id: 45038, name: 'SSEETA/BUWUNDA' },
              ],
            },
            {
              id: 7200,
              name: 'KABUWAMBO WARD',
              villages: [
                { id: 45039, name: 'BUGABO' },
                { id: 45040, name: 'BUWAALI' },
                { id: 45041, name: 'KABUWAMBO EAST' },
                { id: 45042, name: 'KIRIMA' },
                { id: 45043, name: 'KIWAMIREMBE' },
                { id: 45044, name: 'KYAZIZA' },
                { id: 45045, name: 'LUBIRA' },
                { id: 45046, name: 'LULERE' },
                { id: 45047, name: 'NAMYESO' },
                { id: 45048, name: 'NANDEGEJJA' },
                { id: 45049, name: 'NGANJO' },
              ],
            },
            {
              id: 7203,
              name: 'SOUTH WARD',
              villages: [
                { id: 45073, name: 'BUTEGA TOWN' },
                { id: 45074, name: 'KIKUMAMBOGO' },
                { id: 45075, name: 'KIWEESA' },
                { id: 45076, name: 'MAGALA A' },
                { id: 45077, name: 'MAGALA B' },
                { id: 45078, name: 'WABIGALO' },
              ],
            },
            {
              id: 7201,
              name: 'TTAMU WARD',
              villages: [
                { id: 45050, name: 'BUSERE A' },
                { id: 45051, name: 'BUSERE B' },
                { id: 45052, name: 'GGINZI' },
                { id: 45053, name: 'KAMUVOOBE' },
                { id: 45054, name: 'KITINKOKOLA A' },
                { id: 45055, name: 'KITINKOKOLA B' },
                { id: 45056, name: 'KITO/GAYAZA' },
                { id: 45057, name: 'KIWEEBYA' },
                { id: 45058, name: 'MBALIGA' },
                { id: 45059, name: 'MINANA/GALABI' },
                { id: 45060, name: 'MPANGA' },
                { id: 45061, name: 'NDIBULUNGI' },
                { id: 45062, name: 'TTAMU A' },
                { id: 45063, name: 'TTAMU B' },
                { id: 45064, name: 'TTAMU C' },
              ],
            },
            {
              id: 7202,
              name: 'TTANDA WARD',
              villages: [
                { id: 45065, name: 'BUKONGO' },
                { id: 45066, name: 'KISITA' },
                { id: 45067, name: 'KIWAMBYA' },
                { id: 45069, name: 'NAKABISO' },
                { id: 45068, name: 'NAKANYENYA' },
                { id: 45070, name: 'NAKITOLO' },
                { id: 45071, name: 'NAMAYUNJU' },
                { id: 45072, name: 'TTANDA' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
