import { District } from '../types';

export default {
  id: 58,
  name: 'MPIGI',
  counties: [
    {
      id: 134,
      name: 'MAWOKOTA COUNTY NORTH',
      sub_counties: [
        {
          id: 824,
          name: 'KAMMENGO',
          parishes: [
            {
              id: 3812,
              name: 'BUTOOLO',
              villages: [
                { id: 24321, name: 'BUWE A' },
                { id: 24322, name: 'BUWE B' },
                { id: 24323, name: 'DDERA' },
                { id: 24324, name: 'KAMUSOGONYA' },
                { id: 24325, name: 'KIRYAMBIDDE' },
                { id: 24326, name: 'MAKUMBI' },
                { id: 24327, name: 'NJERU' },
                { id: 24328, name: 'NSASA' },
                { id: 24329, name: 'SSENERO' },
              ],
            },
            {
              id: 3813,
              name: 'KAMMENGO',
              villages: [
                { id: 24330, name: 'BULEMBO' },
                { id: 24331, name: 'BWAMURAMIRA' },
                { id: 24332, name: 'FUNVU' },
                { id: 24333, name: 'KAMMENGO A' },
                { id: 24334, name: 'KAMMENGO B' },
                { id: 24335, name: 'KASA' },
                { id: 24336, name: 'KISWA A' },
                { id: 24337, name: 'KISWA B' },
                { id: 24338, name: 'LUKANGO' },
                { id: 24339, name: 'NABBUZI' },
                { id: 24340, name: 'NDODDO' },
                { id: 24341, name: 'SSEETA-GOLI' },
              ],
            },
            {
              id: 3814,
              name: 'KANYIKE',
              villages: [
                { id: 24342, name: 'BUTENGA' },
                { id: 24343, name: 'GGUNDA' },
                { id: 24344, name: 'KANYIKE A' },
                { id: 24345, name: 'KANYIKE B' },
                { id: 24346, name: 'KATABA' },
                { id: 24347, name: 'KAWEERI' },
                { id: 24348, name: 'KIBISI' },
                { id: 24349, name: 'KIKUNYU A' },
                { id: 24350, name: 'KIKUNYU B' },
                { id: 24351, name: 'LUNYERERE' },
                { id: 24352, name: 'NALUWEMBE' },
              ],
            },
            {
              id: 3815,
              name: 'KYANJA',
              villages: [
                { id: 24353, name: 'BANGA' },
                { id: 24354, name: 'BUBUULE' },
                { id: 24355, name: 'BUGABO' },
                { id: 24356, name: 'BUKOOZA' },
                { id: 24357, name: 'GGOMBE' },
                { id: 24358, name: 'KADAKIRO' },
                { id: 24359, name: 'KATWE' },
                { id: 24360, name: 'KIBUYE' },
                { id: 24361, name: 'KWABA-KABIRA' },
                { id: 24362, name: 'NAMBI' },
              ],
            },
            {
              id: 3816,
              name: 'LUWALA',
              villages: [
                { id: 24363, name: 'BUSERO' },
                { id: 24364, name: 'BUZUNGU' },
                { id: 24365, name: 'KIWUMU A' },
                { id: 24366, name: 'KIWUMU B' },
                { id: 24367, name: 'LUWALA' },
                { id: 24368, name: 'MASAKA' },
              ],
            },
            {
              id: 3817,
              name: 'LWAGGWA/KIBAANGA',
              villages: [
                { id: 24369, name: 'KIBANGA' },
                { id: 24370, name: 'KITI' },
                { id: 24371, name: 'LUGADA' },
                { id: 24372, name: 'LWAGGWA' },
                { id: 24373, name: 'MPONDWE' },
                { id: 24374, name: 'NABISAGO' },
                { id: 24375, name: 'SSIGI' },
              ],
            },
            {
              id: 3819,
              name: 'MUSA',
              villages: [
                { id: 24386, name: 'BBAALE' },
                { id: 24387, name: 'BUKABI' },
                { id: 24388, name: 'BUKAGOLO' },
                { id: 24389, name: 'BUYIGA A' },
                { id: 24390, name: 'BUYIGA B' },
                { id: 24391, name: 'KIGO' },
                { id: 24392, name: 'LUUBU' },
                { id: 24393, name: 'MASAAZI' },
                { id: 24394, name: 'MAYIRIKITI' },
                { id: 24395, name: 'MUSA' },
                { id: 24396, name: 'NAMAYUKI' },
                { id: 24397, name: 'NSUMBA A' },
                { id: 24398, name: 'NSUMBA B' },
                { id: 24399, name: 'SSAMMA' },
                { id: 24400, name: 'SSERINYABBI' },
              ],
            },
            {
              id: 3818,
              name: 'MUYIRA',
              villages: [
                { id: 24376, name: 'BULOWA' },
                { id: 24377, name: 'BWANSULE' },
                { id: 24378, name: 'KAJJAGA' },
                { id: 24379, name: 'KAMPIRINGISA' },
                { id: 24380, name: 'MAGEJJO' },
                { id: 24381, name: 'MBUTTE' },
                { id: 24382, name: 'MUYIRA' },
                { id: 24383, name: 'MWEREKE' },
                { id: 24384, name: 'NABYEWANGA' },
                { id: 24385, name: 'NALUWEMBE' },
              ],
            },
          ],
        },
        {
          id: 825,
          name: 'KIRINGENTE',
          parishes: [
            {
              id: 3820,
              name: 'KAVULE',
              villages: [
                { id: 24401, name: 'KATENDE/KIWAMIREMBE' },
                { id: 24402, name: 'KAVULE' },
                { id: 24403, name: 'KYAMBIZZI/BULANSUKU' },
                { id: 24404, name: 'NAKABISO' },
              ],
            },
            {
              id: 3821,
              name: 'KIKONDO',
              villages: [
                { id: 24405, name: 'KATABA' },
                { id: 24406, name: 'KIKONDO' },
                { id: 24407, name: 'MABANGA' },
                { id: 24408, name: 'NAKIREBE' },
                { id: 24409, name: 'NAMUTAMALA' },
                { id: 24410, name: 'NATWAALA' },
                { id: 24411, name: 'NSUJJUWE' },
              ],
            },
            {
              id: 3823,
              name: 'KIRINGENTE',
              villages: [
                { id: 24414, name: 'KAGEZI' },
                { id: 24415, name: 'LUVUMBULA' },
                { id: 24416, name: 'NNAMA' },
              ],
            },
            {
              id: 3822,
              name: 'KOLOLO',
              villages: [
                { id: 24412, name: 'KOLOLO/KYEYITABYA' },
                { id: 24413, name: 'NSUJJUMPOLWE' },
              ],
            },
            {
              id: 3824,
              name: 'SEKIWUNGA',
              villages: [
                { id: 24417, name: 'GALATIYA' },
                { id: 24418, name: 'KAGGABA' },
                { id: 24419, name: 'MABUYE' },
                { id: 24420, name: 'SEKIWUNGA' },
              ],
            },
          ],
        },
        {
          id: 826,
          name: 'MPIGI TOWN COUNCIL',
          parishes: [
            {
              id: 3825,
              name: 'BUMOOZI WARD',
              villages: [
                { id: 24421, name: 'BBOZA' },
                { id: 24422, name: 'BUGAYI' },
                { id: 24423, name: 'BUMOOZI A' },
                { id: 24424, name: 'BUMOOZI B' },
                { id: 24425, name: 'KIGGWANYA' },
                { id: 24426, name: 'KIKAMULA' },
                { id: 24427, name: 'KIMBUGU' },
                { id: 24428, name: 'NAMIRYANGO' },
                { id: 24429, name: 'NNONO' },
              ],
            },
            {
              id: 3826,
              name: 'KAFUMU WARD',
              villages: [
                { id: 24430, name: 'BULIRO' },
                { id: 24431, name: 'BUMYUKA' },
                { id: 24432, name: 'KISALIZA' },
                { id: 24433, name: 'KITAANULWA' },
                { id: 24434, name: 'NAMABO' },
                { id: 24435, name: 'NANYIZI' },
              ],
            },
            {
              id: 3827,
              name: 'KAKOOLA WARD',
              villages: [
                { id: 24436, name: 'BUNAMWERI' },
                { id: 24437, name: 'GGALA' },
                { id: 24438, name: 'KAKOOLA' },
                { id: 24439, name: 'KITAVUJJA/BUKAWAMALA' },
              ],
            },
            {
              id: 3828,
              name: 'KONKOMA WARD',
              villages: [
                { id: 24447, name: 'BWAANYA' },
                { id: 24441, name: 'JJANYA' },
                { id: 24442, name: 'KALIGWA' },
                { id: 24443, name: 'KKONKOMA' },
                { id: 24444, name: 'MPAMBIRE A' },
                { id: 24445, name: 'MPAMBIRE TC' },
                { id: 24446, name: 'NAKIGUDDE' },
                { id: 24440, name: 'NDUGU' },
                { id: 24448, name: 'NSEKE' },
              ],
            },
            {
              id: 3829,
              name: 'KYALI WARD',
              villages: [
                { id: 24449, name: 'BUBEZI' },
                { id: 24450, name: 'BUSOMBA' },
                { id: 24451, name: 'KASAAMU' },
                { id: 24452, name: 'KIRYANKUYEGE/GAYAZA' },
                { id: 24453, name: 'KYALI' },
                { id: 24454, name: 'NSAAMU' },
              ],
            },
            {
              id: 3830,
              name: 'LWANGA WARD',
              villages: [
                { id: 24455, name: 'BULYASI' },
                { id: 24456, name: 'KALAGALA' },
                { id: 24457, name: 'LWANGA' },
                { id: 24458, name: 'MASUJJU/KIZZI' },
                { id: 24459, name: 'NYOMERWA/ZIWUNGWE' },
              ],
            },
            {
              id: 3831,
              name: 'MAZIBA WARD',
              villages: [
                { id: 24460, name: 'BUGOMBE' },
                { id: 24461, name: 'BUZINGU/SENENE' },
                { id: 24462, name: 'LUNGALA' },
                { id: 24463, name: 'MEMBE/MAKUKU' },
                { id: 24464, name: 'MULOLE' },
                { id: 24465, name: 'NAMULAMUZI/BUME' },
                { id: 24466, name: 'NKONGE' },
              ],
            },
            {
              id: 3832,
              name: 'WARD A',
              villages: [
                { id: 24467, name: 'CHURCH CENTRE' },
                { id: 24468, name: 'LUFUKA' },
                { id: 24469, name: 'MPAMI' },
                { id: 24470, name: 'PARK VILLAGE' },
                { id: 24471, name: 'POLICE CENTRE' },
              ],
            },
            {
              id: 3833,
              name: 'WARD B',
              villages: [
                { id: 24472, name: 'KALAGALA' },
                { id: 24473, name: 'KYASANKU' },
                { id: 24474, name: 'MAWONVE' },
                { id: 24475, name: 'SABWE HILL' },
              ],
            },
            {
              id: 3834,
              name: 'WARD C',
              villages: [
                { id: 24476, name: 'BUKAKALA' },
                { id: 24477, name: 'KABANGA' },
                { id: 24478, name: 'MBALE' },
              ],
            },
            {
              id: 3835,
              name: 'WARD D',
              villages: [
                { id: 24479, name: 'MAYEMBE LOWER' },
                { id: 24480, name: 'MAYEMBE UPPER' },
                { id: 24481, name: 'PRISON CENTRE' },
              ],
            },
          ],
        },
        {
          id: 827,
          name: 'MUDUMA',
          parishes: [
            {
              id: 3836,
              name: 'BULEREJJE',
              villages: [
                { id: 24482, name: 'BULEREJJE' },
                { id: 24483, name: 'BUZIMWA/KATUUSO' },
                { id: 24484, name: 'KIBUMBIRO/DDAMBA' },
                { id: 24485, name: 'WALUKUNYU' },
              ],
            },
            {
              id: 3837,
              name: 'JJEZA',
              villages: [
                { id: 24486, name: 'JJEZA A' },
                { id: 24487, name: 'JJEZA B' },
                { id: 24488, name: 'NVUBA' },
                { id: 24489, name: 'VVUMBA-KAPEKE' },
              ],
            },
            {
              id: 3838,
              name: 'LUGYO',
              villages: [
                { id: 24490, name: 'BUJUUKO/KASANA' },
                { id: 24491, name: 'BUYALA/NAZIRI' },
                { id: 24492, name: 'KISAMULA/LUGYO' },
                { id: 24493, name: 'KOLOKOLO/JUMBA' },
                { id: 24494, name: 'MALUBE/NALUBUGO' },
                { id: 24495, name: 'NALYA/NANSESE' },
              ],
            },
            {
              id: 3839,
              name: 'MAGALA',
              villages: [
                { id: 24496, name: 'BUSASI' },
                { id: 24497, name: 'BUYONGO' },
                { id: 24498, name: 'GIMBI/MAWUGULU' },
                { id: 24499, name: 'MAGALA' },
              ],
            },
            {
              id: 3840,
              name: 'MALIMA',
              villages: [
                { id: 24500, name: 'GGAVU' },
                { id: 24501, name: 'KIBUUTU' },
                { id: 24502, name: 'KWATA' },
                { id: 24503, name: 'NKAMBO' },
                { id: 24504, name: 'NSWANJERE' },
              ],
            },
            {
              id: 3841,
              name: 'MBAZZI',
              villages: [
                { id: 24505, name: 'BULAMAZI' },
                { id: 24506, name: 'KISOZI' },
                { id: 24507, name: 'MBAZZI' },
                { id: 24508, name: 'SSIGI' },
              ],
            },
            {
              id: 3842,
              name: 'TIRIBOGO',
              villages: [
                { id: 24509, name: 'BULAMU' },
                { id: 24510, name: 'BUSANYI' },
                { id: 24511, name: 'GALABI-NAKYESANJA' },
                { id: 24512, name: 'MUDUUMA' },
                { id: 24513, name: 'TIRIBOGO' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 135,
      name: 'MAWOKOTA COUNTY SOUTH',
      sub_counties: [
        {
          id: 828,
          name: 'BUWAMA',
          parishes: [
            {
              id: 3844,
              name: 'BULUNDA',
              villages: [
                { id: 24521, name: 'BULUNDA' },
                { id: 24522, name: 'KABAGAMBI/BUMERA' },
                { id: 24523, name: 'KATEBO/KYANGO' },
              ],
            },
            {
              id: 3843,
              name: 'BUNJAKO',
              villages: [
                { id: 24514, name: 'BUGOMA/KIREGA' },
                { id: 24515, name: 'BUZAAMI' },
                { id: 24516, name: 'KASAWO/KITELEDE' },
                { id: 24517, name: 'KINYINABO' },
                { id: 24518, name: 'LUBEMBE' },
                { id: 24519, name: 'MUNYONYO/BUWEJJA' },
                { id: 24520, name: 'SENYONDO/BUKIINA' },
              ],
            },
            {
              id: 3845,
              name: 'KAWUMBA',
              villages: [
                { id: 24524, name: 'BULYOWA' },
                { id: 24525, name: 'KAWUMBA' },
                { id: 24526, name: 'KISUBI' },
                { id: 24527, name: 'SSEMUKOMBE' },
              ],
            },
            {
              id: 3846,
              name: 'SANGO',
              villages: [
                { id: 24528, name: 'BUSSEEBWE' },
                { id: 24529, name: 'BUWANDA' },
                { id: 24530, name: 'BUYIWA' },
                { id: 24531, name: 'KYAATO' },
                { id: 24532, name: 'SSANGO A' },
                { id: 24533, name: 'SSANGO B' },
              ],
            },
          ],
        },
        {
          id: 831,
          name: 'BUWAMA TOWN COUNCIL',
          parishes: [
            {
              id: 3863,
              name: 'BONGOLE WARD',
              villages: [
                { id: 24626, name: 'BONGOLE' },
                { id: 24627, name: 'BUWUNGA' },
                { id: 24632, name: 'KANAANI' },
                { id: 24633, name: 'KASUBIKAMU' },
                { id: 24628, name: 'MAGGYA' },
                { id: 24629, name: 'MITALA-MARIA CENTRAL' },
                { id: 24630, name: 'MITALA-MARIA NTC' },
                { id: 24631, name: 'NYONDO' },
              ],
            },
            {
              id: 3861,
              name: 'BUYIJJA WARD',
              villages: [
                { id: 24615, name: 'BUMBO' },
                { id: 24617, name: 'BUYIJJA' },
                { id: 24618, name: 'KABIRA/JJOBYA' },
                { id: 24616, name: 'KALONGERO' },
                { id: 24619, name: 'KIBENGE' },
                { id: 24620, name: 'NSANGWA' },
              ],
            },
            {
              id: 3858,
              name: 'JALAMBA WARD',
              villages: [
                { id: 24602, name: 'JALAMBA' },
                { id: 24603, name: 'LUBANGA A' },
                { id: 24604, name: 'LUBANGA B' },
                { id: 24605, name: 'NAMASAWO' },
              ],
            },
            {
              id: 3859,
              name: 'LUBUGUMU WARD',
              villages: [
                { id: 24606, name: 'KIREBEJUKO' },
                { id: 24608, name: 'KKUMBYA' },
                { id: 24607, name: 'LUBUGUMU' },
                { id: 24609, name: 'SSAKABUSOLO' },
              ],
            },
            {
              id: 3860,
              name: 'MBIZINYA WARD',
              villages: [
                { id: 24610, name: 'BUWAMA A' },
                { id: 24611, name: 'BUWAMA B' },
                { id: 24612, name: 'BUYAAYA/KITOJJO' },
                { id: 24613, name: 'MBIZZINYA' },
                { id: 24614, name: 'MITALA-MARIA/KATIKANYONYI/KIBOGA' },
              ],
            },
            {
              id: 3862,
              name: 'NABITETE WARD',
              villages: [
                { id: 24621, name: 'BUWERE A' },
                { id: 24622, name: 'BUWERE B' },
                { id: 24623, name: 'KASOSO' },
                { id: 24624, name: 'LUTENGO-BUWUNGU' },
                { id: 24625, name: 'NABITEETE' },
              ],
            },
          ],
        },
        {
          id: 832,
          name: 'KAYABWE TOWN COUNCIL',
          parishes: [
            {
              id: 3864,
              name: 'BUSESE WARD',
              villages: [
                { id: 24634, name: 'BUSESE A' },
                { id: 24635, name: 'BUSESE B' },
                { id: 24636, name: 'KALAGALA' },
                { id: 24637, name: 'NKOZI A' },
                { id: 24638, name: 'NKOZI B' },
                { id: 24639, name: 'NKOZI UNIVERSITY/HOSPITAL' },
              ],
            },
            {
              id: 3865,
              name: 'KAYABWE WARD',
              villages: [
                { id: 24640, name: 'JANDIRA' },
                { id: 24641, name: 'KASUUBO' },
                { id: 24642, name: 'KAYABWE TOWN' },
                { id: 24643, name: 'KIKUTUZI/KALAGALA' },
                { id: 24644, name: 'LUKONGE' },
              ],
            },
            {
              id: 3866,
              name: 'NABUSANKE WARD',
              villages: [
                { id: 24645, name: 'BUTAMBA' },
                { id: 24646, name: 'KIKOMAZI' },
                { id: 24647, name: 'KWAABA' },
                { id: 24648, name: 'NABUSANKE A' },
                { id: 24649, name: 'NABUSANKE B' },
                { id: 24650, name: 'WASSOZI A' },
                { id: 24651, name: 'WASSOZI B' },
              ],
            },
            {
              id: 3867,
              name: 'NAKIBANGA WARD',
              villages: [
                { id: 24652, name: 'KAWANGO A' },
                { id: 24653, name: 'KAWANGO B' },
                { id: 24654, name: 'KITOSI' },
                { id: 24655, name: 'NAKIBANGA A' },
                { id: 24656, name: 'NAKIBANGA B' },
                { id: 24657, name: 'NAKIBANGA C' },
                { id: 24658, name: 'NAKIBANGA D' },
                { id: 24659, name: 'NUNDU' },
              ],
            },
          ],
        },
        {
          id: 829,
          name: 'KITUNTU',
          parishes: [
            {
              id: 3849,
              name: 'BUKEMBA',
              villages: [
                { id: 24550, name: 'BUKEMBA A' },
                { id: 24551, name: 'BUKEMBA B' },
                { id: 24552, name: 'BUKONOKA/NAKIBANGA' },
                { id: 24553, name: 'LWAJJA/KINAKUKKA' },
                { id: 24554, name: 'MULAMA/KATIKO' },
              ],
            },
            {
              id: 3847,
              name: 'KAGENDA',
              villages: [
                { id: 24534, name: 'BUKASA' },
                { id: 24535, name: 'KAGENDA' },
                { id: 24536, name: 'KASAMBYA' },
                { id: 24537, name: 'KATEEBE' },
                { id: 24538, name: 'KAWOOMYA' },
                { id: 24539, name: 'LWAMIKOMA/LWAMANYA' },
                { id: 24540, name: 'LWAWEEBA' },
                { id: 24541, name: 'NJERU A' },
                { id: 24542, name: 'NJERU B' },
                { id: 24543, name: 'WATTUBA' },
              ],
            },
            {
              id: 3848,
              name: 'KANTIINI',
              villages: [
                { id: 24544, name: 'BULUSI' },
                { id: 24545, name: 'KANTIINI' },
                { id: 24546, name: 'KAWANSENYI' },
                { id: 24549, name: 'KITAKYUSA' },
                { id: 24547, name: 'KYEWANISE' },
                { id: 24548, name: 'SEETA/LUKINGA' },
              ],
            },
            {
              id: 3850,
              name: 'KASOZI',
              villages: [
                { id: 24555, name: 'LWAJJA/KITIGI' },
                { id: 24556, name: 'LWAJJA/KITUNTU' },
                { id: 24557, name: 'MBUULE/NSAMBYA' },
                { id: 24558, name: 'SSERUBONA A' },
                { id: 24559, name: 'SSERUBONA B' },
                { id: 24560, name: 'WAJJINJA' },
              ],
            },
            {
              id: 3851,
              name: 'LUWUNGA',
              villages: [
                { id: 24561, name: 'BBULA' },
                { id: 24562, name: 'BUSAGAZI' },
                { id: 24563, name: 'LUWUNGA CENTRAL' },
                { id: 24564, name: 'LUWUNGA NTEETE' },
              ],
            },
            {
              id: 3852,
              name: 'MIGAMBA',
              villages: [
                { id: 24565, name: 'KATIITI' },
                { id: 24566, name: 'MBUULE/MASIKO' },
                { id: 24567, name: 'MIGAMBA' },
                { id: 24568, name: 'NDIRAWERU' },
              ],
            },
            {
              id: 3853,
              name: 'NKASI',
              villages: [
                { id: 24569, name: 'BUKOMA' },
                { id: 24570, name: 'KASINDE' },
                { id: 24571, name: 'MAGUNGU' },
                { id: 24572, name: 'NKASI' },
              ],
            },
          ],
        },
        {
          id: 830,
          name: 'NKOZI',
          parishes: [
            {
              id: 3856,
              name: 'BUKUNGE',
              villages: [
                { id: 24586, name: 'BUGEYE' },
                { id: 24587, name: 'BUKUNGE' },
                { id: 24588, name: 'KIGULI' },
                { id: 24589, name: 'KITOKOLO' },
              ],
            },
            {
              id: 3854,
              name: 'GOLO',
              villages: [
                { id: 24573, name: 'BUGONJA' },
                { id: 24574, name: 'BUKALUNGA  CENTRAL' },
                { id: 24575, name: 'BUKALUNGA A' },
                { id: 24576, name: 'BUKALUNGA B' },
                { id: 24577, name: 'BUKASA' },
                { id: 24578, name: 'BUSEERA' },
                { id: 24579, name: 'BUZIRANGO' },
              ],
            },
            {
              id: 3855,
              name: 'MUGGE',
              villages: [
                { id: 24580, name: 'GWANIKA' },
                { id: 24581, name: 'KAMALIBA' },
                { id: 24582, name: 'LUBANGA' },
                { id: 24583, name: 'MUGGE' },
                { id: 24584, name: 'NABYEWANGA' },
                { id: 24585, name: 'NTIZI' },
              ],
            },
            {
              id: 3857,
              name: 'NINDYE',
              villages: [
                { id: 24590, name: 'BUKIBIRA' },
                { id: 24591, name: 'KANKOBE-BUGABO' },
                { id: 24592, name: 'KANKOBE-SENERO' },
                { id: 24593, name: 'KASSALU' },
                { id: 24594, name: 'KAYUNGA' },
                { id: 24595, name: 'KIKOOTA' },
                { id: 24596, name: 'LUBANDA A' },
                { id: 24597, name: 'LUBANDA B' },
                { id: 24598, name: 'LUBANDA C' },
                { id: 24599, name: 'LUTEETE' },
                { id: 24600, name: 'NINDYE A' },
                { id: 24601, name: 'NINDYE B' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
