import { District } from '../index';

export default {
  id: 59,
  name: 'MUBENDE',
  counties: [
    {
      id: 136,
      name: 'BUWEKULA COUNTY',
      sub_counties: [
        {
          id: 833,
          name: 'BUTOLOOGO',
          parishes: [
            {
              id: 3869,
              name: 'KALAMA',
              villages: [
                { id: 24664, name: 'BUGANYI' },
                { id: 24665, name: 'KAGEZI' },
                { id: 24667, name: 'KANABUGOMA' },
                { id: 24668, name: 'KATULA' },
                { id: 24666, name: 'KIGONDO' },
                { id: 24669, name: 'NYONDO' },
              ],
            },
            {
              id: 3872,
              name: 'KANYOGOGA',
              villages: [
                { id: 24678, name: 'BIWALWE' },
                { id: 24679, name: 'KANYOGOGA' },
                { id: 24681, name: 'KIFUMBIRA' },
                { id: 24680, name: 'KYAKAJJA' },
                { id: 24682, name: 'LWEBAAGA' },
              ],
            },
            {
              id: 3870,
              name: 'KIDONGO',
              villages: [
                { id: 24670, name: 'KASOZI' },
                { id: 24672, name: 'KIGOOBA' },
                { id: 24671, name: 'NSANVU' },
                { id: 24673, name: 'NSINAMU' },
              ],
            },
            {
              id: 3871,
              name: 'KISAGAZI',
              villages: [
                { id: 24674, name: 'KAWOLOLO' },
                { id: 24676, name: 'KISAGAZI' },
                { id: 24675, name: 'KISAGULA' },
                { id: 24677, name: 'KISOJO' },
              ],
            },
            {
              id: 3868,
              name: 'KYEZA',
              villages: [
                { id: 24661, name: 'BUBENGE' },
                { id: 24662, name: 'KAKYUKA' },
                { id: 24663, name: 'KATAGGI' },
                { id: 24660, name: 'KIFUMAMBOGO' },
              ],
            },
          ],
        },
        {
          id: 834,
          name: 'KALONGA',
          parishes: [
            {
              id: 3876,
              name: 'BUDIBAGA',
              villages: [
                { id: 24705, name: 'BUDIBAGA EAST' },
                { id: 24708, name: 'BUDIBAGA WEST' },
                { id: 24710, name: 'KALEMBE' },
                { id: 24707, name: 'KIJJUYA' },
                { id: 24709, name: 'KISONGA' },
                { id: 24706, name: 'KYAMBIDDE' },
              ],
            },
            {
              id: 3873,
              name: 'BUSENYA',
              villages: [
                { id: 24683, name: 'BUSENYA' },
                { id: 24684, name: 'KALAGALA' },
                { id: 24690, name: 'KIBYAMIRIZI' },
                { id: 24687, name: 'KITEREDDE' },
                { id: 24685, name: 'KKIGAGGA' },
                { id: 24688, name: 'KYEGULUMA' },
                { id: 24689, name: 'MPASANA' },
                { id: 24686, name: 'TUBA' },
              ],
            },
            {
              id: 3874,
              name: 'GOGWA',
              villages: [
                { id: 24692, name: 'GOOGWA' },
                { id: 24691, name: 'KAGALAMA' },
                { id: 24693, name: 'KAMUSENENE' },
                { id: 63401, name: 'KIBUTAMU' },
                { id: 24695, name: 'KITUUFU' },
                { id: 24694, name: 'KYAMBOGO' },
                { id: 66289, name: 'MIREMBE' },
                { id: 66747, name: 'MUYENGA' },
              ],
            },
            {
              id: 3877,
              name: 'KABYUMA',
              villages: [
                { id: 24711, name: 'BUKASA' },
                { id: 24712, name: 'BUTUUTI' },
                { id: 24713, name: 'JEMBA' },
                { id: 24715, name: 'KABYUMA' },
                { id: 24714, name: 'KASEKERE' },
                { id: 24716, name: 'KIZINGA' },
                { id: 24718, name: 'LWEMIGO' },
                { id: 24717, name: 'NAJWALI' },
                { id: 24719, name: 'SALA' },
                { id: 24720, name: 'SUNGA' },
              ],
            },
            {
              id: 3878,
              name: 'KALONGA',
              villages: [
                { id: 24722, name: 'BUKONGO' },
                { id: 24723, name: 'BWAKAGO' },
                { id: 24721, name: 'KAGAVU' },
                { id: 24724, name: 'KALONGA A' },
                { id: 24731, name: 'KALONGA B' },
                { id: 24732, name: 'KALONGA GREATER' },
                { id: 24725, name: 'KAYUNGA' },
                { id: 24733, name: 'KINYIGA' },
                { id: 24728, name: 'KISOJJO' },
                { id: 24726, name: 'KYADOKI' },
                { id: 24734, name: 'KYAKATULE' },
                { id: 24729, name: 'KYENGEZA' },
                { id: 24730, name: 'MISENDA' },
                { id: 24727, name: 'NTUNGAMO' },
              ],
            },
            {
              id: 3875,
              name: 'KYABADUMA',
              villages: [
                { id: 24696, name: 'BUTANKANJA' },
                { id: 24701, name: 'KIRUMBI' },
                { id: 24702, name: 'KYABADUUMA' },
                { id: 24697, name: 'KYABAGEYA' },
                { id: 24698, name: 'KYANIKA' },
                { id: 24703, name: 'LWANGIIRE' },
                { id: 24700, name: 'LWENSAMBYA' },
                { id: 24699, name: 'MYABAGALAGWA' },
                { id: 24704, name: 'NAMALEWE' },
              ],
            },
          ],
        },
        {
          id: 838,
          name: 'KAYEBE',
          parishes: [
            {
              id: 3891,
              name: 'BUSOOBA',
              villages: [
                { id: 24836, name: 'BUSOOBA NORTH' },
                { id: 24837, name: 'BUSOOBA WEST' },
                { id: 24838, name: 'KANYEGALAMIRE NORTH' },
                { id: 24839, name: 'RUSIKIZI' },
                { id: 24840, name: 'RWAMASHENJERO A' },
                { id: 70068, name: 'RWAMASHENJERO B' },
              ],
            },
            {
              id: 3892,
              name: 'BUTAYUNJA',
              villages: [
                { id: 24841, name: 'BUTAYUNJA' },
                { id: 24842, name: 'KALINZI' },
                { id: 24843, name: 'LYANDABA' },
                { id: 24844, name: 'MUGAMBA' },
              ],
            },
            {
              id: 3894,
              name: 'KAYEBE',
              villages: [
                { id: 59684, name: 'BULAZA' },
                { id: 62607, name: 'KANYOGOGA' },
                { id: 24853, name: 'KASAMBYA' },
                { id: 24850, name: 'KAWUMULO A' },
                { id: 24852, name: 'KAWUMULO B' },
                { id: 24851, name: 'KAYEBE' },
                { id: 24855, name: 'KIVERA' },
                { id: 24854, name: 'RWITABAYONGA' },
              ],
            },
            {
              id: 3890,
              name: 'KIRYAMENVU',
              villages: [
                { id: 63123, name: 'KATOMA' },
                { id: 63469, name: 'KIGAGGA' },
                { id: 24835, name: 'KIRYAMENVU' },
                { id: 68171, name: 'NYAMIRINGA' },
              ],
            },
            {
              id: 3893,
              name: 'RWAMABOGA',
              villages: [
                { id: 24846, name: 'KANYEGALAMIRE SOUTH' },
                { id: 62818, name: 'KAROKALUNGI' },
                { id: 24845, name: 'KIGANDA' },
                { id: 68112, name: 'NYAKITUNDA' },
                { id: 24847, name: 'RUSIKIZI' },
                { id: 24848, name: 'RWAMABOGA A' },
                { id: 24849, name: 'RWAMABOGA B' },
              ],
            },
          ],
        },
        {
          id: 2035,
          name: 'KIRUUMA',
          parishes: [
            {
              id: 9635,
              name: 'KASOLOKAMPONYE',
              villages: [
                { id: 63403, name: 'KIBUUZA' },
                { id: 63414, name: 'KICHUCHUULO' },
                { id: 63837, name: 'KIRUUMA' },
                { id: 64147, name: 'KIYINJA' },
              ],
            },
            {
              id: 9709,
              name: 'KIJAAGI',
              villages: [
                { id: 63588, name: 'KIJAAGI' },
                { id: 63852, name: 'KIRYANONGO' },
                { id: 67730, name: 'NGANJI' },
              ],
            },
            {
              id: 9738,
              name: 'KIRWANYI',
              villages: [
                { id: 59401, name: 'BUJAALA' },
                { id: 63838, name: 'KIRWANYI' },
                { id: 66575, name: 'MULANDA' },
              ],
            },
            {
              id: 9773,
              name: 'KITUULE',
              villages: [
                { id: 63339, name: 'KIBALAGAZI' },
                { id: 64115, name: 'KITUULE' },
                { id: 67016, name: 'NAKASAGAZI' },
                { id: 70543, name: 'SSUNGA' },
              ],
            },
            {
              id: 9958,
              name: 'MAKUUKUULU',
              villages: [
                { id: 59350, name: 'BUGOMBA' },
                { id: 62244, name: 'KAKONYI' },
                { id: 63997, name: 'KITANDA' },
                { id: 64686, name: 'KYANKUMBA' },
                { id: 64687, name: 'KYANKUMBA B' },
                { id: 65589, name: 'LUGALAMA' },
              ],
            },
          ],
        },
        {
          id: 835,
          name: 'KITENGA',
          parishes: [
            {
              id: 3881,
              name: 'BUGONZI',
              villages: [
                { id: 24755, name: 'BUGONZI' },
                { id: 24759, name: 'BULAMBIRA' },
                { id: 24757, name: 'BUZOOBA' },
                { id: 24758, name: 'KASANA' },
                { id: 24760, name: 'KAVULE' },
                { id: 24761, name: 'KIPPOPO' },
                { id: 24756, name: 'KIRULUMA B' },
                { id: 24762, name: 'KISAWULA' },
                { id: 24763, name: 'KISENYI' },
                { id: 24764, name: 'KITOVU' },
                { id: 24766, name: 'LUKAYA' },
                { id: 24768, name: 'LUKAYA A' },
                { id: 24767, name: 'NAKASEETA' },
                { id: 24769, name: 'NSENGWE' },
                { id: 24765, name: 'RWEBIYONGI' },
              ],
            },
            {
              id: 3880,
              name: 'GOGONYA',
              villages: [
                { id: 24748, name: 'BUSWABWERA' },
                { id: 24749, name: 'GOGONYA' },
                { id: 24750, name: 'KABUNYONYI' },
                { id: 24752, name: 'KALUNGI B' },
                { id: 24751, name: 'KIBUYE-VUGA' },
                { id: 24753, name: 'LWABAGOMA' },
                { id: 24754, name: 'NJAGAZI' },
              ],
            },
            {
              id: 3882,
              name: 'KAGOMA',
              villages: [
                { id: 24771, name: 'BULIMA' },
                { id: 24774, name: 'BULYANA' },
                { id: 24770, name: 'BUTEREVU' },
                { id: 24772, name: 'KAGOMA' },
                { id: 24773, name: 'KASAANA' },
                { id: 24775, name: 'KASAMBYA' },
                { id: 63750, name: 'KINONI' },
                { id: 24782, name: 'KIWUMULO' },
                { id: 24779, name: 'KYABASERESI' },
                { id: 64531, name: 'KYAKADDALI B' },
                { id: 24777, name: 'KYALIGOMBA' },
                { id: 64758, name: 'KYEBANDO' },
                { id: 24776, name: 'KYENDA' },
                { id: 24778, name: 'MUJUNWA' },
                { id: 24780, name: 'NALYANKANJA' },
                { id: 67319, name: 'NAMIREMBE' },
                { id: 24783, name: 'NSISI' },
                { id: 24784, name: 'RWEBUUKA' },
                { id: 24781, name: 'SAKA' },
              ],
            },
            {
              id: 3879,
              name: 'MULEETE',
              villages: [
                { id: 24735, name: 'BUGALYA A' },
                { id: 24736, name: 'BUGALYA B' },
                { id: 24737, name: 'KAKINDU' },
                { id: 24738, name: 'KINONI' },
                { id: 24739, name: 'KIRANGWA' },
                { id: 24740, name: 'KYAKADDALI A' },
                { id: 24741, name: 'KYAKADDALI B' },
                { id: 24743, name: 'KYEBANDO' },
                { id: 24742, name: 'LUGALA' },
                { id: 24745, name: 'MPIGI' },
                { id: 24747, name: 'MULETE' },
                { id: 24744, name: 'MUTTAMBWA' },
                { id: 24746, name: 'NAMIREMBE' },
              ],
            },
          ],
        },
        {
          id: 836,
          name: 'KIYUNI',
          parishes: [
            {
              id: 3883,
              name: 'KATENTE',
              villages: [
                { id: 24785, name: 'BUTUMI' },
                { id: 24786, name: 'BUWANDE' },
                { id: 24787, name: 'KAWALALA' },
                { id: 24788, name: 'KIGAMBA' },
                { id: 24789, name: 'KIYUUNI' },
                { id: 24790, name: 'KYAWOOGA' },
              ],
            },
            {
              id: 3884,
              name: 'KIJUMBA',
              villages: [
                { id: 24791, name: 'KAKIGONDO EAST' },
                { id: 24792, name: 'KAKIGONDO WEST' },
                { id: 24793, name: 'KIJJUMBA EAST' },
                { id: 24794, name: 'KIJJUMBA WEST' },
                { id: 24795, name: 'MUSAMBA' },
              ],
            },
          ],
        },
        {
          id: 837,
          name: 'MADUDU',
          parishes: [
            {
              id: 3886,
              name: 'KABULAMULIRO',
              villages: [
                { id: 24807, name: 'BOMBO' },
                { id: 24808, name: 'BUKADDE' },
                { id: 24809, name: 'KABULAMULIRO' },
                { id: 24813, name: 'KIJAGUZO' },
                { id: 24814, name: 'KISAMULA' },
                { id: 24810, name: 'LULONGO' },
                { id: 24811, name: 'MADUDU' },
                { id: 24812, name: 'NYEGEZA' },
              ],
            },
            {
              id: 3887,
              name: 'KAKENZI',
              villages: [
                { id: 24815, name: 'BULEGA' },
                { id: 24816, name: 'KABAALE' },
                { id: 24817, name: 'KAKENZI' },
                { id: 24818, name: 'KAZIRAJJOMA' },
                { id: 24819, name: 'KYEDIKYO' },
                { id: 24820, name: 'NGABANO' },
              ],
            },
            {
              id: 3885,
              name: 'KANSAMBYA',
              villages: [
                { id: 24803, name: 'KABWEYAKIZA' },
                { id: 24796, name: 'KAGUNGULI' },
                { id: 24797, name: 'KANSAMBYA' },
                { id: 24804, name: 'KIMBEJJA' },
                { id: 24798, name: 'KITO' },
                { id: 24799, name: 'LUTEETE' },
                { id: 24805, name: 'MBUYA' },
                { id: 24800, name: 'MOOMA' },
                { id: 24801, name: 'NABIYUNGU' },
                { id: 24802, name: 'NAKALADDE' },
                { id: 24806, name: 'RWAMIRAMIRA' },
              ],
            },
            {
              id: 3888,
              name: 'KIKOMA',
              villages: [
                { id: 24821, name: 'KIKOMA' },
                { id: 24823, name: 'KISASA' },
                { id: 24822, name: 'KITEREGA' },
              ],
            },
            {
              id: 3889,
              name: 'NALUWONDWA',
              villages: [
                { id: 24832, name: 'BULAMAZI' },
                { id: 24824, name: 'BUTOOLO' },
                { id: 24825, name: 'KIJUNGA' },
                { id: 24826, name: 'KIRYAMAKOBE' },
                { id: 24827, name: 'KISOOLO' },
                { id: 24828, name: 'KITEMBA' },
                { id: 24833, name: 'KYOTA' },
                { id: 24834, name: 'LULAGALA' },
                { id: 24829, name: 'LUWUNGA' },
                { id: 24830, name: 'NAKASOZI' },
                { id: 24831, name: 'NALUWONDWA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 137,
      name: 'KASAMBYA COUNTY',
      sub_counties: [
        {
          id: 839,
          name: 'BAGEZZA',
          parishes: [
            {
              id: 3895,
              name: 'KALAGALA',
              villages: [
                { id: 24856, name: 'KALAGALA' },
                { id: 24857, name: 'KIKOOBA' },
                { id: 24858, name: 'KYENGERA' },
                { id: 24859, name: 'LWENSAMBYA' },
              ],
            },
            {
              id: 3897,
              name: 'KIJJOJOLO',
              villages: [
                { id: 24868, name: 'KALINGO' },
                { id: 24869, name: 'KIJJOJJOLO' },
                { id: 24872, name: 'KINONI' },
                { id: 24867, name: 'KYAKAKONGE A' },
                { id: 24870, name: 'KYAKONGE B' },
                { id: 24873, name: 'KYATEREKERA' },
                { id: 24871, name: 'MUGAAJU' },
              ],
            },
            {
              id: 3896,
              name: 'MUGUNGULU',
              villages: [
                { id: 24862, name: 'BUSINGYE EAST' },
                { id: 24863, name: 'BUSINGYE WEST' },
                { id: 24864, name: 'KALAMA' },
                { id: 24860, name: 'KANAALA' },
                { id: 24861, name: 'KYAKADAALI' },
                { id: 24865, name: 'MUGUNGULU A' },
                { id: 24866, name: 'MUGUNGULU B' },
              ],
            },
          ],
        },
        {
          id: 841,
          name: 'KASAMBYA',
          parishes: [
            {
              id: 3906,
              name: 'BUTUUTI',
              villages: [
                { id: 24923, name: 'BUTUUTI' },
                { id: 24924, name: 'KYAKALULUMA' },
                { id: 24925, name: 'NALUSOMBA' },
              ],
            },
            {
              id: 3908,
              name: 'KABBO',
              villages: [
                { id: 24935, name: 'GAYAZA' },
                { id: 24934, name: 'KABBO A' },
                { id: 24936, name: 'KABBO B' },
                { id: 24937, name: 'LUSAANA' },
                { id: 24938, name: 'MUZIRANDULU' },
                { id: 24939, name: 'NAKAWALA' },
                { id: 24940, name: 'NGALAMA' },
                { id: 24941, name: 'NSUNGA' },
              ],
            },
            {
              id: 3907,
              name: 'KAMUSONGOLE',
              villages: [
                { id: 24932, name: 'BWENGANJANI' },
                { id: 24926, name: 'KAKIIKOBA' },
                { id: 24931, name: 'KALAGALA' },
                { id: 24927, name: 'KAMUSONGOLE  A' },
                { id: 24928, name: 'KAMUSONGOLE  B' },
                { id: 24929, name: 'KISONGOLA' },
                { id: 24930, name: 'KIWUMULO' },
                { id: 24933, name: 'RWENTABO' },
              ],
            },
            {
              id: 3910,
              name: 'KIROLERO',
              villages: [
                { id: 24950, name: 'KIROLERO' },
                { id: 24951, name: 'KYEMBOGO' },
                { id: 24952, name: 'LUTOVU' },
                { id: 24948, name: 'LWENJUKI' },
                { id: 24953, name: 'LWENSAMA' },
                { id: 24949, name: 'MPUGUKYE' },
              ],
            },
            {
              id: 3913,
              name: 'KYAKASA',
              villages: [
                { id: 24969, name: 'KASHENYI' },
                { id: 24970, name: 'KYAKASA  A' },
                { id: 24971, name: 'KYAKASA  B' },
                { id: 24972, name: 'LUKOBA' },
                { id: 24973, name: 'LWEMPANDE' },
              ],
            },
            {
              id: 3911,
              name: 'LWEGULA',
              villages: [
                { id: 24958, name: 'KYAMAKULEGE' },
                { id: 24954, name: 'LUKINGA  A' },
                { id: 24955, name: 'LUKINGA  B' },
                { id: 24956, name: 'LWENONGO' },
                { id: 24957, name: 'RWEGULA A' },
                { id: 24959, name: 'RWEGULA B' },
                { id: 24960, name: 'RWEGULA C' },
              ],
            },
            {
              id: 3909,
              name: 'MUYINAYINA',
              villages: [
                { id: 24947, name: 'KABAFUKUZI' },
                { id: 24942, name: 'KATUNGULU' },
                { id: 24944, name: 'KYABWESENGE' },
                { id: 24945, name: 'MUYINAYINA' },
                { id: 24943, name: 'NAMUNGO' },
                { id: 24946, name: 'NAMWANDALA' },
              ],
            },
            {
              id: 3912,
              name: 'NKIINGA',
              villages: [
                { id: 24961, name: 'BUKOMANSIMBI A' },
                { id: 24962, name: 'BUKOMANSIMBI B' },
                { id: 24965, name: 'KITEREDDE' },
                { id: 24963, name: 'KYALUJUMBA' },
                { id: 24968, name: 'MUWUNGA' },
                { id: 24966, name: 'NALUKOKO A' },
                { id: 24964, name: 'NALUKOKO B' },
                { id: 24967, name: 'NKINGA' },
              ],
            },
          ],
        },
        {
          id: 845,
          name: 'KASAMBYA TOWN COUNCIL',
          parishes: [
            {
              id: 3932,
              name: 'KASAMBYA WARD',
              villages: [
                { id: 25097, name: 'BULONZI A' },
                { id: 25101, name: 'BULONZI B' },
                { id: 25102, name: 'BULONZI C' },
                { id: 25098, name: 'KASAMBYA  A' },
                { id: 25099, name: 'KASAMBYA  B' },
                { id: 25103, name: 'KASAMBYA CENTRAL' },
                { id: 25104, name: 'KIMWANYI A' },
                { id: 25100, name: 'NKRUMAH' },
                { id: 25105, name: 'NKRUMAH SOUTH' },
              ],
            },
            {
              id: 3933,
              name: 'KIRUME WARD',
              villages: [
                { id: 25107, name: 'KIRUME EAST' },
                { id: 25106, name: 'KIRUME WEST' },
                { id: 25108, name: 'MBULIRE' },
                { id: 25109, name: 'NDEBA' },
                { id: 25110, name: 'NSAMBYA' },
              ],
            },
            {
              id: 3930,
              name: 'KISIZIRE WARD',
              villages: [
                { id: 25083, name: 'KISIZIRE A' },
                { id: 25084, name: 'KISIZIRE CENTRAL' },
              ],
            },
            {
              id: 3931,
              name: 'LUBONA WARD',
              villages: [
                { id: 25087, name: 'KACUNGIRO' },
                { id: 25085, name: 'KAMIRANGOMA' },
                { id: 25086, name: 'KAMUSENENE A' },
                { id: 25095, name: 'KAMUSENENE B' },
                { id: 25096, name: 'KANYURIBANO' },
                { id: 63567, name: 'KIHUMURO' },
                { id: 25088, name: 'KIRANGIRA I' },
                { id: 25089, name: 'KIRANGIRA II' },
                { id: 25090, name: 'KIWUUBA' },
                { id: 25091, name: 'KYABUNYANSI' },
                { id: 25092, name: 'RUBONA' },
                { id: 25093, name: 'TOJJO  A' },
                { id: 25094, name: 'TOJJO  B' },
              ],
            },
            {
              id: 3934,
              name: 'NAKASAGA WARD',
              villages: [
                { id: 25113, name: 'KILOKOLE' },
                { id: 25114, name: 'KITEREDDE' },
                { id: 25111, name: 'NAKASAGA CENTRAL' },
                { id: 25115, name: 'NAKASAGA KYEBEREKE' },
                { id: 25112, name: 'NAKASAGA LINE' },
              ],
            },
          ],
        },
        {
          id: 840,
          name: 'KIBALINGA',
          parishes: [
            {
              id: 3898,
              name: 'KAABOWA',
              villages: [
                { id: 24874, name: 'BWEYENDERE' },
                { id: 24876, name: 'KAABOWA' },
                { id: 24875, name: 'KALEZI' },
                { id: 24879, name: 'KAMBAALI' },
                { id: 24877, name: 'KASAMBYA A' },
                { id: 24880, name: 'KASAMBYA B' },
                { id: 24878, name: 'KASASA' },
                { id: 24883, name: 'KAYEMBE' },
                { id: 24881, name: 'MISOGI' },
                { id: 24882, name: 'SUNGA' },
              ],
            },
            {
              id: 3904,
              name: 'KABUBBU',
              villages: [
                { id: 24909, name: 'KABUBBU' },
                { id: 24910, name: 'KALEGA' },
                { id: 24911, name: 'KALONGO' },
                { id: 24913, name: 'KITALEMWA' },
                { id: 24914, name: 'KYAMPISI' },
                { id: 24912, name: 'LWENKOOKO' },
                { id: 24915, name: 'MBONA' },
              ],
            },
            {
              id: 3901,
              name: 'KASAANA',
              villages: [
                { id: 24895, name: 'KASAANA' },
                { id: 24897, name: 'KAZO EAST' },
                { id: 24898, name: 'KAZO WEST' },
                { id: 24896, name: 'LUBUGUMA' },
                { id: 24899, name: 'NAKASAGAZI' },
              ],
            },
            {
              id: 3899,
              name: 'KIBALINGA A',
              villages: [
                { id: 24887, name: 'KALERE' },
                { id: 24884, name: 'KIBALINGA' },
                { id: 24888, name: 'LUSALIRA' },
                { id: 24885, name: 'NAKANYANSI' },
                { id: 24886, name: 'SSEMUTO' },
              ],
            },
            {
              id: 3900,
              name: 'KIBALINGA B',
              villages: [
                { id: 24889, name: 'KABANYI' },
                { id: 24890, name: 'KYAKAJANKU' },
                { id: 24891, name: 'LWEMAMBA' },
                { id: 24892, name: 'LWEMIYAGA' },
                { id: 24893, name: 'LWOBWANA' },
                { id: 24894, name: 'NGOMAZAMUKASA' },
              ],
            },
            {
              id: 3902,
              name: 'KISOMBWA',
              villages: [
                { id: 24900, name: 'KISOMBWA' },
                { id: 24902, name: 'KITEREDDE' },
                { id: 24901, name: 'NABIBUNGO' },
                { id: 24903, name: 'NTUNDA' },
              ],
            },
            {
              id: 3905,
              name: 'NKANDWA',
              villages: [
                { id: 24922, name: 'KISAALABA' },
                { id: 24916, name: 'KYEBBUMBA' },
                { id: 24919, name: 'MIKISA' },
                { id: 24917, name: 'NAKIRULUMA A' },
                { id: 24918, name: 'NAKIRULUMA B' },
                { id: 24920, name: 'NKANDWA A' },
                { id: 24921, name: 'NKANDWA B' },
              ],
            },
            {
              id: 3903,
              name: 'NTUNGAMO',
              villages: [
                { id: 24904, name: 'CHENYI' },
                { id: 24906, name: 'KATEETE' },
                { id: 24905, name: 'KYAMBAZIIRA' },
                { id: 24907, name: 'NTUNGAMO CENTRE' },
                { id: 24908, name: 'NTUNGAMO/KIBIRA' },
              ],
            },
          ],
        },
        {
          id: 843,
          name: 'KIGANDO',
          parishes: [
            {
              id: 3921,
              name: 'BUBANDA',
              villages: [
                { id: 25011, name: 'BUBANDA' },
                { id: 25012, name: 'KABAALE' },
                { id: 25013, name: 'KISONKO' },
                { id: 25015, name: 'KYANKUGU' },
                { id: 25014, name: 'LUGANGA' },
              ],
            },
            {
              id: 3919,
              name: 'DYANGOMA',
              villages: [
                { id: 24999, name: 'DYANGOMA' },
                { id: 25000, name: 'LUGAZI A' },
                { id: 25001, name: 'LUGAZI B' },
                { id: 25002, name: 'MIREMBE' },
                { id: 25003, name: 'NABIKAKALA' },
              ],
            },
            {
              id: 3920,
              name: 'KACWAMANGO',
              villages: [
                { id: 25004, name: 'KABANDOLE' },
                { id: 25005, name: 'KACWAMANGO' },
                { id: 25008, name: 'KASAANA B' },
                { id: 25009, name: 'KASAANA C' },
                { id: 25006, name: 'KASANA A' },
                { id: 25010, name: 'KWEZIKUMWE' },
                { id: 25007, name: 'KYABWIRE' },
              ],
            },
            {
              id: 3922,
              name: 'KIGANDO',
              villages: [
                { id: 25016, name: 'BUTAWATA  A' },
                { id: 25017, name: 'BUTAWATA  E' },
                { id: 25019, name: 'BUTAWATA WEST' },
                { id: 25018, name: 'KABATEZA A' },
                { id: 25024, name: 'KABATEZA B' },
                { id: 25025, name: 'KABATEZA C' },
                { id: 25020, name: 'KIGANDO' },
                { id: 25022, name: 'LUSANA' },
                { id: 25021, name: 'NAMUGONGO' },
                { id: 25023, name: 'RWENSAMA' },
              ],
            },
            {
              id: 3925,
              name: 'KIYONGA',
              villages: [
                { id: 25046, name: 'IKULA' },
                { id: 25047, name: 'KATAMBOGO A' },
                { id: 25048, name: 'KATAMBOGO B' },
                { id: 25049, name: 'KATONGOLE' },
                { id: 25052, name: 'NKUKURU' },
                { id: 25051, name: 'NYABIKANDA' },
                { id: 25053, name: 'NYARAKYI' },
                { id: 25054, name: 'NYARUTETE' },
                { id: 25050, name: 'RWAKIRANGARA' },
                { id: 25045, name: 'RWOBUSHUMI' },
              ],
            },
            {
              id: 3923,
              name: 'LUSIBA',
              villages: [
                { id: 25026, name: 'BUNGOMA' },
                { id: 25037, name: 'KAITABAGOLE' },
                { id: 25027, name: 'KANYOGOGA A' },
                { id: 25038, name: 'KANYOGOGA B' },
                { id: 25028, name: 'KASOLO' },
                { id: 25029, name: 'KATEGA' },
                { id: 25030, name: 'KISALIZI' },
                { id: 25031, name: 'KISENYI' },
                { id: 25032, name: 'KIWOMYA' },
                { id: 25033, name: 'KYAMUGULUMA' },
                { id: 25034, name: 'LUSAANA' },
                { id: 25035, name: 'MAWUJJO' },
                { id: 25036, name: 'NDOREREDE' },
              ],
            },
            {
              id: 3924,
              name: 'MUGOLODDE',
              villages: [
                { id: 25040, name: 'BUTAWATA  B' },
                { id: 25041, name: 'KABUTONGI' },
                { id: 25042, name: 'KAYUNGA' },
                { id: 25043, name: 'KISIITA A' },
                { id: 25039, name: 'KISIITA B' },
                { id: 25044, name: 'MUGOLODDE' },
              ],
            },
          ],
        },
        {
          id: 842,
          name: 'LUBIMBIRI',
          parishes: [
            {
              id: 3915,
              name: 'KAFUNDEZI',
              villages: [
                { id: 24979, name: 'KAFUNDEZI A' },
                { id: 24980, name: 'KAFUNDEZI B' },
                { id: 24981, name: 'MAKUKULU' },
                { id: 24978, name: 'NDIGITO' },
              ],
            },
            {
              id: 3916,
              name: 'KALOKALUNGI',
              villages: [
                { id: 24984, name: 'KALOKALUNGI A' },
                { id: 24985, name: 'KALOKALUNGI B' },
                { id: 24983, name: 'KALOKALUNGI CENTRAL' },
                { id: 24982, name: 'KYALUWEMBA' },
              ],
            },
            {
              id: 3914,
              name: 'KITONZI',
              villages: [
                { id: 24974, name: 'KABULASOKE' },
                { id: 24976, name: 'KAYONZA' },
                { id: 24977, name: 'KITONZI' },
                { id: 24975, name: 'KITONZI B' },
              ],
            },
            {
              id: 3918,
              name: 'LUBIMBIRI',
              villages: [
                { id: 24991, name: 'GAYAZA' },
                { id: 24995, name: 'KAMABAALE' },
                { id: 24992, name: 'KASONGODDE A' },
                { id: 24993, name: 'KASONGODDE B' },
                { id: 24994, name: 'KASONGODDE CENTRAL' },
                { id: 24996, name: 'LUBIMBIRI' },
                { id: 24997, name: 'LUBIMBIRI B' },
                { id: 65708, name: 'LUTOMA' },
                { id: 24998, name: 'RWENSAMBYA' },
              ],
            },
            {
              id: 3917,
              name: 'MAAYA',
              villages: [
                { id: 24987, name: 'KAKINDU' },
                { id: 24988, name: 'KAKINDU B' },
                { id: 24986, name: 'LWEMISEGU' },
                { id: 24989, name: 'MAAYA' },
                { id: 24990, name: 'MAAYA B' },
              ],
            },
          ],
        },
        {
          id: 844,
          name: 'NABINGOOLA',
          parishes: [
            {
              id: 3926,
              name: 'KABALUNGI',
              villages: [
                { id: 58885, name: 'BALIBASEKA' },
                { id: 25056, name: 'KABALUNGI  B' },
                { id: 25057, name: 'KABALUNGI A' },
                { id: 25055, name: 'KANOGA' },
                { id: 25058, name: 'KITABOWA' },
                { id: 25059, name: 'KYASA' },
              ],
            },
            {
              id: 3927,
              name: 'KASASA',
              villages: [
                { id: 25060, name: 'BANGI' },
                { id: 25063, name: 'KAGAVU' },
                { id: 25062, name: 'KALAMA' },
                { id: 25064, name: 'KASASA' },
                { id: 25065, name: 'KYENTULEGE' },
                { id: 25066, name: 'KYENTULEGE QUARTER' },
                { id: 25061, name: 'MYONGO' },
              ],
            },
            {
              id: 3928,
              name: 'KITEERA',
              villages: [
                { id: 25067, name: 'KAKINDO' },
                { id: 25068, name: 'KATOGO' },
                { id: 25069, name: 'KISANYUSA' },
                { id: 25071, name: 'KISANYUSA B' },
                { id: 25070, name: 'KITEERA' },
                { id: 25072, name: 'KIZIZI' },
                { id: 25073, name: 'KYAPA' },
                { id: 25074, name: 'NKOLABASEKA' },
              ],
            },
            {
              id: 3929,
              name: 'KIYITA',
              villages: [
                { id: 25075, name: 'BAMUSUUTA' },
                { id: 25076, name: 'KIWAMIREMBE' },
                { id: 25077, name: 'KIYITA' },
                { id: 25078, name: 'KIYITA B' },
                { id: 25079, name: 'KYABAGENDA' },
                { id: 25080, name: 'NANGABO' },
                { id: 25081, name: 'NANGABO B' },
                { id: 25082, name: 'RWENGIRI' },
              ],
            },
          ],
        },
        {
          id: 846,
          name: 'NABINGOOLA TOWN COUNCIL',
          parishes: [
            {
              id: 3937,
              name: 'GWANIKA WARD',
              villages: [
                { id: 25125, name: 'GWANIKA A' },
                { id: 61471, name: 'GWANIKA B' },
                { id: 25126, name: 'KIRIIRA' },
                { id: 25127, name: 'KIRIIRA B' },
              ],
            },
            {
              id: 3936,
              name: 'KAJUMIRO WARD',
              villages: [
                { id: 25123, name: 'KAJJUMIRO' },
                { id: 25120, name: 'LULONGO' },
                { id: 25122, name: 'LWEBINYAMA' },
                { id: 25121, name: 'LWEMPEFU' },
                { id: 25124, name: 'NKANGA MODERN' },
              ],
            },
            {
              id: 3938,
              name: 'KIBAALE WARD',
              villages: [
                { id: 25130, name: 'BIWANGA' },
                { id: 25129, name: 'KASEESA' },
                { id: 25131, name: 'KIBAALE A' },
                { id: 25132, name: 'KIBAALE B' },
                { id: 25128, name: 'KYAKISA' },
                { id: 25133, name: 'KYEBBUMBA' },
                { id: 25134, name: 'LWAMAZZI' },
              ],
            },
            {
              id: 3939,
              name: 'KITONZI WARD',
              villages: [
                { id: 62897, name: 'KASASA A' },
                { id: 62898, name: 'KASASA B' },
                { id: 25135, name: 'KATOMA' },
                { id: 64079, name: 'KITONZI' },
                { id: 25137, name: 'LWEMIVUBO' },
                { id: 65794, name: 'LWEMIVUBO B' },
                { id: 25136, name: 'LWENGO' },
              ],
            },
            { id: 9940, name: 'LWEMIVUBO WARD', villages: [] },
            {
              id: 3935,
              name: 'NABINGOOLA WARD',
              villages: [
                { id: 25116, name: 'KYETUME' },
                { id: 25119, name: 'LWAWUNA' },
                { id: 25117, name: 'LWENSAMA' },
                { id: 25118, name: 'NABINGOOLA A' },
                { id: 66836, name: 'NABINGOOLA B' },
                { id: 66837, name: 'NABINGOOLA CENTRAL' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 138,
      name: 'MUBENDE MUNICIPALITY',
      sub_counties: [
        {
          id: 847,
          name: 'EAST DIVISION',
          parishes: [
            {
              id: 3944,
              name: 'KANSEERA WARD',
              villages: [
                { id: 25156, name: 'KANSEERA' },
                { id: 25157, name: 'KAWUULA' },
                { id: 25158, name: 'KAYUNGA' },
                { id: 25159, name: 'MABAALE' },
              ],
            },
            {
              id: 3942,
              name: 'KASAANA WARD',
              villages: [
                { id: 25147, name: 'KASAANA  A' },
                { id: 25148, name: 'KASAANA  B' },
                { id: 25150, name: 'KIBAATI' },
                { id: 25149, name: 'KYABBOGO' },
                { id: 25151, name: 'NKANAGA' },
              ],
            },
            {
              id: 3940,
              name: 'KAWERI WARD',
              villages: [
                { id: 25138, name: 'BUKALUNGI' },
                { id: 25139, name: 'KASAMBYA' },
                { id: 25140, name: 'KAWEERI' },
                { id: 25141, name: 'KIRYANNONGO' },
              ],
            },
            {
              id: 3941,
              name: 'KAWUMULWA WARD',
              villages: [
                { id: 25142, name: 'KAWUMULWA' },
                { id: 25143, name: 'KIYUUYA' },
                { id: 25144, name: 'KYERIMA' },
                { id: 25145, name: 'MAZOOBA' },
                { id: 25146, name: 'MUWOKO' },
              ],
            },
            {
              id: 3943,
              name: 'KYATEREKERA WARD',
              villages: [
                { id: 25155, name: 'HOSPITAL' },
                { id: 25152, name: 'KATWE' },
                { id: 25153, name: 'KIGALAGI' },
                { id: 25154, name: 'KYATEREKERA' },
              ],
            },
          ],
        },
        {
          id: 848,
          name: 'SOUTH DIVISION',
          parishes: [
            {
              id: 3945,
              name: 'BUSAALE WARD',
              villages: [
                { id: 25160, name: 'KALEGULIRO' },
                { id: 25161, name: 'KISAGAZI' },
                { id: 25162, name: 'KISINDIZI' },
                { id: 25163, name: 'KISUNA' },
                { id: 25164, name: 'LWEBIGAJI' },
              ],
            },
            {
              id: 3949,
              name: 'GAYAZA WARD',
              villages: [
                { id: 25174, name: 'GAYAAZA' },
                { id: 25176, name: 'KAYUNGA' },
                { id: 25177, name: 'KYAMUGUMA' },
                { id: 25175, name: 'KYEJUNGA' },
                { id: 25178, name: 'KYEWANISE' },
              ],
            },
            {
              id: 3947,
              name: 'KATTABALANGA WARD',
              villages: [
                { id: 25169, name: 'KATTABALANGA A' },
                { id: 25170, name: 'KATTABALANGA B' },
              ],
            },
            {
              id: 3948,
              name: 'KIRUNGI WARD',
              villages: [
                { id: 25171, name: 'KIKONA/KYABATAAGI' },
                { id: 25172, name: 'KIRUNGI A' },
                { id: 25173, name: 'KIRUNGI B' },
              ],
            },
            {
              id: 3946,
              name: 'KISEKENDE WARD',
              villages: [
                { id: 25168, name: 'BAKIJULULA' },
                { id: 25166, name: 'KAWUKA' },
                { id: 25165, name: 'KISEKENDE' },
                { id: 25167, name: 'KISEKENDE CENTRAL' },
              ],
            },
            {
              id: 3950,
              name: 'LWABAGABO WARD',
              villages: [
                { id: 25179, name: 'KYEGULUUSO' },
                { id: 25180, name: 'LWABAGABO' },
                { id: 25181, name: 'NAMAGOGO' },
                { id: 25182, name: 'NJERU' },
              ],
            },
          ],
        },
        {
          id: 849,
          name: 'WEST DIVISION',
          parishes: [
            {
              id: 3951,
              name: 'BIWANGA WARD',
              villages: [
                { id: 25183, name: 'BIWANGA' },
                { id: 25184, name: 'KAJUNJU' },
                { id: 25185, name: 'KISUJJA' },
                { id: 25186, name: 'KYANASIKI' },
              ],
            },
            {
              id: 3957,
              name: 'KASENYI/CALTEX WARD',
              villages: [
                { id: 25210, name: 'KASENYI/CALTEX' },
                { id: 25211, name: 'KATAWA  A' },
                { id: 25212, name: 'KATAWA  B' },
              ],
            },
            {
              id: 3953,
              name: 'KATOGO WARD',
              villages: [
                { id: 25195, name: 'KABASOJJO' },
                { id: 25196, name: 'KATOGO' },
                { id: 25197, name: 'MAIN STREET' },
                { id: 25198, name: 'MAKENKE' },
              ],
            },
            {
              id: 3955,
              name: 'KAYINJA WARD',
              villages: [
                { id: 25202, name: 'KANYEGERA' },
                { id: 25203, name: 'KATOMA' },
                { id: 25204, name: 'KAYINJA' },
                { id: 25205, name: 'KYANYINA' },
              ],
            },
            {
              id: 3956,
              name: 'MIJUNWA WARD',
              villages: [
                { id: 25206, name: 'KABAJOKI' },
                { id: 25207, name: 'KABATENDE' },
                { id: 25208, name: 'KISONGA' },
                { id: 25209, name: 'MIJJUNWA' },
              ],
            },
            {
              id: 3952,
              name: 'NABIKAKALA WARD',
              villages: [
                { id: 25187, name: 'BAGEZZA' },
                { id: 25188, name: 'BULIISA' },
                { id: 25194, name: 'KASENKE' },
                { id: 25189, name: 'KATUNDA' },
                { id: 25190, name: 'KIBUTAMO' },
                { id: 25191, name: 'KISAAWE' },
                { id: 25192, name: 'KYAMUKOONA' },
                { id: 25193, name: 'NABIKAKALA' },
              ],
            },
            {
              id: 3954,
              name: 'NAKAYIMA WARD',
              villages: [
                { id: 25199, name: 'BOMA HILL' },
                { id: 25201, name: 'KIBYAYI A' },
                { id: 25200, name: 'KIBYAYI B' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
