import { District } from '../types';

export default {
  id: 60,
  name: 'MUKONO',
  counties: [
    {
      id: 139,
      name: 'MUKONO COUNTY NORTH',
      sub_counties: [
        {
          id: 850,
          name: 'KYAMPISI',
          parishes: [
            {
              id: 3958,
              name: 'BULIJJO',
              villages: [
                { id: 25213, name: 'BULIJJO' },
                { id: 25214, name: 'BUNYIRI' },
                { id: 25215, name: 'KALAGI' },
                { id: 25216, name: 'KASOZI  A' },
                { id: 25217, name: 'KASOZI  B' },
                { id: 25218, name: 'KIKAABYA' },
                { id: 25219, name: 'KITANDA' },
                { id: 25220, name: 'NAALYA' },
                { id: 25221, name: 'NABIYAGI' },
                { id: 25222, name: 'NAMMERE' },
                { id: 25223, name: 'NKONGE' },
              ],
            },
            {
              id: 3961,
              name: 'DDUNDU',
              villages: [
                { id: 25245, name: 'BAMUTAKUDDE' },
                { id: 25246, name: 'BUNTABA' },
                { id: 25247, name: 'DDUNDU' },
                { id: 25248, name: 'KALAGALA' },
                { id: 25249, name: 'KASAAYI  A' },
                { id: 25250, name: 'KASAAYI  B' },
                { id: 25251, name: 'KIRYAMULI' },
                { id: 25252, name: 'KYOGA' },
                { id: 25253, name: 'MUSOMBWA' },
                { id: 25254, name: 'NAKASAJJA' },
                { id: 25257, name: 'NAKKOBA' },
                { id: 25255, name: 'NAKUMBO' },
                { id: 25256, name: 'NAMULABA' },
              ],
            },
            {
              id: 3959,
              name: 'KABEMBE',
              villages: [
                { id: 25224, name: 'KABEMBE' },
                { id: 25225, name: "KALEBERA 'A'" },
                { id: 25226, name: "KALEBERA 'B'" },
                { id: 25227, name: 'KATEETE' },
                { id: 25228, name: 'KATEGA' },
                { id: 25229, name: 'KIKANDWA' },
                { id: 25230, name: 'KIMOTE' },
                { id: 25231, name: 'KIYUNGA' },
                { id: 25232, name: 'LUGAMBA' },
                { id: 25233, name: 'MBALIGA' },
                { id: 25234, name: 'MIGGO' },
                { id: 25235, name: 'NAMIREMBE' },
              ],
            },
            {
              id: 3960,
              name: 'KYABAKADDE',
              villages: [
                { id: 25236, name: 'BULIMU' },
                { id: 25237, name: 'KAKOOLA' },
                { id: 25238, name: 'KALAGI' },
                { id: 25239, name: 'KASALA' },
                { id: 25240, name: 'KYABAKADDE' },
                { id: 25241, name: 'KYAMPISI' },
                { id: 25242, name: 'NAMANGANGA' },
                { id: 25243, name: 'NAMMENGO' },
                { id: 25244, name: 'NKONGE' },
              ],
            },
            {
              id: 3962,
              name: 'NTONTO',
              villages: [
                { id: 25258, name: 'KASANGA' },
                { id: 25259, name: 'KASENENE' },
                { id: 25260, name: 'KONERO' },
                { id: 25261, name: 'KWAABA' },
                { id: 25262, name: 'LUGUZI' },
                { id: 25263, name: 'LUSANJA' },
                { id: 25264, name: 'MULUNGIOMU' },
                { id: 25265, name: 'NAKUMBO' },
                { id: 25266, name: 'NAMASUMBI' },
                { id: 25267, name: 'NATEETE' },
                { id: 25268, name: 'NTONTO' },
              ],
            },
          ],
        },
        {
          id: 851,
          name: 'NAMA',
          parishes: [
            {
              id: 3963,
              name: 'BULIIKA',
              villages: [
                { id: 25269, name: 'BULIKA' },
                { id: 25270, name: "LUTENGO 'A'" },
                { id: 25271, name: "LUTENGO 'B'" },
                { id: 25272, name: 'NAMULUGWE' },
                { id: 25273, name: 'WABUNUNU' },
                { id: 25274, name: 'WAKISO' },
              ],
            },
            {
              id: 3964,
              name: 'KASENGE',
              villages: [
                { id: 25275, name: 'KAPEKE' },
                { id: 25276, name: "KASENGE 'A'" },
                { id: 25277, name: "KASENGE 'B'" },
                { id: 25278, name: 'KIVUUVU' },
                { id: 25279, name: 'NAKAPINYI NORTH' },
                { id: 25280, name: 'NAKAPINYI SOUTH' },
              ],
            },
            {
              id: 3965,
              name: 'KATOOGO',
              villages: [
                { id: 25281, name: 'BUYUKI' },
                { id: 25282, name: 'KABULA' },
                { id: 25283, name: 'KAKOOLA' },
                { id: 25284, name: 'KATOOGO' },
                { id: 25285, name: 'KAYUNGA' },
                { id: 25286, name: 'LUKALU/KIMBUGUMA' },
                { id: 25287, name: 'NABITIMPA' },
                { id: 25288, name: 'SAMUUKA' },
                { id: 25289, name: 'WALUGA' },
              ],
            },
            {
              id: 3966,
              name: 'MPOMA',
              villages: [
                { id: 25290, name: 'BUYUKI' },
                { id: 25291, name: 'KIBOOBA' },
                { id: 25292, name: 'KISOWERA' },
                { id: 25293, name: 'KITUBA' },
                { id: 25294, name: 'LUKOJJO' },
                { id: 25295, name: 'LUWUNGA' },
                { id: 25296, name: 'MABUYE' },
                { id: 25297, name: 'MPOMA' },
                { id: 25298, name: 'NALYA - KAMPUNGU' },
                { id: 25299, name: 'NAMA I' },
                { id: 25300, name: 'NAMA II' },
                { id: 25301, name: 'NKOOKI' },
                { id: 25302, name: 'NSANVU' },
              ],
            },
            {
              id: 3968,
              name: 'NAMAWOJJOLO',
              villages: [
                { id: 25308, name: 'BULIGOBE' },
                { id: 25314, name: 'BWEFULUMAY WEST' },
                { id: 25309, name: 'BWEFULUMYA EAST' },
                { id: 25310, name: 'NAMAWOJJOLO EAST' },
                { id: 25311, name: 'NAMAWOJJOLO WEST' },
                { id: 25312, name: 'WALUSUBI' },
                { id: 25313, name: 'WANJEYO' },
              ],
            },
            {
              id: 3967,
              name: 'NAMUBIRU',
              villages: [
                { id: 25303, name: 'KIKUBANKIMA' },
                { id: 25304, name: 'KIRANGIRA' },
                { id: 25305, name: 'LWANYONYI' },
                { id: 25306, name: 'NAMUBIRU' },
                { id: 25307, name: 'TAKAJJUNGE' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 140,
      name: 'MUKONO COUNTY SOUTH',
      sub_counties: [
        {
          id: 856,
          name: 'KATOSI TOWN COUNCIL',
          parishes: [
            {
              id: 3992,
              name: 'BUNAKIJJA WARD',
              villages: [
                { id: 25451, name: 'BUNAKIJJA' },
                { id: 25452, name: 'GOLOMOLO' },
                { id: 25453, name: 'LUGOBA' },
              ],
            },
            {
              id: 3994,
              name: 'KALENGERA WARD',
              villages: [
                { id: 25457, name: 'BUGONGE' },
                { id: 25458, name: 'KALENGERA A' },
                { id: 25459, name: 'KALENGERA B' },
                { id: 25460, name: 'KIKOONA' },
              ],
            },
            {
              id: 3995,
              name: 'KATOSI WARD',
              villages: [
                { id: 25461, name: 'BWANGA' },
                { id: 25462, name: 'KATOSI CENTRAL' },
                { id: 25463, name: 'KIZAALA BUGANDA' },
              ],
            },
            {
              id: 3996,
              name: 'LUGAZI WARD',
              villages: [
                { id: 25464, name: 'KULUBBI' },
                { id: 25465, name: 'LUGAZI' },
              ],
            },
            {
              id: 3993,
              name: 'NSANJA WARD',
              villages: [
                { id: 25454, name: 'GONVE' },
                { id: 25455, name: 'KIKUUTA' },
                { id: 25456, name: 'NSANJA' },
              ],
            },
          ],
        },
        {
          id: 852,
          name: 'KOOME ISLANDS',
          parishes: [
            {
              id: 3969,
              name: 'BUGOMBE',
              villages: [
                { id: 25315, name: 'BUGAZI' },
                { id: 25316, name: 'BUGOMBE' },
                { id: 25317, name: 'BULAGO - KAWUNGULI' },
                { id: 25318, name: 'LWAZI' },
                { id: 25319, name: 'ZINGOOLA' },
              ],
            },
            {
              id: 3970,
              name: 'BUSANGA',
              villages: [
                { id: 25320, name: 'BUSANGA' },
                { id: 25321, name: 'KANSAMBWE' },
                { id: 25322, name: 'KIMMI-BANGA' },
                { id: 25323, name: 'KISIGALA' },
                { id: 25324, name: 'LUBEMBE' },
                { id: 25325, name: 'NGAGA' },
                { id: 25326, name: 'TABALIRO' },
              ],
            },
            {
              id: 3971,
              name: 'LWOMOLO',
              villages: [
                { id: 25327, name: 'BUUJE/KITOSI' },
                { id: 25328, name: 'BUYANA' },
                { id: 25329, name: 'KAKUNYU' },
                { id: 25334, name: 'KASENYI - BUSI' },
                { id: 25330, name: 'LUGUMBA' },
                { id: 25331, name: 'LWANGAMUTO' },
                { id: 25332, name: 'LWOMOLO' },
                { id: 25333, name: 'MISENYI' },
                { id: 25335, name: 'NAMUGAMBE - KIBATIIRA' },
              ],
            },
            {
              id: 3972,
              name: 'MUBEMBE',
              villages: [
                { id: 25336, name: 'BATWALA' },
                { id: 25337, name: 'KALYAMBUZI' },
                { id: 25339, name: 'KATOLO' },
                { id: 25340, name: 'KISU' },
                { id: 25341, name: 'MUBEMBE' },
                { id: 25342, name: 'MUWOMA - KAKEEKA' },
                { id: 25338, name: 'NAMBU' },
                { id: 25343, name: 'NYANAMA' },
              ],
            },
          ],
        },
        {
          id: 855,
          name: 'MPATTA',
          parishes: [
            {
              id: 3985,
              name: 'KABANGA',
              villages: [
                { id: 25426, name: 'BUTERE' },
                { id: 25427, name: 'GOBERO' },
                { id: 25428, name: 'KABANGA' },
                { id: 25429, name: 'SSUGU - LUGALA' },
              ],
            },
            {
              id: 3987,
              name: 'KIYANJA',
              villages: [
                { id: 25433, name: 'BANGA' },
                { id: 25434, name: 'BULIKAASA' },
                { id: 25435, name: 'KAWUNA' },
                { id: 25436, name: 'KIYANJA' },
              ],
            },
            {
              id: 3986,
              name: 'MPATTA',
              villages: [
                { id: 25430, name: 'BUKULE' },
                { id: 25431, name: 'MPATTA' },
                { id: 25432, name: 'NTUNDA' },
              ],
            },
            {
              id: 3988,
              name: 'MUBANDA',
              villages: [
                { id: 25438, name: 'BULE' },
                { id: 25437, name: 'BUSOKE' },
                { id: 25439, name: 'KISINSI' },
                { id: 25440, name: 'MUBANDA-LWEZA' },
              ],
            },
            {
              id: 3989,
              name: 'MUGOMBA',
              villages: [
                { id: 25441, name: 'BUGIGI' },
                { id: 25442, name: 'MUGOMBA' },
                { id: 25443, name: 'SSOZI' },
              ],
            },
            {
              id: 3990,
              name: 'NAKALANDA',
              villages: [
                { id: 25444, name: 'BUYUNJU' },
                { id: 25445, name: 'MAWOTTO' },
                { id: 25446, name: 'NAKALANDA' },
              ],
            },
            {
              id: 3991,
              name: 'TTABA',
              villages: [
                { id: 25448, name: 'BUWUNGA' },
                { id: 25447, name: 'BWANIKA' },
                { id: 25449, name: 'MPENJA' },
                { id: 25450, name: 'TTABA' },
              ],
            },
          ],
        },
        {
          id: 854,
          name: 'MPUNGE',
          parishes: [
            {
              id: 3982,
              name: 'LULAGWE',
              villages: [
                { id: 25413, name: 'KIZIRU' },
                { id: 25414, name: 'KYAZI' },
                { id: 25415, name: 'LULAGWE' },
                { id: 25416, name: 'MUVO' },
              ],
            },
            {
              id: 3983,
              name: 'MBAZI',
              villages: [
                { id: 25417, name: 'BULEEBI' },
                { id: 25418, name: 'KAMWANYI' },
                { id: 25419, name: 'MBAZI' },
                { id: 25420, name: 'SANGO' },
              ],
            },
            {
              id: 3981,
              name: 'MPUNGE',
              villages: [
                { id: 25407, name: 'BUSOKE' },
                { id: 25408, name: 'KIKEERA' },
                { id: 25409, name: 'KIRUDDU' },
                { id: 25410, name: 'MASUJJU' },
                { id: 25411, name: 'MENGO' },
                { id: 25412, name: 'MPUNGE' },
              ],
            },
            {
              id: 3984,
              name: 'NGOMBERE',
              villages: [
                { id: 25421, name: 'BUWUJJA-MBEYA' },
                { id: 25422, name: 'KAGULU' },
                { id: 25423, name: 'KIKUBO' },
                { id: 25424, name: 'MBALE' },
                { id: 25425, name: 'NGOMBERE' },
              ],
            },
          ],
        },
        {
          id: 853,
          name: 'NAKISUNGA',
          parishes: [
            {
              id: 3973,
              name: 'KATENTE',
              villages: [
                { id: 25344, name: 'GAMBA' },
                { id: 25345, name: "KATENTE 'A'" },
                { id: 25346, name: "KATENTE 'B'" },
                { id: 25347, name: 'KATWE' },
                { id: 25348, name: 'KISOKO' },
                { id: 25349, name: 'LUGALA' },
                { id: 25350, name: 'NTOVE' },
                { id: 25351, name: 'WANKATA' },
              ],
            },
            {
              id: 3974,
              name: 'KIYOOLA',
              villages: [
                { id: 25352, name: 'BANDA-SUNGA' },
                { id: 25353, name: 'BUMBAJJA' },
                { id: 25354, name: 'BUZZU' },
                { id: 25355, name: 'KISOZI' },
                { id: 25356, name: 'KIYOOLA' },
                { id: 25357, name: 'NANTUULA' },
                { id: 25358, name: 'NASSAKA' },
                { id: 25359, name: 'NSONGA' },
              ],
            },
            {
              id: 3975,
              name: 'KYABALOGO',
              villages: [
                { id: 25360, name: 'BANDA-BUGENDERADDALA' },
                { id: 25361, name: 'BANDA-KYANDAAZA' },
                { id: 25362, name: 'LUSERA' },
                { id: 25363, name: 'NAKISUNGA' },
                { id: 25364, name: 'NAMAKWA' },
                { id: 25365, name: 'NTAKAFUNVU' },
              ],
            },
            {
              id: 3980,
              name: 'KYETUME',
              villages: [
                { id: 25402, name: 'BUKASA' },
                { id: 25403, name: 'KAZINGA' },
                { id: 25404, name: 'KYETUME' },
                { id: 25405, name: 'LUFUNVE' },
                { id: 25406, name: 'NTALE-KYEYO' },
              ],
            },
            {
              id: 3976,
              name: 'NAMAYIBA',
              villages: [
                { id: 25366, name: 'BUZIRANJOVU' },
                { id: 25367, name: 'KAKUBA-KIYANJA' },
                { id: 25368, name: 'KATUBA' },
                { id: 25369, name: 'KITYABULE' },
                { id: 25370, name: 'LUBUGUMU' },
                { id: 25371, name: 'LUWULE' },
                { id: 25374, name: 'MAWA/MANGALIBA' },
                { id: 25372, name: 'NAMAYIBA' },
                { id: 25373, name: 'SSANGA' },
              ],
            },
            {
              id: 3977,
              name: 'NAMUYENJE',
              villages: [
                { id: 25375, name: 'KIWUGO' },
                { id: 25380, name: 'KYAWAMBOGO' },
                { id: 25376, name: 'NAKOOSI' },
                { id: 25377, name: 'NAMUYENJE' },
                { id: 25378, name: 'NANGWA' },
                { id: 25379, name: 'NTULUMUKO' },
              ],
            },
            {
              id: 3978,
              name: 'SEETA-NAZIGO',
              villages: [
                { id: 25381, name: 'BUSIMBE' },
                { id: 25382, name: 'BUWAALI' },
                { id: 25383, name: 'KAVULE' },
                { id: 25384, name: 'KIRIJJA-BUTOOKE' },
                { id: 25385, name: 'KIRONDO' },
                { id: 25386, name: 'KIRWANYI' },
                { id: 25387, name: 'KITEZA' },
                { id: 25388, name: 'MAKATA' },
                { id: 25389, name: 'NAMALIGA' },
                { id: 25390, name: 'SEETA - NAZIGO' },
              ],
            },
            {
              id: 3979,
              name: 'WANKOBA',
              villages: [
                { id: 25391, name: 'BUSAALE' },
                { id: 25392, name: 'BUSIBA' },
                { id: 25393, name: 'KERITA' },
                { id: 25394, name: 'KISOLOOZA' },
                { id: 25395, name: 'LUKONGE' },
                { id: 25396, name: 'MWANYANGIRI' },
                { id: 25397, name: 'NALUVULE' },
                { id: 25398, name: 'NAMINA' },
                { id: 25399, name: 'NAWANJUKI' },
                { id: 25400, name: 'WABINYIRA' },
                { id: 25401, name: 'WANKOBA' },
              ],
            },
          ],
        },
        {
          id: 857,
          name: 'NTENJERU-KISOGA TOWN COUNCIL',
          parishes: [
            {
              id: 3997,
              name: 'BUGOYE WARD',
              villages: [
                { id: 25466, name: 'BUGOYE' },
                { id: 25467, name: 'BUNYAMA' },
                { id: 25468, name: 'KABIRA' },
                { id: 25469, name: 'LWETEEGA' },
                { id: 25470, name: 'MIREMBE' },
              ],
            },
            {
              id: 4003,
              name: 'KISOGA WARD',
              villages: [
                { id: 25494, name: "KISOGA 'A'" },
                { id: 25495, name: "KISOGA 'B'" },
                { id: 25496, name: 'KISOGA CENTRAL' },
                { id: 25497, name: 'KITO-KIGANDA' },
              ],
            },
            {
              id: 4001,
              name: 'MAZIBA WARD',
              villages: [
                { id: 25486, name: 'LUUTE' },
                { id: 25487, name: 'MAVUNIKIRE' },
                { id: 25488, name: 'MAZIBA' },
              ],
            },
            {
              id: 4002,
              name: 'MPUMU WARD',
              villages: [
                { id: 25489, name: 'LUBERENGA' },
                { id: 25490, name: 'LUGA-KAZINGA' },
                { id: 25491, name: 'LUGGA' },
                { id: 25492, name: 'MPOLOGOMA' },
                { id: 25493, name: 'MPUMU' },
              ],
            },
            {
              id: 3998,
              name: 'NTENJERU-NTANZI WARD',
              villages: [
                { id: 25471, name: 'BUGOLOMBE' },
                { id: 25472, name: 'KIWAFU TEA ESTATE' },
                { id: 25473, name: 'NAMATABA' },
                { id: 67845, name: 'NSUMBA' },
                { id: 25474, name: 'NTANZI/MBAJJA' },
                { id: 25475, name: 'NTENJERU' },
              ],
            },
            {
              id: 3999,
              name: 'SSAAYI WARD',
              villages: [
                { id: 25476, name: 'KALAGALA' },
                { id: 25477, name: 'KAZO' },
                { id: 25478, name: 'KITUUZA' },
                { id: 25479, name: 'NAKASUKU' },
                { id: 25480, name: 'NAKIBANGA' },
                { id: 25481, name: 'NTUMUSI' },
                { id: 25482, name: 'SSAAYI' },
              ],
            },
            {
              id: 4000,
              name: 'TERERE WARD',
              villages: [
                { id: 25483, name: 'BUNANKANDA' },
                { id: 25484, name: 'BUTININDI' },
                { id: 25485, name: 'TERERE' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 142,
      name: 'MUKONO MUNICIPALITY',
      sub_counties: [
        {
          id: 866,
          name: 'GOMA DIVISION',
          parishes: [
            {
              id: 4046,
              name: 'BUKERERE WARD',
              villages: [
                { id: 25733, name: 'BUKERERE' },
                { id: 25734, name: 'KAGALA' },
                { id: 25735, name: 'KIWANGO/NAMWEZI' },
                { id: 25736, name: 'KYESEREKA' },
                { id: 25737, name: 'MAWANGALA/KINAFU' },
                { id: 25738, name: 'NAKAGERE' },
                { id: 25739, name: 'NAMASIGA' },
                { id: 25740, name: 'NYANJA' },
                { id: 25741, name: 'PAPATI/BUWAVA/NATONKO' },
              ],
            },
            {
              id: 4047,
              name: 'MISINDYE WARD',
              villages: [
                { id: 25742, name: 'GOMA - MISINDYE' },
                { id: 25743, name: 'JINJA - MISINDYE' },
                { id: 25744, name: 'JJOGGO' },
                { id: 25745, name: 'LUMULI' },
                { id: 25746, name: 'NAMYOOYA' },
                { id: 25747, name: 'SONDE' },
              ],
            },
            {
              id: 4048,
              name: 'NANTABULIRWA WARD',
              villages: [
                { id: 25748, name: 'DEGEYA-SSENYI' },
                { id: 25749, name: 'KASOKOSO-SAGALANKOKO' },
                { id: 25750, name: 'KITALE' },
                { id: 25751, name: 'KIWANGA-RWANDA' },
                { id: 25752, name: 'KKOLO' },
                { id: 25753, name: 'MAWOTTO' },
                { id: 25754, name: 'NAMILYANGO-KISENYI' },
                { id: 25755, name: 'NANTABULIRWA' },
              ],
            },
            {
              id: 4049,
              name: 'NYENJE WARD',
              villages: [
                { id: 25756, name: 'BAJJO' },
                { id: 25757, name: 'BUDDUGALA' },
                { id: 25758, name: 'KIGUUNGA' },
                { id: 25759, name: 'NSAMBWE' },
                { id: 25760, name: 'NYENJE' },
              ],
            },
            {
              id: 4050,
              name: 'SEETA WARD',
              villages: [
                { id: 25761, name: 'BAGGALA' },
                { id: 25762, name: 'BUGOBA' },
                { id: 25763, name: 'GONGOBE' },
                { id: 25764, name: 'GULAMA' },
                { id: 25765, name: 'GWAFU CENTRAL' },
                { id: 25766, name: 'GWAFU WEST' },
                { id: 25767, name: 'KIROWOZA' },
                { id: 25768, name: 'NABUTA' },
                { id: 25769, name: 'NJERERE' },
                { id: 25770, name: 'NTINDA' },
              ],
            },
          ],
        },
        {
          id: 867,
          name: 'MUKONO DIVISION',
          parishes: [
            {
              id: 4054,
              name: 'GGULU WARD',
              villages: [
                { id: 25801, name: 'AGIP' },
                { id: 25802, name: 'COLLINE' },
                { id: 25803, name: "GGULU 'A'" },
                { id: 25804, name: 'HAMU-MUKASA' },
                { id: 25805, name: 'KASANGALABI' },
                { id: 25806, name: 'KIGOMBYA NORTH' },
                { id: 25807, name: 'KIRANGIRA' },
                { id: 25808, name: 'KITETE' },
                { id: 25809, name: 'NGANDU' },
                { id: 25810, name: 'SSAZA' },
                { id: 25811, name: 'TOTAL' },
              ],
            },
            {
              id: 4053,
              name: 'NAMUMIRA/ANTHONY WARD',
              villages: [
                { id: 25789, name: 'ANTHONY' },
                { id: 25790, name: 'BASIIMA-KIKOOZA' },
                { id: 25791, name: 'CENTRAL NABUTI' },
                { id: 25792, name: 'DDANDIRA' },
                { id: 25793, name: 'GUNGA' },
                { id: 25794, name: 'KAVULE' },
                { id: 25795, name: 'KIGOMBYA' },
                { id: 25796, name: 'KITEGA' },
                { id: 25797, name: 'LOWER - NABUTI' },
                { id: 25798, name: 'LWEZA' },
                { id: 25799, name: 'NAMUMIRA' },
                { id: 25800, name: "NSUUBE 'A'" },
              ],
            },
            {
              id: 4051,
              name: 'NSUUBE/KAUGA WARD',
              villages: [
                { id: 25771, name: 'BUGUJJU' },
                { id: 25772, name: 'KATI-KOLO' },
                { id: 25773, name: 'KYUNGU' },
                { id: 25774, name: 'MATERNITY' },
                { id: 25775, name: 'MUKONO HILL' },
                { id: 25776, name: 'NABUTI' },
                { id: 25777, name: "NSUUBE 'B'" },
                { id: 25778, name: 'UPPER KAUGA' },
                { id: 25779, name: 'UPPER NABUTI' },
              ],
            },
            {
              id: 4052,
              name: 'NTAWO WARD',
              villages: [
                { id: 25780, name: 'BUTEBE' },
                { id: 25781, name: 'D.F.I.' },
                { id: 25782, name: 'INDUSTRIAL AREA' },
                { id: 25783, name: 'LOWER KAUGA' },
                { id: 25784, name: 'MULAGO' },
                { id: 25785, name: 'NAKABAGO' },
                { id: 25786, name: 'NASUUTI' },
                { id: 25787, name: 'NSAMBWE' },
                { id: 25788, name: 'NTAWO' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 141,
      name: 'NAKIFUMA COUNTY',
      sub_counties: [
        {
          id: 858,
          name: 'KASAWO',
          parishes: [
            {
              id: 4004,
              name: 'KAKUKUULU',
              villages: [
                { id: 25498, name: 'BUGABO' },
                { id: 25499, name: 'KAKUKULU' },
                { id: 25500, name: 'KIKUBE' },
                { id: 25501, name: 'KIWERE' },
                { id: 25502, name: 'KIZANYIRIZI' },
                { id: 25503, name: 'NAKASWA' },
                { id: 25504, name: 'NAKIDUDUMA' },
                { id: 25505, name: 'NKOKO' },
              ],
            },
            {
              id: 4005,
              name: 'KASANA',
              villages: [
                { id: 25506, name: 'BUTEYONGERA' },
                { id: 25507, name: 'KAKIRA' },
                { id: 25508, name: 'KASALA' },
                { id: 25509, name: 'KASANA' },
                { id: 25510, name: 'KITWE' },
                { id: 25511, name: 'KIYAGI' },
                { id: 25512, name: 'NDIBA' },
              ],
            },
            {
              id: 4006,
              name: 'KIGOGOLA',
              villages: [
                { id: 25513, name: 'BUYUKI' },
                { id: 25514, name: 'KATEETE' },
                { id: 25515, name: 'KIBAMBA' },
                { id: 25516, name: 'KIGOGOLA' },
                { id: 25517, name: 'KISONZI' },
                { id: 25518, name: 'NNONGO' },
                { id: 25519, name: 'NSANVU' },
              ],
            },
            {
              id: 4007,
              name: 'NAMALIRI',
              villages: [
                { id: 25520, name: 'GAVU' },
                { id: 25521, name: 'KAWUTUTU' },
                { id: 25522, name: 'KIGULU' },
                { id: 25523, name: 'NAMALIRI' },
                { id: 25524, name: 'NDESE' },
              ],
            },
          ],
        },
        {
          id: 863,
          name: 'KASAWO TOWN COUNCIL',
          parishes: [
            {
              id: 4025,
              name: 'KABIMBIRI',
              villages: [
                { id: 25647, name: 'CENTRAL' },
                { id: 25648, name: 'EDUCATIONAL' },
                { id: 25644, name: 'KALYOWA' },
                { id: 25645, name: 'NASSEJJOBE' },
                { id: 25646, name: 'SINDA/KIVULUBA' },
              ],
            },
            {
              id: 4027,
              name: 'KABIMBIRI B WARD',
              villages: [
                { id: 25652, name: 'KABIMBIRI' },
                { id: 25654, name: 'KIGGAGA' },
                { id: 25653, name: 'KIKANDWA' },
              ],
            },
            {
              id: 4030,
              name: 'KASAWO WARD',
              villages: [
                { id: 25660, name: 'KASAWO' },
                { id: 25661, name: 'KITEGULA' },
                { id: 25662, name: 'MUBANDA' },
              ],
            },
            {
              id: 4028,
              name: 'KASENGE WARD',
              villages: [
                { id: 25655, name: 'KASENGE' },
                { id: 63502, name: 'KIGAYAZA II' },
                { id: 25656, name: 'KITOVU' },
              ],
            },
            {
              id: 4029,
              name: 'KITALE WARD',
              villages: [
                { id: 63988, name: 'KITALE  BUSIA' },
                { id: 25658, name: "KITALE 'A'" },
                { id: 25659, name: "KITALE 'B'" },
                { id: 25657, name: 'KYEWANISE' },
              ],
            },
            {
              id: 4026,
              name: 'KITOVU',
              villages: [
                { id: 25649, name: 'KIGAYAZA  I' },
                { id: 25650, name: 'KITUNKU' },
                { id: 25651, name: 'MINDI' },
              ],
            },
          ],
        },
        {
          id: 859,
          name: 'KIMENYEDDE',
          parishes: [
            {
              id: 4008,
              name: 'BUKASA',
              villages: [
                { id: 25525, name: 'BUKASA' },
                { id: 25526, name: 'KAWUKU' },
                { id: 25527, name: 'KISOGA' },
                { id: 25528, name: 'NAJJA-KIREKU' },
                { id: 25529, name: 'NAMAKOMO' },
              ],
            },
            {
              id: 4009,
              name: 'KAWONGO',
              villages: [
                { id: 25530, name: 'KAMIRA - BUKONERO' },
                { id: 25531, name: 'KAWONGO' },
                { id: 25536, name: 'KISAMBA - KIRINYABIGO' },
                { id: 25532, name: 'MAYANGAYANGA' },
                { id: 25533, name: 'NAKIBANO' },
                { id: 25534, name: 'WABUSANKE' },
                { id: 25535, name: 'WANJEYO - KALAGALA -  KITO' },
              ],
            },
            {
              id: 4010,
              name: 'KIWAFU',
              villages: [
                { id: 25537, name: 'JUMBA - GENDA' },
                { id: 25538, name: 'KIMENYEDDE' },
                { id: 25539, name: 'KIWAFU' },
                { id: 25540, name: 'MAGONGA - ZIRANSO' },
                { id: 25541, name: 'NABUKUKU - LUBANJA' },
                { id: 25542, name: 'NABULOOTO' },
                { id: 25543, name: 'ZIGULU' },
              ],
            },
            {
              id: 4011,
              name: 'NANGA',
              villages: [
                { id: 25544, name: 'GALIGATYA' },
                { id: 25545, name: 'GIRINYA' },
                { id: 25546, name: 'KAKAKALA' },
                { id: 25547, name: 'KIBIRIBIRI' },
                { id: 25548, name: 'KITUBA - NABIBUGGA' },
                { id: 25549, name: 'KIYIRIBWA' },
                { id: 25550, name: 'NANGA' },
                { id: 25551, name: 'NDWADDEMUTWE' },
              ],
            },
          ],
        },
        {
          id: 860,
          name: 'NAGOJJE',
          parishes: [
            {
              id: 4012,
              name: 'KYAJJA',
              villages: [
                { id: 25552, name: 'BUBIRO' },
                { id: 25553, name: 'BUKUKU' },
                { id: 25554, name: 'BULANGA' },
                { id: 25555, name: 'KIWALA' },
                { id: 25556, name: 'KYAJJA' },
                { id: 25557, name: 'NAMANYAMA' },
              ],
            },
            {
              id: 4013,
              name: 'NAGOJJE',
              villages: [
                { id: 25558, name: 'KALAGI' },
                { id: 25559, name: 'KAWUTUTU' },
                { id: 25560, name: 'MAGADA' },
                { id: 25561, name: 'MAYANGAYANGA' },
                { id: 25562, name: 'NAGOJJE' },
                { id: 25563, name: 'NAKASEETA II' },
                { id: 25564, name: 'NAMIREMBE' },
                { id: 25565, name: 'NATYOLE' },
                { id: 25566, name: 'NDEEBA' },
              ],
            },
            {
              id: 4014,
              name: 'NAKIBANO',
              villages: [
                { id: 25567, name: 'KASANA' },
                { id: 25568, name: 'KASOKOSO' },
                { id: 25569, name: 'KYETUME I' },
                { id: 25570, name: 'KYETUME II' },
                { id: 25571, name: 'MANGIRA' },
                { id: 25572, name: 'NAMASINDA' },
                { id: 25573, name: 'NANFUMBA' },
                { id: 25574, name: 'WABULONGO' },
              ],
            },
            {
              id: 4015,
              name: 'WAGGALA',
              villages: [
                { id: 25575, name: 'KASAALA' },
                { id: 25576, name: 'KASININYA' },
                { id: 25577, name: 'KISOOBA' },
                { id: 25578, name: 'KITTO' },
                { id: 25579, name: 'KYEGALASO' },
                { id: 25580, name: 'LUNNYA' },
                { id: 25581, name: 'MASIKO' },
                { id: 25582, name: 'WAGGALA' },
                { id: 25583, name: 'WASSWA' },
              ],
            },
          ],
        },
        {
          id: 864,
          name: 'NAKIFUMA-NAGGALAMA TOWN COUNCIL',
          parishes: [
            {
              id: 4031,
              name: 'BAMUSUUTA-RURAL WARD',
              villages: [
                { id: 25663, name: 'BAMUSUTA A' },
                { id: 25664, name: 'BAMUSUTA B' },
                { id: 25665, name: 'BUSABALA' },
                { id: 25666, name: 'KAKAKALA' },
                { id: 25667, name: 'KAYUNGA' },
                { id: 25668, name: 'KIYAGI' },
                { id: 25669, name: 'NALUBABWE' },
              ],
            },
            {
              id: 4037,
              name: 'BANDAALI WARD',
              villages: [
                { id: 25699, name: 'BANDAALI' },
                { id: 25695, name: 'BUSENYA - NYWEDDEMALWA' },
                { id: 25696, name: 'DDIIKWE' },
                { id: 25697, name: 'NAMALIGA' },
                { id: 67412, name: 'NAMYOYA' },
                { id: 25698, name: 'NEKOYEDDE -  GAYAZA' },
              ],
            },
            {
              id: 4038,
              name: 'BUBIRO WARD',
              villages: [
                { id: 25700, name: 'BUBIRO' },
                { id: 25701, name: 'NAKIWATE' },
              ],
            },
            {
              id: 4039,
              name: 'KIGAGA-JOMAYI WARD',
              villages: [
                { id: 25703, name: 'BUZIRANDULU' },
                { id: 25702, name: 'KAKINZI' },
                { id: 25704, name: 'KYANKIMA' },
                { id: 25705, name: 'NENYODDE' },
              ],
            },
            {
              id: 4035,
              name: 'MAKUKUBA WARD',
              villages: [
                { id: 25682, name: 'BUGEREKA' },
                { id: 25683, name: 'GONVE' },
                { id: 25684, name: 'KABULO' },
                { id: 25685, name: 'KAWOOMYA' },
                { id: 25686, name: 'KIZIIMA' },
                { id: 25687, name: 'MAKUKUBA' },
                { id: 25688, name: 'NABBAALE I' },
                { id: 25689, name: 'NABBAALE II' },
                { id: 25690, name: 'NAMASENGERE' },
              ],
            },
            {
              id: 4032,
              name: 'NABALANGA RURAL WARD',
              villages: [
                { id: 25670, name: 'KABAWALA' },
                { id: 25671, name: 'LUSANJA' },
                { id: 25672, name: 'MAGOGGO' },
                { id: 25673, name: 'NABALANGA' },
                { id: 25674, name: 'NKULAGIRIRE' },
              ],
            },
            {
              id: 4033,
              name: 'NAGGALAMA A WARD',
              villages: [
                { id: 25675, name: 'GWENDIDDE' },
                { id: 25676, name: 'KALAGI (BBOSA NABBALE)' },
                { id: 25677, name: 'KAZINGA' },
                { id: 25678, name: 'KIWANGWA' },
                { id: 25679, name: 'KIWEBWA' },
                { id: 25680, name: 'WABIKOKOMA' },
              ],
            },
            {
              id: 4040,
              name: 'NAGGALAMA B WARD',
              villages: [
                { id: 25706, name: 'LUTENGO' },
                { id: 25707, name: 'NAGGALAMA  MISSION' },
                { id: 25708, name: 'NAGGALAMA  PROFESSIONAL' },
                { id: 25709, name: 'NAGGALAMA TOWN' },
              ],
            },
            {
              id: 4041,
              name: 'NAKANYONYI-NABBALE WARD',
              villages: [
                { id: 25710, name: 'BUKOOZA' },
                { id: 25711, name: 'KIJJO' },
                { id: 25712, name: 'KITTO' },
                { id: 25713, name: 'LUKYAAMU' },
                { id: 25715, name: 'NAKANYONYI MISSION LAND' },
                { id: 25714, name: 'NAKANYONYI-KIRANGIRA' },
              ],
            },
            {
              id: 4036,
              name: 'NAKIFUMA WARD',
              villages: [
                { id: 25691, name: 'KAAMA -  KAGANJO' },
                { id: 25692, name: 'KIZUNGU ZONE' },
                { id: 25693, name: 'NAKIFUMA EAST' },
                { id: 25694, name: 'NAKIFUMA WEST' },
              ],
            },
            { id: 4034, name: 'NANKULABYE WARD', villages: [{ id: 25681, name: 'NAKULABYE' }] },
          ],
        },
        {
          id: 865,
          name: 'NAMATABA TOWN COUNCIL',
          parishes: [
            {
              id: 4044,
              name: 'NAMAGUNGA ANNEX WARD',
              villages: [
                { id: 25725, name: 'KALAGALA' },
                { id: 63000, name: 'KASOZI' },
                { id: 25726, name: 'KIKUUTA' },
                { id: 25727, name: 'MONEKO-KASANVU' },
                { id: 25728, name: 'NAKAWALA' },
              ],
            },
            {
              id: 4043,
              name: 'NAMAGUNGA WARD',
              villages: [
                { id: 25722, name: 'KAYANJA A' },
                { id: 25721, name: 'KAYANJA B' },
                { id: 63220, name: 'KAYANJA C' },
                { id: 25723, name: 'NAMAGUNGA A' },
                { id: 25724, name: 'NAMAGUNGA B' },
                { id: 67208, name: 'NAMAGUNGA C' },
              ],
            },
            {
              id: 10052,
              name: 'NAMATABA  A WARD',
              villages: [
                { id: 63338, name: 'KIBAATI' },
                { id: 71063, name: 'WANTAAYI' },
              ],
            },
            {
              id: 4045,
              name: 'NAMATABA B WARD',
              villages: [
                { id: 25730, name: 'KANYOGOGA - CAMP' },
                { id: 25731, name: 'KANYOGOGA - KAAZI' },
                { id: 25729, name: 'NAKALASA TEA ESTATE' },
                { id: 25732, name: 'NAKASEETA I' },
              ],
            },
            {
              id: 4042,
              name: 'NAMATABA WARD',
              villages: [
                { id: 25717, name: 'BULAAYA' },
                { id: 25716, name: 'GALABI' },
                { id: 25718, name: 'KYAWANVUBU' },
                { id: 25719, name: 'MUTTANZIGE' },
                { id: 25720, name: 'NAMATABA CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 861,
          name: 'NAMUGANGA',
          parishes: [
            {
              id: 4016,
              name: 'KAYINI',
              villages: [
                { id: 25584, name: 'BWEGIIRE' },
                { id: 25585, name: 'KAKUKUULU' },
                { id: 25586, name: 'KAYINI  I' },
                { id: 25587, name: 'KAYINI  II' },
                { id: 25588, name: 'KIKOMA' },
                { id: 25589, name: 'KIKONDO' },
                { id: 25590, name: 'KIMEGGA' },
                { id: 25591, name: 'LUGUJE' },
                { id: 25592, name: 'NAKYEEKE' },
              ],
            },
            {
              id: 4017,
              name: 'KITALE',
              villages: [
                { id: 25593, name: 'BUTWALA' },
                { id: 25594, name: 'KAKOOGE' },
                { id: 25595, name: 'KASIISO' },
                { id: 25596, name: 'KATUUSO' },
                { id: 25597, name: 'KITALE  BUSIA' },
                { id: 25598, name: 'LUSERA' },
                { id: 25599, name: 'MAGGWA' },
                { id: 25600, name: 'NAKASENYI' },
              ],
            },
            {
              id: 4018,
              name: 'KITUULA',
              villages: [
                { id: 25601, name: 'GIIMBI I' },
                { id: 25602, name: 'GIIMBI II' },
                { id: 25603, name: 'KITUULA' },
                { id: 25604, name: 'KYANIKA' },
                { id: 25605, name: 'LUGALA' },
                { id: 25606, name: 'MBULAMUTI' },
              ],
            },
            {
              id: 4020,
              name: 'NAMANOGA',
              villages: [
                { id: 25617, name: 'BULONGO' },
                { id: 25618, name: 'BUYITA' },
                { id: 25619, name: 'KAWEERI' },
                { id: 25620, name: 'MAKENKE' },
                { id: 25621, name: 'MAWOTTO' },
                { id: 25622, name: 'NAKADDINDIRI' },
                { id: 25623, name: 'NAKASEJJERE' },
                { id: 25624, name: 'NAMANOGA' },
                { id: 25625, name: 'NJALAALWE' },
                { id: 25626, name: 'NSAABWA  A' },
                { id: 25627, name: 'NSAABWA  B' },
                { id: 25628, name: 'SEETA' },
              ],
            },
            {
              id: 4019,
              name: 'NAMUGANGA',
              villages: [
                { id: 25607, name: 'BUTUMBIIRI' },
                { id: 25608, name: 'KABUMBA' },
                { id: 25609, name: 'KAKAKALA' },
                { id: 25610, name: 'KIBBUYE' },
                { id: 25611, name: 'KYAMBOGO' },
                { id: 25612, name: 'NABIGA' },
                { id: 25613, name: 'NAMUGANGA EAST' },
                { id: 25614, name: 'NAMUGANGA WEST' },
                { id: 25615, name: 'NSAGI' },
                { id: 25616, name: 'NTONTO' },
              ],
            },
          ],
        },
        {
          id: 862,
          name: 'NTUNDA',
          parishes: [
            {
              id: 4021,
              name: 'KATETE',
              villages: [
                { id: 25629, name: 'KALAGALA/NAMUGONGO' },
                { id: 25630, name: 'KATEETE' },
              ],
            },
            {
              id: 4022,
              name: 'KYABAZAALA',
              villages: [
                { id: 25631, name: 'BULYANTI' },
                { id: 25632, name: 'KAWUKU' },
                { id: 25633, name: 'KITEREDDE' },
                { id: 25634, name: 'KYABAZAALA' },
              ],
            },
            {
              id: 4023,
              name: 'NAMAYUBA',
              villages: [
                { id: 25635, name: 'KIKOMA' },
                { id: 25636, name: 'NAMAYUBA' },
                { id: 25637, name: 'NTONTO' },
                { id: 25638, name: 'WALUBIRA' },
              ],
            },
            {
              id: 4024,
              name: 'NTUNDA',
              villages: [
                { id: 25639, name: 'BUYOVU' },
                { id: 25640, name: 'KITAYUNJA' },
                { id: 25641, name: 'NAMUKUPA' },
                { id: 25642, name: 'NAMULABA/KITO' },
                { id: 25643, name: 'NTUNDA' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
