import { District } from '../index';

export default {
  id: 84,
  name: 'NAKAPIRIPIRIT',
  counties: [
    {
      id: 211,
      name: 'CHEKWII COUNTY (KADAM)',
      sub_counties: [
        {
          id: 1317,
          name: 'KAAWACH',
          parishes: [
            {
              id: 6180,
              name: 'KAIKU',
              villages: [
                { id: 58524, name: 'ARIONOMORU' },
                { id: 62147, name: 'KAIDOU' },
                { id: 38963, name: 'LOKITE-A-ADIDA WEST' },
                { id: 65361, name: 'LOKITE-A-DIDA EAST' },
                { id: 38964, name: 'LOMOTOTO' },
                { id: 38965, name: 'MORU-A-LODUK' },
                { id: 38966, name: 'NAKIPENET' },
                { id: 67306, name: 'NAMIATHI' },
                { id: 67604, name: 'NATHAPE' },
              ],
            },
            {
              id: 6183,
              name: 'LOMORIMOR',
              villages: [
                { id: 38972, name: 'AWOYALIRA' },
                { id: 38975, name: 'LOKITELA-A-EKOKOROIT' },
                { id: 38973, name: 'LOKOREETO' },
                { id: 38974, name: 'NAKULUNY' },
              ],
            },
            {
              id: 6181,
              name: 'LOPEROT',
              villages: [
                { id: 38967, name: 'APEICORAIT' },
                { id: 58487, name: 'ARIAMAACHUT' },
                { id: 38968, name: 'LOKITELA -A-LOOKWA' },
                { id: 38969, name: 'LOPEDOT' },
                { id: 67149, name: 'NALAIT B' },
              ],
            },
            {
              id: 6182,
              name: 'MORU-A-AJORE',
              villages: [
                { id: 62869, name: 'KARWATALUK' },
                { id: 65253, name: 'LOBURI-A-LOBONG' },
                { id: 38970, name: 'LOPOROKOCHO PRODUCTION' },
                { id: 38971, name: 'MORU-A-AJORE' },
                { id: 67529, name: 'NARENGEYETHE' },
                { id: 68715, name: 'OKUDUD' },
              ],
            },
            {
              id: 6184,
              name: 'NAABORE',
              villages: [
                { id: 38976, name: 'LOKWASINYON' },
                { id: 38977, name: 'NAABORE A' },
                { id: 38979, name: 'NAABORE B' },
                { id: 66929, name: 'NACHELIT' },
                { id: 38978, name: 'NAKUYON' },
                { id: 67148, name: 'NALAIT A' },
              ],
            },
          ],
        },
        {
          id: 1312,
          name: 'KAKOMONGOLE',
          parishes: [
            {
              id: 6161,
              name: 'AKUYAM',
              villages: [
                { id: 38882, name: 'ARECHEK' },
                { id: 38883, name: 'LOKALE' },
                { id: 65455, name: 'LONGEEM' },
                { id: 38884, name: 'LOOI' },
              ],
            },
            {
              id: 6162,
              name: 'NABOLIS',
              villages: [
                { id: 38885, name: 'LOKADWARAN' },
                { id: 65553, name: 'LOYARABOS' },
                { id: 38886, name: 'NACHEELE' },
                { id: 38887, name: 'NAKOREETE' },
              ],
            },
            {
              id: 6166,
              name: 'NADIP',
              villages: [
                { id: 58480, name: 'ARENGEKIPI' },
                { id: 38905, name: 'ARENGESIEP' },
                { id: 38906, name: 'ATULOM' },
                { id: 38904, name: 'LODOKET-A-NGITOME' },
                { id: 38907, name: 'LOKWABOCHET' },
                { id: 67139, name: 'NAKWARA' },
              ],
            },
            {
              id: 6163,
              name: 'NAMOROTOT',
              villages: [
                { id: 38888, name: 'KAAWAR' },
                { id: 38889, name: 'KILIMANJARO' },
                { id: 38890, name: 'KORUDUP' },
                { id: 38891, name: 'LOMARIAMONG' },
                { id: 38892, name: 'LOMOTOTO' },
                { id: 38893, name: 'LORENGEDWAT' },
                { id: 38894, name: 'NACHEELE' },
              ],
            },
            {
              id: 6164,
              name: 'OKWAPON',
              villages: [
                { id: 38899, name: 'ALIBAMUN' },
                { id: 38895, name: 'LOKEERUMAN' },
                { id: 38896, name: 'LOPEDURU' },
                { id: 66418, name: 'MORUWONGOR' },
                { id: 67194, name: 'NALYAKAT' },
                { id: 38897, name: 'NAMINIT' },
                { id: 38898, name: 'NARUKIENY' },
              ],
            },
            {
              id: 6165,
              name: 'TOKORA',
              villages: [
                { id: 38900, name: 'ACHELEL' },
                { id: 65363, name: 'LOKITELA A NGILOBAE' },
                { id: 65540, name: 'LOUSUGU/LORUSUK' },
                { id: 38901, name: 'NABUR-A-EKALE' },
                { id: 38902, name: 'NAKATEROT' },
                { id: 38903, name: 'TOKORA T/C' },
              ],
            },
          ],
        },
        {
          id: 1319,
          name: 'LEMUSUI',
          parishes: [
            {
              id: 6191,
              name: 'AKOKOR',
              villages: [
                { id: 38996, name: 'AKOKOR' },
                { id: 62659, name: 'KAPETAMUGET' },
                { id: 66416, name: 'MORUPUS' },
                { id: 66930, name: 'NACHESET' },
                { id: 69665, name: 'PELMAT' },
              ],
            },
            {
              id: 6192,
              name: 'ALAPAT',
              villages: [
                { id: 38997, name: 'DOO' },
                { id: 61186, name: 'DUNGELECH' },
                { id: 61369, name: 'GHOGOT' },
                { id: 65420, name: 'LOMAKUKO' },
                { id: 66373, name: 'MORU A AKIMAT' },
                { id: 67534, name: 'NARIONOMOR' },
              ],
            },
            {
              id: 6190,
              name: 'KATABOK',
              villages: [
                { id: 38993, name: 'ALAPAT' },
                { id: 58803, name: 'AYAS' },
                { id: 38994, name: 'CHEPKARARAT' },
                { id: 60977, name: 'CHEPTUMOT' },
                { id: 62024, name: 'KADEKEELE' },
                { id: 38995, name: 'KATABOK' },
              ],
            },
            {
              id: 9896,
              name: 'LOKOMA',
              villages: [
                { id: 58475, name: 'AREMECHOT' },
                { id: 65381, name: 'LOKOMA' },
                { id: 65927, name: 'MAKADA' },
                { id: 66234, name: 'METE' },
                { id: 66956, name: 'NAGEE' },
              ],
            },
            {
              id: 6193,
              name: 'ULINGIRO',
              villages: [
                { id: 60965, name: 'CHEPTEMO' },
                { id: 60996, name: 'CHESIRORO' },
                { id: 66400, name: 'MORUKOL' },
                { id: 38998, name: 'NAKORITARUK' },
                { id: 70922, name: 'ULINGIRO' },
              ],
            },
          ],
        },
        {
          id: 1316,
          name: 'LOREGAE',
          parishes: [
            {
              id: 6179,
              name: 'ALAMACAR',
              villages: [
                { id: 57884, name: 'AKWAKURON' },
                { id: 38961, name: 'ALAMACAR' },
                { id: 65255, name: 'LOBURIN' },
                { id: 65315, name: 'LOITARENG' },
                { id: 67067, name: 'NAKINGOL' },
                { id: 38962, name: 'NAMORUPUS' },
                { id: 67533, name: 'NARIKO' },
              ],
            },
            {
              id: 6176,
              name: 'LOREGAE',
              villages: [
                { id: 38952, name: 'AJOKOKIPI' },
                { id: 65551, name: 'LOWOI/LOOI' },
                { id: 66376, name: 'MORU-A-ENGATUNY' },
                { id: 38953, name: 'NABUKUT' },
                { id: 66926, name: 'NACHEELE' },
                { id: 67571, name: 'NASINYONOIT' },
                { id: 38954, name: 'NAWUALAANGOR' },
              ],
            },
            {
              id: 6177,
              name: 'NAKAALE',
              villages: [
                { id: 58619, name: 'ATEEDEOI' },
                { id: 38955, name: 'KOPETATUM' },
                { id: 65385, name: 'LOKOONA' },
                { id: 38956, name: 'NAKASIAN' },
              ],
            },
            { id: 10369, name: 'NAKALE', villages: [] },
            {
              id: 6178,
              name: 'NATURUM',
              villages: [
                { id: 38957, name: 'APEICORAIT' },
                { id: 38958, name: 'ARECHEK' },
                { id: 62231, name: 'KAKOMOKWEE' },
                { id: 67123, name: 'NAKUR' },
                { id: 38960, name: 'NATURUM TRADING CENTRE' },
                { id: 67624, name: 'NATURUM WEST' },
                { id: 38959, name: 'NAWUALAANGOR' },
              ],
            },
          ],
        },
        {
          id: 1318,
          name: 'LORENG',
          parishes: [
            {
              id: 6187,
              name: 'KOBEYON',
              villages: [
                { id: 38985, name: 'AKWAAKORI' },
                { id: 38986, name: 'KOBEYON' },
                { id: 65271, name: 'LOCHOWA' },
                { id: 65429, name: 'LOMEGURO' },
              ],
            },
            {
              id: 6185,
              name: 'LOASAM',
              villages: [
                { id: 58471, name: 'ARECHEK' },
                { id: 66813, name: 'NABATA' },
                { id: 67005, name: 'NAKAMISITAE' },
                { id: 38980, name: 'NAKAUMEUMEI' },
                { id: 38981, name: 'NAYOROIT' },
              ],
            },
            {
              id: 6186,
              name: 'LORENG',
              villages: [
                { id: 57332, name: 'ACHELEL' },
                { id: 38982, name: 'AWOYAARENG' },
                { id: 58784, name: 'AWOYALIIRA' },
                { id: 38983, name: 'LOBOOLOIN' },
                { id: 65347, name: 'LOKIBUIYO' },
                { id: 38984, name: 'LORENG' },
              ],
            },
            {
              id: 6188,
              name: 'NABULENGER',
              villages: [
                { id: 58383, name: 'APEITOLIM' },
                { id: 38989, name: 'LOMUCHURUS' },
                { id: 38987, name: 'LOOLUNG' },
                { id: 38988, name: 'NABARAP' },
                { id: 38990, name: 'NABULENGER' },
                { id: 66937, name: 'NADEKEL' },
              ],
            },
            {
              id: 6189,
              name: 'NATHINYONOIT',
              villages: [
                { id: 38991, name: 'LOOI' },
                { id: 65542, name: 'LOUTA' },
                { id: 66879, name: 'NABUKUT' },
                { id: 38992, name: 'NATHINYONOIT' },
              ],
            },
          ],
        },
        {
          id: 1313,
          name: 'MORUITA',
          parishes: [
            {
              id: 6168,
              name: 'KARINGA',
              villages: [
                { id: 38909, name: 'KARINGA' },
                { id: 38910, name: 'KOPEDUR' },
                { id: 67504, name: 'NAPELES' },
                { id: 67651, name: 'NAWOYAPURU' },
                { id: 38911, name: 'PELPEL' },
                { id: 38912, name: 'SUKUDIK' },
              ],
            },
            {
              id: 6169,
              name: 'KOMORET',
              villages: [
                { id: 64261, name: 'KOMORET' },
                { id: 64263, name: 'KOMORUNYANG' },
                { id: 65520, name: 'LORUKUT' },
                { id: 38913, name: 'MUNYOKERE' },
                { id: 38914, name: 'NACHUKUT' },
                { id: 67099, name: 'NAKOLIKITUK' },
                { id: 67105, name: 'NAKOO' },
                { id: 38915, name: 'NAPUDES' },
              ],
            },
            {
              id: 6167,
              name: 'MORUITA',
              villages: [
                { id: 57334, name: 'ACHERER EAST' },
                { id: 38908, name: 'CHOLOL' },
                { id: 63158, name: 'KATUKUMWOK' },
                { id: 66393, name: 'MORUITA' },
                { id: 67007, name: 'NAKAMURIAE' },
                { id: 67446, name: 'NANGOLEMOR' },
                { id: 70947, name: 'UTUT' },
              ],
            },
          ],
        },
        {
          id: 1314,
          name: 'NAKAPIRIPIRIT TOWN COUNCIL',
          parishes: [
            {
              id: 6170,
              name: 'KATANGA/TOWNSHIP WARD',
              villages: [
                { id: 38916, name: 'KATANGA/TOWNSHIP' },
                { id: 38917, name: 'NANGOROMIT' },
              ],
            },
            {
              id: 6171,
              name: 'LOBULIO/LOMUU WARD',
              villages: [
                { id: 38918, name: 'LOBULIO' },
                { id: 38919, name: 'LOMUU' },
              ],
            },
            {
              id: 6172,
              name: 'LOBUNIET/LOKONA WARD',
              villages: [
                { id: 38920, name: 'LOBUNEIT' },
                { id: 38921, name: 'LOKOONA' },
              ],
            },
          ],
        },
        {
          id: 1315,
          name: 'NAMALU',
          parishes: [
            {
              id: 6173,
              name: 'KOKUWUAM',
              villages: [
                { id: 38922, name: 'ANGOLETUROT' },
                { id: 38924, name: 'KOCHOLIKOKOI' },
                { id: 38925, name: 'LOCHOWA-A-NGIKALEI' },
                { id: 38926, name: 'LOKOMAIT' },
                { id: 38927, name: 'NABURI-A-ESIGIRIA' },
                { id: 38928, name: 'NAKAYOT' },
                { id: 38929, name: 'NAKORISAT' },
                { id: 38930, name: 'NAKWANGA EAST' },
                { id: 67134, name: 'NAKWANGA WEST' },
                { id: 38931, name: 'NAMALU TRADING CENTRE NORTH' },
                { id: 38923, name: 'NAMALU TRADING CENTRE SOUTH' },
                { id: 67330, name: 'NAMONI' },
                { id: 38932, name: 'PRODUCTION' },
                { id: 70820, name: 'TRADING CENTRE EAST A' },
                { id: 70821, name: 'TRADING CENTRE EAST B' },
              ],
            },
            {
              id: 6174,
              name: 'LOKATAPAN',
              villages: [
                { id: 62302, name: 'KALAPATA' },
                { id: 38933, name: 'KOMOJOJ' },
                { id: 38935, name: 'LOBULEPEDED' },
                { id: 38936, name: 'LOKADONGAN' },
                { id: 38938, name: 'LOKIYENGUNET EAST' },
                { id: 38937, name: 'LOKIYENGUNET WEST' },
                { id: 38939, name: 'LOMORUNYANGAE' },
                { id: 38934, name: 'LOOBORIO' },
                { id: 65479, name: 'LOPAGATHI' },
                { id: 38940, name: 'LOWATACHIN' },
                { id: 38944, name: 'MWANAKOLONG' },
                { id: 38941, name: 'NAKILORO' },
                { id: 38942, name: 'NAKUYON' },
                { id: 38945, name: 'NAMALU TRADING CENTRE WEST' },
                { id: 38943, name: 'NAMINIT' },
              ],
            },
            {
              id: 6175,
              name: 'NAMATATA',
              villages: [
                { id: 38949, name: 'ALEMUTABA' },
                { id: 38946, name: 'APEDED' },
                { id: 58552, name: 'ARUMA COLUI' },
                { id: 38947, name: 'KAAWUO LOBU' },
                { id: 38948, name: 'LOLELI-A-ARENGAN' },
                { id: 65532, name: 'LOTHEUTHEU' },
                { id: 38950, name: 'NAPAYAN' },
                { id: 38951, name: 'NASINYONO' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
