import { District } from '../types';

export default <District>{
  id: 78,
  name: 'PADER',
  counties: [
    {
      id: 192,
      name: 'ARUU COUNTY',
      sub_counties: [
        {
          id: 1183,
          name: 'AWERE',
          parishes: [
            {
              id: 9160,
              name: 'AGWENG',
              villages: [
                { id: 57609, name: 'AGWENG CENTRAL' },
                { id: 57610, name: 'AGWENG NORTH' },
                { id: 57611, name: 'AGWENG WEST' },
                { id: 68232, name: 'NYANYA' },
                { id: 68774, name: 'OLAMKARA' },
              ],
            },
            {
              id: 5496,
              name: 'ANGOLE',
              villages: [
                { id: 34819, name: 'ATEDE WIGWENG' },
                { id: 34813, name: 'LATEK EAST' },
                { id: 34814, name: 'LATEK WEST' },
                { id: 34815, name: 'LATIRA  EAST' },
                { id: 34820, name: 'LATIRA WEST' },
                { id: 34816, name: 'OBIC EAST' },
                { id: 34821, name: 'OBIC WEST' },
                { id: 34818, name: 'PAIKAT AGENGO' },
                { id: 34817, name: 'PAIKAT AKIDI' },
              ],
            },
            {
              id: 9226,
              name: 'ATEDE',
              villages: [
                { id: 58073, name: 'ALUNY' },
                { id: 58280, name: 'ANGOLE LAROO' },
                { id: 58610, name: 'ATEDE CENTRAL' },
                { id: 58612, name: 'ATEDE EAST' },
                { id: 58614, name: 'ATEDE WEST' },
                { id: 65027, name: 'LAMINA PUR' },
                { id: 65705, name: 'LUTINI CENTRAL' },
                { id: 65706, name: 'LUTINI EAST' },
                { id: 65707, name: 'LUTINI WEST' },
              ],
            },
            {
              id: 5495,
              name: 'BOLO',
              villages: [
                { id: 34803, name: 'JUK LEBI CENTRAL' },
                { id: 34809, name: 'JUK LEBI WEST' },
                { id: 34802, name: 'LAMACH' },
                { id: 34804, name: 'LAMACH CENTRAL' },
                { id: 34805, name: 'LAMACH NORTH' },
                { id: 34806, name: 'LAMACH SOUTH' },
                { id: 34810, name: 'LAMACH WEST' },
                { id: 34807, name: 'LAMING' },
                { id: 34808, name: 'LANGOLE' },
                { id: 34812, name: 'LANGOLE B' },
                { id: 34811, name: 'LAPETTA CENTRAL' },
              ],
            },
            {
              id: 9559,
              name: 'KAL',
              villages: [
                { id: 58838, name: 'AYOM' },
                { id: 58839, name: 'AYOM CENTRAL' },
                { id: 58840, name: 'AYOM WEST' },
                { id: 61418, name: 'GOT OLAL' },
                { id: 65101, name: 'LAPETA EAST' },
                { id: 65102, name: 'LAPETA WEST' },
              ],
            },
          ],
        },
        {
          id: 2056,
          name: 'LUNYIRI',
          parishes: [
            {
              id: 9783,
              name: 'KOC',
              villages: [
                { id: 57813, name: 'AKOL-TOO' },
                { id: 60838, name: 'CANBENO' },
                { id: 60839, name: 'CANBENO B' },
                { id: 61475, name: 'GWENG LIK' },
                { id: 65009, name: 'LALURUKU' },
                { id: 65035, name: 'LAMINBACA' },
                { id: 65636, name: 'LUKOR' },
                { id: 65645, name: 'LUKWOR OJUU' },
                { id: 69620, name: 'PARWECH LUKEE' },
                { id: 69621, name: 'PARWECH LUKEE EAST' },
                { id: 71166, name: 'WIRAA' },
              ],
            },
            {
              id: 9855,
              name: 'LAGILE',
              villages: [
                { id: 59153, name: 'BOLO DAGO' },
                { id: 59154, name: 'BOLO DAM' },
                { id: 59155, name: 'BOLO DAM WEST' },
                { id: 59158, name: 'BOLO WIGWENG' },
                { id: 68364, name: 'OBOLOKOME' },
                { id: 68847, name: 'OLOKO TUM' },
                { id: 71138, name: 'WII KWEYO' },
              ],
            },
            {
              id: 10200,
              name: 'OPOK ROM',
              villages: [
                { id: 59156, name: 'BOLO OPETTE' },
                { id: 59157, name: 'BOLO OPETTE WEST' },
                { id: 64928, name: 'LADYANGOKUN' },
                { id: 65002, name: 'LALIYA LAROO' },
                { id: 65003, name: 'LALIYA LAROO WEST' },
                { id: 65672, name: 'LUNYIRI EAST' },
                { id: 65673, name: 'LUNYIRI WEST' },
              ],
            },
            {
              id: 10254,
              name: 'RACKOKO',
              villages: [
                { id: 58670, name: 'ATUP' },
                { id: 61474, name: 'GWENG ICWALA' },
                { id: 65030, name: 'LAMINACWER' },
                { id: 65046, name: 'LAMINOKWERA' },
                { id: 69775, name: 'RACKOKO A' },
                { id: 69776, name: 'RACKOKO B' },
                { id: 70753, name: 'TIKTIK' },
              ],
            },
          ],
        },
        {
          id: 1187,
          name: 'OGOM',
          parishes: [
            {
              id: 5512,
              name: 'GULNAM',
              villages: [
                { id: 34927, name: 'ACANO CENTRAL' },
                { id: 34923, name: 'ACANO EAST' },
                { id: 34924, name: 'ACANO WEST' },
                { id: 34926, name: 'LAPENY' },
                { id: 65097, name: 'LAPENY WEST' },
                { id: 34928, name: 'LUZIRA' },
                { id: 34925, name: 'LUZIRA NORTH' },
                { id: 34929, name: 'VIETNAM' },
              ],
            },
            {
              id: 5514,
              name: 'KITENY',
              villages: [
                { id: 34937, name: 'KITENY CENTRAL' },
                { id: 34938, name: 'KITENY WEST' },
                { id: 65091, name: 'LAODO' },
                { id: 34941, name: 'OTUMPILI CENTRAL' },
                { id: 34939, name: 'OTUMPILI NORTH' },
                { id: 34940, name: 'OTUMPILI SOUTH' },
                { id: 70952, name: 'VIETAM EAST' },
              ],
            },
            {
              id: 5513,
              name: 'OGOM',
              villages: [
                { id: 34930, name: 'ACEN NGOLI' },
                { id: 34934, name: 'ACUT OYIKA' },
                { id: 58180, name: 'AMOR NUCU' },
                { id: 63808, name: 'KIRI' },
                { id: 68544, name: 'OGENG CENTRAL' },
                { id: 34932, name: 'OGENG NORTH' },
                { id: 68545, name: 'OGENG SOUTH' },
                { id: 68566, name: 'OGOM TELELA' },
                { id: 69400, name: 'OYEYENG' },
                { id: 34935, name: 'TE - LELA EAST' },
                { id: 70630, name: 'TE-KITUBA' },
                { id: 34936, name: 'TE-LELA WEST' },
                { id: 34933, name: 'TELELA CENTRAL' },
                { id: 34931, name: 'YITODUNY WEST' },
              ],
            },
            {
              id: 5510,
              name: 'OTONG',
              villages: [
                { id: 34912, name: 'GABADIN' },
                { id: 34913, name: 'LACINGA' },
                { id: 34916, name: 'LACINGA CENTRAL' },
                { id: 34914, name: 'LACINGA NORTH' },
                { id: 34915, name: 'LACINGA SOUTH' },
                { id: 34911, name: 'OLUNGOLET' },
                { id: 34917, name: 'WI RAA EAST' },
                { id: 71164, name: 'WIRA CENTRAL' },
                { id: 34918, name: 'WIRAA WEST' },
              ],
            },
            {
              id: 5511,
              name: 'OWELLE',
              villages: [
                { id: 57891, name: 'AKWARA' },
                { id: 34919, name: 'AMATGIRA' },
                { id: 34921, name: 'ATOOCON' },
                { id: 61061, name: 'COOROM WEST' },
                { id: 61432, name: 'GUDA' },
                { id: 34922, name: 'OWELE' },
                { id: 69364, name: 'OWELLE CENTRAL' },
                { id: 69457, name: 'PADER OKET' },
                { id: 69517, name: 'PALABIT' },
                { id: 34920, name: 'YITODUNY EAST' },
              ],
            },
          ],
        },
        {
          id: 1184,
          name: 'PADER',
          parishes: [
            {
              id: 5497,
              name: 'KILAK CORNER',
              villages: [
                { id: 34822, name: 'AGORA' },
                { id: 34823, name: 'BIWANG' },
                { id: 34824, name: 'KILAK CENTRAL A' },
                { id: 34828, name: 'KILAK CENTRAL B' },
                { id: 34825, name: 'LALWAL EAST' },
                { id: 34826, name: 'OBOT AJALI' },
                { id: 34827, name: 'ORA-LUKA' },
              ],
            },
            {
              id: 5498,
              name: 'OGWIL',
              villages: [
                { id: 34829, name: 'LAKUTOO' },
                { id: 34830, name: 'LALWAL WEST' },
                { id: 34832, name: 'OGWIL CENTRAL' },
                { id: 34834, name: 'OGWIL EAST' },
                { id: 34831, name: 'OGWIL WEST' },
                { id: 34833, name: 'TETIDO' },
                { id: 34835, name: 'WINYA' },
              ],
            },
            {
              id: 5499,
              name: 'ONGANY',
              villages: [
                { id: 34837, name: 'AGUNYA' },
                { id: 34839, name: 'KALANGORE NORTH' },
                { id: 34836, name: 'KALANGORE SOUTH' },
                { id: 34840, name: 'LABER DOG' },
                { id: 34841, name: 'NAMIREMBE' },
                { id: 34838, name: 'NANGULU' },
                { id: 34842, name: 'ONGANY SOCIETY' },
                { id: 34843, name: 'PE-NGABE LAMIN OKIGA' },
                { id: 34844, name: 'PE-NGABE SOCIETY' },
                { id: 34845, name: 'TANGI' },
              ],
            },
            {
              id: 5500,
              name: 'TYER',
              villages: [
                { id: 34846, name: 'AGWENG EAST' },
                { id: 34847, name: 'AGWENG WEST' },
                { id: 34848, name: 'AKEMO KOCH' },
                { id: 34849, name: 'ORA-ABIM' },
                { id: 34850, name: 'TYER' },
                { id: 34851, name: 'WANGCOL' },
              ],
            },
          ],
        },
        {
          id: 1186,
          name: 'PADER TOWN COUNCIL',
          parishes: [
            {
              id: 5508,
              name: 'ACORO WARD',
              villages: [
                { id: 34890, name: 'ACORO' },
                { id: 34891, name: 'KITENYI EAST' },
                { id: 34892, name: 'LUPUA NORTH' },
                { id: 34893, name: 'LUPUA SOUTH' },
                { id: 34900, name: 'OGENG SOUTH' },
                { id: 34894, name: 'OLWOR CENTRAL' },
                { id: 34895, name: 'OLWOR NORTH' },
                { id: 34896, name: 'OLWOR SOUTH' },
                { id: 34897, name: 'OPONG BENGE' },
                { id: 34898, name: 'PAGWARI EAST' },
                { id: 34899, name: 'PAGWARI WEST' },
                { id: 34901, name: 'TE-KITUBA' },
              ],
            },
            {
              id: 5507,
              name: 'LAGWAI WARD',
              villages: [
                { id: 34884, name: 'DOGNAM EAST' },
                { id: 34888, name: 'DOGNAM WEST' },
                { id: 34885, name: 'LAGWAI CENTRAL A' },
                { id: 34886, name: 'LAGWAI CENTRAL B' },
                { id: 34887, name: 'LAGWAI EAST' },
                { id: 34881, name: 'LOTYEK' },
                { id: 34889, name: 'OLOK ILEE' },
                { id: 34882, name: 'TE-JINGI' },
                { id: 34883, name: 'TE-ORYANG' },
              ],
            },
            {
              id: 5509,
              name: 'LUNA WARD',
              villages: [
                { id: 34903, name: 'AMOR' },
                { id: 34904, name: 'BARAJWA' },
                { id: 34905, name: 'GOT OLAL' },
                { id: 34902, name: 'KALALO WEST' },
                { id: 34906, name: 'LUBELE NORTH' },
                { id: 34907, name: 'LUBELE SOUTH' },
                { id: 34908, name: 'LWALA' },
                { id: 34909, name: 'OGWALENG VALLEY' },
                { id: 34910, name: 'OYUTU' },
              ],
            },
          ],
        },
        {
          id: 1182,
          name: 'PUKOR',
          parishes: [
            {
              id: 5494,
              name: 'KAL ANGORE',
              villages: [
                { id: 57890, name: 'AKWARA' },
                { id: 58058, name: 'ALUKA CENTRAL' },
                { id: 34798, name: 'ALUKA EAST' },
                { id: 34799, name: 'ALUKA WEST' },
                { id: 58741, name: 'AWENOLWIR' },
                { id: 61060, name: 'COOROM CENTRAL' },
                { id: 34800, name: 'COOROM EAST' },
                { id: 34801, name: 'COOROM WEST' },
                { id: 62651, name: 'KAPEL' },
              ],
            },
            {
              id: 5493,
              name: 'KINENI',
              villages: [
                { id: 58227, name: 'AMYEL' },
                { id: 34792, name: 'BAR ODYEK' },
                { id: 58980, name: 'BARODYEK EAST' },
                { id: 59054, name: 'BIDIN' },
                { id: 34791, name: 'BUROPUK' },
                { id: 34793, name: 'DAGO DWONG' },
                { id: 61081, name: 'DAGODWONG WEST' },
                { id: 34790, name: 'KOMPETENE' },
                { id: 34796, name: 'LABAKA' },
                { id: 34797, name: 'LAPINA BURU PUK' },
                { id: 68331, name: 'OBANY' },
                { id: 34795, name: 'OWILTIKO' },
                { id: 69472, name: 'PAGOR' },
                { id: 34794, name: 'WANGCOL' },
              ],
            },
            {
              id: 5492,
              name: 'OLAM',
              villages: [
                { id: 34785, name: 'ARINGO DYANG' },
                { id: 34786, name: 'KEYO ROM' },
                { id: 34787, name: 'LAPINA BAR DYANG' },
                { id: 34788, name: 'LAPINA TEBUNG' },
                { id: 65731, name: 'LWA-PEBALO' },
                { id: 68769, name: 'OLAM' },
                { id: 34789, name: 'OLAM CENTRAL' },
              ],
            },
            {
              id: 5491,
              name: 'PUKOR',
              villages: [
                { id: 34778, name: 'AGUM WII GWENG' },
                { id: 34779, name: 'GANG BAR' },
                { id: 61756, name: 'JERUSALEM' },
                { id: 34781, name: 'LOYO CAK' },
                { id: 34780, name: 'MISCIRI' },
                { id: 34782, name: 'NYONG' },
                { id: 68292, name: 'NYONG SOUTH' },
                { id: 69484, name: 'PAITINO' },
                { id: 34783, name: 'TE-ADWOKI' },
                { id: 34784, name: 'TOO KODO' },
              ],
            },
          ],
        },
        {
          id: 1185,
          name: 'PURANGA',
          parishes: [
            {
              id: 5502,
              name: 'AGWEL',
              villages: [
                { id: 34856, name: 'ACEK KENE' },
                { id: 34857, name: 'BAR OBIYA' },
                { id: 58975, name: 'BAROBIA B' },
                { id: 34858, name: 'KULU OCWICI' },
                { id: 34859, name: 'LACEKOMYELA' },
                { id: 70625, name: 'TE-GWENG' },
              ],
            },
            {
              id: 5504,
              name: 'APWOR',
              villages: [
                { id: 34866, name: 'ANYANG' },
                { id: 65750, name: 'LWALA' },
                { id: 34867, name: 'OMUNA' },
                { id: 34868, name: 'ONYEDE' },
                { id: 69085, name: 'ONYEDE  B' },
                { id: 69086, name: 'ONYEDE WEST' },
              ],
            },
            {
              id: 5505,
              name: 'LAMINAJIKO',
              villages: [
                { id: 34869, name: 'ABALO KODI' },
                { id: 34870, name: 'APWOR KAMPALA' },
                { id: 34871, name: 'BAR ONGERA' },
                { id: 64902, name: 'LACANDAK KENEKENE' },
                { id: 65032, name: 'LAMINAJIKO' },
                { id: 68968, name: 'OMOKNGOM B' },
                { id: 34873, name: 'OMOKO KI TUNGE' },
                { id: 34872, name: 'OMOKONGOM' },
                { id: 34874, name: 'ORA CING YACINTO' },
                { id: 69161, name: 'ORACINGYACINTO WEST' },
                { id: 34875, name: 'ORAKUL' },
              ],
            },
            {
              id: 5506,
              name: 'LAMINOCWIDA',
              villages: [
                { id: 34877, name: 'ACWINYO' },
                { id: 57393, name: 'ACWINYO B' },
                { id: 34876, name: 'ALEPO A' },
                { id: 34878, name: 'ALEPO B' },
                { id: 58197, name: 'AMUGO B' },
                { id: 34879, name: 'AMUGU' },
                { id: 64386, name: 'KULUOBIYA' },
                { id: 34880, name: 'LAMINO CWIDA' },
                { id: 66359, name: 'MONYETO' },
                { id: 71133, name: 'WIGWENG' },
              ],
            },
            {
              id: 5501,
              name: 'ODUM',
              villages: [
                { id: 34852, name: 'ABAK TWOMERE' },
                { id: 34853, name: 'ABAKTWOMERE B' },
                { id: 58926, name: 'BAR-AGABA' },
                { id: 34855, name: 'ODUM  B' },
                { id: 34854, name: 'ODUM A' },
                { id: 69757, name: 'PUNODYEGI' },
                { id: 70639, name: 'TE-OBWOLO' },
              ],
            },
            {
              id: 5503,
              name: 'ORET',
              villages: [
                { id: 34861, name: 'ALOYO CAK' },
                { id: 34860, name: 'AYOM CWINY' },
                { id: 34862, name: 'CAN BER KI BEDO MOT' },
                { id: 60840, name: 'CANBER IBEDOMOT B' },
                { id: 64248, name: 'KOMDEKLIT' },
                { id: 34863, name: 'LOBOROM' },
                { id: 34864, name: 'PURBER' },
                { id: 34865, name: 'WII-OMAL' },
              ],
            },
          ],
        },
        {
          id: 1181,
          name: 'TE-NAM',
          parishes: [
            {
              id: 5488,
              name: 'ARINGA',
              villages: [
                { id: 34748, name: 'AJANYI' },
                { id: 34749, name: 'ANYADYANG' },
                { id: 34751, name: 'ATUP' },
                { id: 34753, name: 'JUBA' },
                { id: 34750, name: 'LAWIYE OROMO' },
                { id: 34752, name: 'OBIYO MOO' },
                { id: 34754, name: 'OMWONY LEE' },
                { id: 34756, name: 'OPIRO' },
                { id: 34755, name: 'TE-TWORO' },
                { id: 34757, name: 'WANGLOBO' },
              ],
            },
            {
              id: 5487,
              name: 'BARWECH',
              villages: [
                { id: 34741, name: 'ACUT OMER' },
                { id: 34738, name: 'ADONG KENA CENTRAL' },
                { id: 34739, name: 'ADONG KENA WEST' },
                { id: 34743, name: 'ADONGKENA EAST' },
                { id: 34740, name: 'AGRIKACA' },
                { id: 34742, name: 'AWETE' },
                { id: 34744, name: 'LAMING OJUNGUUME' },
                { id: 34745, name: 'LUDEL' },
                { id: 34746, name: 'LWALA' },
                { id: 34747, name: 'PURANGA T/C  A' },
              ],
            },
            {
              id: 5489,
              name: 'LAKOGA',
              villages: [
                { id: 34766, name: 'ENTEBBE' },
                { id: 34758, name: 'GUNYA' },
                { id: 34759, name: 'LAKOGA CENTRAL' },
                { id: 34760, name: 'LAMINAWOTO' },
                { id: 34762, name: 'LUBAT' },
                { id: 34761, name: 'OGULURU' },
                { id: 34764, name: 'OKOCOKABILA' },
                { id: 34763, name: 'TWEE' },
                { id: 34767, name: 'WIGWENG' },
                { id: 34768, name: 'WINY KI OTWOR' },
                { id: 34765, name: 'WINY KI OTWOR CENTRAL' },
              ],
            },
            {
              id: 5490,
              name: 'TEE-OKUTU',
              villages: [
                { id: 34771, name: 'BUNGALUNG A' },
                { id: 34769, name: 'BUNGALUNG B' },
                { id: 34772, name: 'DOG LAKOJO' },
                { id: 34770, name: 'DOG-LAMEJE' },
                { id: 61358, name: 'GENNERY' },
                { id: 34773, name: 'IMAKI OYEKE  A' },
                { id: 34774, name: 'IMAKI OYERE B' },
                { id: 65020, name: 'LAMEJE' },
                { id: 34775, name: 'PURANGA T/C  B' },
                { id: 34776, name: 'TE - OKUTU' },
                { id: 34777, name: 'WICERE' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 193,
      name: 'ARUU NORTH COUNTY',
      sub_counties: [
        {
          id: 1188,
          name: 'ACHOLI-BUR',
          parishes: [
            {
              id: 5515,
              name: 'GEM-CENTRAL',
              villages: [
                { id: 34942, name: 'CENTRAL' },
                { id: 34943, name: 'JUBA' },
                { id: 34947, name: 'LAJWATEK' },
                { id: 34950, name: 'LAPAINAT' },
                { id: 34944, name: 'LARUMU A' },
                { id: 34945, name: 'LARUMU B' },
                { id: 34946, name: 'OMUNY ACUMU' },
                { id: 34948, name: 'PENGENE' },
                { id: 34949, name: 'TEBITO' },
              ],
            },
            {
              id: 5516,
              name: 'GEM-ONYOT',
              villages: [
                { id: 34951, name: 'ARIT LATWONG' },
                { id: 34958, name: 'LABWOR OMOR' },
                { id: 34952, name: 'LADUU' },
                { id: 34959, name: 'LEEBIT' },
                { id: 34953, name: 'LUBYEE' },
                { id: 34960, name: 'LUKOKO' },
                { id: 34954, name: 'OKINGA CENTRAL' },
                { id: 34955, name: 'OTURE OKANG' },
                { id: 34956, name: 'PAGAK' },
                { id: 34957, name: 'PAWACH KANA JOBI' },
                { id: 34961, name: 'WII RAA' },
              ],
            },
            {
              id: 5517,
              name: 'OGAGO',
              villages: [
                { id: 34964, name: 'LAGENG' },
                { id: 34962, name: 'LAWODA PWOYO' },
                { id: 34963, name: 'LUGEDE' },
                { id: 34967, name: 'LUKWOR NORTH' },
                { id: 34968, name: 'LUKWOR PADAT' },
                { id: 34965, name: 'LUNY BUT' },
                { id: 34969, name: 'MUNUTAM' },
                { id: 34966, name: 'OJALO' },
              ],
            },
            {
              id: 5518,
              name: 'WII GWENG',
              villages: [
                { id: 34970, name: 'ACUT OMER NORTH' },
                { id: 34971, name: 'ACUT OMER SOUTH' },
                { id: 34972, name: 'ADOO' },
                { id: 34974, name: 'ADULA EAST' },
                { id: 34973, name: 'ADULA WEST' },
                { id: 34976, name: 'LABWOR OYENG EAST' },
                { id: 34975, name: 'LABWOR OYENG WEST' },
                { id: 34977, name: 'OTWAK' },
              ],
            },
          ],
        },
        {
          id: 1936,
          name: 'AJAN',
          parishes: [
            {
              id: 9484,
              name: 'GOMA',
              villages: [
                { id: 57899, name: 'AKWIR' },
                { id: 58136, name: 'AMILOBO CENTRAL' },
                { id: 58137, name: 'AMILOBO ONIN' },
                { id: 59084, name: 'BILAKWALA A' },
                { id: 59085, name: 'BILAKWALA B' },
                { id: 64437, name: 'KWALA' },
                { id: 65106, name: 'LAPONO' },
                { id: 68912, name: 'OMATO-PIGE' },
                { id: 69072, name: 'ONIN' },
                { id: 69218, name: 'ORUDI' },
                { id: 69536, name: 'PALITO' },
              ],
            },
            {
              id: 10230,
              name: 'PAIBWOR',
              villages: [
                { id: 57294, name: 'ACAMOLING' },
                { id: 61097, name: 'DEGE OTUK' },
                { id: 63741, name: 'KINENE' },
                { id: 65092, name: 'LAORA-KUKU' },
                { id: 65118, name: 'LARWODO' },
                { id: 65256, name: 'LOBUT' },
                { id: 68632, name: 'OJIBU' },
                { id: 68652, name: 'OJUTA' },
                { id: 68955, name: 'OMIDO' },
                { id: 70869, name: 'TUNG TWON' },
                { id: 71031, name: 'WANG-LALA' },
              ],
            },
            {
              id: 10233,
              name: 'PAKEYO',
              villages: [
                { id: 58675, name: 'ATWATO' },
                { id: 58875, name: 'BAJERE' },
                { id: 64120, name: 'KITWOL' },
                { id: 64970, name: 'LAKABAM' },
                { id: 65080, name: 'LANGWIDI' },
                { id: 65099, name: 'LAPETA' },
                { id: 65111, name: 'LAREGO A' },
                { id: 65112, name: 'LAREGO B' },
                { id: 65614, name: 'LUKALOYE A' },
                { id: 65615, name: 'LUKALOYE B' },
                { id: 70770, name: 'TOBII' },
                { id: 71083, name: 'WATLAC' },
              ],
            },
            {
              id: 10349,
              name: 'WIPOLO',
              villages: [
                { id: 57638, name: 'AJAN' },
                { id: 58983, name: 'BAROLAM' },
                { id: 59102, name: 'BIRA' },
                { id: 60164, name: 'BUNGA' },
                { id: 63537, name: 'KIGWEE' },
                { id: 63991, name: 'KITAMA' },
                { id: 64873, name: 'LABINA' },
                { id: 64986, name: 'LAKWATOMER' },
                { id: 64999, name: 'LALI' },
                { id: 65566, name: 'LUBANYA' },
                { id: 70711, name: 'TENGO' },
                { id: 71146, name: 'WIKO' },
                { id: 71160, name: 'WIPOLO DIT BER' },
              ],
            },
          ],
        },
        {
          id: 1195,
          name: 'ANGAGURA',
          parishes: [
            {
              id: 5541,
              name: 'BUR-LOBO',
              villages: [
                { id: 35202, name: 'ARINGO YON' },
                { id: 35203, name: 'BIRA' },
                { id: 35204, name: 'BURLOBO' },
                { id: 35205, name: 'DENG A' },
                { id: 35206, name: 'DENG B' },
                { id: 35207, name: 'LABWOTO' },
                { id: 35208, name: 'LACEDE' },
                { id: 35209, name: 'LEE OYIKA' },
                { id: 35210, name: 'LIBII' },
                { id: 35211, name: 'PABIT' },
              ],
            },
            {
              id: 5542,
              name: 'KALAWINYA',
              villages: [
                { id: 35214, name: 'AGWERA' },
                { id: 35212, name: 'ANGAGURA A' },
                { id: 35213, name: 'ANGAGURA B' },
                { id: 35215, name: 'CENTRAL WARD' },
                { id: 35216, name: 'GO-GWIRI' },
                { id: 35217, name: 'JUPA' },
                { id: 35218, name: 'KIBEGA' },
                { id: 35219, name: 'ODOKOMIT' },
              ],
            },
            {
              id: 5539,
              name: 'PUCOTA',
              villages: [
                { id: 35184, name: 'ABILNINO' },
                { id: 35185, name: 'AKUYAM' },
                { id: 35186, name: 'ARINGA' },
                { id: 35189, name: 'ATURABYE' },
                { id: 35187, name: 'AYWERI' },
                { id: 35190, name: 'LABWOR-OMOR' },
                { id: 35188, name: 'LAPAYA' },
                { id: 35191, name: 'OGOM' },
              ],
            },
            {
              id: 5540,
              name: 'PUNGOLE',
              villages: [
                { id: 35192, name: 'AKELI KONGO' },
                { id: 35193, name: 'ATIAK' },
                { id: 35201, name: 'LACOL' },
                { id: 35194, name: 'LALEM' },
                { id: 35195, name: 'LARABA' },
                { id: 35196, name: 'LEE OGWEYO' },
                { id: 35197, name: 'LUBALA' },
                { id: 35198, name: 'OBITTO' },
                { id: 35199, name: 'OBONO' },
                { id: 35200, name: 'ONIN' },
              ],
            },
          ],
        },
        {
          id: 1189,
          name: 'ATANGA',
          parishes: [
            {
              id: 5520,
              name: 'LAWIYE ADUL',
              villages: [
                { id: 34992, name: 'ALOKOLUM' },
                { id: 34993, name: 'GOT ANYARA' },
                { id: 34994, name: 'LAMWO' },
                { id: 34995, name: 'LANGORONY' },
                { id: 34991, name: 'LAPOYA-OKWE' },
                { id: 34996, name: 'OBONI' },
                { id: 34997, name: 'TEE-LUL' },
                { id: 34998, name: 'WANG-OLWENY' },
                { id: 34999, name: 'WII-LONGOYI' },
              ],
            },
            {
              id: 5519,
              name: 'NGOTO',
              villages: [
                { id: 34978, name: 'ACAMO-GOMA' },
                { id: 34979, name: 'ATAL' },
                { id: 34989, name: 'BAR-AYOM' },
                { id: 34981, name: 'BAR-ORIT' },
                { id: 34980, name: 'BARDEGE' },
                { id: 34990, name: 'LAKITI' },
                { id: 34982, name: 'LAORA-OGALI' },
                { id: 34983, name: 'LAPAK' },
                { id: 34984, name: 'LATUM' },
                { id: 34985, name: 'LAYAMO' },
                { id: 34987, name: 'PUNU-RII' },
                { id: 34986, name: 'PUNULYEC' },
                { id: 34988, name: 'WIAKADO' },
              ],
            },
            {
              id: 5521,
              name: 'OPATE',
              villages: [
                { id: 35000, name: 'ABYEBA' },
                { id: 35001, name: 'ALERO' },
                { id: 35006, name: 'GUCU-LUDUKU' },
                { id: 35007, name: 'JAPA' },
                { id: 35008, name: 'LACOR OBOO' },
                { id: 35009, name: 'LACOR-BOROBORO' },
                { id: 35010, name: 'LAPUL OCWIDA' },
                { id: 35002, name: 'LUKOME' },
                { id: 35011, name: 'NYELOMUNYA' },
                { id: 35014, name: 'ODANE' },
                { id: 35012, name: 'OLUK' },
                { id: 35003, name: 'OTAKA' },
                { id: 35005, name: 'OTINGA' },
                { id: 35004, name: 'OTUKENE' },
                { id: 35013, name: 'TING OBWOR' },
              ],
            },
          ],
        },
        {
          id: 1197,
          name: 'ATANGA TOWN COUNCIL',
          parishes: [
            {
              id: 5548,
              name: 'ABORA WARD',
              villages: [
                { id: 35253, name: 'BEYOJWARA' },
                { id: 35250, name: 'BUR NGUR' },
                { id: 65137, name: 'LAWALO' },
                { id: 35257, name: 'LAWIYADUL A' },
                { id: 35251, name: 'LUBIRI A' },
                { id: 35254, name: 'LUBIRI B' },
                { id: 66313, name: 'MISSION WARD' },
                { id: 35255, name: 'NAGWELA' },
                { id: 68861, name: 'OLUKE' },
                { id: 35256, name: 'ONYUTU TUNGE' },
                { id: 35252, name: 'WIGWENG' },
                { id: 35258, name: 'WIL-PII-NGORA' },
              ],
            },
            {
              id: 5550,
              name: 'GOJANI WARD',
              villages: [
                { id: 35269, name: 'BOROBORO' },
                { id: 35273, name: 'GOJANI' },
                { id: 35270, name: 'LALANGO' },
                { id: 35271, name: 'LANYADWERE' },
                { id: 35272, name: 'OLAM GUM' },
                { id: 69150, name: 'OPUNY MON' },
                { id: 35274, name: 'OTUDOWIYE' },
                { id: 35275, name: 'OYELOC' },
                { id: 35276, name: 'PANYAKAWA' },
                { id: 71028, name: 'WANG PARA' },
              ],
            },
            {
              id: 5547,
              name: 'KAL WARD',
              villages: [
                { id: 35241, name: 'ABOO A' },
                { id: 35243, name: 'ABOO B' },
                { id: 35244, name: 'CENTRAL A' },
                { id: 35245, name: 'CENTRAL B' },
                { id: 35240, name: 'LACAN ODAK' },
                { id: 35242, name: 'LAWIYADUL B' },
                { id: 35248, name: 'OGUTA' },
                { id: 35246, name: 'OGUTATEGOT' },
                { id: 35247, name: 'OLANGKARA' },
                { id: 35249, name: 'ONEGE' },
                { id: 69771, name: 'QUARTER' },
              ],
            },
            {
              id: 5549,
              name: 'LABONGO GURU WARD',
              villages: [
                { id: 35259, name: 'ABAKO-OR A' },
                { id: 35260, name: 'ABAKO-OR B' },
                { id: 35261, name: 'ARIYA' },
                { id: 35265, name: 'LABONGO-GURO' },
                { id: 35262, name: 'LADIKO' },
                { id: 35268, name: 'LAGAR' },
                { id: 35263, name: 'LAGAR WEST' },
                { id: 35264, name: 'OCER' },
                { id: 35266, name: 'RIBE TEKO A' },
                { id: 35267, name: 'RIBE TEKO B' },
              ],
            },
          ],
        },
        {
          id: 1959,
          name: 'BONGTIKO',
          parishes: [
            {
              id: 9232,
              name: 'ATO',
              villages: [
                { id: 61737, name: 'JAKA CENTRAL A' },
                { id: 61740, name: 'JAKA DEG ARONYA  A' },
                { id: 61741, name: 'JAKA DEG ARONYA  B' },
                { id: 65006, name: 'LALOKI CENTRAL' },
                { id: 65062, name: 'LAMMIN KENI' },
                { id: 65145, name: 'LAYIK' },
                { id: 67701, name: 'NEKNENO' },
                { id: 67746, name: 'NGOM BALE' },
                { id: 69055, name: 'ONGAT' },
                { id: 69168, name: 'ORAOTWILO NORTH' },
                { id: 69169, name: 'ORAOTWILO WEST' },
              ],
            },
            {
              id: 9489,
              name: 'GULALELA',
              villages: [
                { id: 58703, name: 'AWALMON EAST' },
                { id: 61137, name: 'DOBOL' },
                { id: 64893, name: 'LABWORDWONG' },
                { id: 64913, name: 'LACINGA' },
                { id: 65090, name: 'LANYWALWORO' },
                { id: 68758, name: 'OKWORO CENTRAL' },
                { id: 70671, name: 'TEE-OLAM' },
                { id: 71165, name: 'WIRAA' },
              ],
            },
            {
              id: 10155,
              name: 'OGOLE',
              villages: [
                { id: 58702, name: 'AWALMON CENTRAL' },
                { id: 58929, name: 'BAR-AYOM' },
                { id: 61438, name: 'GULALELA' },
                { id: 61736, name: 'JAKA  CENTRAL B' },
                { id: 65125, name: 'LATIN LING' },
                { id: 65183, name: 'LEPAMAC' },
                { id: 68759, name: 'OKWORO EAST' },
                { id: 68760, name: 'OKWORO WEST' },
              ],
            },
            {
              id: 10187,
              name: 'OMOGI',
              villages: [
                { id: 58484, name: 'ARIABA  CENTRAL A' },
                { id: 58485, name: 'ARIABA  CENTRAL B' },
                { id: 60822, name: 'BYECE' },
                { id: 61480, name: 'GWENO WANG' },
                { id: 68964, name: 'OMOGI  CENTRAL' },
                { id: 68965, name: 'OMOGI  EAST' },
                { id: 68966, name: 'OMOGI  WEST' },
                { id: 69141, name: 'OPOTAMATUGU' },
                { id: 70752, name: 'TIKILINGO' },
                { id: 71051, name: 'WANGKWEYO' },
              ],
            },
            {
              id: 10338,
              name: 'WANGLOBO',
              villages: [
                { id: 57152, name: 'ABENGA' },
                { id: 59170, name: 'BONGTIKO' },
                { id: 59171, name: 'BONGTIKO B' },
                { id: 61477, name: 'GWENG OBURA' },
                { id: 61738, name: 'JAKA CEYLON A' },
                { id: 61739, name: 'JAKA CEYLON B' },
                { id: 64861, name: 'LAAWIRE' },
                { id: 64880, name: 'LABONGO' },
                { id: 65005, name: 'LALOKE CENTRAL' },
                { id: 68764, name: 'OLAK-KIWIYA' },
              ],
            },
          ],
        },
        {
          id: 1193,
          name: 'LAGUTI',
          parishes: [
            {
              id: 9724,
              name: 'KILIM',
              villages: [
                { id: 58107, name: 'AMATLAC' },
                { id: 58414, name: 'APOBO' },
                { id: 64943, name: 'LAGOT OYWEC' },
                { id: 64971, name: 'LAKALABONG' },
                { id: 65007, name: 'LALUR' },
                { id: 68363, name: 'OBOLOKOME' },
                { id: 69096, name: 'ONYON' },
                { id: 69100, name: 'OPABO' },
              ],
            },
            {
              id: 9856,
              name: 'LAJENG',
              villages: [
                { id: 64267, name: 'KOMYOKE' },
                { id: 64962, name: 'LAJENG CENTRAL' },
                { id: 64969, name: 'LAJWATEK' },
                { id: 65021, name: 'LAMEL' },
                { id: 65085, name: 'LANYALWALA' },
                { id: 65088, name: 'LANYATINGA' },
                { id: 65130, name: 'LATURUTURU' },
                { id: 71045, name: 'WANGE-LACAR' },
              ],
            },
            {
              id: 5536,
              name: 'LAPYEM',
              villages: [
                { id: 35158, name: 'ARINGO YON' },
                { id: 35162, name: 'BUR GWENG' },
                { id: 35148, name: 'KOMYOKE' },
                { id: 35149, name: 'LADYANG' },
                { id: 35150, name: 'LAJENG CENTRAL' },
                { id: 35151, name: 'LAJWATEK' },
                { id: 35152, name: 'LALUR LAKEODING' },
                { id: 35153, name: 'LAMEL' },
                { id: 35160, name: 'LANYALWALA' },
                { id: 35147, name: 'LANYATINGA' },
                { id: 35159, name: 'LAPYEM CENTRAL' },
                { id: 35161, name: 'LATURUTURU' },
                { id: 35154, name: 'NAMASANGALI' },
                { id: 35155, name: 'NAMIREMBE' },
                { id: 35156, name: 'ONGAKO' },
                { id: 35157, name: 'WANGE-LACAR' },
              ],
            },
            {
              id: 10325,
              name: 'TUMALYEC',
              villages: [
                { id: 62327, name: 'KALILI' },
                { id: 62443, name: 'KAMPALA' },
                { id: 64905, name: 'LACARI' },
                { id: 64972, name: 'LAKALANGANYA' },
                { id: 64989, name: 'LAKWOR' },
                { id: 65074, name: 'LANGAO' },
                { id: 65351, name: 'LOKILA' },
                { id: 68543, name: 'OGENG' },
                { id: 70858, name: 'TUMA LYEC CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 1194,
          name: 'LAPUL',
          parishes: [
            {
              id: 9183,
              name: 'ALIM',
              villages: [
                { id: 58005, name: 'ALIM CENTRAL' },
                { id: 58006, name: 'ALIM WEST' },
                { id: 61774, name: 'JORO' },
                { id: 64988, name: 'LAKWER' },
                { id: 65087, name: 'LANYATIDO WEST' },
                { id: 68361, name: 'OBOLO' },
                { id: 68772, name: 'OLAM-PUR' },
                { id: 69421, name: 'OYWELO-MON' },
                { id: 69478, name: 'PAI-TINO' },
                { id: 69865, name: 'ROYA KI TWON' },
              ],
            },
            {
              id: 5537,
              name: 'KOYO',
              villages: [
                { id: 35163, name: 'ABUNGA' },
                { id: 35168, name: 'ABUNGA WEST' },
                { id: 35164, name: 'BAR ODILO' },
                { id: 35169, name: 'BAR ODILO EAST' },
                { id: 35165, name: 'BAR-AYOM' },
                { id: 35170, name: 'GULONGERA' },
                { id: 35166, name: 'LAGARA CENTRAL' },
                { id: 35167, name: 'LAGARA SOUTH' },
                { id: 35171, name: 'ORYANG' },
                { id: 35172, name: 'PUDA' },
                { id: 35173, name: 'PUDA WEST' },
              ],
            },
            {
              id: 9860,
              name: 'LALOGI',
              villages: [
                { id: 58003, name: 'ALILLI' },
                { id: 58841, name: 'AYOMKONYA' },
                { id: 61129, name: 'DINGWUM' },
                { id: 64881, name: 'LABORA' },
                { id: 65004, name: 'LALOGI' },
                { id: 65026, name: 'LAMIN OKECH' },
                { id: 65107, name: 'LAPUNO - MAKWAR' },
                { id: 65628, name: 'LUKOME' },
                { id: 68439, name: 'ODACH' },
                { id: 68650, name: 'OJURU' },
              ],
            },
            {
              id: 5538,
              name: 'LUKACI',
              villages: [
                { id: 35175, name: 'ARINGO-GWA' },
                { id: 35179, name: 'ARINGO-GWA SOUTH' },
                { id: 35176, name: 'DAM-MEKOR' },
                { id: 35174, name: 'DEM' },
                { id: 35177, name: 'LACOYI' },
                { id: 35182, name: 'LANYATIDO CENTRAL' },
                { id: 35178, name: 'LANYATIDO EAST' },
                { id: 35183, name: 'OGAN EAST' },
                { id: 35180, name: 'OGAN-GWOK-ROKO' },
                { id: 35181, name: 'OLAMPUR' },
              ],
            },
          ],
        },
        {
          id: 1196,
          name: 'LATANYA',
          parishes: [
            {
              id: 5544,
              name: 'AMOKO',
              villages: [
                { id: 35228, name: 'AMOKO' },
                { id: 58166, name: 'AMOKO OKWELE' },
                { id: 35225, name: 'LAMING ONYIKO' },
                { id: 35229, name: 'OLANG GANG' },
                { id: 35226, name: 'OLANGANG WEST' },
                { id: 35227, name: 'OLANGNONO' },
                { id: 35230, name: 'OMUNYU EAST' },
                { id: 69017, name: 'OMUNYU WEST' },
              ],
            },
            {
              id: 5545,
              name: 'GOLO',
              villages: [
                { id: 64914, name: 'LACINGA' },
                { id: 35234, name: 'LANYACILA' },
                { id: 65122, name: 'LATANYA CENTRAL' },
                { id: 35235, name: 'LATANYA EAST' },
                { id: 35232, name: 'LATANYA WEST' },
                { id: 35233, name: 'LELA AWOKI' },
                { id: 65684, name: 'LURWAMA' },
                { id: 35231, name: 'OLANGANG NORTH' },
                { id: 69056, name: 'ONGENYO' },
                { id: 71026, name: 'WANG KIKULA' },
                { id: 35236, name: 'WILIWILI' },
              ],
            },
            {
              id: 5546,
              name: 'KINO',
              villages: [
                { id: 61548, name: 'IBUC' },
                { id: 65574, name: 'LUBIRI' },
                { id: 35238, name: 'ORUTI' },
                { id: 69231, name: 'ORUTI CENTRAL' },
                { id: 69232, name: 'ORUTI WEST' },
                { id: 69481, name: 'PAIMINA' },
                { id: 35239, name: 'PARAKAKA' },
                { id: 35237, name: 'TOKE' },
              ],
            },
            {
              id: 5543,
              name: 'NGEKIDI',
              villages: [
                { id: 60169, name: 'BUNGA-ONGERA' },
                { id: 35220, name: 'DAGO IWAYO' },
                { id: 64265, name: 'KOMPETUM' },
                { id: 35221, name: 'LAJWEE' },
                { id: 35223, name: 'LAUMA' },
                { id: 65169, name: 'LELA OYUKU CENTRAL' },
                { id: 65742, name: 'LWALA' },
                { id: 35224, name: 'MWODKODI' },
                { id: 68770, name: 'OLAM ICEKE' },
                { id: 68771, name: 'OLAM ICEKE WEST' },
                { id: 35222, name: 'OYUKU' },
                { id: 71033, name: 'WANG-OLAM' },
              ],
            },
          ],
        },
        {
          id: 1191,
          name: 'PAIULA',
          parishes: [
            {
              id: 5530,
              name: 'LAMOGI',
              villages: [
                { id: 35076, name: 'ALIM' },
                { id: 35075, name: 'LAMOGI CENTRAL' },
                { id: 65066, name: 'LAMOGI WANGANYENA' },
                { id: 65067, name: 'LAMOGI WIACWI' },
                { id: 35077, name: 'LAPENY' },
                { id: 35078, name: 'OMINYI-KI-MAC' },
                { id: 35079, name: 'OMUNY JOBI' },
                { id: 71112, name: 'WI-LYEC' },
              ],
            },
            {
              id: 5531,
              name: 'OGAGO',
              villages: [
                { id: 35096, name: 'AJOBI' },
                { id: 35084, name: 'BAR OYWEC' },
                { id: 35080, name: 'BAR-GOMA' },
                { id: 35081, name: 'KALADIMA' },
                { id: 35082, name: 'KIBONG A' },
                { id: 35083, name: 'KIBONG B' },
                { id: 35085, name: 'LANYATONO A' },
                { id: 35086, name: 'LANYATONO B' },
                { id: 35092, name: 'LAPENYAGA EAST' },
                { id: 35094, name: 'LAPENYANGA WEST' },
                { id: 35087, name: 'LYEC-JURU' },
                { id: 35088, name: 'ODOKOMIT' },
                { id: 35089, name: 'OWELE EAST' },
                { id: 35095, name: 'OWELE WEST' },
                { id: 35093, name: 'WANG LELA' },
                { id: 35090, name: 'WANG-OGALI' },
                { id: 35091, name: 'WANG-YAGO' },
              ],
            },
            {
              id: 5528,
              name: 'PAIULA',
              villages: [
                { id: 35056, name: 'BUNGA' },
                { id: 35059, name: 'BUSIA' },
                { id: 35067, name: 'KEKO MIX' },
                { id: 35057, name: 'LACUR' },
                { id: 35058, name: 'LAKOKOLIL' },
                { id: 35060, name: 'LAKOKOLIL WEST' },
                { id: 35061, name: 'LWALA A' },
                { id: 35062, name: 'LWALA B' },
                { id: 35066, name: 'LWALA C' },
                { id: 35063, name: 'MEKOR' },
                { id: 66262, name: 'MILA' },
                { id: 35064, name: 'TOKODO' },
                { id: 70798, name: 'TOOKODO CENTRAL' },
                { id: 35065, name: 'WI-LYEC' },
              ],
            },
            {
              id: 5529,
              name: 'PALWO',
              villages: [
                { id: 35073, name: 'KANAKOK EAST' },
                { id: 35068, name: 'KANAKOK WEST' },
                { id: 35069, name: 'KOM-TOO' },
                { id: 35070, name: 'LACEK-TAR EAST' },
                { id: 65079, name: 'LANGULA' },
                { id: 35071, name: 'OGAN AYILA EAST' },
                { id: 35074, name: 'OJILE CENTRAL' },
                { id: 35072, name: 'OJILE EAST' },
              ],
            },
          ],
        },
        {
          id: 1192,
          name: 'PAJULE',
          parishes: [
            {
              id: 5535,
              name: 'AMOKO',
              villages: [
                { id: 35141, name: 'AMOKO LAGWAI EAST' },
                { id: 35142, name: 'AMOKO LAGWAI WEST' },
                { id: 35143, name: 'ANGAKO-TOKE' },
                { id: 59278, name: 'BUGA' },
                { id: 35145, name: 'LADYANG-TAR' },
                { id: 64927, name: 'LADYANGATA WEST' },
                { id: 35144, name: 'LAGWOK' },
                { id: 35140, name: 'LAJWINY' },
                { id: 68846, name: 'OLOKKIWINYO' },
                { id: 35146, name: 'OWETE' },
              ],
            },
            {
              id: 5532,
              name: 'ORYANG',
              villages: [
                { id: 35097, name: 'BIWANG' },
                { id: 35098, name: 'BUNGA-LELA WEST' },
                { id: 35109, name: 'BUNGALELA EAST' },
                { id: 35099, name: 'LAMII OGWET' },
                { id: 35107, name: 'LUPARA' },
                { id: 35100, name: 'OCIGA EAST' },
                { id: 35101, name: 'OCIGA WEST' },
                { id: 35108, name: 'ORYANG CENTRAL' },
                { id: 35102, name: 'ORYANG EAST' },
                { id: 35103, name: 'ORYANG WEST' },
                { id: 35104, name: 'PALENGA AYWEE' },
                { id: 35105, name: 'PONG-DWONGO EAST' },
                { id: 35106, name: 'PONG-DWONGO WEST' },
              ],
            },
            {
              id: 5533,
              name: 'OTOK',
              villages: [
                { id: 35112, name: 'AKWARA EAST' },
                { id: 35111, name: 'ALIPAN EAST' },
                { id: 35110, name: 'ALIPAN WEST' },
                { id: 35113, name: 'ATIPI' },
                { id: 35119, name: 'BINEN' },
                { id: 35123, name: 'DEM CENTRAL' },
                { id: 35114, name: 'DEM EAST' },
                { id: 35115, name: 'DEM WEST' },
                { id: 35120, name: 'LAJULE OWINY' },
                { id: 35124, name: 'LANGOLE' },
                { id: 35122, name: 'LATO' },
                { id: 35116, name: 'OGOLE ANGARO' },
                { id: 35117, name: 'OGOLE OTOK' },
                { id: 35125, name: 'OGOLEOTOK WEST' },
                { id: 35118, name: 'ORA-OTWILO EAST' },
                { id: 35121, name: 'ORA-TWILO CENTRAL' },
              ],
            },
            {
              id: 5534,
              name: 'PALENGA',
              villages: [
                { id: 35139, name: 'ABIL-KI-WINYO EAST' },
                { id: 35126, name: 'ABIL-KI-WINYO WEST' },
                { id: 35128, name: 'KILUNGA' },
                { id: 35129, name: 'KOM-PE-TENE' },
                { id: 35130, name: 'LACWERKOR' },
                { id: 35131, name: 'LAMIR LWALA' },
                { id: 35132, name: 'LAMIR NORTH' },
                { id: 65716, name: 'LUTYEK' },
                { id: 69229, name: 'ORUTE CENTRAL' },
                { id: 35133, name: 'ORUTE EAST' },
                { id: 35134, name: 'ORUTE WEST' },
                { id: 35135, name: 'TUMA-ATOO EAST' },
                { id: 35136, name: 'TUMA-ATOO WEST' },
                { id: 35127, name: 'TUMATOO' },
                { id: 35137, name: 'WANDUKU  WEST' },
                { id: 35138, name: 'WANDUKU CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 1198,
          name: 'PAJULE TOWN COUNCIL',
          parishes: [
            {
              id: 5553,
              name: 'AWALMON WARD',
              villages: [
                { id: 35293, name: 'AKWARA WEST' },
                { id: 35294, name: 'GANG LENGO' },
                { id: 35289, name: 'LABATI OLWONGA' },
                { id: 35290, name: 'LACANI' },
                { id: 35291, name: 'LAGEYA' },
                { id: 35292, name: 'MISSION  B' },
              ],
            },
            {
              id: 5554,
              name: 'GWILI WARD',
              villages: [
                { id: 35300, name: 'AYWEE CENTRAL' },
                { id: 35295, name: 'AYWEE EAST' },
                { id: 35301, name: 'AYWEE WEST' },
                { id: 35296, name: 'LACEK-TAR WEST' },
                { id: 35297, name: 'LILA' },
                { id: 35298, name: 'OJILE WEST' },
                { id: 35299, name: 'WAGKWEYO' },
              ],
            },
            {
              id: 5551,
              name: 'LATUTURU WARD',
              villages: [
                { id: 35280, name: 'CENTRAL WARD' },
                { id: 35277, name: 'KAL-KWARO' },
                { id: 35279, name: 'LAPEDE EAST' },
                { id: 35278, name: 'LAPEDE WEST' },
                { id: 35281, name: 'OGANAYILA WEST' },
              ],
            },
            {
              id: 5552,
              name: 'PAGOL WARD',
              villages: [
                { id: 35288, name: 'ADEGDIC' },
                { id: 35284, name: 'GWENG KORO' },
                { id: 35285, name: 'LABATI OLWONGA CENTRAL' },
                { id: 35283, name: 'MISSION  A' },
                { id: 35286, name: 'MISSION C' },
                { id: 35282, name: 'OLAM-PUR' },
                { id: 35287, name: 'TECHNICAL' },
              ],
            },
          ],
        },
        {
          id: 1190,
          name: 'POROGALI',
          parishes: [
            {
              id: 5525,
              name: 'ALIMA',
              villages: [
                { id: 35037, name: 'ALIMA EAST' },
                { id: 35036, name: 'ALIMA SOUTH' },
                { id: 35035, name: 'ALIMA WEST' },
                { id: 35032, name: 'DOL' },
                { id: 35038, name: 'LAGWENOLIM' },
                { id: 35033, name: 'LAGWENOLIM CENTRAL' },
                { id: 35034, name: 'LOC KEN' },
                { id: 35039, name: 'WANG-LAKILA' },
                { id: 71032, name: 'WANG-LANGO' },
              ],
            },
            {
              id: 5526,
              name: 'AWEE',
              villages: [
                { id: 35040, name: 'ABICINIA' },
                { id: 35043, name: 'ABICINIA WEST' },
                { id: 60165, name: 'BUNGA BONE SOUTH' },
                { id: 61476, name: 'GWENG MATAR' },
                { id: 35044, name: 'ODONG WEE' },
                { id: 35045, name: 'ODWAL TYEN' },
                { id: 35046, name: 'OKOMO' },
                { id: 68836, name: 'OLIRI' },
                { id: 69174, name: 'ORAWIC' },
                { id: 35047, name: 'POROGALI CENTRAL' },
                { id: 35041, name: 'POROGALI WEST' },
                { id: 35042, name: 'WANG BAC' },
              ],
            },
            {
              id: 5527,
              name: 'DURE',
              villages: [
                { id: 35051, name: 'ABANEKA' },
                { id: 35052, name: 'ADISABABA' },
                { id: 35048, name: 'BAR OYWEC' },
                { id: 35053, name: 'DURE CENTRAL' },
                { id: 35054, name: 'DURE NORTH' },
                { id: 35055, name: 'DURE SOUTH' },
                { id: 35049, name: 'LOBO LATEK' },
                { id: 35050, name: 'NYANGO GWAR' },
              ],
            },
            {
              id: 5523,
              name: 'LAMIN NYIM',
              villages: [
                { id: 35027, name: 'ABANG' },
                { id: 35024, name: 'BUNGA BONE' },
                { id: 35023, name: 'GWENG OTIRI' },
                { id: 64891, name: 'LABWONO' },
                { id: 65056, name: 'LAMINYIM CENTRAL' },
                { id: 35025, name: 'LAMINYIM EAST' },
                { id: 35026, name: 'LAMINYIM WEST' },
                { id: 65849, name: 'MACOPUR' },
                { id: 35029, name: 'OBALO' },
                { id: 35028, name: 'PURUNGU' },
              ],
            },
            {
              id: 5524,
              name: 'LATAYI',
              villages: [
                { id: 57412, name: 'ADAK' },
                { id: 57417, name: 'ADAK WEST' },
                { id: 35030, name: 'ANGOKO' },
                { id: 58278, name: 'ANGOKO NORTH' },
                { id: 58928, name: 'BAR-AYOM' },
                { id: 61649, name: 'IPABO' },
                { id: 35031, name: 'TUMAYII' },
                { id: 71034, name: 'WANG-OPOK CENTRAL' },
                { id: 71035, name: 'WANG-OPOK EAST' },
                { id: 71036, name: 'WANG-OPOK WEST' },
                { id: 71150, name: 'WILELA' },
              ],
            },
            {
              id: 5522,
              name: 'LATIGI',
              villages: [
                { id: 35015, name: 'ARINGO MONE' },
                { id: 61327, name: 'GALAGALA' },
                { id: 35017, name: 'LAPOGO IKOR' },
                { id: 35018, name: 'LATIGI' },
                { id: 35021, name: 'NEN KIWANGI' },
                { id: 35019, name: 'OMUNY TURUBUC' },
                { id: 35016, name: 'ONYON' },
                { id: 69348, name: 'OWACOMOO' },
                { id: 35022, name: 'PAINYANG' },
                { id: 35020, name: 'PARWEYO' },
                { id: 70624, name: 'TE-GWENG' },
                { id: 70794, name: 'TONGWIRI' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
