import { District } from '../index';

export default {
  id: 64,
  name: 'RAKAI',
  counties: [
    {
      id: 153,
      name: 'BUYAMBA COUNTY',
      sub_counties: [
        {
          id: 944,
          name: 'DDWANIRO',
          parishes: [
            {
              id: 4359,
              name: 'BUYAMBA',
              villages: [
                { id: 27948, name: 'BIGANDO A' },
                { id: 27949, name: 'BIGANDO B' },
                { id: 27950, name: 'BIGANDO C' },
                { id: 27951, name: 'BULONGO' },
                { id: 27952, name: 'BUYAMBA T/C' },
                { id: 27953, name: 'KACCUMU' },
                { id: 27954, name: 'KASAGAZI' },
                { id: 27955, name: 'KIJJUNA A' },
                { id: 27956, name: 'KIJJUNA B' },
                { id: 27957, name: 'KINAAWA' },
                { id: 27958, name: 'KYAKALASA' },
                { id: 27959, name: 'KYONDO' },
                { id: 27960, name: 'MIKONI' },
              ],
            },
            {
              id: 4360,
              name: 'DDWANIRO',
              villages: [
                { id: 27961, name: 'BIGANDO' },
                { id: 27962, name: 'BUYAMU' },
                { id: 27963, name: 'DDWANIRO' },
                { id: 27964, name: 'KANSUNGA' },
                { id: 27965, name: 'KATONTO' },
                { id: 27966, name: 'KIREETA' },
                { id: 27967, name: 'KYABALEMERA' },
                { id: 27968, name: 'KYAKASONZI' },
                { id: 27969, name: 'KYAMASASI' },
                { id: 27970, name: 'LUTOMA' },
                { id: 27971, name: 'LWABBANDA' },
                { id: 27972, name: 'NSIMBO' },
              ],
            },
            {
              id: 4363,
              name: 'KALEERE/MALEMBA',
              villages: [
                { id: 27993, name: 'GGOMBE' },
                { id: 27994, name: 'KABAKYALA' },
                { id: 27995, name: 'KAKUNYU' },
                { id: 27996, name: 'KALEERE A' },
                { id: 27997, name: 'KALEERE B' },
                { id: 27998, name: 'KAMMENGO-NSONSO' },
                { id: 27999, name: 'KICWAMANGO' },
                { id: 28000, name: 'KIJJEBERE' },
                { id: 28001, name: 'LUWAAMA' },
              ],
            },
            {
              id: 4361,
              name: 'KAYONZA',
              villages: [
                { id: 27973, name: 'BYEMBOGO' },
                { id: 27974, name: 'KANAMUZINZI' },
                { id: 27975, name: 'KASWA' },
                { id: 27976, name: 'KAYONZA' },
                { id: 27977, name: 'KIKABYA' },
                { id: 27981, name: 'KIKONDERE' },
                { id: 27978, name: 'KISAANA' },
                { id: 27979, name: 'KYEBBUMBA' },
                { id: 27980, name: 'LWENKOLOGO' },
              ],
            },
            {
              id: 4362,
              name: 'LWAKALOLO',
              villages: [
                { id: 27982, name: 'BINONI' },
                { id: 27983, name: 'KAMPUKI' },
                { id: 27984, name: 'KATEERA A' },
                { id: 27985, name: 'KATEERA B' },
                { id: 27986, name: 'KISAAYI' },
                { id: 27987, name: 'LUTEETE-NTUNTU' },
                { id: 27988, name: 'LWAKALOOLO' },
                { id: 27989, name: 'LWEBISUNSA' },
                { id: 27990, name: 'LWENDAULA A' },
                { id: 27991, name: 'LWENDAULA B' },
                { id: 27992, name: 'NAMIYAGA' },
              ],
            },
          ],
        },
        {
          id: 945,
          name: 'KACHEERA',
          parishes: [
            {
              id: 4364,
              name: 'KAJJU',
              villages: [
                { id: 28002, name: 'KAJJU' },
                { id: 28003, name: 'KATOVU A' },
                { id: 28004, name: 'KATOVU B' },
                { id: 28009, name: 'KIBAATI' },
                { id: 28005, name: 'LUSALWERA' },
                { id: 28006, name: 'MUGOROIRE' },
                { id: 28007, name: 'RWAMATAMA' },
                { id: 28008, name: 'RWEBICOOLI' },
              ],
            },
            {
              id: 4365,
              name: 'KAKIRI',
              villages: [
                { id: 28016, name: 'KIBIKURA' },
                { id: 28010, name: 'KIGANDO' },
                { id: 28011, name: 'KYABALEGEYA' },
                { id: 28014, name: 'LWEBIRIBA' },
                { id: 28012, name: 'LWEKIYENGO' },
                { id: 28013, name: 'RWEBIHIMBA' },
                { id: 28015, name: 'RWENTAMO' },
              ],
            },
            {
              id: 4369,
              name: 'KATATENGA',
              villages: [
                { id: 28034, name: 'KATATENGA' },
                { id: 28035, name: 'KIJUKIMWE/KINYUMBA-KIMU' },
                { id: 28036, name: 'RWAMUNONKO  A' },
                { id: 28037, name: 'RWAMUNONKO  B' },
                { id: 28038, name: 'RWENTARE A' },
                { id: 28039, name: 'RWENTARE B' },
              ],
            },
            {
              id: 4366,
              name: 'KAYONZA',
              villages: [
                { id: 28017, name: 'KINOTA' },
                { id: 28018, name: 'KYAKATAMALA' },
                { id: 28020, name: 'RWANTANGA' },
                { id: 28019, name: 'RWENSHABISHABI' },
              ],
            },
            {
              id: 4367,
              name: 'LWANGA',
              villages: [
                { id: 28021, name: 'KABBUMBA' },
                { id: 28022, name: 'KALYERENGEZA' },
                { id: 28023, name: 'KATANJOVU' },
                { id: 28025, name: 'KYENKOBE' },
                { id: 28024, name: 'LWANGA' },
              ],
            },
            {
              id: 4368,
              name: 'LYAKISANA',
              villages: [
                { id: 28026, name: 'BIKARABO' },
                { id: 28027, name: 'BUYOJWA' },
                { id: 28028, name: 'KAMULABA' },
                { id: 28029, name: 'LWENANGA' },
                { id: 28030, name: 'LYAKISANA' },
                { id: 28031, name: 'MUKOGOTE' },
                { id: 28032, name: 'NAKASENYI' },
                { id: 28033, name: 'RWAMAGABI' },
              ],
            },
          ],
        },
        {
          id: 946,
          name: 'KAGAMBA (BUYAMBA)',
          parishes: [
            {
              id: 4370,
              name: 'KAGAMBA',
              villages: [
                { id: 28040, name: 'BUTTANDIGA' },
                { id: 28041, name: 'KABUSA A' },
                { id: 28042, name: 'KABUSA B' },
                { id: 28043, name: 'KAGAMBA' },
                { id: 28044, name: 'KIYAMBA' },
                { id: 28045, name: 'KIZIRA' },
                { id: 28046, name: 'KYAKABUGEMA' },
                { id: 28047, name: 'NABUBAALE A' },
                { id: 28048, name: 'NABUBAALE B' },
              ],
            },
            {
              id: 4371,
              name: 'KIMULI',
              villages: [
                { id: 28049, name: 'KAKENKE' },
                { id: 28050, name: 'KAMPISI' },
                { id: 28051, name: 'KIGAYAAZA' },
                { id: 28052, name: 'KIMULI' },
                { id: 28053, name: 'KITAMBUZA' },
                { id: 28054, name: 'KITUUNTU A' },
                { id: 28055, name: 'KITUUNTU B' },
                { id: 28057, name: 'LWENTULEGE' },
                { id: 28056, name: 'LWENTULEGE  T/C' },
                { id: 28058, name: 'MWERUKA' },
              ],
            },
            {
              id: 4372,
              name: 'LWABAKOOBA',
              villages: [
                { id: 28059, name: 'BANYORO' },
                { id: 28060, name: 'BBAALE' },
                { id: 28061, name: 'KANAGISA' },
                { id: 28062, name: 'KASERERE' },
                { id: 28063, name: 'KATUNTU' },
                { id: 28064, name: 'KIWOLOLO' },
                { id: 28065, name: 'LUGANDO' },
                { id: 28066, name: 'LUWANGA A' },
                { id: 28067, name: 'LUWANGA B' },
                { id: 28068, name: 'LWABAKOOBA' },
                { id: 28069, name: 'NABIZZI A' },
                { id: 28070, name: 'NABIZZI B' },
              ],
            },
          ],
        },
        {
          id: 2012,
          name: 'KASANKALA',
          parishes: [
            {
              id: 9624,
              name: 'KASANKALA',
              villages: [
                { id: 62891, name: 'KASANKALA A' },
                { id: 62892, name: 'KASANKALA B' },
                { id: 62893, name: 'KASANKALA T/C' },
                { id: 67815, name: 'NNONGO B' },
              ],
            },
            {
              id: 9732,
              name: 'KIRANGIRA',
              villages: [
                { id: 63293, name: 'KENJOKI' },
                { id: 63794, name: 'KIRANGIRA' },
                { id: 64480, name: 'KYABAKAZI A' },
                { id: 64481, name: 'KYABAKAZI B' },
              ],
            },
            {
              id: 9776,
              name: 'KIYUMBAKIMU',
              villages: [
                { id: 62609, name: 'KANYOGOGA' },
                { id: 62884, name: 'KASAMBYA T/C' },
                { id: 64149, name: 'KIYUMBAKIMU' },
                { id: 64596, name: 'KYALUYIMUKA' },
              ],
            },
            {
              id: 9794,
              name: 'KONGOTA',
              villages: [
                { id: 63370, name: 'KIBINGO' },
                { id: 64285, name: 'KONGOTA A' },
                { id: 64286, name: 'KONGOTA B' },
                { id: 66985, name: 'NAKABAZZI' },
              ],
            },
            {
              id: 9823,
              name: 'KYAMAKANAGA',
              villages: [
                { id: 64606, name: 'KYAMAKANAGA A' },
                { id: 64607, name: 'KYAMAKANAGA B' },
                { id: 67814, name: 'NNONGO A' },
              ],
            },
          ],
        },
        {
          id: 947,
          name: 'LWAMAGGWA',
          parishes: [
            {
              id: 4373,
              name: 'BUGONA',
              villages: [
                { id: 28071, name: 'BULONGO' },
                { id: 28072, name: 'KABAALE' },
                { id: 28073, name: 'KINABBEERE' },
                { id: 28074, name: 'KIROWOOZA' },
                { id: 28075, name: "KISAMBA 'A'" },
                { id: 28076, name: "KISAMBA 'B'" },
                { id: 28077, name: 'KYENGEZA-KAFUFU' },
                { id: 28078, name: 'KYERAGONGO' },
                { id: 28079, name: 'LULAGALA' },
                { id: 28080, name: 'MULEEBI' },
              ],
            },
            {
              id: 4374,
              name: 'KABUSOTTA',
              villages: [
                { id: 28081, name: 'BWENYEGE' },
                { id: 28082, name: "KABUSOTTA 'A'" },
                { id: 28083, name: "KABUSOTTA 'B'" },
                { id: 28084, name: 'KATUULO' },
                { id: 28085, name: 'KYENGEZA' },
              ],
            },
            {
              id: 4375,
              name: 'KAKUNDI',
              villages: [
                { id: 28086, name: 'KAGAAGA' },
                { id: 28087, name: 'KAKUNDI' },
                { id: 28088, name: 'KIGOTO' },
                { id: 28089, name: 'LUGALAMA' },
                { id: 28090, name: 'LUNAMUNYU' },
                { id: 28091, name: 'NTALULE' },
              ],
            },
            {
              id: 4376,
              name: 'KIBUUKA',
              villages: [
                { id: 28092, name: 'KAKENKE' },
                { id: 28093, name: 'KAMESE' },
                { id: 28094, name: 'KAMUNUNKU' },
                { id: 28095, name: 'KIKUMBAANO' },
                { id: 28096, name: 'KYABANADDA' },
                { id: 28097, name: 'KYANIKA' },
                { id: 28098, name: 'LUTEETE' },
                { id: 28099, name: "LWOYO 'A'" },
                { id: 28100, name: "LWOYO 'B'" },
                { id: 28101, name: 'SERINYA' },
              ],
            },
            {
              id: 4377,
              name: 'KIWEEKA',
              villages: [
                { id: 28102, name: 'BYEZITIIRE' },
                { id: 28103, name: 'KAKABAGYO' },
                { id: 28104, name: 'KIMYUKA' },
                { id: 28105, name: 'KIWEEKA' },
                { id: 28106, name: 'LUBIMBA' },
                { id: 28107, name: 'LWAMAGGWA' },
                { id: 28108, name: 'MBAALE' },
              ],
            },
            {
              id: 4378,
              name: 'KYABIGONDO',
              villages: [
                { id: 28109, name: 'BUYIIYI' },
                { id: 28110, name: 'KAYABWE' },
                { id: 28111, name: "KIJJAKO 'A'" },
                { id: 28112, name: "KIJJAKO 'B'" },
                { id: 28113, name: 'KYABIGONDO' },
                { id: 28114, name: 'KYAKABIKWA' },
                { id: 28115, name: 'LUNONI' },
                { id: 28116, name: 'LWAMAGABI' },
                { id: 28117, name: 'MUDAALA' },
                { id: 28118, name: 'NDEEBA' },
                { id: 28119, name: "NTOKOTA 'A'" },
                { id: 28120, name: "NTOKOTA 'B'" },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 152,
      name: 'KOOKI COUNTY',
      sub_counties: [
        {
          id: 937,
          name: 'BYAKABANDA',
          parishes: [
            {
              id: 4331,
              name: 'BYAKABANDA',
              villages: [
                { id: 27709, name: 'BYAKABANDA' },
                { id: 27710, name: 'KAKUMBIRO' },
                { id: 27711, name: 'KASABUKENGERE' },
                { id: 27712, name: 'KASIIKA' },
                { id: 27713, name: 'KATERERO' },
                { id: 27714, name: 'KIYOOZA' },
                { id: 27715, name: 'KYALULAALA' },
                { id: 27716, name: 'KYANDAAZA' },
                { id: 27717, name: 'LUGONGO' },
                { id: 27718, name: 'LWANAMBOGA' },
                { id: 27719, name: 'SSERINYA' },
              ],
            },
            {
              id: 4332,
              name: 'KAMUKALO',
              villages: [
                { id: 27720, name: 'BBUBA' },
                { id: 27721, name: 'BUMOGOLO' },
                { id: 27722, name: 'KAAMI' },
                { id: 27723, name: 'KAMUKALO A' },
                { id: 27724, name: 'KAMUKALO B' },
                { id: 27725, name: 'KIBINDA' },
                { id: 27726, name: 'KIKAKATA' },
                { id: 27727, name: 'KISOMOLE' },
                { id: 27728, name: 'KYAWANYANA' },
                { id: 27729, name: 'KYEMPEWO' },
                { id: 27730, name: 'LUKONDO' },
                { id: 27731, name: 'LUKYAMO' },
              ],
            },
            {
              id: 4333,
              name: 'KITAASA',
              villages: [
                { id: 27732, name: 'BULAKATI' },
                { id: 27733, name: 'KAWUNGULI' },
                { id: 27734, name: 'KITAASA' },
                { id: 27735, name: 'KYALUBINGA' },
                { id: 27736, name: 'MICUNGIRO' },
                { id: 27737, name: 'MPUNGE' },
                { id: 27738, name: 'NABUGANDO' },
              ],
            },
          ],
        },
        {
          id: 942,
          name: 'KIBANDA',
          parishes: [
            {
              id: 4350,
              name: 'BBALE',
              villages: [
                { id: 27891, name: 'BBAALE' },
                { id: 27892, name: 'BULANGA' },
                { id: 27893, name: 'GUNDA' },
                { id: 27894, name: 'KASISA' },
                { id: 27895, name: 'KAYUNGA' },
                { id: 27896, name: 'KITOVU' },
                { id: 27897, name: 'LUSASA' },
                { id: 27898, name: 'NAMATA' },
              ],
            },
            {
              id: 4351,
              name: 'KAKINGA',
              villages: [
                { id: 27899, name: 'BYOKYA' },
                { id: 27900, name: 'KAKINGA-NAMAGOMA' },
                { id: 27901, name: 'KASESE' },
                { id: 27902, name: 'KIKONGE A' },
                { id: 27907, name: 'KIKONGE B' },
                { id: 27903, name: 'KYAKABUUTU' },
                { id: 27904, name: 'KYAKAGO' },
                { id: 27905, name: 'LWENSAMBYA' },
                { id: 27906, name: 'NAKAWAMA' },
              ],
            },
            {
              id: 4354,
              name: 'KYABIWA',
              villages: [
                { id: 27923, name: 'KAKOMERO' },
                { id: 27924, name: 'KANAZI-NDYAYANJOVU' },
                { id: 27925, name: 'KATEETE' },
                { id: 27926, name: 'KIBULIRO B' },
                { id: 27927, name: 'KYABIWA-LWANGONDO' },
                { id: 27928, name: 'LUGEZI-KABIRA' },
              ],
            },
            {
              id: 4352,
              name: 'KYALUGABA',
              villages: [
                { id: 27908, name: 'BIGANDO-KYAMUNYERERE' },
                { id: 27909, name: 'BUGOMOLA' },
                { id: 27910, name: 'KABWASA' },
                { id: 27911, name: 'KIBULIRO A' },
                { id: 27912, name: 'KISWERE A' },
                { id: 27913, name: 'KISWERE B' },
                { id: 27914, name: 'KYALUGABA' },
                { id: 27915, name: 'KYAMULENGERA' },
              ],
            },
            {
              id: 4353,
              name: 'MAGABI',
              villages: [
                { id: 27916, name: 'GAYAZA' },
                { id: 27921, name: 'KAJUNGU' },
                { id: 27917, name: 'KITEREDDE' },
                { id: 27918, name: 'KIYONZA' },
                { id: 27922, name: 'NTANTAMUKYE' },
                { id: 27920, name: 'NYAKALINZI' },
                { id: 27919, name: 'RUGALAMA' },
              ],
            },
          ],
        },
        {
          id: 943,
          name: 'KIFAMBA',
          parishes: [
            {
              id: 4355,
              name: 'KABALA',
              villages: [
                { id: 27929, name: 'KABALA' },
                { id: 27930, name: 'KALONGO' },
                { id: 27931, name: 'KITEREDDE' },
                { id: 27932, name: 'MBIRIZI' },
              ],
            },
            {
              id: 4358,
              name: 'KAWUNGULI',
              villages: [
                { id: 27943, name: 'KAGONGERO' },
                { id: 27944, name: 'KASAASA' },
                { id: 27945, name: 'LULAALA' },
                { id: 27946, name: 'LWEMIWULU' },
                { id: 27947, name: 'MANNYA' },
              ],
            },
            {
              id: 4356,
              name: 'KIFAMBA',
              villages: [
                { id: 27933, name: 'KIFAMBA' },
                { id: 27934, name: 'KIJJUMBA' },
                { id: 27935, name: 'KITENTE' },
                { id: 27936, name: 'LUTEMI' },
                { id: 27937, name: 'LWEMISEGE' },
                { id: 27938, name: 'NABBUNGA' },
              ],
            },
            {
              id: 4357,
              name: 'KISAASA',
              villages: [
                { id: 27939, name: 'KIRUULI' },
                { id: 27940, name: 'KISAASA' },
                { id: 27941, name: 'NSEESE' },
                { id: 27942, name: 'NYANGA-KINTALE' },
              ],
            },
          ],
        },
        {
          id: 941,
          name: 'KIZIBA',
          parishes: [
            {
              id: 4348,
              name: 'LUKERERE',
              villages: [
                { id: 27885, name: 'AKASHANSHA' },
                { id: 27877, name: 'LUKERERE A' },
                { id: 27878, name: 'LUKERERE B' },
                { id: 27879, name: 'LUKERERE CENTRAL' },
                { id: 27880, name: 'NSAMBYA  A' },
                { id: 27881, name: 'NSAMBYA  B' },
                { id: 27882, name: 'RYELU A' },
                { id: 27883, name: 'RYELU B' },
                { id: 27884, name: 'RYELU CENTRAL' },
              ],
            },
            {
              id: 4346,
              name: 'MWERUKA',
              villages: [
                { id: 27852, name: 'KALWAYI' },
                { id: 27865, name: 'KASESE' },
                { id: 27855, name: 'KAYORO' },
                { id: 27853, name: 'KEIRALIZO' },
                { id: 27856, name: 'KIBUTAMO' },
                { id: 27857, name: 'KIJWAALA' },
                { id: 27858, name: 'KITAHIZA' },
                { id: 27859, name: 'KIVUMBULA' },
                { id: 27860, name: 'KIZIBA' },
                { id: 27861, name: 'KOBUKULULA' },
                { id: 27862, name: 'KYAJJUMBA' },
                { id: 27863, name: 'MAGABIRANO A' },
                { id: 27866, name: 'MAGABIRANO B' },
                { id: 27854, name: 'MALEMBA' },
                { id: 27864, name: 'MWERUKA' },
              ],
            },
            {
              id: 4349,
              name: 'NDAGGA',
              villages: [
                { id: 27886, name: 'KAMICHOLA' },
                { id: 27887, name: 'KATUNGA' },
                { id: 27888, name: 'KYAMIGONGO' },
                { id: 27889, name: 'NDAGA A' },
                { id: 27890, name: 'NDAGA B' },
              ],
            },
            {
              id: 4347,
              name: 'RWENSINGA',
              villages: [
                { id: 27867, name: 'KABETEMERE' },
                { id: 27868, name: 'KIJONJO' },
                { id: 27869, name: 'KIYONZA' },
                { id: 27870, name: 'KYAVU A' },
                { id: 27871, name: 'KYAVU B' },
                { id: 27872, name: 'KYEMWA' },
                { id: 27873, name: 'RWAKAKALA' },
                { id: 27874, name: 'RWEIBALE A' },
                { id: 27875, name: 'RWEIBALE B' },
                { id: 27876, name: 'RWENSINGA' },
              ],
            },
          ],
        },
        {
          id: 938,
          name: 'KYALULANGIRA',
          parishes: [
            {
              id: 4337,
              name: 'DYANGO',
              villages: [
                { id: 27774, name: 'DYANGO A' },
                { id: 27775, name: 'DYANGO B' },
                { id: 27777, name: 'KAMATE' },
                { id: 27776, name: 'KAROKALUNGI' },
                { id: 27778, name: 'KIJONJO' },
                { id: 27784, name: 'KIJONJO A' },
                { id: 27779, name: 'KIKALABO  A' },
                { id: 27780, name: 'KIKALABO  B' },
                { id: 27781, name: 'KITAHIZA A' },
                { id: 27782, name: 'KITAHIZA B' },
                { id: 27783, name: 'KOBUKULURA' },
              ],
            },
            {
              id: 4334,
              name: 'KALUNGI',
              villages: [
                { id: 27739, name: 'BITUUSI' },
                { id: 27740, name: 'BYENKENDE' },
                { id: 27741, name: 'KABINGO' },
                { id: 27742, name: 'KALIIRO' },
                { id: 27743, name: 'KALUNGI' },
                { id: 27744, name: 'KANGOMBE A' },
                { id: 27745, name: 'KANGOMBE B' },
                { id: 27746, name: 'KIBAALE' },
                { id: 27747, name: 'KIGUMBA' },
                { id: 27748, name: 'KYAKASENENE A' },
                { id: 27749, name: 'KYAKASENENE B' },
                { id: 27750, name: 'KYAMBULUGU' },
                { id: 27751, name: 'LUBUMBA' },
                { id: 27752, name: 'RWANTENDE' },
                { id: 27753, name: 'TOLERO' },
              ],
            },
            {
              id: 4335,
              name: 'KASULA',
              villages: [
                { id: 27754, name: 'BULIGI' },
                { id: 27755, name: 'KALUGU' },
                { id: 27756, name: 'KAMOMA A' },
                { id: 27757, name: 'KAMOMA B' },
                { id: 27758, name: 'KASULA' },
                { id: 27759, name: 'KAYAGO A' },
                { id: 27760, name: 'KAYAGO B' },
                { id: 27761, name: 'KIGOLOMORA' },
                { id: 27762, name: 'KYALULANGIRA' },
                { id: 27763, name: 'KYAMUMBA' },
                { id: 27764, name: 'NTEBEZADDUNGU' },
                { id: 27765, name: 'NTOVU' },
                { id: 27766, name: 'SANJE A' },
                { id: 27767, name: 'SANJE B' },
              ],
            },
            {
              id: 4338,
              name: 'KIZINGA',
              villages: [
                { id: 61965, name: 'KABUNGO' },
                { id: 27785, name: 'KAWENDA' },
                { id: 27786, name: 'KIZINGA A' },
                { id: 27787, name: 'KIZINGA B' },
                { id: 27788, name: 'KIZINGA C' },
              ],
            },
            {
              id: 4336,
              name: 'RWAMBAJJO',
              villages: [
                { id: 27769, name: 'KABAALE' },
                { id: 27768, name: 'KABASHAMBO' },
                { id: 63959, name: 'KISOVU' },
                { id: 27770, name: 'NKUNDI' },
                { id: 27771, name: 'RWABAGANDA' },
                { id: 27772, name: 'RWAMBAJJO A' },
                { id: 27773, name: 'RWAMBAJJO B' },
              ],
            },
          ],
        },
        {
          id: 939,
          name: 'LWANDA',
          parishes: [
            {
              id: 4339,
              name: 'BITABAGO',
              villages: [
                { id: 27789, name: 'BITABAGO' },
                { id: 27790, name: 'BUTERERE' },
                { id: 27791, name: 'BUTULA' },
                { id: 27792, name: "KAKOMA 'A'" },
                { id: 27793, name: "KAKOMA 'B'" },
                { id: 27794, name: 'KIRUNDAMALIGA' },
                { id: 27795, name: 'KITEMBA' },
                { id: 27796, name: 'LUMBUGU' },
                { id: 27797, name: 'MAKONDO' },
              ],
            },
            {
              id: 4340,
              name: 'BUTIITI',
              villages: [
                { id: 27798, name: 'BITOOKE-BISALIRE' },
                { id: 27799, name: 'BUTITI' },
                { id: 27800, name: 'KABAALE-KOOKI' },
                { id: 27801, name: 'KABALUNGI' },
                { id: 27802, name: 'KABINGO' },
                { id: 27803, name: 'KIJJUMBA' },
                { id: 27804, name: 'KITWALANYE' },
                { id: 27805, name: 'KIWENDA' },
                { id: 27806, name: 'LUTUNGU' },
                { id: 27807, name: 'NSIMBO' },
              ],
            },
            {
              id: 4341,
              name: 'KANONI',
              villages: [
                { id: 27808, name: 'BULYAKAMU' },
                { id: 27809, name: 'KAMULI' },
                { id: 27810, name: 'KANONI' },
                { id: 27811, name: 'KAYUNGA' },
                { id: 27812, name: 'KIKAKATA' },
                { id: 27813, name: 'LUTEEBE' },
                { id: 27814, name: 'MPAAMA' },
              ],
            },
            {
              id: 4342,
              name: 'KASENSERO',
              villages: [
                { id: 27815, name: 'KAMMENGO' },
                { id: 27816, name: 'KISIMBANYIRIRI' },
                { id: 27817, name: 'KITONEZI' },
                { id: 27819, name: "KIWAGUZI ''B'" },
                { id: 27818, name: "KIWAGUZI 'A'" },
                { id: 27820, name: 'KYALUWAKULA' },
                { id: 27821, name: 'KYENGEZA' },
                { id: 27822, name: 'MIKUNYU' },
                { id: 27823, name: 'NABYALA' },
                { id: 27824, name: 'NAKITOKOLO' },
                { id: 27825, name: 'NSOZIBBIRI' },
              ],
            },
            {
              id: 4343,
              name: 'KIYOVU',
              villages: [
                { id: 27826, name: 'GOSOOLA' },
                { id: 27827, name: 'KAYIJJA' },
                { id: 27828, name: 'KENGOBE' },
                { id: 27829, name: 'KIGANDA' },
                { id: 27830, name: 'KIGIMBI' },
                { id: 27831, name: 'KIREMA' },
                { id: 27832, name: 'KITUNTU' },
                { id: 27833, name: 'KIYOVU' },
                { id: 27834, name: 'LUKYAMU' },
                { id: 27835, name: 'LUSOLO' },
                { id: 27836, name: 'LWANDA TOWN A' },
                { id: 27839, name: 'LWANDA TOWN B' },
                { id: 27837, name: 'SSERINYA A' },
                { id: 27838, name: 'SSERINYA B' },
              ],
            },
          ],
        },
        {
          id: 940,
          name: 'RAKAI TOWN COUNCIL',
          parishes: [
            {
              id: 4344,
              name: 'KATUNTU WARD',
              villages: [
                { id: 27840, name: 'KAKONI' },
                { id: 27841, name: 'KATUNTU' },
                { id: 27842, name: 'KATWETWE' },
                { id: 27843, name: 'KISANSA' },
                { id: 27844, name: 'KIWAKANYA' },
                { id: 27845, name: 'KYAKASOLO' },
              ],
            },
            {
              id: 4345,
              name: 'KIBONA WARD',
              villages: [
                { id: 27846, name: 'KAGOLOGOLO' },
                { id: 27847, name: 'KAJJOKI' },
                { id: 27848, name: 'KIBONA A' },
                { id: 27849, name: 'KIBONA B' },
                { id: 27850, name: 'LWAKAGALA' },
                { id: 27851, name: 'RAKAI CENTRAL' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
