import { District } from '../types';

export default {
  id: 28,
  name: 'RUBANDA',
  counties: [
    {
      id: 63,
      name: 'RUBANDA COUNTY EAST',
      sub_counties: [
        {
          id: 412,
          name: 'BUBARE',
          parishes: [
            {
              id: 1843,
              name: 'BUBARE',
              villages: [
                { id: 11706, name: 'BUBARE TRADING CENTRE' },
                { id: 11714, name: 'BUZOOBA' },
                { id: 11707, name: 'BWARO  A' },
                { id: 11708, name: 'BWARO  B' },
                { id: 11709, name: 'KANABA  A' },
                { id: 11710, name: 'KANABA  B' },
                { id: 11711, name: 'KITUMBEZI' },
                { id: 11712, name: 'KYAMABARE' },
                { id: 11713, name: 'MUCHAHI' },
              ],
            },
            {
              id: 1849,
              name: 'BUSHUURA',
              villages: [
                { id: 11766, name: 'BUSHURA' },
                { id: 11768, name: 'KABERE' },
                { id: 11767, name: 'KABUGU' },
                { id: 11769, name: 'KATARAGA' },
                { id: 11770, name: 'NYAKIHANGA' },
                { id: 11771, name: 'RUHASYA' },
                { id: 11765, name: 'RWAKAYUNDO' },
              ],
            },
            {
              id: 1844,
              name: 'IHANGA',
              villages: [
                { id: 11715, name: 'BUKAJU' },
                { id: 11716, name: 'KARUBANDA' },
                { id: 11717, name: 'KASHAKI' },
                { id: 11718, name: 'KIHENGAMO' },
                { id: 11719, name: 'KIMUSYA  A' },
                { id: 11720, name: 'KIMUSYA  B' },
                { id: 11721, name: 'KIRURUMA' },
                { id: 11722, name: 'KYANTOBI' },
                { id: 11723, name: 'KYARUGONDO' },
                { id: 11724, name: 'MUNGYEGYE' },
                { id: 11725, name: 'RUKINDA' },
              ],
            },
            {
              id: 1845,
              name: 'KAGARAMA',
              villages: [
                { id: 11726, name: 'BUSHATO' },
                { id: 11727, name: 'HABUTIKI' },
                { id: 11728, name: 'HAMURAMBI' },
                { id: 11729, name: 'ISHANGA' },
                { id: 11730, name: 'KASHEKYE' },
                { id: 11731, name: 'KIRAARO' },
                { id: 11732, name: 'KITOGOTA' },
                { id: 11733, name: 'KYABAHINGA' },
                { id: 11734, name: 'KYARUJUMBA' },
                { id: 11735, name: 'RWAMATE' },
                { id: 11736, name: 'RWENGWE' },
              ],
            },
            {
              id: 1846,
              name: 'KASHENYI',
              villages: [
                { id: 11737, name: 'BUKWATAMAGURU' },
                { id: 11738, name: 'HAMABAARE' },
                { id: 11739, name: 'KANYASHABWE' },
                { id: 11740, name: 'KARUBANDA' },
                { id: 11742, name: 'KITABUGIKA' },
                { id: 11743, name: 'MUMWIGA' },
                { id: 11744, name: 'NTUNGAMO' },
                { id: 11745, name: 'NYAKAFUNJO' },
                { id: 11741, name: 'NYARUNGU' },
                { id: 11746, name: 'NYUNGU' },
                { id: 11747, name: 'RUGARAMBIRO' },
                { id: 11748, name: 'RUTOOMA' },
              ],
            },
            {
              id: 1850,
              name: 'KIBUZIGYE',
              villages: [
                { id: 11772, name: 'KAFUNJO' },
                { id: 11773, name: 'KIGARAMA' },
                { id: 11774, name: 'KITABUGIKA' },
                { id: 11775, name: 'MUKOMBE' },
                { id: 11777, name: 'MURUSHEKYE' },
                { id: 11776, name: 'MUYANJE' },
                { id: 11778, name: 'NYAKABUNGO  A' },
                { id: 11779, name: 'NYAKABUNGO  B' },
                { id: 11780, name: 'NYAKIHANGA' },
                { id: 11781, name: 'NYARUTEIJA' },
                { id: 11782, name: 'RUGYENDERA  A' },
                { id: 11783, name: 'RUGYENDERA  B' },
                { id: 11784, name: 'RWAKAGYEMA' },
                { id: 11785, name: 'RWARUGAMBWA' },
                { id: 11786, name: 'RWENKUNGURU' },
              ],
            },
            {
              id: 1851,
              name: 'KITOJO',
              villages: [
                { id: 11787, name: 'KARAMBAZI' },
                { id: 11788, name: 'KARANDAGASI' },
                { id: 11789, name: 'MURAMBO  I' },
                { id: 11790, name: 'MURAMBO  II' },
                { id: 11791, name: 'NYAKAYENJE' },
                { id: 11792, name: 'NYAKIHARO' },
                { id: 11793, name: 'RWABAREERA' },
              ],
            },
            {
              id: 1847,
              name: 'MUYANJE',
              villages: [
                { id: 11749, name: 'BIRAARA' },
                { id: 11750, name: 'KAZINIRO' },
                { id: 11754, name: 'KIIRWA' },
                { id: 11751, name: 'MURAMBI' },
                { id: 11752, name: 'RUKORE' },
                { id: 11753, name: 'RUSIKIZI' },
                { id: 11755, name: 'RWENKURINJU' },
                { id: 11756, name: 'RWERE' },
              ],
            },
            {
              id: 1848,
              name: 'NYAMIYAGA',
              villages: [
                { id: 11757, name: 'HAMURARA' },
                { id: 11758, name: 'KABINDI' },
                { id: 11759, name: 'KASHAKI  A' },
                { id: 11760, name: 'KASHAKI  B' },
                { id: 11761, name: 'KATOOMA' },
                { id: 11762, name: 'KATUNGU' },
                { id: 11763, name: 'RWAMUTASYA' },
                { id: 11764, name: 'RWEMBUGU' },
              ],
            },
          ],
        },
        {
          id: 413,
          name: 'HAMURWA',
          parishes: [
            {
              id: 1852,
              name: 'IGOMANDA',
              villages: [
                { id: 11794, name: 'BUGANDARA' },
                { id: 11795, name: 'BUGOMORA' },
                { id: 11796, name: 'BWISA' },
                { id: 11797, name: 'HABUBAARE' },
                { id: 11798, name: 'HABUKUBO' },
                { id: 11799, name: 'HAKASHEKYE' },
                { id: 11800, name: 'HAKESIRIBA' },
                { id: 11801, name: 'HAMUKO' },
                { id: 11802, name: 'ISINGIRO' },
                { id: 11803, name: 'KASHEKYERA' },
                { id: 11804, name: 'MBURAMEIZI' },
                { id: 11805, name: 'NYAMIYAGA' },
                { id: 11806, name: 'RWABACENGA' },
                { id: 11807, name: 'RWARUJONGO' },
              ],
            },
            {
              id: 1853,
              name: 'KAKORE',
              villages: [
                { id: 11808, name: 'BUSHUNDE' },
                { id: 11809, name: 'HAKABURARA' },
                { id: 11810, name: 'KABIHIJO' },
                { id: 11811, name: 'KAMUTERERE' },
                { id: 11812, name: 'KATUNGU' },
                { id: 11813, name: 'KIGAZI' },
                { id: 11814, name: 'MURUHITA' },
                { id: 11815, name: 'MWIGURIRO' },
                { id: 11816, name: 'RUGARAMA' },
                { id: 11817, name: 'RWAMUGURA' },
              ],
            },
            {
              id: 1854,
              name: 'MPUNGU',
              villages: [
                { id: 11818, name: 'BUGARAMA' },
                { id: 11819, name: 'BUSHURE' },
                { id: 11820, name: 'HAKITOOMA' },
                { id: 11821, name: 'KABURARA' },
                { id: 11822, name: 'KARUNGU' },
                { id: 11823, name: 'KERERE' },
                { id: 11824, name: 'KIHENGAMO' },
                { id: 11825, name: 'MUKYOGO' },
                { id: 11826, name: 'MUZIRANTE' },
                { id: 11827, name: 'NYAMWIGURA' },
                { id: 11828, name: 'NYARUSHANJE' },
                { id: 11829, name: 'RUBOROGA' },
                { id: 11830, name: 'RUGYENDABARI' },
                { id: 11831, name: 'RUTOOMA' },
                { id: 11832, name: 'RWABUMBE' },
                { id: 11833, name: 'RWAMIGANDA' },
              ],
            },
            {
              id: 1855,
              name: 'RUHONWA',
              villages: [
                { id: 11834, name: 'KABANDAMA' },
                { id: 11835, name: 'KASHONGATI' },
                { id: 11836, name: 'KIGARAMA' },
                { id: 11837, name: 'KIHIIRA' },
                { id: 11838, name: 'MUKAGUMIRA' },
                { id: 11839, name: 'MUTAKYENGWA' },
                { id: 11840, name: 'NYAKANENGO' },
                { id: 11841, name: 'NYAMASIIZI' },
                { id: 11842, name: 'NYARUMBYA  A' },
                { id: 11843, name: 'NYARUMBYA  B' },
              ],
            },
            {
              id: 1856,
              name: 'SHEBEYA',
              villages: [
                { id: 11844, name: 'BUGOMORA' },
                { id: 11845, name: 'HATAABA' },
                { id: 11846, name: 'IKUMBA' },
                { id: 11847, name: 'KATOJO' },
                { id: 11848, name: 'MUKASHEKYE' },
                { id: 11849, name: 'MUKASIRU' },
                { id: 11850, name: 'MUKISA' },
                { id: 11851, name: 'MUZIRANTE' },
                { id: 11852, name: 'NYABIRIGITA' },
                { id: 11853, name: 'NYAKABUNGO' },
                { id: 11854, name: 'NYAKATARE' },
                { id: 11855, name: 'NYAMITOOMA' },
                { id: 11856, name: 'RUSYANGA' },
                { id: 11857, name: 'RWONDO' },
              ],
            },
          ],
        },
        {
          id: 414,
          name: 'HAMURWA TOWN COUNCIL',
          parishes: [
            {
              id: 1857,
              name: 'HAMURWA WARD',
              villages: [
                { id: 11858, name: 'HAMURWA' },
                { id: 11859, name: 'NYAKIHANGA' },
              ],
            },
            {
              id: 1858,
              name: 'KANYABITARA WARD',
              villages: [
                { id: 11860, name: 'KANYABITARA' },
                { id: 11861, name: 'NYARUTEIJA' },
              ],
            },
            {
              id: 1859,
              name: 'KARUKARA WARD',
              villages: [
                { id: 11862, name: 'KARUKARA' },
                { id: 11863, name: 'RWARA' },
              ],
            },
            {
              id: 1860,
              name: 'NANGARO WARD',
              villages: [
                { id: 11864, name: 'HABUSINDE' },
                { id: 11865, name: 'NANGARO' },
              ],
            },
          ],
        },
        {
          id: 415,
          name: 'NYAMWEERU',
          parishes: [
            {
              id: 1863,
              name: 'BIGUNGIRO',
              villages: [
                { id: 11892, name: 'IKAMIRO' },
                { id: 11893, name: 'KAGOYE' },
                { id: 11891, name: 'KEIRU' },
                { id: 11896, name: 'NYAKABINGO' },
                { id: 11890, name: 'NYAMIYAGA' },
                { id: 11894, name: 'RWAKARUMA' },
                { id: 11895, name: 'RWAMUZUKA' },
              ],
            },
            {
              id: 1864,
              name: 'BWAYU',
              villages: [
                { id: 11899, name: 'BWAYU' },
                { id: 11897, name: 'KAGUGO' },
                { id: 11900, name: 'MARONKO' },
                { id: 11901, name: 'RUGOMA' },
                { id: 11902, name: 'RUJANJARA' },
                { id: 11898, name: 'RWABUHINGWA' },
                { id: 11903, name: 'RWABUSINGO' },
                { id: 11904, name: 'RWANYANGABO' },
              ],
            },
            {
              id: 1861,
              name: 'KACEENAGA',
              villages: [
                { id: 11869, name: 'HAKISHENYI' },
                { id: 11872, name: 'KACEENAGA' },
                { id: 11871, name: 'KAGOROGORO' },
                { id: 11873, name: 'KARUBANDA' },
                { id: 11874, name: 'KEITANKOMBE' },
                { id: 11876, name: 'KOBUSINDE' },
                { id: 11877, name: 'KYABAKAZI' },
                { id: 11866, name: 'MIRIINZI' },
                { id: 11868, name: 'MUSHUNGA' },
                { id: 11867, name: 'NYAKAHITA' },
                { id: 11875, name: 'NYAMENGO' },
                { id: 11870, name: 'RWEFURWE' },
              ],
            },
            {
              id: 1866,
              name: 'KYOKYEZO',
              villages: [
                { id: 11916, name: 'BUTAMBI' },
                { id: 11917, name: 'BUTATURWA' },
                { id: 11923, name: 'KASHAMBYA' },
                { id: 11919, name: 'KIRWA' },
                { id: 11918, name: 'KITENGURE' },
                { id: 11924, name: 'KYOKYEZO' },
                { id: 11920, name: 'MUTAABA' },
                { id: 11925, name: 'NYAMWIRIMA' },
                { id: 11921, name: 'RWARUCENCUKA' },
                { id: 11922, name: 'RWENKUBA' },
              ],
            },
            {
              id: 1862,
              name: 'NANGARA',
              villages: [
                { id: 11878, name: 'BURAMBO' },
                { id: 11879, name: 'BUTOBORE' },
                { id: 11882, name: 'KAGAANA' },
                { id: 11884, name: 'KAKARISA' },
                { id: 11881, name: 'KANYANKWANZI' },
                { id: 11880, name: 'KAZINDIRO' },
                { id: 11885, name: 'KIGONGI' },
                { id: 11886, name: 'KIHENGAMO' },
                { id: 11887, name: 'KIHORONGWA' },
                { id: 11883, name: 'MIRINDI' },
                { id: 11888, name: 'MUSHONGATI' },
                { id: 11889, name: 'RUSHAKI' },
              ],
            },
            {
              id: 1865,
              name: 'NYAMWERU',
              villages: [
                { id: 11911, name: 'BWINDI' },
                { id: 11907, name: 'BWINDI T.C' },
                { id: 11908, name: 'IKORE' },
                { id: 11909, name: 'KIHENGAMO' },
                { id: 11910, name: 'KITONKORI' },
                { id: 11906, name: 'MOGONGO' },
                { id: 11912, name: 'NYAKASAAZI' },
                { id: 11913, name: 'NYAMWERU' },
                { id: 11905, name: 'RWABANYERERE' },
                { id: 11914, name: 'RWAMUGASHA' },
                { id: 11915, name: 'RWASHUNJU' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 64,
      name: 'RUBANDA COUNTY WEST',
      sub_counties: [
        {
          id: 416,
          name: 'BUFUNDI',
          parishes: [
            {
              id: 1867,
              name: 'KACERERE',
              villages: [
                { id: 11926, name: 'BUGANDARO' },
                { id: 11927, name: 'BUNIGA' },
                { id: 11928, name: 'KACERERE' },
                { id: 11929, name: 'KAGUGO' },
                { id: 11930, name: 'KASHAMBYA' },
                { id: 11931, name: 'KATUNGU' },
                { id: 11932, name: 'KIBARA' },
                { id: 11933, name: 'KIRURUMA' },
                { id: 11934, name: 'KIRWA' },
                { id: 11935, name: 'KITWEGO' },
                { id: 11936, name: 'MUKITOJO' },
                { id: 11937, name: 'MURUGARAMA' },
                { id: 11938, name: 'NYAMATEMBE' },
                { id: 11939, name: 'NYARUSHIJA' },
                { id: 11940, name: 'QUARTERS  A' },
                { id: 11941, name: 'QUARTERS  B' },
                { id: 11942, name: 'RUTEGYENGYERA' },
                { id: 11943, name: 'RUTOOMA' },
                { id: 11944, name: 'RWAKARORO' },
              ],
            },
            {
              id: 1868,
              name: 'KAGUNGA',
              villages: [
                { id: 11945, name: 'BUGANDARO' },
                { id: 11946, name: 'BUGARA' },
                { id: 11947, name: 'BUNAGANA' },
                { id: 11948, name: 'BUSHAMBARA' },
                { id: 11949, name: 'BUSHARA' },
                { id: 11950, name: 'BUTAHWA' },
                { id: 11951, name: 'BWAMBARI' },
                { id: 11952, name: 'HABUHINGA' },
                { id: 11953, name: 'KAGUNGA' },
                { id: 11954, name: 'KIBARE' },
                { id: 11955, name: 'KIGARYA' },
                { id: 11956, name: 'KIRIBA' },
                { id: 11957, name: 'KIRWA' },
                { id: 11958, name: 'MUMPARO' },
                { id: 11959, name: 'MUTAABA' },
                { id: 11960, name: 'MUZIKU' },
                { id: 11961, name: 'RUHUNGU' },
                { id: 11962, name: 'RUKORE' },
              ],
            },
            {
              id: 1869,
              name: 'KASHAASHA - BUFUNDI',
              villages: [
                { id: 11963, name: 'BUHANYURA' },
                { id: 11964, name: 'KAGARI' },
                { id: 11965, name: 'KIRIBA' },
                { id: 11966, name: 'KIRIMBI' },
                { id: 11967, name: 'KISENYI' },
                { id: 11968, name: 'KITOOMA' },
                { id: 11969, name: 'MURAGO' },
                { id: 11970, name: 'MURANDAMO' },
                { id: 11971, name: 'MUSHANJE' },
                { id: 11972, name: 'MUSHONGATI' },
                { id: 11973, name: 'NYAKABUNGO' },
                { id: 11974, name: 'RYAKASHARA' },
              ],
            },
            {
              id: 1870,
              name: 'KISHANJE',
              villages: [
                { id: 11975, name: 'BUGOMORA' },
                { id: 11976, name: 'HABUHINGA' },
                { id: 11977, name: 'KAMIHUNGYE' },
                { id: 11978, name: 'KASHONGATI' },
                { id: 11979, name: 'KIGUNGUZO' },
                { id: 11980, name: 'KIJAGI' },
                { id: 11981, name: 'KINYAMI' },
                { id: 11982, name: 'KISHANJE' },
                { id: 11983, name: 'KISHANJE T/C' },
                { id: 11984, name: 'MUKO' },
                { id: 11985, name: 'NDASIIRE' },
                { id: 11986, name: 'NYARURAMBI  I' },
                { id: 11987, name: 'NYARURAMBI(II)' },
                { id: 11988, name: 'RUSHAYU' },
                { id: 11989, name: 'RWABAHUNDAME' },
                { id: 11990, name: 'SHEBEYA  I' },
                { id: 11991, name: 'SHEBEYA  II' },
              ],
            },
            {
              id: 1871,
              name: 'MUGYERA',
              villages: [
                { id: 11992, name: 'BUSHURE' },
                { id: 11993, name: 'BUTUSI' },
                { id: 11994, name: 'KASHAMBYA' },
                { id: 11995, name: 'KITABUGIKA' },
                { id: 11996, name: 'MURANDI' },
                { id: 11997, name: 'MURUBANGYE' },
                { id: 11998, name: 'MURUHINGA' },
                { id: 11999, name: 'MUSHEBEYA' },
                { id: 12000, name: 'MUSIRWE' },
                { id: 12001, name: 'NYAMICUCU' },
                { id: 12002, name: 'RWASEYEZI' },
              ],
            },
          ],
        },
        {
          id: 417,
          name: 'IKUMBA',
          parishes: [
            {
              id: 1872,
              name: 'KASHASHA/IKUMBA',
              villages: [
                { id: 12003, name: 'IHUNGA' },
                { id: 12004, name: 'KAGOGO' },
                { id: 12005, name: 'KARONDO' },
                { id: 12006, name: 'KASHASHA' },
                { id: 12007, name: 'KATOJO' },
                { id: 12008, name: 'KIRIBA  A' },
                { id: 12009, name: 'KIRIBA  B' },
                { id: 12010, name: 'KITAHURIRA' },
                { id: 12012, name: 'MASHOHO' },
                { id: 12013, name: 'MURUBAYA' },
                { id: 12014, name: 'MWEFUZO' },
                { id: 12011, name: 'NDEEGO' },
              ],
            },
            {
              id: 1873,
              name: 'MUSHANJE',
              villages: [
                { id: 12015, name: 'BIGANDU' },
                { id: 12016, name: 'KIGUMIRA' },
                { id: 12017, name: 'KINYUNGU' },
                { id: 12020, name: 'KITAGATA' },
                { id: 12018, name: 'MUKIBUNGO' },
                { id: 12019, name: 'MUKIHITA' },
                { id: 12021, name: 'NYAKISHENYI' },
                { id: 12022, name: 'RWABUREGYEYA' },
              ],
            },
            {
              id: 1874,
              name: 'NYAMABARE',
              villages: [
                { id: 12023, name: 'BUREMBA' },
                { id: 12024, name: 'KACWAMUHORO' },
                { id: 12025, name: 'KAMUHOKO' },
                { id: 12026, name: 'KANTOORA' },
                { id: 12027, name: 'KASHURE' },
                { id: 12028, name: 'KIGARAMA' },
                { id: 12029, name: 'KIRINGA' },
                { id: 12030, name: 'MUKIRWA' },
                { id: 12034, name: 'MWIZINGA' },
                { id: 12031, name: 'NYAKAGOROGORO' },
                { id: 12032, name: 'NYAMABALE' },
                { id: 12033, name: 'NYARUGARAGARA' },
                { id: 12035, name: 'RWAMAHINGURA' },
              ],
            },
            { id: 1875, name: 'NYARUHANGA', villages: [{ id: 12036, name: 'NTARAGA' }] },
          ],
        },
        {
          id: 418,
          name: 'MUKO',
          parishes: [
            {
              id: 1876,
              name: 'BUTARE',
              villages: [
                { id: 12037, name: 'BISHAKI' },
                { id: 12038, name: 'BUGARAMA' },
                { id: 12039, name: 'HABUTOBERE' },
                { id: 12041, name: 'HAMUTORA' },
                { id: 12042, name: 'IGABIRO' },
                { id: 12040, name: 'KAGOROGORO' },
                { id: 12043, name: 'MUBYEZA' },
                { id: 12044, name: 'MUFUMBA' },
                { id: 12045, name: 'MUKIBUNGO' },
                { id: 12046, name: 'MURUKORO' },
                { id: 12047, name: 'RUREMBO' },
                { id: 12048, name: 'RWAMIGYENDEZO' },
              ],
            },
            {
              id: 1877,
              name: 'IKAMIRO',
              villages: [
                { id: 12049, name: 'BIGYEEGYE' },
                { id: 12050, name: 'HABUHINGA' },
                { id: 12051, name: 'KARAMBO' },
                { id: 12052, name: 'KATEMBE' },
                { id: 12053, name: 'KIRURUMA' },
                { id: 12054, name: 'MATAKARA' },
                { id: 12055, name: 'NYARURAMBI' },
                { id: 12056, name: 'RWABURINDI' },
                { id: 12057, name: 'RWAMAHANO' },
              ],
            },
            {
              id: 1880,
              name: 'KAARA',
              villages: [
                { id: 12077, name: 'BISIIZI' },
                { id: 12078, name: 'BUTABONANA' },
                { id: 12080, name: 'KABAYA' },
                { id: 12081, name: 'KABINDI' },
                { id: 12082, name: 'KAKANGAGA' },
                { id: 12083, name: 'KATASYA' },
                { id: 12084, name: 'KATEETE' },
                { id: 12085, name: 'KIBUNGO' },
                { id: 12086, name: 'KIVUNGA' },
                { id: 12087, name: 'MUSHUNGA' },
                { id: 12088, name: 'NSHANJARE' },
                { id: 12089, name: 'RUSHEBEYA' },
                { id: 12090, name: 'RWABURARO' },
                { id: 12091, name: 'RWAKAMU' },
                { id: 12092, name: 'RWAMURINDWA' },
                { id: 12079, name: 'RYAMIHANDA' },
              ],
            },
            {
              id: 1878,
              name: 'KABERE',
              villages: [
                { id: 12058, name: 'HAMUKAKA' },
                { id: 12059, name: 'KANYAMATEMBE' },
                { id: 12061, name: 'KARENGYERE' },
                { id: 12060, name: 'KAYORERO' },
                { id: 12062, name: 'MUKIBAYA' },
                { id: 12063, name: 'NYAKATOOMA' },
              ],
            },
            {
              id: 1879,
              name: 'KARENGYERE',
              villages: [
                { id: 12064, name: 'HAMUKO' },
                { id: 12065, name: 'IHIMBI' },
                { id: 12066, name: 'KAGANO' },
                { id: 12067, name: 'KARENGYERE T/C' },
                { id: 12068, name: 'KASHAMBYA' },
                { id: 12069, name: 'KIBUNGO' },
                { id: 12070, name: 'MUKO HILL' },
                { id: 12071, name: 'MURUKORO' },
                { id: 12072, name: 'NYAMIYAGA' },
                { id: 12073, name: 'RUGARAMBIRO' },
                { id: 12074, name: 'RUSHEKYE  A' },
                { id: 12075, name: 'RUSHEKYE  B' },
                { id: 12076, name: 'RWAKAGURUSI' },
              ],
            },
            {
              id: 1881,
              name: 'KYENYI',
              villages: [
                { id: 12093, name: 'BURAMBIRA' },
                { id: 12094, name: 'HAMUKAAKA' },
                { id: 12095, name: 'KABISHA' },
                { id: 12096, name: 'KYAFURWE' },
                { id: 12097, name: 'MUNGARA' },
                { id: 12098, name: 'RWAKIRANGAMA' },
              ],
            },
            {
              id: 1882,
              name: 'NYARURAMBI',
              villages: [
                { id: 12099, name: 'BICERERE' },
                { id: 12100, name: 'BUGUNGA' },
                { id: 12101, name: 'KAGOYE' },
                { id: 12102, name: 'RUSHAMBYA' },
                { id: 12103, name: 'RUSHUNGA' },
                { id: 12104, name: 'RWAMABARE' },
                { id: 12105, name: 'RWAMUYOORA' },
                { id: 12106, name: 'RWARUBAYA' },
              ],
            },
          ],
        },
        {
          id: 420,
          name: 'RUBANDA TOWN COUNCIL',
          parishes: [
            {
              id: 1889,
              name: 'KIGYEYO WARD',
              villages: [
                { id: 12142, name: 'BUSENZI' },
                { id: 12143, name: 'BWEGYERERE' },
                { id: 12144, name: 'IBIMBYA' },
                { id: 12145, name: 'KASHARA' },
                { id: 12148, name: 'KIFURUGUTU' },
                { id: 12146, name: 'KIGYEYO' },
                { id: 12147, name: 'MIVUNE' },
                { id: 12149, name: 'MUJA' },
              ],
            },
            {
              id: 1888,
              name: 'NYAKABUNGO WARD',
              villages: [
                { id: 12135, name: 'BUGARIKA' },
                { id: 12137, name: 'KISHANJE' },
                { id: 12138, name: 'MAREJU' },
                { id: 12139, name: 'MUROLE A' },
                { id: 12141, name: 'MUROLE B' },
                { id: 12136, name: 'NYAKABUNGO' },
                { id: 12140, name: 'NYAMIYAGA' },
              ],
            },
            {
              id: 1891,
              name: 'NYARUHANGA WARD',
              villages: [
                { id: 12157, name: 'KAGUNGA' },
                { id: 12164, name: 'KANDIHE' },
                { id: 12158, name: 'KYANAMIRA' },
                { id: 12159, name: 'MUKASHEKYE' },
                { id: 12160, name: 'MUKATOMA' },
                { id: 12161, name: 'MUKITOJO' },
                { id: 12162, name: 'MUMPARO' },
                { id: 12165, name: 'NYARUGARAMA' },
                { id: 12163, name: 'RURENGYERE' },
              ],
            },
            {
              id: 1890,
              name: 'NYARURAMBI WARD',
              villages: [
                { id: 12151, name: 'HAMUMBA' },
                { id: 12152, name: 'KABIRIZI' },
                { id: 12150, name: 'KAMUSERWA' },
                { id: 12153, name: 'KANYAMATEMBE' },
                { id: 12154, name: 'KATASYA' },
                { id: 12155, name: 'MURAMBO' },
                { id: 12156, name: 'RUTOGA' },
              ],
            },
          ],
        },
        {
          id: 419,
          name: 'RUHIJA',
          parishes: [
            {
              id: 1883,
              name: 'BUHUMURIRO',
              villages: [
                { id: 12107, name: 'BUGONGI' },
                { id: 12108, name: 'BUZANIRO' },
                { id: 12109, name: 'KAGANDE' },
                { id: 12111, name: 'MBURAMEIZI' },
                { id: 12110, name: 'NYABIHA' },
              ],
            },
            {
              id: 1884,
              name: 'KASHEKYERA',
              villages: [
                { id: 12116, name: 'BITANWA' },
                { id: 12112, name: 'INYWERO' },
                { id: 12114, name: 'KITAABA' },
                { id: 12115, name: 'KITARE' },
                { id: 12117, name: 'KYOGO' },
                { id: 12113, name: 'NYAKABUNGO' },
              ],
            },
            {
              id: 1885,
              name: 'KITOJO',
              villages: [
                { id: 12118, name: 'BISHAYU' },
                { id: 12119, name: 'KATOOMA' },
                { id: 12120, name: 'MUSHASHA' },
                { id: 12121, name: 'NKUKURU' },
                { id: 12122, name: 'RWESHANZIRO' },
              ],
            },
            {
              id: 1886,
              name: 'KIYEBE',
              villages: [
                { id: 12123, name: 'KABERE' },
                { id: 12124, name: 'KIYEBE' },
                { id: 12125, name: 'MATAKA' },
                { id: 12127, name: 'MUGURANTE' },
                { id: 12126, name: 'NYAKARANGA' },
                { id: 12128, name: 'RUTOOMA' },
              ],
            },
            {
              id: 1887,
              name: 'NTUNGAMO',
              villages: [
                { id: 12129, name: 'KASHONGATI' },
                { id: 12130, name: 'KINYOOGO' },
                { id: 12132, name: 'KYEITOKWA' },
                { id: 12131, name: 'NTUNGAMO' },
                { id: 12134, name: 'RUGANDU' },
                { id: 12133, name: 'RUGYEYO' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
