import { District } from '../types';

export default <District>{
  id: 24,
  name: 'RUBIRIZI',
  counties: [
    {
      id: 55,
      name: 'BUNYARUGURU COUNTY',
      sub_counties: [
        {
          id: 343,
          name: 'KATUNGURU',
          parishes: [
            {
              id: 1549,
              name: 'KASHAKA',
              villages: [
                { id: 10177, name: 'KIMANVU I' },
                { id: 10178, name: 'KIMANVU II' },
                { id: 10179, name: 'NSINGERA I' },
                { id: 10180, name: 'NSINGERA II' },
              ],
            },
            {
              id: 1550,
              name: 'KATUNGURU',
              villages: [
                { id: 10181, name: 'KIGABO' },
                { id: 10182, name: 'KYANGABUKAMA' },
              ],
            },
            {
              id: 1551,
              name: 'KAZINGA',
              villages: [
                { id: 10183, name: 'KAGERA' },
                { id: 10184, name: 'KANOMBE' },
              ],
            },
            {
              id: 1552,
              name: 'KISHENYI',
              villages: [
                { id: 10185, name: 'KARAMBI' },
                { id: 10186, name: 'NYAMWERU' },
              ],
            },
          ],
        },
        {
          id: 344,
          name: 'KICHWAMBA',
          parishes: [
            {
              id: 1555,
              name: 'KATARA',
              villages: [
                { id: 10207, name: 'KATAARA I' },
                { id: 10208, name: 'KATAARA II' },
                { id: 10209, name: 'KATAARA III' },
                { id: 10206, name: 'KYANYONZA' },
                { id: 10210, name: 'KYARUTAKOBA I' },
                { id: 10211, name: 'KYARUTAKOBA II' },
              ],
            },
            {
              id: 1553,
              name: 'KICHWAMBA',
              villages: [
                { id: 10187, name: 'KYAMBUZI A' },
                { id: 10188, name: 'KYAMBUZI B' },
                { id: 10189, name: 'KYANSAMA A' },
                { id: 10190, name: 'KYANSAMA B' },
                { id: 10191, name: 'MIRAMBI A' },
                { id: 10192, name: 'MIRAMBI B' },
                { id: 10193, name: 'NYABUBAARE I' },
              ],
            },
            {
              id: 1556,
              name: 'KYAMBURA',
              villages: [
                { id: 10213, name: 'KAGANDO A' },
                { id: 10214, name: 'KAGANDO B' },
                { id: 10215, name: 'KYAMBURA A' },
                { id: 10216, name: 'KYAMBURA B' },
                { id: 10212, name: 'KYAMBURA C' },
                { id: 10217, name: 'OMUMASAKA A' },
                { id: 10218, name: 'OMUMASAKA B' },
              ],
            },
            {
              id: 1557,
              name: 'NYAKASOZI',
              villages: [
                { id: 10219, name: 'BUSONGA IA' },
                { id: 10220, name: 'BUSONGA IB' },
                { id: 10221, name: 'BUSONGA II A' },
                { id: 10222, name: 'BUSONGA II B' },
                { id: 10224, name: 'NYABUBARE II A' },
                { id: 10223, name: 'NYABUBARE II B' },
                { id: 10225, name: 'NYAKASOZI A' },
                { id: 10226, name: 'NYAKASOZI B' },
              ],
            },
            {
              id: 1554,
              name: 'RUMURI',
              villages: [
                { id: 10194, name: 'BUHINGO I' },
                { id: 10195, name: 'BUHINGO II' },
                { id: 10196, name: 'BUHINGO III' },
                { id: 10197, name: 'KYANKWANZI' },
                { id: 10198, name: 'KYARUGANDA I' },
                { id: 10199, name: 'KYARUGANDA II' },
                { id: 10200, name: 'NYARUHARO I' },
                { id: 10201, name: 'NYARUHARO II' },
                { id: 10202, name: 'RUMURI I' },
                { id: 10203, name: 'RUMURI II' },
                { id: 10204, name: 'RWANDARO I' },
                { id: 10205, name: 'RWANDARO II' },
              ],
            },
          ],
        },
        {
          id: 346,
          name: 'MAGAMBO',
          parishes: [
            {
              id: 1568,
              name: 'BUGAYA',
              villages: [
                { id: 10276, name: 'BUGAYA I' },
                { id: 10277, name: 'BUGAYA II' },
                { id: 10278, name: 'BUSONGA II' },
                { id: 10279, name: 'KIGABIRO' },
                { id: 10280, name: 'KYEEMA' },
                { id: 10281, name: 'RUKIIZI' },
              ],
            },
            {
              id: 1565,
              name: 'BUTOHA',
              villages: [
                { id: 10261, name: 'BUSONGA' },
                { id: 10262, name: 'BUTOHA I' },
                { id: 10263, name: 'BUTOHA II' },
                { id: 10264, name: 'KANYARA' },
                { id: 10265, name: 'NYAKIHANDA' },
                { id: 10266, name: 'NYANGOROGORO I' },
                { id: 10267, name: 'NYANGOROGORO II' },
              ],
            },
            {
              id: 1566,
              name: 'MAGAMBO',
              villages: [
                { id: 10268, name: 'KYABIKONKO' },
                { id: 10269, name: 'NJUGUTO' },
                { id: 10270, name: 'NYAKAHAAMA' },
                { id: 10271, name: 'RYEKIBAGANE I' },
                { id: 10272, name: 'RYEKIBAGANE II' },
              ],
            },
            {
              id: 1569,
              name: 'RUBIRIZI',
              villages: [
                { id: 10282, name: 'KASARARA II' },
                { id: 10283, name: 'KIJURUGO' },
              ],
            },
            {
              id: 1567,
              name: 'RUGAZI',
              villages: [
                { id: 10273, name: 'KYAMBOGO' },
                { id: 10274, name: 'NYAKATUNGA' },
                { id: 10275, name: 'NYAKEIGA' },
              ],
            },
          ],
        },
        {
          id: 342,
          name: 'RUBIRIZI TOWN COUNCIL',
          parishes: [
            {
              id: 1545,
              name: 'KABETE WARD',
              villages: [
                { id: 10163, name: 'NDEKYE II' },
                { id: 10164, name: 'RYERU II' },
                { id: 10165, name: 'RYERU III' },
              ],
            },
            {
              id: 1546,
              name: 'KASARARA WARD',
              villages: [
                { id: 10166, name: 'KASARARA I' },
                { id: 10168, name: 'KASUNGU' },
                { id: 10167, name: 'NYAKASHARU II' },
                { id: 10169, name: 'RUBIRIZI' },
              ],
            },
            {
              id: 1547,
              name: 'NDEKYE WARD',
              villages: [
                { id: 10171, name: 'KIKUBA' },
                { id: 10170, name: 'NDEKYE III' },
                { id: 10172, name: 'RYERU I' },
              ],
            },
            {
              id: 1548,
              name: 'NYAKASHARU WARD',
              villages: [
                { id: 10173, name: 'BUHERA CENTRAL' },
                { id: 10175, name: 'KYAKABUNDA' },
                { id: 10174, name: 'NYAKASHARU I' },
                { id: 10176, name: 'RUGAZI' },
              ],
            },
          ],
        },
        {
          id: 347,
          name: 'RUTOTO',
          parishes: [
            {
              id: 1572,
              name: 'BURURUMA',
              villages: [
                { id: 10295, name: 'BURURUMA' },
                { id: 10296, name: 'KAGYEZI' },
                { id: 10297, name: 'RURAMA' },
                { id: 10298, name: 'RYEMONDO' },
              ],
            },
            {
              id: 1573,
              name: 'KASHENYI',
              villages: [
                { id: 10300, name: 'KANYAMBIRIRI II' },
                { id: 10301, name: 'KASHENYI' },
                { id: 10302, name: 'KINOKO A' },
                { id: 10299, name: 'KINOKO B' },
              ],
            },
            {
              id: 1570,
              name: 'NDANGARO',
              villages: [
                { id: 10285, name: 'KANTUNGU' },
                { id: 10284, name: 'KANYAMBIRIRI I' },
                { id: 10286, name: 'KYANIKA I' },
                { id: 10287, name: 'KYANIKA II' },
                { id: 10288, name: 'NKOMBE I' },
                { id: 10289, name: 'NKOMBE II' },
              ],
            },
            {
              id: 1571,
              name: 'NYABUBARE',
              villages: [
                { id: 10290, name: 'BIREHE I' },
                { id: 10294, name: 'BIREHE II' },
                { id: 10291, name: 'BUKYABA' },
                { id: 10292, name: 'KYANIKA' },
                { id: 10293, name: 'RWENTUHA' },
              ],
            },
            {
              id: 1574,
              name: 'RWEMITAGU',
              villages: [
                { id: 10303, name: 'KYAMABARE' },
                { id: 10304, name: 'NYABWINA' },
                { id: 10305, name: 'RWEMITAGU' },
                { id: 10306, name: 'RWENKOBE' },
              ],
            },
          ],
        },
        {
          id: 345,
          name: 'RYERU',
          parishes: [
            {
              id: 1558,
              name: 'BUZENGA',
              villages: [
                { id: 10228, name: 'BUZENGA  II' },
                { id: 10227, name: 'BUZENGA I' },
                { id: 10231, name: 'KABIRIZI I' },
                { id: 10232, name: 'KABIRIZI II' },
                { id: 10229, name: 'KAMACUMU I' },
                { id: 10230, name: 'KAMACUMU II' },
                { id: 10233, name: 'KYEIBUMBA I' },
                { id: 10234, name: 'KYEIBUMBA II' },
              ],
            },
            {
              id: 1562,
              name: 'MUBANDA',
              villages: [
                { id: 10248, name: 'MUBANDA A' },
                { id: 10249, name: 'MUBANDA B' },
                { id: 10250, name: 'MUBANDA C' },
                { id: 10251, name: 'MUBANDA D' },
                { id: 10252, name: 'NYAKAKAAKA A' },
              ],
            },
            {
              id: 1563,
              name: 'MUGOGO',
              villages: [
                { id: 10253, name: 'MUGOGO I' },
                { id: 10254, name: 'MUGOGO II' },
                { id: 10255, name: 'MUGOGO III' },
                { id: 10256, name: 'NYAMISHEKYE' },
              ],
            },
            {
              id: 1559,
              name: 'MUSHUMBA',
              villages: [
                { id: 10235, name: 'BIREHE' },
                { id: 10236, name: 'BUSINGO' },
                { id: 10237, name: 'BUTEEZI' },
                { id: 10238, name: 'NYAKAKAAKA B' },
                { id: 10239, name: 'RUGYENDA' },
              ],
            },
            {
              id: 1564,
              name: 'NDANGARA',
              villages: [
                { id: 10257, name: 'KABUKWIRI' },
                { id: 10258, name: 'KARAGARA' },
                { id: 10259, name: 'NDANGARA A' },
                { id: 10260, name: 'NDANGARA B' },
              ],
            },
            {
              id: 1560,
              name: 'NDEKYE',
              villages: [
                { id: 10240, name: 'KASOGA' },
                { id: 10241, name: 'NDEKYE I' },
                { id: 10242, name: 'NYAKAKAAKA' },
              ],
            },
            {
              id: 1561,
              name: 'NYAKIYANJA',
              villages: [
                { id: 10243, name: 'NKONDO A' },
                { id: 10244, name: 'NKONDO B' },
                { id: 10245, name: 'NYAKIYANJA A' },
                { id: 10246, name: 'NYAKIYANJA B' },
                { id: 10247, name: 'NYAKIYANJA C' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 56,
      name: 'KATERERA COUNTY',
      sub_counties: [
        {
          id: 349,
          name: 'KATANDA',
          parishes: [
            {
              id: 1580,
              name: 'KATANDA',
              villages: [
                { id: 10348, name: 'KAKINDO A' },
                { id: 10349, name: 'KAKINDO B' },
                { id: 10343, name: 'KAKINDO C' },
                { id: 10344, name: 'KANYANTANGA' },
                { id: 10350, name: 'KATAKONDWA' },
                { id: 10345, name: 'KATANDA I' },
                { id: 10346, name: 'KATANDA II' },
                { id: 10351, name: 'KATANDA III' },
                { id: 10347, name: 'NYANGOROGORO A' },
                { id: 10352, name: 'NYANGOROGORO B' },
              ],
            },
            {
              id: 1582,
              name: 'KYANKARANGA',
              villages: [
                { id: 10360, name: 'KATOKORI  I' },
                { id: 10361, name: 'KATOKORI  II' },
                { id: 10362, name: 'KIKOMA I' },
                { id: 10359, name: 'KIKOMA II' },
                { id: 10363, name: 'KYANKARANGA I' },
                { id: 10364, name: 'KYANKARANGA II' },
                { id: 10365, name: 'KYANKARANGA III' },
              ],
            },
            {
              id: 1579,
              name: 'MUGYERA',
              villages: [
                { id: 10337, name: 'KANYANSHANDE A' },
                { id: 10342, name: 'KANYANSHANDE B' },
                { id: 10339, name: 'KISIITA A' },
                { id: 10336, name: 'KISIITA B' },
                { id: 10340, name: 'NYAKATUNGA I' },
                { id: 10341, name: 'NYAKATUNGA II' },
                { id: 10338, name: 'RYAMATUMBA III' },
              ],
            },
            {
              id: 1581,
              name: 'MUNYONYI',
              villages: [
                { id: 10353, name: 'MIKONEBIRI I' },
                { id: 10357, name: 'MIKONEBIRI II' },
                { id: 10354, name: 'MUNYONYI I' },
                { id: 10355, name: 'MUNYONYI II A' },
                { id: 10358, name: 'MUNYONYI II B' },
                { id: 10356, name: 'MUNYONYI V' },
              ],
            },
            {
              id: 1583,
              name: 'NYANDONGO',
              villages: [
                { id: 10366, name: 'KANJENJE' },
                { id: 10369, name: 'MUNYONYI III' },
                { id: 10370, name: 'MUNYONYI IV' },
                { id: 10371, name: 'NYANDONGO I A' },
                { id: 10367, name: 'NYANDONGO I B' },
                { id: 10372, name: 'NYANDONGO II' },
                { id: 10368, name: 'NYANDONGO III' },
              ],
            },
            {
              id: 1584,
              name: 'RYAMATUMBA',
              villages: [
                { id: 10375, name: 'KISHARU I' },
                { id: 10373, name: 'KISHARU II' },
                { id: 10376, name: 'RYAMATUMBA I A' },
                { id: 10378, name: 'RYAMATUMBA I B' },
                { id: 10377, name: 'RYAMATUMBA II A' },
                { id: 10374, name: 'RYAMATUMBA II B' },
              ],
            },
          ],
        },
        {
          id: 348,
          name: 'KATERERA',
          parishes: [
            {
              id: 1575,
              name: 'KATERERA',
              villages: [
                { id: 10307, name: 'KATONYA' },
                { id: 10308, name: 'MBUGA A' },
                { id: 10314, name: 'MBUGA B' },
                { id: 10309, name: 'NYAKAHITA' },
                { id: 10310, name: 'NYAMIRIMA I A' },
                { id: 10315, name: 'NYAMIRIMA I B' },
                { id: 10311, name: 'NYAMIRIMA II' },
                { id: 10312, name: 'NYAMIRIMA III' },
                { id: 10313, name: 'RUKOMA' },
              ],
            },
            {
              id: 1576,
              name: 'MWONGYERA',
              villages: [
                { id: 10316, name: 'IBAMBA' },
                { id: 10323, name: 'KABASHEKYE' },
                { id: 10318, name: 'KAGOROGORO I' },
                { id: 10319, name: 'KAGOROGORO II' },
                { id: 10320, name: 'KAGOROGORO III' },
                { id: 10324, name: 'KEMENGO' },
                { id: 10317, name: 'KIDUBULE' },
                { id: 10325, name: 'KIREMBE' },
                { id: 10321, name: 'MWONGERA I' },
                { id: 10322, name: 'MWONGERA II' },
              ],
            },
            {
              id: 1577,
              name: 'NYAMABARE',
              villages: [
                { id: 62593, name: 'KANYEGARAMIRE' },
                { id: 10326, name: 'KANYUNGU' },
                { id: 10328, name: 'NYAMABARE I' },
                { id: 10329, name: 'NYAMABARE II' },
                { id: 10330, name: 'RWENTOJO II' },
                { id: 10331, name: 'RWENTOJO III' },
                { id: 10327, name: 'WANDEGEYA' },
              ],
            },
            {
              id: 1578,
              name: 'NYAMIRIMA',
              villages: [
                { id: 10332, name: 'NYABUSHABE' },
                { id: 10334, name: 'NYAMIRIMA I' },
                { id: 10335, name: 'NYAMIRIMA II' },
                { id: 10333, name: 'NYAMIRIMA III' },
              ],
            },
          ],
        },
        {
          id: 351,
          name: 'KATERERA TOWN COUNCIL',
          parishes: [
            {
              id: 1590,
              name: 'KACU WARD',
              villages: [
                { id: 10418, name: 'KACU' },
                { id: 10419, name: 'KIZIRA' },
                { id: 10420, name: 'KYAMWIGA' },
              ],
            },
            {
              id: 1593,
              name: 'KATERERA WARD',
              villages: [
                { id: 10428, name: 'KABASEEKE' },
                { id: 10429, name: 'KATERERA I' },
                { id: 10430, name: 'KATERERA II' },
                { id: 10431, name: 'KIKONJO' },
              ],
            },
            {
              id: 1591,
              name: 'MUYENGA WARD',
              villages: [
                { id: 10421, name: 'KACUBA I' },
                { id: 10422, name: 'KACUBA II' },
                { id: 10423, name: 'RWENTOJO I' },
              ],
            },
            {
              id: 1592,
              name: 'NYAKAGYEZI WARD',
              villages: [
                { id: 10424, name: 'KAGUGA' },
                { id: 10425, name: 'MYONYO' },
                { id: 10426, name: 'NYAKAGYEZI I' },
                { id: 10427, name: 'NYAKAGYEZI II' },
              ],
            },
          ],
        },
        {
          id: 352,
          name: 'KIRUGU',
          parishes: [
            {
              id: 1595,
              name: 'KIKUMBO',
              villages: [
                { id: 10436, name: 'KABERENGYE A' },
                { id: 10444, name: 'KABERENGYE B' },
                { id: 10437, name: 'KIKUMBO A' },
                { id: 10443, name: 'KIKUMBO B' },
                { id: 10438, name: 'KIRUGU II A' },
                { id: 10445, name: 'KIRUGU IIB' },
                { id: 10439, name: 'KYEIZOGOMBE' },
                { id: 10440, name: 'NTUNGA A' },
                { id: 10441, name: 'NTUNGA B' },
                { id: 10442, name: 'OMUKABAARE A' },
                { id: 10446, name: 'OMUKABAARE B' },
              ],
            },
            {
              id: 1594,
              name: 'KIRUGU',
              villages: [
                { id: 10432, name: 'KAFURO IA' },
                { id: 10433, name: 'KAFURO IB' },
                { id: 10434, name: 'KAFURO II' },
                { id: 10435, name: 'KIRUGU I A' },
              ],
            },
            {
              id: 1596,
              name: 'KYENZAZA',
              villages: [
                { id: 10447, name: 'KIRUGU I B' },
                { id: 10448, name: 'KYENZAZA IA' },
                { id: 10449, name: 'KYENZAZA IB' },
                { id: 10450, name: 'KYENZAZA II A' },
                { id: 10451, name: 'KYENZAZA II B' },
              ],
            },
            {
              id: 1597,
              name: 'MIRARIKYE',
              villages: [
                { id: 10452, name: 'MIRARIKYE A' },
                { id: 10453, name: 'MIRARIKYE B' },
                { id: 10454, name: 'MIRARIKYE C' },
              ],
            },
          ],
        },
        {
          id: 350,
          name: 'KYABAKARA',
          parishes: [
            {
              id: 1585,
              name: 'KAKARI',
              villages: [
                { id: 10379, name: 'IGOMANDA I A' },
                { id: 10385, name: 'IGOMANDA I B' },
                { id: 10380, name: 'KAKAARI I A' },
                { id: 10386, name: 'KAKAARI I B' },
                { id: 10381, name: 'KAKAARI II A' },
                { id: 10387, name: 'KAKAARI II B' },
                { id: 10382, name: 'NYAKANENGO' },
                { id: 10383, name: 'NYAKARAMBI I' },
                { id: 10388, name: 'NYAKARAMBI II' },
                { id: 10384, name: 'NYARUHANGA' },
              ],
            },
            {
              id: 1586,
              name: 'KYABAKARA',
              villages: [
                { id: 10391, name: 'KAGANDO' },
                { id: 10392, name: 'KATABAGO I' },
                { id: 10393, name: 'KATABAGO II' },
                { id: 10394, name: 'KYENJOJO I' },
                { id: 10389, name: 'KYENJOJO II' },
                { id: 10390, name: 'RWEMICEEKA' },
              ],
            },
            {
              id: 1587,
              name: 'NGORO',
              villages: [
                { id: 10395, name: 'BUTATURWA' },
                { id: 10396, name: 'IGOMANDA II A' },
                { id: 10400, name: 'IGOMANDA II B' },
                { id: 10397, name: 'IGOMANDA III' },
                { id: 10401, name: 'KASIBO' },
                { id: 10398, name: 'NGORO I A' },
                { id: 10402, name: 'NGORO I B' },
                { id: 10399, name: 'NGORO II' },
              ],
            },
            {
              id: 1588,
              name: 'NYABUBARE',
              villages: [
                { id: 10410, name: 'KAGARAMA' },
                { id: 10403, name: 'KATEHE' },
                { id: 10404, name: 'KINONI' },
                { id: 10408, name: 'MUGOMBWA' },
                { id: 10411, name: 'NYABUBARE I' },
                { id: 10405, name: 'NYABUBARE II' },
                { id: 10406, name: 'NYAKAGYERA' },
                { id: 10407, name: 'NYEMEKA' },
                { id: 10409, name: 'RUTONDO' },
              ],
            },
            {
              id: 1589,
              name: 'RUGARAMA',
              villages: [
                { id: 10412, name: 'BWEGIRAGYE' },
                { id: 10413, name: 'KALEMBO' },
                { id: 10414, name: 'NYAMIRAMA' },
                { id: 10415, name: 'RUGARAMA I' },
                { id: 10416, name: 'RUGARAMA II' },
                { id: 10417, name: 'RUSORO' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
