import { District } from '../types';

export default {
  id: 65,
  name: 'RUKUNGIRI',
  counties: [
    {
      id: 154,
      name: 'RUBABO COUNTY',
      sub_counties: [
        {
          id: 948,
          name: 'BUYANJA',
          parishes: [
            {
              id: 4379,
              name: 'BUGYERA',
              villages: [
                { id: 28121, name: 'KAGANDO' },
                { id: 28122, name: 'KATERERO' },
                { id: 28123, name: 'KITOJO CENTRAL' },
                { id: 28124, name: 'NYAKIBUNGO' },
                { id: 28125, name: 'NYAKIJU' },
                { id: 28126, name: 'RUGARAMA' },
                { id: 28127, name: 'RUGOONGO' },
                { id: 28128, name: 'RWERE' },
                { id: 28129, name: 'RWESASI' },
              ],
            },
            {
              id: 4380,
              name: 'KASHESHE',
              villages: [
                { id: 28130, name: 'KAKASIITA' },
                { id: 28131, name: 'KAMUTARINDWA' },
                { id: 28132, name: 'MISHENYI' },
                { id: 28133, name: 'NYARURAMBI' },
                { id: 28134, name: 'NYARUTUNTU' },
                { id: 28135, name: 'RWABACERE' },
                { id: 28136, name: 'RWEKIGYERA' },
                { id: 28137, name: 'RWENSHEKYE' },
              ],
            },
            {
              id: 4381,
              name: 'KYAMAKANDA',
              villages: [
                { id: 28138, name: 'KIHUMURO' },
                { id: 28139, name: 'KITOJO' },
                { id: 28140, name: 'KYASHAMIRE' },
                { id: 28141, name: 'OMUYANJA' },
                { id: 28142, name: 'RUGYENDWA' },
                { id: 28143, name: 'RUKIRI' },
                { id: 28144, name: 'RWAMUHA' },
                { id: 28145, name: 'RWAMUHIMA' },
                { id: 28146, name: "RWOBUSISI 'A'" },
                { id: 28147, name: "RWOBUSISI 'B'" },
              ],
            },
            {
              id: 4382,
              name: 'NYABITEETE',
              villages: [
                { id: 28148, name: 'BUGUMA' },
                { id: 28152, name: 'BUHANDAGAZI' },
                { id: 28149, name: 'KAATA' },
                { id: 28150, name: 'KANOMBE' },
                { id: 28151, name: 'KYESHORO' },
                { id: 28153, name: 'RUSHAKA' },
                { id: 28154, name: 'RWENANURA' },
              ],
            },
            {
              id: 4386,
              name: 'NYAKABUNGO',
              villages: [
                { id: 28184, name: 'KATUNGU' },
                { id: 28185, name: 'KYAATO' },
                { id: 28186, name: 'NYAKACWAMBA' },
                { id: 28187, name: 'NYARUTOOMA' },
                { id: 28188, name: 'RUHAZO' },
                { id: 28189, name: 'RURENGYE' },
                { id: 28190, name: 'RWAMPUGA' },
                { id: 28191, name: 'RWEERE' },
              ],
            },
            {
              id: 4383,
              name: 'NYAKAINA',
              villages: [
                { id: 28155, name: 'KAFUNJO' },
                { id: 28156, name: 'KIBOMBO' },
                { id: 28157, name: 'KIBUNDA' },
                { id: 28158, name: 'KITANDA' },
                { id: 28159, name: 'MBUNDA' },
                { id: 28160, name: 'RWENKURIJO' },
              ],
            },
            {
              id: 4384,
              name: 'RUBANGA',
              villages: [
                { id: 28161, name: 'IBUMBA' },
                { id: 28162, name: 'KABAGAHE' },
                { id: 28163, name: 'KAMISHAYO' },
                { id: 28164, name: 'KARUSHANJE' },
                { id: 28165, name: 'KIHENGAMO' },
                { id: 28166, name: 'KISHARARA' },
                { id: 28167, name: 'KISHONGA  UPPER' },
                { id: 28168, name: 'KISHONGA LOWER' },
                { id: 28169, name: 'KYAMABARE' },
                { id: 28170, name: 'NYAKASHARARA' },
                { id: 28171, name: 'NYARUTARE' },
                { id: 28172, name: 'OMUKABINGO' },
                { id: 28173, name: 'OMUKATOJO' },
                { id: 28174, name: 'RUSHARIRA' },
                { id: 28175, name: 'RWENSHEKYE' },
                { id: 28176, name: 'RWENYANGI' },
              ],
            },
            {
              id: 4385,
              name: 'RWAKIRUNGURA',
              villages: [
                { id: 28177, name: 'KAGARAMA A' },
                { id: 28178, name: 'KAKINGA' },
                { id: 28179, name: 'KATUNGU' },
                { id: 28180, name: 'KISHARARA' },
                { id: 28181, name: 'NYABICENCE' },
                { id: 28182, name: 'NYARURARA' },
                { id: 28183, name: 'RWENTUHA' },
              ],
            },
          ],
        },
        {
          id: 953,
          name: 'BUYANJA TOWN COUNCIL',
          parishes: [
            {
              id: 4415,
              name: 'KATOJO WARD',
              villages: [
                { id: 28499, name: 'KAGARAMA B' },
                { id: 28500, name: 'KATOJO' },
                { id: 28501, name: 'RUBIRIIZI' },
              ],
            },
            {
              id: 4414,
              name: 'KYAMAKANDA WARD',
              villages: [
                { id: 28496, name: "KIZINGA 'A'" },
                { id: 28497, name: "KIZINGA 'B'" },
                { id: 28498, name: 'MATEBE' },
              ],
            },
            {
              id: 4416,
              name: 'NYAKAINA WARD',
              villages: [
                { id: 28504, name: 'BUYANJA TOWN CELL A' },
                { id: 28502, name: 'BUYANJA TOWN CELL B' },
                { id: 28503, name: 'NYAKAINA  CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 949,
          name: 'KEBISONI',
          parishes: [
            {
              id: 4391,
              name: 'GARUBUNDA',
              villages: [
                { id: 28229, name: 'KASHANJE' },
                { id: 28230, name: 'KITENGA' },
                { id: 28231, name: 'NKONGORO' },
              ],
            },
            {
              id: 4387,
              name: 'KARUHEMBE',
              villages: [
                { id: 28192, name: 'KAKANYENYE' },
                { id: 28193, name: 'KANONKO' },
                { id: 28194, name: 'KICHWAMBA' },
                { id: 28195, name: 'KIGANGO' },
                { id: 28196, name: 'KIGUNDA' },
                { id: 28197, name: 'KITYAZA' },
                { id: 28198, name: 'KYAHI' },
                { id: 28199, name: 'MUKAZI' },
                { id: 28200, name: 'NYAKAGONGO' },
                { id: 28201, name: 'NYAKAZINGA' },
              ],
            },
            {
              id: 4389,
              name: 'KIIGIRO',
              villages: [
                { id: 28218, name: 'KABUZOOBA' },
                { id: 28219, name: 'KITOOHA' },
                { id: 28214, name: 'MAKIRO' },
                { id: 28215, name: 'NYAMIGONGO' },
                { id: 28216, name: 'NYAMIJUMBI' },
                { id: 28217, name: 'RWEMIYAGA' },
              ],
            },
            {
              id: 4388,
              name: 'MABANGA',
              villages: [
                { id: 28202, name: 'KAMURINDWA' },
                { id: 28203, name: 'KITOJO' },
                { id: 28204, name: 'KYOBUKYERA' },
                { id: 28205, name: 'KYONDO' },
                { id: 28206, name: 'MAKIRO' },
                { id: 28207, name: 'MUKAYENJE' },
                { id: 28208, name: 'NYAKAGANDO' },
                { id: 28209, name: 'NYAMASHAMBO' },
                { id: 28210, name: 'NYARWANYA' },
                { id: 28211, name: 'RUGOROGORO' },
                { id: 28212, name: 'RUGYENDWA' },
                { id: 28213, name: 'RWEMIYAGA' },
              ],
            },
            {
              id: 4390,
              name: 'NYEIBINGO',
              villages: [
                { id: 28220, name: 'BIKUNGU' },
                { id: 28221, name: 'BUTINDE' },
                { id: 28227, name: 'ITEMBA-IZINGA' },
                { id: 28222, name: 'KAGYEYO' },
                { id: 28223, name: 'KAHANGIRO' },
                { id: 28224, name: 'KATENGA' },
                { id: 28225, name: 'KIBALE' },
                { id: 28226, name: 'MAGOMA' },
                { id: 28228, name: 'NYAMUBOGORE' },
              ],
            },
          ],
        },
        {
          id: 952,
          name: 'KEBISONI TOWN COUNCIL',
          parishes: [
            {
              id: 4413,
              name: 'CENTRAL WARD',
              villages: [
                { id: 28488, name: 'BISHOP RUHINDI  H/S' },
                { id: 28489, name: 'KAKINGA' },
                { id: 28492, name: 'KANYAMUTWE' },
                { id: 28491, name: 'KIBOROGOTA' },
                { id: 28490, name: 'NYAKABARE' },
                { id: 28493, name: 'NYAMAMBO A' },
                { id: 28494, name: 'NYAMAMBO B' },
                { id: 28495, name: 'NYAMPIKYE' },
              ],
            },
            {
              id: 4410,
              name: 'EASTERN WARD',
              villages: [
                { id: 28471, name: 'KABASHAKI' },
                { id: 28470, name: 'KABUSHAGI' },
                { id: 28472, name: 'KARIRE' },
                { id: 28473, name: 'KIGANGO' },
                { id: 28474, name: 'KITOOHA' },
                { id: 28475, name: 'RUBUMBA' },
                { id: 28476, name: 'RWABIGANGURA' },
              ],
            },
            {
              id: 4412,
              name: 'NORTHERN WARD',
              villages: [
                { id: 28487, name: 'ITAANO' },
                { id: 28482, name: 'KANYEGANYEGYE' },
                { id: 28484, name: 'KATUNGU' },
                { id: 28485, name: 'KIBOROGOTA' },
                { id: 28483, name: 'NDAMA-NKAMBA' },
                { id: 28486, name: 'NYAKAGONGO' },
              ],
            },
            {
              id: 4411,
              name: 'SOUHERN WARD',
              villages: [
                { id: 28477, name: "KAKIBAYA  'A'" },
                { id: 28478, name: 'KAKIBAYA  B' },
                { id: 28481, name: 'MUTOJO' },
                { id: 28479, name: 'RUGOMA' },
                { id: 28480, name: 'RWANKOMA' },
              ],
            },
          ],
        },
        {
          id: 950,
          name: 'NYAKISHENYI',
          parishes: [
            {
              id: 4399,
              name: 'BIKONGOZO',
              villages: [
                { id: 28332, name: 'BIKONGOZO' },
                { id: 28333, name: 'BIRAARE' },
                { id: 28334, name: 'BYONGO' },
                { id: 28335, name: 'KABUHOME' },
                { id: 28336, name: 'KARUGAZI' },
                { id: 28337, name: 'KATAATE' },
                { id: 28338, name: 'KAYANJA' },
              ],
            },
            {
              id: 4393,
              name: 'KACENCE',
              villages: [
                { id: 28244, name: 'ITERERO' },
                { id: 28245, name: 'KABABAGI' },
                { id: 28246, name: 'KACENCE' },
                { id: 28247, name: 'KAHARA' },
                { id: 28248, name: 'KINIOGO' },
                { id: 28249, name: 'KINISYA' },
                { id: 28250, name: 'MABINDI' },
                { id: 28251, name: 'NUMBA' },
                { id: 28252, name: 'NYABITEKYERE' },
                { id: 28253, name: 'NYAKISOROZA' },
                { id: 28254, name: 'RUGOMA' },
                { id: 28255, name: 'RWANJERU' },
                { id: 28256, name: 'RWONYO' },
              ],
            },
            {
              id: 4394,
              name: 'KAFUNJO',
              villages: [
                { id: 28257, name: 'BUGANDAZA' },
                { id: 28258, name: 'BUGOMORA' },
                { id: 28259, name: 'KABIJAGA' },
                { id: 28260, name: 'KABUZIGYE' },
                { id: 28261, name: 'KAFUNJO' },
                { id: 28262, name: 'KAGASHA' },
                { id: 28263, name: 'KAGOROGORO' },
                { id: 28264, name: 'KAJUBWE' },
                { id: 28265, name: 'KIJUBWE' },
                { id: 28266, name: 'NYABISHAKI' },
                { id: 28267, name: 'NYAKAKIZI' },
                { id: 28268, name: 'NYAMABARE' },
                { id: 28269, name: 'NYARUZIBA' },
                { id: 28270, name: 'RUGANDO' },
                { id: 28271, name: 'RUGAZI' },
                { id: 28272, name: 'RUTOOMA' },
              ],
            },
            {
              id: 4395,
              name: 'KAHOKO',
              villages: [
                { id: 28273, name: 'BUHUMURIRO' },
                { id: 28274, name: 'KAGYEYO' },
                { id: 28275, name: 'KAMUHOZI' },
                { id: 28276, name: 'KARUKONJO' },
                { id: 28277, name: 'KATUNGU' },
                { id: 28278, name: 'KIBEHO' },
                { id: 28279, name: 'KIGOYI' },
                { id: 28280, name: 'KITEBWE' },
                { id: 28281, name: 'KITUGUNDA' },
                { id: 28282, name: 'NYABISONI' },
                { id: 28283, name: 'NYABUBARE' },
                { id: 28284, name: 'NYAKABARE' },
                { id: 28285, name: 'NYAMIRAMA' },
                { id: 28286, name: 'NYARUHANGA' },
                { id: 28287, name: 'NYARURAMBI' },
                { id: 28288, name: 'RUGASHA' },
                { id: 28289, name: 'RUNYINYA' },
                { id: 28290, name: 'RUTOOMA' },
                { id: 28291, name: 'RWANAMA' },
              ],
            },
            {
              id: 4396,
              name: 'KATONYA',
              villages: [
                { id: 28292, name: 'BUGARAMA' },
                { id: 28293, name: 'BUREBANE' },
                { id: 28294, name: 'KAJUMERA' },
                { id: 28295, name: 'KASHENYI' },
                { id: 28296, name: 'MUGURANTE' },
                { id: 28297, name: 'MUSHUNGA' },
                { id: 28298, name: 'NDYABIHANGA' },
                { id: 28299, name: 'NYAKABALE' },
                { id: 28300, name: 'NYAKABUNGO' },
                { id: 28301, name: 'NYAKASHENYI' },
                { id: 28302, name: 'NYARUBIRA' },
                { id: 28303, name: 'OMUKAJAGIRO' },
                { id: 28304, name: 'RUGARAMA' },
                { id: 28305, name: 'RUHONWA' },
                { id: 28306, name: 'RUJOKA' },
                { id: 28307, name: 'RUTOOMA' },
                { id: 28308, name: 'RWANGURA' },
              ],
            },
            {
              id: 4392,
              name: 'MURAMA',
              villages: [
                { id: 28232, name: 'KABARANGA' },
                { id: 28233, name: 'KAGOROGORO' },
                { id: 28234, name: 'KAHAAMA' },
                { id: 28235, name: 'MUGINA' },
                { id: 28236, name: 'NANGARA' },
                { id: 28237, name: 'NDARAGYI' },
                { id: 28238, name: 'NYABYOOGO' },
                { id: 28239, name: 'NYAMABARE' },
                { id: 28240, name: 'NYARUBARE' },
                { id: 28241, name: 'OMUKATOOMA' },
                { id: 28242, name: 'OMURUTEZO' },
                { id: 28243, name: 'RUSHEBEYA' },
              ],
            },
            {
              id: 4397,
              name: 'NGOMA',
              villages: [
                { id: 28309, name: 'BURERA' },
                { id: 28310, name: 'KABINGO' },
                { id: 28311, name: 'KACENCE' },
                { id: 28312, name: 'KANYABUTAYE' },
                { id: 28313, name: 'KIGARAMA' },
                { id: 28314, name: 'NYABISONI' },
                { id: 28315, name: 'RUHITA' },
                { id: 28316, name: 'RURINDO' },
                { id: 28317, name: 'RWERE' },
              ],
            },
            {
              id: 4400,
              name: 'NYARUGANDO',
              villages: [
                { id: 28339, name: 'BUTARE' },
                { id: 28340, name: 'KEINA' },
                { id: 28341, name: 'KIINA' },
                { id: 28342, name: 'MARASHANIRO' },
                { id: 28343, name: 'NYAMITANGA' },
                { id: 28344, name: 'NYARUBARE' },
                { id: 28345, name: 'NYARUTUNTU' },
                { id: 28346, name: 'RWENGOHA' },
              ],
            },
            {
              id: 4398,
              name: 'RWANYUNDO',
              villages: [
                { id: 28318, name: 'BUBARE' },
                { id: 28319, name: 'BUGAMBA' },
                { id: 28320, name: 'BUGORO' },
                { id: 28321, name: 'KAGAAGA' },
                { id: 28322, name: 'KARUBANDA' },
                { id: 28323, name: 'KYONDO' },
                { id: 28324, name: 'MURAMBI' },
                { id: 28325, name: 'NYAKATOKYE' },
                { id: 28326, name: 'NYAMABARE' },
                { id: 28327, name: 'OMUKAJAGIRO' },
                { id: 28328, name: 'RUGASHA' },
                { id: 28329, name: 'RUTOOMA' },
                { id: 28330, name: 'RWONYO' },
                { id: 28331, name: 'SHOGASHOGA' },
              ],
            },
          ],
        },
        {
          id: 951,
          name: 'NYARUSHANJE',
          parishes: [
            {
              id: 4401,
              name: 'BUNONO',
              villages: [
                { id: 28347, name: 'BUNONO' },
                { id: 28348, name: 'IHAMBIRO' },
                { id: 28349, name: 'IZINGA  I' },
                { id: 28350, name: 'IZINGA  II' },
                { id: 28351, name: 'KARUKAATA CENTRAL' },
                { id: 28352, name: 'KAZINGA' },
                { id: 28353, name: 'KIBISHAMWIKA' },
                { id: 28354, name: 'KICHWAMBA' },
                { id: 28355, name: 'KIGANGO' },
                { id: 28356, name: 'KYETOBOKYEIRE' },
                { id: 28357, name: 'MIGYERETEMBA' },
                { id: 28358, name: 'NYAKABINGO' },
              ],
            },
            {
              id: 4402,
              name: 'BURORA',
              villages: [
                { id: 28359, name: 'KABASHURI' },
                { id: 28360, name: 'KAKIRAGO' },
                { id: 28361, name: 'KINANIRA' },
                { id: 28362, name: 'KYARUHOTORA' },
                { id: 28364, name: 'NYAKAGYERA' },
                { id: 28365, name: "NYAMAKUKURU 'A'" },
                { id: 28366, name: "NYAMAKUKURU 'B'" },
                { id: 28367, name: 'NYAMIRIMA' },
                { id: 28368, name: 'NYARWANYA' },
                { id: 28363, name: 'OMUNKAMBI' },
                { id: 28369, name: 'RWAKIGONA' },
                { id: 28370, name: 'RWEMPANGA' },
                { id: 28371, name: 'RWENCERERE' },
              ],
            },
            {
              id: 4403,
              name: 'BWANGA',
              villages: [
                { id: 28372, name: 'KIGINA' },
                { id: 28373, name: 'KYARUSHONGYERA' },
                { id: 28374, name: 'NYABAKOBORA' },
                { id: 28375, name: 'NYAKAZINGA' },
                { id: 28376, name: 'NYANDIRI' },
                { id: 28377, name: 'NYARUBUMBA' },
                { id: 28378, name: 'NYARUSHOOKO' },
                { id: 28379, name: 'OMUKIBIRIZI' },
                { id: 28380, name: 'RUSOROZA' },
                { id: 28381, name: 'SHENGA' },
                { id: 28382, name: 'SHUMBA' },
              ],
            },
            {
              id: 4404,
              name: 'IBANDA',
              villages: [
                { id: 28383, name: 'IBANDA' },
                { id: 28384, name: 'IKONDERE' },
                { id: 28385, name: 'KABUHEMBA' },
                { id: 28386, name: 'KAGOROGORO' },
                { id: 28387, name: 'KASHARARA' },
                { id: 28388, name: 'KASOONI' },
                { id: 28389, name: 'KAZOOHA' },
                { id: 28391, name: 'KICHWAMBA' },
                { id: 28390, name: 'KICUBANYUNGU' },
                { id: 28392, name: 'KYAKABARISINGA' },
                { id: 28393, name: 'NGARAMA' },
                { id: 28394, name: 'NYAKASA' },
                { id: 28395, name: 'NYAKAZINGA' },
                { id: 28396, name: 'RUBIIRA' },
                { id: 28397, name: 'RUTOOMA    A' },
                { id: 28398, name: 'RUTOOMA    B' },
                { id: 28399, name: 'RWEERE' },
                { id: 28400, name: 'RWENTARE' },
                { id: 28401, name: 'STAGE' },
              ],
            },
            {
              id: 4405,
              name: 'IHUNGA',
              villages: [
                { id: 28402, name: 'BUGARAMA' },
                { id: 28403, name: 'BUHESI' },
                { id: 28404, name: 'KABIRIZI' },
                { id: 28405, name: 'KISHUNJURE' },
                { id: 28406, name: 'KITEME' },
                { id: 28407, name: 'KYANJU' },
                { id: 28408, name: 'NYAMICUCU' },
                { id: 28409, name: 'NYARWAMBU' },
              ],
            },
            {
              id: 4406,
              name: 'KISIIZI',
              villages: [
                { id: 28410, name: 'BINYENA' },
                { id: 28411, name: 'BUGARAMA' },
                { id: 28412, name: 'BUTUURWA' },
                { id: 28413, name: 'KAHANGA' },
                { id: 28414, name: 'KAMAKINDA' },
                { id: 28415, name: 'KAMWOBA' },
                { id: 28416, name: 'KANYINYA' },
                { id: 28417, name: 'KASIKIZI' },
                { id: 28418, name: 'KINYAMAHWA' },
                { id: 28419, name: 'KISIIZI HOSP. CELL' },
                { id: 28420, name: 'KITANOGA' },
                { id: 28421, name: 'MICERERE' },
                { id: 28423, name: 'NYARUTUNTU' },
                { id: 28424, name: 'OMUKACUNDEZI' },
                { id: 28422, name: 'OMUKASHENYI' },
                { id: 28425, name: 'OMUKIBAZI' },
                { id: 28426, name: 'RUSA' },
                { id: 28427, name: 'RWEGYEMURIRO' },
                { id: 28428, name: 'RWENGONGO' },
                { id: 28429, name: 'RWENTAKA' },
              ],
            },
            {
              id: 4407,
              name: 'NDAGO',
              villages: [
                { id: 28430, name: 'KAGOROGORO' },
                { id: 28431, name: 'KAHAMA' },
                { id: 28432, name: 'KAMIRA' },
                { id: 28433, name: 'KARUHARA' },
                { id: 28434, name: 'KIKONI A' },
                { id: 28435, name: 'KIKONI B' },
                { id: 28436, name: 'KITOKYE' },
                { id: 28437, name: 'KYANIKA A' },
                { id: 28438, name: 'KYANIKA B' },
                { id: 28439, name: 'KYANYAMAISHWA' },
                { id: 28440, name: 'NYAKAJU' },
                { id: 28441, name: 'NYAKATOKYE' },
                { id: 28442, name: 'TOROTORO' },
              ],
            },
            {
              id: 4408,
              name: 'NYABUSHENYI',
              villages: [
                { id: 28443, name: 'KABASHENYA' },
                { id: 28444, name: 'KABUMBA' },
                { id: 28445, name: 'KAMUZINZI' },
                { id: 28446, name: 'KAROKARUNGI' },
                { id: 28447, name: 'KIGANGA' },
                { id: 28448, name: 'KIMBUGU' },
                { id: 28449, name: 'MUTOJO' },
                { id: 28451, name: 'NYAKAHANGA A' },
                { id: 28450, name: 'NYAKAHANGA B' },
                { id: 28452, name: 'NYAMABARE' },
                { id: 28453, name: 'NYAMATONGO' },
                { id: 28454, name: 'OMUKASHANDA' },
                { id: 28455, name: 'RUBABO   A' },
                { id: 28456, name: 'RUBABO   B' },
                { id: 28457, name: 'RWEBIHONDO' },
              ],
            },
            {
              id: 4409,
              name: 'RUYONZA',
              villages: [
                { id: 28458, name: 'KABAALE' },
                { id: 28459, name: 'KABIMBA' },
                { id: 28460, name: 'KATOBOTOBO' },
                { id: 28461, name: 'KATUNGA' },
                { id: 28462, name: 'KIBURASANO' },
                { id: 28463, name: 'KIGANGO' },
                { id: 28464, name: 'KYARUKAMBA' },
                { id: 28465, name: 'MUKISHANDA' },
                { id: 28466, name: 'NYAKARAMBI' },
                { id: 28467, name: 'RUGOMA' },
                { id: 28468, name: 'RUYONZA' },
                { id: 28469, name: 'RWENSHEKYE' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 155,
      name: 'RUJUMBURA COUNTY',
      sub_counties: [
        {
          id: 960,
          name: 'BIKURUNGU TOWN COUNCIL',
          parishes: [
            {
              id: 4451,
              name: 'CENTRAL WARD',
              villages: [
                { id: 28855, name: 'BIKURUNGU T.C' },
                { id: 28856, name: 'MIRONZI I' },
                { id: 28857, name: 'MIRONZI II' },
                { id: 28858, name: 'MIRONZI III' },
              ],
            },
            {
              id: 4452,
              name: 'EASTERN WARD',
              villages: [
                { id: 28859, name: 'KANSHEKYE I' },
                { id: 28860, name: 'KANSHEKYE II' },
                { id: 28861, name: 'KANYANKWANZI' },
              ],
            },
            {
              id: 4453,
              name: 'WESTERN WARD',
              villages: [
                { id: 28862, name: 'NYAKATUNGURU' },
                { id: 28863, name: 'NYAMITOMA I' },
                { id: 28865, name: 'NYAMITOMA II' },
                { id: 28864, name: 'NYAMITOMA III' },
              ],
            },
          ],
        },
        {
          id: 954,
          name: 'BUGANGARI',
          parishes: [
            {
              id: 4417,
              name: 'BUGANGARI',
              villages: [
                { id: 28505, name: 'BUGARAMA' },
                { id: 28506, name: 'KAGASHE' },
                { id: 28507, name: 'KAKIRAGO I' },
                { id: 28508, name: 'KAKIRAGO II' },
                { id: 28509, name: 'KANYANKYENDE' },
                { id: 28510, name: 'KATERAMO' },
                { id: 28511, name: 'NYAKINENGO' },
                { id: 28512, name: 'RUMIRA' },
                { id: 28513, name: 'RUNYAMUNYU I' },
                { id: 28514, name: 'RUNYAMUNYU II' },
                { id: 28515, name: 'RWEIBARE' },
                { id: 28516, name: 'RWEIBUMBA' },
                { id: 28517, name: 'RWENYERERE' },
                { id: 28518, name: 'RYENGYERERO' },
              ],
            },
            {
              id: 4418,
              name: 'BURAMA',
              villages: [
                { id: 28519, name: 'KABESHEKYERE' },
                { id: 28520, name: 'KAGATI' },
                { id: 28521, name: 'KAHORO' },
                { id: 28522, name: 'KIBARAMA' },
                { id: 28523, name: 'NYAKASHARARA' },
                { id: 28524, name: 'RUGARAMA' },
                { id: 28525, name: 'RUSHINYA' },
                { id: 28526, name: 'RWEMIRONGO' },
              ],
            },
            {
              id: 4419,
              name: 'KAKINDO',
              villages: [
                { id: 28527, name: 'BURAMBIRA' },
                { id: 28528, name: 'KARO KARUNGI' },
                { id: 28529, name: 'KAYAGA' },
                { id: 28530, name: 'NYAKITABATA' },
                { id: 28531, name: 'NYAMIRAMA' },
                { id: 28532, name: 'NYARUBARE' },
                { id: 28533, name: 'OMUKISHAHA' },
                { id: 28534, name: 'OMURUHITA' },
              ],
            },
            {
              id: 4420,
              name: 'KASHAYO',
              villages: [
                { id: 28535, name: 'KANCUCU' },
                { id: 28536, name: 'KASHARARAZI' },
                { id: 28537, name: 'KASHAYO' },
                { id: 28538, name: 'MURAMBO' },
                { id: 28539, name: 'NYAKANENGO' },
                { id: 28540, name: 'NYAKARIRO  CENTRAL' },
                { id: 28541, name: 'NYANKORO' },
                { id: 28542, name: 'RWAKIGAJU' },
                { id: 28543, name: 'RWAKIRIBA' },
                { id: 28544, name: 'RWENGWE' },
              ],
            },
            {
              id: 4421,
              name: 'KAZINDIRO',
              villages: [
                { id: 28545, name: 'KABYOOYA' },
                { id: 28546, name: 'KANYAMUHE' },
                { id: 28547, name: 'KATERAMPUNGU' },
                { id: 28548, name: 'KITUNGURU I' },
                { id: 28549, name: 'KITUNGURU II' },
                { id: 28550, name: 'NYAKAHANGA' },
                { id: 28551, name: 'NYAMIYAGA  B' },
                { id: 28552, name: "NYAMIYAGA 'A'" },
                { id: 68213, name: "NYANGANJARA '?'" },
                { id: 28553, name: "NYANGANJARA '\u00c1'" },
                { id: 28554, name: 'NYANGANJARA B' },
                { id: 28555, name: 'OMURWEERE' },
                { id: 28556, name: 'RUGARAMA' },
                { id: 28557, name: 'RUGOMERA' },
                { id: 28558, name: 'RUHIIRA' },
                { id: 28559, name: 'RWANYANJA' },
              ],
            },
            {
              id: 4422,
              name: 'KYABUREERE',
              villages: [
                { id: 28560, name: 'KANYAMUHE' },
                { id: 28561, name: 'KARO  KARUNGI' },
                { id: 28562, name: 'KIBEIZIRO' },
                { id: 28563, name: 'KILEMBE' },
                { id: 28564, name: 'KITUSI' },
                { id: 28565, name: 'KYABUREERE' },
                { id: 28566, name: 'NYAKABUNGO' },
                { id: 28567, name: 'NYARUBARE' },
                { id: 28568, name: 'RUGARAMA' },
                { id: 28569, name: 'RWENYANGI' },
              ],
            },
            {
              id: 4423,
              name: 'NYABITEETE',
              villages: [
                { id: 28570, name: 'BIZIBIIBI' },
                { id: 28571, name: 'BUREMBO' },
                { id: 28572, name: 'KANYANKYENDE' },
                { id: 28573, name: 'KANYANTUUTU' },
                { id: 28574, name: 'KAREREMA' },
                { id: 28575, name: 'KASHENYI' },
                { id: 28576, name: 'KEITA' },
                { id: 28577, name: 'MABUNGO' },
                { id: 28578, name: 'NYABITEETE' },
                { id: 28579, name: 'NYAKINENGO' },
                { id: 28580, name: 'NYAMABARE' },
                { id: 28581, name: 'RUGANDO' },
                { id: 28582, name: 'RUGOMERA' },
                { id: 28583, name: 'RWEMENGO' },
              ],
            },
          ],
        },
        {
          id: 955,
          name: 'BUHUNGA',
          parishes: [
            {
              id: 4424,
              name: 'BUHUNGA',
              villages: [
                { id: 28584, name: 'KASHENYI' },
                { id: 28585, name: 'KEMPUNGU' },
                { id: 28586, name: 'KIJONDE' },
                { id: 28587, name: 'KISHAKA' },
                { id: 28588, name: 'KITOOKYE' },
                { id: 28589, name: 'MUTANOGA' },
                { id: 28590, name: 'NYAMIYAGA' },
                { id: 28591, name: 'ORUHITA' },
                { id: 28592, name: 'RUGANDO' },
                { id: 28593, name: 'RUSHESHE' },
                { id: 28594, name: 'RUSHOROZA' },
                { id: 28595, name: 'RUTOOMA' },
                { id: 28596, name: "RWABWINGI 'A'" },
                { id: 28597, name: "RWABWINGI 'B'" },
                { id: 28598, name: 'RWAKAKOKO' },
                { id: 28599, name: 'RWAKARIISA' },
                { id: 28600, name: 'RWAKIRIIBA' },
                { id: 28601, name: 'RWAMUNINGA' },
                { id: 28602, name: 'RWENKUBA' },
                { id: 28603, name: 'RYAMITYARI' },
                { id: 28604, name: 'RYARUGAMBWA' },
              ],
            },
            {
              id: 4425,
              name: 'BWANDA',
              villages: [
                { id: 28605, name: 'BISIIKA  B' },
                { id: 28606, name: "BISIIKA 'A'" },
                { id: 28607, name: 'BUNYINYA' },
                { id: 28608, name: 'BWEHARE' },
                { id: 28609, name: 'KAGARAMA' },
                { id: 28610, name: 'KIKURA' },
                { id: 28611, name: 'MUSHUNGA' },
                { id: 28612, name: 'OMUKASHENYI' },
                { id: 28613, name: 'OMWIBARE' },
                { id: 28614, name: "RUMBUGU ''A''" },
                { id: 28615, name: "RUMBUGU ''B''" },
                { id: 28616, name: 'RUSHESHE' },
                { id: 28617, name: 'RWEGA' },
              ],
            },
            {
              id: 4426,
              name: 'KABINGO',
              villages: [
                { id: 28618, name: 'IKUNIRO' },
                { id: 28619, name: 'KABINGO' },
                { id: 28620, name: 'KAGANDO' },
                { id: 28621, name: 'KANKUNGU' },
                { id: 28622, name: 'KASHENYI' },
                { id: 28623, name: 'KEIGANDE' },
                { id: 28624, name: 'KIGARIKO' },
                { id: 28625, name: 'KIRIMBI' },
                { id: 28626, name: 'KITUNGA' },
                { id: 28627, name: 'NCEREERE' },
                { id: 28628, name: 'NYARUBIRA' },
                { id: 28629, name: 'RUGANDO' },
                { id: 28630, name: 'RWAKATUNDURI' },
                { id: 28631, name: 'RWEMPUGUHUGU' },
                { id: 28632, name: 'RWENGAHA' },
              ],
            },
            {
              id: 4429,
              name: 'KIBIRIZI',
              villages: [
                { id: 28653, name: 'KIBARA' },
                { id: 28654, name: 'KIBIRIZI' },
                { id: 28655, name: 'KIFUNJO' },
                { id: 28656, name: 'KIZINGA' },
                { id: 28657, name: 'MABUNU' },
                { id: 28658, name: 'NYAMABARE' },
                { id: 28659, name: 'NYARUBEMBE' },
                { id: 28660, name: 'RUTOOMA CENTRAL' },
              ],
            },
            {
              id: 4427,
              name: 'KIHANGA',
              villages: [
                { id: 28633, name: 'KACENCE CENTRAL' },
                { id: 28634, name: 'KAKATENGA' },
                { id: 28635, name: 'KIGANGO' },
                { id: 28636, name: 'NYAMIYAGA' },
                { id: 28637, name: 'NYAMUNIGA' },
                { id: 28638, name: 'NYARUBARE' },
                { id: 28639, name: 'RUGOROGORO' },
                { id: 28640, name: 'RUNYINYA' },
              ],
            },
            {
              id: 4428,
              name: 'KYARUYENJE',
              villages: [
                { id: 28641, name: 'KABOBO' },
                { id: 28642, name: 'KACENCE' },
                { id: 28643, name: 'KASHENYI' },
                { id: 28644, name: 'MUGAMBA' },
                { id: 28645, name: 'MUSAANA' },
                { id: 28646, name: 'NYAMIYAGA' },
                { id: 28647, name: 'NYARURAMBI' },
                { id: 28648, name: 'RUGANDO' },
                { id: 28649, name: 'RWABUTONYA' },
                { id: 28650, name: 'RWAMARENGYE' },
                { id: 28651, name: 'RWANYAKAHIMBI' },
                { id: 28652, name: 'RWEBIRIBA' },
              ],
            },
          ],
        },
        {
          id: 956,
          name: 'BWAMBARA',
          parishes: [
            {
              id: 4430,
              name: 'BWAMBARA',
              villages: [
                { id: 28661, name: 'BUGARAMA' },
                { id: 28662, name: 'BWAMBARA T .C' },
                { id: 28663, name: 'KAGOROGORO' },
                { id: 28664, name: 'KAMBUGU' },
                { id: 28665, name: 'KANYABISHAMBWE' },
                { id: 28666, name: 'KYABAHANGA' },
                { id: 28667, name: 'KYEHUNDE' },
                { id: 28668, name: 'MUYANJE' },
                { id: 28669, name: 'NYABUGANDO' },
                { id: 28670, name: 'OMUKAYAGA' },
                { id: 28671, name: 'OMUKIKOMO' },
                { id: 28672, name: 'RUSHAYA  A' },
                { id: 28673, name: 'RUSHAYA  B' },
                { id: 28674, name: 'RUSHAYA C+D' },
              ],
            },
            {
              id: 4431,
              name: 'KIKARARA',
              villages: [
                { id: 28675, name: 'GARUKA' },
                { id: 28676, name: 'KAFUNJO' },
                { id: 28677, name: 'KAHIMBI' },
                { id: 28678, name: 'NYABUGANDO' },
                { id: 28679, name: 'NYAKABUNGO A' },
                { id: 28680, name: 'NYAKABUNGO B' },
                { id: 28681, name: 'NYAKATEMBE A' },
                { id: 28682, name: 'NYAKATEMBE B' },
                { id: 28683, name: 'RWESIGIRO' },
              ],
            },
            {
              id: 4432,
              name: 'KIKONGI',
              villages: [
                { id: 28684, name: 'IHIMBO' },
                { id: 28685, name: 'KANYINABARONGO' },
                { id: 28686, name: 'KARYAMACUMU' },
                { id: 28687, name: 'KATERAMO' },
                { id: 28688, name: 'KEMPAZI' },
                { id: 28689, name: 'KIKONGI  TRADING CENTRE' },
                { id: 28690, name: 'MIRONZI' },
                { id: 28691, name: 'NYAKARAMA' },
                { id: 28692, name: 'NYAKATUNGURU' },
                { id: 28693, name: 'NYARUHUNGYE' },
                { id: 28694, name: 'RUSHARARAZI' },
                { id: 28695, name: 'RUSHEBEYA' },
              ],
            },
            {
              id: 4433,
              name: 'NYABUBARE',
              villages: [
                { id: 28696, name: 'BWERONDE' },
                { id: 28697, name: 'IHENDAMATA' },
                { id: 28698, name: 'KAGATI' },
                { id: 28699, name: 'KAKONI' },
                { id: 28700, name: 'KANYANKWANZI' },
                { id: 28701, name: 'KINYAMATOJO' },
                { id: 28702, name: 'NYABUBARE' },
                { id: 28703, name: 'NYAKARAMBI' },
                { id: 28704, name: 'NYAKIBINGO' },
                { id: 28705, name: 'NYAMIHUKU' },
                { id: 28706, name: 'NYARWIMUKA' },
                { id: 28707, name: 'RUGYERA' },
                { id: 28708, name: 'RUTOOMA' },
                { id: 28709, name: 'RWEMISINGA' },
              ],
            },
            {
              id: 4434,
              name: 'RWENSHAMA',
              villages: [
                { id: 28710, name: 'NCWERA' },
                { id: 28711, name: 'RWEBINYONYI' },
                { id: 28712, name: 'RWENSHAMA' },
              ],
            },
          ],
        },
        {
          id: 957,
          name: 'NYAKAGYEME',
          parishes: [
            {
              id: 4437,
              name: 'KABWOMA',
              villages: [
                { id: 28725, name: 'KABALE' },
                { id: 28726, name: 'KABURA' },
                { id: 28727, name: 'KABWOMA' },
                { id: 28728, name: 'KAGOROGORO' },
                { id: 28729, name: 'KAHENDA' },
                { id: 28730, name: 'KASHENYI' },
                { id: 28731, name: 'KATASHORA' },
                { id: 28732, name: 'KITEME' },
                { id: 28733, name: 'RUTEETE' },
              ],
            },
            {
              id: 4438,
              name: 'KAHOKO',
              villages: [
                { id: 28734, name: 'BIHASHA' },
                { id: 28735, name: 'BUGARAMA' },
                { id: 28736, name: 'KAGARAMA' },
                { id: 28737, name: 'KAMUNYU' },
                { id: 28738, name: 'KANTOJO' },
                { id: 28739, name: 'KASHEEGU' },
                { id: 28740, name: 'KIGUHA' },
                { id: 28741, name: 'KINYAMAHWA' },
                { id: 28742, name: 'KYAMAKYERA' },
                { id: 28743, name: 'MAIRO' },
                { id: 28744, name: 'MITOOMA' },
                { id: 28745, name: 'MURAARO' },
                { id: 28746, name: 'NYAKACWAMBA' },
                { id: 28747, name: 'NYAKAFUNJO' },
                { id: 28748, name: 'NYAKAGYERA' },
                { id: 28749, name: 'NYAKARUNDI' },
                { id: 28750, name: 'OMUBUBARE' },
                { id: 28751, name: 'OMUKIBUNGO' },
                { id: 28752, name: 'RUBAMBURA' },
                { id: 28753, name: 'RUNYINYA' },
                { id: 28754, name: 'RWENKUBA' },
              ],
            },
            {
              id: 4435,
              name: 'KIGAAGA',
              villages: [
                { id: 28713, name: 'BUCENCE' },
                { id: 28714, name: 'KAGUNGA' },
                { id: 28715, name: 'KASOROZA' },
                { id: 28716, name: 'KYAMURARI I' },
                { id: 28717, name: 'KYAMURARI II' },
                { id: 28718, name: 'NYAKIZIBA' },
                { id: 28719, name: 'NYAMPIKYE' },
              ],
            },
            {
              id: 4436,
              name: 'KITIMBA',
              villages: [
                { id: 28720, name: 'BUNYINYA' },
                { id: 28721, name: 'KASOROZA' },
                { id: 28722, name: 'KIREHE' },
                { id: 28723, name: 'KITOJO' },
                { id: 28724, name: 'KYEIZOBA' },
              ],
            },
            {
              id: 4439,
              name: 'MASYA',
              villages: [
                { id: 28755, name: 'KANYABIHARA' },
                { id: 28756, name: 'KASHENYI' },
                { id: 28757, name: 'MABUNGO' },
                { id: 28758, name: 'MUNYEGANYEGYE' },
                { id: 28759, name: 'NYABUGANDO' },
                { id: 28760, name: "NYAKAHANGA 'A'" },
                { id: 28761, name: "NYAKAHANGA 'B'" },
                { id: 28762, name: 'RWAMUNYINYO' },
                { id: 28763, name: 'SHONGORA' },
              ],
            },
            {
              id: 4440,
              name: 'NYAKINENGO',
              villages: [
                { id: 28764, name: 'KAHIHI' },
                { id: 28765, name: 'KATUNGU  I' },
                { id: 28766, name: 'KATUNGU  II' },
                { id: 28767, name: 'KIFUNJO' },
                { id: 28768, name: 'KIREHE' },
                { id: 28769, name: 'KISHANDA  I' },
                { id: 28770, name: 'KISHANDA  II' },
                { id: 28771, name: 'NYAKAYAGA' },
                { id: 28772, name: 'RUGANDO' },
                { id: 28773, name: 'RUGUNDA' },
                { id: 28774, name: 'RUSOROZA' },
              ],
            },
            {
              id: 4441,
              name: 'RUSHASHA',
              villages: [
                { id: 28775, name: 'BURERA' },
                { id: 28776, name: 'KATONYA' },
                { id: 28777, name: 'KATUNGU' },
                { id: 28778, name: 'KIBOBO' },
                { id: 28779, name: 'KYABUGASHE' },
                { id: 28780, name: 'NYABIKUKU' },
                { id: 28781, name: 'RUBABI' },
                { id: 28782, name: 'RUGANDO' },
                { id: 28783, name: 'RUGOROGORO' },
                { id: 28784, name: 'RWEMBOGO' },
                { id: 28785, name: 'RWENCWERA' },
              ],
            },
          ],
        },
        {
          id: 958,
          name: 'RUHINDA',
          parishes: [
            {
              id: 4442,
              name: 'BUROMBE',
              villages: [
                { id: 28786, name: 'BUTAGATSI' },
                { id: 28787, name: 'BWAMUHA' },
                { id: 28788, name: 'KAKOMA' },
                { id: 28789, name: 'KATOOKYE' },
                { id: 28790, name: 'KYEBUMBIRE' },
                { id: 28791, name: 'NYEIBANGA' },
                { id: 28792, name: 'RUHIITA' },
                { id: 28793, name: 'RUNYINYA' },
                { id: 28794, name: 'RWAKATEERA' },
                { id: 28795, name: 'RWENSHAKA' },
              ],
            },
            {
              id: 4443,
              name: 'KICWAMBA',
              villages: [
                { id: 28796, name: 'BUSHOGYE' },
                { id: 28797, name: 'KABALE' },
                { id: 28798, name: 'KAJWAMUSHANA' },
                { id: 28799, name: 'NYAKAGYERA' },
                { id: 28800, name: 'NYAKIHANGA' },
                { id: 28801, name: 'OMUKATOOMA' },
                { id: 28802, name: 'OMUKITEEMBE' },
                { id: 28803, name: 'RWABIBANGA' },
                { id: 28804, name: 'RWABUKOBA  S.S.S' },
                { id: 28805, name: 'RWEBIKOONA' },
                { id: 28806, name: 'RWENSIBO' },
              ],
            },
            {
              id: 4444,
              name: 'NDERE',
              villages: [
                { id: 28807, name: 'BUTARIMWA' },
                { id: 28808, name: 'KAJUNJU' },
                { id: 28809, name: 'KISHOKO' },
                { id: 28810, name: 'KYABAGYERWA' },
                { id: 28811, name: 'KYEBICEERE' },
                { id: 28812, name: 'MURARO' },
                { id: 28813, name: 'NKANGA  I' },
                { id: 28814, name: 'NKANGA  II' },
                { id: 28815, name: 'OMWITABA' },
                { id: 28816, name: 'RUHUBUBA' },
                { id: 28817, name: 'RWOYA  I' },
                { id: 28818, name: 'RWOYA CENTRAL' },
              ],
            },
            {
              id: 4446,
              name: 'NYAKITABIRE',
              villages: [
                { id: 28827, name: 'KABASONI' },
                { id: 28828, name: 'KABUBA  I' },
                { id: 28829, name: 'KABUBA  II' },
                { id: 28830, name: 'KENGOMA' },
                { id: 28831, name: 'KIGARIGARI' },
                { id: 28832, name: 'KIKUNYU' },
                { id: 28833, name: 'KYATO' },
                { id: 28834, name: 'MPANGA' },
                { id: 28835, name: 'RUBOROGA' },
                { id: 28836, name: 'RWENTUHA' },
              ],
            },
            {
              id: 4445,
              name: 'NYARWIMUKA',
              villages: [
                { id: 28819, name: 'IHINDIRO' },
                { id: 28820, name: 'KANYAMISHEKURO' },
                { id: 28821, name: 'KYOMERA' },
                { id: 28822, name: 'NYABUKUMBA' },
                { id: 28823, name: 'NYAMIFURA' },
                { id: 28824, name: 'OMWIBUMBA' },
                { id: 28825, name: 'RUSHAYA' },
                { id: 28826, name: 'RUYAYO' },
              ],
            },
            {
              id: 4447,
              name: 'RWAMUGOMA',
              villages: [
                { id: 28837, name: 'KAKOKI' },
                { id: 28838, name: 'KASHENYI' },
                { id: 28839, name: 'KASHENYI S.S.' },
                { id: 28840, name: 'KIRUNDO' },
                { id: 28841, name: 'NYAKANYINYA' },
                { id: 28842, name: 'NYAMITOOMA' },
                { id: 28843, name: 'RWABUREGYEYA' },
                { id: 28844, name: 'RWAMARENGYE' },
                { id: 28845, name: 'RWAMUGOMA' },
              ],
            },
          ],
        },
        {
          id: 959,
          name: 'RWERERE TOWN COUNCIL',
          parishes: [
            {
              id: 4448,
              name: 'BIGAGA WARD',
              villages: [
                { id: 28846, name: 'BIGAGA' },
                { id: 28847, name: 'RWAKAGORO' },
                { id: 28848, name: 'RWAKASHANDA' },
              ],
            },
            {
              id: 4449,
              name: 'KAGUGU WARD',
              villages: [
                { id: 28849, name: 'KAGUGU' },
                { id: 28850, name: 'KAMUJEGYE' },
                { id: 28851, name: 'KIGARAMA' },
              ],
            },
            {
              id: 4450,
              name: 'RUSOROZA WARD',
              villages: [
                { id: 28852, name: "RUSOROZA 'A'" },
                { id: 28853, name: "RUSOROZA 'B'" },
                { id: 28854, name: 'RWAKIRIBA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 156,
      name: 'RUKUNGIRI MUNICIPALITY',
      sub_counties: [
        {
          id: 961,
          name: 'EASTERN DIVISION',
          parishes: [
            {
              id: 4454,
              name: 'KAGASHE WARD',
              villages: [
                { id: 28866, name: 'IMMACULATE HEART S.S.S' },
                { id: 28867, name: 'KAGASHE' },
                { id: 28868, name: 'RUNYINYA/KINOMBE' },
                { id: 28869, name: 'RWABUTENEKA' },
              ],
            },
            {
              id: 4455,
              name: 'KYATOKO WARD',
              villages: [
                { id: 28870, name: 'EISHERERO' },
                { id: 28871, name: 'KACWA' },
                { id: 28881, name: 'KARUCUMITSI B' },
                { id: 28878, name: 'KIFUNJO' },
                { id: 28880, name: 'MUGAMBA' },
                { id: 28872, name: 'NYABIHINGA' },
                { id: 28873, name: 'NYAKASHAKA' },
                { id: 28874, name: 'NYAKIHANGA' },
                { id: 28875, name: 'NYARUHARO' },
                { id: 28876, name: 'RUHEGA' },
                { id: 28879, name: 'RUKUNGIRI POLICE' },
                { id: 28877, name: 'RWAKAHINJU' },
              ],
            },
            {
              id: 4456,
              name: 'NORTHERN B WARD',
              villages: [
                { id: 28882, name: 'KAGARAMA B' },
                { id: 28883, name: 'KAKABADA B' },
                { id: 28884, name: 'KEITUMURA' },
              ],
            },
            {
              id: 4457,
              name: 'RWENTONDO WARD',
              villages: [
                { id: 28898, name: 'BYARA' },
                { id: 28885, name: 'KAFUNJO' },
                { id: 28886, name: 'KAGUGU' },
                { id: 28887, name: 'KAMURI' },
                { id: 28888, name: 'KANYANGA' },
                { id: 28889, name: 'KATWEKAMWE' },
                { id: 28890, name: 'KICENCE' },
                { id: 28891, name: 'KYARUGAMBA' },
                { id: 28892, name: 'NYABIHINGA' },
                { id: 28893, name: 'NYAMAYENJE B' },
                { id: 28894, name: 'NYAMIKO' },
                { id: 28895, name: 'RUGONGI' },
                { id: 28896, name: 'RWAKATUNDURI' },
                { id: 28897, name: 'RWEMPITSI' },
              ],
            },
          ],
        },
        {
          id: 962,
          name: 'SOUTHERN DIVISION',
          parishes: [
            {
              id: 4458,
              name: 'KANYINYA WARD',
              villages: [
                { id: 28899, name: 'KAFUNJO' },
                { id: 28900, name: 'KATARUKA' },
                { id: 28901, name: 'KITAZIGURUKWA' },
                { id: 28902, name: 'KYESHORO' },
                { id: 28903, name: "MARUMBA  'A'" },
                { id: 28904, name: "MARUMBA  'B'" },
                { id: 28905, name: "MARUMBA  'C'" },
                { id: 28906, name: 'NSHURE' },
              ],
            },
            {
              id: 4459,
              name: 'KIGAAGA WARD',
              villages: [
                { id: 28907, name: 'KATUNGU' },
                { id: 28908, name: 'KIBIMBIRI' },
                { id: 28909, name: 'KIGINA' },
                { id: 28910, name: 'RWAGANA' },
                { id: 28911, name: 'RWOBO' },
              ],
            },
            {
              id: 4460,
              name: 'NDORERO WARD',
              villages: [
                { id: 28912, name: 'KIBIRIZI' },
                { id: 28913, name: 'NDORERO' },
                { id: 28914, name: 'NYAMAYENJE A' },
                { id: 28915, name: 'NYARUZINGA' },
              ],
            },
            {
              id: 4461,
              name: 'RWAKABENGO WARD',
              villages: [
                { id: 28916, name: 'BUNURA GO-DOWN' },
                { id: 28917, name: 'KATENGA' },
                { id: 28918, name: 'KATOJO' },
                { id: 28919, name: 'NYAKIBALE HOSPITAL' },
                { id: 28920, name: 'RWAKABENGO A' },
                { id: 28921, name: 'RWAKABENGO B' },
                { id: 28924, name: 'RWARUBIRA' },
                { id: 28923, name: 'RWENKUBA' },
                { id: 28922, name: "ST.  GERALD'S S.S.S" },
              ],
            },
          ],
        },
        {
          id: 963,
          name: 'WESTERN DIVISION',
          parishes: [
            {
              id: 4462,
              name: 'KARANGARO WARD',
              villages: [
                { id: 28925, name: 'FURUMA' },
                { id: 28926, name: 'KABWIRE' },
                { id: 28927, name: 'KAFUNDA' },
                { id: 28928, name: 'KAHORORO' },
                { id: 28929, name: 'KIBARE' },
                { id: 28930, name: 'MUTARA' },
                { id: 28931, name: 'NYAKIHANGA' },
                { id: 28932, name: 'NYAMABARE' },
              ],
            },
            {
              id: 4463,
              name: 'KINYASANO WARD',
              villages: [
                { id: 28936, name: 'BUTAGATSI' },
                { id: 28937, name: 'BUTIMBA' },
                { id: 28938, name: 'KARUCUMITSI A' },
                { id: 28939, name: 'KAYEMBE' },
                { id: 28934, name: 'KINYASANO CATHEDRAL' },
                { id: 28933, name: 'KINYASANO GIRLS' },
                { id: 28935, name: 'MAKOBORE  HIGH SCHOOL' },
              ],
            },
            {
              id: 4464,
              name: 'KITIMBA WARD',
              villages: [
                { id: 28940, name: 'KAARO' },
                { id: 28941, name: 'KANYANKU' },
                { id: 28942, name: 'KATOBO' },
                { id: 28943, name: 'KIGINA' },
                { id: 28944, name: 'KINYABUSHIISHA' },
                { id: 28945, name: 'MAAYA' },
              ],
            },
            {
              id: 4465,
              name: 'NORTHERN A WARD',
              villages: [
                { id: 28946, name: 'KACEEKA' },
                { id: 28947, name: 'KAGARAMA A' },
                { id: 28948, name: 'KAGYERA' },
                { id: 28949, name: 'KAKABADA A' },
                { id: 28950, name: 'KIYAGA' },
                { id: 70044, name: 'RWAKAHINJU B' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
