import { District } from '../types';

export default {
  id: 137,
  name: 'RWAMPARA',
  counties: [
    {
      id: 310,
      name: 'RWAMPARA COUNTY',
      sub_counties: [
        {
          id: 1961,
          name: 'BUGAMBA',
          parishes: [
            {
              id: 9517,
              name: 'KABARAMA',
              villages: [
                { id: 60816, name: 'BYANAMIRA' },
                { id: 61878, name: 'KABARAMA I' },
                { id: 61879, name: 'KABARAMA II' },
                { id: 61992, name: 'KACERERE' },
                { id: 62431, name: 'KAMISHATE' },
                { id: 62582, name: 'KANYANGONGI' },
                { id: 63104, name: 'KATINDA' },
                { id: 63243, name: 'KAYUNGA' },
                { id: 66440, name: 'MPARAMO' },
                { id: 68040, name: 'NYAKASANA' },
                { id: 68245, name: 'NYARUBARE I' },
                { id: 68246, name: 'NYARUBARE II' },
                { id: 69877, name: 'RUBINGO I' },
                { id: 69878, name: 'RUBINGO II' },
                { id: 69961, name: 'RURAMA' },
                { id: 69964, name: 'RURENGYE' },
              ],
            },
            {
              id: 9579,
              name: 'KAMOMO',
              villages: [
                { id: 60222, name: 'BURANGA' },
                { id: 60308, name: 'BUSHAAKA' },
                { id: 61955, name: 'KABUKARA' },
                { id: 62948, name: 'KASHENYI' },
                { id: 67828, name: 'NSHURO' },
                { id: 68266, name: 'NYARWINA' },
                { id: 70075, name: 'RWAMUHURIRA' },
                { id: 70186, name: 'RWENKWANZI' },
              ],
            },
            {
              id: 9761,
              name: 'KITOJO',
              villages: [
                { id: 62111, name: 'KAGOROGORO' },
                { id: 64053, name: 'KITOJO I' },
                { id: 64054, name: 'KITOJO II' },
                { id: 68208, name: 'NYANGA' },
                { id: 70256, name: 'RYAMAIJO' },
              ],
            },
            {
              id: 10090,
              name: 'NGUGO',
              villages: [
                { id: 59101, name: 'BINYUGA' },
                { id: 59132, name: 'BITUNTU' },
                { id: 61834, name: 'KAAYA' },
                { id: 62235, name: 'KAKONGORA I' },
                { id: 62236, name: 'KAKONGORA II' },
                { id: 63477, name: 'KIGANDO' },
                { id: 63681, name: 'KIKUTO I' },
                { id: 63682, name: 'KIKUTO II' },
                { id: 67774, name: 'NGUGO  I' },
                { id: 67775, name: 'NGUGO II' },
              ],
            },
            {
              id: 10131,
              name: 'NYARUHANDAGAZI',
              villages: [
                { id: 60321, name: 'BUSHORO' },
                { id: 62942, name: 'KASHEKURE' },
                { id: 62961, name: 'KASHUNGWE' },
                { id: 63479, name: 'KIGANDO' },
                { id: 64084, name: 'KITOOHA' },
                { id: 66306, name: 'MISIBIKA' },
                { id: 67872, name: 'NTUNGAMO' },
                { id: 68097, name: 'NYAKIBARE' },
                { id: 68126, name: 'NYAMABARE' },
                { id: 68252, name: 'NYARUHANDAGAZI I' },
                { id: 68253, name: 'NYARUHANDAGAZI II' },
                { id: 68265, name: 'NYARWAMBU' },
                { id: 69910, name: 'RUGOROGORO' },
              ],
            },
          ],
        },
        {
          id: 1977,
          name: 'BUTERANIRO-NYEIHANGA TOWN COUNCIL',
          parishes: [
            {
              id: 9296,
              name: 'BUJAGA WARD',
              villages: [
                { id: 59403, name: 'BUJAGA A' },
                { id: 59404, name: 'BUJAGA B' },
                { id: 59405, name: 'BUJAGA CENTRAL' },
                { id: 60455, name: 'BUTERANIRO EAST' },
                { id: 60456, name: 'BUTERANIRO WEST' },
                { id: 62963, name: 'KASHURO' },
                { id: 63603, name: 'KIJOJO A' },
                { id: 68014, name: 'NYAKAHANGA' },
              ],
            },
            {
              id: 9553,
              name: 'KAKIGANI WARD',
              villages: [
                { id: 59071, name: 'BIITI' },
                { id: 62016, name: 'KACUCU' },
                { id: 62579, name: 'KANYANGI' },
                { id: 62765, name: 'KARAGWE' },
                { id: 64041, name: 'KITETE' },
                { id: 64086, name: 'KITOOKYE' },
                { id: 68262, name: 'NYARUTUUTU' },
                { id: 69900, name: 'RUGARAMA' },
                { id: 70005, name: 'RUTOOMA' },
                { id: 70817, name: 'TOWN CELL' },
              ],
            },
            {
              id: 10133,
              name: 'NYEIHANGA WARD',
              villages: [
                { id: 60183, name: 'BUNGYEREZA' },
                { id: 62865, name: 'KARUNYONYOZI' },
                { id: 64810, name: 'KYENOMBE' },
                { id: 68127, name: 'NYAMABARE' },
                { id: 68273, name: 'NYEIHANGA' },
                { id: 68274, name: 'NYEIHANGA CENTRAL' },
                { id: 68275, name: 'NYEIHANGA T/C' },
                { id: 69979, name: 'RUSHASHA' },
                { id: 70029, name: 'RWABAJOJO' },
              ],
            },
          ],
        },
        {
          id: 1992,
          name: 'KABURA TOWN COUNCIL',
          parishes: [
            {
              id: 9720,
              name: 'KIKONKOMA WARD',
              villages: [
                { id: 63658, name: 'KIKONKOMA CENTRAL' },
                { id: 63659, name: 'KIKONKOMA I' },
                { id: 63660, name: 'KIKONKOMA II' },
                { id: 64711, name: 'KYARUHENDA' },
              ],
            },
            {
              id: 10022,
              name: 'MWIZI WARD',
              villages: [
                { id: 61579, name: 'IHOMBYA' },
                { id: 61966, name: 'KABURA' },
                { id: 62937, name: 'KASHARIRA' },
                { id: 66045, name: 'MAREMBO I' },
                { id: 66046, name: 'MAREMBO II' },
                { id: 66777, name: 'MWIZI CENTRAL' },
                { id: 70203, name: 'RWENTAMU' },
              ],
            },
            {
              id: 10085,
              name: 'NGOMA WARD',
              villages: [
                { id: 62780, name: 'KARAMURANI' },
                { id: 63130, name: 'KATOOKYE' },
                { id: 67749, name: 'NGOMA' },
              ],
            },
          ],
        },
        {
          id: 2076,
          name: 'MWIZI',
          parishes: [
            {
              id: 9377,
              name: 'BUSHWERE',
              villages: [
                { id: 59398, name: 'BUHUNGYE' },
                { id: 61923, name: 'KABINGO' },
                { id: 62200, name: 'KAKIIRI' },
                { id: 62853, name: 'KARUHIIRA' },
                { id: 62975, name: 'KASIRIIRI' },
                { id: 63674, name: 'KIKUNDA I' },
                { id: 63675, name: 'KIKUNDA II' },
                { id: 63676, name: 'KIKUNDA III' },
                { id: 63677, name: 'KIKUNDA IV' },
                { id: 63975, name: 'KITAABA' },
                { id: 64559, name: 'KYAKASEETA' },
                { id: 64858, name: 'KYONYO' },
                { id: 68297, name: 'NYUNGU' },
                { id: 70025, name: 'RUZO' },
                { id: 70205, name: 'RWENTOJO' },
              ],
            },
            {
              id: 9688,
              name: 'KIGAAGA',
              villages: [
                { id: 61580, name: 'IHOMBYA I' },
                { id: 61581, name: 'IHOMBYA II' },
                { id: 61889, name: 'KABATANAGI' },
                { id: 61891, name: 'KABATANAGI II' },
                { id: 61896, name: 'KABAYA' },
                { id: 63463, name: 'KIGAAGA' },
                { id: 63726, name: 'KIMULI' },
                { id: 64849, name: 'KYOMA' },
                { id: 64850, name: 'KYOMA II' },
                { id: 69869, name: 'RUBAGANO' },
              ],
            },
            {
              id: 10271,
              name: 'RUKARABO',
              villages: [
                { id: 57742, name: 'AKASHANSHA' },
                { id: 62954, name: 'KASHOJWA I' },
                { id: 62955, name: 'KASHOJWA II' },
                { id: 64744, name: 'KYATOKO' },
                { id: 65851, name: 'MACUUCU' },
                { id: 68124, name: 'NYAMABARE' },
                { id: 69925, name: 'RUKARABO' },
              ],
            },
            {
              id: 10298,
              name: 'RYAMIYONGA',
              villages: [
                { id: 61550, name: 'IBUMBA' },
                { id: 62242, name: 'KAKONI I' },
                { id: 62243, name: 'KAKONI II' },
                { id: 63543, name: 'KIHANGIRE' },
                { id: 64745, name: 'KYATOKO' },
                { id: 64837, name: 'KYEYARE' },
                { id: 66689, name: 'MUSHEESHA' },
                { id: 70212, name: 'RWENYAGA' },
                { id: 70257, name: 'RYAMIYONGA' },
              ],
            },
          ],
        },
        {
          id: 2083,
          name: 'NDEIJA',
          parishes: [
            {
              id: 9673,
              name: 'KIBARE',
              villages: [
                { id: 61578, name: 'IHENA' },
                { id: 62263, name: 'KAKUUTO' },
                { id: 63337, name: 'KIBAARE' },
                { id: 63396, name: 'KIBUMBA' },
                { id: 64153, name: 'KIZIBA' },
                { id: 66636, name: 'MURAGO' },
              ],
            },
            {
              id: 9792,
              name: 'KONGORO',
              villages: [
                { id: 60737, name: 'BUYONGA' },
                { id: 64283, name: 'KONGORO' },
                { id: 64671, name: 'KYANCERE' },
                { id: 64775, name: 'KYEIREMBA' },
                { id: 69906, name: 'RUGAZI' },
              ],
            },
            {
              id: 10079,
              name: 'NDEIJA-MULAGO',
              villages: [
                { id: 61532, name: 'IBAARE' },
                { id: 62962, name: 'KASHURO' },
                { id: 64829, name: 'KYESIKA I' },
                { id: 64830, name: 'KYESIKA II' },
                { id: 67673, name: 'NDEIJA I' },
                { id: 67674, name: 'NDEIJA II' },
                { id: 68288, name: 'NYINDO' },
              ],
            },
            {
              id: 10114,
              name: 'NYAKAIKARA',
              villages: [
                { id: 63389, name: 'KIBUBA' },
                { id: 63491, name: 'KIGARAMA' },
                { id: 64052, name: 'KITOJO B' },
                { id: 68019, name: 'NYAKAIKARA' },
                { id: 69938, name: 'RUKONO' },
              ],
            },
            {
              id: 10292,
              name: 'RWENSINGA',
              villages: [
                { id: 57689, name: 'AKACENCE' },
                { id: 60363, name: 'BUSINGYE' },
                { id: 61731, name: 'IZINGA' },
                { id: 61978, name: 'KABUTARE' },
                { id: 62019, name: 'KACUUCU' },
                { id: 66717, name: 'MUTOOJO' },
                { id: 67996, name: 'NYAKABUNGO' },
                { id: 70002, name: 'RUTOOMA' },
                { id: 70174, name: 'RWENGWE' },
              ],
            },
          ],
        },
        {
          id: 2110,
          name: 'RUGANDO',
          parishes: [
            {
              id: 9771,
              name: 'KITUNGURU',
              villages: [
                { id: 59078, name: 'BIKONOKA' },
                { id: 61582, name: 'IHUNGA' },
                { id: 63071, name: 'KATEREZA' },
                { id: 63560, name: 'KIHONZI' },
                { id: 63754, name: 'KINONI CENTRAL' },
                { id: 64110, name: 'KITUNGURU' },
                { id: 64523, name: 'KYABWIHURE' },
                { id: 64535, name: 'KYAKAHIRA' },
                { id: 64638, name: 'KYAMUGASHA' },
                { id: 68009, name: 'NYAKAGURUKA' },
                { id: 69953, name: 'RUNENA' },
              ],
            },
            {
              id: 9983,
              name: 'MIRAMA',
              villages: [
                { id: 61847, name: 'KABAHESI' },
                { id: 63687, name: 'KIKYERENYO' },
                { id: 63950, name: 'KISORO' },
                { id: 66280, name: 'MIRAMA I' },
                { id: 66282, name: 'MIRAMA II' },
                { id: 69873, name: 'RUBANGA' },
                { id: 70155, name: 'RWEMIYENJE' },
                { id: 70167, name: 'RWENGIRI' },
                { id: 70204, name: 'RWENTOBO' },
              ],
            },
            {
              id: 10108,
              name: 'NYABIKUNGU',
              villages: [
                { id: 59065, name: 'BIHENDEKA' },
                { id: 59366, name: 'BUHAMA I' },
                { id: 59367, name: 'BUHAMA II' },
                { id: 60425, name: 'BUTAHE' },
                { id: 61260, name: 'ENKIRI' },
                { id: 61936, name: 'KABOBO' },
                { id: 63020, name: 'KASYORO' },
                { id: 64474, name: 'KYABAIBA' },
                { id: 64487, name: 'KYABANYORO' },
                { id: 66256, name: 'MIKAMBA' },
                { id: 67904, name: 'NYABIKUNGU' },
                { id: 69899, name: 'RUGARAMA' },
              ],
            },
            {
              id: 10111,
              name: 'NYAKABAARE',
              villages: [
                { id: 59379, name: 'BUHINGO' },
                { id: 59635, name: 'BUKUUNA I' },
                { id: 59636, name: 'BUKUUNA II' },
                { id: 60318, name: 'BUSHENYI' },
                { id: 67965, name: 'NYAKABAARE' },
                { id: 68155, name: 'NYAMIKANJA I' },
                { id: 68156, name: 'NYAMIKANJA II' },
                { id: 70128, name: 'RWEMBOGO' },
              ],
            },
            {
              id: 10130,
              name: 'NYARUBUNGO',
              villages: [
                { id: 59376, name: 'BUHIHI' },
                { id: 62102, name: 'KAGONGI' },
                { id: 62222, name: 'KAKITANGA' },
                { id: 62846, name: 'KARORA' },
                { id: 64116, name: 'KITWE' },
                { id: 64491, name: 'KYABASHUKURA' },
                { id: 68038, name: 'NYAKARONKO' },
                { id: 68138, name: 'NYAMATETE' },
                { id: 68248, name: 'NYARUBUNGO' },
                { id: 69875, name: 'RUBARE' },
                { id: 69905, name: 'RUGARAMA II' },
                { id: 69963, name: 'RURENGYE' },
                { id: 70192, name: 'RWENSHAMA' },
              ],
            },
          ],
        },
        {
          id: 2112,
          name: 'RWEIBOGO-KIBINGO TOWN COUNCIL',
          parishes: [
            {
              id: 9677,
              name: 'KIBINGO WARD',
              villages: [
                { id: 60457, name: 'BUTERERE' },
                { id: 61226, name: 'EKIHENA' },
                { id: 63372, name: 'KIBINGO' },
                { id: 63671, name: 'KIKUKURU' },
                { id: 64831, name: 'KYETINDO' },
                { id: 67865, name: 'NTSINGWA I' },
                { id: 67866, name: 'NTSINGWA II' },
                { id: 67994, name: 'NYAKABUNGO' },
                { id: 69978, name: 'RUSHANJE' },
                { id: 70074, name: 'RWAMUGANGA' },
              ],
            },
            {
              id: 10281,
              name: 'RWEIBOGO WARD',
              villages: [
                { id: 59292, name: 'BUGAMBA' },
                { id: 60817, name: 'BYANAMIRA' },
                { id: 63070, name: 'KATERERO' },
                { id: 66767, name: 'MWEYA' },
                { id: 70022, name: 'RUZINGA' },
                { id: 70111, name: 'RWEIBOGO I' },
                { id: 70112, name: 'RWEIBOGO II' },
                { id: 70151, name: 'RWEMISHA' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
