import { District } from '../types';

export default <District>{
  id: 12,
  name: 'SHEEMA',
  counties: [
    {
      id: 34,
      name: 'SHEEMA COUNTY NORTH',
      sub_counties: [
        {
          id: 177,
          name: 'KAKINDO TOWN COUNCIL',
          parishes: [
            {
              id: 833,
              name: 'KYANGUNDU WARD',
              villages: [
                { id: 5710, name: 'KABIRIZI I' },
                { id: 5716, name: 'KAKINDO' },
                { id: 5711, name: 'KYABAHIJA I' },
                { id: 5712, name: 'KYABAHIJA II' },
                { id: 5713, name: 'KYABAHIJA III' },
                { id: 5714, name: 'KYABAHIJA IV' },
                { id: 5715, name: 'RYENSIBO I' },
              ],
            },
            {
              id: 831,
              name: 'KYANGYENYI WARD',
              villages: [
                { id: 5697, name: 'BWINA I' },
                { id: 5698, name: 'BWINA II' },
                { id: 5699, name: 'KABIRIZI II' },
                { id: 5700, name: 'KABIRIZI III' },
                { id: 5701, name: 'KABIRIZI IV' },
                { id: 5702, name: 'KYANGYENYI I' },
                { id: 5703, name: 'KYANGYENYI II' },
              ],
            },
            {
              id: 834,
              name: 'RWEIBARE WARD',
              villages: [
                { id: 5717, name: 'KATOOMA I' },
                { id: 5718, name: 'KATOOMA II' },
                { id: 5719, name: 'RWEIBARE I' },
                { id: 5720, name: 'RWEIBARE II' },
                { id: 5721, name: 'RWEIBARE III' },
                { id: 5722, name: 'RWEIBARE IV' },
                { id: 70260, name: 'RYENSIBO II' },
              ],
            },
            {
              id: 832,
              name: 'RYENJOKI WARD',
              villages: [
                { id: 5704, name: 'BUHIHI' },
                { id: 5705, name: 'KAMPASHA' },
                { id: 5706, name: 'KYANGUNDU' },
                { id: 5709, name: 'RYENJOK III' },
                { id: 5707, name: 'RYENJOKI I' },
                { id: 5708, name: 'RYENJOKI II' },
              ],
            },
          ],
        },
        {
          id: 173,
          name: 'KIGARAMA',
          parishes: [
            {
              id: 817,
              name: 'BWAYEGAMBA',
              villages: [
                { id: 5591, name: 'BWAYEGAMBA I' },
                { id: 5592, name: 'BWAYEGAMBA II' },
                { id: 5593, name: 'BWAYEGAMBA TC' },
                { id: 5594, name: 'KIKUTO I' },
                { id: 5595, name: 'KIKUTO II' },
                { id: 5596, name: 'KIYUNGU EAST' },
                { id: 5597, name: 'KIYUNGU WEST' },
                { id: 5598, name: 'MWENGURA' },
                { id: 5599, name: 'NYABUBARE I' },
                { id: 5600, name: 'NYABUBARE II' },
                { id: 5601, name: 'NYAKASHARARA' },
                { id: 5602, name: 'NYAMIKO' },
                { id: 5603, name: 'NYAMINA' },
                { id: 5604, name: 'RWAKAHITSI' },
              ],
            },
            {
              id: 815,
              name: 'KATOOMA',
              villages: [
                { id: 5575, name: 'BWEHUNDO' },
                { id: 5577, name: 'NSHONGI GREATER' },
                { id: 5576, name: 'NSHONGI I' },
                { id: 5578, name: 'NYAKASHARARA' },
                { id: 5579, name: 'RYAMIGAAJU' },
              ],
            },
            {
              id: 816,
              name: 'KIGARAMA',
              villages: [
                { id: 5580, name: 'BUTATURWA' },
                { id: 5581, name: 'KATANOGA' },
                { id: 5582, name: 'KIGARAMA' },
                { id: 5583, name: 'KIZIMBI  I' },
                { id: 5584, name: 'KIZIMBI  II' },
                { id: 5585, name: 'KIZIMBI  III' },
                { id: 5586, name: 'MUTANOGA' },
                { id: 5587, name: 'NYAMIYAGA I' },
                { id: 5588, name: 'NYAMIYAGA II' },
                { id: 5589, name: 'RUBUMBA   I' },
                { id: 5590, name: 'RUBUMBA   II' },
              ],
            },
            {
              id: 819,
              name: 'KYENGANDO',
              villages: [
                { id: 5613, name: 'KAJU I' },
                { id: 5614, name: 'KAJU II' },
                { id: 5615, name: 'KATERAMO' },
                { id: 5616, name: 'KYAAHI' },
                { id: 5617, name: 'KYENGANDO' },
                { id: 5618, name: 'RWENGIRI I' },
                { id: 5619, name: 'RWENGIRI II' },
                { id: 5620, name: 'RWENKEIRA' },
              ],
            },
            {
              id: 818,
              name: 'RUNYINYA',
              villages: [
                { id: 5605, name: 'KABAKAIHA' },
                { id: 5606, name: 'KAMURINDA' },
                { id: 5607, name: 'KANYINYA' },
                { id: 5608, name: 'RUNYINYA' },
                { id: 5609, name: 'RWAMUHAMA' },
                { id: 5610, name: 'RWENTUHA I' },
                { id: 5611, name: 'RWENTUHA II' },
                { id: 5612, name: 'RWENYENA' },
              ],
            },
          ],
        },
        {
          id: 174,
          name: 'KYANGYENYI',
          parishes: [
            {
              id: 820,
              name: 'KAGONGI',
              villages: [
                { id: 5621, name: 'KAGONGI' },
                { id: 5622, name: 'KARYANGO' },
                { id: 5623, name: 'MUZIIRA II' },
                { id: 5624, name: 'NYAKATOOMA' },
                { id: 5625, name: 'RYAMASA I' },
                { id: 5626, name: 'RYAMASA II' },
              ],
            },
            {
              id: 821,
              name: 'KASHANJURE',
              villages: [
                { id: 5627, name: 'BUGARAMA' },
                { id: 5628, name: 'KANGORE' },
                { id: 5629, name: 'KASHANJURE I' },
                { id: 5631, name: 'KASHANJURE II' },
                { id: 5630, name: 'KIZIMBI' },
              ],
            },
            {
              id: 822,
              name: 'MASYORO',
              villages: [
                { id: 5632, name: 'KARWESHEREKA' },
                { id: 5633, name: 'MASYORO' },
                { id: 5634, name: 'MIGYEREBIRI' },
                { id: 5635, name: 'NYAKASHEBEYA' },
                { id: 5636, name: 'NYAMITOOMA' },
              ],
            },
            {
              id: 823,
              name: 'MUZIRA',
              villages: [
                { id: 5637, name: 'KAMUHANGAZA' },
                { id: 5638, name: 'MUZIRA CENTRAL' },
                { id: 5639, name: 'NYAKABAYA' },
                { id: 5640, name: 'RUSHAMBYA' },
                { id: 5641, name: 'RYAKAHUNGU I' },
                { id: 5642, name: 'RYAKAHUNGU II' },
              ],
            },
          ],
        },
        {
          id: 175,
          name: 'MASHERUKA',
          parishes: [
            {
              id: 824,
              name: 'KYABUHARAMBO',
              villages: [
                { id: 5649, name: 'KABAKYENDE' },
                { id: 5648, name: 'KEISHEGUNJU' },
                { id: 5643, name: 'KYABUHARAMBO' },
                { id: 5646, name: 'NYABWINA' },
                { id: 5645, name: 'NYAKABUNGO' },
                { id: 5650, name: 'NYAKAYOJO' },
                { id: 5647, name: 'NYAMUGABA' },
                { id: 5644, name: 'RUGARAMA' },
                { id: 5651, name: 'RUGOBA' },
              ],
            },
            {
              id: 825,
              name: 'MASHERUKA',
              villages: [
                { id: 5652, name: 'EKIJOGOMA' },
                { id: 5653, name: 'KABAARE' },
                { id: 5654, name: 'KAMUHEMBE' },
                { id: 5655, name: 'KANGORE' },
                { id: 5656, name: 'KATOJO CENTRAL' },
                { id: 5657, name: 'NYAKARONKO' },
                { id: 5658, name: 'OMUGYERA' },
                { id: 5659, name: 'RUGAZI CENTRAL' },
                { id: 5660, name: 'RUGAZI I' },
              ],
            },
          ],
        },
        {
          id: 176,
          name: 'MASHERUKA TOWN COUNCIL',
          parishes: [
            {
              id: 830,
              name: 'BURINGO WARD',
              villages: [
                { id: 5691, name: 'BURINGO I' },
                { id: 5692, name: 'BURINGO II' },
                { id: 5693, name: 'KANYUGUNYU' },
                { id: 5690, name: 'MUKONO I' },
                { id: 5694, name: 'MUKONO II' },
                { id: 5695, name: 'MUSHEKURE' },
                { id: 5696, name: 'RUSHOROZA' },
              ],
            },
            {
              id: 826,
              name: 'KABUTSYE WARD',
              villages: [
                { id: 5662, name: 'KABUTSYE I' },
                { id: 5663, name: 'KABUTSYE II' },
                { id: 5664, name: 'KAMUKONDO' },
                { id: 5661, name: 'KASHUNGA NORTH' },
                { id: 5667, name: 'KASHUNGA SOUTH' },
                { id: 5665, name: 'KATOOMA CENTRAL' },
                { id: 5666, name: 'KATOOMA EAST' },
                { id: 5668, name: 'KYAMBUBA' },
                { id: 5669, name: 'NYAKIBORERA' },
              ],
            },
            {
              id: 827,
              name: 'KANYEGANYEGYE WARD',
              villages: [
                { id: 5670, name: 'AKACENCE' },
                { id: 5671, name: 'BUGARAMA' },
                { id: 5672, name: 'IHANDA' },
                { id: 5673, name: 'KANYEGANYEGYE I' },
                { id: 5674, name: 'KANYEGANYEGYE II' },
                { id: 5675, name: 'MASHERUKA CENTRAL' },
                { id: 5677, name: 'RWEISHAMIRO' },
                { id: 5676, name: 'RWENKUBA' },
              ],
            },
            {
              id: 829,
              name: 'MABARE WARD',
              villages: [
                { id: 5683, name: 'BUBARE' },
                { id: 5684, name: 'MABAARE I' },
                { id: 5685, name: 'MABAARE II' },
                { id: 5686, name: 'NYAKANONI I' },
                { id: 5687, name: 'NYAKANONI II' },
                { id: 5688, name: 'RUSHARE' },
                { id: 5689, name: 'RWEICUMU' },
              ],
            },
            {
              id: 828,
              name: 'NYAKAMBU WARD',
              villages: [
                { id: 5682, name: 'KATWE' },
                { id: 5678, name: 'MIGYERA' },
                { id: 5679, name: 'MUTANOGA I' },
                { id: 5680, name: 'NYAKAMBU' },
                { id: 5681, name: 'NYAKAMBU T.C' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 35,
      name: 'SHEEMA COUNTY SOUTH',
      sub_counties: [
        {
          id: 181,
          name: 'BUGONGI TOWN COUNCIL',
          parishes: [
            {
              id: 848,
              name: 'ISINGIRO WARD',
              villages: [
                { id: 5842, name: 'ISINGIRO' },
                { id: 5843, name: 'KYABUYONGO' },
                { id: 64518, name: 'KYABUYONGO II' },
                { id: 5844, name: 'KYAKAJUMBA' },
                { id: 5845, name: 'MATSYA' },
                { id: 66135, name: 'MATSYA NORTH' },
                { id: 5846, name: 'NYABUBARE I' },
                { id: 5847, name: 'NYABUBARE II' },
              ],
            },
            {
              id: 849,
              name: 'KYAMURARI NORTH WARD',
              villages: [
                { id: 5848, name: 'BUGONGI T.C' },
                { id: 5849, name: 'KASHENYI' },
                { id: 5850, name: 'RUKARARWE' },
                { id: 5851, name: 'RUNYINYA I' },
                { id: 5852, name: 'RUNYINYA II' },
                { id: 5853, name: 'RWAMUGANGA' },
                { id: 5854, name: 'RWANAMA' },
                { id: 5855, name: 'RWENKURIJO' },
              ],
            },
            {
              id: 850,
              name: 'KYAMURARI SOUTH WARD',
              villages: [
                { id: 5856, name: 'BISHARARA' },
                { id: 5857, name: 'KAMUSHASHA' },
                { id: 5858, name: 'KARIKWEREZA' },
                { id: 5859, name: 'KYAMURARI' },
                { id: 5860, name: 'RUTOOMA CENTRAL' },
                { id: 5861, name: 'RWABIIZI' },
                { id: 5862, name: 'RWAKICUNDIRO' },
              ],
            },
            {
              id: 851,
              name: 'KYARIKUNDA WARD',
              villages: [
                { id: 5863, name: 'KYARUKUNDA I' },
                { id: 5864, name: 'KYARUKUNDA II' },
                { id: 5865, name: 'KYENGIRI' },
                { id: 64804, name: 'KYENGIRI CENTRAL' },
                { id: 5866, name: 'NYAKABUNGO' },
                { id: 5867, name: 'NYAKASHAMBYA' },
                { id: 69983, name: 'RUSHINYA' },
                { id: 5868, name: 'RUTUNGURU' },
              ],
            },
          ],
        },
        {
          id: 180,
          name: 'KASAANA',
          parishes: [
            {
              id: 845,
              name: 'KARUGORORA',
              villages: [
                { id: 5820, name: 'KAKIGUNDU' },
                { id: 5819, name: 'KARUGORORA' },
                { id: 5821, name: 'KYAMWENDA' },
                { id: 5822, name: 'MBAARE I' },
                { id: 5817, name: 'MBAARE II' },
                { id: 5818, name: 'NYAMATONGO' },
                { id: 5823, name: 'OMUKIBARE' },
                { id: 5824, name: 'RWEIBARE' },
              ],
            },
            {
              id: 846,
              name: 'KASAANA CENTRAL',
              villages: [
                { id: 5833, name: 'KASAANA T.C' },
                { id: 5834, name: 'KIBAATI T.C' },
                { id: 5825, name: 'KIGABA I' },
                { id: 5826, name: 'KIGABA II' },
                { id: 5827, name: 'KIHANGA  V' },
                { id: 5828, name: 'KIHANGA  VI' },
                { id: 5829, name: 'KIHANGA I' },
                { id: 5830, name: 'KIHANGA II' },
                { id: 5831, name: 'KIHANGA III' },
                { id: 5832, name: 'KIHANGA IV' },
                { id: 5835, name: 'NYAKATEETE T/C' },
                { id: 5836, name: 'NYAMAMBO II' },
              ],
            },
            {
              id: 844,
              name: 'KASAANA EAST',
              villages: [
                { id: 5814, name: 'KAGATI T.C' },
                { id: 5805, name: 'KIRUGU I' },
                { id: 5815, name: 'KIRUGU II' },
                { id: 5806, name: 'MISHENYI I' },
                { id: 5816, name: 'MISHENYI II' },
                { id: 5810, name: 'NYAKIBERE I' },
                { id: 5807, name: 'NYAKIBERE II' },
                { id: 5808, name: 'NYAKIBERE III' },
                { id: 5809, name: 'NYAKIBERE IV' },
                { id: 5811, name: 'NYAMAMBO I' },
                { id: 5812, name: 'SHENGA I' },
                { id: 5813, name: 'SHENGA II' },
              ],
            },
            {
              id: 842,
              name: 'KASAANA WEST',
              villages: [
                { id: 5793, name: 'KITUNTU  I' },
                { id: 5794, name: 'KITUNTU II' },
                { id: 5799, name: 'KITUNTU III' },
                { id: 5795, name: 'KYABIGO I' },
                { id: 5796, name: 'KYABIGO II' },
                { id: 5798, name: 'KYABIGO III' },
                { id: 5797, name: 'MWIJO' },
              ],
            },
            {
              id: 847,
              name: 'KYEIHARA',
              villages: [
                { id: 5838, name: 'NYAMISHEBEYA' },
                { id: 5839, name: 'NYANGOROGORO' },
                { id: 5840, name: 'NYARUHANGA EAST' },
                { id: 5837, name: 'NYARUHANGA WEST' },
                { id: 5841, name: 'RWAMPUNGYE' },
              ],
            },
            {
              id: 843,
              name: 'RUKONDO',
              villages: [
                { id: 5800, name: 'KASINGA' },
                { id: 5801, name: 'KYAMPETSI I' },
                { id: 5802, name: 'KYAMPETSI II' },
                { id: 5803, name: 'NYAKANYARA I' },
                { id: 5804, name: 'NYAKANYARA II' },
              ],
            },
          ],
        },
        {
          id: 178,
          name: 'KITAGATA',
          parishes: [
            {
              id: 835,
              name: 'KASHEKURO',
              villages: [
                { id: 5723, name: 'KABOBO' },
                { id: 5724, name: 'KANYEGYESHA' },
                { id: 5725, name: 'KASHASHA' },
                { id: 5726, name: 'KASHEKURO I' },
                { id: 5727, name: 'KASHEKURO II' },
                { id: 5728, name: 'KASHEKURO III' },
                { id: 5737, name: 'KASHEKURO T.C' },
                { id: 5729, name: 'KATETE' },
                { id: 5730, name: 'KIBARE' },
                { id: 5731, name: 'KITOJO I' },
                { id: 5732, name: 'KITOJO II' },
                { id: 5733, name: 'MUKO I' },
                { id: 5734, name: 'MUKO II' },
                { id: 5735, name: 'NYABUBARE I' },
                { id: 5736, name: 'NYABUBARE II' },
              ],
            },
            {
              id: 836,
              name: 'KYEIBANGA EAST',
              villages: [
                { id: 5738, name: 'KASHENYI II' },
                { id: 5739, name: 'KIBARE' },
                { id: 5740, name: 'KYARUGOME I' },
                { id: 5741, name: 'KYARUGOME II' },
                { id: 5742, name: 'KYARUGOME III' },
                { id: 5743, name: 'KYEITAMBA' },
                { id: 5744, name: 'NYAKABIRIZI I' },
                { id: 5745, name: 'NYAKABIRIZI II' },
                { id: 5746, name: 'NYAKABIRIZI III' },
              ],
            },
            {
              id: 837,
              name: 'KYEIBANGA WEST',
              villages: [
                { id: 5747, name: 'KASHENYI I' },
                { id: 5748, name: 'KATONGO I' },
                { id: 5749, name: 'KATONGO II' },
                { id: 5750, name: 'KATONGO III' },
                { id: 5751, name: 'KATONGO IV' },
                { id: 5752, name: 'KYEIBANGA  CENTRAL' },
                { id: 5753, name: 'KYEIBANGA I' },
                { id: 5754, name: 'NYARUTOMA' },
              ],
            },
          ],
        },
        {
          id: 183,
          name: 'KITAGATA TOWN COUNCIL',
          parishes: [
            {
              id: 856,
              name: 'BURARO WARD',
              villages: [
                { id: 5899, name: 'BURARO I' },
                { id: 5900, name: 'BURARO II' },
                { id: 5901, name: 'BURARO III' },
                { id: 5902, name: 'IRENGYERO' },
                { id: 5903, name: 'KIKORE I' },
                { id: 5904, name: 'KIKORE II' },
                { id: 5905, name: 'NYAKIGYERA' },
              ],
            },
            {
              id: 857,
              name: 'KYARUSHAKARA WARD',
              villages: [
                { id: 5906, name: 'BWOOMA I' },
                { id: 5907, name: 'BWOOMA II' },
                { id: 5908, name: 'BWOOMA III' },
                { id: 5909, name: 'KATOOMA' },
                { id: 5910, name: 'KINYEMI' },
                { id: 5911, name: 'MASHAMBU  I' },
                { id: 5912, name: 'MASHAMBU  II' },
                { id: 5913, name: 'MURAMA' },
              ],
            },
            {
              id: 859,
              name: 'MAREMBO WARD',
              villages: [
                { id: 5922, name: 'IBANGA  I' },
                { id: 5923, name: 'IBANGA II' },
                { id: 5924, name: 'KIMONDO  I' },
                { id: 5925, name: 'KIMONDO  II' },
                { id: 5926, name: 'KITAGATA  HOSPITAL' },
                { id: 5928, name: 'KITAGATA  MARKET' },
                { id: 5927, name: 'KITAGATA  T/C EAST' },
                { id: 5929, name: 'KITAGATA  T/C WEST' },
              ],
            },
            {
              id: 858,
              name: 'MUHITO NORTH WARD',
              villages: [
                { id: 5914, name: 'KAMBUGYE I' },
                { id: 5915, name: 'KAMBUGYE II' },
                { id: 5916, name: 'KIGAZI' },
                { id: 5917, name: 'KIINA' },
                { id: 5918, name: 'MASHENGA  I' },
                { id: 5919, name: 'MASHENGA  II' },
                { id: 5920, name: 'NYAKAZINGA' },
                { id: 5921, name: 'NYAMIYAGA' },
              ],
            },
            {
              id: 860,
              name: 'MUHITO SOUTH WARD',
              villages: [
                { id: 5930, name: 'BIHANDA' },
                { id: 5931, name: 'KATUUBA I' },
                { id: 5932, name: 'KATUUBA II' },
                { id: 5933, name: 'KATUUBA III' },
                { id: 5934, name: 'KIBINGO I' },
                { id: 5935, name: 'KIBINGO II' },
                { id: 5936, name: 'NYAKASA I' },
                { id: 5937, name: 'NYAKASA II' },
              ],
            },
            {
              id: 861,
              name: 'RUTOMA WARD',
              villages: [
                { id: 5938, name: 'BUBAARE I' },
                { id: 5939, name: 'BUBAARE II' },
                { id: 5944, name: 'BUBAARE III' },
                { id: 5940, name: 'NYAKATUNTU' },
                { id: 5941, name: 'RUKONDO I' },
                { id: 5942, name: 'RUKONDO II' },
                { id: 5943, name: 'RUTOOMA' },
              ],
            },
          ],
        },
        {
          id: 182,
          name: 'RUGARAMA',
          parishes: [
            {
              id: 852,
              name: 'NYAKARAMA NORTH',
              villages: [
                { id: 5869, name: 'KINOGO' },
                { id: 5871, name: 'KISIIZI' },
                { id: 5870, name: 'KISIZI CENTRAL' },
                { id: 5872, name: 'KIYANGA' },
                { id: 5874, name: 'NYAKABARE' },
                { id: 68029, name: 'NYAKARAMA CENTRAL' },
                { id: 5875, name: 'NYAKATOOKYE' },
                { id: 5876, name: 'RWABARUMI' },
                { id: 5877, name: 'RWAMUNENA I' },
                { id: 5873, name: 'RWAMUNENA II' },
              ],
            },
            {
              id: 855,
              name: 'NYAKARAMA SOUTH',
              villages: [
                { id: 5892, name: 'BIGONA I' },
                { id: 5894, name: 'BIGONA II' },
                { id: 5893, name: 'IRASHAGYE' },
                { id: 5897, name: 'KAMATUNGURU' },
                { id: 5895, name: 'KYAMANENGYERE I' },
                { id: 5896, name: 'KYAMANENGYERE II' },
                { id: 5898, name: 'RUBAARE' },
              ],
            },
            {
              id: 854,
              name: 'NYAKASHOGA',
              villages: [
                { id: 5885, name: 'KABWA' },
                { id: 5886, name: 'NYAKAHANGA' },
                { id: 5887, name: 'NYAKASHOGA I' },
                { id: 5888, name: 'NYAKASHOGA II' },
                { id: 5889, name: 'RUGARAMA II' },
                { id: 5890, name: 'RUHOROBERO I' },
                { id: 5891, name: 'RUHOROBERO II' },
              ],
            },
            {
              id: 853,
              name: 'RUGARAMA',
              villages: [
                { id: 5878, name: 'KAZIKO' },
                { id: 5879, name: 'MUGONDO' },
                { id: 5880, name: 'MURARI  I' },
                { id: 5881, name: 'MURARI II' },
                { id: 5882, name: 'NTUNGAMO I' },
                { id: 5883, name: 'NTUNGAMO II' },
                { id: 5884, name: 'RUGARAMA I' },
              ],
            },
          ],
        },
        {
          id: 179,
          name: 'SHUUKU',
          parishes: [
            {
              id: 838,
              name: 'KISHABYA',
              villages: [
                { id: 5756, name: 'KEIJURIRO' },
                { id: 63745, name: 'KINOGO' },
                { id: 5757, name: 'KISHABYA I' },
                { id: 5755, name: 'KISHABYA II' },
                { id: 5758, name: 'KISHABYA T.C EAST' },
                { id: 5759, name: 'KISHAMBYA T.C WEST' },
                { id: 63924, name: 'KISIIZI' },
                { id: 63935, name: 'KISIZI CENTRAL' },
                { id: 64139, name: 'KIYANGA' },
                { id: 5760, name: 'KYENJOJO I' },
                { id: 5762, name: 'KYENJOJO II' },
                { id: 67974, name: 'NYAKABARE' },
                { id: 5761, name: 'NYAKABWERA' },
                { id: 68077, name: 'NYAKATOKYE' },
                { id: 5763, name: 'NYAKATOOKYE' },
                { id: 5764, name: 'NYAKIZINGA I' },
                { id: 5765, name: 'NYAKIZINGA II' },
                { id: 5766, name: 'RWAKABAGURE' },
                { id: 70078, name: 'RWAMUNENA I' },
                { id: 70079, name: 'RWAMUNENA II' },
                { id: 5767, name: 'RYAKASINGA' },
              ],
            },
            {
              id: 839,
              name: 'KYEMPITSI EAST',
              villages: [
                { id: 5770, name: 'AKATEMBO' },
                { id: 5768, name: 'BUZIIMA' },
                { id: 5769, name: 'KIBARUKO' },
                { id: 5771, name: 'KIYAAYO' },
                { id: 5772, name: 'NYAKIHANGA' },
                { id: 5773, name: 'NYAMABAARE' },
                { id: 5774, name: 'RUBANGA' },
                { id: 5775, name: 'RWAMAMYA' },
              ],
            },
            {
              id: 840,
              name: 'KYEMPITSI WEST',
              villages: [
                { id: 5776, name: 'KABURA' },
                { id: 5778, name: 'KYEMPITSI' },
                { id: 5779, name: 'MAILO' },
                { id: 5777, name: 'MAILO T.C' },
                { id: 5780, name: 'NGOMA' },
                { id: 5781, name: 'NYARUHANGA' },
                { id: 5782, name: 'RUGOROGORO' },
                { id: 5783, name: 'RUTOOMA' },
              ],
            },
            {
              id: 841,
              name: 'RWABUZA',
              villages: [
                { id: 5784, name: 'KAGOROGORO' },
                { id: 5785, name: 'KAMWERU' },
                { id: 5787, name: 'KIGARAMA' },
                { id: 5790, name: 'KYAMABAARE' },
                { id: 5786, name: 'NYAKAHITA' },
                { id: 5791, name: 'NYAKAJUMO' },
                { id: 5788, name: 'NYARWIGA' },
                { id: 5792, name: 'RWABUZA' },
                { id: 5789, name: 'RWABUZA T.C' },
              ],
            },
          ],
        },
        { id: 2117, name: 'SHUUKU TOWN COUNCIL', parishes: [] },
      ],
    },
    {
      id: 36,
      name: 'SHEEMA MUNICIPALITY',
      sub_counties: [
        {
          id: 184,
          name: 'KABWOHE DIVISION',
          parishes: [
            {
              id: 863,
              name: 'KABWOHE WARD',
              villages: [
                { id: 5952, name: 'ISHEKYE B' },
                { id: 5953, name: 'KABWOHE HILL' },
                { id: 5954, name: 'KABWOHE MARKET' },
                { id: 5956, name: 'KABWOHE MISSION' },
                { id: 5955, name: 'KAKINGA' },
                { id: 5958, name: 'KAMWEZI B' },
                { id: 5957, name: 'KEMICEERA' },
                { id: 5959, name: 'NYARUHANGA' },
              ],
            },
            {
              id: 866,
              name: 'KAKUNYU WARD',
              villages: [
                { id: 5990, name: 'BURARAMA' },
                { id: 5991, name: 'KABWOHE CENTRAL' },
                { id: 5986, name: 'KABWOHE TOWN B' },
                { id: 5987, name: 'KAKUNYU' },
                { id: 5988, name: 'NYAKABWERA' },
                { id: 5989, name: 'RYAMUHUNGA' },
              ],
            },
            {
              id: 862,
              name: 'KYAGAJU WARD',
              villages: [
                { id: 5945, name: 'KABAARE' },
                { id: 5946, name: 'KAKINDO' },
                { id: 5947, name: 'KATEETE' },
                { id: 5948, name: 'KATOOMA' },
                { id: 5949, name: 'KYAGAJU CENTRAL' },
                { id: 5950, name: 'KYENKUNGA' },
                { id: 5951, name: 'MABAARE' },
              ],
            },
            {
              id: 865,
              name: 'NYANGA WARD',
              villages: [
                { id: 5979, name: 'KIGIMBI EAST' },
                { id: 5980, name: 'KYAMATONGO' },
                { id: 5977, name: 'MABANGA' },
                { id: 5978, name: 'MAILO 4' },
                { id: 5981, name: 'NYANGA CENTRAL' },
                { id: 5982, name: 'NYANGA EAST' },
                { id: 5983, name: 'RUSHOROZA EAST' },
                { id: 5985, name: 'RUSHOROZA WEST' },
                { id: 5984, name: 'RWEMIKO' },
              ],
            },
            {
              id: 864,
              name: 'RUSHOZI WARD',
              villages: [
                { id: 5960, name: 'AHABUGAMBA' },
                { id: 5962, name: 'KAHAAMA' },
                { id: 5961, name: 'KAHAMA' },
                { id: 5963, name: 'KANYAMATAMBARA' },
                { id: 5964, name: 'KAYANJA EAST' },
                { id: 5965, name: 'KAYANJA WEST' },
                { id: 5966, name: 'KIBUTAMO I' },
                { id: 5967, name: 'KIBUTAMO II' },
                { id: 5968, name: 'KYERIMA' },
                { id: 5969, name: 'MAHEEGA' },
                { id: 5970, name: 'MIGAMBA' },
                { id: 5971, name: 'MUZIRIGYEMBE  I' },
                { id: 5972, name: 'MUZIRIGYEMBE  II' },
                { id: 5973, name: 'NCWEZI' },
                { id: 5974, name: 'NYABIREEREMA' },
                { id: 5975, name: 'RUSHOZI CENTRAL' },
                { id: 5976, name: 'RWENTAKA' },
              ],
            },
            {
              id: 867,
              name: 'RUTOOMA WARD',
              villages: [
                { id: 5992, name: 'ISHEKYE A' },
                { id: 5993, name: 'KABWOHE TOWN A' },
                { id: 5994, name: 'KAMWEZI A' },
                { id: 5995, name: 'KITOOHWA EAST' },
                { id: 5996, name: 'NYABISHERA' },
                { id: 5997, name: 'NYAMIYAGA' },
                { id: 5998, name: 'RUTOOMA' },
              ],
            },
          ],
        },
        {
          id: 185,
          name: 'KAGANGO DIVISION',
          parishes: [
            {
              id: 868,
              name: 'ITENDERO WARD',
              villages: [
                { id: 5999, name: 'ITENDERO EAST' },
                { id: 6000, name: 'ITENDERO TOWN A' },
                { id: 6001, name: 'ITENDERO WEST' },
                { id: 6002, name: 'KAKINDO' },
                { id: 6003, name: 'KYAMUNGWE A' },
                { id: 6004, name: 'KYAMUNGWE B' },
                { id: 6005, name: 'RWEITAAMIRO' },
              ],
            },
            {
              id: 872,
              name: 'KANYINASHEEMA WARD',
              villages: [
                { id: 6050, name: 'KANYINASHEEMA A' },
                { id: 6049, name: 'KANYINASHEEMA B' },
                { id: 6051, name: 'KATOOMA' },
                { id: 6052, name: 'RWABUTURA' },
                { id: 6053, name: 'RWEMBOGO' },
                { id: 6054, name: 'RWENTUNDA' },
              ],
            },
            {
              id: 869,
              name: 'KIHUNDA WARD',
              villages: [
                { id: 6006, name: 'BUSHENYI' },
                { id: 6007, name: 'BWAMBARI' },
                { id: 6008, name: 'KAGONGI' },
                { id: 6009, name: 'KAHURURWA' },
                { id: 6010, name: 'KANONI' },
                { id: 6011, name: 'KARUHAMA' },
                { id: 6012, name: 'KYARINO' },
                { id: 6013, name: 'MUYENJE' },
                { id: 6014, name: 'NYAKIZINGA' },
                { id: 6015, name: 'NYAMIKO' },
                { id: 6016, name: 'NYAMPIKYE' },
                { id: 6017, name: 'OBUKUUBO' },
                { id: 6018, name: 'OBURAMA' },
                { id: 6019, name: 'RWEMBIRIZI' },
                { id: 6020, name: 'RWEMBOGO' },
              ],
            },
            {
              id: 870,
              name: 'KIZIBA WARD',
              villages: [
                { id: 6021, name: 'BISHARARA' },
                { id: 6022, name: 'BUNYAGONGO' },
                { id: 6023, name: 'BUTAGATSI' },
                { id: 6024, name: 'BWOTSYA' },
                { id: 6025, name: 'KAGOROGORO' },
                { id: 6026, name: 'KIZIBA' },
                { id: 6027, name: 'MBAGWA' },
                { id: 6028, name: 'NGOMA' },
                { id: 6029, name: 'NTUNGAMO' },
                { id: 6030, name: 'NYAKACEMBA' },
                { id: 6031, name: 'NYAMIRIMA' },
                { id: 6032, name: 'RUBANGA' },
                { id: 6033, name: 'RUBARE' },
                { id: 6034, name: 'RUSHOROZA' },
                { id: 6035, name: 'RWENGANDO' },
                { id: 6036, name: 'RWENGANDO TRADING CENTRE' },
                { id: 6037, name: 'RWENKARABO' },
              ],
            },
            {
              id: 871,
              name: 'MIGINA WARD',
              villages: [
                { id: 6043, name: 'AKAPEERA' },
                { id: 6038, name: 'KABURA' },
                { id: 6039, name: 'KAGANGO' },
                { id: 6040, name: 'KINYAMUGUSHA' },
                { id: 6041, name: 'KIYAGAYAGA' },
                { id: 6042, name: 'MASHOJWA' },
                { id: 6044, name: 'MUTOJO' },
                { id: 6046, name: 'NYABUHAMA II' },
                { id: 6045, name: 'NYAKABIRA' },
                { id: 6047, name: 'RUGASHA' },
                { id: 6048, name: 'RWENKUBA' },
              ],
            },
            {
              id: 873,
              name: 'NDEEBO WARD',
              villages: [
                { id: 6055, name: 'KABINGO' },
                { id: 6058, name: 'MIHAMBO' },
                { id: 6059, name: 'NDEEBO' },
                { id: 6056, name: 'NDEEBO CENTRAL' },
                { id: 6057, name: 'NDEEBO WEST' },
                { id: 6060, name: 'NYABUHAMA I' },
              ],
            },
            {
              id: 874,
              name: 'RWENSHAMA WARD',
              villages: [
                { id: 6062, name: 'ITENDERO TOWN B' },
                { id: 6061, name: 'KAGANGO' },
                { id: 6063, name: 'KAINA-RWENGANDO' },
                { id: 6064, name: 'KISHENYI' },
                { id: 6066, name: 'NKOKONJERU' },
                { id: 6065, name: 'RWENSHAMA' },
              ],
            },
          ],
        },
        {
          id: 186,
          name: 'KASHOZI DIVISION',
          parishes: [
            {
              id: 876,
              name: 'KARERA NORTH WARD',
              villages: [
                { id: 6074, name: 'KARERA I' },
                { id: 6075, name: 'KIKONKO' },
                { id: 6076, name: 'KISOROZA EAST' },
                { id: 6077, name: 'KISOROZA WEST' },
                { id: 6078, name: 'NYAKARAIRE' },
                { id: 6079, name: 'RUTOOMA' },
                { id: 6080, name: 'RWABAGYENDA' },
                { id: 6081, name: 'RWAMURUNGURA' },
              ],
            },
            {
              id: 877,
              name: 'KARERA SOUTH WARD',
              villages: [
                { id: 6082, name: 'ITEGYERO' },
                { id: 6083, name: 'KARUBANZA EAST' },
                { id: 6084, name: 'KARUBANZA WEST' },
                { id: 6085, name: 'KASHUNGA' },
                { id: 6086, name: 'KYAKAKOOTE' },
                { id: 6087, name: 'RURAMA' },
                { id: 6088, name: 'RUTUNGURU' },
                { id: 6089, name: 'RWAKIZIBWA' },
              ],
            },
            {
              id: 878,
              name: 'KASHOZI CENTRAL WARD',
              villages: [
                { id: 6091, name: 'BUTSIBO II' },
                { id: 6092, name: 'KACERERE' },
                { id: 6090, name: 'KAKOROGOTO CENTRAL' },
                { id: 6093, name: 'KAKOROGOTO EAST' },
                { id: 6094, name: 'KAKOROGOTO WEST' },
                { id: 6096, name: 'KITOOKYE' },
                { id: 6097, name: 'KYEMBUGU' },
                { id: 6095, name: 'RUNYINYA II' },
              ],
            },
            {
              id: 875,
              name: 'KASHOZI EAST WARD',
              villages: [
                { id: 6068, name: 'KANEKYE' },
                { id: 6069, name: 'KIYUUYA I' },
                { id: 6070, name: 'KIYUUYA II' },
                { id: 6071, name: 'NSHUNGYEZI I' },
                { id: 6067, name: 'NSHUNGYEZI II' },
                { id: 6072, name: 'NYAMIRIMA' },
                { id: 6073, name: 'RUNYINYA I' },
              ],
            },
            {
              id: 879,
              name: 'KASHOZI WEST WARD',
              villages: [
                { id: 6099, name: 'BUTSIBO CENTRAL' },
                { id: 6098, name: 'BUTSIBO I' },
                { id: 6102, name: 'KANYAMUKONDO T/C' },
                { id: 6103, name: 'KYAKASA' },
                { id: 6104, name: 'RUTUNGURU' },
                { id: 6101, name: 'RWANYAMUKYINYA T/C' },
                { id: 6105, name: 'RWEIGAGA I' },
                { id: 6106, name: 'RWEIGAGA II' },
                { id: 6100, name: 'RWEIGAGA III' },
              ],
            },
          ],
        },
        {
          id: 187,
          name: 'SHEEMA CENTRAL DIVISION',
          parishes: [
            {
              id: 884,
              name: 'KITOJO WARD',
              villages: [
                { id: 6154, name: 'KAHAMA' },
                { id: 6155, name: 'KAMBUGU I' },
                { id: 6156, name: 'KAMBUGU II' },
                { id: 6157, name: 'KATAGATA' },
                { id: 6158, name: 'KITOJO I' },
                { id: 6159, name: 'KITOJO II' },
                { id: 6160, name: 'KITOJO III' },
                { id: 6161, name: 'KYAMUKUMA I' },
                { id: 6162, name: 'KYAMUKUMA II' },
                { id: 6163, name: 'MUTOJO I' },
                { id: 6164, name: 'MUTOJO II' },
                { id: 6165, name: 'MUTOJO III' },
                { id: 6166, name: 'RUGARAMA I' },
                { id: 6167, name: 'RUGARAMA II' },
                { id: 6168, name: 'RUGARAMA III' },
                { id: 6169, name: 'RUGARAMA IV' },
                { id: 6170, name: 'RUSHOROZA I' },
                { id: 6171, name: 'RUSHOROZA II' },
                { id: 6172, name: 'RUSHOROZA III' },
              ],
            },
            {
              id: 880,
              name: 'KYABANDARA WARD',
              villages: [
                { id: 6107, name: 'BUBAARE' },
                { id: 6108, name: 'BUGARAMA' },
                { id: 6109, name: 'KATWE' },
                { id: 6110, name: 'KIBUTAMO' },
                { id: 6111, name: 'KIKONGORO' },
                { id: 6112, name: 'KITEETE' },
                { id: 6113, name: 'KYABANDARA CENTRAL' },
                { id: 6114, name: 'MIKYERERE' },
                { id: 6115, name: 'RUNYINYA' },
                { id: 6116, name: 'RUSHOGASHOGA' },
                { id: 6117, name: 'RWANKORERA' },
                { id: 6118, name: 'RWEMIYAGA' },
                { id: 6119, name: 'RWEYESHERA' },
              ],
            },
            {
              id: 881,
              name: 'NYAKASHAMBYA WARD',
              villages: [
                { id: 6120, name: 'KARUSHANGA' },
                { id: 6121, name: 'KIBINGO' },
                { id: 6122, name: 'KYENKWANZI' },
                { id: 6123, name: 'MISHENYI' },
                { id: 6124, name: 'NYAKASHAMBYA' },
                { id: 6125, name: 'RUGONGI' },
              ],
            },
            {
              id: 882,
              name: 'NYARWESHAMA WARD',
              villages: [
                { id: 6126, name: 'BUTARUMWA' },
                { id: 6127, name: 'KACWAMBA' },
                { id: 6128, name: 'KAGONGI' },
                { id: 6129, name: 'KARINDAMUHORO' },
                { id: 6130, name: 'KARUSHEGU' },
                { id: 6131, name: 'KATERAMO' },
                { id: 6132, name: 'KEIJENGYE' },
                { id: 6133, name: 'KITEETE' },
                { id: 6134, name: 'KITOOHWA WEST' },
                { id: 6135, name: 'MUSHANGA' },
                { id: 6136, name: 'MUSHANGA CENTRAL' },
                { id: 6137, name: 'NYAKANYINYA' },
                { id: 6138, name: 'NYAKASHEBEYA' },
                { id: 6139, name: 'NYAMUFUMURA' },
                { id: 6140, name: 'RUBAARE' },
                { id: 6141, name: 'RUGARAMA' },
                { id: 6142, name: 'RUKANJA' },
                { id: 6143, name: 'RWEMIJUUJU' },
              ],
            },
            {
              id: 883,
              name: 'RWAMUJOJO WARD',
              villages: [
                { id: 6144, name: 'AHANKUNGU' },
                { id: 6145, name: 'BUTAGATSI' },
                { id: 6146, name: 'KABARE' },
                { id: 6147, name: 'KABINGO' },
                { id: 6148, name: 'KAMABARE' },
                { id: 6149, name: 'KATOOKYE' },
                { id: 6150, name: 'NYAMITOOMA' },
                { id: 6151, name: 'NYARUBUNGO' },
                { id: 6152, name: 'RWAMUJOJO' },
                { id: 6153, name: 'RWANYINAKIHAIRE' },
              ],
            },
          ],
        },
      ],
    },
  ],
};
