import { District } from '../types';

export default {
  id: 67,
  name: 'TORORO',
  counties: [
    {
      id: 163,
      name: 'TORORO MUNICIPALITY',
      sub_counties: [
        {
          id: 1003,
          name: 'TORORO EASTERN',
          parishes: [
            {
              id: 4618,
              name: 'AMAGORO A',
              villages: [
                { id: 30002, name: 'AMAGORO A CENTRAL' },
                { id: 30003, name: 'AMAGORO A NORTH' },
                { id: 30004, name: 'AMAGORO A SOUTH' },
                { id: 30005, name: 'MANJASI HIGH SCHOOL' },
                { id: 30006, name: 'SENIOR QUARTERS' },
              ],
            },
            {
              id: 4619,
              name: 'AMAGORO B',
              villages: [
                { id: 30007, name: 'AMAGORO B CENTRAL' },
                { id: 30008, name: 'AMAGORO B NORTH' },
                { id: 30009, name: 'AMAGORO B SOUTH' },
                { id: 30010, name: 'TORORO GIRLS SCHOOL' },
              ],
            },
            {
              id: 4621,
              name: 'KASOLI',
              villages: [
                { id: 30015, name: 'KASOLI' },
                { id: 30019, name: 'KASOLI EAST' },
                { id: 30016, name: 'MEDICAL QUARTERS' },
                { id: 30020, name: 'OGOLLA' },
                { id: 30017, name: 'POLICE QUARTERS' },
                { id: 30018, name: 'RAILWAY QUARTERS' },
              ],
            },
            {
              id: 4620,
              name: 'NYANGOLE',
              villages: [
                { id: 30011, name: 'BENEDICTINE FATHERS' },
                { id: 30012, name: 'NYANGOLE A' },
                { id: 30013, name: 'NYANGOLE B' },
                { id: 30014, name: 'ST. PETERS COLLEGE' },
              ],
            },
          ],
        },
        {
          id: 1004,
          name: 'TORORO WESTERN',
          parishes: [
            {
              id: 4622,
              name: 'AGURURU A',
              villages: [
                { id: 30021, name: 'AGURURU AI' },
                { id: 30022, name: 'AGURURU AII' },
                { id: 30023, name: 'AGURURU AIII' },
              ],
            },
            {
              id: 4623,
              name: 'AGURURU B',
              villages: [
                { id: 30024, name: 'AGURURU BI' },
                { id: 30025, name: 'AGURURU BII' },
                { id: 30026, name: 'AGURURU BIII' },
              ],
            },
            {
              id: 4624,
              name: 'BISON/MAGURIA',
              villages: [
                { id: 30027, name: 'BISON   A' },
                { id: 30028, name: 'BISON   B' },
                { id: 30029, name: 'BISON C JUBA' },
              ],
            },
            {
              id: 4625,
              name: 'CENTRAL',
              villages: [
                { id: 30030, name: 'CENTRAL WARD' },
                { id: 30031, name: 'SOUTH  CENTRAL  EAST' },
                { id: 30032, name: 'SOUTH  CENTRAL  WEST' },
                { id: 30033, name: 'WATER VILLAGE' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 164,
      name: 'TORORO NORTH COUNTY',
      sub_counties: [
        {
          id: 1008,
          name: 'AKADOT',
          parishes: [
            {
              id: 4643,
              name: 'AKADOT',
              villages: [
                { id: 30128, name: 'AKADOT A' },
                { id: 30129, name: 'AKADOT B' },
                { id: 57699, name: 'AKADOT C' },
                { id: 57700, name: 'AKADOT CENTREAL' },
                { id: 57702, name: 'AKADOT WEST' },
                { id: 30130, name: 'ATIRI A' },
                { id: 30131, name: 'ATIRI B' },
                { id: 30132, name: 'NYAKOLI A' },
                { id: 68113, name: 'NYAKOLI B' },
              ],
            },
            {
              id: 4641,
              name: 'KABIRO',
              villages: [
                { id: 58646, name: 'ATIRI A' },
                { id: 58647, name: 'ATIRI B' },
                { id: 30122, name: 'BENDO A' },
                { id: 59033, name: 'BENDO B' },
                { id: 30123, name: 'KATEKI' },
                { id: 64401, name: 'KURUK' },
                { id: 30124, name: 'MORUWA' },
              ],
            },
            {
              id: 4644,
              name: 'KAMULI',
              villages: [
                { id: 30133, name: 'LOLI A' },
                { id: 65414, name: 'LOLI B' },
                { id: 65415, name: 'LOLI C' },
                { id: 30134, name: 'ONGURAI EAST' },
                { id: 30137, name: 'ONGURAI WEST' },
                { id: 30135, name: 'PAGOYA A' },
                { id: 69474, name: 'PAGOYA B' },
                { id: 30136, name: 'RARAKA' },
                { id: 69802, name: 'RARAKA A' },
                { id: 69804, name: 'RARAKA B' },
                { id: 69806, name: 'RARAKA CENTRAL' },
              ],
            },
            {
              id: 4642,
              name: 'KAYORO',
              villages: [
                { id: 30125, name: 'KAYORO A' },
                { id: 30126, name: 'KAYORO B' },
                { id: 63240, name: 'KAYORO C' },
                { id: 63241, name: 'KAYORO CENTRAL' },
                { id: 63242, name: 'KAYORO D' },
                { id: 30127, name: 'SERE A' },
                { id: 70311, name: 'SERE B' },
              ],
            },
            {
              id: 4640,
              name: 'MORUKONYANGAI',
              villages: [
                { id: 30118, name: 'KATHOWA A' },
                { id: 63084, name: 'KATHOWA B' },
                { id: 30119, name: 'KINOM' },
                { id: 63746, name: 'KINOM EAST' },
                { id: 63747, name: 'KINOM WEST' },
                { id: 64402, name: 'KURUK CENTRAL' },
                { id: 30120, name: 'MORUKONYANGAI A' },
                { id: 30121, name: 'MORUKONYANGAI B' },
                { id: 66402, name: 'MORUKONYANGAI C' },
              ],
            },
          ],
        },
        {
          id: 1005,
          name: 'APETAI',
          parishes: [
            {
              id: 4626,
              name: 'AUKOT',
              villages: [
                { id: 30034, name: 'AGURURU A' },
                { id: 57586, name: 'AGURURU B' },
                { id: 30035, name: 'ALUPE A' },
                { id: 58075, name: 'ALUPE B' },
                { id: 30036, name: 'KANGINIMA A' },
                { id: 62527, name: 'KANGINIMA B' },
                { id: 68683, name: 'OKIPORO' },
                { id: 30037, name: 'OPULE A' },
                { id: 69146, name: 'OPULE B' },
                { id: 69800, name: 'RARAK' },
                { id: 30038, name: 'RARAKA-AUKOT' },
              ],
            },
            {
              id: 4630,
              name: 'KALACHAI',
              villages: [
                { id: 57792, name: 'AKIRIAMET' },
                { id: 30052, name: 'ATAPARA A' },
                { id: 58606, name: 'ATAPARA B' },
                { id: 30053, name: 'KALACHAI A' },
                { id: 30054, name: 'KALACHAI B' },
                { id: 62277, name: 'KALACHAI C' },
                { id: 30055, name: 'KAREU' },
                { id: 30056, name: 'KATEKI' },
                { id: 30057, name: 'KOGALA A' },
                { id: 64197, name: 'KOGALA B' },
                { id: 69803, name: 'RARAKA A' },
                { id: 69805, name: 'RARAKA B' },
              ],
            },
            {
              id: 4627,
              name: 'KOCHOGE',
              villages: [
                { id: 30039, name: 'ADEREMA A' },
                { id: 57429, name: 'ADEREMA B' },
                { id: 63056, name: 'KATEKI' },
                { id: 63386, name: 'KIBOKO' },
                { id: 64184, name: 'KOCHOGE A' },
                { id: 64185, name: 'KOCHOGE B' },
                { id: 30040, name: 'OBURI A' },
                { id: 68384, name: 'OBURI B' },
                { id: 30041, name: 'OGIROI A' },
                { id: 68557, name: 'OGIROI B' },
              ],
            },
            {
              id: 4629,
              name: 'PETTA',
              villages: [
                { id: 30047, name: 'KATEKI A' },
                { id: 63060, name: 'KATEKI B' },
                { id: 30048, name: 'KOKIMA A' },
                { id: 64210, name: 'KOKIMA B' },
                { id: 30049, name: 'OKIPORO' },
                { id: 30050, name: 'PETTA A' },
                { id: 69671, name: 'PETTA B' },
                { id: 69808, name: 'RARAKA I' },
                { id: 30051, name: 'RARAKA II' },
              ],
            },
            {
              id: 10373,
              name: 'TOTOKIDWE',
              villages: [
                { id: 57551, name: 'AGOGOMIT B' },
                { id: 57864, name: 'AKURIKIT B' },
                { id: 67737, name: 'NGELECHOM B' },
                { id: 70815, name: 'TOTOKIDWE C' },
                { id: 70816, name: 'TOTOKIDWE E' },
              ],
            },
            {
              id: 4628,
              name: 'TOTOKODWE',
              villages: [
                { id: 30042, name: 'AGOGOMIT A' },
                { id: 30043, name: 'AKURIKIT A' },
                { id: 30044, name: 'NGELECHOM A' },
                { id: 30045, name: 'TOTOKIDWE A' },
                { id: 30046, name: 'TOTOKIDWE B' },
              ],
            },
          ],
        },
        {
          id: 1009,
          name: 'MERIKIT',
          parishes: [
            {
              id: 4647,
              name: 'AMURWO',
              villages: [
                { id: 30158, name: 'AKAPU' },
                { id: 30159, name: 'AMARWO TRIANGLE' },
                { id: 30160, name: 'IPUREGE' },
                { id: 30161, name: 'KACHOLIA' },
                { id: 30162, name: 'KALUNGU' },
                { id: 30163, name: 'MBOGO' },
                { id: 30164, name: 'NANKATA' },
              ],
            },
            {
              id: 4648,
              name: 'APOKOR',
              villages: [
                { id: 30165, name: 'APOKOR SOUTH' },
                { id: 30167, name: 'APOKOR SOUTH WEST' },
                { id: 30166, name: 'APOKOR TRADING CENTRE' },
                { id: 30168, name: 'ASINGE CENTRE' },
                { id: 30169, name: 'ASINGE EAST' },
                { id: 30170, name: 'ASINGE WEST' },
              ],
            },
            {
              id: 4649,
              name: 'KACHINGA',
              villages: [
                { id: 30181, name: 'AGURURU' },
                { id: 30171, name: 'KACHINGA CENTRAL' },
                { id: 30172, name: 'KACHINGA EAST' },
                { id: 30173, name: 'KACHINGA NORTH' },
                { id: 30174, name: 'KACHINGA NORTH EAST' },
                { id: 30175, name: 'KACHINGA SOUTH' },
                { id: 30176, name: 'KACHINGA WEST' },
                { id: 30177, name: 'KARWOK' },
                { id: 30178, name: 'MAGORO NORTH' },
                { id: 30179, name: 'MAGORO SOUTH' },
                { id: 30182, name: 'MERIKIT KENYA' },
                { id: 30180, name: 'RAMOGI' },
              ],
            },
            {
              id: 4645,
              name: 'MALIRI',
              villages: [
                { id: 30138, name: 'ALUPE  A' },
                { id: 30139, name: 'ALUPE  B' },
                { id: 30140, name: 'AMONI   B' },
                { id: 30141, name: 'AMONI  A' },
                { id: 30142, name: 'AROWA   A' },
                { id: 30143, name: 'AROWA  B' },
                { id: 30144, name: 'AROWA  NORTH' },
                { id: 30145, name: 'MALIRI  AGGE' },
                { id: 30146, name: 'MALIRI  CENTRE A' },
                { id: 30147, name: 'MALIRI  CENTRE B' },
              ],
            },
            {
              id: 4646,
              name: 'MERIKIT',
              villages: [
                { id: 30148, name: 'MEREKIT CENTRE' },
                { id: 30150, name: 'OTIROK  WEST' },
                { id: 30149, name: 'OTIROK EAST' },
                { id: 30151, name: 'PARANGANG NORTH' },
                { id: 30152, name: 'PARANGANG RUWA' },
                { id: 30153, name: 'PARANGANG SOUTH' },
                { id: 30154, name: 'SESEME - MUKUMERI' },
                { id: 30155, name: 'SESEME CENTRAL' },
                { id: 30156, name: 'SESEME NORTH CENTRAL' },
                { id: 30157, name: 'SESEME SOUTH' },
              ],
            },
          ],
        },
        {
          id: 1006,
          name: 'MOLO',
          parishes: [
            {
              id: 4631,
              name: 'KIDOKO',
              villages: [
                { id: 30058, name: 'ABWAL A' },
                { id: 30064, name: 'ABWAL B' },
                { id: 30059, name: 'AKADOT' },
                { id: 30060, name: 'KARWOK' },
                { id: 30061, name: 'KIDOKO EAST' },
                { id: 30062, name: 'KIDOKO ROCK' },
                { id: 30063, name: 'KIDOKO WEST' },
              ],
            },
            {
              id: 4633,
              name: 'KIPANGOR',
              villages: [
                { id: 30076, name: 'KIPANGOR A' },
                { id: 30077, name: 'KIPANGOR B' },
                { id: 30078, name: 'KIPANGOR C' },
                { id: 30079, name: 'KIPANGOR D' },
                { id: 30080, name: 'NYEMINYEM A' },
                { id: 30081, name: 'NYEMINYEM B' },
                { id: 30082, name: 'PAPAKOL EAST' },
                { id: 30083, name: 'PAPAKOL WEST' },
              ],
            },
            {
              id: 4632,
              name: 'MOLO',
              villages: [
                { id: 30065, name: 'AKIRUKET' },
                { id: 30069, name: 'AKISIM MOLO' },
                { id: 30066, name: 'KARWOK' },
                { id: 30067, name: 'MAIRO MBILI' },
                { id: 30068, name: 'MOLO  I' },
                { id: 30070, name: 'MORU A' },
                { id: 30071, name: 'MORU B' },
                { id: 30075, name: 'MORU C' },
                { id: 30072, name: 'RARAKA' },
                { id: 30073, name: 'STATION' },
                { id: 30074, name: 'SURUT' },
              ],
            },
            {
              id: 4634,
              name: 'TUBA',
              villages: [
                { id: 30084, name: 'AGOGOMIT' },
                { id: 30085, name: 'AKISIM  TUBA' },
                { id: 30086, name: 'GINNERY' },
                { id: 30087, name: 'KAMARINYANG' },
                { id: 30088, name: 'KIPIRIO NORTH' },
                { id: 30094, name: 'KIPIRIO SOUTH' },
                { id: 30089, name: 'KIPORO' },
                { id: 30090, name: 'MAGA I' },
                { id: 30091, name: 'MAGA II' },
                { id: 30092, name: 'ORAGO' },
                { id: 30093, name: 'TUBA  CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 1007,
          name: 'MUKUJU',
          parishes: [
            {
              id: 4637,
              name: 'AKORET',
              villages: [
                { id: 30103, name: 'AKORET A' },
                { id: 30104, name: 'AKORET B' },
                { id: 57907, name: 'AKWOROT II' },
                { id: 57908, name: 'AKWOROT SOUTH' },
                { id: 66547, name: 'MUKUJU A' },
                { id: 30105, name: 'MUKUJU CENTRAL' },
              ],
            },
            {
              id: 10366,
              name: 'AKWOROT',
              villages: [
                { id: 57905, name: 'AKWOROT C' },
                { id: 57906, name: 'AKWOROT EAST' },
                { id: 57909, name: 'AKWOROT WEST' },
              ],
            },
            {
              id: 4636,
              name: 'AKWOROTO',
              villages: [
                { id: 30100, name: 'AKWOROT A' },
                { id: 30101, name: 'AKWOROT B' },
                { id: 30102, name: 'AKWOROT SOUTH WEST' },
              ],
            },
            {
              id: 4635,
              name: 'ATIRI',
              villages: [
                { id: 30096, name: 'ATIRI A' },
                { id: 30097, name: 'ATIRI B' },
                { id: 30098, name: 'ATIRI C' },
                { id: 30099, name: 'ATIRI D' },
                { id: 58648, name: 'ATIRI EAST' },
                { id: 30095, name: 'ATIRI SOUTH' },
                { id: 58649, name: 'ATIRI WEST' },
              ],
            },
            {
              id: 4638,
              name: 'KAJARAU',
              villages: [
                { id: 30106, name: 'KAJARAU  CENTRAL' },
                { id: 30107, name: 'KAJARAU  EAST' },
                { id: 30108, name: 'KAJARAU  NORHT EAST' },
                { id: 62166, name: 'KAJARAU A' },
                { id: 62167, name: 'KAJARAU B' },
                { id: 62168, name: 'KAJARAU D' },
                { id: 62169, name: 'KAJARAU II' },
                { id: 30109, name: 'KAJARAU NORTH' },
                { id: 30110, name: 'KAJARAU SOUTH' },
                { id: 62170, name: 'KAJARAU WEST' },
              ],
            },
            {
              id: 4639,
              name: 'MUKUJU',
              villages: [
                { id: 30111, name: 'KASAYA SOUTH' },
                { id: 30112, name: 'KASAYA WEST' },
                { id: 30113, name: 'KOI A' },
                { id: 64204, name: 'KOI B' },
                { id: 30114, name: 'KURUKU A' },
                { id: 64404, name: 'KURUKU B' },
                { id: 30115, name: 'MUKUJU A' },
                { id: 66548, name: 'MUKUJU CENTRAL' },
                { id: 30116, name: 'MUKUJU CORE P.T.C' },
                { id: 66549, name: 'MUKUJU D' },
                { id: 30117, name: 'PUTIR' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 162,
      name: 'TORORO SOUTH COUNTY',
      sub_counties: [
        {
          id: 1001,
          name: 'KALAIT',
          parishes: [
            {
              id: 4608,
              name: 'AMONI',
              villages: [
                { id: 29946, name: 'AKISIM' },
                { id: 29943, name: 'AKOU-KETOM' },
                { id: 29944, name: 'ATERAIT' },
                { id: 29945, name: 'KAMENYA' },
                { id: 29947, name: 'OPOPONGO' },
                { id: 29948, name: 'OTEKWA' },
              ],
            },
            {
              id: 4611,
              name: 'ANGOLOLO',
              villages: [
                { id: 29972, name: 'ANGOLOLO A' },
                { id: 29973, name: 'ANGOLOLO B' },
                { id: 29974, name: 'KADANYA' },
                { id: 29975, name: 'KAGULA' },
                { id: 29976, name: 'KAKUYE' },
                { id: 29977, name: 'KATAPALA' },
                { id: 29978, name: 'OMIRIAI' },
              ],
            },
            {
              id: 4609,
              name: 'KALAITI',
              villages: [
                { id: 29954, name: 'ACHILET' },
                { id: 29958, name: 'AGONGET' },
                { id: 29959, name: 'ALECHO' },
                { id: 29949, name: 'ALUPE A' },
                { id: 29950, name: 'ALUPE B' },
                { id: 29953, name: 'ANGOLOL' },
                { id: 29955, name: 'AURIAT' },
                { id: 29960, name: 'KESASAME' },
                { id: 29957, name: 'KOPEE' },
                { id: 29956, name: 'OBILAIP' },
                { id: 29951, name: 'OCHOTO' },
                { id: 29961, name: 'OPOLIA' },
                { id: 29952, name: 'OSERE B' },
              ],
            },
            {
              id: 4612,
              name: 'KODIKE',
              villages: [
                { id: 29981, name: 'APOKOR' },
                { id: 29982, name: 'ASINGE' },
                { id: 29983, name: 'NYAMATUNGA' },
                { id: 29979, name: 'OMAGORO A' },
                { id: 29980, name: 'OMAGORO B' },
              ],
            },
            {
              id: 4610,
              name: 'MORUKEBU',
              villages: [
                { id: 29971, name: 'ATANGI' },
                { id: 29962, name: 'KANGURA A' },
                { id: 29963, name: 'KANGURA B' },
                { id: 29970, name: 'KANGURA CENTRAL' },
                { id: 29969, name: 'KANGURA EAST' },
                { id: 29964, name: 'MORUKEBU A' },
                { id: 29965, name: 'MORUKEBU B' },
                { id: 29967, name: 'MORUKEBU CENTRAL' },
                { id: 29968, name: 'OMEDOI' },
                { id: 29966, name: 'OSERE A' },
              ],
            },
          ],
        },
        {
          id: 997,
          name: 'KAYORO',
          parishes: [
            { id: 9134, name: 'ABUR', villages: [{ id: 70946, name: 'UTRO B' }] },
            {
              id: 4593,
              name: 'ABURI',
              villages: [
                { id: 29836, name: 'ABURI A' },
                { id: 29837, name: 'ABURI B' },
                { id: 29838, name: 'ABURI C' },
                { id: 29840, name: 'ALLELES' },
                { id: 29839, name: 'UTRO A' },
                { id: 29841, name: 'UTRO TRADING CENTRE' },
              ],
            },
            {
              id: 4594,
              name: 'KASIPODO',
              villages: [
                { id: 29842, name: 'AGOLOTO A' },
                { id: 29843, name: 'AGOLOTO B' },
                { id: 29844, name: 'KARUWOKO' },
                { id: 62972, name: 'KASIPODO A' },
                { id: 62973, name: 'KASIPODO B' },
                { id: 62974, name: 'KASIPODO CENTRAL' },
                { id: 66015, name: 'MANAKOR A' },
                { id: 66016, name: 'MANAKOR B' },
              ],
            },
            {
              id: 4595,
              name: 'KAYORO',
              villages: [
                { id: 29850, name: 'AGOLLA' },
                { id: 29845, name: 'ASINGET A' },
                { id: 29846, name: 'ASINGET B' },
                { id: 29851, name: 'ASINGET C' },
                { id: 29847, name: 'KAYORO A' },
                { id: 29848, name: 'KAYORO B' },
                { id: 29849, name: 'KAYORO C' },
              ],
            },
          ],
        },
        {
          id: 996,
          name: 'KWAPA',
          parishes: [
            {
              id: 4591,
              name: 'ASINGE',
              villages: [
                { id: 29816, name: 'AKIRIAMIS' },
                { id: 29817, name: 'AKORET A' },
                { id: 29818, name: 'AKORET B' },
                { id: 29831, name: 'AKORET C' },
                { id: 29819, name: 'APUWAI' },
                { id: 29820, name: 'ASINGE  A' },
                { id: 29821, name: 'ASINGE  B' },
                { id: 58582, name: 'ASINGE III' },
                { id: 29822, name: 'BORDER' },
                { id: 29824, name: 'KOJIM A' },
                { id: 29825, name: 'KOJIM B' },
                { id: 29826, name: 'KOMOLI' },
                { id: 66159, name: 'MAYEMBE' },
                { id: 29827, name: 'OBURI BORDER' },
                { id: 68385, name: 'OBURI GODOWN' },
                { id: 29828, name: 'OGIROI A' },
                { id: 29829, name: 'OGIROI B' },
                { id: 29830, name: 'OGIROI C' },
                { id: 29823, name: 'OGIROI GODOWN' },
              ],
            },
            {
              id: 4590,
              name: 'KWAPA',
              villages: [
                { id: 29798, name: 'ADEREMA' },
                { id: 29811, name: 'AGURU' },
                { id: 29799, name: 'AKADOT I' },
                { id: 57701, name: 'AKADOT II' },
                { id: 29800, name: 'AMAGORO' },
                { id: 29801, name: 'APUWAI' },
                { id: 29802, name: 'ATERAIT I' },
                { id: 29810, name: 'ATERAIT II' },
                { id: 60860, name: 'CHAFU' },
                { id: 29814, name: 'CHEGEN CENTRAL' },
                { id: 29803, name: 'CHEGEN I' },
                { id: 29804, name: 'CHEGEN II' },
                { id: 29815, name: 'CHEGEN III' },
                { id: 29813, name: 'KABOSA GO DOWN' },
                { id: 29805, name: 'KABOSA I' },
                { id: 29806, name: 'KABOSA II' },
                { id: 29807, name: 'KABOSA III' },
                { id: 29809, name: 'KATEKI I' },
                { id: 63061, name: 'KATEKI II' },
                { id: 29808, name: 'KEKWENY' },
                { id: 29812, name: 'KOMACHAR' },
                { id: 64329, name: 'KOTENGEL' },
              ],
            },
            {
              id: 4592,
              name: 'KWAPA TOWN BOARD',
              villages: [
                { id: 29832, name: 'ADAMU' },
                { id: 29833, name: 'KANYAKOR' },
                { id: 29834, name: 'KWAPA CENTRAL' },
                { id: 64438, name: 'KWAPA I' },
                { id: 29835, name: 'KWAPA II' },
                { id: 64439, name: 'KWAPA III' },
              ],
            },
          ],
        },
        {
          id: 1002,
          name: 'MALABA TOWN COUNCIL',
          parishes: [
            {
              id: 4614,
              name: 'AKOLODONG WARD',
              villages: [
                { id: 29989, name: 'AKOLODONGO A' },
                { id: 29990, name: 'AKOLODONGO B' },
                { id: 29991, name: 'AKOLONDONG CENTRAL' },
                { id: 29987, name: 'KATABOI A' },
                { id: 29988, name: 'KATABOI B' },
              ],
            },
            {
              id: 4615,
              name: 'AMAGORO WARD',
              villages: [
                { id: 29992, name: 'AMAGORO A' },
                { id: 29993, name: 'AMAGORO B' },
                { id: 29994, name: 'AMAGORO CENTRAL' },
              ],
            },
            {
              id: 4616,
              name: 'ASINGE WARD',
              villages: [
                { id: 29995, name: 'AMONI "A"' },
                { id: 29996, name: 'AMONI "B"' },
                { id: 29997, name: 'ASINGE A' },
                { id: 29998, name: 'ASINGE B' },
              ],
            },
            {
              id: 4613,
              name: 'MALABA WARD',
              villages: [
                { id: 29984, name: 'MALABA  EAST' },
                { id: 29985, name: 'MALABA  NORTH' },
                { id: 29986, name: 'MALABA  SOUTH' },
              ],
            },
            {
              id: 4617,
              name: 'OBORE WARD',
              villages: [
                { id: 29999, name: 'OBORE  A' },
                { id: 30000, name: 'OBORE B' },
                { id: 30001, name: 'OBORE CENTRAL' },
              ],
            },
          ],
        },
        {
          id: 1000,
          name: 'MELLA',
          parishes: [
            {
              id: 4604,
              name: 'APOKOR',
              villages: [
                { id: 29909, name: 'AMAGORO' },
                { id: 29910, name: 'AUTUTUN' },
                { id: 29921, name: 'CORNER' },
                { id: 29911, name: 'KADAPANY' },
                { id: 29912, name: 'KAPUNGOIT A' },
                { id: 29922, name: 'KAPUNGOIT B' },
                { id: 29913, name: 'KESASAME' },
                { id: 29914, name: 'KOMELAKO' },
                { id: 29915, name: 'KOMOLO' },
                { id: 29916, name: 'NYALAKOT' },
                { id: 29917, name: 'NYAMATUNGA' },
                { id: 29918, name: 'OBURI - APOKOR' },
                { id: 29919, name: 'OTUKURI' },
                { id: 29920, name: 'PEREJE' },
              ],
            },
            {
              id: 4607,
              name: 'KINYII',
              villages: [
                { id: 29938, name: 'KINYIL CENTRAL' },
                { id: 29939, name: 'KINYIL EAST' },
                { id: 29940, name: 'KINYIL NORTH' },
                { id: 29941, name: 'KINYIL SOUTH' },
                { id: 29942, name: 'KINYIL WEST' },
              ],
            },
            {
              id: 4606,
              name: 'KOITANGIRO',
              villages: [
                { id: 29932, name: 'ADUMAI' },
                { id: 29933, name: 'ANGOLOLO NORTH' },
                { id: 29937, name: 'ANGOLOLO SOUTH' },
                { id: 29934, name: 'KOITANGIRO A' },
                { id: 29936, name: 'KOITANGIRO B' },
                { id: 29935, name: 'OKURET' },
              ],
            },
            {
              id: 4605,
              name: 'MELLA',
              villages: [
                { id: 29924, name: 'KADAMOCHE B' },
                { id: 29923, name: 'KADOMOCHE A' },
                { id: 29925, name: 'KATEK' },
                { id: 29926, name: 'KOMOLO' },
                { id: 29927, name: 'MELLA  A' },
                { id: 29928, name: 'MELLA  B' },
                { id: 29929, name: 'MELLA  CENTRAL' },
                { id: 29930, name: 'OLD MELLA A' },
                { id: 29931, name: 'OLD MELLA B' },
              ],
            },
          ],
        },
        {
          id: 998,
          name: 'MORUKATIPE',
          parishes: [
            {
              id: 4597,
              name: 'ANGOLOL',
              villages: [
                { id: 29871, name: 'ALUPE' },
                { id: 29864, name: 'AMONI' },
                { id: 29865, name: 'ASINGE A' },
                { id: 29866, name: 'ASINGE B' },
                { id: 29867, name: 'ASINGE C' },
                { id: 29870, name: 'KODIKE' },
                { id: 29869, name: 'ONYUNYUR' },
                { id: 69206, name: 'ORIYOI A' },
                { id: 29868, name: 'ORIYOI B' },
              ],
            },
            {
              id: 4596,
              name: 'APUTIRI',
              villages: [
                { id: 29852, name: 'ANGOROM  SOUTH' },
                { id: 58290, name: 'ANGOROM  WEST' },
                { id: 29853, name: 'ANGOROM CENTRAL' },
                { id: 29854, name: 'ANGOROM EAST' },
                { id: 29862, name: 'ANGOROM NORTH' },
                { id: 29861, name: 'ANGOROM NORTH WEST' },
                { id: 29863, name: 'ANGOROM SOUTH EAST' },
                { id: 29860, name: 'ANGOROM SOUTH WEST' },
                { id: 29855, name: 'APUTIRI CENTRAL A' },
                { id: 29858, name: 'APUTIRI CENTRAL B' },
                { id: 29856, name: 'APUTIRI EAST A' },
                { id: 29859, name: 'APUTIRI EAST B' },
                { id: 29857, name: 'APUTIRI WEST' },
              ],
            },
            {
              id: 4598,
              name: 'MORUKATIPE',
              villages: [
                { id: 29872, name: 'ATERAIT A' },
                { id: 29873, name: 'ATERAIT B' },
                { id: 58627, name: 'ATERAIT C' },
                { id: 29878, name: 'ATIPE' },
                { id: 29874, name: 'MORUKATIPE CENTRAL' },
                { id: 29875, name: 'MORUKATIPE EAST' },
                { id: 29876, name: 'MORUKATIPE NORTH' },
                { id: 29879, name: 'MORUKATIPE SOUTH' },
                { id: 29877, name: 'MORUKATIPE WEST' },
                { id: 69743, name: 'PRISONS' },
              ],
            },
            {
              id: 4599,
              name: 'NYALAKOT',
              villages: [
                { id: 29887, name: 'ADUMAI' },
                { id: 29880, name: 'AMAGORO' },
                { id: 29881, name: 'APOKOR' },
                { id: 29889, name: 'EUDEYO' },
                { id: 29882, name: 'KACHOMO' },
                { id: 29883, name: 'KALALAN' },
                { id: 29884, name: 'KAPIRI-BELAI' },
                { id: 29888, name: 'MORUKATIPE' },
                { id: 29885, name: 'NYALAKOT' },
                { id: 29886, name: 'ORIYOI CENTRAL' },
                { id: 29890, name: 'RARAKA' },
              ],
            },
          ],
        },
        {
          id: 999,
          name: 'OSUKURU',
          parishes: [
            {
              id: 4600,
              name: 'ABWANGET',
              villages: [
                { id: 29891, name: 'ABWANGET' },
                { id: 57688, name: 'AKABLIT' },
                { id: 58591, name: 'ASURET' },
                { id: 29892, name: 'NGELECHOM' },
              ],
            },
            {
              id: 4601,
              name: 'AMAGORO',
              villages: [
                { id: 58091, name: 'AMAGORO A' },
                { id: 29893, name: 'AMAGORO B' },
                { id: 58092, name: 'AMAGORO C' },
                { id: 29894, name: 'BOKE A' },
                { id: 29895, name: 'BOKE B' },
                { id: 29896, name: 'OSIA LULIKOYO' },
                { id: 69786, name: 'RAMOGI' },
                { id: 29897, name: 'TENGORI' },
              ],
            },
            {
              id: 4603,
              name: 'OSUKURU',
              villages: [
                { id: 29908, name: 'AMAGORO C' },
                { id: 29901, name: 'ANGOROM A' },
                { id: 29902, name: 'ANGOROM B' },
                { id: 29903, name: 'ASINGE A' },
                { id: 29904, name: 'ASINGE B' },
                { id: 29907, name: 'KOYUNE' },
                { id: 29906, name: 'OSUKURU' },
                { id: 29905, name: 'OSUKURU CORNER' },
              ],
            },
            {
              id: 4602,
              name: 'TICAF',
              villages: [
                { id: 69108, name: 'OPEDEDE' },
                { id: 29898, name: 'TCI CAMP' },
                { id: 29899, name: 'TICAF' },
                { id: 29900, name: 'UCI CENTRE' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 160,
      name: 'WEST BUDAMA COUNTY NORTH',
      sub_counties: [
        {
          id: 2015,
          name: 'KATAJULA',
          parishes: [
            {
              id: 9637,
              name: 'KATAJULA',
              villages: [
                { id: 57353, name: 'ACHURURU' },
                { id: 57449, name: 'ADIRIRI' },
                { id: 57726, name: 'AKANDI' },
                { id: 58823, name: 'AYILA' },
                { id: 65880, name: 'MAGANGALA' },
                { id: 70523, name: 'SON OGWANG' },
                { id: 71176, name: 'WOLERA' },
              ],
            },
            {
              id: 9966,
              name: 'MATINDI',
              villages: [
                { id: 66261, name: 'MIKOME' },
                { id: 66512, name: 'MUKAGANGA A' },
                { id: 66513, name: 'MUKAGANGA B' },
                { id: 69719, name: 'POLIECHA A' },
                { id: 69720, name: 'POLIECHA B' },
                { id: 71190, name: 'WUGO' },
              ],
            },
            {
              id: 10002,
              name: 'MUKWANA',
              villages: [
                { id: 64163, name: 'KIZINGA' },
                { id: 66111, name: 'MATAWA' },
                { id: 66221, name: 'MENGO' },
                { id: 66257, name: 'MIKERA' },
                { id: 66567, name: 'MUKWANA-KIJWALA' },
                { id: 66568, name: 'MUKWANA-MORIWA' },
                { id: 69514, name: 'PAKOSI' },
                { id: 69890, name: 'RUDAGO' },
                { id: 70693, name: 'TELE' },
              ],
            },
            {
              id: 10229,
              name: 'PAGOYA',
              villages: [
                { id: 66319, name: 'MITUNGA' },
                { id: 69473, name: 'PAGOYA' },
                { id: 69475, name: 'PAGOYA CENTRAL' },
                { id: 69558, name: 'PAMISUYLWE A' },
                { id: 69559, name: 'PAMISUYLWE B' },
                { id: 70502, name: 'SIWA' },
                { id: 71171, name: 'WIYOLA' },
              ],
            },
          ],
        },
        {
          id: 979,
          name: 'KIREWA',
          parishes: [
            {
              id: 4535,
              name: 'KATANDI',
              villages: [
                { id: 29408, name: 'AKWEDI' },
                { id: 59630, name: 'BUKUSI CENTRAL' },
                { id: 29400, name: 'KATANDI A' },
                { id: 63034, name: 'KATANDI B' },
                { id: 29401, name: 'MAGEMBO A' },
                { id: 65882, name: 'MAGEMBO B' },
                { id: 29402, name: 'MWENGE CENTRAL' },
                { id: 66766, name: 'MWENGE NORTH' },
                { id: 29410, name: 'NYAGULO' },
                { id: 29403, name: 'NYAKASUSA' },
                { id: 29404, name: 'NYAMAYIGA A' },
                { id: 68142, name: 'NYAMAYIGA B' },
                { id: 29405, name: 'SELE NORTH' },
                { id: 70301, name: 'SELE SOUTH' },
                { id: 29406, name: 'TINDO  A' },
                { id: 70757, name: 'TINDO  CENTRAL' },
                { id: 29409, name: 'WIKUS CENTRAL' },
                { id: 29407, name: 'WIKUS RURAL' },
              ],
            },
            {
              id: 4533,
              name: 'KIREWA',
              villages: [
                { id: 29382, name: 'ABARI A' },
                { id: 57135, name: 'ABARI B' },
                { id: 57136, name: 'ABARI CENTRAL' },
                { id: 29383, name: 'AKOL' },
                { id: 57810, name: 'AKOL EAST' },
                { id: 57812, name: 'AKOL WEST' },
                { id: 29384, name: 'BIRANGA A' },
                { id: 59107, name: 'BIRANGA B' },
                { id: 29385, name: 'IYOMYA A' },
                { id: 61722, name: 'IYOMYA CENTRAL' },
                { id: 29386, name: 'KIREWA' },
                { id: 29387, name: 'NAMI' },
                { id: 29388, name: 'NYAFUMBA A' },
                { id: 67957, name: 'NYAFUMBA CENTRAL' },
                { id: 69598, name: 'PANYALIECH B' },
                { id: 29389, name: 'PANYALIECH CENTRAL' },
                { id: 29390, name: 'SIMWENGI A' },
                { id: 70465, name: 'SIMWENGI B' },
              ],
            },
            {
              id: 4534,
              name: 'SENDA',
              villages: [
                { id: 29391, name: 'NYAMBULIE A' },
                { id: 68149, name: 'NYAMBULIE CENTRAL' },
                { id: 29397, name: 'PAGUYUNI' },
                { id: 29392, name: 'PAMANGODE' },
                { id: 29393, name: 'PAMANYAGA' },
                { id: 29394, name: 'PASIKULA' },
                { id: 29398, name: 'PASKULA NORTH' },
                { id: 29395, name: 'SENDA A' },
                { id: 70306, name: 'SENDA B' },
                { id: 29399, name: 'SENDA CENTRAL' },
                { id: 29396, name: 'WANGKWODO' },
              ],
            },
            {
              id: 10319,
              name: 'TINDO',
              villages: [
                { id: 57892, name: 'AKWEDI' },
                { id: 63035, name: 'KATANDI I' },
                { id: 63036, name: 'KATANDI II' },
                { id: 65883, name: 'MAGEMBO CENTRAL' },
                { id: 65884, name: 'MAGEMBO WEST' },
                { id: 70300, name: 'SELE NORTH A' },
                { id: 70302, name: 'SELE SOUTH B' },
                { id: 70758, name: 'TINDO A' },
              ],
            },
          ],
        },
        {
          id: 980,
          name: 'KISOKO',
          parishes: [
            {
              id: 4536,
              name: 'GWARAGWARA',
              villages: [
                { id: 29411, name: 'ABONGIT A' },
                { id: 29412, name: 'ABONGIT B' },
                { id: 29413, name: 'AWAYA' },
                { id: 29414, name: 'CHUKULUK   A' },
                { id: 29415, name: 'CHUKULUK   B' },
                { id: 29416, name: 'GWARAGWARA CENTRAL' },
                { id: 29417, name: 'MAGORO' },
                { id: 29418, name: 'RULOWO' },
                { id: 29419, name: 'RUTENGO' },
              ],
            },
            {
              id: 4537,
              name: 'KISOKO',
              villages: [
                { id: 29420, name: 'BENDO' },
                { id: 29421, name: 'DIDA' },
                { id: 29422, name: 'KISOKO CENTRAL' },
                { id: 29423, name: 'KOI' },
                { id: 29424, name: 'MORWA' },
                { id: 29425, name: 'OLOBAI' },
                { id: 29426, name: 'PAKAMU' },
              ],
            },
            {
              id: 4538,
              name: 'MORIKISWA',
              villages: [
                { id: 29427, name: 'OMWONYOLE' },
                { id: 29428, name: 'OPALPAT' },
                { id: 29429, name: 'PASAYA A' },
                { id: 29435, name: 'PASAYA B' },
                { id: 29430, name: 'PODAKA' },
                { id: 29431, name: 'RUDAM' },
                { id: 29432, name: 'RUKUL' },
                { id: 29433, name: 'RULWA' },
                { id: 29434, name: 'RUNGWING' },
              ],
            },
            {
              id: 4539,
              name: 'PEI-PEI',
              villages: [
                { id: 29436, name: 'KAKOLA A' },
                { id: 29441, name: 'KAKOLA B' },
                { id: 29437, name: 'MAKAUR' },
                { id: 29438, name: 'PEI - PEI A' },
                { id: 29440, name: 'PEIPEI B' },
                { id: 29439, name: 'PILADO' },
              ],
            },
          ],
        },
        {
          id: 981,
          name: 'NAGONGERA',
          parishes: [
            {
              id: 4541,
              name: 'MAUNDO',
              villages: [
                { id: 29457, name: 'BIRANGA' },
                { id: 29454, name: 'MAUNDO  SOUTH' },
                { id: 29456, name: 'MAUNDO CENTRAL' },
                { id: 29460, name: 'MAUNDO CENTRAL' },
                { id: 29461, name: 'MAUNDO EAST' },
                { id: 29455, name: 'MAUNDO NORTH' },
                { id: 29459, name: 'MAUNDO WEST' },
                { id: 29463, name: 'PUBONDO' },
                { id: 29462, name: 'PUBONDO EAST' },
                { id: 29458, name: 'WIDUNYI' },
              ],
            },
            {
              id: 4540,
              name: 'NAMWAYA',
              villages: [
                { id: 29442, name: 'KADEWERE' },
                { id: 29453, name: 'KOYO' },
                { id: 29446, name: 'KWOYO' },
                { id: 29451, name: 'MORIWA' },
                { id: 29443, name: 'NAMWAYA CENTRAL' },
                { id: 29445, name: 'NAMWAYA EAST' },
                { id: 29444, name: 'ODOPONYI' },
                { id: 29447, name: 'OPADA-MWARA' },
                { id: 29448, name: 'PAMBOGO' },
                { id: 29449, name: 'PANYANDERE' },
                { id: 29450, name: 'PANYIRENJA' },
                { id: 29452, name: 'UNIVERSITY' },
              ],
            },
            {
              id: 10173,
              name: 'OKWIRA',
              villages: [
                { id: 59106, name: 'BIRANGA A' },
                { id: 65412, name: 'LOLI' },
                { id: 68214, name: 'NYANGANYA' },
                { id: 68731, name: 'OKUTA' },
                { id: 68732, name: 'OKUTA CENTRAL' },
                { id: 68754, name: 'OKWIRA' },
                { id: 69521, name: 'PALAS' },
                { id: 69722, name: 'POMEDE' },
                { id: 69839, name: 'ROCK MARKET' },
                { id: 69941, name: 'RUKULI' },
              ],
            },
            {
              id: 10252,
              name: 'POKONGO',
              villages: [
                { id: 59032, name: 'BENDO' },
                { id: 62117, name: 'KAGULU' },
                { id: 69703, name: 'POKONGO  AMOR' },
                { id: 69704, name: 'POKONGO  PENYI' },
                { id: 69705, name: 'POKONGO  ROCK' },
                { id: 69706, name: 'POKONGO  WEST' },
                { id: 69707, name: 'POKONGO  WEST A' },
                { id: 69708, name: 'POKONGO KWOYO' },
                { id: 69709, name: 'POKONGO PENYI NORTH' },
                { id: 69710, name: 'POKONGO PLAIN' },
              ],
            },
          ],
        },
        {
          id: 984,
          name: 'NAGONGERA TOWN COUNCIL',
          parishes: [
            {
              id: 4550,
              name: 'CENTRAL WARD',
              villages: [
                { id: 29546, name: 'AWANYA' },
                { id: 29545, name: 'POKWERO' },
              ],
            },
            {
              id: 4551,
              name: 'EASTERN WARD',
              villages: [
                { id: 29547, name: 'MAHANGA' },
                { id: 29548, name: 'TAWO JWOK' },
              ],
            },
            {
              id: 4552,
              name: 'NORTHERN WARD',
              villages: [
                { id: 29549, name: 'CHALUMBA' },
                { id: 29550, name: 'SESERA BENDO' },
                { id: 29551, name: 'SESERA RAMOGI' },
              ],
            },
            {
              id: 4553,
              name: 'SOUTHERN WARD',
              villages: [
                { id: 29553, name: 'BULER' },
                { id: 29554, name: 'KISUBI' },
                { id: 29555, name: 'RUCHWA' },
                { id: 29552, name: 'WERE' },
              ],
            },
          ],
        },
        {
          id: 982,
          name: 'PAYA',
          parishes: [
            {
              id: 4544,
              name: 'BARINYANGA',
              villages: [
                { id: 29494, name: 'ALUKA' },
                { id: 29495, name: 'ATAPARA  A' },
                { id: 29496, name: 'ATAPARA  B' },
                { id: 29497, name: 'BARINYANGA' },
                { id: 29499, name: 'BUDAKA  NORTH' },
                { id: 29498, name: 'BUDAKA  SOUTH' },
                { id: 29500, name: 'KANGORI' },
                { id: 29501, name: 'PAMINYUNYI' },
                { id: 29502, name: 'POWAMIDIA' },
                { id: 29503, name: 'PUPONO' },
                { id: 29504, name: 'SENGO' },
              ],
            },
            {
              id: 4542,
              name: 'NAWIRE',
              villages: [
                { id: 29464, name: 'AGGE' },
                { id: 29466, name: 'JIEP' },
                { id: 29467, name: 'KANDI' },
                { id: 29468, name: 'MAUNDO' },
                { id: 29469, name: 'MIUSI' },
                { id: 29471, name: 'NAWIRE CENTRAL' },
                { id: 29472, name: 'NAWIRE NORTH' },
                { id: 29470, name: 'NAWIRE SOUTH' },
                { id: 29473, name: 'NYASIRENGE  EAST' },
                { id: 29474, name: 'NYASIRENGE  WEST' },
                { id: 29475, name: 'OPALIPATI' },
                { id: 29476, name: 'PASULE  A' },
                { id: 29477, name: 'PASULE  B' },
                { id: 29478, name: 'PASULE  C' },
                { id: 29465, name: 'PAYEDE' },
                { id: 29479, name: 'PODWERA' },
                { id: 29480, name: 'RAMOGI' },
              ],
            },
            {
              id: 4543,
              name: 'PAYA',
              villages: [
                { id: 29481, name: 'BIRANGA' },
                { id: 29482, name: 'KABOSAN' },
                { id: 29483, name: 'NYAKADERE' },
                { id: 29484, name: 'NYAWIMBI' },
                { id: 29485, name: 'PADULA' },
                { id: 29486, name: 'PAMBAYA  EAST' },
                { id: 29487, name: 'PAMBAYA  WEST' },
                { id: 29488, name: 'PAMBEDI' },
                { id: 29489, name: 'PARAGANG' },
                { id: 29490, name: 'PAYA CENTRAL' },
                { id: 29491, name: 'PAYA WEST' },
                { id: 29493, name: 'SIKWALA' },
                { id: 29492, name: 'SUGIDA' },
              ],
            },
            {
              id: 4545,
              name: 'SERE',
              villages: [
                { id: 29505, name: 'KISIA' },
                { id: 29506, name: 'KISOKO' },
                { id: 29507, name: 'LIWIRA' },
                { id: 29508, name: 'MORIWA' },
                { id: 29516, name: 'NYAKIRIGA' },
                { id: 29509, name: 'NYANJATI' },
                { id: 29510, name: 'OLAMA' },
                { id: 29515, name: "P'OPIO" },
                { id: 29511, name: 'PATEWO' },
                { id: 29512, name: 'SERE A' },
                { id: 29513, name: 'SERE B' },
                { id: 29514, name: 'SERE C' },
              ],
            },
          ],
        },
        {
          id: 983,
          name: 'PETTA',
          parishes: [
            {
              id: 4546,
              name: 'MBULA',
              villages: [
                { id: 29517, name: 'KATHOWA NORTH' },
                { id: 29518, name: 'KATHOWA SOUTH' },
                { id: 29519, name: 'KOMOLO' },
                { id: 29520, name: 'MACHAR  EAST' },
                { id: 29521, name: 'MACHAR  WEST' },
                { id: 29522, name: 'MAKEKE NORTH' },
                { id: 29523, name: 'MAKEKE SOUTH' },
                { id: 29524, name: 'MBULA EAST' },
                { id: 29525, name: 'MBULA WEST' },
              ],
            },
            {
              id: 4549,
              name: 'PAKOI',
              villages: [
                { id: 29540, name: 'PAKOI A' },
                { id: 29541, name: 'PAKOI B' },
                { id: 29542, name: 'PAKOI C' },
                { id: 29543, name: 'PARIMA NORTH' },
                { id: 29544, name: 'PARIMA SOUTH' },
              ],
            },
            {
              id: 4547,
              name: 'PETTA',
              villages: [
                { id: 29526, name: 'AYAGO A' },
                { id: 29527, name: 'AYAGO B' },
                { id: 29528, name: 'AYAGO C' },
                { id: 29529, name: 'PETTA CENTRAL NORTH' },
                { id: 29530, name: 'PETTA CENTRAL SOUTH' },
              ],
            },
            {
              id: 4548,
              name: 'RAMOGI',
              villages: [
                { id: 29531, name: 'KANANG A' },
                { id: 29532, name: 'KANANG B' },
                { id: 29533, name: 'KANANG C' },
                { id: 29534, name: 'MAKAUR  EAST' },
                { id: 29535, name: 'MAKAUR  WEST' },
                { id: 29536, name: 'MORIWA NORTH' },
                { id: 29537, name: 'MORIWA SOUTH' },
                { id: 29538, name: 'RAMOGI  EAST' },
                { id: 29539, name: 'RAMOGI  WEST' },
              ],
            },
          ],
        },
        {
          id: 2118,
          name: 'SONI',
          parishes: [
            {
              id: 9419,
              name: 'CHAWOLO',
              villages: [
                { id: 60871, name: 'CHAWOLO' },
                { id: 60875, name: 'CHAWOLO CENTRAL B' },
                { id: 61723, name: 'IYOPOK A' },
                { id: 61726, name: 'IYOPOK B' },
                { id: 64460, name: 'KWOYO A' },
                { id: 64461, name: 'KWOYO B' },
                { id: 66254, name: 'MIJUNGE' },
                { id: 66255, name: 'MIJUNGE SOUTH' },
                { id: 67885, name: 'NYABANJA A' },
                { id: 67886, name: 'NYABANJA CENTRAL' },
                { id: 68041, name: 'NYAKASANA EAST' },
                { id: 68042, name: 'NYAKASANA WEST' },
                { id: 71155, name: 'WINYAKA A' },
                { id: 71156, name: 'WINYAKA B' },
              ],
            },
            {
              id: 9979,
              name: 'MIFUMI',
              villages: [
                { id: 63909, name: 'KISERA A' },
                { id: 63910, name: 'KISERA CENTRAL' },
                { id: 63964, name: 'KISUN' },
                { id: 66245, name: 'MIFUMI' },
                { id: 66246, name: 'MIFUMI NORTH' },
                { id: 67776, name: 'NGULIMO' },
                { id: 68182, name: 'NYAMIYEMBA' },
                { id: 69507, name: 'PAKITAKA' },
                { id: 69508, name: 'PAKITAKA B' },
              ],
            },
            {
              id: 10034,
              name: 'NAGOKE',
              villages: [
                { id: 59671, name: 'BULALO' },
                { id: 64130, name: 'KIWIRI' },
                { id: 66566, name: 'MUKUWA' },
                { id: 66957, name: 'NAGOKE' },
                { id: 66958, name: 'NAGOKE B' },
                { id: 68074, name: 'NYAKATOKE' },
                { id: 68075, name: 'NYAKATOKE EAST' },
                { id: 68076, name: 'NYAKATOKE WEST' },
              ],
            },
            {
              id: 10304,
              name: 'SONI',
              villages: [
                { id: 58607, name: 'ATARO' },
                { id: 61080, name: 'DAGO' },
                { id: 61721, name: 'IYOLWA' },
                { id: 61758, name: 'JIEP' },
                { id: 65214, name: 'LIYONGA' },
                { id: 65215, name: 'LIYONGA CENTRAL' },
                { id: 69235, name: 'ORUWA' },
                { id: 69728, name: 'PORE' },
                { id: 70467, name: 'SINDILA' },
                { id: 70527, name: 'SONI KAINJA A' },
                { id: 70528, name: 'SONI KAINJA B' },
                { id: 70976, name: 'WAGUNGA' },
                { id: 70977, name: 'WAGUNGA B' },
              ],
            },
          ],
        },
        {
          id: 985,
          name: 'SOPSOP',
          parishes: [
            {
              id: 4556,
              name: 'NABOWA',
              villages: [
                { id: 29569, name: 'NABOWA CENTRAL' },
                { id: 29570, name: 'NABOWA NORTH' },
                { id: 29571, name: 'NABOWA SOUTH' },
                { id: 29572, name: 'SINGISI NORTH' },
                { id: 29573, name: 'SINGISI SOUTH' },
              ],
            },
            {
              id: 4557,
              name: 'NAMWENDIA',
              villages: [
                { id: 29574, name: 'BERE  CENTRAL' },
                { id: 29584, name: 'BERE EAST' },
                { id: 29583, name: 'BERE NORTH' },
                { id: 29582, name: 'MULANDA' },
                { id: 29581, name: 'MULANDA CENTRAL' },
                { id: 29575, name: 'NAMWENDIA  EAST' },
                { id: 29576, name: 'NAMWENDIA  WEST' },
                { id: 29577, name: 'NAWEYO CENTRAL' },
                { id: 29578, name: 'NAWEYO EAST' },
                { id: 29579, name: 'NAWEYO WEST' },
                { id: 29580, name: 'NYAMILELE' },
              ],
            },
            {
              id: 4555,
              name: 'PER - PER',
              villages: [
                { id: 29563, name: 'AGUMIT' },
                { id: 29564, name: 'MARUK A' },
                { id: 29566, name: 'PABALA  WEST' },
                { id: 29565, name: 'PABALA EAST' },
                { id: 29567, name: 'PER-PER  A' },
                { id: 29568, name: 'PER-PER  B' },
              ],
            },
            {
              id: 4554,
              name: 'SOP-SOP',
              villages: [
                { id: 29556, name: 'BURIMWENGE' },
                { id: 29557, name: 'KIKADHI NORTH' },
                { id: 29558, name: 'KIKADHI SOUTH' },
                { id: 29559, name: 'MARUK  ROCK' },
                { id: 29560, name: 'MARUK B' },
                { id: 29561, name: 'SOP-SOP NORTH' },
                { id: 29562, name: 'SOP-SOP SOUTH' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 161,
      name: 'WEST BUDAMA COUNTY SOUTH',
      sub_counties: [
        {
          id: 986,
          name: 'IYOLWA',
          parishes: [
            {
              id: 4559,
              name: 'OJILAI',
              villages: [
                { id: 29597, name: 'BUMANDA A' },
                { id: 29598, name: 'BUMANDA B' },
                { id: 29599, name: 'BUMANDA C' },
                { id: 29596, name: 'BUNGANGA A' },
                { id: 29604, name: 'BUNGANGA B' },
                { id: 29600, name: 'FUNGWE' },
                { id: 29601, name: 'NAMAYUNI A' },
                { id: 29605, name: 'NAMAYUNI B' },
                { id: 29602, name: 'OWEERE A' },
                { id: 29607, name: 'OWEERE B' },
                { id: 29603, name: 'PATUMBU A' },
                { id: 29606, name: 'PATUMBU B' },
              ],
            },
            {
              id: 4558,
              name: 'POYEM',
              villages: [
                { id: 29585, name: 'AUYO A' },
                { id: 29586, name: 'AUYO B' },
                { id: 29592, name: 'BENDO' },
                { id: 29593, name: 'KIGURI' },
                { id: 29587, name: 'NYAMILINDE A' },
                { id: 29594, name: 'NYAMILINDE B' },
                { id: 29588, name: 'NYEMERA  A' },
                { id: 29589, name: 'NYEMERA  B' },
                { id: 29595, name: 'OKWENGA' },
                { id: 29590, name: 'POYEM A' },
                { id: 29591, name: 'POYEM B' },
              ],
            },
          ],
        },
        {
          id: 993,
          name: 'IYOLWA TOWN COUNCIL',
          parishes: [
            {
              id: 4580,
              name: 'GULE WARD',
              villages: [
                { id: 29771, name: 'GULE A' },
                { id: 29772, name: 'GULE B' },
                { id: 29773, name: 'GULE C' },
                { id: 61439, name: 'GULE CENTRAL' },
                { id: 65188, name: 'LIGAGA' },
              ],
            },
            {
              id: 4578,
              name: 'IYOLWA WARD',
              villages: [
                { id: 29764, name: 'IYOLWA CENTRAL' },
                { id: 29760, name: 'NAMBOGO  C' },
                { id: 29761, name: 'POTI A' },
                { id: 29762, name: 'POTI B' },
                { id: 29763, name: 'POTI C' },
              ],
            },
            {
              id: 4581,
              name: 'NAMBOGO WARD',
              villages: [
                { id: 29774, name: 'NAMBOGO  A' },
                { id: 29778, name: 'NAMBOGO CENTRAL' },
                { id: 29775, name: 'NGETTA A' },
                { id: 29776, name: 'NGETTA B' },
                { id: 29777, name: 'NGETTA C' },
                { id: 29779, name: 'PURONI' },
              ],
            },
            {
              id: 4579,
              name: 'PABONE WARD',
              villages: [
                { id: 29765, name: 'AKIPENET  A' },
                { id: 29766, name: 'AKIPENET  B' },
                { id: 29767, name: 'PABONE A' },
                { id: 29768, name: 'PABONE B' },
                { id: 29769, name: 'PABONE C' },
                { id: 69438, name: 'PABONE CENTRAL' },
                { id: 29770, name: 'PABONE D' },
              ],
            },
          ],
        },
        {
          id: 990,
          name: 'MAGOLA',
          parishes: [
            {
              id: 4567,
              name: 'GULE',
              villages: [
                { id: 29675, name: 'NAMBOGO  B' },
                { id: 29676, name: 'NAMBOGO  D' },
                { id: 29677, name: 'PABAS  A' },
                { id: 29678, name: 'PABAS  B' },
                { id: 29679, name: 'PAJANGANGO A' },
                { id: 29684, name: 'PAJANGANGO B' },
                { id: 29680, name: 'PAPADA A' },
                { id: 29685, name: 'PAPADA B' },
                { id: 29681, name: 'POMIELA A' },
                { id: 29686, name: 'POMIELA B' },
                { id: 29682, name: 'POSUNA A' },
                { id: 29687, name: 'POSUNA B' },
                { id: 29683, name: 'SEGERE A' },
                { id: 29688, name: 'SEGERE B' },
              ],
            },
            {
              id: 4566,
              name: 'MAGOLA',
              villages: [
                { id: 29664, name: 'MAGOLA A' },
                { id: 29665, name: 'MAGOLA B' },
                { id: 29666, name: 'PAJABO A' },
                { id: 29667, name: 'PAJABO B' },
                { id: 29669, name: 'PALOTO  A' },
                { id: 29670, name: 'PALOTO  B' },
                { id: 29671, name: 'PIMORI' },
                { id: 29672, name: 'POKATCH' },
                { id: 29674, name: 'PONIARA' },
                { id: 29673, name: 'POPANYI A' },
                { id: 29668, name: 'POPANYI B' },
              ],
            },
            {
              id: 4569,
              name: 'PAPOL',
              villages: [
                { id: 29695, name: 'MAGORO A' },
                { id: 29702, name: 'MAGORO B' },
                { id: 29696, name: 'MALAWA  A' },
                { id: 29697, name: 'MALAWA  B' },
                { id: 29698, name: 'OSIA' },
                { id: 29699, name: 'PAKAMALUNGI A' },
                { id: 29703, name: 'PAKAMALUNGI B' },
                { id: 29700, name: 'PAPOL A' },
                { id: 29704, name: 'PAPOL B' },
                { id: 29701, name: 'PAWAGWEWI A' },
                { id: 29705, name: 'PAWAGWEWI B' },
              ],
            },
            {
              id: 4568,
              name: 'POYAMERI',
              villages: [
                { id: 29689, name: 'ASINGE' },
                { id: 29690, name: 'PODUT  A' },
                { id: 29691, name: 'PODUT  B' },
                { id: 29694, name: 'RWANDA' },
                { id: 29692, name: 'YOBOKE  A' },
                { id: 29693, name: 'YOBOKE  B' },
              ],
            },
          ],
        },
        {
          id: 987,
          name: 'MULANDA',
          parishes: [
            {
              id: 9418,
              name: 'CHAWOLO',
              villages: [
                { id: 60872, name: 'CHAWOLO A' },
                { id: 60873, name: 'CHAWOLO B' },
                { id: 60874, name: 'CHAWOLO CENTRAL  A' },
                { id: 60876, name: 'CHAWOLO EAST' },
                { id: 70479, name: 'SIRONGO A' },
                { id: 70480, name: 'SIRONGO B' },
                { id: 70481, name: 'SIRONGO CENTRAL' },
                { id: 70482, name: 'SIRONGO EAST' },
              ],
            },
            {
              id: 9798,
              name: 'KOROBUDI',
              villages: [
                { id: 63062, name: 'KATENDA' },
                { id: 64315, name: 'KOROBUDI A' },
                { id: 64316, name: 'KOROBUDI B' },
                { id: 64317, name: 'KOROBUDI CENTRAL' },
                { id: 64318, name: 'KOROBUDI NORTH' },
                { id: 68158, name: 'NYAMILIRO A' },
                { id: 68159, name: 'NYAMILIRO B' },
                { id: 71152, name: 'WIMBAGA' },
                { id: 71153, name: 'WIMBAGA B' },
              ],
            },
            {
              id: 4560,
              name: 'MULANDA',
              villages: [
                { id: 29619, name: 'ATANGALA  B' },
                { id: 29608, name: 'ATANGALA A' },
                { id: 58792, name: 'AYAGO' },
                { id: 29610, name: 'LOKOMWA' },
                { id: 29614, name: 'LOKOMWA B' },
                { id: 29609, name: 'MULANDA CENTRAL' },
                { id: 29611, name: 'MULANDA STORE' },
                { id: 29613, name: 'MULANDA STORE B' },
                { id: 29620, name: 'NYASIGALA' },
                { id: 29612, name: 'PAITA' },
                { id: 29617, name: 'PAITA B' },
                { id: 29618, name: 'PASIA' },
                { id: 29615, name: 'POCHOWA' },
                { id: 29616, name: 'POCHOWA NORTH' },
              ],
            },
            {
              id: 10248,
              name: 'PASINDI',
              villages: [
                { id: 65413, name: 'LOLI' },
                { id: 69597, name: 'PANYAKENO' },
                { id: 69624, name: 'PASINDI AMOR' },
                { id: 69625, name: 'PASINDI AMOR CENTRAL' },
                { id: 69626, name: 'PASINDI AMOR WEST' },
                { id: 69627, name: 'PASINDI CENTRAL' },
                { id: 69628, name: 'PASINDI ORUWA' },
                { id: 69629, name: 'PASINDI ORUWA WEST' },
                { id: 69697, name: 'POBWOKI' },
                { id: 69698, name: 'POBWOKI SOUTH' },
                { id: 69738, name: 'POTEDO' },
                { id: 69739, name: 'POTEDO NORTH' },
                { id: 69785, name: 'RAMOGI' },
                { id: 71149, name: 'WILEGO' },
              ],
            },
          ],
        },
        {
          id: 2074,
          name: 'MWELLO',
          parishes: [
            {
              id: 9156,
              name: 'AGUMIT',
              villages: [
                { id: 57276, name: 'ABWEL EAST' },
                { id: 57277, name: 'ABWEL WEST' },
                { id: 57546, name: 'AGHEE' },
                { id: 57577, name: 'AGUMIT' },
                { id: 60293, name: 'BUSEMBATIA' },
                { id: 61724, name: 'IYOPOK A' },
                { id: 61725, name: 'IYOPOK B' },
                { id: 65910, name: 'MAIRO PAWIRA NORTH' },
                { id: 65911, name: 'MAIRO PAWIRO SOUTH' },
                { id: 69913, name: 'RUGOT' },
                { id: 69955, name: 'RUNGOLI' },
              ],
            },
            {
              id: 9751,
              name: 'KISOTE',
              villages: [
                { id: 62516, name: 'KANDI A' },
                { id: 62517, name: 'KANDI B' },
                { id: 62518, name: 'KANDI CENTRAL' },
                { id: 63440, name: 'KIDIWA' },
                { id: 63441, name: 'KIDIWA EAST' },
                { id: 63954, name: 'KISOTE CENTRAL' },
                { id: 63955, name: 'KISOTE EAST' },
                { id: 63956, name: 'KISOTE NORTH' },
                { id: 63957, name: 'KISOTE WEST' },
              ],
            },
            {
              id: 9982,
              name: 'MIKIYA',
              villages: [
                { id: 58175, name: 'AMOR' },
                { id: 58176, name: 'AMOR A' },
                { id: 58177, name: 'AMOR CENTRAL' },
                { id: 58178, name: 'AMOR EAST' },
                { id: 58179, name: 'AMOR NORTH' },
                { id: 58181, name: 'AMOR WEST' },
                { id: 66258, name: 'MIKIYA' },
                { id: 66259, name: 'MIKIYA B' },
                { id: 69630, name: 'PASULE' },
                { id: 69888, name: 'RUCHWA' },
              ],
            },
            {
              id: 10017,
              name: 'MWELLO',
              villages: [
                { id: 64345, name: 'KOYO' },
                { id: 65093, name: 'LAPA' },
                { id: 66764, name: 'MWELLO A' },
                { id: 69547, name: 'PAMARAKA EAST' },
                { id: 69548, name: 'PAMARAKA NORTH' },
                { id: 69549, name: 'PAMARAKA SOUTH' },
                { id: 69550, name: 'PAMARAKA WEST' },
                { id: 69611, name: 'PARACHAM EAST' },
                { id: 69612, name: 'PARACHAM NORTH' },
                { id: 69613, name: 'PARACHAM SOUTH' },
                { id: 69614, name: 'PARACHAM WEST' },
              ],
            },
          ],
        },
        {
          id: 988,
          name: 'NABUYOGA',
          parishes: [
            {
              id: 4561,
              name: 'NAMWANGA',
              villages: [
                { id: 29621, name: 'BUJWALA A' },
                { id: 29622, name: 'BUJWALA B' },
                { id: 29632, name: 'IYABARI' },
                { id: 29623, name: 'MAGELO' },
                { id: 29624, name: 'MAGOKHA A' },
                { id: 29631, name: 'MAGOKHA B' },
                { id: 29625, name: 'MUNYINYI A' },
                { id: 29633, name: 'MUYINYI B' },
                { id: 29626, name: 'NAMWANGA A' },
                { id: 29627, name: 'NAMWANGA B' },
                { id: 29628, name: 'NGOTA' },
                { id: 29629, name: 'PAWIRA' },
                { id: 29630, name: 'POMBELO' },
              ],
            },
            {
              id: 4562,
              name: 'NYAMALOGO',
              villages: [
                { id: 29643, name: 'GABA' },
                { id: 29634, name: 'LWALA - POBONA  B' },
                { id: 29649, name: 'LWALA - POBONA  C' },
                { id: 29635, name: 'LWALA-POBONA   A' },
                { id: 29636, name: 'MALAWA A' },
                { id: 29645, name: 'MALAWA B' },
                { id: 29648, name: 'MATAWA' },
                { id: 29637, name: 'MIGANA' },
                { id: 29644, name: 'MINEMBE' },
                { id: 29638, name: 'NYAMALOGO' },
                { id: 29646, name: 'NYAMALOGO B' },
                { id: 29639, name: 'NYAMANDA' },
                { id: 29640, name: 'SIWA   B' },
                { id: 29641, name: 'SIWA  A' },
                { id: 29647, name: 'SIWA C' },
                { id: 29642, name: 'WICHAMA' },
              ],
            },
          ],
        },
        {
          id: 991,
          name: 'NABUYOGA TOWN COUNCIL',
          parishes: [
            {
              id: 4571,
              name: 'MIGANJA WARD',
              villages: [
                { id: 29712, name: 'BENDO A' },
                { id: 29717, name: 'BENDO B' },
                { id: 29713, name: 'MIGANJA' },
                { id: 29716, name: 'SENGO' },
                { id: 29714, name: 'SOMBA' },
                { id: 29715, name: 'YOKOLO' },
              ],
            },
            {
              id: 4573,
              name: 'MUWAFU WARD',
              villages: [
                { id: 29723, name: 'KYAGALA  A' },
                { id: 29724, name: 'KYAGALA  B' },
                { id: 29730, name: 'KYAGALA C' },
                { id: 29725, name: 'MAHO A' },
                { id: 29728, name: 'MAHO B' },
                { id: 29726, name: 'OJILAI A' },
                { id: 29729, name: 'OJILAI B' },
                { id: 29727, name: 'SEGERO A' },
                { id: 29731, name: 'SEGERO B' },
              ],
            },
            {
              id: 4570,
              name: 'NABUYOGA WARD',
              villages: [
                { id: 29706, name: 'MAWELE   A' },
                { id: 29707, name: 'MAWELE   B' },
                { id: 29708, name: 'MISASA' },
                { id: 29710, name: 'MISASA B' },
                { id: 29711, name: "PA'KIDAMBA" },
                { id: 29709, name: 'WAKASIK' },
              ],
            },
            {
              id: 4572,
              name: 'PAWANGA WARD',
              villages: [
                { id: 29718, name: 'KIYEYI' },
                { id: 29719, name: 'MAGOLA-WEYI' },
                { id: 29720, name: 'MATULA' },
                { id: 29721, name: 'PAWANGA' },
                { id: 29722, name: 'UMBWA' },
              ],
            },
          ],
        },
        {
          id: 995,
          name: 'NYANGOLE',
          parishes: [
            {
              id: 4588,
              name: 'ACHILET',
              villages: [
                { id: 29794, name: 'ACHILET A' },
                { id: 29795, name: 'ACHILET B' },
                { id: 29796, name: 'ACHILET C' },
                { id: 57336, name: 'ACHILET D' },
                { id: 57337, name: 'ACHILET E' },
              ],
            },
            {
              id: 4589,
              name: 'IYIKANGO',
              villages: [
                { id: 61720, name: 'IYOKANGO' },
                { id: 66263, name: 'MILE 5 TRADING CENTRE' },
                { id: 29797, name: 'NYAKESI E1' },
                { id: 68092, name: 'NYAKESI E2' },
                { id: 68093, name: 'NYAKESI E3' },
              ],
            },
            { id: 9511, name: 'IYOKANGO', villages: [] },
            {
              id: 4587,
              name: 'NYAKESI',
              villages: [
                { id: 29790, name: 'NYAKESI   A' },
                { id: 29791, name: 'NYAKESI   B' },
                { id: 29792, name: 'NYAKESI   C' },
                { id: 68091, name: 'NYAKESI   CENTRAL' },
                { id: 29793, name: 'NYAKESI   D' },
              ],
            },
            {
              id: 4586,
              name: 'NYANGOLE',
              villages: [
                { id: 29786, name: 'MAGURIA A' },
                { id: 29787, name: 'MAGURIA B' },
                { id: 29788, name: 'NYANGOLE A' },
                { id: 29789, name: 'NYANGOLE B' },
              ],
            },
          ],
        },
        {
          id: 994,
          name: 'OSIA',
          parishes: [
            {
              id: 4583,
              name: 'KAGWARA',
              villages: [
                { id: 62122, name: 'KAGWARA' },
                { id: 29783, name: 'KAGWARA A' },
                { id: 62123, name: 'KAGWARA B' },
                { id: 62124, name: 'KAGWARA C' },
                { id: 69426, name: "P'OKWI" },
              ],
            },
            {
              id: 4584,
              name: 'KATEREMA',
              villages: [
                { id: 29784, name: 'KATEREMA A' },
                { id: 63065, name: 'KATEREMA CENTRAL' },
                { id: 69501, name: 'PAKANGEDA' },
                { id: 69696, name: "PO'BELLA" },
              ],
            },
            {
              id: 4582,
              name: 'OSIA',
              villages: [
                { id: 29780, name: 'KATEREMA B' },
                { id: 29781, name: 'MAGORO A' },
                { id: 29782, name: 'MAGORO B' },
                { id: 69425, name: "P'OBWINI" },
              ],
            },
            {
              id: 4585,
              name: 'UMEME',
              villages: [
                { id: 29785, name: 'ABURI' },
                { id: 57267, name: 'ABURI CENTRAL' },
                { id: 63066, name: 'KATEREMA CI' },
                { id: 63067, name: 'KATEREMA CII' },
                { id: 63068, name: 'KATEREMA CIII' },
                { id: 69992, name: 'RUTELE' },
              ],
            },
          ],
        },
        {
          id: 992,
          name: 'PAJWENDA TOWN COUNCIL',
          parishes: [
            {
              id: 4574,
              name: 'AMOR WARD',
              villages: [
                { id: 29734, name: 'AMOR GEE A' },
                { id: 29738, name: 'AMOR GEE B' },
                { id: 29737, name: 'KOI' },
                { id: 29739, name: 'NYILOTHI' },
                { id: 29740, name: 'PANYAKENO' },
                { id: 29733, name: 'POKANGA' },
                { id: 29735, name: 'POLEKO' },
                { id: 29741, name: 'POLENGE' },
                { id: 29732, name: 'POWINO A' },
                { id: 29742, name: 'POWINO B' },
                { id: 29736, name: 'RAMOGI' },
              ],
            },
            {
              id: 4575,
              name: 'BIRA WARD',
              villages: [
                { id: 29746, name: 'BIRA CENTRAL' },
                { id: 29745, name: 'BIRA EAST' },
                { id: 29747, name: 'BIRA NORTH' },
                { id: 29743, name: 'BIRA WEST' },
                { id: 29744, name: 'MAGORO A' },
                { id: 29748, name: 'MAGORO B' },
              ],
            },
            {
              id: 4576,
              name: 'PAJWENDA WARD',
              villages: [
                { id: 29749, name: 'IYORIANG EAST' },
                { id: 29753, name: 'PAJWENDA CENTRAL A' },
                { id: 29754, name: 'PAJWENDA CENTRAL B' },
                { id: 29750, name: 'PAJWENDA EAST' },
                { id: 29752, name: 'PAJWENDA NORTH' },
                { id: 29751, name: 'PAJWENDA WEST' },
              ],
            },
            {
              id: 4577,
              name: 'PANYIRENJA WARD',
              villages: [
                { id: 29759, name: 'IYORIANG  CENTRAL' },
                { id: 29757, name: 'IYORIANG WEST' },
                { id: 29758, name: 'PANYIRENJA A' },
                { id: 29756, name: 'PANYIRENJA B' },
                { id: 29755, name: 'PANYIRENJA EAST' },
                { id: 69600, name: 'PANYIRENJA WEST' },
              ],
            },
          ],
        },
        {
          id: 989,
          name: 'RUBONGI',
          parishes: [
            {
              id: 4563,
              name: 'KIDERA',
              villages: [
                { id: 29654, name: 'AGOLA A' },
                { id: 29650, name: 'AGOLA B' },
                { id: 29651, name: 'KIDERA CENTRAL' },
                { id: 29652, name: 'POJULO' },
                { id: 29653, name: 'POTELA' },
              ],
            },
            {
              id: 4564,
              name: 'PANYANGASI',
              villages: [
                { id: 29655, name: 'KACHINGA' },
                { id: 29656, name: 'PANYANGASI    A' },
                { id: 29657, name: 'PANYANGASI    B' },
                { id: 29658, name: 'PAPEL' },
                { id: 29659, name: 'PULURO' },
              ],
            },
            {
              id: 4565,
              name: 'RUBONGI',
              villages: [
                { id: 29660, name: 'ATURUKUKU' },
                { id: 29663, name: 'BARRACKS' },
                { id: 59031, name: 'BENDO' },
                { id: 69750, name: 'PULURO' },
                { id: 29661, name: 'RUBONGI   A' },
                { id: 29662, name: 'RUBONGI   B' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
