import { District } from '../index';

export default {
  id: 115,
  name: 'ZOMBO',
  counties: [
    {
      id: 271,
      name: 'OKORO COUNTY',
      sub_counties: [
        {
          id: 1785,
          name: 'ABANGA',
          parishes: [
            {
              id: 8447,
              name: 'ASINA',
              villages: [
                { id: 52562, name: 'ACHU' },
                { id: 52563, name: 'AKWERALI' },
                { id: 52566, name: 'ANDHI' },
                { id: 52561, name: 'ANGENJA' },
                { id: 52567, name: 'ANYARA' },
                { id: 52568, name: 'ASINA' },
                { id: 52569, name: 'KAKRA' },
                { id: 52570, name: 'ORENGO' },
                { id: 52564, name: 'OYARO' },
                { id: 52571, name: 'PANYANGO' },
                { id: 52565, name: 'SANGI' },
              ],
            },
            {
              id: 8445,
              name: 'PAKADHA',
              villages: [
                { id: 52539, name: 'ALENGU' },
                { id: 52540, name: 'AWUJU' },
                { id: 52541, name: 'BENDE' },
                { id: 52542, name: 'IMME' },
                { id: 52543, name: 'KARALONY' },
                { id: 52538, name: 'MALARA' },
                { id: 52544, name: 'MUNZI' },
                { id: 52545, name: 'NGMBANG' },
                { id: 52546, name: 'ODARLEMBE' },
                { id: 52547, name: 'ODUK' },
                { id: 52548, name: 'PAKADHA T/CENTRE' },
                { id: 52549, name: 'ULLU' },
              ],
            },
            {
              id: 8446,
              name: 'PAMITU',
              villages: [
                { id: 52550, name: 'ABONGO' },
                { id: 52551, name: 'ALENGUKUMA' },
                { id: 52553, name: 'ALUKA' },
                { id: 52554, name: 'AMWONYO' },
                { id: 52555, name: 'ARINGO' },
                { id: 52552, name: 'OBEKA' },
                { id: 52556, name: 'ODARLEMBE' },
                { id: 52557, name: 'OKEMU' },
                { id: 52558, name: 'ONYONO' },
                { id: 52559, name: 'OPENJO' },
                { id: 52560, name: 'SIMU' },
              ],
            },
            {
              id: 8448,
              name: 'SER',
              villages: [
                { id: 52572, name: 'ABIBAREM' },
                { id: 52573, name: 'ACANA' },
                { id: 52574, name: 'ALICUDU' },
                { id: 52577, name: 'GIRA' },
                { id: 52575, name: 'GOT LANDI' },
                { id: 52579, name: 'JUPALOZA' },
                { id: 52580, name: 'JUPUJURU' },
                { id: 52576, name: 'LEDA' },
                { id: 52581, name: 'MENGO' },
                { id: 52582, name: 'NYOKA' },
                { id: 52578, name: 'OBAYU' },
                { id: 52583, name: 'OPANO' },
                { id: 52584, name: 'PADEA' },
                { id: 52585, name: 'PAMITU' },
                { id: 52586, name: 'PAVUR' },
                { id: 52587, name: 'SERR' },
              ],
            },
            {
              id: 8444,
              name: 'THANGA',
              villages: [
                { id: 52535, name: 'AKA' },
                { id: 52525, name: 'ANYIKU' },
                { id: 52526, name: 'ARUMUKENG' },
                { id: 52527, name: 'AYUDA' },
                { id: 52536, name: 'CULAMUK' },
                { id: 52528, name: 'GIRA' },
                { id: 52529, name: 'GODUROMBO' },
                { id: 52530, name: 'LARI' },
                { id: 52537, name: 'MALARA' },
                { id: 52531, name: 'NYAGAK' },
                { id: 52532, name: 'ONYEBU' },
                { id: 52533, name: 'RODU' },
                { id: 52534, name: 'THANGA' },
              ],
            },
          ],
        },
        {
          id: 1787,
          name: 'ATHUMA',
          parishes: [
            {
              id: 8452,
              name: 'ABAJI',
              villages: [
                { id: 52620, name: 'AGANYI' },
                { id: 52622, name: 'ALUKA' },
                { id: 52625, name: 'ARINGA' },
                { id: 52621, name: 'ARIWA' },
                { id: 52624, name: 'ATHUMA' },
                { id: 52626, name: 'ATURA' },
                { id: 58764, name: 'AWINJIRI' },
                { id: 52623, name: 'JUPALA' },
                { id: 52627, name: 'MAWA' },
                { id: 67958, name: 'NYAGAK' },
                { id: 68596, name: 'OGWAKU' },
                { id: 69723, name: 'PONDIGORO' },
                { id: 52628, name: 'UDUK' },
              ],
            },
            {
              id: 8453,
              name: 'LEDA',
              villages: [
                { id: 52630, name: 'AKOTH' },
                { id: 52633, name: 'ANYONGO' },
                { id: 52632, name: 'BILIMITI' },
                { id: 52634, name: 'KELLE' },
                { id: 52635, name: 'KOLOLO' },
                { id: 52636, name: 'OBOTH' },
                { id: 52637, name: 'OCUNGULIR' },
                { id: 52638, name: 'OCWALO' },
                { id: 52639, name: 'OJIGU' },
                { id: 52629, name: 'OMIO' },
                { id: 52631, name: 'OMURIRE' },
                { id: 52640, name: 'SAMBA' },
                { id: 52641, name: 'SONGEA' },
              ],
            },
            {
              id: 8455,
              name: 'OLYEKO',
              villages: [
                { id: 52653, name: 'ALUDA' },
                { id: 52654, name: 'ANJATH' },
                { id: 52655, name: 'ARIKPA  CENTRAL' },
                { id: 58502, name: 'ARIKPA EAST' },
                { id: 58503, name: 'ARIKPA TRADING CENTRE' },
                { id: 52658, name: 'ATYENDA  CENTRAL' },
                { id: 52659, name: 'ATYENDA  CORNER' },
                { id: 58679, name: 'ATYENDA LOWER' },
                { id: 52660, name: 'AYIBU' },
                { id: 52656, name: 'CULAMUK' },
                { id: 52657, name: 'KATHANGA' },
                { id: 52661, name: 'NGIRA' },
                { id: 52663, name: 'OGONJU' },
                { id: 68959, name: 'OMIO' },
                { id: 52662, name: 'RABU' },
              ],
            },
            { id: 10370, name: 'OLYEKU', villages: [] },
            {
              id: 8454,
              name: 'ZULUME',
              villages: [
                { id: 57110, name: 'ABADHU' },
                { id: 57855, name: 'AKUNUKUMA' },
                { id: 52647, name: 'AKWERALI' },
                { id: 52648, name: 'CYETHDHIANG' },
                { id: 61402, name: 'GOMBIRI LOWER' },
                { id: 52649, name: 'GOMBIRI UPPER' },
                { id: 52650, name: 'LEWE' },
                { id: 52642, name: 'OBAYO' },
                { id: 52644, name: 'OCOL' },
                { id: 52643, name: 'OLALO' },
                { id: 52645, name: 'OPANO' },
                { id: 52651, name: 'PAKIA/PALWO' },
                { id: 52646, name: 'PALWO' },
                { id: 52652, name: 'ZULUME' },
              ],
            },
          ],
        },
        {
          id: 1781,
          name: 'JANGOKORO',
          parishes: [
            {
              id: 8427,
              name: 'AFUDA',
              villages: [
                { id: 52358, name: 'ALALA' },
                { id: 57959, name: 'ALENGO' },
                { id: 52362, name: 'ANGOLIERO' },
                { id: 52363, name: 'ANYADHA  EAST' },
                { id: 52364, name: 'ANYADHA  WEST' },
                { id: 52359, name: 'ARUA' },
                { id: 52360, name: 'ATEGA' },
                { id: 52365, name: 'AWONGO' },
                { id: 52366, name: 'CANA' },
                { id: 52367, name: 'GBALIA' },
                { id: 65154, name: 'LEDA' },
                { id: 66543, name: 'MUKONO' },
                { id: 52368, name: 'NGMBANGMBA' },
                { id: 52369, name: 'NGUTHE' },
                { id: 52370, name: 'OGALO' },
                { id: 52371, name: 'OMOKU' },
                { id: 52372, name: 'PARONYA' },
                { id: 52361, name: 'POGI' },
                { id: 71193, name: 'WUNGU' },
              ],
            },
            {
              id: 8424,
              name: 'CONGAMBE',
              villages: [
                { id: 57372, name: 'ACULA' },
                { id: 52327, name: 'AKOKORO' },
                { id: 52325, name: 'AKWANYU' },
                { id: 52326, name: 'AKWERALI' },
                { id: 52328, name: 'ARAGO' },
                { id: 60846, name: 'CEDA' },
                { id: 52330, name: 'CENTRAL' },
                { id: 52331, name: 'CONGAMBE' },
                { id: 52332, name: 'LUMA' },
                { id: 65996, name: 'MALARA' },
                { id: 52333, name: 'MANZI' },
                { id: 52329, name: 'MUGONIRE' },
                { id: 66760, name: 'MVUDA' },
                { id: 67715, name: 'NGABICWAKA' },
                { id: 52334, name: 'NYAGAK' },
                { id: 52335, name: 'NYAMBIRI' },
                { id: 52336, name: 'UTHORU' },
                { id: 52337, name: 'VIRRA' },
              ],
            },
            {
              id: 9445,
              name: 'DINDO',
              villages: [
                { id: 57246, name: 'ABUJA' },
                { id: 57435, name: 'ADHINGI' },
                { id: 57859, name: 'AKURAMBE' },
                { id: 57898, name: 'AKWIOKUMA' },
                { id: 57957, name: 'ALENGO' },
                { id: 58706, name: 'AWANGKWAR' },
                { id: 58862, name: 'AZIRI' },
                { id: 60842, name: 'CANONGIO' },
                { id: 61491, name: 'GWOKLEBI' },
                { id: 61782, name: 'JUBBA' },
                { id: 63270, name: 'KELLE' },
                { id: 64957, name: 'LAIMO' },
                { id: 65182, name: 'LENJU' },
                { id: 65578, name: 'LUBIYA' },
                { id: 68301, name: 'NZENSE' },
                { id: 68548, name: 'OGENGO' },
                { id: 68888, name: 'OLYEKO' },
                { id: 69398, name: 'OYEKU' },
                { id: 70733, name: 'THATHA' },
                { id: 70920, name: 'ULAR' },
                { id: 70966, name: 'WABEYO' },
              ],
            },
            {
              id: 8425,
              name: 'JUPADINDO',
              villages: [
                { id: 52338, name: 'ACHU' },
                { id: 52339, name: 'AJIGU' },
                { id: 52340, name: 'ALLO' },
                { id: 52341, name: 'AMOGI' },
                { id: 58755, name: 'AWILLI' },
                { id: 52342, name: 'LARI' },
                { id: 52346, name: 'LIMU' },
                { id: 68283, name: 'NYILIA' },
                { id: 52343, name: 'OBEKI' },
                { id: 52347, name: 'OCOL' },
                { id: 52344, name: 'OMVA' },
                { id: 52345, name: 'RIBBE' },
              ],
            },
            {
              id: 8426,
              name: 'PATEK',
              villages: [
                { id: 52348, name: 'AFOYOPAYONDARA EAST' },
                { id: 52351, name: 'AFOYOPAYONDARA WEST' },
                { id: 52349, name: 'AKUNU' },
                { id: 52350, name: 'AMBAKI' },
                { id: 52354, name: 'GOLOSI' },
                { id: 52352, name: 'GUMIA' },
                { id: 52353, name: 'KAWA' },
                { id: 52355, name: 'NJUDA' },
                { id: 52356, name: 'ODUK' },
                { id: 52357, name: 'OKWALO' },
                { id: 70709, name: 'TENGILEI' },
              ],
            },
            {
              id: 8428,
              name: 'YADA',
              villages: [
                { id: 52373, name: 'ADUWA' },
                { id: 52376, name: 'ALERO' },
                { id: 52379, name: 'AMUDA' },
                { id: 58337, name: 'ANYOLA' },
                { id: 58340, name: 'ANYONGU' },
                { id: 52374, name: 'AYABU' },
                { id: 60323, name: 'BUSIA' },
                { id: 52375, name: 'DEKUMBE' },
                { id: 62611, name: 'KANYONGOMBE' },
                { id: 52381, name: 'LELLO' },
                { id: 52382, name: 'NGMBURINI' },
                { id: 52377, name: 'NYATIGU' },
                { id: 52383, name: 'NZANI' },
                { id: 52384, name: 'OGWARONEN' },
                { id: 52380, name: 'OJEBU' },
                { id: 69240, name: 'ORYANG' },
                { id: 52378, name: 'PAVUR' },
              ],
            },
          ],
        },
        {
          id: 1782,
          name: 'NYAPEA',
          parishes: [
            {
              id: 8429,
              name: 'ABEJU',
              villages: [
                { id: 52385, name: 'AREJU EAST' },
                { id: 52386, name: 'AREJU WEST' },
                { id: 52387, name: 'ATHUMA' },
                { id: 52388, name: 'JUPAKONJA' },
                { id: 52389, name: 'LANYI' },
                { id: 52390, name: 'NGIA' },
                { id: 52391, name: 'PADYERE' },
                { id: 52393, name: 'RINGI  EAST' },
                { id: 52394, name: 'RINGI  WEST' },
                { id: 52392, name: 'ROLA' },
                { id: 52395, name: 'TENGO' },
              ],
            },
            {
              id: 8432,
              name: 'MUNDHEL',
              villages: [
                { id: 52425, name: 'AJJA' },
                { id: 52422, name: 'ANGABA LOWER' },
                { id: 52424, name: 'ANGABA UPPER' },
                { id: 52423, name: 'ATHELE' },
                { id: 52426, name: 'ATHELE NYAGAK' },
                { id: 52430, name: 'GORO' },
                { id: 52429, name: 'OGUTA' },
                { id: 52427, name: 'PATEK EAST' },
                { id: 52428, name: 'PATEK WEST' },
              ],
            },
            {
              id: 8431,
              name: 'OMBILA',
              villages: [
                { id: 52415, name: 'AJEI CENTRAL' },
                { id: 52416, name: 'ALENGO  LARI' },
                { id: 52417, name: 'ALUKA' },
                { id: 52418, name: 'JALUDONGO' },
                { id: 52419, name: 'LARI LUL' },
                { id: 52420, name: 'OVURU KAMBI' },
                { id: 52414, name: 'THATHA' },
                { id: 52421, name: 'YABWENGI' },
              ],
            },
            {
              id: 8433,
              name: 'OSOYE',
              villages: [
                { id: 52431, name: 'AFERE' },
                { id: 52432, name: 'AGWOK' },
                { id: 52433, name: 'AJERE' },
                { id: 52434, name: 'JUPANYADHA' },
                { id: 52435, name: 'KALAGOJU' },
                { id: 52436, name: 'PAPOGA' },
                { id: 52437, name: 'RADA' },
                { id: 52438, name: 'YUGU' },
              ],
            },
            {
              id: 8430,
              name: 'OYEYO',
              villages: [
                { id: 52396, name: 'ACORO' },
                { id: 52397, name: 'AGORE EAST' },
                { id: 52399, name: 'AGORE WEST' },
                { id: 52398, name: 'AGUNYI' },
                { id: 52400, name: 'AJIGU' },
                { id: 52404, name: 'AKWANJI LOWER' },
                { id: 52401, name: 'AKWANJI UPPER' },
                { id: 52402, name: 'ALEGU' },
                { id: 52403, name: 'GOMANDRI' },
                { id: 52405, name: 'GUNA' },
                { id: 52406, name: 'LUL' },
                { id: 52407, name: 'MATHAWELLE' },
                { id: 52408, name: 'MISSION CENTRE' },
                { id: 52409, name: 'NYAPEA  COLLEGE' },
                { id: 52410, name: 'NYARAMBE' },
                { id: 52411, name: 'PELELE' },
                { id: 52412, name: 'ZIWA' },
                { id: 52413, name: 'ZUNGIDA' },
              ],
            },
          ],
        },
        {
          id: 1784,
          name: 'PAIDHA',
          parishes: [
            {
              id: 8443,
              name: 'AMEI',
              villages: [
                { id: 52515, name: 'AGUNYI' },
                { id: 52516, name: 'ALINDI' },
                { id: 52517, name: 'ANDHAMBE' },
                { id: 52519, name: 'AVONO CENTRAL' },
                { id: 52520, name: 'AVONO LOWER' },
                { id: 52521, name: 'AVONO-AGADA' },
                { id: 52522, name: 'KULIGAMBA' },
                { id: 52523, name: 'NJAO' },
                { id: 52524, name: 'NYADIEL' },
                { id: 52518, name: 'ORANGU' },
              ],
            },
            {
              id: 8440,
              name: 'CANA',
              villages: [
                { id: 52484, name: 'AGENGO' },
                { id: 52486, name: 'AMBABANEN' },
                { id: 52487, name: 'AMISSI' },
                { id: 52488, name: 'AYWAYO' },
                { id: 52489, name: 'CHANA NGANO' },
                { id: 52490, name: 'JUPUMWOCO - PAMBO' },
                { id: 52491, name: 'KPELEKPETHE' },
                { id: 52494, name: 'OGURUWI' },
                { id: 52492, name: 'OLYEKO' },
                { id: 52495, name: 'OLYEKO PAMBO' },
                { id: 52485, name: 'ONDWONG' },
                { id: 52493, name: 'ORYEO' },
                { id: 52496, name: 'OWENJE' },
              ],
            },
            {
              id: 8441,
              name: 'KAYA',
              villages: [
                { id: 52497, name: 'AMBAKI' },
                { id: 52505, name: 'ARUMUKENG' },
                { id: 52498, name: 'GUNGURU' },
                { id: 52499, name: 'KELLE' },
                { id: 52500, name: 'LIEN DOLO' },
                { id: 52501, name: 'MALIRI' },
                { id: 52502, name: 'NAMTHIN' },
                { id: 52503, name: 'PAKOLO' },
                { id: 52504, name: 'THATHA' },
              ],
            },
            {
              id: 8442,
              name: 'OTHEKO',
              villages: [
                { id: 52508, name: 'ANYOLA' },
                { id: 52509, name: 'ARISSI' },
                { id: 52506, name: 'AWENDUKEY' },
                { id: 52507, name: 'JUPANEKA' },
                { id: 52512, name: 'JUPANGALI LOWER' },
                { id: 52513, name: 'JUPANGALI UPPER' },
                { id: 52510, name: 'LABORA' },
                { id: 52514, name: 'ORUKU' },
                { id: 52511, name: 'OYORO' },
              ],
            },
          ],
        },
        {
          id: 1783,
          name: 'PAIDHA TOWN COUNCIL',
          parishes: [
            {
              id: 8434,
              name: 'CENTRAL WARD',
              villages: [
                { id: 52439, name: 'ALENGO  KUMA' },
                { id: 52440, name: 'ANYONG' },
                { id: 52441, name: 'AWINJIRI' },
                { id: 52442, name: 'KAWA' },
                { id: 52443, name: 'KOLOLO' },
                { id: 52444, name: 'MVULE' },
                { id: 52445, name: 'SOLIA' },
              ],
            },
            {
              id: 8435,
              name: 'DWONGA WARD',
              villages: [
                { id: 52446, name: 'ABIRA' },
                { id: 52447, name: 'ALUKA' },
                { id: 52448, name: 'ARINGO' },
                { id: 52449, name: 'AWUSANI' },
                { id: 52450, name: 'JUPUJURU' },
                { id: 52451, name: 'KAYA THEYAU' },
                { id: 52452, name: 'MEIRA' },
                { id: 52453, name: 'MVUGU' },
                { id: 52454, name: 'NDARO' },
                { id: 52455, name: 'PAIDHA T.T.C' },
                { id: 52456, name: 'THUNGU' },
              ],
            },
            {
              id: 8438,
              name: 'NYIBOLA WARD',
              villages: [
                { id: 52475, name: 'JUPANDIKA  EAST' },
                { id: 52476, name: 'JUPANYONDO  EAST' },
                { id: 52477, name: 'JUPANYONDO  WEST' },
                { id: 52478, name: 'UVURUYINDI' },
              ],
            },
            {
              id: 8436,
              name: 'OMUA  WARD',
              villages: [
                { id: 52457, name: 'ABONGO' },
                { id: 52458, name: 'CORAMARA' },
                { id: 52459, name: 'ENTEBBE' },
                { id: 52460, name: 'MACWERE' },
                { id: 52461, name: 'MAWA' },
                { id: 52462, name: 'OBOTH' },
              ],
            },
            {
              id: 8437,
              name: 'OTURGANG WARD',
              villages: [
                { id: 52463, name: 'ARUTHA' },
                { id: 52464, name: 'AUTHA' },
                { id: 52465, name: 'AWINI' },
                { id: 52466, name: 'BEDKUWEDU' },
                { id: 52467, name: 'GIRA' },
                { id: 52468, name: 'JUPANDIKA  WEST' },
                { id: 52469, name: 'JUPATHOMBU' },
                { id: 52470, name: 'MBRAZU' },
                { id: 52471, name: 'MISSION' },
                { id: 52472, name: 'OWIRO' },
                { id: 52473, name: 'THENDHE' },
                { id: 52474, name: 'WACACUNGA' },
              ],
            },
            {
              id: 8439,
              name: 'ZINGILI WARD',
              villages: [
                { id: 52479, name: 'AKIR' },
                { id: 52480, name: 'ARINDIMA' },
                { id: 52481, name: 'CULAMUK' },
                { id: 52482, name: 'RUKIDI' },
                { id: 52483, name: 'ZINGILI' },
              ],
            },
          ],
        },
        {
          id: 1786,
          name: 'ZOMBO TOWN COUNCIL',
          parishes: [
            {
              id: 8449,
              name: 'ABIRA EAST WARD',
              villages: [
                { id: 52588, name: 'ABIBAREM' },
                { id: 52590, name: 'ATHUMA' },
                { id: 52591, name: 'CANA' },
                { id: 52589, name: 'CUMU' },
                { id: 52592, name: 'GOTLAU' },
                { id: 52593, name: 'GUNGURU' },
                { id: 52594, name: 'ODARUJU' },
                { id: 52595, name: 'OLAMKULE' },
                { id: 52596, name: 'OTHEYOLEMBE' },
                { id: 52597, name: 'OWOPE' },
                { id: 52598, name: 'ZOMBO EAST' },
              ],
            },
            {
              id: 8450,
              name: 'ABIRA WEST WARD',
              villages: [
                { id: 52599, name: 'ABONGO' },
                { id: 52600, name: 'ACAMUKECH' },
                { id: 52601, name: 'ALIZA' },
                { id: 52604, name: 'ATYENDA EAST' },
                { id: 52605, name: 'AWANYA' },
                { id: 52602, name: 'GOT - LAJWAYA' },
                { id: 52606, name: 'KAROMBO' },
                { id: 52607, name: 'MATHURUMBE' },
                { id: 52608, name: 'MAWA' },
                { id: 52609, name: 'OBIMO' },
                { id: 52610, name: 'ODUK' },
                { id: 52611, name: 'PALANYAK' },
                { id: 52603, name: 'ZOMBO WEST' },
              ],
            },
            {
              id: 8451,
              name: 'PALEI WEST WARD',
              villages: [
                { id: 52612, name: 'AGURE' },
                { id: 52614, name: 'AMBASI' },
                { id: 52615, name: 'ANGENJA' },
                { id: 52616, name: 'ANGULE' },
                { id: 52613, name: 'MOLUJEI' },
                { id: 52617, name: 'OKONGO' },
                { id: 52618, name: 'RIKU' },
                { id: 52619, name: 'TANGALA' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 272,
      name: 'ORA COUNTY',
      sub_counties: [
        {
          id: 1791,
          name: 'AKAA',
          parishes: [
            {
              id: 8469,
              name: 'ABANGA',
              villages: [
                { id: 52827, name: 'AGAWA' },
                { id: 52838, name: 'AGULU' },
                { id: 52828, name: 'AKOR' },
                { id: 52829, name: 'ALEJU' },
                { id: 52830, name: 'ANJAT' },
                { id: 52837, name: 'ASADA' },
                { id: 52831, name: 'CULA' },
                { id: 52832, name: 'GWOKNYERI' },
                { id: 52833, name: 'JUPAWANO' },
                { id: 52834, name: 'OCWANYO' },
                { id: 52835, name: 'OLLU' },
                { id: 52836, name: 'TIDO' },
              ],
            },
            {
              id: 8472,
              name: 'AMUDA',
              villages: [
                { id: 52866, name: 'AJIGU' },
                { id: 52867, name: 'AKAA' },
                { id: 52868, name: 'AMBUZA' },
                { id: 52869, name: 'AMWONYO' },
                { id: 52870, name: 'AWOBIA' },
                { id: 52871, name: 'KAMPALA' },
                { id: 52872, name: 'NENKUWENGI' },
                { id: 52875, name: 'ORIU' },
                { id: 52865, name: 'PADYERE' },
                { id: 52873, name: 'PAYIBE' },
                { id: 52874, name: 'SINA' },
              ],
            },
            {
              id: 8470,
              name: 'AYAKA',
              villages: [
                { id: 52840, name: 'AKAA' },
                { id: 52841, name: 'AKUNUKUMA' },
                { id: 52842, name: 'ATHEJU EAST' },
                { id: 52839, name: 'ATHEJU WEST' },
                { id: 52843, name: 'AYAKA  CENTRAL' },
                { id: 52844, name: 'JUPANGAU EAST' },
                { id: 52850, name: 'JUPANGAU WEST' },
                { id: 52845, name: 'MAWA' },
                { id: 52851, name: 'MAWA EAST' },
                { id: 52846, name: 'MBUNYA' },
                { id: 52847, name: 'NYARKA' },
                { id: 52853, name: 'OMIYO' },
                { id: 52848, name: 'OMOYO' },
                { id: 52852, name: 'OMOYO EAST' },
                { id: 52849, name: 'YIMA' },
              ],
            },
            {
              id: 8471,
              name: 'JUPAMATHO',
              villages: [
                { id: 52854, name: 'ACORO' },
                { id: 52861, name: 'AJUSI' },
                { id: 52856, name: 'AKWERALI' },
                { id: 52857, name: 'ALEGU' },
                { id: 52860, name: 'ARWINYU' },
                { id: 52855, name: 'COPE CENTRE' },
                { id: 52862, name: 'GOLAJU' },
                { id: 52858, name: 'MAWA' },
                { id: 52863, name: 'OLALO' },
                { id: 52859, name: 'OLLU CENTRAL' },
                { id: 52864, name: 'OYEYO' },
              ],
            },
          ],
        },
        {
          id: 1789,
          name: 'ALANGI',
          parishes: [
            {
              id: 8463,
              name: 'AMBELE',
              villages: [
                { id: 52758, name: 'AKWERALI' },
                { id: 52760, name: 'APODHURWA' },
                { id: 52761, name: 'AWARANGI' },
                { id: 52762, name: 'BALIA' },
                { id: 52763, name: 'KOROMOJO' },
                { id: 52764, name: 'ODHOKIRE' },
                { id: 52765, name: 'OGOO' },
                { id: 52766, name: 'OLYEKO' },
                { id: 52767, name: 'OZORISE' },
                { id: 52759, name: 'ZONGO' },
              ],
            },
            {
              id: 8460,
              name: 'ANGAR',
              villages: [
                { id: 52716, name: 'ANGASI' },
                { id: 52717, name: 'ANGYERANGO' },
                { id: 52718, name: 'AWANG' },
                { id: 52719, name: 'BONGO - ACEI' },
                { id: 52720, name: 'CULA' },
                { id: 64348, name: 'KPELE' },
                { id: 52721, name: 'LUNGURU' },
                { id: 52722, name: 'LYANGA' },
                { id: 52723, name: 'MOI' },
                { id: 52724, name: 'TANGALA' },
              ],
            },
            {
              id: 8461,
              name: 'GAMBA',
              villages: [
                { id: 52725, name: 'AGBANDRU' },
                { id: 52727, name: 'AMERI' },
                { id: 52728, name: 'AMERI - BIDONG' },
                { id: 52729, name: 'ANDHAKA' },
                { id: 52726, name: 'ANIZA' },
                { id: 52730, name: 'APURANZU' },
                { id: 52732, name: 'AVOGIRA' },
                { id: 52733, name: 'AWUSONZI' },
                { id: 52734, name: 'AZIRI' },
                { id: 52731, name: 'EDURU' },
                { id: 52735, name: 'GODUNYONA' },
                { id: 52736, name: 'JOBE' },
                { id: 52737, name: 'KAMPALA' },
                { id: 52738, name: 'KUMIRA' },
                { id: 52739, name: 'OMOGO' },
              ],
            },
            {
              id: 8464,
              name: 'NDARA',
              villages: [
                { id: 52768, name: 'ABUKOMU' },
                { id: 52770, name: 'AKISI' },
                { id: 52769, name: 'AKURU' },
                { id: 52773, name: 'ANDHIMANDHI' },
                { id: 52774, name: 'ANYOLA - LOWER' },
                { id: 52771, name: 'ARINGA' },
                { id: 52776, name: 'AVOO' },
                { id: 52772, name: 'GOLOSI' },
                { id: 52777, name: 'JUPAKOPU' },
                { id: 52778, name: 'JUPANDUKILA' },
                { id: 52775, name: 'KARUMBA' },
                { id: 52779, name: 'LOGU' },
                { id: 52780, name: 'NDARA' },
                { id: 52781, name: 'NDAVULA' },
                { id: 52782, name: 'URUSI' },
              ],
            },
            {
              id: 8462,
              name: 'PASAI',
              villages: [
                { id: 52740, name: 'ABALASOMA' },
                { id: 52742, name: 'ALANGI' },
                { id: 52743, name: 'ANGASI' },
                { id: 52744, name: 'AVULELO' },
                { id: 52745, name: 'AZINDA' },
                { id: 52741, name: 'BARUNZE' },
                { id: 52752, name: 'KOLLAS' },
                { id: 52746, name: 'KOSOGO' },
                { id: 52747, name: 'KULIMAU' },
                { id: 52748, name: 'MALAGA' },
                { id: 52754, name: 'MOKORI' },
                { id: 52749, name: 'NDIA' },
                { id: 52750, name: 'NDILI' },
                { id: 52755, name: 'NYANDIMA' },
                { id: 52751, name: 'NYARAMBE' },
                { id: 52753, name: 'OLLI' },
                { id: 52756, name: 'SONZI' },
                { id: 52757, name: 'UTHUVU' },
              ],
            },
          ],
        },
        {
          id: 1788,
          name: 'ATYAK',
          parishes: [
            {
              id: 8456,
              name: 'ANGOL',
              villages: [
                { id: 52664, name: 'ABILAMBE' },
                { id: 52665, name: 'ADONGU' },
                { id: 52666, name: 'AGORO' },
                { id: 52667, name: 'AKWANJI' },
                { id: 52668, name: 'ALLA' },
                { id: 52669, name: 'AMURUPII' },
                { id: 52670, name: 'DHURUDHURU' },
                { id: 52672, name: 'OMOYO' },
                { id: 52671, name: 'UGUDU' },
              ],
            },
            {
              id: 8457,
              name: 'ANYOLA',
              villages: [
                { id: 52673, name: 'ABALATEI' },
                { id: 52674, name: 'AJENGIRA' },
                { id: 52675, name: 'ALEJO' },
                { id: 52676, name: 'ALENDE  JAGI' },
                { id: 52677, name: 'ALOKE' },
                { id: 52678, name: 'ANGALARACH' },
                { id: 52679, name: 'ANYOLA  CENTRE' },
                { id: 52680, name: 'APALALA' },
                { id: 52691, name: 'AYANGA' },
                { id: 52681, name: 'KARALONY' },
                { id: 52682, name: 'NAGURU' },
                { id: 52683, name: 'NAKASEKE' },
                { id: 52684, name: 'NGONGO' },
                { id: 52685, name: 'NYANDIMA' },
                { id: 52686, name: 'NYAWIR' },
                { id: 52687, name: 'OJAYO' },
                { id: 52688, name: 'OKIYO' },
                { id: 52692, name: 'OMBACI' },
                { id: 52693, name: 'ORANGO' },
                { id: 52689, name: 'PACEN' },
                { id: 52694, name: 'YILL' },
                { id: 52690, name: 'YOTHU' },
              ],
            },
            {
              id: 8458,
              name: 'OGUSI',
              villages: [
                { id: 52695, name: 'ABEJU CENTRE' },
                { id: 52696, name: 'AJIGU' },
                { id: 52697, name: 'AKWERALI' },
                { id: 52698, name: 'KAWA' },
                { id: 52699, name: 'OSENEMONDO' },
                { id: 52701, name: 'PADWOR-NGIA' },
                { id: 52702, name: 'PADWOR-RUBANGA' },
                { id: 52700, name: 'PADWOR/ORAA' },
                { id: 52703, name: 'PATHENJU' },
                { id: 52704, name: 'UPENJU' },
                { id: 52705, name: 'WINAM' },
                { id: 52706, name: 'YAMU CENTRE' },
              ],
            },
            {
              id: 8459,
              name: 'PAMACH',
              villages: [
                { id: 52707, name: 'AMVURU' },
                { id: 52708, name: 'KATHELKO' },
                { id: 52709, name: 'NAKASEKE' },
                { id: 52710, name: 'NDINGNDING' },
                { id: 52711, name: 'NYAKADHOGI' },
                { id: 52712, name: 'NYAMULIA' },
                { id: 52713, name: 'OLARO' },
                { id: 52714, name: 'OPOBU' },
                { id: 52715, name: 'ORYANG' },
              ],
            },
          ],
        },
        {
          id: 1790,
          name: 'KANGO',
          parishes: [
            {
              id: 8468,
              name: 'ALUBE',
              villages: [
                { id: 52818, name: 'AMBAO' },
                { id: 52817, name: 'ARAKA' },
                { id: 52821, name: 'AVARI' },
                { id: 52819, name: 'LUKU  BIBIA' },
                { id: 52822, name: 'MARINI' },
                { id: 52823, name: 'MBALE' },
                { id: 52824, name: 'MUNDUDE' },
                { id: 52825, name: 'OFAKA' },
                { id: 52826, name: 'OSUKO' },
                { id: 52820, name: 'ZAMBA' },
              ],
            },
            {
              id: 8465,
              name: 'OLIRI',
              villages: [
                { id: 52783, name: 'ACHORO' },
                { id: 52784, name: 'ALIVU' },
                { id: 58324, name: 'ANYAKAKU' },
                { id: 52792, name: 'AWINDIRI' },
                { id: 52785, name: 'AZAU' },
                { id: 52786, name: 'EROKO' },
                { id: 52787, name: 'EZOO' },
                { id: 52793, name: 'MVULI' },
                { id: 52788, name: 'NGALADEI' },
                { id: 67881, name: 'NUNU' },
                { id: 52789, name: 'ODORIA' },
                { id: 52790, name: 'PAKIA' },
                { id: 52791, name: 'VURRA' },
              ],
            },
            {
              id: 8466,
              name: 'OMUA',
              villages: [
                { id: 52794, name: 'ALENGO' },
                { id: 52795, name: 'BILIKOT' },
                { id: 52796, name: 'JUPATHWON' },
                { id: 52797, name: 'PAKWALA  ADIGA' },
                { id: 52799, name: 'PAKWALA  ULIDU' },
                { id: 52800, name: 'PAWO  OMBILA' },
                { id: 52801, name: 'SOKONZI' },
                { id: 52802, name: 'THANGIRINYA' },
                { id: 52803, name: 'THONGU' },
                { id: 52804, name: 'VURRA  UMBILA' },
                { id: 52798, name: 'YIKWA' },
              ],
            },
            {
              id: 8467,
              name: 'PADUBA',
              villages: [
                { id: 52806, name: 'AROKOSI' },
                { id: 52805, name: 'ARU' },
                { id: 52807, name: 'ARUMVA' },
                { id: 52808, name: 'AWUSI' },
                { id: 52810, name: 'JUPAJALANGU' },
                { id: 52811, name: 'KAWULU' },
                { id: 52809, name: 'LUA' },
                { id: 52812, name: 'ONDREKO' },
                { id: 52813, name: 'OSAO' },
                { id: 52814, name: 'OWATHO' },
                { id: 52815, name: 'OYECO' },
                { id: 52816, name: 'THULI' },
              ],
            },
          ],
        },
        {
          id: 1793,
          name: 'WARR',
          parishes: [
            {
              id: 8481,
              name: 'AFFERE',
              villages: [
                { id: 52997, name: 'AWORA  UPPER' },
                { id: 52998, name: 'AWORALUL' },
                { id: 52999, name: 'JUPATHOI  EAST' },
                { id: 53000, name: 'JUPATHOI  WEST' },
                { id: 53002, name: 'OBAYO' },
                { id: 52996, name: 'OLAYO' },
                { id: 53001, name: 'OLOYO AMURA' },
                { id: 53004, name: 'PADERE ANYIKU' },
                { id: 53005, name: 'REJI' },
                { id: 53006, name: 'RUVUKA' },
                { id: 53003, name: 'UDUGU' },
                { id: 52995, name: 'WARR  AFERE' },
                { id: 53007, name: 'WARR  ALUKA' },
              ],
            },
            {
              id: 8478,
              name: 'JULOKA',
              villages: [
                { id: 52956, name: 'ALAKALA' },
                { id: 52957, name: 'ANGENJA' },
                { id: 52958, name: 'JUPAGULUKONGO' },
                { id: 52959, name: 'JUPAJALAURE' },
                { id: 52960, name: 'JUPAKERUNGA' },
                { id: 52961, name: 'JUPAMEU' },
                { id: 52962, name: 'JUPAVOLU' },
                { id: 52963, name: 'JUPUJUKU' },
                { id: 52964, name: 'JUPUKUNGU' },
                { id: 52965, name: 'JUPULOYU' },
                { id: 52966, name: 'KELLE' },
                { id: 52967, name: 'LWALA' },
                { id: 52968, name: 'PARIEMA' },
                { id: 52969, name: 'UMBAVU' },
                { id: 52970, name: 'WARR OFFAKA' },
                { id: 52971, name: 'WARR T/CENTRE' },
              ],
            },
            {
              id: 8483,
              name: 'NGIRA',
              villages: [
                { id: 53016, name: 'AKWERALI' },
                { id: 66326, name: 'MNGBELE' },
                { id: 66358, name: 'MONKWEROCOO' },
                { id: 67741, name: 'NGIRA' },
                { id: 53017, name: 'OLEDERE' },
              ],
            },
            {
              id: 8482,
              name: 'OMUA LOWER',
              villages: [
                { id: 53009, name: 'AFULAO' },
                { id: 53008, name: 'ATYEROKUMA' },
                { id: 53010, name: 'LEULEU' },
                { id: 53011, name: 'PAKWALA  OMOL' },
                { id: 53013, name: 'PAMWODU' },
                { id: 53012, name: 'PAWO   ZAMBA' },
                { id: 53015, name: 'PAWOANYORISI' },
                { id: 53014, name: 'PAWOZAMBA' },
              ],
            },
            {
              id: 8480,
              name: 'PAGEI',
              villages: [
                { id: 52985, name: 'ACER' },
                { id: 52986, name: 'AKWERALI' },
                { id: 52994, name: 'ALLI' },
                { id: 52987, name: 'ANGIA' },
                { id: 52988, name: 'AYUKPA' },
                { id: 52989, name: 'NGAME' },
                { id: 52990, name: 'NYAMUYENGA' },
                { id: 52991, name: 'PANGA' },
                { id: 52992, name: 'SOKUSOKU' },
                { id: 52993, name: 'THONGA' },
              ],
            },
            {
              id: 8479,
              name: 'PAKIA',
              villages: [
                { id: 52972, name: 'ACIRO' },
                { id: 52973, name: 'ACULANDING' },
                { id: 52974, name: 'AGENGO' },
                { id: 52975, name: 'AVOR' },
                { id: 52976, name: 'AYIDA' },
                { id: 52977, name: 'AZI' },
                { id: 52978, name: 'BINDU' },
                { id: 52979, name: 'GOT  LAU' },
                { id: 52980, name: 'JUPUJUKU' },
                { id: 52981, name: 'MINGA' },
                { id: 52982, name: 'NYAMOLA' },
                { id: 52983, name: 'OLOO' },
                { id: 52984, name: 'ORYANG' },
              ],
            },
          ],
        },
        {
          id: 1792,
          name: 'ZEU',
          parishes: [
            {
              id: 8477,
              name: 'KIGEZI',
              villages: [
                { id: 52939, name: 'ACWERA' },
                { id: 52940, name: 'ALENGO' },
                { id: 52941, name: 'ANYAVU' },
                { id: 52942, name: 'APIKU' },
                { id: 52943, name: 'ARWINYI' },
                { id: 52944, name: 'CANANYIRA' },
                { id: 52945, name: 'DEI' },
                { id: 52946, name: 'JUPANGIRA' },
                { id: 52947, name: 'LEWE' },
                { id: 52948, name: 'LEY' },
                { id: 52949, name: 'MATHANJU' },
                { id: 52950, name: 'NDRINYI' },
                { id: 52951, name: 'OCWALO' },
                { id: 52938, name: 'OCWANYO' },
                { id: 52953, name: 'PAJUR' },
                { id: 52952, name: 'PAKWACH' },
                { id: 52954, name: 'PANGANG' },
                { id: 52955, name: 'SIRI' },
              ],
            },
            {
              id: 8473,
              name: 'LENDU',
              villages: [
                { id: 52877, name: 'AFWODHA' },
                { id: 52876, name: 'ANDHOSI' },
                { id: 52879, name: 'FOREST STATION' },
                { id: 52880, name: 'GBURU' },
                { id: 52890, name: 'KEME' },
                { id: 52881, name: 'LEWE  WEST' },
                { id: 52882, name: 'LEWE EAST' },
                { id: 52883, name: 'MURUKU  LOWER' },
                { id: 52884, name: 'MURUKU  UPPER' },
                { id: 52891, name: 'NGERENGERE' },
                { id: 52885, name: 'NYATEBE' },
                { id: 52886, name: 'OJIEBU' },
                { id: 52878, name: 'OLALO' },
                { id: 52887, name: 'SINDA  EAST' },
                { id: 52888, name: 'SINDA  WEST' },
                { id: 52889, name: 'THERU' },
                { id: 52892, name: 'ZEGUTHE' },
              ],
            },
            {
              id: 8476,
              name: 'LORR CENTRAL',
              villages: [
                { id: 52922, name: 'AFUTHE' },
                { id: 52923, name: 'ALENGO' },
                { id: 52924, name: 'ANYU' },
                { id: 52927, name: 'AYII  GUNA' },
                { id: 52928, name: 'AYII  WEST' },
                { id: 52930, name: 'GIRUBATHE' },
                { id: 52931, name: 'GURUPIMA' },
                { id: 52925, name: 'KELE' },
                { id: 52932, name: 'LORR  ORAA' },
                { id: 52934, name: 'NGARU' },
                { id: 52935, name: 'NYAPEA' },
                { id: 52926, name: 'OBIA' },
                { id: 52936, name: 'THATHA VILLE' },
                { id: 52929, name: 'WIAMUR' },
                { id: 52937, name: 'ZINA EAST' },
                { id: 52933, name: 'ZINA WEST' },
              ],
            },
            {
              id: 8474,
              name: 'OMOYO',
              villages: [
                { id: 52893, name: 'ANGENJA' },
                { id: 52894, name: 'ANGURU' },
                { id: 52895, name: 'AREJU' },
                { id: 52896, name: 'AWIA MUNGU' },
                { id: 52897, name: 'AYUMBI' },
                { id: 52898, name: 'MENZE' },
                { id: 52899, name: 'NGUME' },
                { id: 52900, name: 'OGONJU' },
                { id: 52901, name: 'OMBAKALI' },
                { id: 52902, name: 'SONGOLI' },
                { id: 52903, name: 'THURUMBI' },
              ],
            },
            {
              id: 8475,
              name: 'PAPOGA',
              villages: [
                { id: 52905, name: 'AMOR' },
                { id: 52906, name: 'AMUNZE' },
                { id: 52907, name: 'ARAA HILL' },
                { id: 58571, name: 'ASADA' },
                { id: 52908, name: 'ATONG' },
                { id: 52909, name: 'ENTEBBE' },
                { id: 52910, name: 'GIRA' },
                { id: 52911, name: 'KATERA' },
                { id: 52912, name: 'MOLEM' },
                { id: 52913, name: 'OLALU' },
                { id: 52904, name: 'OLYEKO - AMBE' },
                { id: 52914, name: 'ONYEBU' },
                { id: 52919, name: 'OYARU  LOWER' },
                { id: 52920, name: 'OYARU  UPPER' },
                { id: 52915, name: 'PADUBA' },
                { id: 52916, name: 'PADYERE' },
                { id: 52917, name: 'PANYANGO' },
                { id: 52918, name: 'TENGO' },
                { id: 52921, name: 'ZALE  CENTRE' },
              ],
            },
          ],
        },
      ],
    },
  ],
} as District;
